### ISSUE TITLE
Empty arguments not passed correctly

### ISSUE THREAD

**Issue by Rybak5611** [PowerShell/PowerShell#4661]
Steps to reproduce
------------------
If you run any program with parameter ``""`` program won't receive it as it does in CMD.

Example using simple python script:

```py 
#test.py
import sys
print( sys.argv )
```

```powershell
PS C:\Users\admin\Desktop> py27 test.py test ""
['test.py', 'test']
PS C:\Users\admin\Desktop>cmd
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\admin\Desktop>py27 test.py test ""
['test.py', 'test', '']
```

Expected behavior
-----------------
PS should pass ``""`` as it is.

Actual behavior
---------------
PS completely removes parameter without ever passing it to the program.

Environment data
----------------
```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.5
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by BrucePay** [comment]
This bug is related to #1995. In this case, quotes aren't being preserved for zero-length string arguments. The fix for #1995 should also include this case.
