### ISSUE TITLE
WindowsInstaller.Tests.ps1 failed on debian

### ISSUE THREAD

**Issue by JamesWTruher** [PowerShell/PowerShell#4663]
I couldn't replicate the failure when run in isolation

Description: Should have download link about Universal C runtime that is reachable
Name:        Windows Installer.Visual Studio C++ Redistributables Link.Should have download link about Universal C runtime that is reachable
message:
Error 404 - Not FoundWarning: This site requires the use of scripts, which your browser does not currently allow.See how to enable scripts
        
-->
stack-trace:
at line: 22 in /TEST/PowerShell/test/powershell/Installer/WindowsInstaller.Tests.ps1
1 tests in test/powershell failed
At /TEST/PowerShell/build.psm1:994 char:9
+         throw "$($x.'test-results'.failures) tests in $TestArea faile ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (1 tests in test/powershell failed:String) [], RuntimeException
    + FullyQualifiedErrorId : 1 tests in test/powershell failed
```
Name                           Value                                                                                                       
----                           -----                                                                                                       
PSVersion                      6.0.0-beta                                                                                                  
PSEdition                      Core                                                                                                        
GitCommitId                    v6.0.0-beta.5-81-gcfe173ac0e90d1bc189c469464fd589f3f16ac3b                                                  
OS                             Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07)                                            
Platform                       Unix                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                     
PSRemotingProtocolVersion      2.3                                                                                                         
SerializationVersion           1.1.0.1                                                                                                     
WSManStackVersion              3.0     
```

**Comment by iSazonov** [comment]
Related Issue #4665 and PR #4602 
/cc @mirichmo @bergmeister

**Comment by bergmeister** [comment]
This test does not make sense to run on non-Windows systems but should still not fail on non-
Windows systems(because it does not call any Windows specific API) which indicates that there is a different bug in PowerShell itself. The test simply checks that the content of an Xml file contains a certain download link and that this link is not dead.

**Comment by iSazonov** [comment]
I don't see skipping. Should we test run only on Windows?
