### ISSUE TITLE
Get-Credential does not work for smart cards with multiple certificates.

### ISSUE THREAD

**Issue by jwilczek** [PowerShell/PowerShell#4670]
The Get-Credential cmdlet only shows the first certificate listed on the smart card in the dialog. This makes it impossible to use cards with multiple certificates.

**Comment by milesgratz** [comment]
Well, I'm a bit sad I didn't bother to test `Get-Credential` before we finalized our new PKI setup that has our root domain and child domain on a single smart card. We use PowerShell religiously and this is going to be a huge problem. Is anyone aware of a workaround? I am exploring the .NET class [System.Security.Cryptography.X509Certificates](https://msdn.microsoft.com/en-us/library/system.security.cryptography.x509certificates(v=vs.110).aspx) but haven't found any examples I can steal online. 

I found this - but haven't figured out how to convert it into [PSCredential](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.pscredential?view=powershellsdk-1.1.0) class. 
```
Add-Type -AssemblyName System.Security
$ValidCerts = [System.Security.Cryptography.X509Certificates.X509Certificate2[]](dir Cert:\CurrentUser\My)
$Cert = [System.Security.Cryptography.X509Certificates.X509Certificate2UI]::SelectfromCollection($ValidCerts,'Choose a certificate','Choose a certificate',0
```

**Comment by MarcusLerch** [comment]
Hitting the same bug in customer environment. Any updates on a solution or workaround would be highly appreciated

**Comment by jwilczek** [comment]
I have a solution, but it's not pretty. I punted on doing this solely in PS and opted for c# (although my c# mostly calls PS -- meaning that although I do this in c# it could be done in PS). 

Basically, the process is to import CredUIPromptForWindowsCredentials and CredUnPackAuthenticationBuffer from credui.dll. CredUIPromptForWindowsCredentials  will prompt for the smart card and  you can pick the cert, then you can use CredUnPackAuthenticationBuffer to pull out username, password, etc. With this info, you can create a NetworkCredential object which can be used to create a PSCredential object, which can be used as any other PSCredential object.

**Comment by jscudder** [comment]
jwilczek, I am working on the code solution you discussed. I made a DLL with C# using the native functions you mentioned. Unfortunately, I can get the smart card pin prompt to show, but not the prompt to select one of the certificates. Would you be willing to post your code, specifically the lines that allow the user to select one of the certificates? Regardless, thank you for the solid tip.

**Comment by jimmy58663** [comment]
Hello, I came across this working on grabbing a credential from a smart card and it doesn't look like it has been completely fixed yet. Below is the code that I am using to accomplish grabbing any certificate that is on a smart card and creating a PSCredential object out of it. If you have any questions about it let me know.

    Function Get-SmartCardCred{
    <#
    .SYNOPSIS
    Get certificate credentials from the user's certificate store.

    .DESCRIPTION
    Returns a PSCredential object of the user's selected certificate.

    .EXAMPLE
    Get-SmartCardCred
    UserName                                           Password
    --------                                           --------
    @@BVkEYkWiqJgd2d9xz3-5BiHs1cAN System.Security.SecureString

    .EXAMPLE
    $Cred = Get-SmartCardCred

    .OUTPUTS
    [System.Management.Automation.PSCredential]

    .NOTES
    Author: Joshua Chase
    Last Modified: 01 August 2018
    C# code used from https://github.com/bongiovimatthew-microsoft/pscredentialWithCert
    #>
    [cmdletbinding()]
    param()

        $SmartCardCode = @"
    // Copyright (c) Microsoft Corporation. All rights reserved.
    // Licensed under the MIT License.

    using System;
    using System.Management.Automation;
    using System.Runtime.InteropServices;
    using System.Security;
    using System.Security.Cryptography.X509Certificates;


    namespace SmartCardLogon{

        static class NativeMethods
        {

            public enum CRED_MARSHAL_TYPE
            {
                CertCredential = 1,
                UsernameTargetCredential
            }

            [StructLayout(LayoutKind.Sequential)]
            internal struct CERT_CREDENTIAL_INFO
            {
                public uint cbSize;
                [MarshalAs(UnmanagedType.ByValArray, SizeConst = 20)]
                public byte[] rgbHashOfCert;
            }

            [DllImport("advapi32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
            public static extern bool CredMarshalCredential(
                CRED_MARSHAL_TYPE CredType,
                IntPtr Credential,
                out IntPtr MarshaledCredential
            );

            [DllImport("advapi32.dll", SetLastError = true)]
            public static extern bool CredFree([In] IntPtr buffer);

        }

        public class Certificate
        {

            public static PSCredential MarshalFlow(string thumbprint, SecureString pin)
            {
                //
                // Set up the data struct
                //
                NativeMethods.CERT_CREDENTIAL_INFO certInfo = new NativeMethods.CERT_CREDENTIAL_INFO();
                certInfo.cbSize = (uint)Marshal.SizeOf(typeof(NativeMethods.CERT_CREDENTIAL_INFO));

                //
                // Locate the certificate in the certificate store 
                //
                X509Certificate2 certCredential = new X509Certificate2();
                X509Store userMyStore = new X509Store(StoreName.My, StoreLocation.CurrentUser);
                userMyStore.Open(OpenFlags.ReadOnly);
                X509Certificate2Collection certsReturned = userMyStore.Certificates.Find(X509FindType.FindByThumbprint, thumbprint, false);
                userMyStore.Close();

                if (certsReturned.Count == 0)
                {
                    throw new Exception("Unable to find the specified certificate.");
                }

                //
                // Marshal the certificate 
                //
                certCredential = certsReturned[0];
                certInfo.rgbHashOfCert = certCredential.GetCertHash();
                int size = Marshal.SizeOf(certInfo);
                IntPtr pCertInfo = Marshal.AllocHGlobal(size);
                Marshal.StructureToPtr(certInfo, pCertInfo, false);
                IntPtr marshaledCredential = IntPtr.Zero;
                bool result = NativeMethods.CredMarshalCredential(NativeMethods.CRED_MARSHAL_TYPE.CertCredential, pCertInfo, out marshaledCredential);

                string certBlobForUsername = null;
                PSCredential psCreds = null;

                if (result)
                {
                    certBlobForUsername = Marshal.PtrToStringUni(marshaledCredential);
                    psCreds = new PSCredential(certBlobForUsername, pin);
                }

                Marshal.FreeHGlobal(pCertInfo);
                if (marshaledCredential != IntPtr.Zero)
                {
                    NativeMethods.CredFree(marshaledCredential);
                }
            
                return psCreds;
            }
        }
    }
    "@

        Add-Type -TypeDefinition $SmartCardCode -Language CSharp
        Add-Type -AssemblyName System.Security

        $ValidCerts = [System.Security.Cryptography.X509Certificates.X509Certificate2[]](Get-ChildItem 'Cert:\CurrentUser\My')
        $Cert = [System.Security.Cryptography.X509Certificates.X509Certificate2UI]::SelectFromCollection($ValidCerts, 'Choose a certificate', 'Choose a certificate', 0)

        $Pin = Read-Host "Enter your PIN: " -AsSecureString

        Write-Output ([SmartCardLogon.Certificate]::MarshalFlow($Cert.Thumbprint, $Pin))
    }

**Comment by Qiangong2** [comment]
@jimmy58663 

I keep getting this error on Powershell 5.1 when I try to run Get-SmartCardCred: https://paste.ubuntu.com/p/PtqKqwbNgR/

Any help would be greatly appreciated

**Comment by TravisEz13** [comment]
@Qiangong2 
> I keep getting this error on Powershell 5.1 
Windows PowerShell issues should be reported at https://windowsserver.uservoice.com/forums/301869-powershell

**Comment by TravisEz13** [comment]
Security Working Group: We use Windows/.NET for this.  Is this still an issue?

**Comment by Qiangong2** [comment]
We ended up using a different product overall. I no longer know if it's an issue or not

**Comment by jimmy58663** [comment]
@TravisEz13 Sorry, not sure how I missed @Qiangong2 commenting last year. I rewrote the function and continue to use it for any smart card needs. I have it located at: https://github.com/jimmy58663/pscredentialWithCert.

To my knowledge, get-credential is still limited to 1 cert per smart card. My function works to alleviate that, but there are some PowerShell cmdlets that still do not like the cred object like Start-Process.

I have a work around for Start-Process, but I believe the underlying issue is a smart card cred starts out with @@ and Start-Process tries to split a username by the @ assuming it is in the format of user@domain.

**Comment by TravisEz13** [comment]
https://github.com/jimmy58663/pscredentialWithCert/blob/master/PowerShell/ReadFromAnySmartcard.ps1
looks most related.
I verified the APIs are documented.
The source is MIT licensed:  https://github.com/jimmy58663/pscredentialWithCert/blob/master/LICENSE
One question to the working group is does this belong in the core cmdlet or in another module.

**Comment by jimmy58663** [comment]
@TravisEz13 that is the correct .ps1 containing the updated function I use. That was written by me and as such is technically releasable in the public domain, the MIT license was brought over with the fork of the original project that included the original function, also written by me.

I would say that the capability should be a built-in part of Get-Credential that it is able to access any certificate on a smart card rather than the existing capability it has to just utilize the first certificate that appears on a smart card. My function utilizes the Windows credential prompt and will also work for username/password.

I am not familiar enough with this codebase or the Get-Credential cmdlet to say if you can just replace its code with the C# from my function, if there are issues the original cmdlet addressed over time, or if it would be a lot of work to incorporate the changes my function provides. I assume there would be a bit of work as I wrote it under the assumption it is working from PowerShell 5.1 on a Windows machine. I assume trying to translate it to .NET Core/*NIX would have issues.

If you have any questions about the function I am more than happy to answer what I can.

**Comment by TravisEz13** [comment]
> I am not familiar enough with this codebase or the Get-Credential cmdlet to say if you can just replace its code with the C# from my function, if there are issues the original cmdlet addressed over time, or if it would be a lot of work to incorporate the changes my function provides. I assume there would be a bit of work as I wrote it under the assumption it is working from PowerShell 5.1 on a Windows machine. I assume trying to translate it to .NET Core/*NIX would have issues.

I don't think this would replace the code, but it certainly is a starting point.  Mainly I was just checking all the checks we have to do when we take external code that does p/Invokes.

**Comment by saeckl** [comment]
@jimmy58663
Is it possible to read only the user of the certificate on the smart card. (Powershell) Without the popup for pin query?

**Comment by jimmy58663** [comment]
@saeckl it is possible, but not really related to the above. In Windows the smart card public certs are loaded into the certificate store. You can get the certificates front the store and check their attributes. I believe the Subject Alternative Name is typically used to map a Username, but I am not sure if that is a requirement.

**Comment by TravisEz13** [comment]
Security working group:  I think integrating the example implementation into get-credential would be good.

**Comment by Sunderbraze** [comment]
> I have a work around for Start-Process, but I believe the underlying issue is a smart card cred starts out with @@ and Start-Process tries to split a username by the @ assuming it is in the format of user@domain.

@jimmy58663 Hi, are you able to elaborate on your workaround for Start-Process? 

Currently if I run **$cred = Get-SmartCardCred** and then **Start-Process powershell -Credential $cred** it throws an error claiming "Username or password is incorrect." That doesn't give us much information, but in event viewer I see a Logon Failure that seems to explain it — if we assume that my **$cred.UserName** is **@@123456789ABCDEF** then the event details would show up as follows:

Account For Which Logon Failed:
    Security ID: NULL SID
    Account Name: @
    Account Domain: 123456789ABCDEF

Start-Process is definitely assuming that @@123456789ABCDEF is user "@" from the domain "123456789ABCDEF" which makes it seem like that crucial cmdlet has no idea what to do with smartcard credentials. Any way around that could be a miracle. Thanks!

**Comment by jimmy58663** [comment]
@Sunderbraze Sure, you can see below an example. It is basically just utilizing the .Net Process class instead of Start-Process cmdlet.

```
$Cred = Get-SmartCardCred
$StartInfo = New-Object System.Diagnostics.ProcessStartInfo
$StartInfo.FileName = 'powershell.exe'
$StartInfo.UseShellExecute = $false
$StartInfo.UserName = $Cred.Username
$StartInfo.Password = $Cred.Password
$StartInfo.Arguments = 'Start-Process powershell'
$StartInfo.WorkingDirectory = $env:windir

$Process = New-Object System.Diagnostics.Process
$Process.StartInfo = $StartInfo
$Process.Start()

$Cred = $null
```

It is a little strange that doing so I manually call PowerShell with .Net classes and provide arguments to launch powershell again with Start-Process, but the .Net call closes immediately afterwards and I did not do any research into that. Since the Start-Process call is called from a shell that has the smart card credentials though, the final spawned PowerShell session is with those credentials. Lastly, iirc you can spawn an elevated shell by changing to `$StartInfo.Arguments = 'Start-Process powershell -Verb runas`.

**Comment by AlbertsMTG** [comment]
Hi all.

@jimmy58663 
Say, do you see a way to change the script, so that for PIN entry, it utilizes the PIN-Pad of my SmartCard reader instead of the computer keyboard?

**Comment by AlbertsMTG** [comment]
Too bad, I hoped you would know. I have searched for a while already to find a script that is able to invoke the PIN-Pad entry to no avail. It seems no one else wants to do that.

**Comment by AlbertsMTG** [comment]
@jimmy58663 
Just found the solution. Your script can be used, after all. When the PIN is asked for, just leave it blank and press enter - this will activate the PIN-Pad!
