### ISSUE TITLE
Can we get a new icon for PowerShell Core to distinguish between it and Windows PowerShell?

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShell#4676]
I'm evaluating PS Core on my Windows 10 machine but I also keep Windows PowerShell on my taskbar for times when something doesn't work in PS Core.  The icons for both programs are the same.  It would be nice if we could get an icon for PS Core that was different in some way so it's easier to tell the taskbar icons apart.

**Comment by SteveL-MSFT** [comment]
Anyone an artist that could contribute one? :)

**Comment by RichardSiddaway** [comment]
Differentiating Windows PowerShell and PowerShell core would be extremely useful

**Comment by MaximoTrinidad** [comment]
Done!! I submitted and made the correction to identify these session are about PowerShell Core.


Thanks for the notice,


Maximo Trinidad
Microsoft MVP - Cloud and Datacenter Management (PowerShell 9rs)
MVP Link: https://mvp.microsoft.com/en-us/PublicProfile/4024451?fullName=Maximo%20%20Trinidad
SAPIEN Technologies MVP 2017: https://www.sapien.com/blog/2016/12/21/sapien-mvp-2017-award-winners/
IDERA ACE member 2017: http://community.idera.com/blog/b/community_blog/posts/meet-your-2017-idera-aces
Blog: http://www.maxtblog.com/



________________________________

**Comment by SteveL-MSFT** [comment]
Since for PSCore6 we've gone back to a black background, how about we just change the existing icon to have a black background?

![new icon](https://github.com/SteveL-MSFT/PowerShell/blob/new-icon/assets/Powershell_64.png?raw=true)

**Comment by markekraus** [comment]
@SteveL-MSFT  I'm torn. I like the blue and would miss it. But.. black does make sense and it looks good.

**Comment by iSazonov** [comment]
In Windows 10 task panel is black.

**Comment by joeyaiello** [comment]
I personally prefer color in my icons because it makes them easier to see at a glance. 

Here's a few more options that we played around with before going live with open-source last year. ![taskbar_samp](https://user-images.githubusercontent.com/1255187/30185338-d57f4dce-93d5-11e7-8156-a73c6474f969.png)

If you like any of them, please reply explaining which ones. :)

**Comment by megamorf** [comment]
@joeyaiello @SteveL-MSFT I've also grown accustomed to the blue icon (which I don't relate to the blue console background of PS). If you go for the black version then at least add a contrasting 1px border around (like vscode) it because otherwise recognizing the outline of the icon becomes difficult on a dark background:

![image](https://user-images.githubusercontent.com/1732128/30196683-d426cd52-9462-11e7-992c-b85727e1cf80.png)

**Comment by iSazonov** [comment]
Compare with cmd.exe icon.

**Comment by SteveL-MSFT** [comment]
Added a white border with my limited skills with [Paint.net](https://www.getpaint.net/index.html)

**Comment by dragonwolf83** [comment]
How about no background like many of the Windows 10 icons. That should blend in with the taskbar better.

It might also be worth looking into a different style for Mac/Linux like VS Code was trying to do.

**Comment by megamorf** [comment]
@SteveL-MSFT I really like the version you did in Paint.Net. 👍 I'd still prefer the blue icon from PSv5 but I could live with the black as alternate colour if it comes with that border :P

**Comment by rkeithhill** [comment]
Yup the black with a white border works for me.  I could care less about the blue as I always change my console color scheme away from the blue background. Been doing that for years.

**Comment by SteveL-MSFT** [comment]
I'll make the change for beta.7, we can always change it again if something better comes along

**Comment by glennsarti** [comment]
👍  💯  @megamorf .  You need a contrasting colour otherwise it "disappears" on similar coloured backgrounds.  Also with a gradient colour (vs a solid) you really need a strong border (IMO) as I find it difficult to see where the icon starts and finishes with respect to its background.

e.g. On the taskbar icons are positioned with a fixed amount of space between.  However with no border the spacing looks "odd" as it appears to be too far too left.  That's because you have a high contrast on the left hand side of the icon (the lighter side of the gradient) which your eyes are drawn to; but on the right hand side, it blends into the background.

**Comment by SteveL-MSFT** [comment]
Didn't get it in time for beta.7, but working on another proposal.

**Comment by SteveL-MSFT** [comment]
What are thoughts on using the PowerShell avatar?

![avatar](https://raw.githubusercontent.com/SteveL-MSFT/PowerShell/new-icon/assets/Avatar_256.png)

**Comment by glennsarti** [comment]
Does it scale down properly?

**Comment by SteveL-MSFT** [comment]
I have the original SVG, so I can scale it to all appropriate sizes

**Comment by glennsarti** [comment]
Sorry, what I mean is, will it look good at 32x32 pixels (or whatever size the taskbar or window icons are) e.g. the hair streaks will probably disappear at that small size.

**Comment by SteveL-MSFT** [comment]
@glennsarti got it, let me resize it and see if it becomes a mess

**Comment by SteveL-MSFT** [comment]
16 ![16](https://raw.githubusercontent.com/SteveL-MSFT/PowerShell/new-icon/assets/Avatar_16.png)
20 ![20](https://raw.githubusercontent.com/SteveL-MSFT/PowerShell/new-icon/assets/Avatar_20.png)
24 ![24](https://raw.githubusercontent.com/SteveL-MSFT/PowerShell/new-icon/assets/Avatar_24.png)
32 ![32](https://raw.githubusercontent.com/SteveL-MSFT/PowerShell/new-icon/assets/Avatar_32.png)
40 ![40](https://raw.githubusercontent.com/SteveL-MSFT/PowerShell/new-icon/assets/Avatar_40.png)
48 ![48](https://raw.githubusercontent.com/SteveL-MSFT/PowerShell/new-icon/assets/Avatar_48.png)
64 ![64](https://raw.githubusercontent.com/SteveL-MSFT/PowerShell/new-icon/assets/Avatar_64.png)

**Comment by glennsarti** [comment]
IMO 32 looks ok, 24 and less are bit, meh

**Comment by markekraus** [comment]
I'm all for using PoSH-chan.

**Comment by SteveL-MSFT** [comment]
@glennsarti I cropped it cutting off the bottom of the hair to make it more square

**Comment by markekraus** [comment]
@SteveL-MSFT That looks much better.

**Comment by SteveL-MSFT** [comment]
Working internally to see if we can get a specific version that is suitable for an icon rather than my efforts.

**Comment by iSazonov** [comment]
Nice silhouette, but one eyebrow, nose curve and mouth from the side.

**Comment by SteveL-MSFT** [comment]
I redid the icon a bit adjusting her hair so that it fits nicely as a square.

**Comment by brwilkinson** [comment]
I hate to go against the crowd, however I just want to express my vote for the (plain) Black PowerShell icon. I really like the way it looks, it would also be great, similar with VS code if Preview builds used a color versions

I don't have anything against Posh-Chan, however I just don't think it works as an icon, just because of the small sizing, I think it loses its value, since you cannot see the PowerShell.

**Comment by mattmcnabb** [comment]
I think it would be great to have the PSCore icon look the same as the Windows PowerShell icon, but more lo-fi (think 8-bit). I'm not against blue or black - either is good.

**Comment by SteveL-MSFT** [comment]
We're having one of our internal artists do a formal version of Posh-chan as well as the black background one (probably not 8-bit tho....).  Don't have ETA when those will be done.  What we'll probably end up doing is having both of them available as icons in powershell.exe, however, there's an open question on which is the default.

**Comment by SteveL-MSFT** [comment]
Ok, so after our resident Msft artist tirelessly worked to produce some new icons, would like some feedback.  Apparently, it's not so easy to embed multiple icons into an exe, so for now I'm only updating the shortcut icon.  What follows are three options, vote with your emoticons.  If the one you like doesn't get selected, you can always download the .ico from our GitHub repo and change it yourself.  (Maybe I'll publish a module on PowerShellGallery to make it easy to change in the future)

**Comment by SteveL-MSFT** [comment]
![blackicon](https://raw.githubusercontent.com/SteveL-MSFT/PowerShell/new-icon/assets/ps_black_128.svg?sanitizenew)

**Comment by SteveL-MSFT** [comment]
![avatar](https://raw.githubusercontent.com/SteveL-MSFT/PowerShell/new-icon/assets/avatar_128.svg?sanitize=true)

**Comment by SteveL-MSFT** [comment]
![avatarcolors](https://raw.githubusercontent.com/SteveL-MSFT/PowerShell/new-icon/assets/av_colors_128.svg?sanitize=true)

**Comment by KirkMunro** [comment]
It probably shouldn't, but it bothers me that the underbar ("_") in these icons does not line up with the bottom of the prompt indicator (">"). Now that you see it, maybe it bothers you too. 😜 

Regardless of which is chosen, if it's either of the more traditional PowerShell icons (black or hero-colored), if the underbar could be moved down a pixel, that would be great.

This might not show up as well as it would in an svg, but here's a png image showing what I mean. The one on the right has the modification, and the one on the left doesn't line up.

![image](https://user-images.githubusercontent.com/3515485/30892727-7baa4d4a-a310-11e7-889d-b450a3d26a71.png)

Much better, right? 😄

**Comment by SteveL-MSFT** [comment]
The original doesn't line up either, I think it's `By Design` :P

![blue](https://raw.github.com/PowerShell/PowerShell/blob/master/assets/Powershell_256.png)

**Comment by KirkMunro** [comment]
@SteveL-MSFT: Is that icon file open source? ;)

**Comment by SteveL-MSFT** [comment]
@KirkMunro I'll have an update on use of the assets "soon".  It's trademarked so not the same as OSS.

**Comment by SteveL-MSFT** [comment]
@KirkMunro you can see the instructions on permission to use the assets here: https://github.com/PowerShell/PowerShell/pull/4938

**Comment by glennsarti** [comment]
For ref - the icon chosen was https://raw.githubusercontent.com/SteveL-MSFT/PowerShell/new-icon/assets/ps_black_128.svg?sanitize=true

**Comment by SteveL-MSFT** [comment]
Fixed your link for you

**Comment by glennsarti** [comment]
Can you edit all my github comments :-P

**Comment by SteveL-MSFT** [comment]
No, but I had to edit your comment again since I deleted my working branch :P

**Comment by lakshit1** [comment]
Please tell me how to change PowerShell icon ?

**Comment by megamorf** [comment]
@lakshit1 PS Core has introduced it's own icon ages ago so there's no manual change required. A side-by-side installation of Windows PS and PS Core is clearly distinguishable.

**Comment by lakshit1** [comment]
# @SteveL-MSFT 
How do you changed the icon of power shell in this https://github.com/PowerShell/PowerShell/issues/4676#issuecomment-332377602

**Comment by vexx32** [comment]
That icon is used for the preview builds of PowerShell; if you install PowerShell 7 Preview from the Releases page here on Github it'll have that icon.
