### ISSUE TITLE
In Linux, Find Command Fails Even With Quoted and Escaped Asterisk

### ISSUE THREAD

**Issue by bigboy-pdb-spam** [PowerShell/PowerShell#4680]
Steps to reproduce
------------------

```powershell
PS> touch ab.txt 'a b.txt'

# Question mark character works

PS> find -name 'a?.txt'
ab.txt

PS> find -name 'a??.txt'
a b.txt

# Asterisk appears to be being expanded into file names

PS> find -name 'a*b.txt'
/usr/bin/find: paths must precede expression: ab.txt
Usage: /usr/bin/find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec|time] [path...] [expression]

# Escaping asterisk doesn't work

PS> find -name 'a`*b.txt'
# No output, which indicates the parameters were accepted, but the search produced no results.
```

Expected behavior
-----------------

```powershell
PS> find -name 'a*b.txt'
./ab.txt
./a b.txt
```

Actual behavior
---------------

```powershell
PS> find -name 'a*b.txt'
/usr/bin/find: paths must precede expression: ab.txt
Usage: /usr/bin/find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec|time] [path...] [expression]
```
It appears that the command is being converted into: find -name 'a b.txt' 'ab.txt'

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.0-beta                                      
PSEdition                      Core                                            
GitCommitId                    v6.0.0-beta.6                                   
OS                             Linux 4.4.0-92-generic #115-Ubuntu SMP Thu Au...
Platform                       Unix                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1                                         
WSManStackVersion              3.0 
```

**Comment by mklement0** [comment]
Yes, globbing currently mistakenly also kicks in when the pattern is _quoted_.
A simpler example:

```powershell
printf '%s\n' '*'  # '*' is expanded despite being quoted; in Bash, a literal '*' would print.
```

This was previously reported in #3931, and a fix is pending: #4489

**Comment by bigboy-pdb-spam** [comment]
According to that issue, the asterisk can be escaped using the backquote character, which appears to work for that case:

```powershell
PS> echo '11:1' | grep '.`*:.'
11:1
```

However, in the examples that were listed for this issue, using the backquote produced no results, but the command should have displayed the two newly created files.

```powershell
PS> touch ab.txt 'a b.txt'
PS> find -name 'a`*b.txt'
# No output, but should output the file names:
# ./ab.txt
# ./a b.txt
```

I'll try this example in the next beta and close this issue if the problem is solved.

**Comment by mklement0** [comment]
`'...'` in PS encloses _literals_, and the newly introduced native globbing feature should treat them as such too. Not doing so is a _bug_.
(As is the interpretation of patterns inside _double-quoted_ PS strings).

In short: **Using `` ` `` inside `'...'` before wildcard metacharacters is not a general workaround, nor should it be.**

Adding a `` ` `` (backtick) before `*` disrupts the newly introduced PS-side globbing, but the `` ` `` character is _passed through_ to the target utility, which is undesired.  
(In PS, backticks only function as escape characters in _unquoted_ or _double-quoted_ strings.)

```powershell
PS> printf '%s\n' '`*'
`*   # ` was retained
```

It explains why your `` find -name 'a`*b.txt' `` workaround attempt didn't work.


The `` ` `` is also passed through in your `grep` example - it just _happens_ to work even with the `` ` `` present, but that is _unrelated to the issue at hand_; you get the same behavior in `bash`:

```powershell
# PS
PS> echo 'a' | grep '.`*'
a

# Bash
$ echo 'a' | grep '.`*'  # !! effectively treated as '.*'
a
```

For reasons I don't understand, placing a `` ` ``  before regex duplication symbols `*` and `?` causes the `` ` `` to be ignored.
