### ISSUE TITLE
PowerShell Core - profile issue

### ISSUE THREAD

**Issue by janegilring** [PowerShell/PowerShell#4685]
Steps to reproduce
------------------

Put the following in the PowerShell profile file ($profile)
```powershell

# Press Ctrl to not load profile
if (($host.Version.Major -gt 2) -and ($PSEdition -ne 'Core')) {

  if ($host.Name -eq "ConsoleHost") {
    Add-Type -AssemblyName PresentationCore
  }
  
  if([System.Windows.Input.Keyboard]::IsKeyDown("Ctrl")) { return }
  
}

```

Expected behavior
-----------------

No error messages

Actual behavior
---------------

Even though the if-statement is evaluated to false, the following error is presented:

The following exception occurred while retrieving member "IsKeyDown": "Could not load type 'System.Windows.Input.ModifierKeys' from assembly 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'."
At C:\Users\jan-e\Documents\PowerShell\Microsoft.PowerShell_profile.ps1:6 char:4
 if([System.Windows.Input.Keyboard]::IsKeyDown("Ctrl")) { return }
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : NotSpecified: (:) [], ExtendedTypeSystemException
     FullyQualifiedErrorId : CatchFromBaseGetMember

On a side note: Are there other techniques for discovering whether a specific key is pressed which also works on PowerShell Core?

Environment data
----------------

<!-- provide the output of $PSVersionTable -->

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.6
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
Again I cannot reproduce this on W10:

If I put the following at the very top of my Core `$PROFILE`:

```powershell
$host.Version.Major
$PSEdition
($host.Version.Major -gt 2) -and ($PSEdition -ne 'Core')
```

I get:

```none
6
Core
False
```

suggesting that the conditional in your original post should never be entered - which indeed doesn't happen for me when I use your code verbatim in the same place.

---

> Are there other techniques for discovering whether a specific key is pressed which also works on PowerShell Core?

The only thing I'm personally aware of is `[console]::KeyAvailable` and `[console]::ReadKey()`, but, unfortunately, that doesn't work with _modifier_ keys in isolation - so a `Ctrl` keypress _by itself_ cannot be detected that way.

**Comment by janegilring** [comment]
I see, thanks for the input regarding key presses.

Here is a better example of the issue I am seeing:
'''powershell
if ($false) {

	if([System.Windows.Input.Keyboard]::IsKeyDown("Ctrl")) { return }

}
'''

Put this in the profile and open PowerShell Core.

**Comment by iSazonov** [comment]
You can try `$host.UI.RawUI.ReadKey()` and analyze `KeyInfo`.

**Comment by mklement0** [comment]
@janegilring: My `$PSVersionTable` shows the same output as yours, and I cannot recreate your problem (I've verified that the profile indeed loads).

**Comment by mklement0** [comment]
@iSazonov: What @janegilring is looking for is to asynchronously check whether a given _modifier key by itself_ happens to be held down.

`[console]::KeyAvailable` / `$host.UI.RawUI.ReadKey()` / `[console]::ReadKey()` only check for 
 / read keypresses that involve at least one non-modifier key.

I'm not really familiar with CoreFX, but a quick documentation search tells me that you may be out of luck:

https://docs.microsoft.com/en-us/dotnet/api/?term=keydown&view=netcore-2.0

**Comment by SteveL-MSFT** [comment]
@janegilring also not able to repro this, if you can provide something that can be repro'd we can look into it

**Comment by janegilring** [comment]
Sorry, this was a user error from my side.
It turns out the problematic code was present in 2 different profile files - Microsoft.PowerShell_profile.ps1 and profile.ps1.

Anyway, thanks for the tip regarding keypresses.
