### ISSUE TITLE
$PSScriptRoot is not populated when used in a default value for a non-mandatory script parameter

### ISSUE THREAD

**Issue by ScotiaBaker** [PowerShell/PowerShell#4688]
Steps to reproduce
------------------
Run this script (via PowerShell -File ....)

```powershell
param(
    [Parameter(Mandatory = $false)]
    [string] $Foo = 'hi\{0}\hi' -f $PSScriptRoot
)

Write-Host $Foo

Function Bar {
    param(
        [Parameter(Mandatory = $false)]
        [string] $Bar = $PSScriptRoot
    )
    Write-Host $Bar
}

Function Baz {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $false)]
        [string] $Baz = $PSScriptRoot
    )
    Write-Host $Baz
}

Bar
Baz
```

Expected behavior
-----------------
```
hi\C:\tmp\hi
C:\tmp
C:\tmp
```

Actual behavior
---------------
```
hi\\hi
C:\tmp
C:\tmp
```

Environment data
----------------
```
Name                           Value
----                           -----
PSVersion                      5.1.16353.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16353.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

_[edited by @daxian-dbw to put the repro in code blocks]_

**Comment by mklement0** [comment]
Actually, what matters is whether the script is an _advanced_ (cmdlet-like) script or not.
By using a `[Parameter(...)]` attribute, you're _implicitly_ making your script an advanced script, even without decoration your `param(...)` block with an explicit `[CmdletBinding()]` attribute.

Combining an advanced script with invocation via `powershell -File` is what produces the symptom, as the following simplified script demonstrates:

Save the following as `t.ps1` in the current dir:

```powershell
[CmdletBinding()]
param(
  $Foo = $PSScriptRoot
)

"[$Foo]"
```

```powershell
# Direct invocation works fine.
> ./t.ps1
[/Users/jdoe]

# Invocation via the external CLI with -File shows the symptom:
> powershell -File ./t.ps1
[]
```

Were you to omit `[CmdletBinding()]`, the symptom would _not_ surface.

---

Two asides:

* Your version table shows a _Windows PowerShell_ version. In this case, the symptom also surfaces in _PowerShell Core_. Generally, you should only report issues here that (also) surface in PS Core, using the latest released version. If a symptom surfaces _only_ in Windows PS, report it on [uservoice.com](https://windowsserver.uservoice.com/forums/301869-powershell).

* Please use the fenced code and output blocks provided in the issue template (`` ```powershell ... `` and `` ```none ... ``) - it makes for much more readable representations.

**Comment by daxian-dbw** [comment]
Thanks @mklement0 for the analysis and simple repro! It's really helpful.
It also repros when you dot source a script cmdlet in powershell, for example:
```powershell
# use the same 't.ps1'
> . .\t.ps1
[]
```
This is because the automatic variables are not set up before parameter binding for a script cmdlet. I'm preparing a fix.

**Comment by LaurentDardenne** [comment]
@SteveL-MSFT
This fix does not have the 'Breaking-Change' label ? Is it correct ?

**Comment by iSazonov** [comment]
:-) Any bug fix is a breaking change. I guess this label is useless here.

**Comment by SteveL-MSFT** [comment]
@iSazonov valid point, I've been thinking about having different degrees of `Breaking Change` labels as they are not all equal

**Comment by iSazonov** [comment]
It make sense only if we want strongly document breaking change [buckets](https://github.com/PowerShell/PowerShell/blob/1a97af7e0418fc56151da490e4bb4edf0409457c/docs/dev-process/breaking-change-contract.md#bucket-1-public-contract) in docs and changelog.

**Comment by SteveL-MSFT** [comment]
I believe we've been trying to use `Breaking-Change` label on issues/PRs that we believe will have a high chance of impact or that the impact is high if encountered.  Agree that technically any bug fix is a breaking change.  So as to not dilute this label, I'm removing it from this issue as it's unlikely anyone is expecting the previous behavior.

**Comment by FireEmerald** [comment]
@SteveL-MSFT Please reopen this issue, it still occurs in powershell v7.2.0. Or am i missing something? In which version was the bug fixed?

``` powershell
PS C:\scripts> Get-Host | Select-Object Version

Version
-------
7.2.0

PS C:\scripts> powershell -File C:\scripts\test.ps1
hello \world
```
``` powershell
# Script test.ps1
[CmdletBinding()]
param(
  [Parameter(Mandatory=$false)][string] $aParam = "$PSScriptRoot\world"
)
Write-Host "hello $aParam"
```

**Comment by iSazonov** [comment]
> ```powershell
> PS C:\scripts> powershell -File C:\scripts\test.ps1
> ```

@FireEmerald I wonder you run _Windows PowerShell_ instead of _pwsh_

**Comment by rkeithhill** [comment]
RE @iSazonov's `powershell` (Windows PowerShell) vs `pwsh` (PowerShell v6/7) question:
![image](https://user-images.githubusercontent.com/5177512/143618319-a0f81657-b775-4eec-9c39-4ab803cb4eb6.png)

**Comment by FireEmerald** [comment]
@iSazonov Because pwsh does not exist on the target machine? Seems like the non core version of powershell doesn't contain the fix for this issue. I should also have posted the version of the runtime called via powershell:
``` powershell
powershell -Command "(Get-Variable PSVersionTable -ValueOnly).PSVersion"

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1320
```

**Comment by iSazonov** [comment]
> Seems like the non core version of powershell doesn't contain the fix for this issue.

Yes, Windows PowerShell gets only security fixes, all new features are added only to pwsh.
