### ISSUE TITLE
Native command fails when transcript enabled

### ISSUE THREAD

**Issue by anmenaga** [PowerShell/PowerShell#4690]
Steps to reproduce / Expected behavior / Actual behavior / Environment data:

![nativecommandfailed](https://user-images.githubusercontent.com/11860095/29792610-be8e6600-8bf5-11e7-952e-0786fd9536af.png)

**Comment by SteveL-MSFT** [comment]
We should see if this is a complex fix before moving out of 6.0.0

**Comment by SteveL-MSFT** [comment]
https://github.com/PowerShell/PowerShell/issues/1920
