### ISSUE TITLE
Tab completion fails in some cases; Cursor drops back to parent folder.

### ISSUE THREAD

**Issue by bgshacklett** [PowerShell/PowerShell#4694]
Steps to reproduce
------------------
1. Manually configure the Tab key handler:
    ```powershell
    Set-PSReadlineKeyHandler -Key Tab -Function Complete
    ```
    I'm not certain what this actually changes, as it appears to be the default before-hand, but it seems to be necessary to reproduce what I'm seeing.
1. Create a file structure to recreate the problem:
   1. Make the parent directory:
   
       ```powershell
       cd ~
       New-Item -Type Directory -Path tmp\PSReadLine_260
       cd tmp\PSReadLine_260
       ```
   1. Create some test files in the directory.
   
       ```powershell
       New-Item -Type File -Path testFileOne.txt
       New-Item -Type File -Path testFileTwo.txt
       New-Item -Type File -Path testFileThree.txt
       ```
   1. Create the file that will break tab completion (note the dot at the beginning).
   
       ```
       New-Item -Type File -Path .testFileOne.txt
       attrib +H .testFileOne.txt
       ```
2. Enter `gc t`
3. Press the Tab key

Expected behavior
-----------------
The resultant command line should read:
`> gc .\testFile`

Actual behavior
---------------
The resultant command line reads:
`> gc .\`

Typing enough of the file name will cause completion to function properly.
`gc testFi<Tab>` will result in:
`gc .\`
`gc testFil<Tab>` will result in:
`gc .\testFile`

Environment data
----------------

```powershell

Name                           Value                                           
----                           -----                                           
PSVersion                      5.1.15063.502                                   
PSEdition                      Desktop                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.15063.502}        
BuildVersion                   10.0.15063.502                                  
CLRVersion                     4.0.30319.42000                                 
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1                                         
```

**Comment by SteveL-MSFT** [comment]
This repros with PSCore Beta.6 and appears to be a PSReadline specific issue as `rmo psreadline` the tab complete works

**Comment by iSazonov** [comment]
Maybe related #4683

**Comment by bgshacklett** [comment]
@SteveL-MSFT It's partially reproducible with the PSReadline module removed, actually. In particular, the `System.Management.Automation.CommandCompletion.CompleteInput` method appears to be returning the hidden file as the first item in the completion list. This happens in vanilla PowerShell (just repro'd in `v. 6.0.0-rc`).

As I just recently mentioned in lzybkr/PSReadLine#260, I suspect that the `ReplacementIndex` property returned by `CompleteInput` is set to zero to account for the beginning of this dotfile, when it actually shouldn't be included. I haven't actually been able to write a test or run it in a debugger to verify, yet, though.

**Comment by SteveL-MSFT** [comment]
@bgshacklett thanks for the additional info
