### ISSUE TITLE
PSCredential.Empty.GetNetworkCredential() throws NRE instead of returning null per docs

### ISSUE THREAD

**Issue by Arnavion** [PowerShell/PowerShell#4696]
Steps to reproduce
------------------

```powershell
> [pscredential]::Empty.GetNetworkCredential()
```

Expected behavior
-----------------

```none
$null
```

Per [the docs](https://github.com/PowerShell/PowerShell/blob/fd047a82506ac6a38c20052f45683cf5407c9c3a/src/System.Management.Automation/engine/Credential.cs#L248), an "uninitialized" `PSCredential` object should return `null`

MSDN also documents it as such, though only on [the page of the explicit cast operator](https://msdn.microsoft.com/en-us/library/system.management.automation.pscredential.op_explicit) which just calls `GetNetworkCredential`

Actual behavior
---------------

```none
Exception calling "GetNetworkCredential" with "0" argument(s): "Object reference not set to an instance of an object."
At line:1 char:1
+ [pscredential]::Empty.GetNetworkCredential()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NullReferenceException
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

---

[`_userName` is `null`](https://github.com/PowerShell/PowerShell/blob/fd047a82506ac6a38c20052f45683cf5407c9c3a/src/System.Management.Automation/engine/Credential.cs#L266) so [`SplitUserDomain` throws at the `IndexOf()`](https://github.com/PowerShell/PowerShell/blob/fd047a82506ac6a38c20052f45683cf5407c9c3a/src/System.Management.Automation/engine/Credential.cs#L369)

```
> $Error[0].Exception.InnerException.StackTrace

   at System.Management.Automation.PSCredential.SplitUserDomain(String input, String& user, String& domain)
   at System.Management.Automation.PSCredential.IsValidUserName(String input, String& user, String& domain)
   at System.Management.Automation.PSCredential.GetNetworkCredential()
   at CallSite.Target(Closure , CallSite , PSCredential )
```

**Comment by iSazonov** [comment]
@Arnavion Thanks for your report and repo!

I agree that we should return null in the case.
