### ISSUE TITLE
Add -WhatIf support to Start-Process.

### ISSUE THREAD

**Issue by thezim** [PowerShell/PowerShell#4702]
Had instance were an OpenSSL process was failing with little help from OpenSSL as to why. Having an output of the exact command being executed would helped me solve my problem alot sooner.

**Comment by sarithsutha** [comment]
@ SteveL-MSFT I'm interested in taking this up

**Comment by SteveL-MSFT** [comment]
@sarithsutha awesome!  unfortunately, GitHub only allows certain people to be assigned, so consider this assigned to you until you say otherwise!

**Comment by sarithsutha** [comment]
@SteveL-MSFT Thanks. Sounds good to me.
