### ISSUE TITLE
32 bit needed

### ISSUE THREAD

**Issue by amainyebriggs** [PowerShell/PowerShell#4707]
please make provision for 32bit

**Comment by amainyebriggs** [comment]
kali

**Comment by alwaysharsha** [comment]
We would love to see 32-bit Powershell for Debian Linux environment

**Comment by TravisEz13** [comment]
We have a new process for on boarding new distributions.  https://github.com/PowerShell/PowerShell/issues/new?assignees=&labels=Distribution-Request&template=Distribution_Request.md&title=Distribution+Support+Request

The form should also have the processor architecture, but you can just put it as a comment until I can add that.
