### ISSUE TITLE
Investigate Get/Protect/Unprotect-CmsMessage cmdlets

### ISSUE THREAD

**Issue by palladia** [PowerShell/PowerShell#471]

**Comment by adityapatwardhan** [comment]
@palladia Can you add more details.

**Comment by palladia** [comment]
I believe these 3 were on our original list of cmdlets to support for Linux.  They were probably disabled due to .NET support.

You can get more details about these cmdlets from:

https://technet.microsoft.com/en-us/library/dn807172.aspx

**Comment by SteveL-MSFT** [comment]
fixed by https://github.com/PowerShell/PowerShell/pull/3224
