### ISSUE TITLE
Add Pull verb

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#4714]
From the discussion on Build and Deploy, it seems we should have a Pull verb.

**Comment by SteveL-MSFT** [comment]
cc @joeyaiello for description

**Comment by megamorf** [comment]
I assume `Get` is too generic then, just curious :-)

**Comment by felixfbecker** [comment]
So what is the opposite of `Push` then? `Pop` or `Pull`?

**Comment by vexx32** [comment]
Is this not simply `Get`? 😄

**Comment by joeyaiello** [comment]
Not totally remembering the justification for this. Going to close it given there's no pressing need right now.
