### ISSUE TITLE
Console input (>) on new line

### ISSUE THREAD

**Issue by BenjaVR** [PowerShell/PowerShell#4727]
When I have a long path, and I want to type something in the PowerShell console, it is annoying the input starts right after the directory location. For example Cmder puts it's lambda sign (it's like the *>* of PS) always on the new line. This way your input is always clearly separated from the directory path, and you don't have these troubles with long directory names.

Illustration:
![image](https://user-images.githubusercontent.com/17981138/29934972-c942d08c-8e42-11e7-870f-69668c83e168.png)

**Comment by markekraus** [comment]
You can always modify your prompt to what ever you want:

```powershell
function Global:prompt {"PS $PWD`n>"} 
```

**Comment by BenjaVR** [comment]
@markekraus that's nice, didn't know about that!
