### ISSUE TITLE
Get-pfxCertificate cmdlet not working

### ISSUE THREAD

**Issue by palladia** [PowerShell/PowerShell#473]

**Comment by bgever** [comment]
PFX is a very common certificate encapsulation format, many online services support it to pass certificate structures around that are password protected.

It's also the default way to support [HTTPS with the Kestrel server](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel) in .NET Core 1.1.

Therefore I think PFX support shouldn't be dismissed. I did see that with [release v6.0.0-alpha.17](https://github.com/PowerShell/PowerShell/releases/tag/v6.0.0-alpha.17) #3224 the Get-PfxCertificate is now supported. 👍

**Comment by PsychoData** [comment]
Just to add to this, there is also a -FIlePath to import from a file
` Get-PfxCertificate -FilePath $certFile`

Which I am using to then check the thumbprint of that certificate without importing it into my windows store, this use case could be equally useful on Linuxes.

**Comment by iSazonov** [comment]
@SteveL-MSFT Should we re-open this for Unix?

**Comment by SteveL-MSFT** [comment]
We'll need to do more research on PowerShell cert management on Linux, but this currently is not a priority.

**Comment by iSazonov** [comment]
I think OpenSSL utilities is good start point for the research.

**Comment by iSazonov** [comment]
Get-PfxCertificate was added in #3224 for Windows and Unix.
What do we track here? Maybe close?
