### ISSUE TITLE
Several messages have 2 spaces between words

### ISSUE THREAD

**Issue by korygill** [PowerShell/PowerShell#4740]
Steps to reproduce
------------------

Run a script from non-elevated that requires admin, for example.
```
...Start Windows PowerShell by  using the Run as Administrator option...
..............................^^
```

Or just look at the change and see the issue.

Expected behavior
-----------------

Messages should have 1 space between words.
(I did not fix all the `"\w+  \w+"` errors in all the other, non resx files...)

Actual behavior
---------------

Some messages have 2 space between words.

Environment data
----------------

PSVersion                      5.1.15063.502
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.502
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by iSazonov** [comment]
@korygill Thanks for your contribution!

Could you please clarify (samples):
> (I did not fix all the  "\w+ \w+"  errors in all the other, non resx files...)

**Comment by korygill** [comment]
@iSazonov what I mean is there are more instances of 2 spaces between words (~401 hits in 143 files) but most, if not all, appear in comments on non-user-facing strings, so no need to fix those necessarily.  If someone wanted to do this, they could search for "\w+  \w+" in the files using any regex/editor like notepad++ under src and see them.

**Comment by iSazonov** [comment]
@korygill Thanks for clarify!

@TravisEz13 Should we fix such typos and add the check to meta tests?
