### ISSUE TITLE
Remove rest of PSWorkflow code

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#4747]
PSWorkflow is not supported on PSCore6.  Some code was removed, but we still have [code specific to PSWorkflow](https://github.com/PowerShell/PowerShell/search?utf8=%E2%9C%93&q=workflow&type=) (query is not intended to be accurate or exhaustive as `WF` is also used in the code)

**Comment by lzybkr** [comment]
As much as I'd like to see all of that code go, I think some care is needed around remoting - we might need more than you'd think.

**Comment by SteveL-MSFT** [comment]
I was looking through the code and we should be careful with any public apis exposing WF.  Remoting and debugging is mixed with WF code.  I suppose you're thinking of PSCore6 remoting/debugging WinPS5 workflow?

**Comment by lzybkr** [comment]
Yeah, v6 client with v5.1 or older server.

One area of concern - CommandType comes through remote machines via PRSP: https://msdn.microsoft.com/en-us/library/ee175965.aspx

Similarly, we could see `WorkflowInfo`: https://msdn.microsoft.com/en-us/library/ee175993.aspx

Implicit remoting might also be an issue.

Maybe less important - should the parser produce a valid `Ast` for workflow even though it won't be supported?

**Comment by iSazonov** [comment]
Maybe first we should cover the areas by tests then try to remove the code?

**Comment by SteveL-MSFT** [comment]
My personal view is that because we support PowerShell side-by-side, I would prefer not to continue unsupported features like WorkFlow (which is not heavily used anyways) for PSC6 client to PS5 target.  In those cases, they can just use ssh remoting and start PS5 on the target side.

As @iSazonov noted, at this point I'm not sure what works and doesn't work because we don't have test coverage for this scenario.
