### ISSUE TITLE
Very slow download of a 50.9 MB installer

### ISSUE THREAD

**Issue by dap-jobandesther** [PowerShell/PowerShell#4749]
I'm trying to download the powershell-6.0.0-beta.6-osx.10.12-x64.pkg, but the download speed is less than 10KB/s. I tried the speed test and I have 23.8 Mbps download speed. Am I the only one experiencing this?

**Comment by iSazonov** [comment]
I can download the package in 3 seconds.

**Comment by dap-jobandesther** [comment]
I see, I'll close this instead.
