### ISSUE TITLE
Consider adding -IgnoreCertificateValidationErrors to Invoke-RestMethod/WebRequest

### ISSUE THREAD

**Issue by oising** [PowerShell/PowerShell#4755]
The commonly used unix utility `curl`, and by extension `libcurl` already support this with the `-k` flag (aka `--insecure` so this should be fairly trivial to implement over CoreCLR. 

I nominate myself to implement this feature. I am loathe to make this any more complicated than just ignoring all errors as I think either you should be going all in, or not at all when it comes to dealing with certificates. This offers the "not at all" option. This is a common scenario within enterprises using internally developed microservices that use self-signed certificates. Their goals are typically to just ensure end to end encryption and not to ensure identity.

**Comment by SteveL-MSFT** [comment]
Isn't this the same as https://github.com/PowerShell/PowerShell/issues/1945?

**Comment by oising** [comment]
Why yes it is. I did search existing issues but I probably forgot to remove the isopen:true directive. Oops. Feel free to close.

**Comment by SteveL-MSFT** [comment]
@oising good news is that it's already implemented :)
