### ISSUE TITLE
New-Object cmdlet needs better Pester coverage

### ISSUE THREAD

**Issue by palladia** [PowerShell/PowerShell#476]
New-Object is an often-used cmdlet.  Currently there's only one Pester test.

**Comment by iSazonov** [comment]
It seems dup #4154

/cc @SteveL-MSFT @adityapatwardhan Can we close this?

**Comment by andschwa** [comment]
I think more time has been spent moving this issuearound than it would have taken to do it at this point. Since there's a newer (and more detailed) issue open, I'll close it.
