### ISSUE TITLE
Build is green if an MSI could not be produced due to e.g. a WiX compilation error

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#4760]
[Here](https://ci.appveyor.com/project/PowerShell/powershell/build/6.0.0-beta.6-5027/artifacts) is an example of a build that is green but should have failed because it could not produce an MSI due to a WiX compilation error.
The WiX compilation error can also not be found in the log.

**Comment by iSazonov** [comment]
@bergmeister Thanks for open the Issue. 
We have the same problem with creating all packages. So we can make the Issue more common.
