### ISSUE TITLE
The term 'Get-WmiObject' is not recognized

### ISSUE THREAD

**Issue by chucklu** [PowerShell/PowerShell#4766]
Hi ,
   I find [Getting WMI Objects (Get-WmiObject)](https://docs.microsoft.com/en-us/powershell/scripting/getting-started/cookbooks/getting-wmi-objects--get-wmiobject-?view=powershell-6) ,and try to use it.
   But the powershell can not recognize it.

Steps to reproduce
------------------

```powershell
 Get-WmiObject -List
```

Expected behavior
-----------------

```none
__SecurityRelatedClass                  __NTLMUser9X
__PARAMETERS                            __SystemSecurity
__NotifyStatus                          __ExtendedStatus
Win32_PrivilegesStatus                  Win32_TSNetworkAdapterSettingError
Win32_TSRemoteControlSettingError       Win32_TSEnvironmentSettingError
...
```

Actual behavior
---------------

```none
Get-WmiObject : The term 'Get-WmiObject' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-WmiObject -List
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-WmiObject:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.6
OS                             Microsoft Windows 10.0.10586
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by chucklu** [comment]
Btw, the command works in  this version,which come with win10
```powershell
PS C:\Users\clu> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.0.10586.1045
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.1045
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by iSazonov** [comment]
Get-WmiObject have been deprecated in PowerShell Core. Please use CIM cmdlet.

**Comment by iSazonov** [comment]
Docs Issue #1645

**Comment by chucklu** [comment]
@iSazonov  what did you mean by CIM?
It seems  cim can not be recognized too.
```powershell
PS C:\Program Files\PowerShell\6.0.0-beta.6> cim win32_service -Filter "name='LBS_MONITOR'"
cim : The term 'cim' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the s
pelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ cim win32_service -Filter "name='LBS_MONITOR'"
+ ~~~
    + CategoryInfo          : ObjectNotFound: (cim:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by chucklu** [comment]
@iSazonov  thanks,I have google CIM, and find the [docs](https://blogs.msdn.microsoft.com/powershell/2012/08/24/introduction-to-cim-cmdlets/)

**Comment by chucklu** [comment]
finally, I come with this command
```powershell
Get-CimInstance -ClassName Win32_Service -Filter "name='LISA_43_Dev_Batch'" | select Name,DisplayName,StartMode,State,StartName,SystemName,Description |Format-Table -AutoSize
```

**Comment by Liturgist** [comment]
@chucklu - Are you asking a question about this command? Does it work as you expected?
BTW, did you ever work at Novell?

**Comment by chucklu** [comment]
@Liturgist  no problem now, and this issue can be closed.
I am in China, have no idea about Novell.

**Comment by DougLeary** [comment]
Tried Get-WmiObject based on web research, got the error that it's not recognized, found this from 2017. 
So it's 2021 now, and I'm trying the new thing, Get-CimInstance. 
Big surprise: "Get-CimInstance' is not recognized as an internal or external command. Well now, that didn't last long. My search for how to use this stuff continues.

**Comment by Hffggvb** [comment]
> Hi ,
> I find [Getting WMI Objects (Get-WmiObject)](https://docs.microsoft.com/en-us/powershell/scripting/getting-started/cookbooks/getting-wmi-objects--get-wmiobject-?view=powershell-6) ,and try to use it.
> But the powershell can not recognize it.
> 
> ## Steps to reproduce
> ```powershell
>  Get-WmiObject -List
> ```
> 
> ## Expected behavior
> ```
> __SecurityRelatedClass                  __NTLMUser9X
> __PARAMETERS                            __SystemSecurity
> __NotifyStatus                          __ExtendedStatus
> Win32_PrivilegesStatus                  Win32_TSNetworkAdapterSettingError
> Win32_TSRemoteControlSettingError       Win32_TSEnvironmentSettingError
> ...
> ```
> 
> ## Actual behavior
> ```
> Get-WmiObject : The term 'Get-WmiObject' is not recognized as the name of a cmdlet, function, script file, or operable
> program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> At line:1 char:1
> + Get-WmiObject -List
> + ~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (Get-WmiObject:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> ```
> 
> ## Environment data
> ```powershell
> > $PSVersionTable
> Name                           Value
> ----                           -----
> PSVersion                      6.0.0-beta
> PSEdition                      Core
> GitCommitId                    v6.0.0-beta.6
> OS                             Microsoft Windows 10.0.10586
> Platform                       Win32NT
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
> PSRemotingProtocolVersion      2.3
> SerializationVersion           1.1.0.1
> WSManStackVersion              3.0
> ```
