### ISSUE TITLE
InvokeWithContext modifies the input list of variables if it contains $_, $input, $this

### ISSUE THREAD

**Issue by nightroman** [PowerShell/PowerShell#4768]
`InvokeWithContext` modifies the input list of variables, namely, removes the
first occurrence of found `$_`, `$input`, `$this`. (Yes, only the first is
removed if for some weird reasons there are more.)

Here is the demo:

```powershell
    # two blocks
    $script1 = {Get-Variable _ -Scope 0}
    $script2 = {Get-Variable _ -Scope 0}
    1..2 | ForEach-Object {
        # prepare list of variables
        $variables = [System.Collections.Generic.List[PSVariable]] @()
        $variables.Add((Get-Variable _))

        # invoke blocks with same variables
        # works
        $script1.InvokeWithContext($null, $variables)
        # fails, $_ is removed from $variables
        $script2.InvokeWithContext($null, $variables)
    }
```

The demo is contrived but the behaviour of `InvokeWithContext` is rather
unexpected. This may cause subtle and probably difficult to find issues.

Is this by design? If yes, then is this by design that only first occurrences
of special variables are removed from the input list?

Environment data
----------------

Windows, PowerShell 5.1
Windows, PowerShell-6.0.0-beta.5-win81-win2012r2-x64

**Comment by markekraus** [comment]
Heh. I can't speak towards intention, but it is definitely removing them [(ScriptBlock.cs Line 461)](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/lang/scriptblock.cs#L461).  I assume it needs to be removed from the collection before calling `InvokeWithPipe`.

**Comment by nightroman** [comment]
1. It is possible to make a copy, to avoid changing the input list.
1. If special variables have to be removed than *all* occurrences should be removed, not just first found.

**Comment by markekraus** [comment]
Hmm.

```powershell
# two blocks
$script1 = {Get-Variable _ -Scope 0}
$script2 = {Get-Variable _ -Scope 0}
1..2 | ForEach-Object {
    # prepare list of variables
    $variables = [System.Collections.Generic.List[PSVariable]] @()
    $variables.Add((Get-Variable _))
    $variables.Add((Get-Variable _))
    $variables.Add((Get-Variable _))

    # invoke blocks with same variables
    # works
    $script1.InvokeWithContext($null, $variables)
    # fails, $_ is removed from $variables
    $script2.InvokeWithContext($null, $variables)
}
```
result:

```
Exception calling "InvokeWithContext" with "2" argument(s): "An item with the same key has already been added."
At line:13 char:9
+         $script1.InvokeWithContext($null, $variables)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException
 

Name                           Value                                                                                                                                            
----                           -----                                                                                                                                            
_                              1                                                                                                                                                
Exception calling "InvokeWithContext" with "2" argument(s): "An item with the same key has already been added."
At line:13 char:9
+         $script1.InvokeWithContext($null, $variables)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException
 
_                              2  
```

This is on line 986 of [CompiledScriptBlock.cs](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/runtime/CompiledScriptBlock.cs#L986). Seems to me that the better option is to have the `foreach` loop starting on 971 skip `_`, `this`, and `input` and leave the referenced variables collection unmolested.
