### ISSUE TITLE
#Requires Statement Not Honoring Version

### ISSUE THREAD

**Issue by RickFlist** [PowerShell/PowerShell#4770]
This #Requires statement does not throw an error when the only available version is v2.0. I have verified syntax is correct by fudging the GUID; it throws an error on import.

#Requires -Modules @{ModuleName="Hyper-V";ModuleVersion="1.1.0.0";GUID="af4bddd0-8583-4ff2-84b2-a33f5c8de8a7"}

I want it to error if this is the only version on the system, but the above requires statement works if Hyper-V Module 2.0 is installed

09/07 10:28:38 -|- [ADMIN] -|- History: 33
CWD: D:\Source\MAX-CPUB-LAB\Modules\>
PS>(Get-Module Hyper-V) | Select *

Name                        : Hyper-V
Path                        : C:\windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.HyperV.PowerShell.Cmdlets\v4.0_10.0.0.0__31bf3856ad364e35\Microsoft.HyperV.PowerShell.Cmdlets.dll
ImplementingAssembly        : Microsoft.HyperV.PowerShell.Cmdlets, Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
Guid                        : af4bddd0-8583-4ff2-84b2-a33f5c8de8a7
HelpInfoUri                 : https://go.microsoft.com/fwlink/?linkid=390775
ModuleBase                  : C:\windows\system32\WindowsPowerShell\v1.0\Modules\Hyper-V\2.0.0.0
Version                     : 2.0.0.0
ModuleType                  : Binary
ExportedCmdlets             : {[Add-VMAssignableDevice, Add-VMAssignableDevice], [Add-VMDvdDrive, Add-VMDvdDrive], [Add-VMFibreChannelHba, Add-VMFibreChannelHba], [Add-VMGpuPartitionAdapter, Add-VMGpuPartitionAdapter]...}
ExportedCommands            : {[Add-VMAssignableDevice, Add-VMAssignableDevice], [Add-VMDvdDrive, Add-VMDvdDrive], [Add-VMFibreChannelHba, Add-VMFibreChannelHba], [Add-VMGpuPartitionAdapter, Add-VMGpuPartitionAdapter]...}
RootModule                  : Microsoft.HyperV.PowerShell.Cmdlets.dll
ExportedFormatFiles         : {C:\windows\system32\WindowsPowerShell\v1.0\Modules\Hyper-V\2.0.0.0\Hyper-V.Format.ps1xml}
ExportedTypeFiles           : {C:\windows\system32\WindowsPowerShell\v1.0\Modules\Hyper-V\2.0.0.0\Hyper-V.Types.ps1xml}

Steps to reproduce
------------------
Add this line to the top of a .psm1 file

```powershell
#Requires -Modules @{ModuleName="Hyper-V";ModuleVersion="1.1.0.0";GUID="af4bddd0-8583-4ff2-84b2-a33f5c8de8a7"}
```

Expected behavior
-----------------
An error similar to the following is thrown
```powershell
ipmo : The script 'CP-LocalVirtualMachines.psm1' cannot be run because the following modules that are specified by the "#requires" statements of the script are missing: Hyper-V.
At line:1 char:1
+ ipmo .\CP-LocalVirtualMachines -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (CP-LocalVirtualMachines.psm1:String) [Import-Module], ScriptRequiresException
    + FullyQualifiedErrorId : ScriptRequiresMissingModules,Microsoft.PowerShell.Commands.ImportModuleCommand
```

Actual behavior
---------------
No error is thrown; no information indicating an error
```none

```

Environment data
----------------

```powershell
PS>$PSVersionTable.GetEnumerator() | ForEach-Object { Write-Host ('{0,-26}: {1}' -f $PSItem.Key,($PSItem.Value -join ", " ) ) } | Out-String
PSVersion                 : 5.1.15063.502
PSEdition                 : Desktop
PSCompatibleVersions      : 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.15063.502
BuildVersion              : 10.0.15063.502
CLRVersion                : 4.0.30319.42000
WSManStackVersion         : 3.0
PSRemotingProtocolVersion : 2.3
SerializationVersion      : 1.1.0.1

```

**Comment by SteveL-MSFT** [comment]
I believe this is intended.  Since the Hyper-V module retains the same guid, PowerShell will treat the version as minimal version and if an exact version isn't found, it'll load the latest version.  If you want to error out, you'll have to do it as a runtime check.

**Comment by RickFlist** [comment]
When I see the word "require" is says to me "I require ONLY this version". I'm not sure who says "I REQUIRE chemotherapy but aspirin is OK because it is in the Pfizer bottle". Either way the documentation should either document the non-intuitive function of the feature or the feature should be changed.
