### ISSUE TITLE
Windows system lockdown APIs are currently stubbed out

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PowerShell#4778]
This means that PowerShell Core running on Windows will not detect system lockdown such as when DeviceGuard or AppLocker application allow policies are applied, and so won't automatically transition into constrained language mode.

This is a work item to re-implement these APIs for Windows platform and to finish porting the corresponding tests.

**Comment by joeyaiello** [comment]
Not enough coverage on or usage of 6.0.0 yet to justify this for the 6.0.0 timeframe. Definitely necessary in the long-run though.

**Comment by PaulHigin** [comment]
Yes, this issue is now closed.  Thanks.
