### ISSUE TITLE
Set-Service.Tests.ps1 tests Failing builds

### ISSUE THREAD

**Issue by markekraus** [PowerShell/PowerShell#4800]
#4785 Introduced tests which are failing builds.

On Windows:

```
Description: New-Service with bad parameters will fail for 'badstarttype' where 'StartupType' = 'System'
Name:        Set/New-Service cmdlet tests..New-Service with bad parameters will fail for 'badstarttype' where 'StartupType' = 'System'
message:
Expected string length 66 but was 13. Strings differ at index 0.
Expected: {CouldNotNewService,Microsoft.PowerShell.Commands.NewServiceCommand}
But was:  {No Exception!}
-----------^
stack-trace:
at line: 65 in C:\projects\powershell\test\tools\Modules\HelpersCommon\HelpersCommon.psm1
65:             $_.FullyQualifiedErrorId | Should Be $FullyQualifiedErrorId | Out-Null
```

On Linux and macOS:

```
[-] Error occurred in Describe block 79ms

   The term 'Get-Service' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

   At /home/travis/build/PowerShell/PowerShell/test/powershell/Modules/Microsoft.PowerShell.Management/Set-Service.Tests.ps1:25 char:48
```

`System` is a valid `System.ServiceProcess.ServiceStartMode` so either [the test](https://github.com/PowerShell/PowerShell/blob/2761c3ff210caf7a9c18968c03c18c6921046251/test/powershell/Modules/Microsoft.PowerShell.Management/Set-Service.Tests.ps1#L165) is flawed or there is an issue with `New-Service`.

The Linux/macOS failures are due to `Get-Service` being called in the TestCases [HashTable literal](https://github.com/PowerShell/PowerShell/blob/2761c3ff210caf7a9c18968c03c18c6921046251/test/powershell/Modules/Microsoft.PowerShell.Management/Set-Service.Tests.ps1#L25). That literal gets parsed regardless of the OS skip resulting in calls to `Get-Service`  on OSE's where it is not present.

**Comment by iSazonov** [comment]
@markekraus Thanks for your report - we skipped `[Feature]` in last commits 😕

**Comment by markekraus** [comment]
@iSazonov There are some other PRs "in the pipe" that look like they affect feature tests but don't have any CI runs with `[feature]`

Also, feature test fails on Linux and macOS continue to show "passed" re:  #4641 ([example](https://travis-ci.org/PowerShell/PowerShell/builds/273858136?utm_source=github_status&utm_medium=notification)). ☹️

**Comment by iSazonov** [comment]
I see that "feature test fails on Linux and macOS continue to show "passed" "
/cc @SteveL-MSFT @TravisEz13

**Comment by TravisEz13** [comment]
The code has been changed so that only non-PRs will fail due to Pester test failures.  I didn't notice that logic error last time.
