### ISSUE TITLE
Publish sample for portable 'hello world' module using PS Std 3.0

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#4809]
We [published the assembly](https://www.nuget.org/packages/PowerShellStandard.Library/3.0.0-preview-01), but don't have a simple sample the community can build on to produce a module

**Comment by mklement0** [comment]
@SteveL-MSFT  "hell*p*"? Why not start with hells "a" through "o"? 😜

**Comment by SteveL-MSFT** [comment]
@mklement0 I think it was a Freudian slip to `Help World` given current state of things

**Comment by rkeithhill** [comment]
FYI, I'm going to create a PR probably later tonight that does a similar walk-through using the dotnet CLI from the WSL console.   The doc is done except that I was waiting on a determination of whether or not .NET 4.7.1 fixes the issue with loading a .NET Standard 2.0 based binary module into Windows PowerShell.  AFAICT it does!!  Just tried it this morning on Windows 10 FCU (16299.15) which seems to come with .NET 4.7.1 (or at least a version of .NET that is newer than 4.7).

**Comment by iSazonov** [comment]
Can we close the Issue?
