### ISSUE TITLE
Powershell Module

### ISSUE THREAD

**Issue by livarcocc** [PowerShell/PowerShell#4810]
_From @Ayanmullick on September 8, 2017 11:46_

## Expected  behavior
As an IT Pro I've created a lot of Powershell scripts over the years for my personal use and gotten used to the syntax. And it'd be nice to be able to work with .Net Core in the same syntax. Also, a .Net Core Powershell module would enable integrating .Net into the existing Powershell scripts more easily

## Actual behavior

Will there also be a Powershell module equivalent to the dotnet CLI commands for .Net Core 2.0.

_Copied from original issue: dotnet/cli#7617_

**Comment by SteveL-MSFT** [comment]
@livarcocc not sure why this was moved to this repo, I think the original ask was to have a PowerShell module equivalent of the dotnet CLI commands.  This isn't something the PowerShell Team would do, it should be up to the dotnet cli team.

**Comment by reyou** [comment]
@livarcocc i think this is a very valid request from @Ayanmullick, and I would like to learn what will be the case of this?

It would be great to have a common Powershell command window in VS 2017, with merging nuget-package-manager and dotnet CLI manager.

**Comment by SteveL-MSFT** [comment]
I agree that this is a very valid request, but PowerShell team can't own the modules for everything particularly where we are not area experts.  Perhaps the best course of action is for the community to start this project and have the dotnet CLI team contribute.  The PowerShell team can help with cmdlet review.
