### ISSUE TITLE
Weird behaviour when passing function results directly to a foreach loop

### ISSUE THREAD

**Issue by tyteen4a03** [PowerShell/PowerShell#4813]
Right now I have this C# code, which compiles to a Cmdlet:
```
    [Cmdlet(VerbsCommon.Get, "Numbers")]
    public class GetNumbersCmdlet: Cmdlet
    {
        protected override void BeginProcessing()
        {
            var list = new List<string>();
            list.Add("1");
            list.Add("2");
            list.Add("3");
            list.Add("4");
            list.Add("5");
            WriteObject(results.ToArray());
        }
    }
```
And this PowerShell script:
```
    foreach ($number in Get-Numbers) {
    	Write-Output "Output is $number"
    }
```
Instead of:

```
    Output is 1
    Output is 2
    Output is 3
    Output is 4
    Output is 5
```
I would get:
```
    Output is 1 2 3 4 5
```
However if I switch to 
```
    $numbers = Get-Numbers
    foreach ($number in $numbers) {
    	Write-Output "Output is $number"
    }
````

I get the intended results.

$PSVersionTable:

```
Name                           Value
----                           -----
PSVersion                      5.1.15063.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.0
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by tyteen4a03** [comment]
Just realised that PS doesn't enumerate values by default (I had to change `enumerateCollection` to true in `WriteObject`). Why is that?

**Comment by mklement0** [comment]
Sometimes you want to send collections _as a single object_ to the pipeline, so it is helpful not to _invariably_ have output collections enumerated.

My guess as to why applying enumeration is _opt-in_ is that you don't always build up an entire _collection_ in C# code up front and then use a _single_ `WriteObject()` call to produce output; you may send scalar objects one by one, using multiple calls.

On the PowerShell side, by contrast, the logic is reversed: `Write-Output -NoEnumerate` must be used to _opt out of_ implicit enumeration.
