### ISSUE TITLE
Enable Select-String test with network path

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#4827]
We have the skipped [Select-String test](https://github.com/PowerShell/PowerShell/blob/02b5f357a20e6dee9f8e60e3adb9025be3c94490/test/powershell/Modules/Microsoft.PowerShell.Utility/string.tests.ps1#L39)
```powershell
        It "Network path" -skip:($IsCoreCLR) {
            (select-string -LiteralPath $fileNameAsNetworkPath "b").count | Should Be 2
        }
```

Should we enable the test or remove?

If enable we should:
1. ~Run it with admin privileges~
2. Fix #4828  `New-TemporaryFile` - it don't return extended provider properties like PSDrive, PSPath...

**Comment by SteveL-MSFT** [comment]
@iSazonov I just tried a simple test on my machine with an unelevated powershell core:

```powershell
select-string -literalpath \\localhost\c$\test.txt "Hello"
```

and this worked on Beta.7 so I think we should be able to enable this test for Windows

**Comment by iSazonov** [comment]
@SteveL-MSFT I wonder - `\\localhost\c$` is system share and users haven't  permissions to access such shares.

**Comment by SteveL-MSFT** [comment]
I just tried:
```powershell
runas /user:${env:computername}\localnonadmin cmd
# in the new window
dir \\localhost\c$
```

Actually, both \\localhost\c$ and \\${env:computername}\c$ worked for my nonadmin local user

**Comment by iSazonov** [comment]
I see. 😕 

I agree If we test only how PowerShell parse network path the test is ok.
