### ISSUE TITLE
Enumerate and run installed PowerShell versions

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#4836]
Currently we changed semantic of `-version` command line parameter from "run Windows PowerShell 2.0" to "show current PowerShell version".

Now we need a way to address a side-by-side scenario - to enumerate installed PowerShell versions and run needed PowerShell version.

### Suggesion
[ ] Enumerate installed versions:
```
>powershell -versions
```

[ ] Run needed version:
```
powershell -versions <ver spec>
```

**Comment by iSazonov** [comment]
I am ready to implement enumeration of installed versions based on https://github.com/PowerShell/vscode-powershell/blob/c3e987c9e9add273e6699972bb017ccfbc47e873/src/platform.ts#L110

**Comment by joeyaiello** [comment]
I totally understand the need for this, but I think that it probably shouldn't be implemented in the host binary. Ultimately, this is the job of the package manager, but I get why we might need something like [virtualenv](https://virtualenv.pypa.io/en/stable/) as well.

However, at this point in the release cycle, it's a pretty high-risk change to bring in (and potentially get wrong), especially when you consider that there won't be any production scenarios for side-by-side 6.x's for at least a little while. 

When we do want to bring it in, we should have an RFC for it (and I think we should have some alternate designs that include a PS module that enumerates versions as well as whether it should be a native tool to support bootstrap scenarios).

@iSazonov do you have a scenario today where this is critical? I think unpacking that is the first step to understanding the proper implementation here (and where having a `pwsh` alias for PS Core isn't enough).

**Comment by iSazonov** [comment]
@joeyaiello I see that VS Code (see link above) discover installed PowerShell versions and allow users run desired version.
Also I know Microsoft SCOR 2012 product. It is based on PowerShell 2.0 (!!!). If users need new features they are forced to run needed version explicitly.
I believe it is better to have the discover feature natively (specially on Windows) - this will make other products more stable.
I'm not sure about launching, but it's also interesting, all the more so when we had `-Version 2`.

**Comment by iSazonov** [comment]
Any news?

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and believes this is should be an RFC for a proposal that can be reviewed in its entirety with considerations for different potential design proposals

**Comment by KirkMunro** [comment]
RFC: https://github.com/PowerShell/PowerShell-RFC/pull/202.
