### ISSUE TITLE
Credentials for Set-Service command

### ISSUE THREAD

**Issue by joandrsn** [PowerShell/PowerShell#4843]
Currently when creating a service using the `New-Service` from the module `Microsoft.PowerShell.Management` I can specify the credentials that my new service will be executed with.

`Set-Service` currently does not support setting the new logon account for the service.
The current workarounds that I have found:
* Use sc.exe to change credentials
* Use `Get-WmiObject -Class Win32_Service` and from there use the `Change` method
* Delete the service and create it again.

But I believe it would be nice to have `Set-Service` support credentials.
Is it possible to add functionality for setting the credentials using the `Set-Service` command?

**Comment by SteveL-MSFT** [comment]
Shouldn't be too hard as Set-Service uses [ChangeServiceConfig](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs#L1704) win32 api which accepts username/password.

**Comment by joandrsn** [comment]
#4844 was merged
