### ISSUE TITLE
Add split window (like tmux or cmder)

### ISSUE THREAD

**Issue by copdips** [PowerShell/PowerShell#4846]
Hello Powershell team,

Could you please add the split window feature to Powershell, like tmux for linux, cmder to windows.
This will make Powershell really powerful.  Thx.

**Comment by SteveL-MSFT** [comment]
I don't think this is something we would have as part of PowerShell.  Similar to tmux, screen, cmder, I think it's something that's outside the shell.

**Comment by copdips** [comment]
@SteveL-MSFT,

Thx for your reply, I have two main usages of the split window.

1/ When I connect to my remote admin server by PSRemoting from my desktop. As it's a admin server, I often need to launch multiple powershell windows to manage other servers. And as we don't have the split window yet, I have to launch multiple PSRemoting from my desktop, it takes time.

2/ In VSCode for Windows, we can only see one terminal at the same time, I really need multiple terminal consoles at the same time instead of  switching among them each time. Cmder is a GUI application that cannot be intergrated into VSCode terminal. 

If the Powershell team doesn't want to implement the split windows, we don't have any other choice ...

**Comment by SteveL-MSFT** [comment]
@copdips the lack of similar tools on Windows and in VSCode is certainly a problem, maybe we can look into it after 6.0.0

**Comment by BrucePay** [comment]
@copdips For multi-window terminal support in VSCode, you might want to open an issue in their repo https://github.com/Microsoft/vscode

**Comment by dragonwolf83** [comment]
There already is an open issue for split terminal in https://github.com/Microsoft/vscode/issues/7504

**Comment by copdips** [comment]
Last vscode insider version just added a feature on vertically splitted terminal

**Comment by kazimir-malevich** [comment]
I have vim running in PowerShell and I really need the ability to split panes both horizontally and vertically. It would also be nice to have vi bindings to navigate through the panes as specified here: https://github.com/christoomey/vim-tmux-navigator#usage

**Comment by rkeithhill** [comment]
@kazimir-malevich I think the closest you will get to this is to use the new Windows Terminal - https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701?activetab=pivot:overviewtab /  https://github.com/microsoft/windowsterminal app.  

It supports h/v split panes e.g:

![image](https://user-images.githubusercontent.com/5177512/80765461-5032f880-8b00-11ea-9f4a-f9aeebb86a0e.png)

**Comment by codenoid** [comment]
@rkeithhill that's really awesome bro, i start using it from now

**Comment by osen** [comment]
I was still not happy with the solutions presented, especially via ssh (multiple ssh connections from a console with tab support).
So I made my own tool similar to tmux.

https://github.com/osen/vimux

Just run 'vimux' and then use shortcuts like <ctrl-c> to open a new terminal within the same ssh session.

**Comment by mswanberg** [comment]
I use Windows Subsystem for Linux.  When I want tmux-type utility, I just start my session with "wsl tmux".  Note, you must have tmux installed in wsl.  From there, I can run powershell.exe or cmd.exe to use those shells, but they are running under bash under tmux under bash/wsl.  A bit kludgy, but it works just fine and ALL of tmux is available... split screens, tabs, resizing windows, etc.  I imagine there may be better shortcuts... maybe some form of "wsl tmux -c powershell.exe" or the like, but I haven't explored it that deeply.
