### ISSUE TITLE
Option types?

### ISSUE THREAD

**Issue by lehtoj** [PowerShell/PowerShell#4854]
I would like to propose option type support for PowerShell, similar to what [F# has](https://fsharpforfunandprofit.com/posts/the-option-type/).

An example scenario involves Active Directory automation tool. The tool proceeds to create or modify user accounts based on given input. 

For each AD attribute; if no value has been given, skip the attribute. If a value has been given, check if it is null. If the value is null, clear the attribute. If a proper value has been given, set the attribute to given value.

The above check would be trivial if PowerShell had support for F# -like option types. Right now the tool uses PowerShell 5 classes, an example below.

`class SingleValueStringProperty {
    [bool] $Clear
    [string] $Value
}`

These classes exist for single value string, multi value string, single value int, single value bool and single value datetime. 

Frankly, it's not very intuitive.

**Comment by BrucePay** [comment]
Hi @KeeperB5 - can you provide some examples showing what you think it should look like? Thanks.

**Comment by KeeperB5** [comment]
Note sure actually. PowerShell does not have the kind of pattern matching that F# does which makes use of the option type such a bliss in F#.

**Comment by BrucePay** [comment]
That's more of less what I'm thinking. Pattern matching would be interesting to add to PowerShell but a significant language change like this should go through the RFC process. Is this something you'd like to start?

**Comment by KeeperB5** [comment]
How does one start RFC process and what's involved throughout?

**Comment by BrucePay** [comment]
The RFC repo is here: https://github.com/PowerShell/PowerShell-RFC and the process is described here: https://github.com/PowerShell/powershell-rfc/blob/master/RFC0000-RFC-Process.md
