### ISSUE TITLE
Restart-Computer and Stop-Computer should take custom message like shutdown.exe

### ISSUE THREAD

**Issue by jongross4** [PowerShell/PowerShell#4857]
When using stop-computer or restart-computer, one should be able to log a reason code and custom message similar to the way that shutdown.exe with /d P:0:1 and /c "Custom Message".  This would allow you to stay in powershell without needing to call out to win32 executable.  See similar concern:
https://stackoverflow.com/questions/15656106/restarting-pcs-and-writing-to-the-event-log-with-a-custom-message

**Comment by raghav710** [comment]
@jongross4 can this issue be tackled by a newbie like me? or would this require some experience with the codebase?

**Comment by lukepayne** [comment]
Hey @PowerShellTeam can I take this one on?

**Comment by vexx32** [comment]
It's up for grabs and still here since last year. Go for it! 😆

**Comment by lukepayne** [comment]
Cool, I should be able to submit a PR soon 😄

**Comment by SteveL-MSFT** [comment]
@lukepayne consider it yours!  thanks!

**Comment by lukepayne** [comment]
I've made a PR with #8112 I'm just waiting to see how the checks turn out.

**Comment by bmkaiser** [comment]
@lukepayne you're doing good work here! hope you're able to resume your efforts soon. I was looking for this feature today and was happy to see that someone had picked up development for this issue

**Comment by kvprasoon** [comment]
@lukepayne, @vexx32, is anyone working on this ?

**Comment by lukepayne** [comment]
@kvprasoon I haven't picked it up again yet

**Comment by doctordns** [comment]
just wondering if anyone is still interested in this??

**Comment by bmkaiser** [comment]
> just wondering if anyone is still interested in this??

I know that I still am! But it's not a deal breaker to not have it

**Comment by doctordns** [comment]
I like the idea (but am in no way competent enough to implement the change).  If there are community members who want to pick this up and finish it, great. If not, then it might be better to close it until such time as there is community effort available to implement this.

**Comment by kvprasoon** [comment]
I would like to pick this up. May be 1 or 2 weeks later.

**Comment by doctordns** [comment]
Cool - thanks very much for stepping up @kvprasoon!

Let us know how it goes...

**Comment by Jibun-no-Kage** [comment]
So when or where can an average joe get to use this update?  Or do I have to wait for some major release of PS?
