### ISSUE TITLE
The term 'New-AzureStorageContext' is not recognized as the name of a cmdlet... Linux

### ISSUE THREAD

**Issue by Uranium2** [PowerShell/PowerShell#4864]
I've been running a script that downloads all my BLOB files on my windows machine. I had no problem. Now i'm trying to do the same on my Ubuntu 16.10.

I've installed PowerShell(6.0.0) on my Ubuntu 16.10. When I try to run my script:

   
```
Clear-Host
    $SubscriptionName = "MySubName"
    $StorageAccountName = "MyStorageAccountName" 
    $StorageAccountKey = "SecretKey"
    $ContainerName = "MyContainerName"
    $localTargetDirectory = "/home/"

    #Set up the storage account context 
    $ctx = New-AzureStorageContext -StorageAccountName $StorageAccountName -StorageAccountKey $StorageAccountKey
    
    Get-AzureStorageContainer -Context $ctx
    
    $blobs = Get-AzureStorageBlob -Container $ContainerName -Context $ctx
    
    foreach($Blob in $blobs){
        Get-AzureStorageBlobContent -Blob $Blob.Name -Container $ContainerName -Destination $localTargetDirectory -Context $ctx -Force
        }

```
PowerShell does not recognize several commands.

`    New-AzureStorageContext : The term 'New-AzureStorageContext' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At /home/file.ps1
`
So I tried to install AzureRM module:

     PS /home> Install-Module AzureRM

It works. Now I import the Module:

```
    PS /home> Import-Module AzureRM
    Import-Module : The specified module 'AzureRM' was not loaded because no valid     module file was found in any module directory.
    At line:1 char:1
    + import-module <<<<  azurerm
    + CategoryInfo          : ResourceUnavailable: (azurerm:String) [Import-    Module], FileNotFoundException + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

```
I tried to download manually `AzureRM` module (version 4.3.1) like this:

```
    PS /home> Save-Module -Name AzureRM -Path ~/.local/share/powershell/modules/ -RequiredVersion 4.3.1
    PS /home> Install-Module -Name AzureRM
```

Modules did download, installation gives no out-put and still doesn't work.

**Comment by markekraus** [comment]
I think if you are working on Linux, you need to ensure you are using the `AzureRM.NetCore` Modules.

```powershell
 Install-Module -Name 'AzureRM.NetCore'
```

I'm not familiar with the AzureRM modules, but some of the commands may not be available in the Core module yet or at all. It appears `New-AzureStorageContext` is one of those missing commands. You might need to consult the `AzureRM.NetCore` documentation and project site https://github.com/Azure/azure-PowerShell to find the equivalent command/process, status of adding missing commands, or to open an issue.

**Comment by Uranium2** [comment]
I understand now. Anyway I have found my way trough it without PowerShell.
I'm using [AzCopy](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-linux?toc=%2Fazure%2Fstorage%2Ffiles%2Ftoc.json&view=azuremobileserverentity-2.0.0) that does what I need in one command line.
