### ISSUE TITLE
The tab complete returned command is repeated

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#4865]
Steps to reproduce
------------------
get-psr```<press tab>```

Actual behavior
------------------
return:
Get-PSReadlineKeyHandler  Get-PSReadlineOption      Get-PSRepository          Get-PSReadlineKeyHandler  Get-PSReadlineOption

Environment data
----------------
centos 7.4 + powershell 6.0 beta7

**Comment by lzybkr** [comment]
Duplicate of https://github.com/lzybkr/PSReadLine/issues/430
