### ISSUE TITLE
php exec/shell_exec does not work with powershell v6.0.0-beta.7

### ISSUE THREAD

**Issue by sahnepudding** [PowerShell/PowerShell#4873]
After updating powershell v6.0.0-beta.6 to v6.0.0-beta.7
the following example command does not work anymore:

var_dump(exec("powershell --help"));
result: string(0) ""

On my production site (powershell v6.0.0-beta.6)
i still get the full output of the help command.
I' am sure it's not a problem with filepermissions on the server.

I would appreciate any ideas.

**Comment by markekraus** [comment]
dues using the absolute file path to the `powershell` binary work? Perhaps PHP doesn't see it in its path, for some reason.

Also, can you pleas post the output of `$PSVersionTable`?

**Comment by sahnepudding** [comment]
I just went back to version v6.0.0-beta.6 and the problem still persists on this system. 
So i guess it has nothing to do with the powershell version.
I also used absolute paths for testing and got the same results.

```
exec("powershell -help 2>&1", $out);
var_dump($out);
```

Result: 
`array(7) { [0]=> string(63) "FailFast: Object reference not set to an instance of an object." [1]=> string(0) "" [2]=> string(66) " at System.Environment.FailFast(System.String, System.Exception)" [3]=> string(66) " at System.Environment.FailFast(System.String, System.Exception)" [4]=> string(88) " at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String, System.String[], Int32)" [5]=> string(63) " at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])" [6]=> string(7) "Aborted" }` 

$PSVersionTable:

Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.6
OS                             Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u3 (2017-08-15)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by markekraus** [comment]
if you do 

```php
exec("strace -v powershell -help 2>&1", $out);
var_dump($out);
```
You might get some useful information. Might be a library path is missing from the environment or something. But this appears to be a PHP/Environment issue and not PowerShell specific.

**Comment by sahnepudding** [comment]
Thanks for your assist. 
strace -v returns a huge array and actually there are some files and folders which cannot be found.
E.g. "/netcoredeps/tls". But i have no clue why it's missing or how to fix it. The whole strace output can be found [here](http://88.198.80.208/stracepowershell.txt)

**Comment by markekraus** [comment]
@sahnepudding I believe we determined this is a PHP/Environment issue. I;m going to close this issue. If you can still reproduce this issue in RC.2, please update this issue and I will re-open.
