### ISSUE TITLE
Reduce scope of File Encoding RFC implementation

### ISSUE THREAD

**Issue by JamesWTruher** [PowerShell/PowerShell#4878]
I would like to suggest a staged approach for https://github.com/PowerShell/PowerShell-RFC/blob/master/2-Draft-Accepted/RFC0020-DefaultFileEncoding.md

By removing the support for WindowsLegacy as an encoding type and removing the support for PSDefaultFileEncoding, I believe we can satisfy the bulk of our customers by standardizing our various encoding parameter types to a single type `System.Text.Encoding` and provide a default encoding of UTF-8 without bom. A type forwarder could be constructed to support the string UTF-8WITHBOM to be a utf-8 encoding with BOM. We can use the current code when appending to a file and encoding is not specified.

If customer demand for WindowsLegacy is strong, we can implement that at a later date. This provides a staged approach while producing the breaking change earlier to gather feedback

**Comment by joeyaiello** [comment]
Formal ack, I'm good with it.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and agreed on the proposal

**Comment by JamesWTruher** [comment]
this was addressed byhttps://github.com/PowerShell/PowerShell/pull/5080
