### ISSUE TITLE
PSEdit support from non-ISE PowerShell sessions

### ISSUE THREAD

**Issue by OpsTalkJordan** [PowerShell/PowerShell#4885]
PSEdit is currently the best way to edit files on Nano Server but it requires opening ISE and creating a PSSession there. ISE has it's own drawbacks which makes switching between sessions inconvenient when moving between working directories and trying to edit files. I would like to see PSEdit compatibility added to the standard PowerShell host. The ideal scenario would be to edit the file directly in the console similar to many Linux terminal based text editors. A less ideal but potentially more approachable solution would allowing PSEdit to be used in a non-ISE session that then opens an ISE process on the local machine similar to how PSEdit currently behaves in ISE.

**Comment by SteveL-MSFT** [comment]
You can use any console based editor, but if you want a remote GUI editing experience, perhaps @daviwil can help

**Comment by Nezbourn** [comment]
My concern would be needing to install the console based editor on every remote host. I guess I'm not sure if I installed something like VIM on my admin machine if I would be able to access the binary from a remote host as it is installed locally.

**Comment by SteveL-MSFT** [comment]
@Nezbourn I see, that's a valid scenario that you may not be able to install anything on the target.  I would think this can be solved with VSCode, PowerShell remoting, and PowerShell Editor Services

**Comment by thecliguy** [comment]
@SteveL-MSFT Would an editor agnostic solution be possible? EG:
- On the source computer, run `pwsh`
- `Enter-PSSession` to the target computer.
- Run `psEdit`:
  - Behind the scenes, create a temporary file on the source computer.
  - Open the temporary file in a local editor _(the editor of choice could perhaps be defined in an Automatic Variable or Environment Variable)_.
  - Upon closing the editor, return control to the caller and _behind the scenes_ upload the temporary file to the target computer.

**Comment by SteveL-MSFT** [comment]
@thecliguy it's possible, but we should think through a proper design.  I think a common convention is to use an environmental variable called `Editor` that we could invoke on the client side when `psedit` is invoked on the target side.  The difficulty will be handling cases where you've lost connection.

**Comment by thecliguy** [comment]
@SteveL-MSFT Thanks for the swift response, appreciate it. 

Agreed, it needs a proper design. My thoughts were merely an extension to how I believe `PSedit` in ISE currently works _(Read the content of the remote file, write it to a local file, edit the local file and then replace the content of the remote file)_.

Simple but effective, I've found `PSedit` to be a most useful tool since it was introduced in PowerShell 5.0.

I do hope this feature request gets some attention.

**Comment by SteveL-MSFT** [comment]
PSEdit works from VSCode so deferring this
