### ISSUE TITLE
Improve UTF8 Tests for Invoke-WebRequest and Invoke-RestMethod

### ISSUE THREAD

**Issue by markekraus** [PowerShell/PowerShell#4890]
The current tests (soon to be) added in #4869 are an improvement from before but, perhaps, some better tests could be added.

Possibilities include ensuring there are no UTF16 or UTF32 chars, generating UTF8 from the WebListener controller instead of using a view, etc.

Also after #4888, a check can be made on the response headers from `Invoke-RestMethod`.

**Comment by iSazonov** [comment]
We could look how our file encoding tests works.
Also I believe it make sense to use `u{...} in test file if we need a constant test string - it protect our tests if we change the file encoding.
