### ISSUE TITLE
Showwindow switch for help/get-help cmdlet for Exchange Online Powershell cmdlets

### ISSUE THREAD

**Issue by sulobr** [PowerShell/PowerShell#4901]
When using -showwindow switch with help or get-help for Exchange Online cmdlet, the details of the cmdlet is not displayed. 

instruction to connect to EXO is documented below
https://technet.microsoft.com/en-us/library/jj984289(v=exchg.160).aspx

https://technet.microsoft.com/en-us/library/mt775114(v=exchg.160).aspx

for example 
get-help Get-MailboxCalendarFolder -showwindow 
help Get-MailboxCalendarFolder -showwindow

Get-Help works in cmdlet line as below but -ShowWindow doesn’t show same details  in the window

PS C:\Users\user1> get-help Get-MailboxCalendarFolder

NAME
    Get-MailboxCalendarFolder

SYNOPSIS
    This cmdlet is available in on-premises Exchange Server 2016 and in the cloud-based service. Some parameters and settings may be exclusive to one environment or the other.

    Use the Get-MailboxCalendarFolder cmdlet to retrieve the publishing or sharing settings for a specified mailbox calendar folder.

    For information about the parameter sets in the Syntax section below, see Exchange cmdlet syntax.

SYNTAX
    Get-MailboxCalendarFolder -Identity <MailboxFolderIdParameter> [-DomainController <Fqdn>] [<CommonParameters>]

DESCRIPTION
    The Get-MailboxCalendarFolder cmdlet retrieves information for the specified calendar folder. This information includes the calendar folder name, whether the folder is currently
    published or shared, the start and end range of calendar days published, the level of details published for the calendar, whether the published URL of the calendar can be searched on
    the web, and the published URL for the calendar.

    You need to be assigned permissions before you can run this cmdlet. Although all parameters for this cmdlet are listed in this topic, you may not have access to some parameters if
    they're not included in the permissions assigned to you. To see what permissions you need, see the "Calendar configuration" entry in the Recipients Permissions topic.

RELATED LINKS
    Online Version http://technet.microsoft.com/EN-US/library/dba2cebb-3c37-40ce-8ac0-93ec8d79ce0d(EXCHG.160).aspx

REMARKS
    To see the examples, type: "get-help Get-MailboxCalendarFolder -examples".
    For more information, type: "get-help Get-MailboxCalendarFolder -detailed".
    For technical information, type: "get-help Get-MailboxCalendarFolder -full".
For online help, type: "get-help Get-MailboxCalendarFolder -online"

Expected behavior
-----------------

get-help Get-Mailbox -showwindow or help get-mailbox -showwindow cmdlet should show details of the help documentation in the window

Actual behavior
---------------

get-help Get-Mailbox -showwindow or help get-mailbox -showwindow cmdlet does not show details of the help documentation in the window. It is blank

**Comment by sulobr** [comment]
![showwin2](https://user-images.githubusercontent.com/32208482/30766650-527bb12e-9fab-11e7-9a31-5fe7dd291825.PNG)

**Comment by SteveL-MSFT** [comment]
`-showwindow` isn't supported on PowerShell Core so we should remove that switch.

On Windows PowerShell 5.1, that is a known issue that isn't planned to be fixed since most users use the console output or MSDN.

**Comment by SteveL-MSFT** [comment]
https://github.com/PowerShell/PowerShell/pull/4903 to remove this switch as this feature depends on WPF which isn't on CoreCLR
