### ISSUE TITLE
Missing documentation - What's the purpose of $IsCoreCLR?

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#4904]
This is not an issue but I can't find any information about what's the purpose and usage for this variable:
$IsCoreCLR.

This is not event included in the PowerShell Help documentation.
It's excluded from the "About_Automatic_Variables" help doc.

So, all other $Is* are self-explanatory!

Steps to reproduce
------------------

```powershell
Get-Variable Is*

Name                           Value
----                           -----
**IsCoreCLR                      True**
IsLinux                        False
IsMacOS                        False
IsWindows                      True

Get-Help About_Automatic_Variables

```
Help document has no information about any of the $Is* variables.

$Psver
Environment data
----------------

```powershell
PS C:\Program Files\PowerShell\6.0.0-beta.7> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.7
OS                             Microsoft Windows 10.0.16294
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by SteveL-MSFT** [comment]
This is a new one for PSCore6.  Originally, we weren't committed to only supporting CoreCLR so there was a possibility of a FullCLR version.  I'm actually not sure if there's still value in having this and perhaps we should remove it.  cc @daxian-dbw @joeyaiello

**Comment by markekraus** [comment]
Not that there aren't other ways of doing this, but it is useful for pester testing where features of a module are exclusively available in Core or Windows PowerShell. Since `$IsCoreCLR` will not eval `$true` in 5.1, you can easily add a `-pending:$IsCoreCLR` or `-skip:(-not $IsCoreCLR)`

**Comment by SteveL-MSFT** [comment]
`$PSVersionTable.PSEdition -eq "Core"` covers that usage (although more verbose)

**Comment by markekraus** [comment]
Agreed. It's not a strong argument for keeping it, but I grew fond of it. 😄

**Comment by iSazonov** [comment]
I agree that we should remove `$IsCoreCLR` before RTM.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee discussed this and agrees there is no value to keep $IsCoreClr so we recommend removing it

**Comment by apetitjean** [comment]
I noticed this variable is still present in the Release Candidate 1. Don't forget to remove it ;-)

**Comment by markekraus** [comment]
It maybe here to stay: https://github.com/PowerShell/PowerShell/pull/5324#issuecomment-343644775

**Comment by SteveL-MSFT** [comment]
Given where we are with RC and headings towards GA and this is really a matter of cleanliness and not a functional issue to keep it (and our tests are using it so changing them to use PSEdition is work), this is going to stay.
