### ISSUE TITLE
User Agent Statically Reports "Windows NT" as the platform.

### ISSUE THREAD

**Issue by markekraus** [PowerShell/PowerShell#4913]
https://github.com/PowerShell/PowerShell/blob/1c921cdf85e83c431a4888813302b0c241e384ce/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/PSUserAgent.cs#L125

Steps to reproduce
------------------

```powershell
$bingdings = [System.Reflection.BindingFlags]::NonPublic -bxor [System.Reflection.BindingFlags]::Static
[Microsoft.PowerShell.Commands.PSUserAgent].GetProperty('Platform',$bingdings).GetValue($null,$null)
```

Expected behavior
-----------------

This should change based on the platform 

Examples

| OS | Platform |
|--|--|
| Windows | Windows NT |
| macOS | Macintosh |
| Linux | Linux |

Actual behavior
---------------

```none
Windows NT
```

Environment data
----------------

```powershell
> $PSVersionTable
```

```none
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.7
OS                             Linux 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
Expected platform seems right based on behavior of Internet Explorer and Safari

**Comment by iSazonov** [comment]
I see the `UserAgent` class contains public properties to emulate different User-Agents.
Based on [FireFox](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox) it seems the properties return broken User-Agent strings. We don't use the properties. Why we expose its? If an user want emulate a native User-Agent string he can copy-paste real string.

**Comment by markekraus** [comment]
Maybe removing the public members could be a separate issue. It's definitely a breaking change as people use it now. 

My real concern is the Internal `UserAgent` member which the public will come to recognize as PowerShell's User-Agent signature (and for better or worse shape their HTTP responses to it). That should definitely have the correct Platform. portion.
