### ISSUE TITLE
powershell, whether can like linux, path is the top , command is the bottom

### ISSUE THREAD

**Issue by anlexN** [PowerShell/PowerShell#4915]
![default](https://user-images.githubusercontent.com/8686739/30791338-53031480-a1e4-11e7-90d6-78a4f76e57dd.PNG)
<!--

i'm windows 10pro, the latest powershell

**Comment by Tadas** [comment]
You want to [customise your prompt function](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_prompts?view=powershell-5.1). It prints the prompt and you can change it to output anything you want, in your case:
```powershell
function prompt {
	"PS $($executionContext.SessionState.Path.CurrentLocation)`r`n$('>' * ($nestedPromptLevel + 1)) "
}
```
The prompt is completely customizable and you can do some pretty crazy stuff: https://github.com/Jaykul/PowerLine

**Comment by anlexN** [comment]
@Tadas , thank you so much!
