### ISSUE TITLE
Set-Service should accept InputObject service controller

### ISSUE THREAD

**Issue by kwint** [PowerShell/PowerShell#4916]
Currently set-service doesn't have a InputObject parameter which accepts the System.ServiceProcess.ServiceController object, while other *-service cmdlets do.

Currently this doesn't work:
```
$a = Get-Service vds
set-service $a -startupType Automatic
````

while start-service and stop-service do work this way
```
$a = Get-Service vds
Stop-Service $a
```
and pipeline does also work 
`Get-Service vds | Set-Service -startupType Automatic`

a work around is this:
```
$a = Get-Service vds
Set-Service $a.ServiceName -startupType Automatic
```

**Comment by travisty-** [comment]
It looks like `-InputObject` is a named parameter on `Set-Service` currently.

I'm working on a fix at the moment; @powershell could you assign this issue to me?
