### ISSUE TITLE
'/' WebListener test broken 

### ISSUE THREAD

**Issue by markekraus** [PowerShell/PowerShell#4919]
#4905 and #4888 combined to make the errors showing up in AppVeyor. The URL is probably ending with a double `//` now which is causing the `404`.

https://ci.appveyor.com/project/PowerShell/powershell/build/6.0.0-beta.7-5512
https://ci.appveyor.com/project/PowerShell/powershell/build/6.0.0-beta.7-5509
https://ci.appveyor.com/project/PowerShell/powershell/build/6.0.0-beta.7-5511

**Comment by SteveL-MSFT** [comment]
That explains the failure I was seeing in my PR.
