### ISSUE TITLE
CommandInvocationIntrinsics.InvokeScript bind arguments to $input instead of $args

### ISSUE THREAD

**Issue by PetSerAl** [PowerShell/PowerShell#4923]
[This lines](https://github.com/PowerShell/PowerShell/blob/master@%7B2017-09-26%7D/src/System.Management.Automation/engine/MshCmdlet.cs#L687-L690):
```csharp
public Collection<PSObject> InvokeScript(string script, params object[] args)
{
    return InvokeScript(script, true, PipelineResultTypes.None, args);
}
``` 
Pass `args` parameter into `input` parameter of called function, thus mixing them up.

Steps to reproduce
------------------

```powershell
$ExecutionContext.SessionState.InvokeCommand.InvokeScript('"`$args:($args); `$input:($input)"', 1, 2, 3)
```

Expected behavior
-----------------

```none
$args:(1 2 3); $input:()
```

Actual behavior
---------------

```none
$args:(); $input:(1 2 3)
```

Environment data
----------------

Tested in v2.0 and v5.1.15063.608

**Comment by SteveL-MSFT** [comment]
Good find!  This looks like just a mistake in the code.

**Comment by lzybkr** [comment]
@PowerShell/powershell-committee - Adding `Breaking-Change` because it is. Were call sites reviewed to evaluate impact? On the surface, it feels low risk, but it's hard to evaluate without knowing where the api is actually used.

**Comment by iSazonov** [comment]
Reopen to track previous question.

**Comment by SteveL-MSFT** [comment]
@lzybkr in our code, most calls are using InvokeScript(script) and the rest don't call this specific overload.  Unfortunately, `InvokeScript` is a pretty common method name so a search on GitHub returns many results, but most I looked at briefly on the first 4 pages aren't PowerShell related.

**Comment by lzybkr** [comment]
You need to add an extension when searching - much more useful results:

https://github.com/search?utf8=%E2%9C%93&q=InvokeScript+extension%3Aps1&type=Code
https://github.com/search?utf8=%E2%9C%93&q=InvokeScript+extension%3Apsm1&type=Code

I see many calls to what I think is the same api (mostly in psm1 files), but the parameter in question is always `$null`. I only sampled the results though.

**Comment by SteveL-MSFT** [comment]
@lzybkr As best I could tell based on your search results, the [Reflection](https://www.powershellgallery.com/packages/Reflection/4.8) module uses InvokeScript() passing in input/args.  From my basic test, it appears to work fine with the change.  Are you ok to close this?

**Comment by lzybkr** [comment]
That module doesn't call the overload that was fixed, so it's not affected by the change.
I'm fine with closing as long as the change is documented properly.

**Comment by iSazonov** [comment]
@SteveL-MSFT Could you please add this in the PR description (it is very short) for future documentation?

**Comment by SteveL-MSFT** [comment]
@iSazonov I've already added the `documentation needed` label to the PR

**Comment by iSazonov** [comment]
Yes, I see. I meant that the description very short - don't clear that we should document.

**Comment by SteveL-MSFT** [comment]
I think it's clear enough when my team goes through the `documentation needed` items later.  `args` was being passed to the `input` parameter incorrectly.

**Comment by MartinGC94** [comment]
Just ran into this while making a PowerShell module that is supposed to work in 5.1 and 7+ (please start shipping 7 with Windows). The workaround I came up with was to just add this to the snippet I run: `$FixedInput = if ($args.Count -ne 0) {$args} else {$input}` this also has the positive side effect of enumerating `$input`.
