### ISSUE TITLE
PowerShell ETW logging on windows needs to use a unique provider id and register the manifest.

### ISSUE THREAD

**Issue by dantraMSFT** [PowerShell/PowerShell#4939]
Currently, PowerShell uses the same ETW provider GUID as PowerShell on Windows. This presents a few, subtle problems:
1: PowerShell 6 events cannot be easily distinguished from PowerShell/Windows.
2: PowerShell 6 is relying on a valid ETW manifest being registered to ensure events can be decoded. This assumption breaks on down-level systems that do not contain PowerShell/Windows 5.X and also ties PowerShell 6 to PowerShell/Windows events.
The solution is as follows:
1: Snapshot the PowerShell/Windows ETW manifest and update the provider GUID and Provider Name.
> The Event viewer location should be moved outside the Microsoft/Windows event tree since PowerShell 6 does not ship inbox.
2: Provide a script or MSI action to register the PowerShell 6 manifest either at install time or as a post install, user step to address xcopy deploy use cases.
3: Document the updated Provider GUID, name, and any registration steps (if appropriate)consumers.

**Comment by lzybkr** [comment]
It might be worth moving to EventSource instead of using ETW directly - this would be useful on Linux/Mac.

**Comment by anmenaga** [comment]
What is the plan for several different PS versions installed side-by-side?

**Comment by SteveL-MSFT** [comment]
I think side-by-side PSCore should be fine in the same log as long as it can be filtered.  PSCore and Windows PowerShell should be completely separate

**Comment by iSazonov** [comment]
[EventSource Proposal](https://github.com/dotnet/coreclr/blob/027180d8ef4a8a0e50f4cba3ad985af38882f5ef/Documentation/coding-guidelines/cross-platform-performance-and-eventing.md#eventsource-proposal)

**Comment by SteveL-MSFT** [comment]
I believe the current thinking is to have PSCore6.x all in the same log, but should be easy to filter for a particular version.

**Comment by iSazonov** [comment]
@RichardSiddaway As @SteveL-MSFT said we can use a field to filter. The field can be PSVersion or GitCommitId.

**Comment by mirichmo** [comment]
For reference: #1189

**Comment by daxian-dbw** [comment]
@dantraMSFT #5360 has been merged. Do you want to leave this issue open to track the manifest file clean up work?

**Comment by dantraMSFT** [comment]
No, I'll close it and create a separate issue.  I don't know when we'll do the manifest cleanup since it depends on removing full CLRcode that references it.

https://github.com/PowerShell/PowerShell/issues/5394

**Comment by dantraMSFT** [comment]
Actually, this needs to remain open until the PowerShell.Core.Instrumentation nuget package is published.
