### ISSUE TITLE
Expect like capability with PowerShell

### ISSUE THREAD

**Issue by manofspirit** [PowerShell/PowerShell#4951]
Hi there,

I'm just trying to find a tech for macOS which can be used to automate CLI commands, Like Expect https://en.wikipedia.org/wiki/Expect

So can i use PowerShell for that?

Please advise.

**Comment by SteveL-MSFT** [comment]
I don't think you could do this easily in PowerShell today, but there are ways with PowerShell to redirect stdin/stdout of a console app.  Perhaps this is something we could have better support for once we have DSL available.

However, you should be able to use Expect within PowerShell today.

**Comment by rkeithhill** [comment]
There is a PowerShell module that is supposed to mimic Expect in PowerShell.  https://www.powershellgallery.com/packages/Await/0.8

**Comment by SteveL-MSFT** [comment]
@rkeithhill awesome!
