### ISSUE TITLE
Broken rendering for CJK on Windows

### ISSUE THREAD

**Issue by icylogic** [PowerShell/PowerShell#4964]
Steps to reproduce
------------------
Type CJK characters in Powershell

Expected behavior
-----------------
Correct rendering just like ascii characters.

Actual behavior
---------------
Japanese:
![j](https://user-images.githubusercontent.com/2814357/31048708-070009ec-a5f1-11e7-8abb-67ec2ccb8542.gif)
(Windows Japanese IME installed from Windows settings)

Chinese:
![c](https://user-images.githubusercontent.com/2814357/31048710-1187a1ea-a5f1-11e7-8abc-ada115a52ebf.gif)
(Windows Pinyin installed from Windows settings)

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.7
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Notes:
Chinese users (and Japanese users, I guess) suffer from incorrect rendering on Windows for years. CMD, Powershell and Powershell Core have never solved this issue.

#3560 seems to be a related issue.

**Comment by SteveL-MSFT** [comment]
What code page are you using?  Run `chcp`.  If it's not 65001 (UTF8), try `chcp 65001`.

**Comment by icylogic** [comment]
@SteveL-MSFT 

![2017-09-30_17-35-36](https://user-images.githubusercontent.com/2814357/31049680-f2fa66ee-a605-11e7-8220-604ff25a3a21.gif)

**Comment by SteveL-MSFT** [comment]
If cmd.exe has the same problem, then this is really an issue with the Windows console and I don't think there's anything PowerShell can do to fix it.  Best thing to do is to open an issue here: https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo?query=cjk

**Comment by Chigogo** [comment]
@SteveL-MSFT Insane bug.

**Comment by be5invis** [comment]
@bitcrazed

**Comment by stknohg** [comment]
I had same problem using PSReadline and proportional font.
Diasbling PSReadline(`Remove-Module  PSReadLine`) or using monospaced font(e.g. MS Gothic), I avoid this problem.

I think this problem is related https://github.com/lzybkr/PSReadLine/issues/289
