### ISSUE TITLE
Passing a script block to an external utility should only trigger Base64 encoding if the target is `powershell -command`

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#4973]
Related: #4966

Currently, _any_ script block you pass to an external utility from within PowerShell translates translation of the script block into `-encodedCommand <base64-encoded-script-block-string> -inputFormat xml -outputFormat text` (you can override the `-inputFormat` and `-outputFormat` values by passing them explicitly, however), even though that only makes sense when invoking (another instance of) _PowerShell_.

@PetSerAl has noted that it may be non-trivial to robustly detect when PowerShell is being called and that passing a script block to something other than PowerShell is generally not useful, but the current behavior is surprising and should at least be documented.

An easy improvement would be to restrict the implicit Base64-encoding to commands where `-Command` (or an unambiguous prefix) precedes the script block.

As for what should happen when it is _not_ PowerShell that is targeted: arguably, a script block should be _stringified_ and the result passed as an argument (e.g., `{ "hi" }` -> ` "hi" `).

Steps to reproduce
------------------

Run _from PowerShell_ on a Unix platform:

```powershell
powershell -noprofile -command { "hi" }
/bin/echo { "hi" }
```

Expected behavior
-----------------

```none
hi
 "hi"   # surrounded by a space on either side - the result of { "hi" }.ToString()
```

Actual behavior
---------------

```none
hi
-encodedCommand IAAiAGgAaQAiACAA -inputFormat xml -outputFormat text
```

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.7 on macOS 10.12.6
PowerShell Core v6.0.0-beta.7 on Ubuntu 16.04.3 LTS
PowerShell Core v6.0.0-beta.7 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
Windows PowerShell v5.1.15063.502 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by PetSerAl** [comment]
Nitpicking, but it not always `-inputFormat xml -outputFormat text`:
```powershell
cmd /c echo { } -I T | echo
```

**Comment by mklement0** [comment]
Thanks, @PetSerAl - I've updated the original post to clarify that you can override `-inputFormat` and `-outputFormat`.
