### ISSUE TITLE
Remove use for strlen from native code

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#4975]
Remove and or replace the use for strlen from native code

**Comment by SteveL-MSFT** [comment]
@mirichmo can you take this one?

**Comment by mirichmo** [comment]
I've been looking into it and the use of `strlen` seems appropriate in this case. From [MSDN](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strnlen-strnlen-s), "strnlen is not a replacement for strlen; strnlen is intended to be used only to calculate the size of incoming untrusted data in a buffer of known size—for example, a network packet"

It is used twice within ...\src\powershell-native\nativemsh\CssMainEntry.cpp. One invocation of it calculates the length of a hardcoded string that is guaranteed to be null terminated. The other invocation calculates the length of a string passed in as a command-line argument. In the second instance, we do not know the length of the incoming string so it would introduce a bug to artificially guess the value.

**Comment by TravisEz13** [comment]
this is not an appropriate resolution.  This issue is 'must fix'.  Please speak with me before closing.
