### ISSUE TITLE
PowerShell on Linux package installation should set up a symbolic link to resolve libgssapi_krb5 to support client-side psrp over kerberos.

### ISSUE THREAD

**Issue by dantraMSFT** [PowerShell/PowerShell#4976]
Steps to reproduce
------------------
Install powershell on Ubuntu 16.04  with the latest build of the psrp client (1.3.0).  Domain join the machine/vm and attempt to connect to a windows machine using -Authentication Kerberos.

Expected behavior
-----------------
The connection succeeds.

Actual behavior
---------------
The connection fails with an access denied.

the problem occurs due to a PSRP's dynamic loading of libgssapi_krb5.  Since powershell itself has no explicit dependency, the binary cannot be resolved. Additionally, the while the dependency refers to libgssapi_krb5.so, current versions are .so.2 and .so.2.2.  The solution is to create a symbolic link to the installed binary as libgssapi_krb5.so to ensure it is resolved.

**Comment by DHowett-MSFT** [comment]
This sounds like it should be on the maintainer of `libgssapi_krb5`. Specifically, it is the library owner's job to provide the non-soname symlink without the version number.

Unless we're shipping that in the PowerShell package, of course.

**Comment by dantraMSFT** [comment]
@DHowett-MSFT You're probably right but I don't see how that addresses the existing installations.  Am I missing something?

**Comment by dantraMSFT** [comment]
This is no longer an issue with OMI 1.4.0 and moving psrp to that version. As part of fixing https://github.com/PowerShell/psl-omi-provider/issues/104, I'll also be moving powershell's dependency to 1.4.0.
