### ISSUE TITLE
ConvertTo/From-SecureString not running under Linux

### ISSUE THREAD

**Issue by redfish0** [PowerShell/PowerShell#4982]
Steps to reproduce
------------------
root@Server1:/home/admin# powershell
PowerShell v6.0.0-beta.7
Copyright (C) Microsoft Corporation. All rights reserved.
PS /home/admin> $Secure = Read-Host -AsSecureString
****
PS /home/admin> $Secure
System.Security.SecureString
PS /home/admin> $Encrypted = ConvertFrom-SecureString -SecureString $Secure
ConvertFrom-SecureString : Unable to load DLL 'CRYPT32.dll': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
At line:1 char:14
+ $Encrypted = ConvertFrom-SecureString -SecureString $Secure
+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-SecureString], DllNotFoundException
    + FullyQualifiedErrorId : System.DllNotFoundException,Microsoft.PowerShell.Commands.ConvertFromSecureStringCommand

```

Expected behavior
-----------------

```No error

```

Actual behavior
---------------

```CRYPT32.DLL is missing, for obvious reasons on Linux, is there a way to handle SecureStrings in Linux ?```

Environment data
----------------

```PS /home/adminr> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.7
OS                             Linux 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@redfish0 Thanks for your report!

It's dup #1654 - fill free to discuss the Issue there.
