### ISSUE TITLE
Online help for new-smbshare not working

### ISSUE THREAD

**Issue by davefoxtrin** [PowerShell/PowerShell#4984]
Steps to reproduce
------------------
running the below command opens a page in IE with a URL http://technet.microsoft.comlibrary/jj635722(v=wps.620).aspx
get-help new-smbshare -online
the '/' is missing from the virtual folder path
```

Expected behavior
-----------------

URL should go to http://technet.microsoft.com/library/jj635722(v=wps.620).aspx

```

Actual behavior
---------------
Page shows incorrect URL
```none

```

Environment data
----------------
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.34014
BuildVersion                   6.3.9600.18773
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

```

**Comment by KexyBiscuit** [comment]
The very first requirement of opening issue is 

> Make sure you are able to repro it on the latest released version.

As your `$PSVersionTable` output shows, you're using a version which is obsolete. Please go to [Releases](https://github.com/PowerShell/PowerShell/releases) to install the latest preview version of PowerShell and try to repro this issue. If the issue still remains, you can edit your post, or this issue will be closed.

**Comment by SteveL-MSFT** [comment]
This is an issue in the SMBShare module which is only shipped inbox on Windows and owned by the SMB team.  It appears that their fwlink redirects to an invalid URL.  I opened an issue here to track: https://github.com/PowerShell/PowerShell-Docs/issues/1712
