### ISSUE TITLE
Remove ImportSystemModules command line parameter

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#4987]
We should remove ImportSystemModules command line parameter because PowerShell Core don't care  about backward compatibility with Windows PowerShell 2.0.

**Comment by iSazonov** [comment]
@mklement0 Could you please help - should we remove anything else here?

**Comment by SteveL-MSFT** [comment]
@iSazonov I have a PR I'm already working on to remove `-sta`, `-mta`, FileConsole code, font changing code, and removing `#if CORECLR`.  I can also remove ImportSystemModules in the same PR.
