### ISSUE TITLE
Commands fail when cd to a file share on windows

### ISSUE THREAD

**Issue by roberocity** [PowerShell/PowerShell#4990]
When working on a file share simple commands fail with Cannot find path error message.

Steps to reproduce
------------------

```powershell
cd \\someactual\fileshare\path

ls

rm *.zip

cd ..\another_path
```

Expected behavior
-----------------

```none
Changes working directory to file share path.

Lists the contents of the directory.

Removes any .zip file

Changes directory to another path on the share.
```

Actual behavior
---------------

```none
Changes working directory to file share path.

ls : Cannot find path '\someactual\fileshare\path' because it does not exist.
At line:1 char:1
+ ls
+ ~~
    + CategoryInfo          : ObjectNotFound: (\amcd12f02\devgp\releases\1.dev:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

Same Cannot find path error for all commands.
```

Environment data
----------------

```powershell
> $PSVersionTable


Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.7
OS                             Microsoft Windows 6.1.7601 S
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by KexyBiscuit** [comment]
It does not repro on Windows PowerShell 5.1, but it does repro on PowerShell 6.0.0-beta.7.

**Comment by SteveL-MSFT** [comment]
This doesn't repro for me on Win10 and PSCore6 beta.7.

```powershell
PowerShell v6.0.0-beta.7
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\> cd \\share\scratch\steve
PS Microsoft.PowerShell.Core\FileSystem::\\share\scratch\steve>
```

**Comment by SteveL-MSFT** [comment]
Does the current logged on user have permission to the share and the folder?

**Comment by roberocity** [comment]
Yes, the user has permission to access the share. The user can run utility from a power shell prompt that  reads the files in the directory, manipulates, and saves them again. That works as expected, but the user can't then cd to another folder on the share. 

OS is Windows 7 Enterprise.

**Comment by SteveL-MSFT** [comment]
Ok, there's definitely some regression here.  Although I can `cd` into the folder on the share, `dir` fails saying `\share\scratch\steve` doesn't exist (notice the missing slash from the front)
