### ISSUE TITLE
Install-Module CurrentUser path when Documents is redirected

### ISSUE THREAD

**Issue by lwsrbrts** [PowerShell/PowerShell#4997]
I've redirected my "Documents" location on my PC from C:\Users\name\Documents to D:\Google Drive\My Documents. Yes, the new location is called "My Documents" in this location, the point is that I've redirected Documents from its default location to here. The CurrentUser scope for Install-Module seems to ignore the special path for my "Documents" location on disk and just goes with the default C:\Users\name\Documents. The side-effect of this is that if I then do an Import-Module by name, even immediately after installing the module using -Scope CurrentUser, the module isn't found in the module path....because Install-Module didn't put the module in the folder for my module path.

Steps to reproduce
------------------
```powershell
Install-Module -Name AzureRM -Scope CurrentUser
```

Expected behavior
-----------------
Should install the named module(s) in to the correct user module path - in my case D:\Google Drive\My Documents\PowerShell\Modules
```none

```

Actual behavior
---------------
Installs the AzureRM modules in to C:\Users\name\Documents\PowerShell\Modules - the directory is created.
```none

```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.7
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

> $env:PSModulePath
D:\Google Drive\My Documents\PowerShell\Modules;C:\Program Files\PowerShell\Modules;c:\program files\powershell\6.0.0-beta.7\Modules
```

**Comment by SteveL-MSFT** [comment]
Thanks for the bug report, but can you open it here: https://github.com/powershell/powershellget/issues
