### ISSUE TITLE
scriptfileinfo psprivatedata is not consistent with module manifests

### ISSUE THREAD

**Issue by mgreenegit** [PowerShell/PowerShell#5003]
The current implementation of New/Test-ScriptFileInfo creates a PSPrivateData section that accepts a string value.  Module manifests accept a hashtable of values.  For consistency, these should be the same.

**Comment by SteveL-MSFT** [comment]
@mgreenegit can you open the issue here?  https://github.com/powershell/powershellget/issues

Thanks!
