### ISSUE TITLE
Feature: Windows Installer to offer option of context menu to open PowerShell in explorer

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#5012]
As a user, I often want to start PowerShell in the current directory in which I am browsing in explorer.exe.
Being able to have a context menu so that I can just right click and select `Open PowerShell here` or `Open PowerShell as Admininstrator` here would be very useful. Although a user can setup this manually via the Windows registry (see e.g. [here](https://www.howtogeek.com/165268/how-to-add-open-powershell-here-to-the-context-menu-in-windows/)), this is a tedious process that is often not worth the effort and therefore should rather be replaced by an option in the installer.
What do you think?

**Comment by SteveL-MSFT** [comment]
I think if you can make it a checkbox in the installer, then it seems like a great feature.

**Comment by xee5ch** [comment]
I have been meaning to learn about WiX for years now, and a quick examination shows this is a WiX-based installer.  Can I take a stab at this?

**Comment by bergmeister** [comment]
Yes, it is a WiX based installer. I have not started on it yet, so feel free to give it a try and also ask questions. It is very easy to build via this PowerShell function [here](https://github.com/PowerShell/PowerShell/blob/master/build.psm1#L1802) and you do not even need to build the whole project, you could just point the `-ProductSourcePath` parameter to a bin folder of a dummy project as long as it contains a file named `powershell.exe`
What you will need to do is basically creating and setting registry entries, which means that this action needs to happen in the part where the installer runs with elevated rights, i.e. you will probably need to create a new dialogue with 2 checkboxes. Note that the example link that I have given at the top uses `HKEY_CLASSES_ROOT` but it might be better to use the `HKEY_CURRENT_USER`. In terms of registry entries, I found that 2 entries need to be added:
- One in the `Directory\Background` folder to enable the context menu when right clicking any where in explorer
- Another one in `Directory\shell` to enable the context menu when right clicking on a specific folder
The syntax between the 2 will slightly differently
You will find that there are already folders named `Powershell` of `Windows PowerShell` in the registry so you will need to come up with a folder name, so maybe `PowerShellCore6`? Since the installer does not allow side by side installation any more, a version number is not needed at the moment but it might be better since this might change in the future.,

**Comment by SteveL-MSFT** [comment]
@xee5ch consider this yours!  I've assigned it to myself as GitHub won't allow me to assign it to you, but I don't want other people duplicating your work.

**Comment by xee5ch** [comment]
Ok.  Not sure on the ETA.  I am newbish to Powershell, love what's being done, and need to review how to get the registry keys for the context menu (I know that part) but need to figure WiX and how to get that together.

Hopefully will be back in the next few days with something passable.  Thanks for the more welcome.

**Comment by xee5ch** [comment]
And just saw your comments, @bergmeister.  Apparently, you did all the research for me.  That will cut down turnaround time.

**Comment by SteveL-MSFT** [comment]
@xee5ch don't worry about rushing it.  We'll keep having ~3 week releases (even after 6.0.0 final), so it'll get into a release eventually :)

**Comment by xee5ch** [comment]
Roger that.  But the likes of you all throwing pointers in my direction so quickly will motivate me to be good about this.

**Comment by bergmeister** [comment]
@xee5ch : Are you still interested in doing this? If you want to we could also do it together as I found out today that with some of the new changes, it has become more difficult to compile in a local dev environment (I had to make some local hacks in order to use `New-MSIPackage` locally.

**Comment by bergmeister** [comment]
I have created a new dialogue with 2 checkboxes for this feature in my branch [here](https://github.com/bergmeister/PowerShell/tree/wix_explorerExtension) since this is the first custom dialogue and therefore required some WiX heavylifting. All one would need to do is setting the registry keys and wiring the action up to those 2 new checkboxes.
@SteveL-MSFT : Below is a screenshot of the dialogue, which comes after the installation directory dialogue. Any thoughts on the preferred wording/design? In theory I could add those checkboxes to the installation directory dialogue but I wanted to keep it rather separate.
![2017-11-05 12_31_01-powershell-1 2 3 4 setup](https://user-images.githubusercontent.com/9250262/32414977-75d2c4b4-c229-11e7-9209-4704af323a67.png)
Also, would you mind if I add something like a `-DevBuild` switch to `New-MSIPackage` because at the moment I have comment out some non-functional stuff to build it locally (the culprits are `Start-NativeExecution` and `Get-PackageSemanticVersion`).

**Comment by xee5ch** [comment]
I did mean to continue work on this. Sorry for the delayed reply. I needed to set up Windows VMs for this and that became an issue.  I will start work on this again.

**Comment by bergmeister** [comment]
No worries, I suggest you also downstream the latest changes from master in your fork (see [here](https://gist.github.com/CristinaSolana/1885435) on how to do that) and then cherry-pick my commit [here](https://github.com/bergmeister/PowerShell/commit/46966954264bfa0f11d73cc18a0b5b9f315a2511) to get the new dialogue.

**Comment by xee5ch** [comment]
Thanks for the help. I will definitely cherry pick as described.

**Comment by bergmeister** [comment]
Great. For an explanation of what I have done see [here](http://www.dizzymonkeydesign.com/blog/misc/adding-and-customizing-dlgs-in-wix-3/). This link will also be useful to you because you can take the 2nd code block in the section `Adding a checkbox to conditionally install a desktop shortcut` as a base example for your work.

**Comment by SteveL-MSFT** [comment]
@bergmeister I thought the original ask is a checkbox like:

```markdown
- [  ] add PowerShell Core to Context Menu
```

Where the context menu in Explorer would have the two options:

```none
Open PowerShell Core here
Open PowerShell Core as administrator here
```

**Comment by bergmeister** [comment]
@SteveL-MSFT I was thinking of offering the user the choice but if you prefer only one checkbox that includes admin and nonadmin then that's of course fine as well.

**Comment by SteveL-MSFT** [comment]
@bergmeister apologies, I misread your screenshot.  Since Windows doesn't have `sudo`, I think users will typically want/need both admin and non-admin.

**Comment by bergmeister** [comment]
@xee5ch Just replace the call to `Get-SemanticVersion` inside the function with a hard coded value because for local testing the value does not matter.

**Comment by bergmeister** [comment]
@xee5ch I also had a look at your screenshot (tip: in Github you can just drag and drop an image into the textbox and Giyhub will integrate and host the image for you) and some other parameters are wrong as well: the productsourcepath is the publish folder that it tells you after Start-psbuild and the licencefilepath must be the path to the licence.rtf file

**Comment by xee5ch** [comment]
Thanks, @bergmeister, I updated the comment for posterity, since I was in a rush and I know imgur stuff goes away quickly.  I was reading the help strings and had not thought much about the other docs, I should have git-grep'ed for some pointers.

I will stuff the `Get-SemanticVersion` function with a hard-coded value.  Perhaps I will work on that when I finish this, re developer friendly.  I know I need to finish this because I have been taking my sweet time.

**Comment by bergmeister** [comment]
@xee5ch Could you manage to compile the MSI? I came home only today, so I can give you some more straightforward copy-pastable instructions to build an MSI locally for the current latest state of master  (with bogus versioning but for the purpose of local development and testing this does not matter):
As I said , first replace the call to `Get-PackageSemanticVersion` [here](https://github.com/PowerShell/PowerShell/blob/master/build.psm1#L1965) with something like `1.2.3.4`:
```powershell
$ProductSemanticVersion = '1.2.3.4' # Get-PackageSemanticVersion -Version $ProductVersion
```
Then
````powershell
cd $PathToYourLocalGitRepoFolder
Import-Module .\build.psm1
Start-PSBuild
New-MSIPackage -ProductSourcePath '.\src\powershell-win-core\bin\Debug\netcoreapp2.0\win7-x64\publish' -LicenseFilePath .\assets\license.rtf -ProductVersion '5.6.7' -AssetsPath .\assets\ -ProductTargetArchitecture x64 -Force
````
Please remember to update your Git repo/branch to the latest version due to recent changes (your forks is weeks behind but maybe you just haven't pushed yet?)

P.S. Do not feel pressured to finish it just because of your initial interest, I can easily finish it as well if you don't want any more for whatever reason (difficult, time, etc.). The fact that it is difficult to get started on WiX here is definitely not your fault, sorry for that for that.

**Comment by xee5ch** [comment]
Sorry I was busy yesterday.  I was unable to finish before I slept and I
did not get to it before I had to step out after all.  I am trying this
now.

I appreciate how persistent you are being.  Apologies for my slow
response times.

**Comment by bergmeister** [comment]
@xee5ch Are you still interested/motivated in doing that (since I cannot see any work on your fork)? Do not feel pressured to do so just because you signed up for it initially. I'd be OK to finish it off myself otherwise since I myself proposed/requested this feature.

**Comment by xee5ch** [comment]
My gosh, so sorry.  Yes, I shall work on this during the remainder of the weekend.  Thanks for reminding me.

**Comment by bergmeister** [comment]
@xee5ch I appreciate your persistent motivation but there has simply been no progress at all in the last 3 months and there is not even a single commit or update in your fork. Since I created this issue originally because I would find this very useful, I will finish it off with a PR now. Your original intent was to learn about WiX so feel free to watch the PR and ask any question that you have. Otherwise there are still issues 5705, 5597, 5226, 2881 and 3341 open that are all to do with `WiX` if you really want to give it a go.

**Comment by bergmeister** [comment]
@SteveL-MSFT The PR got merged so I guess we can close this one?
