### ISSUE TITLE
git stash list 2>$null crashes PowerShell Beta.7

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShell#5014]
Windows 10 CU, PowerShell Core Beta.7, Git 2.14.2.windows.1.

This crash seems to be new and specific to Git 2.14.2.

Steps to reproduce
------------------

```powershell
git stash list 2>$null
```

Expected behavior
-----------------
Git errors or maybe git.exe crashes but PowerShell should not crash.

Actual behavior
---------------
PowerShell crashes.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.7
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

FWIW I can crash cmd.exe to with `git stash list 2>nul`.

Related https://github.com/dahlbyk/posh-git/issues/493

**Comment by lzybkr** [comment]
This looks like a git/cygwin issue, repros in cmd as well.

**Comment by rkeithhill** [comment]
Agreed. I've been trying to figure out how to submit this to Git but my email address was rejected:
```
vger.kernel.org gave this error:
Hello [40.92.10.72], for your MAIL FROM address <blah-blah@hotmail.com> policy analysis reported: Your address is not liked source for email 
```
Kinda judgmental if you ask me. :-)

**Comment by SteveL-MSFT** [comment]
This doesn't appear to be an exception that PowerShell can catch.  It seems to be crashing the console due to some threading issue.  I think the best option is to open an issue here: https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo

**Comment by lzybkr** [comment]
@SteveL-MSFT - this is not a crash - powershell/cmd is still running, but cygwin is hiding the wrong window so it looks like it was a crash.

**Comment by SteveL-MSFT** [comment]
@lzybkr that explains why I couldn't get windbg to break
