### ISSUE TITLE
Suggestion: Add #Requires -Assembly AssemblyName support

### ISSUE THREAD

**Issue by brianary** [PowerShell/PowerShell#5022]
Currently, if I want to reference a .NET assembly like System.Configuration, I do something like this at the top of [my scripts](https://github.com/brianary/scripts "context for this usage"):
```powershell
try{[void][Configuration.ConfigurationManager]}catch{Add-Type -AN System.Configuration}
```
it would be much more readable (and declarative) as something like:
```powershell
#Requires -Assembly System.Configuration
```

**Comment by PetSerAl** [comment]
Why do you put `Add-Type` in `catch`? You could also put `using assembly System.Configuration` on top of script.

**Comment by JasonG-STCU** [comment]
I, too, have used this in a script of mine. It would absolutely be beneficial to be able to include it this way.

**Comment by brianary** [comment]
@PetSerAl I wasn't aware of the [`using`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_using?view=powershell-5.1) keyword, though I don't see `assembly` documented as argument to it. Also, our servers are not uniformly on PowerShell 5 just yet, so that extended syntax isn't something we can fully rely on yet (my workstation is stuck on version 5.0.10105.0-April2015Preview which doesn't support `using assembly`, and I'm unable to upgrade or downgrade or uninstall it from Windows 7). It seems odd to have _another_ thing that must come first in the script, along with `[CmdletBinding()]Param(…)`. It looks like `using` *must* precede `[CmdletBinding()]Param(…)`.

The reason I use the above formulation is to `Add-Type` only if referencing the type causes an exception, that way I'm only adding it once per session.

**Comment by PetSerAl** [comment]
> The reason I use the above formulation is to `Add-Type` only if referencing the type causes an exception, that way I'm only adding it once per session.

You can not load same assembly twice anyway. No harm on calling `Add-Type` for already loaded assembly.
```powershell
$a = Add-Type -AssemblyName System.Configuration -PassThru | Select-Object -First 1 -ExpandProperty Assembly
$b = Add-Type -AssemblyName System.Configuration -PassThru | Select-Object -First 1 -ExpandProperty Assembly
[Object]::ReferenceEquals($a, $b)
```

**Comment by brianary** [comment]
I'll have to look into the `using` syntax (I hope it gets added to the docs, and is officially supported) once I can finally upgrade things and get the new features.

However, even on a newer machine, there's a pretty big performance difference:
```
PS C:\Users\me> "$(Measure-Command {0..10000|% {iex 'using assembly System.Configuration'}})"
00:00:08.2655849
PS C:\Users\me> "$(Measure-Command {0..10000|% {Add-Type -AN System.Configuration}})"
00:00:04.6386843
PS C:\Users\me> "$(Measure-Command {0..10000|% {try{[void][Configuration.ConfigurationManager]}catch{Add-Type -AN System.Configuration}}})"
00:00:00.0728870
```
on my older machine, it's even bigger:
```
PS C:\Users\me> "$(Measure-Command {0..10000|% {Add-Type -AN System.Configuration}})"
00:00:08.1306933
PS C:\Users\me> "$(Measure-Command {0..10000|% {try{[void][Configuration.ConfigurationManager]}catch{Add-Type -AN System.Configuration}}})"
00:00:00.2983187
```

**Comment by rjmholt** [comment]
I've opened [an RFC](https://github.com/PowerShell/PowerShell-RFC/pull/122) on updating the behaviour of `#requires`. Please feel free to comment in the PR.
