### ISSUE TITLE
New RPM package doesn't work for AmazonLinux

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#5027]
We have a dockerfile for AmazonLinux (docker/release/amazonlinux), and I found this when validating docker files. It turns out that AmazonLinux doesn't have the package `openssl-libs`.

**Comment by daxian-dbw** [comment]
@SteveL-MSFT Amazon Linux is not an officially supported distro for .NET Core 2.0 (see https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0-supported-os.md#linux). Do we need to support it?

**Comment by SteveL-MSFT** [comment]
No, it's not one we officially support either.

**Comment by daxian-dbw** [comment]
OK, I will remove the dockerfile then.

**Comment by iSazonov** [comment]
Could we document PowerShell Core package dependences to help users to install PowerShell on unsupported distributives?

**Comment by r2690698** [comment]
Hello @SteveL-MSFT  and @daxian-dbw  just hit this issue myself on AWS linux, this was working fine a few days ago. do you have any recommendations to address the dependency issue of openssl-libs ? i realy realy realy dont want to change to a different distro so any help to get this working again would be awesome. (PS support AWS linux ;) )

**Comment by SteveL-MSFT** [comment]
@r2690698 just to be clear, I want to enable running PSCore6 on as many systems/devices as possible, but we can only officially support what dotnetcore supports.  For other platforms, we'll make a best effort (community support like for ArchLinux is always appreciated!).

**Comment by daxian-dbw** [comment]
The powershell package dependencies are the same as those of `dotnet-runtime-2.0.0` packages (DEB, RPM) (available at [here](https://packages.microsoft.com)). You can find the dependencies in the PR description of #4902. Or better, look at the source of truth in `New-UnixPackage` from [packaging.psm1](https://github.com/PowerShell/PowerShell/blob/master/tools/packaging/packaging.psm1#L450).

The RPM package of `dotnet-runtime-2.0.0` depends on `openssl-libs` and thus cannot be installed through `yum install` on Amazon Linux.
However, the dotnet team provide a [`.tar.gz` package](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.0-download.md) of `dotnet-runtime-2.0.0` for users to deploy, similar to the `.zip` package for windows. I think powershell should also provide a `.tar.gz` package for users to use on not officially supported distros. I will add this task to #3961.
