### ISSUE TITLE
Windows MSI beta.8 pkg on Windows 10 requires VC++ runtime redist

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#5029]
The installer didn't require this previously (beta.7) on Win10 but now it does.  We should revisit the dependency check in the msi.

**Comment by daxian-dbw** [comment]
This issue causes docker build for windows server core (docker/release/windowsservercore) to fail.

**Comment by iSazonov** [comment]
Did it come after adding new icon?

**Comment by SteveL-MSFT** [comment]
@iSazonov I think it was #4745

**Comment by iSazonov** [comment]
Thanks! Clear - we don't check OS version.

**Comment by iSazonov** [comment]
I think better check Universal runtime.

**Comment by daxian-dbw** [comment]
The check for `ucrtbase.dll` is to make sure Univeral C Runtime is available.
