### ISSUE TITLE
v6-beta.8: Potential regression of Remove-Item with wildcards and missing items

### ISSUE THREAD

**Issue by nightroman** [PowerShell/PowerShell#5031]
In all previous PowerShell versions (from v2 to v6-beta.7) `Remove-Item`
ignores missing items if they are specified by wildcards, i.e.

```powershell
Remove-Item [z] -Force -Recurse
Remove-Item z.* -Force -Recurse
```

work fine if `z` or `z.*` is missing.

In v6-beta.8 the above commands fail.

Is this by design or a regression?

```
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta.8
PSEdition                      Core
GitCommitId                    v6.0.0-beta.8
OS                             Microsoft Windows 10.0.10586
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by nightroman** [comment]
The change https://github.com/PowerShell/PowerShell/pull/4866 says

> This means that using -literalpath with an asterisk and the filesystem provider will now return an error rather than returning quietly.

This is probably fine for `-literalpath`, using wildcards with it looks like a user error.

But with `-path` wildcards are rather expected and may point to missing items.

**Comment by nightroman** [comment]
NB: new failure `remove-item -LiteralPath z.*` (which looks reasonable) is not consistent with `get-item -LiteralPath z.*` which still ignores wildcards.

**Comment by SteveL-MSFT** [comment]
@nightroman can you open a separate issue for `Get-Item -LiteralPath`?  `-Path` behavior shouldn't have changed, will look into this.

**Comment by nightroman** [comment]
> can you open a separate issue for Get-Item -LiteralPath?

https://github.com/PowerShell/PowerShell/issues/5057
