### ISSUE TITLE
Beta.8 - Installation not removing previous version (Beta.7)

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#5040]
Seems like. after doing 'Update-Help -force' in previous version, it won't remove the previous folder because of the *HelpInfo.xml files.

Steps to reproduce
------------------
Open File Explorer and search inside the C:\Program Files\PowerShell\6.0.0-beta.7

Expected behavior
-----------------
To remove previous version.
```none

```

Actual behavior
---------------
Previous version folder is not removed.
```none

```

Environment data
----------------
Windows 10 Insider Build 16299.15

```powershell
PS C:\Program Files\PowerShell\6.0.0-beta.8> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta.8
PSEdition                      Core
GitCommitId                    v6.0.0-beta.8
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
![pscore_notremovingfiles_2017-10-06_16-26-24](https://user-images.githubusercontent.com/19892435/31297559-6c3e1124-aab4-11e7-8e5b-e001ff92f713.png)

**Comment by SteveL-MSFT** [comment]
If you did `install-module` (allusers scope) or update-help, it creates files in $PSHOME.  What we should probably do is migrate the modules folder to the new install so you don't have to reinstall those modules or re-update help.

**Comment by MaximoTrinidad** [comment]
Thanks @SteveL-MSFT!  I just didn't realized the Help xml to be an issue.  No worries!
:)

**Comment by TravisEz13** [comment]
Please re-open if you think this is not resolved

**Comment by mi-hol** [comment]
@MaximoTrinidad @TravisEz13 I´m trying to understand why the  same issue would not re-occure when when going from 6.0.0 to 6.1.0.  as from the comments here no commit is linked. Maybe I'm just puzzled please bare with me-

**Comment by MaximoTrinidad** [comment]
@mi-hol ,

This is still happening even when upgrading to 6.1.0-preview.1 from the previous version.

In both Linux and Windows OS, the installation is still leaving the previous 6.x.x folder due to the xxx_HelpInfo.xml files in the main folder: C:\Program Files\PowerShell\6.x.. .

So, I ended up manually removing the previous version folders.

I think the installation should detect the older version, check for installed module (not core) and give the option to be remove.  It should be a clean installation.

:)

**Comment by TravisEz13** [comment]
> This is still happening even when upgrading to 6.1.0-preview.1 from the previous version.

`6.1.0-preview.1` is an SxS install, not an upgrade.
> In both Linux and Windows OS, the installation is still leaving the previous 6.x.x folder due to the xxx_HelpInfo.xml files in the main folder: C:\Program Files\PowerShell\6.x.. .

As mentioned, it is by design to leave the folder behind if the user has data left in the folder.  There was a change to update-help to save the help data in the user folder by default.

**Comment by MaximoTrinidad** [comment]
My Apologies!!!

I meant to say "Uninstalling" the previous version won't remove all folders, which I think it should cleared everything before installing the latest.

Sorry!
:)

**Comment by MaximoTrinidad** [comment]
Of course! If it is By-Designed!  Then, feel free to close this issue.

But, I still think is an unnecessary step to always go back and manually remove all folders. You will always be updating the help and reinstalling modules. 

To me it doesn't make any sense.

:)

**Comment by SteveL-MSFT** [comment]
@MaximoTrinidad I think this should no longer be an issue after we implement this [rfc](https://github.com/PowerShell/PowerShell-RFC/pull/115)

**Comment by MaximoTrinidad** [comment]
Aweesome @SteveL-MSFT !

Thanks
:)
