### ISSUE TITLE
broken redhat download link in readme.md

### ISSUE THREAD

**Issue by organicit** [PowerShell/PowerShell#5042]
Steps to reproduce
------------------

```
click on the rpm download link for RHEL 7
```

Expected behavior
-----------------

```
should begin rpm download 
```

Actual behavior
---------------

```
Page returns a 404 not found
```

Environment data
----------------

```powershell
NA

```

**Comment by SteveL-MSFT** [comment]
@daxian-dbw can you fix this?

**Comment by daxian-dbw** [comment]
Sure, right away.
