### ISSUE TITLE
Unable to install powershell on MacOS without root access (brew)

### ISSUE THREAD

**Issue by ssbarnea** [PowerShell/PowerShell#5049]
It seems that at this moment root/admin access is needed in order to install powershell on MacoS.

This is an issue for two reasons:
- a shell should not need admin to be installed (i installed zsh, fish, tcsh, ...) without needing admin
- prevents automation and CI usage, like on Travis

Steps to reproduce
------------------
Follow install instructions and do:

```
brew cask install powershell
```

Expected behavior
-----------------

```
Succeeding installation without prompting for root/admin password
```

Actual behavior
---------------

```
==> Caveats
A OpenSSL-backed libcurl is required for custom handling of certificates.
This is rarely needed, but you can install it with
  brew install curl --with-openssl
See https://github.com/PowerShell/PowerShell/issues/2211

==> Satisfying dependencies
All Formula dependencies satisfied.
==> Downloading https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-beta.8/powershell-6.0.0-beta.8-osx.10.12-x64.pkg
Already downloaded: /Users/ssbarnea/Library/Caches/Homebrew/Cask/powershell--6.0.0-beta.8.pkg
==> Verifying checksum for Cask powershell
==> Uninstalling Cask powershell
==> Running uninstall process for powershell; your password may be necessary
==> Uninstalling packages:
==> Installing Cask powershell
==> Running installer for powershell; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
```

Environment data
----------------
MacOS High Sierra (10.13)

**Comment by iSazonov** [comment]
@ssbarnea Could you please check with latest builds?

**Comment by ihnorton** [comment]
Issue still exists
```
==> Satisfying dependencies
All Formula dependencies satisfied.
==> Downloading https://github.com/PowerShell/PowerShell/releases/download/v6.2.1/powershell-6.2.1-osx-x64.pkg
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/49609581/91aceb00-7bb0-11e9-8431-4cc0dbb1f141?X-Amz-Algorithm=AWS4-HMAC
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'powershell'.
==> Installing Cask powershell
==> Running installer for powershell; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
```

**Comment by ihnorton** [comment]
Appears to be related to https://github.com/PowerShell/PowerShell/issues/5634

**Comment by iSazonov** [comment]
@TravisEz13 Is the issue important for 7.0 release?

**Comment by TravisEz13** [comment]
This is by design… Please use the tar.gz if you want to install without admin access.

**Comment by TravisEz13** [comment]
@ssbarnea Feel free to create another cask which used the tar.gz

**Comment by TravisEz13** [comment]
We could build a formula if it was in our own repo.  Would that work?
I have a prototype in my personal repo: https://github.com/TravisEz13/Homebrew-PowerShell

**Comment by wesdgray** [comment]
using the tar.gz does not work because Mac blocks it from being opened because it cannot check it for malicious software. In order to run anyways you need root.
