### ISSUE TITLE
Powershell Core is unable to enumerate module with casing differences, install-module silently fails

### ISSUE THREAD

**Issue by trondhindenes** [PowerShell/PowerShell#5050]
Steps to reproduce
------------------
Given a Powershell module where the module "name" is Testtest and the psd1 manifest file is named TestTest (notice casing differences), Powershell Core simply disregards the module. This is fine in most cases, but if using Install-Module to install a module with this error from a nuget feed, the install silently fails, instead of reporting the error. 

When using verbose logging with Install-Module the last line logged is:
```powershell
install-module Testtest -Scope CurrentUser -Verbose
<snipped>
VERBOSE: InstallPackageLocal' - name='Testtest', version='1.0.8',destination='/tmp/1267197911'
```

Expected behavior
-----------------
The last line of the verbose output of a successfully installed package seems to be:

```powershell
VERBOSE: Module 'TestTest' was installed successfully to path '/home/ubuntu/.local/share/powershell/Modules/TestTest/1.0.10'
```

In any situation where Install-Module does not complete with the successful installation of a module, the cmdlet should at least write an error to the console.

Since Windows and Linux have very different handling of casing in files and paths, it would (imho) make sense to build some "robustness" into Powershell to deal with this, for instance by printing warnings/errors when there are discrepancies between casing in a module path and it's name (from the manifest). There are tons of things that could be done in order to improve the overall robustness of case-handling in regards to modules etc.

**Comment by SteveL-MSFT** [comment]
@trondhindenes thanks for reporting this issue, but can you cut and paste it over here? https://github.com/powershell/powershellget/issues

Thanks!
