### ISSUE TITLE
Azurecli is not working

### ISSUE THREAD

**Issue by ajithkt** [PowerShell/PowerShell#5060]
After installing the Azure module and while trying to import the module we are getting the below error. Please help us here.

Install-Module Azure -AllowClobber          

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its 
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from 
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
PS /Users/ajithkt/Desktop/bin> Import-Module Azure                         Import-Module : Could not load type 'System.Management.Automation.PSSnapIn' from assembly 'System.Management.Automa tion, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.                                           At line:1 char:1                                                                                                    + Import-Module Azure                                                                                               + ~~~~~~~~~~~~~~~~~~~                                                                                                   + CategoryInfo          : NotSpecified: (:) [Import-Module], TypeLoadException                                      + FullyQualifiedErrorId : System.TypeLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by markekraus** [comment]
The Azure module uses PSSnapins which are no longer supported in PowerShell Core ([more info](https://github.com/PowerShell/PowerShell/blob/master/demos/WindowsPowerShellModules/README.md#windows-powershell-vs-powershell-core)). To use the Azure modules in core, you need to use their Core compatible version, such as [AzureRM.NetCore](https://www.powershellgallery.com/packages/AzureRM.Netcore/).

**Comment by iSazonov** [comment]
We have https://github.com/PowerShell/PowerShell/blob/3a960db5b0a61e0e797fbcaa3f61b06c87d92aff/demos/Azure/README.md

**Comment by ajithkt** [comment]
Thanks a lot guys for your guidance.
