### ISSUE TITLE
Travis CI macOS Builds are failing

### ISSUE THREAD

**Issue by markekraus** [PowerShell/PowerShell#5062]
It appears something has changed, possibly external, and all of the macOS builds are failing (including nightly)

```none
./installpsh-osx.sh: line 99: [: missing `]'

\n*** Installing PowerShell Core for osx...

Howebrew is already installed, skipping...

Installing cask...

Updating Homebrew...

==> Downloading https://homebrew.bintray.com/bottles-portable/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz

######################################################################## 100.0%

==> Pouring portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz

/usr/local/Homebrew/Library/Homebrew/brew.rb:12:in `<main>': Homebrew must be run under Ruby 2.3! (RuntimeError)

ERROR: Cask failed to install! Cannot install powershell...

The command "./install-powershell.sh" failed and exited with 2 during .
```

examples: 

- https://travis-ci.org/PowerShell/PowerShell/jobs/285387333
- https://travis-ci.org/PowerShell/PowerShell/jobs/285471140
- https://travis-ci.org/PowerShell/PowerShell/jobs/285293168
- https://travis-ci.org/PowerShell/PowerShell/jobs/285388460 (nightly)

Also, the nightly badge for Travis CI macOS reports success when it clearly failed.

**Comment by SteveL-MSFT** [comment]
I'm looking into this.  The badge caching is also still an issue.

**Comment by mcarlucci** [comment]
+1

**Comment by benapetr** [comment]
Hello,

How did you fix this? Our project has same issue.

**Comment by mcarlucci** [comment]
@benapetr Homebrew always uses the system Ruby, so it likely started with Ruby 2.0.0, installed the vendored Ruby 2.3.3, but then didn't use the vendored Ruby the first time.

In the interim and until this is specifically addressed by Homebrew or Travis CI, I fixed this by passing the no-auto-update flag:
```
HOMEBREW_NO_AUTO_UPDATE=1 brew install ...
```

**Comment by SteveL-MSFT** [comment]
@benapetr the main part of the fix was to move `brew update` earlier before using brew

**Comment by benapetr** [comment]
oh, I tried this from your patch in this PR, but maybe brew update would be better option: https://github.com/huggle/huggle3-qt-lx/commit/95267bbff361e11212519a609d8c832a704efb56
