### ISSUE TITLE
Piping by property name only looks at default parameter set if defined

### ISSUE THREAD

**Issue by cormacpayne** [PowerShell/PowerShell#5071]
Steps to reproduce
------------------

Using the following sample cmdlet:

```powershell
function Test-Cmdlet
{
    [CmdletBinding(DefaultParameterSetName = "FooTemp")]
    Param(
        [Parameter(Mandatory = $true, Position = 0, ValueFromPipelineByPropertyName = $true, ParameterSetName = "FooTemp")]
        [Parameter(Mandatory = $true, Position = 0, ValueFromPipelineByPropertyName = $true, ParameterSetName = "FooBar")]
        $Foo,

        [Parameter(Mandatory = $true, Position = 1, ValueFromPipelineByPropertyName = $true, ParameterSetName = "FooBar")]
        $Bar,

        [Parameter(Mandatory = $true, Position = 2, ValueFromPipelineByPropertyName = $true, ParameterSetName = "FooTemp")]
        $Temp
    )

    $PSCmdlet.ParameterSetName
    "Foo = $Foo"
    "Bar = $Bar"
    "Temp = $Temp"
}
```

When attempting to pipe a `PSCustomObject` with `Foo` and `Bar` properties, it throws an error:

```powershell
$hash = @{ Foo = "A"; Bar = "B" }
[PSCustomObject]$hash | Test-Cmdlet

Test-Cmdlet : The input object cannot be bound because it did not contain the information required to bind all mandatory parameters:  Temp
At C:\Users\corm\Documents\TestCmdlet.ps1:29 char:25
+ [PSCustomObject]$hash | Test-Cmdlet
+                         ~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (@{Bar=B; Foo=A}:PSObject) [Test-Cmdlet], ParameterBindingException
    + FullyQualifiedErrorId : InputObjectMissingMandatory,Test-Cmdlet

FooTemp
Foo = A
Bar =
Temp =
```

However, I found that the same command works if I remove the `DefaultParameterSet` from the above cmdlet:

```powershell
$hash = @{ Foo = "A"; Bar = "B" }
[PSCustomObject]$hash | Test-Cmdlet

FooBar
Foo = A
Bar = B
Temp =
```

It appears that if a `DefaultParameterSet` is defined for a cmdlet, then it will try to bind an object's parameters to _only_ the specified `DefaultParameterSet`. In both scenarios, the cmdlet works as intended if I don't use piping:

```powershell
Test-Cmdlet -Foo "A" -Bar "B"

FooBar
Foo = A
Bar = B
Temp =
```

Expected behavior
-----------------

In the piping scenario, PowerShell binds to the same parameter set that it would if the values in the hashtable (or object) were used as parameters.

Actual behavior
---------------

If a `DefaultParameterSet` is defined, PowerShell will only try to bind to the values of the `DefaultParameterSet` and won't look to see if it can successfully bind to the parameters of another set.

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.15063.608
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.608
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by lzybkr** [comment]
It does look like a bug, but I think the description is not quite accurate.

I *think* it's more accurate to say - if a parameter is available in multiple parameter sets **and** one of the parameter sets is the default parameter set, then the alternate parameter sets are not considered.

**Comment by lzybkr** [comment]
BTW, I've marked this for discussion - the parameter binder is extremely complex, and it's possible this behavior is somehow desirable or at least to risky to change.

**Comment by cormacpayne** [comment]
@lzybkr good catch - just confirmed that this only occurs when one of the "candidate" parameter sets is the default parameter set.

**Comment by o-l-a-v** [comment]
Just ran into this same problem now, tested with both 5.1 and 6.2.3.

Function:
`function Test-ParameterSet {
    [CmdletBinding(DefaultParameterSetName='Two')]
    Param (
        [Parameter(Mandatory = $true, ParameterSetName = 'One', Position = 0, ValueFromPipelineByPropertyName = $true)]
        [Parameter(Mandatory = $false, ParameterSetName = 'Two', Position = 0, ValueFromPipelineByPropertyName = $true)]
        [string] $Name,

        [Parameter(Mandatory = $true, ParameterSetName = 'One', ValueFromPipelineByPropertyName = $false)]
        [string] $Location,

        [Parameter(Mandatory = $false, ParameterSetName = 'Two', ValueFromPipelineByPropertyName = $false)]
        [string] $Work
    )

    Process {
        Write-Output -InputObject ('ParameterSetName = {0}' -f ($PSCmdlet.'ParameterSetName'))
    }
}`

![image](https://user-images.githubusercontent.com/6450056/65417469-5fc7c180-ddfa-11e9-8b3c-eef5b7b4d8a5.png)

Is this still being looked into?
