### ISSUE TITLE
Add macOS app to launch PowerShell.

### ISSUE THREAD

**Issue by thezim** [PowerShell/PowerShell#5074]
I've been using [this](https://github.com/thezim/launchpowershell) for awhile now. Would be nice if the installer could install something similar making PowerShell launch-able via Spotlight and dock-able.

**Comment by SteveL-MSFT** [comment]
Would you be willing to contribute that as a PR?

**Comment by thezim** [comment]
Sure, just need to figure where it should go. The app really simple, just a few folders, plist file, shell script, and icns file. A shell script can be used to generate everything except the icns file which we already have. Do you think we should pregen it in repo and package it up or have the package generate it during the install.

**Comment by SteveL-MSFT** [comment]
If the content is pretty static, I don't think we need to generate it every time and we can maybe store it under "assets"?  packaging.psm1 would need to be updated to put this into the macOS package.

cc @TravisEz13

**Comment by TravisEz13** [comment]
@thezim Do you know how to use the xcode commandline to package these assets?

**Comment by thezim** [comment]
@TravisEz13 I do now. I was able to create a package with the following. Tested the package and it works.

```bash
chown -R root:wheel *
pkgbuild --root ROOT --identifier com.mirosoft.powershell --version 1.0 PowerShell.pkg
```
ROOT/PowerShell.app/[remaining files and folders]

Is there an existing identifier/CFBundleIdentifier that should be used? I see `powershell` is used by the standard installer.

**Comment by TravisEz13** [comment]
I think this one should be something like `PowerShell launcher` (not intended to be the exact identifier).   The files probably should go in a folder under `tools/packaging`.    An argument could be made that the icon should be under `assets` and copied during packing.  Add a function which builds the package to `tools/packaging/packaging.psm1` and make sure it's exported in the psd1. (I wrote this in a hurry sorry for any errors.)

**Comment by thezim** [comment]
@TravisEz13 thanks. I'll start on a PR.

**Comment by TravisEz13** [comment]
Thank you.

**Comment by thezim** [comment]
@TravisEz13 Now that I understand the `packaging` module better, do we what this as a separate .pkg file and and exported function? I see only `Start-PSPackage` is exported currently. I have it working now 0283108b3eb7014963a7d7cea71068428b2c66b3 by including the app in the entire package which I thought made sense. Let me know gone in a wrong direction.

**Comment by TravisEz13** [comment]
I think one package is okay.  We can see what feedback we get and see if we need to seperate them.
