### ISSUE TITLE
can not create mutex,why?

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#5077]
In linux,i want create a mutex use my old script,just as in windows.
But $mutex_created allways return $true,
why? where is problem? myself or powershell or .net? please help to see.

reference:
https://docs.microsoft.com/en-us/dotnet/api/system.threading.mutex.-ctor?view=netstandard-2.0

Steps to reproduce 
------------------
in two bash termal run:
powershell -file /powershell/my_mutex.ps1
then two powershell process.

```
$mutexname = 'abcd'
$mutex_created = $flase
$mutex_object = New-Object System.Threading.Mutex ($true,$mutexname,[ref]$mutex_created)
if ($mutex_created)
{
	write-host '互斥成功，开始干活!'
	start-sleep  -Seconds 60 #你的任务
	$mutex_object.ReleaseMutex() | Out-Null
	$mutex_object.Dispose() | Out-Null
	write-host '互斥结束，释放'
}
else
{
	write-host '互斥失败 !'
}
```

Actual behavior
------------------
windows 10 14393 + powershell 5.1:
normal 

centos 7.4 + powershell 6.0 beta8: 
No error, $mutex_created allways $true.

**Comment by markekraus** [comment]
This probably has to do with bash session being treated like separate sessions and the default mutex scope being local to the bash session.

```bash
powershell -file my_mutex.ps1 &
powershell -file my_mutex.ps1
```

Works as you expected in the same bash session. 

If you modify the `$mutexname = 'abcd'` to `$mutexname = 'Global\abcd'` then it will work between 2 different bash sessions.

See the note at the very [end of this document](https://docs.microsoft.com/en-us/dotnet/api/system.threading.mutex.-ctor?view=netstandard-2.0#System_Threading_Mutex__ctor_System_Boolean_System_String_System_Boolean__). It appears to apply to Bash sessions too, thought it doesn't explicitly say it.

**Comment by chuanjiao10** [comment]
yes. thanks!
