### ISSUE TITLE
Where should new ETS stuff go?

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#5079]
That's a bit of a vague question, so let me be specific. I want to add the equivalent of this:

```posh
Update-TypeData -TypeName System.Managment.Automation.ErrorRecord -MemberName ErrorRecord -MemberType ScriptProperty -Value { $this }
```

So that you can *always* write: `$_.ErrorRecord` on _anything_ you can `catch` (and conversely: `$_.ErrorRecord.Exception`) ... because I find it confusing that sometimes I catch an Exception and sometimes an ErrorRecord.

I know that the default types files were turned into C# code, but where is it?

P.S. I'd love to also add `.Exception` to all exceptions, but since ETS doesn't apply to derived types the way extension methods do, I think that's probably not worth it. Which reminds me ... PowerShell *really* needs support for .Net extension methods.

**Comment by iSazonov** [comment]
It is here https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/Types_Ps1Xml.cs

**Comment by fmichaleczek** [comment]
PowerShell really needs support for .Net extension methods !

**Comment by iSazonov** [comment]
#2226 for extension methods.

**Comment by iSazonov** [comment]
@Jaykul  Can we close the Issue?
