### ISSUE TITLE
Ambiguous types by namespace can not be resolved by using directive

### ISSUE THREAD

**Issue by Alextocode** [PowerShell/PowerShell#5088]
Hello community, 

I am facing an issue when working with using namespace directive in PowerShell.
I would like to use the Timezone implementation of Java.Util for a small project and therefore work with IKVM, what is meant to be a .net Implementation of Java providing various assembly files (.dll)

I have the following:

```
[System.reflection.assembly]::unsafeLoadFrom("IKVM.OpenJDK.Core.dll")
[System.reflection.assembly]::unsafeLoadFrom("IKVM.OpenJDK.Util.dll")
```

So far so good.

Now I am trying do to this in first line

`using namespace Java.Util`

Actually I  am good here as well, but now I would like to do the following:

`([TimeZone]::getAvailableIDs())  |  { Write-Host $_}`

It won't let me do since in PowerShell I have an implicit "using System" directive in source code, causing that it will be ambiguous with System.TimeZone

It is no problem whenn calling [Java.Util.Timezone] instead but this makes the using directive being redundant.

Probably my issue is that I can't do an alias for my namespace. 
In C# it would be something like using (namespace) JavaTimezone = Java.Util.Timezone

Does similar exist for PowerShell? If not I would like to add it as a feature suggestion.

P.S: In general I am quite unhappy with being the using directive not very well documented. I believe there do also things exist like "using type" and "using assembly", but there is no documentation about it.
Why is that? I'd be glad to use this stuff :)

**Comment by rkeithhill** [comment]
It would be nice in this scenario if PowerShell supported something like C# `global::TimeZone`.  Perhaps `[::Timezone]` or `[global:TimeZone]` or something to indicate to PowerShell it shouldn't prefix w/ `System.` and lookup the type.

**Comment by lzybkr** [comment]
It would be a breaking change now, but we probably should have not have the implicit `using namespace System` if you have *any* `using namespace` statements.

We don't have support for type aliases yet, but the intent was to support `using type TimeZone = Java.Util.TimeZone` - in fact the parser supports this today, but the semantic aspect was never implemented.

**Comment by Alextocode** [comment]
> It would be a breaking change now, but we probably should have not have the implicit using namespace System if you have any using namespace statements.

I believe in general this is a good idea, since it would make it equivalent to C# functionality.
However it will likely not receive this issue, since System namespace is very likely used in almost any .NET code. I am note a professional developer so I can not really estimate it, but maybe it might make sense that compiler can dynamically recognize the correct class by called method / property name? ...however would probably not really work if accidentally both classes have a property or method with same name.
So I think it should be made as the classical concept of namespace aliases to resolve name conflicts.

> We don't have support for type aliases yet, but the intent was to support using type TimeZone = Java.Util.TimeZone - in fact the parser supports this today, but the semantic aspect was never implemented.

But sounds quite neat at all. Thumbs up for this. Is PowerShell actually under active development? I can't find information about a planned release, for instance 5.2. I believe that Microsoft released PowerShell core to OpenSource community, but I am not sure.
Does something like a roadmap for PowerShell exist? :)

**Comment by lzybkr** [comment]
Here is the current [roadmap](https://blogs.msdn.microsoft.com/powershell/2017/07/14/powershell-6-0-roadmap-coreclr-backwards-compatibility-and-more/)

**Comment by Alextocode** [comment]
@lzybkr 
Thank you very much Jason. I will read carefully.
