### ISSUE TITLE
[Proposal] Set-AuthenticodeSignature add timestamp hash algorithm parameter

### ISSUE THREAD

**Issue by LarinLive** [PowerShell/PowerShell#5092]
Now cmdlet Set-AuthenticodeSignature always produce time stamp request with obsolete SHA-1 algorithm. Please add the parameter **TimestampHashAlgorithm** what will specify a desired tsp hash algorithm. Same functionality presents in **signtool.exe** tool with **/td** parameter

Thanks
Anton

**Comment by iSazonov** [comment]
It is not trivial. The timestamp process is described in [Implementation Details and Wire Format](https://msdn.microsoft.com/en-us/library/windows/desktop/bb931395(v=vs.85).aspx).
[SignerTimeStampEx2](https://msdn.microsoft.com/en-us/library/windows/desktop/dd418879%28v=vs.85%29.aspx)

**Comment by AntonPlotnikov** [comment]
I think that it is not so complex. Just add selection of digest function (SHA-1, SHA-256, SHA-384, SHA-512 or SHA-3). All other CMS operations won't be changed

**Comment by TravisEz13** [comment]
Security working group: agree that this is a feature we should do.  Triaging to future to allow some community member to pick this up.

**Comment by AntoineLarine** [comment]
PS team, any news?
