### ISSUE TITLE
Define Uniform Type Identifier for macOS install package.

### ISSUE THREAD

**Issue by thezim** [PowerShell/PowerShell#5103]
The macOS install package should adopt a proper [Uniform Type Identifier (UTI)](https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/understanding_utis/understand_utis_conc/understand_utis_conc.html#//apple_ref/doc/uid/TP40001319-CH202-CHDHIJDE). Current this is just `powershell`. `fpm` offers a `--osxpkg-identifier-prefix` which would add a reverse domain such as `com.microsoft`, final UTI would be `com.microsoft.powershell`. Perhaps even the suffix should be different, e.g powershellcore.

/cc @TravisEz13

**Comment by TravisEz13** [comment]
Marked as high priority, this probably should be fixed for the release.

**Comment by SteveL-MSFT** [comment]
What is the impact if we don't take this for 6.0.0?

**Comment by TravisEz13** [comment]
If I understand correctly, when we change it, the old and new package can be installed side-by-side.

**Comment by thezim** [comment]
@SteveL-MSFT I would have to agree with @TravisEz13 but we should do some testing to ensure that is the case. The desire is to have 6.0 have fixed UTI for its lifecycle, whether that is the existing `powershell` or a new UTI. If the UTI was change post release then updates and bug fixes get installed as side by side. I wouldn't think that is the desired experience. An update/bug fix should replace the existing installation.

**Comment by SteveL-MSFT** [comment]
@thezim thanks for the details, we should fix this for RC then
