### ISSUE TITLE
Investigate why InitialSessionState.CreateDefault2() is slower than CreateDefault()

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#5104]
CreateDefault2() should only be loading the Core cmdlets module while CreateDefault() loads more, yet CreateDefault2() is 3-8 times slower.

```powershell
'CreateDefault','CreateDefault2' | %{  (measure-command {
$iss = [InitialSessionState]::$_();
1..100 | % { $ps = [powershell]::Create($iss).AddCommand('echo').AddArgument(1); $ps.Invoke(); $ps.Dispose() } }).TotalMilliseconds }

1190.377
3268.448
```

**Comment by iSazonov** [comment]
Formally 'CreateDefault2' is faster 'CreateDefault':
```powershell
'CreateDefault','CreateDefault2' | %{  (measure-command {
$iss = [InitialSessionState]::$_();
1..100 | % {  } }).TotalMilliseconds }

5.1233
2.0122
```

**Comment by lzybkr** [comment]
Just creating an `InitialSessionState` is not interesting.

Opening a runspace that uses it is more interesting, bug I get ambiguous results, possibly other factors like garbage collection interfere with definitive results.

But running a command in that runspace - that's a typical scenario, and in theory, in that scenario, `CreateDefault2` should do less work, so it should be measurably slower.

**Comment by Tadas** [comment]
What seems to be happening is that during Invoke() `Microsoft.PowerShell.Utility\Write-Output` (aka. `echo`) triggers `CommandDiscovery.TryModuleAutoDiscovery`. While CreateDefault() returns with that module already loaded.

I've tried to explicitly import "C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1" before Write-Output but it didn't yield the expected results - `AddCommand('Write-Output').AddArgument(1).Invoke()` is now fast, but most of the time is being spent before that in Import-Module. Seems like it's loading more slowly than in CreateDefault, I must be doing something wrong.
