### ISSUE TITLE
The -NoNewLine switch parameter of Out-File and Out-String  should not strip embedded newlines from formatter-generated output 

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#5107]
<sup>Follow-up to #3684.</sup>

With _multiple_ input objects, the `-NoNewline` switch causes said cmdlets not to place a newline after each (output representation of) the input object - in other words: the input objects' (representations) are _directly concatenated_.

While the usefulness of this behavior is debatable, it should work consistently with respect to how newlines _embedded_ in input object representations are handled.

Currently, 

* formatter-generated output representations have their embedded newlines _stripped_

* `.ToString()` generated output representations have their embedded newlines _preserved.

It is the latter behavior that should be consistently applied.

Steps to reproduce:
------------------

```powershell
([pscustomobject] @{ one = 1 }), "two`nthree" | Out-File -NoNewline t.txt; Get-Content -raw t.txt
```
Note how the first input object uses the PS formatting system, whereas the second one doesn't.

Actual behavior:
-----------------

```powershell
one---  1two
three    # no trailing newline
```
Note how the internal newlines were stripped from the default output formatting for `@{ one = 1 }`, which is:

```

one
---
  1

```

Expected behavior:
-----------------

```powershell

one
---
  1two
three  # no trailing newline
```

You could argue that `-NoNewline` with formatter-generated output doesn't make much sense with _multiple_ input objects, and the mixing with `.ToString()` formatted objects produces strange effects, but stripping all embedded newlines makes even less sense.

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.8
```

**Comment by iSazonov** [comment]
I assume that the original idea was to output the original formatted objects without modification and without a new line between its. The thought was probably about simple strings, not composite objects.
```powershell
">>>", $(Get-Date), "<<<" | Out-String -NoNewLine
```

**Comment by mklement0** [comment]
@iSazonov: 

The output of `Get-Date` is not a simple string, it's a formatter-generated multi-line string that happens to have only _one_ data line, surrounded by empty lines.
Have only one data line is rare, however - most formatted output has multiple non-empty lines that make no sense when run together.

Note that the only reason to use `Out-String` /  `Out-File` at all is the express desire to use the formatting system (though in the case of `Out-File` that is obscured if you use `>`).

**Comment by iSazonov** [comment]
If it make no sense nobody use it :-) As for me the Issue looks like a side affectt hat no one can see because it doesn't use.

**Comment by mklement0** [comment]
(Incidentally, I had the actual vs. expected behavior accidentally swapped in the original post - fixed.)

I agree that this very little utility in `-NoNewline` for both `Out-File` and `Out-String`:

As stated, `Out-*` is only needed if you _do_ want the formatter involved, and that's precisely the behavior that is useless with `-NoNewline`.

In hindsight, it makes me wonder whether there was ever a good reason to add `-NoNewline` to `Out-File` to begin with.

I also wonder if the original intent for `-NoNewline` was what we're now proposing for `-NoLastNewline`, and perhaps it was simply mis-implemented.

I'm closing this, and will add more comments to the related doc issue I've created.

**Comment by mklement0** [comment]
(Incidentally, I had the actual vs. expected behavior accidentally swapped in the original post - fixed.)
