### ISSUE TITLE
Add a -NoLastNewline switch parameter to Write-Host, Set-Content, Add-Content, Out-File, Out-String

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#5108]
<sup>Follow-up to #3684.</sup>

With _multiple_ input objects, the `-NoNewline` switch causes said cmdlets to not only omit a _trailing_ (last) newline, but also not to place newlines _between_ the (output representations of) the input objects on output.

However, perhaps more typically, you want to only suppress a _trailing_ newline, so it would be handy to have a `-NoLastNewline` parameter (mutually exclusive with `-NoNewLine`) that does just that.

If #3855 gets implemented, an alias `-NoLastDelimiter` could be defined, which would effectively turn the application of the delimiter from _terminator_ logic (place delimiter after _every_ item, including the last) into _separator_ logic (place delimiter only _between_ items).

Desired behavior
------------------

* `Out-String` example:

```powershell
PS> 'a', 'b' | Out-String -NoLastNewline
a
b
```

Note that without `-NoLastNewLine` you'd get a blank line at the end, due to an extraneous newline getting appended, as discussed in #14444 (which asked for `-NoLastNewLine` to become the _default_ behavior, but that was [declined due to backward-compatibility concerns](https://github.com/PowerShell/PowerShell/issues/14444#issuecomment-1473683009)).

* `Write-Host` example:

```powershell
PS> 'a', 'b' | Write-Host -NoLastNewline; Write-Host 'c'
a
bc
```

Note that with `-NoNewline` you'd get `abc`.

Input object-_internal_ (embedded) newlines should be left untouched by both `-NoLastNewline` and
`-NoNewline` (though the latter doesn't do so consistently at present - see #5107).

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.8
```

**Comment by mklement0** [comment]
@ImportTaste, that would work too (and I'm personally open to either), but what makes you prefer _trailing_ over the _last_? Does the latter strike you as more ambiguous? 

When naming parameters, it's always worth striving for consistency with existing, analogous / conceptually related names. `Get-Help * -Parameter *trailing*` currently doesn't find anything among the standard cmdlets; `Get-Help * -Parameter *last*` yields `Select-Object`, which has a `-Last` parameter (only loosely related).

There's also a balance to strike between expressiveness and simplicity of words, especially keeping in mind the large non-native-speaker user base PowerShell has (though you can argue that _trailing_ is well-established).

**Comment by cow1337killer3** [comment]
Make it happen

**Comment by SteveL-MSFT** [comment]
@PowerShell/wg-powershell-cmdlets discussed this, we agree with the need and proposed new switch and agree that `-NoLastNewline` is probably best option given that `-Last` is used already.
