### ISSUE TITLE
port Get-PSHostProcessInfo and Enter-PSHostProcess cmdlets to non-Windows

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#5110]
These cmdlets currently depend on named pipes on Windows.  We need to support these on non-Windows.

**Comment by KirkMunro** [comment]
I hope you guys can get this working on Linux. At this weeks PowerShell and DevOps Summit, I demoed my debugging talk entirely on macOS, except for this part, for which I had to switch over to Windows.
