### ISSUE TITLE
Web Cmdlets should warn when  legacy -Credential is sent over unencrypted connections

### ISSUE THREAD

**Issue by markekraus** [PowerShell/PowerShell#5112]
# Problem

In #5052 we are introducing the new `-Authentication` parameter which include a terminating error when any scheme other than `https://` is provided in the URI. The legacy `-Credential` usage currently does not offer any warnings or errors when the secrets are sent over an unencrypted connection. 

This issue is to track and discuss which method to go with.

# Possible Solutions

## Add a warning
This solution would add a warning message (via `WriteWarning()`) that the use could suppress with the `-AllowUnencryptedAuthentication` parameter. This would likely be a non-breaking change that would simply the user politely when they use the legacy `-Credential` and something other than `'https://`

## Add an Error
This is similar to the previous but instead return an error. This could be a terminating or non-terminating error, but either would be a breaking change. A common usage of the web cmdlets is to use `-ErrorAction Stop` in a try/catch and this would introduce new stops for previously working code if users were sending credentials over HTTP before

## Remove the legacy `-Credential` usage.
The new `-Authentication` usage has some duplication of functionality in that it does the same thing on its `Basic` option as the legacy `-Credential` usage. Legacy `-Credential` would only sent the Authorization header when the server present an Authorization request where the new method always sends the Authorization header (as many OAuth systems do not present auth realm).  This would require some discovery and clean up. I think this is the ultimate choice, but probably not a good candidate for 6.0.0 RTM.

**Comment by dragonwolf83** [comment]
The wording of `-AllowUnencryptedAuthentication` doesn't make sense for Warning. By issuing a warning, you are by default allowing unencrypted. I propose an `-IgnoreUnencryptedWarning` should be used if Warning is chosen. The Error proposal should continue with `-AllowUnencryptedAuthentication`.

**Comment by markekraus** [comment]
`-AllowUnencryptedAuthentication` is not the warning. That is the parameter switch. 

And, I disagree with `-IgnoreUnencryptedWarning`. `-AllowUnencryptedAuthentication` will already be present and there is no need to add a second parameter to do the same thing. There were already many discussions and back and forth on `-AllowUnencryptedAuthentication` and I think that debate does not need to be revisited.

**Comment by dragonwolf83** [comment]
`-AllowUnencryptedAuthentication` is a parameter switch to do what exactly? I thought it was a new parameter that was pulled out from previous PR specifically for this discussion of whether a Warning or Error should happen if no parameter is specified.

What I'm suggesting is that for Warning Proposal, it is very confusing and doesn't make any sense. If I run `Invoke-WebRequest -Credential` and it works with a warning displayed then you have by default allowed it to happen. So why would I need to set `-AllowUnencryptedAuthentication`? I never would.

Now, if you want `Confirmation` to happen so the user interactively chooses yes or no. Then it makes sense to have an `-AllowUnencryptedAuthentication` switch to hide confirmation and choose yes.

Error Proposal is fine, I just think the wording doesn't make sense if credentials are still sent with just a warning let the user know it happened.

**Comment by markekraus** [comment]
> What I'm suggesting is that for Warning Proposal

And what I'm saying is there is no point in having yet another parameter that does the same thing. If `-AllowUnencryptedAuthentication` didn't already exist, then yea, maybe something else. But there is no point in 2 doing the same thing. seeing both `-IgnoreUnencryptedWarning` and `-AllowUnencryptedAuthentication` would be awkward.

The warning would be temporary. The end game is removing the legacy usage, IMO. For that temporary period of time having using the same parameter even if the wording doesn't suit everyone, is better than adding another parameter that will just end up being removed.

**Comment by markekraus** [comment]
> `-AllowUnencryptedAuthentication` is a parameter switch to do what exactly? 

The new `-Authentication` parameter options give a terminating error for non-https and can only by suppressed with `-AllowUnencryptedAuthentication`.

**Comment by dragonwolf83** [comment]
I think you are separating out logic that shouldn't be separated. `-Credential` and `-Authentication` behavior should match when sent over unencrypted. I think that is where my confusion is coming in. Having one error by default and the other give a warning would be inconsistent. So either both error, both warn, or both ask confirmation. Maybe that is what your 3rd proposal about `-Credential` is about?

Also, you are not proposing removing the `-Credential` parameter right, just cleaning up the code on how it used?

**Comment by markekraus** [comment]
> I think you are separating out logic that shouldn't be separated. 

> Having one error by default and the other give a warning would be inconsistent. 

That's to avoid a breaking change now. Ultimately, there will be a breaking change. But, we can go this route with a warning temporarily an avoid breaking it until we have to.

> Maybe that is what your 3rd proposal about -Credential is about?

That's exactly it. Basically, `-Credential` has 2 uses now. The legacy use where it is just `-Credential` and the new use where it is `-Authentication Basic -Credential`. The legacy use only sends the `Authorization` header when a web server has issues a `401` and `WWW-Authenticate: Basic realm=<realm>`. Many APIs and OAuth grant flows require `Basic` auth without the `401` or `WWW-Authenticate: Basic `. The legacy never errors. The new usage allows for sending the `Authorization` header always and it gives a terminating error when you try anything other that HTTPS unless you provide the switch.

My goal (what I think is the right direction) is to remove the legacy usage and just standardize on the `-Authentication`  parameter. That way we can add more authentication methods which may or may not use the `-Credential` parameter (such as OAuth/Bearer use of `-Token`). But that is not a trivial task. For one it is a significant breaking change and for another there is a lot of code cleanup associated with it. So getting that done before 6.0.0 RTM when it's not really a priority is unlikely.

So that is what the 3rd option is about. It's more of a "do nothing until we do it right and when we can doit right, this is how". But I would rather up the security game in the Web Cmdlets *before* 6.0.0 RTM even if some of those measure are temporary.

> Also, you are not proposing removing the -Credential parameter right, just cleaning up the code on how it used?

No, it will stay. But, to use it, in the future you will need to supply `-Authentication Basic`. For now, the legacy behavior is left in.

**Comment by markekraus** [comment]
Digging into this a bit, removing the legacy usage isn't as simple and I thought. HttpClient apparently does some magic authentication for Basic, NTLM, and Digest using these credentials and it handles some automated detection and resolution, something I'd rather not bring into the web cmdlets. Might be able to get as way with a `-Authentication BuiltIn` or something like that.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this.  desire is that we can use `-Authentication Negotiate` (which is default for compat reasons) to handle the builtin dotnet auth.  and throwing a terminating error (telling them about `-AllowEncryptedAuthentication` switch) if `-url` is "http:" if `-AllowUnencryptedAuthentication` is not used.

**Comment by markekraus** [comment]
@SteveL-MSFT I'm a bit confused about how to implement this. You are saying to add a `Negotiate` option, make it default (replacing `None` as default) having `-Credential` by it self work with out specifying auth because `Negotiate` is default. but... how is it supposed to distinguished between the user doing `irm -Auth negotiate $uri` and not supplying a `-Credential` and just `irm $uri`? The logic for this will be really ugly unless I'm misunderstanding.

**Comment by SteveL-MSFT** [comment]
@markekraus yeah, that detail was missed in the discussion.  I think the way to implement this is:
  
  - `-credential` is a parameterset (let's call it "credential") along with `-auth`
  - default w/o `-auth` is none (aka anonymous)
  - `-credential` w/ `-auth none` is a runtime check and terminating error
  - `-allowunencryptedauthentication` is required if `-url` starts with `http:`
  - `-auth negotiate` is default for parameter set "credential"

**Comment by markekraus** [comment]
I don't think a parameter can have default value on a per-parameterset basis.

The way I would do this change is to break the `iwr -uri $uri -Credential $creds` usage and make `-Credential` require that either `-Auth negotiate` or `-Auth basic` be present:

```powershell
$url = 'https://contoso.com'

# results in an error about requiring -Authentication Basic|Negotiate
iwr -uri $uri -Credential $creds
#Error

# Result in error requiring -Credential
iwr -uri $uri -Auth Negotiate
#Error

# default is still None for -Authentication so this works
iwr -uri $uri
#Success!

# non-https uri errors:
$url = 'http://contoso.com'
iwr -uri $uri -Authentication Negotiate -Credential $creds
#Error

# only ways to use -Credential 
$url = 'https://contoso.com'
iwr -uri $uri -Authentication Negotiate -Credential $creds
#Success!
iwr -uri $uri -Authentication Basic -Credential $creds
#Success!

# -UseDefaultCredentials cannot be use with any auth so these error:
iwr -uri $uri -UseDefaultCredentials -Authentication Negotiate
#Error
iwr -uri $uri -UseDefaultCredentials -Authentication Basic
#Error
iwr -uri $uri -UseDefaultCredentials -Authentication OAuth
#Error
iwr -uri $uri -UseDefaultCredentials -Authentication Bearer
#Error

# -UseDefaultCredentials can be used with -Authentication none:
wr -uri $uri -UseDefaultCredentials -Authentication None
#Success!
```

Otherwise, I'm at a complete loss on how to implement.

**Comment by SteveL-MSFT** [comment]
@markekraus since this deviated a bit from the original expectation from the Committee, let me bring it back up.

**Comment by markekraus** [comment]
Thanks! I would have had a more fleshed out proposal for this.. but I didn't plan on breaking this until later, all I wanted for now was possibly an error on `-Credential`/`-UseDefaultCredential` on http. but if we are going to break it.. we might as well break it all the way.

**Comment by SteveL-MSFT** [comment]
Can we do this?  `-Auth` is `Default` if not specified, but meaning of `Default` changes depending on whether `-Cred` is used.  No cred `Default = none`, with cred `Default = negotiate`.  There is no explicit none or negotiate for `-Auth`.

**Comment by joeyaiello** [comment]
@markekraus I'm actually fine with the full break proposal you made, but I think we need another +1. 

@SteveL-MSFT that seems a bit harder to follow intuitively. The error messages would have to be really good if we went that route. :)

**Comment by SteveL-MSFT** [comment]
Perhaps for now, the best thing to do is simply return an error if `-AllowUnencryptedAuth` isn't used and the `-URI` is http.  Let's leave the other discussion for now which means we'll just have to have that inconsistency.

**Comment by markekraus** [comment]
@SteveL-MSFT that is certainly my minimum ask. 

The breaking change for `-Credential`, is that something that would be possibly for 6.1/6.2? or is that something that would need to tabled until the next major version?

**Comment by SteveL-MSFT** [comment]
@markekraus ideally, I'd like to have telemetry in the future to show that only a small set of customers were using the legacy `-Credential` with PSCore6 so we can deprecate it and eventually remove it.  At this point, we can worry about that later and accept a possibility that we have to just live with it.

**Comment by markekraus** [comment]
@SteveL-MSFT my only fear is that the situations where `-Credential` and `-UseDefaultCredentials` would be used also don't lend themselves well to telemetry: internal applications. They are currently the only means for NTLM and Digest authentication and those kinds of sites and the automation working against them may not have internet access to dial home. I'd rather keep it by breaking the current usage and move it to the new `-Authentication` usage than to break access to legacy systems. *shrugs

But, I'm OK with a PR for just the error on non-https `-Uri` without `-AllowUnencryptedAuth` for now and living with the legacy behavior.

**Comment by markekraus** [comment]
#5402 for the non-HTTPS `-Credential` (legacy) and `-UseDefaultCredentials` errors
