### ISSUE TITLE
-NoTypeInformation should be default on Export-Csv

### ISSUE THREAD

**Issue by markekraus** [PowerShell/PowerShell#5131]
In most situations, the default behavior of `Export-Csv` is undesirable. Its usage as an object Import and Export is limited to begin with. What it is more commonly used for (in my experience, anyway) is to produce CSV files either to be  parsed by other automated processes outside the PowerShell ecosystem or to be used in Excel as human parsable reports. The initial line with the type information is undesirable in those situations. 

This is a common "gotcha" for PowerShell novices. It violates the Principle of least astonishment.

I'm curious how many profiles have this `$PSDefaultParameterValues['Export-CSV:NoTypeInformation'] = $true`.  I know I have that in my work profile and at the top of so many scripts.

It's a minor annoyance and a breaking change, but I just don't think the default behavior is actually useful.

My tentative proposal is to leave `-NoTypeInformation` in for backwards compatibility but make it default and add a `-IncludeTypeInformation` switch to revert to legacy behavior per request.

This issue is for discussion, yays, nays, and possible alternatives for a proposed solution.

**Comment by iSazonov** [comment]
Do anybody use the type information?

**Comment by ww40** [comment]
I can't say I've had a use for the type information in my outputs when I use `Export-Csv`

**Comment by markekraus** [comment]
@iSazonov I have only ever used it for academic purposes, just to see what it does. It doesn't even re-serialize objects upon import, even simple objects like a hashtable. 

Maybe it's useful to know what the object was before it was exported? But I've never personally seen it used in that manner. Usually when a user wants to export and import objects and attempt to preserve type data they will used `*-Clixml` cmdlets, JSON, or a custom serializer.

**Comment by Jawz84** [comment]
Agree fully with @markekraus here. Having -NoTypeinformation as default would be a good breaking change. ++ For -WithTypeInformation

**Comment by iSazonov** [comment]
I believe the design was with PSObject type in mind to export/import. For other types it seems there's no point in doing that.

**Comment by markekraus** [comment]
@iSazonov maybe, but it doesn't even preserve custom PSTypeNames:

```powershell
[PSCustomObject]@{
    PSTypeName = 'My.Custom.Object'
    Column1 = 'values1'
} | Export-Csv C:\temp\csv.csv
$import = Import-Csv C:\temp\csv.csv
$import.PSObject.TypeNames
```

```none
CSV:My.Custom.Object
```

It already pulls in as a PSCustomObject:

```powershell
$import[0].GetType().fullname
```

```none
System.Management.Automation.PSCustomObject
```

so I'm still left wondering what the use-case is.

**Comment by iSazonov** [comment]
@markekraus By the way, it might make sense to fix.

**Comment by markekraus** [comment]
@iSazonov Fix in which way?

**Comment by iSazonov** [comment]
To recover correct object types in your type.

**Comment by markekraus** [comment]
@iSazonov agreed, it might be worth making that breaking change in addition to switching the default behavior.

**Comment by iSazonov** [comment]
I think it's an independent case.

**Comment by markekraus** [comment]
@iSazonov agreed. I meant that it should be tracked as a separate issue but was worth also doing, IMO.

**Comment by artvandelay440** [comment]
Agreed. If wanted, I'd suggest a -IncludeTypeInformation switch.

**Comment by markekraus** [comment]
@artvandelay440 agreed. That is a better switch name and matches other switch parameters.

**Comment by Jawz84** [comment]
@artvandelay440 I think that is a better switch name. Good suggestion.

**Comment by megamorf** [comment]
+1

It's always been annoyance. Whenever you wanted to post-process a csv Export and forgot to disable the type information you were forced to export it again or manually edit the file, urgh.

**Comment by annamdove** [comment]
Definitely needs to be removed as the default behavior. I know to add -NoTypeInformation, and it is frustrating every time I forget.

**Comment by AmazingWizard** [comment]
This trips me up all the time. I would like to put my hat in the ring for `-notypeinformation` being default

**Comment by markekraus** [comment]
@iSazonov #5134 for the import and PSTypeName issue

**Comment by murrahjm** [comment]
I am 100% behind this change. Simpler is better.

**Comment by smooochy** [comment]
+1

Maybe just extend the functionality of -Verbose to include the type information instead of adding a separate -IncludeTypeInformation switch? Just a thought.

**Comment by markekraus** [comment]
@smooochy `-Verbose` is usually intended for verbose console output. I think using it to add the type information to the output file would be a bit anti-pattern.

**Comment by Alcon835** [comment]
+1

**Comment by 91jme** [comment]
+1

This extra information shouldn't be part of the default output. Agreed on adding switch to include it if needed.

**Comment by markekraus** [comment]
I have some demo code available if anyone wants to see the changes:

https://github.com/PowerShell/PowerShell/compare/master...markekraus:ExportCsvNoTypeInformation

Note: this also affects `ConvertTo-Csv` but I can't see the original default behavior being any more useful in that command either. If it is, it can easily be adjusted.

**Comment by jongross4** [comment]
+1

Suggest adding the includetypeinfo switch.  Ignore existing notypeinfo switches.

**Comment by thannett** [comment]
I'd love to see this changed.  Is there any use case for having the type information?  I've never used it personally.

**Comment by iSazonov** [comment]
Wow, 137 votes - Flash mob?
/cc @SteveL-MSFT

**Comment by thannett** [comment]
@iSazonov This got posted to /r/Powershell.  So yeah, kindof a flash mob :)

**Comment by iSazonov** [comment]
Interesting, can we add a label to automatic post to Reddit for chosen discussions?

**Comment by thannett** [comment]
Great idea.  You've got a very passionate community in Reddit.  It would be great to have the open source movement of Powershell extend to a larger community.

**Comment by evilmaverick** [comment]
+1 
If you needed to know, you would know how to add the additional flag for type info.

**Comment by WithHolm** [comment]
+1

**Comment by markekraus** [comment]
@iSazonov I could do that. ;) I think this one got traction because I advertised it on Reddit and twitter.. and.. because it is almost universally disliked feature of the language. I wanted to advertise it in the hopes that someone would provide feedback on how they actually use the default behavior.  So far, I guess no one does?

As for a label and auto-Reddit-Post, That would be something I could do. seems like the perfect job for PowerShell and [PSRAW](https://github.com/markekraus/PSRAW). 😄

**Comment by GHRoss** [comment]
In my early experiences with PowerShell, I didn't know about -NoTypeInformation.

I ended up including in my script something that would remove the first line of the exported CSV file to get rid of the type information!!

I could not agree with this more.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and agree that the default behavior should be `-NoTypeInformation`.  However, we need to retain `-NoTypeInformation` to not break scripts already using it and document the change in behavior for scripts that haven't been using that switch.  We should also introduce a new switch to retain previous behavior.  `-IncludeTypeInformation` seems reasonable.  Documentation and new script analyzer rules will help mitigate existing scripts that may have been skipping or removing the type information line which will now no longer work correctly.

**Comment by markekraus** [comment]
For those following the thread: PR #5164

**Comment by lzybkr** [comment]
`-NoTypeInformation:$false` should probably be equivalent to `-IncludeTypeInformation`.

And maybe the we don't need the new option, a confusing double negative is hardly obvious, but if nobody uses it, then is adding a new option helping anyone?

**Comment by iSazonov** [comment]
We could make an enhance to restore native type.

**Comment by markekraus** [comment]
@lzybkr see #5134  may not be used now... but.. it could be improved so that it would be useful for light weight PSCustomObject Import/Export serialization.

**Comment by wolfbyte** [comment]
I think this is a great idea. I'm constantly having to add the -NoTypeInformation switch every time I use Export-CSV
