### ISSUE TITLE
Web Cmdlet Error Syntax Re-style

### ISSUE THREAD

**Issue by markekraus** [PowerShell/PowerShell#5140]
Currently the errors in the Web Cmdlets are a bit tough to read. specifically the parameters are just unquoted strings. Theys hould be made more readable by using the format `'-Parameter'`.

**Comment by iSazonov** [comment]
See [comment](https://github.com/PowerShell/PowerShell/pull/5972#discussion_r162857125)
>I see we use the file pattern but the messages can be shorter - "Conflicting parameters are specified: Body and Form."
