### ISSUE TITLE
Replace the use of the term `hang` in documentation

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#5147]
Clarify meaning by REPLACING WITH "stop responding" or "not responding."
When used with technical audiences to describe an application, program, website or service that is not responding.

**Comment by SteveL-MSFT** [comment]
From a [search](https://github.com/PowerShell/PowerShell/search?p=2&q=+hang+&type=&utf8=✓) I only see one occurrence in our changelog.  In the source code, it's only in comments.

I do see one case in [PowerShell-Docs](https://github.com/PowerShell/PowerShell-Docs/search?utf8=✓&q=hang&type=)

**Comment by TravisEz13** [comment]
I don't think this is a high priority, but the tool says that we **should** fix it.  So, I filed an issue to track the resolution.

**Comment by TravisEz13** [comment]
Re-reading the guidance, we should fix for all audiences.

**Comment by TravisEz13** [comment]
The following terms still exist:
![image](https://user-images.githubusercontent.com/10873629/33464808-23524834-d5f9-11e7-81ec-a2a605a3152d.png)

**Comment by TravisEz13** [comment]
comments are covered by this issue when the code is published.

**Comment by TravisEz13** [comment]
Move this to 6.1 and created PR to add exceptions for these instances for now.

**Comment by bergmeister** [comment]
As far as I can see, there is no occurence of the word `hang` in the docs of the PowerShell or Docs repo btw,

**Comment by TravisEz13** [comment]
@bergmeister including code comments, those are considered documentation for this context

**Comment by TravisEz13** [comment]
There is still one instance
https://github.com/PowerShell/PowerShell/blob/5d03e1653a7d518715fa3f00587cad6b5c78cc89/src/System.Management.Automation/engine/remoting/commands/newrunspacecommand.cs#L1356
