### ISSUE TITLE
Write-Debug Prompts for Confirmation Stopping All Script Execution When Using -Debug For Some Reason

### ISSUE THREAD

**Issue by RickFlist** [PowerShell/PowerShell#5148]
Steps to reproduce
------------------
Save this to a file with a .ps1 extension and run it
```powershell
function Test-DebugMessage
{
     [CmdletBinding()]
     [OutputType()]

     param ()

     process
     {
         Write-Debug ( 'Test Message' )
     }
}

Test-DebugMessage -Debug
```

Expected behavior
-----------------
The following message is emitted 
```none
DEBUG: Test Message
```

Actual behavior
---------------
Prompted to continue for every Write-Debug statement. A for "Yes to All" does nothing
```none
DEBUG: Test Message

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): a

```

Environment data
----------------

```powershell
> $PSVersionTable.GetEnumerator() | ForEach-Object { Write-Host ('{0,26} : {1,-20}' -f $PSItem.Key,($PSItem.Value -join ', ') ) }
                 PSVersion : 5.1.15063.674
                 PSEdition : Desktop
      PSCompatibleVersions : 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.15063.674
              BuildVersion : 10.0.15063.674
                CLRVersion : 4.0.30319.42000
         WSManStackVersion : 3.0
 PSRemotingProtocolVersion : 2.3
      SerializationVersion : 1.1.0.1
```

**Comment by markekraus** [comment]
I believe that is by deisgn. you can instead do the following:

```powershell
function Test-DebugMessage {
     [CmdletBinding()]
     [OutputType()]
     param ()
     process
     {
         Write-Debug 'Test Message'
     }
}
$DebugPreference = 'Continue'
Test-DebugMessage 
```

And the debug messages will appear without stopping and prompting.

see [about_CommonParamters](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_commonparameters?view=powershell-5.1) and [about_preference_variables](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-5.1)

**Comment by markekraus** [comment]
To distinguish it from `write-verbose`. If it acted exactly as `write-verbose` what purpose would it serve? Generally you wouldn't keep `write-debug` statements in code outside of development. You only put it in development to code so you can perform suspend.

```powershell
function Test-DebugMessage {
     [CmdletBinding()]
     [OutputType()]
     param ()
     process
     {
         $a = 5
         Write-Debug 'First a'
         $a = 10
         Write-Debug 'Second a'
     }
}
Test-DebugMessage -Debug
```

when it prompts choose suspend then run `$a` and see that it is `5`. run `exit` and chose the option to continue. At the next prompt choose suspend and run `$a` and see that it is `10`. run `exit` and then chose the option to continue. This provides an easy way to break into the debugger and check the state of or manipulat variables in your code for the purposes of debugging.

If you just want information on the screen you have `Write-Verbose` and `Write-Information`.

**Comment by RickFlist** [comment]
Oh also, can you define "By design"?  When I hear "by design" I think there is a specification somewhere that says "when you use -Debug we're going to inquire for every single message emission". Is that the case ? What is "By design"?

**Comment by markekraus** [comment]
@RickFlist I mean it is probably by design because it is officially documented behavior. That's usually a good indication of the design. If the behavior differed from the documented behavior, that would like not be by design or possible a documentation issue.

**Comment by RickFlist** [comment]
Oh. Yes, it's usually an excellent indicator. Whoops. :\

The reasoning is actually there as well, which is awesome. 
"The Debug parameter overrides the value of the $DebugPreference variable for the current command, setting the value of $DebugPreference to Inquire. Because the default value of the $DebugPreference variable is SilentlyContinue, debugging messages are not displayed by default."

Any information as to why this doesn't occur with -Verbose? Ostensibly they would work the same way but I don't get prompted with -Verbose. Just curious

**Comment by RickFlist** [comment]
And what about the fact that "A" for "Yes to All" doesn't actually work? e.g. if I have multiple write-debug statements and hit "A" for the first one, I am still prompted for the second one. By design or bug? If the latter I will submit a new bug.

**Comment by markekraus** [comment]
That's also `by design`. the "yes to all" works with this usage:

```powershell
function Test-DebugMessage
{
     [CmdletBinding()]
     [OutputType()]
     param ()
     process
     {
         1,2,3,4 | Write-Debug 
     }
}
```

It's not for all calls to `Write-Debug`, just for all objects passed to the current call to `Write-Debug`.

**Comment by RickFlist** [comment]
I'll open up a couple User Voice request. Danke.

**Comment by KirkMunro** [comment]
Hey @RickFlist, just FYI, my PR that fixes this behavior was just merged, so in an upcoming release -Debug will simply enable debug message output without any of the prompting that was there before.

**Comment by RobinWPollard** [comment]
You can switch it to output the debug, bbut not pause ...
```powershell
if ($DebugPreference -eq "Inquire") {
    $DebugPreference = 'Continue'
    Write-Debug "We are running with Debug active. Expect lots of logging"
}
```

**Comment by KirkMunro** [comment]
@RobinWPollard For older releases, that workaround works. In PowerShell 6.2 and later though, there is no need for that workaround.

**Comment by HQJaTu** [comment]
Thanks for that @KirkMunro.
Since the pre 6.2 behaviour was very annoying, I simply upgraded to 6.2.1 and continued working with much less friction.
