### ISSUE TITLE
Systemwide Pointers To Active Version of PowerShell Core

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/PowerShell#5155]
OpenSSH just got a new parameter for specifying the default shell - but it appears it must be full path specified: https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

It is not clear whether it can receive an environment variable (but should be able to in my opinion).

This issue https://github.com/PowerShell/PowerShell/issues/1354 is asking for a pointer to the default powershell core remoting end point.

I'm not sure I understand not enabling PowerShell Core's configuration to self-publish what active version or folder should be used for these activities.

The alternatives to these would seem to be confusion in one or more of these ways:

- Everyone creating their own mechanisms for tracking the desired version of powershell core they want to be primary
- Everyone creating their own mechanisms for probing the latest version of PowerShell core (e.g. when a full path is required like OpenSSH DefaultShell)
- Inability to find latest PowerShell Core when running a bit of probing code does not work (OpenSSH DefaultShell)
- Lack of simple coordination between wiring up various components to powershell core - even ones out of the same open source team.

Among other problems, relying on the path does not allow for Windows PowerShell to be the system level powershell while all stipulated uses of PowerShell Core have a way to easily find (a) that is present (especially if at a custom path) and (b) what is the active version.

The implementation does not need to be heavy handed, for instance:

- Any pointers could be standardized environment variable names that are optional (but can be relied upon as the authoritative source when they do exist).  [That said I would prefer they always exist because it serves as a possible easy "is Powershell core installed" check - even when using custom install folders for powershell core (and yes I would assume the risk that someone uninstalled without cleaning the var by doing a test-path)]
- They could (SHOULD) require a special switch in the PowerShell Core installer to be changed to the version being installed (so that one can push and test a prospective version before making it primary)
- Any new, interface points like OpenSSH's "DefaultShell" would be more likely to be built the first time around to allow an environment variable if it was known that PowerShell Core had an authoritative one in which it published the active version.
- If an individual chose to they could include the active powershell core environment variable on their path to prevent the need for constant path add/removes (something that is frequently done incorrectly)

I am considering adding the ability to optionally set one or more "active powershell core" pointer environment variables (https://github.com/DarwinJS/ChocoPackages/issues/44) and it would be great if it was to a name agreed on this project - otherwise I can simply implement it as a custom value-add of using the chocolatey package to install powershell core.

Apologies if this has been handled somewhere and I've missed it.

**Comment by SteveL-MSFT** [comment]
In beta.9, the msi installer will add $pshome to %PATH% so you should be able to just rely on `pwsh` to start PSCore6.  In the future, we have a different [tracking issue](https://github.com/PowerShell/PowerShell/issues/4836) to determine how to support enumerating and starting side-by-side versions of PSCore6.

**Comment by DarwinJS** [comment]
Hmm - yeah I can't add the $pshome reference to the openssh key which claims it needs a full path.  The openssh installer also runs in Windows PowerShell by default - so also won't know what $pshome is.

This approach, nor the one in https://github.com/PowerShell/PowerShell/issues/4836, seems to allow an administrator to stipulate a system level version for compatibility - regardless of who might install new additional versions beyond a known compatible one.

**Comment by iSazonov** [comment]
@DarwinJS Can we close the issue? Seems we have a stable distribution model now.

**Comment by DarwinJS** [comment]
Yes it looks good now.  Thanks!
