### ISSUE TITLE
PowerShell: Copy/Paste reverses lines

### ISSUE THREAD

**Issue by AbelHu** [PowerShell/PowerShell#5160]
Steps to reproduce
------------------
Copy below lines from notepad
1234567
abcdefg
ABCDEFG
And paste to powershell

Expected behavior
-----------------

```
1234567
abcdefg
ABCDEFG

```

Actual behavior
---------------

```
>> ABCDEFG
>> abcdefg
>> 1234567
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.15063.674
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.674
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by iSazonov** [comment]
Have you any scripts and modules loaded?

**Comment by Tadas** [comment]
Related https://github.com/Microsoft/vscode/issues/29805

**Comment by iSazonov** [comment]
@Tadas Thanks for clarify!
@AbelHu Thanks for your report! It is dup https://github.com/PowerShell/PowerShell/issues/3816
