### ISSUE TITLE
Need mechanism to disable globbing

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShell#5167]
Globbing support on Linux has caused us to have to revert to using bash scripts because we can't pass parameters that contain `*` through to the executable.  In this case, we are trying to invoke a C++ pkg manager called conan.  It would be nice to have an option like `set -o noglob` in bash to disable globbing.

Steps to reproduce
------------------
Try to execute conan (or echoargs) with:

```powershell
conan info --only "None" --package_filter 'PkgName/*' --cwd ../..
```
Note: I've tried quoting the arg and escaping the `*`. Neither works with conan.

Expected behavior
-----------------
The `PkgName/*` gets passed through to conan,

Actual behavior
---------------
This generates an error:
```none
Cannot find path '/home/hillr/code/dotnet/echoargs/bin/Debug/netcoreapp2.0/PkgName' because it does not exist.
At line:1 char:1
+ dotnet ./echoargs.dll info --only "None" --package_filter PkgName/* - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (/home/hillr/cod...eapp2.0/PkgName:String) [], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta.8
PSEdition                      Core
GitCommitId                    v6.0.0-beta.8
OS                             Linux 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Related issues: #3931 #4971 #4683 and PR #4489

**Comment by SteveL-MSFT** [comment]
`--%` should work on a per command basis today, right?  This is for a session based preference?

**Comment by rkeithhill** [comment]
Indeed that does work - per command.  That's a workaround for now.

**Comment by mklement0** [comment]
This can probably be closed now: 

Using single- or double-quoting now suppresses globbing - https://github.com/PowerShell/PowerShell/pull/5188 was merged a long time ago.

**Comment by SteveL-MSFT** [comment]
@rkeithhill let me know if #5188 doesn't resolve your issue

**Comment by rkeithhill** [comment]
It does and that is what I've been using for a while now on Linux.
