### ISSUE TITLE
Need ability to make a PowerShell Core script "automatically" run under PowerShell Core on Windows

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShell#5168]
If my script `requires` PowerShell Core to run, then on Windows there is no good way to invoke a .ps1 file (say from cmd.exe or Win+r) and have Windows pick the correct version of PowerShell (PS Core or Win PS).  So yeah, this scenario requires that folks configure the `Open` verb to execute the PS1 file extension.  And there can only be one exe for "Open": either powershell.exe or pwsh.exe. 

Another scenario is that you have a build system without support for PowerShell Core yet.  It runs Windows PowerShell.  It would be nice if Windows PowerShell could fire off the appropriate version of PowerShell Core installed on the system if it sees `#requires -Version 6` in the script.  Although using a version for this is less than satisfying.  It would be better in this case to have an edition requirement as well e.g.:

```
#Requires -Edition Core -Version 6.1.0
```

**Comment by SteveL-MSFT** [comment]
I think the simplest solution here might be to introduce .ps2 which would only be associated to pwsh.exe although it can still run .ps1 if explicitly passed.

**Comment by markekraus** [comment]
@SteveL-MSFT if we took a page from the PHP handbook, `.ps6` is a good idea. 

If we took a page from the Python Handbook, we wouldn't do anything at all with file extensions. New extensions become messy and make for transitions between versions supporting multiple versions painful. I realize it would be coercive in the "you must use `.ps6` for core" sense, but as people begin to adopt it you start getting modules and projects with mixed extensions. Python ultimately went with the assumption that users would just have to know what they're doing. 

In any case, I would urge that the decision to add a new extension not be taken lightly. It may be simplest in implementation, but it could have a massive and lasting impact on the PowerShell ecosystem as a whole.

**Comment by SteveL-MSFT** [comment]
@markekraus yes, .ps6 would be better if we decide to go that route, but we've been avoiding introducing a new extension for the reasons you mention.  The main problem I can see is that even if we add support for `#requires -v 6.1.0` which automatically tries to find 6.1.0 and execute it, it means we also need to update Windows PowerShell with that logic which means only Win10/Server2016 would get that change.  A workaround (which I don't like) is to use a batch file to wrap scripts in cases where you can't specify `pwsh.exe <script.ps1>`.

**Comment by rkeithhill** [comment]
Perhaps the install of PowerShell Core on a Windows machine could introduce a "version selector" shim (powershell.com??) kind of like VS has when you open a SLN file (and you have multiple versions of VS that could load the SLN).  I don't anticipate this being interactive choice.  It would merely fire up Windows PowerShell unless the script required PowerShell Core - then it would fire up PowerShell Core.  

I'm not particularly keen on adding a new extension.

**Comment by lzybkr** [comment]
I think you're asking for shebang support.

The extension can't be the answer - new releases will always introduce features, but worse, the version of PowerShell is just one of the variables that impact whether a script will work or not.

**Comment by rkeithhill** [comment]
> The extension can't be the answer - new releases will always introduce features, but worse, the version of PowerShell is just one of the variables that impact whether a script will work or not.

Agreed.  

> I think you're asking for shebang support.

Hmm, most of our shebang'd scripts at the moment run on Windows PowerShell just fine.  And it is convenient that I don't have to tell my team they all have to install PowerShell Core on Windows. 

At some point though, we are going to want to use features only available in PS Core.  It seems like `#requires` is the appropriate way to declare that dependency. Although I'd prefer a new `-Edition` parameter and not solely rely on `-Version` >= 6.  Even though it isn't the plan for Windows PowerShell to ever hit v6.0 - plans change.  Better to have a more "explicit" declaration of what is required IMO.

**Comment by lzybkr** [comment]
`#requires` tells you when you're doing it wrong with an error.

Shebang runs the right version of PowerShell for you implicitly (assuming you specified the right path of course.)

I'm not saying we can get shebang into Windows, but I still think it's what you're looking for.

**Comment by markekraus** [comment]
hm maybe shbang doesn't need to be windows. If you could mix `#!` and `#requires`

assuming shbang support was added in core,

```powershell
#Requires -Version 6.0
#!c:\path\to\pwsh.exe
```

if you tried to launch that in 5.1 it would die rightfully so. If you launch it in core it would run fine

```powershell
#!C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe

<# some 5.1 code #>
``` 

if launched in core, core could launch powershell.exe. if launched in powershell.exe it would just ignore the comment. 

Then the user just places .ps1 to run against pwsh.exe always and pwsh.exe manages the correct one based on shbang.

**Comment by sandersaares** [comment]
My scenario: user opens PowerShell (v5) from start menu, goes to run my script. Oh no, my script is designed for PowerShell 6!

If the user just typed "pwsh myscript.ps1" it would work. But now PowerShell 5 chokes on the script.

I want v5 to automatically execute v6 instead when it detects some annotation. It should prefer "pwsh" in PATH or registry or whereever. I do not wish to hardcode any paths to pwsh in my scripts (especially given that they are crossplatform scripts).

**Comment by SteveL-MSFT** [comment]
As a workaround, you could do something like this:

```powershell
if ($PSVersionTable.PSVersion -lt "6.0")
{
	pwsh -f $SCRIPT:MyInvocation.MyCommand.Path
	return
}

$PSVersionTable.PSVersion
```
