### ISSUE TITLE
Help topic shows Unicode BOM on Linux

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShell#5169]
I seeing the Unicode BOM displayed on Linux when viewing the `about_Requires` help topic.

Steps to reproduce
------------------
Doing this from WSL console with PS Core beta.8 installed
```powershell
Update-Help
help about_requires
```

Expected behavior
-----------------
There is no Unicode BOM displayed.

Actual behavior
---------------
![image](https://user-images.githubusercontent.com/5177512/31785647-18980854-b4c3-11e7-8472-7b2dd35eb5db.png)

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta.8
PSEdition                      Core
GitCommitId                    v6.0.0-beta.8
OS                             Linux 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rkeithhill** [comment]
Perhaps this should go in the PowerShellDocs repo.  OTOH, can't the Get-Help command suppress the display of the BOM?

**Comment by SteveL-MSFT** [comment]
This should probably be a bug in the PlatyPS repo so that the generated help files should not have a BOM.  It's possible to modify `Get-Help` to suppress showing the BOM, that that's a patch over the root problem.
