### ISSUE TITLE
a warning should be presented if -AsByteStream and -Encoding are used together

### ISSUE THREAD

**Issue by JamesWTruher** [PowerShell/PowerShell#5170]
With https://github.com/PowerShell/PowerShell/pull/5080 it is possible to use both `-AsByteStream` and `-Encoding` together. Under these circumstances, `-Encoding` is superfluous as the stream of bytes should represent the bytes in the file (which are not affected by encoding).

**Comment by chuanjiao10** [comment]
remind:
Help with the -AsByteStream parameter,
There is currently no document added to "get-help", and "https: //" on powershell beta9, if the change is complete, do not forget to add, thanks.

**Comment by nityanandagohain** [comment]
Hi, Can anyone help as for how do I work on this, Thanks!

**Comment by vexx32** [comment]
For the cmdlet(s) that have this issue, I think the best approach would be to seclude them to distinct parameter sets, preventing them from being used together. 

Depending on existing parameter sets this could get slightly complex, but should be no more complex than adding a series of `[Parameter()]` attributes with appropriate `ParameterSetName` properties; each parameter should be in distinct set(s). Mind that when other sets are present you may need to end up duplicating existing parameter sets to retain other functionality while segregating these two parameters. The important thing is that at least one of the parameters cannot be in the 'default set' (although one could feasibly be to simplify the code).

Give it a shot, and if you need some more detailed instruction just show me where you get stuck and I'm sure I can point you in the right direction. 😄

**Comment by renehernandez** [comment]
@SteveL-MSFT If this issue is still for grab I would like to work on it as a first time contribution

**Comment by JamesWTruher** [comment]
current behavior provides a warning with get-content, set-content, and add-content
