### ISSUE TITLE
The help content for "Get-Help powershell.exe" needs to be updated to reflect the new name 'pwsh'

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#5181]
Running `get-help pwsh.exe` fails now, while running `get-help powershell.exe` prints the old help content for powershell.exe.

Two things need to be done to update the help content:
1. The local help content we pull in during build needs to be updated. We pull in using the nuget package `powershellhelpfiles`, and the help content are packed in that nuget package.
2. The online help content needs to be udpated.

**Comment by adityapatwardhan** [comment]
PR for updateable help: https://github.com/PowerShell/PowerShell-Docs/pull/1853
