### ISSUE TITLE
Start-Process should support timeout

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#5185]
[System.Diagnostics.Process] has a .WaitForExit which has a timeout value.

Start-Process should have a parameter where we can pass that instead of needing to -Passthru and capture the process object...

**Comment by stuajnht** [comment]
Hi,

I'm happy to have a look at this issue if no-one else has been assigned to it, and it is something that is wanted.

If so, I have a few questions:
- Having a look through the codebase, I believe the file [`Process.cs`](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs#L2016) is where this should be implemented
- [`Process.WaitForExit`](https://msdn.microsoft.com/en-us/library/ty0d8k56(v=vs.110).aspx) uses milliseconds for the timeout value. Should the `Start-Process` parameter also expect milliseconds?
- What should the `Start-Process` parameter be called? I am going to assume `-Timeout`, although `-WaitTimeout` or `-ProcessTimeout` could also be suitable

**Comment by SteveL-MSFT** [comment]
@stuajnht Great!  Consider it yours!  I think following the conventions of `Wait-Process` makes sense.  I'll remove the `Up-for-Grabs` so someone else doesn't duplicate your work.  Thanks!

**Comment by Jaykul** [comment]
This still seems like a pretty simple feature that just got forgotten
