### ISSUE TITLE
ConvertFrom-Json silently throws away duplicated keys with identical casing

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#5199]
If the JSON contains duplicate keys with the same casing, then  only the last key is used and the others are silently thrown away. The code in `JsonObject.cs` [here](https://github.com/PowerShell/PowerShell/blob/50f6667bdb0739a315f13b3dd013dc0fb96103cb/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/JsonObject.cs#L103) actually caters for this case and would throw an error but it never gets to that stage because `JsonConvert.DeserializeObject` [here](https://github.com/PowerShell/PowerShell/blob/50f6667bdb0739a315f13b3dd013dc0fb96103cb/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/JsonObject.cs#L62) does not throw when there are duplicate keys and simply decides to take the last one.

Steps to reproduce
------------------

```powershell
'{ "key":"value1", "key":"value2" }' | ConvertFrom-Json
```

Expected behavior
-----------------

Either a warning that duplicated keys were disregarded or an error stating that duplicate keys are not allowed unless e.g something like. a `-Force` switch is used. Given that this would be a breaking change, it will probably have to be a warning.

Actual behavior
---------------
Only the last key is used when there are duplicate keys
```powershell
key
---
value2
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta.8
PSEdition                      Core
GitCommitId                    v6.0.0-beta.8-20-g0d5a6fbd71c31043d0eda82f7b0e2d4fb0431322
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment]
It is really bug - Json don't allow duplicate keys with the same case.

**Comment by SteveL-MSFT** [comment]
As best as I can tell JSON doesn't require member names to be unique, only [recommended](https://tools.ietf.org/html/rfc7159#section-4).

**Comment by iSazonov** [comment]
:-) I believe implementations "MUST" follow "SHOULD recommendations".

In any case I think `JsonConvert.DeserializeObject` works incorrectly.

**Comment by bergmeister** [comment]
I found the first 2 answers [here](https://stackoverflow.com/questions/21832701/does-json-syntax-allow-duplicate-keys-in-an-object) interesting and their statement is basically that although it is valid JSON from a puristic point of view, JSON parsing libraries have and can choose different behaviours without conflicting with the standard. Normally one should trust the foundation, which is `Newtonsoft.Json`, but I am with @iSazonov that it's behaviour is sub-optimal. If there is a way of at least detecting the duplicates then at least a warning would be nice. A detection should be possible using a custom converter type when calling `JsonConvert.DeserializeObject` but it might come at a higher computational cost.

**Comment by iSazonov** [comment]
If the standard say "SHOULD" it allows for a _reasonable_ deviation from the standard. This means that the API must have the option to turn on or off duplicate keys.

**Comment by bergmeister** [comment]
According to the author of `Newtonsoft.Json` [here](https://github.com/JamesNK/Newtonsoft.Json/issues/931#issuecomment-224104005) it does not seem to be possible, therefore a different library might be need to be used unfortunately.

**Comment by SteveL-MSFT** [comment]
Is there a known use case that depends on duplicate keys?  Otherwise, based on the standard's recommendation, I don't think we must support it and warning the user is sufficient.

**Comment by iSazonov** [comment]
Neton.Json is very popular library - if they don't fix (won't fix) we can ignore this in code and only add notes in docs.
