### ISSUE TITLE
Escape character does not pass through double quotes

### ISSUE THREAD

**Issue by jamesbannan** [PowerShell/PowerShell#5200]
I am trying to pass a query string through to the Azure CLI from within a PowerShell session. I have a working query for Azure CLI which has been tested against bash:

```bash
az image list --query "[?contains(tags.\"image-offer\",'Ubuntu')]"
```
This returns the correct query string which is:
```
"[?contains(tags."image-offer",'Ubuntu')]"
```
The double quotes around "image-offer" are needed for the query to work properly. This behaviour is not the same when the query is run in PowerShell (replacing the '\' escape characters with '`')

Steps to reproduce
------------------

```powershell
az image list --query "[?contains(tags.`"image-offer`",'Ubuntu')]"
```

Expected behavior
-----------------

```
"[?contains(tags."image-offer",'Ubuntu')]"
```

Actual behavior
---------------

```
"[?contains(tags.image-offer,'Ubuntu')]"
```
And the query fails as the double quotes are missing

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta.8
PSEdition                      Core
GitCommitId                    v6.0.0-beta.8
OS                             Darwin 17.0.0 Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by Jaykul** [comment]
The problem is that you're calling a native cli app ... and PowerShell does stuff, but then the cli does more stuff. Did you try putting the `\` in too?

```posh
az image list --query "[?contains(tags.\`"image-offer\`",'Ubuntu')]"
```

Otherwise, you need to either use the `--%` to tell PowerShell to stop processing your stuff
Or use start-process so you can quote the whole block of parameters at once

**Comment by jamesbannan** [comment]
Hi @Jaykul - thanks for the update. I didn't try using the ```\``` escape character but I will give it another go. As a workaround I changed the tag name format from ```image-offer``` to ```imageOffer``` - but I will go back and try your suggestions.

**Comment by iSazonov** [comment]
Old issue without discussion.
