### ISSUE TITLE
$PSBoundParameters contains vestigial arguments from prior records

### ISSUE THREAD

**Issue by alx9r** [PowerShell/PowerShell#5202]
This behavior exists since at least version 4, but I have diagnosed this as the cause of countless unexpected failures so I'm proposing that it be addressed somehow.

`$PSBoundParameters` seems to be customarily used to pass parameters from one function to another function whose interface is substantially similar.  The problem is that `$PSBoundParameters` seems to retain the _last_ value bound to each parameter even if no value was bound to the parameter for the current record.  The presence of such vestigial arguments creates problems for using `$PSBoundParameters` as arguments to another function with the same interface because it can easily contain unexpected and invalid combinations of arguments.  

Anytime all of the following are true, a latent bug probably exists:

* `$PSBoundParameters` is used to pass parameters to a function with the expectation that parameter binding with the callee would occur in the same manner as occurred for the caller.
* The function accepts pipeline input on two or more parameters where one or more parameters may be omitted.

FWIW, I encounter such bugs approximately one a week.

Steps to reproduce
------------------

```powershell
class a {}
class b {}

function f {
    param
    (
        [Parameter(ParameterSetName='a',ValueFromPipeline)][a]$A,
        [Parameter(ParameterSetName='b',ValueFromPipeline)][b]$B
    )
    process
    {
        try
        {
            g @PSBoundParameters
        }
        catch
        {
            Write-Host ($PSBoundParameters | Out-String)
            throw
        }
    }
}

function g {
    param
    (
        [Parameter(ParameterSetName='a',ValueFromPipeline)][a]$A,
        [Parameter(ParameterSetName='b',ValueFromPipeline)][b]$B
    )
    process { $A,$B }
}

[a]::new(),[b]::new() | f
```

Expected behavior
-----------------

```none
a
b
```

Actual behavior
---------------

```none
a

Key Value
--- -----
A   a
B   b

g : Parameter set cannot be resolved using the specified named parameters.
At C:\Users\un1\Desktop\test.ps1:14 char:13
+             g @PSBoundParameters
+             ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [g], ParentContainsErrorRec
   ordException
    + FullyQualifiedErrorId : AmbiguousParameterSet,g
```

Environment data
----------------

```powershell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta.8
PSEdition                      Core
GitCommitId                    v6.0.0-beta.8
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by alx9r** [comment]
FWIW this can be worked around using [a somewhat cumbersome pair of functions](https://github.com/alx9r/BootstraPS/blob/30bf72d6cd1605c3aaedf610374810262972c94f/BootstraPS.psm1#L66-L119).  With the fix applied, a function looks something like this:

```PowerShell
function f
{
    param
    (
         # bunch of pipeline parameters
    )
   begin
    {
        $CommandLineParameters = $PSBoundParameters | BeginFixPSBoundParameters
    }
    process
    {
        $BoundParameters = $CommandLineParameters | ProcessFixPSBoundParameters $PSBoundParameters
        # use @BoundParameters instead of @PSBoundParameters in the process block
    }
}
```

You can find a [real-world example here](https://github.com/alx9r/BootstraPS/blob/30bf72d6cd1605c3aaedf610374810262972c94f/BootstraPS.psm1#L2822-L2879).

**Comment by tlindsay42** [comment]
Just ran into this one too and was able to duplicate in v6.0.2 and v6.1.0-preview.4.  

# Additional Context

* I am **only** able to duplicate this issue if multiple ParameterSets are utilized from the pipeline input object set.
* I am **not** able to duplicate this issue when the same ParameterSet is utilized for all pipeline input objects.
* I can duplicate this issue with pipeline input defined by either property name, by value, or a combination thereof.
* I can duplicate this issue with parameters set to standard types such as `[string]` or `[int]`, not just custom classes.
* The first time a parameter is invoked in the pipeline, all subsequent calls to `$PSBoundParameters` list that parameter with that value, regardless of whether that same parameter was actually bound or not, or set to a different value. 

# Environments

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.4
PSEdition                      Core
GitCommitId                    6.1.0-preview.4
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by KevinMarquette** [comment]
I just ran into this one when piping objects that had different properties into a function. This caused the values from the first object to show up in the PSBoundParameters of the second object.

Here is an example that reproduces the issue:

    $list = @(
        [pscustomobject]@{
            Name='first';
            MaximumVersion='1.1.1'
        },
        [pscustomobject]@{
            Name='second';
            MinimumVersion='2.2.2'
        }
    )
    function pipetest
    {
        [cmdletbinding()]
        param(
            [Parameter(ValueFromPipelineByPropertyName=$true,
                    Position=0)]
            [ValidateNotNullOrEmpty()]
            [string]
            $Name,

            [Parameter(ValueFromPipelineByPropertyName=$true)]
            [ValidateNotNull()]
            [string]
            $MinimumVersion,

            [Parameter(ValueFromPipelineByPropertyName=$true)]
            [ValidateNotNull()]
            [string]
            $MaximumVersion
        )
        process
        {
            Write-Verbose -Verbose ('Parameters        name [{0}] min [{1}] max [{2}]' -f $Name, $MinimumVersion,$MaximumVersion)
            Write-Verbose -Verbose ('PSBoundParameters name [{0}] min [{1}] max [{2}]' -f $PSBoundParameters.Name, $PSBoundParameters.MinimumVersion,$PSBoundParameters.MaximumVersion)
        }
    }

    $list | pipetest

In this example, I have 2 objects where one specifies a min version and the other specifies the max version. The verbose output show both the raw parameters and the `$psboundparameters`

    VERBOSE: Parameters        name [first] min [] max [1.1.1]
    VERBOSE: PSBoundParameters name [first] min [] max [1.1.1]
    VERBOSE: Parameters        name [second] min [2.2.2] max []
    VERBOSE: PSBoundParameters name [second] min [2.2.2] max [1.1.1]

The second object looks like it has a max version if you look at the PSBoundParameters but this is a carry over value from the first object. 

I ran into this issue when trying to pipe a list of module into `Find-Module` and getting validation errors on the version numbers.

**Comment by KevinMarquette** [comment]
It looks like the same $PSBoundParameters dictionary is reused over and over for each loop of the process block. So changes to the dictionary will persist if a parameter is not overridden.

If you return the psboundparameters out of a function, you can see that they are all a reference to the same thing.

    function pipetest2
    {
        [cmdletbinding()]
        param(
            [Parameter(ValueFromPipelineByPropertyName)]
            $Name,
            [Parameter(ValueFromPipelineByPropertyName)]
            $MinimumVersion,
            [Parameter(ValueFromPipelineByPropertyName)]
            $MaximumVersion
        )
        process
        {
            $PSBoundParameters
        }
    }
    $output = $list | pipetest2
    $output[0] -eq $output[1]
