### ISSUE TITLE
PrioritySendDataCollection.Clear() can throw a null reference exception

### ISSUE THREAD

**Issue by dantraMSFT** [PowerShell/PowerShell#5219]
If the system is not configured correctly for SSL, enter-pssession fails. However, the error that is reported is a NullReferenceException at PrioritySendDataCollection.Clear() due to missing null check. The result is a misleading error that results in investigating the wrong issue.
This was seen on Debian 9 which did not have openssl 1.0.0.

Steps to reproduce
------------------
Create an instance of PrioritySendDataCollection
Call Clear()

Expected behavior
-----------------
The call is silently ignored.

Actual behavior
---------------
A NullReferenceException is thrown when attempting to dereference the null _syncObject array.
Early test results - Debian9 has a catastrophic failure after running new-pssession - the shell exits with

**Comment by iSazonov** [comment]
Fixed in https://github.com/PowerShell/PowerShell/pull/5622
