### ISSUE TITLE
Newtonsoft.Json version (10.0.1) that ships with PowerShell 6.0 Beta 8 has Concurrent Collections deserialization bug.

### ISSUE THREAD

**Issue by twitchax** [PowerShell/PowerShell#5224]
Update to Newtonsoft.Json >= 10.0.3 will fix this issue.  Unfortunately, even if a `PSCmdlet` references the newer version, the version of Newtonsoft.Json that ships with PowerShell 6.0 is loaded instead of the version referenced by the `PSCmdlet` library because PowerShell 6.0 owns the AppDomain and configuration.

See Azure/azure-powershell#4488 where this issue has been shown to affect Azure PowerShell Core.
See JamesNK/Newtonsoft.Json#1294 where this was first shown to affect Concurrent Collections deserialization in Newtonsoft.Json for .NET Core 2.0.
See [Newtonsoft.10.0.3 release notes](https://github.com/JamesNK/Newtonsoft.Json/releases/tag/10.0.3) which identifies that the fix went into Newtonsoft.Json.10.0.3.

Steps to reproduce
------------------

```powershell
Install-Module AzureRM.Netcore
Save-AzureRmContext
Import-AzureRMContext
```

Expected behavior
-----------------

Deserialization of a `ConcurrentDictionary` works in PowerShell 6.0.

Actual behavior
---------------

It does not.

**Comment by twitchax** [comment]
Note: it appears as though this change has been made in the repo.  Feel free to close when Beta 9 ships.

**Comment by SteveL-MSFT** [comment]
Confirmed that building master you get 10.0.3
