### ISSUE TITLE
Binary Module on Mac Problem

### ISSUE THREAD

**Issue by christophwille** [PowerShell/PowerShell#5234]
I followed this document https://github.com/PowerShell/PowerShell/blob/master/docs/cmdlet-example/command-line-simple-example.md to build https://github.com/christophwille/ilspy-pscore/tree/master/src

The module works with 5.1 and 6.0b8 on Windows FCU (a dev box with .NET Core SDK installed). When built on Mac, it errors out https://github.com/christophwille/ilspy-pscore/issues/1
```
Import-Module .\ICSharpCode.Decompiler.PSCore.dll
$asm = Get-Assembly .\ICSharpCode.Decompiler.Extensions.dll
$asm
```
Those lines work. When I call eg 
```
$classes = Get-DecompiledTypes $asm -Types class
```
it errors out 

```
PS /Users/christophw/GitWorkspace/ilspy-pscore/src/ICSharpCode.Decompiler.PSCore/bin/Debug/netstandard2.0> $classes = Get-DecompiledTypes $asm -Types class
Get-DecompiledTypes : Specified argument was out of the range of valid values.
At line:1 char:12
+ $classes = Get-DecompiledTypes $asm -Types class
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-DecompiledTypes], ArgumentOutOfRangeException
    + FullyQualifiedErrorId : System.ArgumentOutOfRangeException,ICSharpCode.Decompiler.PSCore.GetDecompiledTypesCmdlet
```

The first cmdlet loads only a 461 compiled assembly (Mono Cecil). All other cmdlets load icsharpcode.decompiler.dll which is a netstandard2 assembly. Given the notes in the aforementioned guideline on writing a binary module (netstandard.dll issues on Windows) - is there a similar issue on Mac?

**Comment by Jaykul** [comment]
That netstandard.dll problem is a problem for anything using full .net prior to the new 4.7.1 which just shipped in the Windows 10 October 2017 update (aka "Fall Creators Update").

That is, if you're using Mono (or .Net Framework prior to 4.7.1) it's not fully .Net Standard 2 compliant, and you're going to have to ship that assembly.

**Comment by christophwille** [comment]
Where does Mono come in with PS Core?

**Comment by rkeithhill** [comment]
I don't think PS Core uses Mono.  I suspect it is one of the assemblies in your module.  Looks like [Mono 5.2.0](http://www.mono-project.com/docs/about-mono/releases/5.2.0/) is starting to support netstandard2.0.  Not sure how good that support is atm.

**Comment by christophwille** [comment]
Can we agree that Mono is not in the picture? 

How would I be able to debug this problem where zilch information is given? Is there something in PSCore to get eg binding logs or something else? Aside: tested with Beta 9, same behavior.

**Comment by christophwille** [comment]
I am pleasantly surprised that the VSMac debugger can attach to pwsh and debug my binary module. I will report back, but it seems the assemblies themselves are loaded properly.

**Comment by christophwille** [comment]
Turns out that an actual exception happens in ProcessRecord. However, it is ToString()-d in a way that nothing is shown, even now that I wrapped it with WriteError (had to resort to also writing verbose output). So it is actually a problem on my end but exception output from PS didn't help pointing to the right place at all.
