### ISSUE TITLE
why pwsh

### ISSUE THREAD

**Issue by ThangarasuS** [PowerShell/PowerShell#5241]
Hello Team,

why was the standard powershell command was changed pwsh?  I think it would be better if its still remains powershell to launch the shell, so that there wont be any confusion.

Steps to reproduce
------------------

```powershell

```

Expected behavior
-----------------

```none

```

Actual behavior
---------------

```none

```

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by iSazonov** [comment]
Please read the discussion https://github.com/PowerShell/PowerShell/issues/4214
