### ISSUE TITLE
Consider creating a string hash method that produces a repeatable hash code.

### ISSUE THREAD

**Issue by dantraMSFT** [PowerShell/PowerShell#5250]
The issue was encountered during implementation of syslog logging.  The output from String.GetHashCode() can vary for a given string when the process or underlying Core CLR version changes. While it's valid for usage in hash tables, it is not intended to be persisted or comparable across processes.

The solution would be to provide a GetHashCode method on a utility class, such as StringUtil that provides the same hashing algorithm without incorporating variable data.  

A good starting point would be GetLegacyNonRandomizedHashCode in https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/String.Comparison.cs

**Comment by iSazonov** [comment]
[Previous discussion](https://github.com/PowerShell/PowerShell/pull/5144#discussion_r146748753)

I don't understand the _purpose_ for which we're writing this hash in log. Can anybody clarify?

If we were to use Git SHA hash, we would copy it to Git and find the exact commit and version tag, or we would find the same of even Google with this hash. Also we always write GitCommitId in log at startup - so we can easy find exact version in the log.
If we calculate our custom hash, it will be unique, but how do we identify the version? We can not do copy-paste-search.

**Comment by SteveL-MSFT** [comment]
I believe the original issue is that PSCore6 side-by-side with another PSCore6.x version, there needs to be a way to filter out traces for a particular version of PSCore6 as all the traces go to the same log.  I think for this scenario, using `$psversiontable.gitcommitid` is probably fine.  Most users are using the official builds and that value is pretty short.  Developers running custom builds can make use of the full hash.

**Comment by iSazonov** [comment]
13 vs 57 chars. Having 57 chars in development builds looks overkill.

As @daxian-dbw  had mentioned we can easily get Git SHA in the same way we're getting GitCommitId from SMA.dll attribute and use 7-14 first chars from the hash.

**Comment by SteveL-MSFT** [comment]
Probability says first 7 chars is probably ok, but it's not guaranteed.

**Comment by dantraMSFT** [comment]
I'm closing this issue. The use case no long longer exists in syslog.
