### ISSUE TITLE
Ctrl + L(Clearscreen shortcut) doesn't works correctly.

### ISSUE THREAD

**Issue by ishanjain28** [PowerShell/PowerShell#5251]
Steps to reproduce
------------------
1. Open Poweshell. 
2. Type `ping 8.8.8.8`, This is kind of necessary to show my problem. Any command that prints >1 line of output'll do just fine. 
3. Now, Type "some text, Doesn't matters what it is". So, Now your shell will look something like this. 
    
    `powershell C:> some text, Doesn't matters what it is`
4. Now press `Ctrl+L`(On Windows). 

Expected behavior
-----------------

It should clear the output printed by the `ping` command and move the prompt to the top of screen without deleting the text "some text, Doesn't matters what it is".  This is the behaviour shown by pretty much all shells on linux. 

Actual behavior
---------------

It just prints `^L` to console. Sometimes it does what I mentioned in the "Expected behaviour" section but most of the time it just prints `^L` in console which is quite annoying. 

I am a begninner in C# and if someone can give me some pointers on what's causing this problem I can try fixing it. 

Regards 
Ishan Jain

PS: 
I searched Github issues, Known Issues page with terms like "Clear screen", "Ctrl+L" and "^L" but didn't found anything relevant.

**Comment by SteveL-MSFT** [comment]
What version of PowerShell are you using and what version of PSReadline?  This doesn't repro for me

**Comment by ishanjain28** [comment]
I updated Windows 10 on my laptop from 1503 to 1703 and it seems to work fine now. Powershell Version is 5.1.1 and I couldn't find a way to get the version of PSReadline. I'll close this issue for now and reopen if this happens again.

**Comment by ishanjain28** [comment]
This was a Windows Powershell related bug so I should have read the Readme correctly and raise this issue on UserVoice. Apologies for wasting time.
