### ISSUE TITLE
Beta.9 - Cmdlet Enter-PSsession -ssh stop working between OS's (Linux/Windows)

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#5253]
This was working in version Beta.8.  Enter-Pssession cmdlet not connection to other system after upgrading/installing Beta.9 using openssh.

Steps to reproduce
------------------

```powershell
## - Either connecting Linux to Windows, or from Windows -to-Linux - fails:
Enter-PSsession -hostname lxwinsystem -username user1

```

Expected behavior
-----------------
To connect without any issues.

```none

```

Actual behavior
---------------
Error message:
```none
PS C:\Program Files\PowerShell\6.0.0-beta.9> enter-pssession -HostName venus -UserName maxt
enter-pssession : The background process reported an error with the following message: The SSH client session has
ended with error message: ssh: connect to host venus port 22: Connection timed out.
At line:1 char:1
+ enter-pssession -HostName venus -UserName maxt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Enter-PSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.PowerSh
   ell.Commands.EnterPSSessionCommand
```

Environment data
----------------
Windows 10 Insider Build 16299
Windows: openssh v0.0.21.0 is the latest version available based on your source(s).
Ubuntu 16.04.3
Linux: OpenSSH 7.2p2/OpenSSL 1.0.2g

```powershell
> $PSVersionTable
PS C:\Program Files\PowerShell\6.0.0-beta.9> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta.9
PSEdition                      Core
GitCommitId                    v6.0.0-beta.9
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
![b9_linux_openssh_01_2017-10-27_13-08-48](https://user-images.githubusercontent.com/19892435/32088912-714685c8-bb19-11e7-8b89-eb42de14410c.png)

**Comment by iSazonov** [comment]
@PaulHigin Could you please comment the Issue?

**Comment by MaximoTrinidad** [comment]
Ha!!  Lucky me.  I'm at the PowerShell Conference Asia and @joeyaiello is here.  

He pointed me in the right direction. There's a bug that PowerShell name still been used as the subsystem name in the OpenSSH file sshd_config.

I thought the subsystem has been already renamed to use "pwsh".  I had to change back to be "powershell"

```
File: sshd_config (subsystem line)
Windows:
Subsystem	powershell	C:\Program Files\PowerShell\6.0.0-beta.9\pwsh.exe -sshs -NoLogo -NoProfile

Linux:
Subsystem	powershell	pwsh.exe -sshs -NoLogo -NoProfile
```
This need to be corrected.

Thanks @joeyaiello

**Comment by bergmeister** [comment]
@MaximoTrinidad I already updated the documentation in this commit [here](https://github.com/PowerShell/PowerShell/commit/715fe94c37fd258a4026f0b7a1448720e2e0c55d) but I think that leaving the subsystem name as it is is ok.

**Comment by MaximoTrinidad** [comment]
No worries! I appreciate the quick response.

Thanks
