### ISSUE TITLE
Dependencies instalation error

### ISSUE THREAD

**Issue by ElectronicaXAB3** [PowerShell/PowerShell#5254]
Platform
------------------

Windows 7 x86 (no SP)

Steps to reproduce
------------------

powershell (PowerShell-6.0.0-beta.9-win-x86.msi) doesn't allow installation without "Universal C Runtime", but "Universal C Runtime" says "The update is not applicable to your computer". I tried "Windows6.1-KB3118401-x86.msu" from the zip file. "Windows Management Framework" outputs the same error. What am I doing wrong?

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
CLRVersion                     2.0.50727.4927
BuildVersion                   6.1.7600.16385
PSVersion                      2.0
WSManStackVersion              2.0
PSCompatibleVersions           {1.0, 2.0}
SerializationVersion           1.1.0.1
PSRemotingProtocolVersion      2.1
```

**Comment by SteveL-MSFT** [comment]
Universal C Runtime requires SP1 on Win7 (it's noted in the Readme within the zip)
