### ISSUE TITLE
powershell: not found - after installing

### ISSUE THREAD

**Issue by sergey-s-betke** [PowerShell/PowerShell#5264]
After installation powershell (6.0.0-beta.9-1.ubuntu.14.04) I have error when launch powershell from command line:
- https://travis-ci.org/Metrolog/marks/builds/294103395
- https://circleci.com/gh/Metrolog/marks/71

Why powershell not found after installation?

**Comment by markekraus** [comment]
@sergey-s-betke  please see the release notes https://github.com/PowerShell/PowerShell/releases/tag/v6.0.0-beta.9

> Note: Starting from this release, the PowerShell Core executable is renamed to be `pwsh` (see the issue #4214 for the discussion details). We also start to provide PowerShell Core binary archive packages for Linux and macOS for advanced deployment.

**Comment by sergey-s-betke** [comment]
Thank You, @markekraus! It is worked!
