### ISSUE TITLE
Strange behavior with Get-ChildItem

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/PowerShell#5269]
Steps to reproduce
------------------

```powershell
$Path='C:\temp'
#remove-item "$Path\TestPS"  -recurse
md "$Path\TestPS"
get-childitem -path "$Path\TestPS\F*.txt" -File -Recurse #OK no file

md "$Path\TestPS\D1"
get-childitem -path "$Path\TestPS" -Directory -Recurse #Ok one directory
get-childitem -path "$Path\TestPS\*" -Directory -Recurse #NOK no result

"Test" > "$Path\TestPS\D1\File1.txt"
get-childitem -path "$Path\TestPS\F*.txt" -File -Recurse #OK one file
get-childitem -path "$Path\TestPS" -File -Recurse #OK one file

get-childitem -path "$Path\TestPS\*" -File -Recurse #NOK no result

#Add a file into the 'root' of the search 
"Test" > "$Path\TestPS\File2.txt"
get-childitem -path "$Path\TestPS\*" -File -Recurse #OK two files !!! Different !!!
get-childitem -path "$Path\TestPS\*" -Directory -Recurse #OK one directory !!! Different !!! 


remove-item "$Path\TestPS\File2.txt"
#The 'root' of the search is empty 
get-childitem -path "$Path\TestPS\*" -File -Recurse #NOK no result
get-childitem -path "$Path\TestPS\*" -Directory -Recurse #NOK no result

#original path
#Get-ChildItem -Path 'C:\Users\laurent\AppData\Local\Mozilla\Firefox\Profiles\*.default*' -File -Rec

#it works
#Get-ChildItem -Path 'C:\Users\laurent\AppData\Local\Mozilla\Firefox\Profiles\*.default*' -Rec|Where-Object {-not $_.PSIsContainer}
```

Expected behavior
-----------------
The following calls must return existing files or directories :
```Powershell
get-childitem -path 'C:\Temp\TestPS\*" -File -Recurse
get-childitem -path 'C:\Temp\TestPS\*" -Directoyr -Recurse
```

Actual behavior
---------------
When the 'root' of the search ('C:\Temp\TestPS') is empty, the search do not return all entries :

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta.9
PSEdition                      Core
GitCommitId                    v6.0.0-beta.9
OS                             Microsoft Windows 6.1.7601 S
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
Same problem with For Windows PowerShell v 5.1.14409.1012 :
```powershell
> $PSVersionTable 
Name                           Value
----                           -----
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.14409.1012}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by SteveL-MSFT** [comment]
It seems that the behavior is that if you have a wildcard, then the recursion is applied to the results of that wildcard expansion.  Assume a folder structure like:

```none
testPS
  d1
    d2
```

`gci testPS\*` returns `d1` as expected
now, if you use `gci testPS\* -recurse`, the `-recurse` is applied to `d1`, not `testPS` due to the wildcard and `d2` is returned.

I agree that the behavior may not seem intuitive, but it does seem (somewhat) logical.  I'd be concerned that a change here would not be a breaking change worth making.  Perhaps we should just update the documentation?

**Comment by LaurentDardenne** [comment]
>>Perhaps we should just update the documentation?

Yes.

1) According to the help file 'about_Wildcards' :
```

  Wildcard Description        Example  Match             No match
  -------- ------------------ -------- ----------------- --------
  *        Matches zero or    a*       A, ag, Apple      banana
           more characters
```
Are these statements equivalent (with my first exemple) ?
```Powershell
$Path='C:\temp'
get-childitem -path "$Path\TestPS\*" -Recurse 
get-childitem -path "$Path\TestPS" -Recurse 
```

2) According to the help file 'FileSytem' (DYNAMIC PARAMETERS) :
```
   -File <System.Management.Automation.SwitchParameter>
       Gets files.

       The File parameter was introduced in Windows PowerShell 3.0.

       To get only files, use the File parameter and omit the Directory parameter. To exclude files, use the
       Directory parameter and omit the File parameter, or use the Attributes parameter.

```
Are these statements equivalent (with my first exemple) ?
```Powershell
$Path='C:\temp'
get-childitem -path "$Path\TestPS\*" -File  -Recurse 
get-childitem -path "$Path\TestPS\*"  -Recurse |Where {-not $_.PSisContainer} 
```
If for this last example these statements are equivalent, in my case the resultat is different.

**Comment by SteveL-MSFT** [comment]
I missed the details about `File` and agree that it's broken.

**Comment by LaurentDardenne** [comment]
@SteveL-MSFT this fix do not should be backported to Windows PowerShel 5.1 ?

**Comment by SteveL-MSFT** [comment]
@LaurentDardenne the concern would be that this is a breaking change so at this time not considered to be ported to 5.1

**Comment by LaurentDardenne** [comment]
OK, thanks.
How to find the list of these bugs / difference ?
Can the addition of a label be considered here or should we duplicate this issue on Uservoice?

**Comment by SteveL-MSFT** [comment]
@LaurentDardenne the label indicates we're considering backporting it to Windows PowerShell 5.1.  At the time of actual port, we'll determine if it's too risky to port due to risk of regression (since the PSCore6 code base has now deviated quite a bit from the Windows PowerShell code base).  Perhaps I'll create a new label `Ported-WindowsPowerShell51` to indicate PRs that have been ported.

**Comment by LaurentDardenne** [comment]
@SteveL-MSFT 
There is the label '_Breaking-Chang_e' which is very useful when porting code v5.n to v6.n
A '_Ported-WindowsPowerShell51_' label can be useful information.

This fix does not have the 'Breaking-Change' label, but in the case of a 6.n code port, (based on this corrected behavior) to-> 5.n, how do I find these cases?
A '_NotPorted-WindowsPowerShell51_' label ? :-)
Or a note inside the Changelog.md file ?

It is information intended for the users and not for the monitoring of the project.

**Comment by SteveL-MSFT** [comment]
@LaurentDardenne this issue should have had the `Breaking-Change` label, was just missed.  We usually have the `Breaking changes` at the top of the ChangeLog.  We have a work item to have better documentation on porting scripts/modules from 5.1 to 6.
