### ISSUE TITLE
Tweak to $PSVersionTable.OS to make it more useful

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShell#5282]
I'm finding the output of Python's mplatform command more useful in helping me determine which distro I'm running on.  I see no reason why PowerShell's `$PSVersionTable.OS` property couldn't be just as useful.

Steps to reproduce
------------------
Run these two commands
```powershell
$PSVersionTable.OS
python3 -mplatform
```
The output is respectively:
```
Linux 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014
Linux-4.4.0-43-Microsoft-x86_64-with-Ubuntu-16.04-xenial
```

Expected behavior
-----------------
I was hoping from PowerShell's `$PSVersionTable.OS` I could easily tell that I'm on A) Ubuntu and B) the version of Ubuntu.  Like I can with Python.

Actual behavior
---------------
PowerShell gives me the kernel release version number only.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta.9
PSEdition                      Core
GitCommitId                    v6.0.0-beta.9
OS                             Linux 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
`$PSVersionTable.OS` is simply `[System.Runtime.InteropServices.RuntimeInformation]::OSDescription`.  Perhaps you can open an issue in corefx repo so that `OSDescription` is more like `python3 -mplatform`?  It seems like all the information is available via `lsb_release` and they just need to stitch it together.

**Comment by MaximoTrinidad** [comment]
Hum! In my opinion, you'll probably use "python -mplatform" command as Python 2.7 is the main and default version use by the OS. All other versions of Python (ie. 3.5, 3.6 (Anaconda)) exist, or installed separately, add value to develop on a updated version.

I notice on my system executing both "python -mplatform" and "python3 -mplatform" give me the same result.  
```
"Linux-4.10.0-38-generic-x86_64-with-Ubuntu-16.04-xenial"
```
But, when I change my python environment to Anaconda (Python 3.6) using "update-alternative" I'll get different results:
"Linux-4.10.0-38-generic-x86_64-with-debian-stretch-sid"

Using "python -mplatform" could give mix results when working with different versions of Python.

:)

**Comment by rkeithhill** [comment]
Perhaps PowerShell should instead use what you are already using in `build.psm1`:

https://github.com/PowerShell/PowerShell/blob/1c446c1be4ac10dd53a1f822e78801dc3da361d0/build.psm1#L130

**Comment by SteveL-MSFT** [comment]
@rkeithhill we could certainly construct it ourselves, but it seems that it would be better relying on corefx for consistency particularly as we support more and more distros
