### ISSUE TITLE
Pwrshplugin Config File Paths Should be Validated Before Use

### ISSUE THREAD

**Issue by mirichmo** [PowerShell/PowerShell#5286]
The paths to CoreCLR and PSHOME read by pwrshplugin should be validated before use to protect against bad input.

A potential API to use is [PathIsDirectory](https://msdn.microsoft.com/en-us/library/windows/desktop/bb773621(v=vs.85).aspx).

It is part of api-ms-win-shlwapi-ie-l1-1-0.dll, but that API set is not present on Windows 7 (shlwapi.dll is though).

**Comment by SteveL-MSFT** [comment]
PathIsDirectory relies on shlwapi which is present on Win7, but not on win-arm builds.  I think using CreateFile() is sufficient.
