### ISSUE TITLE
New-Item -Type Directory -Force # doesn't error when it should

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#5290]
When a **File** exists, and you try to create a **Directory** using `New-Item -Force`, it neither errors nor creates the directory.  Note that the opposite works: if a _Directory_ exists and you try to create a _File_, it errors -- _as it should_.

Steps to reproduce
------------------
```powershell
New-Item Folder -Type Directory -Force
New-Item Folder -Type File -Force
New-Item File -Type File -Force
New-Item File -Type Directory -Force
```

Expected behavior
-----------------

There should be two errors. Ideally, they should indicate that the item already exist but is the wrong type

```none
New-Item : Cannot create a File with the same name as a Folder 'C:\Users\You\Folder'
New-Item : Cannot create a Folder with the same name as a File 'C:\Users\You\File'
```

Actual behavior
---------------

There will only be an error for `-Type File` but not for `-Type Directory`, and the error won't be helpful:

```none
New-Item : Access to the path 'C:\Users\You\Folder' is denied.
```

Environment data
----------------

This has been the behavior "forever" and still is, at least in beta 8:

```none
Name                           Value
----                           -----
PSVersion                      6.0.0-beta.8
PSEdition                      Core
GitCommitId                    v6.0.0-beta.8
OS                             Microsoft Windows 10.0.17025
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
Good find; to avoid confusion, can you please change _Folder_ to _File_ in 
> if a _Directory_ exists and you try to create a _Folder_,

**Comment by kvprasoon** [comment]
I see something similar in 6.0.1 preview.

![image](https://user-images.githubusercontent.com/12897753/38571194-56ec415c-3cdf-11e8-93d9-70b00c4be1bd.png)

**Comment by zhenggu** [comment]
Is there any API of dotnet that we can check the type (such as file, directory, softlink, hardlink, etc...) of file? If not, I think we can only use Directory.Exists and File.Exists to check this.

**Comment by Jaykul** [comment]
@kvprasoon it "works" because by default it creates a _File_ and the bug exists only when trying to create a _Directory_

@zhenggu yes, `Directory.Exists(path)` and `File.Exists(path)` are really the only tools, as far as I know. That should be that's needed to fix the problem, anyway, 😉

**Comment by xtqqczze** [comment]
This is still an issue for the current release, please reopen.
