### ISSUE TITLE
Cannot load PSReadline when lauching from rebol

### ISSUE THREAD

**Issue by lepinekong** [PowerShell/PowerShell#5294]
Steps to reproduce
------------------

download rebol http://www.rebol.com/download-view.html
launch rebol console and type
 call/show "powershell"

From red lang console, it's even worst 
Powershell shows up without finishing initialization
http://www.red-lang.org/

Expected behavior
-----------------

Powershell loads PSReadline

```

Actual behavior
---------------
Powershell doesn't load PSReadline

```none

```

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by markekraus** [comment]
I cannot repro this on Windows 10. 

running

```none
call/show "pwsh"
```

from the rebol console, PowerShell Core launches and PSReadline is loaded and operating normally.

**Comment by lzybkr** [comment]
Is rebol an x86 program and you're running on x64? If so, this is a known issue with Windows PowerShell, you can fix by installing PSReadLine - just run `Install-Module PSReadLine` from the PowerShell you launched from rebol, or run `c:\windows\syswow64\WindowsPowerShell\v1.0\powershell.exe -command "Install-Module PSReadLine"`
