### ISSUE TITLE
SeServiceLogonRight is not getting cleaned up after exiting JEA session

### ISSUE THREAD

**Issue by Earl-S** [PowerShell/PowerShell#5296]
My servers are all getting a new entry in SeServiceLogonRight (Log on as a service) for every JEA connection made and they are not getting cleaned up. The SID is S-1-5-94-xxx with the name of "WinRM Virtual Users\WinRM VA_xxx_Domain_UserID" where xxx is the next numeric number, Domain and UserID are for the person connected to the endpoint. I have some servers that have over 500 entries in a few days that only differ by the incremented number (each time an automated process runs it appears to create another entry).

Reference this bug report on JEA where I was asked to create a new one here:
https://github.com/PowerShell/JEA/issues/27

Steps to reproduce
------------------
Create a basic JEA endpoint with Session, Role, and Module files, then Register the endpoint.
Run Invoke-Command against the new endpoint several times.
Open up Local Security Policy and see that "Log on as a service" (SeServiceLogonRight) has had a new entry added for each instance of Invoke-Command.

Expected behavior
-----------------
JEA should remove the ID from the SeServiceLogonRight when the session closes.

Actual behavior
---------------
JEA leaves the IDs under SeServiceLogonRight indefinitely.

Environment data
----------------
PSVersion 5.1.14409.1012                                                                                                                             
PSEdition Desktop                                                                                                                                    
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...}                                                                                                                    
BuildVersion 10.0.14409.1012                                                                                                                            
CLRVersion 4.0.30319.42000                                                                                                                            
WSManStackVersion 3.0                                                                                                                                        
PSRemotingProtocolVersion 2.3                                                                                                                                        
SerializationVersion 1.1.0.1

**Comment by pra6hu** [comment]
Is there any update on this?

**Comment by PaulHigin** [comment]
Sorry, I lost track of this issue.  PowerShell remoting authentication and endpoint session creation is performed at the WinRM layer.  I spoke internally with the WinRM folks and they are aware of the issue.  I have also created an internal bug report for them.  

@Earl-S I am closing this issue since it outside PowerShell.  But I suggest you also create a UserVoice (https://windowsserver.uservoice.com/forums/301869-powershell) report.

**Comment by rackley096794** [comment]
This issue has been fixed in Server 2016 with the November 2018 rollup and Server 2019 with the January 2019 rollup.  In addition this right is managed slightly differently - please see the documentation update here:  https://github.com/PowerShell/PowerShell-Docs/pull/3446/files

**Comment by Nick-Rimmer2016** [comment]
Was this ever resolved for Windows 2012R2? I have the exact same issue on this platform.
