### ISSUE TITLE
Escape character notation for unicode and escape characters does not work

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell#5298]
Steps to reproduce
------------------
```powershell
"`u{2195}"
```

The following command outputs Green text.

```powershell
$fgColor = 32 # green
"`e[${fgColor}mGreen text`e[0m"
```

Expected behavior
-----------------
"`u{2195}" should output the character '&#x2195;':

"`e[${fgColor}mGreen text`e[0m" should produce the ANSI escape sequence for Green Text.

Actual behavior
---------------
```none
u{2195}

e[32mGreen texte[0m
```

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.15063.674
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.674
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by markekraus** [comment]
I don't think PowerShelll has Unicode literals support. Closest would be something like this

```powershell
"Some $([char]0x2195) Text"
```

```none
Some ↕ Text
```

**Comment by markekraus** [comment]
@sdwheeler I see that. Maybe that is new to 6.0 and somehow that was added to the older docs. When I look at `get-help about_special_characters` on my local system for 5.1 the `` `u{}`` usage is not listed.

**Comment by rkeithhill** [comment]
I don't see these in the 5.1 docs.  Are you sure you have the version filter set to `6`?

**Comment by markekraus** [comment]
@rkeithhill I see them in 3.0, 4.0, 5.0, 5.1, and 6.0

**Comment by rkeithhill** [comment]
Yes, for about_special_characters.  Something got screwed up there.  But the about_escape_characters topic looks correct - 6 only, right?

**Comment by sdwheeler** [comment]
OK, this appears to be new in v6. The  about_Escape_Characters and about_Special_Characters are duplicate articles. I am consolidating them into one.

**Comment by markekraus** [comment]
Yup, about_escape_characters looks fine.
@sdwheeler can you create an issue in PowerShell-Docs?

**Comment by sdwheeler** [comment]
@markekraus I am already working on this topic via https://github.com/PowerShell/PowerShell-Docs/issues/1370.
