### ISSUE TITLE
Question: How To Find Not Correctly Loaded Files?

### ISSUE THREAD

**Issue by ghost** [PowerShell/PowerShell#5305]
Hello community,

I tried to use SAP dotNET Connector with PowerShell 6, but I got an error message:
`The type initializer for <Module> threw an exception.`
`At line:1 char:1`
`+ [SAP.Middleware.Connector.SAPConnectorInfo]::get_Version()`
`+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : OperationStopped: (:) [], TypeInitializationException`
`    + FullyQualifiedErrorId : System.TypeInitializationException`

I use this on PowerShell 5.1:
`PS C:\Windows\System32\WindowsPowerShell\v1.0> $PSVersionTable`
`Name                           Value`
`----                           -----`
`PSVersion                      5.1.14409.1012`
`PSEdition                      Desktop`
`PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}`
`BuildVersion                   10.0.14409.1012`
`CLRVersion                     4.0.30319.42000`
`WSManStackVersion              3.0`
`PSRemotingProtocolVersion      2.3`
`SerializationVersion           1.1.0.1`
`PS C:\Windows\System32\WindowsPowerShell\v1.0> cd E:\Dummy\NCo`
`PS E:\Dummy\NCo> Add-Type -Path .\sapnco.dll`
`PS E:\Dummy\NCo> Add-Type -Path .\sapnco_utils.dll`
`PS E:\Dummy\NCo> [SAP.Middleware.Connector.SAPConnectorInfo]::get_Version()`
`3.0.19.0`

If I used the same in PowerShell 6 I got the error message:
`PowerShell v6.0.0-beta.9`
`Copyright (C) Microsoft Corporation. All rights reserved.`
`PS E:\Language\PowerShell> cd E:\Dummy\NCo\`
`PS E:\Dummy\NCo> Add-Type -Path .\sapnco.dll`
`PS E:\Dummy\NCo> Add-Type -Path .\sapnco_utils.dll`
`PS E:\Dummy\NCo> [SAP.Middleware.Connector.SAPConnectorInfo]::get_Version()`
`The type initializer for '<Module>' threw an exception.`
`At line:1 char:1`
`+ [SAP.Middleware.Connector.SAPConnectorInfo]::get_Version()`
`+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : OperationStopped: (:) [], TypeInitializationException`
`    + FullyQualifiedErrorId : System.TypeInitializationException`
`PS E:\Dummy\NCo> $PSVersionTable`
`Name                           Value`
`----                           -----`
`PSVersion                      6.0.0-beta.9`
`PSEdition                      Core`
`GitCommitId                    v6.0.0-beta.9`
`OS                             Microsoft Windows 6.3.9600`
`Platform                       Win32NT`
`PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}`
`PSRemotingProtocolVersion      2.3`
`SerializationVersion           1.1.0.1`
`WSManStackVersion              3.0`

So I am searching around and found this [this](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/0b85ed2b-a68a-48e7-8093-c06663221608/the-type-initializer-for-module-threw-an-exception-powershell-wpf-on-server-core-with-net-47?forum=wpf) post. How can I find the not correctly loaded files?

Thanks for tips and hints.

Cheers
Stefan

**Comment by iSazonov** [comment]
Perhaps  SAP dotNET Connector was or is not compatible with PowerShell Core.
