### ISSUE TITLE
Question regarding Antimalware Scan Interface

### ISSUE THREAD

**Issue by dlwyatt** [PowerShell/PowerShell#5308]
I've been looking through the documentation on AMSI, and noticed that it supports several types of clean / dirty results (https://msdn.microsoft.com/en-us/library/windows/desktop/dn889584(v=vs.85).aspx) :

```
typedef enum AMSI_RESULT { 
  AMSI_RESULT_CLEAN                   = 0,
  AMSI_RESULT_NOT_DETECTED            = 1,
  AMSI_RESULT_BLOCKED_BY_ADMIN_START  = 16384,
  AMSI_RESULT_BLOCKED_BY_ADMIN_END    = 20479,
  AMSI_RESULT_DETECTED                = 32768
} AMSI_RESULT;
```

However, when I looked through the PowerShell source code, I noticed that it's only concerned with AMSI_RESULT_DETECTED:

https://github.com/PowerShell/PowerShell/blob/532044f27ae42f2c4cf3fb178b4f88bbf126e5c1/src/System.Management.Automation/engine/runtime/CompiledScriptBlock.cs#L203

Should PowerShell also take action when it get something in the "BLOCKED_BY_ADMIN" result range?

**Comment by SteveL-MSFT** [comment]
cc @PaulHigin

**Comment by iSazonov** [comment]
@SteveL-MSFT Can we close the issue?

**Comment by PaulHigin** [comment]
An update to the code to support the new AMSI codes will be coming in November.  So I think we can close this issue.

**Comment by PaulHigin** [comment]
Whoops, just meant to comment, not close.

**Comment by iSazonov** [comment]
@PaulHigin Do we still need the issue opened?

**Comment by PaulHigin** [comment]
@iSazonov  I feel this issue can be closed.
