### ISSUE TITLE
Beta.9 - Disconnect-PSSession not supporting ssh disconnect sessions.

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#5313]
I doing some testing creating sessions using New-PSSession with both Windows and Linux. Just discover that I can't use the Disconnect-PSSession cmdlet to terminate my ssh session to my Linux box. 

Steps to reproduce
------------------
1. Create PSSession to Windows and Linux systems:
```powershell
$linuxSession = New-PSSession -HostName lxsys1 -UserName user1
$windowsSession = New-PSSession -ComputerName winsys2 -Credential user1
```

Expected behavior
-----------------
PSSession should have a disconnect state.
```none

```

Actual behavior
---------------
Disconnect error on Linux PSSession.
```none
PS C:\Program Files\PowerShell\6.0.0-beta.9> Disconnect-PSSession -Session $linuxSession
Disconnect-PSSession : Disconnect-PSSession operation failed for runspace Id = 97a7af76-7509-4274-a796-976fb4324d93
for the following reason: The disconnection operation is not supported on the remote computer. To support
disconnecting, the remote computer must be running Windows PowerShell 3.0 or a later version of Windows PowerShell.
At line:1 char:1
+ Disconnect-PSSession -Session $linuxSession
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ([PSSession]SSH3:PSSession) [Disconnect-PSSession], RuntimeException
    + FullyQualifiedErrorId : PSSessionDisconnectFailed,Microsoft.PowerShell.Commands.DisconnectPSSessionCommand

```

Environment data
----------------
Windows 10 Insider Build 17025

```powershell
PS C:\Program Files\PowerShell\6.0.0-beta.9> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta.9
PSEdition                      Core
GitCommitId                    v6.0.0-beta.9
OS                             Microsoft Windows 10.0.17025
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


PS C:\Program Files\PowerShell\6.0.0-beta.9>

```
![pcoreremoting_04_2017-11-02_10-54-55](https://user-images.githubusercontent.com/19892435/32344042-da92395c-bfdb-11e7-9dc0-f990d5c4aaf1.png)

**Comment by SteveL-MSFT** [comment]
This is currently expected because WinRM provides the disconnect/reconnect capabilities.  SSHD doesn't do this.  For 6.1.0, we can investigate the cost of doing this, or at least have a better error message.

**Comment by MaximoTrinidad** [comment]
@SteveL-MSFT,

Thanks Steve for the quick response! At least I can use the Remove-PSSession get rid of the Linux session.

In the scenario where you have both a Windows and Linux session, using the the following command will work for Windows and the other fail.
```
Disconnect-PSSession -Session $linuxSession, $windowsSession
```
It would be nice if a resolution could be found.
:)

**Comment by MaximoTrinidad** [comment]
Hey @SteveL-MSFT 

OK!! It's been a long time and now I notice that the Disconnect-PSSession was dropped from the linux implementation.

I see it very useful when you are doing implicit remoting.  For example, doing an Import-PSSession while I'm already in a remoting session.

I don't want to drop my existing connect but just the one I did the Import-PSsession on.

The example I'm talking about is when working with Office365 while connected to a linux machine.  I only need to disconnect from one session.

Is it possible to bring back the Disconnect-PSSession??
:)

**Comment by SteveL-MSFT** [comment]
@MaximoTrinidad disconnect/reconnect is implemented by WinRM, so it's not trivial to support this on non-Windows.
