### ISSUE TITLE
Beta 9 - on mac showing as beta 8

### ISSUE THREAD

**Issue by jackfruh** [PowerShell/PowerShell#5316]
Steps to reproduce
------------------
Download beta 9 for mac pkg file from github
Install beta 9 powershell mac pkg on mac.
[optional: Confirm installer says beta 9]
start powershell - displays v6.0.0-beta.8
type $PSVERSIONTABLE

-displays
6.0.0-beta.8

```powershell

```

Expected behavior
-----------------

```none
Beta 9
```

Actual behavior
---------------

```none
Beta 8
```

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by SteveL-MSFT** [comment]
did you start as `powershell`?  You probably still have beta.8 side by side with beta.9.  You need to use `pwsh` to start beta.9.  Unfortunately there's no supported way to uninstall a .pkg (that I could find).  You can manually delete the beta.8 folder along with the /usr/bin/powershell symlink.

**Comment by thezim** [comment]
@jackfruh If you're not interested in side by side this should get you back to zero if you installed from a `.pkg`. Then just reinstall beta 9.

```bash
sudo rm -rf /usr/local/microsoft /usr/local/bin/pwsh /usr/local/bin/powershell /Applications/PowerShell.app /usr/local/share/man/man1/pwsh.1.gz
sudo pkgutil --forget powershell
```

As @SteveL-MSFT  mentioned use `pwsh` if you're opening from a terminal. There is also a PowerShell icon in `Applications` folder in Finder that opens PowerShell as well.

**Comment by jackfruh** [comment]
@SteveL-MSFT @thezim 

Yep this is exactly what happened.

Had beta 8 installed previously.

Is this the first release with the .app icon? I've missed that in the past!

I must admit I am guilty of not seeking out the change log - now that I've seen it, it might be good to include the rename of powershell to pwsh as a breaking change?

@thezim I also appreciate the remove instructions, 9 betas in there is likely to be something there I no longer need!
