### ISSUE TITLE
The [Feature] tag in PR commit message doesn't reliably trigger full build on Travis CIs

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#5319]
The `[Feature]` tag in a PR commit message doesn't reliably trigger full build on Travis CI because `travis.ps1` cannot reliably get the commit message of the PR commit. It could happen that the commit message in use is the commit that was just merged to master branch.

See example PR CI runs:
https://travis-ci.org/PowerShell/PowerShell/jobs/296488902
This CI build is for `"Pull Request #5315 Always run test with crossgen'ed assemblies in CI"`. However, when inspecting the log I see `"Executing travis.ps1 $isPR='True' $isFullBuild='False' - Change line ending in Rename-Computer.Tests.ps1 to LF (#5314)"`

https://travis-ci.org/PowerShell/PowerShell/jobs/296488903
Same here, it shows `"Executing travis.ps1 $isPR='True' $isFullBuild='False' - remove sync-tags for Linux. It is failing. (#5299)"`

**Comment by SteveL-MSFT** [comment]
Long term, we should improve the performance of our tests (like my parallel execution PR which I'll get back to some day) so that we run Feature tests for every PR.

**Comment by ThomasNieto** [comment]
Is this still an issue since Travis isn't used anymore?

**Comment by daxian-dbw** [comment]
@ThomasNieto Good point! 😄 Thanks!
