### ISSUE TITLE
Inheritance from interface and class are inconsistent

### ISSUE THREAD

**Issue by fMichaleczek** [PowerShell/PowerShell#5332]
When PowerShell class is inherited from a C# class, if another C# class invoke an overrided method on this powershell class instance, it invokes C# base method instead of overrided powershell method.

This problem doesn't exist when PowerShell class is inherited from an C# Interface.

Steps to reproduce
------------------

```powershell

Add-Type -Type @' 

// Interface
public interface iMyClass 
{
	void MySharedMethod();
}

// C# Class Example
public class MyClassCSharp : iMyClass
{ 
	public void MySharedMethod() 
	{ 
		System.Console.WriteLine("ClassCSharpMethod");
	} 
} 

// Another class that will target C# Class or PowerShell Class
public static class AnotherClassCSharp
{ 
	public static void StaticMethod(iMyClass myclass) 
	{ 
		myclass.MySharedMethod();
	} 
} 
'@ 

# PowerShell Class Exemple, same as MyClassCSharp
class MyClassFromInterface : iMyClass {
	[void] MySharedMethod() {
		Write-Host "ClassPSMethod"
	}
}

# PowerShell Class Exemple 2, herit from MyClassCSharp 
class MyClassFromCSharp : MyClassCSharp {
	[void] MySharedMethod() {
		Write-Host "ClassPSMethod"
	}
}

# PowerShell Class Exemple 3, herit from MyClassPowerShell
class MyClassFromPowerShell : MyClassCSharp {
	[void] MySharedMethod() {
		Write-Host "ClassPSMethod"
	}
}
$MyClassFromInterface = [MyClassFromInterface]::new()
$MyClassFromCSharp = [MyClassFromCSharp]::new()
$MyClassFromPowerShell = [MyClassFromPowerShell]::new()

[AnotherClassCSharp]::StaticMethod($MyClassFromInterface)
[AnotherClassCSharp]::StaticMethod($MyClassFromCSharp)
[AnotherClassCSharp]::StaticMethod($MyClassFromPowerShell)

```

Expected behavior
-----------------

```none
PS> [AnotherClassCSharp]::StaticMethod($MyClassFromInterface)
ClassPSMethod
PS> C:\Users\flavi> [AnotherClassCSharp]::StaticMethod($MyClassFromCSharp)
ClassPSMethod
PS> C:\Users\flavi> [AnotherClassCSharp]::StaticMethod($MyClassFromPowerShell)
ClassPSMethod
```

Actual behavior
---------------

```none
> [AnotherClassCSharp]::StaticMethod($MyClassFromInterface)
ClassPSMethod
> [AnotherClassCSharp]::StaticMethod($MyClassFromCSharp)
ClassCSharpMethod
> [AnotherClassCSharp]::StaticMethod($MyClassFromPowerShell)
ClassCSharpMethod
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta.8
PSEdition                      Core
GitCommitId                    v6.0.0-beta.8
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by lzybkr** [comment]
This should be an easy one for someone interested in fixing - it sounds like we are acting as though you specified the `new` keyword instead of `override`.

**Comment by IISResetMe** [comment]
This is I'm not quite sure I understand the issue here - the problem here is that `MyClassCSharp.MySharedMethod` is _not overridable_ (for lack of a better word), since the C# compiler marks `MyClassCSharp.MySharedMethod()` `final`. 

In comparison, we keep all methods in PowerShell classes non-final virtual (in turn allowing all derived types to override them by simply existing).

Explicitly marking the `MyClassCSharp.MySharedMethod` implementation `virtual` in `C#` makes the resulting method non-final and resolves the issue as expected:

```powershell
Add-Type -Type @' 

// Interface
public interface iMyClass 
{
	void MySharedMethod();
}

// C# Class Example
public class MyClassCSharp : iMyClass
{ 
	public virtual void MySharedMethod() 
	{ 
		System.Console.WriteLine("ClassCSharpMethod");
	} 
} 

// Another class that will target C# Class or PowerShell Class
public static class AnotherClassCSharp
{ 
	public static void StaticMethod(iMyClass myclass) 
	{ 
		myclass.MySharedMethod();
	} 
}
'@

class MyPowerShellCSharpOverrider : MyClassCSharp {
    MySharedMethod() {
        Write-Host "PowerShell won!"
    }
}

[AnotherClassCSharp]::StaticMethod([MyPowerShellCSharpOverrider]::new())
```

**Comment by fMichaleczek** [comment]
@IISResetMe You're right. Let me try to requalify it.

**Inherited PowerShell class doesn't report error when you try to override a method which is not marked virtual, abstract, or override.**

# Steps to reproduce
```
Add-Type -Type @' 

// C# Class Example
public class MyClass
{ 
	public void MyMethod() 
	{ 
		System.Console.WriteLine("MyMethod");
	} 
} 

'@

class MyInheritedClass : MyClass {
    MyMethod() {
        Write-Host "PowerShell won!"
    }
}


```
# Expected behavior

'MyInheritedClass .MyMethod()': cannot override inherited member 'MyClass.MyMethod()' because it is not marked virtual, abstract, or override
 
# Actual behavior
No error

If you agree with the vocabulary (any help is welcome to be more precise), I closed this one and create a new one.

**Comment by IISResetMe** [comment]
I completely disagree with the expectation - hiding existing implementations by default is pretty consistent PowerShell behavior IMO! 

The verbiage/vocabulary makes perfect sense though, create new issue to discuss how to better handle "sealed/final" vs "overrideable" when extending classes, sounds good to me 👍

**Comment by fMichaleczek** [comment]
@IISResetMe https://github.com/PowerShell/PowerShell/issues/12571
