### ISSUE TITLE
Invoke-RestMethod parses octet-stream responses (binary) incorrectly

### ISSUE THREAD

**Issue by zehranaz** [PowerShell/PowerShell#5334]
If flips random bytes. If output is written to file instead with -OutFile parameter, then the problem goes away. Invoke-WebRequest on the same response shows the expected binary in the Content field.

Steps to reproduce
------------------
I am writing out the string response to a file and reading it into a byte array. After I get the bytes, I convert them like this:
```powershell

[System.BitConverter]::ToSingle($Bytes, $BeginIndex);
```
The response conversion shows that some of the values are garbled, typically the decimals and negatives, but also 1 in a consistent manner. I have also opened the string response in a hex editor and seen certain bytes getting flipped to 3A.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.16299.19
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.19
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by markekraus** [comment]
Can you please provide the output of your `$PSVersionTable`?
Also, Can you provide the exact steps to reproduce the issue? I suspect this is using the cmdlet outside of its intended purpose, but it's hard to make that call without exact steps to reproduce.

When output is not redirected to a file, `Invoke-RestMethod` coerces unknown content to a string which means that a string encoding gets applied to it. If the server is not supplying the correct encoding (which, usually `application/octet-stream` does not send with an encoding) it's quite possible that bytes would get mixed up in the encoding process. `Invoke-RestMethod` isn't really meant for working with a byte stream.

I was unable to reproduce an issue using the following:

```
dotnet new mvc
```
edit `Controllers\HomeController.cs`
att the following endpoint:
```csharp
        [HttpGet]
        public FileStreamResult Bytes()
        {
            Byte[] bytes = new Byte[]{1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16};
            MemoryStream mstream = new MemoryStream(bytes);
            return new FileStreamResult(mstream, "application/octet-stream");            
        }
```
run it
```
dotnet run
```
do the following:
```powershell
[System.Text.Encoding]::UTF8.GetBytes((irm 'http://localhost:5000/home/Bytes' ))
"-----"
(iwr 'http://localhost:5000/home/Bytes' ).Content
```

Result:
```none
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
-----
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
```

**Comment by zehranaz** [comment]
Thank you for the prompt response. Impressive!

I forgot to mention that this issue happens when you send bytes that map to decimal point and negative values such as 10.1 and -1. I have recorded the steps above. I don't have a clear repro to share with you since the response is coming from an internal server. I have updated the repro steps above if it helps though.

I think you're right about the string interpretation messing up the bytes. That would make sense and it's what I had guessed before looking at the code. It helps to know that Invoke-RestMethod is not meant to support binary responses. But what I would suggest is if the encoding is not JSON or XML, to return the Content that is coming back from WebRequest rather than returning as a string. With some more code reading, I could probably submit a PR to fix this, but someone more familiar with the code should be able to do it more quickly :)

**Comment by markekraus** [comment]
>  But what I would suggest is if the encoding is not JSON or XML, to return the Content that is coming back from WebRequest rather than returning as a string.

That's not what I would expect from the command. `Invoke-RestMethod` is more light weight than `Invoke-WebRequest`, which makes it ideal for web scraping and other activities that do not need the structured complexity of the WebResponseObject. If you want the full object, than just use `Invoke-WebRequest`. I think requesting that behavior is a non-starter. It would be a massive breaking change for very little gain when there is already a cmdlet that does that.

There is another request #3829 to provide raw streams to be able to do things like log streams, What you are trying to do would be another use-case for my proposal there to add a new web cmdlet that adds stream handling features. something like `-AsByteStream` or something similar as a switch for that cmdlet.

**Comment by markekraus** [comment]
@zehranaz I see that you have updated your post with the PS version table and it is for Windows PowerShell 5.1. Can you reproduce your issue with with PowerShell Core 6.0.0-beta.9?

If you are not using PowerShell Core and wish to file a bug or feature request for Windows PowerShell 5.1, please use the Windows PowerShell [UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell).

**Comment by iSazonov** [comment]
Old issue without feedback.
