### ISSUE TITLE
Consider porting Windows PowerShell changes to PSCore6

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PowerShell#5335]
This is a list of Windows PowerShell items we should consider porting to PSCore 6.
I'll update this list as needed.

- [ ] TFS:12717061
- [ ] TFS:12318294
- [ ] TFS:12204519
- [ ] TFS:11658687
- [ ] TFS:11711916
- [ ] TFS:11445884
- [ ] TFS:10756506
- [ ] TFS:12405614
- [ ] TFS:11818697
- [ ] TFS:11446093
- [ ] TFS:11211805

**Comment by SteveL-MSFT** [comment]
I updated it to have checkboxes so we can just check them off as completed

**Comment by mi-hol** [comment]
@SteveL-MSFT will the changes listed show up in a preview?

**Comment by MaximoTrinidad** [comment]
Interesting!

Is there a way to list a summary description of these fixes?

:)

**Comment by bergmeister** [comment]
VSTS offers now the feature (in private preview at the moment) of allowing the public a read-only view of a VSTS instance. Thia could be useful to see those referenced items @SteveL-MSFT

**Comment by SteveL-MSFT** [comment]
@bergmeister the TFS id's above come from the uber Windows TFS.  Not only do I not have permission to make something publicly read-only, I doubt Windows org would do that.  The changes will show up in the PSCore6 changelog after the change is ported.

**Comment by iSazonov** [comment]
@SteveL-MSFT Can we close this?
