### ISSUE TITLE
Need install-powershell.ps1 for Windows similar to install-powershell.sh

### ISSUE THREAD

**Issue by bmanikm** [PowerShell/PowerShell#5348]
- Need install-powershell.ps1 for Windows similar to [install-powershell.sh](
https://github.com/PowerShell/PowerShell/blob/f3dd2f041433c274d200720219fe5a80d39aeba3/tools/install-powershell.sh)
- Also provide an option for installing the daily build of PowerShell. This is required for other GitHub repositories like PowerShellGet, OneGet, etc.,

**Comment by daxian-dbw** [comment]
For the second ask, daily builds of win-x64-win7 nuget packages are published to https://powershell.myget.org/feed/powershell-core-daily/package/nuget/powershell-win-x64-win7-x64.

You can install it by running `PM> Install-Package powershell-win-x64-win7-x64 -Version 6.0.0-beta-9-471 -Source https://powershell.myget.org/F/powershell-core-daily/api/v3/index.json`

**Comment by SteveL-MSFT** [comment]
@daxian-dbw the instructions you pasted only work within VisualStudio.  The PSGet instructions on MyGet don't work, it complains about the source location.  The `choco` instruction also failed.

**Comment by SteveL-MSFT** [comment]
There should probably be a `-daily` switch and default to latest release

**Comment by daxian-dbw** [comment]
I don't think we publish nuget packages for releases. All packages at powershell-core-daily are from daily builds /cc @TravisEz13
