### ISSUE TITLE
Support an option on install-powershell.sh for installing the daily builds of PWSH

### ISSUE THREAD

**Issue by bmanikm** [PowerShell/PowerShell#5349]
Need an option for installing daily builds using [install-powershell.sh](
https://github.com/PowerShell/PowerShell/blob/f3dd2f041433c274d200720219fe5a80d39aeba3/tools/install-powershell.sh). This is required for other GitHub repositories like PowerShellGet, OneGet, etc.,

**Comment by SteveL-MSFT** [comment]
`install-powershell.ps1` supports this, I think that should be sufficient once you have a version of PowerShell installed.
