### ISSUE TITLE
Complete breaks when file starts with period

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PowerShell#5351]
_From @Aetylus on August 12, 2016 13:12_

The `Complete` function (using `Set-PSReadlineKeyHandler -Key Tab -Function Complete`) doesn't seem to handle files with similar names but one begins with a period. I do a lot of work in gVim while on Windows which will leave `.[filename].swp` files while open, and attempting to tab complete the filename results in PowerShell completely unwriting the whole word.

Take for example a directory with `.foo.bar` and `foo.bar`. If you have `ii f`, `ii fo` or `ii foo` and attempt tab complete, it will completely rewrite your line to `ii .\`. Same with `ii .\f`, `ii .\fo`, and `ii .\foo`. Once you include the period before the file extension, it will autocomplete to `ii .\foo.bar`.

_Copied from original issue: lzybkr/PSReadLine#415_

**Comment by SteveL-MSFT** [comment]
https://github.com/PowerShell/PowerShell/issues/4694
