### ISSUE TITLE
BasicHtmlWebResponseObject and HtmlWebResponseObject

### ISSUE THREAD

**Issue by pdomansk** [PowerShell/PowerShell#5364]
Hi

I have Linux and Windows operating system. When I use on Windows 
$HTML = Invoke-WebRequest -Uri $u
A was 
IsPublic IsSerial Name                                     BaseType             -------- -------- ----                                     --------             
True     False    HtmlWebResponseObject               Microsoft.PowerSh...
when it run on linux i was
IsPublic IsSerial Name                                     BaseType             -------- -------- ----                                     --------             
True     False    BasicHtmlWebResponseObject               Microsoft.PowerSh...

and some functions like ParseHtml doesn't work.

Where is problem? 

Regards Paweł

**Comment by markekraus** [comment]
@pdomansk are you using PowerShell Core 6.0.0-beta.9 on windows when you see that, or Windows PowerShell 5.1?

Windows PowerShell 5.1 used Internet explorer to parse HTML for ` HtmlWebResponseObject.ParsedHtml` objects . 

PowerShell Core always returns a `BasicHtmlWebResponseObject` and currently only supports basic parsing as it does not use Internet Explorer. The `ParsedHtml` property should be null on both Windows and Linux in PowerShell Core 6.0.0.

**Comment by pdomansk** [comment]
Yes, on 5.1 on windows.
Sorry on linux I can see ParseHtml or I don't know how use it.

**Comment by SteveL-MSFT** [comment]
Windows PowerShell 5.1 and PowerShell Core 6 uses different web client classes (due to limitations of corefx) so the output type is different and this is expected.  `ParsedHtml` is not currently supported as that depended on InternetExplorer to do the parsing.  That is being tracked here https://github.com/PowerShell/PowerShell/issues/2867

**Comment by markekraus** [comment]
@pdomansk ok. I just wanted to make sure. That is by design. PowerShell Core on Windows will behave the same way as it does on Linux.  This is not the same as it was in Windows PowerShell 5.1.

**Comment by pdomansk** [comment]
Thanks for help.
