### ISSUE TITLE
Is there a way to access variables local to a scriptblock's definition site in a manner similar to ForEach-Object?

### ISSUE THREAD

**Issue by alx9r** [PowerShell/PowerShell#5375]
I am experimenting with capturing variables for use in a different runspace for [this certificate validation callback scriptblock](https://github.com/PowerShell/PowerShell/issues/4899#issuecomment-337782867).  For variable capture to be very useful in this case, the command setting up the callback would have to capture the variables local to the site where the scriptblock is defined.  It would have to do so _even_ if the scriptblock was first passed around through various commands and modules.  Such behavior would be consistent with the way `ForEach-Object`, for example, scopes access to variables for scriptblocks it invokes.  (In contrast, `Start-Job` seems to capture `$using:` variables using the `Start-Job` call site rather than the scriptblock definition site.)

It seems like accessing SessionState for a scriptblock's definition site would make it possible for a command to access variables local to the scriptblock's definition site.  That would make it possible to make those variables available in the callback.  Is there a way get such definition-local SessionState for a scriptblock if all I have is a reference to the scriptblock?  Is there some other way to access the variables local to a scriptblock?  It seems like `ForEach-Object` must be doing something like this but I confess I don't understand PowerShell internals enough to follow that bit of code.

Here is a mocked-up example demonstrating what I'm trying to do:

```PowerShell
New-Module m1 {
    $v = 'm1 value'
    function f {
        param($sb)
        g -sb $sb
    }
} | Import-Module

New-Module m2 {
    $v = 'm2 value'
    function g {
        param($sb)
        # I want to be able to get the PSVariable named v whose
        # value is 'definition-local value' from this command.

        # None of these commands work to do that.
        Get-Variable v # 'm2 value'
        Get-Variable v -Scope 1 # 'm2 value'
        Get-Variable v -Scope 2 # 'outer value'
    }
} | Import-Module

$v = 'outer value'

& {
    $v = 'definition-local value'

    f -sb { $v }
}
```

I'm trying to access the `$v` that is local to the definition of `$sb` from inside `g`.  I thought there might be some way to use `Get-Variable -Scope`, but there seems to be cases where the variables local to the scriptblock's definition aren't accessible.

**Comment by lzybkr** [comment]
Module scope links directly to global scope, and when you invoke a command inside a module, it's scope (say `g's` scope) links to the module scope.

So you have `g => m2 => global`. You won't find your local scope in that chain because it was considered too fragile to have dynamic scoping to search anything other than the module and global scope.

To accomplish true closures, you'll need to make changes to the PowerShell engine.

It probably makes sense to add an attribute so that the parameter binder could create the closure before changing the scope, e.g.

```powershell
param([Closure()][ScriptBlock]$sb)
```

**Comment by alx9r** [comment]
> It probably makes sense to add an attribute so that the parameter binder could create the closure before changing the scope...

Interesting.  Would `[Closure()]` mean that given

```PowerShell
New-Module m {
    $v = 'm value'
    function k {
        param($sb)
        & $sb.Module { Get-Variable v -ValueOnly}
    }
    function l {
        param([Closure()]$sb)
        & $sb.Module { Get-Variable v -ValueOnly}
    }
} | Import-Module

$v = 'outer value'

& {
    $v = 'definition-local value'
    k -sb {}.GetNewClosure()
    l -sb {}
}
```
the invocations of `k` and `l` would each output `definition-local value`?

**Comment by lzybkr** [comment]
Yes, that's what I had in mind.

**Comment by alx9r** [comment]
I can imagine some use cases for that and I would welcome `[Closure()]`.  It doesn't seem to solve the problem from my original post, however. For example,

```PowerShell
New-Module m {
    $v = 'm value'
    function n {
        param($sb) # if this line used [Closure()]...
        & $sb.Module { Get-Variable v -ValueOnly }
    }
} | Import-Module

New-Module SomeUserModule {
    $v = 'user module value'
    function o {
        param($sb)
        n -sb $sb.GetNewClosure() # ...it would be like this line used .GetNewClosure()
    }
} | Import-Module

$v = 'outer value'

& {
    $v = 'definition-local value'
    o -sb {}
}
```

outputs `outervalue`.  In other words, the variables are captured at the call site of the function using `[Closure()]` _not_ the definition site of the scriptblock.  The latter is the way scope seems to work for scriptblocks invoked using `ForEach-Object`.  The way `ForEach-Object` works seems intuitive to me.  If nothing else, `ForEach-Object`'s scope rules are familiar to other PowerShell users.

**Comment by SeeminglyScience** [comment]
@alx9r It sounds like you are asking for the `SessionState` property on `ScriptBlock` to be made public.  As long as the scope that the script block was defined in is still active `$sb.SessionState.PSVariable.GetVariable` would work like you describe.

I've definitely ran into a few situations where that property being public would have been very helpful.  Alternatively if the script block isn't associated with a module, the only other way I know of to get the session state is by getting `$PSCmdlet` from the call stack.  But you'd need to know which frame the script block was defined in, and that frame would have to use `CmdletBinding`.

    New-Module {
        function Test-Function {
            param([scriptblock] $sb)
            (Get-PSCallStack)[1].GetFrameVariables().PSCmdlet.Value.SessionState.PSVariable.Get('v')
        }
    } | Import-Module

    $v = 'outer'
    & {
        [CmdletBinding()]
        param()
        $v = 'local'
        Test-Function {}
    }

**Comment by alx9r** [comment]
>It sounds like you are asking for the SessionState property on ScriptBlock to be made public. As long as the scope that the script block was defined in is still active $sb.SessionState.PSVariable.Get would work like you describe.

@SeeminglyScience Is this the [SessionState](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.sessionstate?view=powershellsdk-1.1.0) class you mean?  It sure seems like having access to a `SessionState` object like that for the scriptblock would provide access to the variables I need.

**Comment by lzybkr** [comment]
Exposing SessionState worries me. For a long time (since it was introduced in V2 for modules) I've felt that it gets in the way of implementing real closures and multi-threading. For example, it basically forces us to clone script blocks so you can run them on other threads.

If we expose SessionState, you'll be stuck with this problem forever.

Imagine we always created a closure - with the understanding that certain things can't be captured (e.g. calls to Get-Variable) - that seems like it would solve a lot of problems, right?

**Comment by alx9r** [comment]
>Exposing SessionState worries me. For a long time (since it was introduced in V2 for modules) I've felt that it gets in the way of implementing real closures and multi-threading.

I prefer a future with better language support for multi-threading.

> Imagine we always created a closure - with the understanding that certain things can't be captured (e.g. calls to Get-Variable) - that seems like it would solve a lot of problems, right?

Do you mean that it would be as though every scriptblock definition implicitly called `.GetNewClosure()`.  So

```PowerShell
New-Module m {
    $v = 'm value'
    function n {
        param($sb)
        & $sb.Module { Get-Variable v -ValueOnly }
    }
} | Import-Module

$v = 'outer value'

& {
    $v = 'definition-local value'
    n -sb {} # .GetNewClosure() would be implicit
}
```

would output `definition-local value`?

**Comment by alx9r** [comment]
FWIW I settled on a combination of `$using:` and `.GetNewClosure()` to capture the value of variables from user-defined scriptblocks.  Calls to [`Save-WebFile`](https://github.com/alx9r/BootstraPS/blob/30bf72d6cd1605c3aaedf610374810262972c94f/BootstraPS.psm1#L1271-L1366) involving user variables in the certificate validation scriptblock look like this:

```PowerShell
$githubCaName = 'GeoTrust*'

#...

'https://github.com/alx9r/BootstraPS/blob/master/LICENSE' |
    Save-WebFile -Path c:\temp\LICENSE -CertificateValidator {
        $_ | Assert-RootCaName $using:githubCaName
    }.GetNewClosure()

#...
```

This style is prone to forgetting `.GetNewClosure()` but that is mostly mitigated by `Save-WebFile` checking for the presence of `$githubCaName` in the closure.  It is also prone to forgetting `using` in the same manner as `Invoke-Command` and `Start-Job`.
