### ISSUE TITLE
Is there a way to redirect output from an exe/jar that expects user input

### ISSUE THREAD

**Issue by LethiferousMoose** [PowerShell/PowerShell#5377]
I've been writing automation scripts to wrap a bunch of legacy EXEs and JARs for product development environment setup, and I've come across a few that perform a write operation without a line terminator and then perform a read from the user. I generally try to redirect EXE/JAR output into the verbose channel so it doesn't mess with with the PowerShell function output. But I've noticed unless the compiled programs write a new line, before the read operation, that output cannot be redirected until after the user presses a key. Is there was way to do accomplish this or is it just a limitation of the pipeline? The programs cannot be modified, so I was just looking for a workaround to either show the output in the Verbose channel or some way to automatically answer populate the read values.

I came across this on Stackoveflow (https://stackoverflow.com/questions/34616028/how-to-send-keystroke-to-executable) but that seems a little hacky.

i.e. ```'Yes' | SomeFile.exe```

Example Java code
```
System.out.print(prompt);
System.out.print("(Y/N): ");
answer = br.readLine();
```

Environment data
----------------
```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta.9
PSEdition                      Core
GitCommitId                    v6.0.0-beta.9
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Our test helper module HelpersHostCS  is example.
