### ISSUE TITLE
Remove ETW events used only by Full CLR code.

### ISSUE THREAD

**Issue by dantraMSFT** [PowerShell/PowerShell#5394]
This is an ongoing work item to remove ETW events and associated wrapper code for events that are specific to the full clr.

**Comment by iSazonov** [comment]
@SteveL-MSFT Could you please point examples of a code we should clean up?

**Comment by SteveL-MSFT** [comment]
@iSazonov this is an example: https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Security/security/ExecutionPolicyCommands.cs#L236-L239
