### ISSUE TITLE
Binary for Ubuntu 17.10

### ISSUE THREAD

**Issue by tats-u** [PowerShell/PowerShell#5406]
Is there any plan to distribute a binary for Ubuntu 17.10?
I cannot install one by `apt` and it seems that there is not the package of PowerShell in https://packages.microsoft.com/ubuntu/17.10/prod/pool/main/.

```
$ cat /etc/lsb-release                                                                                                                                                                                  [faab9e7] 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Ubuntu 17.10"
```

**Comment by iSazonov** [comment]
Could you test the package for 17.04?

**Comment by MaximoTrinidad** [comment]
FYI

I got PowerShell Core Beta.9 loaded in Ubuntu 17.10

![u1710_2017-11-10_11-38-05](https://user-images.githubusercontent.com/19892435/32668613-1240f60a-c60c-11e7-8252-849bc81655cc.png)

**Comment by iSazonov** [comment]
@joeyaiello @SteveL-MSFT 
From https://wiki.ubuntu.com/Releases
>Support length
•Regular releases are supported for 9 months. 
•Long term support (LTS) releases are for 5 years. 

It seems that even with a 6-month servicing model, we will not have to keep up with the regular releases.
I think we should point out in our `Servicing support model` document that we support only LTS.
