### ISSUE TITLE
install-powershell.sh support for amazon linux

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/PowerShell#5409]
Create installpsh-amazonlinux.sh to support installation on amazon linux.

Also address:

- incorrect repo urls in comments of each script
- ensure that tarball installs overwrite (reinstall) and upgrades

**Comment by DarwinJS** [comment]
@daxian-dbw - I am also planning to do some cleanup of the install*.sh scripts.  

Is this bit of code already in the package based installs or should it be backported to the other installpsh scripts?  https://github.com/PowerShell/PowerShell/blob/master/tools/installpsh-suse.sh#L174-L179

Are there any improvements in https://github.com/PowerShell/PowerShell/blob/master/tools/installpsh-suse.sh that would be helpful to have in the other installpsh*.sh scripts?

**Comment by DarwinJS** [comment]
@daxian-dbw - I should also ask will installpsh-suse.sh work for upgrading over an older version - did you test it for that?  I am thinking since tarball based installs can't use the package manager to update, it might be nice if this code could be re-run to update.

**Comment by daxian-dbw** [comment]
> Is this bit of code already in the package based installs or should it be backported to the other installpsh*.sh scripts? https://github.com/PowerShell/PowerShell/blob/master/tools/installpsh-suse.sh#L174-L179

This bit of code will be done automatically when installing the DEB/RPM packages.

> Are there any improvements in https://github.com/PowerShell/PowerShell/blob/master/tools/installpsh-suse.sh that would be helpful to have in the other installpsh*.sh scripts

No additional improvement. Just does what the package is doing.

>  should also ask will installpsh-suse.sh work for upgrading over an older version - did you test it for that?

If a newer release is available, then running the script should install the newer package, but it doesn't remove the older powershell core files from `/opt/microsoft/powershell`.
If there is no newer release, then re-running the script might fail as it tries to un-compress the files to the existing folder at [line 167](https://github.com/PowerShell/PowerShell/blob/master/tools/installpsh-suse.sh#L167). I didn't test the re-run scenario.

**Comment by daxian-dbw** [comment]
Close via #5461
