### ISSUE TITLE
Beta.9 - Concern of PowerShellGet modules loaded multiple times.

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#5412]
I'm not sure how to address this one, or if this is the place for it. I'm resuming working with Azure cmdlets and we all know that is not totally working in PowerShell core.  

I'm concerned that I have to load the Azure module twice (once for each PowerShell).  Everything loads without any issues in PowerShell Core.  But, I realized that I need to do it again for Windows Powershell.

I'm not sure if there are some discussion about it but it comes back to identifying PowerShellGet modules that can be installed specifically for Linux.  Or, find a way to established a "Shared Modules" folder for Cross-Platform modules.

Steps to reproduce
------------------

1. In PowerShell Core Beta.9, install Azure and AzureRM modules.
```powershell
Install-Module Azure
Install-Module AzureRm

Get-Module -ListAvailable Azure* | Select name, version
```
2. Open Windows PowerShell
```
Get-Module -ListAvailable Azure* | Select name, version
```

Expected behavior
-----------------
To see in Windows PowerShell Azure modules listed.

```none

```

Actual behavior
---------------
Only PowerShell Core will list installed Azure Modules
```none

```

Environment data
----------------
Windows 10 Build 17035

```powershell
S C:\Program Files\PowerShell\6.0.0-beta.9> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta.9
PSEdition                      Core
GitCommitId                    v6.0.0-beta.9
OS                             Microsoft Windows 10.0.17035
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
![azurecmdlet_2017-11-10_15-15-11](https://user-images.githubusercontent.com/19892435/32677347-0f955bb0-c62c-11e7-8cbf-4aae1a34ffa5.png)

**Comment by SteveL-MSFT** [comment]
This is currently `by-design` as we deliberately wanted Windows PowerShell and PSCore6 to work side-by-side with predictability.  To solve your particular problem, one option is to install the modules using Windows PowerShell and then using https://www.powershellgallery.com/packages/windowspsmodulepath/1.0.0 to import them in PSCore6

**Comment by MaximoTrinidad** [comment]
@SteveL-MSFT ,

Interesting!  Thanks for the information. I'll give it a shot.
:)
