### ISSUE TITLE
Install instructions for Kali Linux are out-of-date

### ISSUE THREAD

**Issue by anmenaga** [PowerShell/PowerShell#5413]
[These instructions for Kali Linux](https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md#kali) specify to deploy

http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u6_amd64.deb

which does Not exist.

Using a similar "libssl1.0.0_1.0.1t-1+deb8u7_amd64.deb" from that location terminates PS with Segmentation fault:
![kalisegfault](https://user-images.githubusercontent.com/11860095/32677700-4766cbae-c614-11e7-8b3d-7a21d80f08b1.png)

**Comment by iSazonov** [comment]
@sdcampbell Could you please address the Issue and update docs?

**Comment by hctrr** [comment]
As of 04.10.18 - the documented URL is still incorrect/not available. 

![2018-04-10_wget](https://user-images.githubusercontent.com/15852711/38576244-717c74ce-3cb2-11e8-93eb-8519cc73ed00.png)
