### ISSUE TITLE
Slow function when parameter is Mandatory its Type is specified

### ISSUE THREAD

**Issue by Atamido** [PowerShell/PowerShell#5417]
Steps to reproduce
------------------

```powershell
[Byte[]]$Value = [System.IO.File]::ReadAllBytes('C:\Some10MBfile')

#  ~1000ms for 10MB array
#  ~0.5ms for 1byte array
function MandType {
    Param (
        [parameter(Mandatory=$True)]
        [Byte[]]$Value
    )
}

#  ~0.3ms for 10MB array
function TypeOnly {
    Param (
        [parameter()]
        [Byte[]]$Value
    )
}

#  ~0.3 for 10MB array
function MandOnly {
    Param (
        [parameter(Mandatory=$True)]
        $Value
    )
}

(Measure-Command { MandType $Value}).TotalMilliseconds
(Measure-Command { MandType ([Byte[]]@(0))}).TotalMilliseconds
(Measure-Command { TypeOnly $Value}).TotalMilliseconds
(Measure-Command { MandOnly $Value}).TotalMilliseconds

```

Expected behavior
-----------------
All versions of the above functions should behave identically and complete immediately, regardless of of parameter size as the functions perform no functions.
```none
1.1
1.1
1.1
1.1
```

Actual behavior
---------------
When setting a parameter to Mandatory, specifying its Type, and passing a large array in, the function will pause for some amount of time before starting.
```none
1000
1.1
1.1
1.1
```

Environment data
----------------

```powershell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta.9
PSEdition                      Core
GitCommitId                    v6.0.0-beta.9
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.19
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.19
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by markekraus** [comment]
I can repro this in Core on Windows, macOS, and Linux. Very odd.

also, just to be thorough I tested with function below just to see if there was a difference between explicit or implicit `mandatory=$false` and did not see the same issue. 

```powershell
function NoMandType {
    Param (
        [parameter(Mandatory=$false)]
        [Byte[]]$Value
    )
}
```

**Comment by daxian-dbw** [comment]
`Mandatory` causes the parameter binder to check for NULL elements in an array argument (code [here](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/ParameterBinderBase.cs#L792)), which causes this perf issue.

It also happens when the `[ValidateNotNull]` attribute is applied to the parameter.

```
function NotNulOrEmtpy {
     Param (
         [ValidateNotNull()]
         [Byte[]]$Value
     )
}
## Long delay
NotNulOrEmtpy -Value $Value
```

The parameter binder shouldn't blindly check null elements. In the case of this repro, the element type of the argument array is value type, and thus cannot have null element.

**Comment by iSazonov** [comment]
@daxian-dbw Do we use new label `bug` instead of `Issue-Bug`?

**Comment by iSazonov** [comment]
What should the attributes be applied to? Argument or its elements? Collection or its elements?

**Comment by markekraus** [comment]
IMO, `[ValidateNotNull()]` and `[ValidateNotNullorEmpty()]` would apply to the collection, not its elements... but... erm... maybe not all types. like `[String[]]` for example.. that one I could see users assuming it applies to elements. but for `[Bytes[]]` I would expect that to work on the collection, not the elements..

**Comment by iSazonov** [comment]
We could disable recursion [here](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/ParameterBinderBase.cs#L561) to set last parameter in false and in ValidateNullOrEmptyArgument add empty collection check.

**Comment by lzybkr** [comment]
For `ValueFromPipeline` arguments, it's important that `Validate...` applies to members of the collection because the recommended pattern is to always accept a collection so that the following work similarly:

```PowerShell
$collection | Do-Something
Do-Something -InputObject $collection
```

It would be a little weird if `Validate...` did not apply to members of a collection if the parameter were not `ValueFromPipeline`.

**Comment by iSazonov** [comment]
I'd expect that we _convert_ `Do-Something -InputObject $collection` to `$collection | Do-Something` if `InputObject ` is a scalar and that we apply `Validate...` to members in this case, otherwise if `InputObject ` is a collection we apply `Validate...` to the collection.

**Comment by lzybkr** [comment]
@iSazonov - do you mean `InputObject` is typed as a collection, or that the value is a collection?

I believe conversions are performed before validation - as this example demonstrates:

```powershell
class MyThing { [string]ToString() { return "" } }
function foo {
    param(
        [ValidateNotNullOrEmpty()]
        [Parameter(Mandatory, ValueFromPipeline)]
        [string[]]$InputObject)
    process { $InputObject.Count }
}
foo -InputObject ([MyThing]::new(),[MyThing]::new())
```
Because you git this error - showing clearly the conversion happened and validation failed on the empty strings:
```
foo : Cannot validate argument on parameter 'InputObject'. The argument is null or empty. Provide an argument that is
not null or empty, and then try the command again.
At line:1 char:18
+ foo -InputObject ([MyThing]::new(),[MyThing]::new())
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [foo], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,foo
```

So when using the usual pattern for pipeline parameters - use a strongly typed collection for `InputObject`, it doesn't matter if you've passed a scalar or collection, the value will have been converted to a collection before validating.

**Comment by daxian-dbw** [comment]
I think we at least should skip checking elements for collections with a value-type element. For collections with a value-type element, the element cannot be `$null`, so in this case, just check if the collection is empty.

**Comment by iSazonov** [comment]
@lzybkr 
My thoughts was about:
```powershell
function foo1 {
    param(
        [ValidateNotNullOrEmpty()]
        [Parameter(ValueFromPipeline)]
        [string[]]$InputObject)
    process { $InputObject.Count }
}

function foo2 {
    param(
        [ValidateNotNullOrEmpty()]
        [Parameter(ValueFromPipeline)]
        [string]$InputObject)
    process { $InputObject.Count }
}

foo1 -InputObject $scalar
$scalar | foo1
foo1 -InputObject $collection
$collection | foo1

foo2 -InputObject $scalar
$scalar | foo2
foo2 -InputObject $collection
$collection | foo2
```

`- if we convert `foo -InputObject $var` to `$var | foo` we could use one code path (to work precisely similarly) and eliminate the internal cycle in `ProcessRecord()` for `InputObject`.

**Comment by iSazonov** [comment]
@lzybkr @daxian-dbw We have an inconsistence with `ValueFromPipeline` arguments.
```powershell
function MandType1 {
    Param (
        [parameter(Mandatory=$true, ValueFromPipeline)]
        [Byte[]]$Value
    )
}

function MandType2 {
    Param (
        [parameter(Mandatory=$true, ValueFromPipeline)]
        $Value
    )
}

# Validate every element in array
MandType1 -Value $Value
$Value | MandType1 

# Validate only whole $Value as Object
MandType2 -Value $Value
# Validate every element in array
$Value | MandType2
```

**Comment by daxian-dbw** [comment]
The not-null-or-empty check of a mandatory parameter is based on the parameter type, while the check for `ValidateNotNullOrEmptyAttribute` or `ValidateNotNullAttribute` (and other validate attributes too) are based on the argument only (the attribute itself doesn't have the information about the type of the parameter/variable/property it applies to).

**Comment by iSazonov** [comment]
I believe we want "works similarly", don't we?
