### ISSUE TITLE
The HadErrors property of System.Management.Automation.PowerShell reports $True in unexpected scenarios

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#5425]
<sup>Related: #4613</sup>

The `.HadErrors` property of `[System.Management.Automation.PowerShell]` currently invariably - and unexpectedly - reflects `$True` in the following situations:

* an external utility reports a nonzero exit code - even overriding `$LASTEXITCODE` later doesn't help that.

* something writes to PowerShell's error stream, notably including stderr output from an external utility.

Generally, having a _separate property_ that reflects `$LASTEXITCODE` would be helpful - see #5426

Examples
---------

```powershell
# Yields $True - triggered by nonzero exit code 
$ps = [PowerShell]::Create().AddScript({ whoami -nosuch }); $ps.Invoke(); $ps.HadErrors

# Unexpectedly also yields $True - despite attempt to set the exit code to 0.
$ps = [PowerShell]::Create().AddScript({ whoami -nosuch; $LASTEXITCODE = 0 }); $ps.Invoke(); $ps.HadErrors

# Unexpectedly also yields $True - triggered by native stderr output.
$ps = [PowerShell]::Create().AddScript({ bash -c 'echo err >&2'  }); $ps.Invoke(); $ps.HadErrors
```

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.9 on macOS 10.13
PowerShell Core v6.0.0-beta.9 on Ubuntu 16.04.3 LTS
PowerShell Core v6.0.0-beta.9 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
Windows PowerShell v5.1.15063.674 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)

```

**Comment by daxian-dbw** [comment]
When running a native utility in `S.M.A.PowerShell`, the standard output/error are always redirected to PowerShell output/error streams. The pipeline would detect there are things written into error stream and thus set `HadErrors` to true.
When running the native utility standalone in an interactive PowerShell session, standard output/error are not redirected, and thus `$Error` doesn't have the error output.

**Comment by SteveL-MSFT** [comment]
Treating stderr output as an error is plainly wrong as many utils use that as a `verbose` type channel so that it doesn't disrupt the actual output from stdout.  Checking exitcode is better although it's only a convention that non-zero means error.

**Comment by mklement0** [comment]
Thanks, @daxian-dbw and @SteveL-MSFT.

Having just come across this again and being somewhat confused by my own initial post, let me try to summarize:

* That _any stderr_output_ currently causes `.HadErrors` to become `$true` is inappropriate and should be fixed.

* Similarly, that an external-program call reporting a nonzero exit currently _by default_ causes `.HadErrors` to be `$true` (irrespective of whether it is the _last_ external program called) is inappropriate and should be fixed.

  * Only with `$PSNativeCommandUseErrorActionPreference = $true`  in effect (via the _experimental_ `PSNativeCommandErrorActionPreference` feature as of pre-v7.3)  is that behavior appropriate.
   
  * As noted in the initial post, it would be desirable to have a `.LastExitCode` _property_ that reflects the value of `$LASTEXITCODE`.

**Comment by SteveL-MSFT** [comment]
Changing definition of `HadErrors` at this point is probably not a bucket 3 breaking change.  It's probably best to check the Error stream instead of this property and leave how it currently works alone (although with better documentation).
