### ISSUE TITLE
Have to run as 'sudo'

### ISSUE THREAD

**Issue by nkean97** [PowerShell/PowerShell#5430]
I'm not sure if it's a bug or by design.  With the latest version of PS on Mac v6.0.0-beta.9 when I open PowerShell with the new "pwsh" command I have to run it as 'sudo'.  This seems to go against the normal as I wouldn't run PowerShell as administrator on Windows for everything I needed to peform.  I understand the need for 'sudo' if I'm installing modules or changing settings but why is it no longer allowed to run as a normal user in the lastest update?

**Comment by markekraus** [comment]
@nkean97 what method did you use to install beta.9? I'm not able to reproduce this issue using brew or compiling from source. https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md#macos-1012

**Comment by nkean97** [comment]
I thought I used brew but maybe I did something really strange over the weekend.  I just followed the steps for uninstalling via brew and direct link.  I think reinstalled via brew and now it doesn't require 'sudo' to run.  Thanks for the help.


Norman Kean

703.483.3949 (Home)

419.377.1833 (Cell)

________________________________
