### ISSUE TITLE
Investigate if we can use `cache` keyword in .travis.yml to cache the brew cache

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#5436]
We may be able to use the `cache` keyword in .traivs.yml to cache the brew cache:
```
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
```
But there are two things need to be investigated:
1. the .travis.yml is shared between Linux build and macOS build, so what will happen to Linux build when the directory to cache is not available.
2. the `cache` keyword seems only useful in some situations, not sure if ours is one of them. Need to research the Travis-CI documentation on this.

**Comment by TravisEz13** [comment]
https://github.com/PowerShell/PowerShell/pull/6003
