### ISSUE TITLE
Get-Command -CommandType shouldn't imply -All

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#5442]
`-CommandType` allows _restricting_ the potential matches by command type.

While that aspect works, the unrelated aspect of returning _all_ matches is currently at play as well: it's as if `-All` were implicitly, invariably specified.

`-CommandType` shouldn't imply `-All`; as without `-CommandType`, the _first_ (effective) match should be returned, with the option  to specify `-All` as needed.

Steps to reproduce
------------------

```powershell
Get-Command notepad  | % Source
'---'
Get-Command -CommandType Application notepad | % Source
```

Expected behavior
-----------------

```none
C:\WINDOWS\system32\notepad.exe
---
C:\WINDOWS\system32\notepad.exe
```

Actual behavior
---------------

```none
C:\WINDOWS\system32\notepad.exe
---
C:\WINDOWS\system32\notepad.exe
C:\WINDOWS\notepad.exe
```

Note how adding `-CommandType Application` returned _all_ `notepad` matches.

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.9 on macOS 10.13
PowerShell Core v6.0.0-beta.9 on Ubuntu 16.04.3 LTS
PowerShell Core v6.0.0-beta.9 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
Windows PowerShell v5.1.15063.674 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by markekraus** [comment]
> `-CommandType` shouldn't imply `-All`

I disagree. `Get-Command` without `-all` or `-CommandType` resolves the command that would be run. Supplying `-CommandType` does not. to me, it implies that i want to see all commands of that type with that type. 

If I have `function:notepad` that will trump either application in cmd resolution. I expect `Get-Command` without `-all` or `-CommandType` to resolve the exact command that would be run if I issue `notepad`. It would return `function:notepad`. When I'm specifying `Get-Command -CommandType Application notepad` I expect to see all the *application* `notepad`s. if it only returned the first one, what help would that be? That's not the command that will run when I issue notepad as the function would be run instead. It doesn't make any sense to me to issue `-All` here. I'm implying I want to see all the application type with that command name.. Also absent  a name `Get-Command -CommandType Cmdlet` I would expect that to return all cmdlets, not just the first one. It would be confusing to me to have a difference in  `-CommandType`  whether I supplied `-Name` or not.

**Comment by mklement0** [comment]
@markekraus: All good points, thanks - closing this.
