### ISSUE TITLE
macOS Limitations in 6.0.0

### ISSUE THREAD

**Issue by markekraus** [PowerShell/PowerShell#5443]
This issue is to track limitations of PowerShell Core 6.0.0 on the macOS platform. Limitations being defined as features that are already included in pwsh but either do not work at all or work partially on macOS (probably due to CoreFX limitations). 

* [ ] Web Cmdlet Client Certificate Authentication Support #4650
* [ ] Web Cmdlet Multiple `-SslProtocol` Support #5329 

Please update with more if you are aware of them.

**Comment by SteveL-MSFT** [comment]
@markekraus great idea, can you move this content to https://github.com/PowerShell/PowerShell/issues/4734 where we can track in one place?
