### ISSUE TITLE
Registry provider: New-Item -Force shouldn't blindly recreate the leaf path component (registry key)

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#5444]
`New-Item -Force`, at least with the filesystem provider, commendably employs desired-state logic with _directories_ (_update: see [comment below](https://github.com/PowerShell/PowerShell/issues/5444#issuecomment-384805763) for why registry keys should be considered the analog of directories, not files_):
If the specified path doesn't exist yet, it is created; if it already does, no action is taken (and no error is reported).

By contrast, the registry provider currently blindly _recreates_ the _leaf_ component of the path, which can result in data loss.

Steps to reproduce
------------------

```powershell
# Create HKCU:/foo/bar with value 'baz1'; -Force ensures that ancestral component `foo` is implicitly created.
New-Item -Force HKCU:/foo/bar | Set-ItemProperty -Name baz1 -Value 1
# Now - seemingly - add another value, 'baz2'
New-Item -Force HKCU:/foo/bar | Set-ItemProperty -Name baz2 -Value 2
# List the resulting values.
Get-Item HKCU:/foo/bar
```

Expected behavior
-----------------

```none


    Hive: HKEY_CURRENT_USER\foo


Name                           Property                                                                                                                                            
----                           --------                                                                                                                                            
bar                            baz1 : 1                                                                                                                                            
                               baz2 : 2                                                                                                                                            


```

Actual behavior
---------------

```none


    Hive: HKEY_CURRENT_USER\foo


Name                           Property                                                                                                                                            
----                           --------                                                                                                                                            
bar                            baz2 : 2                                                                                                                                            
```

Only `baz2` is present, because `New-Item -Force HKCU:/foo/bar` recreated the `bar` key, wiping out `baz1` in the process.

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.9 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
Windows PowerShell v5.1.15063.674 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by Jaykul** [comment]
That's *exactly* what happens with **leaf** items in every provider (if you `new-item -force -type file` it blows away the file).

**Comment by mklement0** [comment]
@Jaykul: 

That's true with _files_, yes, but the registry provider has no sub-item type that is the analog of a file - there's only _one_ item type - a registry _key_ - and it is _always_ a _container_, and thus the equivalent of a _directory_.

Thus, my argument is: just as `New-Item -Type Directory -Force /foo/bar` doesn't blow away the content of an existing `bar` directory, neither should `New-Item -Force HKCU:/foo/bar` recreate key `bar`.
