### ISSUE TITLE
GitHub don't report CI status

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#5446]
Last days GitHub don't report CI Travis status in acceptable manner. MacOS jobs don't start or if start and pass their status remains yellow in GitHub.
It slows down code reviews and block merging PRs.

Last month GitHub don't report CI Appveyor status at the CI job running time - opened page says "not found or access denied". After the job finished the link on status page _changed_ and the new page opens well. 
We can't watch the Job log while the job is running.

In running state https://ci.appveyor.com/project/PowerShell/powershell/build/1.0.6853
After after finish https://ci.appveyor.com/project/PowerShell/powershell/build/6.0.0-beta.9-6853

![appveyor1](https://user-images.githubusercontent.com/22290914/32822184-c034bca0-c9f0-11e7-92b5-5daddff41924.png)

![appveyor2](https://user-images.githubusercontent.com/22290914/32822401-bf0dfbb0-c9f1-11e7-8af4-69af3e1cfbb3.png)

**Comment by markekraus** [comment]
I tweeted at Travis CI about the macOS build start fails this weekend. They responded saying there were no known issues. The macOS builds wnet from 100% not starting to something like 50% not starting. This has to be a Travis CI issue, as it can't be out code if it never even runs.

The status write back from Travis CI has always been buggy when the time between build jobs is too long. What seems to be happening is that the Linux build starts and completes and then hours later the macOS build starts (or doesn't, take you pick) then Travis CI forgets all about the webhook. That's my best guess.

When the time between the Linux build and macOS build are close, it seems to update the stats properly. 

In any case, yes, this is very frustrating.

**Comment by iSazonov** [comment]
>when the time between build jobs is too long

Maybe split jobs to get reports separately.

**Comment by markekraus** [comment]
I don't think that's possible. the jobs are define din a single yml file.

**Comment by SteveL-MSFT** [comment]
cc @TravisEz13

**Comment by markekraus** [comment]
response from Travis CI: 

> Looks like max concurrency was reached, and simply waiting for some of the older ones to complete in queue. :)

I wonder, do we have [auto cancellation](https://blog.travis-ci.com/2017-09-21-default-auto-cancellation) turned on in our Travis CI?

**Comment by markekraus** [comment]
Oh wow.. I just realized I have access to the Travis CI repo settings. And we do not have auto cancelation turned on

@TravisEz13 What do you think about enabling auto cancellation? I think it would speed things up and make us a good Travis CI citizen. Busy PRs in this repo can some times pile up builds that no one cares about the status of. I think it would be a good idea to enable it for PR's at least.

**Comment by TravisEz13** [comment]
I turned auto-cancelation on for PRs.  We would like every branch build to actually complete.

**Comment by TravisEz13** [comment]
Note: I don't have permission to change this setting for other projects.
