### ISSUE TITLE
CI intermittently fails with GitHub throttling issue

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#5456]
CI intermittently fails with GitHub throttling issue

https://ci.appveyor.com/project/PowerShell/powershell/build/6.0.0-beta.9-6834#L22

```
VERBOSE: Destination: C:\Users\appveyor\AppData\Local\Microsoft\powershell
Invoke-RestMethod : {"message":"API rate limit exceeded for 67.225.139.254. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more 
details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
At C:\projects\powershell\tools\install-powershell.ps1:122 char:21
+ ... $metadata = Invoke-RestMethod https://api.github.com/repos/powershell ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

**Comment by SteveL-MSFT** [comment]
I believe they throttle based on the client IP, so not sure if a bunch of unrelated appveyor jobs are hitting GitHub anonymously now and thus getting throttled or if it's just our jobs.  Perhaps we should have a GitHub account created just for builds so it doesn't get throttled so quickly.

**Comment by markekraus** [comment]
@SteveL-MSFT Hmm, how would that work?. It doesn't look to be something that can be configured on the  in the server side settings and if it relied on an encrypted string it would be unavailable in PR builds.

**Comment by iSazonov** [comment]
Do Appveyor use real IP for every VM or 67.225.139.254 is any common IP (NAT)?

Ah, I see the 67.225.139.254 is one from IPs for build workes https://www.appveyor.com/docs/build-environment/ In other words, hundreds of machines can make requestes from this addresses. I believe we should ask GitHub to fix their limitations.

**Comment by markekraus** [comment]
> For unauthenticated requests, the rate limit allows for up to 60 requests per hour.

That number seems really low. I get that they want to push people to use authentication, but NAT is a thing and using an IP address for rate limiting this low is painful. 

It doesn't look like GitHub has a device grant flow for OAuth, so there are no secret-less read-only grants available. If we did include some kind of OAuth, the rate limit would be increased, but, this would also now apply to all consumers of `install-powershell.ps1`, and not just AppVeyor.

We could incorporate retry logic. It looks like the use the `X-RateLimit-Reset` header. At the very least it could try sleeping until the reset. but.. that could be up to an hour. The CI's do not like long naps.

So, maybe asking GitHub to be more lenient with AppVeyor's IPs is the best path? hmm

**Comment by SteveL-MSFT** [comment]
I was thinking we could set an env var in AppVeyor with OAuth key and `install-powershell.ps1` would use it if available.

**Comment by markekraus** [comment]
@SteveL-MSFT was your plan to do this only for daily and branch builds? If so, an encrypted string environment variable would be fine. PR's don't have access to the encrypted strings (to prevent someone from submitting a PR that just dumped or exported encrypted string).  If you wanted the functionality for PRs, then the account would need to be a kind of throw-away account with read-only access to the endpoints and a read-only app key issued. There is no good way to protect/secure a string in a PR.

**Comment by TravisEz13** [comment]
The env vars are not available for PRs.  To prevent this type of issue.  I have another design in mind.  I'll try to get back to this after the current release.

**Comment by daxian-dbw** [comment]
I'm working on this issue now as it's blocking PRs. I will sync with @TravisEz13 and his design.
