### ISSUE TITLE
Duplicate class name PinvokeDllNames

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#5460]
We have [internal static class PinvokeDllNames](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/utils/PInvokeDllNames.cs) in System.Management.Automation and [duplicate](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.LocalAccounts/LocalAccounts/PInvokeDllNames.cs) in LocalAccounts.

Can we remove the duplicate by adding `InternalsVisibleTo` in [AssemblyInfo.cs](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/AssemblyInfo.cs) ?

**Comment by SteveL-MSFT** [comment]
Eventually, we may want the LocalAccounts module separate from PSCore6 repo
