### ISSUE TITLE
Powershell 6.0.0-RC release

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#5472]
From:  https://github.com/PowerShell/PowerShell/blob/master/docs/maintainers/releasing.md

- [x] Create a branch named `release` in `PowerShell/PowerShell` repository.
   All release related changes should happen in this branch.
- [x] Run tests on Centos 7 and publish results
- [x] Run tests on Debian 8 and publish results
- [x] Prepare packages
   - [x]  [Build release packages](#building-packages).
   - [x]  Sign the MSI packages and DEB/RPM packages.
   - [x]  Install and verify the packages.
- [x]  Update documentation, scripts and Dockerfiles
   - [x]  Summarize the change log for the release. It should be reviewed by PM(s) to make it more user-friendly.
   - [x]  Update [CHANGELOG.md](../../CHANGELOG.md) with the finalized change log draft.
   - [x]  Update other documents and scripts to use the new package names and links. (update for the new name -- pwsh)
- [x]  Verify the release Dockerfiles.
- [x]  [Create NuGet packages](#nuget-packages) and publish them to [powershell-core feed][ps-core-feed].
- [x]  [Create the release tag](#release-tag) and push the tag to `PowerShell/PowerShell` repository.
- [x]  Create the draft and publish the release in Github.
- [x]  Merge the `release` branch to `master` and delete the `release` branch.
- [x]  Publish Linux packages to Microsoft YUM/APT repositories.
- [x]  Trigger the release docker builds for Linux and Windows container images.
   - [x]  Linux: push a branch named `docker` to `powershell/powershell` repository to trigger the build at [powershell docker hub](https://hub.docker.com/r/microsoft/powershell/builds/).
     Delete the `docker` branch once the builds succeed.
   - [x]  Windows: queue a new build in `PowerShell Windows Docker Build` on VSTS.
- [ ]  Verify the generated docker container images.
- [x]  [Update the homebrew formula](#homebrew) for the OSX package.
   This task usually will be taken care of by the community,
   so we can wait for one day or two and see if the homebrew formula has already been updated,
   and only do the update if it hasn't.
- [x] Open the next release milestone.

**Comment by daxian-dbw** [comment]
Test run results
----------------

Here are the test results for the non-windows platforms:
```
OS                           Pass Pending Skipped Fail Total
--                           ---- ------- ------- ---- -----
Debian GNU/Linux 9 (stretch) 6036     347    1185    1  7569
CentOS Linux 7 (Core)        6019     348    1185   17  7569
openSUSE Leap 42.3           6035     347    1185    2  7569
Red Hat Enterprise Linux     6018     347    1185   19  7569
Ubuntu 16.04.3 LTS           6036     347    1185    1  7569
Ubuntu 17.04                 6036     347    1185    1  7569
Ubuntu 14.04.5 LTS           6036     347    1185    1  7569
Debian GNU/Linux 8 (jessie)  6036     347    1185    1  7569
```

All the platforms had failures in Get-Help -Online as I run these tests in an SSH session, where no browser can be popped up.
Centos and Red Hat had failures in WebRequest/RestMethod because those systems don't support Client Authentication Certificate because of the version of curl and SSL Backend
Redhat had an additional error where the powershell process does not exit within 5 seconds. However, I have noticed that on this particular VM ALL native executables take an extraordinary about of time to exit.
