### ISSUE TITLE
get-childitem $pshome -include *.dll doesn't work as expected

### ISSUE THREAD

**Issue by chunqingchen** [PowerShell/PowerShell#5476]
After fixing the issue #3730, I find that get-childitem $pshome -include *.dll has strange behavior other than -literalPath 

Steps to reproduce
------------------
get-childitem $pshome -include *.dll

Expected behavior
-----------------
Return all the assembly files under $pshome root

Actual behavior
---------------
Nothing is returned.

Environment data
----------------

Name                           Value
----                           -----
PSVersion                      6.0.0-beta.9
PSEdition                      Core
GitCommitId                    v6.0.0-beta.9-61-g1721f348a5fe864661f2a4060f846cfcfcc3b611
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by iSazonov** [comment]
From PowerShell Core directory:
Don't works:
```powershell
get-childitem .\ -include *.dll
```
Works:
```powershell
get-childitem .\* -include *.dll
```

**Comment by TravisEz13** [comment]
I cannot reproduce the issue
