### ISSUE TITLE
unsigned modules should not load with `AllSigned` policy

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#5485]
Steps to reproduce
------------------

```powershell
Set-ExecutionPolicy -Policy AllSigned -scope process
import-module pester -force  #Import a module which lives in $PSHome
```

But if you copy Pester out of $PSHome it will not load

Expected behavior
-----------------

![image](https://user-images.githubusercontent.com/10873629/32920304-a0468ce6-cadd-11e7-992c-779cb569dacf.png)

Actual behavior
---------------
module loads without error

Notes
-------

PS 5.1 has the same behavior

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-rc
PSEdition                      Core
GitCommitId                    v6.0.0-rc
OS                             Microsoft Windows 6.1.7601 S
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by SteveL-MSFT** [comment]
Currently, PowerShell inherently trusts modules under $PSHome.  For Windows PowerShell, this was ok as only Trusted Installer or admin could put things under %windir%.  It would probably make sense to change this behavior.

**Comment by markekraus** [comment]
hmm... Would that force anyone who wanted to use a daily or build-from-source version to run their entire session in bypass?

**Comment by TravisEz13** [comment]
The default policy is unrestricted.  And only AllSigned would have this issue.  I don't think many people would have to change their workflow.  Only someone who chooses to enable this feature (only supported on windows).

**Comment by markekraus** [comment]
But the only way to run in AllSigned mode, then, would be official releases, no? 
Is this maybe something we could toggle on in release branches (totally fine with a release versions having this set), and then toggle off before it is merged back to master?

Makes it hard to test functionality in AllSigned default environment if it can only be done in a release. It's probably not a huge issue, but I'd rather voice this minor concern than say nothing. *shrugs

**Comment by TravisEz13** [comment]
I don't think we should have any such mechanism.  I think you could test this the vast majority of the time by using the modules from an official build.

**Comment by SteveL-MSFT** [comment]
We've always said that Execution Policy is not a security boundary, it's only to prevent unintentional incidents (aka shooting one self in the foot).  From that perspective, it seems that perhaps relying on $PSHome being properly ACL'd might be sufficient (and using our .msi installer does do that as only Trusted Installer has write access).

**Comment by TravisEz13** [comment]
We are installing 3rd party modules unsigned to PSHome, basically bypassing the policy by default.

**Comment by SteveL-MSFT** [comment]
I talked to @TravisEz13 , I think it's fine to remove the special casing of $PSHome
