### ISSUE TITLE
Master builds produce artifacts with '6.0.0.-rc' versioning instead of '6.1.0-preview.1'

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#5497]
If I understood correctly from the last community call, the `master` branch is now for `6.1.0` development.
However, the artifcats of `master` builds are versioned as `6.0.0.-rc`. See e.g. [here](https://ci.appveyor.com/project/PowerShell/powershell-f975h/build/6.0.0-rc-487/artifacts) for an example of the latest build.

Info: Latest commit of `master` as of November 18: [cb048ea9f4f7ccc3612141ee76f7937b9ca1c823](https://github.com/PowerShell/PowerShell/commit/cb048ea9f4f7ccc3612141ee76f7937b9ca1c823)

**Comment by iSazonov** [comment]
We still are in RC stage not GA.

**Comment by bergmeister** [comment]
I thought that is what the [6.0.0](https://github.com/PowerShell/PowerShell/tree/6.0.0) branch was for?

**Comment by SteveL-MSFT** [comment]
When we merged the changes from the RC release branch back to master, we merged everything including the version string.  Master should be 6.1.0-beta.1 while 6.0.0 continues on the Release branch.  cc @daxian-dbw

**Comment by iSazonov** [comment]
@SteveL-MSFT In blog [post ](https://blogs.msdn.microsoft.com/powershell/2017/11/17/powershell-core-6-release-candidate/) the branch link is broken in "we also created a _branch_ for the eventual PowerShell Core 6.0.0 final release. " I see Release branch renamed to 6.0.0.

**Comment by SteveL-MSFT** [comment]
@iSazonov thanks for catching that, will fix

**Comment by bergmeister** [comment]
@SteveL-MSFT Would it make sense to rather use the word `preview` instead of `beta` starting from `6.1` since .Net Core and the Visual Studio family use that term as well? Also, `preview` indicates that it is just the bleeding edge version of something that already had RTM quality, which  differentiates it from the past 6.0 betas.

**Comment by SteveL-MSFT** [comment]
@bergmeister agree, `preview` captures it better as being incomplete than `beta` which implies subpar quality

**Comment by iSazonov** [comment]
Based On SymVer 2.0 and modern life cycle we could give up on "beta" and "preview" and use 6.1.x on a daily basis.

**Comment by bergmeister** [comment]
[SemVer 2.0](http://semver.org/spec/v2.0.0.html) states that the 3rd number should only be for patches
> PATCH version when you make backwards-compatible bug fixes
