### ISSUE TITLE
6.0.0-rc - Documentation link need to reflect PowerShell Core material.

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#5500]
First, Congrats in accomplishing the RC milestone on PowerShell Core.

Now, the following link: https://aka.ms/pscore6-docs has good intention. But, the first thing I'm reading reflect Windows PowerShell which will "continue" to cause GREAT Confusion.

Also, looking further deep on the Documentation navigation, talks more about Windows PowerShell features: 
1. Get-WMIObject - which (I think) is not use in PowerShell Core.
2. Web Access for PowerShell - This is a Windows PowerShell feature. Please unless I'm wrong!
3. Windows PowerShell ISE  - In this case, should it be replace  to VS Code Editor??

This is just a few items. I'm hoping when the GA becomes available the documentation could be corrected.

Thanks and Great Work!!

Environment data
----------------

```powershell
PS C:\Program Files\PowerShell\6.0.0-rc> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-rc
PSEdition                      Core
GitCommitId                    v6.0.0-rc
OS                             Microsoft Windows 10.0.17040
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Program Files\PowerShell\6.0.0-rc>
```

**Comment by bergmeister** [comment]
@MaximoTrinidad I think this issue should rather be opened in the [PowerShell-Docs](https://github.com/PowerShell/PowerShell-Docs) repo.

**Comment by MaximoTrinidad** [comment]
@bergmeister 

Thanks for the suggestion!  I will copied over to the PowerShell-Doc repo.

:)

**Comment by MaximoTrinidad** [comment]
@bergmeister, It's done!

**Comment by bergmeister** [comment]
@MaximoTrinidad Linking to other issues using the hash does not work across repos. The correct link to the new issue is [here](https://github.com/PowerShell/PowerShell-Docs/issues/1871)

**Comment by MaximoTrinidad** [comment]
Thanks again! I'm closing this one,
👍
