### ISSUE TITLE
license/cla check in PRs stopped working

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#5502]
In new PRs from me and even @SteveL-MSFT (see e.g. [here](https://github.com/PowerShell/PowerShell/pull/5495)) , the `license/cla` check is hanging in status `Waiting for status to be reported`

**Comment by SteveL-MSFT** [comment]
I'm following up on this

**Comment by SteveL-MSFT** [comment]
Sent an email to the owners, but being the weekend...

**Comment by bergmeister** [comment]
Thanks.

**Comment by jeffwilcox** [comment]
FYI @MichaelTsengLZ

**Comment by jeffwilcox** [comment]
@SteveL-MSFT if you have any particular users whose contributions you would like to accept now being hit by this, e-mail their aliases and the pull requests, and we can perform a manual data source check for right now, letting you override as needed

**Comment by SteveL-MSFT** [comment]
@jeffwilcox would like my PR to be approved by the CLA bot https://github.com/PowerShell/PowerShell/pull/5495

**Comment by jeffwilcox** [comment]
@SteveL-MSFT that one has been validated now

**Comment by SteveL-MSFT** [comment]
@jeffwilcox thanks!

For anyone with open PRs affected by this, please close and reopen them.

**Comment by bergmeister** [comment]
Thanks. I re-opened the PRs and it worked :-). As far as I have seen there are no other PRs left.
