### ISSUE TITLE
Is there a way to avert the diamond dependency problem for modules that use .Net types?

### ISSUE THREAD

**Issue by alx9r** [PowerShell/PowerShell#5504]
It seems like certain things can only be defined once per PowerShell session.  Public enums named in calls to `Add-Type` are one such example.  In the repro below, a .Net enum of a particular name could only be defined once even though the two definitions are in separate modules.  Working around such naming collisions amongst unrelated modules is usually a one-time event.  However, the same problem manifests when more than one version of the same module is required to exist in a single session.  This occurs every time a .Net type in a low-level module changes and the mid-level modules aren't updated simultaneously.  I've been running into this problem in PowerShell with increasing frequency as I incorporate more third-party libraries and as my code has become more modular.  

As far as I've read this problem is called "the diamond dependency problem" ([video](https://www.youtube.com/watch?v=tISy7EJQPzI&feature=youtu.be&t=15m0s)).  The repro below demonstrates the canonical scenario described in the video in PowerShell.

There seems to be some signs that C# projects can load multiple versions of the same assembly thereby averting the diamond dependency problem (e.g. [stackoverflow question](https://stackoverflow.com/questions/4451220/loading-multiple-versions-of-the-same-assembly)).  Is there a similar strategy that works in PowerShell?

Steps to reproduce
------------------

```powershell
New-Module libutil_v1 {
    Add-Type -TypeDefinition 'public enum E {a,b,c}'
    function f {
        param
        (            
            [e]
            $E
        )
    }
} | Import-Module

New-Module libutil_v2 {
    Add-Type -TypeDefinition 'public enum E {a,b,c,d}'
    function f {
        param
        (            
            [e]
            $E
        )
    }
} | Import-Module

New-Module liba {
    Get-Module libutil_v1 | Import-Module

    function g_a {
        f -E c
    }
} | Import-Module

New-Module libb {
    Get-Module libutil_v2 | Import-Module

    function g_b {
        f -E d
    }
} | Import-Module


g_a
g_b
```

Expected behavior
-----------------

No exception thrown.

Actual behavior
---------------

```none
Add-Type : Cannot add type. The type name 'E' already exists.
At C:\users\un1\Desktop\test.ps1:13 char:5
+     Add-Type -TypeDefinition 'public enum E {a,b,c,d}'
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (E:String) [Add-Type], Excepti
   on
    + FullyQualifiedErrorId : TYPE_ALREADY_EXISTS,Microsoft.PowerShell.Command
   s.AddTypeCommand

f : Cannot process argument transformation on parameter 'E'. Cannot convert
value "d" to type "E". Error: "Unable to match the identifier name d to a
valid enumerator name. Specify one of the following enumerator names and try
again:
a, b, c"
At C:\users\un1\Desktop\test.ps1:35 char:14
+         f -E d
+              ~
    + CategoryInfo          : InvalidData: (:) [f], ParameterBindingArgumentTr
   ansformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,f
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.0-beta.8                                    
PSEdition                      Core                                            
GitCommitId                    v6.0.0-beta.8                                   
OS                             Microsoft Windows 6.3.9600                      
Platform                       Win32NT                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1                                         
WSManStackVersion              3.0                                             
```

**Comment by iSazonov** [comment]
Add-Type uses a default namespace. I think `Add-Type -Namespace` resolves the issue.

**Comment by iSazonov** [comment]
@daxian-dbw Could you please clarify why we first [load assembly](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs#L1194) and only then check duplicate types? I'd expect that terminating error should prevent loading the assembly with duplicate types.

**Comment by daxian-dbw** [comment]
@iSazonov I agree with you that the duplicate type check should happen before actually loading the assembly. With the current behavior, 2 assemblies containing 2 different implementations of the same type name should be loaded in the AppDomain, and either one will be used when the user references the type name depending on the randomly generated assembly names by Add-Type.

I think we check duplicates after loading now because it's easier. Before loading, it might be harder to know what types are in the assemblies. But I guess we can use the `SyntaxTree` returned from `CSharpSyntaxTree.ParseText` to get that information.

**Comment by daxian-dbw** [comment]
@iSazonov I found an interesting issue when playing with `Add-Type` and opened #5515

**Comment by iSazonov** [comment]
I discover that `CheckTypesForDuplicates` has a wonder logic - it can add new non-duplicate types in a loaded type cache and then throw on duplicate type - and we get full mess with types.

I think our logic should be simple - don't load an assembly if the one contains duplicate types  in relation to loaded ones.

I still not found how get types from `SyntaxTree`. And it seems we need `SemanticModel` not `SyntaxTree`. Roslyn types isn't well-documented. The alternative way is to use new AppDomain to load imitted assembly, maybe with `ReflectionOnlyLoad()` - I don't know if it works.

**Comment by alx9r** [comment]
>Add-Type uses a default namespace. I think Add-Type -Namespace resolves the issue.

@iSazonov Are you suggesting that, to avert this problem, the types used by the `liba` and `libb` modules should be namespaces named uniquely for each minor version of `libutil`?  So accessing the type from, say version 1.3.2 of module `liba` would look like `[libutil.v1_0_0.E]`, for example.  And accessing the type from version 1.3.3 of module `liba` would look like `[libutil.v_1_0_1.E]`.

**Comment by iSazonov** [comment]
@alx9r You can use this as workaround for this certain case.

**Comment by iSazonov** [comment]
Bugs in `Add-Type` fixed. Can we close the Issue? Currently we have a workaround. General solution requires a significant alteration in the type resolution.
