### ISSUE TITLE
Duplicates in ZIP distribution file.

### ISSUE THREAD

**Issue by thezim** [PowerShell/PowerShell#5506]
In [PowerShell-6.0.0-rc-win-x64.zip](https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-rc/PowerShell-6.0.0-rc-win-x64.zip) there is a folder called `signed`. All files within in `signed` folder and subfolders exist at the parent level, their hashes are identical.

Is this a leftover from packaging or is there some other purpose for these files?

**Comment by SteveL-MSFT** [comment]
Seems like leftover from packaging
