### ISSUE TITLE
Set-Service -Status Stopped should not prevent stopping of services without dependents only because they depend on others

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#5517]
`Set-Service -Status Stopped` not only prevents stopping services that other services _depend on_ (`.DependentServices`), but, curiously, also services that _themselves_ depend on others (`.ServicesDependedOn`.

For instance, the `wuauserv` service has no dependents, but itself depends on the `rpcss` service.

As an aside: `Set-Service -Status Stopped` lacks a `-Force` switch that would allow it to stop dependent services too, the way `Stop-Service` offers.

Steps to reproduce
------------------

```powershell
Set-Service -Status Stopped wuauserv
```

Expected behavior
-----------------

Given that the service has no dependents, it should be stopped.

Actual behavior
---------------

The following error occurs:

```none
Set-Service : Cannot stop service 'Windows Update (wuauserv)' because it is dependent on other services.
...
```

That the service depends on _other_ services shouldn't prevent its stopping.

Environment data
----------------

```powershell
PowerShell Core 6.0.0-rc on on Microsoft Windows 7 Enterprise  (64-bit; v6.1.7601)
Windows PowerShell v5.1.14409.1012 on Microsoft Windows 7 Enterprise  (64-bit; v6.1.7601)
```

**Comment by zhenggu** [comment]
Need some helps for adding a new service to test Set-Service Cmdlet.
