### ISSUE TITLE
Invoke-WebRequest does not support UTF-8

### ISSUE THREAD

**Issue by lipkau** [PowerShell/PowerShell#5528]
@## Steps to reproduce
**Assuming you have a URI that returns json and contains a non-Latin char**
_My sample is a [Confluence](https://www.atlassian.com/software/confluence) wiki page which I am requesting with REST_

```powershell
$splatParameters = @{
              Uri             = "https://powershell.atlassian.net/wiki/rest/api/content/13009245?expand=space,version,body.storage,ancestors&limit=25"
              Method          = "GET"
              Headers         = @{
  "Accept-Charset"                = "utf-8"
  "Accept"                        = "application/json"
  "Content-Type"                  = "application/json; charset=utf-8"
  "Authorization"                 = "Basic abcd"
  }
              UseBasicParsing = $true
              ErrorAction     = 'SilentlyContinue'
          };
  Set-Content -Value (Invoke-WebRequest @splatParameters).Content -Path c:\temp\export.txt -Encoding UTF8 -force
```

## Expected behavior
`Invoke-WebRequest` is able to write the file with full support of the unicode chars of the source.
_In this example: `Схема СКУД`_

## Actual behavior
The REST call should return a json like this:
```
{"id":"13009245","type":"page","status":"current","title":"Схема СКУД","space":{....
```

instead, the content of `c:\temp\export.txt` (see example ebove) contains:
```
{"id":"13009245","type":"page","status":"current","title":"Ð¡ÑÐµÐ¼Ð° Ð¡ÐÐ£Ð","space":{.....
```

## Environment data

```powershell
PS C:\Program Files\PowerShell\6.0.0-rc> $PSVersiontable

Name                           Value
----                           -----
PSVersion                      6.0.0-rc
PSEdition                      Core
GitCommitId                    v6.0.0-rc
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by markekraus** [comment]
@lipkau Have you reproduced this issue in 6.0.0-rc? This repository is for PowerShell Core issues. if you have an issue with Windows PowerShell 5.1, please use the [UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell).

**Comment by lipkau** [comment]
Yes... I am waiting on @jaykul for the `$PSVersionTable` (he tested it for me)

**Comment by lipkau** [comment]
VersionTable updated

**Comment by markekraus** [comment]
Since this issue has some non-latin characters in it and is accessible via an API that returns application/json the following should be an equivalent repro:

```powershell
$response = Invoke-WebRequest 'https://api.github.com/repos/PowerShell/PowerShell/issues/5528'
Set-Content -Value $response.Content -Path c:\temp\export.txt -Encoding UTF8 -force
```

When I do that, I see `Схема СКУД` in the file.

Are you sure that 1) the API you are working with is actually returning UTF8 encoding and 2) the body of that content is actually encoded in utf8?

```powershell
$response.BaseResponse.Content.Headers.ContentType.CharSet

```

**Comment by lipkau** [comment]
This seems to be a Confluence API problem.
Closing this issue.
