### ISSUE TITLE
Enter Key on Mac Extended Keyboard enters OM instead of a new line on macOS

### ISSUE THREAD

**Issue by kai-h** [PowerShell/PowerShell#5531]
Steps to reproduce
------------------

Install PowerShell on macOS
Open a new shell.
Type in a command and hit the Enter key (on the numeric keypad) instead of the Return key

Expected behavior
-----------------
It is expected that the Enter key and the Return key behave the same - they terminate a new line and they enter a command.

Actual behavior
---------------
The Enter key inserts OM instead of a new line

Environment data
----------------
```
Name                           Value                                           
----                           -----
PSVersion                      6.0.0-rc
PSEdition                      Core
GitCommitId                    v6.0.0-rc
OS                             Darwin 16.7.0 Darwin Kernel Version 16.7.0: T...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kai-h** [comment]
Confirming that using the Enter key on the keypad works as expected on Windows 10.

**Comment by thezim** [comment]
@kai-h I could not repro this issue.

Numeric key pad `Enter` key:

```powershell
PS /Users/greg> $host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")

VirtualKeyCode Character ControlKeyState KeyDown
-------------- --------- --------------- -------
            13                        0    True
```

`Return` key:

```powershell
PS /Users/greg> $host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")

VirtualKeyCode Character ControlKeyState KeyDown
-------------- --------- --------------- -------
            13       ...               0    True
```

**Comment by kai-h** [comment]
OK, that's odd - I don't recall having any strange terminal settings, however the Enter key on the keypad seems to returning code 79 and the Return key returns 13.
In the example below, the Enter key was the first example and the Return key was the second one
```
PS /Users/kai> $PSVersionTable                                                  

Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.0-rc                                        
PSEdition                      Core                                            
GitCommitId                    v6.0.0-rc                                       
OS                             Darwin 16.7.0 Darwin Kernel Version 16.7.0: T...
Platform                       Unix                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1                                         
WSManStackVersion              3.0                                             


PS /Users/kai> $host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")                  

VirtualKeyCode Character ControlKeyState KeyDown
-------------- --------- --------------- -------
            79         O               0    True


PS /Users/kai> $host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")                  

VirtualKeyCode Character ControlKeyState KeyDown
-------------- --------- --------------- -------
            13       ...               0    True

```

**Comment by SteveL-MSFT** [comment]
@kai-h if you use the numeric Enter key in TextEdit, does it show `O` or a newline?  Seems like your keyboard is configured incorrectly and probably not an issue with PowerShell.

**Comment by kai-h** [comment]
The Enter key seems to work correctly everywhere else.
In TextEdit, it inserts a new line.

**Comment by SteveL-MSFT** [comment]
Do you have a PowerShell profile defined?  `cat $profile`.  If you use `remove-module psreadline`, does it still do that?

**Comment by kai-h** [comment]
No, there's no profile defined - this is a stock-standard Powershell install.
```
[kai@blackmac ~]$ pwsh
PowerShell v6.0.0-rc
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS /Users/kai>  cat $profile                                                    
cat: /Users/kai/.config/powershell/Microsoft.PowerShell_profile.ps1: No such file or directory
PS /Users/kai> 
```
Here it is removing the module:
```
[kai@blackmac ~]$ pwsh
PowerShell v6.0.0-rc
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS /Users/kai> remove-module psreadline                                                                                    
PS /Users/kai> this is hitting the enter key 4 times OMOMOMOM
```

**Comment by thezim** [comment]
@kai-h Double check your `Keyboard` tab in `Terminal` and see if there are any mapping there. Also look at the `Advanced` tab. Here is what mine looks like.

![issue](https://user-images.githubusercontent.com/14023826/33297431-f978bbd4-d3ae-11e7-83c6-1088454b4cfb.png)

**Comment by kai-h** [comment]
My terminal app should be pretty much default settings with the exception that I use the Man Page preset as the default settings (what with cutting my teeth on Solaris). The only other difference I can think of is that my locale is set to English (Australia) - en_AU.UTF-8 but the Australian keyboard layout is identical to the US English keyboard layout (unlike, say, the UK English layout)
Here's my Keyboard tab in Terminal app:
![screen shot 2017-11-28 at 7 54 55 pm](https://user-images.githubusercontent.com/597823/33310622-5879e3b6-d476-11e7-84b8-0394a5e4629d.png)
And here's my Advanced tab:
![screen shot 2017-11-28 at 7 54 28 pm](https://user-images.githubusercontent.com/597823/33310640-66fb6086-d476-11e7-8568-9beefffc4338.png)

**Comment by lzybkr** [comment]
This sounds like a bug in corefx, assuming w/o PSReadLine, we're just calling `Console.ReadLine`.

**Comment by daxian-dbw** [comment]
I will close this one for
1. it was not able to repro the issue
2. it sounds like a .NET Core issue at the time, and could be fixed already.
