### ISSUE TITLE
When copying output to the clipboard on macOS, output is padded to 80 columns wide with whitespace

### ISSUE THREAD

**Issue by kai-h** [PowerShell/PowerShell#5532]
Steps to reproduce
------------------
Install PowerShell on macOS
Open a new PowerShell instance
Do something that causes text to be output to the terminal
Copy and paste this text into somewhere else, e.g. a text editor or an email.
There is extraneous whitespace at the end of every line to pad it out to the width of my Terminal window, which is by default 80 columns.

Expected behavior
-----------------
It is expected that the text output in the Terminal will not have extra whitespace at the end of each and every line.

Actual behavior
---------------
Output is padded to the width of the Terminal window.
e.g. if you look at the output for $PSVersionTable below, copy and paste it into a text editor and you will notice that every line is 150 characters long, padded out with the space character. My Terminal window was 150 characters wide so that it could fit in the output for the OS line without truncating it.

Environment data
----------------
```
PS /Users/kai> $PSVersionTable                                                                                                                        

Name                           Value                                                                                                                 
----                           -----                                                                                                                 
PSVersion                      6.0.0-rc                                                                                                              
PSEdition                      Core                                                                                                                  
GitCommitId                    v6.0.0-rc                                                                                                             
OS                             Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64        
Platform                       Unix                                                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                               
PSRemotingProtocolVersion      2.3                                                                                                                   
SerializationVersion           1.1.0.1                                                                                                               
WSManStackVersion              3.0                                                                                                                   
```

**Comment by iSazonov** [comment]
I can not repo on Windows.

**Comment by kai-h** [comment]
Yes, it works correctly on Windows 10. I haven't tested it on Linux.

**Comment by thezim** [comment]
Repros for me. Using `Trailing Spaces` extension for vscode.

![issue](https://user-images.githubusercontent.com/14023826/33192571-7b46a02a-d091-11e7-96e0-a9dd6247878c.png)

**Comment by iSazonov** [comment]
@thezim What is a platform/version you repo on?

**Comment by thezim** [comment]
@iSazonov High Sierra.

```powershell
PS /Users/greg> $PSVersionTable                                                                                                     

Name                           Value                                                                                               
----                           -----                                                                                               
PSVersion                      6.0.0-rc                                                                                            
PSEdition                      Core                                                                                                
GitCommitId                    v6.0.0-rc                                                                                           
OS                             Darwin 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/R...
Platform                       Unix                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                             
PSRemotingProtocolVersion      2.3                                                                                                 
SerializationVersion           1.1.0.1                                                                                             
WSManStackVersion              3.0                                                                                                 
```

```powershell
PS /Users/greg> sw_vers                                                                                                             
ProductName:	Mac OS X
ProductVersion:	10.13.1
BuildVersion:	17B48
```

Running a native command within PowerShell does not exhibit the same output behavior..

![issue](https://user-images.githubusercontent.com/14023826/33224203-e545c7aa-d134-11e7-99f5-f0d97ca13bbb.png)

**Comment by mklement0** [comment]
This behavior is by (perhaps unfortunate) design: 

PowerShell's formatting system _always_ produces lines right-padded to the (implied or explicitly specified) output width with spaces.

It is only when you copy directly from a Windows console window that _it_ extends you the (debatable) courtesy of trimming the trailing spaces (the macOS terminal program doesn't do that, and neither does Ubuntu's default terminal program, for instance).

You can verify the behavior by piping to `clip` on Windows as opposed to manually copying in the console window:

```powershell
Get-Item / | clip  # text on clipboard will have trailing spaces
```

**Comment by thezim** [comment]
Is this something that can be change without breaking something? Seems inefficient for a console to waste time displaying right padded characters.

**Comment by iSazonov** [comment]
It would be interesting to know the history of that console padding.

**Comment by kai-h** [comment]
I'm having most output padded to, say, 80 columns, but not all. e.g. the output from  $host.UI.RawUI.ReadKey isn't padded:
![screen shot 2017-11-26 at 6 35 49 pm](https://user-images.githubusercontent.com/597823/33238057-f1293462-d2d8-11e7-856c-3c90c0b2269c.png)

**Comment by mklement0** [comment]
@kai-h: 

The padding happens only when PowerShell's formatting system is involved, which in turn only happens if a type has been configured with associated formatting data, as described in `Get-Help about_Format.ps1xml`.

To illustrate the difference (assume an 80-column terminal):

```powershell
# The type of $PSVersionTable derives from [hashtable], which has formatting data associated with it
# -> PADDING 
# All nonempty lines are padded to the output width, which defaults to the terminal width.
> $PSVersionTable | Out-String -Stream | % Length
0
80
80
80
80
80
80
80
80
80
80
80
0
0


# [System.Management.Automation.Host.KeyInfo], as returned by `$host.ui.RawUI.ReadKey()`,
# has NO formatting associated with it
# -> NO padding.
> [System.Management.Automation.Host.KeyInfo]::new(65, 'A', 0, $True) | Out-String -Stream | % Length
0
48
48
48
0
0
```

Normally you could use `Get-FormatData <type-name>` to check if a given type has associated formatting data, but that is currently broken - see #4237 and #4235.

**Comment by SteveL-MSFT** [comment]
This appears to be `by design`.  Any table view has padding.  Any non-table view, I made a PR to remove padding.

**Comment by thezim** [comment]
What about the the PS > line itself? I see it is being padded as well.

**Comment by mklement0** [comment]
@SteveL-MSFT: Thanks for the clarification re table view.

We now know that the behavior is by design, but perhaps it's time to revisit that, as @thezim suggests - especially given that it is behavior related to _for-display-only_ output that no one can expect to rely on for long-term stability and machine parsing, as [@lzybkr  has previously noted](https://github.com/PowerShell/PowerShell/issues/4767#issuecomment-328904091).

Doing away with the padding might also help with #4767 and the [fix that @lzybkr had contemplated](https://github.com/PowerShell/PowerShell/issues/4767#issuecomment-329243332).

**Comment by iSazonov** [comment]
These trailing spaces may be necessary (on display only) if we want to recolor the background of the table.

**Comment by kai-h** [comment]
Following "The law of least surprise" for how things generally should work, if you're getting plain text output, it should not be padded to some arbitrary width that depends on the size of your Terminal window. If it's padded (and it probably shouldn't be) it would possibly be better to be padded to a fixed width, dependent on the width of the output table.
Or, if you're not recolouring the output, it shouldn't be padded at all.
Or somehow have the trailing spaces trimmed when copying to the clipboard, however this may be out of your control and depend more on the Terminal app in use.

**Comment by iSazonov** [comment]
Users may want to copy including color.

**Comment by lzybkr** [comment]
Copying w/ color works fine w/o padding, `CaptureScreen` in PSReadLine handles it cleanly.

**Comment by mklement0** [comment]
Re color and output width: also note that adjusting the output behavior based on whether a _terminal_ is being targeted or not is sensible, as many Unix utilities (e.g., `ls`) do (which is again what  #4767 would benefit fromtoo).

**Comment by SteveL-MSFT** [comment]
For Tables, it seems that there should be no reason for the trailing padding.  A new line should be sufficient.  This isn't macOS specific, it repros on Linux as well (the code is the same on all platforms).  I think Windows clipboard may be doing something to trim trailing whitespace...

I'll look into this as I've made changes to this code previously and think it should be a small change (although not entirely sure of the side effects...)

**Comment by iSazonov** [comment]
If console background is black and we output a table with green background then we can not trim trailing whitespace - we lost green background.

**Comment by mklement0** [comment]
>  I think Windows clipboard may be doing something

It's actually the _console window_ that does it (copying directly out of a window) - if you pipe to `clip.exe` in order to copy to the clipboard, you do get the padding.

**Comment by SteveL-MSFT** [comment]
@iSazonov I think we should support cells in the table having a background, but not the entire table.  Alternatively, if we want to support colored background, then we can special case that to preserve padding.
