### ISSUE TITLE
Update-Help not installing help files locally

### ISSUE THREAD

**Issue by fabio-muramatsu** [PowerShell/PowerShell#5534]
Steps to reproduce
------------------
1. Open Powershell as admin
2. Run `Update-Help -Force`

Expected behavior
-----------------
Help files are installed and accessible when running Get-Help.

Actual behavior
---------------
Help files are not installed locally, and running Get-Help returns the message `Get-Help cannot find the Help files for this cmdlet on this computer. It is displaying only partial help.`.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-rc
PSEdition                      Core
GitCommitId                    v6.0.0-rc
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Observations
----------------
I was unable to reproduce this problem in 2 other systems, both running Windows 10 Fall Creators Update and the same version of Powershell, so I'm not sure if this is related to the affected system being on Creators Update. Any help would be appreciated.

**Comment by iSazonov** [comment]
You could use some sniffer to see  that you have access to the help update site.

**Comment by fabio-muramatsu** [comment]
Hi, thanks for the response.
I think the updater is managing to reach the update site, or at least I'm not getting any connection errors when running in verbose mode:
```
> Update-Help -Force -Verbose
VERBOSE: Resolving URI: "https://go.microsoft.com/fwlink/?linkid=855958"
VERBOSE: Your connection has been redirected to the following URI: "https://pshelp.blob.core.windows.net/powershell/help/6/Microsoft.PowerShell.Management/"
VERBOSE: Resolving URI: "https://go.microsoft.com/fwlink/?linkid=855958"
VERBOSE: Your connection has been redirected to the following URI: "https://pshelp.blob.core.windows.net/powershell/help/6/Microsoft.PowerShell.Management/"
VERBOSE: Resolving URI: "https://go.microsoft.com/fwlink/?linkid=855960"
VERBOSE: Your connection has been redirected to the following URI: "https://pshelp.blob.core.windows.net/powershell/help/6/Microsoft.PowerShell.Utility/"
VERBOSE: Resolving URI: "https://go.microsoft.com/fwlink/?linkid=855960"
VERBOSE: Your connection has been redirected to the following URI: "https://pshelp.blob.core.windows.net/powershell/help/6/Microsoft.PowerShell.Utility/"
VERBOSE: Resolving URI: "https://go.microsoft.com/fwlink/?linkid=855966"
VERBOSE: Your connection has been redirected to the following URI: "https://pshelp.blob.core.windows.net/powershell/help/6/PSReadLine/"
VERBOSE: Resolving URI: "https://go.microsoft.com/fwlink/?linkid=855966"
VERBOSE: Your connection has been redirected to the following URI: "https://pshelp.blob.core.windows.net/powershell/help/6/PSReadLine/"
VERBOSE: Resolving URI: "https://go.microsoft.com/fwlink/?linkid=855946"
VERBOSE: Your connection has been redirected to the following URI: "https://pshelp.blob.core.windows.net/powershell/help/6/CimCmdlets/"
VERBOSE: Resolving URI: "https://go.microsoft.com/fwlink/?linkid=855946"
VERBOSE: Your connection has been redirected to the following URI: "https://pshelp.blob.core.windows.net/powershell/help/6/CimCmdlets/"
...
```
However, I don't see any attempts to save the help files. I'll see if it's actually downloading anything from these requests.

**Comment by iSazonov** [comment]
I believe `-verbose` isn't useful in the case. You need sniff real trafic.

**Comment by fabio-muramatsu** [comment]
Ok, I see a bunch of data being exchanged with pshelp.blob.core.windows.net, but since it's TLS-encrypted it's hard to tell what's going on from a sniffer. 
There are a few plain HTTP requests to urls like http://download.microsoft.com/download/B/2/B/B2BD8D1A-073E-468E-8191-DB39EB94AE18/PackageManagement_4ae9fd46-338a-459c-8186-07f910774cb8_HelpInfo.xml, which returns a small XML file with culture info, apparently.

**Comment by iSazonov** [comment]
I'd compare working and broken traces.

**Comment by fabio-muramatsu** [comment]
Hey, just found the issue! My system language is pt-br, so when I ran specified `-UICulture en-US` it worked as expected. Anyways, thanks for your help!
