### ISSUE TITLE
[ref] may be unwrapped unexpectedly

### ISSUE THREAD

**Issue by nightroman** [PowerShell/PowerShell#5535]
`[ref]` may be used for functions returning something via `[ref]` parameters in
addition to the output or instead of the output.

See

    help about_Ref

There may be problems though when by design `[ref]` is just one of the possible
parameter types. In PowerShell such parameters are normally declared as
`[object]` or `[object[]]`. Namely, `[ref]` may be unexpectedly unwrapped or
expectedly sent as `[ref]` depending (surprisingly) on using or omitting the
parameter name.

Steps to reproduce
------------------

Test-1.lost.ref.object.ps1

```powershell
function Get-ParamType([object]$Param) {
    $Param.GetType().Name
}

# [ref] object
$var = [ref]'bar'

# PSReference, expected
Get-ParamType $var

# String, UNEXPECTED
Get-ParamType -Param $var
```

Test-2.lost.ref.array.ps1

```powershell
function Get-ParamType([object[]]$Param) {
    $Param[0].GetType().Name
}

# [ref] object
$var = [ref]'bar'

# PSReference, expected
Get-ParamType $var
Get-ParamType -Param @($var)

# String, UNEXPECTED
Get-ParamType -Param $var
```

Expected behavior
-----------------

In all cases the type of the received parameter is `PSReference`, i.e. `[ref]`
is not unwrapped.

Actual behavior
---------------

In some cases the type of the received parameter is `PSReference`, as expected,
in others it is `String`, i.e. `[ref]` is unwrapped.

Another concern
---------------

The result depends on whether we send the data as the positional or named
parameter. Whatever the desired behaviour for `[ref]` is, the result must
be at least consistent.

Environment data
----------------

v5, v6-rc

```
Name                           Value
----                           -----
PSVersion                      5.1.15063.674
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.674
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Name                           Value
----                           -----
PSVersion                      6.0.0-rc
PSEdition                      Core
GitCommitId                    v6.0.0-rc
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
[ref] is desined for using with COM-object. So I'd want to see a repo more related to COM.

**Comment by nightroman** [comment]
See

    help about_Ref

I do not know how this manual is related to COM-objects. It describes a totally different scenario.

**Comment by lzybkr** [comment]
I'm told (this is before my time) that `[ref]` was added to support COM. By some luck, it also happened to work for C# `ref` and `out`, but it wasn't meant to be used in some of the ways people do use it today.

I think it's more of an implementation artifact than a real design that you can use `[ref]` like a type. That doesn't mean it's not useful, just that the implementation never considered such usage.

**Comment by nightroman** [comment]
I realize that I hit a scenario with not well defined behaviour. In reality
complex systems often have such areas. This is fine if a user has a chance
to feel that he is experimenting with something questionable and using on
his own risk.

But in PowerShell when I look at `[ref]` as a potential tool for a task I see
nothing that helps me to avoid the trap. I see a handy tool and PowerShell
encourages me using `[ref]`, too.

- It provides the type accelerator `[ref]` (use me!).
- The .NET type behind it looks straightforward and innocent.
- It provides the help topic `about_Ref` where it shows how `[ref]` is used as
  a type for solving a typical task (get something from a command in addition
  to normal output). Very good, I need exactly this.
- It has no usage warnings in this topic and does say "designed for COM".
- Finally, PowerShell even sometimes works with `[ref]` as one may expect, so
  one may think "fine, let's go for it". That is what happened to me. My code
  worked for a while (see examples). Then I realized that if the calls change
  in some seemingly innocent way then the result changes (see examples).
  It was not easy or fast to find the reason of the problem, it is unusual.

**Comment by nightroman** [comment]
And another thing that looks suspicions is the difference of results.

For a command with a positional parameter there are must be no difference
between calling with the parameter name specified or omitted,
at least with the only parameter set. Is this correct?

If this is correct then something is not quite right in the current PowerShell
because the examples show the difference.

Maybe the difference is about `[ref]` only. But I cannot be sure anymore.
I have the fact that processing is different. What else may cause the
difference? In my software, should I test both scenarios, in order to
be sure I covered different PowerShell code paths and processing?

**Comment by iSazonov** [comment]
>should I test both scenarios...?

Do you have other scenarios (without `[ref]`) in which this distinction manifests itself?

**Comment by nightroman** [comment]
> Do you have other scenarios (without [ref]) in which this distinction manifests itself?

No. The `[ref]` case if the first. As soon as I found it I reported it.
I do not quite understand the reason for this question. If I knew something I would tell this right away.

**Comment by iSazonov** [comment]
Do we have to understand - is the problem only with this or more general?

**Comment by nightroman** [comment]
I afraid somebody may have to look at the code and understand what it is doing.
