### ISSUE TITLE
Set-Item -Value should bind pipeline input by property name only; [object] pipeline-binding parameters that bind by value cannot also bind by property name

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#5543]
A concrete example to illustrate the larger problem:

`Set-Item`'s `-Value` parameter is declared to bind pipeline input both by value and by property name.

However, given that the parameter type is `[object]`, the binding by property _name_ can never take effect - the by-value binding always preempts it, because _any_ input object matches type `[object]`.

Binding the whole object is generally undesirable, especially if you want to use a single input object to bind to both the `-PSPath` and `-Value` parameters (as would be possible with CliXML data imported from an earlier `Get-ChildItem env: | Export-CliXml ...` command, for instance).

Steps to reproduce
------------------

Try to set an environment variable via a custom object with `PSPath` and `Value` properties:

```powershell
[pscustomobject] @{ PSPath = 'Environment::FOO'; Value = 'bar' } | Set-Item; $env:FOO
```

Expected behavior
-----------------

```none
bar
```

Actual behavior
---------------

```none
@{PSPath=Environment::FOO; Value=bar}
```

As you can see, the whole input object was bound to `-Value`, and its stringification became the env. variable value.

---

The problem affects all cmdlets that:

* have  parameters that bind pipeline input by _both_ value and property name 
* _and_ are typed generically, as follows:

  * `[object]` / `[object[]]`
  * `[psobject]` / `[psobject[]]`

As of PowerShell Core v6.0.0-rc, the **following cmdlets are affected**:

```none
CommandName      Name        Aliases  ParameterType                          
-----------      ----        -------  -------------                          
Add-Content      Value       {}       System.Object[]                        
ConvertFrom-Csv  InputObject {}       System.Management.Automation.PSObject[]
ConvertTo-Csv    InputObject {}       System.Management.Automation.PSObject  
Export-Csv       InputObject {}       System.Management.Automation.PSObject  
New-Item         Value       {Target} System.Object                          
New-Variable     Value       {}       System.Object                          
Set-Content      Value       {}       System.Object[]                        
Set-Item         Value       {}       System.Object                          
Set-ItemProperty InputObject {}       System.Management.Automation.PSObject  
Set-Variable     Value       {}       System.Object                          
```

The correct resolution will have to be decided on a cmdlet-by-cmdlet basis; those with problematic `-InputObject` parameters may simply have been defined as by-property-value-also by mistake, for instance.

Environment data
----------------

```powershell
PowerShell Core v6.0.0-rc on macOS 10.13
PowerShell Core v6.0.0-rc on Ubuntu 16.04.3 LTS
PowerShell Core v6.0.0-rc on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
Windows PowerShell v5.1.15063.674 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by iSazonov** [comment]
Interesting, is this common binding behavior for all cmdlets?

**Comment by mklement0** [comment]
@iSazonov: Please see my update.

**Comment by atruskie** [comment]
I just ran into this, when coincidently trying to achieve the same thing:

```pwsh
[pscustomobject]@{"Path"="Env:Year";"Value"="1199"}  | Set-Content 
```

Expected: `1199`
Actual: `@{Path=Env:Year; Value=1199}`
