### ISSUE TITLE
Tab completion should return XML documentation for tooltips

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PowerShell#5553]
The [ToolTip property](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.completionresult.tooltip?view=powershellsdk-1.1.0#System_Management_Automation_CompletionResult_ToolTip) exists to give additional information about a completion.

XML documentation is available on many machines (often in `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework`) and should be used if available.

Parsing the XML is relatively straightforward, I found this [blog](https://www.brad-smith.info/blog/archives/220) useful, and more complete documentation [here](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/processing-the-xml-file) - check the license before taking any open source code though.

**Comment by lzybkr** [comment]
I still think this would be really useful.

**Comment by ThomasNieto** [comment]
@StevenBucher98 please tag this for working group review.

**Comment by ThomasNieto** [comment]
@MartinGC94 does this issue interest you? 😉

**Comment by MartinGC94** [comment]
I'm afraid of the potential performance impact. I'd rather have an API that editors can call and display in a window the same way VS does when you press Ctrl+Shift+Space:
![image](https://github.com/user-attachments/assets/5b62f432-0258-4979-a5f5-ccdb62145777)
