### ISSUE TITLE
v6.0.0-rc: unable to execute a command on a remote host

### ISSUE THREAD

**Issue by Ricordel** [PowerShell/PowerShell#5563]
Steps to reproduce
------------------
I have a VM running, and I'm trying to execute a command remotely with the following command (from a bash shell). It sometimes crashes (see #5562), and when it does not, nothing is executed on the remote host.

```bash
    pwsh -Command - <<EOF
\$Username = '$VM_USER'
\$Password = '$VM_PASSWORD'
\$SecurePassword = ConvertTo-SecureString -AsPlainText \$Password -Force
\$Cred = New-Object System.Management.Automation.PSCredential -ArgumentList \$Username,\$SecurePassword
Invoke-Command -ComputerName $VM_IP -Credential \$Cred -Authentication Basic -Command { $VM_COMMAND }
EOF
```

Expected behavior
-----------------

The command executes on the remote host

Actual behavior
---------------

The execution fails, and by running tcpdump at the same time on the interface that connects the host and the virtual machine, I can tell that absolutely no network communication is attempted, not even opening a TCP connection. Here is the run with strace monitoring the `socket` and `connect` calls. As an attachement you'll find a run with `strace` monitoring everything.

[strace.log](https://github.com/PowerShell/PowerShell/files/1509252/strace.log)

```none
socket(PF_LOCAL, SOCK_DGRAM|SOCK_CLOEXEC, 0) = 40
connect(40, {sa_family=AF_LOCAL, sun_path="/dev/log"}, 110) = -1 ENOENT (No such file or directory)
socket(PF_LOCAL, SOCK_DGRAM|SOCK_CLOEXEC, 0) = 56
connect(56, {sa_family=AF_LOCAL, sun_path="/dev/log"}, 110) = -1 ENOENT (No such file or directory)
socket(PF_LOCAL, SOCK_DGRAM|SOCK_CLOEXEC, 0) = 95
connect(95, {sa_family=AF_LOCAL, sun_path="/dev/log"}, 110) = -1 ENOENT (No such file or directory)
Invoke-Command -ComputerName 192.168.60.2 -Credential System.Management.Automation.PSCredential -Authentication Basic -Command { Date }
[192.168.60.2] Connecting to remote server 192.168.60.2 failed with the following error message : MI_RESULT_ACCESS_DENIED For more information, see the about_Remote_Troubleshooting Help topic.
+ CategoryInfo          : OpenError: (192.168.60.2:String) [], PSRemotingTransportException
+ FullyQualifiedErrorId : 2,PSSessionStateBroken
+++ exited with 1 +++
```

By running tcpdump at the same time on the interface connecting the VM, I can tell that no 

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value                                                                  
----                           -----                                                                  
PSVersion                      6.0.0-rc                                                               
PSEdition                      Core                                                                   
GitCommitId                    v6.0.0-rc                                                              
OS                             Linux 4.9.0-0.bpo.4-amd64 #1 SMP Debian 4.9.51-1~bpo8+1 (2017-10-17)   
Platform                       Unix                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                
PSRemotingProtocolVersion      2.3                                                                    
SerializationVersion           1.1.0.1                                                                
WSManStackVersion              3.0
```

Please note that this works fine with at least `6.0.0-beta.9` and `6.0.0-beta.8-1`.

If there is any additional steps I can do to help you find the problem, please let me know and i'll try to do them.

**Comment by trgrassijr55** [comment]
I have the same problem.
Using powershell 6.0.0.-rc 

I have it working from my Cent OS to Windows 2012 R2 but only with OpenSSH and PowerShell 6.0.0.rc on my Windows 2012 R2 server.

Invoke-command -Computername does not work on powershell 6.0.0-rc
Same as Enter-PSSession -Computername

Only way I could get it to work is with 

invoke-command -hostname
enter-PSSEssion -hostname
but those methods have limited paramaters.   no -Credential no -Configurationname  etc

When can we have WINRM working?
