### ISSUE TITLE
Update release build to produce additional binary archive packages

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#5571]
The additional binary archive packages are `tar.gz` package for `linux-arm` build, `zip` packages for `win-arm` and `win-arm64` builds.

/cc @PowerShell/powershell-maintainers

**Comment by daxian-dbw** [comment]
@SteveL-MSFT, are we supposed to create MSI package for `win-arm` and `win-arm64`?
@TravisEz13, about the signing, if we are going to release packages for `win-arm` and `win-arm64`, we need to sign the individual DLL/script files too, right?

**Comment by TravisEz13** [comment]
We should sign those as well.

**Comment by SteveL-MSFT** [comment]
@daxian-dbw I think zip is sufficient for `win-arm` and `win-arm64` for now.

**Comment by daxian-dbw** [comment]
Close via #5664 and #5652
