### ISSUE TITLE
Should we replace our EmptyArray[T] with standard Array.Empty[T]?

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#5575]
We have our implementation of [EmptyArray[T]](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/Utils.cs#L1317) but .Net Core 2.0 now has standard implementation Array.Empty[T] - should we cleanup our code and use .Net Core 2.0 standard implementation?

**Comment by lzybkr** [comment]
`Array.Empty<T>` is slightly slower than `EmptyArray<T>` despite having the exact same implementation. I think I profiled it and there was some extra check happening when the generic method is in a different assembly.

Considering this and the fact that the it's a trivial piece of code, it's probably not worth it.

**Comment by iSazonov** [comment]
@lzybkr Thanks for great comment!
