### ISSUE TITLE
Is there a way to robustly detect that an input object was output by an object's enumerator?

### ISSUE THREAD

**Issue by alx9r** [PowerShell/PowerShell#5578]
Consider the following code:

```PowerShell
function AssertSomething {
    param (
        [parameter(ValueFromPipeline)]
        $InputObject
    )
    process
    {
        # Is there a robust way to distinguish between these
        # two cases:
        #  1.  $InputObject is the only element emitted by
        #      the enumerator of the object piped to the function
        #      at the call site.
        #      
        #  2.  $InputObject is the object piped to the function
        #      at the call site.
    }
}

# For example, 
@(1) | AssertSomething # I would like this call to throw
1 | AssertSomething # and this call to succeed.
```

Is there a way to robustly distinguish between the two call sites on the basis of whether the object piped to `AssertSomething` was enumerated?

### Background

I've been experimenting with improved assertion commands for use with Pester to validate return values.  Wherever a return value encounters `|` on its way to the command there is a potential for PowerShell to enumerate and pass the object contents rather than pass the object itself.  Here is an example:

```PowerShell
function AssertProperty {
    param (
        [Parameter(Position = 1)] $PropertyName,
        [Parameter(Position = 2)] $eq,
        [Parameter(ValueFromPipeline)] $InputObject
    )
    process
    {
        if ( $InputObject.$PropertyName -eq $eq ) 
        {
            return
        }
        throw "Property $PropertyName was $($InputObject.$PropertyName)."
    }
}

function SomeUserFunction {
    ,@([pscustomobject]@{Count=2})
}

Describe SomeUserFunction {
    It 'returns an object whose Count property is 2' {
        $r = SomeUserFunction
        $r | AssertProperty Count 2
    }
}
```

This test passes even though `$r.Count` is 1.  The cause of the false negative is obvious in this contrived example.  In real tests, however, I've found this situation to be much less obvious and much more pernicious.

I've experimented with a few different promising strategies for compensating for this situation, but so far all of them involve somewhat unnatural PowerShell. ( eg. `AssertProperty $r Count 2` or `subject $r | AssertProperty Count 2`).  The ability to detect when the object piped to `AssertProperty` was enumerated would open up some other strategies.

**Comment by mklement0** [comment]
I don't think you can do it _implicitly_ via the pipeline, but here are 2 options:

* Use the `-InputObject` parameter directly, in which case no enumeration happens:

```powershell
AssertProperty -InputObject $r Count 2
```

* Use `Write-Output -NoEnumerate` to prevent enumeration:

```powershell
Write-Output -NoEnumerate $r | AssertProperty Count 2
```

**Comment by alx9r** [comment]
I see.  Those two options _avert_ enumeration.  I was really hoping to _detect_ enumeration.

**Comment by mklement0** [comment]
Understood; I personally don't know how to do that, but perhaps someone else does.

**Comment by lzybkr** [comment]
Without private reflection, I'm not sure it's possible.

I think [this](https://github.com/PowerShell/PowerShell/blob/4bc52d2358222084738157a08907fac32d13bd3a/src/System.Management.Automation/engine/pipeline.cs#L1140) is the decision point, so maybe with some private reflection on `firstcommandProcessor.CommandRuntime.InputPipe`, you can do something.

**Comment by alx9r** [comment]
Thanks @lzybkr.  That seems promising enough for to prove the concept, but I'm not sure I'd be able to get comfortable relying on private reflection for production.

I think the enumeration could also be inferred if I had a reference to the object that may or may not have been enumerated.  Is there a public way to get a reference to the `input` `object` that appears [here](https://github.com/PowerShell/PowerShell/blob/4bc52d2358222084738157a08907fac32d13bd3a/src/System.Management.Automation/engine/pipeline.cs#L1125)?

**Comment by lzybkr** [comment]
I don't think there is even a non-public way, it's a parameter (so it's on the stack) and I'm not aware of a reason for it to be stored elsewhere.

**Comment by alx9r** [comment]
Ok.  Thanks for your help.  I think I'll try first for a solution that doesn't rely on detecting enumeration.
