### ISSUE TITLE
Get-EnvironmentInformation does not properly check for CoreCLR

### ISSUE THREAD

**Issue by markekraus** [PowerShell/PowerShell#5581]
The following code incorrectly reports that I am using CoreCLR on Windows PowerShell 5.1

https://github.com/PowerShell/PowerShell/blob/7dce4116c7182c99db33c5ad202743abe7cc2d88/build.psm1#L100-L117

Steps to reproduce
------------------

```powershell
Import-Module .\build.psm1
Get-EnvironmentInformation
```

Expected behavior
-----------------

```none
IsAdmin           : False
IsLinux           : False
IsCoreCLR         : False
IsWindows         : True
IsMacOS           : False
nugetPackagesRoot : C:\Users\MarkLocal\.nuget\packages
```

Actual behavior
---------------

```none
IsAdmin           : False
IsLinux           : False
IsCoreCLR         : True
IsWindows         : True
IsMacOS           : False
nugetPackagesRoot : C:\Users\MarkLocal\.nuget\packages
```

Environment data
----------------

```none
Name                           Value
----                           -----
PSVersion                      5.1.15063.726
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.726
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by markekraus** [comment]
@iSazonov This is unrelated to `$IsCoreCLR`. 

`Get-EnvironmentInformation` is used inside the `build.psm1` and `packaging.psm1` only. The `IsCoreClr` key of the returned hashtable is used here

https://github.com/PowerShell/PowerShell/blob/7dce4116c7182c99db33c5ad202743abe7cc2d88/build.psm1#L1342

and here

https://github.com/PowerShell/PowerShell/blob/7dce4116c7182c99db33c5ad202743abe7cc2d88/build.psm1#L1660

**Comment by iSazonov** [comment]
Ah, sorry - today is a busy day.

I can not repo on my computer - both [System.Runtime.InteropServices.RuntimeInformation]  and [System.Runtime.InteropServices.OSPlatform] throw. I think you load some assemblies in Windows PowerShell.

**Comment by markekraus** [comment]
@iSazonov what .NET version are you on? 4.7.1 has Both of those as available:

https://docs.microsoft.com/en-us/dotnet/api/?view=netframework-4.7.1&term=System.Runtime.InteropServices.RuntimeInformation

https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.osplatform?view=netframework-4.7.1

Point is, those are not valid checks for CoreCLR anymore.

**Comment by iSazonov** [comment]
I am on 4.6.1

**Comment by SteveL-MSFT** [comment]
I can repro this after installing .Net 4.7.1.  I think it would be fine to change the logic to assume Windows PowerShell 5.1 so we can use $PSVersionTable.PSEdition to determine if running on CoreCLR.
