### ISSUE TITLE
Improve pipeline for native commands

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#559]
Consider

```
ping -c 4 ya.ru | grep 64
```

Run it in PS and in bash. Compare UX.
In PS output of ping is collected,  then it's passed down the pipe all together.
In bash you see output of grep instantly after ping send one line to the pipe.

As @BrucePay pointed out it never appeared to be a problem on windows due to the lack of pipeable native command-line tools.

As a minimum, we should sort out this buffering flow.
Desirable: improve pipe speed for certain cases (i.e. native command to native command).

Open question: can we use a native pipe to provide a compatible speed, when pipeline doesn't involve PS commands?

**Comment by be5invis** [comment]
Related: #1908
Piping through EXEs or EXE to file (or vice versa) currently should not parse the piped content as string, instead of redirecting it directly as bytes.

**Comment by vors** [comment]
@be5invis absolutely!

Current plan is to address it by two separate changes:

1. Move start of native executable from pipeline `Complete()` method (executes at the time of `end` block) to `Prepare()` method (executes at the time of `begin` block). This is prototyped in https://github.com/vors/PowerShell/tree/native-pipe
2. Combine sequential native pipline elements and treat them as one pipeline element. Link them with IO redirection directly instead of powershell pipeline.

Together these two changes will cover simple scenarios:

* `native | native`
* `ps | native`

Unfortunately `native | ps` and more complicated scenarios, like `ps | native | ps`, will still be sub-optimal. I'm looking forward for propositions to address them.

**Comment by be5invis** [comment]
@vors I suggest adding a “as-bytes” operator that accepts raw (bytes) input and redirecting from Native to PS can use this scanerio:

``` powershell
native | as-bytes | your-parser | ps
```

**Comment by Jaykul** [comment]
Currently this behaves as expected, so is it only native-to-native that is affected?
```posh
ping -c 4 ya.ru | sls 64
```

I mean, that might behave weirdly if it was a binary stream, but I imagine that handling byte-by-byte streams in a PowerShell process block would be ... really sub-optimal.

Are you fixing redirect to file as well?

**Comment by vors** [comment]
I'm going to narrow scope if this issue just to the first part:

> Move start of native executable from pipeline Complete() method

For the `native | native` part, we will use #1908

**Comment by vors** [comment]
Doing this work, I'm constantly having problems because of #1486
Since this change will affect a lot of code paths, I'd like to extensively run "Feature" tests locally in different systems and make sure that I don't introduce regressions. I'm considering this work blocked on #1486 and moving it to the next milestone to fix our test harness first.

**Comment by joaoe** [comment]
Did the fix work for the use case with fd redirection 
```
command 2>&1 | other
```
PowerShell also mangles output when redirecting file descriptors.
