### ISSUE TITLE
Docker PowerShell Commands not found

### ISSUE THREAD

**Issue by Laul0** [PowerShell/PowerShell#5600]
I tried PowerShell Docker Container the last month, and I occurred some errors because some features was not available for the previous version. Since I'd Pull the latest version, no PowerShell command work.

The main goal is to use a Docker Container for CI.

Steps to reproduce
------------------
From the CI file, specify microsoft/powershell:latest and execute the following PowerShell command
```powershell
Write-Host "Hello Wolrd !"
```
> /bin/bash: line 50: Write-Host: command not found

```powershell
PowerShell -ExecutionPolicy Bypass -File "PowerShell/HelloWorld.ps1" -user "Toto" -env "GitLab"
```

> /bin/bash: line 50: PowerShell: command not found

(The script works well on Windows environment)

Expected behavior
-----------------
Like the previous version that the script or PowerShell command will be executed.

Actual behavior
---------------
No PowerShell command found

Environment data
----------------
n/a (cannot execute command)

I missed something ? Thx you for your help.

**Comment by markekraus** [comment]
The PowerShell Core binary was renamed `pwsh`. Can you retry with this:

```bash
docker run -it microsoft/powershell pwsh -c '$psversiontable'
```
