### ISSUE TITLE
Need doc for PowerShell logging on Windows/Linux/Mac

### ISSUE THREAD

**Issue by dantraMSFT** [PowerShell/PowerShell#5602]
The doc should provide an overview for viewing and/or collecting PowerShell instrumentation on the three platforms.

For Windows, cover the change in the provider GUID from Windows PowerShell and the location in the event viewer. Note that Get-EventLog is not available.

For Linux, indicate that logging is directed to syslog (or messages) and an overview of filtering using rsyslog  configuration.

On MacOS, provide an overview of using Console to view and filter powershell events (i.e., Process -eq pwsh)

**Comment by tandasat** [comment]
Hi, I am having difficult time to find where PowerShell core puts event logs, and seeing assistance for it.

On v6.0.0-rc on Windows 10, I executed command that should generate EID 4104 (eg `[type]$null`) but could not find out where it was stored on Event Viewer (Windows PowerShell's logs are under `Applications and Services Logs\Microsoft\Windows\PowerShell`).

Please let me know a right place to ask this question (or any general ones), as I do not think this thread is the right place for such questions. 

Thanks!

**Comment by dantraMSFT** [comment]
Hi @tandasat 

You will need to register the ETW manifest before events will appear in the event log.
In the install directory, look for RegisterManifest.ps1.  
From an elevated powershell prompt run the RegisterManifest.ps1 script.  

Events will be located in the event log under  Applications and Services Logs\PowerShellCore.

**Comment by tandasat** [comment]
I had to add double quotes for places taking a full paths of files because of spaces in the path (eg, changed to `'wevtutil.exe im "{0}" /rf:"{1}" /mf:"{1}"'` )

After that, it worked as you described. Thank you @dantraMSFT for help!

**Comment by dantraMSFT** [comment]
See https://github.com/PowerShell/PowerShell-Docs/pull/1922
