### ISSUE TITLE
Merge, Move and Clean Web Cmdlets

### ISSUE THREAD

**Issue by markekraus** [PowerShell/PowerShell#5610]
This issue is to track work on merging, moving , and cleaning the Web Cmdlets code

* [x] Merge partial classes into single class files
* [ ] Clean up and organize the cmdlets code
  * [ ] Remove `partial`'s
  * [ ] Sort `usings`'s, Properties, Methods, etc
  * [ ] Fix comments
  * [ ] Fix Formatting
  * [ ] Convert to automatic properties where possible
  * [ ] Remove `using Microsoft.Win32;`
* [ ] Move all web cmdlet code from sub folders to `src\Microsoft.PowerShell.Commands.Utility\commands\utility\WebCmdlet\`  top level folder
* [ ] Move independent enums and classes out of WebRequestPSCmdlet.cs to separate files

**Comment by markekraus** [comment]
@SteveL-MSFT @TravisEz13  The next phase of this cleanup is to sort and order the web cmdlet code. I looked at the [coding guidlines](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/coding-guidelines.md), but I don't see any guidance for the order of fields, properties, constructors, methods, etc other than "fields at the top unless they are backing properties". The web cmdlets are a mess with code of varying types and access all over the place.

I was looking at this http://stylecop.soyuz5.com/Ordering%20Rules.html and wondering if that would be a good reference or if this project had its own guidance that hasn't been published yet.

**Comment by SteveL-MSFT** [comment]
@markekraus I would be fine starting with stylecop.  Since the codebase is a decade old and produced by various engineers over time, it's inherently inconsistent and something that we should only address over time.

**Comment by iSazonov** [comment]
See [comment](https://github.com/PowerShell/PowerShell/pull/5972#discussion_r162855127) 
(null should be on first place).
