### ISSUE TITLE
Mac version doesn't work at all

### ISSUE THREAD

**Issue by AndrewBragdon** [PowerShell/PowerShell#5613]
This is really broken:

1.  Install Powershell from brew cask install powershell (or manually using the pkg)

Expected: you can run the powershell command to start a powershell session

Observed: command not found

Awesome!!!

Steps to reproduce
------------------

```powershell

```

Expected behavior
-----------------

```none

```

Actual behavior
---------------

```none

```

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by AndrewBragdon** [comment]
This is using the latest version of Mac OS X High Sierra

**Comment by javaptgl** [comment]
The powershell binary is renamed from "powershell" to "pwsh".

**Comment by AndrewBragdon** [comment]
Why would you create an undocumented breaking change like that?

-----------------------------

**Comment by kvprasoon** [comment]
Its documented

[https://github.com/PowerShell/PowerShell/releases/tag/v6.0.0-beta.9](url)

[https://github.com/PowerShell/PowerShell/issues/4214](url)

**Comment by kai-h** [comment]
It is important to point out too that if you have an old version of PowerShell that is launched with **powershell** and you install the new version, as pwsh, the old version is not removed so if you type powershell then you're not getting the latest installed version.

**Comment by AndrewBragdon** [comment]
Bug trackers and release pages don't count as documentation.  The main docs don't make this clear.

There are a lot of web pages that say type "powershell".

**Comment by markekraus** [comment]
@AndrewBragdon Right now, PowerShell Core is only in RC, it's not even in GA. The only way to reliably follow changes in pre-release software is the change log and release notes, where this change is documented in both. If you look at the PowerShell-Docs repo, you can see this change has been documented in the "official documentation" but hasn't been published.  Also, I it is extremely likely that when PowerShell Core 6.0.0 is released, this change will be prominently documented and communicated.
