### ISSUE TITLE
Changelog generation automation

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#5614]
The tracking Issue.
We should consider that we could automatically generate change log from your tags, issues, labels and pull requests on GitHub.
Samples:
https://pypi.python.org/pypi/gitchangelog#changelog
https://www.npmjs.com/package/auto-changelog
https://github.com/skywinder/github-changelog-generator

Also I found [this project](https://github.com/semantic-release/semantic-release#generatenotes) very interesting (and links there too) for releasing process.

**Comment by iSazonov** [comment]
From @TravisEz13 
>I think this one is the most interesting:  https://github.com/skywinder/github-changelog-generator    But, it needs a LOT of work to be usable.  This issue needs to be fixed, and we would like to be able to group by tags.

>This issue needs to be fixed:
https://github.com/skywinder/github-changelog-generator/issues/493

**Comment by iSazonov** [comment]
From @SteveL-MSFT 
>Everyone should understand that we are always open to feedback and nothing is set in stone. Based on a team discussion, one of the biggest costs for a release is creating the ChangeLog hence updating this document to push it to the contributor most aware of why the changes are being made and ideally how it's useful to end users.

**Comment by TravisEz13** [comment]
https://github.com/PowerShell/PowerShell/pull/5712
