### ISSUE TITLE
building appimage should produce a log file

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#5621]
building appimage should produce a log file which we can output only when there is an error.

/cc: @probonopd

**Comment by probonopd** [comment]
Not familiar with PowerShell, but it seems you are invoking [`appimage.sh`](https://github.com/PowerShell/PowerShell/blob/e4d88aaa9d057ee9ee432a6c0c82bd54074a7ce9/tools/appimage.sh).

Possibly you could do the equivalent of `bash -ex appimage.sh 2>&1 | tee output.log` ; check for the exit status of the `bash -ex appimage.sh` command, and use the log accordingly?

**Comment by probonopd** [comment]
On a related note, if may be easier to not use debian packages but generate the AppImage directly from the compiled sources using a tool like `linuxdeployqt`; see the examples at https://github.com/probonopd/linuxdeployqt#using-linuxdeployqt-with-travis-ci (despite the name, this tool is not limited to Qt applications).
