### ISSUE TITLE
macOS Required libcurl+openssl+gssapi for stable Web Cmdlet advanced features

### ISSUE THREAD

**Issue by markekraus** [PowerShell/PowerShell#5638]
CoreFX has moved away from the dependency on OpenSSL, however, the only way to achieve stable feature support on the web cmdlets across macOS versions is to us `brew install curl --with-openssl --with-gssapi`. the web cmdlets will work with out this, however, attempts to use `-SslProtocol` will result in different behavior depending on the version of macOS installed.

We should either create our own stable solution that does not rely on 3rd party packages, seek resolution from CoreFX, or block these features on macOS.

**Comment by kai-h** [comment]
Rather than blocking these features, having something informative presented to the user when they try to use them may be worthwhile.
Also, if it's possible to look for the Homebrew installed OpenSSL libraries or the MacPorts installed versions, that would make it a lot easier for people to install using the package manager of their preference.

**Comment by markekraus** [comment]
@kai-h it is possible for the user to chose the libcurl and openssl package using the `DYLD_LIBRARY_PATH` variable. the problem is that it is not sufficiently easy to get at what libcul the user is using in powershell and make run time decisions based on that information to toggle features or present meaningful errors. instead, the suer just gets things randomly not working or partially supported. 

Frankly, this is a CoreFX stability problem that bubbles up to the web cmdlets. If we have to go look at the lowlevel ourselves to correct around CoreFX's stability problems, that leaves us with either rolling our own solution (which is a huge mess), providing an inconsistent user experience (bad UX) or removing the features on macOS until there is some kind of stability in CoreFX.

**Comment by SteveL-MSFT** [comment]
For the 6.0.0 release, I think we just need to add documentation to the macOS install mentioning these libs as pre-requisites to get full functionality

**Comment by iSazonov** [comment]
Perhaps we should recreate the Issue to remove `curl` mention.

**Comment by markekraus** [comment]
@iSazonov this issue is no longer relevant with .NET Core 2.1 and the removal of the libcurl dependency. The `openssl+gssapi` were only relevant to libcurl.
