### ISSUE TITLE
Need to support running in root privilege on Linux Travis CI similar as in AppVeyor

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#5645]
We need to support running tests in root privilege on Linux Travis CI in a similar way as our windows tests running in AppVeyor. For windows tests, we have a tag `RequireAdminOnWindows` to indicate the tests that need admin privilege. We run those tests in an admin `pwsh` session, and then we use `runas` to remove admin privilege and run the rest tests.

With `sudo: required` in `.travis.yml`, Travis CI Linux builds run in regular user privilege by default, but you can get the root privilege using `sudo` with no need to provide a password (see the [documentation](https://docs.travis-ci.com/user/installing-dependencies/#Installing-Snap-Packages)). So we should be able to support a similar tag like `RequireAdminOnWindows` on Linux.

**Comment by TravisEz13** [comment]
This change needs to use this feature to actually run these tests on linux:  https://github.com/PowerShell/PowerShell/pull/6034/files/df3371990529ae64f481760f1edb7ccdbb89d9d7..ff9a0dde9d655efbe1460e0fab8e3f5dcf7ddee2

**Comment by iSazonov** [comment]
I found some tests that use `Test-Elevated` - I believe we should fix them too.

**Comment by anmenaga** [comment]
Can somebody please confirm/deny if the fix for this won't be limited to "Travis CI" system?
I'm talking about a scenario where I run PS tests on a private Linux VM.
Assuming tests are marked properly, will they run with admin privilege in this case?

**Comment by TravisEz13** [comment]
you could use the same commands to run locally.  The same situation as with windows today.

**Comment by kalgiz** [comment]
Resolved in #6145 PR.
