### ISSUE TITLE
Create new accelerators for easy file and directory operations

### ISSUE THREAD

**Issue by markekraus** [PowerShell/PowerShell#5647]
Moving the discussion from  #2112

We should add simple accelerators for Files and Directories to ease their use within PowerShell. These accelerators should throw if the provided file or directory do not exist. It should be considered whether or not these should support be PSProvider aware.

One concern is that using `[file]` would be ambiguous with `using namespace System.IO`. For that purpose, my examples will tentatively use the `[PSFile]` accelerator. The accelerator names should be discussed here as well

The usage would work something like this:

```powershell
function Get-Widget {
    param([PSFile]$File)
    # Do something with $File
}
Get-Widget -File 'x:\no\lo\existo.nope'
# parameter binding error for non existent file
Get-Widget -File 'c:\some\real\file.txt'
# works with existing file

$file = [PSFile]'x:\no\lo\existo.nope'
# type conversion error on non existing file

$file = [PSFile]'c:\some\real\'
# type conversion error on container

$file = [PSFile]'c:\some\real\file.txt'
# no error

$File = [PSFile](Get-Item 'c:\some\real\file.txt')
# no error

$File = [PSFile][System.IO.FileInfo]'c:\some\real\file.txt'
# no error

$file = [PSFile][System.IO.FileInfo]'x:\no\lo\existo.nope'
# type conversion error on non existing file
```

Something similar would work for `[PSDirectory]`

```powershell
$Directory = [PSDirectory]'c:\some\real\file.txt'
# type conversion error on non-container

$Directory = [PSDirectory]'x:\no\lo\'
# type conversion error on non existing folder

$Directory = [PSDirectory]'c:\some\real\'
# no error
```

If this supported providers, the API for `PSFile` would need to look something like

```csharp
public object BaseObject { get; }
public string Name { get; }
public string FullName { get; }
public PSDirectory Directory { get; }
public string DirectoryName { get; }
```

`BaseObject` would store the System.IO.FileInfo` or whatever item type a PS Provider returns from `get-item`.

**Comment by rkeithhill** [comment]
It's a little more to type but why not just use `[fileinfo]` and `[directoryinfo]`?  

These would be like the `[pscredential]` accelerator in the S.M.A namespace (or [string]/[datetime]) where you don't have to specify the full namespace.

**Comment by markekraus** [comment]
@rkeithhill Because these need to throw on missing or nonexistent files and also they need to support files in PS Providers too, IMO. `System.IO.FileInfo` does not provide either functionality.

**Comment by lzybkr** [comment]
Throw? Or is returning `$null` reasonable?

Does this need to be a type? If it was roughly a shortcut to `Get-Item`, maybe an operator is the right approach, allowing something like:

```
if (-file '\file\doesnt\exist') { ... }
```

The operator could return items, e.g.

```
(-file "$pshome\powershell.exe").VersionInfo
```

**Comment by markekraus** [comment]
@lzybkr Ideally it would throw so it can be used as a parameter type and fail to bind when the file doesn't exist. It is to eliminate this logic which is everywhere:

```powershell
    param (
        [ValidateNotNullOrEmpty()]
        [ValidateScript({
            if(-not (Test-Path $_)){
                throw
            }
        })]
        [string]
        $File
    )
```

With this:

```powershell
param(
    [PSFile]$File
)
```

I believe a type is probably the best implementation. I don't think an operator would work for parameters? I do like the idea of an operator though for use in `if()`... even if yeat-another-unary-operator would rustle some jimmies.

**Comment by lzybkr** [comment]
A new type could get messy with different conversions to worry about. Why not just introduce a validation attribute with the logic you need?

**Comment by markekraus** [comment]
The idea is that this solution is the de facto file identifier.  It's not *just* to use as parameter. The idea is to make a string path to meaningful file object in all circumstances. Assignments, parameters, etc. Validation attributes don't transform objects. Accepting/transforming other Objects such as FileInfo isn't completely necessary, but would make sense.

```powershell
function Write-Log {
    param([PSFile]$Path, [string]$Message)
    $message | Add-Content $Path.FullName
}
$LogFile = Get-Item $PSScriptRoot\log.txt
Write-Log -Path $LogFile -Message 'one'
Write-Log -Path 'c:\out.txt' -Message 'two'

$Form = @{
    UserPicture = [PSFile]'c:\imgag.png'
}
Invoke-RestMethod -Auth OAuth -Token $Token -Form $Form -Method POST -Uri $Uri
```

**Comment by lzybkr** [comment]
I'm skeptical - I think `string` is the de facto file identifier. Today we use a `string` to refer to file that:

* exist
* might exist
* might not exist
* will be created if they don't exist
* etc.

Also worth noting - your proposed type has a false promise - even if the file exists when the instance is constructed, it might not when accessing the file (it shouldn't prevent the file from being deleted.)  In other words, good error reporting is not solved by use of this type.

I am curious if you can point to an example of your proposed type in another environment - it feels like it's not a real (easily solvable) problem, because if it was, I'd expect .Net to already have such a type. For example, `System.IO.Path` feels like the right name for the type you want, but that's a static utility class.

**Comment by markekraus** [comment]
> Also worth noting - your proposed type has a false promise

That's a good point. 

I just hate that anytime something has to deal with files it has to also include redundant logic to check its existence.  But if there is no escaping than, then there wouldn't be any benefit.

To be clear, I'm just trying to flesh out something that was kind of an one-off comment brought up in #2112. Making `[System.IO.FileInfo]` accessible as `[FileInfo]` is still an improvement, but it just leaves so much off the table like files on a ps providers.

> I  am curious if you can point to an example of your proposed type in another environment 

I don't have one. I thought I did, but I must have imagined this existing in other languages.
