### ISSUE TITLE
Getting error "Unable to find type" when using IValidateSetValuesGenerator in a PowerShell module

### ISSUE THREAD

**Issue by LethiferousMoose** [PowerShell/PowerShell#5661]
Steps to reproduce
------------------
1) Create a module file (*.psm1) and add the following code block.
2) Attempt to call Test-ValidateSet -Item 'Hello' from PowerShell

```powershell
class ValidateSetTest : System.Management.Automation.IValidateSetValuesGenerator
{
    [string[]] GetValidValues()
    {
        return 'Hello', 'World'
    }
}

function Test-ValidateSet
{
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [ValidateSet([ValidateSetTest])]
        [string[]]
        $Item
    )
    $Item
}
```
Expected behavior
-----------------

```none
Hello
```

Actual behavior
---------------

```none
Unable to find type [ValidateSetTest].
At C:\PSTest\PSTest.psm1:1364 char:9
+         [ValidateSet([ValidateSetTest])]
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: ([ValidateSet([ValidateSetTest])]:AttributeAst) [], RuntimeException
+ FullyQualifiedErrorId : TypeNotFound
```

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.0.0-rc
PSEdition                      Core
GitCommitId                    v6.0.0-rc
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

This happens because the defined class is only known to the module. In order for this feature to work currently "Using Module \<ModuleName>" must be called from PowerShell to load the class definitions or a second option is to define a *.ps1 file that contains your class definitions, then in the *.psd1 file, add that script path to the ScriptsToProcess attribute list.

The advantages of modifying the manifest file is that it does not require anything from the end user to get the module to work, however since the class definition lives in an external file, that also means it cannot reference of the internal workings of the module. On the flip side, "using module" allows for the class to remain within the module, but also mean a script must be written or end user action must be taken to bring the class definition into the current session. Additionally this will load any internal class definitions inside the module into their session as well.

Without doing something around these lines, this new feature #3744 cannot be used in modules and only works if you dot-source a script file. As this feature was added to get around having to create dynamic parameters to simply add dynamic ValidateSet values, I feel like modules were the intended use case for this feature as they typically are responsible for exposing multiple functions to the end user whereas scripts as generally just called as a script.

Also note that when using the workaround solutions mentioned above, it also exposes those class definitions to the end users session, something that they really should not care about.

**Comment by LethiferousMoose** [comment]
This appears to only be an issue with psm1 files, this works fine in unit tests and regular ps1 scripts. I know scripts are processed top down, so perhaps it has to do with how PowerShell modules are loaded.

**Comment by LethiferousMoose** [comment]
@SteveL-MSFT Do you think this issue needs to be looked at prior to GA?

**Comment by SteveL-MSFT** [comment]
@LethiferousMoose I don't think this blocks 6.0.0 release as it won't impact most users

**Comment by LethiferousMoose** [comment]
Just some additional information based on some testing I did. You can get around this issue if, from PowerShell, you first call "Using Module <ModuleName>" from the command line before you call the function inside the same module. Then it loads the classes into your session and fixes the type errors. I'm guessing this is because the module knows about the class, but the PowerShell command line does not, therefore you get the type not found errors.

**Comment by lzybkr** [comment]
You should update the repro with specific details so nobody has to guess at what you are trying.

It's possible this is by design and there is a straightforward way to get it working.

**Comment by markekraus** [comment]
I can repro this with the provided code. https://github.com/markekraus/PowerShellPowerShellRepro5661/tree/6292b92926128f2c6854e4dc4df04c0c870a7f00

**Comment by LethiferousMoose** [comment]
@lzybkr Updated description and referenced the original issue you created the lead the eventual creation of supporting dynamically created values in the ValidateSetAttribute.

**Comment by lzybkr** [comment]
Yeah, that's a bug and I found the problem, PR submitted (but I'll ask someone else to add tests.)

**Comment by LethiferousMoose** [comment]
@lzybkr I was reading over the PR comments on #3784, do you know if anything more came out of the discussions around accessing the context?

**Comment by iSazonov** [comment]
@LethiferousMoose Thanks for your report! We started with the implementation for C# and later added for scripts. As far as the modules and _contexts_ are concerned, we have not considered this until we receive feedbacks like your one, especially since we have a number of problems with the classes and modules that we plan to address in 6.1.0 phase as I understand.
