### ISSUE TITLE
Invoke-RestMethod should support throttling for following rellinks

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#5679]
Invoke-RestMethod has a `-FollowRelLink` switch to automatically follow relation links to get the net page of results.  If the target web service (like GitHub) has throttling, it can hit this after a few pages and fail.  Haven't thought this through if it should be tied to `-Retry` (https://github.com/PowerShell/PowerShell/issues/5582) or separate.

Perhaps just a `-EnableThrottling` used with `-Retry` that uses some logarithmic backoff timeout if specific error codes are received from the server.

**Comment by markekraus** [comment]
hmm I wonder if snooping `x-rate*` headers would be helpful. i don't know how many API's use that to justify it.

**Comment by SteveL-MSFT** [comment]
@markekraus that would be an interesting way to tackle this

**Comment by markekraus** [comment]
At a quick glance, `x-rate*` seems to not be consistently implemented enough to be useful. using what you propose appears to be more universal.
