### ISSUE TITLE
Have both lite and rich pkgs of PSCore6.x

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#5681]
For deployments of PSCore6.x it would make sense to have a very lightweight pkg that is essentially: Engine, PkgMgmt, PSGet, and basic cmdlets (like Get-Command, Import-Module, Archive module).  This pkg would be mostly used on servers being managed and would `install-module` what they need.

Another pkg would be for the developer/it-pro which is very rich including everything in `lite`, but also modules useful for authoring and debugging scripts/modules: JSON, WebCmdlets, YAML module, Management module, HelpSystem, etc...

**Comment by markekraus** [comment]
I like this. I do have one request: the light weight download cmdlet I've been discussing... I'd like that included in the lite version if possible. The plan is that it wont have any dependency on the web cmdlet code base. But a simple way to download files in native PowerShell would be crucial, IMO, to boot strapping small environments.

**Comment by SteveL-MSFT** [comment]
@markekraus absolutely, the intent of the `lite` pkg is anything needed to bootstrap the system should be part of it, everything else should be downloaded from PSGallery

**Comment by RichardSiddaway** [comment]
Not against the idea but it will need very careful, precise and extensive explanation to the general user otherwise there'll be complaints/comments/statements that all of the functionality has been ripped out of PowerShell.  This is analogous to the way the help systems work and we're still seeing comments and complaints about PowerShell not containing any help!

**Comment by SteveL-MSFT** [comment]
@RichardSiddaway agree that it should be clear to users of the `lite` version what they are getting.  Ideally, the `rich` version is simply getting a single module from PSGallery that is a meta-module that just depends on all the other modules.  This way it also allows a `lite` user to get parity with `rich` which is then just preinstalled.

**Comment by bergmeister** [comment]
@RichardSiddaway I agree with you especially since `Update-Help` is still not working properly. I just tried on a Win10 VM in Azure with the latest updates and even running it as an admin I get:
````powershell
C:\WINDOWS\system32> Update-Help
Update-Help : Failed to update Help for the module(s) 'PrintManagement' with UI culture(s) {en-US} : Unable to connect
to Help content. The server on which Help content is stored might not be available. Verify that the server is
available, or wait until the server is back online, and then try the command again.
At line:1 char:1
+ Update-Help
+ ~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
    + FullyQualifiedErrorId : UnableToConnect,Microsoft.PowerShell.Commands.UpdateHelpCommand
````

**Comment by bergmeister** [comment]
@SteveL-MSFT : I like your idea but please don't create too many bundles with different versioning of their modules in the future because otherwise we'll endup with versioning hell similar to when .Net Core started with hundreds of NuGet packages.

**Comment by SteveL-MSFT** [comment]
@bergmeister I'm thinking of literally just the two.  In the future, we will likely have one additional package only intended for managed nodes where interactive console isn't needed at all.

**Comment by iSazonov** [comment]
Related RFC https://github.com/PowerShell/PowerShell-RFC/pull/153

**Comment by kilasuit** [comment]
simlarly the idea behind this would further tie in with #1979 and would require further planning and discussion to make a feasibility but this is something that I do think warrants further engineering time for smaller use cases where you want to start with just the base engine and bolt on features as needed 

sorta like the SKU modules in Windows work but without the licensing overheads
