### ISSUE TITLE
Remove-PSSession prevents subsequent New-PSSession calls

### ISSUE THREAD

**Issue by pvaillant** [PowerShell/PowerShell#5685]
Steps to reproduce
------------------

```powershell
$sess = New-PSSession -ConnectionUri $url -Credential $cred -Authentication Basic
$two = Invoke-Command -Session $sess -ScriptBlock {1+1}
Remove-PSSession $sess

$sess = New-PSSession -ConnectionUri $url -Credential $cred -Authentication Basic
# this hangs and never returns
```

Expected behavior
-----------------

When attempting to create a new PS Session after calling Remove-PSSession, it should work.

Actual behavior
---------------

A call to New-PSSession after Remove-PSSession never returns. NOTE: multiple New-PSSession can be created as long as Remove-PSSession is never called.

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-rc
PSEdition                      Core
GitCommitId                    v6.0.0-rc
OS                             Linux 4.4.0-103-generic #126-Ubuntu SMP Mon Dec 4 16:23:28 UTC 2017
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by y0zhk** [comment]
Works on Beta9, doesn't work on RC1 and RC2.

**Comment by y0zhk** [comment]
Doesn't work in RC1, RC2 and GA.
Works in Beta 9.

**Comment by y0zhk** [comment]
I think it is high priority issue. This bug appeared in 6.0.0-rc.1 release and is still unfixed in 6.0.0-ga.

- Subsequent "Invoke-Command" doesn't work
- Remove-PSSession prevents New-PSSession
- If no Remove-PSSession was used, but remote machine was restarted, everythings hangs too

**Comment by y0zhk** [comment]
Still unfixed in 6.0.1. Remoting from Linux to Windows is almost imposible for 3 months now.

**Comment by filiphhh** [comment]
It seems as any time the session closes powershell will hang. If you don't close the session you can create new sessions but when the script is finished it hangs (probably when it tries to close the session in it's dispose method). Even if I try to exit the session from within with something like
```
$Session = New-PSSession -ComputerName xxx -Credential $Credential -Authentication Negotiate
Invoke-Command -Session $Session -ScriptBlock {
    Write-Host 'Test'
    Exit
}
```
It immediately hangs.
I've been forced to leave my sessions open and append `kill $PID` at the last lines of my script to workaround this issue which is truly horrific.

**Comment by MaximoTrinidad** [comment]
Just to be clear! This seems not a ssh issue using New-Session.  Looks more like a WinRM issue.
This need to be clear what kind connection is been in play.

:)

**Comment by y0zhk** [comment]
Yep, its WinRM.

**Comment by PaulHigin** [comment]
@dantraMSFT   This is on Linux platform so must be using OMI.

**Comment by filiphhh** [comment]
I am using ubuntu 16.04, with the following packages from the microsoft repo:
powershell 6.0.1-1.ubuntu.16.04
omi 1.4.2.1
omi-psrp-server 1.4.1.28

I the machines I am connecting to are various Windows Servers, it does not seem to depend on which authentication type I use (I've tried basic and negotiate).

The error occurs reliably on every attempt and should be easy to reproduce.

**Comment by filiphhh** [comment]
Any updates on this? Seems like a pretty critical issue, running Remove-PSSession on a WinRM session completely destroys the PSRemoting stack causing infinite deadlocks.
