### ISSUE TITLE
Remote Powershell (Linux) to Windows

### ISSUE THREAD

**Issue by Killklli** [PowerShell/PowerShell#5686]
Not entirely sure why I'm unable to remote to Windows without installing SSH and that would only do PS6 to PS6, not allowing me to run standard powershell commands on the remote windows box. 

I tried using Connect-WSMan, however that module does not seem to compile by default and I'm not sure what directory to pull from.

Steps to reproduce
------------------

```
New-PSSession xxx.xxx.xxx.xxx -Credential test.local\admin

```

Expected behavior
-----------------

```
Access granted to Windows box's Powershell 5
```

Actual behavior
---------------

```
New-PSSession : MI_RESULT_ACCESS_DENIED
At line:1 char:1
+ New-PSSession xxx.xxx.xxx.xxx -Credential test.local\admin
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [New-PSSession], PSInvalidOperationException
+ FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.NewPSSessionCommand
```

Environment data
----------------

```Name                           Value
----                           -----
PSVersion                      6.0.0-rc
PSEdition                      Core
GitCommitId                    v6.0.0-rc
OS                             Linux 4.4.0-1041-aws #50-Ubuntu SMP Wed Nov 15 22:18:17 UTC 2017
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by SteveL-MSFT** [comment]
Is `admin` a local account?  Try with just `-Credential admin` and also add `-Authentication Negotiate`

**Comment by Killklli** [comment]
admin is a domain account. However I did try with a local account and got the same results.

I did try the authentication negotiate and in both cases, with the domain and a local account I get a new issue.
``New-PSSession : [xxxxx] Connecting to remote server xxxxx failed with the following error message : Authorization failed Unspecified GSS failure.  Minor code may provide more information SPNEGO cannot find mechanisms to negotiate For more information, see the about_Remote_Troubleshooting Help topic.
At line:1 char:1
+ New-PSSession xxxxx -Credential test.local\admin -Authentication  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotingTransportException
+ FullyQualifiedErrorId : `2,PSSessionOpenFailed`

**Comment by Killklli** [comment]
I'm able to fully get this to work over ssh from PS6 to PS6, however the connection over WinRM still does not seem to be working. Any thoughts?

**Comment by SteveL-MSFT** [comment]
@Killklli I have limited staff available due to the holiday season the US.  I'll look into it after Christmas.

**Comment by MaximoTrinidad** [comment]
@Killklli 

Curious! Did you went thru to setup instructions of WSMan in your Linux box?  Or, just use the Connect-WSMan?  There are some steps in Linux to follow to make work.

:)

**Comment by Killklli** [comment]
I was just attempting WSMan, I was never actually able to locate an install guide for WSMan, I was probably looking in the wrong spot/trying to pull the module incorrectly.

And strangely enough its both. It will be connecting to a domain box for automated related steps while the local account will be more than enough for Jenkins deployment jobs.

**Comment by MaximoTrinidad** [comment]
@Killklli,

Cool! I got the instructions set aside to setup WSMAN but I didn't have a domain setup until recently.  As I'm preparing some presentations for future events.  

So, within the coming week, and if is not thru this weekend, I'll give it a try to setup WSMAN in Linux. I just need to see if the instructions I got have change in any way.

I'll keep in touch!

:)

**Comment by Killklli** [comment]
So after doing some looking, this basically comes down to https://github.com/PowerShell/PowerShell/issues/3827

I have however been unable to get the steps that were listed there to work, is there an updated step list to make that work?
