### ISSUE TITLE
Failures in our RC.2 release test runs need to be resolved

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#5689]
Test run results
----
```
OS                           Pass Pending Skipped Fail Total
--                           ---- ------- ------- ---- -----
CentOS Linux 7 (Core)        6049     343    1226   17  7635
Debian GNU/Linux 8 (jessie)  6066     342    1226    1  7635
Debian GNU/Linux 9 (stretch) 6066     342    1226    1  7635
openSUSE Leap 42.3           6066     341    1226    2  7635
Red Hat Enterprise Linux     6048     342    1226   19  7635
Ubuntu 14.04.5 LTS           6066     342    1226    1  7635
Ubuntu 16.04.3 LTS           6066     342    1226    1  7635
Ubuntu 17.04                 6066     342    1226    1  7635
```

Test failure analysis
----
- CentOS 7 and RHEL have the trouble with SSL protocol and `Invoke-WebRequest/Invoke-RestMethod`.
- Redhat is still failing the test for powershell exiting without hanging - this should be looked at more carefully in Jan
- OpenSUSE is failing an `invoke-item` test because 2 `ping` native commands are found, and the test should be improved to handle multiple binaries being found.
- The help tests should be improved to know when a browser is possible.

**Comment by markekraus** [comment]
> CentOS 7 and RHEL have the trouble with SSL protocol and Invoke-WebRequest/Invoke-RestMethod

Every release these things come up. In the CentOS Test environment using just the base installed libcurl? Or is the libcurl+openssl+gssapi combo added before the test? I need to get a CentOS 7 vm up and look at this sometime, but we should probably have similar guidance for this OS as we do for macOS.

**Comment by daxian-dbw** [comment]
@markekraus I think we were using the base installed `libcurl` and it should be the same cause of the macOS issue. /cc @JamesWTruher

**Comment by iSazonov** [comment]
It seems [CoreFX](https://github.com/dotnet/corefx/blob/93ee4ba40c82d5aca978447cb3e14c4ef7e7fd53/src/System.Net.Http/src/System/Net/Http/Managed/README.md) want exclude `libcurlv`. 
Interesting, if they have plans to do that in 6.1.0?

**Comment by markekraus** [comment]
I finally had a chance to set up a CentOS 7  box and test this... The good news is that I can get all passing tests! The bad news is that it requires compiling curl from source with the `--with-ssl -with-gssapi` flags and then `pwsh` needs to be started like this `LD_LIBRARY_PATH=/usr/local/lib pwsh`. I'm not sure what value this has so close to GA release... but at least i can confirm that these features and tests do pass when the environment contains libcurl+openssl+gssapi

**Comment by markekraus** [comment]
@daxian-dbw I believe we can close this now? or do we still get all of these failures on releases?
