### ISSUE TITLE
Remove-Service on other computers..

### ISSUE THREAD

**Issue by DynConcepts** [PowerShell/PowerShell#5691]
I see that specifying the -ComputerName was removed....
- Remove `-ComputerName` from `Get/Set/Remove-Service`. (#5094)

I do not see what the proposed method for simply removing services (or adding them) on remote machines will be....

Please advise.

**Comment by markekraus** [comment]
for now you can do this with either implicit remoting or with `Invoke-Command`

**Comment by DynConcepts** [comment]
Thanks for the response. I have been trying for nearly 2 days, without success... If you have a specific link or sample, I am at david.corbin@dynconcepts.com    Thanks in Advance.

**Comment by markekraus** [comment]
It's nothing special. Just call `Remove-Service` on the remote system using `Invoke-Command`:

```powershell
$Cred = Get-Credential
Invoke-Command -ComputerName 'server.contoso,com' -Credential $Cred -ScriptBlock {
    Remove-Service 'MyService' 
}
```

**Comment by DynConcepts** [comment]
Mark - if we can take this off-line I can provide additional info... david.corbin@dynconcepts.com

**Comment by SteveL-MSFT** [comment]
@DynConcepts look at the samples here https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/invoke-command?view=powershell-6

This is the general way to use PowerShell remotely for any cmdlet, not just the ones that happen to expose a `-ComputerName` parameter.
