### ISSUE TITLE
Logging of script block execution cannot be enabled on Unix

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#5695]
PowerShell checks whether to log script block activities in [`ShouldLogScriptBlockActivity`](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/runtime/CompiledScriptBlock.cs#L1478), which query Registry on windows to get the configuration via [`GetGroupPolicySetting`](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/Utils.cs#L527). However, `GetGroupPolicySetting` does nothing on Unix, and thus script block activity logging cannot be enabled on Unix.

A potential fix is to make PowerShell checks against an entry in `pwsh.runtimeconfig.json`.

**Comment by dantraMSFT** [comment]
Reopened since the change causes all analytic events to be logged unconditionally on Linux.
