### ISSUE TITLE
Powershell >=beta.9 (x64) no longer works as a task runner for VS Code

### ISSUE THREAD

**Issue by zackschuster** [PowerShell/PowerShell#5701]
Steps to reproduce
------------------

- Install any 64-bit powershell post-beta.8
- Attempt to run any task using VS Code's GUI

Expected behavior
-----------------
Works fine

Actual behavior
---------------
Blows up with exit code 64, complaining about the `\d` flag not being a script.

I strongly suspect this is due to the recent `powershell` -> `pwsh` rename, but I have no proof for this (nor, for the record, any desire whatsoever to ~pointlessly bikeshed~ _debate the merits of_ the rename).

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value                                                                                                                     
----                           -----                                                                                                                     
PSVersion                      6.0.0-rc.2                                                                                                                
PSEdition                      Core                                                                                                                      
GitCommitId                    v6.0.0-rc.2                                                                                                               
OS                             Microsoft Windows 10.0.14393                                                                                              
Platform                       Win32NT                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                                       
SerializationVersion           1.1.0.1                                                                                                                   
WSManStackVersion              3.0                                                                                                                       

```

**Comment by zackschuster** [comment]
I'll also add that being able to do this is Extremely Crucial for working around situations where e.g. built-in powershell profiles get unfixably broken during IT deployments, which is depressingly prevalent in my office right now.

**Comment by rkeithhill** [comment]
Right now, on Windows you have to customize the `.vscode/tasks.json` file to make it use PowerShell Core on Windows instead of the default shell - Windows PowerShell.  Also, the error `\d` tells me you have a path in the tasks.json file where a backslash has been escaped e.g `\\d<rest of path>`.

**Comment by zackschuster** [comment]
My apologies -- the `\d` was actually `/d`. Here's the full error message:

```powershell
> Executing task in folder Server: dotnet build --no-restore <

The argument '/d' is not recognized as the name of a script file. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
The terminal process terminated with exit code: 64

Terminal will be reused by tasks, press any key to close it.
```

My `tasks.json` file is pretty simple:
```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "build",
			"group": "build",
			"type": "shell",
			"command": "dotnet build --no-restore",
			"problemMatcher": "$msCompile"
		}
	]
}
```

Would you be able to point me in the right direction for how to alter `tasks.json` to use PS Core?

Thanks for your help :)

**Comment by rkeithhill** [comment]
You could change that as a user setting I think - 
```
  "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
```
But then everyone on your team would have to make that change **unless** you put this in the workspace settings file: `.vscode\settings.json`. 

If that doesn't work, take a look at what we do for the tasks.json for the PowerShell extension for VSCode:
https://github.com/PowerShell/vscode-powershell/blob/93bc21c8167001a5701917c21aace9af6492e587/.vscode/tasks.json#L4-L11
You would change this path to the PS Core install location `C:\\Program Files\\PowerShell\\6.0.0-rc.2\\pwsh.exe`

**Comment by zackschuster** [comment]
I already had `terminal.integrated.shell.windows` set; that's how I was able to initially produce the issue.

Though, as you suggested earlier, there's a property in [the schema](https://code.visualstudio.com/docs/editor/tasks-appendix) for `tasks.json` that fixes it:

```json
"options": {
  "shell": {
	"executable": "C:/Program Files/PowerShell/pwsh.exe",
	 "args": [

	  ]
   }
}
```

Without specifying any args, the error becomes:

```powershell
> Executing task in folder Server: dotnet build --no-restore <

The argument 'dotnet' is not recognized as the name of a script file. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
The terminal process terminated with exit code: 64

Terminal will be reused by tasks, press any key to close it.
```

...which I interpret to mean the `dotnet` command is being improperly parameterized by VS Code.

(Adding "-Command" to `args` fixes it, which I'm guessing is related to [what you were saying here](https://github.com/Microsoft/vscode/issues/40228#issuecomment-351926387) about, um, improperly parameterized args).

**Comment by rkeithhill** [comment]
Yup, that's why we use:
```
"args": [ "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command" ]
```
No sense loading a profile and if someone needs to run this on a system where the execution policy hasn't been set, the above default args handle that.

BTW that `group` field looks odd.  For the extension we use:
```
            "group": {
                "kind": "build",
                "isDefault": true
            }
```
Also, are you sure about your pwsh.exe path?  When I look in my `C:\Program Files\PowerShell` folder there is no pwsh.exe file there.  The exe is under a subdir named after the version e.g. `6.0.0-rc2`.

**Comment by zackschuster** [comment]
Yes, I copy it from the install so I can a) avoid updating user settings every time I update, and b) I can freely modify files without corrupting the base install (like when I broke everything trying to fix this issue by renaming `pwsh` back to `powershell` ;) ).

I use string config instead of hash because I invoke all my tasks from `ctrl+shift+b`. Saves me a couple lines per project :)

Thank you so much for your help! Being able to use new Powershell again is so great!

**Comment by zackschuster** [comment]
(Marking as closed since this seems like an upstream issue)
