### ISSUE TITLE
System.Drawing.Bitmap is not support ?

### ISSUE THREAD

**Issue by MuraAtVwnet** [PowerShell/PowerShell#5704]
Steps to reproduce
------------------
$bmp = New-Object System.Drawing.Bitmap($JpegFileFullName)
```powershell

```

Expected behavior
-----------------
Create new object.
```none

```

Actual behavior
---------------
New-Object : Cannot find type [System.Drawing.Bitmap]: verify that the assembly containing this type is loaded.
```none

```

Environment data
----------------

Name                           Value
----                           -----
PSVersion                      6.0.0-rc.2
PSEdition                      Core
GitCommitId                    v6.0.0-rc.2
OS                             Microsoft Windows 10.0.17046
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```powershell
> $PSVersionTable

```

**Comment by markekraus** [comment]
@MuraAtVwnet Not all of `System.Drawing` has been implimented in .NET Core. You can see what is currently available in that namespace [here](https://docs.microsoft.com/en-us/dotnet/api/system.drawing?view=netcore-2.0).  `System.Drawing.Bitmap` is not currently available specifically. More may be added later.

If you want to use any of the classes that are currently available, you will need to use the [Windows Compatibility Pack](https://blogs.msdn.microsoft.com/dotnet/2017/11/16/announcing-the-windows-compatibility-pack-for-net-core/). You can easily add this with the following:

```powershell
Install-Module PSCoreWindowsCompat -Scope CurrentUser
Import-Module PSCoreWindowsCompat
```

This is currently only supported on 64-bit Windows.
