### ISSUE TITLE
Installer should start PS Core with user's home dir as the working dir

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShell#5705]
Steps to reproduce
------------------

```powershell
Install PS Core rc2 and at the select check the box to start PowerShell.
Find PowerShell Core in the task bar, right-click it and select "Pin to taskbar"
```

Expected behavior
-----------------
PowerShell Core as started by the installer, starts in my home dir.
PowerShell Core as started by the taskbar icon, starts in my home dir.

Actual behavior
---------------
PowerShell Core in both cases starts in `C:\Program Files\PowerShell\6.0.0-rc.2`.

I wind up having to edit the taskbar shortcut's properties to change the "Start in:" location to `%USERPROFILE%` - which works but I shouldn't have to do this.  I suspect other folks will use the PS Core started by the installer as the easy means to get PS Core pinned to their taskbar.

If the installer could set the working dir to the current user's home dir before launching PowerShell, that would probably fix both scenarios.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-rc.2
PSEdition                      Core
GitCommitId                    v6.0.0-rc.2
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by bergmeister** [comment]
@rkeithhill My branch [here](https://github.com/bergmeister/PowerShell/tree/LaunchPwshInHomeFolderAfterInstallation) has modified the installer to launch PowerShell when having ticked the checkbox as `pwsh.exe -NoExit -Command Set-Location $env:HOME`. However, if I then right-click on the shell and pin it to the taskbar, the `Start in` is still the installation location of pwsh.

**Comment by rkeithhill** [comment]
Try changing the `Directory="INSTALLFOLDER"` attribute.  Hopefully WiX has a predefined variable for the user's home dir.

**Comment by rkeithhill** [comment]
Looks like you can use either `[%USERPROFILE]` or `[%HOMEDRIVE][%HOMEPATH]`.

**Comment by bergmeister** [comment]
Thanks for the pointers. I am struggling to get a valid syntax that Wix accepts at the moment but will come back to it tomorrow.

**Comment by SteveL-MSFT** [comment]
The last time I looked into this, there isn't a way to do this.  The problem is that the environment variables get resolved at install time, not runtime.

**Comment by SteveL-MSFT** [comment]
Looks like this isn't actually fixed.  Working on a PR.

**Comment by rkeithhill** [comment]
Yup, just noticed that.

**Comment by bergmeister** [comment]
The new `-WorkingDirectory` parameter should make it possible to overcome WiX's syntax limitations.
