### ISSUE TITLE
Create cmdlet with referencing other Project

### ISSUE THREAD

**Issue by windischb** [PowerShell/PowerShell#5706]
Hi!

I know this Problem is not related to Powershell directly, but maybe someone can give me a hint, i can't find a solution for my Problem...

I try to create a cmdlet as described here -> https://github.com/PowerShell/PowerShell/blob/master/docs/cmdlet-example/visual-studio-simple-example.md

The cmdlet dll is referencing another netstandard2.0 library.

I have created a sample Github Project: 
https://github.com/windischb/CmdletTest
Project "Functions" -> Test Project which uses Newtonsoft.Json
Project "CmdletTest" -> cmdlet which references "Functions"

I can build and import the "Cmdlet" Library, but if i invoke the command:

```
PS C:\> ConvertTo-JsonTest (get-date)
ConvertTo-JsonTest : Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral,
PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
At line:1 char:1
+ ConvertTo-JsonTest (get-date)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertTo-JsonTest], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,CmdletTest.ConvertToJsonTest

```
There is no Newtonsoft.Json dll in the output directory...
Can anyone give me hint on how the reference to Newtonsoft.Json will work??

Many thanks!!

**Comment by iSazonov** [comment]
Tracked in #2083
