### ISSUE TITLE
Crash on establishing HTTPS connection for telemetry

### ISSUE THREAD

**Issue by ramon-garcia** [PowerShell/PowerShell#5710]
On Debian GNU/Linux 9, a few seconds after starting pwsh, it crashes with a segmentation fault.

The stack frame

```
#0  0x00007fe4b2224d6d in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#1  0x00007fe4b221fc8b in X509_verify_cert () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#2  0x00007fe4e080d496 in ?? ()
#3  0x00007fe4b20e6d00 in ?? ()
#4  0x00007fe544131f20 in ?? ()
#5  0x0000000012f39ebe in ?? ()
#6  0x00007fe554cd7488 in vtable for InlinedCallFrame () from /opt/microsoft/powershell/6.0.0-rc.2/libcoreclr.so
#7  0x00007fe4b20e7688 in ?? ()
#8  0x00007fe4e084e670 in ?? ()
#9  0x00007fe4e084e670 in ?? ()
#10 0x00007fe4b20e6d00 in ?? ()
#11 0x00007fe4e080d496 in ?? ()
#12 0x00007fe4b20e6d90 in ?? ()
#13 0x00007fe4e084e670 in ?? ()
#14 0x00007fe4b46fde48 in ?? ()
#15 0x0000000000000001 in ?? ()
#16 0x00007fe4b46f45a0 in ?? ()
#17 0x00007fe4b46fdeb8 in ?? ()
#18 0x00007fe4b46fde48 in ?? ()
#19 0x00007fe4b46fde48 in ?? ()
#20 0x00007fe5441185f0 in ?? ()
#21 0x00007fe4b20e6e00 in ?? ()
#22 0x00007fe4df4dca17 in ?? ()
#23 0x00007fe4b20e6da0 in ?? ()
#24 0x00007fe4b46fde48 in ?? ()
#25 0x00007fe4b46f45a0 in ?? ()
#26 0x0000000000000000 in ?? ()
```

shows that this happens during certificate validation (see the call to X509_verify_cert() ). As I was not doing anything remote, the logical explanation is that this happens during telemetry.

At least do not crash :)

**Comment by markekraus** [comment]
> the logical explanation is that this happens during telemetry.

That, or verifying the code signatures on the core modules.

**Comment by ramon-garcia** [comment]
> That, or verifying the code signatures on the core modules.

It does not happen on startup. It crashes after typing some commands. I assume that verification of the core modules takes place at startup. And after removing the file DELETE_ME_TO_DISABLE_CONSOLEHOST_TELEMETRY it no longer crashes :)

**Comment by markekraus** [comment]
ah.. then that *is* a good case for this being telemetry related. 🙂

**Comment by ramon-garcia** [comment]
I have just checked that the cause was somewhat specific to my system.
There were to libcrypto libraries, with versions 1.0.0 and 1.0.2 . After removing 1.0.0 (a Ruby dependency), powershell took the 1.0.2 and no longer crashes.

Perhaps the poblem is taking libcrypto 1.0.0 when both 1.0.0 and 1.0.2 are present.

I think that this problem is too specific to a configuration, so I am closing it.
