### ISSUE TITLE
Clear-History does not remove all history

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell#5711]
This was reported via LiveFyre comments for [Clear-History](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/clear-history?view=powershell-5.1#comments-container)

In PowerShell 5 on Windows 10 (at least) the 'Clear-History' cmdlet does not clear any session history, and certainly not the on-disk history. None of the options seem effective, it appears to be entirely borked and quite the security vulnerability. Googling around it appears broken for a couple years at least, with some workarounds found:

## Steps to reproduce
1) Run: Remove-Item (Get-PSReadlineOption).HistorySavePath
2) Run: [Microsoft.PowerShell.PSConsoleReadLine]::ClearHistory()
3) End the current session

See other online discussions:
- https://blogs.msdn.microsoft.com/stevelasker/2016/03/25/clear-history-powershell-doesnt-clear-the-history-3/
- https://thetechremix.com/2017/02/22/tip-clear-powershell-history-in-windows-10/
- https://stackoverflow.com/questions/13257775/powershell-clear-history-doesnt-clear-history

**After local testing:**

Clear-History does clear the History from the session. Try doing Clear-History then run Get-History. However, that does not clear the history that PSReadline is using. So up-arrow recall of commands still has history information.

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.16299.98
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.98
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by EvanCrowe** [comment]
sdwheeler,

I'm not sure this is an actual error, the PowerShell history and Command Buffer are two different things, this seems to be by design, for what appear to be historical reasons.

If you're interested in seeing who has access to this, check out https://docs.microsoft.com/en-us/windows/console/console-buffer-security-and-access-rights You can also reduce your buffer size to zero in the PowerShell properties menu .

**Comment by sdwheeler** [comment]
I understand that history and command buffer are different. However, before PSReadline. there was no difference. So the user experience has changed and the implications of this change are not well documented. At a minimum, the documentation for History and PSReadline should call this out. But it is also worth discussing whether PSReadline could/should be changed to address these concerns.

**Comment by rkeithhill** [comment]
I would not want the Clear-History command to clear my PSReadLine history.  However, I could see PSReadLine adding a command `Clear-PSReadLineHistory` (to make it more obvious) and I could see updating the Clear-History docs to point out `Clear-PSReadLineHistory` command to fully wipe out history.  That said, I'd want a confirm impact of high on that new command.  I'd be lost if my PSReadLine history were accidentally deleted.  :-)

**Comment by sdwheeler** [comment]
Yes, I think adding Clear-PSReadlineHistory and cross-documentation would be the right thing to do.

**Comment by EvanCrowe** [comment]
Not to go all too crazy, but would a flag for clear-history make more sense than a new cmdlet? We already have ways to clear the history, and ways to clear the buffer; something like clear-history -includebuffer might make more sense with less redundancy.

**Comment by rkeithhill** [comment]
The help file that needs to be updated is the one for `Clear-History`. It should mention that the command only clears the current session's history and if the user if using a module such as PSReadLine that handles the line editing experience (i.e. implements `function PSConsoleHostReadline`), that those modules often store their own history.  And they provide their own commands to clear their history.

**Comment by Jaykul** [comment]
Why would you *not* want Clear-History to clear both?

Under what circumstances are you trying to clear only your PowerShell history buffer, but *not* the ON-DISK cache created by PSReadLine. 

Given that PSReadline is *built in* and *required* for PowerShell 6, why are we still keeping the history separate? What's the point of having multiple copies of history anyway?

**Comment by rkeithhill** [comment]
A PowerShell host (like PSES) may not be using PSReadLine so having the built-in `Clear-History` assume that PSReadLine is always loaded is not a good thing.  Plus, I can always remove the PSReadLine module.  OTOH the cmdlet could check for the presence of PSReadLine.  That might be OK but such a command should have a confirm impact of high.  My PSReadLine history is treasure to me.  :-)

**Comment by SteveL-MSFT** [comment]
I think this is an interesting discussion.  For PSCore6, we deliberately went with a very simple ReadLine implementation in the ConsoleHost deferring all the previous capabilities to PSReadLine so it gets loaded automatically.  Perhaps we can add a `-Scope` type parameter to `Clear-History` that PSReadLine can plug into.  cc @lzybkr

**Comment by iSazonov** [comment]
@SteveL-MSFT @daxian-dbw Please triage the issue

**Comment by daxian-dbw** [comment]
The repro step mentioned ` [Microsoft.PowerShell.PSConsoleReadLine]::ClearHistory()`, I just want to clarify that `ClearHistory()` clears the history for the current running session only. It doesn't affect the history file.
If we want `Clear-History` to clear the PSReadLine history file as well, all it needs to do is to remove the history-save file, which can be queried by `Get-PSReadLineOptions`.

**Comment by SteveL-MSFT** [comment]
I think we should think about how to integrate the `History` cmdlets with PSReadLine to provide a cohesive experience since we've already married the two together.

**Comment by iSazonov** [comment]
Have any plans to move some code from PSRL to Engine (like coloring)? In the case we could do the same for some other  features.
