### ISSUE TITLE
Test-Path returns $true for ' ' on Windows

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#5717]
Steps to reproduce
------------------

```powershell
Test-Path ' '
```

Expected behavior
-----------------
NB: Because the .Net Core method Directory.Exists states in the docs [here](https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.exists?view=netcore-2.0#System_IO_Directory_Exists_System_String_) that trailing whitespaces are removed, the expectation of the last 2 spaces is true.
```none
False
```

Actual behavior
---------------
On Windows:
```none
True
```
On Linux (Ubuntu 17 or WSL):
```none
False
```

Environment data
----------------
Reproes on the latest daily build of `PowerShell Core` (December 19, 2017) and `Windows PowerShell 5.1`

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.519
PSEdition                      Core
GitCommitId                    v6.1.0-preview.519
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
Ubuntu 17 VM
````
Name                           Value
----                           -----
PSVersion                      6.0.0-rc.2
PSEdition                      Core
GitCommitId                    v6.0.0-rc.2
OS                             Linux 4.10.0-42-generic #46-Ubuntu SMP Mon Dec 4 14:38:01 UTC 2017
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

````
The WSL Linux system
````
Name                           Value
----                           -----
PSVersion                      6.0.0-rc.2
PSEdition                      Core
GitCommitId                    v6.0.0-rc.2
OS                             Linux 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
````

**Comment by bergmeister** [comment]
In case anyone wonders how I discovered this:
I was debugging someone else's script today whereby one parameter was expected to be an invalid file path, hence I just used a space but found that not everything was working locally as expected, which I could boil down to an if statement making the wrong decision because of this.

**Comment by markekraus** [comment]
I was able to repro.  These also return true:

```powershell
Test-Path '\ '
Test-Path '.\ '
```

**Comment by bergmeister** [comment]
Thanks, I've updated title and repro steps with those cases as well.

**Comment by nightroman** [comment]
Just in case:

```powershell
[System.IO.Directory]::Exists(' ')
[System.IO.Directory]::Exists('\ ')
[System.IO.Directory]::Exists('.\ ')
```

Output:

```
False
True
True
```

**Comment by bergmeister** [comment]
@nightroman Thanks for the hint. The source code of the Directoy.Exists .Net Core method is [here](https://github.com/dotnet/corefx/blob/0eb5e7451028e9374b8bb03972aa945c128193e1/src/System.IO.FileSystem/src/System/IO/Directory.cs#L66), but the documentation [here](https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.exists?view=netcore-2.0#System_IO_Directory_Exists_System_String_) already states that
> Trailing spaces are removed from the end of the path parameter before checking whether the directory exists.

Therefore I will change the bug title back to be only about the case whereby the `-Path` parameter is just one or multiple space characters

**Comment by bergmeister** [comment]
@markekraus I raised a separate issue for your 2 test cases on Linux in the corefx repo [here](https://github.com/dotnet/corefx/issues/26008)

**Comment by iSazonov** [comment]
You could use the notation `'[ ]'` if you want leading or trailing spaces in paths and file names.

**Comment by KevinMarquette** [comment]
This is hitting on a weird nuance of DOS Path processing. Any number and combination of trailing spaces and periods can be added to the end of a file or path name and it will be ignored.

    Test-Path '...   ...   ...   ...'
    Get-ChildItem '...   ...   ...   ...'

This is the best guide that I have seen on all the DOS Path and NT Path parsing nuances: [The Definitive Guide on Win32 to NT Path Conversion](https://googleprojectzero.blogspot.com/2016/02/the-definitive-guide-on-win32-to-nt.html)
