### ISSUE TITLE
WMI Namespace: WindowsUpdate

### ISSUE THREAD

**Issue by NonSecwitter** [PowerShell/PowerShell#5718]
On Windows 10 and Server 2016 DataCenter, there seems to be a problem with CIM class `MSFT_WUOperationsSession` in namespace `root/Microsoft/Windows/WindowsUpdate`

## Expected Behavior
It seems that the class was properly implemented in server Nano: https://blogs.technet.microsoft.com/nanoserver/2016/01/16/updating-nano-server-using-windows-update-or-windows-server-update-service/

Following the outlined instructions, I would expect to be able to search for and apply updates on any Windows 10/Server 2016 based operating system.

## Current Behavior
This command:
`$sess = New-CimInstance -Namespace root/Microsoft/Windows/WindowsUpdate -ClassName MSFT_WUOperationsSession`

Returns this error:

> New-CimInstance : Invalid class
>At line:1 char:9
> $sess = New-CimInstance -Namespace root/Microsoft/Windows/WindowsUpda ...
>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>CategoryInfo  : MetadataError: (MSFT_WUOperationsSession:CimInstance) [New-CimInstance], CimException
>FullyQualifiedErrorId : HRESULT >0x80041010,Microsoft.Management.Infrastructure.CimCmdlets.NewCimInstanceCommand

However, the class and all of its methods are listed using:
`Get-CimClass -Namespace root/Microsoft/Windows/WindowsUpdate`

and

` Get-CimClass -Namespace root/Microsoft/Windows/WindowsUpdate -ClassName MSFT_WUOperationsSession | select -ExpandProperty CimClassMethods`

## Possible Solution
Complete or update implementation of MSFT_WUOperationsSession for Windows 10 and Server 2016.

## Steps to Reproduce
1. Open Powershell on Windows 10 or Server 2016 Datacenter
2. Execute: `$sess = New-CimInstance -Namespace root/Microsoft/Windows/WindowsUpdate -ClassName MSFT_WUOperationsSession`
3. Execute: `Get-CimClass -Namespace root/Microsoft/Windows/WindowsUpdate`
4. Execute: ` Get-CimClass -Namespace root/Microsoft/Windows/WindowsUpdate -ClassName MSFT_WUOperationsSession | select -ExpandProperty CimClassMethods`

## Context (Environment)
Lack of implementation prevents programmatic control of windows updates through CIM/WMI, particularly remote control over WinRM/WSMan. 

There is a COM object for the Windows Update Agent, but it doesn't support remote execution. Implementing over WinRM/WSMan would improve control of resources from a centralized or remote location.

**Comment by RichardSiddaway** [comment]
On Windows Server 2016 I have successfully used and still use this class. The CIM classes were changed on Windows 10 FCU and Server 1709 and you have to use MSFT_WUOperations instead of MSFT_WUOperationsSession. The methods on MSFT_WUOperations  -  ScanForUpdates and InstallUpdates are static so you don't need to create and instance of the class.

Details of using the MSFT_WUOperations class are here: https://richardspowershellblog.wordpress.com/2017/11/17/windows-update-change-in-server-1709/

**Comment by NonSecwitter** [comment]
@RichardSiddaway Thanks for the information. MSFT_WUOperations does indeed work on my Windows 10 machine, locally. Maybe I was mistaken about 2016, but I could have sworn that earlier testing was not working correctly for myself and others.

In any case, do you have any insights into how this CIM Method works? I'm trying to get this to run remotely, but I get this error, whether I run it with `Invoke-Command` .... `Invoke-CimMethod` .... or in a remote PSSession.

> Invoke-CimMethod : WU Scan Failed
> At line:1 char:1
> + Invoke-CimMethod -Namespace "root/Microsoft/Windows/WindowsUpdate" -C ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : PermissionDenied: (root/Microsoft/...FT_WUOperations:String) [Invoke-CimMethod], CimException
>     + FullyQualifiedErrorId : HRESULT 0x80070005,Microsoft.Management.Infrastructure.CimCmdlets.InvokeCimMethodCommand
>     + PSComputerName        : <computername>

**Comment by RichardSiddaway** [comment]
Can you show your whole line of code. What's the OS of the machine you're trying to remote to?

**Comment by NonSecwitter** [comment]
If I run this, targeting a remote machine, I get the above error:
`Invoke-CimMethod -Namespace "root/Microsoft/Windows/WindowsUpdate" -ClassName "MSFT_WUOperations" -MethodName ScanForUpdates -Arguments @{SearchCriteria="IsInstalled=0"} -ComputerName <computername>`

If I run this, targeting the local machine, I get a result set.

`Invoke-CimMethod -Namespace "root/Microsoft/Windows/WindowsUpdate" -ClassName "MSFT_WUOperations" -MethodName ScanForUpdates -Arguments @{SearchCriteria="IsInstalled=0"} `

Another problem I'm seeing is that I get an empty result set, although WSUS is showing that there are updates needed for the machine. Using the PSWindowsUpdate module, I can see that WSUS is set as the default servicing manager. My updates have installed, so I can't tell whether PSWindowsUpdate or WindwosUpdateProvider are returning the same results as the CIM method, but I noticed the inconsistency between the CIM method and WSUS last night before the updates installed.

**Comment by RichardSiddaway** [comment]
I'm not sure what's happening here but I suspect that someone thought it would be a good idea to revert to the situation we had with the old WSUS COM object that didn't work remotely.  The IIS WMI provider had these sorts of problems but they could be overcome by using PacketPrivacy .
This isn't really a PowerShell problem per se - its a WSUS/CIM problem that's surfacing through PowerShell.  This is madness because the MSFT_WUOperationsSession class from server 2016 and early Windows 10 versions works perfectly well remotely.

**Comment by RichardSiddaway** [comment]
Just to add to the fun with this

I successfully ran the ScanForUpdates method across a remote session direct to the VM using PowerShell Direct. I used the local Administrator credential on the VM and everything worked.

**Comment by NonSecwitter** [comment]
I had the same suspicion. FWIW, 

+ I checked the WMI Controls in the MMC Snapin, and there is nothing unusual about the permissions.
+ Watching the WSMAN traffic with wireshark, I see an HTTP 500 response to my MSFT_WUOperations request. 
+ Event Viewer for "WMI-Activity" shows this error
```
Id = {0A721CAE-794D-0003-1A24-720A4D79D301}; ClientMachine = <computer>; 
User = ASSOC\<myaccount>.admin; ClientProcessId = 2380; Component = Provider; 
Operation = Start IWbemServices::ExecMethod - root\microsoft\windows\windowsupdate :
MSFT_WUOperations::ScanForUpdates; ResultCode = 0x80041001; PossibleCause = Unknown
```
+ ResultCode = 0x80041001 means "Call failed."  (https://msdn.microsoft.com/en-us/library/aa394559(v=vs.85).aspx)
+ The DCOM security configuration doesn't allow me to enable remote execution of wuapihost for admins (just to test and see what would happen)

I suppose *some* functionality is an improvement over needing PSWindowsUpdate, but Microsoft really pisses me off for their lack of attention to such a critical component for maintaining our systems. Why is it such a problem to get a decent update framework? Clearly "Paint 3D" was more important for the bottom line.

**Comment by iSazonov** [comment]
The issue should be reported by Windows Preview feedback channel.
