### ISSUE TITLE
Question about running powershell form apps on mac osx

### ISSUE THREAD

**Issue by jg1000c** [PowerShell/PowerShell#5726]
I have a co-worker that creates GUI apps written in powershell. I'm guessing they rely on the Windows OS but was curious if there is a way to port them to work on a Mac. When I try to run the .ps1, I get "Could not load file or  assembly 'System.Windows.Forms".

**Comment by markekraus** [comment]
@jg1000c `System.Windows.Forms` has not been ported to .NET Core and is thus unavailable in PowerShell Core. This is true on both macOS and Linux.
