### ISSUE TITLE
Resolve-Path param that allows skipping IfExists check

### ISSUE THREAD

**Issue by ghost** [PowerShell/PowerShell#5730]
My eyes were scanning for something like "In 2017, finally PowerShell team has added..." while reading this QA https://stackoverflow.com/questions/3038337/powershell-resolve-path-that-might-not-exist. 😞 

For users to skip existence check, please consider adding a parameter to `Resolve-Path` cmdlet something similar to one of the following option:

```powershell
Resolve-Path -Unresolved <arg>     # OR
Resolve-Path -Unmonitored <arg>    # OR
Resolve-Path -Pretend <arg>        # OR
Resolve-Path -Force <arg>          # OR
Resolve-Path -SkipExistence <arg>
```

**Comment by iSazonov** [comment]
@kasper3 Thanks for your report! Could you please add repo steps in the issue description?

**Comment by kasper3** [comment]
@iSazonov, it's not a bug report but a feature request to add a parameter in Resolve-Path cmdlet

**Comment by iSazonov** [comment]
I ask repo steps because it is easy to understand _desire behavior_ in simple script context - we could use such sample scripts as base for tests.

Perhaps we need Normalize-Path cmdlet.

**Comment by kasper3** [comment]
In dotnet it's called `Path.GetFullPath`, so perhaps `Get-FullPath` cmdlet?
Even better, a more familiar analogous to Unix' readlink https://linux.die.net/man/2/readlink, perhaps `Get-ReadLink` cmdlet (with `readlink` alias) to match with POSIX std.

```powershell
Get-ReadLink ~/.nuget
# -> c:\Users\username\.nuget

mkdir /temp
mkdir /temp/tE$T
readlink /temp/te$t\some\non/existing/path  # casing of tE$T is wrong on purpose
# -> c:\temp\tE$T\some\non\existing\path  (with correct casing)
```

The UNC path rules on Windows are quite detailed to get covered by any interpreter. See @JeremyKuhne's implementation https://github.com/JeremyKuhne/WInterop. Not sure to what extent they can be covered in PowerShell as currently BCL seems to lack some cases.

Note readlink also resolves the symlink. On Windows soft/hard links and Junctions can be covered by the same semantics?

We can also start with simple usecases (without symlinks and UNCs) and then gradually include more features in subsequent releases.

**Comment by lukeb1961** [comment]
this came up today and a suggestion was to use $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath( $InputPath )
but given we have Resolve-Path or Convert-Path these should have the [switch] as suggested above.
