### ISSUE TITLE
Range operator with char returns unexpected value

### ISSUE THREAD

**Issue by stknohg** [PowerShell/PowerShell#5731]
Steps to reproduce
------------------

```powershell
[char]'a'..[char]'e'
```

Expected behavior
-----------------

```powershell
# Char array ([char]'a', [char]'b', [char]'c', [char]'d', [char]'e')
a
b
c
d
e
```

Actual behavior
---------------

```powershell
# Int array (97, 98, 99, 100, 101)
97
98
99
100
101
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-rc.2
PSEdition                      Core
GitCommitId                    v6.0.0-rc.2
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by FireInWinter** [comment]
Oddly the actual behavior matches Windows PowerShell results.  So changing this might break a few scripts that otherwise might work when on PowerShell 6.  
I still think it should be modified to give the expected results, but wanted to call out that ```[char]'a'..[char]'e'``` did work in previous versions of PowerShell by returning 97-101.

**Comment by iSazonov** [comment]
@FireInWinter Thanks! I'll label the fix as Breaking change.

**Comment by nightroman** [comment]
Is it a bug at all? The operator casts operand to integers and then increments. The result is integers. This looks fine (to me).

What about `1.1 .. 9.1`? Should it work with doubles or not? What about datetime, etc.?

**Comment by iSazonov** [comment]
It is bug for PowerShell Core not for Windows PowerShell. Windows PowerShell support only [Int]. PowerShell Core support [char].
It would works with doubles if doubles had an enumerator.
