### ISSUE TITLE
Runspace pool memory leaks (v6, v5, no leaks in v2)

### ISSUE THREAD

**Issue by nightroman** [PowerShell/PowerShell#5746]
Runspace pools may cause memory leaks, at least in tested PowerShell v5, v6.
PowerShell v2 does not have this issue.

The below script repeats a job infinitely in a loop. Run it and watch the
printed application handle counts and memory sizes. Stop scripts manually by
<kbd>Ctrl+C</kbd> or close the PowerShell console.

Steps to reproduce
------------------

```powershell
# This script uses [PowerShell] with runspace pools. Printed handle and memory
# numbers grow over time. Stop manually by Ctrl+C or close the console.
# Otherwise you may run out of memory.

for() {
    $pool = [RunspaceFactory]::CreateRunspacePool(1, 2)
    $pool.Open()

    $ps1 = [PowerShell]::Create()
    $ps1.RunspacePool = $pool

    $job1 = $ps1.AddScript('Get-Date').BeginInvoke()
    $null = $job1.AsyncWaitHandle.WaitOne()
    $result = $ps1.EndInvoke($job1)

    $ps1.Dispose()
    $pool.Close()

    $p = Get-Process -Id $PID
    "$result Handles: $($p.HandleCount) Memory: $($p.PrivateMemorySize64 / 1mb) mb"
}
```

Expected behavior
-----------------

The application used handle counts and memory sizes stay within reasonable ranges.

Actual behavior
---------------

The application used handle counts and memory sizes grow over time,
pretty fast in this example due to leaks in the infinite loop.

Environment data
----------------

```
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-rc.2
PSEdition                      Core
GitCommitId                    v6.0.0-rc.2
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name                           Value
----                           -----
PSVersion                      5.1.15063.786
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.786
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by nightroman** [comment]
Here is the similar script with runspaces but without runspace pools.
It has no obvious leaks in tested v6, v5, v2.

Thus, runspace pools look responsible for leaks.

```powershell
# This script uses [PowerShell] without runspace pools. Printed handle and
# memory numbers stay within reasonable ranges. Stop manually by Ctrl+C or
# close the console.

for() {
	$ps1 = [PowerShell]::Create()

	$job1 = $ps1.AddScript('Get-Date').BeginInvoke()
	$null = $job1.AsyncWaitHandle.WaitOne()
	$result = $ps1.EndInvoke($job1)

	$ps1.Dispose()

	$p = Get-Process -Id $PID
	"$result Handles: $($p.HandleCount) Memory: $($p.PrivateMemorySize64 / 1mb) mb"
}
```

**Comment by potatoqualitee** [comment]
Oh wow, interesting!

**Comment by rkeithhill** [comment]
In many cases, calling `Close()` or `Dispose()` amount to the same thing.  Not with a `RunspacePool` though.  You need to be callind `Dispose()`.  Try this:
```posh
for() {
    $pool = [RunspaceFactory]::CreateRunspacePool(1, 2)
    $pool.Open()

    $ps1 = [PowerShell]::Create()
    $ps1.RunspacePool = $pool

    $job1 = $ps1.AddScript('Get-Date').BeginInvoke()
    $null = $job1.AsyncWaitHandle.WaitOne()
    $result = $ps1.EndInvoke($job1)

    $ps1.Dispose()
    $pool.Dispose()
    $p = Get-Process -Id $PID
    "$result Handles: $($p.HandleCount) Memory: $($p.PrivateMemorySize64 / 1mb) mb"
    $p = $result = $null
    [System.GC]::Collect()
}
```

**Comment by nightroman** [comment]
It's a very good news!

> In many cases, calling Close() or Dispose() amount to the same thing but not with a RunspacePool. You need to call Dispose()

Is this by design or a bug?

**Comment by MaximoTrinidad** [comment]
By the way!!  The initial sample code does shows memory leak in Windows 10 Insider Build 17046 when executing in Windows PowerShell 5.1.

```
PS [441] > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17046.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17046.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by MaximoTrinidad** [comment]
Good one @rkeithhill!  Thanks.

**Comment by potatoqualitee** [comment]
Unfortunately, I've experienced leaks with 

``` powershell 
$pool.Close() 
$pool.Dispose()
```

Executing GC cleanup within the runspace scriptblock cleared it up but slowed things down dramatically.

**Comment by nightroman** [comment]
Also, the fact that v2 does not show leaks with the same code is interesting.

**Comment by rkeithhill** [comment]
@potatoqualitee I would not generally recommend putting GC collect calls in production code because that subverts the GC's (generally good) algorithms for when a GC is needed.  But for memory hoard detection, it is useful to eliminate the "non-determinism" of the GC.

Also, if you call `RunspacePool.Dispose()` it [internally calls](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/hostifaces/RunspacePoolInternal.cs#L830) `Close()` so there is no need to call `Close()` before `Dispose()` AFAICT.

@nightroman 
> Is this by design or a bug?

The [design guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/dispose-pattern) say this:

> ✓ CONSIDER providing method Close(), in addition to the Dispose(), if close is standard terminology in the area. 
When doing so, it is important that you make the Close implementation identical to Dispose and consider implementing the IDisposable.Dispose method explicitly. 

Since this is a "guideline" (CONSIDER vs DO or DO NOT), I wouldn't consider it a bug - bad form perhaps unless there is a way to re-open a closed RunspacePool but I don't see that functionality.

P.S. Whenever I see "DO or DO NOT", I reflexively want to add "there is no try".  Hmm...
