### ISSUE TITLE
-OutVariable common parameter doesn't capture external-utility output in advanced functions

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#5758]
Steps to reproduce
------------------

```powershell
# Define an advanced function that outputs a string as well as 
# stdout output from an external utility:
function get-foo { [CmdletBinding()] param() 'hi'; whoami }

# Invoke the function and also collect its output in variable $var.
# Output the variable afterwards.
get-foo -OutVariable var; '---'; $var
```

Expected behavior
-----------------

```none
hi
jdoe
---
hi
jdoe
```

That is, all of the direct output should be reflected in `$var` too.

Actual behavior
---------------

```none
hi
jdoe
---
hi
```

Note how `$var` collected only `'hi'`, and not also the `whoami` utility's output.

Curiously, the problem goes away if you either assign the `get-foo` call to a variable or pipe to another cmdlet; e.g., the following variations do NOT exhibit the problem:

```powershell
get-foo -OutVariable var | Out-Host; '---'; $var  # OK
$null = get-foo -OutVariable var; '---'; $var  # OK (direct output won't show)
```

Environment data
----------------

```powershell
PowerShell Core v6.0.0-rc.2 on macOS 10.13
PowerShell Core v6.0.0-rc.2 on Ubuntu 16.04.3 LTS
PowerShell Core v6.0.0-rc.2 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
Windows PowerShell v5.1.15063.674 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by PetSerAl** [comment]
Without piping (or with piping to `Out-Default`) native command [qualify for condition](https://github.com/PowerShell/PowerShell/blob/master@%7B2017-12-30%7D/src/System.Management.Automation/engine/NativeCommandProcessor.cs#L1201-L1224) to be patched directly to console (PowerShell's own standard output). Thus, its output not passed thru PowerShell and not captured in `-OutVariable` parameter.
Similar to how `cmd /c "echo Error>&2"` work in console, but produce `ErrorRecord`, when invoked in `ISE`, as job or in remote session.
