### ISSUE TITLE
Preference variable $OutputEncoding in child scopes misbehaves with encodings created with New-Object / commands rather than expressions

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#5763]
Note: This issue may well be just a symptom of  #5579; if so, it still may be of interest, because it demonstrate that the linked issue has real-world consequences.

Preference variable `$OutputEncoding` determines the encoding used to send text to external utilities.

In the _global_ scope, assigning the output from a `New-Object` call or, generally, a _command_ (as opposed to an _expression_) works fine.

However, **in a _non-global_ scope, such as inside a function, it does not: assigning output from a _command_ to `$OutputEncoding` is effectively ignored.**

For simplicity, the example below uses `Write-Output` in a somewhat contrived manner, but **an attempt to use `New-Object` to instantiate a specific encoding, e.g., `New-Object System.Text.Utf8Encoding`, would exhibit the same problem: it would be ignored.**

The **workaround** is to apply `.psobject.BaseObject` to `New-Object`'s result, or, in PSv5+,  to use `[<encoding>]::new()` instead.

Steps to reproduce
------------------

On Windows:

```powershell
function foo0 { 'ü' | findstr 'ü'  }
function foo1 { $OutputEncoding = [Console]::OutputEncoding; 'ü' | findstr 'ü'  }
# Same as foo1, except that Write-Output is used to produce output.
function foo2 { $OutputEncoding = Write-Output ([Console]::OutputEncoding); 'ü' | findstr 'ü'  }

foo0; '---'; foo1; '---'; foo2
```

Expected behavior
-----------------

```none
---
ü
---
ü
```

Note that `foo0`, perhaps surprisingly, does _not_ output anything, because the default `$OuputEncoding` value - UTF-8 in PowerShell Core and ASCII in Windows PowerShell - results in output that prevents `findstr.exe` from matching non-ASCII characters.

Actual behavior
---------------

```none
---
ü
---
```

That is, only the _expression-based_ assignment to the (non-global) `$OutputEncoding` variable took effect, not the _command-based_ one.

The command-based one seems to _quietly fall back to ASCII_.

Also note that this issue won't arise on _Unix_ platforms, where PowerShell now emits UTF-8 by default and external utilities such as `grep` expect just that.

Environment data
----------------

```powershell
PowerShell Core v6.0.0-rc.2 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
Windows PowerShell v5.1.15063.674 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by PetSerAl** [comment]
`Write-Output [Console]::OutputEncoding` -> `Write-Output ([Console]::OutputEncoding)`

[Culprit line](https://github.com/PowerShell/PowerShell/blob/master@%7B2017-12-30%7D/src/System.Management.Automation/engine/NativeCommandProcessor.cs#L1800). Should call `PSObject.Base` before `as`.
