### ISSUE TITLE
Wrong output for Split-Path -LeafBase against a path contains .(dot) in last directory the name

### ISSUE THREAD

**Issue by kvprasoon** [PowerShell/PowerShell#5766]
Steps to reproduce
------------------

```
Split-Path -Path $PSHOME -LeafBase
```

Expected behavior
-----------------

```
PS> Split-Path -Path $PSHOME -LeafBase

PS> 6.0.0-rc.2 #as this is a folder

```

Actual behavior
---------------

```
PS> 6.0.0-rc
# .2 got trimmed assuming it as an extension
```

Environment data
----------------

```
#Windows
Name                           Value                                                                                                                                    
----                           -----                                                                                                                                    
PSVersion                      6.0.0-rc.2                                                                                                                               
PSEdition                      Core                                                                                                                                     
GitCommitId                    v6.0.0-rc.2                                                                                                                              
OS                             Microsoft Windows 10.0.17063                                                                                                             
Platform                       Win32NT                                                                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                                      
SerializationVersion           1.1.0.1                                                                                                                                  
WSManStackVersion              3.0                                                                                                                                      


#Reproducible in Ubuntu as well
```

**Comment by iSazonov** [comment]
What is "6.0.0-rc.2" - file name or folder name? How can we detect the difference?

**Comment by FireInWinter** [comment]
Split-Path is basically just doing string operations, it doesn't determine if the Path exists.  So you could do something like
```
Split-Path -Path '/asdf/asdf.foo' -LeafBase
asdf
```
And it won't give you an error that it doesn't exist.  So for your example, $PSHOME, you know it is a directory, but Split-Path doesn't.  To get what you want, you could do something like:
```
(Get-Item -Path $PSHOME).BaseName
6.0.0-rc.2
```
But that works because the object returned from Get-Item in this case is an IO.DirectoryInfo object.  If the item doesn't exist, you'll have to worry about handling the resulting error.

**Comment by markekraus** [comment]
@kvprasoon if the item does not yet exist, there is no way to know that a string is a file or a directory other than by intentions. If you call `Split-Path -LeafBase -Path c:\path\foo.bar` you are implying that this path is intended to be a file and you are looking for the base of the file name. `Split-Path` is not clairvoyant and cannot divine the future of this path.

**Comment by kvprasoon** [comment]
@markekraus , Yes I agree to your statement. But I believe this is a valid use case and the script logic can go wrong if there is such directories consumed by `Split-Path`

**Comment by markekraus** [comment]
@kvprasoon I don't understand. If the path doesn't exist, use `split-path`, if it does, use the data returned by `get-item`. There is simply no way to just see the future and know that a string that contains data that is ambiguous for a file or a older and divine the future of that string as a real world item. If you tell `split-path` the string is a file path by supplying `-LeafBase` it assumes *you* know that path is file and not a directory. If you don't want an invalid leaf base for that, then don't supply it a string that will be used for a directory. It cannot guess what your intentions are for that string. It should not be used to validate a path, that's not its purpose.

**Comment by kvprasoon** [comment]
@markekraus  - I understand that the `Split-Path` cmdlet will not(or should not) have any idea on the path's existence. But I raised the concern to notify the error I got.

**Comment by markekraus** [comment]
In this case I believe its `by design` and not really an error.

**Comment by kvprasoon** [comment]
Closing the issue #5766 assuming the `Split-Path` cmdlet consumer will use it with `-LeafeBase` parameter only if the consumer is damn sure on the target path will be of a file.
