### ISSUE TITLE
Source code reference site

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#5767]
We could create a site like https://source.dot.net/.
Base project https://github.com/KirillOsenkov/SourceBrowser.

I can compile the project and generate the site (~258Mb) in ten minutes without problems. But I haven't resources to publish it on real web server.

**Comment by iSazonov** [comment]
@SteveL-MSFT Is the team interested in implementation of the site?

**Comment by SteveL-MSFT** [comment]
@iSazonov this is pretty neat.  If I'm reading the SourceBrowser repo correctly, the website that is generated is static, so we would have to update it periodically?

**Comment by iSazonov** [comment]
Yes, we need update by cron every night. It seems CoreFX does this for latest codes from master branch.

**Comment by SteveL-MSFT** [comment]
@iSazonov I think we should adopt this, but it's not high on the priority right now.  Parking in 6.2.0 for now.

**Comment by iSazonov** [comment]
@SteveL-MSFT Will your team have resources for the site in new fin year?

**Comment by SteveL-MSFT** [comment]
I can possibly have someone look at this starting next month.
