### ISSUE TITLE
$Error is empty immediately after Write-Error in module.

### ISSUE THREAD

**Issue by alx9r** [PowerShell/PowerShell#5768]
I'm experimenting with monitoring `$Error` during unit testing to validate commands' non-terminating error behavior.  The scope rules that `$Error` follows seem rather peculiar.  Neither [`about_Automatic_Variables`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_automatic_variables?view=powershell-6) nor [`about_Scope`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_scopes?view=powershell-6) seem to explain this behavior.  I found some discussion about `$Error`'s behavior in modules in [this @BrucePay post](https://stackoverflow.com/a/11457624/1404637).  That post is from 2012 so I'm wondering whether it's still valid.  If it is still valid, I'm not entirely sure how to interpret that post: 
1. Is the non-global `$Error` meant to contain a log of only the module's errors?  
2. Is the non-global `$Error` entirely vestigial and should be altogether avoided?
3. How should I monitor non-terminating errors originating from a module from within that module?  `$Error`?  Some filter of `$global:Error`?

Steps to reproduce
------------------

```powershell
function e {
    Write-Error 'e'
    Write-Host "e: $($Error.Count)"
}
New-Module {
    function f {
        Write-Error 'f'
        Write-Host "f: $($Error.Count)"
    }
    function g {
        param(
            [System.Collections.ArrayList]$ErrorRef
        )
        Write-Error 'g'
        Write-Host "g: $($ErrorRef.Count)"
    }
} | Out-Null


$Error.Clear()
Write-Error 'outer'
Write-Host "outer: $($Error.Count)"

e
f
g -ErrorRef $Error
```

Expected behavior
-----------------
(I have omitted the error stream here.)
```none
outer: 1
e: 2
f: 3
g: 4
```

Actual behavior
---------------

(I have omitted the error stream here.)
```none
outer: 1
e: 2
f: 0
g: 4
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value                                            
----                           -----                                            
PSVersion                      6.0.0-rc.2                                       
PSEdition                      Core                                             
GitCommitId                    v6.0.0-rc.2                                      
OS                             Microsoft Windows 6.3.9600                       
Platform                       Win32NT                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                          
PSRemotingProtocolVersion      2.3                                              
SerializationVersion           1.1.0.1                                          
WSManStackVersion              3.0                                              
```

**Comment by markekraus** [comment]
Personally, I advise against using `$error` for anything other than casual console debugging. 

> How should I monitor errors originating from a module from within that module?

Could you be more specific in what you are asking?

**Comment by alx9r** [comment]
>Personally, I advise against using $error for anything other than casual console debugging.

Can you explain why you advise against using `$Error`?  That advice doesn't seem consistent with [this MSDN article](https://msdn.microsoft.com/en-us/library/ms714412(v=vs.85).aspx) (and [@mklement0's pragmatic summary thereof](https://stackoverflow.com/questions/9294949/when-should-i-use-write-error-vs-throw-terminating-vs-non-terminating-errors/39949027#39949027)).  Each of those recommends using non-terminating errors in certain cases.  It seems that unit testing for non-terminating errors would naturally involve `$Error`.  Is there some other method of unit testing for non-terminating errors that I should consider?

**Comment by markekraus** [comment]
`$Error` is populated by more than just the immediate code (nested code can populate it) and some misguided nested code will even clear it. Also, there are the scoping issues you mentioned with regards to modules. All in all, I just find `$Error` to not be very reliable. It's a handy tool when you are in the console, but I would never personally write code that depended on it or tests that run against it.

For testing non-termination errors, in this project as well as others usually involves toggling the error action preference (either the automatic variable or the via advanced cmdlet parameter) and then passing the script block to `Should Not Throw` and/or `Should Throw`. Another way is to make use of the `-ErrorVariable` parameter.

**Comment by alx9r** [comment]
>For testing non-termination errors, in this project as well as others usually involves toggling the error action preference...

That seems pragmatic as a first approximation.  Converting non-terminating to terminating errors, however, significantly affects control flow especially where the pipeline is involved.  The case where control flow and non-terminating errors both matter is probably an edge case for most commands, but I'm finding that that's an edge case I need to test.  That's why I'm interested in `$Error`.

**Comment by bergmeister** [comment]
@alx9r There is also `$?` which I had to use for special cases in the past to check for non-terminating errors (a different approach would be change the `ErrorAction` to `Stop` inside a try block and then access the error using `$_.Exception` in the catch block). Maybe that could help you but not sure.

**Comment by alx9r** [comment]
I have found some success monitoring the `$global:Error` for unit testing for non-terminating errors.  The scope rules of the non-global `$error`, on the other hand, remain inscrutable to me.
