### ISSUE TITLE
PowerShell prompt teleports cursor around active line.

### ISSUE THREAD

**Issue by ghost** [PowerShell/PowerShell#5778]
To reproduce, follow the build instructions for Ubuntu 17.04 until `pwsh` is available. Enter PowerShell and begin typing. The cursor should flit around the bottom of the screen.

This was experienced over an SSH connection, and may be related to #4141.

**Comment by lzybkr** [comment]
See if PSReadLine 2.0 helps - you can get the beta [in the gallery](https://www.powershellgallery.com/packages/PSReadline/2.0.0-beta1) or [on GitHub](https://github.com/lzybkr/PSReadLine/releases/tag/v2.0.0-beta1)

**Comment by ThomasNieto** [comment]
@StevenBucher98 can this be closed due to lack of updates and the OP account no longer exists?
