### ISSUE TITLE
Active Directory Site

### ISSUE THREAD

**Issue by NoCheroot** [PowerShell/PowerShell#5781]
I rely on this pretty heavily:
```
[System.DirectoryServices.ActiveDirectory.ActiveDirectorySite]::GetComputerSite().Name
```
It is fast and reliable, but does not work in 6.0.

![image](https://user-images.githubusercontent.com/10468415/34537538-736d7e4c-f08e-11e7-8121-e768f357c77e.png)

Tried to resolve the "Could not load file or assembly 'System.Configuration.ConfigurationManager'" with this: https://www.nuget.org/packages/System.Configuration.ConfigurationManager/4.5.0-preview1-25914-04, but I suspect there are reasons I'm not seeing which will prevent that route from working.  I didn't consider loading System.DirectoryServices from .Net Framework a serious solution anyway, but I thought I'd try just to see.

These provide the same information, and work with 6.0:
```
$ADSystemInfo = New-Object -ComObject ADSystemInfo
$type = $ADSystemInfo.GetType()
$type.InvokeMember('SiteName', 'GetProperty', $null, $ADSystemInfo, $null)
```
```
Get-CimInstance -ClassName Win32_NTDomain | Select-Object -ExpandProperty ClientSiteName
```

I'd like to avoid using the COM object option if possible.  I've found it less reliable than GetComputerSite in the past.  The second option is extremely slow.

So, two questions.

I see System.DirectoryServices listed here: https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.Windows.Compatibility/Microsoft.Windows.Compatibility.pkgproj.  Does that mean at some point in the future GetComputerSite() will work with 6.0 out of the box?

Does 6.0 provide another fast reliable way to get AD Site Name I'm not seeing?

**Comment by markekraus** [comment]
Hi @NoCheroot! This will work on 64-bit windows:

```powershell
Install-Module -Name PSCoreWindowsCompat -Scope CurrentUser
Import-Module PSCoreWindowsCompat
[System.DirectoryServices.ActiveDirectory.ActiveDirectorySite]::GetComputerSite().Name
```

For now my separate module or manually adding the [Windows Compatibility Pack for .NET Core](https://blogs.msdn.microsoft.com/dotnet/2017/11/16/announcing-the-windows-compatibility-pack-for-net-core/) are the 2 ways of doing this. There is work underway to make an "offcial" compatibility module which will restore many missing windows-only functions and .NET classes. https://github.com/PowerShell/WindowsPowerShellCompatibilityPack it is in the very early stages though. Eventually it will replace my community module.

**Comment by NoCheroot** [comment]
Perfect.  Thank you.

**Comment by iSazonov** [comment]
It seems .Net Core 2.1.0 will have ported `System.DirectoryServices` (but not still ActiveDirectory).

**Comment by chuanjiao10** [comment]
@markekraus : 
hi ,i found  PSCoreWindowsCompat owners is you.that can not be installed:
with "-Scope CurrentUser" or without

error message:
```
PackageManagement\Install-Package : Unable to load DLL 'api-ms-win-core-sysinfo-l1-1-0.dll': The specified module or one of its dependencies could not be found.                                                                                                                                     (Exception from HRESULT: 0x8007007E)                                                                                                             At /opt/microsoft/powershell/6.0.0-rc.2/Modules/PowerShellGet/1.6.0/PSModule.psm1:2057 char:21                                                    + ...          $null = PackageManagement\Install-Package @PSBoundParameters                                                                       
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
+ FullyQualifiedErrorId : System.DllNotFoundException,Microsoft.PowerShell.Commands.TestModuleManifestCommand,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage


```

**Comment by markekraus** [comment]
@chuanjiao10 Please open an issue here https://github.com/markekraus/PSCoreWindowsCompat/issues
