### ISSUE TITLE
Provide new interface to implement a PSProvider

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#5789]
The current apis are difficult to use which spawned middle-ware like [SHiPS](https://github.com/powershell/ships) and [Simplex](https://github.com/beefarino/simplex).  The downside to these additional layers is performance impact.  Consider having new apis that simplify the PSProvider authoring experience.

**Comment by iSazonov** [comment]
Who can design the API? I am afraid that the design and implementation may take several months to work intensively. We have to start now if we want to get this to 6.1.0.

**Comment by SteveL-MSFT** [comment]
@iSazonov at this time, I don't have any engineers available to design nor implement this.  If you're interested, feel free to tackle this and author an RFC.  Later this month I'm going to re-triage the issues marked for `6.1.0-Consider` and will probably move a bunch to `6.2.0-Consider`.

**Comment by iSazonov** [comment]
Oh, I don't know this code so well to redesign it. I know a few weaknesses and will continue to investigate this code.

It would also be good to have PowerShell Core **roadmap** on next 1-2 years so that the community can work effectively with MSFT.

**Comment by SteveL-MSFT** [comment]
@iSazonov excellent point about an updated roadmap.  Will work on it and target getting it published by GA time.

**Comment by jzabroski** [comment]
The ideal design pattern for "provider model" (in my opinion) is that of "implicit traits" (Scala) or type classes (Haskell).

**Comment by vexx32** [comment]
WG-Engine discussed this one a bit today. Our general consensus is that this is a huge scope of work and currently not well-defined. Accomplishing this would likely involve a lengthy RFC process and a full rewrite of the provider spec / a completely new provider specification before we ever got to looking at any implementations. Reviewing it also would be a lengthy task.

Given that, our opinion is essentially that this is unlikely to happen until funding and support is provided from the PowerShell team, and that means this kind of issue is pretty much unilaterally in @SteveL-MSFT's (and/or other PowerShell PMs') ballpark as to if and when it might get worked on, much less completed.

The addition of a `major-investment` Github label was briefly suggested, as a shortlist of things that are nice to dream about but basically only the pwsh PMs can realistically move forward in the project. This might be one such issue. 😁
