### ISSUE TITLE
dose "ls variable: " abandoned in ps6.x?

### ISSUE THREAD

**Issue by rocketRobin** [PowerShell/PowerShell#5795]
Just like the title, my question is. and what command instead that?

**Comment by SteveL-MSFT** [comment]
Don't understand your question.  The `variable:` drive still exists in PSCore6.

**Comment by rkeithhill** [comment]
`ls` is an alias that is no longer defined on Linux or macOS.  If you are on one of those platforms, try `gci variable:`.

**Comment by rocketRobin** [comment]
ok! I got it. thaks!

**Comment by rocketRobin** [comment]
And I have another question:
when I use "cgi env:", I got a list ,and  I use "$env:home" but nothing out put ,but it have a value(root) in the list before ,and  I try outher it's also nothing. so why?
my os is fedora 27
