### ISSUE TITLE
Method parameter attributes are ignored

### ISSUE THREAD

**Issue by lyra-edmundson** [PowerShell/PowerShell#5796]
It seems that if you set an attribute targeting a method parameter in a PowerShell class, it is ignored.

Note that I don't mean attributes on function/cmdlet parameters. Those attributes, such as `[ValidateNotNullOrEmpty()]`, are actually targeting a property.

Steps to reproduce
------------------

```powershell
class ExampleClass {
    ExampleMethod([System.Reflection.Obfuscation()][string]$attrParam) {
    }
}
[ExampleClass].GetMethod("ExampleMethod").GetParameters()
```

Expected behavior
-----------------

`CustomAttributes` for _attrParam_ contains `ObfuscationAttribute`.

Actual behavior
---------------

`CustomAttributes` for _attrParam_ is an empty collection:

```powershell
Attributes       : None
Member           : Void ExampleMethod(System.String)
Name             : attrParam
ParameterType    : System.String
Position         : 0
IsIn             : False
IsLcid           : False
IsOptional       : False
IsOut            : False
IsRetval         : False
DefaultValue     :
RawDefaultValue  :
HasDefaultValue  : False
CustomAttributes : {}
MetadataToken    : 134217729
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-rc.2
PSEdition                      Core
GitCommitId                    v6.0.0-rc.2
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Notes
----------------

* The choice of `ObfuscationAttribute` above is irrelevant. It was just the first builtin attribute I found that can target a method parameter.
* This issue also occurs for me on PowerShell 5.1.

**Comment by jayson-edmundson** [comment]
In retrospect, `CallerMemberName` was a poor choice for an example attribute since it might not have worked even if it wasn't ignored. Updated description to use `ObfuscationAttribute`.
