### ISSUE TITLE
Replace Googletest git submodule with NuGet package

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#5801]
[PR 5786](https://github.com/PowerShell/PowerShell/pull/5786) revealed that the only git submodule that is left in this repo is the [src/libpsl-native/test/googletest](https://github.com/google/googletest/tree/c99458533a9b4c743ed51537e25989ea55944908) submodule and @iSazonov pointed out that we could maybe replace it with the following NuGet package:
https://www.nuget.org/packages/googletest/
The only caveat is that the current submodule is from September 2013 (version 1.7), which means the newer NuGet package (first version in October 2016, version 1.8) might contain breaking changes.

**Comment by bergmeister** [comment]
@iSazonov Shall we move this issue to the PowerShell-Native repo where the code has been moved to?
https://github.com/PowerShell/PowerShell-Native

**Comment by iSazonov** [comment]
@bergmeister Please move the Issue to https://github.com/PowerShell/PowerShell-Native and fill free to push PR there. 
Seems we already have newest Googletest version in PowerShell-Native repo.
