### ISSUE TITLE
Get-WinEvent on Linux/Ubuntu 16.04

### ISSUE THREAD

**Issue by geekscrapy** [PowerShell/PowerShell#5810]
Installed Powershell via the suggested commands however I don't seem to have access to Get-WinEvent. The functionality I'm looking for is to take a EVTX file and output to JSON, probably using ConvertTo-Json. Happy to hear of another way to convert EVTX. TIA!

```
> Get-WinEvent                                                                                                                                           
Get-WinEvent : The term 'Get-WinEvent' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-WinEvent
+ ~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Get-WinEvent:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```

```
> $PSVersionTable                                                                                                                                        

Name                           Value                                                                                                                                  
----                           -----                                                                                                                                  
PSVersion                      6.0.0-rc.2                                                                                                                             
PSEdition                      Core                                                                                                                                   
GitCommitId                    v6.0.0-rc.2                                                                                                                            
OS                             Linux 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016                                                                     
Platform                       Unix                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                
PSRemotingProtocolVersion      2.3                                                                                                                                    
SerializationVersion           1.1.0.1                                                                                                                                
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
The API is Windows-only. You can use `Get-WinEvent` on Windows or through remoting from Unix to Windows.

**Comment by iSazonov** [comment]
Perhaps we get it with [WindowsPowerShellCompatibilityPack](https://github.com/PowerShell/WindowsPowerShellCompatibilityPack)

**Comment by geekscrapy** [comment]
I installed this however the cmdlet isn't included... How else might I read Windows evtx logs on Linux? Using PS ofc

**Comment by iSazonov** [comment]
WindowsPowerShellCompatibilityPack is still not supported on Unix-s :-(
You could open remote connection (ssh), start Windows PowerShell and run the cmdlet.

**Comment by geekscrapy** [comment]
I'm trying to use it forensic analysis so the logs are copied from an offline system...
😣

**Comment by iSazonov** [comment]
Perhaps @SteveL-MSFT has an idea as address your request.

**Comment by SteveL-MSFT** [comment]
I believe the .Net APIs that `Get-WinEvent` uses relies on native Win32 APIs that simply won't ever exist on Linux.  Unless there is an existing OSS library to read evtx logs on non-Windows, you'll need to remote into a Windows machine to read them (even in offline scenario).

**Comment by iSazonov** [comment]
@SteveL-MSFT I found https://github.com/dotnet/corefx/issues/31358 and https://github.com/dotnet/corefx/pull/33662 - perhaps we could cleanup PowerShell Core code after moving to .Net Core 3.0.

**Comment by SteveL-MSFT** [comment]
@iSazonov I took a quick look at those two PRs and it's calling into Win32 dlls so it wouldn't work on on-Windows

**Comment by iSazonov** [comment]
@SteveL-MSFT Yes, it is Windows-only. My comment was that we could use the new Core code in PowerShell Core and remove a code we use currently.

**Comment by defensivedepth** [comment]
Any update on this functionality?

**Comment by iSazonov** [comment]
> Any update on this functionality?

@defensivedepth The API is Windows-only.

**Comment by defensivedepth** [comment]
ah, ok, thanks!
