### ISSUE TITLE
Powershell 6.0.0-GA release

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#5833]
From:  https://github.com/PowerShell/PowerShell/blob/master/docs/maintainers/releasing.md

- [x] Create a branch named `release` in `PowerShell/PowerShell` repository.
   All release related changes should happen in this branch.
- [x] Run tests on all supported Linux distros and publish results
- [x] Prepare packages
   - [x]  Build release packages
   - [x]  Sign the MSI packages and RPM package.
   - [x]  Install and verify the packages.
- [x]  Update documentation, scripts and Dockerfiles
   - [x]  Update [CHANGELOG.md](../../CHANGELOG.md) with the finalized change log draft.
   - [x]  Update other documents and scripts to use the new package names and links.
- [x]  Verify the release Dockerfiles.
- [x]  Create NuGet packages and publish them to `powershell-core` feed.
- [x]  Publish Linux packages to Microsoft YUM/APT repositories.
- [x]  Create the release tag and push the tag to `PowerShell/PowerShell` repository.
- [x]  Create the draft and publish the release in Github.
- [x]  Merge the `release` branch to `master` and delete the `release` branch.
- [x]  Trigger the release docker builds for Linux and Windows container images.
   - [x]  Linux: push a branch named `docker` to `powershell/powershell` repository to trigger the build at [powershell docker hub](https://hub.docker.com/r/microsoft/powershell/builds/).
     Delete the `docker` branch once the builds succeed.
   - [x]  Windows: queue a new build in `PowerShell Windows Docker Build` on VSTS.
- [x]  Verify the generated docker container images.
- [x]  Update the homebrew formula for the OSX package.
   This task usually will be taken care of by the community,
   so we can wait for one day or two and see if the homebrew formula has already been updated,
   and only do the update if it hasn't.
- [x] Open the next release milestone.

**Comment by daxian-dbw** [comment]
Test results:
```
OS                           Total Pass Fail Skipped Pending
--                           ----- ---- ---- ------- -------
CentOS Linux 7 (Core)         7590 6024   17    1207     342
Debian GNU/Linux 9 (stretch)  7590 6041    1    1207     341
openSUSE Leap 42.3            7590 6040    2    1207     341
Red Hat Enterprise Linux      7590 6019   23    1207     341
Ubuntu 14.04.5 LTS            7590 6041    1    1207     341
Ubuntu 16.04.3 LTS            7590 6041    1    1207     341
Ubuntu 17.04                  7590 6041    1    1207     341
```
Failures on CentOS are ones we've seen before: SSL not supported (16 errors); email not sent (1 error).
Other errors include
 - online help issues (known)
 - `Invoke-Item` (known - test issue)
 - DSC MOF Compilation issue (this is new, but I could not repro in isolation)
 - PowerShell freezes on exit (I think I've narrowed this down to this specific VM)

**Comment by chuanjiao10** [comment]
Congratulations!

Thanks to each powershell community member,
more than a year of hard work. 2016/08 --- 2018/01


He eat AWK's meat when h'm hungry.
He drink SED's blood and Laughing when h'm thirsty.
He drive a longer tank，going into the Linus Torvalds hometown.
He is the script Great,PowerShell Core V6!

壮志饥餐awk肉，笑谈渴饮sed血，驾powershell core v6长车，踏上linux山头~~~

**Comment by pcgeek86** [comment]
When will the release process be completed, and the Docker images get updated on the Docker Store? Right now, the Docker Store is only hosting the 6.0.0-RC2 container images. https://store.docker.com/community/images/microsoft/powershell

**Comment by daxian-dbw** [comment]
@pcgeek86 We have an issue on the YUM repository, and we are working on it now. Will trigger the docker build once it's resolved.

**Comment by pcgeek86** [comment]
@daxian-dbw Awesome, thanks for the insight. I was just curious what was holding it up. I'll be patient. :)

**Comment by daxian-dbw** [comment]
Docker images on docker hub have been updated. Will close this issue.
