### ISSUE TITLE
Feature Proposal: Splatting for .NET String Formatting

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#5844]
It would be really awesome if PowerShell developers could do something like this ...

```
$Params = @{
  FirstName = 'Trevor'
  LastName = 'Sullivan'
}
'Hello, my name is {FirstName} {LastName}.' -f @Params
```

Result:

```
Hello, my name is Trevor Sullivan.
```

### Option 1: Add a `-fs` operator

The new `-fs` operator would be short for "*format with splatting*." When used, PowerShell would look for a single HashTable on the right-hand side of the operator, and substitute the values with the appropriate, named placeholders in the string.

### Option 2: Your Ideas?

... this is just a quick idea. If anyone else has input on how this functionality could be implemented, or if it would even be useful, I'd love to hear it! What do you guys think?

People seem to like the benefits of .NET string formatting, but it can become unwieldy quickly, if there are lots of parameters on the right-hand side of the `-f` operator. This proposal to support "**splatting with .NET string formatting**" would make the syntax a bit more manageable.

**Comment by KevinMarquette** [comment]
I like this idea quite a bit. I would not even complain if it became a parameter

    'Hello, my name is {FirstName} {LastName}.' -f -hashtable $Params

**Comment by lzybkr** [comment]
See https://github.com/PowerShell/PowerShell-RFC/issues/6 for other splatting ideas.

A new operator might not be necessary - `$fmtString -f @expr` is already an error, so new semantics can be defined.

Things to think about:

* Should you allow splatting of multiple hashtables like `$fmtString -f @h1,@h2`? If so, what how would you support mixing, e.g. `"{0} is {Thing}" -f $x,@y` or `"{0} is {Thing}" -f @y,$x`
* What about .Net formatting, e.g. `"Memory Read: {Address,10:x8} -f @@{Address = $something}`

**Comment by Jaykul** [comment]
Is it worth adding yet another way to do string interpolation?

Given that we already have:

```posh
$FirstName = 'Trevor'
$LastName = 'Sullivan'
"Hello, my name is ${FirstName} ${LastName}"
```
and 
```posh
$name = @{
  First = 'Trevor'
  Last = 'Sullivan'
}
"Hello, my name is $($First.Name) $($Last.Name)"
```

Do we really need:

```posh
$name = @{
  First = 'Trevor'
  Last = 'Sullivan'
}
"Hello, my name is {First} {Last}" -f @name
```
