### ISSUE TITLE
Provide command-line option for loading a custom powershell.config.json

### ISSUE THREAD

**Issue by dantraMSFT** [PowerShell/PowerShell#5847]
This enhancement is primarily driven by testing use cases including the following:

1: On Linux, syslog imposes a measurable overhead impacting test runtimes. (@JamesWTruher: Please provide data)

2: For testing syslog and os_log there is a need to override the source name and output log to provide reliable verification.

One solution to both issues is to support launching an instance of PowerShell with a custom powershell.config.json file as a command-line option.  For test runs, the json could restrict log output to error and critical messages.  For syslog testing, the log file can be changed to ensure only the expected output is captured.  For syslog and os_log, the source name can be changed to enable filtering and verifying the expected log messages.

**Comment by JamesWTruher** [comment]
During GA testing I observed that many tests were taking many seconds (I didn't capture any specific data, but it was considerable), after disabling `systemd-journald` the time dropped considerably. It should be noted that the system under test was a single vcpu system, which may have some impact on logging efficiency

**Comment by iSazonov** [comment]
Should the command-line option be only in debug code?
