### ISSUE TITLE
PSCore6 - Won't install in Ubuntu thru the apt Update/Upgrade

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#5850]
This is just an observation as I'm not sure which direction Microsoft will take with Linux distro to do the auto upgrade of PowerShell Core.

Steps to reproduce
------------------
sudo apt update

sudo apt upgrade

```powershell
pwsh
$psversiontable
```

Expected behavior
-----------------
After executing apt upgrade then PowerShell Core 6.0.0 would have been installed.
```none

```

Actual behavior
---------------
It just won't download PowerShell Core 6.0.0 for upgrade
```none

```

Workaround
--------------
Manually do the following steps:
sudo apt remove powershell
sudo apt install -y powershell

Environment data
----------------
Window 10 Ubuntu
Ubuntu 16.04
Ubuntu 17.10

```powershell
> $PSVersionTable

```
![pscore6 0 0_03c_2018-01-10_17-37-05](https://user-images.githubusercontent.com/19892435/34800782-54a970ba-f633-11e7-8398-6b9200553da0.png)

**Comment by markekraus** [comment]
I can confirm. But.. it looks like the package is there and some how thinks rc.2 is newer:

```bash
sudo apt -a list powershell

```

```none
powershell/now 6.0.0-rc.2-1.ubuntu.16.04 amd64 [installed,local]
powershell/xenial 6.0.0-1.ubuntu.16.04 amd64
```

Perhaps this is related to the same thing seen in Suse? #5846

**Comment by markekraus** [comment]
Also, here is a workaround:

```bash
 sudo apt-get install --upgrade powershell=6.0.0-1.ubuntu.16.04
pwsh -v
```

```none
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be DOWNGRADED:
  powershell
0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 52 not upgraded.
Need to get 51.9 MB of archives.
After this operation, 7,168 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 powershell amd64 6.0.0-1.ubuntu.16.04 [51.9 MB]
Fetched 51.9 MB in 1s (29.7 MB/s)
dpkg: warning: downgrading powershell from 6.0.0-rc.2-1.ubuntu.16.04 to 6.0.0-1.ubuntu.16.04
(Reading database ... 136521 files and directories currently installed.)
Preparing to unpack .../powershell_6.0.0-1.ubuntu.16.04_amd64.deb ...
Unpacking powershell (6.0.0-1.ubuntu.16.04) over (6.0.0-rc.2-1.ubuntu.16.04) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up powershell (6.0.0-1.ubuntu.16.04) ...

PowerShell v6.0.0

```

**Comment by rkeithhill** [comment]
Yup, see the same thing here.  Those instructions should include running `sudo apt-get update` before installing the GA version e.g.:
```bash
sudo apt remove powershell
sudo apt-get update
sudo apt install -y powershell
```

**Comment by rkeithhill** [comment]
BTW after I did the `sudo apt-get update` I was able to use just `sudo apt-get install -y powershell` and it pulled down the GA version.

**Comment by SteveL-MSFT** [comment]
This is caused by https://github.com/PowerShell/PowerShell/issues/5846, we are working with the owners of packages.microsoft.com to update their cache after we removed the pre-release versions since alphabetically 6.0.0-1 comes before 6.0.0-alpha, 6.0.0-beta, and 6.0.0-rc
