### ISSUE TITLE
PSCore6 - PowerShell Core landing page download links are wrong.

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#5851]
Under the "Get PowerShell' section all Download links are still pointing to RC2.  
I know this has been a recurring issue for some time but I got to post the issue.  

WorkAround
---------------
Get the downloads from the Release page: https://github.com/PowerShell/PowerShell/releases

:)

**Comment by SteveL-MSFT** [comment]
Looks like this is already fixed in our release branch, just need to merge it back to master

**Comment by SteveL-MSFT** [comment]
https://github.com/PowerShell/PowerShell/pull/5854 will fix this

**Comment by TravisEz13** [comment]
This was resolved when the 6.0.0 branch was merged to master.
https://github.com/PowerShell/PowerShell/commit/a08f3241a344220f64922584a562837f7600c6c7

**Comment by TravisEz13** [comment]
We always have a release issue open.  You can track our status on this using this issue:  https://github.com/PowerShell/PowerShell/issues/5833
