### ISSUE TITLE
We should start using caskroom-versions for prerelease mac packages

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#5855]
https://github.com/caskroom/homebrew-cask is supposed to be for released versions
Pre-release version of the formula should be here https://github.com/caskroom/homebrew-versions

**Comment by iSazonov** [comment]
Can we publish nightly builds? On MyGet?

**Comment by TravisEz13** [comment]
you could have a `powershell-preview` and a `powershell-nightly`, but it would require updating the formula nightly.  We would need someone to take that on.

**Comment by iSazonov** [comment]
If it is not automated for MacOs we could do this (publish nightly builds on MyGet) for Windows and Linux as .Net Core team do.

**Comment by TravisEz13** [comment]
`install-powershell.sh -daily` already does this.

**Comment by iSazonov** [comment]
Is it public? I can not find in https://powershell.myget.org/gallery/powershell-core

**Comment by TravisEz13** [comment]
https://powershell.myget.org/gallery/powershell-core-daily

**Comment by vors** [comment]
looks like this is done 🎉 https://github.com/Homebrew/homebrew-cask-versions/pull/5815
