### ISSUE TITLE
Add a more specific error message when PowerShell Remoting via SSH fails

### ISSUE THREAD

**Issue by janegilring** [PowerShell/PowerShell#5864]
Scenario: PowerShell Remoting via SSH from Windows to Linux.
After adding ssh.exe to the Path Env Variable, I hadn't restarted my PowerShell 6 console. Hence I got the below error message stating 'An error has occurred which PowerShell cannot handle. A remote session might have ended.'.

This isn't a very actionable error message. Would it be possible to check for basic prerequisites such as the precense of ssh.exe, and add such information to the error message?

Steps to reproduce
------------------

```powershell
$session = New-PSSession -HostName SRV1 -UserName myuser
```

Expected behavior
-----------------

```none
Return an error indicating what the underlying problem is.
```

Actual behavior
---------------

```none
PS C:\Program Files\PowerShell\6.0.0> $session = New-PSSession -HostName SRV1 -UserName myuser
New-PSSession : [SRV1] An error has occurred which PowerShell cannot handle. A remote session might have ended.
At line:1 char:12
+ $session = New-PSSession -HostName SRV1 -UserName myuser
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotingDataStructureException
+ FullyQualifiedErrorId : PSSessionOpenFailed
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0
PSEdition                      Core
GitCommitId                    v6.0.0
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by MaximoTrinidad** [comment]
Funny!!  That's old issue.  I had this problem a over a year ago.

This gets solved by using Chocolatey to install and upgrade OpenSSH application in Windows.
It will automatically update the Windows Environment variable.  

There's no need to add to the Env Path.

:)

**Comment by MaximoTrinidad** [comment]
@janegilring,

I forgot to mention, you can check the Github OpenSSH issues at https://github.com/PowerShell/Win32-OpenSSH 

This really is not a PowerShell Core issue.

Let me know how it went.
:)
