### ISSUE TITLE
All native Linux commandline applications is not available via PowerShell Remoting

### ISSUE THREAD

**Issue by janegilring** [PowerShell/PowerShell#5867]
Steps to reproduce
------------------
Log on to a Linux machine (I used CentOS 7) via SSH, open pwsh.exe and execute the following:
```powershell
Get-Command -CommandType Application | measure
```
Then execute the same command via a PowerShell Remoting session against the same machine.

Expected behavior
-----------------

```none
Count    : 1252

```

Actual behavior
---------------

```none
Count          : 810

```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0
PSEdition                      Core
GitCommitId                    v6.0.0
OS                             Linux 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

I accidentally discovered this when trying to run ifconfig via a PowerShell Remoting session, and got an error stating that the command does not exist.

**Comment by markekraus** [comment]
Can you review you PATH environment variable from your usual linux shell, from pwsh launched form your normal linux shell and from pwsh over ssh remoting?

**Comment by janegilring** [comment]
PATH via SSH                          
/opt/microsoft/powershell/6.0.0:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/myuser/.local/bin:/home/myuser/bin

PATH via PS Remoting
/opt/microsoft/powershell/6.0.0:/usr/local/bin:/usr/bin

**Comment by al-ign** [comment]
> I accidentally discovered this when trying to run ifconfig via a PowerShell Remoting session, and got an error stating that the command does not exist.

CentOS 7 does not include ifconfig by default.
And clearly - your paths are different in ssh and remoting.

**Comment by iSazonov** [comment]
@rjmholt Was the issue fixed with `-login` feature?

**Comment by janegilring** [comment]
FYI: I re-tested this on PowerShell 7.4.0 running on Ubuntu 22.04, and the issue seems to be resolved as I see the same paths and applications both locally and via remoting.

```
Get-Command -CommandType Application | measure
Count             : 3464

[192.168.1.20]: PS /home/jan> Get-Command -CommandType Application | measure
Count             : 3464
```
