### ISSUE TITLE
Is .NET Core (2.0.0) a prerequisite for powershell core?

### ISSUE THREAD

**Issue by TheNec** [PowerShell/PowerShell#5878]
I know that this may not be be right place but as I didn't find the answer somewhere else and I don't know where I could ask this elsewhere...

I know that "PowerShell Core is the edition of PowerShell built on top of .NET Core" so in my understanding I need/should install .NET Core (at least e.g. the runtimes from https://github.com/dotnet/core/releases) to (completely) use PowerShell Core. Why isn't this mentioned in the prerequisites section? Did someone forget it or am I wrong?

Thank you and best regards!

**Comment by iSazonov** [comment]
You do not need to specifically install .Net Core. Our distribution packages already contains all needed .Net Core files.

**Comment by bergmeister** [comment]
This is correct but whilst speaking about prerequisites I just wanted to add that there are 2 other small prerequisites that are needed for WinRM remoting to work on Windows:
https://github.com/PowerShell/PowerShell/blob/master/docs/installation/windows.md#prerequisites
