### ISSUE TITLE
Using the .NET IL Linker

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#5881]
In next development cycle we should try to use [`.NET IL Linker`](https://github.com/dotnet/announcements/issues/30) to reduce PowerShell Core distribution (not .Net Core!).
It can help to find dead code and other amazing things.
Also we should check the scenario when this tool will be used by other developers using PowerShell Core SDK.

**Comment by iSazonov** [comment]
My thoughts was about SMA and so not .Net Core.

**Comment by lzybkr** [comment]
I don't think we need additional build complexity to remove dead code from SMA, we should just delete that code.

Of course if a tool helps find that dead code, then cool. I'm sure the IL Linker is capable of helping, but other tools can as well, e.g. R#.

**Comment by iSazonov** [comment]
@markekraus @lzybkr Thanks! I updated the Issue.
