### ISSUE TITLE
Application hang while reading the powershell.Streams.Error

### ISSUE THREAD

**Issue by hongtao-chen** [PowerShell/PowerShell#5883]
This is a scenario while using the PowerShell core GA SDK.

In my C# wrapper library, the loop of powershell.Streams.Error hangs after it reads the first error.

For example, 

I start a PowerShell command "dir -s". it failed with an error "folder ABC access denied".

But when my C# library try to read the powershell.Streams.Error. it reads the first "access denied" and hangs there, cannot move forward, also does not fail.

foreach (var e in powershell.Streams.Error)
{
  if (e.Exception is RemoteException remoteException)
  {
    ReadRemoteException(remoteExcetpion);
  }
  else
  {
    ReadMessage(e.Exception.Message);
  }
}

**Comment by iSazonov** [comment]
@hongtao-chen Thanks for your report! Could you link a sample application on GitHub?

**Comment by hongtao-chen** [comment]
I found a workaround for this issue.
instead of
foreach (var e in powershell.Streams.Error)

I do
foreach (var e in powershell.Streams.Error**.ToArray()**)
