### ISSUE TITLE
Document powershell.config.json settings.

### ISSUE THREAD

**Issue by dantraMSFT** [PowerShell/PowerShell#5885]
Currently, there is no documentation about the format and usage of json file(s), what can be configured and the distinction between user and system-wide settings.

The document should call out what settings are valid in the user and system-wide files, their location, and a notation, for windows, what settings are overridden by group policy.

**Comment by SteveL-MSFT** [comment]
I think this issue should be in the PowerShell-Docs repo

**Comment by dantraMSFT** [comment]
I'll move it.
