### ISSUE TITLE
PowerShell 6.0.1-GA Release

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#5887]
From:  https://github.com/PowerShell/PowerShell/blob/master/docs/maintainers/releasing.md

- [x] Create a branch named `6.0.1` in `PowerShell/PowerShell` repository.
   All release related changes should happen in this branch.
- [x] Run tests on all supported Linux distros and publish results
- [x] Prepare packages
   - [x]  Build release packages
   - [x]  Sign the MSI packages and RPM package.
   - [x]  Install and verify the packages.
- [x]  Update documentation, scripts and Dockerfiles
   - [x]  Update [CHANGELOG.md](../../CHANGELOG.md) with the finalized change log draft.
   - [x]  Update other documents and scripts to use the new package names and links.
- [x]  Verify the release Dockerfiles.
- [x]  Create NuGet packages and publish them to `powershell-core` feed.
- [x]  Publish Linux packages to Microsoft YUM/APT repositories.
- [x]  Create the release tag and push the tag to `PowerShell/PowerShell` repository.
- [x]  Create the draft and publish the release in Github.
- [x]  Merge the `release` branch to `master` and delete the `release` branch.
- [x]  Trigger the release docker builds for Linux and Windows container images.
   - [x]  Linux: push a branch named `docker` to `powershell/powershell` repository to trigger the build at [powershell docker hub](https://hub.docker.com/r/microsoft/powershell/builds/).
     Delete the `docker` branch once the builds succeed.
   - [x]  Windows: queue a new build in `PowerShell Windows Docker Build` on VSTS.
- [x]  Verify the generated docker container images.

**Comment by bergmeister** [comment]
@TravisEz13 : Surely, the branch should be called `6.0.1` then? Can you please give details about why the patch is needed or is this due to versioning problem with package managers?

**Comment by TravisEz13** [comment]
There will be no code changes other than the version.  So, we are using the existing branch.  Yes, we are doing this release to address the issue with the package managers.

**Comment by TravisEz13** [comment]
Well, no product code changes.  One test had to be updated.

**Comment by TravisEz13** [comment]
We are considering taking PR #5903  as well.

**Comment by TravisEz13** [comment]
```
OS                          Total Pass Fail
--                          ----- ---- ----
CentOS Linux 7 (Core)        7629 6043   17
Debian GNU/Linux 8 (jessie)  7629 6060    1
Debian GNU/Linux 9 (stre...  7629 6060    1
openSUSE Leap 42.3           7629 6060    2
Red Hat Enterprise Linux     7629 6042   19
Ubuntu 14.04.5 LTS           7629 6060    1
Ubuntu 16.04.3 LTS           7629 6060    1
Ubuntu 17.04                 7629 6060    1
```

**Comment by TravisEz13** [comment]
Linux repos are being a bit slow.  Docker files are wait for the linux repos to have the package available.

**Comment by TravisEz13** [comment]
cask update merged
