### ISSUE TITLE
How do I install this on Server Core 1709?

### ISSUE THREAD

**Issue by TheCodeFiend** [PowerShell/PowerShell#5895]
I see an MSI and a ZIP file.  The MSI launches a GUI which Windows Server Core does not support.  Is there an installer that doesn't require a GUI, or are there manual installation instructions?

**Comment by iSazonov** [comment]
You can use silent msi installation (see `msiexec /?` options) or Zip distributive file.

**Comment by bergmeister** [comment]
Yes, just use the `/q` (quiet) option on msiexec. In cmd:
`msiexec /i Path/To/PowerShell-X.Y.Z.0-x64.msi /q`
Or in PowerShell:
` & Path/To/PowerShell-X.Y.Z.0-x64.msi /q`
This will install it in the background. See [this](https://kevinmarquette.github.io/2016-10-21-powershell-installing-msi-files/) blog post for more advanced scenarios if you want to block the shell until the installation has finished.
