### ISSUE TITLE
Question about System.Span

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/PowerShell#5897]
Is it possible to use this class with Powershell core ?
Today I get a System.InvalidProgramException : Common Language Runtime detected an invalid program.
```Powershell 
[System.Span[byte]]
# 
# IsPublic IsSerial Name                                     BaseType
# -------- -------- ----                                     --------
# True     False    Span`1                                   System.ValueType


[System.ReadOnlySpan[char]]
# 
# IsPublic IsSerial Name                                     BaseType
# -------- -------- ----                                     --------
# True     False    ReadOnlySpan`1                           System.ValueType

[byte[]]$Tb=1..5
$Result=[System.Span[byte]]::new($Tb)
# Common Language Runtime detected an invalid program.
# At line:1 char:1
# + $Result=[System.Span[byte]]::new($Tb)
# + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# + CategoryInfo          : OperationStopped: (:) [], InvalidProgramException
# + FullyQualifiedErrorId : System.InvalidProgramException

[char[]]$T=@('a','b','c','d')
[System.ReadOnlySpan[char]]::new($T)
# Common Language Runtime detected an invalid program.
# At line:1 char:1
# + [System.ReadOnlySpan[char]]::new($T)
# + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# + CategoryInfo          : OperationStopped: (:) [], InvalidProgramException
# + FullyQualifiedErrorId : System.InvalidProgramException

$psversiontable

Name                           Value
----                           -----
PSVersion                      6.0.0
PSEdition                      Core
GitCommitId                    v6.0.0
OS                             Microsoft Windows 6.1.7601 S
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
If System.Span is stack only based we can not use it in PowerShell Core scripts.

**Comment by iSazonov** [comment]
Perhaps we should generate a more friendly message instead "Common Language Runtime detected an invalid program."

@lzybkr @SteveL-MSFT

**Comment by LaurentDardenne** [comment]
According the [documentation](https://msdn.microsoft.com/en-us/library/system.invalidprogramexception(v=vs.110).aspx)
>The exception that is thrown when a program contains invalid Microsoft intermediate language (MSIL) or metadata. Generally this indicates a bug in the compiler that generated the program.

According to your answer this seems to be an impossibility under Powersehll core and not a bug.

**Comment by iSazonov** [comment]
My thought was that Span<T> is stack-only type and can not be allocated in Heap http://adamsitnik.com/Span/#no-heap
- in script we haven't a stack. This can be seen as PowerShell Core bug in the sense that we have to write a good error message.

**Comment by lzybkr** [comment]
`Span` is not usable from a PowerShell script. It is possible to support in some limited scenarios, but some things like `Get-Variable` couldn't work on a variable holding a `Span`.

That said, there is little advantage to using `Span` in PowerShell other than experimenting with it - if you care about performance (which is implied if you're using `Span`), then you should stick with C#.

As for a diagnostic - it's certainly possible to improve, but I might not bother.

I wouldn't want to disallow any use of `Span`, e.g. `[Span[Byte]].GetMembers()` or `[Span[Byte]] | Get-Member -Static` might still be useful to folks, and a nuanced error would be much harder to implement.

I suppose we could catch the `Invalid Program` exception and look for the use of `Span` - maybe that's not so bad.

**Comment by LaurentDardenne** [comment]
Thanks.

**Comment by iSazonov** [comment]
I think this question will arise again and again - we could make the Jason's comment in the documentation.
