### ISSUE TITLE
Why script extesion is stille *.ps1 for PS Core 6?

### ISSUE THREAD

**Issue by dronkoff** [PowerShell/PowerShell#5904]
10 year ago we said that an extension will change in case of major changes.
https://blogs.msdn.microsoft.com/powershell/2007/11/02/ctp-versioning/
"_PowerShell Scripts continue to use “.PS1”. We will continue to pursue this approach until there is a major change in the CLR or .NET frameworks which force us to go side-by-side. It is at that point that we’ll go from .PS1 to .PS2_"
Looks like Core release is this change. Especially taking into account that PS Core 6 is not fully compatible with previous versions and not all existent *.ps1 scripts will successfully run on PS Core.
What is the reason why we didn't change the extension?

**Comment by iSazonov** [comment]
.PS2 implies a complete lack of backward compatibility, but PowerShell Core was created in the thought of maximum backward compatibility. Therefore, there is no need for .PS2 - we can execute .PS1 scripts in PowerShell Core.
From your link:
>Until then we will stay with .PS1 and everything that runs today will continue to run in new releases.

**Comment by dronkoff** [comment]
> everything that runs today will continue to run in new releases
It's ironic that the first simple script I tried to run on PS Core 6 failed. It uses [adsi] type accelerator. There are tons of WMI scripts that are still in use even by MS tools, they will fail. Of course they can be rewritten to CIM cmdlets, but it will require some work to do. I don't know much people who use Workflows, but met some customers who really do. So we can not talk about full backward compatibility and that's why I'm asking. 
Nevertheless, thanks for the answer, I got the message - same extension because almost fully compatible an some breaking changes are not taken into account.

**Comment by iSazonov** [comment]
@dronkoff That's another question. Yes, we only ported 40% of the cmdlets on Linux and 60% on Windows. Many limitations are related to the fact that not all interfaces are ported in .Net Core. We will be glad to your help and contributions.

**Comment by dronkoff** [comment]
Sounds like a job offer :))

**Comment by iSazonov** [comment]
It is a wonderful project for soul and mind. :)
And MSFT experts always do great contributions!

**Comment by bergmeister** [comment]
I agree as well with @iSazonov. Although the cmdlet support is only a subset at the moment, it is expected that the gap becomes smaller and smaller until eventually PowerShell 6 will take over in a few years.

**Comment by al-ign** [comment]
> It's ironic that the first simple script I tried to run on PS Core 6 failed. It uses [adsi] type accelerator.

Please, do not confuse script and functionality - your _script_ worked, ahem, 'flawlessly', it just called unsupported, on this specific machine, interface.
If you call some Exchange 2007 scripts on fresh Windows 10 Home machine - the scripts will work fine, but, of course, they will do nothing, because there would be no modules/cmdlets to work with Exchange 2007. I don't think you will blame Win10 PowerShell for failing in this scenario.
