### ISSUE TITLE
Service 'TokenBroker (TokenBroker)' cannot be queried due to the following error

### ISSUE THREAD

**Issue by dfinke** [PowerShell/PowerShell#5916]
![image](https://user-images.githubusercontent.com/67258/34967866-ae905680-fa33-11e7-89db-bb70bea02446.png)

**Comment by markekraus** [comment]
Hmm  I cannot reproduce this. It doesn't fail in `pwsh`, `pwsh` as administrator, `powershell` then `pwsh`, nor `powershell` as administrator the `pwsh`.

**Comment by kvprasoon** [comment]
No repro for me too...

![image](https://user-images.githubusercontent.com/12897753/34970194-d4e918bc-fa6a-11e7-8cb2-c023aa006036.png)

```
Name                           Value
----                           -----
PSVersion                      6.0.0
PSEdition                      Core
GitCommitId                    v6.0.0
OS                             Microsoft Windows 10.0.10586
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by dfinke** [comment]
I've tried it on another Windows 10 machine and could not repro

**Comment by kvprasoon** [comment]
Will it have any relation with OS Build version ? 15063
