### ISSUE TITLE
Powershell scripts are not recognised as a 'Program' for 'Open with' screen. Only .cmd, and .bat are.

### ISSUE THREAD

**Issue by mikemaccana** [PowerShell/PowerShell#5928]
Windows 10, build 6.2.9200.0.

Try and associate a file type with a Powershell script.

Right click a file, pick 'Open With'.  `.bat` and `.cmd` files are included as 'Programs'. `ps1` is not.

![image](https://user-images.githubusercontent.com/172594/35052408-68f4def8-fb9f-11e7-9d78-bd02ca47cbec.png)

**Comment by kvprasoon** [comment]
@mikemaccana PowerShell were never included in the open with list in windows and PowerShell core has nothing to do with this. You could probably give feedback via User voice for Windows [https://wpdev.uservoice.com/forums/110705-universal-windows-platform](url)

**Comment by mikemaccana** [comment]
> PowerShell were never included in the open with list in windows 

I know, hence creating this bug.

> You could probably give feedback via User voice for Windows 

I would have thought so too, but [Steve Lee from Microsoft just asked me to file it here](You could probably give feedback via User voice for Windows )

**Comment by kvprasoon** [comment]
@mikemaccana Ok!

**Comment by iSazonov** [comment]
Close as stale issue. Feel free to continue discussion.

**Comment by mikemaccana** [comment]
@iSazonov still occurs in Windows 10 build 210108. What should I do to get it fixed?

**Comment by iSazonov** [comment]
@mikemaccana I guess it is Windows _security_ design. You will also not find VBS on this list. You could discuss this in a more appropriate security forum. (I'm not even sure if this can be configured.)
