### ISSUE TITLE
Mac installer was signed in RC, no longer signed for Final release?

### ISSUE THREAD

**Issue by jackfruh** [PowerShell/PowerShell#5939]
The mac installer is no longer code signed, I believe the last RC (RC2) was signed.

if it's not signed then mac users get an security stop message and can't install.

Savvy users may know the "right click->Open" trick, but from a security perspective, they shouldn't have to and should be able to trace the origins of the installer back to this distribution point.

**Comment by thezim** [comment]
Agreed, it is not signed.

## RC2

```bash
pkgutil --check-signature ~/Downloads/powershell-6.0.0-rc.2-osx.10.12-x64.pkg 
Package "powershell-6.0.0-rc.2-osx.10.12-x64.pkg":
   Status: signed by a certificate trusted by Mac OS X
   Certificate Chain:
    1. Developer ID Installer: Microsoft Corporation (UBF8T346G9)
       SHA1 fingerprint: 9B 6B 91 3B B1 3F 68 26 12 20 EC 72 11 F0 F2 0E 92 E4 B1 EB
       -----------------------------------------------------------------------------
    2. Developer ID Certification Authority
       SHA1 fingerprint: 3B 16 6C 3B 7D C4 B7 51 C9 FE 2A FA B9 13 56 41 E3 88 E1 86
       -----------------------------------------------------------------------------
    3. Apple Root CA
       SHA1 fingerprint: 61 1E 5B 66 2C 59 3A 08 FF 58 D1 4A E2 24 52 D1 98 DF 6C 60
```

## Current
```bash
pkgutil --check-signature ~/Downloads/powershell-6.0.0-osx.10.12-x64.pkg
Package "powershell-6.0.0-osx.10.12-x64.pkg":
   Status: no signature
```

**Comment by TravisEz13** [comment]
I verified it was signed.  perhaps the unsigned artifact was picked up from the build.

**Comment by TravisEz13** [comment]
I discussed it with @daxian-dbw there was confusion.  The signing process for mac is complex and we picked up the unsigned file.  I'll replace it with the signed file.

**Comment by TravisEz13** [comment]
The release has been updated.  A note about the old hash has been added as well.

**Comment by thezim** [comment]
@TravisEz13 are there any post build/packaging tests?

**Comment by TravisEz13** [comment]
Not for mac, the build wasn't even fully automated until after `6.0.0`. This was some confusion among the maintainers.  Please file an issue.  I think all the package verification tests need to add signing verification.

**Comment by iSazonov** [comment]
I think we could add this in #3942

**Comment by TravisEz13** [comment]
I think this a new issue would be good.  That issue is already overloaded.
