### ISSUE TITLE
New-PSSession from MacOS to Windows Server 2016 running Win32-OpenSSH, using SSH password authentication

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#5943]
## Reproduction Step

```
$cred = Get-Credential -Credential .\AdminUsername # Type password interactively
Enter-PSSession -ComputerName x.x.x.x -Credential $cred -SSHTransport
```

## Expected Result 

Command successfully creates PowerShell Remoting session, using password authentication.

## Actual Result

Command fails due to invalid parameter set.

```
Enter-PSSession : Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
```

How do I correctly create a PowerShell Remoting (PSRP) session to Win32-OpenSSH using password authentication?

**Comment by bergmeister** [comment]
Please read the docs. You have to use the -HostName parameter and -Credential is not supported for OpenSSH based remoting.

**Comment by SteveL-MSFT** [comment]
We currently don't support -Credential w/ SSHTransport.  We recommend using public key auth or keyboard-interactive.  It's not trivial to have -Credential work with keyboard-interactive and there are currently no plans to support this.
