### ISSUE TITLE
pwsh -? missing docs for -sshs parameter

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#5944]
It seems there's an `-sshs` parameter on the PowerShell Core binary, to enable it to work as a SSHD subsystem. However, this is mentioned nowhere when you run `pwsh -?`. This needs to be added.

**Comment by pcgeek86** [comment]
https://docs.microsoft.com/en-us/powershell/scripting/core-powershell/ssh-remoting-in-powershell-core

**Comment by iSazonov** [comment]
It is temporary parameter for remoting. We use it only internally.

**Comment by daxian-dbw** [comment]
The flags for server modes are not exposed today. You can find a few [others](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs#L552) in the code.
/cc @SteveL-MSFT @PaulHigin, shall we document the server modes flags?

**Comment by iSazonov** [comment]
If only in developer docs not user docs.

**Comment by SteveL-MSFT** [comment]
In general, I think we don't want to document server modes as they are not intended for end user use.  In the case of `-sshs` which is explicitly put into `sshd_config`, I think we should replace the need for that switch and instead check if the parent process is `sshd`.  We may need to keep `-sshs` as no-op for compat reasons.

**Comment by iSazonov** [comment]
@SteveL-MSFT Could you please open new Issue to remove `-sshs`?

**Comment by PaulHigin** [comment]
>> ... I think we should replace the need for that switch and instead check if the parent process is sshd...
This feels contrived to me, and will make it impossible to implement an alternative hosting model in the future (which we will need to do if we want to support endpoint configuration).  I prefer the current method of explicitly specifying the desired server mode via command line switch.

**Comment by SteveL-MSFT** [comment]
@PaulHigin if we have a different host in the future, calling it `-sshs` may not make sense.  We can also apply the same logic in that case to use a `server mode` if the parent process is that host.

@iSazonov created https://github.com/PowerShell/PowerShell/issues/5985

**Comment by PaulHigin** [comment]
@SteveL-MSFT  It will still be an SSH transport, but just not hosted directly by SSH parent process.  I feel that trying to divine the transport type by checking parent process will be error prone.

**Comment by iSazonov** [comment]
[My comment](https://github.com/PowerShell/PowerShell/issues/5985#issuecomment-359664112) from #5985 
> Can we run pwsh as demon, i.e. sshd from pwsh? It can help if we'll need set config name/file.
 Also I wonder why OpenSSH is not library?

**Comment by SteveL-MSFT** [comment]
Perhaps we can support both sshd detection and `-sshs`.  Currently, I think it's difficult to discover for someone trying to configure PSRP SSH.

**Comment by PaulHigin** [comment]
Users shouldn't have to manually set up PowerShell SSH remoting and should not need to know about -sshs switch.  Enable-SSHRemoting should set up remoting an any platform and verify connection.  I have been working on a prototype but haven't had time recently to continue the effort.  But ideally this would be used for set up and diagnosis.

**Comment by SteveL-MSFT** [comment]
I suppose with Enable-SSHRemoting, this becomes less of an issue for configuration, but then we have to go back to documenting this switch properly.

**Comment by iSazonov** [comment]
I remember that WS-Management was specifically installed on a separate port. This is important for network security. Maybe it also matters here.
In that case we could fork sshd out of Powershell - `pwsh -sshd <config>`
