### ISSUE TITLE
New-PSSession error "subsystem request failed on channel 0" when using SSH key authentication

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#5945]
## Reproduction Steps

```
New-PSSession -SSHTransport -UserName SpockAdmin -KeyFilePath /Users/tsulli/Spocks_Private_Key.pem -HostName x.x.x.x
```

## Symptom
> New-PSSession : [x.x.x.x] The background process reported an error with the following message: The SSH client session has ended with error message: subsystem request failed on channel 0.

**NOTE**: I'm able to successfully SSH into the system using the `ssh` command line client from Mac.

### Fix

Make sure your `sshd_config` contains the `Subsystem` configuration as documented in the following article: 
https://docs.microsoft.com/en-us/powershell/scripting/core-powershell/ssh-remoting-in-powershell-core

After modifying the `sshd_config`, you also need to restart the SSH daemon on your Windows instance: `Restart-Service -Name sshd`.

Closing immediately, as I found the fix. This is being posted purely for community documentation purposes, so others can benefit from my learnings.

**Comment by RangaSamdurala** [comment]
sshd_config is located in %ProgramData%\ssh AND NOT where OpenSSH is installed.

**Comment by ulibte** [comment]
Subsystem	powershell pwsh.exe -sshs -NoLogo -NoProfile

**Comment by cawoodm** [comment]
Borken Link:

https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-7.1
