### ISSUE TITLE
Unable to add modules to Linux Powershell 

### ISSUE THREAD

**Issue by nucleuspoc** [PowerShell/PowerShell#5948]
Hello, 
This isn't a bug, more asking for advice. I am currently trying to install modules onto my Powershell instance installed on my Linux machine. I installed it all ok, log into Powershellusing 'pwsh' and tried to add a module however it doesn't seem to want to be added. 
Module: ```Save-Module -Name HPOneView.400 -Path /opt/microsoft/powershell/6.0.0 ```
which states: “command was found in the module '<ModuleName>', but the module could not be loaded"

Can this be done via a Linux instance or can I only add modules in a Windows instance of Powershell?

Thank you in advance

**Comment by MaximoTrinidad** [comment]
Just curious!  Have you tried to save the module to the /home/user folder?
I wonder it it works.

:)

**Comment by MaximoTrinidad** [comment]
I have done a test using Windows 10 Ubuntu and seems to work when using 'Import-Module' from the  User home folder.  

You may want to try using "sudo pwsh" and then do the "Save-Module" as you're saving to a protected area.

:)

**Comment by MaximoTrinidad** [comment]
Ah! Check the PSModulePath variable:
```
$Env:PSModulePath
/home/maxt/.local/share/powershell/Modules:/usr/local/share/powershell/Modules:/opt/microsoft/powershell/6.0.0/Modules
```
You'll probably need to save it under "/opt/microsoft/powershell/6.0.0/Modules" and not "/opt/microsoft/powershell/6.0.0".

Or, add the module folder to the $Env:PSModulePath.  This may fix the issue.

:)

**Comment by daxian-dbw** [comment]
> which states: “command was found in the module '', but the module could not be loaded"

@nucleuspoc Did you see this when running `Save-Module` or when running a function from the module you saved? If it's the former, it seems indicating the module `PowerShellGet` cannot be auto-loaded. Can you run "Import-Module PowerShellGet" and see what error you get?

**Comment by MaximoTrinidad** [comment]
@nucleuspoc,

So I went overboard on this issue.  So, check the help documentation at: https://docs.microsoft.com/en-us/powershell/module/PowershellGet/Save-Module?view=powershell-6

You're missing the '-LiteralPath' parameter. I was able to save the module to a Linux folder.

Correct oneliner: (Example)
Save-Module -LiteralPath "/home/maxt/MyModules" -Name "HPOneView.400"    

![savemodule_01_2018-01-19_14-00-04](https://user-images.githubusercontent.com/19892435/35166796-1a592dde-fd21-11e7-9be8-84eed8d8ca3f.jpg)

**Comment by MaximoTrinidad** [comment]
Word of Caution! I check for the "Linux" tag for this module "HPOneView.400". But doesn't have Linux.  
So, although it's save on my Linux module folder, it doesn't guarantee that will work. 

Only you can test this module in Linux. If it doesn't work then its a Windows only module.
:)

**Comment by JohnAZoidberg** [comment]
The new version 500 supports Linux (Powershell Core): https://www.powershellgallery.com/packages/HPOneView.500
