### ISSUE TITLE
Disable StrictHostKeyChecking in New-PSSession command

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#5949]
I have an automation script that creates many SSH-based PowerShell Remoting sessions, from MacOS to Windows, using key-based authentication, with the `New-PSSession` command. However, when I run this script, I constantly get prompted to add the host key fingerprint to my `known_hosts` file.

Is there a way to temporarily skip / bypass this check?

```
The authenticity of host 'x.x.x.x (x.x.x.x)' can't be established.
ECDSA key fingerprint is SHA256:h976+qzJTEsnDaweawhyCBkOYaBSxhwaljhsqomwg048i7yc.
Are you sure you want to continue connecting (yes/no)?
```

https://serverfault.com/questions/132970/can-i-automatically-add-a-new-host-to-known-hosts

**Comment by daxian-dbw** [comment]
@PaulHigin Any ideas?

**Comment by SteveL-MSFT** [comment]
Perhaps what we really want is a way to passthru switches to ssh.exe

**Comment by PaulHigin** [comment]
This is part of SSH security and is not something we can affect, and certainly not something we would want to bypass.  SSH has no way to verify a host before initiating a user key validation the way it can be done via Kerberos (although I believe there is current work to add Kerberos authentication to SSH), so the user must provide the validation.  

If you don't want to do this via New-PSSession, you can use ssh.exe to first establish a connection to a known/trusted host.  This only happens once and the host/key is added to the cache, and afterwards you are no longer required to validate the host.

**Comment by SteveL-MSFT** [comment]
It seems that using `ssh-keyscan -H hostname` and redirecting the output to known_hosts is better than providing a switch to bypass the check which opens the user up to man-in-the-middle attacks.

**Comment by steve-kurtz-google** [comment]
> This is part of SSH security and is not something we can affect, and certainly not something we would want to bypass. SSH has no way to verify a host before initiating a user key validation the way it can be done via Kerberos (although I believe there is current work to add Kerberos authentication to SSH), so the user must provide the validation.
> 
> If you don't want to do this via New-PSSession, you can use ssh.exe to first establish a connection to a known/trusted host. This only happens once and the host/key is added to the cache, and afterwards you are no longer required to validate the host.

Can you elaborate on this? Are you suggesting to connect with ssh first and then use the enter-pssession? How would you pass the session from the start-process ssh [...] to enter-pssession?

**Comment by PaulHigin** [comment]
No, it would be two steps.  The first connection attempt with ssh.exe will prompt for the fingerprint confirmation, and the connection can be allowed.  Then any other connection with Enter-PSSession or New-PSSession will not prompt, since the first response is stored.  This just prevents a prompt from occurring later within an automated script, where user interaction is undesirable.

**Comment by steve-kurtz-google** [comment]
I am connecting to a non-standard SSH endpoint that the pssession cmdlets do not seem to be compliant with. Openssh works great, so I was trying to find a way of accessing openssh std-in / std-out. Apparently openssh does not expose these.

**Comment by CarlosAugustoDeSouzaJunior** [comment]
In ssh client we have the option, why we cannot pass the switch '-o StrictHostKeyChecking=no', in the command.
