### ISSUE TITLE
Input to function incorrectly reported as null for `% p` but not `% {$_.p}`

### ISSUE THREAD

**Issue by alx9r** [PowerShell/PowerShell#5953]
Steps to reproduce
------------------

```powershell
function f
{
    param([Parameter(ValueFromPipeline)]$x)
    process {$x}
}

function g {
    param(
        [Parameter(ValueFromPipeline)] $InputObject,
        [switch] $UseScriptblock
    )
    process { 1 | a -UseScriptblock:$UseScriptblock | b }
}

function a {
    param (
        [Parameter(ValueFromPipeline,Mandatory)] $InputObject,
        [switch] $UseScriptblock
    )
    process {
        if ( $UseScriptblock )
        {
            [pscustomobject]@{p=1} | % {$_.p} # <= shouldn't this...
        }
        else
        {
            [pscustomobject]@{p=1} | % p      # <= ...produce the same result as this?
        }
    }
}

function b
{
    param
    (
        [Parameter(ValueFromPipeline,Mandatory)]
        $InputObject
    )
    process
    {
        throw 'function b'
    }
}

1 | f | g 
1 | f | g -UseScriptblock
```

Expected behavior
-----------------

```none
function b
At C:\users\un1\Desktop\test.ps1:41 char:9
+         throw 'function b'
+         ~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (function b:String) [], RuntimeExcep
tion
+ FullyQualifiedErrorId : function b
function b
At C:\users\un1\Desktop\test.ps1:41 char:9
+         throw 'function b'
+         ~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (function b:String) [], RuntimeExcep
tion
+ FullyQualifiedErrorId : function b
```

Actual behavior
---------------

```none
b : Cannot bind argument to parameter 'InputObject' because it is null.
At C:\users\un1\Desktop\test.ps1:12 char:55
+     process { 1 | a -UseScriptblock:$UseScriptblock | b }
+                                                       ~
+ CategoryInfo          : InvalidData: (:) [b], ParameterBindingValidationExcept
ion
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,b

function b
At C:\users\un1\Desktop\test.ps1:41 char:9
+         throw 'function b'
+         ~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (function b:String) [], RuntimeExcep
tion
+ FullyQualifiedErrorId : function b
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value                                            
----                           -----                                            
PSVersion                      6.0.0                                            
PSEdition                      Core                                             
GitCommitId                    v6.0.0                                           
OS                             Microsoft Windows 6.3.9600                       
Platform                       Win32NT                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                          
PSRemotingProtocolVersion      2.3                                              
SerializationVersion           1.1.0.1                                          
WSManStackVersion              3.0                                              
```

**Comment by alx9r** [comment]
@iSazonov I see you have tagged this with "Issue-Question".  I'm not sure exactly what the PowerShell team's definition of "Question" and "Bug" is, but I consider this more of a bug than a question.  

If you need convincing, watch the control flow, `$InputObject`, and `$Error` through the first run through the `throw` statement.  Control flow enters function `b`, `$InputObject` is `1` and the exception is thrown.  However, instead of just one error record, two result:

1. a complaint that the input to `b` was `$null`, and
2. the exception from the line `throw 'function b'`

This seems almost consistent with a spurious null being output by `% p` prior to `1`.  

I don't think that is the whole story, however.  If the problem were merely a spurious null, a terminating error would have occurred when parameter binding for function `b` failed for the null, binding `1` would not even be attempted, and control flow would not have entered function `b`.  That is the behavior when `% {$_.p}` is replaced with `% {$null,$_.p}`, for example.

**Comment by alx9r** [comment]
Here is a more succinct repro of the same problem:

```PowerShell
function z {
    process {
        try { 1 }
        catch { Write-Host 'caught upstream' }
    }
}

function a {
    param ([Parameter(ValueFromPipeline,Mandatory)] $InputObject)
    process {
        [pscustomobject]@{p=1} | % p
    }
}

function b {
    param ([Parameter(ValueFromPipeline,Mandatory)] $InputObject)
    process {
        Write-Host "InputObject $InputObject"
        throw 'function b'
    }
}

$ErrorActionPreference = 'Stop'
z | a | b
```

### Expected Behavior
The exception thrown by `b` is caught in `z`.

```none
InputObject 1
caught upstream
```

### Actual Behavior
The entire pipeline is terminated when `throw` is reached.

```none
InputObject 1
b : Cannot bind argument to parameter 'InputObject' because it is null.
At C:\users\un1\Desktop\test3.ps1:17 char:9
+ 1 | a | b
+         ~
    + CategoryInfo          : InvalidData: (:) [b], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,b
```

**Comment by iSazonov** [comment]
@alx9r  Don't worry about the label. I daresay to qualify an issue as a bug only in obvious (for me) cases. You made a wonderful reproduction, so label is `question`. Without it I would put `discussion` to get more opinions. Now we only need MSFT expert conclusion. Only experts can give the exact conclusion that it is a bug, that it is necessary to fix or leave as is. Then we will change the label to `bug`, `enhance` or `won't fix`.

/cc @SteveL-MSFT I think we need to provide the community with a better understanding of the Issue process - can we update our documents?

**Comment by alx9r** [comment]
I'm not sure if this is related.  There seems also to be a spurious null appearing from a member of `[pscustomobject]` in #5607.

**Comment by SteveL-MSFT** [comment]
@iSazonov I think the current [docs](https://github.com/PowerShell/PowerShell/blob/master/docs/maintainers/issue-management.md) make it clear what the issue types mean which in this case if it's not clear if a bug, it seems it should be `Discussion` if it's not clear if a bug or not.

cc @daxian-dbw to help with clarity if this behavior is expected

**Comment by alx9r** [comment]
It seems that this is somehow related to the exception mechanism.  Removing the `throw` statement from [this repro](https://github.com/PowerShell/PowerShell/issues/5953#issuecomment-359118341) averts the spurious null.
