### ISSUE TITLE
Tab-Completion tests leveraging PackageManagement consistently fail.

### ISSUE THREAD

**Issue by dantraMSFT** [PowerShell/PowerShell#5958]
Steps to reproduce
------------------

Start-PSBuild -Clean -PSModuleRestore
Start-PSPester

Expected behavior
-----------------
All tests pass.

Actual behavior
---------------
three tab completion tests fail due to the missing PackageManagement module

'gmo -list PackageM'
'gcm -Module PackageManagement Find-Pac'
'ipmo PackageM'

When running the built pwsh, PackageManagement is not available.

Environment data
----------------
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0
PSEdition                      Core
GitCommitId                    v6.0.0-128-gf587fd06d6046859ca1a9fe3470d5f9615dc5e01
OS                             Microsoft Windows 10.0.17080
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by ThomasNieto** [comment]
@TravisEz13 is this still an issue?
