### ISSUE TITLE
Get-FileHash tests consistently failing on Server 2016

### ISSUE THREAD

**Issue by dantraMSFT** [PowerShell/PowerShell#5960]
Steps to reproduce
------------------

Build current sources and run Start-PSPester, no parameters

Expected behavior
-----------------

All Tests pass.

Actual behavior
---------------
Each test Get-FileHash.Tests.ps1 that is comparing against an expected hash is failing with a mismatched hash value.

Note that this mismatch is not a case-sensitivity failure; while the string lengths match for each algorithm, the the hash values are completely different.

Environment data
----------------
Running on server datacenter 2016

$PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0
PSEdition                      Core
GitCommitId                    v6.0.0-128-gf587fd06d6046859ca1a9fe3470d5f9615dc5e01
OS                             Microsoft Windows 10.0.17080
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by rjmholt** [comment]
@dantraMSFT Does #6430 fix this?
