### ISSUE TITLE
PowerShell Core 6 GA hangs after setting the execution policy for the current user

### ISSUE THREAD

**Issue by alexandair** [PowerShell/PowerShell#5969]
Steps to reproduce
------------------

```powershell
# open PowerShell Core 6.0 and run
Set-ExecutionPolicy restricted -Scope CurrentUser

# close the console

# open PowerShell Core 6.0 again
# you get an error message and console hangs
```

Expected behavior
-----------------

```none
The user should be able to start new PowerShell Core 6.0 session without a problem.
```

Actual behavior
---------------

```powershell
# when I start PowerShell Core 6.0 after setting the execution policy for the current user, I get:
PowerShell v6.0.0
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

The shell cannot be started. A failure occurred during initialization:
The static PrimaryRunspace property can only be set once, and has already been set.

```
If I delete powershell.config.json file in c:\Users\USERNAME\Documents\PowerShell, I'm able to start PowerShell Core 6.0 again.

Environment data
----------------

```powershell
PS C:\Program Files\PowerShell\6.0.0> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0
PSEdition                      Core
GitCommitId                    v6.0.0
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by Jaykul** [comment]
I see the same thing

**Comment by markekraus** [comment]
Hmm.. if I remove the PSReadline module I am able to start `pwsh` with the restricted scope.  I'm not familiar with this area of code, but maybe it's realated to code in 

https://github.com/PowerShell/PowerShell/blob/beffdcf94d00b51d9339bb26dbc0e477cd147c92/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs#L1568

where it makes multiple calls to `OpenConsoleRunspace()` doing stuff the PSReadline. I'm using the 2.0.0-beta1 version of PSReadLine if that makes any difference. *shrugs

If i reinstall the PSReadline module then the console fails to open.

**Comment by guitarrapc** [comment]
I repoduced the issue. Any update with?

**Comment by ternag** [comment]
This is still an issue in version 6.0.2

**Comment by Cheetah85** [comment]
Unfortunately yes. It is still an issue.

`PS C:\Program Files\PowerShell\6.0.2> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


PS C:\Program Files\PowerShell\6.0.2> Set-ExecutionPolicy Restricted -Scope CurrentUser
PS C:\Program Files\PowerShell\6.0.2> exit

Restart:

PowerShell v6.0.2
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

The shell cannot be started. A failure occurred during initialization:
The static PrimaryRunspace property can only be set once, and has already been set.
`
