### ISSUE TITLE
DarkYellow color not correctly displayed with write-host

### ISSUE THREAD

**Issue by agaace** [PowerShell/PowerShell#5971]
Steps to reproduce
------------------

```powershell
write-host hello -foreground "DarkYellow"
```

Expected behavior
-----------------

```none
hello (displayed in dark yellow/ochre color)
```

Actual behavior
---------------

```none
hello (displayed in default color)
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.98
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.98
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by bergmeister** [comment]
Does not repro for `6.0.0`
Also, the issue template clearly states :

> For Windows PowerShell 5.1 issues, suggestions, or feature requests please use the following link instead:
>  - Windows PowerShell [UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)

I cannot speak for MSFT but I have heard from multiple people, including Jeffrey Snover, that MSFT will backport only certain important fixes/features to Windows PowerShell.

**Comment by stknohg** [comment]
It isdup #2210 , and this behavior is by design.
