### ISSUE TITLE
license terms

### ISSUE THREAD

**Issue by simevo** [PowerShell/PowerShell#5976]
Hi, while pwsh itself is MIT-licensed, it "_ALSO CONTAINS THIRD PARTY AND OTHER PROPRIETARY SOFTWARE THAT ARE GOVERNED BY SEPARATE LICENSE TERMS_".

Looking at this file:
https://github.com/PowerShell/PowerShell/blob/master/license_thirdparty_proprietary.txt#L417
it would seem that pwsh "INCLUDES" .NET, which has quite a lot of limitations.

But I understand that pwsh 6.0 can be "linked" with .NET Core which is also MIT licensed !

Can you please clarify / simplify the license terms ?

This could be a showstopper for pwsh diffusion on open source OSs:
https://bugs.debian.org/834756#16

**Comment by iSazonov** [comment]
@simevo Thanks for your question! We already have #5869

**Comment by simevo** [comment]
closing as duplicate, thanks
