### ISSUE TITLE
MSI installer run RegisterManifest.ps1 and Enable-PSRemoting

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#5979]
Users may not be aware that they need to run RegisterManifest.ps1 to get logging and Enable-PSRemoting to have a PSCore6 remoting endpoint.  The MSI installer should have two checkboxes: register eventing manifest (checked by default), register powershell remoting (unchecked by default) along with appropriate MSI options for quiet installs.

**Comment by bergmeister** [comment]
@SteveL-MSFT Would you consider taking in the followign Wix extension as a Nuget package to simplify the WiX code since WiX has not built in support for powershell? https://github.com/flcdrg/PowerShellWixExtension

**Comment by bergmeister** [comment]
@SteveL-MSFT I'll tackle this if you don't mind. I already have a dummy prototype working that executes a psscript as an admin but will be busier for the rest of this week, so I guess you can expect a PR in February of that's OK?
Have a think about the UI aspect please in the meantime and the preferred name for the MSI properties. I suggest putting it together with the existing custom dialog:
![image](https://user-images.githubusercontent.com/9250262/35248128-dff40bc2-ffc4-11e7-904f-c6774486a195.png)

**Comment by SteveL-MSFT** [comment]
@bergmeister consider it yours!  Thanks!

No rush as 6.1.0 previews will come out on a regular cadence.  If it doesn't make Preview1, no problem!

I think putting it in the `Optional Features` in your mockup seems fine.  Suggest some wording changes:

- Register Windows Event Logging Manifest
- Enable PowerShell Core remoting

cc @joeyaiello for wording suggestions

**Comment by alexverboon** [comment]
From an Enterprise Management and Security point of view , I would like to see that the owerShell ETW manifest is registered by default. Is there a reason to not do so?

**Comment by SteveL-MSFT** [comment]
@alexverboon I believe the current design is that the ETW manifest is registered by default (option is checked).
