### ISSUE TITLE
ConvertFrom-Base64, ConvertTo-Base64

### ISSUE THREAD

**Issue by felixfbecker** [PowerShell/PowerShell#5982]
Currently to decode/encode Base64 we have to call into cumbersome .NET APIs:

```powershell
[System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('aGVsbG8gd29ybGQK'))
```

Base64 is needed in a lot of cases. For example, getting a secret value out of `kubectl` is incredibly cumbersome:

```powershell
[System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String((kubectl get secret database -o json | ConvertFrom-Json).data.username))
```

It would be great if we could just do this:

```powershell
(kubectl get secret database -o json | ConvertFrom-Json).data.username | ConvertFrom-Base64
```

This is something that is available on every Unix shell with the `base64` utility (which can be piped into).

There is a Base64 module on PSGallery, but given this is available in .NET and Unix shells imo it should be exposed as a convenient PS cmdlet, so it is available in all installations and reliable.

For example, the Base64 module on PSGallery always uses UTF16 so the above example just results in mangled characters. A core implementation should support the standard `-Encoding` parameter etc.

This is unlikely to create a maintenance burden because it just calls into .NET and the Base64 spec will not change.

**Comment by rkeithhill** [comment]
Agreed.  We've had these commands in PSCX for years (~11 years).  This one would probably be an easy "up-for-grabs" set of commands to tackle.  See:

https://github.com/Pscx/Pscx/blob/master/Src/Pscx/Commands/Text/ConvertToBase64Command.cs
https://github.com/Pscx/Pscx/blob/master/Src/Pscx/Commands/Text/ConvertFromBase64Command.cs

**Comment by felixfbecker** [comment]
@rkeithhill does PSCX support PS Core (mac/Linux)?

**Comment by rkeithhill** [comment]
No, not yet.  I've been so busy contributing to every one else's OSS project (PowerShell, PSES, posh-git, psake) that I've been neglecting my own.  :-(  Must carve out some time to start moving the useful stuff over.  There is a lot that can be left out now that PowerShell has implemented more and more of the functionality in PSCX with built-in commands and PSGallery modules.

**Comment by chriskuech** [comment]
What would an approved interface for this cmdlet look like?

**Comment by iSazonov** [comment]
I close this as dup #8620
