### ISSUE TITLE
Resizing window under macOS overrides text

### ISSUE THREAD

**Issue by felixfbecker** [PowerShell/PowerShell#5983]
PowerShell 6.0.0 on macOS

![2018-01-22 11 39 00 am](https://user-images.githubusercontent.com/10532611/35240634-ef033324-ff68-11e7-8a0e-a82365cb1b34.gif)

Also happens with the integrated terminal inside VS Code.
Does not happen with Bash.

**Comment by thezim** [comment]
I know there are some [issues](https://github.com/PowerShell/PowerShellEditorServices/pull/592) with VS Code and the debugger/terminal. Perhaps this is related to the corefx. While the referenced PR will not fix terminal.app I highly recommend you get the PR in your VS Code, it has really helped the frustration level in VS Code for myself.

**Comment by felixfbecker** [comment]
I don't think that PR is related to this issue or that this issue is related to VS Code

**Comment by msftrncs** [comment]
I see this issue happen on PS 6.0.3 on both Ubuntu 18.04 and on Windows 10.   Also, Windows PowerShell 5.1 has the same issue.  I will also note it does not happen to BASH, BASH behaves really well when its window is resized, both vertically and horizontally.  PS, not so much.  Its worse (more noticed) in VS Code integrated console, as its more likely to have the window resized throughout a development/test cycle.

**Comment by felixfbecker** [comment]
@iSazonov shouldn't this be `Issue-Bug`?

**Comment by iSazonov** [comment]
@felixfbecker We need more info. Currently PowerShell works with a console in simplest way or "as is". I guess there is tons of things which we would want to improve on Linux and MacOs..

**Comment by felixfbecker** [comment]
What additional info can I provide?

**Comment by felixfbecker** [comment]
cc @SteveL-MSFT @travisez123

**Comment by TravisEz13** [comment]
This repro's for me for both macOS and Linux.  I'm not sure if this is a PowerShell or DotNet issue and I believe there is an existing issue for this.

**Comment by SteveL-MSFT** [comment]
Not repro'ing for me with 6.1.0.  However, if you can repro, does it repro with PSReadLine removed? (remove-module psreadline)

**Comment by TravisEz13** [comment]
Actually, you are right, it doesn't repro in 6.1.0 for me.

**Comment by felixfbecker** [comment]
Ah, it does repro for me in 6.1, but not if I remove PSReadline. Should I move this to the PSReadline repo?

**Comment by TravisEz13** [comment]
It doesn't repro from me even with PSReadline loaded with `6.1.0` on macOS with the latest updates.  I tried iTerm2 and the built in console.

**Comment by felixfbecker** [comment]
It is still happening:

![2018-09-21 11 31 29](https://user-images.githubusercontent.com/10532611/45873118-f7cb3f00-bd91-11e8-901b-ec2fac50bf1f.gif)

```
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```
> Get-Module PSReadline

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.0.0      PSReadline                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-P...
```
What's your PSReadline version?

**Comment by TravisEz13** [comment]
`2.0.0-beta2`   It shows up as what you say above in Get-module

**Comment by TravisEz13** [comment]
My macOS is the same as well.

**Comment by TravisEz13** [comment]
What tool are using to make the gifs?

**Comment by felixfbecker** [comment]
Seems to be fixed!
