### ISSUE TITLE
pwsh in sshd.config should not require the `-sshs` switch

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#5985]
Currently, when using PSCore6 PSRP over SSH you register a new subsystem in sshd_config passing `pwsh -sshs`.  It seems that for PSRP over SSH, we can use `SSH Server mode` of pwsh if the parent process is `sshd`.  We can keep `-sshs` as a `no-op` switch for compatibility reasons.

**Comment by thezim** [comment]
A couple of questions.

1. What about possible other SSH implmentations where the parent process is not `sshd`?
2. Are there any security concerns with auto-enabling the mode? Like if I wrote my own wrapper app and named it `sshd` and called upon PowerShell from it?

**Comment by iSazonov** [comment]
Can we run pwsh as demon, i.e. sshd from pwsh? It can help if we'll need set config name/file.
Also I wonder why OpenSSH is not library?

**Comment by SteveL-MSFT** [comment]
@thezim As discussed in #5944, we can retain `-sshs` which can be used with other implementations/hosts, although I believe OpenSSH has something like 90+% marketshare.

I can't imagine any security concerns with someone trying to masquerade as `sshd` since it would be within their own user space.  If they can get a system service called `sshd` running, they already own the system.

@iSazonov in the future we may need to consider other remote hosting models, but I don't image it would be pwsh itself running as a daemon.  OpenSSH is designed to be used not as a library.  Their client api is basically wrapping `ssh.exe`.  There are 3rd party SSH libraries, though.

**Comment by tdaniely** [comment]
+1 For keeping -sshs functionality for external consumption, it doesn't matter if powershell can do it on it's own, the shell should behave correctly under any ssh host binary. Consider high security networks where they sometimes use custom tools all together, even if just not to use the publicly available code.

**Comment by SteveL-MSFT** [comment]
My proposal retains `-sshs` for compatibility and also enable working with other sshd implementations.  There shouldn't be any security concern as pwsh would run under the parent context.  So if run manually, it'll run as that user.  A user would have to configure a service to start pwsh so they can do what they want as that service account anyways.
