### ISSUE TITLE
[pscredential] (credential) instances are not deserialized as such when invoking another PowerShell process via the CLI

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#5988]
Passing a `[pscredential]` instance to another instance via the _CLI_ using a _script block_ doesn't deserialize to a `[pscredential]` instance; the `[pscustomobject]` instance you get instead isn't directly usable with `-Credential` parameters (requires an explicit cast to `[pscredential]`).

For a real-life use case, see [this SO question](https://stackoverflow.com/q/48369027/45375).

Note that `[pscredential]` instances _do_ deserialize properly in the context of _remoting_:

```powershell
ELEV> Invoke-Command -Computer .  { $Args[0].GetType().FullName } -Args (Get-Credential)
System.Management.Automation.PSCredential  # properly deserialized to original type
```

Given that in the script-block invocation scenario a simple _cast_ back to `[pscredential]` makes things work again, I suspect that the issue is _not_ one of _security_.

Steps to reproduce
------------------

```powershell
# Create a dummy credentials object
$cred = [pscredential]::new('foo', (ConvertTo-SecureString -force -AsPlainText bar))
# Print its ETS type names.
$cred.pstypenames
'---'
# Print its ETS type names again after serialization / deserialization via another PS instance
pwsh -nop -c {  $Args[0].pstypenames  } -args $cred
```

Expected behavior
-----------------

```none
System.Management.Automation.PSCredential
System.Object
---
System.Management.Automation.PSCredential
System.Object
```

Actual behavior
---------------

```none
System.Management.Automation.PSCredential
System.Object
---
Deserialized.System.Management.Automation.PSCredential
Deserialized.System.Object
```

Environment data
----------------

```powershell
PowerShell Core v6.0.0 (v6.0.0) on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
Windows PowerShell v5.1.15063.786 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by iSazonov** [comment]
For reference https://github.com/PowerShell/PowerShell/issues/3172#issuecomment-284041243

**Comment by mklement0** [comment]
@iSazonov: That's helpful background info, thank you.

Note that `[pscredential]` instances _do_ deserialize properly in the context of _remoting_, however; I've updated the original post accordingly.
