### ISSUE TITLE
Two problem in Invoke-Expression

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#5992]
Steps to reproduce 
------------------
problem1:
Invoke-Expression return EMPTY

PS /tmp> Get-Content /tmp/test.txt
1 a
2 b

PS /tmp> Get-Content /tmp/test.txt |foreach-object { ($_ -split ' ')[0]}
1
2

$cmd1 = "Get-Content ./test.txt |foreach-object { ($_ -split ' ')[0]}"
Invoke-Expression $cmd1
#return EMPTY

==================================================================================

problem2:
Invoke-Expression Ignore the linux external command behind the pipe

get-process sshd |select-object name,cpu | awk '{print $1}'
#return
```
Name
----
sshd
sshd
```

$cmd2 = "get-process sshd |select-object name,cpu | awk '{print $1}'"
Invoke-Expression $cmd2
#return
```
Name  CPU
----  ---
sshd 0.02
sshd 0.75
```

Environment data
----------------
Name                           Value                                                                                                             
----                           -----                                                                                                             
PSVersion                      6.0.0                                                                                                             
PSEdition                      Core                                                                                                              
GitCommitId                    v6.0.0                                                                                                            
OS                             Linux 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018                                               
Platform                       Unix                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                               
SerializationVersion           1.1.0.1                                                                                                           
WSManStackVersion              3.0   

cenos74  + powershell v6 ga

reporter
----------------
By the chinese powershell study & research group. QQ group No. is 183173532

**Comment by MaximoTrinidad** [comment]
Hum! This is nothing to do with Invoke-Item.  In the main sample the one-liner is using double-quotes "" to store the commands when it should use a single command. 

```
PS C:\Program Files\PowerShell\6.0.0> "..$_ Test"
.. Test
PS C:\Program Files\PowerShell\6.0.0> '..$_ Test'
..$_ Test
PS C:\Program Files\PowerShell\6.0.0>
```
That's why the other example with the "get-process sshd |select-object name,cpu | awk '{print $1}'" works : "..'{print $1}'..".

Now, there's a behavior when storing the one-liner in single quotes that breaks storing into a variable.  
The issue becomes why a normal statement won't work when storing a PS variable?

```
PS C:\Program Files\PowerShell\6.0.0>
PS C:\Program Files\PowerShell\6.0.0> Get-Content c:\tmp\test2.txt |foreach-object { ($_ -split ' ')[0]}
A
B
PS C:\Program Files\PowerShell\6.0.0> Get-Content c:\tmp\test2.txt |foreach-object { ($_ -split ' ')[1]}
b
c
PS C:\Program Files\PowerShell\6.0.0>
## The following iteration fails: (Either it stores OK or it fails saving to the variable)
PS C:\Program Files\PowerShell\6.0.0> $cmd1 = Get-Content c:\tmp\test2.txt |foreach-object { ($_ -split ' ')[1]}
PS C:\Program Files\PowerShell\6.0.0> Invoke-Expression $cmd1
Invoke-Expression : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Command'. Specified method is not supported.
At line:1 char:19
+ Invoke-Expression $cmd1
+                   ~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Invoke-Expression], ParameterBindingException
+ FullyQualifiedErrorId : CannotConvertArgument,Microsoft.PowerShell.Commands.InvokeExpressionCommand

PS C:\Program Files\PowerShell\6.0.0> $cmd1 = 'Get-Content c:\tmp\test2.txt |foreach-object { ($_ -split ' ')[1]}'
At line:1 char:70
+ ...  'Get-Content c:\tmp\test2.txt |foreach-object { ($_ -split ' ')[1]}'
+                                                                   ~~~~~~~
Unexpected token '')[1]}'' in expression or statement.
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : UnexpectedToken

PS C:\Program Files\PowerShell\6.0.0>
```
I thought the single quotes should have store the whole one-liner without validation. 
Is this a bug!!  Not in Invoke-Expression.

```
## - Example from Help Doc:
PS C:\Program Files\PowerShell\6.0.0> $Command = 'Get-Process | Where-Object { $_.cpu -gt 1000 }'
PS C:\Program Files\PowerShell\6.0.0> Invoke-Expression $Command

 NPM(K)    PM(M)      WS(M)     CPU(s)      Id  SI ProcessName
 ------    -----      -----     ------      --  -- -----------
     96   157.63     212.66   1,773.59   12144   1 chrome
     85   424.07     273.11   2,833.11    1328   1 dwm
     23   138.12      17.48   2,376.31    9156   0 Launchpad
    565   149.44      16.79   2,401.00    9180   0 Launchpad
     48    46.49      51.88   1,782.89   10484   1 Lenovo.Modern.ImController.PluginHost.SettingsApp
     84   235.93     166.28   1,918.45    5652   0 MsMpEng
     98    69.33     182.92   1,288.34   13860   1 SnagitEditor
    130   995.99     282.50   5,862.23    5912   0 sqlservr
    679 1,056.58     164.07   8,656.13    5976   0 sqlservr
      0     0.27      45.85   1,832.23       4   0 System
    570   127.44     127.88   5,121.38   17260   1 VirtualBox
```
Any Comments?
:)

**Comment by MaximoTrinidad** [comment]
By the way, this is also happening in Windows PowerShell 5.1. 
:)

**Comment by MaximoTrinidad** [comment]
Ok!

It's all mind game!

Bottomline - 
1. Don't use Double-Quotes on one-liner(s) containing $. 
2. When using Single-Quotes, the one-liner(s) string need to be properly constructed (String concatenation) as multiple single quotes will break the line.

Here's the fixed line:
```
$cmd1 = 'Get-Content c:\tmp\test2.txt |foreach-object { ($_ -split ' + "' " + "'" + ')[1]}';
Invoke-Expression $cmd1;
```
This one got me!
:)

**Comment by chuanjiao10** [comment]
Both are double-quotation-escalation problems，thank you！
