### ISSUE TITLE
The help function breaks when [Console]::OutputEncoding is set to Unicode

### ISSUE THREAD

**Issue by ExE-Boss** [PowerShell/PowerShell#5994]
Given the fact that PowerShell is moving to Unicode (see #4681, https://github.com/PowerShell/PowerShell-RFC/issues/71#issuecomment-306614751, etc.), it might be a good idea to fix the `help` function for this particular case.

https://github.com/PowerShell/PowerShell/blob/5b5168d72e0a51679667ec26e31d426b5ab4a122/src/System.Management.Automation/engine/InitialSessionState.cs#L4261-L4264

## Known cases where `[Console]::OutputEncoding` is set to Unicode:
- PowerShell is launched inside Visual Studio Code
- PowerShell is launched in a non-Windows environment (even Bash on Ubuntu on Windows)
- `[Console]::OutputEncoding` has been manually set to Unicode

---

Blocks #7233

---

A possible workaround is to install [`less` for Windows](https://chocolatey.org/packages/less) and set `$env:PAGER` to `less.exe`, which supports UTF-8 properly, unlike the old `more.com`.

**Comment by iSazonov** [comment]
`More` has related [comment](https://github.com/PowerShell/PowerShell/blob/5b5168d72e0a51679667ec26e31d426b5ab4a122/src/System.Management.Automation/engine/InitialSessionState.cs#L4758)

**Comment by mklement0** [comment]
**Indeed, we need a replacement for `more.com`.**

Note that "Unicode" in Windows speak often refers to UTF-16LE specifically, not to Unicode encodings in general.

UTF-8 is Core's default, though not yet fully implemented in the console / terminal - see #7233 and #7634 

And with UTF-8 also assigned to `[console]::InputEncoding` (not just ` [console]::OutputEncoding` and `$OutputEncoding`), as will be the case, `more.com` goes haywire.

(Curiously, using UTF-16LE output results only in minor misbehavior: non-Basic Latin / Latin1- Supplement-range characters render as `?`).

```powershell
PS> $OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding = [text.utf8encoding]::new($False); 'ü', '€' +  0..5 | more.com
(gobbledygook along the lines of:
ü
€            ♛ￚ̀耀                                    ♞￑Ѐ耀                                    ♕ￔԀ耀                                    ♨￫؀耀                   ♯￮܀耀                                    ♢￥ࠀ耀"C:\WINDOWS\system32\more.com"
)
```
---

For the sake of completeness: UTF-16LE:

```powershell
PS> $OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding = [text.encoding]::unicode; 'ü', '€' +  0..5 | more.com
ü
?
0
1
2
3
4
5
```

`€`, which is outside the Latin-1 Supplement Unicode range, rendered as `?`.

**Comment by ExE-Boss** [comment]
@rkeithhill The issue is that `less` is GPL licensed, whereas `ssh` and `tar` are BSD licensed and `curl` is [MIT/X-derivate licensed](https://curl.haxx.se/docs/copyright.html).

**Comment by rkeithhill** [comment]
OK, well then perhaps an overhaul of `more.com` or more likely, a new pager for Windows.  Probably would be better to have more typical Windows key bindings anyway, like `Ctrl+f` for find, etc.

**Comment by bitcrazed** [comment]
We're keen to add more *NIX command-line tools where we can. Bear with ;)
