### ISSUE TITLE
Possible method resolution regression calling String.Split

### ISSUE THREAD

**Issue by dantraMSFT** [PowerShell/PowerShell#5996]
The below script does not resolve to any of the char[] or string[] overloads of String.Split on PS 6. It does resolve correctly on Windows PowerShell 5.1 and versions of PS 6 alpha 11 and earlier.  The same behavior is observed with the various char[] and string[] overloads of the method.

It's not clear to me if this is expected behavior or a regression.

The workaround requires either explicitly casting the array to a string[] array or assigning the array to a strongly type variable, such as char[] or string[].

Steps to reproduce
------------------

```powershell
$f = "[123]"
$split = @('[',']')
$f.Split($split, [StringSplitOptions]]::RemoveEmptyEntries)
```

Expected behavior
-----------------

```none
123
```

Actual behavior
---------------

```none
[123]
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Microsoft Windows 10.0.17080
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
N

**Comment by bergmeister** [comment]
@dantraMSFT : Maybe this is a regression or breaking change in .Net Core?

**Comment by lzybkr** [comment]
Not a regression exactly.  See the discussion in duplicate https://github.com/PowerShell/PowerShell/issues/3809
