### ISSUE TITLE
Web Cmdlets test intermittently fail with WebListener timeout

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#6001]
I've seen this a few times.

Steps to reproduce
------------------

Run Windows CI Tests

Expected behavior
-----------------
No failures

Actual behavior
---------------
https://ci.appveyor.com/project/PowerShell/powershell/build/6.0.0-7706#L2212
```none
Describing Web cmdlets tests using the cmdlet's aliases
 [-] Error occurred in Describe block 15.39s
   WebListener did not start before the timeout was reached.
   At C:\projects\powershell\test\tools\Modules\WebListener\WebListener.psm1:91 char:13
Describing Write-Debug tests
+
```

Environment data
----------------

```powershell
> $PSVersionTable
in 6.0.1 branch

```

**Comment by markekraus** [comment]
I have seen this before a few times, but I can never reproduce it when I try. The only way I see we can get to the bottom if it is to add super verbose failure messages and then reviewing the output when it does fail.

**Comment by iSazonov** [comment]
Maybe CI very slow and we should wait more? What is timeout for the start?

**Comment by markekraus** [comment]
15 seconds

https://github.com/PowerShell/PowerShell/blob/44793e306a0414fb0d58a0d15992fff6f2307b94/test/tools/Modules/WebListener/WebListener.psm1#L58

**Comment by iSazonov** [comment]
We could increase the timeout and get anything useful to `$initStatus`.

**Comment by iSazonov** [comment]
Also we check a real time with Get-Date. But if VM sleeps long time the real time loses a value. I think it is more reliably count 100ms intervals in the cycle.

**Comment by markekraus** [comment]
>  But if VM sleeps long time the real time loses a value. 

what?

**Comment by markekraus** [comment]
as for $initstatus.. `$Job | Stop-Job -PassThru | Receive-Job` should b dumping anything that would be in it in the catch block.

**Comment by iSazonov** [comment]
>But if VM sleeps long time the real time loses a value.
what?

We get `$timeOut = (get-date).AddSeconds($initTimeoutSeconds)`. Then VM sleep 30 seconds. Then it run and we check `(get-date) -lt $timeOut)` - we already expire although we worked only 100 ms!

**Comment by markekraus** [comment]
> Then VM sleep 30 seconds. 

what?

**Comment by iSazonov** [comment]
I mean, CI farm can be very busy and VM can be put in a pause.

**Comment by markekraus** [comment]
so something like

```powershell
$sleepMilliseconds = 100
$sleepCount = $initTimeoutSeconds * 1000 / $sleepMilliseconds
do {
    Start-Sleep -Milliseconds $sleepMilliseconds
    $initStatus = $Job.ChildJobs[0].Output | Out-String
    $isRunning = $initStatus -match $initCompleteMessage
    $sleepCount--
}
while (-not $isRunning -and $sleepCount -gt 0)
```

**Comment by iSazonov** [comment]
Yes. If CI VM really slow-slow this help.
