### ISSUE TITLE
Why does PowerShell Core say "All rights reserved." if it's MIT licensed?

### ISSUE THREAD

**Issue by hach-que** [PowerShell/PowerShell#6004]
I just installed PowerShell Core 6.0.0 on Linux, and when starting it I'm presented with this prompt:

```
PowerShell v6.0.0
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS /ssd/opt/root> 
```

Why does it say "All rights reserved" if PowerShell Core is supposed to be MIT licensed? Is the precompiled binary provided under a more restrictive license that the source code?

**Comment by SteveL-MSFT** [comment]
Please see discussion in https://github.com/PowerShell/PowerShell/issues/2129
