### ISSUE TITLE
`ImportPSModule` on `InitialSessionState` should be `params`.

### ISSUE THREAD

**Issue by twitchax** [PowerShell/PowerShell#6005]
Functions in the automation API which take arrays should take them as `params`.

For example [this](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/InitialSessionState.cs#L1883) should be:

```csharp
        public void ImportPSModule(params string[] name)
        {
            if (name == null)
                throw new ArgumentNullException("name");
            foreach (string n in name)
            {
                ModuleSpecificationsToImport.Add(new ModuleSpecification(n));
            }
        }
```

A developer should not _have_ to call this by newing up an array of strings.

**Comment by iSazonov** [comment]
It seems we get extra allocation.

/cc @lzybkr @daxian-dbw

**Comment by twitchax** [comment]
@iSazonov, what do you mean you get extra allocation?

**Comment by iSazonov** [comment]
In both cases we do `new string[]`. Although it is so critical - we call this method rarely.

**Comment by twitchax** [comment]
Yeah.  I meant more for the sake of developers.  Regardless of the number of times PowerShell 6 calls it, writing an app which hosts PowerShell needs to explicitly new up a `string[]`, which is not syntactically preferred.

**Comment by lzybkr** [comment]
FWIW, I believe adding `params` is a breaking change if you don't recompile your code - you could end up with a missing method exception. This might be a non-issue as there are so few hosts that this might affect.

A better change that might be sufficient is to add some overloads that take 1, 2, or 3 parameters. These overloads would avoid creating an array and cover the most common cases.

**Comment by twitchax** [comment]
How is adding `params` a breaking change?

Any caller will have to do

```csharp
state.ImportPSModule(new string[] { "Module1", "Module2" });
```

That line will still compile with `params`.  How often do developers upgrade their packages and not recompile?  Also, I would need to look at the IL, but my impression was that adding `params` would not change the signature of the method: it would simply allow the caller to use the syntactic sugar.  In the end, only the caller needs to take `params` into account when using the syntactic sugar call: in the case of a method that already news up an 

It is totally cool to make methods that take 1, 2, or 3 parameters, but that only solves part of the problem, as their may be developers that need more.  The BCL does this by providing methods with 1, 2, or 3 parameters, and then a fourth overload that takes a `params` as its fourth parameter.

**Comment by twitchax** [comment]
Actually, it looks like the IL method signature is the same...there is just an attribute applied for syntactic purposes (I would guess).

```csharp
private static void WithArray(string[] array)
{
}
```

goes to

```il
.method private hidebysig static 
	void WithArray (
		string[] 'array'
	) cil managed 
{
	// Method begins at RVA 0x205e
	// Code size 2 (0x2)
	.maxstack 8

	IL_0000: nop
	IL_0001: ret
} // end of method Program::WithArray
```

And with `params`, this

```csharp
private static void WithParams(params string[] array)
{
}
```

goes to

```il
.method private hidebysig static 
	void WithParams (
		string[] 'array'
	) cil managed 
{
	.param [1]
	.custom instance void [System.Runtime]System.ParamArrayAttribute::.ctor() = (
		01 00 00 00
	)
	// Method begins at RVA 0x2061
	// Code size 2 (0x2)
	.maxstack 8

	IL_0000: nop
	IL_0001: ret
} // end of method Program::WithParams
```

So, even if a developer did not rebuild against new binaries with `params`, it should still work exactly the same.

**Comment by lzybkr** [comment]
I'm assuming that the callsig in the reference will look different because of the attribute on the parameter.

For example, C++/CLI uses an attribute to distinguish between `int` and `long` when they map to the same CLI type.

**Comment by twitchax** [comment]
It seems to work fine.  I just tried this scenario, and the call works fine, even if you do not rebuild after a dependency updates to use `params`.

**Comment by twitchax** [comment]
This change is obviously not required, it is just normally expected that methods like this take `params` since it just makes life easier for developers.

**Comment by lzybkr** [comment]
Thanks for checking, my memory was fuzzy. I might have been remembering modopt/modreq which is on the signature, not on the references.

**Comment by iSazonov** [comment]
It is public API - we should PowerShell Committee conclusion. 
/cc @SteveL-MSFT

**Comment by powercode** [comment]
Maybe not on topic, but related:
Is is possible to filter the imported commands when adding a module to the `InitialSessionState`?

Like we have on `Import-Module` with for example `-Cmdlet`?

**Comment by iSazonov** [comment]
Internally we use `Import-Module` cmdlet to import a module in `InitialSessionState`.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this.  We believe this is the right change and we should look at all the other public apis to see if this is applicable elsewhere.  It doesn't appear to be a breaking change based on the discussion.

**Comment by iSazonov** [comment]
I found only [`public static void RemoveKeyHandler(string[] key)`](https://github.com/PowerShell/PowerShell/blob/5b5168d72e0a51679667ec26e31d426b5ab4a122/src/Microsoft.PowerShell.PSReadLine/Options.cs#L276) and [`public static int Main(string[] args)`](https://github.com/PowerShell/PowerShell/blob/c1c5344a8897262433141ecbc13bb06ac2c4bbef/src/powershell/Program.cs#L20). The first has still another overload. So I believe there's nothing more to fix.

**Comment by PixleProgrambetaxl** [comment]
+1
