### ISSUE TITLE
Unable to run pwsh in azure website (inside asp.net core)

### ISSUE THREAD

**Issue by andrew-vdb** [PowerShell/PowerShell#6007]
It works locally on my machine but not in azure website
I can run phyton, node in azure website but not powershell core

Use case 01:
01. I use .zip of powershell core
02. I extract it in directory
03. I call "pwsh.exe" from c# with System.Diagnostic.Process
04. No standard error, no standard output in azure website (works in my local machine)
Expected:
At least give some error so I know what is wrong

Use case 02:
Calling Powershell.Create() return null
Expected:
There should be a way in the api to point where powershell core installed

The problem:
I think powershell core is expected to be installed in the machine.
Expected:
It should be more portable

**Comment by iSazonov** [comment]
@andrew-vandenbrink Thanks for your report! Please add $PSVertionTable in the description.

`pwsh` can not start if you removed standard environment variables.

**Comment by andrew-vandenbrink** [comment]
I was copy pasting $PSVertionTable --> typo, I don't get any feedback from standard output and error 

Anyway here's requested version,
![image](https://user-images.githubusercontent.com/12871379/35324914-80f155ba-00f2-11e8-9c28-6fdb74ac2503.png)

**Comment by iSazonov** [comment]
Do you see the issue with PowerShell 7.)?

**Comment by andrew-vdb** [comment]
Sorry, I don't remember it anymore, lets close it..
