### ISSUE TITLE
PowerShell Core 6.0.0.-1 does not support the stroage and stroage blob cmdlets. 

### ISSUE THREAD

**Issue by mhiggins5470** [PowerShell/PowerShell#6011]
Steps to reproduce
------------------
pwsh

Expected behavior
-----------------
Remove-AzureStorageBlob
New-AzureStorageContext
etc.

Actual behavior
---------------
cmdlets not found

Environment data
----------------
Name                           Value
----                           -----
PSVersion                      6.0.0
PSEdition                      Core
GitCommitId                    v6.0.0
OS                             Linux 4.13.0-1006-azure #8-Ubuntu SMP Fri Jan 12 13:18:04 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by markekraus** [comment]
Hi @mhiggins5470! Not all modules made for Windows PowerShell 5.1 and older will work with PowerShell Core 6.0.0 and newer. For Azure, you will need to use the [`AzureRM.Netcore` module ](https://www.powershellgallery.com/packages/AzureRM.Netcore/). Not all of the azure cmdlets are available. If you have specific problems with this module, you will want to report them at the https://github.com/Azure/azure-powershell repo.
