### ISSUE TITLE
wget should be an alias for Invoke-WebRequest -OutFile filename

### ISSUE THREAD

**Issue by snobu** [PowerShell/PowerShell#6017]
Not sure if the `wget` alias is present in Core as well, if it is, this issue is valid here.

`wget` is an alias for `Invoke-WebRequest`. The expected result of running `wget` on *NIX systems is to **download** a file, which means we should pass `-OutFile last_segment_of_url` to `Invoke-WebRequest`.

Example:

```powershell

PS C:\tmp\test> wget http://cdn.dribbble.com/users/189524/screenshots/1968200/01-squirrel_v6.gif


StatusCode        : 200
StatusDescription : OK
...

PS C:\tmp\test> ls
PS C:\tmp\test>




PS C:\tmp\test> wget -OutFile squirrel.gif http://cdn.dribbble.com/users/189524/screenshots/1968200/01-squirrel_v6.gif
PS C:\tmp\test> ls


    Directory: C:\tmp\test


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        1/25/2018  11:19 AM         635972 squirrel.gif
```

**Comment by iSazonov** [comment]
wget and some aliases was removed because of conflicting with native commands. We have tons Issues about aliases and I can not fast find where we made the conclusion.

**Comment by snobu** [comment]
I approve of this. Wise decision.
