### ISSUE TITLE
SSH Agent Forwarding

### ISSUE THREAD

**Issue by gergap** [PowerShell/PowerShell#6019]
Is it possible or at least planned to support SSH agent forwarding?

I would like to login via "ssh -A <host>" from my Linux host into a Windows guest,
and have a working ssh-agent in the same way as it works with Linux guests,
so that I can use git to checkout code.
Currently this does not work, at least not as I know it from the Linux world.

If I start ssh-agent.exe there is no output like on Linux with SSH_AUTH_SOCK,
but it seems to run. At least "ssh-add -L" works and shows that there are no identities.

Then I log into the Windows guest from Linux using "ssh -A <ip>". This works without errors,
but "ssh-add -L"  still shows nothing.

I know that a Linux socket is not of much help in the Windows world, so I wonder if this can works at all.

**Comment by chris-trading** [comment]
Any update on this one?
