### ISSUE TITLE
Unify installation instruction on Ubuntu with .NET Core SDK

### ISSUE THREAD

**Issue by aetos382** [PowerShell/PowerShell#6036]
The installation instruction of PowerShell Core 6.0 for Ubuntu 16.04 is below.
https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md#ubuntu-1604

And the installation instruction of .NET Core SDK is below.
https://www.microsoft.com/net/learn/get-started/linuxubuntu

The scripts for registering key and package sources in these documents are different.
If they are practically the same, please unify either.

**Comment by iSazonov** [comment]
@aetos382 It is Open Source project - feel free contribute!
