### ISSUE TITLE
Cannot invoke-command if the cmdlet does not exist locally

### ISSUE THREAD

**Issue by lansalot** [PowerShell/PowerShell#6037]
I cannot execute a cmdlet that exists on a remote host via invoke-command, because the cmdlet doesn't exist on my own machine, and psReadline interjects and says the command cannot be found. I am prevented from even submitting the command as a result.

Steps to reproduce
------------------
On the remote Server:
```
PS C:\> get-command Remove-DnsServerResourceRecord

CommandType     Name                                               ModuleName
-----------     ----                                               ----------
Function        Remove-DnsServerResourceRecord                     DnsServer
```

My machine

```
PS C:\>  invoke-command -ComputerName remoteserver -ScriptBlock {Remove-DnsServerResourceRecord someparametersetcetc}
Command 'Remove-DnsServerResourceRecord' cannot be found.
```

Expected behavior
-----------------
Expect Invoke-Command to pass whatever I wish through, without PSReadline trying to act all helpful and getting it wrong. A way to "escape" the psreadline checking would be useful.

Environment data
----------------

```
<Name                           Value
----                           -----
PSVersion                      5.0.10514.6
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   10.0.10514.6
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
```

**Comment by MaximoTrinidad** [comment]
Please, as stated in the PowerShell Core landing page all "**Windows PowerShell**" specific issues should be opened on UserVoice:
https://windowsserver.uservoice.com/forums/301869-powershell 

Thx

**Comment by lzybkr** [comment]
See https://github.com/lzybkr/PSReadLine/issues/231 for discussion.
