### ISSUE TITLE
Is there a Powershell SDK for powershell 6.0 core?

### ISSUE THREAD

**Issue by LDSpits** [PowerShell/PowerShell#6038]
I would like to be able to extend a program of mine with powershell capabilities. There was an SDK for that available in older versions of PowerShell. I have looked for a new version for core hut haven't found any. 

Is there a Powershell SDK available? Or was support for it dropped with 6.0?

**Comment by iSazonov** [comment]
Yes, https://powershell.myget.org/feed/powershell-core/package/nuget/Microsoft.PowerShell.SDK
