### ISSUE TITLE
Consider adding #Requires as its own cmdlet.

### ISSUE THREAD

**Issue by thezim** [PowerShell/PowerShell#6039]
This would allow for better discoverability. Formatting has always been ugly too.

```powershell
#Requires -Modules PSWorkflow @{
  ModuleName="PSScheduledJob"
  ModuleVersion="1.0.0.0"
} 
```

#Requires should still work as expected.

**Comment by lzybkr** [comment]
This might result in a poor experience if the script were parsed by a version of PowerShell that did not support this extended syntax.
