### ISSUE TITLE
Setting up 2 Seprate Locations for Mining as an Administrator

### ISSUE THREAD

**Issue by cvshanab** [PowerShell/PowerShell#6040]
Steps to reproduce
------------------

```powershell

```

Expected behavior
-----------------

```none

```

Actual behavior
---------------

```none

```

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by SteveL-MSFT** [comment]
@iSazonov seems like it.  Feel free to just auto-close empty issues.  If they are a legit mistake, the author can comment or open new one.
