### ISSUE TITLE
Usage Question: Importing Assemblies for workflow.

### ISSUE THREAD

**Issue by Alextocode** [PowerShell/PowerShell#6047]
Dear team, 

I am trying to find a solution for optimizing a script that I use at work to automatically build software packages.

In general there are different .exe and .zip files that are copied from a share into another share and later one zipped.
Because this is really slow I considered to try make it working with a workflow using foreach -parallel.

Maybe you can tell me, what I am doing wrong.

Steps to reproduce
------------------
Here is my code excerpt:
```
workflow Copy-ItemParallel
{
 param (
 [array]$sourceelements, [string]$destination)
  {
    foreach -parallel($element in $sourcelements)
    {
        Copy-Item -Path $element -Destination $destination -force
    }
 }
}
```
Expected behavior
-----------------
The workflow can be executed when being called passing an array of source files and a unique destination path.

Actual behavior
---------------
I receive an error I do not really find something about when using Google.
I am using a German Powershell so let me try to translate the error into English.

_Workflow "Copy-ItemParallel" could not be started: The requested process ("Create", "Get" or "Remove") could not be executed, because the type "JobSourceAdapter" that is passed in the task definition (job definition) is not registered. You need to register the type "JobSourceAdapter" either via an explicit call or via using Cmdlet "Import-Module" and passing an assembly name._

Environment data
----------------

PS C:\WINDOWS\system32> $PSVersionTable

Name                           Value                                                
----                           -----                                                
PSVersion                      5.1.16299.98                                         
PSEdition                      Desktop                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                              
BuildVersion                   10.0.16299.98                                        
CLRVersion                     4.0.30319.42000                                      
WSManStackVersion              3.0                                                  
PSRemotingProtocolVersion      2.3                                                  
SerializationVersion           1.1.0.1     
```

**Comment by markekraus** [comment]
Hi @Alextocode ! this GitHub repository is for PowerShell Core (6.0.0 and newer) issues only.  For Windows PowerShell (5.1 and older) bug reporting please use the Windows PowerShell [UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell). If you are not experiencing a bug and are looking for general assistance with using PowerShell, You might find the following resources helpful:

* https://stackoverflow.com/questions/tagged/powershell
* https://powershell.org/forums/
* https://www.reddit.com/r/PowerShell/
* http://slack.poshcode.org/

**Comment by Alextocode** [comment]
Okay @markekraus I will have a look. I was not aware that this has been changed, a few months ago I was allowed to post a question/suggestion regarding PowerShell here and I had also 5.1

**Comment by iSazonov** [comment]
@Alextocode Any file operations over network is always slow. You could use PowerShell remoting to run your scripts directly on remote systems.

**Comment by Alextocode** [comment]
@markekraus  oha, this sounds interesting, but this means currently there is no real option for parallel processes in 6.0?

I need to check also whether I can install PowerShell 6.0 on our servers anyway.

**Comment by Alextocode** [comment]
@iSazonov Yep, but unfortunately the server is one of our main servers I won't get access to. Only my boss and our service admin got access there using the domain admin, it is blocked for all other IT admin users.
Therefore I can't run a PSSession there.
I fear I will have to keep it as it is. In general it does not hurt that much, because the scripts are executed once every morning to build the packages for the day. However since big packages take more than 2 minutes to be copied and zipped I wondered if there can be done some optimization.
The actual script execution time is only 0,5s :D although it does a lot of business logic using a PowerShell class, a cmdlet with dynamic parameters, bla bla bla :D

**Comment by iSazonov** [comment]
You can connect from PowerShell Core to Windows PowerShell.

**Comment by Alextocode** [comment]
As far as I know to enter a PSRemote session there are credentials necessary to execute on the remote computer. As mentioned for the source server I don't have them, I can just access the share with my scripts.
However I think I will do some more evaluation now, if there are some other options.

**Comment by markekraus** [comment]
@Alextocode There are several options for parallel processing in PowerShell, The 2 most common are Jobs (`Start-Job` and friends) and PowerShell Runspaces.

**Comment by chuanjiao10** [comment]
try code:
```
workflow Copy-ItemParallel
{
	param
	(
		[array]$sourceelements, [string]$destination
	)
	
	foreach -parallel($element in $sourcelements)
	{
		inlinescript
		{
			Copy-Item -Path $using:element -Destination $using:destination -force
		}
	}
}

Copy-ItemParallel -sourceelements $array -destination $string

```
