### ISSUE TITLE
PSCore6 - Still installer won't remove previous version from system.

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#6048]
Just an observation.  Installation still leave the previous version in the system.

Environment data
----------------
Windows 10 Insider Build 17083

root@mars:/home/maxt# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Ubuntu 17.10"

```powershell
PS C:\Program Files\PowerShell\6.0.1> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Microsoft Windows 10.0.17083
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS /home/maxt> $PSVersionTable                                                                                          

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      6.0.1                                                                                   
PSEdition                      Core                                                                                    
GitCommitId                    v6.0.1                                                                                  
OS                             Linux 4.13.0-31-generic #34-Ubuntu SMP Fri Jan 19 16:34:46 UTC 2018                     
Platform                       Unix                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 
WSManStackVersion              3.0
```
![pwsh_leftovers_win_2018-01-27_9-40-17](https://user-images.githubusercontent.com/19892435/35472990-37d8778a-0347-11e8-8d93-c784476c0489.jpg)

![pwsh_leftovers_linux_2018-01-27_9-40-17](https://user-images.githubusercontent.com/19892435/35472995-4502bc18-0347-11e8-80fa-a6618be2bd69.jpg)

**Comment by bergmeister** [comment]
Did you upgrade install or uninstall the old version before installing. I have seen this in the past but to me it seemed that the problem disappeared after the rename to pwsh but I might be wrong. I remember trying to reproduce using clean uninstall and install in the past but could not. I am wondering if this only occurs when someone performs a certain action with the installed product that makes it not remove the folder.

**Comment by RichardSiddaway** [comment]
I did an install of 6.0.1 over the top of 6.0.0 this morning at it removed the 6.0.0 folder

**Comment by RichardSiddaway** [comment]
Now I'm confused because I did an install of 6.0.1 over RC2 and the RC2 part wasn't removed.

**Comment by bergmeister** [comment]
Ok, So I tried it by installing 6.0.0 and the installing 6.0.1 on top of it and I cannot repro. Please show us the content of the old folder. Should you have ever created a file in the installation folders (which can easily happen because the default working directory is in the installation director) then it won't remove the folder by design (but still the old files). If a PowerShell cmdlet drops a file in the installation folder then this could maybe be be considered an issue but otherwise I'd mark it as `CANNOT REPRO`.
Note that I am only speaking about the Windows Installer but maybe the case of files getting into the installation folder after installation applies probably to *nix systems as well.

**Comment by MaximoTrinidad** [comment]
Here's the monkey wrench..  

I have .NETCore AzureRM modules loaded, and a Nuget SMO (.NetCore) package installed.

I would (possibly) expect, on a clean PSCore6 6.0.0 installation, that the next PSSCore6 (6.0.1) update could (possibly) remove the previous version.

In my situation, I had 6.0.0 and updated to 6.0.1. 

Also, I remember a known issue when doing the Update-Help, The installation won't remove the folder due to the existing help files.

To Repo... Have anyone try the following:
1. Install clean pswh 6.0.0.
2. Executed the "Update-Help" command
3. Then, install the latest version 6.0.1.

See if this helps. 

:)

![pwsh_leftovers_win_01_2018-01-27_9-40-17](https://user-images.githubusercontent.com/19892435/35485192-e5b6f632-0429-11e8-81f9-235855ec8498.jpg)

![pwsh_leftovers_win_02_2018-01-27_9-40-17](https://user-images.githubusercontent.com/19892435/35485193-ec6c6822-0429-11e8-95dc-e2032b65ae1d.jpg)

![pwsh_leftovers_linux_01_2018-01-27_9-40-17](https://user-images.githubusercontent.com/19892435/35485400-496b97ca-042d-11e8-9a07-0e8cda0a8546.jpg)

![pwsh_leftovers_linux_02_2018-01-27_9-40-17](https://user-images.githubusercontent.com/19892435/35485404-4f610d36-042d-11e8-9ae6-c5a81d68a1ea.jpg)
