### ISSUE TITLE
Windows Defender - PowerShell Core 6.0.1

### ISSUE THREAD

**Issue by ljt91** [PowerShell/PowerShell#6056]
Steps to reproduce
------------------
Installed the latest PowerShell Core 6.0.1 (x64 .MSI) from the GitHub Releases on this repository and received this alert from Windows Defender Security Center about the PackageManagement.psd1 file.

Actual behavior
---------------
![image](https://user-images.githubusercontent.com/158992/35487725-8d0f67c4-0444-11e8-83c5-d5ccdee0c869.png)

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by ljt91** [comment]
Seems to be a number of modules are seeing similar behaviour with the latest signature updates. 

https://social.technet.microsoft.com/Forums/en-US/40fa56dd-b73f-456a-9d97-cdb4500bc7ed/latest-updates-indicated-peasectoa-infection-?forum=WindowsDefenderATPPreview

**Comment by elijahgagne** [comment]
I've run into this as well. I've had to do a repair on PowerShell 6 to get it working again and then turn off Windows Defender temporarily to run certain commands.

**Comment by KevinMarquette** [comment]
If Windows defender cleans up PackageManagement 1.1.7.0, PowerShellGet 1.6.0 will fail to work. This will break the use of `Install-Module` and `Find-Module`.

**Comment by lucdekens** [comment]
For what it's worth, this not limited to Core, PS v5.1 has this as well with newer modules.
In short, PowerShell becomes unusable!

Only alternative is to fall back to an older version of the impacted modules, if you have those around.
TG is still had PowerShellGet 1.0.0.1 sitting in the Modules folder (in PS v5.1)

**Comment by KevinMarquette** [comment]
The Windows Defender issue is resolved in definition update 1.261.424.0

    PS:> Get-MpComputerStatus | Select AntivirusSignature*

    AntivirusSignatureLastUpdated   : 1/28/2018 8:28:37 PM
    AntivirusSignatureVersion       : 1.261.424.0

This won't fix any modules that were broken, those will still have to be repaired.

**Comment by lucdekens** [comment]
I just learned that even with signature file 1.261.433.0, the false positives are still there.
And it is apparently not only Defender, but also SCEP (but I guess they are using the same signature files).

**Comment by SteveL-MSFT** [comment]
It is my understanding that the latest signature update resolves this (there has been at least two updates).
