### ISSUE TITLE
Please support using external/existing .NET core runtime

### ISSUE THREAD

**Issue by AceHack** [PowerShell/PowerShell#6058]
I would like to install PowerShell on an existing .NET core docker image and just update/configure PowerShell to use the existing runtime.  I would like to be able to completely install PowerShell without a packaged .NET instance to reduce space and just use the existing instance.

**Comment by iSazonov** [comment]
I don't know whether it's implemented https://github.com/dotnet/designs/issues/3 - I suppose it should be before we can do not only selfcontained app but also framework based.

**Comment by richlander** [comment]
We are happy to add add PowerShell to the .NET Core Docker SDK image as long as there is a framework-dependent version for us to install that targets .NET Core 2.0.

**Comment by iSazonov** [comment]
Framework-dependent model has one specific thing - we can run application only by `dotnet app.dll`. Perhaps we'll have to create a custom runner for each platform.

**Comment by richlander** [comment]
We are working on fixing that right. Global tools are another option.

**Comment by iSazonov** [comment]
@richlander Do you have tracking issues? Could you please add links?
