### ISSUE TITLE
Powershell 6.0.1 crashes when hosted in a Windows Service

### ISSUE THREAD

**Issue by alekseysshubin** [PowerShell/PowerShell#6062]
With the help of [Host PowerShell Core in .NET Core Applications](https://github.com/PowerShell/PowerShell/tree/master/docs/host-powershell) guide, I've successfully hosted PowerShell Core in a .NET Core 2 console app. But after converting it to a Windows Service, invoking a PowerShell command crashes the service silently.

Steps to reproduce
------------------

- Unzip [PowerShellCoreService.zip](https://github.com/PowerShell/PowerShell/files/1674573/PowerShellCoreService.zip), open the project in Visual Studio.
- Open `MyService.cs`, set a breakpoint on line 18 (`var results = ps.AddScript...`).
- Open cmd, `cd` to the project folder, run `dotnet publish -c Debug -r win10-x64 -o PublishOutput`.
- Open cmd as an administrator, run `sc create PowerShellCoreService binpath= "path\to\PublishOutput\PowerShellCoreService.exe"`
- Start the service and attach Visual Studio debugger to the service process.
- Wait for the breakpoint to activate and step over the line.

Expected behavior
-----------------

The script executed and the results returned to the code.

Actual behavior
---------------

The application crashes, and Visual Studio stops the debugging session immediately. The `catch` block is not activated.

Environment data
----------------

- Windows 10 1709 x64
- Visual Studio 2017 15.5.5

Notes
----------------

The same happens on RunspacePool.Open() call.
My understanding is that I don't need to install PowerShell Core to my system for this code to work (is it right?). But just in case, I tried to install the latest PowerShell 6.0.1, but it hasn't helped.
I have also tried it with PowerShell 6.0.0, the result is the same.

**Comment by iSazonov** [comment]
>My understanding is that I don't need to install PowerShell Core to my system for this code to work 

Yes, currently PowerShell Core is self-contained app.

**Comment by SteveL-MSFT** [comment]
@alekseysshubin can you provide a stack trace at time of crash?

**Comment by alekseysshubin** [comment]
@SteveL-MSFT I cannot collect it from Visual Studio because it closes debugging session. I've tried to collect it using first WER and then ProcDump tool, but they both don't detect a crash. I've tried again in VS debugger, and `AppDomain.ProcessExit` event is called. So it looks like the application doesn't crash but just exits. Is it possible that something like `Environment.Exit()` is called by some code within PowerShell?

**Comment by anmenaga** [comment]
Looks like something is special about the environment...
I've tried to repro but service runs fine in my case:
Code:
```
        public void Start(string[] startupArguments, ServiceStoppedCallback serviceStoppedCallback)
        {
            try
            {
                using (var ps = PowerShell.Create())
                {
                    foreach (var result in ps.AddScript("$PID; \"$($PSVersionTable.PSVersion) $($PSVersionTable.PSEdition)\"").Invoke())
                    {
                        Debug.WriteLine(result.ToString());
                    }
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);
                throw;
            }
        }
```
when stepped through in VS 2017 debugger prints this in output window:
```
6660
6.0.0 Core
```
and service is displayed as running:
```
PS C:\WINDOWS\system32> Get-Service PowerShellCoreService

Status   Name               DisplayName
------   ----               -----------
Running  PowerShellCoreS... PowerShellCoreService
```

My env is:
```
Windows Server x64 / 16299.0.amd64fre.rs3_release.170922-1354
VS 2017 Community 15.4.0
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
dotnet --version == 2.0.2
```

**Comment by anmenaga** [comment]
@alekseysshubin Can you please try with Windbg?
Install [Debugging tools for Windows](https://developer.microsoft.com/en-us/windows/hardware/download-windbg);
then start service `Start-Service PowerShellCoreService` and attach Windbg within 10 seconds by command like this:
`c:\Debuggers\windbg.exe -pn PowerShellCoreService.exe -c 'sxe -c "!pe;!clrstack;gc" clr;g'`
It will run the process till termination and should print exceptions happening in it. For example:
```
ModLoad: 00007ffc`318f0000 00007ffc`31916000   C:\WINDOWS\SYSTEM32\sppc.dll
ModLoad: 00007ffc`33590000 00007ffc`335b2000   C:\WINDOWS\SYSTEM32\gpapi.dll
ModLoad: 00007ffb`f9ab0000 00007ffb`f9ab3000   C:\Temp\1\PublishOutput\System.Threading.ThreadPool.dll
12168
6.0.0 Core
(2f88.2998): CLR exception - code e0434352 (first chance)
Exception object: 000001ef4ec900f8
Exception type:   System.InvalidOperationException
Message:          Test exception
InnerException:   <none>
StackTrace (generated):
<none>
StackTraceString: <none>
HResult: 80131509
OS Thread Id: 0x2998 (6)
        Child SP               IP Call Site
0000000a7a1ff708 00007ffc34b43fb8 [HelperMethodFrame: 0000000a7a1ff708] 
0000000a7a1ff800 00007ffba20123c7 PowerShellCoreService.MyService.Start(System.String[], DasMulli.Win32.ServiceUtils.ServiceStoppedCallback) [C:\Temp\1\MyService.cs @ 24]
0000000a7a1ff8c0 00007ffba2011b23 DasMulli.Win32.ServiceUtils.SimpleServiceStateMachine.OnStart(System.String[], DasMulli.Win32.ServiceUtils.ServiceStatusReportCallback)
0000000a7a1ff920 00007ffba2011529 DasMulli.Win32.ServiceUtils.Win32ServiceHost.ServiceMainFunction(Int32, IntPtr)
0000000a7a1ff980 00007ffba20113bf DomainBoundILStubClass.IL_STUB_ReversePInvoke(Int32, Int64)
ModLoad: 00007ffb`ead80000 00007ffb`eaeb8000   C:\Temp\1\PublishOutput\Microsoft.DiaSymReader.Native.amd64.dll
ModLoad: 00007ffb`f4730000 00007ffb`f4739000   C:\Temp\1\PublishOutput\System.Diagnostics.StackTrace.dll
ModLoad: 00007ffb`eb110000 00007ffb`eb210000   C:\Temp\1\PublishOutput\System.Reflection.Metadata.dll
ModLoad: 00007ffb`eaec0000 00007ffb`eb104000   C:\Temp\1\PublishOutput\System.Collections.Immutable.dll
System.InvalidOperationException: Test exception
   at PowerShellCoreService.MyService.Start(String[] startupArguments, ServiceStoppedCallback serviceStoppedCallback) in C:\Temp\1\MyService.cs:line 24
(2f88.2998): CLR exception - code e0434352 (first chance)
CLR exception type: System.InvalidOperationException
    "Test exception"
Exception object: 000001ef4ec900f8
Exception type:   System.InvalidOperationException
Message:          Test exception
InnerException:   <none>
StackTrace (generated):
    SP               IP               Function
    0000000A7A1FF800 00007FFBA20123C7 PowerShellCoreService!PowerShellCoreService.MyService.Start(System.String[], DasMulli.Win32.ServiceUtils.ServiceStoppedCallback)+0x157

StackTraceString: <none>
HResult: 80131509
OS Thread Id: 0x2998 (6)
        Child SP               IP Call Site
0000000a7a1fd528 00007ffc34b43fb8 [HelperMethodFrame: 0000000a7a1fd528] 
0000000a7a1fd620 00007ffba2012475 PowerShellCoreService.MyService.Start(System.String[], DasMulli.Win32.ServiceUtils.ServiceStoppedCallback) [C:\Temp\1\MyService.cs @ 13]
0000000a7a1ff708 00007ffc01a13190 [HelperMethodFrame: 0000000a7a1ff708] 
0000000a7a1ff800 00007ffba20123c7 PowerShellCoreService.MyService.Start(System.String[], DasMulli.Win32.ServiceUtils.ServiceStoppedCallback) [C:\Temp\1\MyService.cs @ 24]
0000000a7a1ff8c0 00007ffba2011b23 DasMulli.Win32.ServiceUtils.SimpleServiceStateMachine.OnStart(System.String[], DasMulli.Win32.ServiceUtils.ServiceStatusReportCallback)
0000000a7a1ff920 00007ffba2011529 DasMulli.Win32.ServiceUtils.Win32ServiceHost.ServiceMainFunction(Int32, IntPtr)
0000000a7a1ff980 00007ffba20113bf DomainBoundILStubClass.IL_STUB_ReversePInvoke(Int32, Int64)
ntdll!ZwTerminateProcess+0x14:
00007ffc`387203c4 c3              ret
```

**Comment by alekseysshubin** [comment]
@anmenaga, my environment:
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core
dotnet --version == 2.1.4

[WinDbg log](https://github.com/PowerShell/PowerShell/files/1685347/PowerShellCoreService-windbg-log.txt). The only exception:

    ModLoad: 00007ff9`e9580000 00007ff9`e959a000   C:\Users\aleks\Documents\Projects\PowerShellCoreService\PowerShellCoreService\PublishOutput\netstandard.dll
    ModLoad: 00007ff9`e26c0000 00007ff9`e26c6000   C:\Users\aleks\Documents\Projects\PowerShellCoreService\PowerShellCoreService\PublishOutput\System.Diagnostics.Debug.dll
    ModLoad: 00007ff9`e2150000 00007ff9`e215b000   C:\Users\aleks\Documents\Projects\PowerShellCoreService\PowerShellCoreService\PublishOutput\System.Threading.Thread.dll
    (3b90.310c): Break instruction exception - code 80000003 (first chance)
    *** ERROR: Symbol file could not be found.  Defaulted to export symbols for C:\WINDOWS\SYSTEM32\ntdll.dll - 
    Processing initial command 'sxe -c "!pe;!clrstack;gc" clr;g'
    ntdll!DbgBreakPoint:
    00007ffa`021d3800 cc              int     3
    0:006> sxe -c "!pe;!clrstack;gc" clr;g
    ModLoad: 00007ff9`e2130000 00007ff9`e213b000   C:\Users\aleks\Documents\Projects\PowerShellCoreService\PowerShellCoreService\PublishOutput\System.Runtime.InteropServices.dll
    ModLoad: 00007ff9`e1cc0000 00007ff9`e1cc5000   C:\Users\aleks\Documents\Projects\PowerShellCoreService\PowerShellCoreService\PublishOutput\Microsoft.Win32.Primitives.dll
    ModLoad: 00000222`4ec10000 00000222`4f342000   C:\Users\aleks\Documents\Projects\PowerShellCoreService\PowerShellCoreService\PublishOutput\System.Management.Automation.dll

**Comment by alekseysshubin** [comment]
I've tried on a fresh Win10 virtual machine, and it works there. Looks like a problem with my environment indeed.

**Comment by SteveL-MSFT** [comment]
@alekseysshubin if you can get a clear repro, please respond to this and I'll reopen the issue.  Currently there's no action we can take.  Thanks.
