### ISSUE TITLE
Why is there an restriction  to disallow on All Digits for the new computername?

### ISSUE THREAD

**Issue by AdamGrossTX** [PowerShell/PowerShell#6067]
https://github.com/PowerShell/PowerShell/blob/d43b2cf958805ab12906c682f5d75ba01641cb47/src/Microsoft.PowerShell.Commands.Management/commands/management/Computer.cs#L1989

According to this https://support.microsoft.com/en-us/help/909264/naming-conventions-in-active-directory-for-computers-domains-sites-and, AD doesn't seem to restrict digits only.  However, you can see I tried Rename-Computer and PS doesn't like it. But can change it to digits only in the Windows UI without issue.  

![image](https://user-images.githubusercontent.com/20917262/35575630-7de7e8d4-05a2-11e8-9ed3-f71a5b16bc28.png)

**Comment by markekraus** [comment]
https://support.microsoft.com/en-us/help/909264/naming-conventions-in-active-directory-for-computers-domains-sites-and

from the Computer names > NetBIOS computer names > Disallowed characters section:

> In Windows 2000 and in later versions of Windows, computers that are members of an Active Directory domain cannot have names that are composed completely of numbers. This restriction is because of DNS restrictions.

**Comment by AdamGrossTX** [comment]
Wow. I even linked to the same article. I tried to due diligence. Sorry I missed that.
