### ISSUE TITLE
Take ownership of my Snap package build repository

### ISSUE THREAD

**Issue by diddledan** [PowerShell/PowerShell#6071]
In https://github.com/diddledan/powershell-snap I have worked with @TravisEz13 to scaffold a working Snap package build based on Snapcraft and Docker build processes. Can you review and take ownership or propose alternative way of proceeding.

**Comment by TravisEz13** [comment]
Verified license is MIT

**Comment by TravisEz13** [comment]
We are doing an internal review.  This will take some time.

**Comment by TravisEz13** [comment]
Snapcraft appears to be GPLv3

**Comment by TravisEz13** [comment]
@diddledan Do you want to go ahead and transfer ownership to the PowerShell org?

**Comment by diddledan** [comment]
Yes, I can transfer now if everything is ready...

**Comment by TravisEz13** [comment]
Everything is ready.  Request transfer and mention that you have and I'll have someone take ownership.

**Comment by diddledan** [comment]
Seems I can't request a transfer to the PowerShell organisation on GitHub without "create repository" permission granted to my account (https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/). I suggest instead that, either I transfer to a member of the organisation's personal account (you, @TravisEz13?) who does have create repository permission and they re-transfer it from their personal account into the PowerShell org; or, someone with create repository permission can use GitHub's "Import Repository" (https://github.com/new/import) to copy my repo, not fork, into the PowerShell org.

**Comment by TravisEz13** [comment]
The import (https://github.com/new/import) seems like the easiest way
@SteveL-MSFT  can you import this repository into the PowerShell org.

**Comment by SteveL-MSFT** [comment]
@TravisEz13 @diddledan done: https://github.com/PowerShell/PowerShell-Snap

**Comment by joeyaiello** [comment]
@TravisEz13 what is this blocked on? Are you using this to track the Snap package now, or is this considered done because we have our repo now?

**Comment by TravisEz13** [comment]
This is done.  I need to do an RFC for preview snaps
