### ISSUE TITLE
Copyright in files

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#6073]
The repo is under MIT license.

Currently many files in the repo contain Microsoft Copyrights. New files haven't copyrights at all.
All files in CoreFX repo has MIT copyright banner. This is expected for the repo too (including distributed files).

**Comment by SteveL-MSFT** [comment]
Following up

**Comment by iSazonov** [comment]
Also question is that we should place in module Author(s) fields - Microsoft, real man name, PowerShell Community, ...

**Comment by SteveL-MSFT** [comment]
Per https://docs.opensource.microsoft.com/releasing/copyright-headers.html

It appears we should have a copyright header on all source files.  We should follow the same header in our module manifests.  I'll submit a PR.
