### ISSUE TITLE
PowerShell v6.0.1 crash after using the command Login-AzureRMAccount

### ISSUE THREAD

**Issue by BEPROnICT** [PowerShell/PowerShell#6077]
Steps to reproduce
------------------
![image](https://user-images.githubusercontent.com/32331187/35636351-2c62bdda-06b1-11e8-9c87-4baa8db45b27.png)

```

Expected behavior
-----------------
Opening login page to Azure Portal. 

Actual behavior
---------------
When using the command Login-AzureRmAccount. PS Core is crashing and pop-up has been shown onto the screen that PS Core has stopped working. 

Environment data
----------------

<!-- provide the output of $PSVersionTable -->

```powershell
> $PSVersionTable
PS C:\Program Files\PowerShell\6.0.1> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


PS C:\Program Files\PowerShell\6.0.1>

**Comment by daxian-dbw** [comment]
@BEPROnICT .NET Core doesn't support Windows Form. Are you using the [`AzureRM`](https://www.powershellgallery.com/packages/AzureRM/5.1.1) module or [`AzureRM.Netcore`](https://www.powershellgallery.com/packages/AzureRM.Netcore/0.9.1) module? The former is for Windows PowerShell (targeting full .NET framework), and the latter is for PowerShell Core (targeting .NET Core). Can you try the `AzureRM.Netcore` module and see if it works for you?

**Comment by MaximoTrinidad** [comment]
FYI 

AzureRM.Netcore modules works great for Windows PSCore6 and specially on Linux.  Although not all AzureRM modules are ported to *.Netcore, you can connect, build and manage AzureRM VM's the same way. 

Using the initial command "Add-AzureRmAccount" the first time will ask you to open the browser to authorize your device to connect. 

![azurenetcore_login_2018-01-30_15-44-02](https://user-images.githubusercontent.com/19892435/35645133-f7d4c6ac-0698-11e8-88af-eceb86e990c5.jpg)

After that, you can save to a json file (using the Save-AzureRmContext), you can automate the login connection using the Import-AzureRmContext for the subscription you are working. 

![azurenetcore_login_011_2018-01-30_15-44-02](https://user-images.githubusercontent.com/19892435/35645310-6c9d5f30-0699-11e8-99da-7444c4f429c4.jpg)

```
## Windows or Linux connection - one time only
Add-AzureRmAccount;
:
## Add resource group, create Azure Storage,..
:

## - Save changes to AzureRMProfile: example Linux
Save-AzureRmContext -Path "/home/user01/AzureSubscriptions/AsubRMprofile.json";
:

## - From now on connect to Azure (not using Add-AzureRmAccount): 
## - To Login using the JSON profile: example Linux
Import-AzureRmContext -Path "/home/user01/AzureSubscriptions/lx_AsubRMprofile.json";
:
```
:)
