### ISSUE TITLE
Convert-String results in NoProgramFound exception

### ISSUE THREAD

**Issue by yakovkeselman** [PowerShell/PowerShell#6079]
$ExamplePatterns = @(
	@{before='SQ *UBER PARTNERS ( JASON'; after='UBER'},
	@{before='OFFICE DEPOT620'; after='OFFICE DEPOT'},
	@{before='IMPARK00250058U'; after='IMPARK'},
	@{before='0000NYCTAXI2H44'; after='NYCTAXI'},
	@{before='UBERSEAT TICKETS'; after='UBERSEAT TICKETS'},
	@{before='UBER BV'; after='UBER'},
	@{before='NYC TAXI 9H61'; after='NYC TAXI'}
)

Data (one-column CSV, saved as "g1-small.csv"):

vendor
IMPARK US ONLINE
IMPARK US RECURRING
IMPARK00250145A
BECK TAXI
HENDERSON TAXI
INDEPENDENT TAXI LA
ROYAL TAXI
SEETAXI 865751
SQ    TAXI GOSQ.COM
Uber-TAXI from airpor
VTS CITY SERVICE TAXI
VTS GLOBE TAXI

Import-Csv g1-small.csv | Convert-String -Example $ExamplePatterns

Exception:
Convert-String : Convert-String appears to be having trouble parsing your data using the examples you've provided.
We'd love to take a look at what went wrong - feel free to send the command you tried in a mail to
psdmfb@microsoft.com. We will review all submissions, although we can't guarantee a response.
At line:1 char:27
+ Import-Csv g1-small.csv | Convert-String -Example $ExamplePatterns
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (:) [Convert-String], ArgumentException
    + FullyQualifiedErrorId : NoProgramFound,Microsoft.PowerShell.Commands.StringManipulation.ConvertStringCommand

**Comment by SteveL-MSFT** [comment]
`Convert-String` isn't part of PSCore6.  It appears you are using Windows PowerShell.  Windows PowerShell issues/suggestions should be posted to https://windowsserver.uservoice.com/forums/301869-powershell.  However, general usage issues (which seems to be case here) might be better posted on StackOverflow or PowerShell.org
