### ISSUE TITLE
reg key not removed on upgrade

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#6089]
Steps to reproduce
------------------
`HKEY_CURRENT_USER\Software\Microsoft\PowerShell-6.0.0\ProgramsMenuShortcut` is not removed on upgrade to 6.0.1

Expected behavior
-----------------
should be removed on upgrade

Actual behavior
---------------

stays

Environment data
----------------

```powershell
> $PSVersionTable
6.0.0
```

**Comment by iSazonov** [comment]
@TravisEz13 Currently we use [HKLM branch](https://github.com/gpduck/PowerShell/blob/8119712fccb71a2c0d5c9b49d49aa212b067ada2/assets/Product.wxs#L195)

**Comment by TravisEz13** [comment]
The problem is that we change the key in each package.

**Comment by iSazonov** [comment]
I install and then uninstall PowerShell-6.1.0-preview.7845-win-x64.msi - the registry key was removed.

**Comment by TravisEz13** [comment]
Try the upgrade scenario.   I'll update the instruction to remove the uninstall, scenario.

**Comment by TravisEz13** [comment]
We can fix this by changing the key to `HKEY_CURRENT_USER\Software\Microsoft\PowerShellCore\ProgramsMenuShortcut`

**Comment by iSazonov** [comment]
I still can not repo. I install PowerShell-6.1.0-preview.7856-win-x64.msi over PowerShell-6.1.0-preview.7845-win-x64.msi  - the previous key was removed.

Our msi do uninstall previous version before install new.

**Comment by TravisEz13** [comment]
fixed in https://github.com/PowerShell/PowerShell/commit/9fc964a2303fb90858467117183320f5d844c878
