### ISSUE TITLE
vbscript in MSI fails

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#6095]
Steps to reproduce
------------------

build and run MSI from master branch

Expected behavior
-----------------

msi should install without error

Actual behavior
---------------

![image](https://user-images.githubusercontent.com/10873629/35761898-1b9a6cee-0843-11e8-8ca4-1a32124e0fb5.png)

Log Excerpt
-------------

>Action 18:10:37: SaveShortcutPath. 
Action start 18:10:37: SaveShortcutPath.
Action ended 18:10:37: SaveShortcutPath. Return value 1.
Action 18:10:37: FixShortcutWorkingDirectory. 
Action start 18:10:37: FixShortcutWorkingDirectory.
DEBUG: Error 2851:  The data for the icon WixUI_Ico_Info is not valid
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2851. The arguments are: WixUI_Ico_Info, , 
Error 1720. There is a problem with this Windows Installer package. A script required for this install to complete could not be run. Contact your support personnel or package vendor.  Custom action FixShortcutWorkingDirectory script error -2147024891, WshShortcut.Save: Unable to save shortcut "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\PowerShell\PowerShell 6.0.1-c876ae3.lnk". Line 8, Column 9,  
MSI (s) (8C:24) [18:10:39:239]: Product: PowerShell-6.0.1-c876ae3-x64 -- Error 1720. There is a problem with this Windows Installer package. A script required for this install to complete could not be run. Contact your support personnel or package vendor.  Custom action FixShortcutWorkingDirectory script error -2147024891, WshShortcut.Save: Unable to save shortcut "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\PowerShell\PowerShell 6.0.1-c876ae3.lnk". Line 8, Column 9,  

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1-164-g7dc54b240297ce5d79ac3a567de781d6a3e7df23
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by bergmeister** [comment]
I saw the PR that added this VBScript but since I don't have much knowledge about it, I decided to not comment on it, therefore I cannot be of any help in this issue.
What I would suggest is to have a simple smoke test (as part of the `AppVeyor` build or a feature test) that installs it via the `/quiet` option of `msiexec.exe` and checks that the exit code is 0 (if there was a problem then it would be something like 1603, etc. This should not be too expensive in terms of time (I guess around 15-20 seconds).

**Comment by iSazonov** [comment]
I see two errors and don't understand how they relate. First is bad icon format. Second error -2147024891 is access denied.

**Comment by gpduck** [comment]
I'm getting the same error on my laptop, I'll see what I can come up with.

**Comment by iSazonov** [comment]
@SteveL-MSFT Could you please consider to introduce new label `Area-Install` or `Area-Setup` for issues with MSI and installation scripts?

**Comment by gpduck** [comment]
@TravisEz13 can you test the build at https://ci.appveyor.com/project/PowerShell/powershell/build/v6.1.0-preview.7845/artifacts and verify that it is fixed?

**Comment by TravisEz13** [comment]
I'll try it when I get back to a windows machine.

**Comment by TravisEz13** [comment]
No error and it worked

**Comment by bergmeister** [comment]
@TravisEz13 PR #6203 has fixed this, therefore this issue can be closed now.

**Comment by TravisEz13** [comment]
Agreed
