### ISSUE TITLE
Unable to use Ctrl+V keyboard shortcut on Windows despite Ctrl key shortcut is enabled

### ISSUE THREAD

**Issue by rumrais1n** [PowerShell/PowerShell#6096]
Steps to reproduce
------------------
1. Select any string and press Ctrl+C to copy selected string.
1. Press Ctrl+V to paste copied string.

Expected behavior
-----------------
1. Copied string is pasted on console.

Actual behavior
---------------
1. Nothing is pasted on console despite Ctrl key shortcut is enabled.
(Right-click on window title → "Property" → "Option" tab → put a check to "Enable Ctrl key shortcut(Ctrl キー ショートカットを有効にする)")
![2018-02-03_18-23](https://user-images.githubusercontent.com/13467319/35765855-2b02c94c-0910-11e8-8435-299fed2d90ed.png)

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
My machine is Japanese environment

**Comment by iSazonov** [comment]
It is dup #4294
We'll get this with PSReadline 2.0.0

**Comment by rumrais1n** [comment]
Thanks.
I could resolve the issue after executing `Remove-Module PSReadLine`

**Comment by rumrais1n** [comment]
Thanks.
I could resolve the issue after executing `Remove-Module PSReadLine` so I close the issue. Please reopen the issue if needed.
