### ISSUE TITLE
The remote PowerShell can't install .NET-4.5.2-KB2901907-x86-x64-AllOS-ENU.exe on Window Server 2008 R2

### ISSUE THREAD

**Issue by chancein007** [PowerShell/PowerShell#6106]
Dear Guys,

We tried to install  install .NET-4.5.2-KB2901907-x86-x64-AllOS-ENU.exe on the remote Window Server 2008 R2 by remote PowerShell over WinRM from another server. As we known that the default PowerShell Version on  Window Server 2008 R2 is v2, it failed and throw the below exception when I run the below command after using Enter-PSSession PowerShell command to connect to the remote Windows 2008R2 server.
@ The command: c:\setup\.NET-4.5.2-KB2901907-x86-x64-AllOS-ENU.exe /q /log c:/setup/install.log
@  The Exception is as below: An error was encountered. Unspecified error.

Is there any limitation for remote Powershell on Window Server 2008R2 to stop the above PowerShell command to install .NET 4.5.2? By the way, the same remote PowerShell command by WinRM can run successfully on Windows 2012 R2. Is there any difference between them?

It is a little urgent and right now it blocked us, Any help is much appreciated in advanced.

**Comment by MaximoTrinidad** [comment]
What version of PowerShell??

Remember that only PSCore6 issue are posted in Github.  Windows PowerShell (v2-v5.x) Issues goes to UserVoice: https://windowsserver.uservoice.com/forums/301869-powershell 

If this is a production issue then use your Premier Support contact.

**Comment by chancein007** [comment]
Thanks, it is the windows server 2008 and the PS version is 2.0. The issue has been resolved and we should set the MaxMemoryPerShellMB value as bigger number, for example, 2048

Set-Item WSMan:\localhost\Shell\MaxMemoryPerShellMB 2048 -force
Set-Item WSMan:\localhost\Plugin\Microsoft.PowerShell\Quotas\MaxMemoryPerShellMB 2048  -force
Start-Service winrm
