### ISSUE TITLE
Powershell Core 6 breaks the `MenuComplete` style tab completion

### ISSUE THREAD

**Issue by mikemaccana** [PowerShell/PowerShell#6108]
Powershell Core 6 breaks the `MenuComplete` style tab completion.

When running `pwsh` with: 

    Set-PSReadlineKeyHandler -Chord Tab -Function MenuComplete
 
And tabbing through the options, when each new option is selected, the highlight from the previous selection stays on screen:

![image](https://user-images.githubusercontent.com/172594/35851565-4c235bfc-0b20-11e8-9e6a-4b8a91776d83.png)

Steps to reproduce
------------------

```powershell
Set-PSReadlineKeyHandler -Chord Tab -Function MenuComplete
```

Expected behavior
-----------------
And tabbing through the options, when each new option is selected, the highlight is moved to the new selection, as works with Powershell 5 (`powershell`).

Actual behavior
---------------

And tabbing through the options, when each new option is selected, the highlight from the previous selection stays on screen:

![image](https://user-images.githubusercontent.com/172594/35851565-4c235bfc-0b20-11e8-9e6a-4b8a91776d83.png)

Environment data
----------------

  Name                           Value
  ----                           -----
  PSVersion                      6.0.0
  PSEdition                      Core
  GitCommitId                    v6.0.0
  OS                             Microsoft Windows 10.0.17074
  Platform                       Win32NT
  PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
  PSRemotingProtocolVersion      2.3
  SerializationVersion           1.1.0.1
  WSManStackVersion              3.0

**Comment by lzybkr** [comment]
This is fixed in [PSReadLine 2.0.0-beta1](https://www.powershellgallery.com/packages/PSReadline/2.0.0-beta1).

This release can be installed by running `Install-Module PSReadLine -Force -AllowPrerelease -AllowClobber -SkipPublisherCheck` or something like that.

**Comment by mikemaccana** [comment]
Thanks @lzybkr!
