### ISSUE TITLE
Add microsoft Update opt-in functionality to MSI

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#6118]
In the future we plan on supporting security updates through Microsoft Update, for this to work well, the installer should ask users to opt-in to Microsoft Update.

## Workflow

- [ ] check existing MU opt-in status
    - [ ] If already opt-in to MU, go to the last step
    - [ ] if not, go to next step.
- [x] Show opt-in UI
    - [x] if the user opts out, go to the last step
    - [x] if the user opts in, got to next step
- [x] Add MU service using WUA API (see examples in a separate section)
- [ ] Configure AU
    - [ ]  If Windows 10, goto to last step
    - [ ] if AU is on, goto last step
    - [ ] check OS install type
        - [ ] if client OS set AU notification level (see examples in a separate section) to `scheduled installs`
        - [ ] if server OS set AU notification level (see examples in a separate section) to `notify before installation` 
- [ ] Continue with the installation
    
### PowerShell
https://github.com/PowerShell/xWindowsUpdate/blob/dev/DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1#L490

### API

https://msdn.microsoft.com/en-us/library/windows/desktop/aa385824(v=vs.85).aspx

### in PowerShell

https://github.com/dsccommunity/xWindowsUpdate/blob/6aab96e94e4a53b817e9f9b7cc403b8036c8b93f/source/DSCResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1#L747

### VB

And the documentation:  https://msdn.microsoft.com/en-us/library/windows/desktop/aa826676(v=vs.85).aspx

### example
Here is what the screen should say and look like (icon blurred until we get permission to use them):
![image](https://user-images.githubusercontent.com/10873629/35881386-7d40fe0a-0b35-11e8-90b6-16b8171fe605.png)

### text
Text | Location | Comments
-- | -- | --
Use Microsoft Update to help keep your computer secure and up to date | Header |  
Microsoft Update helps keep your computer secure and up to date for Windows and other Microsoft products, including PowerShell 7. Updates will be delivered based on your current update settings. You can review or change these settings from the Windows Update control panel. | Description text… top /  middle |  
Use Microsoft Update when I check for  updates (recommended) | First radio selection | Boldface
I don’t want to use Microsoft Update. | Second radio selection |  
See the Microsoft Update FAQ | Bottom left (aligned left), first link. | Link (see below for  details)
Read the Microsoft Update Privacy  Statement | Bottom left (aligned left), second  link | Link (see below for  details)

### urls
* Microsoft Update online FAQ URL 

http://go.microsoft.com/fwlink/?LinkID=57191​

* Microsoft Update privacy statement URL 

http://go.microsoft.com/fwlink/?LinkID=57190

**Comment by chuanjiao10** [comment]
The best default automatically updated to provide a command to stop.

**Comment by TravisEz13** [comment]
@chuanjiao10 Can you please restate?  I don't understand what you are trying to say.

**Comment by bergmeister** [comment]
When auto-update is turned on would that also mean that minor version updates get applied automatically or only patches?

**Comment by TravisEz13** [comment]
> would that also mean that minor version updates get applied automatically or only patches?

The plan is preliminary (not final), but currently is **only** to release minor updates which are **critical security** updates.  Other limitations mean, this will likely not happen until after 6.0.2, as I had to make fixes to the MSI in order to make it serviceable using Microsoft Update.

**Comment by chuanjiao10** [comment]
Sorry for the late reply, these days Chinese New Year holiday.

Our aim is to:
Eliminate powershell version debris, windows.

my suggestion is:

1 If you have open windows update, powershell can be through it, monthly automatically upgrade.

2 If you have closed windows update, but ran powershell.exe, powershell can background tasks, quietly automatically upgrade to the latest version.

3 provides a turn off the automatic upgrade command switch, used to turn off the above two actions.

**Comment by TravisEz13** [comment]
@chuanjiao10 This work item must be done as stated to meet our requirements to release security updates.  Your stated aim is unrelated to this issue.  Your requirements are new requirements.  Please file a new issue.

**Comment by TravisEz13** [comment]
This is partially done. I don't plan on doing any of the rest of the items.
