### ISSUE TITLE
Select-Object misbehaves with a property name that has a quoted component

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#6125]
Note: `Select-Object` fundamentally only supports _top-level property names_, not property _paths_.

With no quoting involved, the behavior is as follows:
A `.`-separated path argument is treated like a nonexistent top-level property name and:
* with `-Property`, causes a `$null`-valued property by that name to be created.
* with `-ExpandProperty`, causes an error that complains about the nonexistent property.

By contrast - and this smells like a bug - if you _quote_ a _component_ of a path-like property name, the input object is quietly passed through.

Steps to reproduce
------------------

```powershell
$obj = [pscustomobject] @{ dummy = 1 }

$obj | Select-Object -Property dummy.foo | out-default
'==='
$obj | Select-Object -Property 'dummy'.foo | out-default
'==='
$obj | Select-Object -ExpandProperty dummy.foo | out-default
'==='
$obj | Select-Object -ExpandProperty 'dummy'.foo | out-default
```

Expected behavior
-----------------

```none
dummy.foo
---------



===
dummy.foo
---------



===
Select-Object : Property "dummy.foo" cannot be found.
....
===
Select-Object : Property "dummy.foo" cannot be found.
....
```

Actual behavior
---------------

```none
dummy.foo
---------



===

dummy
-----
    1


===
Select-Object : Property "dummy.foo" cannot be found.
At C:\Users\MKT6\Desktop\pg\t.ps1:7 char:8
+ $obj | Select-Object -ExpandProperty dummy.foo | out-default
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (@{dummy=1}:PSObject) [Select-Object], PSArgumentException
    + FullyQualifiedErrorId : ExpandPropertyNotFound,Microsoft.PowerShell.Commands.SelectObjectCommand

===

dummy
-----
    1
```

Note how with the quoted path component the input object is simply passed through.

Environment data
----------------

```powershell
PowerShell Core v6.0.0-rc.2 (v6.0.0-rc.2) on Microsoft Windows 7 Enterprise  (64-bit; v6.1.7601)
Windows PowerShell v5.1.14409.1012 on Microsoft Windows 7 Enterprise  (64-bit; v6.1.7601)
```

**Comment by BrucePay** [comment]
Hi @mklement0 - I believe the problem has to do with the dot not the quotes (the dot problem is addressed in another issue). If the parser is in command mode and encounters an argument beginning with a quote, everything in the quotes is treated as the argument. Everything after the quotes is treated as the next argument:
```
PS > write-output "hi"there   # returns two arguments                                                                                                    
hi
there
PS > 
```
However, if the parser encounters a quote in the body of the argument, the entire string is taken as the argument:
```
PS > write-output oh" hi "there   # returns one argument                                                                                             
oh hi there
PS > 
```

**Comment by mklement0** [comment]
@BrucePay:

Actually, what's happening here is different: `'dummy'.foo` is evaluated as an _expression_, which means that `.foo` is interpreted as a _property access_ on string literal `'dummy'`, which yields `$null`.
(By contrast, if it were parsed as _two_ arguments, `Select-Object` would report an _error_, due to a now unbindable positional argument.)

That fact is more obvious if you use an existing property name:

```powershell
> Write-Output 'dummy'.Length
5
```

I'm closing this issue, but I'll address this behavior generally, along with the `"a"b`-`a"b"` asymmetry, in a new issue.

**Comment by mklement0** [comment]
@BrucePay: I've created #6467 to highlight the underlying issue (and others).
