### ISSUE TITLE
CTRL+V does not paste

### ISSUE THREAD

**Issue by ChadMcCaffery** [PowerShell/PowerShell#6126]
```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

#### Steps to reproduce
1. Open pwsh console
2. Type something
3. Highlight it and press [Ctrl]+C to copy it to the clipboard
4. Press [Esc] to clear the line
5. Press [Ctrl]+V to paste it
6. ``Remove-Module PSReadline``
7. Repeat steps 2 through 5

#### Result
1. With PSReadline loaded, no text is pasted.
2. After unloading PSReadline module, text is pasted correctly

#### Expected Behavior
Clipboard text is pasted regardless of PSReadline module being loaded

#### More Info
```powershell
Name              : PSReadLine
Path              : C:\program files\powershell\6.0.1\Modules\PSReadLine\PSReadLine.psd1
Description       : Great command line editing in the PowerShell console host
ModuleType        : Script
Version           : 1.2
NestedModules     : {Microsoft.PowerShell.PSReadLine}
ExportedFunctions : PSConsoleHostReadline
ExportedCmdlets   : {Get-PSReadlineKeyHandler, Set-PSReadlineKeyHandler, Remove-PSReadlineKeyHandler, Get-PSReadlineOption...}
ExportedVariables :
ExportedAliases   :
```
Pwsh Console window properties
![pwsh_props](https://user-images.githubusercontent.com/22089594/35921189-e3b0c468-0c11-11e8-8572-52366650cb9b.jpg)

**Comment by iSazonov** [comment]
@ChadMcCaffery Thanks for your report!
It is dup #4294
We'll get this with PSReadline 2.0.0
