### ISSUE TITLE
Is the Remove-item -Recurse bug present in PS6?

### ISSUE THREAD

**Issue by StingyJack** [PowerShell/PowerShell#6127]
From the [PS 5.1 docs](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/Remove-Item?view=powershell-5.1)

> Because the Recurse parameter in Remove-Item has a known issue, the command in this example uses Get-ChildItem to get the desired files, and then uses the pipeline operator to pass them to Remove-Item.

Did this get fixed in v6?

**Comment by iSazonov** [comment]
@StingyJack You fill free load latest PowerShell Core and check scenarios you want.

I believe it is dup #3727

**Comment by StingyJack** [comment]
I'll accept that dupe#
