### ISSUE TITLE
Test-ScriptFileInfo cannot complete if the script has parse errors

### ISSUE THREAD

**Issue by mgreenegit** [PowerShell/PowerShell#6128]
Steps to reproduce
------------------
Create script with scriptfileinfo.  Paste in DSC configuration that includes import-dscresources.  List modules that are not available.

```powershell
test-scriptfileinfo .\dscscript.ps1
```

Expected behavior
-----------------
Return the metadata about the script, most importantly the list of required modules so they can be loaded during test automation.

Actual behavior
---------------

```none
Test-ScriptFileInfo : The specified script file 'path\dscscript.ps1' has parse errors, try
again after fixing the parse errors.
```

The command cannot reveal the list of required modules, so that test automation can know which modules to install.  Ideally, the scriptfileinfo could be read even if the script body contains parse errors, as an "off by default" option.

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.0.0
PSEdition                      Core
GitCommitId                    v6.0.0
OS                             Microsoft Windows 10.0.17093
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
@mgreenegit this cmdlet comes from PSGet, you should open an issue there.
