### ISSUE TITLE
Feature-request: Windows update cmdlets

### ISSUE THREAD

**Issue by garegin16** [PowerShell/PowerShell#6129]
I know that Server releases have sconfig, but it seems that it’s a basic enough function that should have a CLI equivalent.

**Comment by RichardSiddaway** [comment]
This could get messy.  Windows Server 2016 and Windows Server 1709 use different CIM classes. Windows 10 uses one or the other CIM class depending on version. Pre Windows 10/Server 2016 you were required to use a COM object. The COM object and the Windows 1709 CIM class don't work if called remotely though the CIM class does work through a PowerShell direct session.

**Comment by SteveL-MSFT** [comment]
These cmdlets wouldn't be developed/owned by the PowerShell team.  I would creating/upvoting an issue on [UserVoice](https://windowsserver.uservoice.com/forums/295047-general-feedback)
