### ISSUE TITLE
Feature Request: Suppress sleep cmdlet

### ISSUE THREAD

**Issue by garegin16** [PowerShell/PowerShell#6130]
A caffeinate equivalent on Windows would be nice. It’s so annoying when you do updates and the computer goes to sleep

**Comment by bergmeister** [comment]
There is already a program called [NoSleep ](https://www.symantec.com/connect/downloads/readynosleepexe-prevents-screensaver-and-pc-locking)but I agree, this would be nice to have in PowerShell

**Comment by parkovski** [comment]
I'm using (this program)[https://github.com/iorate/win-caffeinate] on Windows, seems to work well.
