### ISSUE TITLE
Question: Concatenation of empty arrays

### ISSUE THREAD

**Issue by xenalite** [PowerShell/PowerShell#6131]
I have been reading this doc about arrays:
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_arrays?view=powershell-6#zero-objects

However, nowhere does it mention the effects of concatenating multiple nulls / empty arrays.
It seems concatenation of arrays in different order will yield different results.
I had problems with functions returning a singleton array, where the single element inside the array is a null rather than an empty array instead.

I can't class it as a bug, because I don't know what the expectation is in the language design. It does, however, seem counter intuitive and prone to bugs in scripts working with collections.

Steps to reproduce
------------------

```powershell
$a = @()
$b = $null

$a.Length + $b.Length
($a + $b).Length
($a += $b).Length

$a = @()
$b = $null

$b.Length + $a.Length
($b + $a).Length
($b += $a).Length
```

Expected behavior
-----------------

```powershell
0
0
0
0
0
0
```

Actual behavior
---------------

```powershell
0
1
1
0
0
0
```

It makes no difference as to how many elements `$a` is holding. If i run this:
```powershell
$a = @(1)
$b = $null

$a.Length + $b.Length
($a + $b).Length
($a += $b).Length

$a = @(1)
$b = $null

$b.Length + $a.Length
($b + $a).Length
($b += $a).Length
```

Output is:
```powershell
1
2
2
1
1
1
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by BrucePay** [comment]
Closing as it is marked "resolved" and no ones commented on it for a while.
