### ISSUE TITLE
where is Get-PSSnapin?

### ISSUE THREAD

**Issue by mallochine** [PowerShell/PowerShell#6135]
This function is not available on Centos 7: Get-PSSnapin

**Comment by stknohg** [comment]
PowerShell Core 6.0 no longer supports snap-ins.  
Cmdlets related to snap-ins(`Add-PSSnapin`, `Get-PSSnapin`, `Remove-PSSnapin`) don't exist.

See [breaking changes](https://github.com/PowerShell/PowerShell/blob/master/docs/BREAKINGCHANGES.md#custom-snap-ins) :

> Custom snap-ins
>  
> PowerShell snap-ins are a predecessor to PowerShell modules that do not have widespread adoption in the PowerShell community.
>  
> Due to the complexity of supporting snap-ins and their lack of usage in the community, we no longer support custom snap-ins in PowerShell Core.

Incidentally, maybe related to #2122.

**Comment by SteveL-MSFT** [comment]
@stknohg is correct, we removed custom PSSnapin support in PSCore6

**Comment by mallochine** [comment]
what is the easiest way for users to install cmdlets that my company may write as part of an SDK?

**Comment by SteveL-MSFT** [comment]
@mallochine best practice is to wrap the cmdlets as a module and then you can just xcopy the module folder to <user data directory>\powershell\modules

**Comment by mallochine** [comment]
is this something like where I provide a compiled DLL and my users can just download the DLL to that directory?

Where is the '\powershell\modules' directory on Linux?

**Comment by SteveL-MSFT** [comment]
@mallochine if it's something that can be public, the easiest way is to publish it to powershellgallery.com and then your users can just do `install-module <foo>` and it'll put it in the right place regardless of platform.

Unfortunately, we never completed the work to support leaving modules as a .zip archive so modules have to be a folder.  For a compiled assembly, it's really just having the folder with your .dll and a .psd1 module manifest file. 

On Linux, it should be ~/.local/share/powershell/modules
