### ISSUE TITLE
Need fix deb package names

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#6137]
deb packages still have "_" in name powershell_6.0.1-1.ubuntu.17.04_amd64.deb

**Comment by TravisEz13** [comment]
@iSazonov is there a requirements document somewhere that says that this is required?

**Comment by iSazonov** [comment]
I found it https://www.debian.org/doc/manuals/debian-reference/ch02.en.html#_debian_package_file_names

They use "_"  like `<package-name>_<epoch>:<upstream-version>-<debian.version>-<architecture>.deb`

So I close the Issue.
