### ISSUE TITLE
Minor issues with Restore-PSPester

### ISSUE THREAD

**Issue by anmenaga** [PowerShell/PowerShell#6143]
`build.psm1` was recently updated to use '`Save-Module`' in `Restore-PSPester `#6112 
Side effects of this update broke Docker package validation tests.
Specifically:
1) Now `Restore-PSPester` requires` -Destination `directory to exist and throws error if it doesn't; Previously `Restore-PSPester` was creating it.
![restorepester0](https://user-images.githubusercontent.com/11860095/36054648-7e13407e-0def-11e8-994a-677fe6e1d61c.png)

2) Default `-Destination` directory is NOT based on `PSModulePath`, but rather on a `(Get-PSOptions -DefaultToNew).Output`, which is not helpful at all since it requires to provide full path to the module in case pwsh is run from an installed package as opposed to built from clone repo.
![restorepester1](https://user-images.githubusercontent.com/11860095/36054653-81c861b8-0def-11e8-8dc5-576fd0a97bc7.png)

**Comment by iSazonov** [comment]
I don't still test - Is this works for VS Code debugging? - there another output path is.
