### ISSUE TITLE
RelationLink dictionary keys should be case-insensitive

### ISSUE THREAD

**Issue by markekraus** [PowerShell/PowerShell#6146]
Per RFC 8288, relation types on `Link` response headers MUST be compared in a case-insensitive fashion. HTTP servers SHOULD send relation types as all lower case, but parsing them MUST be case-insensitive. 

Currently, the `RelationLink` dictionary we create is case sensitive. This should be change to case-insensitive, An HTTP server sending more than one of the same relation type (case-insensitive) is not RFC compliant, therefore a case-insensitive dictionary should not encounter keys of the same characters with different casing.

https://github.com/PowerShell/PowerShell/blob/0ad9fc9d7057bbe50c77b7d297f102a68380918b/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs#L1593

Steps to reproduce
------------------

```powershell
$uri = 'https://api.github.com/repositories/49609581/issues?page=2'
$response = Invoke-WebRequest -Uri $Uri
$response.RelationLink.next -eq 'https://api.github.com/repositories/49609581/issues?page=3'
$response.RelationLink.Next -eq 'https://api.github.com/repositories/49609581/issues?page=3'
```

Expected behavior
-----------------

```none
True
True
```

Actual behavior
---------------

```none
True
False
```

Environment data
----------------

```none
Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment]
Confirm. The standard and previous say "MUST be case-insensitive". Need fix.

**Comment by markekraus** [comment]
I updated the issue language to be more in line with the RFC language. I was using "should" where I should have been using "must".
