### ISSUE TITLE
Built-in "sls" alias for Select-String has nonstandard name, should be "scs"

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#6148]
From the quibbles department:

According to [Approved Verbs for PowerShell Commands](https://docs.microsoft.com/en-us/powershell/developer/cmdlet/approved-verbs-for-windows-powershell-commands), the official alias prefix for `Select-*` cmdlets is `sc`, not `sl` (the latter is for `Split-*` cmdlets).

Therefore, the naming-convention-compliant alias for `Select-String` should be `scs`, not `sls`.

It's probably too late to remove `sls`, but we could add `scs`.

Either way, a note in the documentation would be helpful.

Environment data
----------------

```powershell
PowerShell Core v6.0.0
```

**Comment by HumanEquivalentUnit** [comment]
The documentation link is now dead, this looks like the new location: https://docs.microsoft.com/en-us/powershell/developer/cmdlet/approved-verbs-for-windows-powershell-commands

**Comment by mklement0** [comment]
Thanks, @HumanEquivalentUnit  - I've updated the OP.

**Comment by SteveL-MSFT** [comment]
@mklement0 you're right this is too late to change, but agree the docs should be updated for this exception.  cc @sdwheeler
