### ISSUE TITLE
Power shell script to get data from each subfolders

### ISSUE THREAD

**Issue by rajeshshishodia** [PowerShell/PowerShell#6152]
I have a folder inside this folder I have around 20 sub folders, each sub folder having .wav files and I have a power shell script using this script I am able to get data from a single folder, but I want to get data from all sub folders in one go when I click on main folder. Below is my power shell script. Please help me to modify my script.

What I have tried:

# Show an Open Folder Dialog and return the directory selected by the user.
function Read-FolderBrowserDialog([string]$Message, [string]$InitialDirectory, [switch]$NoNewFolderButton)
{
    $browseForFolderOptions = 0
    if ($NoNewFolderButton) { $browseForFolderOptions += 512 }

    $app = New-Object -ComObject Shell.Application
    $folder = $app.BrowseForFolder(0, $Message, $browseForFolderOptions, $InitialDirectory)
    if ($folder) { $selectedDirectory = $folder.Self.Path } else { $selectedDirectory = '' }
    [System.Runtime.Interopservices.Marshal]::ReleaseComObject($app) > $null
    return $selectedDirectory
}
$folder= Read-FolderBrowserDialog
$com = (New-Object -ComObject Shell.Application).NameSpace($folder)
for($i = 0; $i -lt 64; $i++) {
                $name = $com.GetDetailsOf($com.Items, $i)
                if ($name -eq 'Length') { $lengthattribute = $i}
}
$com.Items() |
ForEach-Object {
[PSCustomObject]@{
Name = $_.Name
Path = $_.Path
Size = $com.GetDetailsOf($_, 1)
DateCreated = $com.GetDetailsOf($_, 4)
Length = $com.GetDetailsOf($_, $lengthattribute)
}
} |
Export-csv report.csv -notypeinformation

**Comment by iSazonov** [comment]
@rajeshshishodia The repo is for PowerShell engine development.

You should ask help in other channels - slack.com, forums.

**Comment by BrucePay** [comment]
Hi @rajeshshishodia , I might be missing something. Is there a particular reason you are using com? It seems to make things more complicated than they need to be. The following pipeline should cover your high-level goal: get information about a group of *.wav files in a subdirectory:
`Get-ChildItem -Recurse *.cs | select Name, FullName, Length, LastWriteTime `
