### ISSUE TITLE
PowerShell Classes Typesafe?

### ISSUE THREAD

**Issue by constantinhager** [PowerShell/PowerShell#6158]
Steps to reproduce
------------------

```powershell

class Rock {
    [string]$Color
    [string]$Luster
    [string]$Shape
    [string]$Texture
    [string]$Pattern
    [string]$Size
    [int]$Location   
    }

$rock = [rock]::New()
$rock.Color = 1

```

Expected behavior
-----------------

```none
Error Message that Color is of Type String and not of type int
```

Actual behavior
---------------

```none
Color    : 1
Luster   :
Shape    :
Texture  :
Pattern  :
Size     :
Location : 0
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Microsoft Windows 10.0.17093
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

Additional Information
----------------
If I try to set the Location Variable with a string, It does the right thing.

```powershell
class Rock {
    [string]$Color
    [string]$Luster
    [string]$Shape
    [string]$Texture
    [string]$Pattern
    [string]$Size
    [int]$Location   
    }

$rock = [rock]::New()
$rock.Location = "Test"
```

Error Message:
```powershell
Exception setting "Location": "Cannot convert value "Test" to type "System.Int32". Error: "Input string was not in a correct format.""
At line:12 char:1
+ $rock.Location = "Test"
+ ~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
+ FullyQualifiedErrorId : ExceptionWhenSetting
```

Is this normal or am I doing something wrong?

**Comment by markekraus** [comment]
PowerShell is a shell and like many shells it performs some automatic type transformations for the user. 

```powershell
[int]$Int = "5"
$Int
[string]$String = 6.00
$string
[string]$String = 6
$string
```

```none
5
6
6
```

**Comment by iSazonov** [comment]
Do we need strict typing in strict mode?

**Comment by markekraus** [comment]
@iSazonov I don't thinks so. IMO, the nature of PowerShell is to handle many automatic type conversions. I think any attempt to take that away would just make PowerShell a thin wrapper for .NET. It would look more like Object Oriented Programming and less like command driven shell. the type conversions happen in so many places that users would find an option like that makes PowerShell very foreign. For example, so many parameters Enums and PowerShell handles the String to Enum conversion.

So, unless there was some way to limit it to just assignment operations, it wouldn't be a good idea, IMO. But, I'm not sure I see the value of doing it in the first place.

**Comment by constantinhager** [comment]
OK. Thank you for the information. In my opinion you can close the issue.
