### ISSUE TITLE
Hello, I'm interested in contributing to this project by offering a translation to the changelog, readme .md files, let me know if interested.

### ISSUE THREAD

**Issue by LuigiBaute** [PowerShell/PowerShell#6162]

**Comment by SteveL-MSFT** [comment]
@LuigiBaute this would be great!  Thanks for the offer!  What languages would you support?

**Comment by LuigiBaute** [comment]
@SteveL-MSFT Spanish if thats OK with you guys I'll start asap! :+1:

**Comment by SteveL-MSFT** [comment]
Just waiting on @joeyaiello to define how we should separate out different languages.
