### ISSUE TITLE
Enhancement: support a script block as the replacement operand of the -replace operator to enable dynamic substitutions 

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#6164]
**Wishful thinking**:

```powershell
# Script block as replacement operand allows dynamic substitutions.
# TBD: how to refer to the match at hand in the script block.
> 'Increment these numbers: 1 2 3' -replace '\d+', { [int] $Args.Value + 1 }   
Increment these numbers: 2 3 4
```

Sometimes string replacements need to be _dynamic_, i.e., the replacement string must be _derived from the match at hand_.

Consider the following (contrived example):

You want to increment all numbers in an input string; e.g.:  

`'Increment these numbers: 1 2 3'` -> `'Increment these numbers: 2 3 4'`

Currently, `-replace` doesn't support this type of replacement, because the replacement operand can only _statically_ refer to the match at hand (`$&` for the match in full, `$1` for the 1st capture group's match (if any), ...).

Thus, to achieve this kind of substitution the .NET Framework must currently be used:

```powershell
> [regex]::Replace('Increment these numbers: 1 2 3', '\d+', { param($match) [int] $match.Value + 1 })
Increment these numbers: 2 3 4
```

Needless to say, this is neither PowerShell-like nor simple.

---

Supporting the syntax as proposed at the top would greatly simplify such operations.

### Syntax details

The simplest approach is to use `[regex]::Replace()` as-is behind the scenes, and let  the script block reference the match at hand - which is passed as a `[System.Text.RegularExpressions.Match]` instance - via `$Args` (or, optionally, an explicitly defined parameter via `param()`).

The alternative is to stick with the `$&`, `$1`, ... syntax, but that would require behind-the-scenes manipulation of the script block.

### Backward-compatibility considerations

Currently, attempting to use a script block as the replacement operand simply _stringifies_ that block (i.e., uses its _string contents_ as the replacement string).

Since this behavior isn't useful, it's hard to imagine anyone relying on it, so this change probably falls into [Bucket 3: Unlikely Grey Area](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md#bucket-3-unlikely-grey-area)

Environment data
----------------

Written as of  PowerShell Core v6.0.1

**Comment by lzybkr** [comment]
This is approved in in review, see https://github.com/PowerShell/PowerShell/pull/6029

**Comment by LaurentDardenne** [comment]
To allow [this call](https://msdn.microsoft.com/en-us/library/ms149474(v=vs.110).aspx) would also be appreciated :
```powershell
'Increment these numbers: 1 2 3' -replace '\d +', {[int] $ Args.Value + 1}, $Count, $StartAt
```

**Comment by iSazonov** [comment]
@LaurentDardenne Please open new issue for your suggestion.
