### ISSUE TITLE
WCF client fails on Linux but works on Windows

### ISSUE THREAD

**Issue by pkjaer** [PowerShell/PowerShell#6168]
I'm having some issues calling a WCF service from Linux. 
The same code works fine on Windows. 

I'm getting this error when trying to use basic authentication:

`The HTTP request is unauthorized with client authentication scheme 'Basic'. The authentication header received from the server was 'Basic realm="local.realm"'.
`

The service is hosted in IIS on a Windows machine.
Unfortunately, I cannot share the web service or the code behind it.

The client was generated as a "Connected Service" in Visual Studio 2017.
The source code for the module is available on GitHub:
https://github.com/pkjaer/tridion-powershell-modules/tree/pwsh-core-support/Tridion.Community.PowerShell

Specifically, the generated client is here:
https://github.com/pkjaer/tridion-powershell-modules/blob/pwsh-core-support/Tridion.Community.PowerShell/Tridion.Community.PowerShell/Connected%20Services/CoreService/Reference.cs

And the class that sets up the bindings and such is here:
https://github.com/pkjaer/tridion-powershell-modules/blob/pwsh-core-support/Tridion.Community.PowerShell/Tridion.Community.PowerShell/Client.cs

None of the bindings work on Linux currently, but I figured the `BasicHttpBinding` would be the easiest to get running first.

Since it works in PowerShell 6 on a Windows machine, but not on Linux, I'm thinking there is something in the OS that behaves differently. 

Expected behavior
-----------------

The client is able to communicate with the WCF service using Basic authentication and a BasicHttpBinding.

Actual behavior
---------------
Any call to the service gives the following error:

```
The HTTP request is unauthorized with client authentication scheme 'Basic'. 
The authentication header received from the server was 'Basic realm="local.realm"'.

```

Environment data
----------------

```powershell
Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.1                                           
PSEdition                      Core                                            
GitCommitId                    v6.0.1                                          
OS                             Linux 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu D...
Platform                       Unix                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1                                         
WSManStackVersion              3.0                                             
 
```
(Above is for RHEL but I've tried Ubuntu (16 & 17) as well, with the same result)

**Comment by pkjaer** [comment]
No one has any ideas?

**Comment by iSazonov** [comment]
@markekraus Could you please look the Issue? 
@pkjaer Could you please create more simple repo so we can debug?

**Comment by markekraus** [comment]
@pkjaer Looking at the code one issue I potentially see is that the settings is using a PSCredential object imported from `Import-Clixml`. On Linux, you cannot serialize PSCredential objects to CLIXML because `SecureString` does not have Windows DPAPI to encrypt/decrypt the secrets with. The result is that null is likely being used for the user/password when WCF client sends the basic auth.

**Comment by iSazonov** [comment]
> On Linux, you cannot serialize PSCredential objects to CLIXML because SecureString does not have Windows DPAPI to encrypt/decrypt the secrets with.

Based on the Issue should we throw (PlatformNotSupportedException) in this situation?

**Comment by pkjaer** [comment]
@markekraus That's great info! Is there an alternative that will allow me to store the credentials between sessions, on all supported platforms?

I will double-check, but I believe I was testing it with credentials specified directly in the parameters to the function (not loading it from a file). So I don't think that is the root issue, in this case.

**Comment by markekraus** [comment]
> Is there an alternative that will allow me to store the credentials between sessions, on all supported platforms?

Currently, no. There is a "community" project in its infancy to create a cross-platform and cross-version password storage and retrieval solution that allow you to bring your own secure storage (such as KeePass, DPAPI, encrypted sqlite, etc) through a PSProvider drive. But it's still in the conceptualization phase and is mostly the brainchild of @Jaykul. 

You can still use some form of encrypted store, but you will have a "chicken and egg" scenario where you have to store the secret to unlock the encrypted secret in plain text.

On Linux, the common practice for secrets is to store them in plain text in a file or as an environment variable. (Assuming the system is not shared and you are the owner). You could allow for password override based on the presence of an environment variable in your settings restore functions. You can still convert a plain-text string to  SecureString in Linux to attach to the PSCredential object. On windows you could still store the password in CLIXML file and on Linux you could store the password in an environment variable and the module logic would determine which to use.

**Comment by markekraus** [comment]
@iSazonov I think in this case the errors were being suppressed because it should have been noticeable. If you try to import a CLIXML that has a SceureString in it (which you would need to have copied from another computer or something), you get `Unable to load DLL 'CRYPT32.dll': The specified module or one of its dependencies could not be found.` on Linux/macOS/not-windows. You get the same when you try to export a `SecureString`.

I think there is an open issue on improving that message already.

**Comment by iSazonov** [comment]
@markekraus Thanks for remainder - the Issue https://github.com/PowerShell/PowerShell/issues/1654
