### ISSUE TITLE
Method `.Trim()` removes additional "e" from string

### ISSUE THREAD

**Issue by dustinmoris** [PowerShell/PowerShell#6174]
This is an extremely weird one...

Steps to reproduce
------------------

```powershell
> "GiraffeTestsPaketApp".Trim("App").Trim("Paket").Trim("Tests")
Giraff
```

Expected behavior
-----------------

```none
Giraffe
```

Actual behavior
---------------

```none
Giraff
```

This only happens when the last letter of the remaining string has an "e". If I'd change the initial string to "DogTestsPaketApp" then it would work as expected:

```powershell
> "DogTestsPaketApp".Trim("App").Trim("Paket").Trim("Tests")
Dog
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-rc
PSEdition                      Core
GitCommitId                    v6.0.0-rc
OS                             Darwin 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Updated to the latest release and still get the same wrong behaviour:

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Darwin 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Workaround
----------------

I can currently work around this issue by running:

```powershell
> "GiraffeTestsPaketApp".Replace("App", "").Replace("Paket", "").Replace("Tests", "")
Giraffe
```

**Comment by thezim** [comment]
This is by [design](https://docs.microsoft.com/en-us/dotnet/api/system.string.trim?view=netframework-4.7.1#System_String_Trim) in .NET and not a PowerShell issue.

> The Trim method removes from the current string all leading and trailing characters that are in the trimChars parameter. Each leading and trailing trim operation stops when a character that is not in trimChars is encountered. For example, if the current string is "123abc456xyz789" and trimChars contains the digits from "1" through "9", the Trim method returns "abc456xyz".

The `e` is being trimmed because it being matched by one of the provided characters in the array `T`,`e`,`s`,`t`,`s`.

**Comment by dustinmoris** [comment]
Oh wow.. this was unexpected. I thought a string would be treated as a whole string, otherwise I would have passed in a char array if I wanted to trim individual chars. Weird design choice IMHO...
