### ISSUE TITLE
Get-Command -ParameterName computername returns cmdlets that should not be

### ISSUE THREAD

**Issue by apetitjean** [PowerShell/PowerShell#6175]
I saw this issue with both Windows PowerShell 5.1 and PowerShell Core 6.0.1

Steps to reproduce
------------------

```powershell
Get-Command -ParameterName computername | Select-Object -ExpandProperty Name

Connect-PSSession
Connect-WSMan
Disconnect-WSMan
Enter-PSSession
Get-PSSession
Get-WSManInstance
Invoke-Command
Invoke-WSManAction
New-PSSession
New-WSManInstance
Receive-Job
Receive-PSSession
Remove-PSSession
Remove-WSManInstance
Rename-Computer
Restart-Computer
Send-MailMessage
Set-WSManInstance
Stop-Computer
Test-WSMan

```

Expected behavior
-----------------

The result should not return Send-MailMessage because this cmdlet does not have a such parameter (it's an alias on SMTPServer).

This is hence not consistent with the result of:

```powershell
Get-Help * -parameter computername

```

Environment data
----------------

```powershell
$PSVersionTable

Name                           Value                                                                                                                                
----                           -----                                                                                                                                
PSVersion                      6.0.1                                                                                                                                
PSEdition                      Core                                                                                                                                 
GitCommitId                    v6.0.1                                                                                                                               
OS                             Microsoft Windows 10.0.14393                                                                                                         
Platform                       Win32NT                                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                              
PSRemotingProtocolVersion      2.3                                                                                                                                  
SerializationVersion           1.1.0.1                                                                                                                              
WSManStackVersion              3.0                                                                                                                                  

```

**Comment by mklement0** [comment]
`Get-Command -ParameterName` - unlike `Get-Help -Parameter` - also matches _parameter aliases_.

Thus, `Get-Command -ParameterName ComputerName` includes `Send-MailMessage`, because the latter's `SmtpServer` parameter has the alias name `ComputerName`, as the following command demonstrates.

```powershell
> (Get-Command Send-MailMessage).Parameters.SmtpServer.Aliases
ComputerName
```

This inconsistency between `Get-Command` and `Get-Help` is worth addressing (though, as your post shows, the inclusion of parameter aliases can be confusing).

Note that with a specific cmdlet / advanced-function name you _can_ discover alias names with `Get-Help`, but only if you know the _original_ parameter name:

```powershell
# Note the 'Aliases' output line.
> Get-Help Send-MailMessage -Parameter SmtpServer

-SmtpServer <string>
    
    Required?                    false
    Position?                    3
    Accept pipeline input?       false
    Parameter set name           (All)
    Aliases                      ComputerName
    Dynamic?                     false
    
```

I've created #6183 to track this.

**Comment by apetitjean** [comment]
To me, there's no interest to search by parameter aliases. I would prefer that both cmdlets do not return them because in this specific case I want to *only* get the real parameter names and *not* the aliases.

That being said, we agree that in this context both cmdlets should return the same result ;-).

**Comment by mklement0** [comment]
@apetitjean:

Understood (I had missed that you were already aware of the alias-name issue).

My sense is that alias names _should_ be considered, at least _by default_, as that is consistent with how _command_ alias names are treated (by _both_ `Get-Command` and `Get-Help` - try `Get-Command gci` and `Get-Help gci`, for instance).

The - cumbersome - _workaround_ for what you're trying to do is:

```powershell
Get-Command -ParameterName computername | ? { $_.Parameters.ContainsKey('ComputerName') }
```

If you feel strongly enough that (opt-in) support for ignoring alias names should be built in, say via a new `-NoAlias` switch, I encourage you to revise your original post accordingly - as it stands, it doesn't adequately reflect the general issue we're discussing here.

**Comment by apetitjean** [comment]
Whatever you prefer! But what I would like is consistency.

**Comment by mklement0** [comment]
@apetitjean: I agree re consistency, but what was I trying to say in my previous comment was:

_If_ the current inconsistency gets resolved the way I'm suggesting (and it's just that - a suggestion) and you feel that ignoring aliases should at least be available _on demand_, without needing a workaround, you should ask for that - either by revising this issue's title and first post or by creating a new issue.

**Comment by SteveL-MSFT** [comment]
I believe the current behavior is working as designed.  For most users, they want the alias as they can use it the same as a parameter name.  Instead of a `-NoAlias` switch, perhaps adding a property to the output on whether the parametername is an alias making filtering more intuitive.

**Comment by mklement0** [comment]
@SteveL-MSFT: I agree, though a property won't help in this case, because the `-ParameterName` parameter acts as a _filter_ for returning _commands_; that is, you're not getting _parameter_ information back (where a property might help).

**Comment by SteveL-MSFT** [comment]
@mklement0 I was thinking a script property that would do additional gathering
