### ISSUE TITLE
Compiling powershell in an offline environment

### ISSUE THREAD

**Issue by trikotrako** [PowerShell/PowerShell#6178]
I've tried to compile Powershell when there wasn't available internet access, and the 'dotnet restore' command failed even though i have compiled Powershell before and I have all the nuget packages needed.

The error was: 

Restoring packages for C:\git\PowerShell\src\Microsoft.Management.Infrastructure.CimCmdlets\Microsoft.Management.Infrastructure.CimCmdlets.csproj...
C:\Program Files\dotnet\sdk\2.1.4\NuGet.targets(103,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\git\PowerShell\PowerShell-Win.sln]
C:\Program Files\dotnet\sdk\2.1.4\NuGet.targets(103,5): error :   An error occurred while sending the request. [C:\git\PowerShell\PowerShell-Win.sln]
C:\Program Files\dotnet\sdk\2.1.4\NuGet.targets(103,5): error :   The server name or address could not be resolved [C:\git\PowerShell\PowerShell-Win.sln]

which is obvious because i didn't have internet access.
I tried to remove the sources from nuget.config file, but i got the error:

Restoring packages for C:\git\PowerShell\src\Microsoft.Management.Infrastructure.CimCmdlets\Microsoft.Management.Infrastructure.CimCmdlets.csproj...
C:\git\PowerShell\src\Microsoft.Management.Infrastructure.CimCmdlets\Microsoft.Management.Infrastructure.CimCmdlets.csproj : error NU1100: Unable to resolve 'Microsoft.Management.Infrastructure (>= 1.0.0-alpha)' for '.NETCoreApp,Version=v2.0'. [C:\git\PowerShell\PowerShell-Win.sln]
C:\git\PowerShell\src\Microsoft.Management.Infrastructure.CimCmdlets\Microsoft.Management.Infrastructure.CimCmdlets.csproj : error NU1100: Unable to resolve 'PowerShell.Core.Instrumentation (>= 6.0.0-beta)' for '.NETCoreApp,Version=v2.0'. [C:\git\PowerShell\PowerShell-Win.sln]

even though i do have these packages in the ~\.nuget\packages folder.

any ideas how to solve this?

**Comment by azstate** [comment]
I have the internet connection but getting the same error while Docker build. If I run dotnet restore manually, it works. If I try to run from dockerfile, it fails with error 

Step 1/10 : FROM microsoft/dotnet:sdk AS build-env
 ---> 21113273c8c7
Step 2/10 : WORKDIR /app
 ---> Using cache
 ---> eca84d90c802
Step 3/10 : COPY *.csproj ./
 ---> Using cache
 ---> 34e3b3aefc35
Step 4/10 : RUN dotnet restore
 ---> Running in dba5d43d9b7a
  Restoring packages for C:\app\FileUploader.csproj...
  Restoring packages for C:\app\FileUploader.csproj...
C:\Program Files\dotnet\sdk\2.1.4\NuGet.targets(103,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\app\FileUploader.csproj
C:\Program Files\dotnet\sdk\2.1.4\NuGet.targets(103,5): error :   An error occurred while sending the request. [C:\app\FileUploader.csproj]
C:\Program Files\dotnet\sdk\2.1.4\NuGet.targets(103,5): error :   The operation timed out [C:\app\FileUploader.csproj]
The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; dotnet restore' returned a non-zero code: 1


My dockefile:

FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app
COPY *.csproj ./
RUN dotnet restore
COPY . ./
RUN dotnet publish -c Release -o out
FROM microsoft/dotnet:runtime
WORKDIR /app
COPY --from=build-env /app/out ./
ENTRYPOINT ["dotnet", "run"]

**Comment by azstate** [comment]
anybody is facing similar issue?

**Comment by SteveL-MSFT** [comment]
I don't think there's anything we can do here.  I would suggest continuing this discussion in this dotnetcli issue https://github.com/dotnet/cli/issues/5815

**Comment by fibonaccho** [comment]
Does anybody get a solution about this?
