### ISSUE TITLE
Treat C# XML comment warnings as errors

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#618]
## Motivation
Windows build treat C# xml comments warnings as errors and so should we, to enable bringing changes back to windows.

### Example

https://github.com/PowerShell/psl-monad/blob/e0dc79b0744bba098e931a8266df97da478eccda/monad/src/engine/remoting/fanin/WSManPlugin.cs#L1149

`PerformWSManPluginStopShell` comment has mismatch with the signature. It should be compile error.

**Comment by andschwa** [comment]
This is implemented per https://github.com/PowerShell/PowerShell/pull/1428. There are some exceptions made, but I think I can close this now.
