### ISSUE TITLE
Get-Help -Parameter does not find parameter aliases

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#6183]
In order to get help for a parameter only the _original_ name is recognized by `Get-Help -Parameter`.

It should be possible to ask for parameter help by alias names too, similar to how `Get-Command -ParameterName ad` is able to locate `Get-ChildItem` via (any of) the `Directory` parameter's alias names, such as `ad`.

Steps to reproduce
------------------

```powershell
# Ask for help by original parameter name.
Get-Help -Parameter Directory Get-ChildItem

# Ask for help by parameter *alias*.
Get-Help -Parameter ad Get-ChildItem
```

Expected behavior
-----------------

Both commands should output details about the specified parameter, irrespective of whether the original name or an alias was used.

Actual behavior
---------------

```none

-Directory
    
    Required?                    false
    Position?                    Named
    Accept pipeline input?       false
    Parameter set name           (All)
    Aliases                      ad, d
    Dynamic?                     true
    

Get-Help : No parameter matches criteria ad.
At line:1 char:1
+ Get-Help -Parameter ad Get-ChildItem
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (System.Manageme...CommandHelpInfo:ProviderCommandHelpInfo) [Get-Help], PSArgumentException
+ FullyQualifiedErrorId : NoParmsFound,Microsoft.PowerShell.Commands.GetHelpCommand
 ```

That is, asking for `-Directory` via an _alias name_ failed.

Environment data
----------------

```powershell
PowerShell Core v6.0.1 on macOS 10.13.3
PowerShell Core v6.0.1 on Ubuntu 16.04.3 LTS
PowerShell Core v6.0.1 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
Windows PowerShell v5.1.15063.674 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by DJackman123** [comment]
Actually, the "actual behavior" you have here doesn't even match what Get-Help returns today.  When I execute `Get-Help -Parameter Directory Get-ChildItem` today (with PowerShell 7.1.3) it doesn't say anything about aliases, dynamic, or parameters sets:

```
-Directory <System.Management.Automation.SwitchParameter>
    To get a list of directories, use the Directory parameter or the Attributes parameter with the Directory property. You can use the Recurse parameter with Directory .

    Required?                    false
    Position?                    named
    Default value                False
    Accept pipeline input?       False
    Accept wildcard characters?  false
```

I'd love to see Get-Help not only accept parameters aliases but show what the parameter aliases are (again).  Is that something that should be a separate issue?

**Comment by mklement0** [comment]
Good point, @DJackman123 - this information is also missing in the current LTS version (7.0.5)

Yes, I suggest opening a separate issue.

**Comment by DJackman123** [comment]
Looks like it's already reported in issue #7381.
