### ISSUE TITLE
libcurl dependency on openSUSE

### ISSUE THREAD

**Issue by Arnavion** [PowerShell/PowerShell#6184]
From `docs/installation/linux.md`:

>Note: When installing PowerShell Core, OpenSUSE may report that nothing provides `libcurl`. `libcurl` should already be installed on supported versions of OpenSUSE. Run `zypper search libcurl` to confirm. The error will present 2 'solutions'. Choose 'Solution 2' to continue installing PowerShell Core.

1. If the intention is that the user should choose the `break powershell-6.0.1-1.rhel.7.x86_64 by ignoring some of its dependencies` option, then describing the option text explicitly ("Choose the solution to ignore dependencies and install the package anyway.") would be better. I don't believe zypper has to deterministically give that one as "Solution 2" and it's a vague instruction anyway.

1. It would be better to tell users to run `zypper search --provides --match-exact '/usr/lib64/libcurl.so.4'` instead of just `zypper search libcurl` to verify that they have the required library. The current command finds all packages that have `libcurl` in the name. While it's obvious which package the user should be looking for, there's no reason to be vague about it.

1. I assume this situation happens because you reuse the RHEL package for openSUSE and RHEL's libcurl package provides "libcurl". Why not make a separate package for openSUSE that requires "libcurl4" so that this workaround is not needed in the first place?

**Comment by iSazonov** [comment]
Perhaps we'll use .Net Core 2.1 in the next release and the behavior can be changed.

**Comment by markekraus** [comment]
@iSazonov are they for sure going to have the managed HTTP solution baked into .NET Core 2.1.x? I tried to figure out where they were at on that, but was only able to find vague mentions of it.
I will be very happy to be rid of this painful relationship with libcurl.

**Comment by iSazonov** [comment]
I believe we could ask them directly about managed httpclient. Previously I saw md file about this.
I also saw a recent PR which makes searching for *.so more reliable.

**Comment by Arnavion** [comment]
(Note that (1) and (2) are doc fixes and could be done now.)

**Comment by iSazonov** [comment]
@Arnavion Feel free to create PR.

**Comment by Arnavion** [comment]
Opened a PR.

**Comment by Arnavion** [comment]
>>Perhaps we'll use .Net Core 2.1 in the next release and the behavior can be changed.
>are they for sure going to have the managed HTTP solution baked into .NET Core 2.1.x? I tried to figure out where they were at on that, but was only able to find vague mentions of it.

FYI, [the blog post for 2.1.300-preview2 says it has the managed HTTP implementation.](https://blogs.msdn.microsoft.com/dotnet/2018/04/11/announcing-net-core-2-1-preview-2/#user-content-sockets-performance-and-socketshttphandler)

**Comment by iSazonov** [comment]
@Arnavion Thanks for the reference! It is good news. 

@daxian-dbw @SteveL-MSFT .Net Core 2.1 **Preview2** is released. Seems they fixed tons bugs. Is we ready to migrate?

**Comment by SteveL-MSFT** [comment]
I think we should move to Preview2 before our next 6.1 Preview release

**Comment by iSazonov** [comment]
Tracking Issue #6632

**Comment by Arnavion** [comment]
Since the 2.1 port was done and 2.1 was released today, I assume it's final that the next PS major release will use it? If so, should this issue target 1) removing the libcurl required dependency from the RHEL rpm package,  and 2) removing the note in the OP from the docs?

**Comment by iSazonov** [comment]
@Arnavion We is already on 2.1 RC1 :-) And yes, next release will be on 2.1.
We have to review our packaging and doc. Feel free to contribute!

**Comment by Arnavion** [comment]
This is done now.
