### ISSUE TITLE
For better DSL

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#6194]
this code work

```
function a 
{
   b {
        write-host 'hello'
   }
}

function b 
{
   param([scriptblock]$sb)
   &$sb
}
```

but this don't work because the character {

```
function a 
{
   b 
  {
        write-host 'hello'
   }
}

function b 
{
   param([scriptblock]$sb)
   &$sb
}
```

```
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-rc.2
PSEdition                      Core
GitCommitId                    v6.0.0-rc.2
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by markekraus** [comment]
I can't see how this could ever be added.

```powershell
b
{
    write-host 'hello'
}
```

Would currently returns the result of `b` and `scriptblock`. That may be desirable and changing the behavior would break the old behavior. This will probably not be doable with functions, but perhaps a new language keyword to distinguish DSL elements.

something like

```powershell
function a 
{
   b 
  {
        write-host 'hello'
   }
}

DSLfunction b 
{
   param([scriptblock]$sb)
   &$sb
}
```

This is the reason I highly recommend OTBS or Stroustrup indentation in PowerShell. There are far fewer places you can use Allman and friends.

**Comment by lzybkr** [comment]
Dynamic keywords enable this scenario (first introduced with DSC).

This #3169 was an attempt at properly supporting DSLs in PowerShell.

**Comment by markekraus** [comment]
@lzybkr awesome!
@p0W3RH311 

here is how you could make that work now:

```powershell
$keyword = [System.Management.Automation.Language.DynamicKeyword]@{
    Keyword ="b"
    BodyMode = [Management.Automation.Language.DynamicKeywordBodyMode]::ScriptBlock
    NameMode = [Management.Automation.Language.DynamicKeywordNameMode]::NoName
}
[System.Management.Automation.Language.DynamicKeyword]::AddKeyword($keyword)

function a 
{
   b 
  {
        write-host 'hello'
   }
}

function b 
{
    param (
        [Management.Automation.Language.DynamicKeyword] $KeywordData,
        $Name,
        [ScriptBlock] $Value,
        $SourceMetaData,
        $InstanceName
    )
   & $Value
}

a
```

**Comment by p0W3RH311** [comment]
@markekraus 

PowerShell v6.0.0-rc.2
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

```
PS C:\Users\My\Desktop> & 'C:\Users\walid\My\TEST.PS1'
The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command n
ame, a script block, or a CommandInfo object.
At C:\Users\My\Desktop\TEST.PS1:25 char:6
+    & $Value
+      ~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : BadExpression


        write-host 'hello'

```

**Comment by markekraus** [comment]
Heh.. that's weird. works if I do this:

Test.ps1:

```powershell
$keyword = [System.Management.Automation.Language.DynamicKeyword]@{
    Keyword ="b"
    BodyMode = [Management.Automation.Language.DynamicKeywordBodyMode]::ScriptBlock
    NameMode = [Management.Automation.Language.DynamicKeywordNameMode]::NoName
}
[System.Management.Automation.Language.DynamicKeyword]::AddKeyword($keyword)

. .\Test2.ps1
```

Test2.ps1:

```powershell
function b 
{
    param (
        [Management.Automation.Language.DynamicKeyword] $KeywordData,
        $Name,
        [ScriptBlock] $Value,
        $SourceMetaData,
        $InstanceName
    )
   & $Value
}

function a 
{
   b 
  {
        write-host 'hello'
   }
}

a
```

then run `& .\Test.ps1`

When I was tasting this out I was doing it with the interactive console on VS Code and executing a block at a time. It appears to not work when used in the same execution block, but if you can separate it out it works. i dunno. I didn't even know this existed until @lzybkr's comment in this issue.

**Comment by lzybkr** [comment]
There's a reason it's not formally supported yet.

**Comment by rjmholt** [comment]
Yes, the parser has rules in it for `DynamicKeyword`s that let you do things like hang the braces, and #3169 extends that so you can nest keyword contexts, but there are still issues with making the keyword functionality robust and predictable enough and they require some work to solve.
