### ISSUE TITLE
Ubuntu based Docker images have unnecessary apt cache bloat

### ISSUE THREAD

**Issue by MichaelSimons** [PowerShell/PowerShell#6213]
The Dockerfiles for the ubuntu images do not follow the [best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run).  They do not remove the apt cache thus causing docker images to be larger than necessary.

An illustration of this is the following instruction. https://github.com/PowerShell/PowerShell/blob/master/docker/release/ubuntu16.04/Dockerfile#L47
```
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
	powershell
```

It should include 
```
&& rm -rf /var/lib/apt/lists/*
```
which is done in the previous apt-get instruction at https://github.com/PowerShell/PowerShell/blob/master/docker/release/ubuntu16.04/Dockerfile#L26

Cleaning up the apt cache in the ubuntu 14.04 image will reduce the image size by 21MB (5%).

**Comment by iSazonov** [comment]
@MichaelSimons Thanks! Good catch!
