### ISSUE TITLE
Need to use 600000000 to set 60 seconds timeout in System.Management.Automation.Remoting.PSSessionOption

### ISSUE THREAD

**Issue by sh0375** [PowerShell/PowerShell#6216]
Steps to reproduce
------------------

```powershell
$PSSessionOptionOverride = New-Object System.Management.Automation.Remoting.PSSessionOption -Property  @{'CancelTimeout'=15000;'OperationTimeout'=45000;'IdleTimeout'=60000;'OpenTimeout'=15000}
```

Expected behavior
-----------------

```powershell
$PSSessionOptionOverride

OperationTimeout                  : 00:00:45
OpenTimeout                       : 00:00:15
CancelTimeout                     : 00:00:15
IdleTimeout                       : 00:01:00
```

Actual behavior
---------------

```powershell

$PSSessionOptionOverride                                                                                                                                                                            

OperationTimeout                  : 00:00:00.0045000
OpenTimeout                       : 00:00:00.0015000
CancelTimeout                     : 00:00:00.0015000
IdleTimeout                       : 00:00:00.0060000
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Linux 3.13.0-141-generic #190-Ubuntu SMP Fri Jan 19 12:52:38 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by vinodc** [comment]
I believe in the 6.0.0 beta1, this correctly accepted values in milliseconds rather than 10^-7 seconds increments.

**Comment by sh0375** [comment]
On windows I see same results as in 6.0.1:

PS C:\Users\Sergey.Nikulin> $PSSessionOptionOverride = New-Object System.Managem
ent.Automation.Remoting.PSSessionOption -Property  @{'CancelTimeout'=15000;'Oper
ationTimeout'=45000;'IdleTimeout'=60000;'OpenTimeout'=15000}
PS C:\Users\Sergey.Nikulin> $PSSessionOptionOverride

OpenTimeout                       : 00:00:00.0015000
CancelTimeout                     : 00:00:00.0015000
IdleTimeout                       : 00:00:00.0060000

So 6.0.1 is working correctly perhaps

**Comment by JustinGrote** [comment]
FYI it's a duration property, so you can do string representations like '00:00:60' instead and it will translate to the proper amount of time.
