### ISSUE TITLE
Low performance when transferring long arrays from PSSession

### ISSUE THREAD

**Issue by psmolkin** [PowerShell/PowerShell#6229]
I faced with the performance problem when I tried to recive a long array (e.c. file system entries) from remote pssession. The transfer of such an array takes a long time. Unfortunately it is obvious that Powershell has problems with it.

Steps to reproduce
------------------

```powershell

$session = New-PSSession localhost
# or
# $session = New-PSSession -HostName localhost -UserName <username>

$arrayLen = 1024000
Measure-Command{
  Invoke-Command -Session $session -ScriptBlock {
    Write-Host ("Preparing test array {0} elements length..." -f $using:arrayLen)
    $global:result = [Byte[]]::new($using:arrayLen)
    [System.Random]::new().NextBytes($result)
  }
} |% {Write-Host ("Completed in {0} sec`n" -f $_.TotalSeconds)}

Measure-Command{
  Invoke-Command -Session $session -ScriptBlock {
    Write-Host ("Transfer array ({0})" -f $using:arrayLen)
    return $result
  } | Out-Null
} |% {Write-Host ("Completed in {0} sec`n" -f $_.TotalSeconds)}

Measure-Command{
  Invoke-Command -Session $session -ScriptBlock {
    Write-Host ("Transfer same array nested in a single object")
    return @{array = $result}
  } 
} |% {Write-Host ("Completed in {0} sec`n" -f $_.TotalSeconds)}
```

Expected behavior
-----------------

```none
less than a second.
```

Actual behavior
---------------

```none
Preparing test array 1024000 elements length...
Completed in 0.0211385 sec

Transfer array (1024000)
Completed in 48.0192142 sec

Transfer same array nested in a single object
Completed in 0.0990711 sec
```

Environment data
----------------

```none
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Microsoft Windows 10.0.17074
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
Previous versions have the same problem

**Comment by PetSerAl** [comment]
Use `return ,$result`, otherwise you are transferring 1024000 individual bytes instead of one byte array.

**Comment by PetSerAl** [comment]
@iSazonov
IMHO, not really related to remoting. You can see similar difference in time without remoting envolved:

```powershell
$Array = [byte[]]::new(1024000)
(Measure-Command { ,$Array | Out-Null }).TotalMilliseconds
(Measure-Command { $Array | Out-Null }).TotalMilliseconds
```

**Comment by iSazonov** [comment]
@PetSerAl Thanks for the sample! I see that pipeline add 50% time (I believe it is expected) but in original message with remoting we are slow in many times.

**Comment by psmolkin** [comment]
@PetSerAl Thanks for your explanation! I've understood why this happens, but I think that this behavior is not obvious and should be corrected

**Comment by SteveL-MSFT** [comment]
The current behavior is "expected" in that it's a difference of passing an array vs passing elements of an array through the pipeline.  Certainly we should continue to improve the performance of the pipeline.
