### ISSUE TITLE
FailFast: padding is not correct

### ISSUE THREAD

**Issue by sayujshajith** [PowerShell/PowerShell#6234]
Description
------------------
Running Start-DevPowerShell or running the executable "pwsh.exe" results in new PowerShell window, but once you enter any table command, the window crashes. 

Noticed that this error occurs with fixes for pull request #5568 
Works with earlier versions however.

https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs#L501

Assert Statement Fails

Steps to reproduce 
------------------
Run the v6.0.1 executable "pwsh.exe" from the 5.1 launcher or type Start-DevPowerShell
```powershell
Start-DevPowerShell
```
Then type in any table view command such as: 
```powershell
ls
```
Expected behavior
-----------------
Should run PowerShell v6.0.1 in a new window without crashes 

Actual behavior
---------------
Initially opens PowerShell v6.0.1, but when you type in any table view command, the window crashes. 

Environment data
----------------

When checking the version table in the original PowerShell Window:
```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.15063.909
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.909
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
After running the pwsh in one instance within the same window:
```powershell
> pwsh
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vors** [comment]
@sayujshajith can you, please copy the crash trace and message?

**Comment by sayujshajith** [comment]
Pull Request #6230 fixes this issue.
