### ISSUE TITLE
Ubuntu 16.04 installation guide is broken

### ISSUE THREAD

**Issue by chipitsine** [PowerShell/PowerShell#6242]
Steps to reproduce
------------------

I followed official guide to install powershell on 16.04

https://gitlab.com/chipitsine/powershell/blob/master/.gitlab-ci.yml  (it's ubuntu 16.04 within docker)

Expected behavior
-----------------

should work

Actual behavior
---------------

https://gitlab.com/chipitsine/powershell/-/jobs/54309354

**Comment by dsolodow** [comment]
Change line 5 in your .gitlab-ci.yml to:
sudo apt-get install curl apt-transport-https -y

**Comment by chipitsine** [comment]
yes, it helps.

should it be also documented ?

**Comment by iSazonov** [comment]
@TravisEz13 Could you please answer?

**Comment by dsolodow** [comment]
Hmm. I think this is a limitation of the Ubuntu 16.04 Docker image; the WSL Ubuntu install has this package installed.

It probably doesn't hurt to update the documentation to include it as this package **is** required for the install to work and including it on the *apt install* won't hurt anything.

**Comment by TravisEz13** [comment]
The Ubuntu 16.04 docker image (and most docker images) is different than Ubuntu 16.04 itself.  You should use the [Ubuntu 16.04 docker file](https://github.com/PowerShell/PowerShell/blob/master/docker/release/ubuntu16.04/Dockerfile) for installing on an Ubuntu 16.04 docker image, which already has this as needed.

At most, there should be a single comment about this on the page.

**Comment by chipitsine** [comment]
well, I've taken official ubuntu 16.04 and precisely followed official installation guide for ubuntu 16.04
installation failed, what did I do wrong ?

**Comment by TravisEz13** [comment]
@chipitsine Can you file an issue reporting what you did (for example, what official image you used.   In this report, you indicate you use the docker image [based on your YML](https://docs.gitlab.com/ce/ci/yaml/README.html#image-and-services)) there and what issues you faced?

**Comment by chipitsine** [comment]
yml is what I did. nothing else

**Comment by TravisEz13** [comment]
The YML files use the docker image, not a full Ubuntu image which is what the instructions are for.  Please use the docker files, as mentioned previously ( https://github.com/PowerShell/PowerShell/issues/6242#issuecomment-369700532), when configuring a docker image or alternatively use our docker image.  

```yml
  image: microsoft/powershell:ubunutu16.04
```
