### ISSUE TITLE
Unable to remove (default) property of registry item

### ISSUE THREAD

**Issue by ZSkycat** [PowerShell/PowerShell#6243]
Steps to reproduce
------------------

```powershell
New-Item 'registry::HKEY_CURRENT_USER\test'
Set-ItemProperty 'registry::HKEY_CURRENT_USER\test' -Name '(default)' -Value 'test1'
Remove-ItemProperty 'registry::HKEY_CURRENT_USER\test' -Name '(default)'

Remove-ItemProperty : Property (default) does not exist at path HKEY_CURRENT_USER\test.
At line:1 char:1
+ Remove-ItemProperty 'registry::HKEY_CURRENT_USER\test' -Name '(defaul ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: ((default):String) [Remove-ItemProperty], PSArgumentException
+ FullyQualifiedErrorId : System.Management.Automation.PSArgumentException,Microsoft.PowerShell.Commands.RemoveItemPropertyCommand
```
see more https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/146

Expected behavior
-----------------

```none

```

Actual behavior
---------------

```none

```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@ZSkycat Could you please repo with latest PowerShell Core build?

**Comment by ZSkycat** [comment]
@iSazonov 6.0.1 reproduce this bug

**Comment by stknohg** [comment]
Related this, I found very strange behavior.

I add `"(default)"` property in this registry key.

```powershell
# set default(no named) property
New-Item 'registry::HKEY_CURRENT_USER\test'
Set-ItemProperty 'registry::HKEY_CURRENT_USER\test' -Name '(default)' -Value 'test1'

# add "(default)" property
$regkey = [Microsoft.Win32.Registry]::CurrentUser.OpenSubKey("test", $true)
$regKey.SetValue('(default)','test2')
$regkey.Close()
```

After commands, `HKEY_CURRENT_USER\test` has 2 properties.

1. `Default(no named)` : value is "test1"
2. `"(default)"`       : value is "test2"

![fig01](https://user-images.githubusercontent.com/720127/36830817-91377ff2-1d68-11e8-858a-c5f563ce9464.png)

In this condition, `Remove-ItemProperty -Name '(default)'` exits without error and default(no named) property value has deleted.

```powershell
# no error
Remove-ItemProperty 'registry::HKEY_CURRENT_USER\test' -Name '(default)'
```

![fig02](https://user-images.githubusercontent.com/720127/36830838-a3ce2a76-1d68-11e8-9da4-6eb74ec2aa9b.png)

----

The cause of this behavior is below, 

https://github.com/PowerShell/PowerShell/blob/67c9ae47f81a38ee3fcc1e16b187b79fb9cbe148/src/System.Management.Automation/namespaces/RegistryProvider.cs#L2329-L2333

Registry provider changes the property name(`"(default)"` to `""`) just before deleting value not at validating property name.

**Comment by iSazonov** [comment]
I believe it is bug - default value name should be null.

**Comment by ZSkycat** [comment]
@iSazonov 
I found a way to get (default). It is an empty string.
```
$a = Get-Item 'registry::HKEY_CURRENT_USER\test'
$a.GetValue('')
```

**Comment by iSazonov** [comment]
@ZSkycat Thanks for your research - feel free to create PR.

**Comment by ThubLives** [comment]
I can reproduce all the behaviour mentioned here in PowerShell Core 7.3.9.

**Comment by ThubLives** [comment]
I'm not sure why this was closed despite being able to reproduce this problem on a then-current version.  It seems that 7.4.0 has been released now, but I haven't had a chance to test it on a Windows system.

**Comment by virginviolet** [comment]
pls fix

**Comment by ThubLives** [comment]
This problem still occurs in PowerShell 7.4.4.
