### ISSUE TITLE
Multiple modules missing after Powershell 6.0.1 installation on Linux

### ISSUE THREAD

**Issue by Ayanmullick** [PowerShell/PowerShell#6248]
Steps to reproduce
------------------
Install Powershell on a RedHat 7.3 VM per documentation
https://docs.microsoft.com/en-us/powershell/scripting/setup/Installing-PowerShell-Core-on-macOS-and-Linux?view=powershell-6#installation-via-package-repository-preferred---red-hat-enterprise-linux-rhel-7

```Get-module -ListAvailable

```

Expected behavior
-----------------
This should list the below modules per this blog
https://blogs.msdn.microsoft.com/powershell/2018/01/10/powershell-core-6-0-generally-available-ga-and-supported/

1. CimCmdlets
2. Microsoft.PowerShell.Archive
3. Microsoft.PowerShell.Diagnostics
4. Microsoft.PowerShell.Host
5. Microsoft.PowerShell.Management
6. Microsoft.PowerShell.Security
7. Microsoft.PowerShell.Utility
8. Microsoft.WSMan.Management
9. PackageManagement
10. PowerShellGet
11. PSDesiredStateConfiguration
12. PSDiagnostics
13. PSReadLine

```none

```

Actual behavior
---------------
However the below modules are missing.

1. CimCmdlets
2. Microsoft.PowerShell.Diagnostics
3. Microsoft.WSMan.Management
4. PSDiagnostics
```none

```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Linux 3.10.0-514.28.1.el7.x86_64 #1 SMP Fri Jul 7 12:58:19 EDT 2017
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Please document additional steps for the missing modules.

**Comment by joeyaiello** [comment]
Unfortunately, these modules are only available on Windows due to reliance on Windows-specific APIs. 

Could you explain how you're trying to use them? Generally speaking, we haven't seen much demand for local usage of those cmdlets on non-Windows platforms. Even if you want to run them on a Windows box from a Mac or Linux client, that's enabled via PSRemoting.

**Comment by Ayanmullick** [comment]
My understanding is that OMI is the Linux-equivalent of CIM. I want to use the something like this to DomainJoin my RedHat VM's

""(Get-CimInstance -ClassName Win32_ComputerSystem).JoinDomainOrWorkgroup($Domain,$Credential.GetNetworkCredential().Password,$Credential.UserName,$null,3)""

**Comment by Ayanmullick** [comment]
No one assigned to this yet!

**Comment by SteveL-MSFT** [comment]
@Ayanmullick OMI is the Linux equivalent of WMI, but what you also need is the Linux equivalent implementations of CIM classes (so CIM_ComputerSystem would need to be implemented) and they would also need to implement Windows specific extensions to the CIM class (JoinDomainOrWorkgroup() method is specific to Windows and the Win32_ComputerSystem class and not part of the CIM standard).

OMI and CIM class implementations are not part of PowerShell.  Your request will need to be given to either RedHat to implement or to [OpenPegasus](https://collaboration.opengroup.org/pegasus/pr/) which similar to OMI is an OSS implementation of a CIMOM (what WMI is).

There are no plans to port the CIM cmdlets to non-Windows.

**Comment by Ayanmullick** [comment]
Azure Sphere OS?

**Comment by SteveL-MSFT** [comment]
@Ayanmullick for Azure Sphere OS, that team would need to do the work.  I would suggesting adding a comment to their [blog post](https://azure.microsoft.com/en-us/blog/introducing-microsoft-azure-sphere-secure-and-power-the-intelligent-edge/)

**Comment by Ayanmullick** [comment]
Wish there was a way to reassign this issue.
