### ISSUE TITLE
PSCore6 - PSCustomObject difference result Windows vs. Core?

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#6262]
Just an observation as I was expecting to return the same results.  Why is not keeping the same order?

Steps to reproduce
------------------
Here's the code:

```powershell
## - Build PSCustomObject:
[PSCustomObject]$SystemInfo = New-Object PSObject -Property @{
	ComputerName    = "SAPIEN01";
	OperatingSystem = "Windows10";
	LastBootUpTime  = '02/27/2018';
	Status		    = "Success";
	Manufacturer    = "Lenovo";
	SystemModel	    = 'P50';
}

$SystemInfo
```

Expected behavior
-----------------
PSCore6 object will be the same as Windows PowerShell.

```
PS [13] > $SystemInfo

Manufacturer    : Lenovo
SystemModel     : P50
OperatingSystem : Windows10
ComputerName    : SAPIEN01
LastBootUpTime  : 02/27/2018
Status          : Success

```

Actual behavior
---------------
The order of the property are not the same.
(see Image below)

```
PS [12] > $systemInfo

LastBootUpTime  : 02/27/2018
Manufacturer    : Lenovo
Status          : Success
ComputerName    : SAPIEN01
SystemModel     : P50
OperatingSystem : Windows10

```

Environment data
----------------
Microsoft Windows [Version 10.0.17101.1000]

```powershell
PS [24] > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Microsoft Windows 10.0.17101
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
![pscustomobject_issue_2018-02-27_16-53-15](https://user-images.githubusercontent.com/19892435/36757635-1bb233b4-1be0-11e8-86b4-bbc61448442f.jpg)

**Comment by SteveL-MSFT** [comment]
I don't believe order is guaranteed unless you use a format data file (ps1xml).

**Comment by markekraus** [comment]
You are using a HashTable for the properties. The HashTable "orders" the keys based on the Hashcode of the key. HashTables in PowerShell use `[System.StringComparer]::CurrentCultureIgnoreCase` as the `IEqualityComparer`. So you can look and see what hashcodes would be generated for the keys of your hashtable with the following:

```powershell
$Comparer = [System.StringComparer]::CurrentCultureIgnoreCase
$Hash =  @{
	ComputerName    = "SAPIEN01";
	OperatingSystem = "Windows10";
	LastBootUpTime  = '02/27/2018';
	Status		    = "Success";
	Manufacturer    = "Lenovo";
	SystemModel	    = 'P50';
}
$Hash.Keys | ForEach-Object {
    [PSCustomObject]@{
        Name = $_
        HashCode = $Comparer.GetHashCode($_)
    }
} | Sort-Object -Property HashCode
```

If you run that in 5.1 you will see the results are fairly static. The underlying hash code generation code in .NET Framework is somewhat predictable across systems.

However, HashCode generation is never guaranteed to be consistent outside of the current session. They are meant only for sorting items into hash buckets. hashcode generating code is supposed to evenly distribute values, but the actual implementation is meant to a black box and you aren't meant to know the dark elven magic used.

.NET Core seems to take this to the extreme. I can open up multiple PS Core 6.0.1 consoles, run my code or yours and get different orders in every console. The orders will be consistent within a console, but wildly different between them

If the property order matters (and it really shouldn't except for displaying to users and som APIs), you can either supply TypeData and use a `PSTypeName`, use `[ordered]@{}` for your property hashtable, or use the `[PSCustomObject]` type accelerator.

Using `[ordered]`:

```powershell
$Properties = [ordered]@{
	ComputerName    = "SAPIEN01"
	OperatingSystem = "Windows10"
	LastBootUpTime  = '02/27/2018'
	Status		    = "Success"
	Manufacturer    = "Lenovo"
	SystemModel	    = 'P50'
}
[PSCustomObject]$SystemInfo = New-Object PSObject -Property $Properties
$SystemInfo
```

using  `[PSCustomObject]` type accelerator (doesn't work on older versions, but will at least in 5.1 and 6.0.0):

```powershell
[PSCustomObject]$SystemInfo = [PSCustomObject]@{
	ComputerName    = "SAPIEN01"
	OperatingSystem = "Windows10"
	LastBootUpTime  = '02/27/2018'
	Status		    = "Success"
	Manufacturer    = "Lenovo"
	SystemModel	    = 'P50'
}
$SystemInfo
```

Using TypeData (note that this will only affect the display of properties, not the actual definietion order you see in serialization such as `ConvertTo-Json`):

```powershell
Update-TypeData -TypeName 'My.Custom.Type' -DefaultDisplayPropertySet @(
    'ComputerName'
    'OperatingSystem'
    'LastBootUpTime'
    'Status'
    'Manufacturer'
    'SystemModel'
)

[PSCustomObject]$SystemInfo = New-Object PSObject -Property @{
    PSTypeName      = 'My.Custom.Type'
	ComputerName    = "SAPIEN01";
	OperatingSystem = "Windows10";
	LastBootUpTime  = '02/27/2018';
	Status		    = "Success";
	Manufacturer    = "Lenovo";
	SystemModel	    = 'P50';
}

$SystemInfo
```

For most things, you can not care about the property order and just sue `format-list` or `format-table` and set the order when you are displaying them:

```powershell
[PSCustomObject]$SystemInfo = New-Object PSObject -Property @{
	ComputerName    = "SAPIEN01";
	OperatingSystem = "Windows10";
	LastBootUpTime  = '02/27/2018';
	Status		    = "Success";
	Manufacturer    = "Lenovo";
	SystemModel	    = 'P50';
}

$SystemInfo | Format-List -Property @(
    'ComputerName'
    'OperatingSystem'
    'LastBootUpTime'
    'Status'
    'Manufacturer'
    'SystemModel'
)
```

The actual order of properties on an object shouldn't matter for anything other than displaying them to the user or working with nasty APIs that require specific orders on serialized objects for whatever crazy reason.

**Comment by MaximoTrinidad** [comment]
Sorry for the misunderstanding!

I'm not looking for ordering the result.  Just wanted to point out, or make an observation, that the default output result were not the same if I'm comparing Windows PowerShell vs PowerShell.  

It maybe irrelevant and maybe due to the full clr vs. core way of creating PSCustomObject.

I can always manipulate the data in different ways. 

:)

**Comment by markekraus** [comment]
Understood. It's not a difference in how PowerShell is doing anything. Just a difference in how keys are ordered in HashTables, which was never guaranteed to be the same unless you used an ordered hashtable. You just as easily could have seen different ordering on different systems with different versions of .NET framework. without any Windows PowerShell  vs PowerShell Core differences to consider. :)

**Comment by MaximoTrinidad** [comment]
Thanks @markekraus!  I appreciate the comments.
:)
