### ISSUE TITLE
User voice

### ISSUE THREAD

**Issue by rsumner31** [PowerShell/PowerShell#6266]
Steps to reproduce
------------------

```powershell

```

Expected behavior
-----------------

```none

```

Actual behavior
---------------

```none

```

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by bergmeister** [comment]
@rsumner31 Please provide details if it  is related to PowerShell Core, otherwise report it on User Voice and close this issue please. Otherwise this issue will get closed by maintainers.
