### ISSUE TITLE
Segmentation Violation while doing reverse search

### ISSUE THREAD

**Issue by kam1sh** [PowerShell/PowerShell#6269]
Hello. I'm afraid I got rare segmentation violation =(
I couldn't reproduce it again, but, fortunately, systemd caught coredump, so I decided to post an issue with coredump that, I hope, could help you.
I'm not sure, is this related to #6190, because stack traces are different.

Steps to reproduce
------------------
I entered PSSession command and pressed Ctrl-R in the middle to find previously entered credentials. After ten seconds of reverse search powershell dumped:

` Enter-PSSession <...> -^Redential <...> `
__fish: 'pwsh' terminated by signal SIGSEGV (Address boundary error)__
Brief of stack trace:

>     Stack trace of thread 7274:
>     #0  0x00007fa05751c284 utext_nativeLength_57 (libicuuc.so.57.1)
>     #1  0x00007fa05755a13e _ZN6icu_5722RuleBasedBreakIterator10isBoundaryEi (libicuuc.so.57.1)
>     #2  0x00007fa0556c5659 usearch_search_57 (libicui18n.so.57.1)
>     #3  0x00007fa0556c5edf usearch_handleNextExact_57.part.15 (libicui18n.so.57.1)
>     #4  0x00007fa0556c6bd5 usearch_handleNextExact_57 (libicui18n.so.57.1)
>     #5  0x00007fa0556c6e67 usearch_next_57 (libicui18n.so.57.1)
>     #6  0x00007fa0640475d9 GlobalizationNative_IndexOf (System.Globalization.Native.so)

[core.pwsh.zip](https://github.com/PowerShell/PowerShell/files/1767118/core.pwsh.zip)

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value                                                                                                                                                                               
----                           -----                                                                                                                                                                               
PSVersion                      6.0.1                                                                                                                                                                               
PSEdition                      Core                                                                                                                                                                                
GitCommitId                    v6.0.1                                                                                                                                                                              
OS                             Linux 4.14.18-300.fc27.x86_64 #1 SMP Thu Feb 8 01:35:31 UTC 2018                                                                                                                    
Platform                       Unix                                                                                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                             
PSRemotingProtocolVersion      2.3                                                                                                                                                                                 
SerializationVersion           1.1.0.1                                                                                                                                                                             
WSManStackVersion              3.0                                                                                                                                                                                 

```

**Comment by SteveL-MSFT** [comment]
@dantraMSFT there's a core dump attached, can you see if you can get anything meaningful out of it?

**Comment by dantraMSFT** [comment]
I'm not able to get anything from it; can't get symbol information.

**Comment by SteveL-MSFT** [comment]
I don't think there's any action to be taken on this right now unless we can get something that can be reproduced or at least a more complete stacktrace showing some part of PowerShell

**Comment by MaximoTrinidad** [comment]
@kam1sh,

Can you please provide a sample oneliner using Enter-PSSession? You example is not enough to reproduce.

It seems you are trying using WinRm on Linux, by the abbreviation " -^Redential <...>.  So anyone could assume "-Credential" is in play.

:)

**Comment by kam1sh** [comment]
@MaximoTrinidad 
Yes, I tried to use WinRM on Linux, and I left it: it doesn't work, unlike, for example, python module `winrm`. 
And I can't reproduce it either. It' sad that core dump could not help, because I have nothing else.
I guess, **issue could be left/closed for later**, until someone else will face it.

**Comment by iSazonov** [comment]
I close this until we get repo steps.

@kam1sh Thanks for you report!
