### ISSUE TITLE
Add help to command completion tooltips

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShell#6275]
I have a PR that displays help description in tooltips for commands and command parameters.

![cmdhelp](https://user-images.githubusercontent.com/3505151/36815472-119f57d4-1cdb-11e8-9653-b6bc8aa5ced3.gif)

This issue is for discussion it is a good idea, if it needs tweaking or just isn't the right thing.

Personally, I think it can help with discoverability.

**Comment by rkeithhill** [comment]
Looks pretty sweet to me!  👍 from me.

**Comment by thezim** [comment]
What happens if near the end of the terminal window? Does it auto scroll to show the tooltip or pop below?

**Comment by powercode** [comment]
The layout is handled by PSReadline. The only thing I have done is provided more text in the tooltip.

**Comment by YenForYang** [comment]
Ah I wish this worked. It really would help users, particularly the newer ones (like myself).
