### ISSUE TITLE
Measure-Object should support a `-All` parameter

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell#6278]
By default, Measure-Object only returns a value for `Count`, omitting `Average`, `Sum`, `Minimum`, and `Maximum` unless those are each specified by analogous parameters. 

Given that the perf impact of finding *one* of those additional values is the same as finding *all* of them ( O(n) ), we should add a `-All` parameter that 

Steps to reproduce
------------------

```powershell
1,2,3 | Measure-Object -All
```

Expected behavior
-----------------

```none
Count    : 3
Average  : 2
Sum      : 6
Maximum  : 3
Minimum  : 1
Property :
```

Actual behavior
---------------
An error is thrown. But without `-All`, you just get:

```none
Count    : 3
Average  :
Sum      :
Maximum  :
Minimum  :
Property :
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Microsoft Windows 10.0.17613
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by lzybkr** [comment]
You don't need a new parameter to do this. Just compute all if any of those parameters is specified.

I say this because the proposed parameter just looks weird, I'd start to wonder what it is doing if I don't specify `-All` - is it not measuring **all** of the objects? 😕

**Comment by raghav710** [comment]
@lzybkr  @joeyaiello would computing all the values when no parameter is specified be a good solution?
Either that, or we could name the parameter as `-AllStats` or something similar
