### ISSUE TITLE
Powershell dropping empty string argument

### ISSUE THREAD

**Issue by NicolasDorier** [PowerShell/PowerShell#6280]
Step to reproduce

Using [EchoArgs](https://chocolatey.org/packages/echoargs)

Actual:
```
PS C:> EchoArgs.exe ""

Command line:
"C:\ProgramData\chocolatey\lib\echoargs\tools\EchoArgs.exe"
```

Expected:
```
PS C:> EchoArgs.exe ""
Arg 0 is <>

Command line:
"C:\ProgramData\chocolatey\lib\echoargs\tools\EchoArgs.exe" ""
```

Workaround with back tilt:

```
PS C:> EchoArgs.exe `"`"
Arg 0 is <>

Command line:
"C:\ProgramData\chocolatey\lib\echoargs\tools\EchoArgs.exe" ""
```

Is it expected behavior ? If so, this is easy way for foot shooting.

Using a variable has the same issue, need to use the back tilt:

```
PS C:> EchoArgs.exe `"$(variable)`"
Arg 0 is <>

Command line:
"C:\ProgramData\chocolatey\lib\echoargs\tools\EchoArgs.exe" ""
```

If failing to use back tilt, and variable is empty string, the argument get ignored.

```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      16299  98
```

**Comment by SteveL-MSFT** [comment]
This repros with PSCore6.  Although the backtick is a viable workaround, it seems like we shouldn't drop an argument that is explicitly an empty string.

**Comment by SteveL-MSFT** [comment]
Looks like this is fixed in corefx 2.1 https://github.com/dotnet/corefx/issues/25456

**Comment by NicolasDorier** [comment]
This is interesting, so this is a bug of the underlying `Process` class.

This seems weird though, why escaping with backtick would work though?

**Comment by mklement0** [comment]
`` `"`" `` is actually only a workaround on _Windows_; it doesn't work on Unix.

**Comment by mklement0** [comment]
@SteveL-MSFT: Without having looked a the source, I suspect there are _2_ layers of bugs at play here:

* One in PowerShell itself, where an empty string is dropped in formulating the command line to invoke behind the scenes.

* If the PowerShell bug is worked around with `` `"`" `` to force literal inclusion of `""` in the command line, _then_ the CoreFX bug kicks in, but only on _Unix_.

**Comment by SteveL-MSFT** [comment]
@mklement0 you are correct that there is a bug in PowerShell itself, I found the corefx issue since I made a change to fix the PowerShell issue so that an empty string gets passed, but it still didn't work as expected.  To fix this, I'll need to submit a PR that pulls in the appropriate version of corefx with their fix along with a fix on our side.

**Comment by NicolasDorier** [comment]
So in summary, with .NET 2.1 the back tick workaround should work though?

**Comment by mklement0** [comment]
In combination with the PowerShell-side fix that @SteveL-MSFT mentioned, _you won't need a workaround anymore_.

In fact, I would consider the workaround a bug in itself: `` `"`"` `` asks that two _literal_ `"` chars. be passed as an argument and thus what the target program should end up seeing is just that; to put in PowerShell terms - `'""'`, not `''` (the empty string).

**Comment by NicolasDorier** [comment]
interesting, I think fixing this workaround might break quite a lot of script though, I can't believe nobody got into the problem before.

**Comment by pcrockett** [comment]
Hm, for some reason backticking the way you all suggested didn't work for me, but I do have a workaround that does work. I wrote a simple bash script (`countparams`) to test:

```
#!/bin/bash
echo Number params: $#
```

Running `./countparams foo "" bar` in _bash_ yields this:

> Number params: 3

In PowerShell, running both `./countparams foo "" bar` _and_ ``./countparams foo `"`" bar`` yields the wrong result:

> Number params: 2

The solution I found was this:

    "./countparams foo `"`" bar" | /bin/bash

which yields the correct result:

> Number params: 3

Ubuntu 16.04, PowerShell version 6.1.0-preview.2

**Comment by mklement0** [comment]
@pcrockett: Yes, the `` `"`" `` workaround only works on _Windows_ (as stated) - and it's bittersweet, because not only should it not be necessary, it also _shouldn't work_.

Kudos for the Unix workaround.
Since you're effectively passing an a single string as a piece of source code for evaluation by `bash`, you don't need  `` `"`" `` per se (which in your case are only need in order to embed `"` inside `"..."`, by PowerShell's _internal_ rules; a such `""""` would work too).

Thus, the following two variants work too:

```sh
# Pass the Bash command as a *double*-quoted PS string.
"./countparams foo '' bar" | /bin/bash

# Pass the Bash command as a *single*-quoted PS string.
'./countparams foo "" bar' | /bin/bash
```

**Comment by lucy** [comment]
Is there ANY portable way to pass an empty string to a native command right now? None of the various workarounds I've seen (`'""'`, `"''"`, `[String]::Empty`, `` `"`" ``, etc...) seem to work on every powershell version.

**Comment by mklement0** [comment]
Workaround `'""'` works in both Windows PowerShell and PowerShell (Core) on all platforms up to at least v7.2.4, but breaks in 7.3 _preview_ versions with the `PSNativeCommandArgumentPassing` experimental feature turned on - and may break:
 * if that experimental feature (a) becomes an official feature behavior in 7.3 ...
 * ... and (b) the fix becomes the _default_ behavior (as opposed to requiring _opt-in_ via the `$PSNativeCommandArgumentPassing` preference variable).

The [`Native` module](https://github.com/mklement0/Native) (`Install-Module Native`; authored by me), has an `ie` function (short for: Invoke Executable), which is a polyfill that provides sane,  workaround-free, cross-edition (v3+) and cross-platform behavior that is also forward-compatible (it'll continue to work, irrespective of what happens in 7.3; believe  me, I wish there were no need for such a module.)

**Comment by NicolasDorier** [comment]
maybe we should ping somebody from MS that they are going to break something @SteveL-MSFT

**Comment by SteveL-MSFT** [comment]
@VeMike if you want empty args to be dropped like previously, you'll have to set `$PSNativeCommandArgumentPassing = 'Legacy'`.  The change was to support the other scenarios where you want to pass an empty arg value.  However, if you are dynamically building an array of args, you can also pass `$null` instead of empty string which will get dropped with the new argument passing code.

**Comment by SetTrend** [comment]
I'm sharing the same issue since updating to PowerShell 7.4.*. Unfortunately, I don't grasp the suggested workaround.

Can someone please help me out on this? How should I escape a call like that:

```powershell
[string[]]$branches = @()
[string]$remoteRefName = ''
[string]$svnRepositoryLocation = 'https://svn.local/rep'
[string]$pathWithSpaces = 'c:\Program Files\Test'

git svn clone $($branches -join ' ') "$remoteRefName" "$svnRepositoryLocation" "$pathWithSpaces"
```

Currently, this call fails with "`SVN repository location required as a command-line argument`".

**Comment by VeMike** [comment]
@SetTrend 
I can not test your specific case but have you tried either:

Setting the `$PSNativeCommandArgumentPassing = 'Legacy'`? So your snippet becomes:

```powershell
$PSNativeCommandArgumentPassing = 'Legacy'

[string[]]$branches = @()
[string]$remoteRefName = ''
[string]$svnRepositoryLocation = 'https://svn.local/rep'
[string]$pathWithSpaces = 'c:\Program Files\Test'

git svn clone $($branches -join ' ') "$remoteRefName" "$svnRepositoryLocation" "$pathWithSpaces"
```

or using `$null` instead of an empty string? So your snippet becomes:

```powershell
[string[]]$branches = @()
[string]$remoteRefName = $null
[string]$svnRepositoryLocation = 'https://svn.local/rep'
[string]$pathWithSpaces = 'c:\Program Files\Test'

git svn clone $($branches -join ' ') "$remoteRefName" "$svnRepositoryLocation" "$pathWithSpaces"
```

**Comment by SetTrend** [comment]
@VeMike: Thanks for enlightening me on this!

I guess I won't be able to use the $PSNativeCommandArgumentPassing flag as it won't run on PowerShell installations v7.2--. So, I'll stick to the `$null` option.

However, I fail to comprehend the reasoning for the change. What is the advantage in dropping all subsequent arguments when an empty string is provided as one of the arguments? Why is this logical?

**Comment by SetTrend** [comment]
Ah, I found the reason for my confusion. And for anyone stranding here, facing the same issue, I'd like to share my findings:

The new parsing is keeping the empty string arguments in the argument array while the legacy one was dropping them. So, the new handling seems more "accurately" reflecting the argument list than the previous one did.

The issue I was facing was that the `git svn` command parser was using positional parameters, and so the empty string arguments were now recognized, parsed and assigned to the wrong parameters, which wasn't happening before.

Now that I know its implications, I can very much live with the new behavior.

---

Here's a sceenshot, depicting what I found:

![NativeArgumentPassingStyle](https://github.com/PowerShell/PowerShell/assets/9283914/fac215e3-8498-4c2c-9aef-a1007c6a7f42)

**Comment by VeMike** [comment]
@SetTrend 
It's not the subsequent arguments that are dropped when an empty string is encountered. The new powershell behavior is that empty strings are kept as arguments and are passed to the _native command_ (i.e. an external program that is not part of powershell itself).

The old behavior was to drop the arguments.

The first argument to `git svn clone` is the repo URL and since that becomes an empty string you get the error you posted
