### ISSUE TITLE
Should `New-PSSession` using SSH accept user@hostname?

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#6284]
Currently, `New-PSSession` has a parameter set to use `-Hostname` and `-Username` to indicate SSHTransport is being used (instead of `-ComputerName` and `-Credential`).  SSH users are probably more familiar and comfortable with `ssh user@hostname`, so it seems we should support `New-PSSession -Hostname user@hostname` (unfortunately, it would be a breaking change to default to `-Hostname` instead of `-Computername` to support this as a positional parameter)

cc @PaulHigin @joeyaiello

**Comment by bergmeister** [comment]
I would rather defer this till the end of the 6.1 release cycle and focus more on actual features that add value tbh.

**Comment by SteveL-MSFT** [comment]
@bergmeister this isn't marked for 6.1, although I also don't think it would be difficult to implement (split the string, pass it to the existing parameters...).  This came up for me as I was using `ssh` to a Linux VM and then had to use `new-pssession` over SSH and was annoyed how easy it was using `ssh`

**Comment by markekraus** [comment]
@SteveL-MSFT might as well use URI builder instead of split string. It would position us for possible furthe enchantments in the future.

```powershell
$Hostname = 'myuser@somehost.com'
$Builder = [System.UriBuilder]::New($Hostname)
$Hostname = $Builder.Host
$Username = $Builder.UserName
$Port = $Builder.Port
```

The format, after all, is a URI.

**Comment by SteveL-MSFT** [comment]
Was investigating a SSH MFA issue and this annoyed me enough to submit a fix
