### ISSUE TITLE
.WasThrownFromThrowStatement not available for System.Exception

### ISSUE THREAD

**Issue by alx9r** [PowerShell/PowerShell#6288]
Steps to reproduce
------------------

```powershell
try
{
    throw
}
catch
{
    [bool]$_.Exception.WasThrownFromThrowStatement
}

try
{
    throw [System.Exception]::new()
}
catch
{
    [bool]$_.Exception.WasThrownFromThrowStatement
}
```

Expected behavior
-----------------

```none
True
True
```

Actual behavior
---------------

```none
True
False
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value                                            
----                           -----                                            
PSVersion                      6.0.0                                            
PSEdition                      Core                                             
GitCommitId                    v6.0.0                                           
OS                             Microsoft Windows 6.3.9600                       
Platform                       Win32NT                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                          
PSRemotingProtocolVersion      2.3                                              
SerializationVersion           1.1.0.1                                          
WSManStackVersion              3.0                                              
```

**Comment by mklement0** [comment]
As discussed, the problem happens with `[System.Exception]`-_derived_ types as well, except for `[System.Management.Automation.RuntimeException]`, which is what PowerShell _implicitly_ uses when you throw nothing or any object that is not an exception.

**Comment by BrucePay** [comment]
The `.WasThrownFromThrowStatement` property along with `RuntimeException` are implementation details for the PowerShell runtime and aren't intended to be used by end users. `.WasThrownFromThrowStatement` exists so that the `throw` statement can throw an exception that won't be caught by pipeline exception handlers allowing the exception to propagate up through a set of nested pipelines. Since it's PowerShell-specific, it won't appear on any non-PowerShell types.

**Comment by alx9r** [comment]
>Since it's PowerShell-specific, it won't appear on any non-PowerShell types.

Thanks for the clarity @BrucePay
