### ISSUE TITLE
Table format has been broken when output column contains east asian fullwidth characters

### ISSUE THREAD

**Issue by stknohg** [PowerShell/PowerShell#6290]
Steps to reproduce
------------------

```powershell
# make directories contains east asian fullwidth characters.
# in this example, I use Japanese.
mkdir .\Test
cd .\Test
mkdir Hello
mkdir HelloWorld
mkdir Helloワールド
mkdir ハロー
mkdir ハローワールド

# invoke Get-ChildItem (output table format by default)
Get-ChildItem
```

Expected behavior
-----------------

Table layout is not broken.

e.g. on Windows PowerShell 5.1

![error02](https://user-images.githubusercontent.com/720127/36887317-00949454-1e34-11e8-8916-df60343f4ab3.png)

Actual behavior
---------------

Table layout has been broken.  

![error01](https://user-images.githubusercontent.com/720127/36887330-0c15b8b2-1e34-11e8-91a5-3d1ebf733075.png)

In this case, the last column(`Name`) is broken.  
But the column other than the last column will also be broken.  

![error03](https://user-images.githubusercontent.com/720127/36887340-17f63008-1e34-11e8-8d07-ec9b0c6f4c88.png)

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

This problem occurs on all platforms.

Cause
----------------

The root cause is [ConsoleControl.LengthInBufferCells()](https://github.com/PowerShell/PowerShell/blob/v6.0.1/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs#L2763) method returns invalid value when `str` parameter contains east asian fullwidth characters.  

https://github.com/PowerShell/PowerShell/blob/67c9ae47f81a38ee3fcc1e16b187b79fb9cbe148/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs#L2763-L2786

When [TableWriter](https://github.com/PowerShell/PowerShell/blob/v6.0.1/src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs) creates table row line, `ConsoleControl.LengthInBufferCells()` method is called to get row character width.

`ConsoleControl.LengthInBufferCells()` method is expected to return a value according to the width of the character.  
Generally, east asian fullwidth characters(e.g. Japanese) are expected to return 2 or more per a character, but current version of `ConsoleControl.LengthInBufferCells()` simply returns character length.

```csharp
// length expected 6(3 fullwidth characters), but actual returns 3.
ConsoleControl.LengthInBufferCells("ハロー", 0, false); 
```

So, the padding in the last column(`Name`) has be greater than expected and then Table layout has been broken.

```powershell
# expected 120 characters width
"d-----       2018/03/02     15:52                Hello                                                                 "
# actual 123 characters width
"d-----       2018/03/02     15:52                ハロー                                                                   "            
```

Reference 1
----------------

The past version of `ConsoleControl.LengthInBufferCells()` method calls [LengthInBufferCellsFE()](https://github.com/PowerShell/PowerShell/blob/v6.0.0-alpha.9/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs#L2875) method internally.  (FE means Far East?)

https://github.com/PowerShell/PowerShell/blob/f46284414e9dda57eff3cdba7e61570a9a83e27e/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs#L2875-L3036

This `LengthInBufferCellsFE()` method handles the length of east asian fullwidth characters correctly, but it was removed at f604b0e3f063c7a89db025f11b320e5c9797c6e0 .

Reference 2
----------------

Technical report about East Asian Width.

* [East Asian Width](http://unicode.org/reports/tr11/)

**Comment by takekazuomi** [comment]
I built and checked the latest source. In doing the same thing, `` Get-ChildItem`` is looks like OK for my results. However, `` Get-ChildItem | Select Name, Mode`` was broken.

This is not a problem only in Japanese, the displayed character width depends on the character. Therefore, it is necessary to calculate the display width for each character.

![image](https://user-images.githubusercontent.com/73158/36894802-f5d8d982-1e4f-11e8-84b4-204433730a07.png)

**Comment by stknohg** [comment]
@takekazuomi  #5568 has been merged into the latest source, so the last column of the table now has no padding whitespace.
For this reason, `Get-ChildItem` seems to be OK, `Get-ChildItem | Select Name, Mode` is still broken.

**Comment by kwkam** [comment]
The formatter could not get the display width of CJK character, thus padding unnecessary spaces.
#5739 is also about this.
