### ISSUE TITLE
let powershell core 6 join ubuntu18.04

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#6307]
@jpsnover  ,   @joeyaiello  :

hi, 
Tense time
Contact everyone,  do everything possible,   let powershell core 6 join ubutu18.04 too please !
contact him:  Craig Wilhite, Program Manager at Microsoft.

Let the powershell core 6 to the distribution’s official repository.
Help them solve the powershell compile issue in the distribution.
Do some tech.

look news
------------------
Microsoft and Canonical to Offer Enhanced VM Experiences for Ubuntu 18.04 LTS

http://news.softpedia.com/news/microsoft-and-canonical-to-offer-enhanced-vm-experiences-for-ubuntu-18-04-lts-520035.shtml

**Comment by bergmeister** [comment]
I find the link totally irrelevant because it is about HyperV. I could copy-paste into my Ubuntu VM already 5 years ago using `VirtualBox`.

**Comment by ScriptAutomate** [comment]
Just want to confirm what this issue is asking for. Is it asking for publishing publishing to the ubuntu/18.04 package repo to allow the following package source to work for installing with `sudo apt install powershell`:

- `deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main`

If so, just wanted to add my note of interest here also. :+1:

**Comment by SteveL-MSFT** [comment]
Supporting 18.04 is certainly something we want.  Getting into a distro's official repo isn't likely going to happen (anytime soon at least) as it means the distro forks our code and maintains it.

**Comment by chuanjiao10** [comment]
Is it possible to do this:
Let Ubuntu's publisher Canonical place a powershell icon on the ubuntu desktop. The script behind this icon runs for the first time and can install powershell from ms repo.
Just like installing a copyright driver, let users activate themselves.

The same reasoning:
Provide a command in ubuntu server:
Enable-powershell

**Comment by ScriptAutomate** [comment]
@SteveL-MSFT The repository I was referrencing is owned by Microsoft: https://packages.microsoft.com/

It is not owned by Canonical / Ubuntu. It is a separate repo that one configures their system to be able to install from.

Currently, `powershell` is available to install via earlier versions of Ubuntu (included in the Microsoft package repos up to version 17.04 of Ubuntu) but the 18.04 repo does not contain it. It does currently contain other packages that Microsoft has been maintaining, such as `dotnet-runtime-2.1.0-preview2-26406-04` , `aspnetcore-runtime-2.1.0-preview2-final` , `dotnet-host` and `aadlogin`. `powershell isn't there. You can check which ones are currently in the Microsoft 18.04 repo here: https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages

**Comment by SteveL-MSFT** [comment]
@ScriptAutomate yes, we should publish 18.04 build to Msft repo once we have a 18.04 build of PSCore6.

**Comment by CZakalwe** [comment]
Having just installed 18.04 and very keen to get cracking on some PowerShell in Linux I was pretty deflated to find it's not available yet. Any ETA at all on that?

**Comment by chuanjiao10** [comment]
@ScriptAutomate 
Let powershell 6.01 binary file, join the server version ubuntu 18.04 iso file, or join the command "Enable-powershell",my original purpose is.
This is a very important thing until now. Unfortunately, there are no leaders to promote.

**Comment by KloudEzy** [comment]
I'm trying to install PowerShell Core on Ubuntu 18.04 and found that there is no package available. Please let me know when will it be officially supported.

**Comment by MaximoTrinidad** [comment]
@KloudEzy 

This already has been discussed and should be in place for the next release of PowerShell Core (Preview.3) for Ubuntu 18.04.  

Next update is around the corner!

**Comment by SteveL-MSFT** [comment]
PSCore6.1-Preview3 has 18.04 debs

**Comment by chuanjiao10** [comment]
![image](https://user-images.githubusercontent.com/8968667/46330967-3db4bc80-c648-11e8-8698-2588af890cb5.png)

**Congratulations   ！！！**
