### ISSUE TITLE
RfC: Get-ChildItem fails when there are two Environment variables with the same name but cased differently.

### ISSUE THREAD

**Issue by CodeHeadTheo** [PowerShell/PowerShell#6309]
Steps to reproduce
------------------
Use npm to modify Environment Variables to have two entries that are the same but cased differently i.e.

NPM_CONFIG_PATH
npm_config_path

Then complete a get-childitem on env:

Expected behavior
-----------------

[Environment]::GetEnvironmentVariables() does not fail.

Actual behavior
---------------
The error message is: "An item with the same key has already been added"

Environment data
----------------

PSVersion "5.1.14393.1944"

**Comment by TravisEz13** [comment]
#6305  is duplicate

**Comment by TravisEz13** [comment]
This issue does not have enough information no reproduce teh issue and #6305 does.  Closing this as a duplicate
