### ISSUE TITLE
ACLs not deserialized correctly during remoting (.Access CodeProperty nonfunctional)

### ISSUE THREAD

**Issue by hmmwhatsthisdo** [PowerShell/PowerShell#6311]
When ACLs are deserialized after being sent over a PSRemoting session (`Invoke-Command`, etc.), the `.Access` CodeProperty on the returned ACL is reconstituted as returning a static string (with one `"System.Security.AccessControl.FileSystemAccessRule"` line for each ACE in the ACL).

Steps to reproduce
------------------
First, acquire two computers with PSRemoting functional between the two of them.
```powershell
$Session = New-PSSession $RemoteComputer <# -Credential, -Authentication, etc. as needed #>
$ACL = Invoke-Command -Session $Session {Get-ACL C:}
$ACL.Access
$ACL | Get-Member Access | % Definition
```

Expected behavior
-----------------

```none
PS C:\> $ACL.Access


FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : NT AUTHORITY\SYSTEM
IsInherited       : False
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : BUILTIN\Administrators
IsInherited       : False
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None

FileSystemRights  : ReadAndExecute, Synchronize
AccessControlType : Allow
IdentityReference : BUILTIN\Users
IsInherited       : False
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None



PS C:\> $ACL | gm Access | % Definition
System.Security.AccessControl.AuthorizationRuleCollection Access{get=GetAccess;}
```

Actual behavior
---------------

```none
PS C:\> $ACL.Access
System.Security.AccessControl.FileSystemAccessRule
System.Security.AccessControl.FileSystemAccessRule
System.Security.AccessControl.FileSystemAccessRule
PS C:\> $ACL | gm Access | % Definition
Deserialized.System.Security.AccessControl.AuthorizationRuleCollection Access=System.Security.AccessControl.FileSystemAccessRule System.Security.AccessControl.FileSystemAccessRule System.Security.AccessControl.FileSystemAccessRule
```

Environment data
----------------

This bug was confirmed across several different Windows versions, with PoSH v5.1 and v6.0.1:
- Client: Windows Server 2012R2, PoSH v5.1; Server: Windows Server 2012R2, PoSH v5.1
- Client: Windows 10 1709, PoSH v5.1; Server: Windows 10 1709, PoSH v5.1
- Client: Windows 10 1709, PoSH v5.1; Server: Windows Server 2016 1607, PoSH v5.1
- Client: Windows 10 1709, PoSH v6.0.1; Server: Windows Server 2016 1607, PoSH v6.0.1
```none
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```none
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.16299.248
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.248
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
(Sadly, I don't have the 2012R2 `$PSVersionTable` output handy, but I don't think it's a requirement in this situation)

**Comment by BrucePay** [comment]
Hi @hmmwhatsthisdo, this is a consequence of how the remoting protocol/CliXML was designed. Properties and methods are not transported over the protocol. Methods are ignored and properties (including code properties) are evaluated during serialization with the resulting data value attached to the serialized object as a data member (field). You can find more information about the remoting protocol at [MS-PSRP](https://msdn.microsoft.com/en-us/library/dd357801.aspx)
