### ISSUE TITLE
Format-Table -Wrap produces strange output for a mix of long lines and lines containing tabs

### ISSUE THREAD

**Issue by Arnavion** [PowerShell/PowerShell#6313]
Steps to reproduce
------------------

Windows 7, with pwsh.exe's window size set to 200x75. The width is the relevant thing. Choice of font does not seem to matter.

Edit: Also repros on openSUSE Tumbleweed in a similarly sized ssh window or konsole window.

```powershell
@((
	New-Object psobject | Add-Member -Passthru Foo "a`tb"
), (
	New-Object psobject | Add-Member -Passthru Foo ("c`t" + 'd' * 200)
), (
	New-Object psobject | Add-Member -Passthru Foo "e`tf"
)) | Format-Table -Wrap
```

Expected behavior
-----------------

![image](https://user-images.githubusercontent.com/1096010/36970546-d560d89c-201d-11e8-9d49-2db86e5b2ae6.png)

(from PS 5)

Actual behavior
---------------

![image](https://user-images.githubusercontent.com/1096010/36970578-eccf7128-201d-11e8-9318-5917e782650c.png)

- There is an extra line after the first and last element (in fact there is an extra line after every row except the one with the wrapping value)

- The row that has the long value is wrapped strangely.

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Microsoft Windows 6.1.7601 S
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

and

```powershell
Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Linux 4.15.6-1-default #1 SMP PREEMPT Sun Feb 25 18:51:57 UTC 2018 (06f0b06)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

---

Removing the tab character from the first object's property (or even replacing it with 8 spaces) fixes the extra line between the rows but does not fix the strange wrapping of the long row.

Shortening the long row so that it does not need to wrap also fixes the extra line between the rows.

**Comment by Arnavion** [comment]
Anotehr bit of strange behavior for

```powershell
@((
	New-Object psobject | Add-Member -Passthru Foo "a`tb"
), (
	New-Object psobject | Add-Member -Passthru Foo ("c`t" + 'd' * 100 + ' ' + 'd' * 100)
), (
	New-Object psobject | Add-Member -Passthru Foo "e`tf"
)) | ft -Wrap
```

PS 5.0:

![image](https://user-images.githubusercontent.com/1096010/36971290-31bfcf74-2020-11e8-9ef1-dccc1e333b0a.png)


PS Core:

![image](https://user-images.githubusercontent.com/1096010/36971384-845a0088-2020-11e8-98f6-ddaa53bf3a2c.png)

There is now also an empty line between the two parts of the wrapping second row. This line does *not* go away if I replace the tab in the first row with spaces, but does go away if I replace the tab in the *second* row with spaces.

**Comment by iSazonov** [comment]
@Arnavion Thanks for you report. Could you please repo with laters daily build?

**Comment by iSazonov** [comment]
@Arnavion Thanks for the repo.

/cc @SteveL-MSFT Could you please comment the Issue?

**Comment by SteveL-MSFT** [comment]
Looks like a bug in the wrapping logic.  I'll look into this.

**Comment by SteveL-MSFT** [comment]
The way `-Wrap` works is that it tries not to split a word.  So in the second case above (w/ latest master), the wrap inserts a newline after the first `'d' * 100` since it fits, but puts the second one on a new line rather than split it.  In the first case, the tab character's display size isn't taken into account, so it treats it as size 1.  `'d' * 200` is wider than the width of the console, so it has to split it in half, but due to the wrong total length calculation of the tab, it inserts the newline in the wrong place.

Not sure how to fix this.  On macOS, the default tab stop is 8, so "a`tb" would show "a       b".  However you can use `tabs -4` to change the tab stop to 4 or even set different sizes for tab stop 1, 2, ... so we can't make assumptions about the tab stops.

**Comment by SteveL-MSFT** [comment]
There are already some places in the PowerShell code base that replaces tabs with four spaces, although it's not consistent everywhere.
