### ISSUE TITLE
In what conditions is `Cmdlet.StopProcessing()` invoked?

### ISSUE THREAD

**Issue by alx9r** [PowerShell/PowerShell#6316]
[The documentation for `Cmdlet.StopProcessing()`](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.cmdlet.stopprocessing?view=powershellsdk-1.1.0) includes the following statement:

>...interrupts currently running code within the command...

I understand this to mean that, when the PowerShell engine wants to interrupt the command, `StopProcessing()` is invoked.  Accordingly, I expect that `StopProcessing()` is called when certain errors are encountered or when <kbd>CTRL</kbd>-<kbd>C</kbd> are pressed during pipeline processing.  That behavior would be consistent with [this explanation on stackoverflow](https://stackoverflow.com/questions/1628127/difference-between-cmdlet-endprocessing-and-cmdlet-stopprocessing) and [this PluralSight course](https://www.pluralsight.com/courses/powershell-cmdlet-development-csharp).

I haven't succeeded at getting `StopProcessing()` to run at all.  In what conditions is `Cmdlet.StopProcessing()` invoked?  How can I reproduce those conditions?

Steps to reproduce
------------------

```powershell
Add-Type '
    using System;
    using System.Management.Automation; 
    
    [Cmdlet("Trace", "ProcessMethodOverrides")]
    public class TraceProcessMethodOverrides : Cmdlet 
    {
        [Parameter(Mandatory=true,ValueFromPipeline=true)]
        public object InputObject { get; set; }

        protected override void BeginProcessing()
        { 
            WriteVerbose("BeginProcessing");
        }

        protected override void ProcessRecord()
        { 
            WriteVerbose("ProcessRecord");
            WriteObject(InputObject,true);
        }

        protected override void EndProcessing()
        {
            WriteVerbose("EndProcessing");
        }

        protected override void StopProcessing()
        {
            WriteVerbose("StopProcessing");
        }
    }' -PassThru | % Assembly | Import-Module

function TerminateStatement {
    [CmdletBinding()]
    param
    (
        [Parameter(ValueFromPipeline)]$x
    )
    process
    {
        $PSCmdlet.ThrowTerminatingError(
            [System.Management.Automation.ErrorRecord]::new(
                'Statement-Terminating Error',
                'id',
                0,
                $null
            )
        )
    }
}

$ErrorActionPreference = 'Continue'
$VerbosePreference = 'Continue'
Write-Host '=== TerminateStatement'

1 | Trace-ProcessMethodOverrides | TerminateStatement

Write-Host '=== throw'
try
{
    1 | Trace-ProcessMethodOverrides | & {process{throw}}
}
catch {}

Write-Host '===Ctrl-C'
1 | Trace-ProcessMethodOverrides | % { sleep 10 } # press Ctrl-C while sleeping
```

Expected behavior
-----------------

```none=== TerminateStatement
VERBOSE: BeginProcessing
VERBOSE: ProcessRecord
TerminateStatement : Statement-Terminating Error
...
VERBOSE: StopProcessing
=== throw
VERBOSE: BeginProcessing
VERBOSE: ProcessRecord
VERBOSE: StopProcessing
===Ctrl-C
VERBOSE: BeginProcessing
VERBOSE: ProcessRecord
VERBOSE: StopProcessing
```

Actual behavior
---------------

```none
=== TerminateStatement
VERBOSE: BeginProcessing
VERBOSE: ProcessRecord
TerminateStatement : Statement-Terminating Error
... 
=== throw
VERBOSE: BeginProcessing
VERBOSE: ProcessRecord
===Ctrl-C
VERBOSE: BeginProcessing
VERBOSE: ProcessRecord
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value                                            
----                           -----                                            
PSVersion                      6.0.0                                            
PSEdition                      Core                                             
GitCommitId                    v6.0.0                                           
OS                             Microsoft Windows 6.3.9600                       
Platform                       Win32NT                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                          
PSRemotingProtocolVersion      2.3                                              
SerializationVersion           1.1.0.1                                          
WSManStackVersion              3.0                                              
```

**Comment by lzybkr** [comment]
The pipeline is stopped before calling `StopProcessing`, so you won't see any output, but the code is executed.

You can verify by calling `Console.WriteLine` instead of writing to the pipeline.

`StopProcessing` is meant for stopping a pipeline asynchronously, e.g. to unblock a thread waiting on an event or whatever. Ctrl+c is the obvious way to do this, but another common way is to call `PowerShell.Stop` or `PowerShell.BeginStop` on an instance of `PowerShell`, perhaps as a way of supporting a timeout on an operation.

**Comment by alx9r** [comment]
>You can verify by calling Console.WriteLine instead of writing to the pipeline.

Replacing `WriteVerbose` with `Console.WriteLine` in the repro outputs the following:

```none
=== TerminateStatement
BeginProcessing
ProcessRecord
TerminateStatement : Statement-Terminating Error
...
=== throw
BeginProcessing
ProcessRecord
===Ctrl-C
BeginProcessing
ProcessRecord
StopProcessing
```

This seems to indicate that `StopProcessing` is invoked when PowerShell is stopped using <kbd>CTRL</kbd>-<kbd>C</kbd> but is _not_ invoked when errors are encountered.  Is that correct @lzybkr?

**Comment by lzybkr** [comment]
Correct, errors are synchronous.

**Comment by alx9r** [comment]
Thanks for your help @lzybkr. :)
