### ISSUE TITLE
Preview Releases (and builds?) to have a different icon to help distinguish from production version

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#6317]
As agreed in [PR 6301](https://github.com/PowerShell/PowerShell/pull/6301), preview releases should have a different icon to distinguish it from the production version and avoid people accidentally using the preview version.
For the daily builds I already changed it using the code [here](https://github.com/PowerShell/PowerShell/blob/master/tools/install-powershell.ps1#L162) to use the [Powershell_av_colors.ico](https://raw.githubusercontent.com/PowerShell/PowerShell/master/assets/Powershell_av_colors.ico) icon:
![image](https://user-images.githubusercontent.com/9250262/36993175-06b144b8-20a5-11e8-8a96-c850bd366649.png)

The only remaining icon is [Powershell_avatar.ico](https://raw.githubusercontent.com/PowerShell/PowerShell/master/assets/Powershell_avatar.ico):
![image](https://user-images.githubusercontent.com/9250262/36993205-1a3065f0-20a5-11e8-8d1b-946d8fbc7bd5.png)

Therefore I suggest that the preview should use the [Powershell_av_colors.ico](https://raw.githubusercontent.com/PowerShell/PowerShell/master/assets/Powershell_av_colors.ico) icon instead now and the daily builds should start using the  [Powershell_avatar.ico](https://raw.githubusercontent.com/PowerShell/PowerShell/master/assets/Powershell_avatar.ico) icon instead.

I think, preview builds (produced e.g. by AppVeyor) should also have a different icon and I will leave it up to the maintainers which of the 2 icons to choose or if a new icon should be used for those.

**Comment by Lachlan125** [comment]
Just a quick question how can I get an installer of the nightly version of powershell 6.1 I have been looking everywhere on the site cannot seem to locate. I am a 16 year old high school student whom is looking at and wanting to code programs and apps. Please help

**Comment by bergmeister** [comment]
@Lachlan125 You can e.g. use the following command (on any OS) to get an unzipped installation of the daily build
````powershell
iex "& { $(irm https://aka.ms/install-pscore ) } -Daily"
````
Otherwise you can click also e.g. on the AppVeyor builds of any commit and download the msi as an artefact for a proper installation.
