### ISSUE TITLE
Does the PowerShell SDK needs to include module manifests etc.?

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#6340]
I've gotten a PowerShell Core host working (finally!) using the new 6.0.1.1 SDK release -- if you want an example, it's [my Jupyter-PowerShell kernel](https://github.com/Jaykul/Jupyter-PowerShell)

However, there's one or two significant problems.

The primary one is that without the `Modules` folder that PowerShell ships, there are no modules at all, and even simple command lines like `Get-Command` fail with a "Command not found" error.

Since the built-in modules _need to be available_ when someone's hosting PowerShell - which means they need to be on the `PSModulePath`, I think that means they should be included as content in the SDK, and I think that PowerShell itself should make sure that path is _always_ included, regardless of whether PowerShell is created via `PowerShell.Create()` or `RunspaceFactory.CreateRunspace` ... and regardless of the value of the environment variable when PowerShell is initialized.

**Comment by bergmeister** [comment]
@Jaykul I was playing with the SDK as well and found that it was better to to do a platform specific `dotnet publish` to get all dependencies to work on non-Windows systems.

**Comment by Jaykul** [comment]
@bergmeister yep. In order to ship something, you have to -publish, otherwise everyone needs the SDK ;-)

**Comment by bergmeister** [comment]
No, I rather meant specifying the platform when publishing. Net core can make a generic publish folder that 'should' run everywhere but specifying the platform compiles a platform specific and optimised version and I found that I had to use this rather than the generic one because otherwise native low level dependencies were missing.
