### ISSUE TITLE
How can I access the interactive desktop from a JEA endpoint?

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShell#6341]
Is it possible?

I guess I would involve running as LocalSystem and use ```WTSQueryUserToken (WTSGetActiveConsoleSessionId (), &hToken) ;``` and ```CreateProcessAsUser```, but I can't figure out how to configure the session.

**Comment by BrucePay** [comment]
Just out of curiosity, what's the scenario you're trying to enable?

**Comment by powercode** [comment]
Launching AAA games on test machines, monitor it, gather logs and crashdumps, restart it etc.

And doing it without sending clear text passwords.

**Comment by powercode** [comment]
@SteveL-MSFT

**Comment by SteveL-MSFT** [comment]
@powercode it seems that you might be able to [modify the ACL on a winstation](https://msdn.microsoft.com/en-us/library/windows/desktop/ms687391(v=vs.85).aspx) so you can read the screen
