### ISSUE TITLE
Expand-Archive doesn't use -WhatIf parameter from calling function

### ISSUE THREAD

**Issue by juliank** [PowerShell/PowerShell#6342]
When decorating a function with `[CmdletBinding(SupportsShouldProcess=$true)]`, calling that function with `-WhatIf` will pass on the `-WhatIf` parameter to functions called within that also supports this. In the example below one can see this working for `Move-Item`, but not for `Expand-Archive`.

Steps to reproduce
------------------

```powershell
function Demonstrate-Bug {
    [CmdletBinding(SupportsShouldProcess=$true)]
    param ()

    # Does not rename file, but instead outputs the following:
    # What if: Performing the operation "Move File" on target "Item: C:\Temp\Foo.zip Destination: C:\Temp\Bar.zip".
    Move-Item -Path .\Foo.zip -Destination Bar.zip

    # Would expect the following to not expand the archive, but instead only print a "What if" message similar to above.
    Expand-Archive -Path .\Foo.zip

    # If Expand-Arvhice is called explicitely with -WhatIf, I get the following output:
    # What if: Performing the operation "Expand-Archive" on target "C:\Temp\Foo.zip".
}

Demonstrate-Bug -WhatIf
```

Expected behavior
-----------------

`Expand-Archive` isn't actually called, but instead a message explaining what would happen without `-WhatIf` is outputted.

Actual behavior
---------------

The `Foo.zip` archive gets expanded, even though `Demonstrate-Bug` is called with the `-WhatIf` parameter.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.16299.248
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.248
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by mklement0** [comment]
Good catch; it seems that `Expand-Archive` only respects the _global_ scope's `$WhatIfPreference` variable, not the local copy created implicitly inside the advanced function.

**Comment by markekraus** [comment]
Hi @juliank ! can you file this issue at the https://github.com/PowerShell/Microsoft.PowerShell.Archive repo where the `Expand-Archive` code is maintained?

The problem appears to be here:

https://github.com/PowerShell/Microsoft.PowerShell.Archive/blob/master/Microsoft.PowerShell.Archive/Microsoft.PowerShell.Archive.psm1#L336

Rather than using `$PSCmdlet.ShouldProcess()` they are checking if the `-WhatIf` parameter is bound.. which means it would only support `-WhatIf` if directly supplied to the function.

**Comment by juliank** [comment]
I wasn't aware of that @markekraus, thank you.

But that doesn't seem like particularly active repo. I found [an issue describing this very bug](https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/35), which is a whole year old, and there isn't even a single comment. Much less any work done solving it...
