### ISSUE TITLE
Why is ,(1)[1] different from ,$null?

### ISSUE THREAD

**Issue by alx9r** [PowerShell/PowerShell#6357]
I'm trying to understand why the following two statements yield different outputs:

```PowerShell
&{,$null} | % {'x'} # x
&{,(1)[1]} | % {'x'} # no output
```

`,$null` and `,(1)[1]` both seem to be arrays containing a single null element.  Yet they behave differently during output from a scriptblock.  What is happening here?

**Comment by powercode** [comment]
The second returns `AutomationNull.Value` which is not enumerated by the pipeline.

`$null` is enumerated.

**Comment by alx9r** [comment]
Thank you @powercode.  For posterity, here are some resources on `AutomationNull`:

* [#5674 (comment)](https://github.com/PowerShell/PowerShell/issues/5674#issuecomment-352260793)
* [stackoverflow.com: Why and how are these two $null values different?](https://stackoverflow.com/questions/30016949)

**Comment by mklement0** [comment]
@alx9r: This comes down to the question you later asked in #6436 and which I've brought into focus in https://github.com/PowerShell/PowerShell/issues/6436#issuecomment-375151317, but I've decided to create a separate issue for it: #6823
