### ISSUE TITLE
Support more distributions in installpsh-debian.sh script

### ISSUE THREAD

**Issue by pawamoy** [PowerShell/PowerShell#6364]
This is a follow-up of #6314 (and #5700).

I would like to know if you want to support more Debian distributions in the installation script, and if so, how you would like to support them (and if this would be tested or not).

We could simply add a message in the script that says to open a PR (with a link to this repo) to add support for the current distribution (if it's not already supported), and let people open PRs one by one.

If you are ok with more distributions support, I can immediately add BunsenLabs to the list :wink: 

The diff is basically:

```diff
- debian)
+ debian|bunsenlabs)
```

I tried it and it works fine!

**Comment by iSazonov** [comment]
I wonder - how many Debian distributions exist?
I would prefer to add references to community-supported scripts to our documentation.

**Comment by Pawamoy** [comment]
There are a lot indeed! Here is the [Debian family tree](https://upload.wikimedia.org/wikipedia/commons/6/69/DebianFamilyTree1210.svg).

Would these community-supported scripts reside in the powershell repository itself? Or another, dedicated repository? Or would the references just point to random repositories, like `https://github.com/some-user/some-repo/blob/master/installpsh-some-distro.sh`, and people would open PRs to add them in the docs?

**Comment by iSazonov** [comment]
I believe we can not test and support all such scripts in the repo.

/cc @joeyaiello @SteveL-MSFT

**Comment by SteveL-MSFT** [comment]
@Pawamoy are you aware of any existing precedent set by other projects when the community extends distro support?  If there's already a well defined pattern, would prefer to use that unless there's a big reason not to follow it.

**Comment by Pawamoy** [comment]
@SteveL-MSFT unfortunately no, but I will dig a bit and see if I can find some useful examples or patterns.

**Comment by iSazonov** [comment]
@pawamoy Have you any updates?

**Comment by iSazonov** [comment]
@pawamoy In the repo we can support only distributives which CoreFX supports. Other ones can be only community driven.

**Comment by pawamoy** [comment]
Seeing that LinuxMint was added, would you agree to add BunsenLabs to the list? I know it's not a widespread distribution but I'm still interested in it being supported. Besides, as written in the first comment, it's simply a matter of adding `bunsenlabs` in the `debian)` case. I can open a new issue for it if you prefer.

**Comment by iSazonov** [comment]
I see that Linux Mint will added in .Net Core 3.0 https://github.com/dotnet/core/blob/de2f7eaab2bb652b246c322827bda42a05e2fbb3/release-notes/3.0/3.0-supported-os.md#linux

@pawamoy We will move to 3.0 in weeks. Please wait and then you can make PR to update the install script and docs.

**Comment by TravisEz13** [comment]
We have two paths, PowerShell can support it.  Or this script can unofficially support it.  If we want the former, we should file an issue that specifically asks that linux mint be added to the list of supported distributions.

**Comment by pawamoy** [comment]
About LinuxMint, I myself have no preferences. About BunsenLabs, I don't mind it being unofficially supported in the script. Afterall, I just want to be able to run `./installpsh-debian.sh`.

**Comment by TravisEz13** [comment]
BunsenLabs would have to be unofficial as it's not supported by DotNet.

**Comment by SteveL-MSFT** [comment]
@pawamoy perhaps an option is to update `./installpsh-debian.sh` to have a `-force` type switch so that we aren't preventing attempts to use it but it wouldn't be something we would support

**Comment by pawamoy** [comment]
@SteveL-MSFT I think it would complicate the script too much. I understand it's preferable to only add officially supported distributions in the script (by the way, debian 8 still appears in the script but is out of support, right?), so I won't push for BunsenLabs. For people who really want to install it on a distro based on debian 9, it's very easy anyway:

```bash
curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
curl https://packages.microsoft.com/config/debian/9/prod.list | sudo tee /etc/apt/sources.list.d/microsoft.list
sudo apt-get update
sudo apt-get install powershell
```

Thanks for your feedback everyone :slightly_smiling_face:

**Comment by iSazonov** [comment]
#10773 now we use /etc/os-release
