### ISSUE TITLE
S.M.A.Powershell class :  the contents of the 'IsRunspaceOwner' property change after displaying the instance in the console.

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/PowerShell#6365]
Steps to reproduce
------------------

```powershell
$ps=[powershell]::Create()

$ps.IsRunspaceOwner
#False

$ps
# 
# Commands            : System.Management.Automation.PSCommand
# Streams             : System.Management.Automation.PSDataStreams
# InstanceId          : 751da833-83c7-4577-af37-346f05251001
# InvocationStateInfo : System.Management.Automation.PSInvocationStateInfo
# IsNested            : False
# HadErrors           : False
# Runspace            : System.Management.Automation.Runspaces.LocalRunspace
# RunspacePool        :
# IsRunspaceOwner     : True
# HistoryString       :
# 

$ps.IsRunspaceOwner
#True

```

Expected behavior
-----------------
The contents of the 'IsRunspaceOwner' property corresponding to the state of the associated runspace object.

Actual behavior
---------------
The contents of the 'IsRunspaceOwner' property change after displaying the instance in the console.

Environment data
----------------
```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Microsoft Windows 6.1.7601 S
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.1}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
`IsRunspaceOwner` doesn't get set until the Runspace is created (using the getter is sufficient).  Seems like we should just add more documentation to this member.

**Comment by LaurentDardenne** [comment]
> Seems like we should just add more documentation to this member.

Although this seems to be an implicit behavior, could you also specify the role of this property when we  calling the Dispose() method?

For example in the following case does the call to Dispose() 'delete' the associated runspace ?
```Powershell
 $InitialSessionState= [System.Management.Automation.Runspaces.InitialSessionState]::Create()

 $SessionStateCmdletEntry = New-Object System.Management.Automation.Runspaces.SessionStateCmdletEntry 'Get-ChildItem',([Microsoft.PowerShell.Commands.GetChildItemCommand]),$null
 $InitialSessionState.Commands.Add($SessionStateCmdletEntry)

 $Runspace= [RunspaceFactory]::CreateRunspace($InitialSessionState)
 $Runspace.Open()

 try {
  $PS = [PowerShell]::Create()
  $PS.Runspace = $Runspace
  $null=$PS.AddCommand("Get-ChildItem").AddParameter('Path','c:\temp\') 
  $Results = $PS.Invoke()
  if ($PS.Streams.Error.Count -gt 0)
  { 
    Write-Warning "Erreur"
    $PS.Streams.Error 
  }
 }
 finally {
  $PS.Dispose()
 }
```

**Comment by SteveL-MSFT** [comment]
@LaurentDardenne `IsRunspaceOwner` is `$true` when there is an associated runspace.  On `Dispose()`, if `IsRunspaceOwner == true`, `Dispose()` is [called on the runspace](https://github.com/PowerShell/PowerShell/blob/c1c5344a8897262433141ecbc13bb06ac2c4bbef/src/System.Management.Automation/engine/hostifaces/PowerShell.cs#L3830)

**Comment by LaurentDardenne** [comment]
Thank you.

**Comment by LaurentDardenne** [comment]
In case I create an instance of the Powershell class by specifying an InitialSessionState, the runspace is created internally, but the 'IsRunspaceOwner' property is not updated.
Is this another behavior that is not documented or a bug?
```powershell 
try {
  $InitialSessionState=  [System.Management.Automation.Runspaces.InitialSessionState]::Create()
  
 $SessionStateCmdletEntry = New-Object System.Management.Automation.Runspaces.SessionStateCmdletEntry 'Get-ChildItem','Microsoft.PowerShell.Commands.GetChildItemCommand',$null
 $InitialSessionState.Commands.Add($SessionStateCmdletEntry)

 $Provider = New-Object System.Management.Automation.Runspaces.SessionStateProviderEntry 'FileSystem',([Microsoft.PowerShell.Commands.FileSystemProvider]),$null
 $InitialSessionState.Providers.Add($Provider)

  $PS = [PowerShell]::Create($InitialSessionState)
  Write-Warning "Automatic release : $($ps.IsRunspaceOwner)"
   $PS.AddCommand("Get-ChildItem") > $null
   $Results = $PS.Invoke()                        
  Write-Warning "Automatic release : $($ps.IsRunspaceOwner)"

}
finally {
 $PS.Dispose()
}
#WARNING: Automatic release : False
#WARNING: Automatic release : False

$PS.Runspace

#  Id Name            ComputerName    Type          State         Availability
#  -- ----            ------------    ----          -----         ------------
#   2 Runspace2       localhost       Local         Opened        Available
```

**Comment by SteveL-MSFT** [comment]
@LaurentDardenne that seems like a bug to me.  Perhaps you can open that as a separate issue so we can use this one for the doc update?

**Comment by LaurentDardenne** [comment]
See #6422

Some examples in the class documentation use wrong method name :
[AddArgument](https://github.com/PowerShell/PowerShell/blob/c1c5344a8897262433141ecbc13bb06ac2c4bbef/src/System.Management.Automation/engine/hostifaces/PowerShell.cs#L1328), [AddScript](https://github.com/PowerShell/PowerShell/blob/c1c5344a8897262433141ecbc13bb06ac2c4bbef/src/System.Management.Automation/engine/hostifaces/PowerShell.cs#L992).

**Comment by joeyaiello** [comment]
Closing this issue to track the doc bug out of PowerShell/PowerShell-Docs#3041

**Comment by joeyaiello** [comment]
The fix here is just a change to the `///` comments that @LaurentDardenne mentioned. Re-opening here so we can close the one on MicrosoftDocs/PowerShell#3041
