### ISSUE TITLE
PowerShell 6.0.2 Release

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#6383]
From:  https://github.com/PowerShell/PowerShell/blob/master/docs/maintainers/releasing.md

- [x] Create a branch named `6.0.2` in private repository.
   All release related changes should happen in this branch.
- [x] Run tests on all supported Linux distros and publish results
- [x] Prepare packages
   - [x]  Build release packages
   - [x]  Sign the MSI packages and RPM package.
   - [x]  Install and verify the packages.
- [x]  Update documentation, scripts and Dockerfiles
   - [x]  Update [CHANGELOG.md](../../CHANGELOG.md) with the finalized change log draft.
   - [x]  Update other documents and scripts to use the new package names and links.
- [x]  Verify the release Dockerfiles.
- [x]  Create NuGet packages and publish them to `powershell-core` feed.
- [x]  Publish Linux packages to Microsoft YUM/APT repositories.
- [x]  Create the release tag and push the tag to `PowerShell/PowerShell` repository.
- [x]  Create the draft and publish the release in Github.
- ~~Merge the `release` branch to `master` and delete the `release` branch.~~
- [x]  Trigger the release docker builds for Linux and Windows container images.
   - [x]  Linux: push a branch named `docker` to `powershell/powershell` repository to trigger the build at [powershell docker hub](https://hub.docker.com/r/microsoft/powershell/builds/).
     Delete the `docker` branch once the builds succeed.
   - [x]  Windows: queue a new build in `PowerShell Windows Docker Build` on VSTS.
- [x]  Verify the generated docker container images.

**Comment by bergmeister** [comment]
Is this because of https://github.com/dotnet/announcements/issues/62?

**Comment by TravisEz13** [comment]
@bergmeister Please see our policy on [reporting security issues](https://github.com/PowerShell/PowerShell/blob/master/docs/maintainers/issue-management.md#security-vulnerabilities) and our [Release Steps](https://github.com/PowerShell/PowerShell/blob/master/docs/maintainers/releasing.md#release-steps).  At step 8 in the release, all work in the release will become public.  Other than work that must remain private due to policy, is also submitted to master and marked for the 6.0.2 milestone.

**Comment by TravisEz13** [comment]
```
Pass Total Fail Skipped Pending OS                          
---- ----- ---- ------- ------- --                          
6043  7629   17    1226     343 CentOS Linux 7 (Core)       
6060  7629    1    1226     342 Debian GNU/Linux 8 (jessie) 
6060  7629    1    1226     342 Debian GNU/Linux 9 (stretch)
6060  7629    2    1226     341 openSUSE Leap 42.3          
6042  7629   19    1226     342 Red Hat Enterprise Linux    
6060  7629    1    1226     342 Ubuntu 14.04.5 LTS          
6060  7629    1    1226     342 Ubuntu 16.04.3 LTS          
6060  7629    1    1226     342 Ubuntu 17.04                
```

**Comment by TravisEz13** [comment]
Nanoserver image is delayed.

**Comment by TravisEz13** [comment]
Nanoserver image is in docker hub and verified

**Comment by bergmeister** [comment]
@TravisEz13  Note that the [releases](https://github.com/PowerShell/PowerShell/releases) page contains a spelling mistake of the word `releases`: It says `v6.0.2 releaes of PowerShell Core`

**Comment by TravisEz13** [comment]
@bergmeister Thanks.  I think I fixed it.

**Comment by bergmeister** [comment]
@TravisEz13 `vulnerabilities` is also misspelled as `vulenerabilities`

**Comment by TravisEz13** [comment]
Thanks again, updated

**Comment by bergmeister** [comment]
You're welcome.
