### ISSUE TITLE
Opening vim within Powershell cmdlet is broken

### ISSUE THREAD

**Issue by mallochine** [PowerShell/PowerShell#6395]
Steps to reproduce
------------------

My C# code:
```
using Newtonsoft.Json.Linq;

[CmdletAttribute("Set", "Json")]
public class SetJsonCmdlet : Cmdlet {
  protected override void ProcessRecord() {
    System.Diagnostics.Process.Start("/bin/vim", "/home/nutanix/asdf");
  }
}
```

Makefile:
```
mcs -target:library -out:a.dll -reference:$(DEPS_DIR)/Newtonsoft.Json.10.0.3/lib/net40/Newtonsoft.Json.dll
```

Compile using `make`

Then in powershell, I run: 
```powershell
Import-Module ./a.dll
Set-Json
```

How to install Newtonsoft.Json dependency: `nuget install -OutputDirectory deps Newtonsoft.Json -Version 10.0.3`

Expected behavior
-----------------

Should open up vim editor cleanly.

Actual behavior
---------------

It looks like both powershell and vim are outputting chars to stdout? It's screwed up for sure.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Linux 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by BrucePay** [comment]
You're getting output from both programs at the same time because your cmdlet isn't waiting for the editor to exit. Calling `Start()` on the `Process` class is non-blocking. The editor starts and PowerShell keeps on going. If you change your code to capture the the process object then call `.WaitForExit()` you should be fine:
``` 
var proc = System.Diagnostics.Process.Start("/bin/vim", "/home/nutanix/asdf");
proc.WaitForExit();
```

**Comment by mallochine** [comment]
sorry bug in C# code. Thank you BrucePay.
