### ISSUE TITLE
Import-Module on Mac/Linux errors due to not finding nuget dependency that is referenced

### ISSUE THREAD

**Issue by Salmanius** [PowerShell/PowerShell#6400]
Steps to reproduce
------------------

Not easily reproducible, but the issue comes from the nuget package "System.Runtime". In our csproj file that build the DLL that fails, we build for netcoreapp2.1 along with net451. The net451 dll on windows works great. The build for both DLLs works, but the mac/linux import does not work. We use the following Package References for the netcoreapp2.1 framework build.

```xml
<ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp2.1' ">
    <PackageReference Include="Microsoft.PowerShell.SDK" Version="6.0.1.1" />
    <PackageReference Include="System.Runtime" Version="4.3.0" />
  </ItemGroup>
```
As you can see we are referencing System.Runtime version 4.3 which is the newest version. The problems come when you try and import that dll (or the psd1 file). The error is listed below in Actual Behavior. It is erroring on not being able to find version 4.2.1, which is never referenced in our project or anywhere we can find. Removing the version tag results in the same behavior, along with removing the whole package reference line. 

Expected behavior
-----------------

```none
The library is found, and the module properly imports.
```

Actual behavior
---------------

```powershell
Import-Module : Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
At line:1 char:1
+ Import-Module SolidFire
+ ~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
+ FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand

```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value                                                                                                                                                    
----                           -----                                                                                                                                                    
PSVersion                      6.0.1                                                                                                                                                    
PSEdition                      Core                                                                                                                                                     
GitCommitId                    v6.0.1                                                                                                                                                   
OS                             Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64                                            
Platform                       Unix                                                                                                                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                                                      
SerializationVersion           1.1.0.1                                                                                                                                                  
WSManStackVersion              3.0                        
```

**Comment by daxian-dbw** [comment]
@adityapatwardhan Can you take a look?
FWIW, PowerShell 6.0.1.1 depends on `System.Runtime 4.2.0.0`.

**Comment by ahaid** [comment]
Why does it depend on `System.Runtime 4.2.0.0`? From what I'm seeing on the [csproj](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj), most of the version references are `4.4.*`.

**Comment by daxian-dbw** [comment]
@ahaid Assembly version is different from a package version.

**Comment by adityapatwardhan** [comment]
@Salmanius Do you see the same problem if the netcoreapp version is 2.0?

**Comment by Salmanius** [comment]
Sorry for the slow response. We got the issues worked out for our short term purposes. Netcoreapp 2.0 works, building for 2.0 with 2.1-preview1 works but building for 2.1 fails. The chart below shows how it runs on a Mac running Powershell 6.0.2. 

<img width="468" alt="screen shot 2018-03-30 at 11 51 45 am" src="https://user-images.githubusercontent.com/12905380/38147727-c14bfa56-3410-11e8-86b3-b6aa8f024c7f.png">

The SSL Error in the 2.0 is why we are trying to bump the version to 2.1 so we can access the new class "SocketsHttpHandler" to handle the problems with SSL handling on Mac.

**Comment by JamesWTruher** [comment]
this looks to be answered
