### ISSUE TITLE
Enable-PSRemoting takes a long time when number of registered endpoints is large

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#6407]
`Enable-PSRemoting` takes a long time when the number or registered endpoint is large. 
Adding 10 endpoints increases the duration by a factor almost 5 times.

Steps to reproduce
------------------

```powershell
Measure-Command { Enable-PSRemoting -SkipNetworkProfileCheck }
TotalSeconds      : 35.8128436

1..10 | % { Register-PSSessionConfiguration -Name $_ } 


Measure-Command { Enable-PSRemoting -SkipNetworkProfileCheck }
TotalSeconds      : 174.0488275
```

Expected behavior
-----------------

Number of registered endpoints should not affect the performance of `Enable-PSRemoting`

Actual behavior
---------------

```none
Duration increases by a factor of about 5.
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by namangoel19** [comment]
I tried with GA build on Cent OS 7.3.

from there I am running invoke-command and calling some powershell on windows, first time it is working fine and it is returning response in 10 sec but after that the invoke-command is taking too much time.

Any body is facing the same issue?
