### ISSUE TITLE
No way to detect if a file pointed to by System.IO.FileInfo is special (device, socket, fifo)

### ISSUE THREAD

**Issue by DHowett-MSFT** [PowerShell/PowerShell#6410]
Steps to reproduce
------------------

```powershell
Get-Item /dev/null | fl *
Get-Item /path/to/a/socket | fl *
```

Expected behavior
-----------------

Expected some way to determine that `null` is a _character device_, or that `socket` is a UNIX domain socket

Actual behavior
---------------

No such way.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0
PSEdition                      Core
GitCommitId                    v6.0.0
OS                             Linux 4.15.0-1-amd64 #1 SMP Debian 4.15.4-1 (2018-02-18)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Also 6.0.1, 6.0.2.
Similar to #1817.

**Comment by DHowett-MSFT** [comment]
(I realize this is likely to be a limitation of .NET Core; it is perhaps still useful to catalogue here.)

**Comment by DHowett-MSFT** [comment]
Relies on/discussed further in dotnet/corefx#312

**Comment by iSazonov** [comment]
> Relies on/discussed further in dotnet/corefx#312

New link https://github.com/dotnet/runtime/issues/13946
