### ISSUE TITLE
Is there a way to predicate stream redirection?

### ISSUE THREAD

**Issue by alx9r** [PowerShell/PowerShell#6423]
I'm wondering if it's possible to predicate stream redirection on some user-defined logic without resorting to building a command line using strings.  Here is a mock up of what I am trying to achieve:

```PowerShell
function f {
    Write-Error 'f'
}

function g {
    param([switch]$SuppressErrorStream)
    # ... imagine some elaborate logic deciding about stream 
    # redirection is here ...

    # How can I predicate the redirection of the error stream on,
    # for example, $SuppressErrorStream?

    f 2>$null
}

g                      # this should leave the error stream unredirected
g -SuppressErrorStream # this should redirect the error stream to null
```

Note that I don't want to prevent writes to the error stream (so `$ErrorActionPreference` isn't suitable), rather I want to programmatically control the output of the error stream.  These are two different concepts by design per #4572.

The analog for arguments that I use is `@splat`.  Is there something similar to splatting for the stream redirection operators?

**Comment by BrucePay** [comment]
Splatting language elements (e.g. redirections) is problematic because a PowerShell script is full compiled before execution begins.  Perhaps you could use scriptblocks and do something like:
```
function f {
    Write-Error 'f'
}

function g {
    param([switch]$SuppressErrorStream, $commandScriptblock)

    if ($SuppressErrorStream)
    {
        & $commandScriptblock 2> $null
    }
    else
    {
        & $commandScriptblock
    }
}

"Suppress"
g -SuppressErrorStream {f}
"Don't suppress"
g {f}
```

**Comment by alx9r** [comment]
>Splatting language elements (e.g. redirections) is problematic because a PowerShell script is full compiled before execution begins.

Oh right.  I see that now. 

>Perhaps you could use scriptblocks...

That seems like the best option.  Thanks for your help @BrucePay!
