### ISSUE TITLE
get-childitem "directory:"

### ISSUE THREAD

**Issue by veepee78** [PowerShell/PowerShell#6424]
reproduce:
go, for example, to c:\windows directory and type

get-childitem c:\users

-> get-childitem first line says Directory: c:\windows, and then it lists users directory contents. Is this intended behavior? If it is, it's quite confusing. Same with earlier versions. This is also very confusing when using filter to search subdirectories.

I would expect directory: to show the listed directory's name, not the current.

**Comment by markekraus** [comment]
This does not reproduce for me 6.0.2

![2018-03-19_6-53-44](https://user-images.githubusercontent.com/6509955/37594177-7880c7a6-2b42-11e8-8530-7e2956ca70d4.png)

Nor in  5.1.16299.251:

![2018-03-19_6-56-22](https://user-images.githubusercontent.com/6509955/37594343-e3e1d0bc-2b42-11e8-92ee-64d714b16402.png)


Can you verify that this behavior persists by starting PowerShell with the `-NoProfile` option?

**Comment by MaximoTrinidad** [comment]
@veepee78 ,

It's important to always provide the information of both PowerShell Core and which Windows OS versions are in play.

Behavior is as expected! No issues.
:)

**Comment by veepee78** [comment]
@markekraus I did try with noprofile and it worked as in your screenshots. Without it as I described. Seems that pscolor caused this weird behavior.

@MaximoTrinidad  Yes, I should have told those. win10ent, powershell 6.0.1 and 5.1.

Ok, so issue only at my end. Closed.
