### ISSUE TITLE
get-childitem -recurse is pulling twice from apple file share with two root folders

### ISSUE THREAD

**Issue by jackfruh** [PowerShell/PowerShell#6425]
Is this a bug in get-childitem?

On Mac OS 10.12.6, powershell core 6.0.2

Steps to recreate:
1. Mount network share using apple file protocol:
(finder -> Go menu -> Connect to server -> afp://ipaddress/sharename
2. open powershell for this location 
3. type $items = get-childitem -recurse
4. Observe: each item is in the $items array twice.
5. Observe $items.count is exactly 2x times the actual count of files.

Note: adding a 3rd empty folder on the share and rerun the command, it returns the correct number of files.

![screenshot of terminal](https://content.screencast.com/users/basementjack/folders/Snagit/media/90b172d6-612c-4beb-baaf-14c08e9fec16/2018-03-19_08-27-27.png)

Note in the above screenshot, it should not be possible for the first result to be greater than the second result.

Can anyone else recreate this behavior?

**Comment by iSazonov** [comment]
@jackfruh Do you see the issue with latest PowerShell 7.0 build?

**Comment by iSazonov** [comment]
Close as stale issue. Feel free to continue discussion.
