### ISSUE TITLE
Unable to load System.Data.SqlClient, Version 4.2.0.2

### ISSUE THREAD

**Issue by axelheer** [PowerShell/PowerShell#6426]
Steps to reproduce
------------------

Call a custom Cmdlet, which uses the current version 2.0.2 of *Entity Framework Core*, which uses the current version 4.4.3 of *System.Data.SqlClient*, which has the actual assembly version 4.2.0.2.

```powershell
> [System.AppDomain]::CurrentDomain.GetAssemblies() |? { $_.Location -match "SqlClient" }
> Get-Geburtstagsliste
Get-Geburtstagsliste : Could not load file or assembly 'System.Data.SqlClient, Version=4.2.0.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
At line:1 char:1
+ Get-Geburtstagsliste
+ ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Get-Geburtstagsliste], FileLoadException
+ FullyQualifiedErrorId : noe.dotnuts2.Jobs.Commands.GetGeburtstagsliste

> [System.AppDomain]::CurrentDomain.GetAssemblies() |? { $_.Location -match "SqlClient" }

GAC    Version        Location
---    -------        --------
False  v4.0.30319     C:\Program Files\PowerShell\6.0.2\System.Data.SqlClient.dll
```

The then loaded assembly has the version 4.2.0.1, which matches the version 4.4.2 of *System.Data.SqlClient*, but is older / not compatible with the desired version 4.4.3.

Shouldn't include an update to .NET Core version 2.0.6 as described for PowerShell Core 6.0.2 also include an update for stuff like 'System.Data.SqlClient'?

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
6.0.2 is only a security update.

**Comment by axelheer** [comment]
Any idea how to load the "correct" version of *System.Data.SqlClient*?

**Comment by MaximoTrinidad** [comment]
After opening PWSH:
No load required:
```
$getSqlSvr = "mars";
$sqlcon = "server=$getSqlSvr;database=Master;Integrated Security=false;User ID=sa;" + 'Password=$SaPasswd1!';

## - SQL Query:
$SqlQry = @'
sp_who2
'@;

## - Create connection to SQL Server and execute the T-SQL command:
$sda = New-Object System.Data.SqlClient.SqlDataAdapter ($SqlQry, $sqlcon);
$sdt = New-Object System.Data.DataTable;
$sda.fill($sdt) | Out-Null;

PS [20] > $sdt.rows | Select-Object -first 10 | Format-Table;

SPID  Status                         Login HostName BlkBy DBName Command          CPUTime DiskIO LastBatch
----  ------                         ----- -------- ----- ------ -------          ------- ------ ---------
1     BACKGROUND                     sa      .        .          XTP_CKPT_AGENT   0       0      03/19 12:39:25
2     BACKGROUND                     sa      .        .          LOG WRITER       0       0      03/19 12:39:25
3     BACKGROUND                     sa      .        .          RECOVERY WRITER  0       0      03/19 12:39:25
4     BACKGROUND                     sa      .        .          LAZY WRITER      0       0      03/19 12:39:25
5     BACKGROUND                     sa      .        .          LOCK MONITOR     0       0      03/19 12:39:25
6     BACKGROUND                     sa      .        .   master SIGNAL HANDLER   0       0      03/19 12:39:25
7     BACKGROUND                     sa      .        .          XIO_RETRY_WORKER 0       0      03/19 12:39:25
8     BACKGROUND                     sa      .        .          XIO_LEASE_RENEWA 0       0      03/19 12:39:25
9     BACKGROUND                     sa      .        .   master BRKR TASK        0       0      03/19 12:39:31
12    BACKGROUND                     sa      .        .          RESOURCE MONITOR 0       0      03/19 12:39:25
```
Works perfectly!!

**Comment by axelheer** [comment]
Using it directly isn’t the same as using it as a dependency (of another dependency), when it’s referenced using a higher (!) assembly version.

The problem is, that the current PowerShell version, which is build on the current .NET Core version, comes with an older (?) SqlClient version. And that does not work, if a Cmdlet has a dependency, which uses the current Entity Framework, which uses the *current* (!) SqlClient.

Welcome back, DLL hell!

**Comment by MaximoTrinidad** [comment]
@axelheer, Gotcha!!

Let me check on my setup and see what I get then.

:)

**Comment by hali15845** [comment]
@axelheer Did you find any workaround? I have the same issue.

**Comment by mi-hol** [comment]
@axelheer did the release of new SDK version change anything?
https://github.com/PowerShell/PowerShell/issues/6475

**Comment by MaximoTrinidad** [comment]
Hi there!

You may want to try either the latest 6.0.4 GA  and/or Preview-4.

Both work as expected!

:)

![gasqldata_2018-08-17_16-46-36](https://user-images.githubusercontent.com/19892435/44288188-6f5ef900-a23d-11e8-955a-5f75a8d31824.jpg)

![presqldata_2018-08-17_16-46-36](https://user-images.githubusercontent.com/19892435/44288201-771e9d80-a23d-11e8-8c37-0992bbd1ae23.jpg)

**Comment by axelheer** [comment]
@mi-hol I don't compile against the full SDK, only the PowerShell Standard

**Comment by brent-robinson** [comment]
I experienced a similar problem on PowerShell 6.1.1 when loading `System.Data.SqlClient`, however it appears to be resolved under PowerShell 6.2.0-preview.3

```
PowerShell 6.1.1
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS C:\Program Files\PowerShell\6> Add-Type -Path F:\Temp\System.Data.SqlClient.dll
Add-Type : Could not load file or assembly 'System.Data.SqlClient, Version=4.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
At line:1 char:1
+ Add-Type -Path F:\Temp\System.Data.SqlClient.dll
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Add-Type], FileLoadException
+ FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.AddTypeCommand
PS C:\Program Files\PowerShell\6-preview>
```

```
PowerShell 6.2.0-preview.3
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS C:\Program Files\PowerShell\6-preview> Add-Type -Path F:\Temp\System.Data.SqlClient.dll
PS C:\Program Files\PowerShell\6-preview>
```

Further usage allows me to run Entity Framework Core. Loading `Newtonsoft.Json.dll` also works under the preview version.

**Comment by MaximoTrinidad** [comment]
@brent-robinson 

Hum! Something is missing in your sample.

First, System.Data.SqlClient.dll is included in the PowerShell 6.1.1 folder, and it's working fine.

So, I'm dare to assuming that you installed another version of the DLL. Right!
If that's the case then... maybe... that DLL on the F: drive wasn't build to work with 6.1.1 .NET Core Version(??)

Any way, look at the https://github.com/PowerShell/PowerShell/releases where is states that on the PowerShell Core v6.2.0-preview.3 - "Bump System.Data.SqlClient from 4.5.1 to 4.6.0".

Loading the DLL from either of the PowerShell Core 6.1.1 and 6.2.0 location works!

![pscoresqlclient_2019-01-02_15-21-09](https://user-images.githubusercontent.com/19892435/50610753-1917ed00-0ea2-11e9-9838-49a2b0be24c1.jpg)

I'm curious! How and from where you install the System.Data.SqlClient.dll on your F: drive?

**Comment by brent-robinson** [comment]
@MaximoTrinidad - You're correct. My copy of `System.Data.SqlClient.dll` was from a binary PowerShell module I'd developed. My application uses the same version of `System.Data.SqlClient.dll` as PowerShell `6.2.0-preview.3`.

The left dialog is PowerShell `6.1.1`, the middle PowerShell `6.2.0-preview.3`, and the right my application.

![image](https://user-images.githubusercontent.com/6666613/51287828-7b99ed00-1a4d-11e9-90f4-a89a137ff37e.png)

**Comment by SteveL-MSFT** [comment]
This assembly is shipped with PSCore6 and that version should be used.  Older .NET Framework based ones are not compatible.
