### ISSUE TITLE
Program xxx failed to run: Cannot allocate memory

### ISSUE THREAD

**Issue by skest3qc** [PowerShell/PowerShell#6428]
Steps to reproduce
------------------
Windows 10 14393.2068
Installed Bash on Ubunutu
Installed PS Core 6.0.2
Seems to fail on aliases?
```
pwsh
PS /root> ls
Program 'ls' failed to run: Cannot allocate memoryAt line:1 char:1
+ ls
+ ~~.
At line:1 char:1
+ ls
+ ~~
+ CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
+ FullyQualifiedErrorId : NativeCommandFailed

PS /root>

PS /root> cls
Program 'clear' failed to run: Cannot allocate memoryAt line:2 char:1
+ & (Get-Command -CommandType Application clear | Select-Object -First  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:2 char:1
+ & (Get-Command -CommandType Application clear | Select-Object -First  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
+ FullyQualifiedErrorId : NativeCommandFailed
```
Environment data
----------------

PS /root> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Linux 3.4.0+ #1 PREEMPT Thu Aug 1 17:06:05 CST 2013
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```powershell
> $PSVersionTable

```

**Comment by MaximoTrinidad** [comment]
Hum! In Windows 10, check under the programs and features, See if you're using WSL Beta version.
If I can recall correctly, WSL RTM version is only on Windows 10 Build 16299 or greater.

All aliases works find with the latest version of PScore6 v6.0.2:

![pwsh_ls_2018-03-19_13-15-09](https://user-images.githubusercontent.com/19892435/37611035-a0a9c266-2b77-11e8-9c9a-a88d84dd906c.jpg)

![wsl_requirements_2018-03-19_13-17-44](https://user-images.githubusercontent.com/19892435/37611167-fe941c64-2b77-11e8-89a3-32cdd13575e8.jpg)


:)

**Comment by iSazonov** [comment]
We don't get confirmations a long time.
