### ISSUE TITLE
In what conditions does operator [] return AutomationNull?

### ISSUE THREAD

**Issue by alx9r** [PowerShell/PowerShell#6436]
Chapter 7.1.4 of the [PowerShell spec](https://www.microsoft.com/en-ca/download/details.aspx?id=36389) indicates that for arrays, strings, hashtables, and XML documents operator `[]` returns `$null` for non-existent indexes.  The spec seems to be silent for other types, however.  I expected that, for other types, operator `[]` would also return `$null` for non-existent indexes.  It seems that for some combinations of types and indexes, however, operator `[]` returns `AutomationNull`.  In what conditions does operator [] return AutomationNull?

Steps to reproduce
------------------

```powershell
&{(1)[1]} |  % {'output from indexing [int] out-of bounds'}
&{(,1)[1]} | % {'output from indexing array out-of-bounds'}
```

Expected behavior
-----------------

```none
output from indexing [int] out-of bounds
output from indexing array out-of-bounds
```

Actual behavior
---------------

```none
output from indexing array out-of-bounds
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value                                            
----                           -----                                            
PSVersion                      6.0.0                                            
PSEdition                      Core                                             
GitCommitId                    v6.0.0                                           
OS                             Microsoft Windows 6.3.9600                       
Platform                       Win32NT                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                          
PSRemotingProtocolVersion      2.3                                              
SerializationVersion           1.1.0.1                                          
WSManStackVersion              3.0                                              
```

**Comment by alx9r** [comment]
I _think_ the logic is [here](https://github.com/PowerShell/PowerShell/blob/c8ccb376b489bc17c76b94a60ce218f023c936bd/src/System.Management.Automation/engine/runtime/Binding/Binders.cs#L3888), but I only have a guess at what that code does.

**Comment by alx9r** [comment]
It looks like this is different behavior from selecting a non-existent property.  Selecting a non-existent property seems to always output `$null` not `AutomationNull`:

```PowerShell
&{(1).NonExistent}  | % {'output from selecting non-existent property on [int]'}
&{(,1).NonExistent} | % {'output from selecting non-existent property on [array]'}
```

outputs

```none
output from selecting non-existent property on [int]
output from selecting non-existent property on [array]
```

**Comment by mklement0** [comment]
Indeed, accessing a nonexistent _property_ always returns `$null`, whether applied to a scalar or a collection.

By contrast, indeed, _indexing_ a _scalar_  out of bounds returns `[System.Management.Automation.Internal.AutomationNull]::Value`, whereas indexing a _collection_ out of bounds returns `$null`, which is an interesting inconsistency (for which I have no explanation).
