### ISSUE TITLE
Make a "Powershell-release#" subdirectory in distribution tar.gz

### ISSUE THREAD

**Issue by mystica555** [PowerShell/PowerShell#6437]
Steps to reproduce
------------------

```
tar zxvf powershell-6.0.2-linux-x64.tar.gz
```

Expected behavior
-----------------

```
it creates its own new directory as a subdirectory of where i've put the tarball
```

Actual behavior
---------------

```
my downloads directory full of crap at top-level
```

**Comment by boltronics** [comment]
I too got quite a shock when I first extracted a release tarball and had it spew files everywhere in the current directory. That's a really bad first impression. What's perhaps even more shocking is that something so simple to fix has been an issue for almost three years, and yet the project doesn't seem dead based on commit history.

Please follow standard conventions and extract everything under a single directory.

This isn't the only questionable thing going on here. We've got broken symlinks also packaged (why not just create them automatically during installation?) and at a glance it looks like ~75% of the .dll files are executable, so there has bee no thought put into file permissions or presentation.

These should be very easy wins so I hope someone can look into this.
