### ISSUE TITLE
There is no way to rick-roll

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#644]
Couple things that would be nice to have

Rick-roll
http://www.nextofwindows.com/powershell-fun-watch-rick-astley-sing-and-dance-never-let-you-down

Burning console
http://www.leeholmes.com/blog/2005/12/18/burn-console-optimized-and-ready-for-marshmallows/

**Comment by iSazonov** [comment]
Rick-roll works on PowerShell Core 6.0.4 with minor (non-terminating) error at start (on $runspace.ApartmentState = "MTA" - no such property).

**Comment by vors** [comment]
Doesn't work on mac :(

For rick-roll I see no image (and background changes to white)
For the burning console, there is unimplemented API

```
Exception calling "UpdateScreen" with "1" argument(s): "The method or operation is not implemented."
At /Users/svorobev/dev/ZLocation/foo.ps1:259 char:5
+     $returnClass::UpdateScreen($inputs)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : NotImplementedException
```

**Comment by RDIL** [comment]
God please no

**Comment by Nasherx** [comment]
It kind of works on 7.0.0-rc.2, though it outputs what I believe to be all the frames of the animation first and then starts playing. Does play quite well besides the initial output though

Burning console works from what I can tell

**Comment by awsumbill** [comment]
This works on 7.0.3

**Comment by daxian-dbw** [comment]
The fix should be made to the script, given that the scripts were targeting Windows PowerShell.
If any issue is found in powershell when fixing the scripts, please open new issues specific to the issue.
