### ISSUE TITLE
Export-CliXml - issue with $PSVersionTable xml tag when importing CliXml to psobject .

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#6448]
Ok! Heard me out.  While I was playing around with PowerShell Studio to create a form to display results coming from $PSversionTable in PSCore6 psobjects exported to clixml to then import to a psobject in Windows PowerShell.  

I found out the Import-CliXml will error out in Windows PowerShell with the following message:
```
Import-Clixml : SemanticVersion XML tag is not recognized. Line 81, position 8.
At line:1 char:10
+ $psobj = Import-Clixml -Path c:\Temp\pwshobject602.xml;
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Clixml], XmlException
    + FullyQualifiedErrorId : System.Xml.XmlException,Microsoft.PowerShell.Commands.ImportClixmlCommand
```
Of course, this is not a Windows PowerShell issue as the workaround below works.

WorkAround
-----------------
Via code I had to fix the xml tag;
```
:
 $line.Replace('SemanticVersion', 'Version');
:
```
![psverxml_012018-03-21_11-17-46](https://user-images.githubusercontent.com/19892435/37719350-32476eec-2cfb-11e8-8f3a-2ec4929ec865.png)

After fixing the xml tag then my application works. This only happens with the $PSVersionTable.

![pss2018_pwshcore_win01_2018-03-21_10-53-04](https://user-images.githubusercontent.com/19892435/37719083-9a2d68f0-2cfa-11e8-9267-8b3f6ec9485e.jpg)

Steps to reproduce
------------------

```powershell
## - Execute in PSCore 6.0.2:
(Get-Variable PSVersionTable).value.GetEnumerator()| Export-Clixml -Path c:\Temp\pwshobject602.xml;

## - Execute in Windows PowerShell:
$psobj = Import-Clixml  -Path c:\Temp\pwshobject602.xml;
Import-Clixml : SemanticVersion XML tag is not recognized. Line 81, position 8.
At line:1 char:10
+ $psobj = Import-Clixml -Path c:\Temp\pwshobject602.xml;
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Clixml], XmlException
    + FullyQualifiedErrorId : System.Xml.XmlException,Microsoft.PowerShell.Commands.ImportClixmlCommand

```

Expected behavior
-----------------
To import the CliXml to a PSobject without any error.

Actual behavior
---------------
Error: "Import-Clixml : SemanticVersion XML tag is not recognized. Line 81, position 8."

Environment data
----------------

```powershell
## - PSCore6:
PS [156] > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Microsoft Windows 10.0.17127
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by MaximoTrinidad** [comment]
@markekraus, 

Hum! Interesting.  Still I don't understand the reason for not leave it with "version" instead for "semanticversion". This way it will keep it consistent with other version.

Anyway, it was just an observation, as replacing the xml tag works as a workaround.
:)

**Comment by MaximoTrinidad** [comment]
Thanks @SteveL-MSFT!

**Comment by daxian-dbw** [comment]
`SemanticVersion` also affects remoting from windows powershell to a powershell core endpoint; related issue: #1819
We should bring `SemanticVersion` to windows powershell to solve the root problem.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and although a breaking change, we recommend having `PSVersion` be of type `System.Version` and add a `PSSemanticVersion` string to have the `SemanticVersion`.  Because this is a behavioral and breaking change, @JamesWTruher will author a small RFC to cover this.
