### ISSUE TITLE
Member enumeration unwraps and flattens array-valued properties

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#6454]
Note: 
* The behavior described below has been in place since [member enumeration](https://blogs.msdn.microsoft.com/powershell/2012/06/13/new-v3-language-features/) was introduced in v3 and only affects _array-valued_ properties.
* The behavior may well be by design, but given that it can be surprising, it may need to be _documented_.

Steps to reproduce
------------------

```powershell
# Create an object whose .prop value is an array of hashtables, only one of 
# which as a .subProp entry whose value is a single-element array, then
# access .subProp via member enumeration.
$obj=[pscustomobject] @{ prop = @{foo='foo'}, @{subProp=,1}}; ($obj.prop.subProp).GetType().Name

# Create two 2-element arrays and let member enumeration collect them.
$obj=[pscustomobject] @{prop = @{subProp=1,2}, @{subProp=3,4}}; $obj.prop.subProp.Count
```

Actual behavior
---------------

```none
Int32
4
```

The single-element array was _unwrapped_.
The two 2-element arrays were _concatenated_ (rather than collected as-is in a 2-element array).

Alternative behavior
-----------------

One _could_ expect the following behavior, and contrasting it with the actual behavior is worth documenting:

```none
Object[]
2
```

The value of the properties could have been passed through, just as with _direct_ property access (e.g., `$obj.prop[-1].subProp`):

* In the first case: `, 1` may be expected, but `1` is returned.
  * Note that it's fine not to wrap `, 1` in an _outer_ array if only _one_ collection element's property value is found, because that is consistent with pipeline behavior.
* In the second case: `(1, 2), (3, 4)` may be expected, but `1, 2, 3, 4` is returned (the equivalent of `(1, 2) + (3, 4)`)

Environment data
----------------

```powershell
PowerShell Core v6.0.2 on macOS 10.13.3
PowerShell Core v6.0.2 on Ubuntu 16.04.3 LTS
PowerShell Core v6.0.2 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
Windows PowerShell v5.1.15063.674 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by BrucePay** [comment]
Per the linked document `$obj.prop.subProp` is equivalent to `$obj.prop | foreach subProp` and so the individual member collections get flattened as expected. Here is a simplified example:
```
PS[1] (67) > ( @{a=1, 2} , @{a=3, 4} ).a
1
2
3
4
```
Note that this behavior is currently documented in about_Properties. Do you think additional exposition is required?

**Comment by mklement0** [comment]
@BrucePay: 

Thanks for pointing that out. The `$obj.prop | foreach-object subProp` analogy indeed is a good explanation of the behavior (`( @{a=1, 2} , @{a=3, 4} ).a.Count` yielding `4`  rather than `2`).

I also wasn't aware that `about_Properties` already talks about member enumeration, thanks.

However, the linked page is a 6-year-old blog post, and  `about_Properties` does _not_ discuss the flattening:

> PowerShell returns the value of that property for every object in the collection.

That phrasing could easily lead one to expect the alternative behavior.

Therefore, **I suggest amending `about_Properties`**:

* by adding the `$obj.prop | foreach-object subProp` analogy to it.

* mentioning the feature's _name_:  "member enumeration", assuming that should be the official term; it always helps to have a name for a feature.
