### ISSUE TITLE
Treating scalars implicitly as collections doesn't work with all objects - some lack a .Count property, as do some objects that are implicitly treated as collections

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#6456]
#3671 discussed the issue with respect to `[pscustomobject]` instances, for which a fix was attempted in #5756 (but the fix is not in v6.0.2 - @iSazonov, should it be?).

However, there are instances of other types where the problem persists.

It would be good to clarity on the _generic_ issue, so that it can be fixed for _any_ (current and future) type.

Steps to reproduce
------------------

```powershell
([System.Data.DataTable]::new()).Count
([pscustomobject] @{}).Count
```

Expected behavior
-----------------

```none
0   # because [System.Data.DataTable] is treated as an *enumerable* - see @stknohg's comment below.
1
```

Actual behavior
---------------

The output is `$null`, because there is no `.Count` property.

Environment data
----------------

```powershell
PowerShell Core v6.0.2 on macOS 10.13.3
PowerShell Core v6.0.2 on Ubuntu 16.04.3 LTS
PowerShell Core v6.0.2 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
Windows PowerShell v5.1.15063.674 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by stknohg** [comment]
`DataTable` is defined as enumerable in PowerShell.

I think 

```powershell
([System.Data.DataTable]::new()).Count
```

should retruns `0`.

but this expression returns nothing currently...  
I think it is a bug.

----

### workaround?

```powershell
([System.Data.DataTable]::new().Rows).Count
```

returns `0` as expected.

**Comment by mklement0** [comment]
@stknohg: Thanks, good point about `[System.Data.DataTable]` being enumerable (though seemingly [not in all contexts (anymore)](https://github.com/PowerShell/PowerShell/issues/6453) - I've updated the original post.

Yes, it should  return `0` in this case (or, generally, however many rows the `.Rows` property contains) which, as you state, doesn't work.

**Comment by iSazonov** [comment]
v6.0.2 is only security update.

**Comment by iSazonov** [comment]
Is the Issue for `ForEach` and `Where` too?

**Comment by mklement0** [comment]
@iSazonov: Thanks; your `[pscustomobject]` fixes were indeed effective in all respects (`.Count`, `[0]`, `.ForEach()`, `.Where()`), I checked with the latest code. The issue with `[DataTable]` is a different one that I'll address in a new issue.
