### ISSUE TITLE
Creating PowerShell Hosts: Licensing question

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#6463]
Anyway, I was reading through [the third party license list](https://github.com/PowerShell/PowerShell/blob/master/license_thirdparty_proprietary.txt) and taking deep breaths. I suppose that every PowerShell host must now redistribute the entire license file, right? I'm not exactly looking for a lawyer's opinion -- but it seems like this should be mentioned as a reminder in any documentation created about hosting PowerShell Core, because it's a major change from hosting Windows PowerShell.

As a side note:

Someone pointed out that there's [a _lot_ of libraries listed](https://github.com/PowerShell/PowerShell/blob/master/license_thirdparty_proprietary.txt#L160-L414) as being under the 

```
MICROSOFT SOFTWARE LICENSE TERMS
MICROSOFT .NET LIBRARY
```

Which is, you know ... the old .NET license which is a bit confusing about redistribution.

I should point out that [this section](https://github.com/PowerShell/PowerShell/blob/master/license_thirdparty_proprietary.txt#L466-L474) in particular is being [decried](https://listas.trisquel.info/pipermail/trisquel-users/2017-May/077549.html) online as non-free:

```
4.      SCOPE OF LICENSE.  The software is licensed, not sold. This agreement only gives you some rights to
use the software. Microsoft reserves all other rights. Unless applicable law gives you more rights despite
this limitation, you may use the software only as expressly permitted in this agreement. In doing so, you
must comply with any technical limitations in the software that only allow you to use it in certain ways.
You may not
•          work around any technical limitations in the software;
•          reverse engineer, decompile or disassemble the software, except and only to the extent that
applicable law expressly permits, despite this limitation;
•          publish the software for others to copy;
•          rent, lease or lend the software;
•          transfer the software or this agreement to any third party; or
• use the software for commercial software hosting services.
```

**Comment by BrucePay** [comment]
Hi @Jaykul - I'm trying to get some clarification for you. BTW - is this related to the Jupyter stuff you're working on?

**Comment by Jaykul** [comment]
Yes @BrucePay 

I'm obviously not personally too bother about the .Net SDK license -- but someone mentioned that post online, and when I looked at the license list, it dawned on me that I really probably need to include all that text in my project too -- and it made me wonder what redistribution rights I even have. 

The whole thing gets complicated. In addition to NuGet packages, currently there are modules and assemblies I have to outright _copy from PowerShell's deployment package_ (i.e. not just the SDK from NuGet).

This whole thing (plus the monthly bugfix release) has made me a bit nervous about the maintenance. I don't suppose you guys want a PR to just add the jupyter kernel to the core? ;-)

**Comment by Jaykul** [comment]
Any word on this @BrucePay?

I'm creating a release for the Jupyter-Kernel, and I basically need to re-ship **everything** in the PowerShell package for the OS. The Chocolatey validator automatically failed me because I don't have a license file. 

After double-checking, it turns out the same is true of PowerShell releases: there's _no license file in the PowerShell release **except**_ the `license_thirdparty_proprietary.txt`

Y'all need to sort this out. 😕 Currently we have one license file and two (or three) third party license files -- but only one of the third party license files ships in the product (even the main license file doesn't).

- https://github.com/PowerShell/PowerShell/blob/master/LICENSE.txt
- https://github.com/PowerShell/PowerShell/blob/master/ThirdPartyNotices.txt
- https://github.com/PowerShell/PowerShell/blob/master/license_thirdparty_proprietary.txt
- https://github.com/PowerShell/PowerShell/blob/master/assets/AppImageThirdPartyNotices.txt

To make matters worse, there are also source code files with **Apache** License in them. Here are just a few (note these aren't just examples or tests):
- [/src/System.Management.Automation/engine/interpreter/ILightCallSiteBinder.cs](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/interpreter/ILightCallSiteBinder.cs)
- [/src/System.Management.Automation/engine/interpreter/RuntimeVariables.cs](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/interpreter/RuntimeVariables.cs)
- [/test/powershell/Modules/PackageManagement/PackageManagement.Tests.ps1](https://github.com/PowerShell/PowerShell/blob/master/test/powershell/Modules/PackageManagement/PackageManagement.Tests.ps1)
- [/src/System.Management.Automation/engine/interpreter/PowerShellInstructions.cs](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/interpreter/PowerShellInstructions.cs)
- [/src/System.Management.Automation/engine/interpreter/DynamicSplatInstruction.cs](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/interpreter/DynamicSplatInstruction.cs)

**Comment by SteveL-MSFT** [comment]
cc @TravisEz13

**Comment by Jaykul** [comment]
Ping

**Comment by Jaykul** [comment]
If you don't think this license situation blocks shipping PowerShell -- _at all_, _by anyone_, including you -- I'd like to know why...

**Comment by TravisEz13** [comment]
I have done an initial review of this issue with our legal team. 
The two Third Party Notices can be combined.  These are notices about other licenses that apply.

- https://github.com/PowerShell/PowerShell/blob/master/ThirdPartyNotices.txt
- https://github.com/PowerShell/PowerShell/blob/master/license_thirdparty_proprietary.txt

The following file is the license for the PowerShell Core project/product itself and I was advised to keep it separate to keep that clear ([This is a recognized best practice](https://softwareengineering.stackexchange.com/a/234526)).

- https://github.com/PowerShell/PowerShell/blob/master/LICENSE.txt 

The DotNet License is the current license on the package(s) we consume.  For example, click `License Info` on [Microsoft.CodeAnalysis.CSharp](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp/).  I'm following up directly with the team, but feel free to [open an issue with the team](https://github.com/dotnet/roslyn/issues/new)

The Apache licence header files were copied from other Microsoft Sponsored projects with Apache Licenses.  Attribution should be added for clarity.

This Third Party Notice only applies to AppImage Packages and we believe it should remain seperate (we currently have issues generating AppImages):
- https://github.com/PowerShell/PowerShell/blob/master/assets/AppImageThirdPartyNotices.txt

**Comment by TravisEz13** [comment]
@Jaykul 	I removed the offending terms in PR https://github.com/PowerShell/PowerShell/pull/8415.  There are discussions that we may be able to simplify further.  Please tell us if you have any additional concerns.

**Comment by TravisEz13** [comment]
Well updated is a better term that removed.  DotNet updated their license.
