### ISSUE TITLE
Release 6.1.0-preview.1

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#6465]
From:  https://github.com/PowerShell/PowerShell/blob/master/docs/maintainers/releasing.md

- [x] Create a private branch named `6.1.0-preview.1` in private repository.
   All release related changes should happen in this branch.
- [x] Run tests on all supported Linux distros and publish results
- [x] Prepare packages
   - [x]  Build release packages
   - [x]  Sign the MSI packages and RPM package.
   - [x]  Install and verify the packages.
- [x]  Update documentation, scripts and Dockerfiles
   - [x]  Update [CHANGELOG.md](../../CHANGELOG.md) with the finalized change log draft.
   - [x]  Update other documents and scripts to use the new package names and links.
- [ ]  Verify the release Dockerfiles.
- [x]  Create NuGet packages and publish them to `powershell-core` feed.
- [x]  Publish Linux packages to Microsoft YUM/APT repositories.
- [x]  Create the release tag and push the tag to `PowerShell/PowerShell` repository.
- [x]  Create the draft and publish the release in Github.
- [x]  Merge the `release` branch to `master` and delete the `release` branch.
- [ ]  Trigger the release docker builds for Linux and Windows container images.
   - [ ]  Linux: push a branch named `docker` to `powershell/powershell` repository to trigger the build at [powershell docker hub](https://hub.docker.com/r/microsoft/powershell/builds/).
     Delete the `docker` branch once the builds succeed.
   - [ ]  Windows: queue a new build in `PowerShell Windows Docker Build` on VSTS.
- [ ]  Verify the generated docker container images.

**Comment by TravisEz13** [comment]
@adityapatwardhan is everything done?
