### ISSUE TITLE
Timeline for Microsoft.PowerShell.SDK being in nuget.org

### ISSUE THREAD

**Issue by normj** [PowerShell/PowerShell#6475]
Is there a rough timeline when Microsoft.PowerShell.SDK and it's dependencies will be GA and pushed to nuget.org?

**Comment by SteveL-MSFT** [comment]
Can you be more specific what you mean by SDK?  We recommend developers use https://www.nuget.org/packages/PowerShellStandard.Library for modules or https://powershell.myget.org/feed/powershell-core/package/nuget/System.Management.Automation for hosted scenarios.

**Comment by normj** [comment]
Currently Microsoft.PowerShell.SDK is only on the PowerShell team's myget feed not NuGet.org. This package is what allows us to host a PowerShell environment in a .NET Core application on Linux.

**Comment by jherby2k** [comment]
I was wondering the same thing. SteveL, that package is for hosting under full framework not a netcore project.

**Comment by SteveL-MSFT** [comment]
Got it.  Thanks.

cc @adityapatwardhan

**Comment by adityapatwardhan** [comment]
We would evaluate releasing on Nuget.org during the next servicing release.

**Comment by adityapatwardhan** [comment]
@normj I am actively working on this and this should be out in a few days.

**Comment by Mattacks** [comment]
@adityapatwardhan 
Hi.
Any ETA on the for-.Net-core-package being properly published in NuGet? We (especially our legal departments) don't like referencing alternative NuGet repositories.
Matt

**Comment by kentcb** [comment]
Came here looking for the same thing, mainly because I can't seem to consume from MyGet anymore:

```
PM> Install-Package Microsoft.PowerShell.SDK -Version 6.0.2 -Source https://powershell.myget.org/F/powershell-core/api/v3/index.json
The 'Source' parameter is not respected for the transitive package management based project(s) Redacted.PowerShell. The enabled sources in your NuGet configuration will be used. 
Restoring packages for C:\Users\Kent\Repository\Redacted\Src\Redacted.PowerShell\Redacted.PowerShell.csproj...
  GET https://powershell.myget.org/F/powershell-core/FindPackagesById()?id='Microsoft.NETCore'&semVerLevel=2.0.0
  GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore/index.json
  GET https://powershell.myget.org/F/powershell-core/FindPackagesById()?id='Microsoft.NETCore.Portable.Compatibility'&semVerLevel=2.0.0
  GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.portable.compatibility/index.json
  GET https://powershell.myget.org/F/powershell-core/FindPackagesById()?id='Microsoft.PowerShell.SDK'&semVerLevel=2.0.0
  GET https://api.nuget.org/v3-flatcontainer/microsoft.powershell.sdk/index.json
  OK https://api.nuget.org/v3-flatcontainer/microsoft.netcore.portable.compatibility/index.json 948ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.netcore/index.json 985ms
  OK https://powershell.myget.org/F/powershell-core/FindPackagesById()?id='Microsoft.NETCore.Portable.Compatibility'&semVerLevel=2.0.0 1055ms
  OK https://powershell.myget.org/F/powershell-core/FindPackagesById()?id='Microsoft.NETCore'&semVerLevel=2.0.0 1090ms
  OK https://powershell.myget.org/F/powershell-core/FindPackagesById()?id='Microsoft.PowerShell.SDK'&semVerLevel=2.0.0 1186ms
  GET https://powershell.myget.org/F/powershell-core/api/v2/package/Microsoft.PowerShell.SDK/6.0.2
  NotFound https://api.nuget.org/v3-flatcontainer/microsoft.powershell.sdk/index.json 1694ms
  OK https://powershell.myget.org/F/powershell-core/api/v2/package/Microsoft.PowerShell.SDK/6.0.2 1273ms
Installing Microsoft.PowerShell.SDK 6.0.2.
Install-Package : NU1102: Unable to find package Microsoft.NETCore.Portable.Compatibility with version (>= 
1.0.3-beta-24514-00)
  - Found 9 version(s) in nuget.org [ Nearest version: 1.0.2 ]
  - Found 2 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 1.0.1 ]
  - Found 0 version(s) in PowerShell
At line:1 char:1
+ Install-Package Microsoft.PowerShell.SDK -Version 6.0.2 -Source https ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'Redacted.PowerShell'.
At line:1 char:1
+ Install-Package Microsoft.PowerShell.SDK -Version 6.0.2 -Source https ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

Worse, MyGet has seemingly screwed up my account - I can no longer login with credentials that worked a month or so ago (and are stored in LastPass, so I definitely haven't forgotten them). To top it off, their password reset function isn't working.

Really looking forward to this being available without the pain...

**Comment by kentcb** [comment]
@adityapatwardhan it's the end of June, so just pinging to get an update on where things are at.

**Comment by fulghum** [comment]
@adityapatwardhan – any update on when Microsoft.PowerShell.SDK will be available for us to consume from NuGet.org?

**Comment by MaximoTrinidad** [comment]
Yeah! I can't seems to be able to download Preview.3 using any of the command lines provided.
Only the Ga 6.0.2 can be downloaded.

:(

**Comment by khansen00** [comment]
Appreciate you're working on it and apparently there were unexpected complications.
Do we have some estimate? It is preventing us from shipping now, so it would be great to have some good idea of when it will be available.

**Comment by adityapatwardhan** [comment]
Thank you for your patience. An estimate for packages to be release on Nuget will be end of next week.

**Comment by adityapatwardhan** [comment]
Quick update. We are testing the packages and would be publishing them to NuGet.org in a few days.

**Comment by normj** [comment]
Awesome!

**Comment by adityapatwardhan** [comment]
@normj @khansen00 @MaximoTrinidad @kentcb @Mattacks @jherby2k 

`Microsoft.PowerShell.SDK` and related packages were released on [NuGet.org](https://www.nuget.org/packages/Microsoft.PowerShell.SDK) today morning for PowerShell Core version 6.0.4. 

Please give them a try and re-open the issue if you see any problems.

**Comment by normj** [comment]
Great news, thanks for getting this out.

**Comment by normj** [comment]
In case you guys were curious, at AWS today we released PowerShell Core support for AWS Lambda, our serverless offering. It's based on this NuGet package which was why I was pushing for this release. Thanks for pushing to get this released.

https://aws.amazon.com/blogs/developer/announcing-lambda-support-for-powershell-core/

**Comment by SteveL-MSFT** [comment]
@normj congrats on supporting PSCore6 in AWS Lambda!
