### ISSUE TITLE
Exception when importing  custom modules in c# using powershell sdk

### ISSUE THREAD

**Issue by alokkms** [PowerShell/PowerShell#6476]
Steps to reproduce
------------------

```c#
var absmodule = Path.GetFullPath(@".\PSModules\ABSModule.psd1");
var state = InitialSessionState.CreateDefault(); 
state.ImportPSModule(new [] {
    absmodule
});

PowerShell ps = PowerShell.Create(state);
ps.Streams.Error.DataAdded += (object sender, DataAddedEventArgs e) => ScriptErrorAdded(ps, sender, e);
var results = ps.AddCommand("Test-Ping").AddArgument("Hello World").Invoke();
```
This works as expected when we run "dotnet run" in the project, but throws the following exception when we run the app from the published version when we publish as "dotnet publish -c Release -r win10-x64"

Unhandled Exception: System.Management.Automation.CmdletInvocationException: E:\PwshTest\bin\Release\netcoreapp2.0\win10-x64\publish\Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psm1 ---> System.IO.FileNotFoundException: E:\PwshTest\bin\Release\netcoreapp2.0\win10-x64\publish\Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psm1
   at System.Management.Automation.SignatureHelper.GetSignatureFromCatalog(String filename)   at System.Management.Automation.SignatureHelper.GetSignatureFromCatalog(String filename)
   at System.Management.Automation.SignatureHelper.GetSignature(String fileName, String fileContent)
   at System.Management.Automation.Internal.SecuritySupport.IsProductBinary(String file)   at System.Management.Automation.CompiledScriptBlockData.ReallyCompile(Boolean optimize)
   at System.Management.Automation.CompiledScriptBlockData.CompileOptimized()   at System.Management.Automation.CompiledScriptBlockData.Compile(Boolean optimized)
   at System.Management.Automation.ScriptBlock.GetCodeToInvoke(Boolean& optimized, ScriptBlockClauseToInvoke clauseToInvoke)
.
.
.

The sample project is available here: 
[PwshTest.zip](https://github.com/PowerShell/PowerShell/files/1843066/PwshTest.zip)

Note: I also tried with using "Import-Module" command, but that fails to load the module as well. The sample project has both test scenarios.

Environment data
----------------

.Net core 2.0
"Microsoft.PowerShell.SDK" Version="6.0.2"

**Comment by daxian-dbw** [comment]
@adityapatwardhan Could you please take a look?

**Comment by iSazonov** [comment]
@SteveL-MSFT What should we do with such issues?

**Comment by alokkms** [comment]
@SteveL-MSFT I tried with .netcore 2.1 and ps sdk 6.1.0, but i still see the same error
```
Unhandled Exception: System.Management.Automation.CmdletInvocationException: E:\Users\alokk\Downloads\PwshTest\Test2\bin\Release\netcoreapp2.1\win10-x64\publish\Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psm1 ---> System.IO.FileNotFoundException: E
:\Users\alokk\Downloads\PwshTest\Test2\bin\Release\netcoreapp2.1\win10-x64\publish\Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psm1
   at System.Management.Automation.SignatureHelper.GetSignatureFromCatalog(String filename)
   at System.Management.Automation.SignatureHelper.GetSignatureFromCatalog(String filename)
   at System.Management.Automation.SignatureHelper.GetSignature(String fileName, String fileContent)
   at System.Management.Automation.Internal.SecuritySupport.IsProductBinary(String file)
   at System.Management.Automation.CompiledScriptBlockData.ReallyCompile(Boolean optimize)
   at System.Management.Automation.CompiledScriptBlockData.CompileOptimized()
```

**Comment by iSazonov** [comment]
@alokkms Could you please show your PATH env variable?

**Comment by alokkms** [comment]
> @alokkms Could you please show your PATH env variable?

C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\wbin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\nodejs\;C:\Program Files\dotnet\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Windows Kits\10\Microsoft Application Virtualization\Sequencer\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files\Docker;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\alokk.REDMOND\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\alokk.REDMOND\AppData\Local\Programs\Python\Python36\;C:\Users\alokk.REDMOND\AppData\Local\Microsoft\WindowsApps;C:\Users\alokk.REDMOND\AppData\Roaming\npm;C:\texlive\2017\bin\win32;C:\Program Files (x86)\Git\cmd;C:\Python27;C:\Python27\Scripts;C:\Users\alokk.REDMOND\AppData\Local\Programs\Fiddler;C:\Program Files (x86)\Java\jdk1.8.0_131\bin;C:\Users\alokk.REDMOND\.dotnet\tools

**Comment by vexx32** [comment]
Above text `-split ';'` for readability:
```
C:\Program Files (x86)\Common Files\Oracle\Java\javapath
C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\wbin
C:\windows\system32
C:\windows
C:\windows\System32\Wbem
C:\windows\System32\WindowsPowerShell\v1.0
C:\Program Files\Microsoft SQL Server\120\Tools\Binn
C:\Program Files\Microsoft SQL Server\130\Tools\Binn
C:\Program Files\Microsoft\Web Platform Installer
C:\Program Files\nodejs
C:\Program Files\dotnet
C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit
C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit
C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn
C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn
C:\Program Files (x86)\Windows Kits\10\Microsoft Application Virtualization\Sequencer
C:\ProgramData\chocolatey\bin
C:\Program Files\Git\cmd
C:\Program Files\MiKTeX 2.9\miktex\bin\x64
C:\Program Files\Docker
C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code
C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager
C:\Program Files (x86)\GtkSharp\2.12\bin
C:\Program Files (x86)\Microsoft Emulator Manager\1.0
C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn
C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn
C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn
C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio
C:\Program Files (x86)\Microsoft VS Code\bin
C:\Users\alokk.REDMOND\AppData\Local\Programs\Python\Python36\Scripts
C:\Users\alokk.REDMOND\AppData\Local\Programs\Python\Python36
C:\Users\alokk.REDMOND\AppData\Local\Microsoft\WindowsApps
C:\Users\alokk.REDMOND\AppData\Roaming\npm
C:\texlive\2017\bin\win32
C:\Program Files (x86)\Git\cmd
C:\Python27
C:\Python27\Scripts
C:\Users\alokk.REDMOND\AppData\Local\Programs\Fiddler
C:\Program Files (x86)\Java\jdk1.8.0_131\bin
C:\Users\alokk.REDMOND.dotnet\tools
```

**Comment by adityapatwardhan** [comment]
@alokkms Can you try with: `dotnet publish -c Release --framework netcoreapp2.1 --runtime win7-x64`

Please note the framework change from `2.0` -> `2.1`

**Comment by alokkms** [comment]
Hi @adityapatwardhan I did try with framework netcoreapp2.1 (i also updated the project file to use netcoreapp2.1), and updated the sdk to 6.1.0, but still see the same error

**Comment by iSazonov** [comment]
@alokkms  Can you confirm that the path exists `E:\PwshTest\bin\Release\netcoreapp2.0\win10-x64\publish\Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psm1`?

**Comment by alokkms** [comment]
The path does not exist. The above folder (E:\PwshTest\bin\Release\netcoreapp2.0\win10-x64\publish\) is generated by dotnet publish, and it does not contain Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psm1.

**Comment by adityapatwardhan** [comment]
@alokkms I made some changes and compiled the project files you attached, and it seems to work.
The change I made: 
1. Can the csproj file to use netcoreapp2.1, and win7-x64.
2. Change the SDK version to 6.1.0

The output I got:

```
PS D:\temp\PwshTest\PwshTest> dotnet restore
  Restoring packages for D:\temp\PwshTest\PwshTest\PwshTest.csproj...
  Generating MSBuild file D:\temp\PwshTest\PwshTest\obj\PwshTest.csproj.nuget.g.props.
  Generating MSBuild file D:\temp\PwshTest\PwshTest\obj\PwshTest.csproj.nuget.g.targets.
  Restore completed in 1.28 sec for D:\temp\PwshTest\PwshTest\PwshTest.csproj.

PS D:\temp\PwshTest\PwshTest> dotnet publish -c Release -r win10-x64
Microsoft (R) Build Engine version 15.8.166+gd4e8d81a88 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for D:\temp\PwshTest\PwshTest\PwshTest.csproj...
  Generating MSBuild file D:\temp\PwshTest\PwshTest\obj\PwshTest.csproj.nuget.g.props.
  Generating MSBuild file D:\temp\PwshTest\PwshTest\obj\PwshTest.csproj.nuget.g.targets.
  Restore completed in 881.2 ms for D:\temp\PwshTest\PwshTest\PwshTest.csproj.
  PwshTest -> D:\temp\PwshTest\PwshTest\bin\Release\netcoreapp2.1\win10-x64\PwshTest.dll
  PwshTest -> D:\temp\PwshTest\PwshTest\bin\Release\netcoreapp2.1\win10-x64\publish\

PS D:\temp\PwshTest\PwshTest> D:\temp\PwshTest\PwshTest\bin\Release\netcoreapp2.1\win10-x64\publish\PwshTest.exe
Hello World

```
I have attached my modified project. Please give it a try.
[PwshTest.zip](https://github.com/PowerShell/PowerShell/files/2443119/PwshTest.zip)
