### ISSUE TITLE
Splatting not identical

### ISSUE THREAD

**Issue by kasper3** [PowerShell/PowerShell#6477]
a.ps1:

```ps
echo "`n`nHello from a`n`n"
echo @args
&".\b.ps1" @args
```

b.ps1

```ps
echo "`n`nHello from b`n`n"
echo @args
```

From command line:

```ps
.\a.ps1 -x 1 -y:@{z='1'}
```

Output:

```ps


Hello from a


-x
1
-y:

Name                           Value
----                           -----
z                              1


Hello from b


-x
1
-y:
z                              1


```

The output of `b` is not same as output of `a` (object header is missing). Is this a bug?

**Comment by SteveL-MSFT** [comment]
I believe you're seeing an instance of https://github.com/PowerShell/PowerShell/issues/2228

If you change b.ps1 to

> echo @args | ft

You'll see the header.  Because the object type is the same as the first one (hashtable), the table formatter doesn't output the header again.
