### ISSUE TITLE
Download links for non-windows packages are broken for v6.1.0-preview.1

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#6485]
GitHub does not allow ~ to be present in the release asset name. The README was updated with filenames having ~ for all non-Windows packages. The links need to be fixed.

Steps to reproduce
------------------

```powershell

```

Expected behavior
-----------------

```none

```

Actual behavior
---------------

```none

```

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by iSazonov** [comment]
Related #5846

**Comment by adityapatwardhan** [comment]
This has been fixed for latest releases. Closing this. Please re-open if any issues are seen.
