### ISSUE TITLE
Update the package generation logic to replace ~ with - for non-windows packages

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#6486]
GitHub does not allow uploading asset names with ~ in file name. We need to update the package generation scripts to have - instead of ~.

Steps to reproduce
------------------

```powershell

```

Expected behavior
-----------------

```none

```

Actual behavior
---------------

```none

```

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by iSazonov** [comment]
Related #5846

**Comment by iSazonov** [comment]
Based on Related #5846 maybe we'll upload zipped files?

**Comment by TravisEz13** [comment]
@iSazonov  you can change the filename.  The repository will still use the name used to generate the file.
