### ISSUE TITLE
Switch with coloned value parsed differently when invoking with pass thru args

### ISSUE THREAD

**Issue by kasper3** [PowerShell/PowerShell#6492]
### Setup

a.ps1

```ps1
&".\b.ps1" @args
```

b.ps1

```ps1
Param
(
    [Switch]
    $p1,
    [Switch]
    $p2,
    [String]
    $p3,
    [int]
    $p4
)

echo "p1: $p1"
echo "p2: $p2"
echo "p3: $p3"
echo "p4: $p4"
```

### Execution

👍  Invoke b.ps1 directly:

```ps1
.\b.ps1 -p1:$true -p2:$true

p1: True
p2: True
p3:
p4: 0
```

👎 Invoke through a.ps1:

```ps1
.\a.ps1 -p1:$true -p2:$true

p1: True
p2: True
p3: True
p4: 1
```

👍 Invoke through a.ps1 removing `:$true`:

```ps1
.\b.ps1 -p1 -p2

p1: True
p2: True
p3:
p4: 0
```

@SteveL-MSFT, this is our production code and i have reduced and anonymize it to demonstrate the problem. External party (Visual Studio in our case) calls `a.ps1` with `-p1:$true`, so we don't control that part. The only viable solution is to move code from b.ps1 to a.ps1. In our case, that means a lots of duplicate code.

is this a bug with PowerShell argument parsing, splatting or parameter binding? Please share if there is a workaround that can be made in a.ps1 or b.ps2 without raising our expectation from the caller.

**Comment by mklement0** [comment]
@kasper3: I think this is a duplicate of #6360 and part of larger discussion about parameter parsing (#6467).

**Comment by kasper3** [comment]
@mklement0, thanks for pointing out. Well, in my defense i searched something before opening the issue but apparently with wrong keywords Will close this one too then. 😢 

I was thinking about parsing `@args` in a.ps1 and pass each argument separately to b.ps1. Do you know of any better workaround?

**Comment by mklement0** [comment]
@kasper3: 

The workaround is to define the same `param()` block in `a.ps1` and then pass `@PSBoundParameters` through instead of `@args`.

Of course, if you need to support unknown-in-advance parameters to pass through, that won't work.
