### ISSUE TITLE
Get-Help -Path doesn't select provider-specific help

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#6495]
See also: #6494, which suggests simplify the mechanism for obtaining provider-specific help.

Steps to reproduce (run on Windows, with help files installed)
------------------

```powershell
# Try to obtain the filesystem-specific Get-Item help topic by passing a filesystem-provider
# path to -Path:
(Get-Help Get-Item -Path C:\).Synopsis
```

Expected behavior
-----------------

```none
Gets files and folders.
```

The above is the synopsis of the filesystem-provider-specific `Get-Item` help topic, as expected.

Actual behavior:
---------------

```none
Gets the item at the specified location.
```

That is, the abstract, provider-independent help was returned.
It seems that the `-Path` argument is ignored altogether.

Note that _Windows PowerShell_  is _not_ affected by this bug.

A quirk that _is_ in Windows PowerShell may resurface when this is fixed for Core, and is it worth fixing too:

Specifying a _nonexistent_ path is quietly ignored.
(As stated, Core currently ignores _any_ path.)

Environment data
----------------

```powershell
PowerShell Core v6.0.2 on macOS 10.13.3
PowerShell Core v6.0.2 on Ubuntu 16.04.3 LTS
PowerShell Core v6.0.2 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by adityapatwardhan** [comment]
Currently the help content published for PS 6.x does not have provider specific help. We hope to address this issue sometime in future.

**Comment by adityapatwardhan** [comment]
`-Path` being ignored definitely seems like a bug. Please file a separate issue for it.

**Comment by mklement0** [comment]
@adityapatwardhan: Sounds good - please see #6611.
