### ISSUE TITLE
Ubuntu: Software updater and apt-get update to 6.1.0-preview despite pre-release option being not ticked

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#6496]
Steps to reproduce
------------------

Run the Ubuntu Software updater GUI or `sudo apt-get update; sudo apt-get upgrade`

Expected behavior
-----------------

When `pre-releases` are not ticked then the updater should not suggest an upgrade to preview versions.

Actual behavior
---------------

It suggest and update to the new preview version despite the pre-release option being not ticked in the settings.

![image](https://user-images.githubusercontent.com/9250262/37878023-c3aafb3a-305a-11e8-9f02-c77c4a7dcc5b.png)

The same is true for `apt-get`

Environment data
----------------

```powershell
> $PSVersionTable                                                                                

Name                           Value                                                                          
----                           -----                                                                          
PSVersion                      6.0.2                                                                          
PSEdition                      Core                                                                           
GitCommitId                    v6.0.2                                                                         
OS                             Linux 4.13.0-37-generic #42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018     
Platform                       Unix                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                        
PSRemotingProtocolVersion      2.3                                                                            
SerializationVersion           1.1.0.1                                                                        
WSManStackVersion              3.0                                                                            
```

**Comment by iSazonov** [comment]
Related #6486

**Comment by MaximoTrinidad** [comment]
Hum! I was able to upgrade to pwsh 6.1.0-preview doing both the "sudo apt update" and "sudo apt upgrade". But not sure about the updater.

This was on Ubuntu 17.10.

**Comment by TravisEz13** [comment]
I think normally prerelease is separated into different repros.  @joeyaiello PowerShell/Powershell-RFC#115 should probably address this as well.

**Comment by DarwinJS** [comment]
Related: #6815

**Comment by bergmeister** [comment]
@SteveL-MSFT Has this been fixed by now or will we hit this issue again once the first preview of 6.2 comes out?

**Comment by iSazonov** [comment]
Yes, now prerelease is distributed through different channel.

**Comment by bergmeister** [comment]
Ok, I will close then for now
