### ISSUE TITLE
GA build is taking too much time in returning response from Invoke-Command cmdlets

### ISSUE THREAD

**Issue by namangoel19** [PowerShell/PowerShell#6500]
I tried with GA build on Cent OS 7.3.

from there I am running invoke-command and calling some powershell on windows, first time it is working fine and it is returning response in 10 sec but after that the invoke-command is taking too much time.

Any body is facing the same issue?

**Comment by iSazonov** [comment]
@namangoel19 Could you please test with latest build?

**Comment by daxian-dbw** [comment]
@dantraMSFT might have some insights.

**Comment by krishnakumargupta** [comment]
Hi, I am also facing the same problem where GA builds (from RC) is taking much time compare to beta build.

Till beta 6.0.0_beta.9-1 build the responses were very fast from from windows to linux and vice versa but after RC and till latest build of power shell, It taking much time to connect to the system.
in terms of data, where Beta was taking 6-10 sec to connect to system, the latest build is taking 1-2 minutes to connect the system.

from beta to RC. i am not seeing much about remoting commit apart from inclusion of psrp packages. 
P.S: Separate Install-PowerShellRemoting.ps1 from psrp.windows nuget package.

Can anybody help me to understand more about the issue like why GA is taking time.

**Comment by iSazonov** [comment]
@PaulHigin Could you please comment the remoting performance issue?

@namangoel19 @krishnakumargupta Could you please add more repo steps?

**Comment by krishnakumargupta** [comment]
@iSazonov Please find the below step to repo the issue.
on the centOS7.3 box run the below steps to install powershell, OMI and gssntlm.

curl https://packages.microsoft.com/config/rhel/7/prod.repo > /etc/yum.repos.d/microsoft.repo
yum install -y powershell or yum install https://github.com/PowerShell/PowerShell/releases/download/v6.0.2/powershell-6.0.2-1.rhel.7.x86_64.rpm

yum install omi

sudo rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
yum install gssntlmssp

Open pwsh session by typing pwsh.

run below command to connect to windows system.

invoke-command -computername IP -credential domain\user -authentication Negotiate -scriptblock {$pwd}

try to run the same command on same powershell open window.


In this case, powershell is taking time to connect the windows system but if we uses any beta version of powershell then invoke command is taking less time.

**Comment by PaulHigin** [comment]
This is using the OMI bridge to do PowerShell WinRM based remoting, something that I am not familiar with, but @dantraMSFT  should be able to help.
