### ISSUE TITLE
Get-Process Should have a  Property "commandline"

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#6507]
Get-Process Should have a  Property "commandline"

Expected behavior
-----------------

linux:
(Get-Process xxx).commandline   can return Process's commandline ,not need "ps -ef |grep xxx"

windows:
(get-wmiobject -query "select * from win32_process").commandline
Not intuitive

**Comment by KevinMarquette** [comment]
related to #3322

**Comment by mklement0** [comment]
@KevinMarquette: Good find; I'd say it's a duplicate.
