### ISSUE TITLE
Support property paths in cmdlets that accept property names (nested member access)

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#6509]
_Update_: @kvprasoon  suggests more generally to **support property _paths_ in cmdlets that accept property _names_**, typically via parameter `-Property`, such as `Select-Object` and  `Compare-Object`.

PSv3 introduced two simplified syntax forms that, in simple scenarios, allow use of _parameters_ (i.e., argument mode) rather than _script blocks_ for a cleaner, less "noisy" experience:

_Operation statements_ for `ForEach-Object`:

```powershell
# Equivalent to: ... | ForEach-Object { $_.one }
[pscustomobject] @{ one = 1 } | ForEach-Object one  # -> 1

# Equivalent to: 1 | ForEach-Object { $_.Equals(1) }
1 | ForEach-Object Equals 1    # -> $True
```

_Comparison statements_ for `Where-Object`:

```powershell
# Equivalent to: ... | Where-Object { $_.one -eq 1 }
[pscustomobject] @{ one = 1 } | Where-Object one -eq 1
```

However, the simplified syntax does'nt work for _nested_ member access, e.g., for accessing `one.two` in `[pscustomobject] @{ one = [pscustomobject] @{ two = 2 } }` - see below.

Note that, by contrast, analogous nested access _does_ work in general in "naked" expression-based arguments:

```powershell
$obj = [pscustomobject] @{ one = [pscustomobject] @{ two = 2 } }
Write-Output $obj.one.two  # correctly yields 2
```

Therefore, nested instance-member access - both properties and methods - should be supported.

Steps to reproduce
------------------

```powershell
$obj = [pscustomobject] @{ one = [pscustomobject] @{ two = 2 } }

$obj | ForEach-Object one.two
'---'
$obj | Where-Object one.two -eq 2
```

Expected behavior
-----------------

```none
1
---

one     
---     
@{two=2}
```

Actual behavior
---------------

```none
---
```

That is, the nested member access results in `$null` output.

Environment data
----------------

```powershell
PowerShell Core v6.0.2 on macOS 10.13.3
PowerShell Core v6.0.2 on Ubuntu 16.04.3 LTS
PowerShell Core v6.0.2 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
Windows PowerShell v5.1.15063.674 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by BrucePay** [comment]
@mklement0 Just out of curiosity, how do you see multiple levels of method calls working? Methods can take arguments which works for one level as in your example:
```
1 | ForEach-Object Equals 1 
```
by taking a single argument list. How would things work when you have more than one method taking arguments (multiple argument lists)?

> analogous nested access does work in general in "naked" expression-based arguments:

Please be careful about mixing up language elements and command parameter behaviours. In the following:
```
PS[1] (220) > $m = "y"
PS[1] (221) > @{m=1; y=2} | foreach m
1
PS[1] (222) > @{m=1; y=2} | foreach $m
2
```
are the arguments `m` and `$m` mean very different things. (I worry about confusing the user when we have multiple features that appear similar but are very different e.g. the foreach statement and the foreach cmdlet.)

**Comment by mklement0** [comment]
@BrucePay:

> Please be careful about mixing up language elements and command parameter behaviours. In the following:

Completely agreed: It's why I said _analogous_, not _equivalent_, and referred to _expression-based_ arguments.

The features _are_ different, but they also have something in common, and exhibiting _analogous_ behavior is useful in the case at hand (and, conversely, not exhibiting analogous behavior is surprising).

What they have in common is that what is normally used in _expression_ mode is being used in _argument_ mode - whether the object being operated on is _implied_ (in the operation statement's `-MemberName` argument) or is _explicitly specified_ (general, expression-based argument).

It's reasonable - and lends itself to knowledge transfer - to expect both scenarios to support the same kind of member access, their differences notwithstanding.

**Comment by mklement0** [comment]
@BrucePay:

The above analogy may also provide a solution to your other question:

> How would things work when you have more than one method taking arguments (multiple argument lists)?

Using an expression-based argument requires you to use _method syntax_ to call methods:

```powershell
Write-Output $host.ToString().ToUpper('fr-FR')
```

Analogously, we could require the same in comparison / operation statements for _nested_ method calls:

```powershell
$Host | ForEach-Object ToString().ToUpper('fr-FR')
```

For _non-nested_ method calls, the existing syntax could remain in place: No trailing `()`, with the arguments, if any, passed in _argument_ mode (though, frankly, I was surprised that `ForEach-Object Equals 1` works): 

```powershell
# Single-argument method:
# Same as: 1 | ForEach-Object { $_.Equals(1) }
1 | ForEach-Object Equals 1  # -> $True

# Multi-argument / array-valued single-arguments methods
# Same as: 'bar' | ForEach-Object { $_.Trim('r', 'a')
'bar' | % Trim 'r', 'a'  # -> 'b'
```

In fact, using method syntax _accidentally_ already works when at least 1 argument is passed; without arguments, however, it breaks:

```powershell
# Works: Same as: 'bar' | % Trim 'r', 'a'
'bar' | ForEach-Object Trim('r', 'a')

# !! BREAKS: trailing `()` not recognized.
'bar' | ForEach-Object Trim()
```

Note that you can currently already _get away_ with method syntax if there's _at least one argument_, because the parser ultimately sees `Trim 'r', 'a'` and `Trim('r', 'a')` as the same.
(For the same reason, people get away with fake method syntax in widely used calls such as `New-Object foo('a', 2)`).

---

Generally, though, _property_ access rather than method calling strikes me as the far more common use case.

**Comment by BrucePay** [comment]
@mklement0 Hmmm - parens are syntactically significant in argument mode so
```
$Host | ForEach-Object ToString().ToUpper('fr-FR')
```
is a syntax error. An open paren  introduces a new argument expression:
```
PS[1] (25) > write-output ToUpper('fr-FR') # equals two arguments to write-output
ToUpper
fr-FR
PS[1] (26) > write-output ToUpper(2+2) # expression (2+2) is evaluated
ToUpper
4
```

**Comment by mklement0** [comment]
@BrucePay:

Good point: Essentially, we'd have to special-case the parsing of arguments passed to `ForEach-Object`'s `-MemberName` parameter (and possibly `Where-Object`'s `-Property` parameter) and parse such arguments as _expressions_.

I can see how that is potentially awkward / impractical to implement - do tell us.  
(I don't think _users_ would necessarily notice the anomaly, however).

Thus, perhaps the better approach is to simply _disallow_ nested method calls.

Given that (a) (as stated), _property_ access is the far more prevalent use case and (b) users already know that operation/comparison statements have limitations, I think that's an acceptable approach (if documented appropriately).

**Comment by PetSerAl** [comment]
`.` is not prohibited symbol for property name thus `$obj | ForEach-Object one.two` is equivalent to `$obj.'one.two'`, but not `$obj.'one'.'two'`.

```powershell
$obj = [pscustomobject]@{ 'one.two' = 3 }
$obj | ForEach-Object one.two
```

**Comment by mklement0** [comment]
@PetSerAl:

Ouch! Good point, thanks.

So this would be a breaking change.

Before we even discuss the bucket (somewhere between 2 and 3), @BrucePay: would distinguishing between `ForEach-Object 'one.two'`  (single property) and `ForEach-Object one.two` (dot notation) even be possible without special-casing? (There is _some_ precedent for this distinction:  
`write-output -foo:bar` vs. `write-output '-foo:bar'`)

**Comment by vexx32** [comment]
That 'special casing' you talk about there isn't really any kind of special case. Parameter names aren't permitted to be enclosed in quotes, generally.

On the other hand, parameter values being enclosed in quotes is always optional except in cases ambiguous to the PS parser. For example, if you want to pass the value `-Foo` to a parameter, you *will* need to enclose it in quotes to prevent the parser seeing it as a parameter and not a value.

**Comment by mklement0** [comment]
@vexx32: Yes, your 2nd example is the more relevant one: it is an instance where the token is interpreted differently depending on whether it is single-quoted or not.

However, as I now realize, both cases apply to the parameter binder only, so a difference in quoting is not seen by the target command.
(And, as an aside, even passing `-Foo` as a parameter _value_ shouldn't require quoting, if it's _syntactically implied_ that the token is a value, not a parameter name - see #4624).

Thus, quoting alone is not a solution; instead, some indicator in the _contents_ of the token is needed to distinguish the two cases.

If we were to use `` ` `` for escaping the `.` - to be interpreted by the target program, then an argument such as ``foo`.bar`` would _additionally_ have to be _quoted_, given that the parameter binder would otherwise "eat" the unquoted `` ` ``
(as stated, this is how it is already done for escaping metacharacters in wildcard expressions).

While it would technically work - if we make the _nested_ case _opt-in_ for the sake of backward compatibility - it is clumsy:

```powershell
# Wishful thinking

PS> [pscustomobject] @{ one = [pscustomobject] @{ two = 2 } }  | Select-Object 'one`.two'
2

PS> $propPath = 'one.two'; [pscustomobject] @{ one = [pscustomobject] @{ two = 2 } }  |
   Select-Object ($propPath -replace '\.', '`.')
2
```

**Comment by mklement0** [comment]
Closed in favor of https://github.com/PowerShell/PowerShell/issues/14633#issuecomment-763228730
