### ISSUE TITLE
Collection operators .Where() and .ForEach() do not unwrap single-item results

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#6512]
The PSv4+ collection operators `.Where()` and `.ForEach()` differ from normal pipeline-output collecting behavior in two respects:

* If the result is a _single_ item, it _isn't unwrapped_; that is, a _collection_ is _always_ returned, and
* that collection is always of type `[System.Collections.ObjectModel.Collection[psobject]]` rather than a regular PS array (`[object[]]`)

In the spirit of https://github.com/PowerShell/PowerShell-RFC/pull/120, the **behavior should be harmonized with how pipeline output is already collected and how the `-*Variable` common parameters (except `-PipelineVariable`) _should_ collect output, according to the RFC**.

Given how contentious the linked `-OutVariable`-related RFC is turning out to be, this proposal may need to become an RFC as well, though perhaps the decision on said RFC will imply how to proceed here.

To reiterate what, to me, motivates this desire for harmonization / resolving inconsistencies:

**The unifying vision is to provide a consistent experience whenever PowerShell collects output for you**, so you never need to worry about different unwrapping  behavior and/or differing collection types.

Note:

**This harmonization would currently incur a performance cost**, because the internally used, resizable collection data types must on output be converted to `object[]]`.

However, **the proper way to resolve this is to switch PowerShell's fundamental collection data type from `[object[]]` to an _efficiently resizable_ one that can be used internally _and_ directly output.**
[Discussion in that direction has started](https://github.com/PowerShell/PowerShell/issues/5643#issuecomment-349811857), but it's obviously a massive _internal_ change; _externally_, assuming no bugs have crept in, however, much of existing code may not only continue to work as-is, but may exhibit automatic performance gains.

To quote @lzybkr  from the linked issue:

> I've often wondered if the comma operator could create a list instead of an array. I have a feeling most scripts would never notice a difference because of how freely things are converted to an object array.

Current Behavior
-----------------

```powershell
PS> (1).ForEach({$_}).GetType().Name; (1, 2).ForEach({$_}).GetType().Name
Collection`1  # single-item result wasn't unwrapped
Collection`1  # output collection type is not [object[]]
```

Desired Behavior
-----------------

```powershell
PS> (1).ForEach({$_}).GetType().Name; (1, 2).ForEach({$_}).GetType().Name
Int32      # single-item result was unwrapped
Object[]   # regular PS array
```

**Comment by BrucePay** [comment]
@mklement0 The `Where()` and `Foreach()` methods *always* return `Collection[PSObject]` by design. This is intended to match the signatures of other methods in the PowerShell API, for example:
```
PS[1] (13) > [powershell]::Create().Invoke

OverloadDefinitions
-------------------
System.Collections.ObjectModel.Collection[psobject] Invoke()
System.Collections.ObjectModel.Collection[psobject] Invoke(System.Collections.IEnumerable input)
System.Collections.ObjectModel.Collection[psobject] Invoke(System.Collections.IEnumerable input,
System.Management.Automation.PSInvocationSettings settings)
:
```

**Comment by mklement0** [comment]
@BrucePay:

`[powershell]::Create().Invoke` is an _API_ function, as you say, whereas `.Where()` and `.ForEach()` are public methods on _any_ object surfaced in regular PowerShell use.

Or where they never meant to be used as such?

If they _are_ meant to be provided as - more performant and flexible - complements to `ForEach-Object` and `Where-Object` (which they are), then consistency with normal PowerShell behavior seems more important to me.

**Comment by BrucePay** [comment]
@mklement0 I guess I'm not being clear. The key point is that they are _methods_, not _commands_and should behave like _methods_, not _commands_. Methods don't stream so there is no ambiguity as to whether the result should be a collection or not. The design team explicitly decided that they would have consistent behaviour and always return a collection. They return `Collection<PSObject>` both for performance reasons, and because this matches the return type other methods in the PowerShell API. Again, both explicit decisions on the part of the design team.

**Comment by mklement0** [comment]
> The key point is that they are methods, not _commands_and should behave like methods, not commands.

That is indeed an important clarification.

> Methods don't stream so there is no ambiguity as to whether the result should be a collection or not.

On a side note: That's perhaps the most commendably succinct rationale for pipeline-output behavior I've ever come across.

> They return Collection<PSObject> both for performance reasons

Understood. I've addressed the performance aspect in my proposal.

> and because this matches the return type other methods in the PowerShell API. 

So the awkwardness arises out of these methods doing double duty: (a) being part of the API and (b) being public methods accessible to regular PowerShell users.

But perhaps (b) was _incidental_, given that:

* these methods aren't documented, as far as I'm aware of.

* [at least internally terming them _operators_](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs#L2427) - seems like a misnomer, given the _method_ syntax.

   * Breaking news: The `.Where()` "operator" (though not `.ForEach()`, as far as I can tell) does make a brief - and unexpected - cameo in the documentation:  ["Where() operator behavior has changed."](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Core/Where-Object?view=powershell-6#notes).

Was (b) incidental?

Either way, **how about surfacing these API methods as bona fide _operators_**?

So, instead of:

```powershell
(1, 2, 3).Where({ $_ -gt 1 })
```

implementing something like:

```powershell
1, 2, 3 -where { $_ -gt 1 }
```

(And analogously for `.ForEach()`).

That would not only make for more natural, PowerShell-like syntax, but would allow us to discuss the output behavior separately from the strictures of the API.

**Comment by BrucePay** [comment]
`.Where()` and `.Foreach` _are_ documented in the context for which they were designed: processing DSC ConfigurationData. See [Using configuration data in DSC](https://docs.microsoft.com/en-us/powershell/dsc/configdata) and [Separating configuration and environment data](https://docs.microsoft.com/en-us/powershell/dsc/separatingenvdata). The second document in particular shows examples of use.

Now there doesn't appear to be a standalone help topic for these methods. We should add this but as near as I can tell, we don't document any of the existing type extensions anywhere (e.g. `.Count` on `object[]`).

> at least internally terming them operators 

This terminology was picked up from LINQ which referred to query methods like `where()` as "operators". 

> the awkwardness arises out of these methods doing double duty: (a) being part of the API and (b) being public methods accessible to regular PowerShell users

I don't understand this statement. What "double duty"?  You seem to be making some artificial distinction here. The PowerShell API **is** part of the regular PowerShell user's experience. Advanced experiences perhaps but not different. 

>Was (b) incidental?

No. It was entirely intentional. 

> how about surfacing these API methods as bona fide operators?

In query scenarios, methods are simpler and compose more naturally (again see LINQ).

> That would not only make for more natural, PowerShell-like syntax, but would allow us to discuss the output behavior separately from the strictures of the API.

Operators aren't commands. Operators have operator semantics, not command semantics. Operators don't stream.

**Comment by mklement0** [comment]
> documented in the context for which they were designed: processing DSC ConfigurationData

That's a fair point: the regular documentation makes no mention of `.Where()` and `.ForEach()`, except for the seemingly random cameo I've mentioned.
I initially discovered them [here](http://www.powershellmagazine.com/2014/10/22/foreach-and-where-magic-methods/) (an article by @KirkMunro), and have been using them ever since.

So, given their lack of user documentation and how hard it is to discover them with reflection, perhaps their esoteric nature spares regular PowerShell users puzzlement over:

* the unfamiliar _collection_ type returned (``System.Collections.ObjectModel.Collection`1``)
* the problematic _element_ type (`[psobject]`) - the usually behind-the-scenes type that causes issues when it surfaces publicly (see #4344, #4343, #5579, #5763, #5797)

Seemingly exactly as designed for API use, but awkward for in-PowerShell use (more on that below).

However, I do now understand the point you were trying to make with: 

> Operators aren't commands. Operators have operator semantics, not command semantics. Operators don't stream.

That's a helpful distinction, thank you - and the kind of basic tenet that I wish were documented somewhere.

---

> This terminology was picked up from LINQ which referred to query methods like where() as "operators".
> In query scenarios, methods are simpler and compose more naturally (again see LINQ).

For in-PowerShell use (not from C#), methods are an awkward fit, due to the different argument syntax, [as I've tried to argue here](https://github.com/PowerShell/PowerShell/issues/5805#issuecomment-366811092):

> _Property_ access comes naturally in PowerShell, _method_ calls do not.
>
> Ideally, you never need to call methods - that's what _cmdlets_ are for.
> 
> The context switching between PowerShell's argument mode and .NET method syntax is a perennial > pain point, even for experienced users.
> [...]
> Instead, PowerShell uses _operators_ to provide convenient abstractions: Much of what requires method calls in, say, C#, is provided via operators such as -join, -split, -replace, ...
> [...]
> As an aside: consider how PowerShell's one foray into method syntax has fared; the (confusingly named) .ForEach() and .Where() collection operators never gained traction.

Of course, I now have a better understanding of perhaps the main reason for their not gaining traction, as discussed above.

> You seem to be making some artificial distinction here. The PowerShell API is part of the regular PowerShell user's experience. Advanced experiences perhaps but not different.

I think the distinction is real, both conceptually and pragmatically:

* the API is for controlling PowerShell from the outside (even though you can also use PowerShell scripting to do so; the more typical use case is to use C#, however, methinks)

* as a regular PowerShell user, you can spend your entire PowerShell life blissfully ignorant of even the existence of the API: you typically don't need it to call cmdlets and write scripts, and the regular `Get-Help` based help system makes no mention of it.

Hence my suggestion to surface `.Where()` and `.ForEach()` as _operators_ `-where` and `-foreach`, ideally with `[object[]]` output for consistency - even though that is clearly implies performance hit, which takes us back to the [discussion of fundamentally changing PowerShell's collection data type](https://github.com/PowerShell/PowerShell/issues/5643#issuecomment-378467986).

**Comment by mklement0** [comment]
@KirkMunro:

As a comparatively inexperienced user, I can tell you that switching between argument mode and method syntax still trips me up on occasion.

It's not that cmdlets _should_ always be used, it's about _ideally_ having the majority of use cases covered by cmdlets, so that less savvy users have their needs met without having to learn about specific .NET types and switching back and forth between conflicting syntax forms and, not least, to benefit from the higher level of abstraction that cmdlets usually provide.

As I've said before: that you have the _option_ to call methods from PowerShell is a great blessing and gives PowerShell its virtually unlimited power, but it is an advanced use case.

**Comment by mklement0** [comment]
Let me try a focused summary:

* No _native_ PowerShell features  that I am aware of are exposed as _methods_: instead, functionality is surfaced as _commands_ (cmdlets/functions) and _operators_.

  * Methods belong to a _different realm_, to which [`Get-Help about_Methods`](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Methods.md) is the portal (albeit one that, unfortunately, currently doesn't discuss syntax pitfalls and doesn't even reference [`Get-Help about_Parsing`](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Parsing.md)); it's a powerful realm and definitely worth knowing about, but it is a different realm, distinct from how PowerShell itself surfaces its functionality.

* The `.Where()` and `.ForEach()` methods were introduced as such for the benefit of _DSC_ - of necessity, I presume, given that the DSC DSL doesn't allow use of _pipelines_.

   * Despite their general availability inside PowerShell itself, they're effectively undocumented, and many people may not even be aware of their existence (since tab completion doesn't help, and neither `Get-Member` nor `.psobject.Methods` find them, you simply have to _know_ of their existence).

   * Even if fully documented (and, as discussed, this is currently even lacking in the _DSC_ context, and overall Kirk's blog post is still the most complete documentation), these methods make awkward tools in general PowerShell use, due to their method syntax and output data types.

Hence my suggestion to surface them as _operators_ with `[object[]]` output, which would make them discoverable interactively (`-<tab>`) , and they would be documented alongside the existing operators.

They'd make concise complements to their cmdlet counterparts; `-foreach` would make the `foreach` _loop_ unnecessary in many situations and with its use of `$_` reduce the existing confusion between the loop and the cmdlet - see #3830:

```powershell
$var = 1, 2, 3 -foreach { $_ + 1 }  # wishful thinking

# vs.

$var = foreach ($i in 1, 2, 3) { $i + 1 }
# or (slower)
$var = 1, 2, 3 | ForEach-Object { $_ + 1 }

#  ---

$var = 1, 2, 3 -where { $_ -gt 1 } # wishful thinking

# vs.
# (slower)
$var = 1, 2, 3 | Where-Object { $_ -gt 1 }
# or
$var = foreach ($i in 1, 2, 3)  { if ($i -gt 1) { $i } }

```

Arguably, even DSC could benefit from the cleaner operator syntax; contrast the following:

```powershell
# Note that this example, taken from https://docs.microsoft.com/en-us/powershell/dsc/separatingenvdata
# doesn't even use `()` around the script-block argument, so the use of Where() 
# isn't even readily recognizable as a *method* call.
Node ($AllNodes.Where{$_.Role -eq "WebServer"}).NodeName { ...

# vs.

Node ($AllNodes -where {$_.Role -eq "WebServer"}).NodeName { ...  # wishful thinking
```

**Comment by mklement0** [comment]
I've decided to create a new issue to focus on the operator proposal: #6576
