### ISSUE TITLE
Profile doesn't load in pwsh6 (but does in 5.1)

### ISSUE THREAD

**Issue by vr8hub** [PowerShell/PowerShell#6514]
I have pwsh6 installed alongside Windows Powershell 5.1 that comes installed with Win10.
I have a profile, profile.ps1, in my Documents\WindowsPowerShell directory.
That profile isn't loading in pwsh6.

That led me to look at about_profile, to see if the profile names or some other behavior changed.
And the text of that statement in pwsh6, unlike 5.1, is almost unreadable.

The, I think, applicable portion:
```
  ---------------------------------------------------------------------------------------------------------------------------------
  Description                  Path
  ---------------------------- ----------------------------------------------------------------------------------------------------
  Current user, Current Host   $Home\\[My ]Documents\\WindowsPowerShell | | | \\Profile.ps1 | |Current User, All Hosts |$Home\[My
                               ]Documents\Profile.ps1

  All Users, Current Host      $PsHome\Microsoft.PowerShell_profile.ps1 | |All Users, All Hosts |$PsHome.ps1
  ---------------------------------------------------------------------------------------------------------------------------------
```

I can't make heads or tails of that. There are double-backslashes where there don't need to be, there are two and three consecutive pipe symbols for unknown reasons, there are names that don't make any sense, e.g. \\Profile.ps1, $PsHome.ps1 ($PsHome is a directory, so $PsHome.ps1 is nonsense), there are what appear to be descriptions embedded in the middle of a line (| |Current User, All Hosts). I assume (hope) the formatting of that section is screwed up.

The end result is I can't tell if this is a real problem, because I can't tell from that documentation what the valid profile locations and names are. If they are the same as 5.1, then this would appear to be a real problem; the profile loads correctly in 5.1 and does not in 6.0.2.

Also, if I dot source the file in pwsh6, it loads without error. So the not loading doesn't appear to be because of a problem with the profile itself.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
Profiles load from ..Documents\PowerShell\Microsoft.PowerShell_Profile.ps1 (you can just use `$profile` to show the path in the console) instead of `WindowsPowerShell` path.  Looks like the doc needs to be updated.  If you want the same profile loaded in both, you can create a symlink.  The markdown that you see will look a bit strange as backslashes need to be escaped, but the rendered HTML should read fine: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-6.

Can you open an issue in the doc repo to get the documentation corrected?  https://github.com/PowerShell/PowerShell-Docs/issues

**Comment by vr8hub** [comment]
What I posted is what actually displayed on the screen. There should be no double-underscores on the screen. (Oh, you mean what's displayed on the screen *is* the Markdown because something happened to keep it from rendering in the help text. That makes sense.)

Yes, I will.
