### ISSUE TITLE
Invoke-RestMethod $uri -FollowRelLink without -MaximumFollowRelLink specified keep running in the loop on the last page.

### ISSUE THREAD

**Issue by white-bee** [PowerShell/PowerShell#6525]
Steps to reproduce
------------------
I was trying to get all the data from REST endpoint that paginated. But it running in the loop on the last page. I would expect it should exit after the last page processed. It works as expected with MaximumFollowRelLink specified, But I can not get the number of the pages in total in Invoke-RestMethod.

```powershell
 $Results = Invoke-RestMethod @Params -Verbose | ForEach-Object {$_}
```

Expected behavior
-----------------

```none
to return data from all pages
```

Actual behavior
---------------
keep running in a loop on the last page 
```none

```

Environment data
----------------
PSVersion                      6.1.0-preview.1
PSEdition                      Core
GitCommitId                 v6.1.0-preview.1
OS                                 Microsoft Windows 10.0.16299
Platform                                 Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion   2.3
SerializationVersion                 1.1.0.1
WSManStackVersion                3.0

```powershell
> $PSVersionTable

```

**Comment by markekraus** [comment]
@white-bee Can you provide what you have supplied in the `@params` hash? Also, How many pages does the API return? 

The default for `-MaximumFollowRelLink` is [5 pages](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Invoke-RestMethod?view=powershell-5.1#optional-parameters).  

Once either the the API has no more pages to return or the `-MaximumFollowRelLink` the looping stops.

https://github.com/PowerShell/PowerShell/blob/5da5a4bf62fcd628d16a50aaf2acf5a85738e064/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs#L1507-L1515

**Comment by markekraus** [comment]
Oops.. too early. I should not respond to things before coffee..

The default for `-MaximumFollowRelLink` is `[int][:MaxValue` ([correct link](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Invoke-RestMethod?view=powershell-6#optional-parameters)). 

What will happen when `-MaximumFollowRelLink` is not present is that the cmdlet will continue to grab the next link until either 2147483647 pages have been pulled or until the API no longer supplies a `next` link.

for example:

```powershell
$res = Invoke-RestMethod -Uri 'https://api.github.com/repositories/49609581/issues' -FollowRelLink
```

There are currently 46 pages so the cmdlet pulls in all 46 pages and then exist.

If you have an API that is looping on the last page, it is possible that the API is providing a `next` link on the last page even though there is no next page. To test this, get the URL of the last page and use the following:

```powershell
$res = Invoke-WebRequest -Uri $uri
$null -eq $res.RelationLink.next
```

If the above is True, then the API is not returning a next link and we would need more details about the API to investigate.

If the above returns False, then the API is returning a next link. In that case there is nothing we can do. The server says there is a next page and you have told us to grab the next page until we reach `2147483647`. It's up the the API to provide us accurate information. Some APIs do use the same URL for `next` over and over, so there is no reasonable way for us to determine if we should ignore the `next` link. All we can do is trust  the server and your settings.

**Comment by KevinMarquette** [comment]
This question may be out of scope for this issue, but is `[int]::MaxValue` an appropriate default?

**Comment by markekraus** [comment]
@KevinMarquette The idea being that when the user does not supply `-MaximumFollowRelLink`, It grabs all the pages (well, assuming the API has -le  2147483647 pages anyway). 

I think the current default is fitting for the Principle of Least Astonishment. If I only know about `-FollowRelLink`, didn't know about `-MaximumFollowRelLink`, and ran `Invoke-RestMethod -Uri $Uri -FollowRelLink`, then I would expect it to grab all the available pages from the API. If it only grabbed 5 by default, I might assume there were only 5 pages on the endpoint when I only receive 5 pages. That would break PoLA, in my opinion.

**Comment by white-bee** [comment]
thank you @KevinMarquette for the prompt reply.

> If you have an API that is looping on the last page, it is possible that the API is providing the next link on the last page even though there is no next page. 

I think you are right. I was going thru RFC and could not find specifics as to what next should be on the last page before I talk to the vendor of the API. Would it make sense to add an additional check like next <> last of something to cover cases like this?

$res.RelationLink
next  https://---?limit=500&offset=18000
prev  https://---?limit=500&offset=17500
last  https://---?limit=500&offset=18000
first https://---?limit=500&offset=0

I could probably have some workaround with using Invoke-WebRequest and get a number of pages and then use it for -MaximumFollowRelLink but that would not make code cleaner...

**Comment by markekraus** [comment]
If there is no `next` page there should be no `next` link. Next is explicit that there is a next page.

As I mentioned, some APIs purposely use the current URL as the next URL. We cannot assume that just because the URL for first page, previous page, and last page is the same as the next page that we are looping needlessly. 

For example:

```none
next https://api.contoso.com/v2/batch/report?id=4f45db04-6517-4de6-88fc-924a807dc578
first https://api.contoso.com/v2/batch/report?id=4f45db04-6517-4de6-88fc-924a807dc578
last https://api.contoso.com/v2/batch/report?id=4f45db04-6517-4de6-88fc-924a807dc578
prev next https://api.contoso.com/v2/batch/report?id=4f45db04-6517-4de6-88fc-924a807dc578
```

The API returns the same `next` link multiple times until the entire batch has been grabbed. When the entire batch is complete, no `next` link is returned. This decreases processing as the backend may not have a page count or it may not be possible to obtain a page count. The batch may be forward-only processing so no `prev` is supplied nor possible.

If your API is supplying a next page and there is no next page, then using `-FollowRelLink` may not be the best solution. You may have to do your own looping:

```powershell
$Pages = do {
    $Response = Invoke-WebRequest -Uri $Uri
    $Response.Content | ConvertFrom-Json
} while ($Response.RelationLink.Next -ne $Response.RelationLink.Last)
```
```

**Comment by white-bee** [comment]
thank you @markekraus . I will try to figure out what API vendor have to say and if not will go back looping (with background jobs probably to make it more fun)

But for the  Invoke-RestMethod  sake how do you safeguard for cases like this so it will not go into a long journey for 2 147 483 647 pages?

**Comment by markekraus** [comment]
@white-bee As said, when there is no next page, an API does not normally provide a `next` link. You have hit an edge case that is, as I understand it anyway, and incorrect use of the `next` link. There really is nothing we can realistically do to prevent that. Decreasing the default `-MaximumFollowRelLink` would break the Principle of Least Astonishment and we can't make any assumptions about links matching. We are at the mercy of API authors to follow RFCs and best practices.

As a general API access rule, one should avoid grabbing all pages blindly. Best practice would be to pull in X number of pages at a time. There are other scenarios where grabbing all pages can lead to unexpected results and API throttling. In my own code, I batch pull no more than 10 pages at a time even when I need to pull all pages. In that case, I would recommend always supplying a `-MaximumFollowRelLink`.

**Comment by KevinMarquette** [comment]
I think I am more astonished at this behavior than I would be with a default limit of say 1000. A sane default with a warning message when you hit that default limit would be ideal.

The current experience of grabbing 100% of all data no matter how much there is or causing the shell to "hang" by default does not feel like a good user experience.

**Comment by markekraus** [comment]
Closing as this appears to be a 3rd party issue.
