### ISSUE TITLE
Feature Request: Hashtable expression splatting

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#6528]
Not my idea, but had a conversation with someone last week (and asked him to open an issue...).

He has many situations where cmdlets have a number of common parameters and then each has one or two of its own. So what he'd like to do is:

```powershell
$commonParameters = @{
    Foo = "Duck"
    Bar = "Moo"
}

Start-FirstThing <splat-syntax>$commonParameters + @{ Arg = 6 }</splat-syntax>

Start-SecondThing <splat-syntax>$commonParameters + @{ Quux = "Bang" }</splat-syntax>
```

Now, I know there are a bunch of ways to come close to this and a few workarounds. **But**, I personally like the sentiment that *expressions* should be splattable, rather than *variables*.

**Comment by markekraus** [comment]
So this

```powershell
$Params = @{
    Name = 'Get-Command'
    Module = 'Microsoft.PowerShell.Core'
}
get-command @Params -CommandType 'Cmdlet' -All
```

and this

```powershell
$Params = @{
    Name = 'Get-Command'
    Module = 'Microsoft.PowerShell.Core'
}
$Params2 = @{
    CommandType = 'Cmdlet'
    All = $true
}
get-command @Params @Params2
````

Are already doable. If those combined with [RFC0002](https://github.com/PowerShell/PowerShell-RFC/blob/master/1-Draft/RFC0002-Generalized-Splatting.md), would that fulfill what they are seeking?

**Comment by markekraus** [comment]
for example

```powershell
Start-FirstThing @commonParameters @@( Arg = 6; Baz = 'Foo' }
```

**Comment by rjmholt** [comment]
Aha! I searched for issues, but should have looked in the RFCs too. Yes, @lzybkr's RFC describes this perfectly.

**Comment by BrucePay** [comment]
Closing in favour of the [Generalized Splatting RFC](https://github.com/PowerShell/PowerShell-RFC/blob/master/1-Draft/RFC0002-Generalized-Splatting.md)

**Comment by TheIncorrigible1** [comment]
I was about to open a feature request based on this topic, so I'm glad github suggested this thread to me!  The links above are dead, but here is the proper one:

https://github.com/PowerShell/PowerShell-RFC/blob/master/2-Draft-Accepted/RFC0002-Generalized-Splatting.md
