### ISSUE TITLE
Incorrect URLs in Readme ("Get PowerShell")

### ISSUE THREAD

**Issue by thorstenkampe** [PowerShell/PowerShell#6532]
A lot of links for the preview packages under [Get PowerShell](https://github.com/PowerShell/PowerShell#new-to-powershell) are broken:

Example for Ubuntu 17.04
```
https://github.com/PowerShell/PowerShell/releases/download/v6.1.0-preview.1/powershell_6.1.0~preview.1-1.ubuntu.17.04_amd64.deb
```
.The second `preview` has a `~` in front instead of a `-`

**Comment by iSazonov** [comment]
Related #6486

**Comment by TravisEz13** [comment]
#6485 is already tracking this
