### ISSUE TITLE
Rename-Item -Force should replace an existing target item for symmetry with Move-Item and New-Item

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#6538]
Note: This would technically be a breaking change and would fall into [Bucket 3: Unlikely Grey Area](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md#bucket-3-unlikely-grey-area).

In the context of the **file-system provider and the registry provider**:

`Move-Item -Force` allows you to replace an existing target file / target registry key (as does `New-Item`).

By contrast, **`Rename-Item -Force` currently refuses to replace (overwrite) an existing item**.

By contrast, all other providers that ship with PowerShell DO support replacing an existing target item via `Rename-Item -Force`:

* Function provider
* Alias provider
* Environment-variable provider
* Variable provider

(Note that these providers have non-hierarchical stores (flat list of items), so they only support `Rename-Item`, not also `Move-Item`).

Note: The forced replacement should only apply to _files_, not _directories_.

Steps to reproduce
------------------

From a filesystem location:

```powershell
New-Item t1, t2
Rename-Item -Force t1 t2
```

Expected behavior
-----------------

The command should (quietly) succeed in renaming `t1`  to `t2`, replacing the existing `t2`.

Actual behavior
---------------

```none
Rename-Item : The file '/Users/jdoe/t2' already exists.
```

Environment data
----------------

```powershell
PowerShell Core v6.0.2 on macOS 10.13.3
PowerShell Core v6.0.2 on Ubuntu 16.04.3 LTS
PowerShell Core v6.0.2 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
Windows PowerShell v5.1.15063.674 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by BrucePay** [comment]
The current behavior of `Rename-Item` in the file system is definitely by design. `Rename-Item` and `Move-Item` are two different cmdlets and have _explicitly different semantics._ `Rename-Item` renames an item in place - an atomic operation in most file systems. It doesn't make a copy of the file in a new location and then remove the old item.

**Comment by mklement0** [comment]
@BrucePay:

* It is commendable that PowerShell (like `cmd.exe`, but unlike `bash`) has distinct commands for _moving_ and _renaming_, because users are likely to think of these operations as distinct (`cmd.exe` offers the same distinction with `move` vs. `rename`, Unix-like platforms do not (just `mv`)).

    * However, with respect to forced replacement I think users are likely to expect consistent behavior.

   * I don't expect the _technical_ issue you bring up to be on a user's mind; fortunately, though, it doesn't have to, because there is a solution (see below).
 
   * The existing help topics for `Move-Item` and `Rename-Item` make no mention of replacement behavior, primarily because there are no filesystem-provider-specific topics for these cmdlets.

* At the level of _system calls_, however, only _one_ function exists for both moving and renaming:

  * On both Windows and Unix-like platforms, replacing an existing target _can_ be achieved with a _single system call_ (I'm assuming that is what you mean by _atomicity_  in this context - another definition (that is not specific to replacement) is along the lines of "The `rename()` system call guarantees that an instance of `new` [the target name/path] will always exist, even if the system should crash in the middle of the operation." (from the [macOS `rename` man page](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man2/rename.2.html))).

    * Unix-like platforms: The `rename()` function even replaces existing targets _by default_ on [macOS](http://www.manpagez.com/man/2/rename/) and [Linux](http://man7.org/linux/man-pages/man2/rename.2.html), and that behavior is also reflected in the standard `mv` utility (something we don't want to emulate).  
(The [POSIX standard](http://pubs.opengroup.org/onlinepubs/9699919799/functions/rename.html) defers to the ISO C standard for the `rename()` system call, where replacement behavior is seemingly left up to the implementation, according to [this draft](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf) (the real document costs money).)

    * Windows API: replacing existing files is _opt-in_ via the [`MoveFileEx()`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365240(v=vs.85).aspx) Windows API function's `MOVEFILE_REPLACE_EXISTING` (I cannot tell whether the behavior is atomic in the Unix sense quoted above).
Currently, for files, both `Move-Item` and `Rename-Item` ultimately call [`System.IO.FileInfo.MoveTo()`](https://docs.microsoft.com/en-us/dotnet/api/system.io.fileinfo.moveto?view=netframework-4.7.1#System_IO_FileInfo_MoveTo_System_String_) and `-Force` for `Move-Item` precedes the `.MoveTo()` with a `.Delete()` call, because `.MoveTo()` _fails_ with a preexisting target (presumably because it either calls the option-less `MoveFile()` WinAPI function or invariably calls `MoveFileEx()` without the `MOVEFILE_REPLACE_EXISTING ` option).
Both calls could be replaced with a single call to `MoveFileEx()` to support both forced replacement and cross-volume moving:
      * `Move-Item`:  use option `MOVEFILE_COPY_ALLOWED ` to support cross-volume moving, and add `MOVEFILE_REPLACE_EXISTING` in case of  `-Force`.
      * `Rename-Item` use option `MOVEFILE_REPLACE_EXISTING` in case of  `-Force` (by definition, a rename operation is never cross-volume).

* A few asides:

  * Even though the Unix `rename()` system call only supports moving  within a given volume, the `mv` utility does support cross-volume moves.

  * The user utilities - `move`, `mv` and `Move-Item` - all _bypass_ the issue of replacing a preexisting target _directory_ by simply moving the source path _into_ that directory.
     * This means that the new path depends on whether a target directory happens to preexist or not - a behavior that can be considered problematic, especially in the context of `Copy-Item` - see #2934
