### ISSUE TITLE
Update-Help tests sporadicly failed

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#6541]
Sample https://travis-ci.org/PowerShell/PowerShell/jobs/360846618#L5033
```
5032 Describing Validate Update-Help from the Web for all PowerShell Core modules.
5033+++++Update-Help : Failed to update Help for the module(s) 'PackageManagement' with UI culture(s) {en-US} : One or more errors occurred. (A task was canceled.)
5034At /home/travis/build/PowerShell/PowerShell/test/powershell/engine/Help/UpdatableHelpSystem.Tests.ps1:204 char:25
5035+                         Update-Help -Module $moduleName -Force
5036+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
5037+ CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
5038+ FullyQualifiedErrorId : UnknownErrorId,Microsoft.PowerShell.Commands.UpdateHelpCommand
5039 
5040
5041    [-] Validate Update-Help for module 'PackageManagement' 30.33s
5042      Expected 1, but got 0.
5043      159:     $helpFilesInstalled.Count | Should -Be $expectedHelpFiles.Count
5044      at ValidateInstalledHelpContent, /home/travis/build/PowerShell/PowerShell/test/powershell/engine/Help/UpdatableHelpSystem.Tests.ps1: line 159
5045      at <ScriptBlock>, /home/travis/build/PowerShell/PowerShell/test/powershell/engine/Help/UpdatableHelpSystem.Tests.ps1: line 208

```

**Comment by iSazonov** [comment]
What we test - Update-Help (1) can update or (2) can dowload?
If we should test only (1) we could cache the help content locally and publish it by means of a test help module (WebListener?).

**Comment by adityapatwardhan** [comment]
Update-Help tests tests are executed against cached local content in most cases. But, we still have to test the code path for downloading the help content. There have been some timeout issues with the help content for `PackageManagement` recently. A similar `Save-Help` test was marked [pending](https://github.com/PowerShell/PowerShell/pull/6545) for same reason. Maybe this should be marked as pending as well till we find a solution.

**Comment by iSazonov** [comment]
Can we use our WebListener module to emulate downloading?
