### ISSUE TITLE
Use nameof() in BoundParameters.ContainsKey() 

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#6548]
We should replace code like `BoundParameters.ContainsKey("Delimiter")` with `BoundParameters.ContainsKey(nameof(Delimiter))`.

Old pattern come from old C# (<6.0) without `nameof()`.

**Comment by iSazonov** [comment]
@SteveL-MSFT 
There are still some examples of the old code. They can be found by `BoundParameters.ContainsKey("`. It is related to parameters like "WhatIf", "TotalCount" and so on. I don’t know how to fix them correctly and forced to leave it to your team, sorry.

**Comment by SteveL-MSFT** [comment]
@iSazonov no worries, I appreciate the work you've already done!
