### ISSUE TITLE
Harmonize Get-Process and Stop-Process syntax with Wait-Process to accept both ID and name positionally

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#6551]
Note: Technically, this would be a [Bucket 3: Unlikely Grey Area](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md#bucket-3-unlikely-grey-area) change.

`Wait-Process` conveniently allows you to target a process by _positional_ argument either by Name or by ID; that is, if a process named `foo` exists with `Id` (PID) `1`, you can choose either of the following options:

```powershell
Wait-Process foo  # binds to -Name
Wait-Process 1    # binds to -Id, because 1 can be parsed as [int]
```

This is convenient; in the unlikely event of an all-digits process name, you can use `-Name` to disambiguate.

Note: since `-Name` and `-Id` are array-valued, the `-Id` parameter is only bound if _all_ array elements can be parsed as `[int]`.

By contrast, `Get-Process` and `Stop-Process`:

* do not offer the same convenience

* bind to _different_ parameters by default: `Get-Process` binds the 1st positional argument to `-Name`, `Stop-Process` to `-Id`.

Harmonizing the parameter syntax among all 3 cmdlets:

* provides more convenience overall

* lessens the cognitive load of having to remember which cmdlets defaults to what parameter.

Hypothetically, existing scripts that used something like `Get-Process 1234` could break, because with the new syntax the previously `-Name`-bound `1234` value would now bind to `-Id` - again, this would only apply to an all-digits name that can be parsed as (and fit into) an `[int]`.

Environment data
----------------

Written as of:

```powershell
PowerShell Core v6.0.2
```

**Comment by BrucePay** [comment]
`Stop-Process` binds to `-ID` by default because ID _identifies a specific process_. This is by design to reduce the chance to killing the wrong process - a non-recoverable operation - **and should not change**.  Simply specifying the process name does not guarantee uniqueness. On the other hand, `Get-Process` binds to `-Name` because that is most useful. `Get-Process -Id` is much less common. I suppose we could change `Get-Process` but I don't see that there is sufficient utility hear to warrant taking a breaking change

**Comment by mklement0** [comment]
@BrucePay:

> because ID identifies a specific process.

Yes, but sometimes you want to kill _all_ process instances of a given executable or you may happen to know that there's only _one_.

**If someone uses, say, `Get-Process bash` and sees _multiple_ processes as a a result, it's fair to assume they'll understand that `Stop-Process bash` will likewise terminate them all.**

Personally, I would value the convenience of, say, `Stop-Process bash` over `Stop-Process (Get-Process bash).Id`

Yes, the change would be a breaking one, but the risks strike me as low.
The upside is the double benefit of convenience and consistency.

**Comment by mklement0** [comment]
@BrucePay:  

Yes, that pattern is easier than `Stop-Process (Get-Process bash).Id`

Here's another pattern, which is the one that keeps tripping me up:

1. _If_ I need to check first - during experimentation on the command line, I often know that it's fine to just kill by name - I run `gps bash` to see what `bash` processes are running.

2. If I know up front / have determined that all can be killed, I try - and fail to - run `spps bash`.

**Preventing accidental destruction is a good thing** to strive for, but it seems to me the **better way to handle this is via confirmation prompts / `-Force` switches, not by restricting syntax and thereby introducing inconsistencie**s.

(Both features already are a part of `Stop-Process`, but only for killing _another user's_ process(es), which (a) requires admin privileges and (b) is currently not enforced on Unix-like platforms).

Also note that the **the current restriction offers little protection**:

If I try to use `Stop-Process <name>` and I get an error message  and then remember to use `-Name` / discover `-Name` via  `Stop-Process -?`, I will run`Stop-Process -Name <name>`, resulting in the feared destruction.

---

As an aside: the error message you get for `Stop-Process <name>` is unhelpful, another result of the syntax restriction:

    Stop-Process : Cannot bind parameter 'InputObject'. Cannot convert the "foo" value of type
    "System.String" to type "System.Diagnostics.Process"

**Comment by BrucePay** [comment]
> I will run `Stop-Process -Name <name>`, resulting in the feared destruction

After a 3-step process (including looking up the command syntax), one hopes one is paying attention to what one is doing. 

In summary, providing friction along destructive paths doesn't guarantee that you won't do something unwise, but it gives you more opportunities to **_think_** about what you are doing.

**Comment by mklement0** [comment]
I fully agree: sowing confusion with inconsistency and unhelpful error messages, and generally making the task at hand as difficult as possible even to those who know what they're doing is indeed the best way to educate and guide users toward not harming themselves.

Satire aside, is this not a fair summary of the current behavior?

**Comment by lzybkr** [comment]
See #2722 for a related discussion.
