### ISSUE TITLE
Should be able to call Get-PSSession -State Opened

### ISSUE THREAD

**Issue by KevinMarquette** [PowerShell/PowerShell#6554]
When I call `Get-PSSessions -State Opened` I get this error that says the parameter set cannot be resolved. It should be valid to call `Get-PSSession` with just the `-State` parameter to get the sessions that match that state.

Steps to reproduce
------------------

```powershell
Get-PSSession -State Opened
```

Expected behavior
-----------------

```none
Id Name            ComputerName    ComputerType    State         ConfigurationName     Availability
 -- ----            ------------    ------------    -----         -----------------     ------------
  1 WinRM1          Server1   RemoteMachine   Opened        Microsoft.PowerShell     Available
  3 WinRM2          Server2   RemoteMachine   Opened        Microsoft.PowerShell     Available
  2 WinRM3          Server3   RemoteMachine   Opened        Microsoft.PowerShell     Available
  4 WinRM4          Server4   RemoteMachine   Opened        Microsoft.PowerShell     Available
```

Actual behavior
---------------
```none
Get-PSSession : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Get-PSSession -State Opened
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-PSSession], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.PowerShell.Commands.GetPSSessionCommand
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by KevinMarquette** [comment]
looks like `-ConfigurationName` suffers from the same problem.

**Comment by iSazonov** [comment]
`Get-PSSession -State Opened -ComputerName localhost`

**Comment by KevinMarquette** [comment]
The discussion point here is that the current implementation requires that you will provide another parameter. This is the current workaround:

    Get-PSSession | Where State -eq 'Opened'

**Comment by thomascwiley** [comment]
> `Get-PSSession -State Opened -ComputerName localhost`

This doesn't work when connecting to a remote host, obviously. For scripts that run in loops for multiple hours (e.g. moving several hundred accounts to Skype online) it's useful to clear out the broken sessions on an interval. 

The 'Get-pssession | where-object {$_.State -eq 'Opened'}' workaround is reliable, but not very efficient.
