### ISSUE TITLE
Screen buffer seems busted after starting a new process on Linux

### ISSUE THREAD

**Issue by jianyunt** [PowerShell/PowerShell#6566]
I am trying to programmatically launch vim for allowing users to edit a file on a Linux VM.  So I did  

 [System.Diagnostics.Process]::Start("vim", "/home/myname/foobar.ps1") 

The vim does launched, however the screen is busted by injecting some random characters for a while then hangs.

![image](https://user-images.githubusercontent.com/10171679/38340009-022818b6-3826-11e8-914e-e25ed519796f.png)

Steps to reproduce
------------------

```powershell

Linux VM
pwsh
[System.Diagnostics.Process]::Start("vim", "/home/myname/foobar.ps1") 

```

Expected behavior
-----------------

The editor should work just as a user directly launches it.

Actual behavior
---------------

See above.

Environment data
----------------

![image](https://user-images.githubusercontent.com/10171679/38339457-3a743af4-3823-11e8-92c4-460edfc7f4d5.png)

env $TERM
xterm-256color
uname -a:
4.4.0-116-generic #140-UBuntu
UBuntu 16.04.1 LTS

**Comment by MaximoTrinidad** [comment]
Hum! Although I don't know reason of using [System.Diagnostics.Process]::Start( ) with VIM, as by itself runs OK!

![diagproces_issue_02_2018-04-04_19-47-29](https://user-images.githubusercontent.com/19892435/38340548-0bd5cc02-3842-11e8-84b4-2f4f7335564e.jpg)

But, Yes! Using [System.Diagnostics.Process]::Start("vim", "/home/myname/foobar.ps1") will impact the console to the point of not able to exit and leaving the swap file open.

![diagproces_issue_01_2018-04-04_19-47-29](https://user-images.githubusercontent.com/19892435/38340553-136312ae-3842-11e8-8f1f-61d08e540cde.jpg)

This happening in my Ubuntu 17.10 
PowerShell
```
PS /home/maxt> $PSVersionTable                                                                                          

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.1
PSEdition                      Core
GitCommitId                    v6.1.0-preview.1
OS                             Linux 4.13.0-38-generic #43-Ubuntu SMP Wed Mar 14 15:20:44 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Also,  my VIM in Windows won't work any more in PowerShell Core Preview.1 as is not accepting keys entries misbehaving to the point not able to make any changes to the file.

![diagproces_issue_03_2018-04-04_19-47-29](https://user-images.githubusercontent.com/19892435/38340723-db358906-3842-11e8-8359-6709150faa74.jpg)

I remember VIM working fine in PowerShell 6.0.1 in Windows.
:(

**Comment by BrucePay** [comment]
Doing `[System.Diagnostics.Process]::Start("vim", "/home/myname/foobar.ps1") ` creates a background process that will conflict with the foreground PowerShell since both processes are writing to the screen. What happens when you just do
`start-process -Wait -FilePath vim -ArgumentList /home/myname/foobar.ps1`
or just
`vim /home/myname/foobar.ps1`

**Comment by MaximoTrinidad** [comment]
I just verify that in one of my Windows 10 VM I have VIM installed and works without any issues in PowerShell 6.0.2.

![diagproces_issue_04_2018-04-04_19-47-29](https://user-images.githubusercontent.com/19892435/38341189-3f241250-3845-11e8-955b-3f4c6bd01818.jpg)

But, using the [System.Diagnostics.Process]::Start("vim", "/home/myname/foobar.ps1") method will make PowerShell Core console misbehave to the point forcing you to close it.

Now, very interesting, using the "start-process" method in Windows will open another console and works like a charm.

![diagproces_issue_05_2018-04-04_19-47-29](https://user-images.githubusercontent.com/19892435/38341437-81765202-3846-11e8-8707-63bc142f7dfd.jpg)

Then, in Linux using start-process, it just stays in the same console but works.  I tested this in both PowerShell Core 6.0.2 and 6.1.0-Preview.1 Ubuntu and WSL.

![diagproces_issue_06_2018-04-04_19-47-29](https://user-images.githubusercontent.com/19892435/38341507-ed54184c-3846-11e8-8b11-aa3187e0cdbd.jpg)

So here's the status:
1. VIM will work in both Windows and Linux in PowerShell Core
2. Start-Process work with VIM in PowerShell Core Windows and Linux.
3. Using the [System.Diagnostics.Process]::Start() method - FATAL BLOW!

:)

**Comment by iSazonov** [comment]
I think we can close this with By-Design.

**Comment by jianyunt** [comment]
Thanks all. "start-process -wait" helps.
