### ISSUE TITLE
Duplicate get-help results:  Powershell does not resolve duplicates.

### ISSUE THREAD

**Issue by JeffGreenlee42** [PowerShell/PowerShell#6569]
I have found previous bugs that have been filed on this..  #4014 all are marked as duplicate and then marked or merged into other bugs but then they are inexplicably closed!   Clearly, this get-help issue is NOT yet fixed!   

Note,  I used "about_ForEach-Parallel"  as an example.  There are many other "about" topics that suffer the same issue.  Just run "get-help about*"   and try some!  It will not be long before you duplicate this error.  Clearly,  Powershell finds the documented source from several sources -  and it simply cannot take the step of displaying one of the documents.   (After searching for about topics online I was able to locate it through Web search engines! )   If there are duplicate documents with the same name,  the user should not have to take steps to ensure there is only one instance of them. 

Steps to reproduce
------------------

> get-help about_ForEach-Parallel -Online

Expected behavior
-----------------

I expect to see the the defined about topic.  (Note:  "-online" parameter is optional. Error Result is the same) 

Actual behavior
---------------

```
PS C:\WINDOWS\system32> Get-Help about_ForEach-Parallel -Online

Name                              Category  Module                    Synopsis                                         
----                              --------  ------                    --------                                         
about_ForEach-Parallel            HelpFile                            Describes the ForEach -Parallel language const...
about_ForEach-Parallel            HelpFile                            Describes the ForEach -Parallel language const...
Get-Help : Multiple Help topics were found. Use only one Help topic with the -Online option.
At line:1 char:1
+ Get-Help about_ForEach-Parallel -Online
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-Help], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.GetHelpCommand
```
 

Environment data
----------------

>  $PSVersionTable
> Name                           Value                                                                                   
> ----                           -----                                                                                   
> PSVersion                      5.1.16299.251                                                                           
> PSEdition                      Desktop                                                                                 
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
> BuildVersion                   10.0.16299.251                                                                          
> CLRVersion                     4.0.30319.42000                                                                         
> WSManStackVersion              3.0                                                                                     
> PSRemotingProtocolVersion      2.3                                                                                     
> SerializationVersion           1.1.0.1      
>

**Comment by iSazonov** [comment]
@JeffGreenlee42 Could you please test with latest PowerShell Core build?

**Comment by JeffGreenlee42** [comment]
@iSazonov  Ok,  I installed Core Build 6.1.0-preview.1 .  I hope that is what you intended.   Upon testing I was not able to repro this issue.  (Note that I did not methodically test every *about* document.)   

However, I'm not sure this proves the original problem has been addressed.   The reason I have doubts is that PS Core 6.1  comes with a much smaller set of "about" documents than the .NET Windows version of Powershell 5.1 .  In order to test this I would need to know which About topics are shared by both versions so I could run and compare the same command.

**Comment by iSazonov** [comment]
@JeffGreenlee42 You copy full set of "about" files to PowerShell Core directory.
Also the repo is for PowerShell Core issues. I don't know whether the #4014 patch was ported to Windows PowerShell.

**Comment by JeffGreenlee42** [comment]
Yes,  I am aware of that.  That is what prompted my last comment.  Running that command in PSCore6.1  gets a VERY different (and much smaller)  list of about topics then running that command in PS5.1.   My question is this:  Are there any About topics that fail (due to this bug)  in PS5.1  that are available in PSCore6.1?      
I think its a reasonable expectation that one could run the EXACT same PS command in both versions to test whether the underlying issue is resolved.

**Comment by vexx32** [comment]
Here is a comprehensive list after running `Update-Help` in administrative mode and pulling the lists from both PS Core and PS 5.1:

Core Topics that are not in PS 5.1:
```
PS C:\WINDOWS\system32> $CoreHelp | Where-Object {$_ -notin $WinPSHelp}
about_Enum
about_Logging
about_pwsh
about_simplified_syntax
About_Using
```

5.1 Topics that are not in Core:
```
PS C:\WINDOWS\system32> $WinPSHelp | Where-Object {$_ -notin $CoreHelp}
about_ActivityCommonParameters
about_Checkpoint-Workflow
about_CimSession
about_DesiredStateConfiguration
about_Escape_Characters
about_Eventlogs
about_ForEach-Parallel
about_InlineScript
about_Parallel
about_Parsing_LocTest
about_PowerShell.exe
about_PowerShell_Ise.exe
about_PSSnapins
about_Scheduled_Jobs
about_Scheduled_Jobs_Advanced
about_Scheduled_Jobs_Basics
about_Scheduled_Jobs_Troubleshooting
about_Sequence
about_Suspend-Workflow
about_Transactions
about_Windows_PowerShell_5.0
about_Windows_PowerShell_ISE
about_Windows_RT
about_WMI
about_WMI_Cmdlets
about_WorkflowCommonParameters
about_Workflows
about_WQL
about_WS-Management_Cmdlets
about_BeforeEach_AfterEach
about_Mocking
about_Pester
about_should
about_TestDrive
about_Scheduled_Jobs
about_Scheduled_Jobs_Advanced
about_Scheduled_Jobs_Basics
about_Scheduled_Jobs_Troubleshooting
about_ActivityCommonParameters
about_Checkpoint-Workflow
about_ForEach-Parallel
about_InlineScript
about_Parallel
about_Sequence
about_Suspend-Workflow
about_WorkflowCommonParameters
about_Workflows
```

**Comment by vexx32** [comment]
So I used this to get a list of all duplicate help topics in my version of PowerShell 5.1:
```
Get-Help about_* | group | where count -gt 1 | select -exp group | select -unique -exp Name
about_ActivityCommonParameters
about_Checkpoint-Workflow
about_ForEach-Parallel
about_InlineScript
about_Parallel
about_Scheduled_Jobs
about_Scheduled_Jobs_Advanced
about_Scheduled_Jobs_Basics
about_Scheduled_Jobs_Troubleshooting
about_Sequence
about_Suspend-Workflow
about_WorkflowCommonParameters
about_Workflows
```
Checking this against the help available in PS Core:
```
PS C:\Program Files\PowerShell\6.0.1> get-help about_* | where{ $_.name -in $winPSTopics }
```
(There was no output.)

So, the answer to your question is... nope! Not one of these duped topics is available in PS Core, at least as far as I can determine right here. :)

**Comment by vexx32** [comment]
Possible stop-gap solution -- have `Get-Help` automatically pass its list through `Group-Object` and return only unique entries?

Obviously it's not perfect, but it's one way of retaining the ability to see at least *one* of the duplicate topics. One is better than none. [*shrugs*]

**Comment by JeffGreenlee42** [comment]
Nice! My question was rhetorical, but now it’s answered! Thank you! I am
glad to see the list of duplicate entries is not so large. Still, those are
some hefty about topics that are rendered unavailable to your average PS5.1
user! (Unless they search a the internet )

I do wonder what led to the duplications in the first place. The “stop-gap”
solution would work....but I would think the ultimate solution should be
with update-help. That command should take steps to ensure that all
get-help topic titles remain unique, should it not?

Actually, correct me if I'm wrong (please!)....but I think a user has the
capability to create help topics, for new modules and functions? What
prevents a hapless user from creating get-help duplicates? I should think
update-help would maintain the help topic collection.

**Comment by vexx32** [comment]
Yeah, there should either be a cmdlet that will scan for and prompt for removal of duplicates (or perhaps just keep the newest file?) at the user's choice... or Update-Help could do that also.

One other interesting thing I found was a list of help topics that are not in Core that are in 5.1 and vice versa, which I thought might also be interesting, if not *directly* relevant ;)

Core Topics that are not in PS 5.1:
```
PS C:\WINDOWS\system32> $CoreHelp | Where-Object {$_ -notin $WinPSHelp}
about_Enum
about_Logging
about_pwsh
about_simplified_syntax
About_Using
```

5.1 Topics that are not in Core:
```
PS C:\WINDOWS\system32> $WinPSHelp | Where-Object {$_ -notin $CoreHelp}
about_ActivityCommonParameters
about_Checkpoint-Workflow
about_CimSession
about_DesiredStateConfiguration
about_Escape_Characters
about_Eventlogs
about_ForEach-Parallel
about_InlineScript
about_Parallel
about_Parsing_LocTest
about_PowerShell.exe
about_PowerShell_Ise.exe
about_PSSnapins
about_Scheduled_Jobs
about_Scheduled_Jobs_Advanced
about_Scheduled_Jobs_Basics
about_Scheduled_Jobs_Troubleshooting
about_Sequence
about_Suspend-Workflow
about_Transactions
about_Windows_PowerShell_5.0
about_Windows_PowerShell_ISE
about_Windows_RT
about_WMI
about_WMI_Cmdlets
about_WorkflowCommonParameters
about_Workflows
about_WQL
about_WS-Management_Cmdlets
about_BeforeEach_AfterEach
about_Mocking
about_Pester
about_should
about_TestDrive
about_Scheduled_Jobs
about_Scheduled_Jobs_Advanced
about_Scheduled_Jobs_Basics
about_Scheduled_Jobs_Troubleshooting
about_ActivityCommonParameters
about_Checkpoint-Workflow
about_ForEach-Parallel
about_InlineScript
about_Parallel
about_Sequence
about_Suspend-Workflow
about_WorkflowCommonParameters
about_Workflows
```

Some pretty big topics are completely missing from Core! Some are a given now that it's cross-platform and not Windows-specific, but there are still a few that I think ought to be there.

**Comment by JeffGreenlee42** [comment]
Yes, I don't know enough to get a picture of the venn diagram between core
and . Net versions.. I suppose there might be other issues that would make
a significant single document inappropriate and inaccurate for one of the
other platforms. There are some that are just plain obvious. "About_WMI".
For example would seem to be a painfully obvious inappropriate topic in
Linux or OSX.🤓. What I am not clear on is how well Core allows remote
operations. If I were on a Mac or Linux machine and I wanted to perform a
WMI operation on a remote Windows machine from a local PSCore shell or
script I would think "about-WMI". Would prove to be a rather handy resource
to have access to!
Then again, maybe PSCore to PS.Net WMI actions are not possible....I'll
have to try it out sometime.

My guess is that the architects of PSCore wish to customize some about
topics to make them more relevant and accurate...I am sure the about
library will be increasing in future builds.

**Comment by vexx32** [comment]
I believe the `*-CimInstance` and similar cmdlets should still function in place of the WMI ones -- they are meant to be the cross-platform replacements, after all! The primary differences are, I believe, the classes and methods available on Linux/Mac/Unix systems.

But yes, I think it's pretty clear on the topic of `Get-Help` that it should absolutely try to resolve duplicates. Just because there aren't any *currently* in PS Core doesn't mean we shouldn't attempt to catch the edge case and have an established method of dealing with it!
