### ISSUE TITLE
PS Installation document needs to be updated to the latest package version.

### ISSUE THREAD

**Issue by anmenaga** [PowerShell/PowerShell#6578]
Installation instructions in [`docs/installation/linux.md`](https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md) use packages `powershell_6.0.2-1`.
They should be updated to use the latest version `v6.1.0-preview.1`

**Comment by bergmeister** [comment]
I disagree. This file should only be for release versions since it gets referenced by the main readme. Pre-release packages should be in a separate file. cc @SteveL-MSFT

**Comment by TravisEz13** [comment]
This documentation is being migrated to PowerShell/PowerShell-Docs . Please file this issue there.
