### ISSUE TITLE
Obsolete struct System.Span was introduced

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#6579]
https://docs.microsoft.com/en-us/dotnet/api/system.span-1?view=netcore-2.0
![image](https://user-images.githubusercontent.com/10873629/38397738-33c468b0-38f4-11e8-9a54-7988495dac72.png)

It was introduced by this change:
https://github.com/PowerShell/PowerShell/pull/6504

**Comment by SteveL-MSFT** [comment]
That doc seems to be wrong.  Span is new and isn’t marked obsolete in corefx https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/Span.Portable.cs.  We would have a compilation error if it was obsolete

**Comment by iSazonov** [comment]
It is in runtime and System.Memory from last summary.

**Comment by iSazonov** [comment]
I found description of the feature https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.2/span-safety.md#metadata-representation-or-ref-like-structs
>Having no other good alternatives that work in old compilers without servicing, an Obsolete attribute with a known string will be added to all ref-like structs. Compilers that know how to use ref-like types will ignore this particular form of Obsolete.

**Comment by daxian-dbw** [comment]
Thanks @iSazonov, that explains it :)

**Comment by TravisEz13** [comment]
Once I did a second restore this error went away.  VS seemed to have some issues...
