### ISSUE TITLE
-Encoding would be to allow more types of values

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#6581]
Currently `-Encoding` parameter accept:
- values of `Encoding` type
- string values that are transformed to `Encoding` type. The strings is a short list from [EncodingConversion](https://github.com/PowerShell/PowerShell/blob/c1c5344a8897262433141ecbc13bb06ac2c4bbef/src/System.Management.Automation/utils/EncodingUtils.cs#L14)

Suggestion:
- allow numeric Ids of registered code pages (like `-Encoding 1251`)
- allow string names of registered code pages (like `-Encoding "windows-1251"`)

**Comment by chuanjiao10** [comment]
3q

**Comment by iSazonov** [comment]
Leave a comment
