### ISSUE TITLE
#requiring a module that dot-sources causes Exit to return 0

### ISSUE THREAD

**Issue by alx9r** [PowerShell/PowerShell#6615]
This came up in Pester/Pester#1021.

Steps to reproduce
------------------

### `ExitCodeTest` folder
Folder in `$Env:PSModulePath` containing files:

```none
ExitCodeTest
 | ExitCodeTest.psm1
 | empty.ps1
 | test.ps1
```
#### `ExitCodeTest.psm1`
```PowerShell
. "$PSScriptRoot\empty.ps1"
```

#### `empty.ps1`

An empty text file in `ExitCodeTest` folder.

#### `test.ps1`

```powershell
#requires -Modules ExitCodeTest
Exit 666777
```

### Invoke

Invoke the following commands at the location of `test.ps1`.

```PowerShell
pwsh.exe .\test.ps1; $LASTEXITCODE
```

Expected behavior
-----------------

```none
666777
```

Actual behavior
---------------

```none
0
```

Workarounds
-------

Removing dot-sourcing from the `.psm1` file results in `666777`.

Replacing `Exit` with `[System.Environment]::Exit()` results in `666777`.

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value                                            
----                           -----                                            
PSVersion                      6.0.2                                            
PSEdition                      Core                                             
GitCommitId                    v6.0.2                                           
OS                             Microsoft Windows 6.3.9600                       
Platform                       Win32NT                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                          
PSRemotingProtocolVersion      2.3                                              
SerializationVersion           1.1.0.1                                          
WSManStackVersion              3.0                                              
```

**Comment by mjr4077au** [comment]
Can this please be re-opened, and can the bot _please_ be investigated? I just encountered this in Windows PowerShell 5.1, it still happens in PowerShell 7.4.1, and nothing's going to happen when the stupid bot is closing off legitimate issues left, right and centre.
