### ISSUE TITLE
Non-uniform behavior when defining a hashtable literal

### ISSUE THREAD

**Issue by Chirishman** [PowerShell/PowerShell#6616]
Int32 keys cannot be defined in a hashtable literal if they match a string key, even if they are strongly typed but Int16 and Int64 keys can.

Steps to reproduce
------------------

```powershell
#Can Be Defined

@{ [int16]1 = 1; [int64]1 = 1; [int32]1 = 1 }
@{ [int16]1 = 1; [int64]1 = 1; 1 = 1 }
@{ [int16]1 = 1; [int64]1 = 1; '1' = 1 }

#Cannot Be Defined

@{ [int16]1 = 1; [int64]1 = 1; 1 = 1;  '1' = 1 }
@{ [int16]1 = 1;  [int64]1 = 1; [int32]1 = 1; 1 = 1 }
@{ [int16]1 = 1;  [int64]1 = 1; [int32]1 = 1; '1' = 1 }

#tl;dr
<#Fail#>    @{[int32]1=1; '1'=1}
<#Work#>    @{[int16]1=1; '1'=1}
```

Expected behavior
-----------------

Either strictly enforce uniqueness of hashtable keys between string and int16 and int64 as is done with int32 or allow hashtable keys to be nonunique if their datatypes are different and either way document as such.

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.16299.251
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.251
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

@BrucePay  - Tagging you as requested

Edit:
I was thinking that this might have at one point had some relation to looking up elements of a hashtable via dot notation. It looks like for numerals to be treated as a string here they must be wrapped in quotes while alpha characters are always treated as strings.

```powershell
PS> $a=@{'1'='a'}
PS> $a.1
PS> $a.'1'
a
PS> $a=@{'a'='a'}
PS> $a.a
a
PS> $a=@{1='a'}
PS> $a.'1'
PS> $a.1
a
```

**Comment by BrucePay** [comment]
@Chirishman Thanks for opening this. I'll take a look.

**Comment by lzybkr** [comment]
I do think this was done originally because the dot syntax for accessing a property always converts the value to a string. V2 reports the same error, so it's definitely not a new(ish) thing.

It might be overly restrictive, but you can always use apis to construct your hashtable.

**Comment by Chirishman** [comment]
@lzybkr  Did you see my edit above re: dot syntax not always casting to string?

**Comment by lzybkr** [comment]
@Chirishman - I did. I can't test V1, but I think that might have changed between V1 and V2, possibly by me.

**Comment by mklement0** [comment]
> you can always use apis to construct your hashtable.

Actually, a cast is all it takes to bypass the problem, so, @Chirishman, your tl;dr example actually shows the _workaround_, not the failure:

```powershell
@{ [1 = 'int'; '1' = 'string' } # BREAKS
@{ [int] 1 = 'int'; '1' = 'string' } # Workaround: use cast
```

_Any_ numerical cast bypasses the problem at definition time.

In short: Given that a cast bypasses the problem and allows later access to both keys, **the problem affects only hashtable _literals_.**

---

However, when accessing the keys later there is a **pitfall** as well:

While the distinction between numeric keys (unquoted; e.g., `1`) and string keys (quoted; e.g., `'1'`) works in principle, the specific integer type chosen is based on the value:

`[int]` (`[int32]`) by default, with implicit widening to `[int64]` -> `[decimal]` -> `[double]` as 
needed to accommodate larger values.

Thus, if the key type is `[int64]`, for instance, but a given key value is small enough to fit into `[int]`, the lookup won't work, and an indexed lookup with an explicit cast must be used.

```powershell
$ht = @{ [int64] 1 = 'int'; '1' = 'string' }

$ht.1 # !! FAILS, because 1 is treated as [int]
$ht[1] # ditto

$ht[[int64] 1]  # OK - using index syntax with a cast is the only option in this case.
```

**Comment by mklement0** [comment]
P.S.: The problem applies to keys that look like floating-point literals too:

```powershell
@{ 1.2 = 'double'; '1.2' = 'string' }  # BREAKS
```

Also note that the faulty hash-table-literal duplicate detection clearly goes out of its way to treat an unquoted number-like key as a string:

```powershell
@{ 1L =  'long'; '1' = 'string' }  # STILL BREAKS; despite the attempt to type 1 as [long]
```

---

As an aside:

Perhaps surprisingly, accessing a `[double]` key works even with dot notation, even though it looks like _nested_ access:
```powershell
@{ 1.2 = 'double' }.1.2   # OK
```

Even mixing that with nested access works:
```powershell
@{ 1.2 = @{ 3 = '1-2-3' } }.1.2.3   # OK too 
```

**Comment by mklement0** [comment]
P.P.S.: 

Perhaps a more puzzling example:

```powershell
@{ 1e2 = 'double'; '100' = 'string' }  # BREAKS
```

Haven't looked at the source code, but it seems that the duplicate-detection mechanism performs the equivalent of `1e2 -eq '100'`; i.e., the string-valued RHS is coerced to the LHS's number type before comparing, whereas using a cast is seemingly taking a different code path.
