### ISSUE TITLE
TrimEnd cuts off last letter of of the string before a dot if after the dot has the same first letter

### ISSUE THREAD

**Issue by unfw** [PowerShell/PowerShell#6621]
When using TrimEnd to trim off after a dot, if the string before the dot has the same last letter as the first letter after the dot, then the trimmed string cuts off the last letter of the resultant string.

Steps to reproduce
------------------

```powershell
"abcde.exe".TrimEnd(".exe")
```

Expected behavior
-----------------

```none
"abcde"
```

Actual behavior
---------------

```none
"abcd"
```

Environment data
----------------

Windows 10 Pro Version 1709 OS Build 16299.309
```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.16299.251
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.251
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by thezim** [comment]
See #6174. This is by design in .Net.

**Comment by unfw** [comment]
Thank you for letting me know.
