### ISSUE TITLE
Ctrl+Arrow Keys are not supported on pwsh Linux

### ISSUE THREAD

**Issue by jianyunt** [PowerShell/PowerShell#6624]
Currently the (Get-PSReadLineOption).EditMode is set to "Emacs" on pwsh Linux.  [The key lookup _dispatchTable for Emacs editmode](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.PSReadLine/KeyBindings.cs#L220) does not have Ctrl+Left or RightArrow defined. Therefore we cannot use Ctrl+L or R arrow key to move to next word on Linux or CloudShell.

The workaround is set the edit mode to `Windows` on Linux OS to make the key work. This is a bit odd.

Set-PSReadLineOption -EditMode Windows

We can either complete the key lookup table definition for Linux or set the  editmode to `Windows` by default while launching pwsh?

Steps to reproduce
------------------
- Linux VM or CloudShell bash + pwsh
- Type "how are you" and press ctrl+right Arrow key or left arrow

Expected behavior
-----------------

```none
The cursor moves to the nextword.
```

Actual behavior
---------------

```none
Cursor stays in its place, no move.
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.1
PSEdition                      Core
GitCommitId                    v6.1.0-preview.1
OS                             Linux 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
Please open PSReadline issues in https://github.com/lzybkr/PSReadLine

**Comment by jianyunt** [comment]
Submitted a PR to see how things go: https://github.com/lzybkr/PSReadLine/pull/668
