### ISSUE TITLE
Install-Module azuread doesn't work on OSX

### ISSUE THREAD

**Issue by samspade21** [PowerShell/PowerShell#6644]
Steps to reproduce
------------------

```powershell
install-module azuread
```

Expected behavior
-----------------

```
azuread module installed.
```

Actual behavior
---------------

```
PackageManagement\Install-Package : Unable to load DLL 'api-ms-win-core-sysinfo-l1-1-0.dll': The specified module or one of its dependencies could not be found.                                       (Exception from HRESULT: 0x8007007E)                                                                                                                                                                 At /usr/local/microsoft/powershell/6.0.2/Modules/PowerShellGet/1.6.0/PSModule.psm1:2057 char:21                                                                                                       + ...          $null = PackageManagement\Install-Package @PSBoundParameters                                                                                                                           +                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
+ FullyQualifiedErrorId : System.DllNotFoundException,Microsoft.PowerShell.Commands.TestModuleManifestCommand,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

```

Environment data
----------------

Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Darwin 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```powershell
> $PSVersionTable

```

**Comment by SteveL-MSFT** [comment]
@samspade21 that module is owned by the AzureAD team and not serviced by this repo.  I would suggest using the `Contact Owners` button on their [PowerShellGallery page](https://www.powershellgallery.com/packages/AzureAD/2.0.1.3) to request that they make their module cross platform
