### ISSUE TITLE
Web Cmdlets Session Cookies not working on macOS

### ISSUE THREAD

**Issue by markekraus** [PowerShell/PowerShell#6645]
Reported to me this week at the PowerShell summit was that the Cookies are not working on macOS when passing a session object.

I have yet to get a repro or the exact details of the issue, but I'm documenting it here for further investigation.

**Comment by vexx32** [comment]
Not sure how useful it'll be, but since I'm here anyway, this might come in handy (aka "it's dangerous to go alone, take this"):
```powershell
function Get-WebSessionCookies {
    [CmdletBinding()]
    param(
        [Parameter(Position = 0, Mandatory, ValueFromPipeline)]
        [Alias('Session', 'InputObject')]
        [ValidateNotNull()]
        [Microsoft.PowerShell.Commands.WebRequestSession]
        $WebRequestSession
    )
    begin {}
    process {
        $CookieContainer = $WebRequestSession.Cookies
        try {
            [hashtable] $Table = $CookieContainer.GetType().InvokeMember("m_domainTable",
                [System.Reflection.BindingFlags]::NonPublic -bor
                [System.Reflection.BindingFlags]::GetField -bor
                [System.Reflection.BindingFlags]::Instance,
                $null,
                $CookieContainer,
                @()
            )
            Write-Output $Table.Values.Values
        }
        catch {
            $PSCmdlet.ThrowTerminatingError($_)
        }
    }
    end {}
}
```
(Because it's low-key a bit of a pain to pull all the cookie data from a websession at times). :)

**Comment by plmcgrn** [comment]
I was able to reproduce this with Invoke-RestMethod, but not Invoke-WebRequest.  It appears that Invoke-RestMethod doesn't play well with object scopes or something, as the session variable is always null unless I'm referencing it from within the same function.

My code is a bit more involved than the above, as I wanted to make the actual REST API request into a reusable function, so I'm passing in headers, body, etc. to that function, and returning a hashtable with both the session and response objects.  If you are running code all in one shot, it seems to work.

Like, this works:
`
$session = $null
$response = Invoke-RestMethod -Uri 'http://www.google.com' -method 'GET' -SessionVariable session                 

$session.cookies

Capacity Count MaxCookieSize PerDomainCapacity
-------- ----- ------------- -----------------
     300     2          4096                20
`
However, creating a PowerShell script and directly calling functions in the script to do this, will not.  
The resulting object you'd return from a function containing Invoke-RestMethod does not have a session object with cookies in it.

Obviously the workaround to this would be to use Invoke-WebRequest and then process the response body for JSON/XML, but it's not simple as Invoke-RestMethod automatically doing that.

**Comment by markekraus** [comment]
I cannot reproduce this.

```powershell
Function Test-SessionScope {
    #build request params
    $params = @{
        uri = 'https://httpbin.org/cookies/set?cookie=a'
        Method = 'GET'
    } 
    $response = Invoke-RestMethod @params -SessionVariable session
    
    [PSCustomObject]@{
        cookieCount = "{0}" -f $Session.cookies.Count
        response = $response
        session = $session
    }
}

$result = Test-SessionScope

$result.cookieCount
$result.response
$result.session.Cookies.GetCookies('https://httpbin.org/cookies/')
````

Result:

```none
1

cookies
-------
@{cookie=a}

Comment    :
CommentUri :
HttpOnly   : False
Discard    : False
Domain     : httpbin.org
Expired    : False
Expires    : 1/1/0001 12:00:00 AM
Name       : cookie
Path       : /
Port       :
Secure     : True
TimeStamp  : 1/23/2019 5:42:55 PM
Value      : a
Version    : 0
```

**Comment by CarloToso** [comment]
Is this still an issue in the latest Powershell version?
