### ISSUE TITLE
Use the MetadataLoadContext to restore reflection-only type discovery for mechanisms like using assembly

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#6653]
See #3641. Types needed in PowerShell classes must be available at parse-time (i.e. not loaded with `Import-Module` or `Add-Type`) to be able to compile classes to IL.

To be able to resolve these types, we want to support the `using assembly` statement. However, the most available way to do this involves loading a DLL and possibly executing some of its code, presenting a vector for arbitrary code execution.

~~Instead, we should analyse a DLL's metadata to discover the types it exports, using a [`System.Reflection.Metadata.MetadataReader`](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.metadata.metadatareader?view=netcore-2.0). Example code for this is in PR #3169. The entry point for this analysis would be the [`PowerShellModuleAssemblyAnalyzer` class](https://github.com/PowerShell/PowerShell/blob/feb38cff707aec8a68f53153008af6233c9e202b/src/System.Management.Automation/CoreCLR/CorePsStub.cs#L639).~~

The right way to do this is now to use a [MetadataLoadContext](https://docs.microsoft.com/en-us/dotnet/standard/assembly/inspect-contents-using-metadataloadcontext)

**Comment by iSazonov** [comment]
Should we thing about PowerShell classes too? I mean getting PowerShell classes at parse time from PowerShell modules.

**Comment by PetSerAl** [comment]
@iSazonov
>Should we thing about PowerShell classes too? I mean getting PowerShell classes at parse time from PowerShell modules.

Is not `using module` already do that?

**Comment by iSazonov** [comment]
I don't know.

**Comment by rjmholt** [comment]
@iSazonov when you say "getting PowerShell classes at parse time" do you mean loading?

That's basically what happens with `using module`. Since we have a nice PowerShell parser that we know doesn't run any code, we read in the class definitions with it and then compile them to .NET IL. So the parser is already able to resolve PowerShell-class-defined types at parse time.

The problem is that we don't have a nice .NET IL parser that we know doesn't run any code (and we only need the IL metadata anyway, to discover what types are available). corefx [ships one](https://github.com/dotnet/corefx/tree/c45c7a7439ab2925d1a6e17e80f396a6bd35c17b/src/System.Reflection.Metadata), but it's pretty low level and documentation on it is sparse. Last time I wrote something using it, I used their tests for guidance. But it should be relatively straightforward.

**Comment by iSazonov** [comment]
@rjmholt You could look our new `Add-Type` cmdlet - it has a code to retrieve types from assemblies (to check duplications).

**Comment by iSazonov** [comment]
It makes sense to use MetadataReader in our TypeResolver too - it seems we load dozens of assemblies unnecessarily.

**Comment by rjmholt** [comment]
This implementation from us is no longer required, since https://github.com/dotnet/corefx/pull/33201

**Comment by daxian-dbw** [comment]
This might not be that useful to `using assembly` since `using assembly` needs to make the assembly actually loaded for its types to be used in IL emitting. But this will be very useful to module analysis, e.g. the [`PowerShellModuleAssemblyAnalyzer`](https://github.com/PowerShell/PowerShell/blob/feb38cff707aec8a68f53153008af6233c9e202b/src/System.Management.Automation/CoreCLR/CorePsStub.cs#L639) class which is not implemented today.

**Comment by rjmholt** [comment]
> This might not be that useful to using assembly since using assembly needs to make the assembly actually loaded for its types to be used in IL emitting

I think the scenario here was to make class definition that depends on `using assembly` and `using module` still safe, so that script files can be parsed and type check successfully without the risk of running an arbitrary DLL on the filesystem.

Much of this [isn't actually required](https://github.com/PowerShell/PowerShell/issues/6722), but the discussion in that issue seems to indicate a preference for going down that path.

I suspect a lot of these implementation discussions should really be had secondary to a design review of classes in some sense, but the available tooling in .NET has moved to a point that makes more things possible.
