### ISSUE TITLE
New-SelfSignedCertificate doesn't exist on windows

### ISSUE THREAD

**Issue by ForkBug** [PowerShell/PowerShell#6656]
Type New-SelfSignedCertificate, we got

PS C:\Program Files\PowerShell\6.0.2> New-SelfSignedCertificate
New-SelfSignedCertificate : The term 'New-SelfSignedCertificate' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ New-SelfSignedCertificate
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (New-SelfSignedCertificate:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

At least it should work on windows 2016

**Comment by iSazonov** [comment]
`New-SelfSignedCertificate` is in PKI module. The module is outside the repository. You could send the request by UserVoice site.

**Comment by ForkBug** [comment]
"It's not our fault. You should blame another department"
