### ISSUE TITLE
Add Levels/Count/AncestorCount to Split-Path -Parent parameter set

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShell#6659]
I quite often end up in situations where I need to remove a known number of directories from the end of a path.

Today, it requires a looping or piping multiple times to split-path.

```powershell
$ancestorLevel = 4
$p = "a\b\c\d\e\f"
while($ancestorLevel--){
   $p = split-path $p
}
$p
```

What is the opinion around having the following?

```powershell
Split-Path -Parent a\b\c\d\e\f -AncestorLevel 2
a\b\c\d

Split-Path -Parent a\b\c\d\e\f -AncestorLevel 4
a\b
```

Better naming is left as an exercise for attentive readers with English as their native toungue.

**Comment by iSazonov** [comment]
We could solve this with #5270

**Comment by powercode** [comment]
Yes, but with less precision since the path separators differ from system to system.
Seems more error prone to me.

**Comment by iSazonov** [comment]
Another question is maybe it is usefull enhancement for .Net  API?

**Comment by BrucePay** [comment]
@iSazonov `Split-Path` is specific to PowerShell in that it depends on the providers to split paths. This means that, along with file paths, it can split registry paths, AD paths, etc. So I don't think .NET will be interested in this specific scenario.

**Comment by iSazonov** [comment]
@BrucePay I don't understand why a script writer is interesting in the feature and C# writer is not. Also .Net has special class `System.IO.Path` which could be enhanced with the feature. For other providers we could do it in the repo.
