### ISSUE TITLE
When will Get-EventLog and Remove-EventLog will be added to powershell 6.0?

### ISSUE THREAD

**Issue by chucklu** [PowerShell/PowerShell#6662]
Hi，
   I am using powershell 6.1.0, I try to use get-eventlog and remove-eventlog today.
  And I find it was not supported in 6.0, but was supported in 5.0 .

**Comment by SteveL-MSFT** [comment]
These cmdlets will be resolved by https://github.com/powershell/windowspowershellcompatibilitypack
