### ISSUE TITLE
Mac High Sierra: Microsoft.Powershell.MANAGEMENT module missing

### ISSUE THREAD

**Issue by venkat-prasadh** [PowerShell/PowerShell#6663]
The Management Module is missing when Powershell is installed in Mac High Sierra 10.13.4.

![screen shot 2018-04-16 at 4 45 44 pm](https://user-images.githubusercontent.com/35565629/38806189-0db2b8f2-4196-11e8-8258-590c25d033fe.png)

This module is available when PS is installed in Sierra 10.12.6

**Comment by SteveL-MSFT** [comment]
`get-module` only shows the modules that are loaded.  Use `get-module -listavailable` to see all available modules.  I'm running the same version of macOS and the Management module works fine.
