### ISSUE TITLE
Import-Module silently fails if RootModule is not set

### ISSUE THREAD

**Issue by felixfbecker** [PowerShell/PowerShell#6666]
- I have been trying to write a set of C# cmdlets and package them up in a module for PowershellGallery.
- I followed the documentation for writing Cmdlets and am compiling it with `dotnet build`.
- I generated a module manifest .psd1 and referenced the output DLL in `RequiredAssemblies`.
- When I run `Import-Module my.psd1`, I get no error, but invoking any of the cmdlets fails with an error that the cmdlet is not recognized. `Get-Module` shows that the module was loaded but `ExportedCommands` is empty.

I don't know if this is a bug in PowerShell or I am doing something wrong, but this is a very frustrating dev experience. If I am doing something wrong, I would expect some kind of error message or better documentation on what needs to be done to hook up C# cmdlets to Powershell.

Here's the repository to reproduce: https://github.com/felixfbecker/ps-kubectl

Environment data
----------------

```powershell
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      6.0.1                                                                                   
PSEdition                      Core                                                                                    
GitCommitId                    v6.0.1                                                                                  
OS                             Darwin 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-45...
Platform                       Unix                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 
WSManStackVersion              3.0                                                                                     
```

**Comment by iSazonov** [comment]
Is this work for you -"specify the dll as your RootModule"?

**Comment by felixfbecker** [comment]
After getting help on Gitter I got it to work by setting the DLL as the RootModule.

I still strongly believe there should be an error if `Import-Module` is called on a module manifest without `RootModule`, or `Test-ModuleManifest`.

It would be nice if this was also mentioned in the tutorial for [writing Cmdlets in C#](https://msdn.microsoft.com/en-us/library/dd878294(v=vs.85).aspx). It is obvious for normal modules, but for C# I assumed I had to add it to `RequiredAssemblies`.

**Comment by iSazonov** [comment]
@felixfbecker Feel free open new Issues with the requests.

**Comment by felixfbecker** [comment]
I believe this issue describes the wish for a better dev experience / error clear enough?

**Comment by iSazonov** [comment]
The Issue is a help question and you get an answer.
If you want a fix for `import-module` you should open new Issue with `Actual behavior` and `Expected behavior`.

**Comment by felixfbecker** [comment]
Here you go: https://github.com/PowerShell/PowerShell/issues/6668
