### ISSUE TITLE
 Import-Module silently fails if RootModule is not set

### ISSUE THREAD

**Issue by felixfbecker** [PowerShell/PowerShell#6668]
Context in #6666

Steps to reproduce
------------------

```powershell
New-ModuleManifest test.psd1
Import-Module ./test.psd1
```

Expected behavior
-----------------

Should error saying that `RootModule` was not set.

Actual behavior
---------------

No error.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      6.0.1                                                                                   
PSEdition                      Core                                                                                    
GitCommitId                    v6.0.1                                                                                  
OS                             Darwin 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-45...
Platform                       Unix                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 
WSManStackVersion              3.0                                                                                     
```

**Comment by BrucePay** [comment]
@felixbecker It's perfectly fine for the root module to be empty. For example you may only have nested modules. But even if you have nothing, you can still manipulate the module through it's `ModuleInfo` object. Now if you specify something as the root module that doesn't exist, you should definitely get an error.

**Comment by felixfbecker** [comment]
Hmm, could the requirement of having to set `RootModule` to a DLL be clarified in the docs on how to write C# cmdlets? I was assuming I have to include it in `RequiredAssemblies` instead. I was following this guide: https://msdn.microsoft.com/en-us/library/dd878294(v=vs.85).aspx
But it doesn't mention module manifests at all, so I was tapping in the dark

**Comment by SteveL-MSFT** [comment]
@felixfbecker a C# cmdlet doesn't require having a [module manifest](https://msdn.microsoft.com/en-us/library/dd878342(v=vs.85).aspx) although it's a best practice.

**Comment by BrucePay** [comment]
@felixfbecker If you start at the top level document [How to Write a Module](https://msdn.microsoft.com/en-us/library/dd878310(v=vs.85).aspx) you should have the information you're looking for. That document links to [How to Write a Binary Module](https://msdn.microsoft.com/en-us/library/dd878342(v=vs.85).aspx) which, in turn, links to the document where you started [Writing a Windows PowerShell Cmdlet](https://msdn.microsoft.com/en-us/library/dd878294(v=vs.85).aspx). Manifests are covered in [How To Write A Module Manifest](https://msdn.microsoft.com/en-us/library/dd878337(v=vs.85).aspx).
