### ISSUE TITLE
Using Enter-PSSession -ContainerId is hardcoded to powershell.exe

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#6669]
The code to connect to a container is [hardcoded](https://github.com/PowerShell/PowerShell/blob/c1c5344a8897262433141ecbc13bb06ac2c4bbef/src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs#L3163) to start powershell.exe.  Need to expose a parameter to allow starting `pwsh`.

Also, `-ContainerId` requires full hash and not just the partial hash which is a usability problem.

Steps to reproduce
------------------

```powershell
docker run microsoft/windowsservercore
# get containerid
docker ps
enter-pssession -containerid <containerId>
```

Expected behavior
-----------------

```none
Ability to connect to PowerShell Core via PowerShell Direct
```

Actual behavior
---------------

```none
Can only connect to Windows PowerShell
```

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.1
PSEdition                      Core
GitCommitId                    v6.1.0-preview.1
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by bergmeister** [comment]
The current cmdlet syntax is:
```powershell
Enter-PSSession [-ContainerId] <string> [-ConfigurationName <string>] [-RunAsAdministrator] [<CommonParameters>]
```
The proposal would be to add a switch `DoNotUseWindowsPowerShell` to be able to use PowerShell Core. I know, the naming does not sound good (double negative, etc), but such a switch parameter is more useful as existing scripts can't be broken by changing the default and having to incorporate the word `PowerShell Core` in a ValidateSet is also not good if it gets renamed back to just `PowerShell` in the future. I am happy to take any suggestions

**Comment by MaximoTrinidad** [comment]
+1

That sounds interesting!  In the scenario of using winrm and having both PowerShell installed in Windows. I would see it practical to have a switch to pick which PowerShell to use.

:)

**Comment by bergmeister** [comment]
Also, as far as I see, the same parameter would need to be added to the `Invoke-Command` cmdlet

**Comment by SteveL-MSFT** [comment]
Closing this since #7241 provides a good enough solution
