### ISSUE TITLE
Introduce attribute to tag a script block as something that should be compiled

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#6672]
PowerShell currently only compiles a script block after it's run 32 times, we should allow scripts authors to tag script blocks where they choose to have compiled initially.

**Comment by BrucePay** [comment]
Compilation is expensive and consumes space. Doing it unnecessarily will slow everything down. So consider a set of modules all annotated to compile but only a subset are actually called. You end up taking the time/space hit from compiling unnecessarily. As was the case with the `register` keyword in C, the compiler can figure out low-level resource allocation better than the script author so I don't think this is a desirable thing long-term. Improving hotspot detection seems like a better place to invest resources.

**Comment by SteveL-MSFT** [comment]
@BrucePay compilation is expensive, but this would be opt-in by the user.  Perhaps consider it a hint than a directive.

**Comment by BrucePay** [comment]
@SteveL-MSFT history has shown this to be a bad idea (Java hotspot, V8, etc). People aren't good at flow analysis of significant code basis. Modern C compilers ignore `register` because it actively interferes with compiler register allocation i.e. it makes things worse. I expect that we would end up in a similar situation.

**Comment by SteveL-MSFT** [comment]
I can accept that if such a capability was introduced, too many people would simply use it to compile their scripts which will introduce other problems.

**Comment by iSazonov** [comment]
Users could use classes if want compilation. Another option is `Add-Type` to get critical fast code.
