### ISSUE TITLE
Make Export-FormatData syntax support specifying the output file positionally

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#6680]
<sup>Related: #6681</sup>

Currently, you cannot _positionally_ specify an output file for `Export-FormatData`, even though it is typically the only (non-switch) parameter, and other export-/file-writing cmdlets you _do_ allow you to specify the target file positionally.

I'd expect all of the following forms to be equivalent:

```powershell
... | Export-FormatData foo.format.ps1xml  # !! NOT supported: positional out-file argument
... | Export-FormatData -Path foo.format.ps1xml
... | Export-FormatData -LiteralPath foo.format.ps1xml
```

~~Also, given that `-Path` doesn't support wildcards, there's no need for a separate parameter set, and so `-Path` can simply be made an _alias_ of `-LiteralPath`.~~ (`-Path`, perhaps surprisingly, does support wildcard expressions, as long as they resolve to a _single_ file.)

Environment data
----------------

Written as of:

```powershell
PowerShell Core v6.0.2
```

**Comment by BrucePay** [comment]
@mklement0 
> Also, given that -Path doesn't support wildcards,

Umm - it most definitely supports wildcards, as in: 
```
Get-FormatData | Export-FormatData -Path b*r.*
```

**Comment by mklement0** [comment]
@BrucePay:

Spoke too soon: the part about how `Export-FormatData`  should support a _positional_ output file-path argument still applies, so I'm reopening this with the wildcard-related part crossed out.

**Comment by mklement0** [comment]
Re not permitting wildcard expressions with `-Path` - please see #6714
