### ISSUE TITLE
Default Export-FormatData to pretty-printing  or add an option

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#6681]
<sup>Related: #6680</sup>

One use case for `Export-FormatData` - even though [`about_Format.ps1xml` doesn't currently mention it](https://github.com/PowerShell/PowerShell-Docs/issues/2341) - is to use existing formatting definitions as a starting point for creating new ones.

To that end, outputting _pretty-printed_ XML would be much more convenient - currently, a single-line XML string is output.

* If changing the existing behavior is not a backward-compatibility concern:

  * Simply output pretty-printed XML by default (it will consume more space, however)

* Otherwise:
  
  * Introduce a switch such as `-Format` (or, to follow the  - inverted - logic of `ConvertTo-Json`, perhaps `-Uncompress`?) that results in pretty-printed output.

Environment data
----------------

Written as of:

```powershell
PowerShell Core v6.0.2
```

**Comment by BrucePay** [comment]
@mklement0 This sounds like a good thing to do. (I would have thought we were already doing it actually.) Anyway, as long as the result is valid XML, simply pretty-printing it should fall within acceptable changes.

**Comment by SteveL-MSFT** [comment]
Pretty printed xml is well-formed and valid, so there's no functional impact.  Seems like a good idea and should be a small change.
