### ISSUE TITLE
Addition error

### ISSUE THREAD

**Issue by Willsatroyd** [PowerShell/PowerShell#6685]
Steps to reproduce
------------------

  [int]$start = 0
  [int]$end = 110
  [double]$Increment = 0.1
  [double]$t = 0

  ($start..$end).foreach({$t = $t + $Increment; "$_ $t"})

Expected behavior
-----------------

Accurately counting from $start to $end by $increment

Actual behavior
---------------

At count 59 the result becomes incorrect: 5.99999999999999, where 60 is expected
At count 100 the result returns as expected
The error indices vary depending on $increment

Environment data
----------------

Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Linux 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

This behaviour is the same in this environment:

Name                           Value
----                           -----
PSVersion                      5.1.16299.15
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.15
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by PetSerAl** [comment]
```powershell
[double]$Increment = 0.1
```
Actual value of `$Increment` is `0.1000000000000000055511151231257827021181583404541015625`, but not `0.1`. It is not PowerShell issue, that is how **binary** floating point numbers work. [Any other language](https://ideone.com/uoSycC) will "suffer" from the same problem. If you need exact **decimal** numbers, then you should use `[decimal]`:
```powershell
$start = 0
$end = 110
$Increment = 0.1d
$t = 0
$start..$end | % { "$_ $(($t += $Increment))" }
```

**Comment by Willsatroyd** [comment]
Understood. Thank you.
