### ISSUE TITLE
Support Ubuntu 18.04

### ISSUE THREAD

**Issue by borgdylan** [PowerShell/PowerShell#6692]
Ubuntu 18.04 has moved to using libcurl4 instead of libcurl3. Even if both verison of the curl bianries and libraries are comaptible, there is a packaging issue that disallows packages using libcurl3 such as powershell to coexist with others that need libcurl4 such as cmake. Please relase powershell for Ubuntu 18.04 a.k.a bionic or people will be getting nasty surpirises next week just liek I did whe I upgraded early.

**Comment by iSazonov** [comment]
@borgdylan Thanks for your contribution! 

It is dup #6307.

We have plans to move to .Net Core 2.1 before PowerShell 6.1 Preview2. 
.Net Core 2.1 will remove the curl dependency.

**Comment by sandersaares** [comment]
Ubuntu 18.04 is just around the corner and not having support for PowerShell in it would be a major loss, forcing people to convert their scripts to inferior systems like Bash.

**Comment by psgivens** [comment]
First off, thank you for the great work on PowerShell. Ubuntu 18.04 is here! Do we know when can I expect to install PowerShell?

**Comment by iSazonov** [comment]
After we merge #6718 we'll review installations, packaging and processing on all systems. Guys, your help in testing and contributions will be very handy.

**Comment by tohuw** [comment]
For those who can't wait (me) and don't want to go crippling your `curl` on 18.04, I'll leave this here:

1. Download the libicu57 dependancy:
```
cd /tmp
wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu57_57.1-6ubuntu0.3_amd64.deb
```
2. Download the Debian package powershell_6.0.1-1.ubuntu.17.04_amd64.deb from the releases page onto the Ubuntu machine.
```
wget https://github.com/PowerShell/PowerShell/releases/download/v6.0.1/powershell_6.0.1-1.ubuntu.17.04_amd64.deb
```
3. Extract the PowerShell package and change the dependencies to libcurl4
```
dpkg-deb -R powershell_6.0.1-1.ubuntu.17.04_amd64.deb pwsh-patched
sudo apt install -y rpl
rpl libcurl3 libcurl4 pwsh-patched/DEBIAN/control
```
4. Re-Package the p package
```
dpkg-deb -b pwsh-patched pwsh-patched.deb
```
5. Install both packages in this order:
```
sudo apt install -fy ./libicu57_57.1-6ubuntu0.3_amd64.deb ./pwsh-patched.deb
```
Kudos to [Tim De Pauw](https://launchpad.net/~timdepauw) for [figuring out this exact libcurl3 dependency problem for another package](https://bugs.launchpad.net/ubuntu/+source/curl/+bug/1754294/comments/25), and @borgdylan for [suggesting this same fix for dotnet](https://github.com/dotnet/core-setup/issues/3875#issuecomment-383187576)

**Comment by kenk667** [comment]
@iSazonov I see that the merge for #6718 was completed, any info on a stable, or even experimental release for 18.04? Install via apt still gets a libicu57 dependency error.

**Comment by iSazonov** [comment]
@kenk667 I believe we don't publish daily builds. I guess latest 17.04 [builds](https://powershell.myget.org/gallery/powershell-core-daily) should run on 18.04
Also I can confirm 18.04 support #6769
I expect we get the package in Preview3 time (in 1-2-3 weeks).

**Comment by iSazonov** [comment]
Latest builds is based on .Net Core 2.1 RC and don't depend on `curl`, I don't now about `libicu57`.

**Comment by patroza** [comment]
@tohuw thanks a lot, it seems to work so far also for the latest 6.1.0 preview https://github.com/PowerShell/PowerShell/releases/download/v6.1.0-preview.2/powershell_6.1.0-preview.2-1.ubuntu.17.04_amd64.deb

**Comment by kenk667** [comment]
@iSazonov I'm unable to install latest (17.04) deb package w/o a libicu57 conflict, and wish not to downgrade to install. Any roadmap for supporting 18.04? I was able to successfully install it by changing the .deb requirements after downloading https://github.com/PowerShell/PowerShell/releases/download/v6.1.0-preview.2/powershell_6.1.0-preview.2-1.ubuntu.17.04_amd64.deb

' ' 'bash
dpkg-deb --raw-exatrct powershell_6.1.0-preview.2-1.ubuntu.17.04_amd64.deb 6.1.0_patched
' ' '

Then alter two patterns, curl and libicu dependencies to current versions;

' ' 'bash
sudo awk '{gsub("curl3","curl4");gsub("libicu57","libicu60");print}' 6.1.0_pathched/DEBIAN/control
' ' '

Repackage as a debian package;

' ' 'bash
dpkg-deb --build 6.1.0_pathched/ powershell_6.1.0-patched.2-1.ubuntu.18.04_amd64.deb
' ' '

Now just install the newly patched .deb package, I like to use gdebi to install;

' ' 'bash
sudo gdebi powershell_6.1.0-patched.2-1.ubuntu.18.04_amd64.deb
' ' '

**Comment by iSazonov** [comment]
>Any roadmap for supporting 18.04?

Seems MSFT teams agreed to add this in 6.1 Preview3.

**Comment by MaximoTrinidad** [comment]
@iSazonov,

That would be nice! I will keep my Ubuntu 18.04 version clean. Until MSFT Team release Preview3, if it makes it available for the new version.

I'm hoping the SQL Server Team would also catch up with SQL Server Linux to make it available too.

:)

**Comment by iSazonov** [comment]
> SQL Server Team

Ping them on UserVoice.

**Comment by MaximoTrinidad** [comment]
@iSazonov, 

I already did back in May 7th: https://feedback.azure.com/forums/908035-sql-server/suggestions/34175752-sql-server-won-t-install-on-linux-ubuntu-18-04-due 

But, I know it's going to take time.

:)

**Comment by iSazonov** [comment]
Leave a comment
