### ISSUE TITLE
Feature Request - Add Support for MacPorts

### ISSUE THREAD

**Issue by dmidlo** [PowerShell/PowerShell#6696]
Homebrew and Macports are the two most popular package managers for macOS.  Unfortunately it's bad practice to coexist MacPorts and Homebrew, How some love for Macports users?  😀 

In practice, adding support for Macport based installation of Powershell would be very similar to the workflow you have for cask development and publication. You can check out the Macports contributor guide here: https://guide.macports.org/chunked/project.contributing.html 

A deployment could be spun up quickly enough, by converting the instructions found here into a portfile: https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-powershell-core-on-macos?view=powershell-6#binary-archives

Anywhoo, this should have the Issue-Enhancement, OS-macOS, labels applied to it.

Here's the Docs:
Macports Contributer Guide: https://guide.macports.org/chunked/project.contributing.html 
Phases of Macports installation: https://guide.macports.org/chunked/reference.phases.html
Portfile Development: https://guide.macports.org/#development
Portfile Reference: https://guide.macports.org/chunked/reference.html

Here's the Repo:
https://github.com/macports/macports-ports

Here's some user commentary:
https://stackoverflow.com/questions/21374366/what-is-the-difference-usage-of-homebrew-macports-or-other-package-installation/21375370#21375370
https://apple.stackexchange.com/questions/32724/what-are-pros-and-cons-for-macports-fink-and-homebrew

Note: I'm a humble sysadmin, packing is far removed from my skillset, so I've simply done my best to apply due-diligence in locating references in the hope that i can keep powershell core up-to-date in a simple way using a very established package manager for the macOS ecosystem.

**Comment by mklement0** [comment]
Can you add more information to the original post as to what, specifically, Powershell supporting MacPorts would mean in practice?

It's unclear to me what _Supports binary archive installation, so a portfile could be spun up quickly enough (I think)..._ means.
