### ISSUE TITLE
Imported module is not removed

### ISSUE THREAD

**Issue by Suncatcher** [PowerShell/PowerShell#6698]
##
I imported module into user directory

    New-Item "$($profile | split-path)\Modules\AudioDeviceCmdlets" -Type directory -Force
    Copy-Item "C:\Path\to\AudioDeviceCmdlets.dll" "$($profile | split-path)\Modules\AudioDeviceCmdlets\AudioDeviceCmdlets.dll"
    Set-Location "$($profile | Split-Path)\Modules\AudioDeviceCmdlets"
    Get-ChildItem | Unblock-File
    Import-Module AudioDeviceCmdlets
Steps to reproduce
------------------
Now it is listed poperly via 

    Get-Module -ListAvailable -Name AudioDeviceCmdlets`
however I cannot remove it with `Remove-Module`. I tried
```powershell
Remove-Module -Name "AudioDeviceCmdlets"
```
and 
```powershell
"AudioDeviceCmdlets" | Remove-Module -Verbose
```
No luck.

Expected behavior
-----------------

```
VERBOSE: Performing operation "Remove-Module" on Target "filetransfer (Path: 'C:\Windows\system32\WindowsPowerShell\v1.0\Modules\filetransfer\filetransfer.psd1')".
VERBOSE: Performing operation "Remove-Module" on Target "Microsoft.BackgroundIntelligentTransfer.Management (Path: 'C:\Windows\assembly\GAC_MSIL\Microsoft.BackgroundIntelligentTransfer.Management\1.0.0.0__31bf3856ad364e35\Microsoft.BackgroundIntelligentTransfe
r.Management.dll')".
VERBOSE: Performing operation "Remove-Module" on Target "psdiagnostics (Path: 'C:\Windows\system32\WindowsPowerShell\v1.0\Modules\psdiagnostics\psdiagnostics.psd1')".
VERBOSE: Removing imported function 'Start-Trace'.
VERBOSE: Removing imported function 'Stop-Trace'.
VERBOSE: Removing imported function 'Enable-WSManTrace'.
VERBOSE: Removing imported function 'Disable-WSManTrace'.
VERBOSE: Removing imported function 'Enable-PSWSManCombinedTrace'.
VERBOSE: Removing imported function 'Disable-PSWSManCombinedTrace'.
VERBOSE: Removing imported function 'Set-LogProperties'.
VERBOSE: Removing imported function 'Get-LogProperties'.
VERBOSE: Removing imported function 'Enable-PSTrace'.
VERBOSE: Removing imported function 'Disable-PSTrace'.
```

Actual behavior
---------------

```
Remove-Module : No modules were removed. Verify that the specification of modules to remove is correct and those
modules exist in the runspace.
At line:1 char:1
+ Remove-Module -Name "AudioDeviceCmdlets"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Remove-Module], InvalidOperationException
    + FullyQualifiedErrorId : Modules_NoModulesRemoved,Microsoft.PowerShell.Commands.RemoveModuleCommand
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.16299.251
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.251
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
Am I doing something wrong?

**Comment by Suncatcher** [comment]
Also I cannot remove conflicting modules. For example, I have those dup modules (bolded) in the directory:

> Directory: C:\Program Files\WindowsPowerShell\Modules
> ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
> Script     1.0.1      Microsoft.PowerShell.Operation.V... {Get-OperationValidation, Invoke-OperationValidation}
> Script     4.2.3      NTFSSecurity                        {Add-NTFSAccess, Clear-NTFSAccess, Disable-NTFSAccessInher...
> **Script     1.1.7.0    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-Packa...
> Binary     1.0.0.1    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-Packa...**
> Script     3.4.0      Pester                              {Describe, Context, It, Should...}
> **Script     1.6.0      PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}
> Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}**
> Script     1.2        PSReadline                          {Get-PSReadlineKeyHandler, Set-PSReadlineKeyHandler, Remov...

How to remove older versions? Remove-Module runs fine first time, but then they listed via `Get-Module` anyway.

**Comment by BrucePay** [comment]
`Get-Module -ListAvailable -Name AudioDeviceCmdlets` will list modules in the module path. Try `Get-Module -Name AudioDeviceCmdlets` to see if the module is actually loaded in memory. 

WRT to multiple versions of a module loaded in memory, modules are stored in the global module table by full path name. This allows you to have multiple modules with the same name loaded. `Remove-Module 'name'` should remove the first matching module. Running it again should remove the second instance. However, you can remove a specific module version with something like
```
remove-module -FullyQualifiedName @{modulename="nettcpip"; moduleversion="1.0.0.0"}
```

**Comment by Suncatcher** [comment]
> Try Get-Module -Name AudioDeviceCmdlets to see if the module is actually loaded in memory

No, it is not loaded. If it's not loaded, is it sufficient to remove the file (DLL) from the path directory?

> However, you can remove a specific module version with something like

Tried this command but it failed again


    PS C:\Windows\system32> Get-Module -ListAvailable -Name PackageManagement
    
    
        Directory: C:\Program Files\WindowsPowerShell\Modules
    
    
    ModuleType Version    Name                                ExportedCommands
    ---------- -------    ----                                ----------------
    Script     1.1.7.0    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-Packa...
    Binary     1.0.0.1    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-Packa...
    
    
    PS C:\Windows\system32> remove-module -FullyQualifiedName @{modulename="PackageManagement"; moduleversion="1.0.0.1"}
    remove-module : No modules were removed. Verify that the specification of modules to remove is correct and those
    modules exist in the runspace.
    At line:1 char:1
    + remove-module -FullyQualifiedName @{modulename="PackageManagement"; m ...
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : ResourceUnavailable: (:) [Remove-Module], InvalidOperationException
        + FullyQualifiedErrorId : Modules_NoModulesRemoved,Microsoft.PowerShell.Commands.RemoveModuleCommand
    
    PS C:\Windows\system32>

**Comment by BrucePay** [comment]
> No, it is not loaded.

If it's not loaded then you can't remove it with `Remove-Module` which only removes modules from memory. 

> If it's not loaded, is it sufficient to remove the file (DLL) from the path directory?

Do you mean $ENV:PATH (the executable path) or $ENV:PSModulePath (the module path). Assuming you meant the module path, if you remove the module directory that contains the .dll, then it will no longer be available as a module.

**Comment by Suncatcher** [comment]
I mean user module path `C:\Users\User\Documents\WindowsPowerShell\Modules`
Okay, so I got it, just to remove the file.
And why does Powershell allow identical modules of different versions with the same commands? How it decides which one to use?

**Comment by BrucePay** [comment]
You can have multiple versions of a module in in case you need them. For example, you may have scripts that depend on a specific version of a module and can't work with the latest version. Conversely you may have other scripts that only work with the latest version.

**Comment by LinuxOnTheDesktop** [comment]
> If it's not loaded then you can't remove it with Remove-Module which only removes modules from memory.

Ah. One expects `Remove-Module` to undo that which `Install-Module`, and perhaps `Import-Module`, does. (That expectation led me to this webpage - I was trying to remove - uninstall - a module.) I do not know what the solution is. Having `Remove-Module` declare, when one tells it to 'remove' an unloaded module, that it removes modules only from memory - that would be clunky.  And `help Remove-Module` does, already, produce text that includes the following.

> This cmdlet doesn't uninstall the module or delete it from the computer. It affects only the current PowerShell session.

Yet, here we have a 'gotcha'.

**Comment by Suncatcher** [comment]
> > If it's not loaded then you can't remove it with Remove-Module which only removes modules from memory.
> 
> Ah. One expects `Remove-Module` to undo that which `Install-Module`, and perhaps `Import-Module`, does. (That expectation led me to this webpage - I was trying to remove - uninstall - a module.) I do not know what the solution is. Having `Remove-Module` declare, when one tells it to 'remove' an unloaded module, that it removes modules only from memory - that would be clunky. And `help Remove-Module` does, already, produce text that includes the following.
> 
> > This cmdlet doesn't uninstall the module or delete it from the computer. It affects only the current PowerShell session.
> 
> Yet, here we have a 'gotcha'.

yep, very stupid behavior, as many things in MS ecosystem. What supposed to be opposite to install does completely different things 🤷‍♂️
