### ISSUE TITLE
Feature request: Add -VerboseVariable and -DebugVariable common paramaters

### ISSUE THREAD

**Issue by markekraus** [PowerShell/PowerShell#6702]
I have often run into the need to capture output from `Write-Verbose` and `Write-Debug`. I know that it can currently be done by using subexpressions and output redirection. Those methods are not quite as user friendly as `-OutVariable`, `-InformationVariable`, `-ErrorVaraiable`, and `-WarningVariable`. I'm sure there was a good reason for not including `-DebugVariable` and `-VerboseVariable`, but I'm curious if these could be added.

**Comment by BrucePay** [comment]
@markekraus IIRC I don't think we saw a need to capture this stuff since it's transient execution information (which you can record with transcript). I'm curious - what are the cases where you find you need it? (I'm not objecting to adding these parameters - it shouldn't be hard, I'm just curious)

**Comment by markekraus** [comment]
Honestly, it's more often `Write-Verbose` and I've never really needed this for `Write-Debug`. But much of it is about UX testing (i.e. Making sure `-Verbose` on certain commands actually return something). The other use case is just general "capture all the outputs" for selective verbose logging (where you want all the output streams captured for some commands but not all). 

There have even been times in the Web Cmdlets tests where we are using the Verbose stream to ensure certain code paths are being hit when it is not obvious or possibel to derive from command output or behavior. For example, this test function:
https://github.com/PowerShell/PowerShell/blob/2da75767365c7136877b53339aec7b372acf16d6/test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1#L266

**Comment by bstrautin** [comment]
Apparently at least one person has a real-world use for this: [Reddit thread](https://www.reddit.com/r/PowerShell/comments/9610yo/capture_verbose_output_of_copyitem/)

**Comment by tnieto88** [comment]
@SteveL-MSFT can this enhancement be added to PS 7?

**Comment by SteveL-MSFT** [comment]
@tnieto88 this is currently not a priority for PS7.  We would welcome a PR from the community however :)

**Comment by KirkMunro** [comment]
This is related to the need for -VerboseAction and -DebugAction as.well,.as mentioned in [this set of RFCs:](https://github.com/PowerShell/PowerShell-RFC/pull/187#pullrequestreview-247359715) . Can I add the lot of them?

**Comment by vexx32** [comment]
👀 _do iiiit_

**Comment by KirkMunro** [comment]
@vexx32 I'm about half way there. Working out kinks from the first pass through the code. That plus Pester tests on deck for tomorrow morning.

**Comment by jantari** [comment]
Is still still on the roadmap?

I want to be able to run a command that produces quite a bit of verbose and/or debug output and capture BOTH those streams to a file for later reference. I do not want these streams in the main output (transcript) of the command because they are lengthy and really spam the otherwise concise transcript with tons of information that is only needed very very rarely.

I basically want to be able to do:

```powershell
# This errors because details.log is locked / already in use
Invoke-ExampleCmdlet -Parameter "value" -Verbose -Debug 4>details.log 5>details.log
```

or

```powershell
# This fails for absolutely no reason really, I guess redirecting streams to anything other
# than 1, 2 or null was just never implemented for unknown or nonsensical reasons ??
Invoke-ExampleCmdlet -Parameter "value" -Verbose -Debug 5>&4 4>details.log
```

or at least:

```powershell
Invoke-ExampleCmdlet -Parameter "value" -Verbose -Debug -VerboseVariable details_verbose -DebugVariable details_debug
```

although that last option would of course result in separatelt captures streams so the order of the output cannot be reconstructed. But at least it's _something_.

**Comment by jantari** [comment]
I still want this.
