### ISSUE TITLE
Remove binary module analysis caching in ModuleCmdletBase.cs

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#6709]
ModuleCmdletBase.cs goes to [some effort](https://github.com/PowerShell/PowerShell/blob/942c68e796c2ff8c40ed31faffe9527e15c8339c/src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs#L5808) currently to run and cache analysis on binary modules. However, in .NET Core, we [don't actually do any analysis](https://github.com/PowerShell/PowerShell/blob/942c68e796c2ff8c40ed31faffe9527e15c8339c/src/System.Management.Automation/CoreCLR/CorePsStub.cs#L641). And we no longer support FullCLR.

So we should consider removing binary module analysis for now, and reinstate it when we have a way to analyse a module without loading it. /cc @daxian-dbw.

**Comment by daxian-dbw** [comment]
We have the guideline that module manifest should not use the wildcard "*" for entries like `FunctionsToExport`, `CmdletsToExport` and etc. Currently, with PowerShell Core, we solely rely on the module manifest when it comes to module analysis for a binary module, and it seems working well enough. So maybe we can remove the remaining DLL inspection analysis code (_not working_) completely for now, and if we have a strong request at a later time, we can implement it in PowerShell Core.

**Comment by daxian-dbw** [comment]
@BrucePay The work for #6653 only requires reading the available public types from a given assembly, while binary module analysis would require more (_attribute, base type, and possibly need to follow the base type chain to another assembly, which would require assembly resolution_). So the work for #6653 would be a subset of the things we need for binary module analysis.

Given your comment, I think we should keep the existing binary module analysis code untouched. The code can be refactored when we get to the implementation.
