### ISSUE TITLE
[Question] How to detect when MSI installer execution failed.

### ISSUE THREAD

**Issue by stknohg** [PowerShell/PowerShell#6715]
Hi. I have a question.

I tried silent install PowerShell Core 6.1.0-preview.1 on Windows Server 2012 R2.  
Here is sample code.

```powershell
# on Windows PowerShell 4.0 console. 
msiexec.exe /i C:\Temp\PowerShell-6.1.0-preview.1-win-x64.msi /le C:\Temp\msi.log /passive
```

This installation failed because of the lack of the Universal C Runtime.  
`msi.log` shows follow. 

```
=== Logging started: 2018/04/24  11:24:41 ===
PowerShell requires the Universal C Runtime to be installed to enable remoting over WinRM. You can find a download link to it here: https://aka.ms/pscore6-prereq
=== Logging stopped: 2018/04/24  11:24:41 ===
```

This is the expected behavior, but exit code of msiexec.exe is `0`, so `$?` returns always `true`.

I want to know how to detect when MSI installer execution failed.

Environment data
----

* PowerShell Core 6.1.0-preview.1
* Windows Server 2012 R2

**Comment by itn3000** [comment]
This is msiexec's spec.
msiexec does not return exitcode to shell in normal way because its subsystem is win32.
you can get exit code by `Start-Process`'s return object with `-PassThru`.
```
$proc = Start-Process msi.exec -Wait -PassThru -ArgumentList "/i","C:\Temp\PowerShell-6.1.0-preview.1-win-x64.msi","/le","g:\temp\msi.log","/passive"
$proc.ExitCode
```
if installation is success, return 0, or installation success but reboot required, return 3010.

**Comment by stknohg** [comment]
@itn3000 Thank you.
I got the exit code 1622.

**Comment by stknohg** [comment]
I close this issue.
