### ISSUE TITLE
Notify runspace that it is beeing debugged

### ISSUE THREAD

**Issue by ForeachCookieInJarGrowALittle** [PowerShell/PowerShell#6719]
Since debugging a runspace essentially allows an adminstrator to impersonate the account the runspace has been started with, it should not be possible to do so unnoticed.

What I would like to see is a notification beeing displayed in the runspace, that is beeing debugged and an event or logentry somewhere to document the runspace-debugging.

**Comment by BrucePay** [comment]
@ForeachCookieInJarGrowALittle 
> What I would like to see is a notification beeing displayed in the runspace

What does this mean? When debugging remote runspaces, background jobs, DSC and workflow, who does it get displayed to?

**Comment by ForeachCookieInJarGrowALittle** [comment]
I think the message should go to the host and in paralell to the eventlog.

The message should at least include information about the user debugging session and the source computer beeing used
