### ISSUE TITLE
Non-filesystem providers don't display root of the drives correctly in the prompt

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell#6721]
In PowerShell Core, it appears that provider prompts are using `PSDriveInfo.Root` instead of `PSDriveInfo.Name` in order to generate each provider's prompt function. 

This is a regression from Windows PowerShell (I can't find a PR that intended to change this behavior), and it makes it significantly more difficult to deduce which provider you're using during interactive usage.

Additionally, the inconsistency of `HKEY_LOCAL_MACHINE:\` vs. `HKLM:\` means that a user may think that they can `cd HKEY_LOCAL_MACHINE:\` when that doesn't actually work.

Steps to reproduce
------------------

```powershell
Get-PSDrive | ? Provider -NotMatch 'FileSystem' | % { cd "$($_.Name):"; prompt }
```

Expected behavior
-----------------

```none
PS Alias:\>
PS Cert:\>
PS Env:\>
PS Function:\>
PS HKCU:\>
PS HKLM:\>
PS Variable:\>
PS WSMan:\>
```

Actual behavior
---------------

```none
>
\>
>
>
HKEY_CURRENT_USER\>
HKEY_LOCAL_MACHINE\>
>
>
>
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.1
PSEdition                      Core
GitCommitId                    v6.1.0-preview.1
OS                             Microsoft Windows 10.0.17650
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by BrucePay** [comment]
@joeyaiello  I can't seem to repro your issue. The `prompt` function uses this API ` $executionContext.SessionState.Path.CurrentLocation.` to figure out what path to display. What happens if you try your example calling this API directly instead of through the prompt. When I run it, I see
```
PS HKLM:\> Get-PSDrive | ? Provider -NotMatch 'FileSystem' | 
    % { cd "$($_.Name):"; $executionContext.SessionState.Path.CurrentLocation.Path }
Alias:\
Cert:\
Env:\
Function:\
HKCU:\
HKLM:\
Variable:\
WSMan:\
```
which looks fine.

**Comment by iSazonov** [comment]
It is not clear what we are tracking here. Should we fix something or we can close the issue? /cc @joeyaiello
