### ISSUE TITLE
Type checking in PowerShell class method bodies is not needed

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#6722]
https://github.com/PowerShell/PowerShell/issues/2074 and https://github.com/PowerShell/PowerShell/issues/3641 and https://github.com/PowerShell/PSScriptAnalyzer/issues/850 discuss type resolution in PowerShell classes.

The examples they use involve types that are required to be known (because they are field/property/method-return types) at compile time (in order to compile the class to IL).

But, we also do type checking in method bodies, even though we don't need to. Example:
```powershell
> class MyClass { [string] GenStr() { return [Foo]::new().ToString() } }
At line:1 char:45
+ class MyClass { [string] GenStr() { return [Foo]::new().ToString() }  ...
+                                             ~~~
Unable to find type [Foo].
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : TypeNotFound
```

In the above, we don't need to compile against `[Foo]` at all, so this should be a runtime error. /cc @daxian-dbw.

**Comment by markekraus** [comment]
@BrucePay 
> I don't know - maybe we should make you add `using module` statements for cmdlets that aren't part of the PowerShell core.

Lets say I have the following `MyModule.psm1`:

```powershell
Enum MyEnum {
    A
    B
}

class MyClass {
    [MyEnum]$Prop1

    MyClass () {
        $This.Prop1 = Get-MyEnumPrivate
    }
}

function Get-MyClassPublic {
    [CmdletBinding()]
    [OutputType([MyClass])]
    param ()
    end {
        [MyClass]::New()
    }
}
Export-ModuleMember -Function Get-MyClassPublic

function Get-MyEnumPrivate {
    [CmdletBinding()]
    [OutputType([MyEnum])]
    param ()
    end {
        [MyEnum]::B
    }
}
```

If checking for unresolved commands and compile time resulted in an error, would that mean module authors would now need to ensure the private functions a method consumes exists or is defined before the class is compiled? That would seem troubling.

**Comment by BrucePay** [comment]
Why? It's already the case for functions i.e. functions must be defined before they can be used. Alternatively we could build the AST for the module, find all the function definitions in the ast and then check the methods to make sure all of the directly called functions are defined, either in the module or through `using module` statements. And for dynamic dispatches, you could still use the call (`&`) operator.

**Comment by markekraus** [comment]
@BrucePay 
> It's already the case for functions i.e. functions must be defined before they can be used.

Perhaps I'm misunderstanding here, but weren't you suggesting with this 

> I don't know - maybe we should make you add using module statements for cmdlets that aren't part of the PowerShell core.

That the PowerShell classes would error at compile time if a method body contained a function that is not already defined? That is a different from a function calling another function at runtime. I can define a function that calls another function that is not yet defined and that will only cause an error at runtime. it does not, however, cause an error at definition time.

> Alternatively we could build the AST for the module, find all the function definitions in the ast and then check the methods  [snip]

Yes. That's where I was going with this, but I just wanted clarity first.

**Comment by BrucePay** [comment]
> That the PowerShell classes would error at compile time if a method body contained a function that is not already defined?

Right. This is different than the dynamic behaviour of functions but we've had a lot of asks for essentially static function resolution at compile time. (I implemented it once to see if it would make dispatch faster - at the time it didn't). Since we've had this idea that classes would exhibit more traditional programming language semantics, having static function resolution seems appropriate.

**Comment by markekraus** [comment]
So long as the module author doesn't need to care too deeply about the order in which the Classes, Enums, and functions are defined in the module, I'm on board with it being stricter.

**Comment by vexx32** [comment]
Being strict is fine, but if we have to start being incredibly picky about the order of definition it would quickly become nothing more than a nuisance. So... yes go for it.
