### ISSUE TITLE
Decide what Unix-relevant functionality should be exposed through cmdlets

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#6725]
Follow-up from #6679, where the difficulty of setting an effective `umask` value from PowerShell is discussed, with @BrucePay wondering whether a `Set-Umask` cmdlet should be provided on Unix-like platforms.

More generally, all Unix/POSIX system calls exposed via the [`Mono.Posix.NETStandard` NuGet package](https://www.nuget.org/packages/Mono.Posix.NETStandard/1.0.0)  should be examined to decide what functionality should be surfaced via cmdlets.

The implementing class is [here](https://github.com/mono/mono/blob/master/mcs/class/Mono.Posix/Mono.Unix.Native/Syscall.cs).

Environment data
----------------

Written as of:

```powershell
PowerShell Core v6.0.2
```

**Comment by SteveL-MSFT** [comment]
https://github.com/PowerShell/PowerShell-RFC/pull/183

**Comment by SteveL-MSFT** [comment]
@JamesWTruher has started working on this module, but it's not planned to be shipped with PS7 but in the PSGallery initially

**Comment by kilasuit** [comment]
@SteveL-MSFT / @JamesWTruher as part of looking at #21005 & the current builing on macos doc I noticed [this comment in issue 847](https://github.com/PowerShell/PowerShell/issues/847#issuecomment-786250031) and wondered if this is something that may get released at all?
