### ISSUE TITLE
Adjust logic of Web Cmdlet Authorization Header Stripping to work with .NET Core 2.1

### ISSUE THREAD

**Issue by markekraus** [PowerShell/PowerShell#6728]
Re #6718 #6632

In dotnet/corefx#26864 the Authorization header is now stripped on redirect. This means that the logic we currently have in place to handle this and to bypass is now reversed. We need to update the logic of the web cmdlets to manually handle redirection when `-PreserveAuthorizationOnRedirect` is supplied and an Authorization request header is present. Currently, they are doing the exact opposite.

**Comment by SteveL-MSFT** [comment]
@markekraus is the test result implying that on a redirect a GET turns into a POST and vice versa?

**Comment by markekraus** [comment]
@SteveL-MSFT  It looks like we originally shipped some incorrect behavior. This was only exposed when I let HttpClient handle the redirects as the existing tests were now testing HttpClient's redirection behavior and not our own code paths.

`Ambiguous` and `MultipleChoices` should redirect POST requests as GET. I verified this behavior in 5.1's HttpClient. We were letting those pass through POST when stripping authorization headers.

`RedirectKeepVerb` and `TemporaryRedirect` should redirect POST requests as POST (that should be obvious from the name KeepVerb). We were changing these to GET when stripping authorization headers.

The problem is that we didn't have tests for both scenarios (keep authorization and strip authorization). It makes sense that we didn't have tests for keeping the authorization header since we were not using our own code paths for redirection. However, without testing both ways, we didn't catch the difference in behavior between the two modes.

I guess fixing this is technically a breaking change... Can you flag this for review?

I pushed a new commit which fixes all of these and ensures we have tests in both keeping and stripping authorization. It finally passes all of the Web Cmdlets tests.

**Comment by markekraus** [comment]
* https://ci.appveyor.com/project/markekraus/powershell/build/v6.1.0-preview.85#L5022
* https://travis-ci.org/markekraus/PowerShell/jobs/372962462#L6006
* https://travis-ci.org/markekraus/PowerShell/jobs/372962463#L4961

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and agrees with the breaking change to get back to correct behavior.  This is really a bug fix that has an unfortunate breaking change from 6.0.
