### ISSUE TITLE
Cursor position gets miscalculated while rendering output on Linux

### ISSUE THREAD

**Issue by jianyunt** [PowerShell/PowerShell#6734]
The cursor randomly jumps around if you resize your console.  This does not happen on bash. 
For the cloudshell, we want to make pwsh better or @ least on par with bash experience . Please consider for the fix. Thanks. 

Steps to reproduce
------------------
1. Linux VM or CloudShell bash + pwsh
2. ls -la 
3. If you make the console smaller, you will see a large space added before the current line
![image](https://user-images.githubusercontent.com/10171679/39273591-213eb4a2-4894-11e8-8db6-63c1ddcd4037.png)
![image](https://user-images.githubusercontent.com/10171679/39273889-1042011c-4895-11e8-822e-0031b6a56e9c.png)

4. make the console bigger, you will see your cursor jump in the middle of the console.

![image](https://user-images.githubusercontent.com/10171679/39273626-3b367c82-4894-11e8-887e-d52b97cf7ddd.png)

```powershell

```

Expected behavior
-----------------

```none

```

Actual behavior
---------------

```none

```

Environment data
----------------

```powershell

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.1
PSEdition                      Core
GitCommitId                    v6.1.0-preview.1
OS                             Linux 4.4.0-121-generic #145-Ubuntu SMP Fri Apr 13 13:47:23 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

**Comment by jianyunt** [comment]
Yes the problem repos on the psreadline 2.0.0-beta1 too.

**Comment by SteveL-MSFT** [comment]
@jianyunt just to be clear, it also repros without PSReadLine loaded?

**Comment by jianyunt** [comment]
Without PSReadline, I am encountering https://github.com/PowerShell/PowerShell/issues/6520. But I guess resizing handling is likely in psreadline.

**Comment by SteveL-MSFT** [comment]
@jianyunt in that case, please open this issue in the [PSReadLine repo](https://github.com/lzybkr/PSReadLine)

**Comment by jianyunt** [comment]
Thanks I added https://github.com/lzybkr/PSReadLine/issues/682
