### ISSUE TITLE
Add overloads to WriteVerbose/WriteWarning to defer string construction until it's necessary

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#6740]
Quote from Jason's [comment](https://github.com/PowerShell/PowerShell/pull/6708#discussion_r183563704) in #6708:

> Not for this PR - but the result of this format call is typically thrown away. It should be possible to check if methods like WriteVerbose will do anything before formatting, or at least add overloads that do the formatting only after deciding the formatted string is needed.

We could add a few overloads to `WriteVerbose` and `WriteWarning`, which take a format string and arguments. So we can defer the construction of message until we know for sure we are going to write out verbose messages.

Open this issue to track this investigation.

**Comment by GeeLaw** [comment]
I'm with @lzybkr on the way to implement this -- use an `if` to check effective configuration.

It's noticeable that currently, if you do the following:

```powershell
Function Test-Information
{
[CmdletBinding()] Param ()
Process { Write-Information $InformationPreference }
}
$a = ''
Test-Information -InformationVariable a
Write-Host $a
```

You will get `SilentlyContinue`, so simply checking whether `InformationPreference` is not `SilentlyContinue` **does not suffice**. I would suggest `$PSCmdlet.ShouldWriteInformation` and friends to check if there is someone receiving the output. People can choose to use that only if formatting is "expensive".

It is also noticeable that, if the message output procedure has any side effects, they will for sure manifest themselves under current implementation, and for once (whether or not it is `SilentlyContinue`, whether or not it is directed to a variable). Documentation on the new paradigm should warn programmers of side effects.
