### ISSUE TITLE
Get-Help output doesn't format propely when aliases man or help is used

### ISSUE THREAD

**Issue by kvprasoon** [PowerShell/PowerShell#6744]
When using Get-Help aliases `man` or `help` output for a cmdlet gives output properly formatted till PS 5.1, but 6.x misses that.

Steps to reproduce
------------------

```powershell
man Invoke-Command
```

Expected behavior
-----------------
![image](https://user-images.githubusercontent.com/12897753/39321998-0ba46bc0-4978-11e8-84b2-e20d06442d86.png)

Actual behavior
---------------

![image](https://user-images.githubusercontent.com/12897753/39321755-6b223344-4977-11e8-8c1e-c557b944349b.png)

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.1
PSEdition                      Core
GitCommitId                    v6.1.0-preview.1
OS                             Microsoft Windows 10.0.10586
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kvprasoon** [comment]
@iSazonov  Actually I'm facing some difficulty in building it locally,

![image](https://user-images.githubusercontent.com/12897753/39366226-d23480f4-4a22-11e8-93ae-4315ccc32189.png)

**Comment by iSazonov** [comment]
Please download from https://github.com/PowerShell/PowerShell#get-powershell

**Comment by iSazonov** [comment]
Thanks! I can not repo with default console. What is your console config? Width?

**Comment by kvprasoon** [comment]
IMO, it should responsive.
```
ForegroundColor       : Gray
BackgroundColor       : Black
CursorPosition        : 0,1
WindowPosition        : 0,0
CursorSize            : 25
BufferSize            : 237,9001
WindowSize            : 237,63
MaxWindowSize         : 237,63
MaxPhysicalWindowSize : 239,63
KeyAvailable          : True
WindowTitle           : PowerShell 6.1.0-preview.1
```

**Comment by iSazonov** [comment]
Thanks! Could you tests with width < 120?

**Comment by kvprasoon** [comment]
Sure, this is with 119
![image](https://user-images.githubusercontent.com/12897753/39378146-0d83fc2e-4a47-11e8-9e4b-f19e17951793.png)

**Comment by iSazonov** [comment]
I can get the same only if I maximize console window, do `Get-Help Invoke-Command`, restore console windows. If I then get previous command the cursor set on top line :confused:

**Comment by SteveL-MSFT** [comment]
I'm not able to repro this either with various console sizes.  Like @iSazonov I can only get "improper" formatting if I resize the console window after it's calculated the output which is expected.

**Comment by iSazonov** [comment]
Maybe a locale or font?

**Comment by kvprasoon** [comment]
Very interesting, I'm getting only when I use aliases both `man` and `help`. `Get-Help` works fine. But the aliases works perfectly till 5.1 !!!

Very interesting.

**Comment by SteveL-MSFT** [comment]
This is "by design" in that when you just use `Get-Help`, it returns an ExtendedCmdletHelpInfo object which gets formatted.  When you use `help` (or alias `man`) or even `Get-Help | more`, it's the raw text which is not formatted for your console.

**Comment by kvprasoon** [comment]
Got it, but **alias** _(definition: used to indicate that a named person is also known or more familiar under another specified name.)_ should be a kind of **aka** , but what I understood from this exercise is `man` and `help` does a `|more` to the output by default, is my understanding correct ?

**Comment by ThomasNieto** [comment]
Is this still an issue? I wasn't able to reproduce on 7.1rc1.

**Comment by kvprasoon** [comment]
looks fine now. Thanks @ThomasNieto for checking this out.
