### ISSUE TITLE
powershell on macOS cannot read files for smb shares

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#6759]
Steps to reproduce
------------------

```powershell
cd smb://server/share/manikb/AADRM/
```

Expected behavior
-----------------

```none
change directories to the share
```

Actual behavior
---------------

```none
dir : Cannot find drive. A drive with the name 'smb' does not exist.
At line:1 char:1
+ dir smb://server/share/manikb/AADRM/
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (smb:String) [Get-ChildItem], DriveNotFoundException
+ FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.2
PSEdition                      Core
GitCommitId                    v6.1.0-preview.2
OS                             Darwin 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by WindowsAdmin92** [comment]
Created a test share on my server and tried the following;

1) cd smb://homeserver/test
1) cd "smb://homeserver/test"
3) cd smb://homeserver\test
4) cd smb:\\homeserver\test
5) cd smb:\\homeserver\test"
6) cd "\\homeserver\test"

^ Also tried the above with "\" at the end of test

Even if I use SMBD with "statshares" or "view", I can't see my SMB share. 

I'll test more tomorrow

**Comment by WindowsAdmin92** [comment]
@MaximoTrinidad 

Try this from Posh = smbutil view //servername/servershare

If that works for you as it did for me, we're one step closer :)

**Comment by WindowsAdmin92** [comment]
I'm also trying with New-PSDrive/Get-PSDrive, but not having any luck.

**Comment by MaximoTrinidad** [comment]
I think it's working as I've shown above.
Here's my test results using the following commands:
```
## - These work!
smbutil view //max_t@sapien01 
smbutil view //max_t@sapien01/TempSQLBackups

## - This one doesn't:
smbutil view //sapien01/TempSQLBackups                                                                  
Password for sapien01: 
smbutil: server rejected the authentication: Authentication error
```
But, the last line is missing the userid!

![macos_smb_03_2018-05-13_9-02-49](https://user-images.githubusercontent.com/19892435/39967902-c6975a16-5691-11e8-9106-b60ea4790c25.jpg)

**Comment by WindowsAdmin92** [comment]
Yes, I'm seeing the same thing you are per my previous comment. I'm just curious as to why it won't work with Set-Location or New-PSDrive. Smbutil doesn't feel like the PowerShell way! Lol. I'm going to keep testing with New-PSDrive and see what there is to be unraveled.

**Comment by MaximoTrinidad** [comment]
As a matter of fact!!  Yes! New-PSDrive doesn't feel like PowerShell and could be true.
I've seen the alias of "mount" with it.  I'm suspecting they left the Linux/Unix command to be use instead.

:)

**Comment by MaximoTrinidad** [comment]
FYI - For some time now, and I think either I post the issue or commented, that New-PSDrive wasn't working to create CIFS/SMBFS drives.  
:)

**Comment by WindowsAdmin92** [comment]
Awe dang! Well thank you. Hopefully it's resolved soon.

**Comment by MaximoTrinidad** [comment]
I will search for that issue to resurface.  I've just realized that the help is lacking information big time in both Windows and Non-Windows PSCore New-PSDrive cmdlet.

![new-psdrive_mac_2018-05-13_9-52-43](https://user-images.githubusercontent.com/19892435/39967993-cef68cde-5693-11e8-80d3-fb2e6246838c.jpg)

![new-psdrive_win_2018-05-13_9-52-43](https://user-images.githubusercontent.com/19892435/39967995-d5db8a9a-5693-11e8-9173-4711df631a64.jpg)

**Comment by MaximoTrinidad** [comment]
FYI - New-PSDrive referencing mapping issues cross-platform: (https://github.com/PowerShell/PowerShell/issues/1409) and (https://github.com/PowerShell/PowerShell/issues/6629)
