### ISSUE TITLE
Autocompletion ctrl+space does not unmark items already selected

### ISSUE THREAD

**Issue by bateskevin** [PowerShell/PowerShell#6785]
Powershell 6.1.0 preview.1
 
If I use ctrl+space to show me the autocompletion options items I already selected will not unmark them. 

Steps to reproduce
------------------

Open Powershell type in 'write-host "test" -foregroundcolor ' hit ctrl+space and use the cursors to select an item. 

Expected behavior
-----------------

When I move on to another item the item that was selected and marked before should be unmarked.

```

Actual behavior
---------------

The Item that was selected before is not unmarked.

```
![cd177096-6a25-4421-9788-b83d58bc7a93](https://user-images.githubusercontent.com/31886373/39479445-8a47857a-4d65-11e8-92e3-6ea0d7ac9495.GIF)

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.1
PSEdition                      Core
GitCommitId                    v6.1.0-preview.1
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

**Comment by SteveL-MSFT** [comment]
Try beta1 of PSReadLine 2.0 which seems to have resolved this:

```powershell
install-module psreadline -AllowPrerelease -Force -RequiredVersion 2.0.0-beta1
```

**Comment by bateskevin** [comment]
Hi Steve, I updated the psreadline module and I'm still facing the same issue. Just to be clear, this is not in any way critical for me. I just thought I'd report it.

**Comment by SteveL-MSFT** [comment]
@bateskevin did you remove the existing version of PSReadLine that we ship with PSCore6 and made sure you loaded 2.0.0-beta1?  After I use 2.0.0-beta1, I don't see this issue on Win10.

**Comment by cpmcgrath** [comment]
I also experienced this error, I installed psreadline 2.0.0-beta2 and the issue was resolved.
