### ISSUE TITLE
Unspecific error when importing Format.ps1xml: A node is missing from TableControl, ListControl, WideControl, CustomControl

### ISSUE THREAD

**Issue by felixfbecker** [PowerShell/PowerShell#6788]
When I am trying to import my Format.ps1xml file, I get a very unspecific errors message. I am coming here because I couldn't figure out what is wrong about this file after reading the XML reference extensively, asking a [question on StackOverflow](https://stackoverflow.com/questions/50095027/whats-wrong-about-this-format-ps1xml-file-a-node-is-missing-from-tablecontrol/50096396#50096396) and Gitter, and even digging through the PowerShell source code to find out where it is thrown.

I assume this is not a bug, so it would be great if the error had a more helpful error message. An XSD schema would also help.

Steps to reproduce
------------------

```xml
<?xml version="1.0" encoding="utf-8" ?>
<Configuration>
    <ViewDefinitions>
        <View>
            <Name>MyType</Name>
            <ViewSelectedBy>
                <TypeName>MyTypeName1</TypeName>
                <TypeName>MyTypeName2</TypeName>
            </ViewSelectedBy>
            <ListControl>
                <ListEntries>
                     <ListEntry>
                        <EntrySelectedBy>
                            <TypeName>MyTypeName1</TypeName>
                        </EntrySelectedBy>
                        <ListItems>
                            <ListItem>
                                <PropertyName>myProp1</PropertyName>
                            </ListItem>
                        </ListItems>
                    </ListEntry>
                    <ListEntry>
                        <EntrySelectedBy>
                            <TypeName>MyTypeName2</TypeName>
                        </EntrySelectedBy>
                        <ListItems>
                            <ListItem>
                                <PropertyName>myProp2</PropertyName>
                            </ListItem>
                        </ListItems>
                    </ListEntry>
                </ListEntries>
            </ListControl>
        </View>
    </ViewDefinitions>
</Configuration>
```
```powershell
Update-FormatData test.Format.ps1xml
```

Expected behavior
-----------------

This should load without error, and make `MyTypeName1` and `MyTypeName2` display as a list, with `myProp1` being shown for `MyTypeName1` and `myProp2` being shown for `MyTypeName2`.

Actual behavior
---------------

This error:

```
Update-FormatData : Errors occurred while loading the format data file:
test.Format.ps1xml, Error at XPath /Configuration/ViewDefinitions/View[1] in file test.Format.ps1xml: A node is missing from TableControl, ListControl, WideControl, CustomControl.
At line:1 char:1
+ Update-FormatData ./PSSourcegraph.Format.ps1xml
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Update-FormatData], RuntimeException
+ FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.UpdateFormatDataCommand
```

I don't see what node is missing.
Weirdly, if I remove `EntrySelectedBy`, the error doesn't occur - but I need it to switch between the types, and I don't see what else I am missing from the [documentation](https://msdn.microsoft.com/en-us/library/gg580904(v=vs.85).aspx).

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Darwin 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by sethvs** [comment]
Hello.
There should be one default `<ListEntry>` without `<EntrySelectedBy>` tag.

```xml
<?xml version="1.0" encoding="utf-8" ?>
<Configuration>
    <ViewDefinitions>
        <View>
            <Name>MyType</Name>
            <ViewSelectedBy>
                <TypeName>MyTypeName1</TypeName>
                <TypeName>MyTypeName2</TypeName>
            </ViewSelectedBy>
            <ListControl>
                <ListEntries>
                    <ListEntry>
                        <ListItems>
                            <ListItem>
                                <PropertyName>myDefaultProp</PropertyName>
                            </ListItem>
                        </ListItems>
                    </ListEntry>
                     <ListEntry>
                        <EntrySelectedBy>
                            <TypeName>MyTypeName1</TypeName>
                        </EntrySelectedBy>
                        <ListItems>
                            <ListItem>
                                <PropertyName>myProp1</PropertyName>
                            </ListItem>
                        </ListItems>
                    </ListEntry>
                    <ListEntry>
                        <EntrySelectedBy>
                            <TypeName>MyTypeName2</TypeName>
                        </EntrySelectedBy>
                        <ListItems>
                            <ListItem>
                                <PropertyName>myProp2</PropertyName>
                            </ListItem>
                        </ListItems>
                    </ListEntry>
                </ListEntries>
            </ListControl>
        </View>
    </ViewDefinitions>
</Configuration>
```

**Comment by Stephanevg** [comment]
I agree with @felixfbecker  This is not a bug, and more an issue related to the documentation of custom types. 
I had the same issue, adding that missing node fixed it.

**Comment by felixfbecker** [comment]
I am working on XSDs for Format and Types.ps1xml files:

![image](https://user-images.githubusercontent.com/10532611/45297479-cdfa5880-b505-11e8-88d4-20cf464532f8.png)

This is with the [vscode-xml](https://github.com/redhat-developer/vscode-xml) extension.
Schemas are here: https://github.com/felixfbecker/PowerShellXSD

I currently just autogenerated this schema from the Format file in that repo.

I will investigate writing a script that parses the official schema markdown reference [here](https://github.com/PowerShell/PowerShell-Docs/blob/staging/developer/format/format-schema-xml-reference.md) and converts it into an XSD (probably with manual edits afterwards).

I couldn't find reference docs for Types.ps1xml files unfortunately, but they also seem simpler.

Another unfortunate thing to mention is that schema validation won't work if you want to use ANSI color codes in Format files because of https://github.com/PowerShell/PowerShell/issues/7526

**Comment by felixfbecker** [comment]
Filed https://github.com/PowerShell/PowerShell/issues/7749 to track work on schemas
