### ISSUE TITLE
Extension crashes all the time in random places and actions

### ISSUE THREAD

**Issue by justin-romano** [PowerShell/PowerShell#6792]
Steps to reproduce
------------------
Sorry this is brief but there is no pattern and you most likely will tell by the logs i have posted what is going on.
1. Write some powershell code
2. Run the code

Expected behavior
-----------------
It should run without random crashes.

Actual behavior
---------------
it runs with random crashes. Sometimes i have to close vscode
I get the message "Debug adapter process has terminated unexpectedly"
Environment data

```powershell
Name                           Value
----                           -----
PSVersion                     5.1.16299.251
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.251
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
[EditorServices.log](https://github.com/PowerShell/PowerShell/files/1965781/EditorServices.log)
[vscode-powershell.log](https://github.com/PowerShell/PowerShell/files/1965782/vscode-powershell.log)

**Comment by SteveL-MSFT** [comment]
Please open an issue here: https://github.com/powershell/powershelleditorservices

**Comment by justin-romano** [comment]
ok, have done. also does not seems to support Load-Module as the debugger does not load edits. is that yours or theirs?

**Comment by SteveL-MSFT** [comment]
@justin-romano Thanks!  The second item also sounds like an issue in editorservices.
