### ISSUE TITLE
ConvertFrom-Csv multiline entries

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#6793]
CSV supports multiline entries with quoting escaping.
When a file is streamed as a collection of strings and not a single one, it will result in incorrect treating of such entries.

Steps to reproduce
------------------

 
1. create a `test.csv` file with the following content

```
a,b
"1
2
3",x
```

```powershell
cat ./test.csv | ConvertFrom-Csv
```

Expected behavior
-----------------

```none
a     b
-     -
1...  x
```

This is the output of `cat ./test.csv -Raw | ConvertFrom-Csv`

Actual behavior
---------------

```none
a b
- -
1 
2 
3 x
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.1
PSEdition                      Core
GitCommitId                    v6.1.0-preview.1
OS                             Darwin 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by BrucePay** [comment]
@vors So doing `Get-Content -Raw` works properly?

**Comment by mklement0** [comment]
@BrucePay: Yes, it does, given that a scalar multi-line string works too:

```powershell
@'
a,b
"1
2
3",x
'@ | ConvertFrom-Csv | Measure-Object
```

The above yields a count of `1`,  as expected.

**Comment by vors** [comment]
@BrucePay yes, as @mklement0 mentioned. But there should not be the semantical difference imo.

**Comment by aggieben** [comment]
Using `Get-Content -Raw` doesn't work in a particular circumstance where this problem is affecting me:

```
gc -wait postgresql-2020-02-10_182428.csv | ConvertFrom-Csv -Header $csvHeader -Delimiter ','
```

The `-Raw` flag on `Get-Content` cannot be used with `-Wait`.

**Comment by codeulike** [comment]
There are other sources of CSV data (apart from Get-Content) where this could be a problem.

e.g. I hit this bug using the Salesforce Command Line Interface:

For example this Salesforce CLI command:
`sf data query --query $soql --target-org $login  -r csv` 
.. emits CSV data, if there are line breaks in the CSV data then ConvertFrom-CSV is unable to handle it

I can work around it by piping to Out-String first and then into ConvertFrom-CSV

In general I suppose you can't handle this in ConvertFrom-CSV without some sort of 'read ahead if the CSV line seems incomplete' kind of feature
