### ISSUE TITLE
Extend support for the file-system recycle bin / trash

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#6801]
#6778 tracks porting the `Clear-RecycleBin` cmdlet to PowerShell Core, and it would be helpful to support other recycle-bin/trash-related functionality too, notably the ability to move filesystem items there.

Note:

* Windows calls the transient storage area for deleted-via-File Explorer files and folders the _recycle bin_. In the world of macOS and Linux, the same concept is known as the _trash_.  
As a real-world metaphor _trash_ makes more sense, because recovering an item from this storage area is not an act of _recycling_.  
The rest of this post uses the term _trash_, but it's worth creating _aliases_ so as to offer command and parameter names familiar on all supported platforms.

* In the Linux world, only distros with freedesktop.org-compliant desktop environments have a [standardized trash interface](https://specifications.freedesktop.org/trash-spec/trashspec-latest.html), most easily accessibly via CLIs, as shown in #6778.

### Support for moving (sending) filesystem items to the trash

[As suggested by @geelaw](https://github.com/PowerShell/PowerShell/issues/6743#issuecomment-385472864), we could add a `-ToRecycleBin` / `-ToTrash` switch to the FileSystem provider's implementation of the `Remove-Item` cmdlet.

@iSazonov suggests complementing the new switch with a _preference variable_ that sends items to the trash _by default_.  
The alternative is to use the generic `$PSDefaultParameterValues` mechanism:  
`$PSDefaultParameterValues['Remove-Item:ToTrash']=$True`

### Support for recovering items from the trash.

Programmatically recovering items from the trash is nontrivial and the question is whether _programmatic_ support for it is needed at all (say, via a `Recover-Item` cmdlet).

@geelaw's thoughts:

> One possible way for this is to let the cmdlet return a set of recycled items, where each item has an identifier (consistent across invocations but platform-dependent), date of removal, restoration path (sometimes might be unavailable) etc., and another cmdlet would restore items. I would suggest not having such cmdlets.

There's also the issue of feasibility - do all platforms have enough API / CLI support to support such a cmdlet? 
On Windows, we can use `(New-Object -ComObject Shell.Application).NameSpace(0xA).Items()`

### Support for opening the trash-folder GUI

Recovering items from the trash is typically done interactively, via the platform's file manager's GUI.

A cmdlet such as `Show-RecycleBin` / `Show-Trash` could facilitate that.

That said, perhaps such functionality doesn't add enough value to warrant implementation as a cmdlet, given that users can simply use the respective platform's GUI file manager and, as @geelaw points out, GUI-focused cmdlets are rare in PowerShell (and are typically only useful in command-line use).

Environment data
----------------

Written as of:

```powershell
PowerShell Core v6.0.2
```

**Comment by iSazonov** [comment]
What about a preference variable to set remove to trash by default without `-ToTrash`?

**Comment by mklement0** [comment]
@iSazonov: Good idea; I've added your suggestion to the OP, but note that we could get away with 
`$PSDefaultParameterValues['Remove-Item:ToTrash']=$True`

**Comment by GeeLaw** [comment]
@iSazonov I was about to post what @mklement0 said. Side-note: it seems that `PSDefaultParameterValues` is not hierarchical. For `VerbosePreference`, it is possible to set a local version of it without affecting outer-scoped preference. However, it is not the same with `PSDefaultParameterValues`.

It doesn't seem to worth adding a preference variable just for removing items in the file system -- existing preference variables are all *widely applicable* (whenever the advanced function/script has `CmdletBinding`, and further, whenever it `SupportsShouldProcess`).

**Comment by fowl2** [comment]
Various other PSDriveProviders have a "Trash" / soft delete concept - eg. AD, Exchange, SharePoint - but as with files the "restore" operation is much harder to generalise between providers.

`Restore-Item` (or is it `Undo-Item`?) does sounds fun though =]

**Comment by kilasuit** [comment]
Reopening use to linked issue

For Recycling I think we can add to Remove-Item a parameter`Recycle` (aliased as Trash) as opposed to `ToRecycleBin` or `ToTrash` as suggested in the op.

As for Restore-Item this would need more thought to complete but would be a good improvement if possible.

**Comment by doctordns** [comment]
I've been bitten badly by PowerShell's lack of support for the recycle bin over the years. I would very much support any mechanism to get PowerShell to use this. I would prefer to see ```Remove-Item``` use the recyclebin/trash by default. Perhaps a ```-deleteforreal``` parameter to nuke the files permanently. The default should be the safest and a parameter used to override.

**Comment by SteveL-MSFT** [comment]
The @PowerShell/wg-powershell-cmdlets discussed this.  Since we already have `Clear-RecycleBin` only for Windows, we would support adding a `-ToRecycleBin` parameter only for Windows to `Remove-Item`.
