### ISSUE TITLE
Do we need empty branch in Microsoft.PowerShell.Commands.ExportCsvHelper?

### ISSUE THREAD

**Issue by sethvs** [PowerShell/PowerShell#6809]
Do we need this check in Microsoft.PowerShell.Commands.ExportCsvHelper?

```powershell
        ExportCsvHelper(PSCmdlet cmdlet, char delimiter)
        {
            if (cmdlet == null)
            {
            }
            _cmdlet = cmdlet;
            _delimiter = delimiter;
        }
```
https://github.com/PowerShell/PowerShell/blob/84344cbb32ec5e2479e00394951832794bf37244/src/Microsoft.PowerShell.Commands.Utility/commands/utility/CSVCommands.cs#L880

**Comment by iSazonov** [comment]
@sethvs Please add a link to the code. 

The code should be removed.
