### ISSUE TITLE
MSI Installer Should Clean up Old Paths

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/PowerShell#6811]
I know that there will be a new approach that leaves the path the same - but it would be nice if the current package cleaned up the accumating path adds from version 6.0.0.

I could write the powershell to do it if @TravisEz13 wants to figure out how to call it as a custom action ;)

![image](https://user-images.githubusercontent.com/11597190/39574766-4d6e7608-4ea6-11e8-862d-f6dc193812a1.png)

**Comment by TravisEz13** [comment]
This is already fixed in 6.1.0-preview.2.  and will be fixed in the next release of 6.0.*

I think just a doc with a script to cleanup would be enough.

**Comment by DarwinJS** [comment]
An additional switch in the chocolatey package will allow the removal of all powershell core paths from machine and user scope before performing the next MSI install - hopefully the cleanest path forward.

> <#
> .SYNOPSIS
>   Idempotently removes extra PowerShell Core paths from the machine, user and/or process environment scope with no reordering.
> .DESCRIPTION
>   Defaults to machine scope and leaving the last sorted path alone.
> .PARAMETER PathScope
>   Set of machine scopes to clean up.  Valid options are Machine, User, Process.
> .PARAMETER RemoveAllOccurences
>   By default the cleanup leaves the highest sorted PowerShell Core path alone.  
>   This switch causes it to be cleaned up as well.
> .EXAMPLE
>   .\Reset-PWSHSystemPath.ps1
>   
>   Removes all PowerShell core paths but the very last one when sorted in ascending order from the Machine level path.
>   Good for running on systems that already has at least one valid PowerShell install.
> 
> .EXAMPLE
>   .\Reset-PWSHSystemPath.ps1 -RemoveAllOccurences
>   
>   Removes ALL PowerShell core paths from the Machine level path.
>   Good for running right before upgrading PowerShell install.
> .EXAMPLE
>   .\Reset-PWSHSystemPath.ps1 -PathScope Machine, User, Process
> 
>   Removes all paths but the very last one when sorted in ascending order.
>   Processes all path scopes including current process.
> .EXAMPLE
>   .\Reset-PWSHSystemPath.ps1 -PathScope Machine, User, Process -RemoveAllOccurencs
> 
>   Removes all paths but the very last one when sorted in ascending order.
>   Processes all path scopes including current process.
> #>

**Comment by DarwinJS** [comment]
@joeyaiello - what about putting this in the tools folder and people can download it or call it from the repo directly if they want it?

**Comment by TravisEz13** [comment]
@DarwinJS That sounds good.  Just create a subfolder.   Maybe `windows`, `msi` or something similar.   the root of the folder is getting crowded with unrelated tools.
