### ISSUE TITLE
Proper prerelease handling for install-powershell.sh and linux respositories

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/PowerShell#6815]
I updated the installer with a bug fix so that it would recognize preview releases and now it takes them by default.

I noticed that yum update now takes subsequent preview releases - but I'm uncertain whether that is because I already took a preview or if the yum repository is serving up the latest regardless of preview status.

As a consumer of both the installer-powershell.sh script and the Microsoft Linux repositories, I think opting into previews should be under the control of the installer and default to stable only.

I can foresee how that would mean a special switch on install-powershell.sh should be necessary, but I don't know if the repository is setup properly to serve only stable by default?

**Comment by TravisEz13** [comment]
The linux package should be renamed to `powershell-preview` for non-stable releases so people can choose if they want stable or preview.

**Comment by TravisEz13** [comment]
The issue is it shouldn't even be the same package in the first place.  You should have to opt-in to getting the preview releases.

**Comment by DarwinJS** [comment]
install-powershell.sh is not a package - it is a method for installing packages.  So I'm advocating that like package managers the script adopt the same approach of a switch which controls opt-in to prereleases.

I'm also trying to express that splitting into two scripts does not lessen development as the same logic to avoid or consume prerelease tagged packages must be built and used in both for anything that is not repo based.

So there does not seem to be speed of development nor simplicity benefits to splitting into two scripts.

**Comment by DarwinJS** [comment]
I have a follow up question - should prereleases be publish here - this is why the script finds them at all: https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/metadata.json

Should this be in a separate file for prereleases?

**Comment by DarwinJS** [comment]
It looks like the releases are not being properly tagged - so it will also be up to parsing to determine prerelease status:

![image](https://user-images.githubusercontent.com/11597190/39664413-e97f5c32-5050-11e8-885a-ea16e6498162.png)

**Comment by iSazonov** [comment]
I wonder too why we don't set the check box.

**Comment by markekraus** [comment]
It looks like it can be change retroactively. I'll defer the actual change to @TravisEz13 or @daxian-dbw as I'm not sure if changing it would break anything.

**Comment by TravisEz13** [comment]
@daxian-dbw  told me not to tag any release as pre-release.  I'm not sure why.

**Comment by TravisEz13** [comment]
|distro | problem | implementation |
|------|----------|----------------|
|debian| package | package Mgr |
|redhat| package | package Mgr |
|susue | script      | tar gz            |
|macos| working  | brew             |
|amazonlinux| script| tar gz     |

The problem is actually with our package where the script is using the inbox package manage. The issue is only in your script for two of the distros.  I would suggest just hard coding the latest stable version in those two scripts.  We should fix the package manager issues.

**Comment by DarwinJS** [comment]
Can anyone help with the statement so I can get one list of preview releases and one of product (based on presence or lack of "-" or characters) ?

I'm not sure how just regular sorting will work of those two lists - but I could work that part out.

**Comment by DarwinJS** [comment]
Looking for feedback on this code.  Only tested on CentOS.

FYI - I'm not trying to create a universal bash github version enumerator - so it may contain some assumptions - for instance that all prerelease identifiers sort with the most recent last in the case an overlapping version number is used between prereleases.

```
echo "All Versions"
curl https://api.github.com/repos/PowerShell/PowerShell/releases | grep -Po '"tag_name":(\d*?,|.*?[^\\]",)' | grep -Po '\d.\d[\da-z.-]*'

lastprodrelease=$(curl https://api.github.com/repos/PowerShell/PowerShell/releases | grep -Po '"tag_name":(\d*?,|.*?[^\\]",)' | grep -Po '\d.\d.\d[\da-z.-]*' | grep -v '[a-z]' | sort | tail -n1)

echo "Latest Regular Version: $lastprodrelease"

lastprerelease=$(curl https://api.github.com/repos/PowerShell/PowerShell/releases | grep -Po '"tag_name":(\d*?,|.*?[^\\]",)' | grep -Po '\d.\d.\d[\da-z.-]*' | grep '[a-z]' | sort | tail -n1)

echo "Latest Prerelease Version: $lastprerelease"
```

**Comment by DarwinJS** [comment]
#6405 seems to track the same thing.
