### ISSUE TITLE
Re-evaluate Pending and Skipped Web Cmdlets tests

### ISSUE THREAD

**Issue by markekraus** [PowerShell/PowerShell#6820]
Many of the Web Cmdlet tests that were marked pending and/or skipped in 6.0.0 were done so due to libcurl and environment difference in `HttpClient` across various platforms and distributions. Now that .NET Core 2.1 is merged and `HttpClient` no longer relies on libcurl or WinHTTP, these tests need to be evaluated to see if they can be tested across all platforms

**Comment by rkeithhill** [comment]
I like this adjective `sklipped`. It's a combination of skipped and slipped.  :-)

**Comment by markekraus** [comment]
I need to submit a PR to Pester to get it added....
