### ISSUE TITLE
Autocomplete list not showing

### ISSUE THREAD

**Issue by zeroxmxi** [PowerShell/PowerShell#6821]
<p>Powershell ISE in Elevated/non-elevated mode.</p>
<p>Intellisense worked but the autocomplete list does not show up.</p>
<p>See attached picture.</p>
<p>Surrounded in red rectangle, a dot appears to be the pixel draw of the autocomplete list but nothing shows up.</p>

<pre>
Name                           Value<br/>
----                           -----<br/>
PSVersion                      5.1.17134.1<br/>
PSEdition                      Desktop<br/>
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}<br/>
BuildVersion                   10.0.17134.1<br/>
CLRVersion                     4.0.30319.42000<br/>
WSManStackVersion              3.0<br/>
PSRemotingProtocolVersion      2.3<br/>
SerializationVersion           1.1.0.1<br/>
</pre>

![autocomplete-list-not-showing](https://user-images.githubusercontent.com/11497291/39611163-38cbe66c-4f88-11e8-959a-2468eb8c5208.png)

**Comment by iSazonov** [comment]
ISE is not in the repo. Please report on UserVoice.

**Comment by NJ-Dude** [comment]
This issue occurs in Win 10 after upgrading to version 1803 (April Upgrade)

**Comment by rahul-warhekar** [comment]
Same issue for me as well.

**Comment by mpack7225** [comment]
Same issue for me.
