### ISSUE TITLE
Invoke-Item /tmp fails on Debian with strange errors

### ISSUE THREAD

**Issue by iricigor** [PowerShell/PowerShell#6827]
Steps to reproduce
------------------

```powershell
Invoke-Item /tmp
```

Expected behavior
-----------------

Throw a PowerShell error (i.e. no default handler is available or similar).

The issue is not folder specific, i.e. it fails on any folder. It is tested on PS 6.1.0-preview.2 

The issue seems to be related to #4252 and #4262, but this is more to address proper error handling than to actually implement the functionality.

Actual behavior
---------------

It throws different errors from the underlying system.
On Debian Stretch, it throws full 9 line xdg-open error stack.
![screenshot_1](https://user-images.githubusercontent.com/15923171/39673167-52fe39f8-5137-11e8-840e-4ae95eb774d2.png)

On Debian subsystem on Windows 10, it throws 'No such file or directory' whereas folder exists. If a folder is really not existing, it throws 'Cannot find path'
![screenshot_2](https://user-images.githubusercontent.com/15923171/39673171-67f01c0a-5137-11e8-8aff-1225d471288b.png)

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by SteveL-MSFT** [comment]
@iricigor does this repro with 6.2-preview.4?  I tried this on macOS and it opened the /tmp folder just fine

**Comment by iricigor** [comment]
Hi @SteveL-MSFT, I cannot reproduce the problem on Ubuntu 16.04 VM with PowerShell 6.1.2, neither with 6.2.0-preview.3.  :relieved:

However, on Windows Subsystem Linux (WSL) problem persists on both distributions I have, Ubuntu 16.04 and Debian 9, with both latest official and preview versions of PowerShell. In all 4 cases, the error is the same as the above. Though, I am not even sure if that's supported scenario (pwsh running under Linux, but with Windows GUI).
