### ISSUE TITLE
Please use pre-release option in GitHub releases 

### ISSUE THREAD

**Issue by ghost** [PowerShell/PowerShell#6830]
<img width="30%" src="https://user-images.githubusercontent.com/33230602/38854373-ea235cc8-4228-11e8-9967-5306ba868ef9.png" />

Please mark prerelease as prerelease. This helps downstream in a build automation etc. when using GitHub APIs. For example currently `v6.1.0-preview.2` is showing up in https://api.github.com/repos/powershell/powershell/releases with `"prerelease": false`.

**Comment by iSazonov** [comment]
Was in #6815

**Comment by ThomasNieto** [comment]
@TravisEz13 / @iSazonov This doesn't seem to be an issue anymore. Can this issue be closed?
