### ISSUE TITLE
Import-Module : This command is not available in offline mode.

### ISSUE THREAD

**Issue by WilliamRyan** [PowerShell/PowerShell#6832]
PS C:\Program Files\PowerShell\6.0.2> Import-Module posh-gvm
Import-Module : This command is not available in offline mode.
At line:1 char:1
+ Import-Module posh-gvm
+ ~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (This command is...n offline mode.:String) [Import-Module], RuntimeException
+ FullyQualifiedErrorId : This command is not available in offline mode.,Microsoft.PowerShell.Commands.ImportModuleCommand

How to fix it?

**Comment by WindowsAdmin92** [comment]
@WilliamRyan 

Hi,

Just tested on PowerShell 6.0.2 and PowerShell 5.1. It looks like the module isn't working for Windows PowerShell or PowerShell Core. I also tried installing it via New-Object Net.WebClient. I was unable to install the module. I see that the owner did list an issue with an API call. He asked everyone to please update the module via Update-Module posh-gvm. Have you tried that?

Thanks,
Michael Levan

**Comment by WilliamRyan** [comment]
@WindowsAdmin92 
Hi, I had tried the update command, but it did not work.
The information likes this:
PS C:\Program Files\PowerShell\6.0.2> Update-Module posh-gvm
Update-Module : Module 'posh-gvm' was not installed by using Install-Module, so it cannot be updated.
At line:1 char:1
+ Update-Module posh-gvm
+ ~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (posh-gvm:String) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : ModuleNotInstalledUsingInstallModuleCmdlet,Update-Module

I will report the information to the owner
Thanks,
Ryan

**Comment by BrucePay** [comment]
This error is being generated by the `posh-gvm` module on module load. Please take a look at this [issue](https://github.com/flofreud/posh-gvm/issues/30).
