### ISSUE TITLE
Consuming external modules/cmdlets from binary modules

### ISSUE THREAD

**Issue by cskwrd** [PowerShell/PowerShell#6840]
Hey everyone,

Sorry for asking a question that isn't strictly related to the development of powershell itself, but I can't find an answer to this it.

How are we supposed to call cmdlets that are located in other modules or otherwise defined elsewhere?

To me it seems like I must create a new runspace and pass a string representing what I want to execute to it.

**Comment by BrucePay** [comment]
Hi @cskwrd I'm not sure I understand exactly what you're asking. The basic answer is to install the module if it isn't already installed, load the module (or let autoloading do it for you) then call the cmdlet. (But I'm guessing that's not the answer you're looking for.)

**Comment by cskwrd** [comment]
@BrucePay You're right, that isn't quite what I wish to do.

I have the following class in a binary module I am making.
```csharp
    [Cmdlet(VerbsDiagnostic.Test, "Widget")]
    public class TestWidgetCommand : PSCmdlet
    {
        protected override void ProcessRecord()
        {
            base.ProcessRecord();
            // I can do this to invoke other cmdlets defined in this binary module.
            var result = (new OtherCmdletFromMyModuleWrittenInCsharp()).Invoke();

            // here I would like to call something like 'Get-Member $result'
        }
    }
```

I hope the comments I have left in the code above help to further clarify my question.

More abstractly, I want to invoke a cmdlet that either exists (in script form instead of C#) as part of my module or external to my module (think system provided cmdlets, like `Get-Member`). If ` public class TestWidgetCommand : PSCmdlet { ... }` were written as `function Restore-Database { ... }`, the answer would be to just call `Get-Member $result` in the body of the function, but I am working in C# and can't do that.

Must I do some thing like this: [Runpool PowerShell Example](https://code.msdn.microsoft.com/PowerShell-Sample-02-affe8453/sourcecode?fileId=70908&pathId=720601728) (see the string script variable)

**Comment by BrucePay** [comment]
@cskwrd You do have to use the `PowerShell` API to call other commands from C# but you don't need to create new runspaces. Instead, use `PowerShell.Create(RunspaceMode.CurrentRunspace)` to create the `PowerShell` instance (this is assuming that you don't want to do asynchronous stuff). That way, you'll have access to the current session. So
```csharp
var myPowerShellInstance = PowerShell.Create(RunspaceMode.CurrentRunspace).
    AddCommand("OtherCmdletFromMyModuleWrittenInCsharp");
Collection<PSObject> result = myPowerShellInstance.Invoke();
```
Then to call `Get-Member` with the results,
```csharp 
var mySecondPowerShellInstance = PowerShell.Create(RunspaceMode.CurrentRunspace).
    AddCommand("Get-Member");
Collection<PSObject> result2 = mySecondPowerShellInstance.Invoke(result1);
```
(Note:  WRT getting members, the `Invoke()` method returns `Collection<PSObject>` and  `PSObject` has a property `Members` which is essentially what `Get-Member` returns.)

Or you can do it all in one pipeline
```csharp
 var myPowerShellInstance = PowerShell.Create(RunspaceMode.CurrentRunspace).
    AddCommand("OtherCmdletFromMyModuleWrittenInCsharp").
         AddCommand("Get-Member");
Collection<PSObject> result = myPowerShellInstance.Invoke();
```
And remember to dispose your `PowerShell` instances. Also, you can reuse a `PowerShell` instance by calling `myPowerShellInstance.Commands.Clear()` which removes the commands from the pipeline.

**Comment by cskwrd** [comment]
@BrucePay Thanks for the info! This is what I needed.
