### ISSUE TITLE
ValidateSet for optional parameters.

### ISSUE THREAD

**Issue by LethiferousMoose** [PowerShell/PowerShell#6841]
I was attempting to validate an optional parameter, but I realized that also more or less makes it mandatory, because now it is forced to have a value. So I attempted to use empty string as a valid possibility, but that also has issues.

So I have two issues here:
1) If a parameter is not mandatory, why is validate set running when the parameter is not supplied, does it look the same as passing in a null value and therefore cannot be determined if it is absent?
2) If empty string is a valid value in ValidateSet, then I expect tab completion to work. This would also be fine on mandatory parameters if AllowEmpyString or AllowNull are also provided.

Steps to reproduce
------------------

```powershell
param([ValidateSet('', "Test")]
          [string] $Param)
```

Expected behavior
-----------------

```none
Empty string should either show up in tab completion OR tab completion should ignore it, display all non-empty values, and allow the parameter to be left out (i.e. empty).
```

Actual behavior
---------------

```none
Tab completion does NOT work at all when empty string is provided as a valid value. Note: that the set validation DOES work fine, i.e. I can still only provide empty string or "Test" as values and all other values error, but the empty string breaks tab completion. This seems like very confusing behavior, if it works I would expect tab completion, if it is not supported I would expect it error or get ignored all together.
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.2
PSEdition                      Core
GitCommitId                    v6.1.0-preview.2
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
> If a parameter is not mandatory, why is validate set running when the parameter is not supplied, 

If you simply _omit_ the parameter, no validation is performed. Do you mean something else by "not supplied"?

> If empty string is a valid value in ValidateSet, then I expect tab completion to work

Yes, that cycling through valid values stops working if you tab-complete without having typed at least one characters is unexpected.

**Comment by LethiferousMoose** [comment]
Hm... Well I just tested it again and now I am not seeing what I saw before. I can close this as it does appear to work as I wanted it to.

**Comment by vivekgite** [comment]
@Tim Biggin 
I am facing similar issue,Can you help us with the solution that you've tried to resolve this issue?
Thanks

**Comment by vexx32** [comment]
@vivekgite what's the issue you're seeing?

In general terms, if you _don't_ mark a parameter as mandatory, and you also apply a ValidateSet, the validation is only performed if and when the parameter is supplied.

**Comment by LethiferousMoose** [comment]
@vivekgite I didn't really have a solution, the problem just went away when I went to test it again.
