### ISSUE TITLE
PowerShell Core doesn't inherit PSModulePath environment variable from the environment

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#6850]
Windows PowerShell **correctly** inherits environment variables from the environment -- although it may **add** paths to these variables, it doesn't ignore the existing environment.

PowerShell Core sets the PSModulePath -- completely ignoring **and overwriting** the existing environment, **including** the default values set in the Windows System Properties control panel...

This makes PowerShell Core's PSModulepath basically impossible to **manage**, since it can only be set reliably in a machine profile script --which depend on the _install location_ of the shell, which changes with each release!!

Steps to reproduce
------------------

From Windows PowerShell run:
```powershell
$Env:PSModulePath
pwsh -noprofile -command { $Env:PSModulePath }
pwsh -noprofile -command { powershell -noprofile -command { $Env:PSModulePath } }
```

From `pwsh` run:
```powershell
$Env:PSModulePath
PowerShell -noprofile -command { $Env:PSModulePath }
```

Expected behavior
-----------------

pwsh should respect it's environment.

Actual behavior
---------------

pwsh overwrites it's environment

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by Jaykul** [comment]
yes, but that code is based on the incorrect (or rather, outdated) assumptions that "The machine-wide and user-wide environment variables are only meaningful for full ps"

First of all, since PowerShell itself *does not set* those environment variables, there is **no basis** for this assumption. These are environment variables under the control of the user. You have no right to ignore them.

Second, as noted on [#2636](https://github.com/PowerShell/PowerShell/issues/2636#issuecomment-322342900), many of the core modules _do_ work. You've even released [a module](https://www.powershellgallery.com/packages/WindowsPSModulePath) predicated on the fact that this is, in fact, **not true** 😉 

We can't on the one hand _say_ that many (or most) modules will just work, and on the other hand say that the environment variable is _so toxic_ that we can't trust users (and enterprises) to deal with it properly.

**Comment by BrucePay** [comment]
Maybe we should have another environment variable  `$ENV:PSModulePathCore`. On startup, if PowerShell Core sees this variable, it uses it otherwise it falls back to `$ENV:PSModulePath`. With two variables, then `powershell` can call `pwsh` and `pwsh` can call `powershell` and everything works. And eventually we can create a `PowerShellCommon` module directory for modules that work with both and that both variables include.

**Comment by Jaykul** [comment]
A separate `$Env:PSCoreModulePath` environment variable kind-of makes sense.

However, there are probably a lot of scripts and modules using `$Env:PSModulePath` ... I mean, at a minimum, people's profiles, and modules like [PSDepend](/RamblingCookieMonster/PSDepend/)

Could we rely on the modules themselves setting `CompatiblePSEditions`, and let each version of PowerShell ignore modules that aren't compatible?

**Comment by BrucePay** [comment]
>  I mean, at a minimum, people's profiles

There are different profiles for desktop and core. You have to expend effort to get them to share common code and work properly. (e.g. no loading `winform` assemblies in your Core profile). So you put edition-specific tweaks in the appropriate profile.

> However, there are probably a lot of scripts and modules using $Env:PSModulePath

Most scripts and modules depend on the module path being set correctly for the PS edition they are using. With separate variables, by default they will only load modules from the module directories associated with their shell edition. For things that work directly with PSModulePath, they'll have to be updated to understand PowerShell Core.

> Could we rely on the modules themselves setting CompatiblePSEditions, and let each version of PowerShell ignore modules that aren't compatible?

Without separate 'edition' directories, how do I have both "core" and "desktop" install paths for a given module/version?  (Nuget does this with `<package>/<version>/lib/<editionEquivalent>` but that would require changing both Core and Windows Powershell so it is unlikely to happen.)

> Bear in mind that in the near future, the more frustrating problem is Windows PowerShell. As new modules come out which take advantage of PowerShell Core functionality, Windows PowerShell won't be able to use them, and it does inherit the environment variable, already.

All the more reason to have separate module paths. I should be able to do
```
powershell {
    Get-ADComputer ...
}
```
from `pwsh.exe` and it should just work.

**Comment by kilasuit** [comment]
Separate env vars doesn't make sense to me

but neither was the decision to overwrite the existing 1 on pwsh loading, although I can understand WHY it happened, it doesn't mean I agree that the decision was the right course of action either back then or now going forward.

I'd personally opt for reverting the explicit code that changed this as IMO this wasn't an ideal change to make 

Otherwise you'd need to change pwsh and a number of other tools, like PowerShellGet to have more unneeded points of complexity where reverting this would in my opinion make much more sense going forward

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and agrees that this issue warrants an RFC.  @BrucePay has offered to author the RFC.

**Comment by SteveL-MSFT** [comment]
I believe @BrucePay still plans to author this

**Comment by BrucePay** [comment]
@SteveL-MSFT @joeyaiello The existing RFC PR is here: https://github.com/PowerShell/PowerShell-RFC/pull/133 Perhaps we can discuss this in the next committee RFC meeting on Monday.

**Comment by TheIncorrigible1** [comment]
Any update to where this is at?  Just re-installed pwsh on a machine and it clobbered my psmodulepath for *Windows* powershell which broke psreadline - immediately noticeable.

**Comment by marcinsmialek** [comment]
While this isn't the solution to this problem, this may be a handy workaround, at least it's how I deal wit this issue right now:
From PowerShell Core:
1. Install it with remoting / enable remoting
2. Install-Module WindowsCompatibility
3. Import-WinModule LegacyModule
4. Run commands from the LegacyModule shim

**Comment by iSazonov** [comment]
#10300 is pulled to resolve the issue and others based on PowerShell Committee conclusion.

**Comment by MarcoPeraza** [comment]
This is broken again, at least on insider builds and latest versions of pwsh.

**Comment by bedesv** [comment]
I'm getting this issue with Get-FileHash on Powershell Core v7.4.2.
![image](https://github.com/PowerShell/PowerShell/assets/5328041/2db9fb93-cc1e-4e96-bf0f-1deaa4368d4b)

Line causing the error:
`powershell -c "foreach ($file in Get-ChildItem '%TARGET_LOCATION%') { Get-FileHash -Algorithm MD5 $file.FullName }"`

```
Get-FileHash : The term 'Get-FileHash' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:68
+ ... Get-ChildItem 'C:\temp' -Filter enabler-*.zip) { Get-FileHash -Algori ...
+                                                      ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-FileHash:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
