### ISSUE TITLE
Allow Measure-Object to accept ad-hoc script-block arguments in lieu of property names

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#6855]
<sup>This issue arose out of #6837.</sup>

Motivation:

`Sort-Object`'s `-Property` not only supports property _names_ (the typical case), but also _script blocks_ that are evaluated for each input object and thereby enable sorting criteria _derived_ from properties, which is a powerful feature (also found, in essence, in `Select-Object`); e.g.:

```powershell
# Sort by only the numerical part of the input, via a script-block parameter argument.
PS> 'z1', 'a0', 'b10' | Sort-Object -Property { [int] $_.Substring(1) }
a0
z1
b10
```

Suggestion:

It would be handy if `Measure-Object` supported analogous use; e.g.:

```powershell
# Count the  odd numbers in the input.
PS> 1, 2, 3 | Measure-Object -Sum -Property { $_ % 2 }  # wishful thinking
2
```

To that end:

* The `-Property` parameter's data type would have to change from`[string[]]` to `[object[]]`
* In the event of a script block getting passed, it would have to be evaluated for each input object and used in lieu of a simple property access on the input object.

Environment data
----------------

Written as of:

```powershell
PowerShell Core v6.0.2
```

**Comment by BrucePay** [comment]
It's actually just a 3-line change with Property going from [string[]] to [MshExpression[]]. The downside is that MshExpression is an internal (and unfortunately named) class. So about 30 files need to be changed to do this properly (rename MshExpression -> PSPropertyExpression and make it public.)

**Comment by mklement0** [comment]
Thanks, @BrucePay, but wouldn't changing the type to `[object[]]` do, accompanied by internal logic to see if the object passed is either a `[scriptblock]` or `[string]` (or something that can be coerced to a string)?

That's how `Sort-Object` seems to do it.

**Comment by mklement0** [comment]
Thanks, @BrucePay. 

My point was that if `Sort-Object` types its `-Property` parameter `[object[]]` _publicly_ and uses `[MshExpression]` _internally_, can't `Measure-Object` do the same, thereby saving us from having to make [a renamed] `[MshExpression]`  public?

**Comment by mklement0** [comment]
That's good to hear, @SteveL-MSFT.

We should consider doing the same thing not only for `Sort-Object`, but also for `Select-Object`.

Note, however, that additional considerations apply, because **both commands accept a _hashtable_ in addition to a script block**:

* `Sort-Object` only requires a hashtable if you want to reverse the sort direction on a per property/expression basis:

```powershell
PS> 'z1', 'a0', 'b10' | Sort-Object -Property @{ Descending=$True; Expression = { [int] $_.Substring(1) }
b10
z1
a0
```

* In the case of `Select-Object` use of a hashtable is actually the _typical_ case, because in the absence of a _name_ for the property created by the script block the script block's literal string contents becomes the name:

```powershell
# With just a script block, the resulting property name is the *expression source code*:
PS> 1 | Select-Object { $_ * 10 }

 $_ * 10
---------
       10

# Typical case: provide a hashtable wrapper for the expression that names the property:
PS> 1 | Select-Object @{ Name='TimesTen'; Expression = { $_ * 10 } }

TimesTen
--------
      10

```

**Comment by mklement0** [comment]
... and `ConvertTo-Html` - see #6994
