### ISSUE TITLE
Modulo operator does not work as expected with decimals

### ISSUE THREAD

**Issue by hksky** [PowerShell/PowerShell#6860]
Steps to reproduce
------------------
1 % 0.2

Expected behavior
-----------------

1 % 0.2 = 0

Actual behavior
---------------
1 % 0.2 = 0.2
Environment data
----------------

```powershell
> $PSVersionTable  5.1.14393.2189

```
Also able to repro in 6.0.2

**Comment by WindowsAdmin92** [comment]
Try using the decimal type

[decimal]1 % 0.1 = 0.0

[decimal]1 % 0.8 = 0.2

[decimal]1 % 0.9 = 0.1

**Comment by BrucePay** [comment]
In arithmetic operations, PowerShell converts the operands to the most accurate type. So the type of the operation `1 % 0.2` is `[double]` and the type of `[decimal] 1 % 2` (which could more easily be written as `1d % 0.2`) is `[decimal]`. Once the type is established, PowerShell uses the underlying .NET framework APIs to perform the operation e.g. [System.Decimal.Modulus](https://docs.microsoft.com/en-us/dotnet/api/system.decimal.op_modulus?view=netframework-4.7.1#System_Decimal_op_Modulus_System_Decimal_System_Decimal_).

**Comment by mklement0** [comment]
@hksky: In light of the comments above:

_Why_ do you expect 

```powershell
1 % 0.2 
```

 to yield `0` (whether typed `[double]` or `[decimal]`)?

**Comment by hksky** [comment]
@mklement0 expectation was to receive
0.0 or 0
because 5 % .5 yields 0 and several other Modulo operations with decimal  do yield the expected result.

I do understand the explanation and appreciate the response from @BrucePay  which makes sense and we could mark this as working correctly as per the developer but not for the end user.
