### ISSUE TITLE
Consider introducing a `ValueFromPipelineByScriptBlock` attribute to signal support for ad-hoc script-block arguments

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#6861]
#6837 discussed making [ad-hoc script-block arguments](https://github.com/PowerShell/PowerShell-Docs/issues/2338) an _implicit_ feature of cmdlets / advanced functions rather than requiring explicit per-parameter opt-in via attributes.

It looks like this won't happen, but there is room for improving the existing opt-in mechanism:

**tl;dr:**

Introduce a `ValueFromPipelineByScriptBock` attribute to _directly_ mark a parameter as supporting ad-hoc script-block arguments.

---

Currently, in order to signal that a given parameter should accept an ad-hoc script block (e.g., `Rename-Item`'s `-NewName` parameter in invocations such as  
`Get-ChildItem ... | Rename-Item -NewName { $_.BaseName + ... }`, 
it must be decorated with either `ValueFromPipeline` or, more typically, with `ValueFromPipelineByPropertyName` (which is the case for `-NewName`).

However, the primary purpose of `ValueFromPipelineByPropertyName` is to enable binding via _objects from the pipeline_ that _have a property by that name_.

In the case of `Rename-Item`'s `-NewName`  parameter that would mean something like:

```powershell
[pscustomobject] @{ NewName = 'bar.txt' } | Rename-Item -LiteralPath foo.txt
```

which is unlikely to be useful in the real world.

Thus, it is conceptually awkward to have to signal support for ad-hoc script-block arguments via  `ValueFromPipelineByPropertyName`:

 * You have to express your intent _indirectly_, via an attribute designed for a _different_ purpose.
 * Support for that different purpose is likely unnecessary.

Introduction of a `ValueFromPipelineByScriptBock` attribute would solve these problems.

The only down-side is that for backward compatibility `ValueFromPipelineByPropertyName` would have to continue to _imply_ `ValueFromPipelineByScriptBlock`, so users would have to examine parameters for _either_ attribute in order to determine ad-hoc script-block argument support.

Environment data
----------------

Written as of:

```powershell
PowerShell Core v6.0.2
```

**Comment by lzybkr** [comment]
I don't see this attribute getting much use. It would reduce the portability of a command for almost no benefit.

I *think* your proposed semantics are:

* Value from the pipeline **only** via script block binding, not by name or value.

I see little (no?) harm in allowing binding by name or value to also support script block binding.

**Comment by mklement0** [comment]
@lzybkr:

> It would reduce the portability of a command 

What do you mean by portability in this context?

> for almost no benefit.

The benefit is semantic directness: to have an attribute that expresses the intended functionality.

The ad-hoc script-block argument feature is currently virtually unknown for two reasons:

* lack of documentation - see https://github.com/PowerShell/PowerShell-Docs/issues/2338

* the absence of a dedicated attribute that signals support for it (which means you can't even _stumble upon_ the feature) - see https://github.com/PowerShell/PowerShell-Docs/issues/2427

> I _think_ your proposed semantics are:
>  * Value from the pipeline **only** via script block binding, not by name or value.

Yes, and that is arguably _all_ that you want for script-block binding: binding of a parameter via a value _derived_ from the objects in the pipeline (themselves bound to a _different_ parameter;  see the `-NewName` example above).

> I see little (no?) harm in allowing binding by name or value to also support script block binding.

That's fine - and won't go away with the proposed new attribute.

But the _coupling_ with the ad-hoc script-block argument feature is neither obvious nor necessary, hence my suggestion to introduce a dedicated attribute.

If you think that introducing a new attribute is not worth the trouble, then we should at least make sure that the coupling is clearly documented for the `ValueFromPipeline*` attributes (which I've already asked for via the linked docs issues).

**Comment by mklement0** [comment]
@lzybkr: 

Good points, especially re targeting Windows PowerShell.

I guess documenting the existing attributes (and the feature in general) properly is the way to go, so I'm closing this.

**Comment by MaximoTrinidad** [comment]
Key sentences:
"Portability - commands targeting Windows PowerShell in addition to PowerShell Core." and
"Good points, especially re targeting Windows PowerShell."

We all know, all work efforts and concentration will only target PowerShell Core(not Windows PowerShell).  

So, if this is needed in Windows PowerShell then create the UserVoice issue for it. This way it will be taken care of.

:)

**Comment by mklement0** [comment]
@MaximoTrinidad:

Now that we've decided not to add to Core, how would adding it to Windows PowerShell help?

**Comment by mklement0** [comment]
@MaximoTrinidad:

Ore are you saying that we generally shouldn't worry about whether changes to PowerShell Core prevent code based on these changes from running on Windows PowerShell and older versions of it?

**Comment by MaximoTrinidad** [comment]
@mklement0,

Yes! It won't hurt to have the changes moving forward to Core.  Looks interesting!
