### ISSUE TITLE
AMSI not uninitialized when pwsh is not crossgen'd and the window hosting pwsh (directly or indirectly) gets closed (on Windows)

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#6862]
This is either a bug or a `Debug.Assert` call needs to be reviewed. The `VerifyAmsiUninitializeCalled` method that is called [here](https://github.com/PowerShell/PowerShell/blob/80951777cfde34e9d527dedd833f90cc715ad684/src/System.Management.Automation/security/SecuritySupport.cs#L1635) has a `Debug.Assert` violation in the following scenario:
- Debug build (because `Debug.Assert` is only enabled in Debug)
- The `-CrossGen` option on `Start-PSBuild` is not used
- The ConsoleHost gets closed by the window that is hosting pwsh (can be directly or indirectly, i.e. nested) via the Windows UI (Close button on the window itself or the taskbar) but not via typing `exit`

Steps to reproduce
------------------

```powershell
git clone https://github.com/PowerShell/PowerShell.git PowerShellReproIssue6862
cd .\PowerShellReproIssue6862
Import-Module .\build.psm1
Start-PSBootStrap
Start-PSBuild
Invoke-Item "$pwd/src\powershell-win-core\bin\Debug\netcoreapp2.1\win7-x64\publish\pwsh.exe"
# Then close the window via the `X` button or the `Close` option on the taskbar
```

Expected behavior
-----------------

The window closes normally.

Actual behavior
---------------

Debug.Assert failure [here](https://github.com/PowerShell/PowerShell/blob/80951777cfde34e9d527dedd833f90cc715ad684/src/System.Management.Automation/security/SecuritySupport.cs#L1711)
![image](https://user-images.githubusercontent.com/9250262/39972339-00255166-5705-11e8-8b13-a808f7a5b823.png)

Environment data
----------------

(Latest state of master)

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta.3
PSEdition                      Core
GitCommitId                    v6.0.0-beta.3-1131-gd07a3e7c2faf3f3489ae80e17cb2f02533c392e6
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by PaulHigin** [comment]
Thanks.  I'll take a look sometime this week.

**Comment by PaulHigin** [comment]
When PowerShell is closed via the console (clicking on window [x]) there is a race condition between PowerShell runspace clean up, the appdomain callback for the AMSI uninit assert check, and the process terminating.  I don't believe this code was intended to work for this case, but instead is for the case where PowerShell exits cleanly from the command line (by typing 'exit').

I believe the assert is useful for the cleanly exiting case so it would be good to keep it.  It is interesting that we are seeing the assert for the "Invoke-Item" case, when in most other cases the process terminates before the assert can be displayed.

**Comment by bergmeister** [comment]
Thanks for the info. The fact that the assertion failure does not happen when using the `-CrossGen` switch confirms to me as well that it is a race condition as some code is faster. I guess there could also be scenarios on different hardware where this happens even when using `-CrossGen`. We should maybe eat more dog food that is compiled in Debug to uncover such cases.

**Comment by bergmeister** [comment]
Note that I still see this happening with the latest changes in master but the likelihood seems to have decreased a bit.

**Comment by iSazonov** [comment]
Continues to annoy.

**Comment by PaulHigin** [comment]
I agree.  I am beginning to use PSCore6 more than Windows PowerShell and it is very annoying.  I think the assert should be removed.  I'll check with the AMSI folks and see if it is Ok to ignore the un-initialize on process exit.

**Comment by SteveL-MSFT** [comment]
We discussed this briefly this morning and agree that @PaulHigin will submit PR to remove this assert as it's no longer providing value

**Comment by PaulHigin** [comment]
I have submitted a PR (#8713).

**Comment by bergmeister** [comment]
@PaulHigin One can use [closing keywords](https://help.github.com/articles/closing-issues-using-keywords/) in the PR (e.g `Fixes #REPLACE_WITH_ISSUE_NUMBER`), then the issue gets closed automatically when the PR gets merged. It is not important in this case but useful in general where people track issues.
