### ISSUE TITLE
Update Linux installation doc during 6.1.0-preview.3 release

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#6867]
Packaging script has been updated to produce Ubuntu 17.10 package, and there are EOL Linux distros that we will no longer support, so we need to update the Linux installation doc during the next release, when we publish the Ubuntu 17.10 package.

Related comments: https://github.com/PowerShell/PowerShell/pull/6859#discussion_r187771647

**Comment by rjmholt** [comment]
.deb file repo URLs will need to be updated.

I think the only one in need of updating it [here](https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md#ubuntu-1704): the URL for the .deb file is `https://packages.microsoft.com/config/ubuntu/17.04/prod.list`, but the new .deb file should be at `https://packages.microsoft.com/config/ubuntu/17.10/prod.list`.

Debian will also have this problem when they increment version, as our URLs reference the release name (e.g. "Jessie").

OpenSUSE, CentOS and Fedora all seem to use our RHEL RPM repo, whose URLs reference the RHEL version.

**Comment by TravisEz13** [comment]
Docs are up:  https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-powershell-core-on-linux?view=powershell-6#ubuntu-1710
