### ISSUE TITLE
Send-MailMessage names attachment using full path and name on Linux

### ISSUE THREAD

**Issue by ZizzyZizzy** [PowerShell/PowerShell#6878]
When emailing files using Send-MailMessage, they show up named with the full path to the file + filename instead of just the short file name.

I've attempted changing the current working directory to the location where the attachment lives, then stripping off the path, but then Send-MailMessage complains that it can't find the file because it's looking in the folder where the script lives.

This is also a security risk. Not only does it expose that the system is Linux, it exposes the full path to the file. 

Steps to reproduce
------------------
    $MasterCSVFile = "/some/path/to/MasterCSV_List.csv"
    $MessageBody =  "All VM's for vCenter $servername"
    $MessageBody += $VMSortedMasterList | format-table -AutoSize | out-string
    $MessageBody  =  '<pre>{0}</pre>' -f [System.Net.WebUtility]::HtmlEncode($MessageBody)
    $MessageSubject = "VM List for vCenter " + $servername

    $messageParameters = @{
        Body = $MessageBody
        Subject = $MessageSubject
        From = $FromEmail
        To = $ToEmail
        SmtpServer = $SMTPServer
        Attachments = $MasterCSVFile
    }

        Send-MailMessage @messageParameters -BodyAsHtml

Expected behavior
-----------------

Attachment should be named "**MasterCSV_List.csv**"

Actual behavior
---------------

Attachment is named "**/some/path/to/MasterCSV_List.csv**" and will not open in Gmail's preview like it does using an attached CSV file from a Windows PowerShell session.

Environment data
----------------
```

PS /root/powershell> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.2
PSEdition                      Core
GitCommitId                    v6.1.0-preview.2
OS                             Linux 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


RPM:
Name        : powershell
Version     : 6.1.0~preview.2
Release     : 1.rhel.7
Architecture: x86_64
Install Date: Tue 15 May 2018 02:15:56 PM EDT
Group       : shells
Size        : 141014973
License     : MIT License
Signature   : RSA/SHA256, Thu 26 Apr 2018 05:01:23 PM EDT, Key ID eb3e94adbe1229cf
Source RPM  : powershell-6.1.0~preview.2-1.rhel.7.src.rpm
Build Date  : Wed 25 Apr 2018 01:59:52 PM ED

```

Here is what shows up in the email header:

```
----boundary_0_5c9a4c9c-1387-4d6e-8d4a-7a8c31a3479a
Content-Type: application/octet-stream; name=""/some/path/to/MasterCSV_List.csv"
Content-Transfer-Encoding: base64
Content-Disposition: attachment
```

**Comment by kvprasoon** [comment]
My observation is slightly different .
Attachment is having the absolute path of the file without the path separator.
If attachment path is `/mnt/c/test.log`, in mail the attachment name is `mntctest.log`


![image](https://user-images.githubusercontent.com/12897753/40324485-414d45b6-5d56-11e8-9c87-23c91f936178.png)

**Comment by kvprasoon** [comment]
@iSazonov  I have tried with `System.Net.Mail` APIs and found the same issue, So the issue is in .Net Core.

**Comment by iSazonov** [comment]
@kvprasoon Thanks!
The issue is dup #6564. Fix is already in .Net Core 2.1. So we can test with current night builds or wait Preview3.

**Comment by kvprasoon** [comment]
@iSazonov Yes, but I tried with latest nightly build with latest .Net preview following [this](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.0-preview2-download.md ) link and was a repro.

**Comment by iSazonov** [comment]
@kvprasoon Today we compile with .Net Core 2.1 RC1 Final not Preview2

**Comment by SteveL-MSFT** [comment]
I believe this is fixed with latest corefx.  Reply if not and we can reopen.
