### ISSUE TITLE
Progress bar with user inputs,  verbose or write-output sometimes interfered each other

### ISSUE THREAD

**Issue by jianyunt** [PowerShell/PowerShell#6880]
Try the following sample, press any key, let's say aaaaaaaa, you will see the progress bar moves to right while you are typing. This happens on Linux or Azure cloudshell.
 ``` Powershell
 1..100 | foreach{write-progress -id 1 -activity foobar -status busy -percentcomplete $_; sleep 1}
```
should we turn off echo (stty -echo) before executing the cmdlet and turn it back on after completing the execution?

Steps to reproduce
------------------
Run the above sample on Linux
or
In Azure cloudshell bash + pwsh
Get-AzureRMWebApp and then press any key

```powershell

```

Expected behavior
-----------------

User inputs or write-output should not interference with progress bar position.

Actual behavior
---------------

The progress bar position changes based on user input.  It impacts the verbose message start position too while running install-module.

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Linux 4.4.0-124-generic #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

cc @BrucePay

**Comment by jianyunt** [comment]
@BrucePay I no longer can repro after applied your fix for  the particular repro case: 
``` PowerShell
1..100 | foreach{write-progress -id 1 -activity foobar -status busy -percentcomplete $_; sleep 1}
```

But the gaps issue still exist which may or may not related to the write-progress. I will try to investigate it.
After the Azure drive appears, get `<tab`> which will start showing progress bar. After that, a big space gap appears. This issue is manifested in the PSReadline 2.0 beta version only.

![image](https://user-images.githubusercontent.com/10171679/40932608-c57ab58e-67e3-11e8-9c96-f9ef448d401c.png)

**Comment by ocitrev** [comment]
This happens not only on Linux
Easy to repro on Windows:

```ps1
0..100 | %{ Write-Progress 'Wait' -Percent ($_); sleep -ms 10; if ($_ -eq 42) { cmd /c help } }
```
