### ISSUE TITLE
Can't install on Linux mint

### ISSUE THREAD

**Issue by WattanaGaming** [PowerShell/PowerShell#6885]
One dependency installable(liblttng-ust0) and one not installable(libicu57)
Any fix?

**Comment by rjmholt** [comment]
Hi @WattanaGaming, would you be able to give some details about the OS/platform you're running?

Maybe the output of:
```
cat /etc/os-release
```
and
```
uname -a
```

**Comment by WattanaGaming** [comment]
Im using Linux mint 18.3 Sylvia

**Comment by iSazonov** [comment]
>not installable(libicu57

It is Mint community issue - we can not compile and distribute the library.
