### ISSUE TITLE
No stable release of docker image based on microsoft/nanoserver:1803

### ISSUE THREAD

**Issue by jnm2** [PowerShell/PowerShell#6905]
The latest stable image for Nano Server is [`6.0.2-nanoserver-1709`](https://hub.docker.com/r/microsoft/powershell/). Is 6.0.2 in the works for 1803?

(Looks like a matter of bumping a couple things in [https://github.com/PowerShell/PowerShell/blob/master/docker/release/nanoserver/Dockerfile](https://github.com/PowerShell/PowerShell/blob/master/docker/release/nanoserver/Dockerfile)?)

**Comment by TravisEz13** [comment]
@jnm2 It can take several days to get the server working as our scripts to set up a build machine is intended for a server with the desktop experience and 1709/1803 are not available with the desktop experience.

**Comment by TravisEz13** [comment]
I have a build server ready and I'm making changes to the official build to build for both 1709 and 1803.

**Comment by TravisEz13** [comment]
done `docker run -it mcr.microsoft.com/powershell:6.0.2-nanoserver-1803`
I created the `nanoserver` tag but there is an issue getting it to work on the mcr.microsoft.com preview.  you have to use `docker run -it microsoft/powershell:nanoserver` 

Hopefully it will be resolved soon

**Comment by jnm2** [comment]
Up and running with it! Thank you for your speedy response!
