### ISSUE TITLE
PSReadLine reports access denied

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#6906]
The problem is in WSL, PowerShell Core 6.1.0 Preview1

```
Error reading or writing history file '/home/sie/.local/share/powershell/PSReadLine/ConsoleHost_history.txt': Access to the path '/home/sie/.local/share/powershell/PSReadLine/ConsoleHost_history.txt' is denied.
```

![pwsh_hist_err](https://user-images.githubusercontent.com/22290914/40290088-78753c34-5cab-11e8-83fe-b445250ce5af.png)

**Comment by MaximoTrinidad** [comment]
Is it possible to get the steps to reproduce this error in WSL?

So, I'm assuming that you are executing:
```
## - Return False:
[system.io.directory]::Exist("/mount/c/Temp")

## - Return True:
[system.io.directory]::Exist("/mnt/c/Temp")
```

Using latest PowerShell Core Version I can't repo the issue:
```
PS /home/maxt> $PSVersionTable                                                                                           
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.2
PSEdition                      Core
GitCommitId                    v6.1.0-preview.2
OS                             Linux 4.4.0-17672-Microsoft #1000-Microsoft Fri May 11 14:45:00 PST 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS /home/maxt> cat /etc/lsb-release                                                                                      DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
```
![wsl_preview 2_2018-05-21_12-50-03](https://user-images.githubusercontent.com/19892435/40319424-1f64e41e-5cf6-11e8-9a89-506059e50364.jpg)

**Comment by iSazonov** [comment]
I get the error some times and don't understand how and why.

**Comment by MaximoTrinidad** [comment]
Is it maybe something to do with the Windows Build?  I'm on Microsoft Windows [Version 10.0.17672.1000].
:)

**Comment by iSazonov** [comment]
I see this on 1803 ans saw this before update to 1803.

**Comment by MariusVolkhart** [comment]
I have this same output when I run powershell on linux. Powershell is installed by `root`, then I run `chmod a+x`, and finally as non-root execute `pwsh`. The shell runs, but when I go to exit I get `Error reading or writing history file '/.local/share/powershell/PSReadLine/ConsoleHost_history.txt': Access to the path '/.local/share/powershell/PSReadLine' is denied.`

Powershell 6.1.3 for linux alpine

**Comment by jazzdelightsme** [comment]
See also #10601. I think this has to do with how permissions get set up on the .local/share/powershell directory. I have a [setup script with this code](https://github.com/jazzdelightsme/nixSetup/blob/44242496b82b2685fa8b92b48c2c896dcbbb932c/moreSetup.ps1#L52) for exactly this problem:

```powershell
    # Fix up permissions, since we've first run pwsh as root:
    # (irritating that chown can't handle ~)
    $refDir = Resolve-Path '~'
    $dstDir = Resolve-Path '~/.local/share/powershell'
    chown -R --reference=$refDir $dstDir
```

**Comment by jazzdelightsme** [comment]
See also #5239.
