### ISSUE TITLE
libcurl4 error Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by jackfido** [PowerShell/PowerShell#6914]
I have Ubuntu 18.04 (that is not listed here) but I have libcurl4 and the installation has an error:

x@x:~$ sudo apt-get upgrade powershell
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-runtime-2.0.7 : Depends: libcurl4 (>= 7.58.0) but it is not going to be installed
E: Broken packages
x@x:~$ sudo apt-get install libcurl4
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libcurl4 is already the newest version (7.58.0-2ubuntu3).
libcurl4 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by iSazonov** [comment]
@jackfido PowerShell Core will support Ubuntu 18.04 since 6.1.0 version. You can test with latest nightly builds. 6.1.0 version is based on .Net Core 2.1 and haven't curl dependency.

**Comment by jackfido** [comment]
I downloaded it, but I cant install it. Its shows me that need libcurl3 and it will remove curl and libcurl4: https://mega.nz/#!vJw3kTIK!1ibUxYtmK2N5YcYrwjih4o-qqJOPwetSqS6urcBGI2w https://mega.nz/#!XVIiDCDR!DMh03n-YmN5dnC-6y8FhIsrruGyjCGzNHwd0sGM2KNc

**Comment by iSazonov** [comment]
Download from https://powershell.myget.org/gallery/powershell-core-daily

**Comment by MaximoTrinidad** [comment]
@iSazonov 

The link you provided doesn't show the version for Ubuntu 18.04, or you mean to use the Debian version instead. 

:)

**Comment by iSazonov** [comment]
@MaximoTrinidad We are ready to publish a package for 18.04 in Preview3.

**Comment by MaximoTrinidad** [comment]
@iSazonov,

That's Awesome!!  I will wait for the release then.  
Thanks,
:)
