### ISSUE TITLE
ForEach-Object and Where-Object supercede ErrorRecords from their scriptblock with their own

### ISSUE THREAD

**Issue by alx9r** [PowerShell/PowerShell#6918]
This results in the true cause of errors being obscured whenever an error passes through `ForEach-Object` or `Where-Object` from the site of the error to the user.  The consequences of this are broader than might be apparent at first glance.  That is because the affected errors includes any error that occurred downstream in the pipeline pursuant to an object output by `ForEach-Object` or `Where-Object`.

Steps to reproduce
------------------

```powershell
try
{
    1 | ForEach-Object {
        0 -gt 0,0
    }
}
catch
{
    $_.InvocationInfo.PositionMessage
}

try
{
    1 | & { process { 
        0 -gt 0,0 
    }}
}
catch
{
    $_.InvocationInfo.PositionMessage
}
```

Expected behavior
-----------------

```none
At C:\Users\un1\Desktop\test.ps1:4 char:9
+         0 -gt 0,0
+         ~~~~~~~~~~~~~~~~
At C:\Users\un1\Desktop\test.ps1:15 char:9
+         0 -gt 0,0
+         ~~~~~~~~~
```

Actual behavior
---------------

```none
At C:\Users\un1\Desktop\test.ps1:3 char:9
+     1 | ForEach-Object {
+         ~~~~~~~~~~~~~~~~
At C:\Users\un1\Desktop\test.ps1:15 char:9
+         0 -gt 0,0
+         ~~~~~~~~~
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value                                            
----                           -----                                            
PSVersion                      6.0.2                                            
PSEdition                      Core                                             
GitCommitId                    v6.0.2                                           
OS                             Microsoft Windows 6.3.9600                       
Platform                       Win32NT                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                          
PSRemotingProtocolVersion      2.3                                              
SerializationVersion           1.1.0.1                                          
WSManStackVersion              3.0                                              
```

**Comment by BrucePay** [comment]
Hi @alx9r I didn't quite understand this statement:
> That is because the affected errors includes any error that occurred downstream in the pipeline pursuant to an object output by ForEach-Object or Where-Object.

Could you expand on this a bit? Thanks.

**Comment by alx9r** [comment]
> Could you expand on this a bit? Thanks.

Hi @BrucePay .  I seem to have misinterpreted what I was seeing.  I mistook the misleading contents of `.PositionMessage` as being caused by `Foreach-Object` not passing through error records like `{}.Invoke()`  (#3018).  But this looks more like a manifestation of a [not-so-useful position message noted by @lzybkr](https://github.com/PowerShell/PowerShell/issues/3647#issuecomment-297208232).  The error record in my OP indeed includes a correct `.ScriptStackTrace` and `.Exception`.  It's just `.InvocationInfo` that has puzzling contents. Whether the contents is puzzling doesn't seem to depend on the use of `Foreach-Object`, though.

The less-than-helpful position messages sometimes have a dramatic mismatch between the top of the `.ScriptStackTrace` and the site to which `.InvocationInfo` refers.  The mismatch sometimes results in navigating to an entirely different module which turns out to be unrelated.  That slows troubleshooting.  I guess that's what I was seeing when I wrote "The consequences of this are broader than might be apparent at first glance."  

Here is a contrived example of such a mismatch:

```PowerShell
function e {
    param ( [Parameter(ValueFromPipeline)] $x )
    process { f }
}

function f { g }

New-Module {
    function g { 0-gt 0,0 }
} | Import-Module

try
{
    e
}
catch
{
    $_.ScriptStackTrace
    $_.InvocationInfo.PositionMessage
}
```

The error occured in a module on line 9.  But `.InvocationInfo` doesn't mention anything about that line.  Instead `.InvocationInfo` refers to line 14 which is at the opposite end of the `.ScriptStackTrace` and isn't even in the module where the error originated.
