### ISSUE TITLE
Make all Send-MailMessage parameters accepting value from pipeline by property name

### ISSUE THREAD

**Issue by sethvs** [PowerShell/PowerShell#6924]
It would be nice to use with custom functions, where function is collecting some amount of information, generating PSCustomObject with needed properties, and sending it through the pipeline to Send-MailMessage cmdlet.

```
Get-SomeInfo | Send-MailMessage
```

**Comment by BrucePay** [comment]
Note: this is already pretty easy to do with `foreach` and splatting:
```powershell
$listOfParameterObject | foreach { Send-MailMessage @_ }
```

**Comment by thezim** [comment]
@BrucePay wow didn’t know you could do that but the foreach is awkward. In your case it seems like an abuse of a foreach for a single iteration, hackish.

**Comment by BrucePay** [comment]
@thezim He talks about taking pipeline input for what, I assume, would be multiple mail messages. Obviously, if it's just a single object then `Send-MailMessage @parameters` is sufficient.
