### ISSUE TITLE
Should we remove standard device detection code?

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#6925]
Currently our code detects names of standard devices:
https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/Utils.cs#L1042-L1070

Really it doesn't work in Windows PowerShell 5.1 and PowerShell Core too.
Simple test:
```powershell
copy .\README.md CON
copy : Cannot process path 'C:\Users\1\Documents\GitHub\iSazonov\PowerShell\CON' because the target represents a reserv
ed device name.
At line:1 char:1
+ copy .\README.md CON
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\1\Docu...\PowerShell\CON:String) [Copy-Item], IOException
    + FullyQualifiedErrorId : CopyError,Microsoft.PowerShell.Commands.CopyItemCommand


copy .\README.md CON:
copy : Cannot find drive. A drive with the name 'CON' does not exist.
At line:1 char:1
+ copy .\README.md CON:
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (CON:String) [Copy-Item], DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.CopyItemCommand
```

I guess it comes from PowerShell 2.0.
I suggest to remove the code.

PS: the sample works in cmd.exe

/cc @lzybkr @BrucePay @SteveL-MSFT

**Comment by BrucePay** [comment]
@iSazonov What do you mean by "it doesn't work"? In your first example, you get the intended error when you try to access a device name. In the second example 'con:' is not a device name, its a drive and you get the correct error for that. Checking for the devices allows us to produce a more reasonable error message. Note that we don't do it everywhere. For example:
```
PSCore (1:50) >  ls > con
out-file : FileStream was asked to open a device that was not a file. For support for devices like 'com1:' or 'lpt1:', call CreateFile, then use the FileStream constructors that take an OS handle as an IntPtr.
At line:1 char:1
+ ls > con
+ ~~~~~~~~
+ CategoryInfo          : OpenError: (:) [Out-File], NotSupportedException
+ FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
```
As you can see, without the check , you get a much more obscure error message. Now ideally, it would be nice if it actually did work and write to the terminal, but that wasn't implemented in V1 and has never, as far as I know, come up in all the years since then.

**Comment by lzybkr** [comment]
The `cmd` behavior is questionable, e.g. all of the following copy output to the console:

```cmd
copy file.txt con
copy file.txt con:
copy file.txt con.txt
copy file.txt con.exe
```

The extension is ignored. This is not specific to `cmd` - it's specific to Win32.

I believe the error message was introduced to avoid confusing errors when you **don't** get the behavior you thought you should (like my last 2 examples).

**Comment by iSazonov** [comment]
> What do you mean by "it doesn't work"? In your first example, you get the intended error when you try to access a device name.

1. A reserved device name is CON not `C:\Users\1\Documents\GitHub\iSazonov\PowerShell\CON`
2. If I use other tools I can copy (create/rename/delete) to file `C:\Users\1\Documents\GitHub\iSazonov\PowerShell\CON` 

As I understood Win32 behavior is not desirable.

Open question is -  should this file (`C:\Users\1\Documents\GitHub\iSazonov\PowerShell\CON`) be created instead of reporting the error?

**Comment by lzybkr** [comment]
@iSazonov - See [here](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx) and [here](https://googleprojectzero.blogspot.com/2016/02/the-definitive-guide-on-win32-to-nt.html) for some background, but the short answer is - those names (with/without a path and/or extension) are special and there's nothing any Windows application can do about it.

**Comment by iSazonov** [comment]
I was able to create files/directories with the reserved names by means of Far Manager (unlike Explorer.exe). This is misleading.

So I agree that current behaviour is right but we need still fix a message for `ls > con`.

Thanks for great comments!
