### ISSUE TITLE
Hashtables resulting from ConvertFrom-JSON -AsHashtable have case sensitive keys

### ISSUE THREAD

**Issue by strawgate** [PowerShell/PowerShell#6928]
Steps to reproduce
------------------

```powershell
@{"test"=1}.containsKey("Test")
True

("{""test"":1}" | convertfrom-json -AsHashtable).containsKey("Test")
False
```

Expected behavior
-----------------

```none
both should return true and keys should not be case sensitive
```

Actual behavior
---------------

```none
keys from convertfrom-json -ashashtable are case sensitive
```

Environment data
----------------

```powershell
> $PSVersionTable
PSVersion                      6.1.0-preview.1
PSEdition                      Core
GitCommitId                    v6.1.0-preview.1
OS                             Microsoft Windows 10.0.17666
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by markekraus** [comment]
@strawgate Case sensitivity is `by design` to accommodate case sensitive key names:

```json
{
  "key1": "value1",
  "KEY1": "value2"
}
```

This is documented in `-AsHashtable` fdocumentation:

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertfrom-json?view=powershell-6#optional-parameters

> If the JSON contains a list with keys that only differ in casing. Without the switch, those keys would be seen as identical keys and therefore only the last one would get used.

**Comment by strawgate** [comment]
Case sensitive hashtables are not the norm elsewhere --

`group-object -AsHashTable` does not produce case sensitive hashtables and neither does `@{}` with group-object being the reference for justifying the behavior and flag that was used.

I guess i'll leave this as a fun warning to anyone else using this cmdlet

```
$test1 = @{"Test"=1} | convertto-json | convertfrom-json -ashashtable
$test1.containsKey("test") # False
```

```
$test2 = @{"Test"=1}
$test2.containskey("test") # True
```

**Comment by markekraus** [comment]
> Case sensitive hashtables are not the norm elsewhere

Yes, but `-AsHashTable`  on `convertfrom-json` was implemented specifically to address the issue of case sensitive key names among other issues. It's by design and documented as such.

It probably should have been implemented as case insensitive by default with an option for case sensitive.

**Comment by strawgate** [comment]
Referencing the original PR: https://github.com/PowerShell/PowerShell/pull/5043
