### ISSUE TITLE
Test-NetConnection cmdlet is missing from PowerShell Core 6.0.1 release

### ISSUE THREAD

**Issue by kevinlrak** [PowerShell/PowerShell#6932]
Test-Connection was added in [5328](https://github.com/PowerShell/PowerShell/pull/5328 "Add ported Test-Connection cmdlet") but it appears that Test-NetConnection is still missing.

Steps to reproduce
------------------

```powershell
Get-Command Test-NetConnection
```

Expected behavior
-----------------

```none

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Test-NetConnection                                 1.0.0.0    NetTCPIP

```

Actual behavior
---------------

```none
Get-Command : The term 'Test-NetConnection' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-Command Test-NetConnection
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Test-NetConnection:String) [Get-Command], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand

```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.2
PSEdition                      Core
GitCommitId                    v6.1.0-preview.2
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kevinlrak** [comment]
I'm a little unclear, does that mean that Powershell 6 will not have Test-NetConnection? I would expect the ability to check a specific port on a system would be of even more interest to unix admins.

My assumption was that, like Test-Connection, Test-NetConnection had also been overlooked. If that was an incorrect assumption, then perhaps this should be re-labeled as a feature request. Otherwise, I believe this is a bug.

**Comment by iSazonov** [comment]
@kevinlrak Current `Test-Connection` ported implementation was enhanced. Please see `help Test-Connection`. 
```powershell
Get-Help -Name Test-Connection
NAME
    Test-Connection

SYNTAX
    Test-Connection [-TargetName] <string[]> [-Ping] [-IPv4] [-IPv6] [-ResolveDestination] [-Source <string>]
    [-MaxHops <int>] [-Count <int>] [-Delay <int>] [-BufferSize <int>] [-DontFragment] [-TimeoutSeconds <int>]
    [-Quiet] [<CommonParameters>]

    Test-Connection [-TargetName] <string[]> [-Ping] [-IPv4] [-IPv6] [-ResolveDestination] [-Source <string>]
    [-MaxHops <int>] [-Delay <int>] [-BufferSize <int>] [-DontFragment] [-Continues] [-TimeoutSeconds <int>] [-Quiet]
    [<CommonParameters>]

    Test-Connection [-TargetName] <string[]> -Traceroute [-IPv4] [-IPv6] [-ResolveDestination] [-Source <string>]
    [-MaxHops <int>] [-TimeoutSeconds <int>] [-Quiet] [<CommonParameters>]

    Test-Connection [-TargetName] <string[]> -MTUSizeDetect [-IPv4] [-IPv6] [-ResolveDestination] [-TimeoutSeconds
    <int>] [-Quiet] [<CommonParameters>]

    Test-Connection [-TargetName] <string[]> -TCPPort <int> [-IPv4] [-IPv6] [-ResolveDestination] [-Source <string>]
    [-TimeoutSeconds <int>] [-Quiet] [<CommonParameters>]
```
You can to check a specific port too.
.Net Core has still bugs in APIs and not all in Test-Connection works on Unix.
Fill free to test and feedback.

Nettcpip module is not in the repo (another MSFT team is owner) and it is not ported.

**Comment by kevinlrak** [comment]
@iSazonov what version are you running? I'm on the 6.1.0-preview.2, but my help Test-Connection does not match what you put above. Neither does [the online help page for Test-Connection in Powershell 6](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/Test-Connection?view=powershell-6).

Here is what I get:
``SYNTAX
    Test-Connection [-ComputerName] <String[]> [-AsJob] [-BufferSize <Int32>] [-Count <Int32>] [-Delay <Int32>] [-Impersonation {Default | Anonymous | Identify | Impersonate | Delegate}] [-ThrottleLimit <Int32>] [-TimeToLive <Int32>] [-DcomAuthentication <AuthenticationLevel>] [-Protocol <String>] [-WsmanAuthentication <String>] [<CommonParameters>]

    Test-Connection [-ComputerName] <String[]> [-Source] <String[]> [-AsJob] [-BufferSize <Int32>] [-Count <Int32>] [-Credential <PSCredential>] [-Delay <Int32>] [-Impersonation {Default | Anonymous | Identify | Impersonate | Delegate}] [-ThrottleLimit <Int32>] [-TimeToLive <Int32>] [-DcomAuthentication <AuthenticationLevel>] [-Protocol <String>] [-WsmanAuthentication <String>] [<CommonParameters>]

    Test-Connection [-ComputerName] <String[]> [-BufferSize <Int32>] [-Count <Int32>] [-Delay <Int32>] [-Impersonation {Default | Anonymous | Identify | Impersonate | Delegate}] [-Quiet] [-TimeToLive <Int32>] [-DcomAuthentication <AuthenticationLevel>] [-Protocol <String>] [-WsmanAuthentication <String>] [<CommonParameters>]
``

However, when I try running Test-Connection with the -TCPPort flag, it does seem to function. So I believe this is mostly a problem with that enhancement being undocumented in the latest current release (6.1.0-preview.2)

**Comment by corretge** [comment]
In PowerShell 6.0.2, last version when install PowerShell though HomeBrew on Mac both commands are missing:

- Get-Command : The term 'Test-NetConnection' is not recognized as the name of a cmdlet [...]
- get-Command : The term 'Test-Connection' is not recognized as the name of a cmdlet [...]

```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Darwin 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEA...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment]
@corretge You'll get Test-Connection in 6.1 version or you can use 6.1 Preview2 or current dev builds.

**Comment by MrFly72** [comment]
In my eyes this is breaking all compatibility with no understand from my side, why not implement Test-NetConnection...
It would be really wise to implement it .
This is again one of the commands where I have if/else for what it is running on. and worse enough, it has to be a check for 5.1/7.x, Windows/Linux (5.1 does not support -TCPPort, Linux does not support Test-NetConnection)
is this the type of Multi-Plattform-Support Microsoft is aiming at?
Please reconsider this, as it really breaks scripts that do network checks and should run on multiple plattforms or be easy to port.

**Comment by claytonolley** [comment]
I just came across this today and could really use Test-NetConnection in pwsh on Mac!

**Comment by vexx32** [comment]
See above; you should be able to use `Test-Connection` for most of the use cases that `Test-NetConnection` covered in earlier versions. If you have a specific use case that the current implementation doesn't cover, I suggest you open a feature / improvement request for that cmdlet instead. 🙂

**Comment by MrFly72** [comment]
@vexx32 But as said above. This breaks scripts to be compatible on multiple plattforms. And that because of a really bad reason, in my eyes, as Test-NetConnection could be easily built as the functionality is present in parts in test-connection.

**Comment by vexx32** [comment]
I have to disagree, since I wrote quite a lot of the current implementation of Test-Connection. Many of the features Test-NetConnection had are simply not available in .NET itself currently. Even the things that are there largely only work on Windows, from what I've been able to determine.

It's probably possible with a third-party library, but I'm not familiar enough in that area to know what would be useful to look at, nor would I expect the maintainers to want to pull it in as a permanent dependency.

Test-NetConnection is simply not cross-platform compatible. `Test-Connection` is, to the best of our current ability, the closest we have and is available even back in WinPS 5.1 (with some minor differences from the current implementation; it too had to be rewritten completely, in the end).

If you'd like to expand what it can do, feel free; I have no doubt that useful functionality would likely be welcomed as a PR. 🙂

**Comment by MrFly72** [comment]
But exactly thats the current problem. Test-Connection does not support eg. TCPPort in 5.1
So there is no way currently to write code that can be used on 5.1 + 7.x on multiple plattforms, other then doing stuff like.
if ($IsLinux) ..... etc.

**Comment by ClaytonOlleyNutrien** [comment]
Test-Connection is icmp only... I specifically needed something to test a tcp port connection. I just ended up using netcat instead.

**Comment by MrFly72** [comment]
> Test-Connection is icmp only... I specifically needed something to test a tcp port connection. I just ended up using netcat instead.

With -TCPPort Parameter it is a TCP-Connection?

**Comment by shaheerxt** [comment]
I know this discussion has been closed, but I wanted to provide an important takeaway.

I am using mac and installed powershell for it. 
`brew install --cask powershell`

I access it using pwsh command.

First i logged in with **Az login** , and it was successful.

But i faced an issue with **Get-AzStorageAccount** command.
`Get-AzStorageAccount: The term 'Get-AzStorageAccount' is not recognized as a name of a cmdlet, function, script file, or executable program.`

So installed **Az** module
`Install-Module Az
`

But still there was an issue with port connectivity check
```
PS /Users/whosecode> Test-NetConnection -ComputerName ([System.Uri]::new($storageAccount.Context.FileEndPoint).Host) -Port 445
Test-NetConnection: The term 'Test-NetConnection' is not recognized as a name of a cmdlet, function, script file, or executable program.
```

So I came across a note about  **Test-Connection** instead of Test-NetConnection , and it seems returning right result.
```
PS /Users/whosecode> Test-Connection -ComputerName ([System.Uri]::new($storageAccount.Context.FileEndPoint).Host) -TcpPort 445
False
```

**Comment by ahaleiii** [comment]
`Test-NetConnection` has a `SourceAddress` property on the response, from which I can get the source `IPAddress`.

`Test-Connection` has a `Source` property on the response, but this only appears to be the `hostname`.

Is there a way to replicate the `Test-NetConnection` behavior to get `SourceAddress` on Linux?
