### ISSUE TITLE
CodeFactor PR check flags up problems on ontouched and unrelated lines/methods

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#6941]
As per title, the `CodeFactor` check makes most PRs red because it flags up issues that are unrelated to the PR.
This is due to the files containing a lot of other code. Neither do I want to change unrelated code as part of the PR nor seeing the PR checks as red, we should not have a '50 shades of red' build.
The team should clean up the warnings first or suppress some of the warnings since so far most of them are purely stylistic.
.Net Core has the [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers) NuGet package, which is a subset of the CA warnings that most people are familiar with from the full .Net framework, I found those warnings more useful rather than having a linter check, since linters are more useful when being used in VS Code extensions

**Comment by markekraus** [comment]
ref: #6930  #4708

I personally think CodeFactor should be disabled until it can be useful. That could be either after CodeFactor makes it more surgically applied to the PR changes or until the project has a cohesive style that rule and CI checks can actually be applied against.

I definitely agree with you on not wanted PS merged with failed checks. Right now CodeFactor is noise.

**Comment by iSazonov** [comment]
Currently CodeFactor is optional and don't block current PRs.
We have already opened #6930 to get feedback about CodeFactor. Please leave comments there what rules should be turned off or configured.

**Comment by iSazonov** [comment]
We continue to adjust CodeFactor setting step by step. Please discuss next steps in 4708.
