### ISSUE TITLE
Support for Ubuntu 18.04 the newest LTS Release of Ubuntu?

### ISSUE THREAD

**Issue by rmiddle** [PowerShell/PowerShell#6942]
Ubuntu 18.04 LTS release has been out for a month now but it doesn't look like any builds are available yet for it.  Any word when 18.04 builds are going to be released?

**Comment by iSazonov** [comment]
@rmiddle 18.04 support is already in master branch. You can build and even create a Ubuntu package.
We expect that community get this with PowerShell Core 6.1 Preview3 in weeks.

Dup #6307, #6692
