### ISSUE TITLE
Strange column header alignment with PSCustomObject

### ISSUE THREAD

**Issue by LethiferousMoose** [PowerShell/PowerShell#6955]
Steps to reproduce
------------------
In PowerShell terminal enter the following:

```powershell
[PSCustomObject]@{
    Column1 = 'Test'
    Column2 = 'This is some text'
    Column3 = 'This is some more text'
    Column4 = $true
}
```

Expected behavior
-----------------

```none
Column4 is correctly positioned over the dotted separator line.
```
![pscustomobject working](https://user-images.githubusercontent.com/24547864/40680971-61538134-634d-11e8-92a5-4362327845ef.png)

Actual behavior
---------------

```none
Column4 is butted up against Column3 and is not positioned over its content.
```
![pscustomobject issue](https://user-images.githubusercontent.com/24547864/40680917-3ffcb1c2-634d-11e8-9320-60a8b29fc7cb.png)

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.2
PSEdition                      Core
GitCommitId                    v6.1.0-preview.2
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Note: this appears to be a new bug with the 6.1 build, it works as expected in 6.0 GA release (I have not tested against 6.0.1, 6.0.2, or 6.1-preview1 so it may have existed before 6.1)
.

**Comment by SteveL-MSFT** [comment]
This is already fixed as part of the format-table changes since Preview.2.  Just validated it works fine off master build.
