### ISSUE TITLE
Cursor isn't displayed on Powershell 6.1.0-preview.2

### ISSUE THREAD

**Issue by mikemaccana** [PowerShell/PowerShell#6957]
Steps to reproduce
------------------

Start Powershell 6.2 preview 2

Expected behavior
-----------------

A cursor should appear at the end of the prompt.

Actual behavior
---------------

Cursor is missing.

![image](https://user-images.githubusercontent.com/172594/40723045-d4b40130-6415-11e8-872e-8f5f9516433b.png)

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.2
PSEdition                      Core
GitCommitId                    v6.1.0-preview.2
OS                             Microsoft Windows 10.0.17677
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

Note starting Powershell 5 shows the normal `_` cursor.

**Comment by MaximoTrinidad** [comment]
Hum!! Is this on a Virtual Machine?? I just realized I'm getting the same issue only in a VM and not on a physical machine.

```
PS C:\Program Files\PowerShell\6-preview> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.2
PSEdition                      Core
GitCommitId                    v6.1.0-preview.2
OS                             Microsoft Windows 10.0.17677
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
Image from a VM:
![pscorecursor_vm_issue_2018-05-30_9-55-43](https://user-images.githubusercontent.com/19892435/40724746-c84cd9f6-63ef-11e8-9479-b7b9b7f70936.jpg)

Image from my physical machine:
![img_5583](https://user-images.githubusercontent.com/19892435/40725000-5f9551a8-63f0-11e8-8a99-3b216705d43e.JPG)

**Comment by mikemaccana** [comment]
Physical machine.

Interestingly it seems to come back, and then go away. Going to try a few more things.

**Comment by lzybkr** [comment]
You can check the property `[Console]::CursorVisible`, it's probably `false`, setting it to `true` should help.

Are you using `PSReadLine 2.0.0-beta1`? In that version, I started hiding the cursor while rendering to fix the flashes people see on Linux/Mac, but nobody has reported any similar issue and I've never noticed any problems.

**Comment by mikemaccana** [comment]
```
$ get-package psreadline

Name                           Version          Source                           ProviderName
----                           -------          ------                           ------------
PSReadLine                     2.0.0-beta1      https://www.powershellgallery... PowerShellGet
```

Yeah using 2.0.0-beta1.

**Comment by mikemaccana** [comment]
Hey @MaximoTrinidad - just wanted to respond re: uninstalling PSReadline. https://blogs.msdn.microsoft.com/powershell/2018/01/24/powershell-core-6-1-roadmap/ mentions:

> Some of my engineers will be spending time contributing to this project to get it to production quality so we can include it in PowerShell Core 6.0.

So I thought PSReadLine 2.0.0-beta1 was installed by Powershell 6.1 Preview 2. Is this incorrect?

**Comment by SteveL-MSFT** [comment]
@mikemaccana PSCore6 still currently ships with PSReadLine 1.2 due to an issue in PSReadLine 2.0.  The issue has since been fixed, but the fix isn't available until the next PSReadLine beta release.  You would have had to manually install PSReadLine 2.0.

**Comment by MaximoTrinidad** [comment]
Thanks @SteveL-MSFT and @mikemaccana!

Just an FYI ... I create a incident in UserVoice for Windows PowerShell as the cursor has disappear from the prompt only on Virtual Machines.

**Comment by SteveL-MSFT** [comment]
@MaximoTrinidad is it Windows PowerShell specific or does it repro with cmd?  Also does it repro with PSReadLine removed?

**Comment by MaximoTrinidad** [comment]
@SteveL-MSFT,

I can repo both Windows PowerShell and PowerShell Core only on a virtual machine even without the PSReadline loaded.  

This happened after upgrading Windows 10 Insider to build 17677. 

Again, this didn't happened on the previous Windows 10 Insider.  And, it's working fine on Microsoft Windows [Version 10.0.17134.48]. 

:)

**Comment by SteveL-MSFT** [comment]
@MaximoTrinidad but does it repro with cmd.exe?  We haven't made any changes in Windows PowerShell that would affect this.  It's more likely a change in Windows.

**Comment by MaximoTrinidad** [comment]
@SteveL-MSFT 

Apologies!!  Yes! It's happening in DOS Command Prompt too. But, is not happening with WSL Ubuntu prompt.

FYI - I'm using VMware Workstation to create my VM's.  I got one non-Insider version that's working fine.

**Comment by MaximoTrinidad** [comment]
I have to say, I have notice the cursor disappearing on/off on my physical machine too. It recovers fast and is not happening all the time.

**Comment by mikemaccana** [comment]
I wish I could help more - the cursor is appearing since my last reboot and I haven't been able to repro since. Going to keep an eye out for it and will tell you if I find out what behaviour causes it.

**Comment by SteveL-MSFT** [comment]
This is most likely changes happening in the Windows console.  In general, I would suggest seeing if you have the same issue with cmd.exe as that uses the same console.  I just updated to a newer build and via RDP the console cursor is gone sometimes.

**Comment by MaximoTrinidad** [comment]
Yeah! It comes and goes on my physical machine but is gone all the time on my VM. 
Well! At least someone will let the Windows Team know about it.

Thanks,
:)

**Comment by MaximoTrinidad** [comment]
@SteveL-MSFT 

Just an FYI

I just installed Windows Server Insider Build 17677 (Server Core) and the Console Prompt is "Gone!" when creating a VMWare Workstation Virtual Machine.

I'm wondering is it happens in Hyper-V too.

:)

**Comment by mikemaccana** [comment]
@SteveL-MSFT Can you paste a link to the corresponding console issue? Thanks!

**Comment by MaximoTrinidad** [comment]
@SteveL-MSFT 

In my case, I discovered that my issue is leaning towards VMWare Tools on my VM. I get the cursor back if I remove VMWare Tool from Windows 10 17677.

I posted the issue in UserVoice: https://windowsserver.uservoice.com/forums/295047-general-feedback/suggestions/34422874-windows-server-insider-17677-all-shells-lost-con

**Comment by mikemaccana** [comment]
It's come back. Yeah it's in `cmd` too. What was the https://github.com/Microsoft/console/ issue number?

**Comment by SteveL-MSFT** [comment]
@mikemaccana I think it might be https://github.com/Microsoft/console/issues/193
