### ISSUE TITLE
Improve the error message for when a property-name / hashtable-key token cannot be parsed as such

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#6959]
Following up from #6946:

A token to the right of `.` when accessing an object property or hashtable entry is parsed as an _expression_ if it doesn't start with a _letter_.

If that token is ultimately not a _valid_ expression, the error message erroneously suggests that _no token_ was specified, which is confusing:

```powershell
$obj = [pscustomobject] @{ '1a' = 'one A' }
PS> $obj.1a  # !! Breaks; must use $obj.'1a', due to property name starting with a *digit*
At line:1 char:6
+ $obj.1a
+      ~
Missing property name after reference operator.
```

Given that the fact that `1a` is _not_ treated as a string - and instead evaluated as an _expression_ that _breaks_ - is not obvious, providing specific guidance in the error message along the following lines would be helpful:

```none
At line:1 char:6
+ $obj.1a
+      ~
Invalid property-name expression; use quotes for literal interpretation.
```

Environment data
----------------

Written as of:

```powershell
PowerShell Core v6.1.0-preview.2
```

**Comment by iSazonov** [comment]
Is it necessary to use quotes in the scenario? Maybe can fix this?
