### ISSUE TITLE
Add-Type -Language FSharp

### ISSUE THREAD

**Issue by brianary** [PowerShell/PowerShell#6969]
I'd like to request and track FSharp support in Add-Type (separate from the broader #5725 ). FSharp's syntax seems to lend itself optimally well to the kind of terse type and member definitions that are passed to Add-Type.

**Comment by iSazonov** [comment]
Today MSFT team plan to remove VisualBasic support in order to reduce distributive size. So adding F# looks unreal in near future.
We could consider refactor Add-Type to support an addins from optional modules.

**Comment by brianary** [comment]
That's disappointing. Hopefully something that dynamically uses what languages are available on the system would be an option in the future.

**Comment by iSazonov** [comment]
In #5725 I see a few votes. If we get a lot of votes then we can get approval from PowerShell Committee.

**Comment by brianary** [comment]
It seems like a closed issue is unlikely to get a lot of votes, though. And given that #5725 covers several different features, I thought an open issue specific to one feature would be more effective.

**Comment by iSazonov** [comment]
If you are from F# community then ask there for a vote.

**Comment by brianary** [comment]
Being able to write something like this:

```powershell
Add-Type -Language FSharp -TypeDefinition `
  "let (JustEven: int seq -> int seq) = Seq.choose (function | x when (x % 2) = 0 -> Some(x) | _ -> None)"
```

still seems like it would be a nice alternative to this:

```powershell
Add-Type -Language FSharp -TypeDefinition @'
using System.Collections.Generic;
using System.Linq;
public static class EvenTest
{
    public static int[] JustEven(IList<int> values) => values.Where(x => x % 2 == 0).ToArray();
}
'@
```

This is one of those things that seems to stick out whenever F# is described as a first-class language.

**Comment by JustinGrote** [comment]
This would require shipping the fsharp.core library with Powershell which would be a whole thing.

However, I have come up with a module based solution that should not require shipment as long as everyone uses the same fsharp.core module as a dependency (or hides it behind an ALC)

http://github.com/justingrote/fsharp

It has a working Add-FSharpType implementation.
