### ISSUE TITLE
Create tooling to update files in packaging.psm1, files.wxs, pwrshcommon.cpp automatically

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#6978]
Whenever we reference new packages or existing packages add new assemblies, we go through a manual exercise to update source files.  This should be automated and manually reviewed.

**Comment by TravisEz13** [comment]
Whenever files.wxs is regenerated, The following properties about existing components can change or patching will be completely broken:

- Component Id
- Component GUID
- File Id
- File Name (the source path of the file, however, can change.  Although, the destination cannot change, but that is in a separate WXS file)

This assumes we stick to the WiX recommendation of one file per component.  If we don't, the rules become more complex.

**Comment by iSazonov** [comment]
If the script find and report what lines we should remove or add why we can not edit the file automatically? It is not regeneration of the file with scratch.

**Comment by TravisEz13** [comment]
@iSazonov basically, its just more work and it hasn't been done.  I'm just listing the requirements for the work, which may not be obvious.  We cannot just use the WiX toolset to generate the file and replace the existing file.

**Comment by iSazonov** [comment]
@TravisEz13 has already updated packaging.psm1 in #7272.
