### ISSUE TITLE
"How to Install" "Instructions" for all Windows and Ubuntu version goes to 404

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/PowerShell#6983]
Steps to reproduce
------------------

```powershell
Browse to github.com/PowerShell/PowerShell
Scroll down to the "Get PowerShell" section
Select any of the "Instructions" links
```

Expected behavior
-----------------
```none
Page appears telling how to install PowerShell
```

Actual behavior
---------------

```none
404
This is not the web page you are looking for.
```

Environment data
----------------

```powershell
Occurs using Chrome on Windows 10
Occurs using Firefox on Ubuntu 16.04 LTS
```

**Comment by kwiknick** [comment]
It looks like a recent commit moved the docs into it's own repo, and I'm wondering if the /installation/*.* folder got missed somehow.

**Comment by stknohg** [comment]
The "Instructions" was removed by #6899.
#6981 has been requested to fix this.
