### ISSUE TITLE
Binding Redirects for Binary Modules in PS Core

### ISSUE THREAD

**Issue by glatzert** [PowerShell/PowerShell#6987]
I started writing a binary module for managing my instance of IdentityServer4 (from Thinktecture via Dotnet Foundation). Since I need the EntityFramework-Enabled Storage the Dependencies are rather complex, which possibly leads to mismatches of Assembly Versions and BindingRedirects come into play.

PS 5.1 allowed to use the `AssemblyResolve` Event of `System.AppDomain.CurrentDomain` to bypass the problems, by just loading whatever version is available.
As far as I understood .NET Core (and thus PS Core) do not have AppDomain.

Is there any story to do binding redirects in complex binary modules?

**Comment by iSazonov** [comment]
Possibly the API is already in .Net Core 2.1 - please ask .Net team.
