### ISSUE TITLE
Install-Package Microsoft.Windows.Compatibility // Unable to find dependent package(s) (System.Reflection.Emit.Lightweight)

### ISSUE THREAD

**Issue by AlexBillon07** [PowerShell/PowerShell#6988]
Hello,

I am trying to install [Microsoft.Windows.Compatibility](https://www.nuget.org/packages/Microsoft.Windows.Compatibility) package from NuGet with Powershell 6.0.2 console but I always get the same exception Unable to find dependent package(s) (System.Reflection.Emit.Lightweight)

I am not sure if I report this issue in the right place so please point me in the right direction if I am mistaken.

Steps to reproduce
------------------

```powershell
Find-Package -Name Microsoft.Windows.Compatibility -ProviderName NuGet | Install-Package
```

Expected behavior
-----------------
Installation of the package

Actual behavior
---------------
UnableToFindDependencyPackage Exception

```none
Install-Package : Unable to find dependent package(s) (System.Reflection.Emit.Lightweight)
At line:1 char:74
+ ... ft.Windows.Compatibility -ProviderName NuGet | Install-Package -Force
+                                                    ~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (System.Reflection.Emit.Lightweight:String) [Install-Package], Exception
+ FullyQualifiedErrorId : UnableToFindDependencyPackage,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Microsoft Windows 6.1.7601 S
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
WCP is already in PowerShell Core 6.1 - the PR was merged today.
So you get this in next preview or in release 6.1.

**Comment by markekraus** [comment]
For 6.0.0-6.0.2, you can use PSCoreWindowsCompat https://www.powershellgallery.com/packages/PSCoreWindowsCompat/ if you just want to make the missing libraries loaded in powerShell.

**Comment by AlexBillon07** [comment]
Thanks.
I'll wait for the next release of 6.1.
