### ISSUE TITLE
Include Windows PowerShell System32 module directories on module path

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#6990]
PowerShell Core 6 should try to use compatible Windows modules out of the box. Part of this is including those modules under the `\Windows\System32\` path on the module path to allow discovery and loading of those modules.

**Comment by rjmholt** [comment]
See also:
* https://github.com/PowerShell/PowerShell/issues/6991
* https://github.com/PowerShell/PowerShell/issues/6992

**Comment by rjmholt** [comment]
Tagging @PowerShell/powershell-committee for review

**Comment by SteveL-MSFT** [comment]
See https://github.com/PowerShell/PowerShell-RFC/pull/130
