### ISSUE TITLE
Respect CompatiblePSEditions field in module manifests, with sane default

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#6991]
For Windows PowerShell/PowerShell Core modules to have a clear cross-compatibility story, we need PowerShell Core to respect the `CompatiblePSEditions` field.

This means, for PowerShell Core:
* `Get-Module -ListAvailable` lists only those modules on the module path that are Core compatible
* `Import-Module` will only import a module that is Core compatible and throw an error otherwise
* The absence of the `CompatiblePSEditions` field should imply a sane default. The current suggested default is `CompatiblePSEditions = @('Desktop')`, i.e. compatible with Windows PowerShell (since there is no such field in Windows PowerShell and modules written for it only would lack this field by default).

**Comment by rjmholt** [comment]
See also: https://github.com/PowerShell/PowerShell/issues/6992

**Comment by rjmholt** [comment]
Tagging @PowerShell/powershell-committee for discussion. I think we're also going to do an RFC for this, yes?

**Comment by rjmholt** [comment]
We should also clarify the difference between `PSEdition` and `CompatiblePSEdition`

**Comment by SteveL-MSFT** [comment]
@rjmholt yes, RFC to be published shortly

**Comment by SteveL-MSFT** [comment]
https://github.com/PowerShell/PowerShell-RFC/pull/130
