### ISSUE TITLE
Module discovery cmdlets should be able to override PSCompatibleEdition

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#6992]
Moving toward broader usage on Windows for PowerShell Core 6, we will need to honour the `PSCompatibleEditions` field of module manifests.

However, this field may be set conservatively or defaulted to a conservative value. As such we should allow a flag to allow the forced import of those modules for `Get-Module [-ListAvailable]` and `Import-Module`.

Ideally the name of this flag should be pithy, expressive about being a compatibility override behaviour, and dangerous-sounding so that users will understand that things may break as a result.

**Comment by mklement0** [comment]
`-Force` may actually work for this - though knowing _what_ is being forced would have to be gleaned from the documentation.

* `Get-Module` currently doesn't have a `-Force` switch.

* `Import-Module` does, and there it forces _reloading_ of the target module ([wonderfully summed up as "Indicates that this cmdlet re-imports a module and its members, even if the module or its members have an access mode of read-only."  in the docs](https://github.com/PowerShell/PowerShell-Docs/issues/2498)).
   * However, I think it's fine to overload semantics of `-Force` situationally, given that you wouldn't ordinarily use `-Force` unless you expected the module to have been imported already.

**Comment by rjmholt** [comment]
Tagging @PowerShell/powershell-committee for review

**Comment by SteveL-MSFT** [comment]
See https://github.com/PowerShell/PowerShell-RFC/pull/130
