### ISSUE TITLE
Register-EngineEvent -MessageData 'Value' seemingly has no effect

### ISSUE THREAD

**Issue by LethiferousMoose** [PowerShell/PowerShell#7000]
Steps to reproduce
------------------

```powershell
# Listen for the event.
Register-EngineEvent -SourceIdentifier SomethingChanged -MessageData 'Not Hello World' -Action {
    Write-Host $event.MessageData 
}

# Now raise the event.
New-Event -SourceIdentifier 'SomethingChanged' -MessageData 'Hello World'
```

Expected behavior
-----------------

```none
The MessageData value provided from Register-EngineEvent should be retrievable in the Action block.
```

Actual behavior
---------------

```none
The $event.MessageData is always the value provided from New-Event.  In this case it is always "Hello Word" from the New-Event call.
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.2
PSEdition                      Core
GitCommitId                    v6.1.0-preview.2
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Is there some different way to retrieve the MessageData provided by Register-EngineEvent? The documentation on both Register-EngineEvent and New-Event both say that is provided in the event object.

**Comment by iSazonov** [comment]
@LethiferousMoose Please add working repo steps. We could use them as a test.

**Comment by LethiferousMoose** [comment]
I rearranged the cmdlets into the correct order. That should be all that's needed.

**Comment by LethiferousMoose** [comment]
For more context this is what I am doing with Register-ObjectEvent:
```powershell
class BaseConfiguration {
    # Properties
    [bool] $CacheInvalidated;
    
    # Hidden Properties
    hidden [System.IO.FileSystemWatcher] $Watcher;
    hidden [System.Management.Automation.PSEventJob] $FileChangedEventJob;

    hidden [void] AddConfigurationFileChangedListener([string] $configPath) {
        if ($null -eq $this.FileChangedEventJob) {
            $this.Watcher = [System.IO.FileSystemWatcher]::new($configPath, '*.json')
            $this.Watcher.NotifyFilter = [System.IO.NotifyFilters]::FileName, [System.IO.NotifyFilters]::LastWrite
            $this.Watcher.IncludeSubdirectories = $true
            
            $this.FileChangedEventJob = Register-ObjectEvent -InputObject $this.Watcher -MessageData $this `
                                                             -EventName Changed -Action {
                # Conditional statement here to check if the cache is invalidated
                $event.MessageData.CacheInvalidated = $true
            }
        }
    }
}
```

Based on the documentation for Register-EngineEvent is sounded like the same behavior I used for Register-ObjectEvent was possible with Register-EngineEvent.

For example:
```powershell
class BaseConfiguration {
    # Properties
    [bool] $CacheInvalidated;
    
    # Hidden Properties
    hidden [System.Management.Automation.PSEventJob] $ConfigurationChangedEventJob;

    hidden [void] AddConfigurationChangedListener() {
        if ($null -eq $this.ConfigurationChangedEventJob) {
            $this.ConfigurationChangedEventJob = Register-EngineEvent -SourceIdentifier 'ConfigurationChanged' `
                                                                      -MessageData $this -SupportEvent -Action {
            $event.MessageData.CacheInvalidated = $true
        }
    }
}
```

Then I could call:
```powershell
New-Event -SourceIdentifier 'ConfigurationChanged'
```

From a different module to update all derived configuration classes.

According to https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/register-engineevent?view=powershell-6#optional-parameters

Register-EngineEvent's MessageData property is defined as:

> Specifies additional data associated with the event. The value of this parameter appears in the MessageData property of the event object.

Also confusingly, if we look at New-Event's documentation we find the same definition:
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/new-event?view=powershell-6#optional-parameters

So if this gets fixed, it is going to have to be determined how the two different MessageData parameters live together from both New-Event and Register-EngineEvent.

**Comment by iSazonov** [comment]
@lzybkr Could you please clarify - should we resolve the request?

**Comment by Kungfoowiz** [comment]
I get a similar but slightly different issue when working with PS events.
I am also experiencing this problem when working with PS events. I expected it to use the original event subscription's MessageData, but it looks like I need to provide its MessageData object each time New-Event is called. I am using -Forward parameter to forward the event to the main subscribed event.

**Simplified code**

**Main script:**
$testEventData = New-Object PSObject -property @{someValue = $someValue}
Register-EngineEvent -SourceIdentifier Test.Event -MessageData $testEventData -Action { ... }

**In another script:**
Register-EngineEvent -SourceIdentifier Test.Event -Forward
New-Event Test.Event

---

$event.MessageData.someValue is null when the event is called in another script, even though I have set that event to forward to the main event.

**Comment by jfriend00** [comment]
This bug still exists.  Not sure why it was closed.
