### ISSUE TITLE
Powershell on Linux link is broken on README.md file

### ISSUE THREAD

**Issue by ShekharReddy4** [PowerShell/PowerShell#7003]
Please check the readme.md file :)

**Comment by bergmeister** [comment]
@ShekharReddy4 Can you please be more specific?  PR #6981 got merged recently with link fixes to the Readme. Can you confirm that this fixed it? cc @sdwheeler

**Comment by ShekharReddy4** [comment]
@bergmeister seems like you fixed it. 👍
