### ISSUE TITLE
Globally install help on Linux

### ISSUE THREAD

**Issue by pavelbraginskiy** [PowerShell/PowerShell#7015]
I would like to install help documents on my Linux system globally, rather than per-user. The documentation for `Update-Help` states that in order to install help to `$PSHome`, I should use the command `Start-Process PowerShell -Verb RunAs` in order to run `Get-Help` as admin. Without elevated privelages, the help documents are installed in the user's `~/.local/share/powershell` directory.

This does not work on Linux (and I assume Mac): Start-Process : `The parameter '-Verb' is not supported for the cmdlet 'Start-Process' on this edition of PowerShell.` Starting powershell with `sudo` to run as root does not work either--it instead installs help into `/root`, the root users home directory. 

Is there a way to globally install help on Linux? If not, there should be, if so, it should be better documented.

Of course, it's possible I just missed something, but I have checked the help document for `Update-Help` several times.

**Comment by thnk2wn** [comment]
I have a similar problem on Mac. At first:

<pre>
PS /Users/hudgeo> update-help                                                                                                 
update-help : Failed to update Help for the module(s) 'Microsoft.PowerShell.Archive, Microsoft.PowerShell.Core, Microsoft.PowerShell.Host, Microsoft.PowerShell.Management, Microsoft.PowerShell.Security, Microsoft.PowerShell.Utility, PackageManagement, PowerShellGet, PSReadLine' with UI culture(s) {en-US} : Access to the path '/usr/local/microsoft/powershell/6.0.2/en-US/Microsoft.PowerShell.Commands.Management.dll-Help.xml' is denied.                                                                   At line:1 char:1                                                                                                              
+ update-help
+ ~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
+ FullyQualifiedErrorId : UnknownErrorId,Microsoft.PowerShell.Commands.UpdateHelpCommand
</pre>

Also tried Start-Process and sudo ("command not found")

**Comment by pavelbraginskiy** [comment]
@thnk2wn Here's a function you can put in your profile to make Sudo work with Powershell cmdlets and aliases, with `sudo !!` functioning like in Bash thrown in:

```
function sudo
{
	if($args[0] -eq '!!')
	{
		sudo $((Get-History ((Get-History).Count))[0].CommandLine) 
		return
	}
	. $(which sudo) pwsh -NoProfile -Command ". $PROFILE *> /dev/null; $args"
}
```

Probably won't help you with `Update-Help` though.
