### ISSUE TITLE
Failed to install powershell-preview trying to overwrite /usr/local/share/main/main1/pwsh.1.giz

### ISSUE THREAD

**Issue by jianyunt** [PowerShell/PowerShell#7027]
While running `sudo apt-get install -y --no-install-recommends powershell-preview` on my linux vm, i got the follow error.

![image](https://user-images.githubusercontent.com/10171679/41176655-1b541826-6b16-11e8-946d-a9794e8ade4d.png)

Workaround
------
Thanks to @TravisEz13! The install went successfully after  `apt-get remove powershell` first then install again. 

Steps to reproduce
------------------

```powershell

```

Expected behavior
-----------------

```none

```

Actual behavior
---------------

```none

```

Environment data
----------------

I have PowerShell v6.1.0-preview.1 installed on my Linux Ubuntu 16.04 before I upgrade to the preview3.

**Comment by rjmholt** [comment]
Assume we need to rename the preview's `man` artefact to be `pwsh-preview.1.gz`?

**Comment by rjmholt** [comment]
Is this function the right place?

https://github.com/PowerShell/PowerShell/blob/50d061148d369e6a77cf48db34c27c9f2b24ae6b/tools/packaging/packaging.psm1#L1084-L1103

**Comment by TravisEz13** [comment]
I checked in a fix directly into the preview.3 release branch.  We will merge it into master when we are done with the release

**Comment by TravisEz13** [comment]
https://github.com/PowerShell/PowerShell/commit/f08a031f88ce1d3866a21720bf8d832490a90652
