### ISSUE TITLE
Installing libcurl3 led to losing half of the tools installed

### ISSUE THREAD

**Issue by rahulr311295** [PowerShell/PowerShell#7036]
Powershell needed a dependency called libcurl3 so i tried to manually install It which led to removing most of my pre-installed tools like curl metasploit etc,

![image](https://user-images.githubusercontent.com/21986177/41195004-e610193e-6c42-11e8-86f7-f14f9621173d.png)

![image](https://user-images.githubusercontent.com/21986177/41195001-c84fb0f8-6c42-11e8-93e3-8c13f8232aa8.png)

**Comment by iSazonov** [comment]
@rahulr311295 .Net 2.0 has curl dependency not PowerShell Core. Currently we already moved to .Net Core 2.1 which haven't the dependency. You can test this with latest PowerShell Core builds or wait Preview3.

**Comment by rahulr311295** [comment]
Ok thanks il check that
