### ISSUE TITLE
AppVeyor PR builds can hang sporadically and then timeout/abort after only 3 hours

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#7038]
Not sure if this has happened before or is due to a new test, but there were recently 2 different `AppVeyor` PR builds that got stuck and then only aborted due to the 3 hour timeout.

I first saw it in [this ](https://ci.appveyor.com/project/PowerShell/powershell/build/v6.1.0-preview.9622) PR build of PR 7013 and then also in [this ](https://ci.appveyor.com/project/PowerShell/powershell/build/v6.1.0-preview.9662)PR build of PR 7033
The log stops at different tests in those 2 runs, therefore not sure if it is a problem of a specific test or aftereffect of a certain test suite or an AppVeyor problem

**Comment by iSazonov** [comment]
I guess there was unhandled error in build process.

**Comment by bergmeister** [comment]
It happened again (in master) yesterday:
https://ci.appveyor.com/project/PowerShell/powershell/build/v6.1.0-preview.9751

**Comment by TravisEz13** [comment]
The last two hangs I saw where in this code: https://github.com/PowerShell/PowerShell/blob/master/tools/appveyor.psm1#L551

I'm guessing that AppVeyor is hanging after we throw the error back to appveyor.  
Finish is a really wierd place to be doing this type of stuff... building a package and testing it.  I would refactor this into a different bulid and test job if I had the time and see if it behaves better.

**Comment by iSazonov** [comment]
Maybe don't throw - write an error and `exit -1`?

**Comment by RDIL** [comment]
This is fixed now
