### ISSUE TITLE
Provide a way to only return specified return value

### ISSUE THREAD

**Issue by jez9999** [PowerShell/PowerShell#7041]
PowerShell default behaviour is to return everything that has been output in a function, which can be very annoying when you get a function that outputs something and you have to spend time figuring out which function is outputting noise and then explicitly redirect the output to null with ` | Out-Null`.  It would be very useful if you could prevent PowerShell doing this, maybe by decorating the function declaration with an attribute `[ExplicitReturn]` or maybe a keyword like `ReturnOnly $RetVal` or something which would empty the output buffer and only populate it with the value of `RetVal`.

**Comment by markekraus** [comment]
Hi @jez9999 I'm going to close this as a duplicate. Please comment on  #3669
