### ISSUE TITLE
pwsh hangs if omi spnego-ntlmv2 is not correctly configured on a Linux Client

### ISSUE THREAD

**Issue by raghushantha** [PowerShell/PowerShell#7043]
Steps to reproduce
------------------

- On a Ubuntu 16.04 machine, deploy PSCore 6.1.0 preview 2
- Configure omi client to use spnego-ntlmv2 as per instructions:
https://github.com/Microsoft/omi/blob/master/Unix/doc/setup-ntlm-omi.md
- Ensure $env:NTLM_USER_FILE env var is missing or incorrectly configured
- Try remoting to any Windows target (Invoke-Command / Enter-PSSession) -Authentication Negotiate

```powershell

```

Expected behavior
-----------------
- Invoke-Command / Enter-PSSession fail and control returns to user
```none

```

Actual behavior
---------------
- Invoke-Command / Enter-PSSession hangs indefinitely
- Note: This is a blocker for CloudShell - if the user's environment is incorrectly configured, Shell hangs and needs to be restarted.
```none

```

Environment data
----------------

```powershell
> $PSVersionTable

PS /home/localadmin> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.2
PSEdition                      Core
GitCommitId                    v6.1.0-preview.2
OS                             Linux 4.13.0-1018-azure #21-Ubuntu SMP Thu May 17 13:58:38 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by dantraMSFT** [comment]
@raghushantha There is a known hang in preview-2 and earlier.  Would you try this with a daily build to ensure it is not something new?

**Comment by raghushantha** [comment]
@dantraMSFT  Thanks. I can confirm that the hang issues are resolved in latest nightly builds

```
 $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.9958
PSEdition                      Core
GitCommitId                    v6.1.0-preview.9958
OS                             Linux 4.13.0-1018-azure #21-Ubuntu SMP Thu May 17 13:58:38 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by dantraMSFT** [comment]
Here's the PR that fixes this.
https://github.com/PowerShell/psl-omi-provider/pull/115
