### ISSUE TITLE
When creating file using -Path c: without a backslash, file created in the drive root and not in the current folder.

### ISSUE THREAD

**Issue by sethvs** [PowerShell/PowerShell#7048]
Steps to reproduce
------------------

```powershell
PS C:\Folder> New-Item -Path c: -Name testfile.txt
```

Expected behavior
-----------------

```none
File is created in the C:\Folder directory
```

Actual behavior
---------------

```none
File is created in the root of the drive c:\
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.705
PSEdition                      Core
GitCommitId                    v6.1.0-preview.705
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kilasuit** [comment]
@sethvs  - I Don't think this is an issue as this is expected behaviour because you are telling New-item to create the file in the C: directory 

If you leave off `-Path C:` it will create that file in the current directory which in this case is `C:\Folder`

**Comment by sethvs** [comment]
@kilasuit It is the behavior of the 6.1.0-preview.2 version and earlier.

**Comment by kilasuit** [comment]
@sethvs - I think this is expected behaviour and your use is more of an incorrect edge use case than being an actual issue - because you are explicitly telling New-Item what Path you want it to create in which is `C:` - as far as i know this is how New-Item has worked since v3 and whist it never crosses my mind to ever use drive directories without the slash this I don't think is unexpected behaviour in the slightest

if you had

``` powershell
New-Item -Path C:\folder1\folder2\ -Name testfile.txt
```
this will create the file in `C:\folder1\folder2\ ` which is in my opinion exactly as it was designed to do so and ergo is the designed and expected behaviour.

However if you do this

``` powershell
Set-Location C:\folder1\
New-Item -Path .\folder2\ -Name testfile.txt
```
this creates this in the folder2 directory as intended

also take this example 

```powershell
Set-location HKLM:\
New-Item -Path C:\temp -Name Test.ps1 -Value '$pwd'
```

You would not expect a ps1 file to be created in HKLM - or would you?

**Comment by iSazonov** [comment]
I'd add that the behavior came from cmd.exe - `dir c;`  works as `dir c:\`.

**Comment by sethvs** [comment]
Guys, please pay attention:

Windows PowerShell 5.1: file is created in **current** path - C:\Folder

```
[5.1] PS C:\Folder> New-Item -Path c: -Name testfile.txt


    Directory: C:\Folder


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        6/14/2018  12:30 PM              0 testfile.txt
```

PowerShell Core 6.0.2: file is created in **current** path - C:\Folder

```
[6.0.2] PS C:\Folder> New-Item -Path c: -Name testfile.txt


    Directory: C:\Folder


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        6/14/2018  12:32 PM              0 testfile.txt
```

PowerShell Core 6.1.0-preview.2: file is created in **current** path - C:\Folder

```
[6.1.0-preview.2] PS C:\Folder> New-Item -Path c: -Name testfile.txt


    Directory: C:\Folder


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        6/14/2018  12:28 PM              0 testfile.txt
```

PowerShell Core 6.0.1-preview.3: **file is created in root path - C:\\**

```
[6.1.0-preview.3] PS C:\Folder> New-Item -Path c: -Name testfile.txt


    Directory: C:\


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        6/14/2018  12:29 PM              0 testfile.txt
```

Again, this was changed with PR #6774.
My fix for this is in #7033.

**Comment by sethvs** [comment]
@iSazonov Nope.

`dir c:\` lists the root of the drive
```
C:\Folder>dir c:\
 Volume in drive C has no label.
 Volume Serial Number

 Directory of c:\

06/13/2018  11:02 AM    <DIR>          Program Files
05/30/2018  09:08 AM    <DIR>          Program Files (x86)
12/28/2017  04:25 PM    <DIR>          Temp
05/13/2018  05:43 PM    <DIR>          Users
05/13/2018  06:00 PM    <DIR>          Windows

etc...
```
 while `dir c:` lists current folder
```
C:\Folder>dir c:
 Volume in drive C has no label.
 Volume Serial Number

 Directory of C:\Folder

06/14/2018  12:32 PM    <DIR>          .
06/14/2018  12:32 PM    <DIR>          ..
06/14/2018  12:32 PM                 0 testfile.txt
               1 File(s)              0 bytes
               2 Dir(s)
```

**Comment by iSazonov** [comment]
@sethvs Please update the PR description with the samples..

**Comment by sethvs** [comment]
@iSazonov Done.
