### ISSUE TITLE
need a mechanism for execute native commands with higher priority

### ISSUE THREAD

**Issue by chenyj796** [PowerShell/PowerShell#7055]
Steps to reproduce
------------------
I have a .ps1 file, contains some commands as below.
```powershell
swapoff -a && sed -i '/swap/d' /etc/fstab
echo -e "net.bridge.bridge-nf-call-ip6tables = 1\nnet.bridge.bridge-nf-call-iptables = 1\nvm.swappiness = 0" >> /etc/sysctl.conf
```

Expected behavior
-----------------
I hope it can execute correctly in a scope, like this:
```powershell
&{
    swapoff -a && sed -i '/swap/d' /etc/fstab
    echo -e "net.bridge.bridge-nf-call-ip6tables = 1\nnet.bridge.bridge-nf-call-iptables = 1\nvm.swappiness = 0" >> /etc/sysctl.conf
}
```
It means in the scope "&{}", native commands will have higher execution priority.

Actual behavior
---------------

```none
At line:1 char:12
+ swapoff -a && sed -i '/swap/d' /etc/fstab
+            ~~
The token '&&' is not a valid statement separator in this version.
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : InvalidEndOfLine

```

**Comment by BrucePay** [comment]
Hi @chenyj796, as the error message you're seeing states, `&&` is not currently implemented in PowerShell. For now, you will have to write something like
```
swapoff -a; if ($?) { sed -i '/swap/d' /etc/fstab }
```
> It means in the scope "&{}", native commands will have higher execution priority

I'm not sure I understand exactly what you're asking. `& { }` simply creates a new variable scope.  Why do you think it will change execution priority?

**Comment by chenyj796** [comment]
Thanks BrucePay,
Actually I hope pwsh can provide a syntax to contains scripts which come from .sh file immediately.
something likes "unsafe" keyword in C#:

unsafe{
    // here write some unmanaged codes like C++
}

**Comment by mklement0** [comment]
@chenyj796: It sounds like you're looking for a mechanism to _embed_ POSIX-like shell code (e.g., Bash code) in PowerShell.

Piping a here-string with such code to `/bin/sh` (or `/bin/bash`) allows you to do that already:

```powershell
@'
    swapoff -a && sed -i '/swap/d' /etc/fstab
    echo -e "net.bridge.bridge-nf-call-ip6tables = 1\nnet.bridge.bridge-nf-call-iptables = 1\nvm.swappiness = 0" >> /etc/sysctl.conf
'@ | /bin/bash
```

`$LASTEXITCODE` will contain the invoked shell's exit code.

Use the double-quoted here-string variety to include references to PowerShell variables and expressions.

**Comment by chenyj796** [comment]
Thanks mklement0, I got it.

**Comment by daxian-dbw** [comment]
@chenyj796 I'm closing this issue since your question has been answered.
