### ISSUE TITLE
Trouble generating powershell.inc using the msbuild target from internals.md

### ISSUE THREAD

**Issue by kylesferrazza** [PowerShell/PowerShell#7057]
Hi there, I am the maintainer of the [powershell](https://aur.archlinux.org/packages/powershell/) package for Arch Linux.

I was just working on updating the PKGBUILD for the latest version of dotnet, and encountered the following error message:
```
Unhandled Exception: System.ArgumentException: Cannot find the file that contains the reference list. The path '[build directory]/src/TypeCatalogGen/powershell.inc' doesn't exist.
```
After closer inspection, it seems that `powershell.inc` is not generated by the given msbuild target any more.

Is this an error on my end, or has the build process changed?

Steps to reproduce
------------------
Following the steps in [docs/building/internals.md](/PowerShell/PowerShell/blob/master/docs/building/internals.md)
```bash
dotnet msbuild src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj /t:_GetDependencies "/property:DesignTimeBuild=true;_DependencyFile=$(pwd)/src/TypeCatalogGen/powershell.inc" /nologo
```

Expected behavior
-----------------
powershell.inc gets generated at `src/TypeCatalogGen/powershell.inc`.

Actual behavior
---------------
Powershell.inc is not created, but no errors are reported.

**Comment by rjmholt** [comment]
HI @kylesferrazza! How are you building PowerShell itself? I'm not very savvy on `.inc` files, but have you tried `Start-PSBuild <other options> -TypeGen`?

**Comment by iSazonov** [comment]
@kylesferrazza The change is in .Net Core. Please see code and comments
https://github.com/PowerShell/PowerShell/blob/master/build.psm1#L1922-L1940

**Comment by kylesferrazza** [comment]
@iSazonov thanks! That fixed it.

**Comment by daxian-dbw** [comment]
I will update the document `internals.md`. Will close this issue along with the doc update.

**Comment by iSazonov** [comment]
@kylesferrazza If you have automatically build indicator we could add it in our readme.md to see Arch Linux night build status.
