### ISSUE TITLE
Should namespaces should be case perserving/Case-Insensitive?

### ISSUE THREAD

**Issue by jpsnover** [PowerShell/PowerShell#706]
Discuss. (I don't know what the right answer is)

**Comment by Zsoldier** [comment]
case-insensitive.  I should be able to designate when I need case-sensitive.

**Comment by joeyaiello** [comment]
As stated in #3573, right now `Remove-Module` is case-insensitive, and `Import-Module` is case-sensitive. 

I still think my [original principles](https://github.com/PowerShell/PowerShell/issues/706#issuecomment-225667423) apply to this scenario.

**Comment by joeyaiello** [comment]
Long discussion about case sensitivity in general by @PowerShell/powershell-committee today. 

Some starting principles:
* C# (and by extension, .NET) is fully case sensitive (types, variables, methods, etc.)
* *Internally*, PowerShell is case-insensitive (PS variables, functions, cmdlets)
  - There are exceptions (`#region` or comment-based help, for instance), but for the sake of this disucssion, I think that's irrelevant.
* For most cases, filesystems are case-sensisitive (even on Windows, it's tricky, but NTFS can have two files with the same case).
* On non-Windows platforms, environment variables are case-sensitive. PowerShell already respects the platform behavior here.
* Tab completion is interactive where we allow all kinds of things that aren't possible with scripted behavior (which has to be deterministic)

As I linked above, there's 4 different cases that have to be solved for (I'm going to use "Namespace" as the stand-in term for all the things being discussed in this thread)
1. One option which is an exact match
    * Namespace: Apple; Input: Apple
1. One match which doesn't match the given case
    - Namespace: Apple; Input: apple
1. Multiple matches where one matches the given case
    - Namespaces: Apple, apple; Input: Apple
1. Multiple matches where none match the given case
    - Namespaces: Apple, apple; Input: aPPLE

Everyone in the room agreed that 1 and 3 should always match the exact match. From there, we agreed that 2 and 4 shouldn't "do something random" by calling the incorrect match. 

However, we also agreed that tab-completing in a case-insensitive way is highly desirable so as to correct typing errors. We already do this for .NET namepsaces (e.g. `[environme<tab>` completes to `[System.Environment]`). (It should probably go without saying, but this would be implemented as a PSReadline feature and should be exposed as a configurable option.)

Bug to file that could make this all annoying: `Move-Item` and `Rename-Item `can't change a file's case in place

**Comment by joeyaiello** [comment]
Clarifying question to @PowerShell/powershell-committee based on #1621. The statement "internally, PowerShell is case-insensitive" breaks down when you look at modules. I've elaborated in that issue.

**Comment by iSazonov** [comment]
Is there _really_ namespaces differing only by case? In C#?

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and modules paths and names should be case-insensitive
