### ISSUE TITLE
PSCore-Preview.3 - Fix Ubuntu 18.04 missing PWSH path when calling PowerShell.

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#7062]
Steps to reproduce
------------------
After installing deb package, type 'pwsh'.

```powershell
maxt@ubuntu:~$ pwsh

Command 'pwsh' not found, did you mean:

  command 'wsh' from deb wcc
  command 'ppsh' from deb ppsh
  command 'posh' from deb posh
  command 'pdsh' from deb pdsh

Try: sudo apt install <deb name>

maxt@ubuntu:~$
```

Expected behavior
-----------------
type: pwsh, then will open PowerShell Core.
```none

```

Actual behavior
---------------
pwsh can't be found to execute
```none

```

Workaround
--------------
Type the full path:
```
/opt/microsoft/powershell/6-preview/pwsh

Environment data
----------------

<!-- provide the output of $PSVersionTable -->

```powershell
PS /home/maxt> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.3
PSEdition                      Core
GitCommitId                    v6.1.0-preview.3
OS                             Linux 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


PS /home/maxt> cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
PS /home/maxt> 

```
![ubun1804_pwsh_2018-06-13_19-38-02](https://user-images.githubusercontent.com/19892435/41383969-5876576c-6f41-11e8-986a-c8fe9ac16ec9.jpg)

**Comment by markekraus** [comment]
Hi @MaximoTrinidad ! Did you try what was listed in the release notes?

> Note: In order to be able to deliver the PowerShell Core preview release and not deliver it to users expecting the stable release, we have renamed the preview package to `powershell-preview` and allowed it to be installed side by side with the stable package. This resulted in the symbolic link which exposes PowerShell to the Unix systems to be renamed. It was renamed to `pwsh-preview` for both macOS and Linux. We are considering something similar for Windows.

**Comment by markekraus** [comment]
```none
mark@posh-ubuntu:~$ pwsh-preview
PowerShell v6.1.0-preview.3
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS /home/mark> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.3
PSEdition                      Core
GitCommitId                    v6.1.0-preview.3
OS                             Linux 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by MaximoTrinidad** [comment]
@markekraus 

Not really! I went straight to the instruction docs and then did the deb package installation. 

I will check the release notes!  Hehe
:)

**Comment by markekraus** [comment]
@MaximoTrinidad The instruction docs are for release versions. Preview and RC's live and die by the release notes. 😃

**Comment by MaximoTrinidad** [comment]
Ah! Got it now! 

Well, a little bit of pain won't hurt. I'm guessing that's why the deb package is available.

Thanks for clarifying!
:)
