### ISSUE TITLE
write-host -NoNewline parameter is ignored with powershell 5.1

### ISSUE THREAD

**Issue by sashah363** [PowerShell/PowerShell#7068]
Steps to reproduce
------------------

Starting with WMF 5.1 the -NoNewLine option for Write-Host is essentially ignored.

Simple example: 
PS C:\> Write-Host "no newline test " -NoNewline

Expected behavior
-----------------
no newline test PS C:\>

Actual behavior
---------------
no newline test 
PS C:\>

Environment data
----------------

PS version Table is as follows.

Name Value 
---- ----- 
PSVersion   5.1.14409.1012 
PSEdition    Desktop 
PSCompatibleVersions    {1.0, 2.0, 3.0, 4.0...} 
BuildVersion    10.0.14409.1012 
CLRVersion    4.0.30319.42000 
WSManStackVersion    3.0 
PSRemotingProtocolVersion    2.3 
SerializationVersion    1.1.0.1

**Comment by iSazonov** [comment]
Right test is
```powershell
Write-Host "no newline test " -NoNewline ; write-host "qqqqq"
Write-Host "no newline test " ; write-host "qqqqq"
```

**Comment by sashah363** [comment]
@iSazonov 
As per microsoft docs, it should work for single line command also. Please refer below link.
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/write-host?view=powershell-5.1

**Comment by BrucePay** [comment]
Hi @sashah363 It's actually the examples in the documentation that are problematic. `Write-Host -NoNewLine` works properly as @iSazonov  demonstrates with his examples. What you are seeing is that, after a command is run, the console host fixes the cursor position before emitting the prompt (which is exactly what it should do.)  You can see the code at [ConsoleHost.cs:2417](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs#L2417). I suspect the doc examples date back quite a ways when we were less sophisticated in our handling of prompts.

**Comment by iSazonov** [comment]
@sashah363 You could open new Issue in [PowerShwll-Docs](https://github.com/PowerShell/PowerShell-docs/) repo.

**Comment by alexandair** [comment]
@BrucePay @iSazonov 
Maybe this example is a little bit more obvious:
```
PS C:\> 1,2,3,4 | Write-Host
1
2
3
4
PS C:\> 1,2,3,4 | Write-Host -NoNewline
1234
PS C:\>
```
