### ISSUE TITLE
In WFC a shared disk device has a dependency on a cluster resource like SQL Server. With the introduction of CSV (Cluster Shared Volumes) this dependency isn't there any longer because we assume that a CSV is always there. That's right (sometimes), but if a SAN failure happens, the CSV or several volumes presenting the CSV will be gone and SQL Server will start again. Ths brings SQL Server in an unpredictable situation and happened. So we like to have a PowerShell-Script (running on every node on the cluster) monitoring the CSV and stopping the group hosting the SQL resources if CSV failures happen.

### ISSUE THREAD

**Issue by royalharikrishna** [PowerShell/PowerShell#7069]
In WFC a shared disk device has a dependency on a cluster resource like SQL Server. With the introduction of CSV (Cluster Shared Volumes) this dependency isn't there any longer because we assume that a CSV is always there. That's right (sometimes), but if a SAN failure happens, the CSV or several volumes presenting the CSV will be gone and SQL Server will start again. Ths brings SQL Server in an unpredictable situation and happened. 
So we like to have a PowerShell-Script (running on every node on the cluster) monitoring the CSV and stopping the group hosting the SQL resources if CSV failures happen.

**Comment by BrucePay** [comment]
Hi @royalharikrishna I'm not sure what the actual issue is. Is there some problem in PowerShell that is preventing you from writing your script?

**Comment by Tadas** [comment]
I think you want to read these, no need to complicate your WFC with an ad-hoc PowerShell script.

- http://level7techgroup.com/blog/?p=823
- https://docs.microsoft.com/en-us/sql/sql-server/failover-clusters/windows/add-dependencies-to-a-sql-server-resource?view=sql-server-2017

Unless someone wants to write the script this can probably be closed...
