### ISSUE TITLE
PowerShell v6.1.0-preview.3 on macOS - PowerShell.app does not start PowerShell

### ISSUE THREAD

**Issue by najeebanwer** [PowerShell/PowerShell#7074]
on macOS, the PowerShell.app/Contents/MacOS/PowerShell.sh script does not invoke pwsh-preview; it incorrectly tries to invoke pwsh.

**Comment by najeebanwer** [comment]
on macOS, the PowerShell.app/Contents/MacOS/PowerShell.sh script does not invoke pwsh-preview; it incorrectly tries to invoke pwsh.

**Comment by MaximoTrinidad** [comment]
I got Preview.3 working on my MacOS.
```
PS /Users/maxt> sw_vers                                                                                                 ProductName:    Mac OS X                                     
ProductVersion: 10.13.5                                         
BuildVersion:   17F77 
```
![macos_preview3_2018-06-15_12-34-57](https://user-images.githubusercontent.com/19892435/41479631-d46b30fa-7099-11e8-8f27-285616a7649f.jpg)

**Comment by mklement0** [comment]
@MaximoTrinidad:

Yes, invoking `pwsh-preview` _directly_ works as intended, but @najeebanwer  is referring to the `.sh` file that is part of the `/Applications/PowerShell.app` macOS application bundle.

What it _should_ be invoking is:

```sh
open /usr/local/bin/pwsh-preview
```

Instead, it invokes:

```powershell
open /usr/local/bin/pwsh
```

That is, it invokes an installed *released* Powershell version (if present), not the _preview_ version.

**Comment by mklement0** [comment]
@najeebanwer: Glad to hear we're on the same page.

Now that I think about it: shouldn't the conclusion be that there should be a parallel `/Applications/PowerShell-preview.app` bundle, alongside `/Applications/PowerShell.app`?

**Comment by najeebanwer** [comment]
@mklement0\: That sounds like a reasonable conclusion. 
However, since the PowerShell.app bundle is associated with a particular release, presumably it would be updated to invoke the correct PowerShell target (either pwsh or pwsh-preview).

**Comment by mklement0** [comment]
Given that `pwsh-preview` was specifically introduced to allow installation _alongside_ regular releases (`pwsh`), it makes sense to me to mirror this distinction in separate  `.app` bundles.

This would obviate the need to decide whether the single `/Applications/PowerShell.app` bundle should be updated for preview versions as well (which currently doesn't happen).

**Comment by najeebanwer** [comment]
@mklement0\: I agree.

**Comment by MaximoTrinidad** [comment]
Thanks for the explanation!
:)
