### ISSUE TITLE
PowerShell v6.1.0-preview.3: Non-GAC DLLs Not Found

### ISSUE THREAD

**Issue by rockerinthelocker** [PowerShell/PowerShell#7076]
While loading non-GAC DLLs works as shown below

```
PS C:\Program Files\PowerShell\6-preview> [System.Reflection.Assembly]::LoadFile($GeoIpDbLibrary)

GAC    Version        Location
---    -------        --------
False  v4.0.30319     C:\GeoIP\MaxMind.Db.dll

```
, PowerShell v6.1.0-preview.3 fails with

```
Could not load file or assembly 'MaxMind.Db, Version=2.0.0.0, Culture=neutral, PublicKeyToken=66afa4cc5ae853ac'. The system cannot find the file specified.
At line:1 char:1
+ $asnReader = [MaxMind.GeoIP2.DatabaseReader]::new($GeoIpAsnDb)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (:) [], FileNotFoundException
+ FullyQualifiedErrorId : System.IO.FileNotFoundException

```
when utilizing APIs afterwards like so:

`PS C:\Program Files\PowerShell\6-preview> $asnReader = [MaxMind.GeoIP2.DatabaseReader]::new($GeoIpAsnDb)
`
Process Monitor shows that pwsh.exe searches for the DLL in GAC instead of the file path given by LoadFile():

```
C:\Windows\Microsoft.NET\assembly\GAC_MSIL\MaxMind.Db
C:\Windows\Microsoft.NET\assembly\GAC_64\MaxMind.Db

```
Previous PowerShell versions (including v6.1.0-preview.2) work just fine so something seems to be broken in v6.1.0-preview.3.

**Comment by iSazonov** [comment]
@daxian-dbw Could you please comment?

**Comment by rockerinthelocker** [comment]
See #7326 for update. Closing this now @iSazonov @daxian-dbw .
