### ISSUE TITLE
WindowsPE: Openfiledialog doesn´t work

### ISSUE THREAD

**Issue by logg-sar** [PowerShell/PowerShell#7077]
Steps to reproduce
------------------
As seen here: https://blogs.technet.microsoft.com/heyscriptingguy/2009/09/01/hey-scripting-guy-can-i-open-a-file-dialog-box-with-windows-powershell/

This is the crucial part:

[System.Reflection.Assembly]::LoadWithPartialName("System.windows.forms")
$OpenFileDialog = New-Object System.Windows.Forms.OpenFileDialog
$OpenFileDialog.ShowDialog()

Expected behavior
-----------------
The open file dialog is opening (as in full/normal windows)

Actual behavior
---------------
With PS 5.1.16299.15
`PS S:\Temp> $OpenFileDialog.ShowDialog()
Exception calling "ShowDialog" with "0" argument(s): "Creating an instance of the COM component with CLSID {DC1C5A9C-E88A-4DDE-A5A1-60F82A20AEF7} from the
IClassFactory failed due to the following error: 80040111 ClassFactory cannot supply requested class (Exception from HRESULT: 0x80040111
(CLASS_E_CLASSNOTAVAILABLE))."
At line:1 char:1
+ $OpenFileDialog.ShowDialog()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : COMException`

With PS 6.1.0-preview.3
Already `[System.Reflection.Assembly]::LoadWithPartialName("System.windows.forms")` is failing with
`Exception calling "LoadWithPartialName" with "1" argument(s): "Could not load file or assembly 'System.windows.forms, Culture=neutral, PublicKeyToken=null'. Operation is not supported. (Exception from HRESULT: 0x80131515)"
At line:1 char:2
+  [System.Reflection.Assembly]::LoadWithPartialName("System.windows.fo ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : FileLoadException`

Environment data
----------------
Windows PE [Microsoft Windows [Version 10.0.16299.5]]

PS S:\Temp> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.15
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.15
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

PS S:\Temp> $psversiontable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.3
PSEdition                      Core
GitCommitId                    v6.1.0-preview.3
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by BrucePay** [comment]
Hi @logg-sar WinForms is not currently supported by .NET Core so you can't use them from PowerShell Core. (.NET Standard 3.0 is expected to fix this.).   With PowerShell 5.1, have you made sure all required components are present in your WinPE image?
