### ISSUE TITLE
Format-Table left aligns header for right aligned column

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShell#7078]
Steps to reproduce
------------------

```powershell
class X {	
	[string] $s
	[int] $I
}

[X] @{
	I = 1123098
	S = "Text"
}
```

Expected behavior
-----------------

```none
s          I
-          -
Text 1123098
```

Actual behavior
---------------

```none
s    I
-          -
Text 1123098
```

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.3
PSEdition                      Core
GitCommitId                    v6.1.0-preview.3
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

This does not happen on Windows PowerShell 5.1 or pwsh 6.0.2.

**Comment by powercode** [comment]
I think the problem only manifest when the right aligned item is the last column. In an effort to get rid of the padding at the end of the row, I think we might have gotten rid of the right-alignment padding.

@SteveL-MSFT Do you recognize any of this from your table formatting changes?

**Comment by SteveL-MSFT** [comment]
@powercode I think you're right.  @iSazonov and I added more tests to [Format-Table.Tests.ps1](https://github.com/PowerShell/PowerShell/blob/master/test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Table.Tests.ps1), but it looks like we missed cases where the header is shorter than the width.

Are you planning on submitting a PR?

**Comment by powercode** [comment]
I have other things I should catch up with first, but I think we should fix this before releasing.

**Comment by SteveL-MSFT** [comment]
@powercode no problem, I'll see about looking at this after my current PRs, just didn't want to work on it if you were going to.
