### ISSUE TITLE
Get the default PSModulePath at runtime?

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#7082]
Two questions on the PSModulePath in PowerShell Core:

1. Is the the default setting of PSModulePath in PS Core documented anywhere (e.g. online) in a way that is general and cross platform? Like a table of what it is on each supported platform, or a string with unexpanded platform-specific variables in it? (e.g. `$PSHOME/Modules:$AnotherPlace/SecondModuleDir`)
1. Is it possible to access the default PSModulePath at runtime? (Or to reset the current one?)

**Comment by SteveL-MSFT** [comment]
This is probably a `Documentation-Needed` situation.  Currently, you'll probably have to look at the [code](https://github.com/PowerShell/PowerShell/blob/8aec1585195e6d4871538aaa2ad2b112cf5fbfee/src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs)

**Comment by rjmholt** [comment]
It would also be nice to have it as an API endpoint perhaps (like a variable, static property, etc) -- like `[ModuleIntrinsics]::GetModulePath()` except without requiring arguments. Curious if anyone else has felt a need for that?

**Comment by mklement0** [comment]
What I feel is absent is not necessary the built-in default value, but a way to access the various well-known module locations by _scope_.

By analogy, let's take the example of `$PROFILE`, which contains the well-known profile locations as named-for-the-scope `NoteProperty` members:

```powershell
# Sample output when run on macOS
PS> $PROFILE | Get-Member -type noteproperty | Select Name, Definition

Name                   Definition
----                   ----------
AllUsersAllHosts       string AllUsersAllHosts=/usr/local/microsoft/powershell/6-preview/profile.ps1
AllUsersCurrentHost    string AllUsersCurrentHost=/usr/local/microsoft/powershell/6-preview/Microsoft.PowerShell_profile.ps1
CurrentUserAllHosts    string CurrentUserAllHosts=/Users/jdoe/.config/powershell/profile.ps1
CurrentUserCurrentHost string CurrentUserCurrentHost=/Users/jdoe/.config/powershell/Microsoft.PowerShell_profile.ps1
```

I think we should provide something similar for module locations, using scopes such as `AllUsers`,     `CurrentUser`, `System`, and `Custom` (the latter comprising all `$env:PSModulePath` entries in addition to the well-known locations).

I'm unclear on how best to surface this functionality, however. 

In theory, we could use the same approach as with `$PROFILE`: decorate the `$env:PSModulePath` `[string]` value with `NoteProperty` members, but that is somewhat obscure.

Then again, if properly documented, perhaps that's the way to go.

**Comment by SteveL-MSFT** [comment]
@BrucePay you should take @mklement0's suggestion as part of your `PSModulePath6` RFC

**Comment by fsackur** [comment]
I have submitted https://github.com/PowerShell/PowerShell-Docs/pull/3214 to add the *nix locations to the existing about_Modules and about_Environment_Variables docs.

**Comment by rjmholt** [comment]
Want to add that this may be of use in hosted PowerShell contexts where the hosting implementation might have reasons for using different paths for them all.

It might merit being able to set the scoped module paths in the `powershell.config.json` and exposing their location through some PowerShell API. (Like @mklement0, I'm not sure what shape that API should be -- but I'd opt for either a variable or a method call, with the latter being a more direct fit to the current implementation).

**Comment by rjmholt** [comment]
Oh good point. Yes, I wrote that method for 6.1. Windows PowerShell should have some method like that in it, but I don’t know what it is. The method I wrote is equivalent to just `”${env:windir}\System32\WindowsPowerShell\v1.0\Modules”`

**Comment by mklement0** [comment]
Thanks for the handy function, @rjmholt (also interesting to see the use of reflection to call the non-public methods - I hope we won't need that in the long run).

It seems that in Windows PowerShell only the method that returns the `CurrentUser` scope exists, so I've amended your function to add fallback values for Windows PowerShell.
(I've also changed the name to `Get-StandardModulePath`, shortened `WindowsPSSystem` to `WinPSSystem` and I'm using an _ordered_ hashtable for the result, which makes the function v3+; btw, you forgot to rename a couple of instances of `WindowsSystem` to `WindowsPSSystem` in your recent edit).

```powershell
#requires -version 3
function Get-StandardModulePath {
  param(
    [Parameter()]
    [ValidateSet('AllUsers', 'CurrentUser', 'System', 'WinPSSystem')]
    [string[]]
    $Scope
  )

  if ($Scope -eq 'WinPSSystem' -and ($IsLinux -or $IsMacOs)) {
    throw "The scope '$Scope' does not exist on non-Windows platforms."
  }

  if (-not $Scope) {
    $Scope = 'CurrentUser', 'AllUsers', 'System'
    if (-not ($IsLinux -or $IsMacOS)) {
      $Scope += 'WinPSSystem'
    }
  }

  $invokeModuleMethod = {
    $bindingFlags = [System.Reflection.BindingFlags]'static,nonpublic'
    $m = [System.Management.Automation.ModuleIntrinsics].GetMethod($args[0], $bindingFlags)
    $m.Invoke($null, @())
  }

  $paths = [ordered] @{}
  switch ($Scope) {
    'CurrentUser' {
      $paths.CurrentUser = try {
        & $invokeModuleMethod 'GetPersonalModulePath'
      }
      catch {
        # WinPS fallback.
        "$(Split-Path $PROFILE)\Modules"
      }
    }

    'AllUsers' {
      $paths.AllUsers = try {
        & $invokeModuleMethod 'GetSharedModulePath'
      }
      catch {
        # WinPS fallback.
        "$env:ProgramFiles\WindowsPowerShell\Modules"
      }
    }
          
    'System' {
      $paths.System = try {
        & $invokeModuleMethod 'GetPSHomeModulePath'
      }
      catch {
        # WinPS fallback.
        "$PSHOME\Modules"
      }
    }

    'WinPSSystem' {
      $paths.WinPSSystem = try {
        & $invokeModuleMethod 'GetWindowsPowerShellPSHomeModulePath'
      }
      catch {
        # WinPS fallback.
        "$PSHOME\Modules"
      }
    }
  }

  return $paths
}
```

**Comment by rjmholt** [comment]
@mklement0 Yeah I opened this issue because I think those methods (or something like them) should really be a public API, since they are a contract with PSGet

**Comment by mklement0** [comment]
Ah, of course, @rjmholt; so another thank you for opening this issue.

**Comment by rjmholt** [comment]
@

**Comment by rjmholt** [comment]
@SteveL-MSFT is there a reason #11057 is marked as closing this issue? I couldn't find any new mechanism to solve feature request in that PR

**Comment by JustinGrote** [comment]
Since this was erroneously closed, https://github.com/PowerShell/PowerShell/issues/15552 is probably the best location to continue discussion.
