### ISSUE TITLE
too much ".." in filename start with ls

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#7089]
I cannot determine the source of the problem. I suspect that it is related to the powershell engine. 
Please help find the cause and change the issue title.

Steps to reproduce
------------------

```
PS /root> ls /bin/b*    
../bin/base64  ../bin/basename	../bin/bash  ../bin/bashbug  ../bin/bashbug-64	../bin/bg  ../bin/bond2team  ../bin/bootctl  ../bin/busctl

PS /root> bash -c "ls /bin/b*"
/bin/base64  /bin/basename  /bin/bash  /bin/bashbug  /bin/bashbug-64  /bin/bg  /bin/bond2team  /bin/bootctl  /bin/busctl
```
ls /bin/*  **# same,more with ..**

Environment data
----------------

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.3
PSEdition                      Core
GitCommitId                    v6.1.0-preview.3
OS                             Linux 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by BrucePay** [comment]
Hi @chuanjiao10, on Linux we don't include an alias `ls -> Get-ChildItem` so what you're seeing is the behaviour of `/bin/ls`. If you run `Get-ChildItem /bin/b*`, you'll see what you expect.

**Comment by chuanjiao10** [comment]
My point is that the powershell implementation of "linux ls"  has a different return value than "bash -c". Two more points.

ls /bin/* # same,more with ..
-------------------------------------

```
PS /root> bash -c 'ls /bin/*'     
/bin/[					 /bin/grub2-render-label    /bin/nmtui-edit		   /bin/sg_xcopy
/bin/a2p				 /bin/grub2-script-check    /bin/nmtui-hostname		   /bin/sh
/bin/addr2line				 /bin/grub2-syslinux2cfg    /bin/nohup			   /bin/sha1sum
/bin/alias				 /bin/gsettings		    /bin/nproc			   /bin/sha224sum
/bin/apropos				 /bin/gsoelim		    /bin/nroff			   /bin/sha256sum
/bin/ar					 /bin/gtar		    /bin/nsenter		   /bin/sha384sum
====more====
```

```
PS /root> ls /bin/*          
../bin/[				   ../bin/grub2-render-label	../bin/nmtui-edit		 ../bin/sg_xcopy
../bin/a2p				   ../bin/grub2-script-check	../bin/nmtui-hostname		 ../bin/sh
../bin/addr2line			   ../bin/grub2-syslinux2cfg	../bin/nohup			 ../bin/sha1sum
../bin/alias				   ../bin/gsettings		../bin/nproc			 ../bin/sha224sum
../bin/apropos				   ../bin/gsoelim		../bin/nroff			 ../bin/sha256sum
../bin/ar				   ../bin/gtar			../bin/nsenter			 ../bin/sha384sum
../bin/arch				   ../bin/gtbl			../bin/numfmt			 ../bin/sha512sum
../bin/aria2c				   ../bin/gtroff		../bin/objcopy			 ../bin/showconsolefont

====more====
```

**Comment by mklement0** [comment]
@chuanjiao10: 

You've asked for a new issue title: here is my suggestion:

> Globbing for native utilities unexpectedly produces relative paths

To recap what is happening: In the context of invoking an external program (native utility), when PowerShell expands a wildcard pattern  _with an absolute path_ to matching paths, it currently unexpectedly expresses the matching paths as _relative to the current location_, via `../` path components.  
(By contrast, patterns based on relative paths expand as expected.)

To provide a simpler example:

```powershell
PS> Set-Location /tmp; /bin/echo /tm?
../tmp   # !! This should be /tmp, not a relative path
```

@BrucePay: Can you please reclassify this issue as a bug?

**Comment by BrucePay** [comment]
@mklement0  You are correct - the code that does globbing doesn't respect absolute paths.  It's a pretty simple fix.
