### ISSUE TITLE
Improve user guidance during automatic prompting for mandatory parameter values

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#7093]
### Background

In the absence of arguments provided for mandatory cmdlet / advanced function parameters, PowerShell automatically prompts the user.

These prompts support `!`-prefixed commands:

* `!?` displays the help message associated with the parameter at hand, assuming a `helpMessage` argument  was provided as part of the parameter's `[Parameter()]` attribute.

* `!""` allows entering an empty string as an argument - this is necessary for array-valued parameters that permit empty strings as elements, such as `[string[]]`-typed parameters with the `[AllowEmptyString()]` attribute, because submitting nothing (just pressing <kbd>Enter</kbd>) signals the end of the input for that parameter, i.e., it is how you signal that all array elements have been entered.

* `!!` is needed to escape a `!` at the beginning of a value; e.g., in order to submit `!foo`, `!!foo` must be typed.

As an aside: These commands unexpectedly also surface when you use `Read-Host -Prompt`, even though they serve no purpose there - see #4066.

### Problems with the current behavior

Currently, when a mandatory prompt is shown, only the `!?` command is mentioned, and only if the parameter at hand has a help message defined.

By contrast, the existence of `!""` and `!!` is not mentioned, and currently not even _documented_.

Similarly, it isn't documented that only _literal_ values can be entered by the user - no references to variables or subexpressions are evaluated as such.

Additional problems (not the focus of this issue):

* #4068 discusses how automatic prompting doesn't work (meaningfully) for parameters types `[scriptblock]`, `[hashtable]` or `[bool]` / `[switch]`, with a fix being considered that disables automatic prompting for `[scriptblock]`, `[hashtable]`, and fixes `[bool]` / `[switch]` prompting to present Y/N-style prompts.

* No tab completion is offered for `[ValidateSet()]`-constrained parameters, and entering an invalid value _aborts_ the prompt rather than given the user a chance to correct the problem.

* Conversely, empty input can result in unexpected conversion, such a empty input for a mandatory `[int]` parameter getting interpreted as `0`.

* As stated, only input of _literals_ is supported - allowing expressions would have to be carefully designed.

* A corollary of the above is that you cannot enter `$null` (for parameters with `[AllowNull()]`).

* The wording of the prompt messages should be improved.

* A potential UX improvement would be to present the resulting command for final inspection to the user before submitting it, both as a safety measure and as a teaching tool (to show how the command could have been submitted non-interactively).

In short: A nontrivial amount of effort would be needed to make automatic prompting work comprehensively and in a user-friendly manner. 
The solution proposed here is just a small step in that direction.

### Possible solution

_Eliminate_ the prompt commands altogether:

* Simply print the help message *by default*, if present, obviating the need for the `!?` command.

* A `!` at the start of a user-typed value would then no longer require escaping as `!!`.

* The only downside is the loss of `!""` for entering empty strings, but given the rarity of the need for this and the other holes in the automatic prompting functionality, that price seems worth paying.

Of course, if automatic prompting is ever fixed to work comprehensively, the ability to enter empty strings would need to be restored somehow.
At this point that doesn't sound likely, however.

Environment data
----------------

Written as of:

```powershell
PowerShell Core v6.1.0-preview.3
```

**Comment by mklement0** [comment]
@vexx32:

Re `HelpMessage`: Indeed, and it's what I meant to say by:

> Simply print the help message _by default_, if present, obviating the need for the `!?` command.

**Comment by Jaykul** [comment]
I'd love to see the HelpMessage (if any) printed by default. 
Further than that, if there is no HelpMessage, I'd like to see the parameter help printed.

If we think that might be overwhelming, add a preference variable like `$PSHelpfulPrompts = $true` or whatever.
