### ISSUE TITLE
Cryptography.X509Certificates.X509Certificate2Collectio.Export method throws exception on Linux (Azure Cloudshell)

### ISSUE THREAD

**Issue by mosharafMS** [PowerShell/PowerShell#7095]
Using the same code on pwsh on Windows 10 works but fails on Linux (Azure Cloud Shell). 
When using this code snipped 

   ```
             $certSecret=Get-AzureKeyVaultSecret -VaultName $keyVaultName -Name sslcertOrigin
		$SecretBytes = [System.Convert]::FromBase64String($certSecret.SecretValueText)
		$certCollection = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2Collection
		$certCollection.Import($SecretBytes,$null,[System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable)

		$certPassword="RandomPassword"
		$protectedCertificateBytes = **$certCollection.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Pkcs12, $certPassword)**

```
the last line throws this exception 
**Exception calling "Export" with "2" argument(s): "error:0D0C6070:asn1 encoding routines:ASN1_item_pack:encode error"
At line:1 char:1
+ $protectedCertificateBytes = $certCollection.Export([System.Security. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : OpenSslCryptographicException**

Steps to reproduce
------------------
Use the above code snipped with Azure Cloud Shell (Bash). Same code works fine on Windows 10

Expected behavior
-----------------

success

Actual behavior
---------------

Exception 
**Exception calling "Export" with "2" argument(s): "error:0D0C6070:asn1 encoding routines:ASN1_item_pack:encode error"
At line:1 char:1
+ $protectedCertificateBytes = $certCollection.Export([System.Security. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : OpenSslCryptographicException**

Environment data
----------------

PS Azure:\> $PSVersionTable
```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Linux 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```Bash
PS Azure:\> uname -a
Linux cc-fbeed40e-1468250273-6f9qr 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mosharafMS** [comment]
**Update:**
Using Pwsh  v6.1.0-preview3 on Ubuntu 18.04 works fine. Don't know if it's the Ubuntu version used in Cloud Shell or this bug has been fixed in preview3

**Comment by SteveL-MSFT** [comment]
cc @HemantMahawar @edyoung

**Comment by iSazonov** [comment]
@SteveL-MSFT Can we close the issue?
