### ISSUE TITLE
Double quote delimiter in Import-Csv

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#7110]
Why double quote delimiter has a special behavior (skipping columns) in Import-Csv?
Is this expected/documented/RFC-defined behavior?

```powershell
# Input 1.csv
# a1""a3
# v1"v2"v3

Import-csv .\1.csv -Delimiter '"'

# Output
a1 a3
-- --
v1 v3
```

```powershell
# Input 2.csv
# a1,,a3
# v1,v2,v3

Import-csv .\2.csv -Delimiter ','

# Output
WARNING: One or more headers were not specified. Default names starting with "H" have been used in place of any missing headers.

a1 H1 a3
-- -- --
v1 v2 v3
```

**Comment by iSazonov** [comment]
@SteveL-MSFT Have you any information about the special behavior? Is this side affect (bug) in the code or a standard?

**Comment by vexx32** [comment]
That's probably somewhere between a "why would you use that as delimiter" and "special case that needs dealing with". CSV entries with spaces need to be enclosed with (usually) double quotes. I don't know if there's another possible enclosing character that can be relied upon, really (single quotes maybe?)

The trouble with CSV is there isn't a concrete "standard" just a bunch of very similar implementations with some differences scattered throughout.

But I've never seen a CSV with double quotes as delimiter before... I'd be of the inclination that it be treated as a reserved character and not be permitted as a delimiter for parsing at all, but...

**Comment by iSazonov** [comment]
> But I've never seen a CSV with double quotes as delimiter before... 

The Issue is that we _accept_ the delimiter and _skip_ one column. So I'd expect that we either do not accept the delimiter or do not skip the column.

**Comment by vexx32** [comment]
The former sounds perfectly fine to me, but I'm unsure if there's a valid reason to use a double quote as a delimiter.

**Comment by SteveL-MSFT** [comment]
Took a look at the code, as noted above, double quotes is a special character for containing whitespace so that this:

> "foo,bar","apple"

becomes:

> foo,bar  apple

and not:

> foo  bar  apple

So using `"` as the delimiter breaks this.  I think that unless there's a real scenario to use the double quote as a delimiter, it's not worth making a change.  Otherwise, we'd special case if double quote is used, you cannot have whitespace as part of a value.

**Comment by iSazonov** [comment]
@SteveL-MSFT My question is should we address  scenario from my repo steps where we lost column?

**Comment by SteveL-MSFT** [comment]
@iSazonov there's probably a bug in the logic when double quotes are used as the delimiter as there's special code already to handle double quotes to preserve whitespace.  I think the question is whether it's worthwhile to spend time investigating and fixing something that is a corner case.

**Comment by iSazonov** [comment]
>  I think the question is whether it's worthwhile to spend time investigating and fixing something that is a corner case.

Yes, I think we can label this with Up-For-Grabs and Hackathon.
