### ISSUE TITLE
Unexpected stringification behavior of Get-Help output

### ISSUE THREAD

**Issue by tlindsay42** [PowerShell/PowerShell#7116]
Steps to reproduce
------------------
From @mklement0's great update in  https://github.com/PowerShell/PowerShell/issues/7107#issuecomment-398414775
> Applying `.ToString()` directly always yields the empty string:
> ```powershell
> PS> '' -eq (Get-Help Get-ChildItem).ToString()
> True
> ```
>
> By contrast, implicit stringification - which happens inside "..." and when piping to a string-binding cmdlet such as Select-Object - produces the equivalent of .psobject.ToString();
>
> ```powershell
> PS> (Get-Help Get-ChildItem).psobject.ToString()
> @{alertSet=@{alert=System.Management.Automation.PSObject[]}; inputTypes=@{inputType=@{type=@{name=System.String}; description=System.Management.Automation.PSObject[]}}; relatedLinks=@{navigationLink=System.Management.Automation.PSObject[]}; details=@{verb=Get; noun=ChildItem; description=System.Management.Automation.PSObject[]; name=Get-ChildItem}; parameters=@{parameter=System.Management.Automation.PSObject[]}; examples=@{example=System.Management.Automation.PSObject[]}; returnValues=@{returnValue=System.Management.Automation.PSObject[]}; syntax=@{syntaxItem=System.Management.Automation.PSObject[]}; description=System.Management.Automation.PSObject[]; xmlns:maml=http://schemas.microsoft.com/maml/2004/10; xmlns:command=http://schemas.microsoft.com/maml/dev/command/2004/10; xmlns:dev=http://schemas.microsoft.com/maml/dev/2004/10; xmlns:MSHelp=http://msdn.microsoft.com/mshelp; Name=Get-ChildItem; Category=Cmdlet; Synopsis=Gets the items and child items in one or more specified locations.; Component=; Role=; Functionality=; PSSnapIn=; ModuleName=Microsoft.PowerShell.Management}
> ```
>
> In fact, this behavior is tied to type `[pscustomobject]`, which is what `Get-Help` outputs: #6163 asks for `.ToString()` and `.psobject.ToString()` to be the same, though in the specific case of Get-Help output you could argue that the ETS should be used to provide a `.ToString()` method that renders the help text (an implicit Out-String).

Expected behavior
-----------------
`( Get-Help -Name $cmdletName ).ToString()` should return the help content in a `[string]` object.

Actual behavior
---------------
`( Get-Help -Name $cmdletName ).ToString()` returns a `$null` string (eg: `''`).

Environment data
----------------

```powershell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.3
PSEdition                      Core
GitCommitId                    v6.1.0-preview.3
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

References:
* #7107 
* #6163

**Comment by BrucePay** [comment]
The `.ToString()` on `PSCustomObject` explicitly returns an empty string which is pretty much useless.  Having `PSCustomObject.ToString()` do what `PSObject.ToString()` does makes sense. Note - this is a breaking change as there is a slim possibility that people might use `.ToString() -eq ''` to detect `PSCustomObject`.

For help objects specifically, which are "typeless" `PSCustomObjects`, `Get-Help` could add a script method to each instance it emits along the lines of
```powershell
Add-Member -Force -InputObject $h ScriptMethod ToString {$this | Out-String }
```
so that `.ToString()` would render the help object as a formatted string.
