### ISSUE TITLE
Need review uses of PsUtils.IsRunningOnProcessorArchitectureARM()

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#7121]
Inspired by #7046.
Are all uses of this code `PsUtils.IsRunningOnProcessorArchitectureARM()` relevant?

https://github.com/PowerShell/PowerShell/search?utf8=%E2%9C%93&q=IsRunningOnProcessorArchitectureARM&type=

**Comment by SteveL-MSFT** [comment]
We should re-review this.  That old check was for WinRT which was for Surface tablets competing with iPads. Windows on ARM64 is now full featured so many of those old checks likely are no longer relevant or correct.
