### ISSUE TITLE
Possible performance enhancement with Write-* cmdlets

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/PowerShell#7124]
This is more of a question than an issue at this point.

I wonder if PowerShell could invoke Write-_Stream_ (Write-Verbose, Write-Debug, etc.) commands differently, still performing parse checking on scripts containing those commands to make sure they parse properly, but not actually invoking those commands unless the preference variable is appropriately configured or the parameter to make that stream's output show up was used directly or via $PSDefaultParameterValues.

For example, `Write-Verbose -Message 'Hello' -Verbose` would be invoked, but `Write-Debug -Message $(Get-Service | Format-List * | Out-String)` would not, unless $DebugPreference was set to something other than SilentlyContinue or Ignore).

For anyone familiar with the details surrounding how PowerShell executes commands, can someone comment on the feasibility/possibility of skipping commands that should be skipped as a way to optimize script performance? It's not hard to see how it could make a big difference, while encouraging broader use of Write-Verbose and Write-Debug at the same time (for the latter, especially if #7122 gets implemented).

cc: @lzybkr

**Comment by lzybkr** [comment]
There are certainly some significant performance gains possible, but I don't think targeting the `Write-` commands is a good approach.

Some issues:

* What if the command is a function or alias, not the built in cmdlet?
* What if the command forces the action, e.g. `Write-Verbose "Hi there" -Verbose`?

These 2 issues hit general performance issues (command lookup and parameter binding) that have room for **major** improvements.

If command lookup and parameter binding are fast, I have a feeling you won't care about the minor overhead of actually calling into the `Write-` commands.

**Comment by KirkMunro** [comment]
Thanks @lzybkr, that's good food for thought.

**Comment by iRon7** [comment]
I came to the same question from a security and performance view, taking the following example:

```
$Credential = Get-Credential
Write-Debug "Password: $(($credential.GetNetworkCredential()).Password)"
```

That the `Write-Debug` evaluates the message appears from:

```
Write-Debug "$(Write-Host 'Host') Debug"
```
Where the word `Host` is always displayed no matter of the `$DebugPreference`
From my point of view it would make sense that the `$DebugPreference` (and similar `Write-*` cmdlets) would have (default?) `Bypass` value.

**Comment by vexx32** [comment]
`Write-Host` is explicitly coded to display by default unless you set `-InformationAction Ignore`, it's kind of what it's designed for. Subexpressions are evaluated before being passed to the command invocation.

I'd also contend that silencing or skipping the write cmdlets entirely would only ever make sense if their corresponding `Action` parameter or `Preference` variable is set explicitly to `Ignore` -- in all other cases users or administrators will often want the data to be captured in a transcript if one is running, so skipping the call completely isn't often really an option.

@lzybkr you mention that there are improvements to be made here. Is this a current focus for the PS team, or is this something I could take a look at? (And if so, I'd appreciate a pointer to where this code is so I or others can check it out!) 😄

**Comment by iRon7** [comment]
Hello vexx32,

Thanks for the comment. You are right, the string is of cause already evaluated before it is passed to the `Write-Debug` cmdlet. I wonder if accepting a `ScriptBlock`  for the `-Message` parameter would make sense.

Something like:

````
Write-Verbose -Message {Get-Service | Format-List * | Out-String}
````

Or is that where KirkMunro actually asks for?

**Comment by lzybkr** [comment]
I believe @KirkMunro is asking for something like [ConditionalAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.conditionalattribute?view=netframework-4.7.2) with the difference being PowerShell would inject a runtime check for the preference variable around the call to the command.

@vexx32 - the improvements I have in mind are a major work item and I'm not aware of anyone that is seriously looking at. The basic idea is to use dynamic sites (like what is used for operators and member access) for command lookup and parameter binding, basically introducing a layer on top of the existing code. These areas probably have room for more incremental improvements too, but it will take some digging with a profiler and probably some creativity combined with some deep understanding of how those areas work.

**Comment by iRon7** [comment]
Please either mark this issue with something like <kbd>Resolution-Declined</kbd> or put it on a kind of <kbd>wishlist</kbd> "[*Issue we would like to prioritize, but we can't commit we will get to it yet*](https://github.com/dotnet/runtime/labels?q=wishlist)
