### ISSUE TITLE
Returning nothing (Automation.Null) from an [object]-typed custom-class method breaks

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#7128]
Steps to reproduce
------------------

```powershell
class Foo { [object] Bar() { return & {} } }; (new Foo).Bar()
```

Note that `& {}` outputs "nothing", i.e., the "null collection" `[System.Management.Automation.Internal.AutomationNull]::Value`

Expected behavior
-----------------

Given that PowerShell allows casting _any_ value to `[object]` - including `$null` and `[System.Management.Automation.Internal.AutomationNull]::Value`, the operation should succeed and the `[System.Management.Automation.Internal.AutomationNull]::Value`) should be passed through.

@BrucePay's take on the desired behavior differs, however (taken from [this SO answer](https://stackoverflow.com/a/50957388/45375) of his):

> We should still generate an error but it should be "non-void methods must return a value" or some such

Actual behavior
---------------

The following error occurs:

```none
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: Index
...
```

An analysis of the cause, courtesy of @BrucePay's previously linked answer:

> [...] the code that invokes the scriptblock expects there to be an object in the result List i.e. `result.Count == 1`. There are no objects in the pipeline case so you get an index-out-of-range error. [...]
> BTW - the [code in question is here](https://github.com/PowerShell/PowerShell/blob/c1c5344a8897262433141ecbc13bb06ac2c4bbef/src/System.Management.Automation/engine/lang/scriptblock.cs#L508).

Environment data
----------------

```powershell
PowerShell Core v6.1.0-preview.2 on macOS 10.13.4
PowerShell Core v6.1.0-preview.2 on Ubuntu 16.04.4 LTS
PowerShell Core v6.1.0-preview.2 on Microsoft Windows 10 Pro (64-bit; Version 1709, OS Build: 16299.371)
Windows PowerShell v5.1.17134.48 on Microsoft Windows 10 Pro (64-bit; Version 1709, OS Build: 16299.371)
```

**Comment by BrucePay** [comment]
Rather than generating an error which wouldn't have been very useful, I changed the code to return default(T).

**Comment by mklement0** [comment]
Thanks, @BrucePay, that makes sense.

To spell it out, in the case of `[object]` - and any reference type - this will default to `$null` - see https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/default-value-expressions for the full story.

**Comment by winperec** [comment]
The one thing I don't like every time I should check for $null before iterating. because:

$null | Foreach-Object { $_.someprops.prop = "111" } # throws exception;

&{} | Foreach-Object { $_.someprops.prop } # no throw because no iterating;
