### ISSUE TITLE
Suggestion:  add .LICENSE help topic for cmdlet licensing information

### ISSUE THREAD

**Issue by rhymeswithmogul** [PowerShell/PowerShell#7133]
PowerShell's self-documentation capability is great, but there's no room to add license information at the top of the file.  If you try that, the entire help system breaks, and ```Get-Help``` ignores everything. 

For example, I tried to include it before my regular help and my code:
```
<#
Test-FeatureRequest.ps1
by John Doe <jdoe@example.tld>

This program is free software: you can redistribute it and/or modify it under the terms of
the GNU General Public License as published by the Free Software Foundation, either version
3 of the License.  This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program.
If not, see <https://www.gnu.org/licenses/gpl-3.0.en.html>.

.SYNOPSIS
foo

.DESCRIPTION
foo

.PARAMETER result
foo
#>
code goes here
```

That caused the entire comment block to be ignored:
```
PS C:\Users\jdoe> Get-Help .\Test-FeatureRequest.ps1
Test-FeatureRequest.ps1 [-result] <Object> [<CommonParameters>]
```

I tried a few variants unsuccessfully, like splitting the comment block into two.  There was no difference between me putting the license information first or second.
```
<#
[license text goes here -- I won't retype it every time]
#>
<#
.SYNOPSIS
foo

.DESCRIPTION
foo

.PARAMETER result
foo
#>
```
I tried inventing a .LICENSE keyword and using that, in hopes PowerShell would think it's from a future version of the language and quietly ignore it.  That, too, made PowerShell ignore the entire block.
```
<#
.LICENSE
[license text goes here]

.SYNOPSIS
foo

.DESCRIPTION
foo

.PARAMETER result
foo
#>
```

In the end, I had to stick my license information into the .NOTES section.  This works, but it has the side effect of showing the information, which is meant to be a file header, every time someone uses the Get-Help command on my script -- not the end of the world.

I feel the next iteration of PowerShell Core should have a new documentation item, ```.LICENSE```.  Its primary purpose would be to "decorate" the top of a file.  However, if implemented, it should also be shown when ```Get-Help -Full``` is called, as many licenses also specify how the program can be shared with others;  this is similar to finding most apps' license information under Help > About.

I tried this on PowerShell and Windows PowerShell, with identical results:
```
Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```
Name                           Value
----                           -----
PSVersion                      5.1.17134.112
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.112
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by rkeithhill** [comment]
Why not put that text in a regular comment block (as opposed to a doc comment block) at the top of the file e.g.:
```
<#
Test-FeatureRequest.ps1
by John Doe <jdoe@example.tld>

This program is free software: you can redistribute it and/or modify it under the terms of
the GNU General Public License as published by the Free Software Foundation, either version
3 of the License.  This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program.
If not, see <https://www.gnu.org/licenses/gpl-3.0.en.html>.
#>

<#
.SYNOPSIS
foo

.DESCRIPTION
foo

.PARAMETER result
foo
#>
function One {}

<#
.SYNOPSIS
foo

.DESCRIPTION
foo

.PARAMETER result
foo
#>
function Two {}
```

**Comment by rhymeswithmogul** [comment]
I already tried putting it in a separate block at the top of the file, before the self-help, but that didn't work.

However, I tried your example, with a blank line between the two blocks, and that worked successfully.
