### ISSUE TITLE
How to list preview packages with new package id

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/PowerShell#7141]
@TravisEz13 - doing 'yum search powershell' on a system that is already setup with Microsoft yum repos does not show any powershell packages with new ids.

Can you post to this issue when this is available and if there is more to than just listing the current repos to find the preview packages?

**Comment by TravisEz13** [comment]
`yum search powershell-preview` should show the new packages

**Comment by DarwinJS** [comment]
@TravisEz13,
Install-powershell.sh uses the tar ball when a package manager is not available.  How should it operate in order to accomplish a pre-release?

Should it simply not do the symlink to /usr/bin/pwsh ?

Thanks for any guidance.

**Comment by TravisEz13** [comment]
I think we can leave it as is until we get feedback

**Comment by DarwinJS** [comment]
Seems a little weird that they behavior will vary according to distro.  On non-packaged managed distros installing a pre-release will make it the primary version.  A direct antipattern of the benefit sought by establishing two package ids?

Also way back I left SUSE as non-package managed because of the unautomatability of that question it throws.

**Comment by TravisEz13** [comment]
Agreed, but creating the shortcut is important.  If we can detect that we care installing preview, we should create the preview shortcut.  /usr/bin/pwsh-preview

**Comment by DarwinJS** [comment]
Ah that's actually the answer I was looking for!

**Comment by TravisEz13** [comment]
Is this question answered?
