### ISSUE TITLE
Does a finally{} block reliably run on PowerShell.Stop() when its try{} block has been entered?

### ISSUE THREAD

**Issue by alx9r** [PowerShell/PowerShell#7144]
The following code has a race between `try{}` and `.Stop()`:

```PowerShell
1..60 | % {
    $h = [ordered]@{
        'Delay(ms)' = $_
        EnteredScript = ''
        EnteredTry    = ''
        Finally       = ''
        Completing    = ''
    }

    $powershell = [powershell]::Create().AddScript({
        param($h)
        $h.EnteredScript = $true
        sleep -Milliseconds 10
        try
        {
            $h.EnteredTry = $true
            sleep -Milliseconds 30
        }
        finally
        {
            $h.Finally = $true
        }
        $h.Completing = $true
    }).AddParameter('h',$h)

    $invocation = $powershell.BeginInvoke()
    sleep -Milliseconds $_
    $powershell.Stop()

    [pscustomobject]$h
} |
    Format-Table
```

I've found that `finally{}` seems to always run once the `try{}` block is entered.  Is this just fortunate timing?  Or is this behavior that I can rely on for all timing?

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.688
PSEdition                      Core
GitCommitId                    v6.1.0-preview.688
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by FireInWinter** [comment]
It should always try to execute the finally block.  Even if you CTRL-C and stop the script, it still tries to execute the finally block.  However, if the finally block tries to dump something to the pipeline, it won't be displayed if the script was stopped.

If you run the following and break it before the sleep time ends, $t is still updated to 1, but the string won't display.
```$t=0; try { sleep 60 } catch {'oops'} finally {$t=1; 'not displayed if stopped early'}```

**Comment by BrucePay** [comment]
We had a number of discussions back in the V3 time frame around whether the `finally` block should run if `.Stop()` was called or not. Some people felt that `.Stop()` should stop all execution including `finally` blocks since a `finally` block could run for some time and how would you stop that. But in the end, we decided that `finally` blocks should run after `Stop()` because the canonical use-case for `finally` is to clean up after the code in the `try` block. So it's by design that in-scope `finally` blocks run after `.Stop()`.

**Comment by alx9r** [comment]
Thanks  @BrucePay.
