### ISSUE TITLE
New PSSession stuck after entering password with HostName

### ISSUE THREAD

**Issue by asishm** [PowerShell/PowerShell#7147]
Trying to connect from Windows to Windows after following through the guidelines at https://docs.microsoft.com/en-us/powershell/scripting/core-powershell/ssh-remoting-in-powershell-core?view=powershell-6 

Steps to reproduce
------------------

```powershell
$session = New-PSSession -HostName <Host> -UserName <User>
<User>@<Host>'s password:
```

Expected behavior
-----------------
I would be able to connect and then enter using `Enter-PSSession`.

Actual behavior
---------------

Authentication seems to work because if I enter in wrong username or password - it does throw a PermissionDenied error. However, with the right credentials, it just seems to sit there after entering the password and does not do anything
Environment data.

----------------

Client
```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0
PSEdition                      Core
GitCommitId                    v6.0.0
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
Server
```powershell
Name                           Value
----                           -----
PSVersion                      6.0.0
PSEdition                      Core
GitCommitId                    v6.0.0
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by MaximoTrinidad** [comment]
Just an FYI

You need to make sure to follow all the instructions to setup OpenSSH in Windows. This will include to **create to ssh port rule**, **properly configure the sshd_config file** with all needed enabled lines, and  **adding the Subsystem PowerShell Core path**.

Also, keep in mind, that the latest version of Windows 10 (I think greater than 14393, and specially Insider Version) will include the OpenSSH client ready to go.  And, in  those version, the OpenSSH Server need to be installed separately.

I can tell you that everything work as expected, and specially with the latest PowerShell Core 6.1.0-Preview.3. 

:)

**Comment by nibhatish** [comment]
Was this issue resolved? I am facing same issue.

**Comment by AdeventureTime** [comment]
Try the following:

1. Check the powershell subsystem registration path in **sshd_config**.
It should not contain any space.
Wrong
`Subsystem powershell C:\Program Files\PowerShell\7\pwsh.exe -sshs -NoLogo -NoProfile`
**Correct** (based on PowerShell/Win32-OpenSSH#784)
`Subsystem powershell C:/progra~1/PowerShell/7/pwsh.exe -sshs -NoLogo -NoProfile`

2. Restart OpenSSH service.
`Restart-Service sshd`

3. Try loging again on the client side.
`Enter-PSSession`
