### ISSUE TITLE
Is there a way to protect a critical section against .Stop() to ensure cleanup?

### ISSUE THREAD

**Issue by alx9r** [PowerShell/PowerShell#7155]
Consider the case where a handle to a resource that needs cleanup is obtained and assigned to a variable in a `try{}`.  Cleanup would customarily be performed in the associated `finally{}`.  However, if the `.Stop()` signal is sent during the obtain-and-assign step, the resource can be allocated without the handle being assigned.  This means that the `finally{}` can't clean up the resource because it has no handle to it.

Steps to reproduce
------------------

```powershell
# a hashtable to track state
$h = [ordered]@{
    Begin = ''
    End = ''
    BeginFinally = ''
    EndFinally   = ''
}

# an example IDisposable class
class c : System.IDisposable
{
    [bool] $Disposed = $false
    [void] Dispose()
    {
        $this.Disposed = $true
    }
}

function New-C {
    $c = [c]::new() # this IDisposable gets created

    sleep 1         # stop occurs here

    $c              # this never gets returns
}

$powershell = [powershell]::Create().AddScript({
    param($h)
    try
    {
        $h.Begin = $true
        $disposable = New-C # stop occurs during this call,
                            # so $disposable is not assigned

        $h.End = $true      # this line is never reached
    }
    finally
    {
        $h.BeginFinally = $true

        $disposable.Dispose() # $disposable is null
        
        $h.Disposed = $disposable.Disposed
        $h.EndFinally = $true

        # we reach the end without $c ever being disposed
    }
}).AddParameter('h',$h)

$invocation = $powershell.BeginInvoke() # invoke the script
sleep -Milliseconds 500                 # wait until it's in New-C
$powershell.Stop()                      # send the stop signal

[pscustomobject]$h
```

Expected and Actual behavior
-----------------

The actual behavior is the behavior I expect: `$c` is never disposed because it is not available in `finally{}`.

```none
Begin        : True
End          : 
BeginFinally : True
EndFinally   : True
Disposed     : 
```

Behavior I'm Hoping for
---------------

I'm hoping for some way to ensure that the call to `New-C` and assignment to `$disposable` is allowed to completed before `.Stop()` causes flow of control to jump to `finally()`.  That way `$c` can be disposed.

```none
Begin        : True
End          : 
BeginFinally : True
EndFinally   : True
Disposed     :  True
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.688
PSEdition                      Core
GitCommitId                    v6.1.0-preview.688
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Seems we discussed this previously and have an opened Issue.

**Comment by alx9r** [comment]
@iSazonov Do you have a reference to that issue?  Do you mean #6673?  #6673 seems to be about reliably cleaning up a resource to which a function has a handle.  This issue is about not being able to reliably obtain that handle in the first place.

**Comment by BrucePay** [comment]
@iSazonov This a different issue than adding a dispose clause to functions.
@alx9r No - there is currently no mechanism to block `Stop()`. Is this an actual problem you are hitting or is it theoretical only?  Remember, when you hit `Stop`, the state of the system is essentially unknown. Partially written files will still be there, processes that have started won't be stopped, etc. But the gc *will* (eventually) clean up and dispose allocated objects. If it's *really* important that this object gets disposed immediately, you could alter `New-C` to take care of this case. Something like:
```powershell
function New-C {
    try {
        $returned = $false
        $c = [c]::new() # this IDisposable gets created

        sleep 5         # stop occurs here

        $c                # this never gets returns
        $returned = $true
    }
    finally {
        # gets cleaned up here...
        if (-not $returned -and $c)
        {
            Write-Host "Disposing c"
            $c.Dispose()
        }
    }
}
```
All that said, handling ctrl-C/SIGINT was in plan for V1. The `trap` statement was supposed to be able to handle  ctrl-c and decide if execution should proceed (`continue`) or terminate (`break`). (Note - it would trap the signal but explicit calls to `.Stop()` would go through). However this was never implemented and in all the time since it hasn't really been raised as an issue. Of course we now have a broader audience so perhaps we should reconsider adding it. (and `bash` has it)

**Comment by alx9r** [comment]
> Is this an actual problem you are hitting or is it theoretical only?

The general problem of incomplete cleanup on `.Stop()` and ctrl-C is something I battle at least daily.  I've found it requires unusual diligence to craft PowerShell commands and tests such that they reliably avert meaningless results caused by vestigial state.  I think it's too early to say, though, whether this particular vulnerability of cleanup to the `.Stop()` signal will significantly slow the inner development loop on my projects.

>...you could alter New-C to take care of this case.

Is `$c = [c]::new()` atomic when subject to `.Stop()` or ctrl-C?

**Comment by BrucePay** [comment]
`Stop()` is implemented by having the runtime check the `Stopping` flag in a bunch of places. Any long-running operation should check but we don't check for every operation as that would be too much overhead. I don't believe we check it for assignment statements (but I'd have to check the code). 

> The general problem of incomplete cleanup on .Stop() and ctrl-C is something I battle at least daily.

I'm curious about what you're going that is causing such problems. And have you considered using DSC which has a declarative state model?
