### ISSUE TITLE
Connect-MsolService : Could not load file or assembly 'System.IdentityModel, Version=4.0.0.0

### ISSUE THREAD

**Issue by nvtag** [PowerShell/PowerShell#7162]
PS /root> Connect-MsolService                                                                                                                                               
Connect-MsolService : Could not load file or assembly 'System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
At line:1 char:1
+ Connect-MsolService
+ ~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (Microsoft.Onlin...nectMsolService:ConnectMsolService) [Connect-MsolService], FileNotFoundException
+ FullyQualifiedErrorId : System.IO.FileNotFoundException: Could not load file or assembly 'System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
File name: 'System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at Microsoft.Online.Administration.Automation.ConnectMsolService.MsolCmdletProcessRecord()
   at Microsoft.Online.Administration.Automation.MsolCmdlet.ProcessRecord()
,Microsoft.Online.Administration.Automation.ConnectMsolService
 
Connect-MsolService : Could not load file or assembly 'System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
At line:1 char:1
+ Connect-MsolService
+ ~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Connect-MsolService], FileNotFoundException
+ FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.Online.Administration.Automation.ConnectMsolService

**Comment by adityapatwardhan** [comment]
@nvtag Could you include the PSVersion table according to the issue template.

**Comment by maica1** [comment]
I'm having this issue too.

PS /home/maicon/Downloads> Connect-MsolService -Credential $conector            
Connect-MsolService : Could not load file or assembly 'System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
At line:1 char:1
+ Connect-MsolService -Credential $conector
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (Microsoft.Onlin...nectMsolService:ConnectMsolService) [Connect-MsolService], FileNotFoundException
+ FullyQualifiedErrorId : System.IO.FileNotFoundException: Could not load file or assembly 'System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
File name: 'System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at Microsoft.Online.Administration.Automation.ConnectMsolService.MsolCmdletProcessRecord()
   at Microsoft.Online.Administration.Automation.MsolCmdlet.ProcessRecord()
,Microsoft.Online.Administration.Automation.ConnectMsolService
 
Connect-MsolService : Could not load file or assembly 'System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
At line:1 char:1
+ Connect-MsolService -Credential $conector
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Connect-MsolService], FileNotFoundException
+ FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.Online.Administration.Automation.ConnectMsolService
 
PS /home/maicon/Downloads> $PSVersionTable                                      

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.2
PSEdition                      Core
GitCommitId                    v6.1.0-preview.2
OS                             Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+de...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


PS /home/maicon/Downloads>

**Comment by MaximoTrinidad** [comment]
This has been an issue for some time now.
It only works for Windows PowerShell!
:(

**Comment by True-Demon** [comment]
Just pointing out that this is still an issue and has not been acknowledged. 🙁

**Comment by sphen13** [comment]
just ran into this

**Comment by vexx32** [comment]
Not sure the MSOL cmdlets were ever slated to be supported in PS Core? Part of the Connect-MsolService cmdlet involves popping a GUI window for the login; this is not particularly practical or possible at the moment in PS Core -- you'll note that in Core, even credential prompts are _in the shell_ rather than being the WinPS-style credential popups. The MSOL module hasn't accounted for this...

This has probably already been reported, but searching on the UserVoice channels for this module/service is probably a good idea just in case. I'm not sure the MSOL module is still being maintained / updated.

**Comment by iSazonov** [comment]
All MSOL cmdlets are not compatible with PowerShell Core. It is documented.

**Comment by fioresarro** [comment]
> Is it possible that this problem is oucourring for the lack of Microsoft Online Services Sign-In Assistant?
> In the download [link ](https://www.microsoft.com/en-us/Download/details.aspx?id=28177) it shows only windows supported systems.

I have this problem on macos. How can I solve it? This link is only for Windows.

**Comment by vexx32** [comment]
Not much you can do without them redesigning how the authentication is handled for the module, I think.

**Comment by fioresarro** [comment]
> Not much you can do without them redesigning how the authentication is handled for the module, I think.

Thank you very much. So I work with Windows.

**Comment by knightian** [comment]
Well ExchangeOnline module opens up a browser session to auth and works just fine. Why MsolService cannot do it?

**Comment by iSazonov** [comment]
It is too old and not compatible with Core.

**Comment by kmccl922** [comment]
Please stopped sending me these damn messages please !

Sent from Yahoo Mail on Android 
 
  On Sat, Nov 20, 2021 at 1:51 AM, ***@***.***> wrote:   


It is too old and not compatible with Core.

**Comment by WillFulmer** [comment]
Correct. This does not work on MacOS PowerShell. This requires a Windows OS with the Sign-In Assistant Module loaded.

**Comment by keifgwinn** [comment]
Coming at this problem on an m1 mac, I thought I'd just try cloud console and ran into the same issue.

**Comment by jdlinux** [comment]
Not really expecting any replies to this, but also attempting this on an Ubuntu 22.04 LTS system. Hitting the same issue and assuming still not supported sadly :(
