### ISSUE TITLE
Error in creating azure search indexer

### ISSUE THREAD

**Issue by Adavesh** [PowerShell/PowerShell#7166]
I am unable to create azure search indexer. I am able to create datasource and index but creating indexer is giving issues.

Steps to reproduce
------------------

function CreateOrUpdateIndexer()
{
    $indexerApiUrl = $("https://$siteName.search.windows.net/indexers/$indexerName" + "?api-version=$apiVersion");
    $RequestHeader = @{ 'api-key'=$adminKey; 'content-type'='application/json'};
    $body = @{};
    $body.Add('name', $indexerName);
    $body.Add('description', "Help Search Indexer");
    $body.Add('dataSourceName', $datasourceName);
    $body.Add('targetIndexName', $indexName);
    $body.Add('parameters', @{ "maxFailedItems" = "15"; "batchSize" = "100"; "configuration" = @{ "parsingMode" = "text"; "indexedFileNameExtensions" = ".htm, .html"; "imageAction" = "none"; "dataToExtract" = "contentAndMetadata" } });
    $RequestBody = $body | ConvertTo-Json;

    $response = Invoke-WebRequest -Uri $indexerApiUrl -Headers $RequestHeader -TimeoutSec 15000000 -Method "PUT" -ContentType 'application/json' -Body $RequestBody
    Write-Output $("Operation Status: (" + $response.StatusCode + ") " + $response.StatusDescription);
}

Expected behavior
-----------------

It should create the indexer

Actual behavior
---------------

```none
Error:
Invoke-WebRequest : {"error":{"code":"","message":"Connection string could not be parsed. 
It must be in one of the following formats: 
'DefaultEndpointsProtocol=https;AccountName=[your storage account];AccountKey=[your 
account key];' or 'BlobEndpoint=[your blob endpoint URI];SharedAccessSignature=[your 
account shared access token];' or 'ContainerSharedAccessUri=[your container shared access 
token with read and list permissions]'"}}
At line:15 char:17
+ ... $response = Invoke-WebRequest -Uri $indexerApiUrl -Headers $RequestHe ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest 
   ) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands 
   .InvokeWebRequestCommand
```

**Comment by iSazonov** [comment]
@markekraus Could you please look the Issue?

**Comment by markekraus** [comment]
@Adavesh It looks like this was answered in the [SO thread](https://stackoverflow.com/questions/51026966/azure-search-error-in-creating-indexer). It looks like you were able to resolve the issue by correcting the connection string in the data source definition. As the problem does not appear to be related to PowerShell I will close this issue. If you feel this is in error, please let us know and we can reopen and investigate.
