### ISSUE TITLE
Plan release process for Alpine Linux

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#7167]
Steps to reproduce
------------------
Plan the release of PowerShell for Alpine Linux, either as a package or just a docker image.

Expected behavior
-----------------
PowerShell can be used on Alpine Linux.

**Comment by SteveL-MSFT** [comment]
I think initially, we should just release as a docker image

**Comment by SteveL-MSFT** [comment]
docker run -it mcr.microsoft.com/powershell:preview-alpine-3.8

known issue with console rendering
