### ISSUE TITLE
Line wrapping in PS Core in-the-box help does not indent appropriately 

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShell#7175]
Issue Details
-----------------
Long spans of help text that wrap lines do not honor indentation on subsequent lines.  This results in a less than pleasant reading experience. Here is what I'm seeing in 6.1 preview 3 on Windows:

![image](https://user-images.githubusercontent.com/5177512/41734116-4145f77a-7543-11e8-8951-e91c008ecbd7.png)

Compare this to the nicer formatted 5.1 help:

![image](https://user-images.githubusercontent.com/5177512/41734185-7348234c-7543-11e8-8575-7c041c354fed.png)

There is also a typo in the 6.1 Get-ChildItem Description - it says `all child continers` and it should be `all child containers`.  Apparently that has been introduced by the rendered as the typo isn't in the source doc.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.3
PSEdition                      Core
GitCommitId                    v6.1.0-preview.3
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Moved from https://github.com/PowerShell/PowerShell-Docs/issues/2606 per request of @sdwheeler.

**Comment by powercode** [comment]
@SteveL-MSFT I don't think this is help system or Future. I think it is a regression in the formatting system.
Probably got broken with the format trimming work.

**Comment by powercode** [comment]
#7179

**Comment by SteveL-MSFT** [comment]
@powercode the help formatting doesn't go through the tablewriter so not related to #7179.  I checked with 6.0.2 and it's the same issue when you pipe help to a pager, so it's not a regression from the formatting changes, but I think it's something in the HelpSystem.  It's in `future` since it's not blocking 6.1 release.  `future` is the new `backlog`.

**Comment by rkeithhill** [comment]
This issue gives PoweShell Core a bit of a black eye when it comes to help topics. I have found that I can correct this like so:
```
Get-Help <cmd-name> -Full | Out-String -Width ($host.UI.RawUI.WindowSize.Width - 1) | less
```
