### ISSUE TITLE
File Imports Appear Broken in Server 2016

### ISSUE THREAD

**Issue by talaniz** [PowerShell/PowerShell#7185]
Version:
--------
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  2339   
``` 

Error:
-----
Error: The term '﻿function' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was includ
ed, verify that the path is correct and try again.

Summary:
---------
Last night, an update was implemented on our system via active directory. Today, I am unable to run file imports that work on other versions (5.1.16299.431 is working fine on my local machine, Windows 10). I'm not 100% sure that this is a bug, but I can't reproduce on other versions and there doesn't appear to be any link I could find to get an upgrade on the OS I'm using. The latest update was KB4284833 run overnight.

- Does this look like an end user issue?
- Is there a way to upgrade Windows Server 2016 PS to 5.1.16299.431 (working)?

Test Code:
--------------------------
_ZipFiles.ps1_
```
Param ($type)

$ScriptDirectory = Split-Path -Path $MyInvocation.MyCommand.Definition -Parent
$date = get-date -UFormat %Y%m%d
$Logfile = "$ScriptDirectory\FileManagement-$date.log"
try {
    . ("C:\Program Files (x86)\oneZero\Scripts\SendMail.ps1")
    . ("C:\Program Files (x86)\oneZero\Scripts\LogWrite.ps1")
}
catch {
    Write-Host "Error while loading supporting PowerShell Scripts"
    Write-Host "Error: $($_.Exception.Message)"
    exit 1
}
```

_SendMail.ps1_
```
function sendHTMLMail {

    Param (
        [string]$Body = '',
        [string]$Subject = ''
    )

    $SMTPServer = "smtp.sendgrid.net"
    $SMTPClient = New-Object Net.Mail.SmtpClient($SmtpServer, 587)
    $SMTPClient.EnableSsl = $false
    $SMTPClient.Credentials = New-Object System.Net.NetworkCredential("user", "password");
    $EmailFrom = "email"
    $EmailTo = "email"
	$message = New-Object System.Net.Mail.MailMessage $EmailFrom, $EmailTo
	$message.Subject = $Subject
	$message.IsBodyHtml = $true
	$message.Body = $Body
    $SMTPClient.Send($message)
}
```

_LogWrite.ps1_
```
﻿function LogWrite
{
   Param (
    [string]$logstring,
    [string]$logfile)

   $date = Get-Date
   $log = "$date - $logstring"
   
   if (!(Test-Path $Logfile))
   {
	 New-Item -path $Logfile -type file
     Add-content $Logfile -value $log
   }
   else
   {
   Add-content $Logfile -value $log
   }
}
```

**Comment by MaximoTrinidad** [comment]
Question to you @talaniz?

Is this a Windows PowerShell issue? Or, a PowerShell Core issue?

Keep in mind, Github is only PowerShell Core only.  Any Windows PowerShell issue should be address thru the UserVoice forum: https://windowsserver.uservoice.com/forums/301869-powershell 

This is as stated in the PowerShell Core landing page: https://github.com/PowerShell/PowerShell#windows-powershell-vs-powershell-core

Now, I would recommend to test the issue on a later Windows 10 build (< 16299) or Insider edition as we've seen issues been corrected on later builds.

:)

**Comment by talaniz** [comment]
Thank you for clarifying. I have updated on the UserVoice forum. Closing out.
