### ISSUE TITLE
Remove-PSDrive don't work

### ISSUE THREAD

**Issue by kkbruce** [PowerShell/PowerShell#7193]
Steps to reproduce
------------------

```powershell
New-PSDrive -Name "J" -PSProvider FileSystem -Root "\\ip\temp" -Persist
Remove-PSDrive -Name "J"
```

Expected behavior
-----------------

```
Delete "J"
```

Actual behavior
---------------

```
Remove "J" don't work.
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.17134.112
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.112
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by MaximoTrinidad** [comment]
Just to be clear!

This Github repository is for PowerShell Core only. Any Windows PowerShell issue should be address thru the UserVoice forum: https://windowsserver.uservoice.com/forums/301869-powershell

As is stated in the PowerShell Core landing page: https://github.com/PowerShell/PowerShell#windows-powershell-vs-powershell-core

Now, I would recommend to test the issue on a later Windows 10 build (> 16299) or Insider edition as sometimes seen that Windows PowerShell issues has been corrected on later builds.

:)

**Comment by MaximoTrinidad** [comment]
Now, I did test both Windows PowerShell and PowerShell Core.

I can't replicate the condition.  I see no issues in either PowerShell.

Please, make sure the shared folder is accessible in order for the cmdlet to work.

![psdrive_2018-06-27_6-46-20](https://user-images.githubusercontent.com/19892435/41969642-1fc7ebd4-79d6-11e8-84a0-eb677565935d.jpg)

```
PS [15] > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.3
PSEdition                      Core
GitCommitId                    v6.1.0-preview.3
OS                             Microsoft Windows 10.0.17686
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by kkbruce** [comment]
@MaximoTrinidad  Thanks your information.

**Comment by VortexUK** [comment]
Can we reopen this as it IS an issue, it's just missing a one peice of information. Add '-scope Global' on the 'New-PSDrive' command and the Remove-PSdrive command will not work.

**Comment by MaximoTrinidad** [comment]
@VortexUK 

Better off opening a new issues and complete the required information, like which version of PowerShell Core you are working and which system is running on: Windows, Linux, or Mac.

Your comment doesn't related to the original issue posted initially. Please, include sample code to try to reproduce the issue you're experiencing and what  the expected results.

Also, just a friendly  reminder, that all Windows PowerShell issues are not addressed in this repository.  This is only for PowerShell Core.

Thanks!
