### ISSUE TITLE
Allow Convert-Path to convert paths that don't exist [yet] and allow specifying the target provider

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#7197]
#3428 discusses the perennial point of PowerShell's current filesystem location not being in sync with .NET's, which causes surprising behavior whenever relative paths are passed to .NET methods.  
(Sadly, there seems to be no good fundamental solution to this problem.)

The pain could be alleviated if there were an easy way to convert relative filesystem paths to _absolute_ ones, so that the latter can be passed to the .NET methods for predictable behavior.

While `Convert-Path`'s purpose is to convert (relative or not) paths to provider-native absolute paths (e.g., by resolving custom-PS-drive-based paths to their underlying filesystem paths), `Convert-Path` currently requires that the input path _already exist_.

However, you may find yourself wanting to convert a path _about to be created_ to `Convert-Path`, e.g. when trying to use `[io.file]::WriteAllText()` with the name of a new file to be created in the current location.

To that end, a new switch such as `-NoCheck` could be introduced that simply converts the path _formally_, whether or not it ends up referring to an existing item.

Note: Arguably, `Convert-Path` should always have _defaulted_ to this behavior, but I presume that changing this now would be considered an unacceptable breaking change.

This could be complemented with a `-PSProvider` parameter that would allow you to target a specific provider irrespective of the current location's, thus allowing the use of `-PSProvider FileSystem` in order to reliably target the filesystem provider.

For example, you could then use the following code to reliably create a new file in the current PS filesystem location:

```powershell
# Wishful thinking
# Add -PSProvider FileSystem if there's a chance that the current location is 
# not a filesystem one.
[io.file]::WriteAllText((Convert-Path -NoCheck fileInCurrentDir.txt), 'file content') 
```

Environment data
----------------

Written as of:

```powershell
PowerShell Core v6.1.0-preview.3
```

**Comment by iSazonov** [comment]
Do cmd.exe and .Net keep current path state internally or get from OS?

**Comment by mklement0** [comment]
@iSazonov: 

My understanding is that every process has a current directory (working directory) associated with it, which .NET reflects in `[Environment]::CurrentDirectory` and cmd.exe  in `%CD%`.

My guess is that cmd.exe and .NET both rely directly on the process's current directory and that it is only PowerShell that "does its own thing" where its notion of the current filesystem directory can deviate from the process's.

**Comment by iSazonov** [comment]
> PowerShell that "does its own thing"

Then it is a problem of documenting and learning.

[io.file]::WriteAllText and cmdlets use string as paths. But first uses .Net path, second uses filesystem path - it is different things. They are the same for full paths, but may differ for relative paths. We should treat it as two different namespaces otherwise we have to fix then other possible scenarios. 

If someone wants to use methods ([io.file]::WriteAllText) instead of cmdlets why would he want to use the cmdlet to get the full path? It can use `[System.IO.FileInfo]::new(...).FullPath`.

**Comment by mklement0** [comment]
> Then it is a problem of documenting and learning.

It's a matter of _convenience_ that is _rooted in already knowing the underlying problem_ of not being able to assume that relative paths work the same in both worlds.  
That said, documenting is obviously _also needed_ - see https://github.com/PowerShell/PowerShell-Docs/issues/2626

> why would he want to use the cmdlet to get the full path?  It can use [System.IO.FileInfo]::new(...).FullPath

Because it offers a predictable, robust way to pass a PS path to .NET, whether the path is relative or not, whether it is based on a custom PS drive or not, and because it is a natural extension of the existing `Convert-Path` functionality.

`[System.IO.FileInfo]::new(...).FullName`, aside from being awkward to type, suffers the very same problem as the one this proposal is trying to solve: if you pass it a _relative_ path, it will be resolved relative to `[Environment]::CurrentDir`, not to _PowerShell_'s current filesystem location.

It is really too bad that the two directories cannot be kept in sync, but it sounds like PowerShell's multiple-runspaces-per-process feature prevents a good solution there (see the linked issue).

**Comment by iSazonov** [comment]
>It is really too bad that the two directory locations cannot be kept in sync

:-) Why bad? If we want keep the state in every runspace - want? - we have not two but many cwd. It is simple and clear. 

> [System.IO.FileInfo]::new(...).FullName, aside from being awkward to type, suffers the very same problem as the one this proposal is trying to solve: if you pass it a relative path, it will be resolved relative to [Environment]::CurrentDir, not to PowerShell's current filesystem location.

I meant that the user should stay within the same namespace.
Why would  anybody want to convert PowerShell path to .Net path? If we have scenarios where we really can't do without it, it's more useful to enhance the capabilities of PowerShell. Otherwise, we're opening an infinite path to fix PowerShell behaviors. For example, someone will want a reverse operation - convert .Net path to a PowerShell path, etc.

**Comment by mklement0** [comment]
Just realized that this is a duplicate of the much older #2993.

@iSazonov, can you please marks this as a duplicate?

**Comment by iSazonov** [comment]
@mklement0 I think we would get more progress if we added Pester test prototypes to issue text description :-)

**Comment by mklement0** [comment]
Thanks for labeling, @iSazonov, but I don't understand your comment.

**Comment by iSazonov** [comment]
Sorry. We need tests before merge a PR. The Pester tests is exact contracts. If we create the tests in an issue discussion time we will speed up the fix creation. If there is an approved contract, even a novice developer can prepare fix.
