### ISSUE TITLE
For a conceptually clear start/launch/open user experience, provide dedicated Start-* cmdlets

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#7201]
A follow-up from #5715:

Start/launch/open-something tasks can be categorized as follows:

* (a) Start _executables_, using a variety of options (asynchronous or not, different credentials, hidden, ...).

* (b) Start (open) _documents_ (including directories), asynchronously, using whatever GUI application is registered to handle them by default.

* (c) Start (open) _URIs_, asynchronously, using whatever using whatever GUI application is registered to handle them by default.

For technical and historical reasons, in _Windows PowerShell_ it is `Start-Process` that handles _all 3_ categories, with category (b) _also_ handled by `Invoke-Item`.

As of PowerShell Core v6.1.0-preview.3, `Start-Process` cannot handle (b) and (c), but `Invoke-Item` covers (b), as in Windows PowerShell.

.NET Core has since made the previously full-framework-only `.UseShellExecute` property available, so that #5715 can be resolved by integrating (b) and (c) functionality to `Start-Process` too, for symmetry with Windows PowerShell.

However, going forward I suggest (also) reflecting the categories in _distinct cmdlets_, so as to:

* make them easier to discover.

* have clear separation of purpose.

* have simpler syntax (no need to figure out which of the many `Start-Process` parameters make sense / are compatible with (b) and (c) functionality).

In practice this means:

* Leave `Start-Process` as-is (after integrating (b) and (c)), but deemphasize (b) and (c) in the _documentation_ and instead point to `Start-Item` and `Start-Uri` (see below).

* Introduce alias `Start-Item` for `Invoke-Item` - given the asynchronous nature of `Invoke-Item` (at least in the filesystem - it isn't currently implemented for other providers), it should always have been named `Start-Item`.

  * On a side note: the reverse goes for `Start-Sleep`, which should have been named `Invoke-Sleep` - see #3990

* Introduce a simple new `Start-Uri` cmdlet whose sole purpose is to cover (c).

Environment data
----------------

Written as of:

```powershell
PowerShell Core v6.1.0-preview.3
```

**Comment by BrucePay** [comment]
Nice analysis but not quite complete as PowerShell natively handles category a).e.g. `PS > netstat.exe` just works.  My intention when I added `Start-Process` was to handle the *exceptional* case where `Invoke-Item` and native commands were insufficient e.g. starting a background console process without relying on `ShellExecute` or jobs. It's a relatively thin layer on top of the `Process` class and that shows through (to the detriment of the cmdlet). IMHO, the fact that `Invoke-Item` doesn't handle URIs should be fixed first before we do anything with `Start-Process`. I'm OK with adding a specific discoverable command for URIs but should probably be `Invoke-URI` rather than `Start` since you can't stop it.

**Comment by mklement0** [comment]
Thanks, @BrucePay.

> as PowerShell natively handles category a).e.g. PS > netstat.exe just works.

Yes, but the focus of my analysis were all the _other_ scenarios where an external program / resource is executed / opened : asynchronously (at least by default), with no (direct) connection to the standard streams.
(Leaving aside that it's a common beginner mistake to think that `Start-Process` is needed for the it-just-works-with-direct-invocation scenario: synchronous execution with the standard streams connected.)

> before we do anything with `Start-Process`

Aside from completing the work to bring `Start-Process` on (near-)par with the way it works in Windows PowerShell (now that `.UseShellExecute` is available), I wasn't suggesting any changes to `Start-Process` - those who are used to how it works in Windows PowerShell and know that (b) and (c) functionality are built in can continue to use it as they're used to.

My suggestion was to _additionally_ give (c) (URI launching) a distinct cmdlet (`Start-Uri`), and to provide an alias for the already (b)-focused `Invoke-Item`, so as to make its name comply with PowerShell's naming rules (see below).

The net effect would be that each category would have a distinct cmdlet (despite the fact that `Start-Process` can do it all).

> the fact that Invoke-Item doesn't handle URIs should be fixed first

My concern is that the `Item` noun suggests too strongly that the cmdlet acts on _PS provider items_ only, which URIs are not, hence the suggestion to add a URI-focused cmdlet.

Here too we could take the same approach however: add URI support to `Invoke-Item` as well, in addition to providing a dedicated `Start-Uri` cmdlet.

>  should probably be `Invoke-URI` rather than `Start` since you can't stop it.

I was thinking `Start` in order to reflect the _asynchronous_ nature of the operation. 

That said, not being able to stop the operation is unusual in this case, so we could consider a "non-committal" alternative such as `Open` (a verb that is commonly applied to documents and URIs even outside of PowerShell).

By contrast, `Invoke` strikes me as not appropriate, based on what the [documentation](https://docs.microsoft.com/en-us/powershell/developer/cmdlet/approved-verbs-for-windows-powershell-commands) tells us (emphasis added):

> `Invoke` vs. `Start`: The **`Invoke` verb** is used to perform an operation that is **generally a synchronous operation**, such as running a command. The **`Start` verb** is used to begin an operation that is **generally an asynchronous operation**, such as starting a process.
