### ISSUE TITLE
Support Import-PfxCertificate on Unix

### ISSUE THREAD

**Issue by SidShetye** [PowerShell/PowerShell#7213]
Needed for x-platform scripting (us: our .net core projects)

### Scenario

Use PowerShell to initialize development and production environments with certificates with private keys across supported platforms, mirroring DotNet Core`s certificate store model.  Development platforms are Windows 10, macOS and Ubuntu. Production platforms are Windows Server and RHEL.  This should support user and machine locations and the various certificate stores supported on that platform by DotNet Core.

**Comment by TravisEz13** [comment]
what would this do on Linux?    I think we need a little more information.

**Comment by SidShetye** [comment]
It should import the certificate and private key into specified certificate stores (my, trust/root etc) and locations (local user vs machine). They aren’t fully consistent across OS’s, so I’d suggest mirroring the same model as dotnet’s.

**Comment by TravisEz13** [comment]
So the expectation would be able to use the certificates stored in DotNet Core applications?

**Comment by SidShetye** [comment]
Yes, powershell initializes the environments, including certificates and private keys in each OS. .NET Apps use these certificates. Development platforms are Windows 10, macOS and Ubuntu. Production platforms are Windows Server and RHEL.

**Comment by TravisEz13** [comment]
I updated the issue description with my current understanding of the Enhancement request. Please tell me if I got it wrong.

BTW, I checked about 3 Unix platforms and none of the certificate stores have certificates in them by default (vs Windows behavior).  Also, very few stores were supported in the local machine context.  But, I agree we should mirror the DotNet Core behavior.  I just want to set expectations.

Another thing to consider, is that this CmdLet is provided by Windows, in Windows PowerShell, not PowerShell it self.  So, we have to think about how to maintain compatibilty with Windows when implementing.

Thanks for the feedback.

**Comment by SidShetye** [comment]
Thanks for the background. To share more, we're retooling our environments to support x-platform builds and products. Various OSes don't follow the same certificate store model (makes sense) but that makes it hell for end users like ourselves. The hope is that by .NET/Powershell abstracting away the underlying differences, users have a consistent API to work against productively.

**Comment by SidShetye** [comment]
Any update on this? Certificate store operations are pretty painful across the platforms supported by powershell/ps core, so having PS abstract this pain away would be great.

**Comment by TravisEz13** [comment]
The request is understood.  It's in our backlog, but if we decide to work on it, then it will be moved to a specific milestone.
