### ISSUE TITLE
add back options for STA

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#7216]
Add command line option to specify apartment state and ability to create runspace with apartment state

**Comment by iSazonov** [comment]
Related #4995

**Comment by bergmeister** [comment]
What are the plans here in terms of timeline/expectations as this could be important for WPF? Add STA for PS 7.0? Or is it too much involved and will come only in 7.1? @SteveL-MSFT

**Comment by SteveL-MSFT** [comment]
@bergmeister agree that this is probably needed for WPF to work with 7, so we should do this for 7.0.

**Comment by iSazonov** [comment]
We preserved all apartment code. Only .Net Core has probably deviations from .Net Framework.

**Comment by bergmeister** [comment]
@iSazonov Except for the `-Sta` and `-Mta` switches on the `pwsh` binary that were removed in # 4995

**Comment by iSazonov** [comment]
Has MSFT team tests for the code area?

**Comment by SteveL-MSFT** [comment]
@iSazonov I searched the old tests and they don't seem comprehensive.  All it really does is use `-STA` with powershell.exe and validates that the apartmentstate is set correctly.  Ideally, we should include a specific test like using a COM object that requires STA or even WPF (not getting an exception).  Also manually run all tests with `-STA` to see if anything fails unexpectedly.
