### ISSUE TITLE
Add desktop files for Linux

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#7228]
https://fedoraproject.org/wiki/Packaging:Guidelines?rd=PackagingGuidelines#Desktop_files

A `.desktop` file was created for the snap here:  https://github.com/PowerShell/PowerShell-Snap/blob/master/stable/snap/gui/powershell.desktop

**Comment by alekonko** [comment]
Hi @TravisEz13, 

 i don't use snap but rpm (powershell-6.2.3-1.rhel.7.x86_64), but I think you can take as an example what I have done.
The only note in my case is to indicate the right Icon file path, I had to download it as it is not provided by the indicated rpm.

Ah, given the age of the issue maybe you had already solved it :)

Powershell-launcher.desktop 

```config
[Desktop Entry]
Categories=ConsoleOnly;System
Comment[en_US]=PowerShell Core
Comment[it_IT]=PowerShell Core
Comment=PowerShell Core
Exec=pwsh
GenericName[en_US]=Powershell
GenericName=Powershell
Icon=/usr/local/share/icons/powershell.png
MimeType=
Name=PowerShell
Path=
StartupNotify=true
Terminal=true
TerminalOptions=
Type=Application
X-DBUS-ServiceName=
X-DBUS-StartupType=
X-KDE-SubstituteUID=false
X-KDE-Username=
```
bye
Alessandro

**Comment by TravisEz13** [comment]
It was solved for snap but snap is actually easier...

**Comment by TravisEz13** [comment]
Where does the desktop file go?

**Comment by alekonko** [comment]
Simply put it on you Desktop ! :) 
In my case  at $HOME/Desktop path (under KDE)

bye
Alessandro

**Comment by TravisEz13** [comment]
This feature is currently under development in our packaging tool:
https://github.com/jordansissel/fpm/issues/610

**Comment by TravisEz13** [comment]
Apparently you can put the file in `/usr/share/applications` .  This isn't native support in fpm but doable.

**Comment by RokeJulianLockhart** [comment]
@TravisEz13, youy could copy https://github.com/jordansissel/fpm/issues/610#issuecomment-305996585 for now.
