### ISSUE TITLE
PowerShell remoting incorrectly converts script to command with ForEach-Object

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PowerShell#7229]
Before PowerShell sends a scriptblock to a remote session, it first tries to convert it into a command plus bound parameters as an optimization.  It does this incorrectly when the script uses ForEach-Object as shown below.

Steps to reproduce
------------------

```powershell
Invoke-Command -cn localhost -ScriptBlock { param($s,$x) foreach-object ([scriptblock]::Create($s)) -InputObject $x } -ArgumentList "`$_","HI"
```

Expected behavior
-----------------

```none
HI
```

Actual behavior
---------------

```none
No output
```
But if you modify the script slightly so that PowerShell cannot convert it into a command, then the scriptblock is sent as is and works as expected.

```powershell
Invoke-Command -cn localhost -ScriptBlock { param($s,$x) $null; foreach-object ([scriptblock]::Create($s)) -InputObject $x } -ArgumentList "`$_","HI"
HI
```

**Comment by BrucePay** [comment]
@PaulHigin How strange. It should just be calling `GetPowerShell()` on the scriptblock which does fail with the example::
```powershell
PS >  { param($s,$x) foreach-object ([scriptblock]::Create($s)) -InputObject $x }.getpowershell()
Exception calling "GetPowerShell" with "0" argument(s): "Cannot generate a Windows PowerShell object for a ScriptBlock
evaluating dynamic expressions. Dynamic expression: ([scriptblock]::Create($s))."
```
