### ISSUE TITLE
Get-Help can break if any command in the session has parameters of a type that cannot be loaded

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#7234]
Steps to reproduce
------------------

```powershell
function foo([aTypeThatCannotBeLoaded] $bar) { }; Get-Help somethingEntirelyUnrelated
```

Expected behavior
-----------------

The inability to load a type should be ignored and search results for `somethingEntirelyUnrelated` should be displayed or, if there aren't any, the usual error message should be displayed (`Get-Help : Get-Help could not find somethingEntirelyUnrelated in a help file in this session ...`)

Actual behavior
---------------

The following error occurs:

```none
Get-Help : Unable to find type [aTypeThatCannotBeLoaded].
...
```

Reporting an error would make more sense if help for function `foo` were specifically sought, but even then a more helpful error message is called for.

Environment data
----------------

```powershell
PowerShell Core v6.1.0-preview.3 on macOS 10.13.5
PowerShell Core v6.1.0-preview.3 on Ubuntu 16.04.4 LTS
PowerShell Core v6.1.0-preview.3 on Microsoft Windows 10 Pro (64-bit; Version 1709, OS Build: 16299.371)
Windows PowerShell v5.1.17134.48 on Microsoft Windows 10 Pro (64-bit; Version 1709, OS Build: 16299.371)
```

**Comment by adityapatwardhan** [comment]
@mklement0 Thanks for reporting.
