### ISSUE TITLE
PowerShell Core 6.0.2 is slow with Get-ChildItem

### ISSUE THREAD

**Issue by Hermholtz** [PowerShell/PowerShell#7238]
The following command takes more than 2 times as long in PowerShell Core than in Windows PowerShell. I don't see the reason for this huge difference on the same OS instance (Windows 10). I repeated the test several times and these results are on hot filesystem cache (no actual I/O). During the tests in both PowerShell versions I observed the same CPU load (around 18% on a 4-core 8-thread i7 system).

```powershell
Set-Location $ENV:UserProfile
Measure-Command { Get-ChildItem -Recurse | Measure-Object }
```

Output in PowerShell Core on my profile folder (153000 files):

```none
(...)
TotalSeconds      : 22,439892
TotalMilliseconds : 22439,892
```

Output in Windows PowerShell on the same folder:

```none
(...)
TotalSeconds      : 10,8080086
TotalMilliseconds : 10808,0086
```

Environment data
----------------

$PSVersionTable:

```none
Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```none
Name                           Value
----                           -----
PSVersion                      5.1.17134.137
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.137
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by TheIncorrigible1** [comment]
Commands have variance from run to run and only posting results from a single run isn't very effective.  Try the following:

    1..100 | % { Measure-Command { Get-ChildItem -Recurse } } | Measure-Object TotalSeconds -Average

**Comment by chojrak11** [comment]
I repeated the test several times (as noted above), but here you go, as you requested, the results of your command. To be clear, they were executed sequentially, not simultaneously:

Windows PowerShell:

```none

PS C:\> 1..10 |
>>     ForEach-Object { Measure-Command { Get-ChildItem -Recurse -Path $HOME } } |
>>     Measure-Object TotalSeconds -Average

Count    : 10
Average  : 9,5322764
Sum      :
Maximum  :
Minimum  :
Property : TotalSeconds
```

PowerShell Core 6.0.2:

```none
PS C:\Program Files\PowerShell\6.0.2> 1..10 |
>>     ForEach-Object { Measure-Command { Get-ChildItem -Recurse -Path $HOME } } |
>>     Measure-Object TotalSeconds -Average

Count    : 10
Average  : 19,21532841
Sum      :
Maximum  :
Minimum  :
Property : TotalSeconds
```

That's almost exactly twice as long.
I don't have any idea where to start looking for the problem, hope there are wise people here who can explain (and fix) this.

If your results are not as prominent, please select a bigger folder for the test, e.g. Program Files or Windows.

**Comment by powercode** [comment]
I have less than 10% difference on 5.1 and 6.1-preview 3.

Still slow...

**Comment by 9Rune5** [comment]
I found this thread because I experienced this issue on an older version of Windows Server. 

I had installed PSCore, but `gci -recurse \*.config`  ran so slow that I had to stick with an older version of Powershell. I didn't measure time spent, but it was unusable.
