### ISSUE TITLE
Add a -Recurse switch to Measure-Object to support input objects / properties that are collections themselves

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#7244]
Currently, `Measure-Object` treats each input object / input object's property as a _scalar_; e.g.:

```powershell
PS> ((1, 2), (3, 4) | Measure-Object).Count
2 # The input arrays each counted as *1* object - their elements weren't counted.

PS> ([pscustomobject] @{ prop = 1, 2 }, [pscustomobject] @{ prop = 3, 4 } | 
      Measure-Object -Property prop).Count
2  # The arrays stored in .prop each counted as *1* object - their elements weren't counted.
```

Note that if you also specified a switch such as `-Sum`, the commands would _break_, because an attempt is made to interpret the _array_ as a number, which fails: `Measure-Object : Input object "System.Object[]" is not numeric.`

It would be handy if a `-Recurse` switch would allow opting into recursing into array-valued input objects / properties:

```powershell
PS> ((1, 2), (3, 4) | Measure-Object -Recurse).Count  # WISHFUL THINKING
4   # The input arrays' elements were counted individually

PS> ([pscustomobject] @{ prop = 1, 2 }, [pscustomobject] @{ prop = 3, 4 } | 
      Measure-Object -Recurse -Property prop).Count  # WISHFUL THINKING
4 # The elements of the arrays stored in .prop were counted individually
```

Environment data
----------------

Written as of:

```powershell
PowerShell Core v6.1.0-preview.3
```

**Comment by BrucePay** [comment]
Note that there are already many ways to achieve the same effect : `(1, 2), (3, 4) | write | Measure-Object` or `$objList.prop | write | Measure-Object` or `$objList | select Expand prop | Measure-Object`  or `$objList | foreach prop | Measure-Object`

**Comment by mklement0** [comment]
Thanks for the examples, @BrucePay.

While the problem can definitely be solved with the current features, as you demonstrate, my motivation for suggesting  `-Recurse` is the desire for convenience and concision (and greater efficiency, to a lesser degree).

If backward compatibility weren't a concern, I would have have suggested the inverse logic: enumeration _by default_, with an opt-out via `-NoEnumerate`.
