### ISSUE TITLE
The term 'Remove-AzureStorageAccount' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by amjad** [PowerShell/PowerShell#7250]
I am getting this error, when I am trying to run this command.

```
Remove-AzureStorageAccount : The term 'Remove-AzureStorageAccount' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

+     Remove-AzureStorageAccount -StorageAccountName ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Remove-AzureStorageAccount:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Name                           Value                                                                                                                            
----                           -----                                                                                                                            
PSVersion                      5.0.10586.117                                                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                          
BuildVersion                   10.0.10586.117                                                                                                                   
CLRVersion                     4.0.30319.42000                                                                                                                  
WSManStackVersion              3.0                                                                                                                              
PSRemotingProtocolVersion      2.3                                                                                                                              
SerializationVersion           1.1.0.1     

What can be causing this?

**Comment by MaximoTrinidad** [comment]
@amjad 

This is just a reminder that this section is only for PowerShell Core issues and not Windows PowerShell.
https://github.com/PowerShell/PowerShell#windows-powershell-vs-powershell-core

So, with that said, due to the fact that your having an Azure cmdlet issue, I would suggest to repost it and following the guidelines in providing all necessary information to the following link:
https://github.com/Azure/azure-powershell

The issue need to be posted in the right place so the proper team can help.

Thanks!

**Comment by MaximoTrinidad** [comment]
FYI ... Did you import the module?

**Comment by amjad** [comment]
Thanks @MaximoTrinidad, I will post it in the right place. 

Yes I did import the module. Are you talking about a specific module?

**Comment by MaximoTrinidad** [comment]
Give me the link when you repost the issue and then I can followup you question.
This way will keep it in the same post.
:)

**Comment by amjad** [comment]
@MaximoTrinidad https://github.com/Azure/azure-powershell/issues/6632
