### ISSUE TITLE
Add option to MSI installer to allow user scoped installation that does not require elevation

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#7256]
Currently the MSI installer uses `InstallScope="perMachine"` [here](https://github.com/PowerShell/PowerShell/blob/master/assets/Product.wxs#L36).
It would be helpful if the installer offered an option via a radiobutton and MSI property to allow for installation that uses `InstallScope="perUser"` in order to not need Admin right for installation/deployment. 

Do you think it will be possible to achieve a non-Admin installation with that and would you accept a PR for that @SteveL-MSFT ?

Expected behavior
-----------------

I can install `PowerShell` Core easily remotely on a system without needing to have Admin rights.

Actual behavior
---------------

MSI Installer is scoped to machine wide installation and requires Admin rights

Environment data
----------------

```powershell
> $PSVersionTable
PS C:\Program Files\PowerShell\6-preview> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.3
PSEdition                      Core
GitCommitId                    v6.1.0-preview.3
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
@bergmeister I think the default should stay as machine wide, but if we can add the radio button option for a user install thus not requiring elevation, that would be great.
