### ISSUE TITLE
Member enumeration with a nonexistent property works differently with custom objects than with other types

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#7261]
Steps to reproduce
------------------

```powershell
    # Accessing a nonexistent property on a collection of *custom objects*
    # returns a $null for each element, i.e.: @( $null, $null ) in this case:
    ([pscustomobject] @{foo=1}, [pscustomobject] @{foo=2}).Bogus.GetType().Name

    # By contrast, *other types* seem to evaluate to a $null *scalar*,
    # as evidenced by the .GetType() call failing:
    ($PSVersionTable, $PSVersionTable).Bogus.GetType().Name

```

Expected behavior
-----------------

```none
Object[]
Object[]
```

Actual behavior
---------------

```none
Object[]
You cannot call a method on a null-valued expression.
```

Arguably, it is the behavior with custom objects (returning an _array_ of `$null` values) that is consistent with member enumeration: whatever the result of accessing the specified property on the collection element returns is collected in an array.

On the flip side, the fact that a 2+-element array of `$null`s is truthy may be surprising
(e.g., `[bool] ($null, $null)` yields `$True`).

Environment data
----------------

```powershell
PowerShell Core v6.1.0-preview.3
```

**Comment by surfingoldelephant** [comment]
> Arguably, it is the behavior with custom objects (returning an _array_ of `$null` values) that is consistent with member enumeration: whatever the result of accessing the specified property on the collection element returns is collected in an array.

I agree with this sentiment. Consistency with features like this is key.

The alternative approaches (`ForEach-Object -MemberName`, member-access in a `foreach` loop, etc) that member-access enumeration provides convenience for behave in the same manner: 
* The value of the member if it exists (methods excluded).
* `$null` if it doesn't exist. 

Yet member-access enumeration was designed to deviate from this. It's meant to be a convenience feature - once you deviate from original, fundamental behavior, you start to lose some of that convenience.

Personally, I would prefer this bug/https://github.com/PowerShell/PowerShell/issues/13752 to be addressed by making all _other_ types consistent with the current "broken" custom object behavior. However, I suspect that would be deemed an unacceptable breaking change.
