### ISSUE TITLE
There are some "peculiarities" with argument completers and their scriptblocks

### ISSUE THREAD

**Issue by eosfor** [PowerShell/PowerShell#7265]
Hello, colleagues, I've put all my "troubleshooting" steps into the bigger article, [here](https://eosfor.github.io/2018/Episode1-Issues-with-Argument-Completers/). In short what I've found is that when scriptblock is passed to  ```[ArgumentCompleter()]``` as a parameter, does not see functions local to a module.

Or, maybe i do something wrong?

Expected behavior
-----------------
When ```[ArgumentCompleter()]``` "runs" a script block, it should attach it to a module "local scope".  I mean that it should see functions local to the module/script, because commonly I don't want to export "completers" out of a module

Actual behavior
---------------
When ```[ArgumentCompleter()]``` "calls" a script block passed to it, scriptblock, looks like does not see internal functions of a module, but it seems to be able to see them if they are exported to a global scope.

Environment data
----------------

Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by mklement0** [comment]
@eosfor: Perhaps #7071 is a duplicate?

**Comment by eosfor** [comment]
yes, looks like this, thanks @mklement0. However, as i said in the post, option with providing [type] to the completer attribute works fine, perhaps because it is "local" to the function or something, i don't know. @iSazonov, you are in +2hrs from me ;), so we can talk and i can show you this live, if you want.

**Comment by eosfor** [comment]
@iSazonov i wish i could, not sure even where to start. Give me some guidance and i'll try )

**Comment by eosfor** [comment]
@iSazonov @BrucePay wow, i never thought i could ask this question!
