### ISSUE TITLE
Parser bug: using break inside of switch in finally block fails to parse

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/PowerShell#7267]
Steps to reproduce
------------------

```powershell
try {
} finally {
    switch ($foo) {
        'bar' {break}
        'foo' {break}
    }
}
```

Expected behavior
-----------------

This should parse just fine.

Actual behavior
---------------

The parser spits out the following error:

```none
At line:4 char:8
+ 'bar' {break}
+        ~~~~~
Flow of control cannot leave a Finally block.
At line:5 char:8
+ 'foo' {break}
+        ~~~~~
Flow of control cannot leave a Finally block.
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : ControlLeavingFinally
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0
PSEdition                      Core
GitCommitId                    v6.0.0
OS                             Microsoft Windows 10.0.17692
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kvprasoon** [comment]
repro in latest preview as well.

```
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.3
PSEdition                      Core
GitCommitId                    v6.1.0-preview.3
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by lzybkr** [comment]
This is by design and consistent with C#, see: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/statements#the-try-statement - specifically this:

> It is a compile-time error for a break, continue, or goto statement to transfer control out of a finally block. When a break, continue, or goto statement occurs in a finally block, the target of the statement must be within the same finally block, or otherwise a compile-time error occurs.

> It is a compile-time error for a return statement to occur in a finally block.

This is not allowed because it makes no sense if an exception occurs - where would you resume execution?

**Comment by BrucePay** [comment]
I'm pretty sure this is a simple bug. The post-parse checks allow break in "loop statements" but switch isn't a "loop statement" but it is a "labelled statement". Changing the check from "loopstatement" to "labelledstatement" fixes this.
