### ISSUE TITLE
Cannot set [environment]::CurrentDirectory to value in Get-Location

### ISSUE THREAD

**Issue by CatGirlsAreLife** [PowerShell/PowerShell#7268]
I am trying to set [environment]::CurrentDirectory to the value in Get-Location just so I can take that location to do this:

    $env:nsmkpth = [environment]::CurrentDirectory + "\newsmake\"
    if(!(Test-Path -Path $env:nsmkpth)) {
        git clone -q https://github.com/Elskom/newsmake.git
        Set-Location -Path newsmake/build
        cmake ..
        Set-Location -Path ../..
    } else {
        Set-Location -Path newsmake
        git pull -q
        Set-Location -Path ..
    }

I am needing this to work on appveyor on my GitHub repository to when after it restores newsmake folder from the build cache, it would run git pull on it and check for changes and then run msbuild on it when it does change (eventually as it would need a way to compare the commit hashes that HEAD points to).

Alternatively if using Get-Location in the setting of the environment variable did not fail I would use that but it would still lead to ps saying native command error on anything git outputs even when pulling I think. Powershell really also needs to be more git friendly and not mark any output from it as a error. Although maybe they write everything to stderr which might be why powershell thinks it is a error. If this if actually worked I would be able to test the git pull senerio then.

**Comment by BrucePay** [comment]
Hi @CatGirlsAreLife PowerShell supports multiple shell instances per-process so it can't (and doesn't) use the process current directory. This means that you can't use `[environment]::CurrentDirectory` to find out the current PowerShell instances current directory. You should do something like:
```powershell
$env:nsmkpth = Join-Path (Get-Location) newsmake
```
>  if using Get-Location in the setting of the environment variable did not fail 

Hmm - it shouldn't be failing. What error message do you get?

**Comment by CatGirlsAreLife** [comment]
I was refering to where it seems the if would always return true and do what is not in the else statement. All because it would try to look in C:\Windows\system32\newsmake which never is created in my build. which then causes this:

git : fatal: destination path 'newsmake' already exists and is not an empty directory.
At line:5 char:1
+ git clone -q https://github.com/Elskom/newsmake.git
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   + CategoryInfo          : NotSpecified: (fatal: destinat...mpty directory.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

And thanks for a option for the fix to the environment variable. Will test that now :ok_hand:.

**Comment by BrucePay** [comment]
>  it would try to look in C:\Windows\system32\newsmake

Right - that's because it's using the process working directory, which, as I said, is not the PowerShell instance current working directory. If you use `Get-Location` (or the `$PWD` variable) instead of `[environment]::CurrentDirectory` to get the working directory location it should work properly.

**Comment by CatGirlsAreLife** [comment]
Thanks, also the Join-Path solution worked flawlessly.
