### ISSUE TITLE
Module manifests should use DebuggerHidden automatically

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/PowerShell#7269]
This is a long-time pet peeve of mine.

You're writing a script. You want to debug it. You set a breakpoint on a line in your script with a command that comes from a script module that is not loaded yet. You hit the breakpoint, which happens before the command is executed. You press F11 to step in, and.......you find yourself stepping through your module manifest?

This happens because the module manifest is technically PowerShell (although it is restricted language), and since the module hasn't loaded yet, it loads, which runs through the manifest, so you get to step through it.

Steps to reproduce
------------------

Create the following file at path C:\test.ps1:

```
Find-Module foo

'Hello'
```

Now run the following
```powershell
Set-PSBreakpoint -Script C:\test.ps1 -Line 1
. C:\test.ps1
```

Once you are at that breakpoint, press s to "step into the Find-Module command". This will step you into the module manifest for PowerShellGet instead. From there you need to press o to step out of the manifest, and into the Find-Module command in the psm1 file.

Expected behavior
-----------------

Stepping into a module manifest is pretty much useless. There needs to be a way to step into a function in an unloaded module without going through the manifest first. If we must keep it, then we need a way to mark a manifest with the DebuggerHidden attribute (which currently is not possible because you can only apply that attribute when you are using CmdletBinding with a param block, and the param block is not allowed in the restricted manifest language). If we're in agreement that it is indeed useless, then treat all manifest files as debugger hidden and bring people to the location they were expecting when they stepped into the function that their breakpoint was on.

Actual behavior
---------------

As described above, the debugger takes you through the manifest.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0
PSEdition                      Core
GitCommitId                    v6.0.0
OS                             Microsoft Windows 10.0.17692
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by KirkMunro** [comment]
@PaulHigin Care to share your thoughts on this? Since I originally logged this issue, I've been thinking that manifests, which only allow for a handful of variables as well as Import-LocalizedData, ConvertFrom-StringData, Write-Host, Out-Host, and Join-Path should use the DebuggerNonUserCode flag. There's really not much to debug, if anything at all, and it would be great if the debugger would simply ignore them when scripters step through their code.

The current behavior (allowing the debugger to step into the manifest) pretty much makes the debugging experience unusable. Every time I step into a command from a module that isn't loaded, and end up in the manifest, I quickly stop what I was doing, make sure the module was loaded, and then go back to my debugging, because you can't avoid stepping through the entire manifest if you unintentionally step into it (and that can take a very long time for manifests that have a lot of exports). I'd like to correct the behavior so that the debugger simply skips over manifests entirely.

**Comment by lzybkr** [comment]
This seems reasonable to me. I also think that the attribute could be applied to all `psd1` files, not just module manifests.

`DebuggerStepThrough` might be more appropriate on the off chance that you really do want to debug by setting a breakpoint, or perhaps step into code that is called from the manifest.

**Comment by KirkMunro** [comment]
Thanks for that suggestion @lzybkr. I agree this would be useful for all psd1 files, and will implement it that way.

As for the suggestion about `DebuggerStepThrough`vs `DebuggerNotUserCode`, looking through PowerShell Core it seems that DebuggerNotUserCode isn't implemented/supported right now, unless I'm missing something. That surprises me a little because I thought we had support for 3 debugger attributes (DST, DH, and DNUC).

**Comment by PaulHigin** [comment]
I agree with @lzybkr.  And overall I agree this will improve debugging experience.

**Comment by KirkMunro** [comment]
After spending some time working on this issue, I've come to the conclusion that the debugger attributes don't work as they should today (I already knew this, really, but not to the extent that I know now), and there are a number of bugs that I'd like to address here.

@lzybkr and @PaulHigin, I could really use your thoughts here, so if you can go through these and let me know if I'm missing something, I would appreciate it.

The point of this exercise (and this issue I logged was just a very small part of it) is to enable effective debugging. As someone who uses the PowerShell debugger quite a bit, the way it works today is not very effective and I would like to remedy that, which will require more changes than what I mentioned above, because the above changes are blocked by the issues listed below, so a deeper analysis is necessary.

## Current debugger attribute functionality in PowerShell 6.1

For reference, a lot of what I have been reading on this subject is documented [here](https://docs.microsoft.com/en-us/visualstudio/debugger/just-my-code?view=vs-2017#BKMK__NET_Framework_Just_My_Code).

### DebuggerHidden (DH)

- Applies always, even if Just My Code (JMC) is turned off (more on JMC below)
- Step into is treated as step over
- Breakpoints not triggerable
- Shows up in call stack
    - BUG: according to DH docs in MSDN, DH frames should not appear in the call stack at all
    - FIX: identify and hide DH frames from the call stack, since they are truly meant to be internal/hidden functionality, and not for users to see
- Examples where this would be used: low-level formatting code that ships with a module or with PowerShell itself (i.e. format.ps1xml extensions), or PowerShell code invoked from a compiled executable (exe or dll) that is meant to be internal, and not visible to end users at all

### DebuggerStepThrough (DST)

- Step into is treated as step over
    - LEGACY: you can step into DST blocks in PowerShell 5.1, but that's not right either
    - BUG: Step into should be treated as step through, stopping on the first command that is not in a script block with DH or DST
    - FIX: when stepped into, the debugger should walk the code until it finds an invoked block that does not have one of these debugger attributes attached it it, and step into that code (this is what the name of this attribute means)
- Breakpoints always triggerable
    - DESIGN ISSUE: according to docs, breakpoints should not always be triggerable in DST blocks; instead, they should only be triggerable when JMC is disabled, so that users can debug code they didn't write if/when they need to (but not internal DH code, that's off limits); as things stand today, users can not debug as effectively because BPs are always triggerable in non-user code, even when this attribute is applied, and when you ship code, you want users to work with it as a black box by default, only being able to hit breakpoints in code that isn't theirs if they explicitly do something to make that happen
    - FIX: add Just My Code (JMC) support to PowerShell, as a debugger parameter that is on ($true) by default but can be turned off (set to $false), and have BPs triggerable in DST blocks only if JMC is turned off (all BP types)
    - ALT FIX: if having JMC supported as a feature is not desirable, only explicit breakpoints (ie. line breakpoints) should be triggerable (since this code is not owned by the scripter, they should have to explicitly place a BP in the code in order for it to trigger -- this design keeps variable and command breakpoints highly effective, and only designed for use with JMC, without having to add a JMC option)
    - ALT FIX 2: add JMC, but instead of having it be a JustMyCode boolean property, have it be an bitwise enum flag called NonUserCodeBreakpoints, allowing users to control what is allowed (options would include Disabled, meaning all non-user code breakpoints would be skipped, or a combination of Line, Command, and Variable enumeration values to identify which types of BPs could be triggered in non-user code)
    - THOUGHTS: There are pros/cons to each proposed fix. The first proposal would mean any BP could be triggerable in DST blocks, but adds an additional flag that must be disabled to allow that to happen. The second proposal avoids the need for a flag, but makes it impossible to trigger command/variable BPs in DST blocks. The third proposal provides the most control, satisfying both of the first two proposals, but needs a little more explanation/documentation. My preference is for the third option (ALT FIX 2), because it allows users to control what types of breakpoints should be supported in non-user code (which could be their own released modules if they are debugging a reported issue), without having to modify the code. If that is not desirable, then I would vote for the first option, so that all BP types could be turned on or off in non-user code.
- Shows up in call stack like any other command
    - BUG: DST docs state that DST frames should appear in the call stack as "[external]", visible via double-click, but otherwise not visible
    - FIX: render DST frames in the call stack as "[external]" with no arguments or location, unless Get-CallStack is invoked with a new -Force parameter, in which case users get to see DST frames.
- Examples where this would be used: your own commands that you have already debugged and don't want to step through unless you go out of your way to enable breakpointing in that code; your own commands that you've already debugged that invoke script block parameters; once you've debugged the commands themselves, you can add this attribute so that you can step through other code with the debugger without going through code that you don't need to go through 

### DebuggerNonUserCode (DNUC)

- Internally treated as DST today
    - DESIGN ISSUE: MSDN documentation states the following:
        > The debugger behavior when the DebuggerNonUserCodeAttribute is present is _similar_ to using a combination of the DebuggerHiddenAttribute attribute, which hides the code from the debugger, and the DebuggerStepThroughAttribute attribute, which tells the debugger to step through, rather than into, the code it is applied to.

        There is a difference between DNUC and DST, and the current implementation ignores this.
    - FIX: Like DH, breakpoints should never be triggerable in DNUC blocks, even when JMC is turned off, but unlike DH, DNUC frames should appear in the call stack as DST frames do (only when -Force'd), and users should be able to step through (not into) the DNUC blocks like they can with DST. Essentially DNUC is DST, but with no breakpoint support.

### All Debugger Attributes

- Users must re-apply them in any nested functions or script blocks that are invoked internally
    - DESIGN ISSUE: This results in bugs, even in PowerShell, because of scenarios where you
        need to invoke code in a new scope.
    - FIX: Whenever a debugger attribute is applied on a block of code, apply it recursively to
        all nested script blocks and functions as well

### Other Issues

While reviewing all of this, I discovered that Get-CallStack returns a bunch of StringBuilder data in the Arguments property in PowerShell 6.1. That's a bug that needs fixing as well.

### End result

The end result of these changes should result in debugger attributes behaving as follows:

||Step into|Breakpoints triggerable|Call stack visibility|
|--|--|--|--|
|DebuggerHidden|Treated as step over|Never|None|
|DebuggerStepThrough|Treated as step through|Depends on JMC settings <sup>1</sup>|Visible when -Force'd <sup>2</sup>|
|DebuggerNonUserCode|Treated as step through|Depends on JMC settings <sup>1</sup>|None|

<sup>1</sup> New option added to `ScriptDebugger` class.
<sup>2</sup> New parameter added to `Get-CallStack` cmdlet and related method.

### Outstanding questions

What about classes? I haven't dug into how these attributes work with classes/methods/properties
in PowerShell at all yet, but from the outside I think the exact same behavior would apply, and the only decisions would be whether or not these attributes can be applied on classes, methods, properties, accessors, etc.

That's enough of my thoughts on this for now. I'm looking forward to hearing more about the original intent for these attributes in PowerShell and helping figure out how they should be working to enable effective debugging.

**Comment by lzybkr** [comment]
That's a lot to discuss, maybe worth an RFC, or maybe this is the RFC?

Some quick thoughts:

* What is JMC from the PowerShell point of view? We don't have projects, so it's not clear.
* `Get-CallStack` is used in ways outside of debugging, it's default behavior shouldn't change. Internal debugger use could, but the cmdlet shouldn't.

**Comment by KirkMunro** [comment]
I thought about an RFC for this, given the depth, but it's also a relatively simple set of non-breaking changes to make, and I don't necessarily want to slow down the process (i.e. I'm hoping a few decisions can be made and/or clarifications identified in my analysis, so that I can just get it done).

In my mind, JMC from PowerShell is simply a line in the sand between scripts/functions/modules I write (that I want easy debugger access into) and the same that I don't write. If I ship a script/module that someone ends up using, and it's properly tested/debugged, ideally the functions in that module should run as close to compiled cmdlets do as possible, so that my logic does not impact their debugging experience with their own code. Using the debugger attributes, I also have the flexibility to add an attribute to hide some of my own code from the debugger, which I would want to do for modules I have tested as well, so that my debugging experience is optimal when using those commands as well. I think that's a pretty clear line in the sand that can be drawn, implicitly in the case of installed content (scripts/modules), and explicitly everywhere else I want to use it (or just make explicit use mandatory if we must, but there is an opportunity for implicit work here that I really like).

Regarding `Get-PSCallStack`, how is it used outside of debugging? Profiling? What if the behavior change was only in the default output in the F&O layer, marking certain frames as external? And for hidden frames showing, I wonder if that's a design flaw that should be fixed. Hidden should mean hidden.

**Comment by KirkMunro** [comment]
I would consider PowerShell code to be "My Code" if the following are true:

1. The code does not belong to an installed package (script or module).
1. The code does not have one of the following debugger attributes set on it: `DebuggerHidden`, `DebuggerStepThrough`, `DebuggerNonUserCode`.

That's it. If either of those are false, then it's not my code, in which case the JMC options proposed may allow me to set breakpoints in it and debug it, but only if it's not in a `DebuggerHidden` block of code.

I was thinking about scopes when you mentioned `Get-PSCallStack` use outside of the debugger, and how they should work with things like `DebuggerHidden` (i.e. should `Get-Variable -Scope 1` return variables in that scope if it uses `DebuggerHidden`? Or should `-Scope 1` be treated as the scope one level higher in that scenario, effectively hiding the frame (my preference).

Pushing the JMC and call stack parts of this aside, something I may work on that can (and should) be fixed is the step through logic (and breakpointing logic for `DebuggerHidden`) so that the debugger ends up where it needs to based on the attributes that are used. None of that is dependent on JMC. JMC really only applies to call stack visibility, influencing when breakpoints work, and applying default debugger attributes. I can probably get away with fixing the step through parts now and then pulling the JMC portions of this discussion into an RFC so that more eyes are on it, gathering more information in the meantime.

**Comment by KirkMunro** [comment]
Maybe. Need to think about profiles (all users profiles are user code, but they're just individual files). Given how people can put files anywhere though, and organize their system however they like, I think it would be better if products/apps could register a path for what is considered "**not** my code" instead. Maybe something like `$env:PSModulePath`, so users could also mark specific paths as not their code if products don't do it themselves (in cases where products install PowerShell scripts/modules outside of PowerShellGet/PackageManagement).

**Comment by rkeithhill** [comment]
I'd rather not have to know where Pester / PSSA is installed.  I mighth have installed it or maybe I'm using the versions installed under the install folder for the PowerShell extension for VSCode.  Also, the PowerShell extension for VSCode could register the workspaceFolder(s) paths and for "most" people that would be a sensible default.  

BTW we do this already to some extent in the extension's debug code.  We "dim" stack frames that are from script not under the current workspaceFolder.
