### ISSUE TITLE
PSCore - Where is the PowerShell Core GA version(s)?

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#7271]
On the releases page, I'm looking for the PowerShell Core 6.0 GA version. But, I can't find it. 
So, which of the non-Preview are GA releases.  

Or, should I assume that all non-Preview are actually GA's?

I think this should be address better in the Release Notes.  My organization only support GA release in  their products.

**Comment by bergmeister** [comment]
Preview releases are marked as preview, everything else is GA. But I agree, it is not very easy to find out as one has to scroll down quite a bit.
The latest GA release is 6.0.2 [here](https://github.com/PowerShell/PowerShell/releases/tag/v6.0.2)
Maybe it would be better to display the latest GA always at the very top or at least at 2nd place?

**Comment by iSazonov** [comment]
We have links on main page https://github.com/PowerShell/PowerShell#get-powershell

**Comment by MaximoTrinidad** [comment]
@iSazonov 

I see now. Of course... "Stable" = "GA".  Understood!

:)

**Comment by MaximoTrinidad** [comment]
@iSazonov 

Forgot to mention, my main point is more about the "Release Notes" not mention when the product release reached GA status.  I think it would be a "nice" to include in the notes.

:)

**Comment by iSazonov** [comment]
I believe this could be added in release check list.

**Comment by MaximoTrinidad** [comment]
@iSazonov,  

That would be Great!!
:)

**Comment by iSazonov** [comment]
@SteveL-MSFT Is the request about "GA in Release Notes" addressed? Can we close the issue?

**Comment by SteveL-MSFT** [comment]
I believe this can be closed
