### ISSUE TITLE
Invoke-RestMethod is giving errors when running on Linux Subsystem or Docker ubuntu official image.

### ISSUE THREAD

**Issue by deivisvieira** [PowerShell/PowerShell#7274]
So, we have a PS script that interacts with a few APIs of ours that is currently working on our dev environment (Win10). When we tried to publish it on a jenkins pipeline, we had this error "Access to the path '/.dotnet/corefx/cryptography/x509stores/ca' is denied.". So we went back to our scrapbook and tried to reproduce on our WLS and got this error this time: Peer certificate cannot be authenticated with given CA certificates

We've tried to manually register our certificate on linux but it had no effect,
We also tried to invoke a public rest API that uses a Google cert and it worked.

I'm not sure if the errors are related at all, but we couldn't find anything regarding this matter on the issues.

Steps to reproduce
------------------

Invoke-RestMethod to any of our servers that uses a GoDaddy SSL cert
The method is being called from:
1 - Docker official latest image;
2 - Ubuntu 18.04 (inside Windows 10)

Expected behavior
-----------------
Response of the given API call

Actual behavior
---------------
On docker image: Invoke-RestMethod : Access to the path '/.dotnet/corefx/cryptography/x509stores/ca' is denied.
On WLS: Invoke-RestMethod : Peer certificate cannot be authenticated with given CA certificates

Environment data
----------------

Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Linux 4.4.0-17134-Microsoft #137-Microsoft Thu Jun 14 18:46:00 PST 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by markekraus** [comment]
@deivisvieira Can you provide a public URI that can repro this issue as well as the parameters you are passing to invoke-restmethod?

**Comment by markekraus** [comment]
I am not able to reproduce in 6.1.0-preview.3 nor in 6.0.2 on Ubuntu 16.0.4 WSL with the following:

```powershell
Invoke-RestMethod -Uri https://www.godaddy.com/
```

We will require more details on how to reproduce the issue.

**Comment by deivisvieira** [comment]
@markekraus thanks for your response. I tried using the godaddy home to test but couldn't reproduce the issue. Once I find a public URL that throws this error I will post here.

**Comment by deivisvieira** [comment]
Apparently our public SSL certificate was incorrectly being used on our internal API also. Removing that invalid certificate resolved the issue.
@markekraus thanks for the time and response anyways, appreciate it.
