### ISSUE TITLE
macOS launcher application does not work.

### ISSUE THREAD

**Issue by thezim** [PowerShell/PowerShell#7275]
PowerShell does not open when using the macOS launcher. Script needs to be updated to reflect binary name change.

https://github.com/PowerShell/PowerShell/blob/79d20a187309717b5f7f73b26192a2d815c48395/tools/packaging/macos/launcher/ROOT/Applications/PowerShell.app/Contents/MacOS/PowerShell.sh#L2

Steps to reproduce
------------------

Open /Applications/PowerShell from Finder.

Expected behavior
-----------------

PowerShell open in Terminal.

Actual behavior
---------------

PowerShell does not open.

Environment data
----------------
```powershell
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.3
PSEdition                      Core
GitCommitId                    v6.1.0-preview.3
OS                             Darwin 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RE...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
@thezim: Looks like a duplicate of #7074, correct?

**Comment by thezim** [comment]
@mklement0 Yes. I’ll close this one.
