### ISSUE TITLE
Including modified PowerShell source files in another project

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#7279]
I'm looking to include a few classes from this repo (mainly around AST type inference) in a project.  The files have been modified, mostly to replace internal API calls.

Should I include the copyright headers on the modified files?  Or would a third party notices file be sufficient?

**Comment by SteveL-MSFT** [comment]
@SeeminglyScience let me get back to you on this

**Comment by SeeminglyScience** [comment]
@SteveL-MSFT Any updates on this? I know it's not a quick question to answer, just making sure it doesn't fall through the cracks.

**Comment by SteveL-MSFT** [comment]
@SeeminglyScience sorry, will ping legal again

**Comment by SteveL-MSFT** [comment]
@SeeminglyScience the recommendation is to attribute in a top level ThirdPartyNotices.txt file
