### ISSUE TITLE
Custom-class and enum type literals are not recognized by tab completion

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#7287]
<sup>Note: Updated based on feedback from @daxian-dbw below.</sup>

**Any custom `class` and `enum` instances added to a session are currently not recognized by tab completion**, whereas analogous definitions created via `Add-Type` based on strings containing C# source code are:

Steps to reproduce
------------------

```powershell
# Define a custom enum
enum Fruit { Apple = 1; Orange = 2}
# Define an equivalent enum via Add-Type and C# code
Add-Type -TypeDefinition 'public enum SharpFruit { Apple = 1, Orange = 2 }'

PS> [fru<tab-keypress>
PS> [sharpfru<tab-keypress>
```

Expected behavior
-----------------

`[fru<tab-keypress>` should complete to `[Fruit]`
`[sharpfru<tab-keypress>` should complete to `[SharpFruit]`

Actual behavior
---------------

`[fru<tab-keypress>` performs no completion.

By contrast, `[sharpfru<tab-keypress>` completes as expected.

Environment data
----------------

```powershell
PowerShell Core v6.1.0-preview.3 on macOS 10.13.5
PowerShell Core v6.1.0-preview.3 on Ubuntu 16.04.4 LTS
PowerShell Core v6.1.0-preview.3 on Microsoft Windows 10 Pro (64-bit; Version 1709, OS Build: 16299.371)
Windows PowerShell v5.1.17134.48 on Microsoft Windows 10 Pro (64-bit; Version 1709, OS Build: 16299.371)
```

**Comment by daxian-dbw** [comment]
Not just enum, powershell class, in general, doesn't have tab completion support when it comes to type reference such as `[Fru<tab>`.

**Comment by mklement0** [comment]
Thanks, @daxian-dbw - should I make this issue about all custom classes then, or is this already being tracked elsewhere?

**Comment by daxian-dbw** [comment]
@mklement0 Please make this issue about all custom powershell classes. I don't know of an existing issue.

**Comment by mklement0** [comment]
@daxian-dbw: Sounds good - I've update the initial post.
