### ISSUE TITLE
Task Scheduler CIM Issues

### ISSUE THREAD

**Issue by somewhatlogical** [PowerShell/PowerShell#7292]
I am unsure if this is a bug in task scheduler and how it registers itself with CIM, or if there's something on the PS end.  This effects at least 5 and core (guessing like everything though).  These and others basically result in the inability to use the built-in PS5 task scheduler Cmdlets to add triggers for these types that aren't handled on the Cmdlet (ie:  by manually creating CimClass for the trigger types missing to try to put them in that means).  Also, invalid data is returned since the PS class returns these cim instances.

I've noticed two issues (I'm guessing there are more):

1. Classes do not have correct types on the properties.  Note I've only included one example, though have seen several other instances.  I think most of these triggers should be gone through to type appropriately, since I know I've seen at least one other somewhere that seemed like it was incorrect.  The problem is that the values cannot be set because they become out of range due to incorrect typing on the CIM class (ie:  it's impossible to pass all available combinations through using a CIM instance and the existing New-ScheduledTask*, which basically removes some of the various combinations of months/days/weeks/etc. you can use).  I presume this also makes the values impossible to retrieve reliably using the built in *-ScheduledTask* cmdlets for scheduled tasks (or on Core through CIM directly... would sure be cool if getting working functionality on Windows for these extremely common administrative tasks was a priority before abstracting out the OS layer).

Steps to reproduce
------------------
$tempCimClass = Get-CimClass -ClassName MSFT_TaskMonthlyTrigger  `
                -Namespace Root/Microsoft/Windows/TaskScheduler:MSFT_TaskMonthlyTrigger
$tempCimClass | Select *

Expected behavior
-----------------
Name               : DaysOfMonth
Value              :
CimType            : UInt32 (really, if going by the API this should be a non-nullable long)
Flags              : Property, NullValue
Qualifiers         : {}
ReferenceClassName :

Actual behavior
---------------
Name               : DaysOfMonth
Value              :
CimType            : UInt16
Flags              : Property, NullValue
Qualifiers         : {}
ReferenceClassName :

---------------------------------------

2.  Some classes are not typed correctly.  The instance I saw of this was on both the Monthly and MonthlyDOWTrigger.  When it is returned, it is typed as its base class (MSFT_TaskTrigger), and thus does not have the all the properties available on it for retrieval.  You can get the actual classes (as they currently exist in CIM, **but note issue 1 where the types on these and possibly others are incorrect**; this example is just pulling the existing from CIM, not showing what the corrected data types would be since I don't know what standard you guys use for that) here:
$tempCimClass = Get-CimClass -ClassName MSFT_TaskMonthlyTrigger  `
                -Namespace Root/Microsoft/Windows/TaskScheduler:MSFT_TaskMonthlyTrigger
            $tempCreatedTrigger = New-CimInstance -CimClass $tempCimClass -ClientOnly
$tempCimClass.CimClassProperties | Select *

$tempCimClass = Get-CimClass -ClassName MSFT_TaskMonthlyDOWTrigger  `
                -Namespace Root/Microsoft/Windows/TaskScheduler:MSFT_TaskMonthlyDOWTrigger
            $tempCreatedTrigger = New-CimInstance -CimClass $tempCimClass -ClientOnly
$tempCimClass.CimClassProperties | Select *

Steps to reproduce
------------------

Create monthly and monthly DOW trigger
![image](https://user-images.githubusercontent.com/26860540/42737231-51367384-8836-11e8-80c0-77374af0c570.png)

In PS:

$temp = (get-ciminstance -ClassName 'MSFT_ScheduledTask' `
        -Namespace 'Root/Microsoft/Windows/TaskScheduler' `
        -Shallow:$false
    ) `
| Where-Object { `
    $_.TaskName -like 'test2' `
}

$temp.Triggers | Select *

Expected behavior
-----------------

Enabled               : False
EndBoundary           : 2019-07-13T21:50:17-05:00
ExecutionTimeLimit    :
Id                    :
Repetition            : MSFT_TaskRepetitionPattern
StartBoundary         : 2018-07-13T21:50:15-05:00
PSComputerName        :
CimClass              : Root/Microsoft/Windows/TaskScheduler:MSFT_**TaskMonthlyTrigger**
CimInstanceProperties : {Enabled, EndBoundary, ExecutionTimeLimit, Id...}
CimSystemProperties   : Microsoft.Management.Infrastructure.CimSystemProperties

...CimInstanceProperties
Name               : Enabled
Value              :
CimType            : Boolean
Flags              : Property, NullValue
Qualifiers         : {}
ReferenceClassName :

Name               : EndBoundary
Value              :
CimType            : String
Flags              : Property, NullValue
Qualifiers         : {}
ReferenceClassName :

Name               : ExecutionTimeLimit
Value              :
CimType            : String
Flags              : Property, NullValue
Qualifiers         : {}
ReferenceClassName :

Name               : Id
Value              :
CimType            : String
Flags              : Property, NullValue
Qualifiers         : {}
ReferenceClassName :

Name               : Repetition
Value              :
CimType            : Instance
Flags              : Property, NullValue
Qualifiers         : {EmbeddedInstance}
ReferenceClassName : MSFT_TaskRepetitionPattern

Name               : StartBoundary
Value              :
CimType            : String
Flags              : Property, NullValue
Qualifiers         : {}
ReferenceClassName :

Name               : DaysOfMonth
Value              :
CimType            : UInt16
Flags              : Property, NullValue
Qualifiers         : {}
ReferenceClassName :

Name               : MonthOfYear
Value              :
CimType            : UInt16
Flags              : Property, NullValue
Qualifiers         : {}
ReferenceClassName :

Name               : RandomDelay
Value              :
CimType            : String
Flags              : Property, NullValue
Qualifiers         : {}
ReferenceClassName :

Name               : RunOnLastDayOfMonth
Value              :
CimType            : Boolean
Flags              : Property, NullValue
Qualifiers         : {}
ReferenceClassName :

--------------------------------
Enabled               : False
EndBoundary           :
ExecutionTimeLimit    :
Id                    :
Repetition            : MSFT_TaskRepetitionPattern
StartBoundary         : 2018-07-15T13:47:26
PSComputerName        :
CimClass              : Root/Microsoft/Windows/TaskScheduler:MSFT_**TaskMonthlyDOWTrigger**
CimInstanceProperties : {Enabled, EndBoundary, ExecutionTimeLimit, Id...}
CimSystemProperties   : Microsoft.Management.Infrastructure.CimSystemProperties

...CimInstanceProperties

Name               : Enabled
Value              :
CimType            : Boolean
Flags              : Property, NullValue
Qualifiers         : {}
ReferenceClassName :

Name               : EndBoundary
Value              :
CimType            : String
Flags              : Property, NullValue
Qualifiers         : {}
ReferenceClassName :

Name               : ExecutionTimeLimit
Value              :
CimType            : String
Flags              : Property, NullValue
Qualifiers         : {}
ReferenceClassName :

Name               : Id
Value              :
CimType            : String
Flags              : Property, NullValue
Qualifiers         : {}
ReferenceClassName :

Name               : Repetition
Value              :
CimType            : Instance
Flags              : Property, NullValue
Qualifiers         : {EmbeddedInstance}
ReferenceClassName : MSFT_TaskRepetitionPattern

Name               : StartBoundary
Value              :
CimType            : String
Flags              : Property, NullValue
Qualifiers         : {}
ReferenceClassName :

Name               : DaysOfWeek
Value              :
CimType            : UInt16
Flags              : Property, NullValue
Qualifiers         : {}
ReferenceClassName :

Name               : MonthOfYear
Value              :
CimType            : UInt16
Flags              : Property, NullValue
Qualifiers         : {}
ReferenceClassName :

Name               : RandomDelay
Value              :
CimType            : String
Flags              : Property, NullValue
Qualifiers         : {}
ReferenceClassName :

Name               : RunOnLastWeekOfMonth
Value              :
CimType            : Boolean
Flags              : Property, NullValue
Qualifiers         : {}
ReferenceClassName :

Name               : WeeksOfMonth
Value              :
CimType            : UInt16
Flags              : Property, NullValue
Qualifiers         : {}
ReferenceClassName :
……….

Actual behavior
---------------

Enabled               : False
EndBoundary           : 2019-07-13T21:50:17-05:00
ExecutionTimeLimit    :
Id                    :
Repetition            : MSFT_TaskRepetitionPattern
StartBoundary         : 2018-07-13T21:50:15-05:00
PSComputerName        :
CimClass              : Root/Microsoft/Windows/TaskScheduler:MSFT_**TaskTrigger**
CimInstanceProperties : {Enabled, EndBoundary, ExecutionTimeLimit, Id...}
CimSystemProperties   : Microsoft.Management.Infrastructure.CimSystemProperties

….CimInstanceProperties

Name            : Enabled
Value           : False
CimType         : Boolean
Flags           : Property, NotModified
IsValueModified : False

Name            : EndBoundary
Value           : 2019-07-13T21:50:17-05:00
CimType         : String
Flags           : Property, NotModified
IsValueModified : False

Name            : ExecutionTimeLimit
Value           :
CimType         : String
Flags           : Property, NotModified, NullValue
IsValueModified : False

Name            : Id
Value           :
CimType         : String
Flags           : Property, NotModified, NullValue
IsValueModified : False

Name            : Repetition
Value           : MSFT_TaskRepetitionPattern
CimType         : Instance
Flags           : Property, NotModified
IsValueModified : False

Name            : StartBoundary
Value           : 2018-07-13T21:50:15-05:00
CimType         : String
Flags           : Property, NotModified
IsValueModified : False

-------

Enabled               : False
EndBoundary           :
ExecutionTimeLimit    :
Id                    :
Repetition            : MSFT_TaskRepetitionPattern
StartBoundary         : 2018-07-15T13:47:26
PSComputerName        :
CimClass              : Root/Microsoft/Windows/TaskScheduler:MSFT_**TaskTrigger**
CimInstanceProperties : {Enabled, EndBoundary, ExecutionTimeLimit, Id...}
CimSystemProperties   : Microsoft.Management.Infrastructure.CimSystemProperties

…CimInstanceProperties

Name            : Enabled
Value           : False
CimType         : Boolean
Flags           : Property, NotModified
IsValueModified : False

Name            : EndBoundary
Value           : 2019-07-13T21:50:17-05:00
CimType         : String
Flags           : Property, NotModified
IsValueModified : False

Name            : ExecutionTimeLimit
Value           :
CimType         : String
Flags           : Property, NotModified, NullValue
IsValueModified : False

Name            : Id
Value           :
CimType         : String
Flags           : Property, NotModified, NullValue
IsValueModified : False

Name            : Repetition
Value           : MSFT_TaskRepetitionPattern
CimType         : Instance
Flags           : Property, NotModified
IsValueModified : False

Name            : StartBoundary
Value           : 2018-07-13T21:50:15-05:00
CimType         : String
Flags           : Property, NotModified
IsValueModified : False

……...

**Comment by danielboth** [comment]
Having the same issue with the Monthly and MonthlyDOW trigger types. Additionally, it is also not possible to create a task using one of these schedule types in PowerShell.

**Comment by gmitch64** [comment]
I'm also having issues creating a task with a Monthly DoW trigger. Been bashing my head again the wall trying to get it to work before someone pointed me here.

**Comment by bc-nf** [comment]
+1 on Monthly Triggers missing from get-scheduledtask -- I assume the issues with creating are a problem too as mentioned above, but I've not had a reason to test/use them via PS.

**Comment by davehope** [comment]
Commenting to keep the issue open.

**Comment by Fantasillion** [comment]
+1. The documentation for task scheduler in Powershell has both daily and weekly but no monthly (- and perhaps also no yearly?). This may be closed but it is definitely not resolved.

**Comment by Borgquite** [comment]
Playing with this today **in a completely unsupported way - only do this on a test system, and at your own risk**!

The types returned by Get-CimClass appear to be defined in 

`C:\Windows\System32\wbem\SchedProv.mof`

```
class MSFT_TaskMonthlyDOWTrigger : MSFT_TaskTrigger
{
	boolean RunOnLastWeekOfMonth;
	string RandomDelay;
	uint16 MonthOfYear;
	uint16 WeeksOfMonth;
	uint16 DaysOfWeek;
};

class MSFT_TaskMonthlyTrigger : MSFT_TaskTrigger
{
	boolean RunOnLastDayOfMonth;
	string RandomDelay;
	uint16 MonthOfYear;
	uint16 DaysOfMonth;
};
```

And if you edit these, the output of Get-CimInstance changes. (for example, modifying 'DaysOfMonth' from unit16 to unit32 or sint64 etc)

Run this command to recompile the MOF and apply the changes

`mofcomp ([Environment]::GetFolderPath("System") + "\wbem\SchedProv.mof")`

NB also that in the MOF file it says 'MonthOfYear' whereas the underling APIs use 'MonthsOfYear' for both - perhaps also related to the issue?

https://learn.microsoft.com/en-us/windows/win32/taskschd/monthlytrigger-monthsofyear
https://learn.microsoft.com/en-us/windows/win32/api/taskschd/nf-taskschd-imonthlytrigger-get_monthsofyear

I still haven't been able to get the correct CimClass returned for a Monthly or MonthlyDOW trigger via (`Get-ScheduledTask -TaskName <taskname>).Triggers.CimClass.CimClassName` yet, but perhaps more experimentation might yield success.
