### ISSUE TITLE
Supporting RFC 7617  in Invoke-WebRequest - UTF-8 in Basic Authentication and Non ASCII passwords

### ISSUE THREAD

**Issue by mvadu** [PowerShell/PowerShell#7293]
RFC 7617 asks the client to send the Basic Authentication header `Authorization` to be encoded in `UTF-8`. Currently `Invoke-WebRequest` when invoked with a `-Credential` parameter with a non-ascii password, basic authentication fails as it does not pass the password in UTF-8.

Example, I setup Influxdb with a non-ascii password

```
$user = "admin"
$passwd = "test123€€€üöä§"
```

I passed these as `-credential $(New-Object System.Management.Automation.PSCredential($user, $(ConvertTo-SecureString $passwd -AsPlainText -Force)))` which results in two requests. First one without any Auth header, and server is following RFC 7617 and indicates it expects UTF-8 auth header. Second is with Auth header, but it does not work.

```
POST http://ubuntu:8086/query? HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT; Windows NT 10.0; en-US) WindowsPowerShell/5.1.17713.1000
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Host: ubuntu:8086
Content-Length: 12


HTTP/1.1 401 Unauthorized
Content-Type: application/json
Request-Id: eeac4ae3-889f-11e8-8024-00155d163e0e
Www-Authenticate: Basic realm="InfluxDB"
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.7.0~n201807150800
X-Request-Id: eeac4ae3-889f-11e8-8024-00155d163e0e
Date: Mon, 16 Jul 2018 02:28:32 GMT
Content-Length: 55
------------------------------------------------------------------
POST http://ubuntu:8086/query? HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT; Windows NT 10.0; en-US) WindowsPowerShell/5.1.17713.1000
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Authorization: Basic YWRtaW46dGVzdDEyM4CAgPz25Kc=
Host: ubuntu:8086
Content-Length: 12


HTTP/1.1 401 Unauthorized
Content-Type: application/json
Request-Id: eead64b4-889f-11e8-8025-00155d163e0e
Www-Authenticate: Basic realm="InfluxDB"
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.7.0~n201807150800
X-Request-Id: eead64b4-889f-11e8-8025-00155d163e0e
Date: Mon, 16 Jul 2018 02:28:32 GMT
Content-Length: 33
```

Next I manually added UTF-8 header with `-Header $(@{Authorization = "Basic $([System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("$($user):$($passwd)")))"})` and it works just fine.

```
POST http://ubuntu:8086/query? HTTP/1.1
Authorization: Basic YWRtaW46dGVzdDEyM+KCrOKCrOKCrMO8w7bDpMKn
User-Agent: Mozilla/5.0 (Windows NT; Windows NT 10.0; en-US) WindowsPowerShell/5.1.17713.1000
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Host: ubuntu:8086
Content-Length: 12
Connection: Keep-Alive


HTTP/1.1 200 OK
Content-Type: application/json
Request-Id: e00cb7e6-889f-11e8-8023-00155d163e0e
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.7.0~n201807150800
X-Request-Id: e00cb7e6-889f-11e8-8023-00155d163e0e
Date: Mon, 16 Jul 2018 02:28:07 GMT
Transfer-Encoding: chunked
```

**Comment by markekraus** [comment]
@mvadu 

Please provide the full `Imvoke-WebRequest` command you are issuing.

If you are just using `Invoke-WebRequest -Uri $Uri -Credential $Credential`, Then you will need to open an issue in CoreFX as PowerShell only passes the provided credentials to [`HttpClientHelper.Credential`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.credentials?view=netcore-2.1). That is an older style of API and unlikely to change for legacy support.

If you use `Invoke-WebRequest -Uri $Uri -Credential $Credential -Authentication Basic` That should fully support RFC-7617 https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-6#optional-parameters. If that is not working properly then we have a bug here.

**Comment by mvadu** [comment]
@markekraus  I am on latest insider version of Windows, but apparently still not on PS v6. 

```
$r = Invoke-WebRequest -Method Post -Uri "http://ubuntu:8086/query?" -Body "q=Show stats" -UseBasicParsing -ContentType $contentType -credential $(New-Object System.Management.Automation.PSCredential($user, $(ConvertTo-SecureString $new_passwd -AsPlainText -Force))) -Authentication Basic
Invoke-WebRequest : A parameter cannot be found that matches parameter name 'Authentication'.
At line:1 char:268
+ ... SecureString $new_passwd -AsPlainText -Force))) -Authentication Basic
+                                                     ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17713.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17713.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by markekraus** [comment]
@mvadu You will need to open a [UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell) issue for Windows PowerShell. This GitHub rep is only for PowerShell Core 6+ issues. As we currently have RFC-7617 support beginning with PowerShell 6.0.0, I would suggest using PowerShell 6.0.0 or newer for your code that required RFC-7617 support. You can run PowerShell Core side-by-side with Windows PowerShell 5.1.

As there appears to be no issue with PowerShell Core, I will close this issue.
