### ISSUE TITLE
Classes: an uninitialized [string] property defaults to $null rather than the empty string

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#7294]
This is an inconsistency discovered by @alx9r:

If you define a class property of type `[string]` without assigning an initial value, its value is unexpectedly `$null`, even though in all other contexts PowerShell defaults `[string]` values to `''` (the empty string) and even converts explicitly assigned `$null` to `''`.

Steps to reproduce
------------------

```powershell
class c { [string] $prop }; $null -eq [c]::new().prop
class c { [string] $prop = $null }; $null -eq [c]::new().prop
class c { [string] meth() { return $null } }; $null -eq [c]::new().meth()
```

Expected behavior
-----------------

```none
False
False
False
```

Actual behavior
---------------

```none
True
False
False
```

That is, the uninitialized `[string]` property unexpectedly contains `$null`.

Environment data
----------------

```powershell
PowerShell Core v6.1.0-preview.3 on macOS 10.13.5
PowerShell Core v6.1.0-preview.3 on Ubuntu 16.04.4 LTS
PowerShell Core v6.1.0-preview.3 on Microsoft Windows 10 Pro (64-bit; Version 1709, OS Build: 16299.371)
Windows PowerShell v5.1.17134.48 on Microsoft Windows 10 Pro (64-bit; Version 1709, OS Build: 16299.371)
```

**Comment by mattpwhite** [comment]
Is this unexpected?  I know that I would personally be very surprised to find string members initialized to empty strings.  I would expect class members to have default values as they do in other .NET languages.  Coercing null to empty string is already a confusing foot gun in other contexts, I wouldn’t want to see it extended to classes.

**Comment by mklement0** [comment]
@mattpwhite: 

The primary purpose of this issue is to show the _lack of consistency_.

I suggested resolving the inconsistency toward PowerShell-like behavior, because, as demonstrated, in the majority of cases you already _do_ get the surprising behavior in the context of custom classes - in line with non-class PowerShell behavior: 

  * assigning `$null` to a `[string]`-typed property or variable
  * returning `$null` from a `[string]`-typed method.

(Ideally, PowerShell itself should also default `[string]` instances to `$null`, but [that ship has sailed](https://github.com/PowerShell/PowerShell/issues/4616#issuecomment-323530442))

That said, in other respects classes are closer to C# behavior, not least syntactically.

So I suppose resolving the inconsistency toward C#-like behavior (allowing assigning `$null` to `[string]` variables/properties / returning `$null` from `[string]`-typed methods) is another option.

Both resolutions are technically breaking changes, so a third option is to simply live with the inconsistency and merely document it.

I can't really speak to the guiding principles behind the behavior of PowerShell classes.
Perhaps @lzybkr  can help out.
