### ISSUE TITLE
Cannot run Python Interpreter remotely with PSSession

### ISSUE THREAD

**Issue by clayms** [PowerShell/PowerShell#7295]
Running the Python Interpreter on a particular Windows machine locally and remotely using ssh works great. However, Windows does not have a Linux screen equivalent, so I want to switch to using PSSession to remote into this Windows machine so I can start jobs, then disconnect and reconnect later to get the results.

The problem is when I successfully connect via PSSession and can run many powershell commands and scripts without issue, when I type python as I would locally or remotely with ssh, nothing happens. Only the PSSession remote command prompt is returned on the next line. There are no errors reported.

Can the Python Interpreter be run remotely on Windows with PSSession?

Do I need to set additional [PSSessionOptions](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/new-pssessionoption?view=powershell-6)?

**Comment by clayms** [comment]
Looks like the answer *was* No.
https://stackoverflow.com/a/21466434/5060792

Is it still?

**Comment by MaximoTrinidad** [comment]
OK!!  This is what I've done.

No! You can't open Python on a Enter-PSSession. 

But, you can execute Python with the code:
```
:
PS /home/user01/$results = python -c $RunPython;
:
```
![pscorelinuxpython_01_2018-07-16_12-15-51](https://user-images.githubusercontent.com/19892435/42770063-108b4c12-88f2-11e8-81b0-a790bfbfbc9b.jpg)

**Comment by iSazonov** [comment]
Continue in #7581.
