### ISSUE TITLE
PowerShell Core release for v6.1.0-preview.4

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#7303]
From:  https://github.com/PowerShell/PowerShell/blob/master/docs/maintainers/releasing.md

- [x] Create a private branch named `release-v6.1.0-preview.4` in VSTS repository.
   All release related changes should happen in this branch.
- [x] Run tests on all supported Linux distros and publish results
- [x] Prepare packages
   - [x]  Build release packages
   - [x]  Sign the MSI packages and RPM package.
   - [x]  Install and verify the packages.
- [x]  Update documentation, scripts and Dockerfiles
   - [x]  Update [CHANGELOG.md](../../CHANGELOG.md) with the finalized change log draft.
   - [x]  Update other documents and scripts to use the new package names and links.
- [x]  Create NuGet packages and publish them to `powershell-core` feed.
- [x]  Publish Linux packages to Microsoft YUM/APT repositories.
- [x]  Create the release tag and push the tag to `PowerShell/PowerShell` repository.
- [x]  Create the draft and publish the release in Github.
- [x]  Merge the release branch to Github `master` with a merge commit. Then delete the release branch.
- [x]  Trigger the release docker builds for Linux and Windows container images.

**Comment by iSazonov** [comment]
I wonder why we stopped creating milestones https://github.com/PowerShell/PowerShell/milestones -  I believe creating milestones and assigning issues to it help community members to plan their process.

**Comment by TravisEz13** [comment]
We will try to do this in the future.

**Comment by TravisEz13** [comment]
OS                           Total Pass Fail Pending Skipped
--                           ----- ---- ---- ------- -------
CentOS Linux 7 (Core)         8435 6703    3     338    1391
Debian GNU/Linux buster/sid   8521 6781    7     340    1393
Debian GNU/Linux 9 (stretch)  8435 6702    2     340    1391
openSUSE Leap 42.3            8435 6704    3     337    1391
Red Hat Enterprise Linux      8435 6703    1     340    1391
Ubuntu 14.04.5 LTS            8440 6708    1     340    1391
Ubuntu 16.04.4 LTS            8440 6708    1     340    1391
