### ISSUE TITLE
ConvertFrom-Json does not convert Newtonsoft.Json specific metadata properties in root object

### ISSUE THREAD

**Issue by louistio** [PowerShell/PowerShell#7307]
Steps to reproduce
------------------

```powershell
> '{"$id": 1, "$type": "System.String", "id": "value"}' | ConvertFrom-Json
```
1. Add `$id` and `$type` properties to a json object
2. Pipe object to `ConvertFrom-Json` Cmdlet
3. Notice that `$id` and `$type` properties are missing from resulting `PSCustomObject`

Expected behavior
-----------------
`ConvertFrom-Json` does not ignore properties when deserializing into generic `PSCustomObject`, regardless of their name.
```powershell
> '{"$id": 1, "$type": "System.String", "id": "value"}' | ConvertFrom-Json

$id $type         id
--- -----         --
  1 System.String value
```

Actual behavior
---------------

```powershell
> '{"$id": 1, "$type": "System.String", "id": "value"}' | ConvertFrom-Json

id
--
value
```

Additional Notes
---------------
- Issue does not occur when metadata properties are deeper in the hierarchy.
- Other `Newtonsoft.Json` metadata properties include `$values` and `$ref`.

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.3
PSEdition                      Core
GitCommitId                    v6.1.0-preview.3
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by markekraus** [comment]
I can repro this. It also repros with `-AsHashtable` and it does not repro on nested objects, only root.

```powershell
('{"a":{"$id": 1, "$type": "System.String", "id": "value"}}' | ConvertFrom-Json).a
```

result:

```none
$id $type         id
--- -----         --
  1 System.String value
```
