### ISSUE TITLE
Update package name "ubuntu 17.10" -> "ubuntu 18.04"

### ISSUE THREAD

**Issue by anmenaga** [PowerShell/PowerShell#7310]
Ubuntu 17.10 reached End of Life.
The supported upgrade path from Ubuntu 17.10 is via Ubuntu 18.04 LTS.

Currently package file name is "powershell-preview_6.1.0~preview.4-1.ubuntu.17.10_amd64.deb".

**Comment by TravisEz13** [comment]
I think we already added 18.04.  We should add 18.10

**Comment by Jaykul** [comment]
Please!

**Comment by TravisEz13** [comment]
Maintaining packages for the non-LTS releases has been painful.  We are adding community support for 18.10 and 19.04 via the snap package.
