### ISSUE TITLE
Where are released v6.1.0-preview.3 and v6.1.0-preview.4?

### ISSUE THREAD

**Issue by nightroman** [PowerShell/PowerShell#7320]
Is it just me or released v6.1.0-preview.3 and v6.1.0-preview.4 disappeared from the Releases page?

**Comment by kilasuit** [comment]
not just you @nightroman - I was also looking for these this morning

**Comment by kilasuit** [comment]
though they may still be in flight as per #7303 & #7304

**Comment by nightroman** [comment]
I downloaded v6.1.0-preview.4 a few hours ago.
v6.1.0-preview.3 was available for a long time.
Then both disappeared.

**Comment by markekraus** [comment]
I'm going to speculate that 6.1.0-preview.3 was pulled due to PowerShell/Announcements#6. I have no clue on the 6.0.3 and 6.1.0-preview releases. I can only speculate that those releases were not yet fully ready.

**Comment by krushmike** [comment]
Seems MS is all jumbled right now with this.  The security announcement indicates all releases prior to 6.0.3, however 6.0.3 is missing entirely, from both the download link I was using yesterday to the release page.  Hopefully they get this ironed out soon.

**Comment by krushmike** [comment]
Perhaps they could at least update https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/metadata.json to 6.0.2 until 6.0.3 is ready?  This is breaking install scripts.  Guess this is a chicken and egg situation.

**Comment by MaximoTrinidad** [comment]
Well,  yesterday I installed it and it did show both releases: GA 6.0.3 and Preview.4
Ha! That's a bubu!

![nomorepscore_2018-07-20_12-43-31](https://user-images.githubusercontent.com/19892435/43014582-a6c693d2-8c1a-11e8-845f-0cbf313d87c3.jpg)

**Comment by TravisEz13** [comment]
There was a signing issue.  We are revising the release draft and will republish it soon.  Sorry, we were not aware that they disappeared while we are revising the drafts

**Comment by daxian-dbw** [comment]
The `preview.3` release was accidentally removed during yesterday's publishing process. It's now republished. We apologize for all the inconveniences.

**Comment by TravisEz13** [comment]
We have republished the edited drafts.  preview.3 was changed to a pre-release.  The MSI's on 6.0.3 and 6.1.0-preview.4 were replaced with the signed versions with notes about both hashes.
