### ISSUE TITLE
Request: call it `posh` rather than `pwsh`

### ISSUE THREAD

**Issue by mikemaccana** [PowerShell/PowerShell#7323]
Heya!

Powershell 6 is `pwsh`. But folks in the Powershell community have called it `posh` for more than a decade now. It would be cool for the command to do the same.

<img src="https://media.giphy.com/media/OFcP2ojNIAkec/giphy.gif"/>

**Comment by kvprasoon** [comment]
@mikemaccana  What do you mean by CALL here ? are you referring to the executable name(pwsh.exe) ?

**Comment by kvprasoon** [comment]
There are reasons why we didn't(were not able to) use `posh`. [see](https://github.com/PowerShell/PowerShell/issues/4214 ) this .

**Comment by SteveL-MSFT** [comment]
@mikemaccana within the Community, people call it `posh` and as far as I'm concerned `pwsh` is pronounced `posh`.  However, as @kvprasoon pointed out, we've been through this discussion and we couldn't use `posh` literally as it's an existing shell
