### ISSUE TITLE
Request for PowerShell for ARM64 Ubuntu

### ISSUE THREAD

**Issue by michal5520pl** [PowerShell/PowerShell#7330]
Hi
Is there any possibility for creating PowerShell for Ubuntu ARM64 and ARM32?
Thanks,
Michał.

**Comment by SteveL-MSFT** [comment]
@michal5520pl I believe the Raspbian ARM32 build should just work on Ubuntu ARM32 (barring a known crashing issue due to dotnetcore...) as Raspbian is an Ubuntu derivative.  We can enable the current build script to support Linux ARM64 so that builds can be produced.

**Comment by SteveL-MSFT** [comment]
@slide I'll see if I can look into this later this week just to enable such builds, but it's unlikely we'll be able to support it and have official releases due to lack of hardware to test on

**Comment by slide** [comment]
@SteveL-MSFT I'd be happy to help out any way I can. Is there a bootstrapping document that would allow me to build it myself ON my ARM64 system? I'm using the PINE64 board (https://www.pine64.org/) which is a fairly cheap 64-bit ARM setup if you want something.

**Comment by michal5520pl** [comment]
I have BananaPi W2 with Ubuntu 16.04, so I can also offer help

**Comment by slide** [comment]
@SteveL-MSFT Any updates on this? As I mentioned, if I had some bootstrapping information for when I don't already have pwsh available, I'd be happy to try building it on my own.

**Comment by SteveL-MSFT** [comment]
I'm busy this week prepping for PSConfAsia, I'll see about spending some time after 10/21.  If you want to try to get this to work, it should "simply" be a change in `builds.psm1` at the root of this repo to support `linux-arm64` RID in `start-psbuild` cmdlet.

**Comment by slide** [comment]
I was able to get it to build. I will try and create a PR for PowerShell-Native and PowerShell.

**Comment by slide** [comment]
See https://github.com/PowerShell/PowerShell/pull/8016 and https://github.com/PowerShell/PowerShell-Native/pull/16

**Comment by SteveL-MSFT** [comment]
https://github.com/PowerShell/PowerShell/releases/download/v6.2.0-preview.3/powershell-6.2.0-preview.3-linux-arm64.tar.gz

**Comment by slide** [comment]
:+1: thanks!

**Comment by slide** [comment]
Would the project be open to building debs for arm64 as well? I believe for supports this with the `-a` parameter

**Comment by SteveL-MSFT** [comment]
@slide feel free to submit a PR to build debs for arm64 :)
