### ISSUE TITLE
Task Scheduler DLL First-Call on Method issue

### ISSUE THREAD

**Issue by somewhatlogical** [PowerShell/PowerShell#7331]
I was working on a wrapper for dahall/TaskScheduler since I couldn't find any non-COM working solution for managing scheduled tasks (#7292), and came up with some interesting behavior when going through PS Core against a .NET Standard DLL.  Basically, on the first method call to file checks when using the task scheduler COM returns for some reason with an error:  

> System.IO.FileNotFoundException, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e

 Note I have not checked this using his .NET Standard .DLL against regular PS5.1.

This may be something with the task scheduler COM objects, or something with PS/Net Standard, or with the project and how it loads COM, but its beyond my skills to debug.  The code works find using his .NET 4.5.2 library against PS 5.1, works fine from a .NET Core Console project, but also fails when trying to proxy the call through a PS .NET Standard Binary Module.  So, the only real common factors I hit were PowerShell and .NET standard for the difference in behavior.  A quick test script module to highlight what is happening is at the following link:

https://github.com/dahall/TaskScheduler/issues/776

```
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.4
PSEdition                      Core
GitCommitId                    6.1.0-preview.4
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Brief update:  loading the assembly with reflection and performing the calls works, so it's just when loaded from module

**Comment by iSazonov** [comment]
> loading the assembly with reflection 

What assembly you mean?
