### ISSUE TITLE
ConvertTo-Html -As List appends colon to property name

### ISSUE THREAD

**Issue by thezim** [PowerShell/PowerShell#7332]
When using `ConvertTo-Html -As List` colon is appended to the property name. While this inline with `Format-List` there should be some way of either to not append anything or allow a custom string.

My first thought is to add a switch to ignore appending the colon entirely. This keeps it non breaking and pretty simple but seems like a fix for a singular case.

Second idea is to have the delimiter defined as a global for both 'ConvertTo-Html' and 'Format-List' if it does not already exist. Default would be `:` and overridden when needed. This gives flexibility to both cmdlets.

Third option might be letting both the property and value have its own script block expression. This would allow maximum flexibility beyond the colon use. One could wrap their property name or value in a tag, apply a class to it, etc. 

I know tis beyond the current scope but a having this cmdlet accept a Razor (.cshtml) view would be great addition later down the road.

**Comment by SteveL-MSFT** [comment]
It might make sense to introduce a `-HtmlOption` parameter that accepts a `HtmlOption` object where we can add more customization without new parameters (particularly with lesser used customizations) which would still allow for providing custom script blocks.

**Comment by mklement0** [comment]
Good points, @thezim, but can you please correct `semicolon` -> `colon` both in the title and the body in order to make this issue more discoverable?
