### ISSUE TITLE
Automation via .NET Core

### ISSUE THREAD

**Issue by danielman111** [PowerShell/PowerShell#7333]
Hi All. I am using .NET Core to write some automation with powershell,
I installed the following nugets:

```
Microsoft.PowerShell.Commands.Management
Microsoft.PowerShell.SDK
Microsoft.WSMan.Management
System.Management.Automation

```

and is using the following code:

```
Runspace runspace = RunspaceFactory.CreateRunspace();
runspace.Open();

Pipeline pipeline = runspace.CreatePipeline();
pipeline.Commands.AddScript("$service = Get-CimInstance -ClassName Win32_Service -Filter \"name = 'MyNewService\'\"");

pipeline.Commands.AddScript("$service.DisplayName");

```

Getting the following Error 

```
System.Management.Automation.CommandNotFoundException: 'The term 'Get-CimInstance' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.'
```

Any Ideas how to fix the problem, so it will recognize it?

**Comment by mklement0** [comment]
Are you running this on a Unix-like platform? The CIM cmdlets only work on Windows, with [no plans to implement them on other platforms](https://github.com/PowerShell/PowerShell/issues/6248#issuecomment-382679853).

**Comment by danielman111** [comment]
Running on Windows Server

**Comment by mklement0** [comment]
Untested, but I suspect you need this nuget package (namespace `Microsoft.Management.Infrastructure`):

https://www.nuget.org/packages?q=Microsoft.Management.Infrastructure

**Comment by mklement0** [comment]
One last (wild) guess, then I'll leave it to someone more knowledgeable to to help you (I've personally never gone beyond making the [sample application](https://github.com/PowerShell/PowerShell/tree/master/docs/host-powershell/sample-dotnet2.0-powershell-crossplatform) work.)

Perhaps `$env:PSModulePath` is populated in a way that auto-loading of the `CimCmdlets` module doesn't work?

(Downloading `Microsoft.Management.Infrastructure` may not have been necessary at all, given that you're not directly interacting with it from C#, and that the `CimCmdlets` module should be present by default.)

**Comment by xGord** [comment]
Any progress on this?

**Comment by marc-dworkin** [comment]
https://github.com/PowerShell/PowerShell/issues/8119
