### ISSUE TITLE
System.Management.Automation assembly version is not stable but should be

### ISSUE THREAD

**Issue by SteveGilham** [PowerShell/PowerShell#7334]
This assembly provides the primary API for customization via compiled cmdlets; in the original Windows PowerShell, this was acknowledged by keeping the assembly version at 1.0.0.0 through several releases (adhering to the Open/Closed principle), so that cmdlets written to that API could continue to be used without being bound to that version.

I discovered this by having recently upgraded from 6.0.2 to 6.0.3 and attempting to import a module built against 6.0.2, which promptly failed with the assembly version mismatch for this assembly.  Assembly versioning, alas, does not understand the concept of semantic versioning, and considers any change breaking, so should only be stepped at major breaking versions.

With the situation we are in at the moment, having the expected stable 6.0.0.0 version is not possible, but a stable 6.#.#.# version should be chosen and stuck with until it is time to move to 7.0.0.0 instead.

Meanwhile, I'm having to downgrade back to 6.0.2

**Comment by iSazonov** [comment]
@adityapatwardhan @daxian-dbw What is recommended practice? Compile a  custom module against SMA _>=6.0.*_ / `>=6.*`?

**Comment by daxian-dbw** [comment]
@SteveGilham I tried to repro the issue but couldn't. Can you please provide repro steps for the reported issue?

In my attempt, I built a simple assembly targeting the `System.Management.Automation 6.0.2` Nuget package:

#### templib.csproj

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management.Automation" Version="6.0.2" />
  </ItemGroup>

</Project>
```

#### Class1.cs

```c#
using System;
using System.Management.Automation;

namespace templib
{
    [Cmdlet("Test", "MyCommand")]
    public class MyCommand : PSCmdlet
    {
        [Parameter(Mandatory = true)]
        public string Name { get; set; }

        protected override void ProcessRecord()
        {
            WriteObject($"Hello {Name}");
        }
    }
}
```

#### build `templib.dll`
```none
[E:\arena\dotnetApp\test\templib]
PS:119> dotnet build
Microsoft (R) Build Engine version 15.7.177.53362 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 49 ms for E:\arena\dotnetApp\test\templib\templib.csproj.
  templib -> E:\arena\dotnetApp\test\templib\bin\Debug\netcoreapp2.0\templib.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.53
```

As shown in `ILDasm`, the generated `templib.dll` references `System.Management.Automation 6.0.2.0`:
![image](https://user-images.githubusercontent.com/127450/43286137-f5357938-90d5-11e8-8e84-9a76b44d211d.png)

And importing the assembly in PSCore 6.0.3 works fine:

```none
PS:1> $PSVersionTable.PSVersion.ToString()
6.0.3
PS:2> Import-Module E:\arena\dotnetApp\test\templib\bin\Debug\netcoreapp2.0\templib.dll
PS:3> Test-MyCommand -Name Joe
Hello Joe
```

**Comment by SteveGilham** [comment]
Sorry for the delay.  I have some good news and some not so good news from this particular corner of DLL Hell --

First, the good news : I've not been able to repro the original issue after a number of upgrade/reinstall cycles and a few reboots for other reasons -- it may have been something banal like needing a reboot at the time because of other changes built up on the machine (physical, rather than a VM I could have rewound), or a stale environment in the pwsh launch from the installer, or some other, separate and harmless seeming, change, now discarded.

However, having gone round the loop of various version upgrades a number of times, I do have a robust result that goes against the spirit of semantic versioning for patch releases, and it's the complete opposite one.  Linking a compiled module against 6.0.3 for the definition of `PSCmdlet` and running against 6.0.2 fails with
```
ERR : Import-Module : Could not load file or assembly 'System.Management.Automation, Version=6.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
```
This has the unpleasant effect that if the developer is keeping project dependencies updated, especially with some of the automation from things like dotnet-outdated or NuKeeper, that will also drag the minimum supported user version forwards, unless explicitly reverted for this one case.
