### ISSUE TITLE
Add Virtualenv support

### ISSUE THREAD

**Issue by thomas-illiet** [PowerShell/PowerShell#7335]
Hi All.

I use Jenkins to build / test my Powershell modules, I would like to create virtual environments to separate dependencies from my projects ( Like Python Virtualenv )

Actualy i create a litle module for this : https://www.powershellgallery.com/packages/Virtualenv/

could we have an integration of this feature in powershell ?

**Comment by iSazonov** [comment]
@thomas-illiet Could you please add more information/scenarios? Can this help to isolate different version dll-s like Newton.Json used in PowerShell engine and in custom modules?

/cc @SteveL-MSFT @daxian-dbw

**Comment by thomas-illiet** [comment]
Hello @iSazonov :)

## Scenarios

For example I have a lot of scripts with the same module with breaking changes. I do not want to specify the version of the module in the script.

Another example, in Visual Studio the libraries are not installed in the system because it is in the project ( 
 it seems to me )

## Folder structure diagram
 - Project01
    |  - Venv
    |     - Pester
    |         - V1.0 
    |  -  toto.ps1
    |  -  requirements.txt


## Source
- https://virtualenv.pypa.io/en/stable/
-
