### ISSUE TITLE
Invoking an executable plain-text file that lacks a shebang line fails quietly on macOS

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#7336]
On Unix-like platforms, plain-text files that are marked as executable require a shebang line (`#!...`) for meaningful interpretation; in the absence of a (valid) shebang line, it is unclear what interpreter to pass the file to.

On _macOS_ (but not on Linux) PowerShell currently _fails quietly_ when attempting to invoke an executable plain-text without (valid) shebang line, _presumably_ because the invocation is delegated to a system call that fails.

Note that while POSIX-like shells such as `bash` have a _fallback mechanism_ that makes them execute such files either themselves or by passing it to `/bin/sh`, I think the more sensible behavior is to _fail_.

Either way, the current quiet failure is problematic (though `$?` and `$LASTEXITCODE` do indicate failure).

Also, I suspect that the quiet failure is not limited to shebang-lacking plain-text executable files and may surface for any invalid executable (such as a corrupted binary or one for a different architecture), regardless of the cause.

_Update_: In fact, a likelier scenario that also surfaces the problem is if a shebang line _is_ present, but happens to reference a _non-existent interpreter_.

Steps to reproduce (macOS only)
------------------

```powershell
# Create a plain text file without a shebang line (content is otherwise irrelevant),
# make it executable, and try to execute it.
'ls' > t  
chmod a+x t
./t
```

Note: The same behavior applies to invocation with `&` (unsurprisingly), and also `.`

Expected behavior
-----------------

A _statement-terminating error_ should be reported, detailing the inability to execute the file (with the message possibly coming from a platform-native system call).

Actual behavior
---------------

No error _message_ is output.

However, `$?` _is_ set to `$FALSE` and `$LASTEXITCODE` is `8`, so it is at least possible to detect the failure programmatically.

`8` is `ENOEXEC`, which is a standard error code defined as follows (from `man 2 intro` on macOS):

>    8 ENOEXEC Exec format error.  A request was made to execute a file that,
>         although it has the appropriate permissions, was not in the for-
>         mat required for an executable file.

It makes more sense to treat this as a statement-terminating error, just as trying to invoke a _non-existent_ executable is (while still setting `$LASTEXITCODE`).

Environment data
----------------

```powershell
PowerShell Core 6.1.0
```

**Comment by iSazonov** [comment]
@PaulHigin Maybe it will be interesting to you.

**Comment by iSazonov** [comment]
Seems it will be a breaking change if we add a terminating error.

**Comment by SteveL-MSFT** [comment]
In the case of PowerShell, if the command is not a script nor a cmdlet, it runs it as a `NativeCommand`.  This means it attempts to start a new process with that name ( 't' in the local directory in the sample above ).  Create process on "./t" fails since it's not a binary executable.

Looking at the bash source, they have a helper to look into executables to determine if it's likely a script or a binary and if a script (meaning all printable characters up to the newline) it processes it as a script.  PowerShell, of course, only processes the file if it ends in .ps1.

I don't think we want to special case this and check for an exit code of 8.  This seems to be an edge case that would be handled by https://github.com/PowerShell/PowerShell/issues/3415

**Comment by mklement0** [comment]
> they have a helper to look into executables to determine if it's likely a script or a binary and if a script (meaning all printable characters up to the newline) it processes it as a script. 

Yes, that's the behavior I suggest we _avoid_, because in the absence of a shebang line it is a tenuous assumption for a shell to make that it must be written in its _own_ language - to me, it's not a reasonable default behavior (and it sounds like we agree on that).

However, what _is_  shell's job - any shell's - is to report an error in the event of _fundamental inability to invoke an external executable_.

This is different from fundamentally successful invocation (in that the process could be _created_), which may then be followed by the successfully launched external executable _itself_ indicating failure (via its _exit code_ and typically also stderr output).

Here we're talking about the _system call_ that attempts to _create the new process_ indicating failure _to the shell_, which it should surface.

So, thinking about this some more, **I'm not asking to special-case error code `8`, I'm asking PowerShell to surface _any_ error condition indicated by the underlying system call when trying to launch an external executable** (which presumably is ultimately from the `exec` family of functions, whose errno values are defined by POSIX [here](http://pubs.opengroup.org/onlinepubs/9699919799/functions/exec.html#tag_16_111_05)).

It's important for the inability to even launch an external program to fail conspicuously:

* PowerShell already reports a statement-terminating error for a _non-existent_ command (executable); e.g., `PS> nosuchexe -h`

  * It just so happens that PowerShell _itself_ makes the determination whether a command exists rather than relying on a system call (right?).

* A non-existent command is just _one_ reason for the invocation to fail fundamentally, and I don't see a reason to treat others - such as an invalid executable file - differently.

Once we have a shared understanding, I'm happy to amend the title and OP to reflect the broader scope.

**Comment by mklement0** [comment]
@SteveL-MSFT:

Thanks for digging deeper - I've created https://github.com/dotnet/corefx/issues/31519 in the CoreFX repo.

I guess we can label this issue `Resolution-External`.

**Comment by mklement0** [comment]
Thanks for adding the label, @SteveL-MSFT, but shouldn't the issue then remain _open_ until the external resolution comes?

**Comment by SteveL-MSFT** [comment]
Changed the labels, we can leave this open for now.

**Comment by mklement0** [comment]
@SteveL-MSFT: 

On the plus side: It turns out that the problem exists on macOS only - my bad for not checking initially (I've updated the title and original post)

The less good news that a far less exotic scenario than the one initially described (missing shebang line) also surfaces the problem: if a shebang line _is_ present, but happens to reference a _non-existent interpreter_.

The discussion at https://github.com/dotnet/corefx/issues/31519 is ongoing, but what it comes down to that we currently don't know how to fix the problem _technically_ - macOS lacks a system call that is used on Linux, where the problem doesn't occur.

If you happen to know macOS / BSD system-programming experts, could you point them to the issue? Thanks.

**Comment by mklement0** [comment]
As of at least v7.1 the problem no longer occurs, and you now get a meaningful `` error message:

```
ResourceUnavailable: Program 't' failed to run: Exec format errorAt line:1 char:1
```
