### ISSUE TITLE
Microsoft.PowerShell.SDK version 6.1.0-preview.4 fails at InitialSessionState.CreateDefault()

### ISSUE THREAD

**Issue by jherby2k** [PowerShell/PowerShell#7339]
I'm unable to use preview.4 of the SDK with my test project. preview.3 worked fine. The test project targets .net core 2.1.

Steps to reproduce
------------------

1.  Clone https://github.com/jherby2k/AudioWorks.git.
1. Run the tests in the AudioWorks.Commands.Tests project. All should pass.
1. Change the project to reference Microsoft.PowerShell.SDK version 6.1.0-preview.4 (from preview.3)
1. Run the tests again. Most will fail.

Expected behavior
-----------------

all tests pass

Actual behavior
---------------

> One or more errors occurred. (Cannot load PowerShell snap-in Microsoft.PowerShell.Diagnostics because of the following error: Could not load file or assembly '..\Source\Repos\AudioWorks\AudioWorks\tests\AudioWorks.Commands.Tests\bin\Release-Windows\netcoreapp2.1\Microsoft.PowerShell.Commands'. The system cannot find the file specified.

**Comment by SteveL-MSFT** [comment]
cc @adityapatwardhan

**Comment by adityapatwardhan** [comment]
@jherby2k I believe this is on Windows? Which Windows version is it?

**Comment by jherby2k** [comment]
Probably best to unpublish it until at least MarkdownRender is available, no?

**Comment by adityapatwardhan** [comment]
@jherby2k Thank you for reporting this issue. We will be fixing and re-publishing the SDK soon.

**Comment by adityapatwardhan** [comment]
@jherby2k new packages published. Can you give them a try?

**Comment by jherby2k** [comment]
Thanks. Working for me!
