### ISSUE TITLE
Improve error message when autoloaded module fails the PSCompatibleEditions check

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell#7352]
Module auto-loading knows about the existence of incompatible commands, even when `Get-Command` does not, so when you try to execute a command in an Edition-incompatible module (without loading it first), it will complain about being unable to load the module. 

Also note that `Get-Command Add-WindowsCapability` returns nothing here.

We may also want to extend `Get-Command` to support `-SkipEditionCheck`, but I'll file that issue as this one plays out.

Steps to reproduce
------------------

```powershell
C:\WINDOWS\system32> Add-WindowsCapability
```

Expected behavior
-----------------

One of these two:

```none
Add-WindowsCapability : The 'Add-WindowsCapability' command was found in the module 'Dism', but 'Dism' does not support current PowerShell edition 'Core'. Its supported editions are 'Desktop'. Use 'Import-Module -SkipEditionCheck 'Dism'' to ignore the compatibility of this module.
At line:1 char:1
+ Add-WindowsCapability
+ ~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Add-WindowsCapability:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
```

less desirable, but still acceptable:

```none
Add-WindowsCapability : The term 'Add-WindowsCapability' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Add-WindowsCapability
+ ~~~~~
+ CategoryInfo          : ObjectNotFound: (Add-WindowsCapability:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```

Actual behavior
---------------

```none
Add-WindowsCapability : The 'Add-WindowsCapability' command was found in the module 'Dism', but the module could not be loaded. For more information, run 'Import-Module Dism'.
At line:1 char:1
+ Add-WindowsCapability
+ ~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Add-WindowsCapability:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.4
PSEdition                      Core
GitCommitId                    6.1.0-preview.4
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
So this is just an error message change, right?  Is this part really necessary?

> Its supported editions are 'Desktop'

**Comment by joeyaiello** [comment]
I just copied the error message from `Import-Module`. 

Seems like it makes sense to have consistency between `Get-Command` and `Get-Module`, though, and autoloading seems like it should dovetail with `Get-Command`.

**Comment by rjmholt** [comment]
I'm trying to reproduce this, but haven't been able to yet. @joeyaiello, try nuking the module analysis cache (`rm $env:AppData\..\Local\Microsoft\PowerShell\ModuleAnalysisCache` should do it) and see if this happens again.

**Comment by joeyaiello** [comment]
I get the second of my two "Expected Behavior" now, likely had to do with the command cache and my prior usage of `Add-WindowsPSModulePath`.

That being said, error message 1 under my Expected Behavior is still a way better error. We talked about this offline, I understand why #7366 wasn't the right fix (changed an error in more cases), but ultimately there may be a good reason to keep cache of incompatible modules as well as compatible.

**Comment by rjmholt** [comment]
Yeah I agree that we should use a more specific error message for diagnosability -- all abstractions are leaky, so we should be ready to expose some internals when something goes wrong
