### ISSUE TITLE
Powershell installation via package manager method results in 'preview' version regardless of option chosen.

### ISSUE THREAD

**Issue by Zsoldier** [PowerShell/PowerShell#7359]
Tested on both CENTOS 7 and Ubuntu 16.04
Adding repo as instructed in both systems.
Running install w/ option of "powershell" or "powershell-preview" results in an installation of the current powershell "preview" version.  

"Powershell" option never targets current stable release version.

Workaround is to simply download pkg or directly reference git uri to appropriate pkg.

**Comment by iSazonov** [comment]
Seems this will not work until 6.1 release.
/cc @TravisEz13

**Comment by Zsoldier** [comment]
Good to know.  Thanks.

**Comment by TravisEz13** [comment]
@Zsoldier we could delete the preview packages that were published as `powershell` but at this point, I think it is better for us to just wait until 6.1 is released and that will fix it.  cc/ @SteveL-MSFT  @daxian-dbw

**Comment by SteveL-MSFT** [comment]
Yes, we are in a transition state unfortunately.  With 6.1 release next month, I think this will be cleaned up.

**Comment by TravisEz13** [comment]
Closing this issue as I think this has been answered and the fix has already been made.  We are just waiting for the 6.1 release to happen.
