### ISSUE TITLE
'ConvertFrom-Markdown' should take positional argument and 'Show-Markdown' should have consistent default as 'ConvertFrom-Markdown'

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#7363]
1. `ConvertFrom-Markdown e:\powershell\readme.md` throws error: `A positional parameter cannot be found that accepts argument 'E:\PowerShell\README.md'`. I think it should work.

2. `ConvertFrom-Markdown -Path E:\PowerShell\README.md | Show-Markdown` fails with this error: `Show-Markdown : The property VT100EncodedString of the given object is null or empty.` So, `ConvertFrom-Markdown` by default only populates HTML, while `Show-Markdown` by default show VT100. That feels very inconsistent to me.

**Comment by Jaykul** [comment]
yeah, the architecture of these commands is wrong.

I would expect that if I say to convert markdown `-AsVT100EncodedString` that I should get *just* the vt encoded string out. I should not need Show-Markdown at that point.  Alternatively, Show-Markdown shouldn't need ConvertFrom-Markdown, and ConvertFrom-Markdown doesn't need that other output.

I still want the HTML option for ConvertFrom-Markdown -- but this is just confusing.

**Comment by adityapatwardhan** [comment]
Issues mentioned here were fixed by PRs #7329 and #7354
