### ISSUE TITLE
HELP! help docker module

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#7368]
https://github.com/Microsoft/Docker-PowerShell/

Docker module is very good module for management container and image.

now project is readonly,we can not download & installed  from https://ci.appveyor.com/nuget/docker-powershell-dev

I expect PowerShell Gallery to include this module.

Request powershell-team rescue docker module

===================================
0.1.0.111 is latest version.
this version work normal in ps core 6.1 preview2,
but report error for any module-command in ps core 6.1 preview3,preview4
eg: "Get-Container : Docker API responded with status code=BadRequest, response=400 Bad Request: unsupported protocol version"

@joeyaiello    @SteveL-MSFT

**Comment by SteveL-MSFT** [comment]
@chuanjiao10 per that repo, the module is deprecated.  PowerShell Team is already involved in too many projects so I don't think we can pick up another one.  It would be great if the community can take ownership of that module.

**Comment by chuanjiao10** [comment]
Why is it abandoned?
Is there a similar module replacement in the powershell gallery?
The module is deprecated. It’s sad ...  ...

**Comment by SteveL-MSFT** [comment]
@chuanjiao10 according to the README.md it seems that at the time it was not used enough to justify the engineering cost.  Perhaps as we continue to grow PSCore6 usage that project can be picked up again.

**Comment by chuanjiao10** [comment]
Well, the problem with chicken and eggs. There are fewer users, so close. Closed, so there are fewer users.

There is no choice to enter the powershell gallery, the first step of this project is wrong.

Continue to fix the bug and introduce the usage of this module on the "Script Guy" blog. Maybe we can open the situation.

Have a look, anyone. The project needs to be rescued!

**Comment by TravisEz13** [comment]
Question about an external module was answered.
