### ISSUE TITLE
PackageProvider system not in sync between Windows PS and PS Core

### ISSUE THREAD

**Issue by codeHorse87** [PowerShell/PowerShell#7369]
Steps to reproduce
------------------

```powershell
1. perform (Package Management) commands Get-PackageSource or Get-PackageProvider on PS Core 
2. perform the same commands on Windows PS v5.1


Expected behavior
-----------------

```
I'd expect both PS implementations using the same Package Management as being implemented in .NET, including access to the same PackageSource's or PackageProvider's. Which means in a powershell script I have to determine in the script of it's going to be executed in PS Core or the Windows PS. 
Having the OS abstraction with PS Core having the abstraction of the execution environment to use the package management would make software management by PS much more effective.
```

Actual behavior
---------------

```
PS Core only provides access to the Package Provider PowerShellGet but provides not access to the msi, msu, or Programs package providers. As well extension on PackageProviders, or Sources are not taken into account in one or the other environment.
```

Environment data
----------------

<!-- provide the output of $PSVersionTable -->

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by iSazonov** [comment]
PowerShell Core seems to be at the beginning of the road.

**Comment by ThomasNieto** [comment]
@SydneyhSmith can this issue be closed or moved to the OneGet repo?
