### ISSUE TITLE
Keyboard interface of some external terminal-based programs is broken on Unix-like platforms

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#7375]
Note: At this point I know of only one utility, `n`, the Node.js version manager, but I suspect other utilities are affected too.

Presumably, the issue is related to programs using the "alternate screen" technique (as used by the `screen` utility and the `tput smcup` and `tput rmcup` commands)  described in [this SO post](https://stackoverflow.com/q/11023929/45375).

Steps to reproduce (macOS or Linux)
------------------

```powershell
# Install `n`, the Node.js version manager with 2 Node.js versions:
curl -L https://git.io/n-install | bash -s -- -q -n lts latest
$env:N_PREFIX="$HOME/n"; $env:PATH += ":$HOME/n/bin"
n  # Invoke n for interactive selection of the active Node.js version.
```

Note: Run `n-uninstall` afterward to remove both `n` and the installed Node.js versions.

Expected behavior
-----------------

A menu with the two installed Node.js versions should be presented, and _the up/down arrow keys should allow navigating between the two._

![image](https://user-images.githubusercontent.com/588825/43344460-d1b3282e-91b7-11e8-8f7b-3347c5abb15d.png)

Actual behavior
---------------

The up/down arrow keys do not work (though Enter does).

Invocation from `bash` does not exhibit the problem.

The problem is not PSReadLine-related, as even unloading it first makes no difference.

Environment data
----------------

```powershell
PowerShell Core v6.1.0-preview.4 on macOS 10.13.6
PowerShell Core v6.1.0-preview.4 on Ubuntu 16.04.4 LTS
```

**Comment by chuanjiao10** [comment]
Someone taught me a trick, do you see it useful?

```powershell
@'
echo "any bash command run in pwsh"
curl -L https://git.io/n-install | bash -s -- -q -n lts latest
'@ | /usr/bin/bash

```

**Comment by mklement0** [comment]
@chuanjiao10: It's a useful technique in general, but how does it help here?

**Comment by mklement0** [comment]
Ultimately a duplicate of #12268
