### ISSUE TITLE
Get-Help -Full / -Parameter does not display parameter aliases

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#7381]
<sup>[Originally reported in the docs repo](https://github.com/PowerShell/PowerShell-Docs/issues/1638), but since it affects the `Get-Help` cmdlet, I'm reposting it here.  It seemed that the problem was fixed at some point, but it is back as of PowerShell Core 6.1.0-preview.4</sup>

Currently, the only way to discover parameter aliases is via the _online_ help topics; e.g., the [`Get-ChildItem`'s `-Directory` switch parameter](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Get-ChildItem.md#-directory) stated that the `-Directory` parameter has two aliases, `-ad` and `-d`:

![image](https://user-images.githubusercontent.com/588825/43324157-63e45416-9181-11e8-8a24-071da12988e4.png)

(While the description _may_ mention aliases too, it doesn't do so consistently, and showing the aliases in the structured way highlighted above is more important.)

The omission of this information from `Get-Help -Full` and `Get-Help -Parameter` makes it difficult to discover parameter aliases offline.

Additionally or alternatively, consider including the alias names (more formally and consistently) also in the `-Detailed` view, in the header line for each parameter-description block:

Instead of:

```none
 -Directory [<SwitchParameter>]
```

consider:

```none
-Directory [<SwitchParameter>]    or  -ad [<SwitchParameter>]   or  -d [<SwitchParameter>] 
```

or something similar.

Steps to reproduce
------------------

```powershell
Get-Help Get-ChildItem -Parameter Directory
```

Expected behavior
-----------------

```none
    -Directory [<SwitchParameter>]   or  -ad [<SwitchParameter>]   or  -d [<SwitchParameter>]
        Gets directories (folders).
        
        To get only directories, use the `-Directory` parameter and omit the `-File` parameter. To exclude directories, use the `-File` parameter and omit the 
        `-Directory` parameter, or use the `-Attributes` parameter.
        
        To get directories, use the Directory parameter, its "`ad`" alias, or the Directory attribute of the `-Attributes` parameter.
        
        Aliases                      d, ad             
        Required?                    false
        Position?                    named
        Default value                False
        Accept pipeline input?       False
        Accept wildcard characters?  false

```

Note the `Aliases` line in the table of properties at the bottom,
and the enumeration of aliases in the header line.

Arguably, we don't need _both_, however.

Actual behavior
---------------

```none
    -Directory [<SwitchParameter>]
        Gets directories (folders).
        
        To get only directories, use the `-Directory` parameter and omit the `-File` parameter. To exclude directories, use the `-File` parameter and omit the 
        `-Directory` parameter, or use the `-Attributes` parameter.
        
        To get directories, use the Directory parameter, its "`ad`" alias, or the Directory attribute of the `-Attributes` parameter.
        
        Required?                    false
        Position?                    named
        Default value                False
        Accept pipeline input?       False
        Accept wildcard characters?  false
```

Note the absence of alias information in the table of properties at the bottom.

Environment data
----------------

```powershell
PowerShell Core v6.1.0-preview.4
```

**Comment by marcinsmialek** [comment]
The problem is still present in PowerShell Core 7.2.2 and 7.3.0-preview.3

It adds friction, which is even worse with modules which aren't present on https://docs.microsoft.com/en-us/powershell/scripting especially in dll flavor.
