### ISSUE TITLE
Cannot paste complete password when creating a new credential

### ISSUE THREAD

**Issue by mmcelreath** [PowerShell/PowerShell#7382]
When running Get-Credential, if I try to paste my password when prompted for a password, it only takes the first character or so then exits the command. The rest of the password is then pasted to the console.

Steps to reproduce
------------------

PS C:\> "TestPassword123" | clip.exe
PS C:\> $cred = Get-Credential

PowerShell credential request
Enter your credentials.
User: Test
Password for user Test: *
PS C:\> stPassword123

Expected behavior
-----------------

When pasting the password into the password prompt, the entire password should be accepted to properly create the credential object

Actual behavior
---------------

As single character is pasted to the password field then the command closes and the remainder of the password gets pasted to the console.

Environment data
----------------

PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.4
PSEdition                      Core
GitCommitId                    6.1.0-preview.4
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by mmcelreath** [comment]
I'm also seeing this in the stable version as well.

**Comment by mmcelreath** [comment]
I tried searching for it but wasn't able to find one. Do you have the issue #?

**Comment by iSazonov** [comment]
I can not find too.

**Comment by ephos** [comment]
Came to see if someone opened an issue for this, saw that @mmcelreath already did!  I am seeing this as well.  Environment information below!

```powershell
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by ThomasNieto** [comment]
@iSazonov / @vexx32 I don't think this is any issue anymore since I'm not able reproduce this on 7.1 rc1. Can this issue be closed?

```powershell
C:\> "TestPassword123" | clip.exe
C:\> $cred = Get-Credential

PowerShell credential request
Enter your credentials.
User: test
Password for user test: ***************

C:\> $cred.GetNetworkCredential().Password
TestPassword123
```

**Comment by vexx32** [comment]
Tested and confirmed this works as expected for me as well.

**Comment by iSazonov** [comment]
I set "Resolution-Answered" because we have no link to PR.
