### ISSUE TITLE
wrong：The latest stable version of powershell is 6.1.preview.2, not 6.03

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#7385]
For historical reasons, the package name wrong in ms repo.
This is still the case until now.

#7359 can not Clearly explain the reason, It is recommended to keep this issue , close #7359.

ubuntu has same problem.

Steps to reproduce
------------------
```bash
yum clean all
yum list |grep powershell
===return===
powershell.x86_64                         6.1.0~preview.2-1.rhel.7     packages-microsoft-com-prod
powershell-preview.x86_64                 6.1.0~preview.4-1.rhel.7     packages-microsoft-com-prod

yum install powershell
===return===
==================================================================================================================================================
 Package                     架构                    版本                                      源                                            大小
==================================================================================================================================================
正在更新:
 powershell                  x86_64                  6.1.0~preview.2-1.rhel.7                  packages-microsoft-com-prod                   50 M

事务概要
==================================================================================================================================================
升级  1 软件包

总下载量：50 M
Is this ok [y/d/N]: 


```

Expected behavior
-----------------
How to fix:

in
https://packages.microsoft.com/rhel/7/prod/

A person with permission changes the package file name.

from
https://packages.microsoft.com/rhel/7/prod/powershell-6.1.0~preview.1-1.rhel.7.x86_64.rpm
to
https://packages.microsoft.com/rhel/7/prod/powershell-preview-6.1.0~preview.1-1.rhel.7.x86_64.rpm

from
https://packages.microsoft.com/rhel/7/prod/powershell-6.1.0~preview.2-1.rhel.7.x86_64.rpm
to
https://packages.microsoft.com/rhel/7/prod/powershell-preview-6.1.0~preview.2-1.rhel.7.x86_64.rpm

Environment data
----------------

centos 7.5

**Comment by SteveL-MSFT** [comment]
We introduced the `stable` and `preview` channels in the middle of 6.1.  I don't think we'll go back and fix the existing releases particularly since we expect to have our next stable release (6.1 GA) by end of August.

**Comment by chuanjiao10** [comment]
I understand. 
So, in powershell powerbi borard, 6.03 will be a rarely used version.
