### ISSUE TITLE
Extend Get-Command to support a -Resolve switch for resolving to an alias' underlying command or an executable symlink's true filesystem location

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#7387]
<sup>Updated to extend the resolution functionality to executable symlinks.</sup>

It would be convenient  to allow passing `-Resolve`  to `Get-Command` so as to immediately display information about the command underlying an alias, if applicable.

In other words: given an alias name, `-Resolve` would act like `(Get-Command someAlias).ResolvedCommand`.

This is more useful than the default behavior, where the output for an alias name only indicates the _name_ of the underlying command.

Similarly, if a command refers to an executable that is a _symlink_ (common on Unix-like platforms, `-Resolve` could resolve that symlink to its (ultimate) target path and emit information about that, as it sometimes of interest where an executable truly resides.

For all other command forms the switch should have no effect.

Desired behavior
------------------

For an **alias**:

```powershell
PS> Get-Command gci -Resolve  # wishful thinking; equivalent of (Get-Command gci).ResolvedCommand

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Get-ChildItem                                      6.1.0.0    Microsoft.PowerShell.Management


```

For an executable that is a **symlink**:

```powershell
# Wishful thinking: pwsh is symlink /usr/local/bin/pwsh on macOS for instance,
# whose target is something like  /usr/local/microsoft/PowerShell/6.1.0/pwsh.
PS> Get-Command pwsh -Resolve 

CommandType     Name       Version    Source
-----------     ----       -------    ------
Application     pwsh       0.0.0.0    /usr/local/microsoft/PowerShell/6.1.0/pwsh
```

Additionally, it may be of interest to see the _chain_ of resolutions, perhaps via  a separate `-Follow` or `-ResolveChain` switch, which could emit both the immediate target and the (chain of) ultimate target(s), as a sequence of objects.

For instance, with `gci` you'd get both the alias info and the underlying cmdlet info, and with `pwsh` you'd get the original symlink info as well as info for their target(s).

Environment data
----------------

Written as of:

```powershell
PowerShell Core 6.1.0-preview.4
```

**Comment by kvprasoon** [comment]
Great idea !!!

**Comment by iSazonov** [comment]
I think it could be `-ResolveAlias`.

**Comment by mklement0** [comment]
@iSazonov: 

I was thinking `-Resolve` for consistency with other cmdlets (currently only `Join-Path` and `Split-Path`), but I guess we can do both - make one an alias of the other.

(Even though dynamic syntax would allow using `-Resolve` in lieu of `-ResolveAlias` anyway, it's better to "make it official".)

**Comment by iSazonov** [comment]
I suggest `-ResovleAlias` because it is self-documented and it is not clear that `-Resolve` should resolve - full module name, full source path and so on.

**Comment by mklement0** [comment]
@iSazonov:

Maybe we can turn that into a virtue, given that there's at least one other way to resolve a command name:

For external programs that happen to be _symlinks_, make `-Resolve` show the _ultimate target file path_ (at least currently, such a feature is of much more interest on Unix-like platforms); e.g.:

```powershell
# Currently, you get just the symlink's path
PS> Get-Command pwsh

CommandType     Name       Version    Source
-----------     ----       -------    ------
Application     pwsh       0.0.0.0    /usr/local/bin/pwsh


# Wishful thinking: -Resolve shows the symlink's (ultimate) *target* path
PS> Get-Command pwsh -Resolve

CommandType     Name       Version    Source
-----------     ----       -------    ------
Application     pwsh       0.0.0.0    /usr/local/microsoft/PowerShell/6.1.0/pwsh

```

On a side note, complementing `-Resolve` with something like `-Follow` or `-ResolveChain`  may make sense, which could emit both the immediate target and the (chain of) ultimate target(s), as a _sequence_ of objects.

For instance, with `gci` you'd get both the alias info and the underlying cmdlet info, and with `pwsh` you'd get the original symlink info as well as info for their target(s).

**Comment by mklement0** [comment]
@iSazonov : Too late - I've fallen in love with the idea 😜. 

I can tell you that inspecting the true filesystem locations of symlinked executables is something I deal with frequently (on Unix-like platforms).

`Format-List` would only help if you crammed more information into the one and only output object currently emitted, which strikes me as a bad idea.
This issue is about resolving to the command that is effectively used / to see the chain of commands (symlinks) that lead to it.

I've updated the original post with my suggestions; let's see what others think.
