### ISSUE TITLE
PowerShell working on libcurl4?

### ISSUE THREAD

**Issue by thewinner666** [PowerShell/PowerShell#7389]
Ok, I am just going to ask this question. Are you going to make Powershell to work on libcurl4 because most programs that I have rely on this library and if I try to install libcurl3 it will not just remove libcurl4, but all programs that need it to run properly.

**Comment by thezim** [comment]
PowerShell Core no longer has a dependency on libcurl #6964

**Comment by iSazonov** [comment]
I confirm - no dependency on libcurl.
