### ISSUE TITLE
Inspecting parameters via a CmdletInfo instance obtained via an AliasInfo's ResolvedCommand property is missing dynamic parameters

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#7391]
Steps to reproduce
------------------

Run from a filesystem location.

```powershell
# Inspect Get-ChildItem directly and look for the 
# dynamic, filesystem-provider-specific -Directory parameter.
((Get-Command Get-ChildItem).ParameterSets.Parameters.Name | Select-String Directory)[0]
'---'
# Inspect Get-ChildItem indirectly via its gci alias and .ResolvedCommand
((Get-Command gci).ResolvedCommand.ParameterSets.Parameters.Name | Select-String Directory)[0]
```

Expected behavior
-----------------

```none
Directory
---
Directory
```

Actual behavior
---------------

```none
Directory
---
Cannot index into a null array.
...
```

That is, no `Directory` parameter was present in the output from `(Get-Command gci).ResolvedCommand`, even though by itself it appears to produce the same output as `Get-Command Get-ChildItem`

Environment data
----------------

```powershell
PowerShell Core v6.1.0-preview.4 on macOS 10.13.6
PowerShell Core v6.1.0-preview.4 on Ubuntu 16.04.4 LTS
PowerShell Core v6.1.0-preview.4 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.165)
\Windows PowerShell v5.1.17134.165 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.165)
```

**Comment by BrucePay** [comment]
Dynamic parameters are dynamic i.e. based on some condition. This condition typically takes the form of an argument to the cmdlet which is why `Get-Command` has a `-ArgumentList` parameter. In the case of `Get-ChildItem` that argument is a path. So if you do
```powershell
((get-command get-childitem -ArgumentList c:\).ParameterSets.Parameters.Name  | Select-String Directory)[0]
```
you will get the expected output.

**Comment by mklement0** [comment]
@BrucePay: 

Yes, but it's my understanding that in the _absence_ of `-ArgumentList` it is the _provider underlying what happens to the be the current location_ whose dynamic parameters are returned.

That is the reason the steps to reproduce state, "Run from a filesystem location."

Thus, when invoked from a_filesystem location_ (a current location that is provided by the `FileSystem` provider), the following commands should be - and are - equivalent:

```powershell
# *Implicit* use of the FileSystem provider, based on the current location.
((Get-Command Get-ChildItem).ParameterSets.Parameters.Name | Select-String Directory)[0]

# *Explicit* use of the FileSystem provider, via -ArgumentLIst / (Unix; on Windows, use C:\).
((Get-Command Get-ChildItem -ArgumentList /).ParameterSets.Parameters.Name | Select-String Directory)[0]
```

So, to return to the original question:

Why shouldn't 

```powershell
((Get-Command gci).ResolvedCommand.ParameterSets.Parameters.Name | Select-String Directory)[0]
```

be equivalent? 

* Is the implicit provider context lost due to the level of indirection (resolving `gci` to `Get-ChildItem`)?

* If so, does this behavior make sense to you?
