### ISSUE TITLE
Zoom In and Out not possible

### ISSUE THREAD

**Issue by liszca** [PowerShell/PowerShell#7395]
Hi,
working on Hi resolution displays can be quiet painful without being able to zoom in.

Doing so with CTRL + Mousewheel and CTRL + "+"/ "-" should be possible.

Greetings
filip

**Comment by rkeithhill** [comment]
PowerShell is not responsible for console functionality.  You need to submit that issue to the console repo - https://github.com/microsoft/console

**Comment by git4ranjan** [comment]
was there any solution provided to zooming ?

**Comment by SteveL-MSFT** [comment]
@git4ranjan the solution depends on your operating system
