### ISSUE TITLE
Missing members on XML elements

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#7415]
Given XML, such as:

```posh
$xml = [xml]"<person><name type='first'>John</name><name type='last'>Doe</name></person>" 
```
If we use Get-Member on an XML Element:

```posh
$xml.person | Get-member
```

We are missing _all_ of the basic XML properties such as `InnerText` and even when using `Get-Member -Force` they are only shown as hidden `get_*` and `set_*` _methods_ rather than as properties!

These properties are crucial to doing serious Xml work, and only the properties are being hidden. That is, `ChildNodes` and `FirstChild` and `LastChild`  are missing, but `AppendChild(...)` and `PrependChild(...)` and `RemoveChild(...)` and `ReplaceChild(...)` are all still there.

I understand the need to hide these in formatted output objects to prevent complicated unrolling and preserve the impression of XML nodes as custom objects -- but they really should show up in the output of `Get-Member` (or at least, be displayed properly in `Get-Member -Force`).

This is a long-standing discoverability problem, but it's high time it was fixed.

We need our `Attributes` or `BaseURI` or `ChildNodes` or `FirstChild` or `HasAttributes` or `HasChildNodes` or `InnerText` or `InnerXml` or `IsEmpty` or `IsReadOnly` or `Item` or `LastChild` or `LocalName` or `Name` or `NamespaceURI` or `NextSibling` or `NodeType` or `OuterXml` or `OwnerDocument` or `ParentNode` or `Prefix` or `PreviousSibling` or `PreviousText` or `SchemaInfo` or `Value` ...

**Comment by robderickson** [comment]
I was personally struggling with getting text within an XML element node, and did not realize the `InnerText` property was available to me until Joel pointed it out.

**Comment by robderickson** [comment]
Should the properties also be available if you go one node deeper?

```PowerShell
$xml.person.name.psbase | Get-Member
```
I don't see them there, but I can get values with `$xml.person.name.InnerText`
