### ISSUE TITLE
Clixml Serialization Inconsistencies

### ISSUE THREAD

**Issue by FriedrichWeinmann** [PowerShell/PowerShell#7417]
Hi guys, got something weird going on here ...
I'm currently playing with serialization of objects and there's something ... odd happening here with noteproperties on collections and wondered whether somebody knew what hit me and how to work around it.

Setting up the collection:

```powershell
$list = 'a', 'b', 'c'
Add-Member -InputObject $list -MemberType NoteProperty -Name Foo -Value Bar
```

A simple array of three characters, then add some arbitrary property _to the collection_ .
Now, if I export it using `Export-Clixml`, the added noteproperty will be correctly serialized as intended:

```powershell
Export-Clixml -InputObject $list -Path .\test.xml
```

If however I serialize the list using the PSSerializer, it will _not_ be part of the xml:

```powershell
[System.Management.Automation.PSSerializer]::Serialize($list)
```

What makes this so bloody confusing is that beneath the hood, both lead to the exact same serializer as far as I can see, called with the same constructor parameters.

Anybody understand where the difference is coming from?

> Note: I am aware that adding noteproperties to collection objects themselves is generally ... not an awesome idea. My current quest is knowledge on why it happens, because some of my users already use this and it works just fine on Export-Clixml, but not my custom tools

> Note2: This behavior exists from the oldest PowerShell console I could scrap up into the latest PS6 build I have installed somewhere ...

**Comment by 0xfeeddeadbeef** [comment]
One important difference between the two: when invoking `Export-Clixml` cmdlet, `InputObject` argument ends up implicitly cast to `PSObject` type; and in case of `Serialize` method call, it remains as an `Object[]` array.

**Comment by SeeminglyScience** [comment]
Looks like method resolution is unwrapping the `PSObject` because the parameter type is `object`.  Here is proof/a workaround.

```powershell
using namespace System.Linq.Expressions
using namespace System.Management.Automation

$list = 'a', 'b', 'c'
Add-Member -InputObject $list -MemberType NoteProperty -Name Foo -Value Bar

# Returns clixml for the BaseObject
[System.Management.Automation.PSSerializer]::Serialize($list)

# Create a delegate that takes a PSObject and passes it directly to Serialize,
# bypassing PowerShell's argument conversion.
$serializeMethodInfo = [PSSerializer].GetMethod('Serialize', [type[]][object])
$parameter = [Expression]::Parameter([psobject], 'pso')
$lambda = [Expression]::Lambda(
    [Expression]::Call($serializeMethodInfo, $parameter),
    $parameter)

# Returns clixml for the PSObject, including the `Foo` property
$lambda.Compile().Invoke($list)
```

**Comment by FriedrichWeinmann** [comment]
@SeeminglyScience thank you for that explanation and sample, makes sense and works perfectly! 👍
