### ISSUE TITLE
Markdown commands should be distributed via the gallery

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#7423]
First of all, users of PowerShell 5 (and 3 and 4) need markdown commands too. Additionally, this steps on **multiple** third party modules that already exist and *are* backward compatible.

Finally, I'm really not sure why we need commands for markdown in PowerShell anyway.

I mean, I get that you want to use markdown stuff for help, but **obviously** you're not expecting people to get help by doing:  

```powershell
$Env:PSModulePath -split [IO.Path]::PathSeparator | 
Get-ChildItem -recurse -filter *.md | 
Get-Content | Select-String MyHelpSearch |
ConvertFrom-Markdown -asVt100 | 
Show-Markdown
```

Given all that, and the obviously limited Markdown that you can render in the console, there's no need to ship generic markdown cmdlets in the core -- but if you did need them, you should either use an existing third party module, or build your own and ship it to the gallery, not put them in Microsoft.PowerShell.Utility

**Comment by SteveL-MSFT** [comment]
[MarkdownEx](https://www.powershellgallery.com/packages/MarkdownEx/0.0.6) was a project created just 9 hours ago and published today so we couldn't have known about it.

I don't believe these cmdlets preclude use of other third party Markdown cmdlets.

The [Markdown Rendering RFC](https://github.com/PowerShell/PowerShell-RFC/blob/b276b9a6f29f52b52209feccb4e4b108779ad690/3-Experimental/RFC0025-Native-Markdown-Rendering.md) was first published last April so certainly sufficient time to get feedback.

The current cmdlets are on a path for [native markdown support for help content](https://github.com/PowerShell/PowerShell/issues/3954) and move away from MAML which requires the doc writers to convert from markdown to publish.  Additional work in 6.2 timeframe to have this work end-to-end.

The longer term plan is to [decouple all modules from PS Core](https://github.com/PowerShell/PowerShell/issues/1979).

**Comment by Jaykul** [comment]
I would not be very concerned about stepping on other commands -- **if** these commands were available on the gallery for older versions (like PowerShell 6)
