### ISSUE TITLE
Enter-PSSession Centos To Windows Fails

### ISSUE THREAD

**Issue by danielman111** [PowerShell/PowerShell#7425]
Using PowerShell version 6.0.2 on Centos 7, trying to get Session to Windows 2012 Server. 
Doing the following:

```
$secpasswd = ConvertTo-SecureString "password" -AsPlainText -Force

$mycreds = New-Object System.Management.Automation.PSCredential ("domain\username", $secpasswd)

Enter-PSSession -ComputerName Some-Host-Name -port 5985 -Credential $mycreds
```

Getting the Following Error:

```
 Enter-PSSession : MI_RESULT_ACCESS_DENIED                                                                                       At line:1 char:2
+  Enter-PSSession -ComputerName Some-Host-Name -port 5985 -Credential $m ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (Some-Host-Name :String) [Enter-PSSession], PSInvalidOperationException
+ FullyQualifiedErrorId : CreateRemoteRunspaceFailed
```

Should get session to the Windows Machine.

Any ideas what I need to do?

**Comment by kvprasoon** [comment]
@danielman111 PowerShell remoting from Linux to Windows currently works only using `ssh` . See **Remoting over WSMan** section [here](https://github.com/PowerShell/PowerShell/projects) and see examples [here](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Core/Invoke-Command?view=powershell-6#examples).

**Comment by danielman111** [comment]
> @danielman111 PowerShell remoting from Linux to Windows currently works only using ssh . See Remoting over WSMan section here and see examples here.

So the official answer is that PowerShell Core cant use Enter-PSSession to gain session from Linux to Windows?

**Comment by danielman111** [comment]
In the Link kvprasoon added, under **Remoting over WSMan**, it says the following:

> for macOS/Linux -> Windows remoting scenarios, our goal is to enable existing remoting cmdlets (e.g. Enter-PSSession, New-PSSession, and Invoke-Command) using the traditional WSMan protocol. This currently works for basic authentication as well as for NTLM-based authentication from (only) Linux environments.

So if I understand it correctly, It should be able me to use **Enter-PSSession** command in order to gain access remotely from Linux to Windows.
What am I missing?

**Comment by MaximoTrinidad** [comment]
@danielman111 

As it was mention before, Openssh need to be setup on the Windows Server.  To setup WSMan in Linux, although possible, it's harder compare to just install and configure Openssh in Windows.

In the above comments, is missing the information to setup WSMan for PowerShell in Linux. 
I found the following article that may bring some light to your dilema: https://4sysops.com/archives/powershell-remoting-between-windows-and-linux/

:)

**Comment by chuanjiao10** [comment]
1 install basic authentication as well as for NTLM-based authentication from  Linux ,then use Enter-PSSession over win-rm  to windows.
ntlm Depend on krb5.

2 install sshd on windows,then use Enter-PSSession over ssh to windows.
