### ISSUE TITLE
Where and forEach method missing in Get-member

### ISSUE THREAD

**Issue by adrienst** [PowerShell/PowerShell#7426]
I am not sure if it's a bug.

Steps to reproduce
------------------

$Array = 1,2,3,4,5
Get-member -inputobject $Array

Expected behavior
-----------------
I expected the Where and the ForEach method would show in a Get-member

Actual behavior
---------------

Where and ForEach method don't show in a Get-member 

Environment data
----------------

> $PSVersionTable
PSVersion                      6.1.0-preview.4
PSEdition                      Core
GitCommitId                    6.1.0-preview.4
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by mklement0** [comment]
These methods are PSv4+ and it took a while to even get them _documented_ - now they are, as part of [`Get-Help about_Arrays`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_arrays)

Similarly, the implicit `.Count` and `.Length` properties are mentioned there.

What these have in common is that they're _part of the plumbing_, if you will: PowerShell makes them available on instances of _any_ type, so as to facilitate unified handling of collections and scalars; e.g.:

```powershell
# Invoke .ForEach on string *scalar*
PS> 'foo'.ForEach({ "Hi, $_." }
Hi, foo.

# Invoke .Count on an integer *scalar*
PS> (666).Count
1
```

So there is some justification in omitting them from reflecting on a _given type's_ members, given they're not really members of any individual type.

That said, perhaps they could be discovered via new `-View` mode, such as `Get-Member -View Universal` - though discovering that view mode may in itself be a challenge.

I guess showing them by default is an option, but I wonder if that introduces too much noise.
