### ISSUE TITLE
start-process not passing arguments

### ISSUE THREAD

**Issue by liszca** [PowerShell/PowerShell#7427]
Steps to reproduce
------------------

```powershell
Start-Process Expand-Archive -Verb runas -ArgumentList "$HOME\Downloads\vim-ps1.zip -DestinationPath 'C:\Program Files (x86)\Vim\vimfiles\'"
```

Expected behavior
-----------------

```none
run command as Administrator and unzip the archive
```

Actual behavior
---------------

```none
Start-Process : This command cannot be run due to the error: Не удается найти указанный файл.
At line:1 char:1
+ Start-Process Expand-Archive -Verb runas -ArgumentList "$HOME\Downloa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
+ FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.4
PSEdition                      Core
GitCommitId                    6.1.0-preview.4
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by PetSerAl** [comment]
`Expand-Archive` is not executable program.

**Comment by liszca** [comment]
more hints please, isn't it a commandlet?

**Comment by PetSerAl** [comment]
Yes, `Expand-Archive` is cmdlet but `Start-Process` is not capable of starting cmdlets. You need to start PowerShell to use PowerShell cmdlets.

```powershell
Start-Process PowerShell <#or pwsh#> -ArgumentList …
```

**Comment by kvprasoon** [comment]
@liszca  You can execute `Get-Help Start-Process -Examples` or `Get-Help Start-Process -Online` check for the examples.

**Comment by SteveL-MSFT** [comment]
@liszca, as @PetSerAl explained, cmdlets are not processes you start with `Start-Process`.  If your intent is to run a cmdlet elevated, you can use the example he provided to start a new powershell (or pwsh) elevated and have that run your command line.

What you really want, however, is https://github.com/PowerShell/PowerShell/issues/3232

**Comment by liszca** [comment]
In my opinion there is something substantial wrong with the powershell if cmdlets are not processes, that should be changed, or at least tell me why this design dissension.

**Comment by PetSerAl** [comment]
@liszca Can you propose multi-process design, which allows passing live object around?
