### ISSUE TITLE
Disable-NetAdapterBinding -Name "MyAdapter"  -AllBindings -IncludeHidden disables bindings that cannot be disabled with -DisplayName or -ComponentID

### ISSUE THREAD

**Issue by Gristrosia** [PowerShell/PowerShell#7428]
Hi,

The help text for the command -AllBindings in the help page of "Disable-NetAdapterBinding" specify that "Some protocols and filters may be mandatory and therefore cannot be disabled"; however when used the command disables all the protocols, even those that cannot be disabled with -ComponentID  like  ms_netbt, ms_pppoe, ms_rdma_ndk, ms_pppoe, or when using -DisplayName. I assume these protocols that cannot be disabled using the -ComponentID or -DisplayName are the mandatory protocols that shouldn't be disabled.

So I was wondering; is this behavior normal, or is it an issue? 

Step to reproduce: 

Disable-NetAdapterBinding -Name 'Ethernet' -AllBindings -IncludeHidden

The command disables everything and it is impossible to re-enable disabled protocols like   ms_netbt, ms_pppoe, ms_rdma_ndk or ms_pppoe

![capture2](https://user-images.githubusercontent.com/25066224/43535577-abfd7664-95ba-11e8-9cdf-ec6435298c29.JPG)
![capture](https://user-images.githubusercontent.com/25066224/43535579-b11010c6-95ba-11e8-87ad-258b200c3f68.JPG)

**Comment by SteveL-MSFT** [comment]
This is not a module owned by PowerShell Team.  You should go here and submit Feedback: https://docs.microsoft.com/en-us/powershell/module/netadapter/disable-netadapterbinding?view=win10-ps
