### ISSUE TITLE
Select Storage Commands Don't Work in WinPE

### ISSUE THREAD

**Issue by Chirishman** [PowerShell/PowerShell#7429]
Bug Age: [5 Years](https://social.technet.microsoft.com/Forums/exchange/en-US/3a0e7e9c-f1ea-4324-8a17-f4c447efcbb0/some-storage-cmdlets-do-not-work-under-winpe?forum=winserverpowershell)

Steps to reproduce
------------------

[Follow this](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/winpe-adding-powershell-support-to-windows-pe)

Attempt to use:
```powershell
Clear-Disk
Format-Volume
```

Expected behavior
-----------------

Clears and or formats the disk in question

Actual behavior
---------------

`Unspecified Error 0x80004005`

Environment data
----------------

```powershell

Name                           Value
----                           -----
PSVersion                      5.1.17134.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by Chirishman** [comment]
Anybody? Bueller?

This problem has been open since 2013 guys, please at least triage it and label it as an issue so I know someone's read this...

@daxian-dbw @TravisEz13 @adityapatwardhan @iSazonov @anmenaga

**Comment by TravisEz13** [comment]
Please follow the instructions in the Issue template for Windows PowerShell issues:
https://github.com/PowerShell/PowerShell/blob/master/.github/ISSUE_TEMPLATE/Windows_PowerShell.md

**Comment by Chirishman** [comment]
@BrucePay sorry to bug you but when we talked about issue #6616 last year (which I had [originally raised on UserVoice all the way back in 2016](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/11638974-int32-keys-in-a-hashtable-do-not-match-equal-int64)) you told me that I should raise issues here because Uservoice is pretty much useless for getting bug reports seen.

Can I get some guidance here? Because in fact _still_ no one has responded to or triaged the UserVoice version of that bug report from 2016.

Sorry, I know this isn't an interesting engine problem like the Hashtable one, but it _is_ one that was discussed during the **OS Deployments using WinPE + PowerShell and WindowsImageTools** panel by David Jones at last year's PowerShell Summit and there doesn't seem to be any official acknowledgement that this issue exists.

**Comment by TravisEz13** [comment]
cc @SteveL-MSFT

**Comment by SteveL-MSFT** [comment]
@Chirishman Those cmdlets are in the `Storage` module which is not owned by the PowerShell team.  You should open the issue here: https://windowsserver.uservoice.com/forums/295056-storage
