### ISSUE TITLE
Enable whitelisting for debugging

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#7430]
From https://github.com/PowerShell/PowerShellEditorServices/issues/618.

There is an ask for a "just my code" functionality in the PowerShell debugger, so that debugging a script inside a Pester test, you don't have to step through, say, It.ps1 or Should.ps1.

Does anything like this exist in PowerShell currently?

**Comment by KirkMunro** [comment]
Thanks @iSazonov.

@rjmholt: See #10530 for my developing thoughts on JMC (just my code).
