### ISSUE TITLE
Event logging fails on macOS 10.13

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#7432]
Travis CI update macOS to `10.13.3` from `10.12.6` and the logging tests for macOS started to fail after that.
Here are a few failed builds:
https://travis-ci.org/PowerShell/PowerShell/jobs/410647719#L4675
https://travis-ci.org/PowerShell/PowerShell/jobs/410584884#L5560
https://travis-ci.org/PowerShell/PowerShell/jobs/410959434#L5523

The logging tests for macOS is marked as `pending` for now by PR #7433.

I tried the script block logging on macOS `10.12.6` with the file `powershell.config.json` located in `$PSHome` and the logging works fine -- expected script invocation related events show up in `Console`. However, when starting `pwsh` with `-settings <config.json>`, `Console` shows a bunch of security exceptions (see an example screenshot below).

Be noted that, @TravisEz13 tried the scirpt block logging on his macOS (version `10.13.6`), and `Console` consistently shows a bunch of security exception errors no matter by putting `powershell.config.json` under `$PSHOME` or by using `-settngs <config.json>`.

<img width="1121" alt="screen shot 2018-08-01 at 3 56 05 pm" src="https://user-images.githubusercontent.com/127450/43553372-8084e0c4-95a3-11e8-858a-1c1964464f56.png">

**Comment by TravisEz13** [comment]
I've debugged and there is a code path loading the configuration before the `-settingfile` parameter has been parsed in `Release` configuration but not others.  Here is the call stack
![image](https://user-images.githubusercontent.com/10873629/43680104-cb4f40ea-97e7-11e8-9481-b842bd86ac44.png)

**Comment by dantraMSFT** [comment]
Fixed by https://github.com/PowerShell/PowerShell/pull/7449
