### ISSUE TITLE
Add a ConvertTo-Markdown

### ISSUE THREAD

**Issue by mikemaccana** [PowerShell/PowerShell#7440]
Feature request:

Add a `ConvertTo-Markdown` - some common use cases:

 - Outputting objects into Markdown tables for documentation
 - Viewing HTML in the terminal with `Show-Markdown`
 
This would be a nice complement to https://github.com/PowerShell/PowerShell/pull/6926

**Comment by michaeltlombardi** [comment]
This would be enormously useful, especially now that [GitHub Actions have job summaries](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/) - I can think of several use cases where it would be very convenient to dump objects to markdown tables for reporting.
