### ISSUE TITLE
The Powershell 6.1 preview 4 icon varies from Windows icon guidelines

### ISSUE THREAD

**Issue by mikemaccana** [PowerShell/PowerShell#7441]
The powershell 6 preview 4 icon is very, er, edgy:

![image](https://user-images.githubusercontent.com/172594/43642270-74327cae-9716-11e8-96e1-1609d7c511bc.png)

More to the point, it's not [Windows icon guidelines](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/app-assets) 

 - it's got a lot of detail - Windows icons are generally a few basic shapes
 - not all the detail is recognisable - what is the curvy pink line?

This may be a test icon for preview releases (in which case close this bug) but a modern version of the previous icon (removing the gloss etc) would be much better.

**Comment by thezim** [comment]
It is hair of the avatar. You can see better [here](https://github.com/PowerShell/PowerShell/blob/master/assets/macDialog.png). Choosing an icon is always [difficult](https://code.visualstudio.com/blogs/2017/10/24/theicon).

**Comment by mikemaccana** [comment]
Thanks @thzom. I know the mascot, and even still I wasn't sure what I'm looking at. The detail looks even harder to distinguish in application windows:

![image](https://user-images.githubusercontent.com/172594/43644111-786679b0-9725-11e8-8fbf-677cc9cbda87.png)

VScode eventually settled on a really lovely icon. It could be worth asking @chrisdias to make something beautiful for Powershell!

**Comment by SteveL-MSFT** [comment]
This PR https://github.com/PowerShell/PowerShell/pull/7086 was provided to help disambiguate between stable and preview releases of PSCore6 as they co-exist side-by-side and many of our contributors have both pinned to the taskbar (including myself).

If anyone has contributions to alternate icons, please propose something and we can discuss.

**Comment by mikemaccana** [comment]
Even at large sizes, and having seen the powershell woman avatar (which TBH I'm not a fan of - it's a bit edgy and doesn't really go with Powershell's clean vibe) during the install, it's not clear it's her face and hair in the icon

![image](https://user-images.githubusercontent.com/172594/44256637-ad3e2c00-a201-11e8-990c-6328b0e79321.png)

**Comment by mikemaccana** [comment]
Thanks @SteveL-MSFT. vscode uses blue for stable, green for development builds, so why not:

![ps_black_64](https://user-images.githubusercontent.com/172594/44256962-8c2a0b00-a202-11e8-9873-b3e8fd60d301.png)

**Comment by SteveL-MSFT** [comment]
@mikemaccana You'll need to get more community support to enact a change of the icon

**Comment by mikemaccana** [comment]
Yep agreed. Thinking about it, it's probably better to get the regular Powershell icon (which also doesn't match the Windows style) updated too - remove the shadows, the round edges and focus on shape like Windows 10 icons. @chrisdias who made the vscode icon?

**Comment by mikemaccana** [comment]
@SteveL-MSFT Hello again! Here's an updated suggestion that fits in more with other Windows 10 icons but is still recognisable as Powershell, while being significantly different from the previous icon per #7086. Happy to send a PR.

![image](https://user-images.githubusercontent.com/172594/44930703-1328c880-ad57-11e8-810a-6c03f83c42dd.png)

**Comment by vexx32** [comment]
I might advocate for using slightly thicker lines for a less spindly look, but that looks *lovely*. Nice work!

**Comment by thezim** [comment]
Don’t forget that other operating systems may have [guidelines](
https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/) as well. Personally I think the current non-preview icon is good and distinguishable from its Windows counterpart which is important. For the preview version I feel it is a little too busy and prefer the green version in this issue so far.

**Comment by mikemaccana** [comment]
@vexx32 Thanks for the positive feedback! Yeah I agree, it's the same size but doing it negatively makes it look thinner. Will update shortly.

**Comment by vexx32** [comment]
I would also probably encourage that the icon should keep a similar look on OSX -- black background, blue console prompt foreground type of style.

This could also be a good branchpoint for the preview icon; say, having the preview icon retain the black background but be given a green foreground color, or something similar.

**Comment by mikemaccana** [comment]
Cropped it to make it thicker while still keeping the same proportions as the original icon, and sharped the edges:

![image](https://user-images.githubusercontent.com/172594/44935254-db764c80-ad67-11e8-955d-44a0bfefdeb9.png)

The preview icon is based on the vscode insiders color:

![image](https://user-images.githubusercontent.com/172594/44935531-f3020500-ad68-11e8-9358-489c5467977f.png)

**Comment by thezim** [comment]
@mikemaccana do you have your work in a repo yet, in SVG? Would like to see how they look on macOS.

**Comment by thezim** [comment]
@mikemaccana It definitely need a margin to fit in on macOS. I've included my full Dock so you can see the context. Click to enlarge.

![new-ps](https://user-images.githubusercontent.com/14023826/44936951-ecfa2d00-ad44-11e8-94a8-47b73c440b79.png)

**Comment by vexx32** [comment]
I'd be tempted to say you'll still want some kind of a background behind the prompt symbol, at least on MacOS.

**Comment by thezim** [comment]
Remember the guidelines are just that. I think there needs to area where the two can meet. The selling point of PowerShell Core is it is cross platform and having consitency cross platforms is important. This shouldnt be overlooked by taking a hardline with "guidelines".

@SteveL-MSFT can you weigh in on this before efforts are made?

**Comment by MSAdministrator** [comment]
Personally, I like this first one shared (with thinner lines). ++++

**Comment by mikemaccana** [comment]
Thanks for the committee review @SteveL-MSFT. https://github.com/PowerShell/PowerShell/issues/7441#issuecomment-417787361 is the most recent, and the most that meets with other Windows icons. @thezim while Powershell is cross platform, but look at other cross platform apps - Office, vscode, etc - the icons used are native to the OS style.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee appreciates the input, however, branding and trade dress is currently owned by the PowerShell team.  There will be opportunities in the future where we may look for community input in these areas, however, at this time we are not looking to update our icons.

**Comment by mikemaccana** [comment]
@SteveL-MSFT OK, obviously you reviewed it and you think it sucks. Fair enough. But can you please get someone - an actual graphic designer in Microsoft - to make a Windows-10 style PS icon?

Currently we have a mix of:

 - A modern flat, outline-style icon used by VSCode's official powershell extensions
 - The anime-face avatar used in Powershell Core 6.1
 - The blue background powershell icon used for Windows Powershell

None of these are ideal.

**Comment by SteveL-MSFT** [comment]
@mikemaccana I know you don't like the current icons, but the ones were are currently using are from an actual graphic designer at Microsoft

**Comment by mikemaccana** [comment]
Steve are you sure? It seems a little odd a professional would create three
wildly different icons for the same product. Whether I like them or not is
off topic.

**Comment by mmillar-bolis** [comment]
@mikemaccana I find some of your points actually support the PowerShell team's decisions, actually.

Office and VSCode are graphical applications intended to be accessed and manipulated through a GUI shell. PowerShell is just that, another shell that also implements it's own language; it's NOT an app.

On every system except for NT, the user will be accessing pwsh the same as any other shell, via their terminal emulator, and that is the icon they will likely see (if using a GUI at all). The PowerShell Core icons in your GUI shell's path are just a courtesy shortcut, extra to any features of the project. On NT, try creating your own shortcut for conhost invocations, and be aware that changes are on the horizon for how that might work.

The point is, PowerShell Core's "logo" should be understood like Bash or Python's: It's just part of the project branding.

Have a look at some other shell and language logos. Most of those projects, when packaged downstream, don't even distribute shortcuts for invoking their shells EXCEPT on NT.

The very nature of conforming to each platform suggests to me that it's worth considering getting rid of the shortcuts entirely at some point. It doesn't seem like the kind of thing that should be the PowerShell team's responsibility, and I assume these courtesy shortcuts are for ease of use to aid in adoption.

Regardless, for intersystem maintainers, I wouldn't necessarily encourage any habits that rely on their form or function outside of teaching new users how to invoke other shells.

**Comment by mikemaccana** [comment]
There hasn't been a 'decision'. There's just very obviously been different
grouos within Microsoft that have made different versions of the same logo
and no effort to do as the issue title says.

As you say, Linux shells don't have icons because they're generally invoked
via a terminal app. In Windows they're not invoked  this way. That supports
having a properly maintained icon.

Let's kill the thread and I'll throw away the contribution. These
conversations - being gaslit into thinking there's actually a current
consistent power I can't see it and this one and being told we should throw
away all shell shortcuts - are inane and unpleasant.

**Comment by mikemaccana** [comment]
(deleted previous reply as email replies aren't formatted properly)

There hasn't been a 'decision'. There's just very obviously been different groups that have made different versions of the same logo and no effort to do as the issue title says.

As you say, Linux shells don't have icons because they're generally invoked via a terminal app. In Windows they're not invoked  this way. That supports having a properly maintained icon.

**Let's kill the thread and I'll throw away the contribution.** These conversations - being gaslit into thinking there's actually a current consistent powershell icon and I just can't see it and this one and being told we should throw away all shell shortcuts - are inane and unpleasant. 

I'm muting the thread.
