### ISSUE TITLE
PowerShell Core: Unable to return custom pstypename added to object

### ISSUE THREAD

**Issue by MSAdministrator** [PowerShell/PowerShell#7450]
Steps to reproduce
------------------
I am seeing an issue with setting a custom Type on a `PSCustomObject`.  To reproduce, I have a function that takes input and returns a custom object
```powershell
function New-CustomObject{
[CmdletBinding(DefaultParameterSetName = 'Parameter Set 1',
        PositionalBinding = $false,
        HelpUri = '',
        ConfirmImpact = 'Medium')]
    param (
        [Parameter(Mandatory = $true,
            Position = 0,
            ValueFromPipelineByPropertyName = $true,
            ParameterSetName = 'Parameter Set 1')]
        [ValidateNotNull()]
        [ValidateNotNullOrEmpty()]
        [String]$SomeString
)

$CustomObject = @()

$CustomObject = $SomeString
$CustomObject.PsObject.TypeNames.Add('Example.Custom.Type')
$CustomObject.PSObject.TypeNames.Insert(0, 'Example.Custom.Type')

return $CustomObject
# I have also tried to call Write-Output and still the same result.
}
```

Expected behavior
-----------------
The expected behavior is that when an object has a custom type set, it should retain this custom type when returned from a function in PowerShell core.
```none

```

Actual behavior
---------------
When getting the returned object it does not have the PSTypeName and it cannot be used in an additional function with a specified custom type name.  For example, in a Advanced Function I have a parameter with a custom type and it will not accept this object:

```powershell
[PSTypeName('Example.Custom.Type')][object[]]$SomeCustomType,
```

Calling the function I provided above has the following results:
```powershell
$CustomTypeObject = New-CustomObject -SomeString 'Here is some string'
$CustomTypeObject.GetType()
```

```output
#Returned results
IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     String                                   System.Object
```

```powershell
# Calling the pstypenames property I get the following
$CustomTypeObject.pstypenames
```

```output
System.String
System.Object
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
What about
```powershell
$b = [pscustomobject]@{v = "tst"}
$b
$b.psobject
$b.psobject.TypeNames.add("TestType")
$b.psobject
```

**Comment by markekraus** [comment]
This actually has nothing to do with functions. It appears that you cannot add custom types to strings. In your example code, you are essentially assigning a custom type name to the `$SomeString` string. 

You can repro this problem more succinctly with:

```powershell
$a = 'a'
$a.PSObject.TypeNames.Insert(0,'Example.Custom.Type')
$a.PSOBject.TypeNames
```

You can see that the `'Example.Custom.Type'` PSTypeName is not added to the TypeNames collection. I get the same result in 5.1 as  do in 6.0.0+

**Comment by dragonwolf83** [comment]
The code is not producing a `PSCustomObject`. You are setting an array and then overwriting it with a string, so the type is `String`. Using `Write-Output` or `return` does not change or set the type to be a `PSCustomObject`. 

You either need to use `New-Object` and `Add-Member` or more simply
```PowerShell
$CustomObject = [PSCustomObject] @{ SomeString = $SomeString }
```

You can also simplify it down even further by setting `PSTypeName` with the object and let it output directly to the Pipeline. See the code below:
```PowerShell
function New-CustomObject{
[CmdletBinding(DefaultParameterSetName = 'Parameter Set 1',
        PositionalBinding = $false,
        HelpUri = '',
        ConfirmImpact = 'Medium')]
    param (
        [Parameter(Mandatory = $true,
            Position = 0,
            ValueFromPipelineByPropertyName = $true,
            ParameterSetName = 'Parameter Set 1')]
        [ValidateNotNull()]
        [ValidateNotNullOrEmpty()]
        [String]$SomeString
)

    [PSCustomObject] @{ 
        PSTypeName = "Example.Custom.Type"
        SomeString = $SomeString
    }
}

$CustomTypeObject = New-CustomObject -SomeString 'Here is some string'
$CustomTypeObject | Get-Member 
```

Notice, I do not have `Write-Output` or `return`. Anything that generates output defaults to writing to the `Output Stream` of the Pipeline which is what is returned, no matter where or how many times it is written in the function. If I set the object to a variable, I can just output with `$customVariable` and will do the same thing as `Write-Output $customVariable`.

**Comment by markekraus** [comment]
@dragonwolf83 You can manipulate TypeNames on just about any object type, not just `PSCustomObject`s. However, it appears that Strings are an exception to the rule.

Tak Int for example:

```powershell
[int]$One = 1
$One.PSObject.TypeNames.Insert(0,"Example.Custom.Type")
$One.PSObject.TypeNames
```

Result

```none
Example.Custom.Type
Test.Type
System.Int32
System.ValueType
System.Object
```

But String does not:

```powershell
$a = 'a'
$a.PSObject.TypeNames.Insert(0,'Example.Custom.Type')
$a.PSOBject.TypeNames
```

Result:

```none
System.String
System.Object
```

**Comment by dragonwolf83** [comment]
Interesting... That is good to know. I only added a comment because @MSAdministrator refers to setting a PSTypeName on a  `PSCustomObject` and I didn't see it get set anywhere.

If Strings are expected to allow a custom PSTypeName, then I think a new issue needs to be created or this issue and description updated to ask for it.

**Comment by MSAdministrator** [comment]
I will go ahead and close this issue out and create a separate issue for being able to set a custom type on a `system.string`.  Thanks all for the clarification!
