### ISSUE TITLE
Show-Markdown unusable on a dark terminal theme

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#7454]
Steps to reproduce
------------------

I'm using a dark background on a terminal on mac. This is pretty common setup as far as I know.
Here is how `Show-Markdown` output looks.

![markdown-powershell](https://user-images.githubusercontent.com/816680/43689895-bb3ff5ea-98b5-11e8-862e-d235333b618a.gif)

Expected behavior
-----------------

All text should be readable.

Actual behavior
---------------

Code snippet text is not readable against the background.

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.4
PSEdition                      Core
GitCommitId                    6.1.0-preview.4
OS                             Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/REL...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
What do you suggest? Change default theme on Mac?

**Comment by vors** [comment]
There are many themes, unfortunately theme only provides the normal text and selected text color, nothing else that could be used.

![image](https://user-images.githubusercontent.com/816680/43737743-2e52bdee-9977-11e8-8861-bbf00938b001.png)

**Comment by adityapatwardhan** [comment]
@vors 

The code block not showing on macOS was fixed in https://github.com/PowerShell/PowerShell/pull/7329 
Can you give it a try on master?

**Comment by ThomasNieto** [comment]
@iSazonov I tested this using 7.1rc and didn't have the issue. Can you please confirm and see if this issue can be closed?

**Comment by vexx32** [comment]
Looks like it's sorted for me on Mac as well.

**Comment by ThomasNieto** [comment]
@vexx32 should this issue be closed then?
