### ISSUE TITLE
Setting Security Protocol to ssl3 is not supported

### ISSUE THREAD

**Issue by MaxBurgert** [PowerShell/PowerShell#7474]
When trying to run [chocolatey](https://github.com/chocolatey/choco) with PSVersion 6.0.3 setting the security protocol to ssl3 raises the mentioned error [here](https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/helpers/functions/Get-ChocolateyWebFile.ps1#L312).

In addition there seems to be no explicit information about the deprecation of ssl3 in PowerShell 6.

Steps to reproduce
------------------

```powershell
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::ssl3
```

Expected behavior
-----------------

```none
C:\Users\user\Documents> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::ssl3
C:\Users\user\Documents>
```

Actual behavior
---------------

```none
Exception setting "SecurityProtocol": "The requested security protocol is not supported."
At line:1 char:1
+ [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolTy ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
+ FullyQualifiedErrorId : ExceptionWhenSetting
```

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.0.3
PSEdition                      Core
GitCommitId                    v6.0.3
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment]
SSL 3.0 was deprecated
https://blogs.technet.microsoft.com/askpfeplat/2018/02/12/retire-those-old-legacy-protocols/
https://tools.ietf.org/html/rfc7568
https://docs.microsoft.com/en-us/security-updates/securityadvisories/2015/3009008

**Comment by MaxBurgert** [comment]
Thank you. I've opened an [PR](https://github.com/chocolatey/choco/pull/1624) that will resolve this issue.
