### ISSUE TITLE
Select-String check pattern not work correct in this case (.,$,^)

### ISSUE THREAD

**Issue by ahmedjavid** [PowerShell/PowerShell#7480]
Actual behavior

PS C:\> "Powershell" | Select-String -Pattern "."
Powershell
PS C:\> "Powershell" | Select-String -Pattern "$"
Powershell
PS C:\> "Powershell" | Select-String -Pattern "^"
Powershell

**Comment by thezim** [comment]
This is by design. Those are all valid regular expressions that match.

-Pattern

Specifies the text to find. Type a string or regular expression. If you type a string, use the SimpleMatch parameter.

You can try them out [here ](https://regex101.com/) too.

**Comment by powercode** [comment]
```powershell
