### ISSUE TITLE
Import-Module on path ignores version constraints

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#7496]
Steps to reproduce
------------------

**Note**: The repro uses a relative path, but an absolute path works too; just insert `$PWD` instead of the `.` below.

```powershell
> mkdir ./AModule
> New-ModuleManifest -Path ./AModule/AModule.psd1 -ModuleVersion '2.0'
> Import-Module -Path ./AModule/
> Import-Module -PassThru -FullQualifiedName @{ ModuleName = "./AModule/AModule.psd1"; ModuleVersion = '3.0' } # Also try the absolute path - same outcome
```

Expected behavior
-----------------

```none
Import-Module : The specified module './AModule/AModule.psd1' with version '3.0' was not loaded because no valid module file was found in any module directory.
At line:1 char:1
+ Import-Module -PassThru -FullyQualifiedName @{ ModuleName = './AModul ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ResourceUnavailable: (./AModule:String) [Import-Module], FileNotFoundException
+ FullyQualifiedErrorId : Modules_ModuleWithVersionNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

```

Actual behavior
---------------

```none

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   2.0        AModule                             

```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.4
PSEdition                      Core
GitCommitId                    6.1.0-preview.4-61-g1243891ea8c04609ce21d0b31d40945fd46a3576
OS                             Linux 4.15.0-30-generic #32-Ubuntu SMP Thu Jul 26 17:42:43 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

## More information

**EDIT**: Just realised this is for re-imports only (which is good!)

The important note is that importing the same module off the module path will fail:

```powershell
> $env:PSModulePath += [System.IO.Path]::PathSeparator + $PWD
> Import-Module -PassThru -FullyQualifiedName @{ ModuleName = 'AModule'; ModuleVersion = '3.0' }
Import-Module : The specified module 'AModule' with version '3.0' was not loaded because no valid module file was found in any module directory.
At line:1 char:1
+ Import-Module -PassThru -FullyQualifiedName @{ ModuleName = 'AModule' ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ResourceUnavailable: (AModule:String) [Import-Module], FileNotFoundException
+ FullyQualifiedErrorId : Modules_ModuleWithVersionNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
 
```

This behaviour is caused by this logic:
https://github.com/PowerShell/PowerShell/blob/1243891ea8c04609ce21d0b31d40945fd46a3576/src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs#L589-L595

Note that [it's impossible to instantiate a ModuleSpecification with all checked fields not `null`](https://github.com/PowerShell/PowerShell/blob/1243891ea8c04609ce21d0b31d40945fd46a3576/src/System.Management.Automation/engine/Modules/ModuleSpecification.cs#L155-L165), so this check always succeeds.

This is addressed by https://github.com/PowerShell/PowerShell/pull/7125, but this discovery means it's a breaking change.

**Comment by iSazonov** [comment]
Absolute or relative path?

**Comment by rjmholt** [comment]
@iSazonov Turns out it's both, but this only occurs after the module has already been imported beforehand.

I've updated the issue.

**Comment by iSazonov** [comment]
@rjmholt Could you update the Issue header too?

**Comment by rjmholt** [comment]
Which part is the issue header? I updated the repro before -- I think all parts of the issue are correct now

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this, this definitely is both a breaking change and a bug.  We should do the version check to look for the requested version instead of just returning the loaded version.

**Comment by SteveL-MSFT** [comment]
@rjmholt can we get this fix in sooner so that we can get community feedback if it's an impactful breaking change?

**Comment by rjmholt** [comment]
Fix is in https://github.com/PowerShell/PowerShell/pull/7125
