### ISSUE TITLE
upgrade to RS5 17723->open file explorer->click on  "file" which is on the upper left to select "open Windows powershell" and press "Tab" button->the powershell window can extend-retract by itself F/R:100%

### ISSUE THREAD

**Issue by os-ly** [PowerShell/PowerShell#7508]
Steps to repro:
-1.install Mach RS4 1.4.0.7;
 2.upgrade to 17723.1000 by image file;
 3.open file explorer;
 4.click on the file which is on the upper left to run powershell;
 5.press "Tab"or "enter"  button.

Expected results: the powershell window side is displayed normally

Actual results: the powershell window side can extend-retract by itself

Repro rate: 5 out of 5 times
```
Environment data
----------------
PS C:\> $psversiontable

Name                           Value
----                           ----- 
PSVersion                                  5.1.17733.1000
PSEdition                                   Desktop
PSCompatibleVersions              {1.0, 2.0, 3.0, 4.0...}
BuildVersion                               10.0.17733.1000
CLRVersion                                 4.0.30319.42000
WSManStackVersion                  3.0
PSRemotingProtocolVersion      2.3
SerializationVersion                    1.1.0.1

**Comment by iSazonov** [comment]
@os-ly Thanks for your report!

Windows PowerShell is not in the repo. Please report with Windows 10 Preview tools or on [UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell).

**Comment by os-ly** [comment]
we repro it also on Uservoice, pls check and respond, thanks

**Comment by os-ly** [comment]
related link on uservoice: https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/35104927-powershell-gui-interface-extension-unnormally-issu

**Comment by iSazonov** [comment]
@os-ly Thanks for your report!
