### ISSUE TITLE
Parser incorrectly parses large integer values as double, losing precision

### ISSUE THREAD

**Issue by vexx32** [PowerShell/PowerShell#7510]
Although there *is* a case for bigint parsing in the tokenizer.cs file, it is almost never used, even when it would arguably be preferable to the loss of precision that using double for large integers creates.

Parsing a large integer as a double is pretty hard to fail at, since the double parser will simply treat it as an exponential number. This may be fine for some data entry, but in most cases if you're literally entering a huge integer, you probably want to keep the data intact.

Currently one must work around this by surrounding the value in quotes and manually casting that string value to `[bigint]`. In calculations, there is arguably reason to treat such values as double, especially when division is an operation that may create a double value regardless of the initial number type... but when initially parsing the number type it doesn't make sense to automatically treat it as a double. 

The bigint conversion should be tried first, before double parsing is attempted. (in my opinion)

Steps to reproduce
------------------

```powershell
PS> 99999999999999999999999999999
```

Expected behavior
-----------------

```powershell
99999999999999999999999999999
```

Actual behavior
---------------

```powershell
1E+29
```
Note the unnecessary loss of precision.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.4
PSEdition                      Core
GitCommitId                    6.1.0-preview.4
OS                             Microsoft Windows 10.0.17713
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Why not `int64`? We convert `long` in `int64`.

**Comment by vexx32** [comment]
`long` *is* `int64` but that also doesn't go nearly as high as `bigint` does.

Well it does automatically use `int64` up to `Int64.MaxValue` (9223372036854775807) after which.. let's see... seems to convert to `Decimal`. OK... After that max value (79228162514264337593543950335) it automatically goes to `double` which is an *instant* precision loss.

If it instead tries to convert to `[bigint]` before jumping to `double` you can retain precision for many significantly large integers. There might be a point at which significant digits is more important than retaining input integrity, but arguably if someone inputs a large integer deliberately in the console or directly in the script (which is what the tokenizer is looking at) they probably *want* to retain the integer integrity and not switch to significant digits.

Since we have `bigint` available, we should probably use it. Currently the way the tokenizer handles it, purely by order of trying parse methods, it completely skips the `bigint` code branch, from what I can see.

It may be worth having it do *both* `double` and `bigint` parsing and trying to compare which is closest to the original, but I don't know if there's a meaningful data type that can check that accurately (if there were... we'd probably be using that instead of either of them!)

**Comment by iSazonov** [comment]
What about decimal?
```powershell
> (999999).GetType().Fullname
System.Int32
> (9999999).GetType().Fullname
System.Int32
> (99999999).GetType().Fullname
System.Int32
> (999999999).GetType().Fullname
System.Int32
> (9999999999).GetType().Fullname
System.Int64
> (99999999999).GetType().Fullname
System.Int64
> (999999999999).GetType().Fullname
System.Int64
> (9999999999999).GetType().Fullname
System.Int64
> (99999999999999).GetType().Fullname
System.Int64
> (999999999999999).GetType().Fullname
System.Int64
> (9999999999999999).GetType().Fullname
System.Int64
> (99999999999999999).GetType().Fullname
System.Int64
> (999999999999999999).GetType().Fullname
System.Int64
> (9999999999999999999).GetType().Fullname
System.Decimal
> (99999999999999999999).GetType().Fullname
System.Decimal
> (999999999999999999999).GetType().Fullname
System.Decimal
> (9999999999999999999999).GetType().Fullname
System.Decimal
> (99999999999999999999999).GetType().Fullname
System.Decimal
> (999999999999999999999999).GetType().Fullname
System.Decimal
> (9999999999999999999999999).GetType().Fullname
System.Decimal
> (99999999999999999999999999).GetType().Fullname
System.Decimal
> (999999999999999999999999999).GetType().Fullname
System.Decimal
> (9999999999999999999999999999).GetType().Fullname
System.Decimal
> (99999999999999999999999999999).GetType().Fullname
System.Double
```

**Comment by vexx32** [comment]
As you demonstrate, decimal also has a maxvalue. As I mentioned. 

In terms of actually doing calculations, other types are likely preferable, as doubles (for example) are much better to work with for complex mathematical operations. That's fair enough, but if you go to the effort to actually input a ginormous integer in console or script (i.e., where the tokenizer is looking) you probably want that ginormous integer, rather than `1E+40`

**Comment by BrucePay** [comment]
Hi @vexx32  As a systems management and automation language, what use cases to do you see for supporting `BigInteger` in PowerShell? Since doing so would increase the complexity of numeric processing and almost certainly have a performance cost, what benefits would accrue to offset these costs? For example, what new scenarios would be enabled? Thanks!

**Comment by vexx32** [comment]
You can automate counting grains of sand? 

Server stacks?

Hard drives?

Accurately!

In all seriousness, I just think that if the user goes to the effort of actually inputting a huge integer there's not much reason for the parser to assume that only significant digits are needed. If you type out a 50-digit integer, you *damn well want* that 50-digit integer!

As long as the overall mathematical operations aren't impeded by this, I don't see a great deal of change here apart from not thwarting the user's efforts to use arbitrarily large integers. 😁

**Comment by iSazonov** [comment]
I also think that this is superfluous. Decimal type is big enough to cover all existing needs.

I think we have enough information for PowerShell Committee conslusion.

/cc @SteveL-MSFT

**Comment by joeyaiello** [comment]
@PowerShell/powershell-committee reviewed this. We can revisit this when we see a strong customer case, but right now we think that the change would require some guidance from a performance expert on the team, and we don't think that's worth anyone's time right now. 

Leaving open if people want to stash more discussion or use cases, but we don't plan on revisiting it soon.
