### ISSUE TITLE
MacOS Homebrew can't find powershell-preview package

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#7520]
No able to install the PowerShell-Preview package in MacOS using HomeBrew

Steps to reproduce
------------------

```powershell
brew cask install powershell-preview
```

Expected behavior
-----------------
To be able to install the latest version of the preview.
```none

```

Actual behavior
---------------
HomeBrew error.
```none
kronos:~ maxt$ brew cask install powershell-preview
Error: Cask 'powershell-preview' is unavailable: No Cask with this name exists.
```

Environment data
----------------
MacOS version:
```
kronos:~ maxt$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65

```

```powershell
> $PSVersionTable

```
![macos_pwshpreview _err_ga_2018-08-14_8-17-09](https://user-images.githubusercontent.com/19892435/44091571-e8debf6c-9f9b-11e8-8d40-fe20eac41673.jpg)

**Comment by MaximoTrinidad** [comment]
Forgot to mention.  I'm following the instructions found in MS Docs: https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-powershell-core-on-macos?view=powershell-6

:)

**Comment by TylerLeonhardt** [comment]
I'm pretty sure the powershell-preview package isn't owned by our team... Is this still true @TravisEz13?

**Comment by TravisEz13** [comment]
@MaximoTrinidad 	Are you sure you did this step?
```
brew tap homebrew/cask-versions
```

Since, the preview cask is not stable, it cannot be in the main tap.
