### ISSUE TITLE
-Repository parameter should have tab completion

### ISSUE THREAD

**Issue by maddieclayton** [PowerShell/PowerShell#7545]
The -Repository parameter in Install-Module (and other cmdlets) should have tab completion over the known repositories.  This should be easy because you can easily get repository names by running Get-PSRepository.

**Comment by vexx32** [comment]
Just needs a `Register-ArgumentCompleter` somewhere, at the very low-effort end of things.

**Comment by SteveL-MSFT** [comment]
Please open this issue in https://github.com/powershell/powershellget
