### ISSUE TITLE
PowerShell core release process for v6.1.0-rc.1

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#7548]
From:  https://github.com/PowerShell/PowerShell/blob/master/docs/maintainers/releasing.md

- [x] Create a private branch named `release-v6.1.0-rc.1` in VSTS repository.
   All release related changes should happen in this branch.
- [x] Run tests on all supported Linux distros and publish results
- [x] Prepare packages
   - [x]  Build release packages
   - [x]  Sign the MSI packages and RPM package.
   - [x]  Install and verify the packages.
- [x]  Update documentation, scripts and Dockerfiles
   - [x]  Update [CHANGELOG.md](../../CHANGELOG.md) with the finalized change log draft.
   - [x]  Update other documents and scripts to use the new package names and links.
- [x]  Create NuGet packages and publish them to `powershell-core` feed.
- [x]  Publish Linux packages to Microsoft YUM/APT repositories.
- [ ]  Create the release tag and push the tag to `PowerShell/PowerShell` repository.
- [x]  Create the draft and publish the release in Github.
- [x]  Merge the release branch to Github `master` with a merge commit. Then delete the release branch.
- [x]  Trigger the release docker builds for Linux and Windows container images.
- [x] Release SDK packages to NuGet.org

**Comment by dantraMSFT** [comment]
Created issue for PSRP remoting on Debian 9: https://github.com/PowerShell/PowerShell/issues/7598

**Comment by adityapatwardhan** [comment]
Release completed.
