### ISSUE TITLE
Improve error message when trying to convert from obj to older version of obj class.

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShell#7558]
When reloading a module with classes, and the current session has data created by the older version of the module, we get error messages like

```
Cannot convert the "A" value of type "A" to type "A".
At line:1 char:1
+ $a = [A]::new()
```

Sample code:
```
class A {
    [string] $a
}

[A] $a = [A]::new()

# paste this later

class A {
    [string] $a
}

$a = [A]::new()
```

I suggest that we add a check if the names of the classes are the same, when generating the error message, and in that case add some explanation why it is happening.

**Comment by potatoqualitee** [comment]
Lost 3 hours of my life to this issue this morning. Thank you Steffan for the insight!

**Comment by powercode** [comment]
Ping to keep alive
