### ISSUE TITLE
There should be more `Test-Command` and `Test-Module` cmdlets

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#7562]
Specifically, `Test-Command` and `Test-Module` is used heavily in our tests and build module which currently rely on `Get-Command -ErrorAction SIlentlyContinue` which can mask other issues other than testing if a command exists.

- [ ] - Test-Culture (approved in #7702)

**Comment by joeyaiello** [comment]
There is a reasonable design proposal for `Test-Command` in #8755, which is now closed as a duplicate. 

Marking this as `Up-for-Grabs` given that @PowerShell/powershell-committee is fairly confident that we would take something like this into PowerShell .
