### ISSUE TITLE
Missing cmdlets in SQLServer Module.

### ISSUE THREAD

**Issue by RavenSwords** [PowerShell/PowerShell#7563]
Sorry if this has been asked before etc....

There seems to be a number of missing cmdlets from the SQLServer module when I import it into a 6.04 session vs  5. 

For instance, Restore-SQLDatabase is missing, but Backup-SQLDatabase is present and works...

The list of missing cmdlets as far as I can tell is:

 

Add-RoleMember
Add-SqlAzureAuthenticationContext
Add-SqlFirewallRule
Backup-ASDatabase
Complete-SqlColumnMasterKeyRotation
Disable-SqlAlwaysOn
Enable-SqlAlwaysOn
Export-SqlVulnerabilityAssessmentBaselineSet
Export-SqlVulnerabilityAssessmentScan
Import-SqlVulnerabilityAssessmentBaselineSet
Invoke-ASCmd
Invoke-PolicyEvaluation
Invoke-ProcessASDatabase
Invoke-ProcessCube
Invoke-ProcessDimension
Invoke-ProcessPartition
Invoke-ProcessTable
Invoke-Sqlcmd
Invoke-SqlColumnMasterKeyRotation
Invoke-SqlVulnerabilityAssessmentScan
Merge-Partition
New-RestoreFolder
New-RestoreLocation
New-SqlColumnEncryptionKey
New-SqlColumnEncryptionKeyEncryptedValue
New-SqlColumnEncryptionSettings
New-SqlVulnerabilityAssessmentBaseline
New-SqlVulnerabilityAssessmentBaselineSet
Remove-RoleMember
Remove-SqlFirewallRule
Restore-ASDatabase
Restore-SqlDatabase
Save-SqlMigrationReport
Set-SqlAuthenticationMode
Set-SqlColumnEncryption
Set-SqlNetworkConfiguration
Start-SqlInstance
Stop-SqlInstance
Test-SqlAvailabilityGroup
Test-SqlAvailabilityReplica
Test-SqlDatabaseReplicaState
Test-SqlSmartAdmin

 To reproduce:
Install and import SQLServer module, then try to run any of the above commands.

Thanks,
p~

**Comment by MaximoTrinidad** [comment]
Just an FYI

This is only for PowerShell Core issues (not Windows PowerShell) and not non-Core Modules.

The SQLServer module issues need to be reports thru email on PowerShell Gallery directly to the module owner: https://www.powershellgallery.com/packages/SqlServer/21.0.17279

Just use the Contact Owner link and send the email.

Yes! The Restore-Backup has been missing for some time.  In this case, you could use SMO to script your own version of a Restore-Backup command.

Hope this helps!

**Comment by RavenSwords** [comment]
Yes, thank you!
