### ISSUE TITLE
New-PSSession does not connect to a redirected URI when larger token-based authorization headers are provided

### ISSUE THREAD

**Issue by vinodc** [PowerShell/PowerShell#7567]
Steps to reproduce
------------------

The ConnectionURI passed to New-PSSession sometimes redirects to another URI. This was handled in for Linux in https://github.com/PowerShell/psl-omi-provider/issues/72. However, this does not seem to work when a token is used instead.

```powershell
> $Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri "https://ps.compliance.protection.outlook.com/PowerShell-LiveId?BasicAuthToOAuthConversion=true" -Credential $Ctoken -Authentication Basic -AllowRedirection

New-PSSession : [ps.compliance.protection.outlook.com] Connecting to remote server
ps.compliance.protection.outlook.com failed with the following error message :
Basic Authorization failed for user ***@***.com For more information, see the about_Remote_Troubleshooting Help topic.
At line:1 char:12
+ $Session = New-PSSession -ConfigurationName Microsoft.Exchange -Conne ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotingTransportException
+ FullyQualifiedErrorId : 2,PSSessionOpenFailed
```

In this case, the redirect would have been to `https://nam04b.ps.compliance.protection.outlook.com/PowerShell-LiveId?BasicAuthToOAuthConversion=true`

Expected behavior
-----------------

The connection should proceed to `https://nam04b.ps.compliance.protection.outlook.com/PowerShell-LiveId?BasicAuthToOAuthConversion=true`

The following warning should be displayed:

```
WARNING: Your connection has been redirected to the following URI:
"https://nam04b.ps.compliance.protection.outlook.com/PowerShell-LiveId?BasicAuthToOAuthConversion=true;PSVersion=6.1.0"
```

Actual behavior
---------------

The connection does not succeed.

I made the following observations:
* Connecting directly to `https://nam04b.ps.compliance.protection.outlook.com/PowerShell-LiveId?BasicAuthToOAuthConversion=true` works fine with both an OAuth token as well as username/password auth.
* Connecting via username/password basic auth instead of a token redirects fine with or without the query parameters, and includes the query parameters in the redirect.
* At a network level, the error occurs before the connection to the redirected URL is ever attempted. The expected warning does not show up either.
* Capturing the HTTP packet sent by New-PSSession and sending it manually shows that the 
ps.compliance.protection.outlook.com server correctly responds with the redirect. mitmproxy shows the HTTP response was correctly received as well. I'm not sure why the error claims that "Basic Authorization failed" though.

Perhaps the header is too large and that messes up the redirect logic somehow? The Authorization header is "Basic ...<2300 characters here>..." when an OAuth token is used.

Environment data
----------------

Tested with the latest nightly build for Linux

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.10729
PSEdition                      Core
GitCommitId                    6.1.0-preview.10729
OS                             Linux 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@vinodc Could you please test on Windows system?

**Comment by vinodc** [comment]
@iSazonov This does work fine on the PowerShell that comes with Windows Server 2016, but I haven't had a chance to test with the specific version I used on Linux. Is that necessary for this issue to be resolved?

**Comment by iSazonov** [comment]
@vinodc It could help to understand that the Issue is Linux only or not.

**Comment by vinodc** [comment]
@iSazonov We've confirmed this works fine on Windows, so it appears to be a Linux issue.

**Comment by SteveL-MSFT** [comment]
cc @dantraMSFT

**Comment by BellaLi** [comment]
We hit the same issue. Here are the request and response on Linux. After receiving 302, no further request was sent out.

Request:
<s:Header><a:To>HTTPS://ps.compliance.protection.outlook.com:443/PowerShell-LiveId?BasicAuthToOAuthConversion=true;PSVersion=6.1.0</a:To>…
Response:
<s:Envelope xml:lang="en-US" xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" xmlns:p="http://schemas.microsoft.com/wbem/wsman/1/wsman.xsd"><s:Header><a:Action>http://schemas.xmlsoap.org/ws/2004/09/transfer/DeleteResponse</a:Action><a:MessageID>uuid:13AC019D-CD80-4C3F-9563-89A18946C2C1</a:MessageID><p:ActivityId>F8FBAC6E-B1B0-0010-8986-6C70A64DD401</p:ActivityId><a:To>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:To><a:RelatesTo>uuid:230BC4FC-763D-0005-0000-000000BF0000</a:RelatesTo></s:Header><s:Body></s:Body></s:Envelope>
<s:Envelope xml:lang="en-US" xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" xmlns:p="http://schemas.microsoft.com/wbem/wsman/1/wsman.xsd"><s:Header><a:Action>http://schemas.xmlsoap.org/ws/2004/09/transfer/DeleteResponse</a:Action><a:MessageID>uuid:13AC019D-CD80-4C3F-9563-89A18946C2C1</a:MessageID><p:ActivityId>F8FBAC6E-B1B0-0010-8986-6C70A64DD401</p:ActivityId><a:To>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:To><a:RelatesTo>uuid:230BC4FC-763D-0005-0000-000000BF0000</a:RelatesTo></s:Header><s:Body></s:Body></s:Envelope>
[Session: 4 Date: 2018-09-19 18:26:24.0547291Z]
HTTP/1.1 302 Found
Location: https://nam02b.ps.compliance.protection.outlook.com/PowerShell-LiveId?BasicAuthToOAuthConversion=true;PSVersion=6.1.0
Server: Microsoft-IIS/8.0
request-id: 944f34bf-832b-48e8-a1a8-33574cce62f3
X-Powered-By: ASP.NET
X-DiagInfo: BL2FFO11WS085
Date: Wed, 19 Sep 2018 18:26:24 GMT
Content-Length: 234

<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="https://nam02b.ps.compliance.protection.outlook.com/PowerShell-LiveId?BasicAuthToOAuthConversion=true;PSVersion=6.1.0">here</a>.</h2>
</body></html>

**Comment by SteveL-MSFT** [comment]
cc @PaulHigin

**Comment by IT-Gremlin** [comment]
> Right. We've currently implemented a workaround to make the initial request and capture the 302 `Location` header, then redo the connection to that URI instead. Would still be great to have it auto-resolve redirects at some point in time.

How? I have the same problem.

**Comment by yevhenvasylyev** [comment]
Hi Guys,

Do you have any news about when it could be fixed ?

**Comment by PaulHigin** [comment]
/cc @SteveL-MSFT 
AFAIK WinRM/OMI bridge is deprecated and we are no longer supporting it.

**Comment by toupeiro** [comment]
This is a bit of a pickle if WinRM/OMI bride is deprecated yet there is claimed support in ExchangeOnlineManageme for linux in 2.0.5+.  The requirement to use WinRM is due to the nature of the workflow established when connect-ippssession is invoked.  I would LOVE not to use it, or its wsman equivalent in linux.  So, is this an issue with Powershell Core or the Microsoft Security and Protection folks, because its a pretty big deal in my organization, and I would love to get it solved and am willing to test and work with anyone in MSFT on it.

**Comment by navgupta1208** [comment]
Hey

Can you drop an email to ***@***.*** so that I can add you to the preview ?

**Comment by toupeiro** [comment]
> Hey Can you drop an email to ***@***.*** so that I can add you to the preview ? From: toupeiro ***@***.***> Sent: Wednesday, September 1, 2021 6:37 PM To: PowerShell/PowerShell ***@***.***> Cc: Navin Gupta ***@***.***>; Manual ***@***.***> Subject: Re: [PowerShell/PowerShell] New-PSSession does not connect to a redirected URI when larger token-based authorization headers are provided (#7567) This is a bit of a pickle if WinRM/OMI bride is deprecated yet there is claimed support in ExchangeOnlineManageme for linux in 2.0.5+. The requirement to use WinRM is due to the nature of the workflow established when connect-ippssession is invoked. I would LOVE not to use it, or its wsman equivalent in linux. So, is this an issue with Powershell Core or the Microsoft Security and Protection folks, because its a pretty big deal in my organization, and I would love to get it solved and am willing to test and work with anyone in MSFT on it. - You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPowerShell%2FPowerShell%2Fissues%2F7567%23issuecomment-910266718&data=04%7C01%7CNavin.Gupta%40microsoft.com%7C21429fbbb16e495e2fbe08d96d495a56%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637660984127337506%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OlOaAWDZZ3YGezw4rKEUEczFAf9rnzpf%2FGYRII7%2Fjhk%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMFUVNM4DRW7AKUAEHFW72TT7YQONANCNFSM4FQLJ55Q&data=04%7C01%7CNavin.Gupta%40microsoft.com%7C21429fbbb16e495e2fbe08d96d495a56%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637660984127347496%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IcvChI%2BmY4fI1%2FZ25liaYYH1lQAZjpmwajixCT7NN3w%3D&reserved=0>. Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CNavin.Gupta%40microsoft.com%7C21429fbbb16e495e2fbe08d96d495a56%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637660984127357492%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5axBuUUFlXgrK32%2BAPKd1qASUoroyGFkV0XiiHZQhFk%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CNavin.Gupta%40microsoft.com%7C21429fbbb16e495e2fbe08d96d495a56%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637660984127357492%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8Q9pP2H474DzAIUlsSwQz1RypnWqZy3s0rfWsHQOFXI%3D&reserved=0>.

I'd love to but unfortunately the address was redacted. :(

**Comment by SteveL-MSFT** [comment]
Can someone who repros this confirm if https://www.powershellgallery.com/packages/PSWSMan resolves this problem?  cc @jborean93

**Comment by jborean93** [comment]
I think it may still be a problem and not fixed even in my fork. I've yet to try and reproduce it myself but https://github.com/jborean93/omi/issues/36#issuecomment-907889875 seems like a similar problem.

**Comment by n3tl0kr** [comment]
Hey everyone, its 2022 and I'm still seeing a similar error on macOS where this redirect is not happening and a basic auth failure is returned. Can anyone confirm that this is still an active issue?

```
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Darwin 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Error**
```
VERBOSE: ExchangeEnvironment : O365Default
VERBOSE: ConnectionUri : https://ps.compliance.protection.outlook.com/PowerShell-LiveId
VERBOSE: AzureADAuthorizationEndpointUri : https://login.microsoftonline.com/organizations
VERBOSE: DelegatedOrganization :
VERBOSE: Prefix :
VERBOSE: FormatTypeName :*
VERBOSE: CommandName :*
VERBOSE: Importing cmdlet 'Add-EXOClientTelemetryWrapper'.
VERBOSE: Importing cmdlet 'New-EXOClientTelemetryFilepath'.
VERBOSE: Importing cmdlet 'Push-EXOTelemetryRecord'.
VERBOSE: Importing cmdlet 'Clear-ActiveToken'.
VERBOSE: Importing cmdlet 'New-ExoPSSession'.
VERBOSE: Importing cmdlet 'Test-ActiveToken'.
Exception: Connecting to remote server ps.compliance.protection.outlook.com failed with the following error message : Basic Authorization failed for user
**********@contoso.com For more information, see the about_Remote_Troubleshooting Help topic.
```

**Comment by Parkhost** [comment]
What the, is this MS, claiming to support Powershell EO management module on Linux but the dependencies are broke or deprecated and not supported..? Guess am back on the Windows host again... /sigh

**Comment by freakynl** [comment]
Same issue. Can this be resolved?

PS /tmp> Connect-IPPSSession
Exception: Connecting to remote server ps.compliance.protection.outlook.com failed with the following error message : Basic Authorization failed for user XXX@domain.tld For more information, see the about_Remote_Troubleshooting Help topic.

**Comment by freakynl** [comment]
Seemingly running into this on setting authenticationpolicies now too.

Have done this on linux many times before without issues.

PS /home/freaky> get-user | Set-User -AuthenticationPolicy ALLOW-BasicAuth-SMTP
OperationStopped: Sending data to a remote command failed with the following error message: Basic Authorization failed for user xxx@yyy.zzz For more information, see the about_Remote_Troubleshooting Help topic.
