### ISSUE TITLE
New-PSSession Fails Ubuntu to Windows using .NET Core Packages

### ISSUE THREAD

**Issue by danielman111** [PowerShell/PowerShell#7571]
I am trying to invoke a command using a Session created from Ubuntu to Windows
I am using Ubuntu 16.04, I wrote a project using .NET Core, and installed the following nuget packages:

```
System.Management.Automation 6.02
Microsoft.WSMan.Management 6.02
Microsoft.PowerShell.SDK 6.02
Microsoft.PowerShell.Commands.Management 6.02
Microsoft.Management.Infrastructure 1.00
```

Using the following code:

```
Runspace runspace = RunspaceFactory.CreateRunspace();
runspace.Open();
Pipeline pipeline = runspace.CreatePipeline();

pipeline.Commands.AddScript("$secpasswd = ConvertTo-SecureString \"MyPassowrd\" -AsPlainText -Force");
pipeline.Commands.AddScript("$mycreds = New-Object System.Management.Automation.PSCredential (\"admin\", $secpasswd)");
pipeline.Commands.AddScript("$session = New-PSSession -ComputerName 10.81.4.4 -port 5985 -Credential $mycreds -Authentication Negotiate");
pipeline.Commands.AddScript("Invoke-Command -Session $session -ScriptBlock {get-service}");
var resPipe = pipeline.Invoke();

```

I get this error:

`Exception :The method or operation is not implemented. The method or operation is not implemented. at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)\n at System.Management.Automation.Runspaces.Pipeline.Invoke()
`

The thing is, that if I use powershell 6.0 in my Ubuntu, and trying to get session using the commands above, It works, but when using .NET Core, I am getting an error,
Anyone knows why?

**Comment by iSazonov** [comment]
@danielman111  Please test with latest PowerShell Core version Preview4.

**Comment by danielman111** [comment]
Eventually I used the following code to run my set of commands:

```
public static string RunCommand(string cmd)
{

        var base64EncodedString = Convert.ToBase64String(ASCIIEncoding.Unicode.GetBytes(cmd));

        var process = new Process()
        {
            StartInfo = new ProcessStartInfo
            {
                FileName = "pwsh",
                Arguments = $"-encodedcommand \"{base64EncodedString}\"",
                RedirectStandardOutput = true,
                UseShellExecute = false,
                CreateNoWindow = true,
            }
        };
        process.Start();
        string result = process.StandardOutput.ReadToEnd();
        process.WaitForExit();
        return result;
}
```
Where the cmd param is concatenation of all my commands with ; separator.

For windows to windows remoting, the filename should be:
`FileName = @"C:\Program Files\PowerShell\6.0.4\pwsh.exe",`

**Comment by iSazonov** [comment]
The path is changed in 6.1.0.
