### ISSUE TITLE
Crash in Microsoft.PowerShell.TaskbarJumpList.CreateElevatedEntry(System.String)

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShell#7572]
I have an intermittent crash in 
```
 Microsoft.PowerShell.TaskbarJumpList.CreateElevatedEntry(System.String)
```

on process startup. 
```
0:009> !pe
Exception object: 000002a22d6b11f8
Exception type:   System.ExecutionEngineException
Message:          <none>
InnerException:   <none>
StackTrace (generated):
<none>
StackTraceString: <none>
HResult: 80131506
```

With symbols available, it had been a lot easier to provide better debug info.

```
0:009> !clrstack
OS Thread Id: 0x5f3c (9)
        Child SP               IP Call Site
000000b2b7d7ebb0 00007ffbc04100f4 [GCFrame: 000000b2b7d7ebb0] 
000000b2b7d7ed20 00007ffbc04100f4 [GCFrame: 000000b2b7d7ed20] 
000000b2b7d7ee48 00007ffbc04100f4 [HelperMethodFrame_1OBJ: 000000b2b7d7ee48] 
000000b2b7d7ef80 00007ffb305bf033 Microsoft.PowerShell.TaskbarJumpList.CreateElevatedEntry(System.String)
000000b2b7d7f0f0 00007ffb305c18a4 Microsoft.PowerShell.ConsoleHost+<>c.<Start>b__4_0()
000000b2b7d7f120 00007ffb2a84cb49 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [E:\A\_work\31\s\src\mscorlib\shared\System\Threading\ExecutionContext.cs @ 167]
000000b2b7d7f1a0 00007ffb2a8ff517 System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef) [E:\A\_work\31\s\src\mscorlib\src\System\Threading\Tasks\Task.cs @ 2440]
000000b2b7d7f240 00007ffb2a9366bc System.Threading.ThreadPoolWorkQueue.Dispatch() [E:\A\_work\31\s\src\mscorlib\src\System\Threading\ThreadPool.cs @ 588]
000000b2b7d7f690 00007ffb2d071573 [DebuggerU2MCatchHandlerFrame: 000000b2b7d7f690] 
```

----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.4
PSEdition                      Core
GitCommitId                    6.1.0-preview.4
```
~~OS                             Microsoft Windows 10.0.17134~~
```
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

@bergmeister Is this something you recognize?

**Comment by powercode** [comment]
`ExecutionEngineException` usually mean that we have messed up unmanaged memory somehow.

**Comment by powercode** [comment]
In TaskbarJumpList.cs

![image](https://user-images.githubusercontent.com/3505151/44340408-0e296680-a485-11e8-87fa-485a555b3131.png)

**Comment by bergmeister** [comment]
@powercode Yes, but I have never seen a problem despite using/testing it on multiple OSs, which version of Windows are you using exactly? This code creates the Jumplist entry in the taskbar and was added in PR #6985 by converting unmanaged C++ code from the  unmanaged Windows PowerShell ConsoleHost to partially managed C# code in the managed PowerShell Core ConsoleHoist
Can you retry to build and repro locally:
```powershell
Import-Module .\build.psm1
Start-PSBootStrap
Start-PSBuild
Invoke-Item "$pwd/src\powershell-win-core\bin\Debug\netcoreapp2.1\win7-x64\publish\pwsh.exe"
```

**Comment by bergmeister** [comment]
@powercode Sorry, I saw your screenshot only now

**Comment by powercode** [comment]
@bergmeister After some investigations, it seems I actually only have machines with 1709 that manifest the problem. I updated the version info in the original description.

**Comment by powercode** [comment]
Don't we have to call CoInitialize on the task thread?

**Comment by powercode** [comment]
I cannot reproduce the problem when I run without the Task, and neither with a debug build.

**Comment by powercode** [comment]
In ComInterfaces.cs, we have 
```
[DllImport("kernel32.dll", SetLastError = true, EntryPoint = "GetStartupInfoA")]
        internal static extern void GetStartupInfo(out StartUpInfo lpStartupInfo);
```
but 
```
[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
        internal struct StartUpInfo
```

So we pass the Unicode struct to the ansi function.

**Comment by powercode** [comment]
And we never set the size of the cb member of `StartUpInfo`. I had expected that to be set before the call to `GetStartUpInfo`, that I would have expected to have a `ref`, not `out` parameter.

**Comment by powercode** [comment]
Could lead to strange marshalling behavior for our strings.

**Comment by bergmeister** [comment]
@powercode Does it repro when you compile using `-Configuration Release` and/or `-CrossGen`? The COM code that you referenced is from the WindowsCompatibiltyPack. We could check what the code in the WPF workspace looks like by decompiling it, maybe we can improve it. We could also look for the documentation of the Windows API in question to figure out an improved COM interface

**Comment by SteveL-MSFT** [comment]
@powercode the discrepancy between `GetStartupInfo` calling the Ansi version of the API and the `StartUpInfo` struct being Unicode seems suspect and wrong.  By chance are you using a language on your machine other than English?

**Comment by powercode** [comment]
It not my machine - I see it out in the wild. Have to check tomorrow if it was a Swedish locale, but I don't think it was.

**Comment by powercode** [comment]
I suggest using IntPtr instead of the strings. We don't need them anyway.

**Comment by powercode** [comment]
@bergmeister Yes, I reprod on crossgen:ed. Could not repro on debug. Maybe the marshaller works different in debug? 
@SteveL-MSFT We could you IntPtr for the strings. That would make the struct blittable, with a much simpler marshaller. And we don't use them anyway.

**Comment by powercode** [comment]
I haven't been able to reproduce the crash with the marshalling changes in #7580.

**Comment by bergmeister** [comment]
@powercode  My fix for this issue has been back-ported to the recent release of `6.2.2`, please update and provide feedback if it fixed it. If you use the preview you will have to wait for `7.0.0-preview.2` or use the daily build instead (or build from `master`)
https://github.com/PowerShell/PowerShell/releases/tag/v6.2.2
