### ISSUE TITLE
Why do we have *-ExecutionPolicy cmdlets on Linux?

### ISSUE THREAD

**Issue by alexandair** [PowerShell/PowerShell#7573]
Why do we have Get-ExecutionPolicy and Set-Executionpolicy on Linux when running Set-ExecutionPolicy returns:

```
Set-ExecutionPolicy : Operation is not supported on this platform.
````

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.4
PSEdition                      Core
GitCommitId                    6.1.0-preview.4
OS                             Linux 4.4.0-17134-
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
I belive https://github.com/PowerShell/PowerShell/issues/1998 will address the Issue.

**Comment by alexandair** [comment]
@iSazonov 
Sure, that will address it.
The only problem is that that issue is 2 years old (posted 3 days after PowerShell Core was announced) and nothing happened. 2 years.

**Comment by iSazonov** [comment]
Because we hope to port all cmdlets :-) You can vote in  #1998.

**Comment by iSazonov** [comment]
@alexandair The problem is not rejected - it is tracked in #1998. The solution is already known too. The only thing left to do is implement it.

**Comment by alexandair** [comment]
Let me put it differently.

I don't really care if this issue is open or closed. But, I care that we have something  exposed in Linux that is just not valid in the currently available versions, both stable and preview.
If it's not relevant it **should be removed**.
When the time and resources allow, it can be implemented. Having an issue posted more than two years ago to track it doesn't improve the user experience.

Get-ExecutionPolicy, Set-ExecutionPolicy, and pwsh's -ExecutionPolicy should be removed from Linux releases.

**Comment by iSazonov** [comment]
@alexandair We all completely agree with this. Please move your comment in #1998 to increase a priority the issue. 
Also you can discuss the Issue on next monthly community call. Over the past year, we have done a lot of code and docs cleanups. The discussion can help us to prioritize further work.
