### ISSUE TITLE
Python REPL over winrm

### ISSUE THREAD

**Issue by copdips** [PowerShell/PowerShell#7581]
Hello, 

Python is more and more used by windows admins, is it possible to support Python REPL over winrm session ? 
Thx.

Steps to reproduce
------------------

```powershell
# pre-install python on server1
enter-pssession server1
python
```

Expected behavior
-----------------

```python
# the python >>> prompt appears instead of the powershell one
>>>
```

Actual behavior
---------------

```none

```

Environment data
----------------

```powershell
# all ps versions
```

**Comment by MaximoTrinidad** [comment]
Not only over winrm but also ssh.  

As of now, you can't directly execute python (not even VIM) remotely.  This maybe **By-Design**!

![sshpython_03_2018-08-21_9-26-59](https://user-images.githubusercontent.com/19892435/44405581-9b24fc00-a527-11e8-8d3b-714645978afb.jpg)

Now, what it can be done from PowerShell remotely, you can execute and collect/save the results from Python with PowerShell.  The following command line works:

```
$result = python -c $RunPythonCode;
:
```

![sshpython_02_2018-08-21_9-26-59](https://user-images.githubusercontent.com/19892435/44405612-aaa44500-a527-11e8-8c58-e3ec626f8cf7.jpg)

![sshpython_01_2018-08-21_9-26-59](https://user-images.githubusercontent.com/19892435/44405629-b5f77080-a527-11e8-9ee3-6552f13844c8.jpg)

![sshpython_04_2018-08-21_9-26-59](https://user-images.githubusercontent.com/19892435/44405923-71b8a000-a528-11e8-8ea1-2d33a7ef1d94.jpg)

I see the benefit of using python remotely as well as other tools.  
It would be a good feature to add!

**Comment by copdips** [comment]
@MaximoTrinidad 

Thx for your reply, but Python repl works well over ssh, that's why I asked for Powershell winrm.
Currently, when I need to do some Python tests on a windows server, I must connect to RDP.

**Comment by MaximoTrinidad** [comment]
@copdips 

Oh Yes!! I was trying to state the with PowerShell Core ssh is not when using the *-PSSession cmdlets.  I know with ssh works as expected.

```
## - When using OpenSsh:
Enter-PSSession -HostName kronos -UserName maxt 
```
:)

**Comment by copdips** [comment]
cool :)

**Comment by chuanjiao10** [comment]
Iet **the python standard library** in the form of a **powershell third-party module**. I think it is better.
```powershell
enter-pssession server1
import module python.re
$a = re.xxx() 
```

**Comment by copdips** [comment]
@chuanjiao10 

`import-module python.re`, are you sure this works ? 
Or this is what you expect in the future powershell release ?

**Comment by copdips** [comment]
Could anyone tells us why it doesn't work at least ?

**Comment by MaximoTrinidad** [comment]
For now, forget about python.re module.  The main issue in question is about Python REPL in PS Remoting.  I think it should work in both ssh and winrm.

I would recommend, to pursue python.re, someone should open a separate issue.
:)

**Comment by chuanjiao10** [comment]
Forget repl. The main problem with python is that it does not support the command line. Remote command line is not supported. It is difficult to transform the structure.

Powershell is born with a command line, which is a remote command line.

Compiling and creating the python standard library source code into a powershell module is the best way. Maybe you don't need to compile the source code, you only need to make the namespace interface and the import interface. This is very simple, there is no need to modify the python architecture to accommodate the command line.

Learning python standard library is to learn python.

If you do this, you can let more people use python. You can also extend python.



Copdips :
There is no such library for now.

**Comment by chuanjiao10** [comment]
@copdips ：
If you like the number of game frames is too low,
Will you modify the game, or the game engine, or directX, or opengl? Or graphics card driver?

If python's http performance is poor, would you modify tcp to adapt to python?

Python is an application. You should modify python to adapt to powershell and bash, not vice versa.

If the powershell console is modified for python,
So should it also be modified for java?
Should it also be modified for nodejs?

**Comment by copdips** [comment]
hello Powershell team,

Could you please take a look, I don't need to implement the feature, I would like to know why it doesn't work. 

Not only Python REPL doesn't work over PS remote, many other widely used command line tools work well locally, but not over PS remote. Or sometime, it works but their outputs are shown in red, which seems to be considered as an error message.

**Comment by iSazonov** [comment]
My understanding is that PowerShell remoting is actually a link between two PowerShell engines made using serialization and local PowerShell has to process _all_ IO to/from remote one - it has no way to determine what it should handle itself, and (1)  what to pass on the local console from remote and (2) what send from local console to remote. We'd can to "turn off" PowerShell Engine after running interactive application remotely but in the case it would be easier to simply create a second connection like an interactive ssh session.

**Comment by copdips** [comment]
yes, I tried to install a ssh server on windows server, it works fine with vim and python repl.
But I encounter some display issue over SSH, after some typing and some copy/past, the cursor is drifted from the prompt.

sth like:
```powershell
ps prompt here>



               | （<-cursor here)
```

I followed the [official installation procedure](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH).

**Comment by copdips** [comment]
And it's not easy to let the CTO in a big company to make the decision today to deploy the SSH to all the windows servers. 
We need to wait for a while (maybe years) to witness SSH server works really very fine on Windows.

**Comment by iSazonov** [comment]
@copdips Feel free to report issues in https://github.com/PowerShell/Win32-OpenSSH

**Comment by copdips** [comment]
Got response from #7894
