### ISSUE TITLE
Preview.4 - During ssh session Linux-to-Windows Clear-Host not clearing screen 

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#7583]
Steps to reproduce
------------------
1. Connect ssh from Linux to Windows.  
2. Run code to populate the screen.
3. Then, use Clear-Host.

The screen content stays the cursor return to the top.

Expected behavior
-----------------
To clear the screen when returning to the top screen.

```none

```

Actual behavior
---------------
Executing the Clear-Host cmdlet, doesn't clear the screen. it give the message:
"Method or Operation is not implemented"

```none

```

Environment data
----------------

From Linux:
```powershell
PS /home/maxt> cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

PS /home/maxt> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.4
PSEdition                      Core
GitCommitId                    6.1.0-preview.4
OS                             Linux 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
To Windows:
```
PS C:\Users\max_t> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.4
PSEdition                      Core
GitCommitId                    6.1.0-preview.4
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
![sshcls_01_2018-08-21_9-26-59](https://user-images.githubusercontent.com/19892435/44410412-518dde80-a532-11e8-990a-5e56800cf9b2.jpg)

![sshcls_02_2018-08-21_9-26-59](https://user-images.githubusercontent.com/19892435/44410432-5b174680-a532-11e8-83c9-6c69785d23f9.jpg)

**Comment by MaximoTrinidad** [comment]
Hum! I think there's a workaround manually executing a command to manually fix this issue.

I thought it was already handle by the PSSession. :)

**Comment by thezim** [comment]
Does Clear-Host rely on the console API directly? If so those API calls don't work on remote sessions if I recall.

**Comment by iSazonov** [comment]
I think it is dup #7584 .

**Comment by MaximoTrinidad** [comment]
Hi @iSazonov 

Windows not equal Linux.   Different behavior! 

In Linux it doesn't clear the screen nor return to the top of the screen.
In Windows, it doesn't clear the screen but the cursor goes to the top of the screen.

:)
