### ISSUE TITLE
Variable defined in InitialSessionState is not available in scriptblock originating from another runspace

### ISSUE THREAD

**Issue by alx9r** [PowerShell/PowerShell#7593]
This came up when experimenting with @lzybkr's workaround for #7530.  In short, I'm using the ScriptBlock (not just its string representation) from one runspace in another so that file position information is correctly reported when an error is encountered.

Steps to reproduce
------------------

```powershell
$scriptblock = {
    "a in dot-invoked scriptblock: $a"
}

$powershell = [powershell]::Create().
    AddScript({
        "a in outer scriptblock: $a"
        . $args[0]
    }).
    AddArgument($scriptblock)

$initialSessionState = [initialsessionstate]::CreateDefault()
$initialSessionState.Variables.Add(
    [System.Management.Automation.Runspaces.SessionStateVariableEntry]::new(
        'a',
        1,
        ''
    )    
)
$runspace = [runspacefactory]::CreateRunspace($initialSessionState)
$runspace.Open()

$powershell.Runspace = $runspace
$powershell.Invoke()
```

Expected behavior
-----------------

```none
a in outer scriptblock: 1
a in dot-invoked scriptblock: 1
```

Actual behavior
---------------

```none
a in outer scriptblock: 1
a in dot-invoked scriptblock:
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.4
PSEdition                      Core
GitCommitId                    6.1.0-preview.4
OS                             Microsoft Windows 6.3.9600 
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by lzybkr** [comment]
@BrucePay - that's mostly right, but scriptblocks created via `[ScriptBlock]::Create` are not bound to a runspace until they are first invoked.

**Comment by BrucePay** [comment]
@lzybkr Right but then you lose all of the source context which was the whole point of the exercise. Now If we made the overload of `[scriptblock]::Create()` that takes an AST public, then everything should work.

**Comment by lzybkr** [comment]
The binding to the runspace happens [here](https://github.com/PowerShell/PowerShell/blob/d6817a42e4b75c915d9ccc3772172a4a63395d1a/src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs#L1254) - and you can see it is not part of `ScriptBlock.Create`, though that line could maybe be moved into `ScriptBlock.Create`.
