### ISSUE TITLE
New-PSSession on Linux to office365.com fails on Debian 9 due to missing symlinks for libssl and libcrypto

### ISSUE THREAD

**Issue by dantraMSFT** [PowerShell/PowerShell#7598]
Client PSRP for Linux fails on a clean Debian 9 install of PowerShell due to the inability of libmi to resolve libssl and libcrypto.  While this worked as-is on Debian 8, Debian 9 fails unless symlinks for these two libraries are created in the $PSHOME directory.

To work around the problem, create the following symlinks in the PSHOME directory. Verify the version of ssl and crypto that are installed and adjust the references accordlingly.

```bash
sudo ln -s /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2 libssl.so.1.0.0
sudo ln -s /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2 libcrypto.so.1.0.0
```

Steps to reproduce
------------------

```powershell
$uri = 'https://outlook.office365.com/powershell-liveid'
$cred = Get-Credential
$session = New-PSSession -ConnectionUri $uri  -ConfigurationName Microsoft.Exchange -Credential $cred -Authentication Basic -AllowRedirection
```

Expected behavior
-----------------
The connection succeeds.

Actual behavior
---------------
The following error is reported:

This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system.

**Comment by rfoust** [comment]
fwiw, I just ran into this as well on Debian 9, and pwsh 6.1.2 and 6.2.0.preview3. Creating the symlinks resolved the issue for me.

**Comment by midacts** [comment]
I ran this on Debian 10 : `7.0.0-preview.6-debian-10` and it did **NOT** work.

**Comment by TravisEz13** [comment]
@midacts Please file a new issue with repro details including installation steps.
