### ISSUE TITLE
Parameter binding stops when a transformation attribute throws a ArgumentTransformationMetadataException

### ISSUE THREAD

**Issue by jazzdelightsme** [PowerShell/PowerShell#7600]
`ArgumentTransformationMetadataException` is supposed to represent a recoverable error, but PS does not recover.

You can use an [`ArgumentTransformationAttribute`](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.argumenttransformationattribute?view=powershellsdk-1.1.0) to help massage an object into the type expected for a particular command parameter. If the transformation fails, the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.argumenttransformationattribute.transform?view=powershellsdk-1.1.0#System_Management_Automation_ArgumentTransformationAttribute_Transform_System_Management_Automation_EngineIntrinsics_System_Object_) say to "throw ArgumentException if the value of inputData is invalid, and throw ArgumentTransformationMetadataException for other recoverable errors".

However, if you throw an `ArgumentTransformationMetadataException` to indicate a recoverable error, PS does not recover--binding is halted. So if, for example, you have a parameter that can be bound by name to pipeline input (`ValueFromPipelineByPropertyName = $true`), then piping in an object with a property with the right name will not work, because the transformation will first be attempted on the object that was piped in (which will fail, as expected), and then it won't continue to look for a property on that object with the expected name.

Steps to reproduce
------------------

```powershell

Add-Type -TypeDefinition @'
namespace Repro
{
    using System;
    using System.Management.Automation;
    using System.Reflection;

    /// <summary>
    ///    Useful to transform a string representation of a timezone ("Pacific Standard
    ///    Time") into an actual TimeZoneInfo object.
    /// </summary>
    [AttributeUsage( AttributeTargets.Property | AttributeTargets.Field, AllowMultiple = false )]
    public class TimeZoneTransformationAttribute : ArgumentTransformationAttribute
    {
        /// <summary>
        ///    Set this (or the other UseWorkaround_ property) to 'true' if you want the
        ///    PS runtime to be able to try other binding options (such as binding to a
        ///    pipeline value by property name).
        ///
        ///    If left as the default (false), it means the attribute will throw an
        ///    exception if it can't convert the object; else it will return the original
        ///    object for further binding.
        /// </summary>
        public bool UseWorkaround_FailGracefully { get; set; }


        /// <summary>
        ///    Set this (or the other UseWorkaround_ property) to 'true' if you want the
        ///    PS runtime to be able to try other binding options (such as binding to a
        ///    pipeline value by property name).
        ///
        ///    If left as the default (false), it means that the inner exception of the
        ///    exception that the attribute will throw if it can't convert the object will
        ///    NOT be a PSInvalidCastException.
        /// </summary>
        public bool UseWorkaround_WrapPSInvalidCastException { get; set; }


        public override object Transform( EngineIntrinsics engineIntrinsics, object inputData )
        {
            object originalObject = inputData;

            Console.WriteLine( "===============================================" );
            try
            {
                Console.WriteLine( "Welcome to the TimeZoneTransformationAttribute." );
                Console.WriteLine( "   inputData is null? {0}", inputData == null );
                if( null != inputData )
                {
                    Console.WriteLine( "   inputData type: {0}", inputData.GetType().FullName );
                    Console.WriteLine( "   inputData value: {0}", inputData );
                }

                var pso = inputData as PSObject;
                if( null != pso )
                {
                    Console.WriteLine( "getting baseobject... ({0})", pso.BaseObject.GetType().FullName );
                    inputData = pso.BaseObject;
                }

                if( inputData is TimeZoneInfo )
                {
                    Console.WriteLine( "it's already a tzi" );
                    return inputData;
                }

                string str = inputData as string;
                Exception e = null;
                if( null != str )
                {
                    try
                    {
                        var tzi = TimeZoneInfo.FindSystemTimeZoneById( str );
                        if( null != tzi )
                        {
                            Console.WriteLine( "(successfully transformed inputData: {0})", tzi );
                            return tzi;
                        }
                    }
                    catch( TimeZoneNotFoundException tznfe )
                    {
                        e = tznfe;
                    }
                }
                else
                {
                    Console.WriteLine( "it's not a string" );
                }


                if( UseWorkaround_FailGracefully )
                {
                    Console.WriteLine( "(failing gracefully by just returning the original object)" );
                    return originalObject;
                }

                Console.WriteLine( "(failing by throwing an ArgumentTransformationMetadataException)" );
                Console.WriteLine( "(which is supposed to be \"recoverable\")" );

                // BUG: Documentation indicates that this exception should indicate a
                // recoverable error; however the PS runtime does not recover by
                // continuing to attempt parameter binding once this exception is thrown,
                // UNLESS the inner exception is a PSInvalidCastException.

                throw new ArgumentTransformationMetadataException(
                    String.Format( "Could not convert '{0}' to a timezone.",
                                   inputData ),
                    UseWorkaround_WrapPSInvalidCastException ? new PSInvalidCastException() : e );
            }
            finally
            {
                Console.WriteLine( "-----------------------------------------------" );
            }
        } // end Transform()
    } // end class TimeZoneTransformationAttribute
}
'@


function Repro
{
    [CmdletBinding()]
    param( [Parameter( Mandatory = $true,
                       Position = 0,
                       ValueFromPipeline = $true,
                       ValueFromPipelineByPropertyName = $true )] # <-- BUG: will not work
           [Repro.TimeZoneTransformation()]
           [TimeZoneInfo] $TZI
         )

    process
    {
        Write-Host "$($MyInvocation.InvocationName): `$TZI is: $TZI" -Fore Cyan
    }
}

function NoRepro1
{
    [CmdletBinding()]
    param( [Parameter( Mandatory = $true,
                       Position = 0,
                       ValueFromPipeline = $true,
                       ValueFromPipelineByPropertyName = $true )]
           [Repro.TimeZoneTransformation( UseWorkaround_FailGracefully = $true )]
           [TimeZoneInfo] $TZI
         )

    process
    {
        Write-Host "$($MyInvocation.InvocationName): `$TZI is: $TZI" -Fore Green
    }
}

function NoRepro2
{
    [CmdletBinding()]
    param( [Parameter( Mandatory = $true,
                       Position = 0,
                       ValueFromPipeline = $true,
                       ValueFromPipelineByPropertyName = $true )]
           [Repro.TimeZoneTransformation( UseWorkaround_WrapPSInvalidCastException = $true )]
           [TimeZoneInfo] $TZI
         )

    process
    {
        Write-Host "$($MyInvocation.InvocationName): `$TZI is: $TZI" -Fore Green
    }
}


$customObj = [PSCustomObject] @{ TZI = "Pacific Standard Time" }

$customObj | NoRepro1
$customObj | NoRepro2
$customObj | Repro
```

Expected behavior
-----------------
No errors should be generated by the repro script: the `TZI` parameter should be bound by property name in all cases.

Actual behavior
---------------
Property binding stops (so that binding by property name is not attempted) when an `ArgumentTransformationMetadataException` is thrown, so `$customObj | Repro` generates an error instead of succeeding.

```none
===============================================
Welcome to the TimeZoneTransformationAttribute.
   inputData is null? False
   inputData type: System.Management.Automation.PSObject
   inputData value: @{TZI=Pacific Standard Time}
getting baseobject... (System.Management.Automation.PSCustomObject)
it's not a string
(failing by throwing an ArgumentTransformationMetadataException)
(which is supposed to be "recoverable")
-----------------------------------------------
Repro : Cannot process argument transformation on parameter 'TZI'. Could not convert '' to a timezone.
At C:\temp\TransformationAttrRepro\Repro.ps1:177 char:14
+ $customObj | Repro
+              ~~~~~
+ CategoryInfo          : InvalidData: (@{TZI=Pacific Standard Time}:PSObject) [Repro], ParameterBindingArgumentTransformationException
+ FullyQualifiedErrorId : ParameterArgumentTransformationError,Repro
```

Options to fix this
--------------------
Option 1) When an `ArgumentTransformationMetadataException` is thrown, PS should continue to attempt binding (so that binding by property name can be tried). Currently, if the ATME wraps a `PSInvalidCastException`, then things work as expected. (But how would you know to do that, and why shouldn't it just work for a plain ATME?)

See the code in [CmdletParameterBinderController.cs](https://github.com/PowerShell/PowerShell/blob/5d03e1653a7d518715fa3f00587cad6b5c78cc89/src/System.Management.Automation/engine/CmdletParameterBinderController.cs#L3571).

OR

Option 2) The first option would be a breaking change, but probably in the category of "acceptable" changes ("Any existing behavior that results in an error message generally may be changed to provide new functionality."). However, if for some reason we don't want to do that, the documentation should be updated to instruct how to properly fail a transformation without halting binding. The repro script above demonstrates two different approaches for coaxing parameter binding into continuing.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.4
PSEdition                      Core
GitCommitId                    6.1.0-preview.4
OS                             Microsoft Windows 10.0.17713
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@jazzdelightsme Look `ArgumentToEncodingTransformationAttribute` implementation in the repo.
https://github.com/PowerShell/PowerShell/blob/c1c5344a8897262433141ecbc13bb06ac2c4bbef/src/System.Management.Automation/utils/EncodingUtils.cs#L90

**Comment by jazzdelightsme** [comment]
Sorry @iSazonov , I don't understand the relevance of that transformer. Yes, it also demonstrates the first workaround demonstrated by the repro script (`UseWorkaround_FailGracefully`).

Even if we decide that all the code works exactly as desired, then this is a doc bug, because you can't tell from reading the docs that it's how you should fail (docs incorrectly instruct you to throw an ATME if transformation fails, which will break further binding, which cannot possibly be what the user wanted).

(To be clear, my preferred option is to change PS to treat all ATMEs the same way that ATMEs which wrap PSInvalidExceptions are today. But even if we decide against that, _something_ should be done; this is painful to figure out.)

**Comment by iSazonov** [comment]
@jazzdelightsme Thanks for clarify. I think the code works as expected and it is doc issue - we should add that we should throw `ArgumentTransformationMetadataException` with inner `PSInvalidCastException` exception. (Sample code in `ArgumentTypeConverterAttribute`). Please open new issue in PowerShell-Docs repo if you agree.

**Comment by joshooaj** [comment]
Hi @jazzdelightsme, I just wanted to say thank you for reporting this issue 7 years ago - it helped me today! https://bsky.app/profile/joshooaj.com/post/3lqkw4gvs5k2m

<blockquote><img src="https://cdn.bsky.app/img/feed_thumbnail/plain/did:plc:a3yierchgwp2lvyontsragui/bafkreicdzsgnrrnpdhnt5i5445gxlhq5ejx4t5jkugwyltqw4sba5sxmqi@jpeg" width="48" align="right"><div><img src="https://web-cdn.bsky.app/static/favicon-16x16.png" height="14"> Bluesky Social</div><div><strong><a href="https://bsky.app/profile/joshooaj.com/post/3lqkw4gvs5k2m">Josh Hendricks | MVP (@joshooaj.com)</a></strong></div><div>I love #powershell argument transformation attributes and was adding more of them to my module but ran into an issue with them and I'm not sure if there's a way to avoid this problem.

(HINT: There is! 🎉)</div></blockquote>
