### ISSUE TITLE
Module autoloading does not invoke correct command on first use

### ISSUE THREAD

**Issue by PetSerAl** [PowerShell/PowerShell#7612]
Steps to reproduce
------------------

Having module with following definition:
```powershell
function Get-SomeName { 'Get-SomeName' }
function SomeName { 'SomeName' }
```

Invoke following in PowerShell prompt:
```powershell
SomeName; SomeName
```

Expected behavior
-----------------

```none
SomeName
SomeName
```

Actual behavior
---------------

```none
Get-SomeName
SomeName
```

Environment data
----------------

```
Name                           Value
----                           -----
PSVersion                      6.1.0-rc.1
PSEdition                      Core
GitCommitId                    6.1.0-rc.1-7-g7b790f2f618c37d46518d2c4c95c4e47c46c6924
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Looks like "By-Design" - we search in a cache before start autoloading.

**Comment by PetSerAl** [comment]
@iSazonov Not sure how this is related to cache. As far as I understand command lookup algorithm looks like following:
```
LookForCommand(string name) {
    LookForAlreadyLoadedCommand(name);
    if(name is single world) {
        LookForCommand("Get-" + name);
    }
    AutoloadCommand(name);
}
```
So, due to recursive call to `LookForCommand("Get-" + name)` it happens that ` AutoloadCommand("Get-" + name)` is called before `AutoloadCommand(name)` which cause the issue.

**Comment by iSazonov** [comment]
I meant the same. I think it is an edge case and we can consider this as "By-Design".
