### ISSUE TITLE
The link to download PSCore v6.1.0-rc.1 for Red Hat family included in the README.md is broken

### ISSUE THREAD

**Issue by it-praktyk** [PowerShell/PowerShell#7613]
The [README.md](https://github.com/PowerShell/PowerShell/blob/master/README.md) at the line 86 contains

```powershell
[pv-centos]: https://github.com/PowerShell/PowerShell/releases/download/v6.1.0-rc.1/powershell-preview-6.1.0-rc.1-1.rhel.7.x86_64.rpm
```

That link is incorrect - it returns the 404 page.

The link to download the rpm file at [the release page](https://github.com/PowerShell/PowerShell/releases/tag/v6.1.0-rc.1) is working and is

```powershell
https://github.com/PowerShell/PowerShell/releases/download/v6.1.0-rc.1/powershell-preview-6.1.0.rc.1-1.rhel.7.x86_64.rpm
```

The issue is the dot/dash before the `rc` name part.

**Comment by iSazonov** [comment]
@it-praktyk Thanks for your report! All links on deb and rpm is broken.
