### ISSUE TITLE
Update to community dashboard to show 6.1 development cycle?

### ISSUE THREAD

**Issue by mi-hol** [PowerShell/PowerShell#7616]
I like the dashboard https://github.com/PowerShell/PowerShell#community-dashboard
but several pages seem to require an update, as data refreshes stoppend some time back.
Specifically page 5 should show stats from 6.1 development cycle.

**Comment by chuanjiao10** [comment]
The same dashboard problem. 
1 Is it possible to count linux data by release version instead of by kernel?
2 Can the powershell version data follow the "version percentage" instead of the column chart.

**Comment by SteveL-MSFT** [comment]
@mi-hol  I'll update the dashboard to reflect current development.  I think I'll just leave it as 6.x so I don't have to keep updating it for each new release.

@chuanjiao10 we only get what is returned by [System.Runtime.InteropServices.RuntimeInformation]::OSDescription which gives the kernel information and not the distro information.  If someone can point me to a mapping between what `uname` returns and the distro/version I can see about reporting that.  I can add a pie chart for the pwsh version.

**Comment by SteveL-MSFT** [comment]
I've updated section 5 to not be focused on 6.0.0 release.  Instead, it should automatically show trend for Top 7 milestones (the 6.0.0 should eventually drop off).  Section 7 has new pie chart showing PS version usage.  I'll see about mapping the kernel info to distros, but it probably won't be perfect.

**Comment by SteveL-MSFT** [comment]
Using a simple pattern if OSDescription contains:
  - Darwin == macOS
  - Windows == Windows
  - freebsd == FreeBSD
  - amzn == Amazon Linux
  - el7 = RHEL7
  - debian == Debian
  - ubuntu == Ubuntu
  - arch == Arch Linux
  - v7+ == Raspbian
  - fc == Fedora
  - ph2-esx == PhotonOS
  - coreos == CoreOS
  - linuxkit == Linux Kit
  - lcow == LCOW
  - linode == LiNode
  - everything else == OtherLinux

**Comment by iSazonov** [comment]
@SteveL-MSFT Great!
It would be interesting to see how the popularity of the product grows from month to month, from year to year.
Also it is not so useful to see all the preview versions on the dashboard. Maybe group by 6.0. * - preview *, 6.1. * - preview * and similarly for release versions?

**Comment by mi-hol** [comment]
@SteveL-MSFT thanks for taking the time!

Would you consider @iSazonov 's proposal above? It would greatly improve usability :)

There are few other topics to improve usability like the used number scaling on Page 8 'Windows'  where '0M(illion) is showing for most entries. That scaling issue might be caused by a limitation in PowerBI. Do you happen to know?

**Comment by SteveL-MSFT** [comment]
@iSazonov it's in our backlog to archive the data so we can see longer trends.  By default, I believe AppInsights only retains 3 months worth of data.  I'll probably work on this after 6.1 GA.  Grouping is something I can look into.

@mi-hol I'm definitely not a PowerBI expert.  In the GUI, I have limited options to choose representation of th text in the chart.  Unfortunately, PowerBI (currently) seems to have simple logic in that if any data point is > million, it sets the units to millions.  So any data point < 1M shows as 0M (although not literally 0).  I'll just leave this part as-is as the other option is to just show the percentage, but as the numbers grow, having the units will be more interesting.

**Comment by iSazonov** [comment]
> people have custom builds 

It could be separate report/page from official builds.

**Comment by mi-hol** [comment]
@SteveL-MSFT regarding 'PowerBI expert' neither am I but perhaps you'd want to reach out to your MSFT fellow Amanda Cofsky, PM for PowerBI :) 
hint: I was looking for a dashboard tool to recommend to a large customer but these limitations turn it down
