### ISSUE TITLE
Cannot redirect streams to anything else than output stream 1

### ISSUE THREAD

**Issue by felixfbecker** [PowerShell/PowerShell#7620]
Steps to reproduce
------------------

When running PowerShell, I sometimes need to redirect all "log" streams (including the information stream) to STDERR. For this, I am trying to redirect the information stream 6 to the warning stream 3:
```powershell
'test' 6>&3
```
I also tried redirecting all streams:
```
'test' *>&3
```
And redirecting to the error stream:
```
'test' 6>&2
```
```
'test' *>&2
```

Expected behavior
-----------------

This should redirect `test` to the warning or error stream, as described in https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_redirection 

Actual behavior
---------------

The first two examples fail with
```
At line:1 char:10
+ 'test' 6>&3
+          ~
Missing file specification after redirection operator.
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : MissingFileSpecification
```

```none
At line:1 char:10
+ 'test' *>&3
+          ~
Missing file specification after redirection operator.
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : MissingFileSpecification
```

Redirecting to stream 2 fails with:
```
At line:1 char:8
+ 'test' 6>&2
+        ~~~~
The '6>&2' operator is reserved for future use.
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : RedirectionNotSupported
```
```
At line:1 char:8
+ 'test' *>&2
+        ~~~~
The '*>&2' operator is reserved for future use.
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : RedirectionNotSupported
```

The only thing that works properly is redirecting to the output stream like `*>&1` or `6>&1`, which makes `*>&1 | Write-Warning` possible as a warning, but that will put _everything_ on the warning stream, including the _actual output_ of the function.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by PetSerAl** [comment]
Linked documentation only show three forms of redirection operator: `n>`, `n>>` and `n>&1`. There are no documented operators `n>&2` or `n>&3`.

**Comment by felixfbecker** [comment]
That's true, but it's not very obvious, especially when the same operator in bash works for stderr too (`>&2`). The error messages are also confusing.

In Linux programs, often STDERR is used as the logging stream, especially if STDOUT is speaking an RPC protocol, e.g. needs to be valid JSON. PowerShell currently can't really be used for this because any information or warning logs will gets sent to STDOUT.

**Comment by BrucePay** [comment]
@felixfbecker Something to keep in mind: in traditional text-based shells, the various output streams are just undifferentiated text so it doesn't matter what goes where.. In PowerShell, the streams are strongly typed. The error stream only contains ErrorRecords, the VerboseStream only contains VerboseRecords, etc. The only polymorphic stream is the output stream so it's the only one where merge semantics are clear. That said, the higher-level scenario is important and we should have a way to accommodate it. One of the ideas we had in the past is to allow you to redirect into an action (scriptblock) and the action can do things like logging, etc. Anyway, I'm going to mark this as an enhancement request.

**Comment by felixfbecker** [comment]
That makes sense - in a way, it reminds me of [ReactiveX `Materialize`](http://reactivex.io/documentation/operators/materialize-dematerialize.html) - redirecting all event types to the primary stream, while maintaining the information about where it came from through the type info.

You should already be able to pipe it further into `ForEach-Object` and check if `$_` is `ErrorRecord`, `InformationRecord`, and depending on the type, call `Write-Error`, `Write-Warning`, etc.

Here is an implementation of `Dematerialize` in PowerShell:

```powershell
filter Write-StreamByType {
    param(
        [int] $SuccessTarget = 1,
        [int] $ErrorTarget = 2,
        [int] $WarningTarget = 3,
        [int] $VerboseTarget = 4,
        [int] $DebugTarget = 5,
        [int] $InformationTarget = 6
    )
    if ($_ -is [ErrorRecord]) {
        $e = [ErrorRecord]$_
        Write-Error -ErrorRecord $e
    } elseif ($_ -is [InformationRecord]) {
        $i = [InformationRecord]$_
        Write-Information -MessageData $i.MessageData -Tags $i.Tags
    } elseif ($_ -is [WarningRecord]) {
        $w = [WarningRecord]$_
        Write-Warning -Message $w.Message
    } elseif ($_ -is [VerboseRecord]) {
        $v = [VerboseRecord]$_
        Write-Verbose -Message $v.Message
    } elseif ($_ -is [DebugRecord]) {
        $d = [DebugRecord]$d
        Write-Debug -Message $d.Message
    } else {
        $_
    }
}
```

If we extend this, we can write a function that redirects output streams arbitrarily:

```powershell
# Writes the input to the given target stream
function Write-TargetStream {
    param(
        [Parameter(Mandatory, Position = 0)]
        [ValidateRange(1, 6)]
        [int] $Target,

        # A union of all parameters of the Write cmdlets
        # Error
        [Parameter(ValueFromPipeline)]
        [ErrorRecord] $ErrorRecord,

        # Debug, Verbose, Warning
        [Parameter(ValueFromPipelineByPropertyName, ValueFromPipeline)]
        [Alias('MessageData')] # Information
        $Message = $InputObject,

        # Information
        [Parameter(ValueFromPipelineByPropertyName)]
        [string[]] $Tags
    )
    switch ($Target) {
        1 { $Message }
        2 {
            if ($null -ne $ErrorRecord) {
                Write-Error -ErrorRecord $ErrorRecord
            } else {
                Write-Error -Message $Message
            }
        }
        3 { Write-Warning -Message $Message }
        4 { Write-Verbose -Message $Message }
        5 { Write-Debug -Message $Message }
        6 { Write-Information -MessageData $Message -Tags $Tags }
    }
}

# Redirects streams to other streams
filter Write-Stream {
    param(
        [int] $SuccessTarget = 1,
        [int] $ErrorTarget = 2,
        [int] $WarningTarget = 3,
        [int] $VerboseTarget = 4,
        [int] $DebugTarget = 5,
        [int] $InformationTarget = 6
    )
    if ($_ -is [ErrorRecord]) {
        $_ | Write-TargetStream -Target $ErrorTarget
    } elseif ($_ -is [InformationRecord]) {
        $_ | Write-TargetStream -Target $InformationTarget
    } elseif ($_ -is [WarningRecord]) {
        $_ | Write-TargetStream -Target $WarningTarget
    } elseif ($_ -is [VerboseRecord]) {
        $_ | Write-TargetStream -Target $VerboseTarget
    } elseif ($_ -is [DebugRecord]) {
        $_ | Write-TargetStream -Target $DebugTarget
    } else {
        $_ | Write-TargetStream -Target $SuccessTarget
    }
}
```

This makes use of PowerShell's `ValueFromPipelineByPropertyName` and `ValueFromPipeline` handling to automatically destructure Record objects from the pipeline into common properties (e.g. `Message`) and passing those into the required `Write` cmdlets as asked for by the user. Some properties may get lost (e.g. error -> warning, or information -> verbose). If the types are incompatible, e.g. an object in the success stream -> verbose stream, it will be coerced to a string by PowerShell automatically (calling `.ToString()`).

Usage:
```powershell
# Redirect error to warning stream, and warning to verbose
Write-Error "test" *>&1 | WriteStream -ErrorTarget 3 -WarningTarget 4
# Redirect output to information stream (useful for executing native commands!)
echo "Doing operation..." | Write-Stream -SuccessTarget 6
```

This is basically what I would expect the redirection operator to be able to do. PowerShell is a very dynamic language and has automatic type coercion, so it should be able to automatically coerce types between streams.

**Comment by coin8086** [comment]
> @felixfbecker Something to keep in mind: in traditional text-based shells, the various output streams are just undifferentiated text so it doesn't matter what goes where.. In PowerShell, the streams are strongly typed. The error stream only contains ErrorRecords, the VerboseStream only contains VerboseRecords, etc. The only polymorphic stream is the output stream so it's the only one where merge semantics are clear. That said, the higher-level scenario is important and we should have a way to accommodate it. One of the ideas we had in the past is to allow you to redirect into an action (scriptblock) and the action can do things like logging, etc. Anyway, I'm going to mark this as an enhancement request.

Good explanation. But I think it's better put into the document so that we don't get confused by the error.

**Comment by rklec** [comment]
For future readers. ChatGPT proposed this for redirecting a stream to STDERR (e.g. when saved in a temporary file):
```
Get-Content "$workingDir\stdout.log"
Get-Content "$workingDir\stderr.log" | ForEach-Object { Write-Error $_ }
```
