### ISSUE TITLE
Enhance "Invoke-RestMethod" -v(verbose) equivalent to curl -v

### ISSUE THREAD

**Issue by zizifn** [PowerShell/PowerShell#7627]
Linux curl -v will have information like:
`
 * Rebuilt URL to: www.google.com/
*   Trying 1*.2**.3**.4**(IP)...
* Connected to ProxyHostName (ProxyHostIP) port ****(#0)
`

This is every help when i debug issue under PROXY environment.

If there possible we can get this kind of function into "Invoke-RestMethod" and "invoke-webrequest". Thx.

**Comment by markekraus** [comment]
Dplicate of #5564
