### ISSUE TITLE
Missing v6.1.0-rc.1 Docker Images

### ISSUE THREAD

**Issue by strawgate** [PowerShell/PowerShell#7637]
Steps to reproduce
------------------

Navigate to: https://hub.docker.com/r/microsoft/powershell/tags/

Expected behavior
-----------------

See tags for "6.1.0-rc.1-centos-7

Actual behavior
---------------

No 6.1.0-rc.1 tags for any OS

**Comment by adityapatwardhan** [comment]
@strawgate The images are hosted on mcr.microsoft.com. The README on dockerhub explains the `latest`, `preview` and stable releases. [README](https://hub.docker.com/r/microsoft/powershell/)

The way to pull the rc.1 version for centos-7 will be 
```
docker pull mcr.microsoft.com/powershell:6.1.0-rc.1-centos-7
```

/cc @TravisEz13

**Comment by TravisEz13** [comment]
@strawgate  I can delete the older tags from before we made the switch to `mcr.microsoft.com` (MCR) if that would make this clearer, but that would break anyone that hasn't updated.  I've been told that the Docker that MCR will eventually update either the tags page or the readme with a full list of tags available on MCR.

**Comment by strawgate** [comment]
I had not realized that the repository had changed to mcr.microsoft.com -- maybe adding something to the page indicating that it has changed would be useful.

It would seem as though anyone using microsoft/powershell:latest will apparently be pinned to 6.0.4 forever?

**Comment by TravisEz13** [comment]
`latest`, `preview` and `nanoserver` tags which are manifest list will be updated and the associated tags pulled over to docker hub for now.  I'll give your feedback to the MCR team.

**Comment by rotata** [comment]
Is the questions related to the latest tag on Dockerhub vs what is available on MCR?

**Comment by rotata** [comment]
restarting the conversation...can we confirm that this issues is related to the latest tag.

**Comment by strawgate** [comment]
I was just mentioning that previously the images were microsoft/powershell:6.0.1 etc and that i hadnt seen any communication or warning that it had switched to mcr.microsoft.com so I was expecting to find the tags on docker hub but they were not there and it wasnt until someone pointed it out on this issue that I noticed that the urls on the description page had changed from "microsoft/" to "mcr.microsoft.com"

I'm not sure there is any actual action item here
