### ISSUE TITLE
The VSTS Deploy task Azure PowerShell and Build task - PowerShell are not able to handle secret variables and Azure key vault variables correctly while writing their values to console  using write-host. This is causing the values of secret variables to the exposed in log files.

### ISSUE THREAD

**Issue by rathirad** [PowerShell/PowerShell#7638]
1. Issue:
The VSTS Deploy task Azure PowerShell and Build task - PowerShell are not able to handle secret variables and Azure key vault variables correctly while writing their values to console  using write-host. This is causing the values of secret variables to the exposed in log files.

2. Steps to reproduce
------------------
a. Sample script:
=======
param(
[Parameter(Mandatory=$true)]
[string]$Secretvariablewithspecialcharacter,
[Parameter(Mandatory=$true)]
[string]$normalVariablewithspecialcharacter,
[Parameter(Mandatory=$true)]
[string]$Secretvariablewithnospecialcharacter
)
Write-Host "Printing parameters:"
Write-Host "Secretvariablewithspecialcharacter: $Secretvariablewithspecialcharacter"
Write-Host "normalVariablewithspecialcharacter: $normalVariablewithspecialcharacter"
Write-Host "Secretvariablewithnospecialcharacter: $Secretvariablewithnospecialcharacter"

$notspecialcharacter="1234abcd";
$specialcharacter ="1234§-¤%#&/=abcd"

Write-Host "notspecialcharacter: $notspecialcharacter"
Write-Host "specialcharacter: $specialcharacter"

if ($Secretvariablewithspecialcharacter -eq $specialcharacter)
{
Write-Host "Secretvariablewithspecialcharacter $Secretvariablewithspecialcharacter and $specialcharacter specialcharacter match"
}

else 
{
Write-Host "Secretvariablewithspecialcharacter '$Secretvariablewithspecialcharacter' and '$specialcharacter' specialcharacter don't match"
}

if ($normalVariablewithspecialcharacter -eq $specialcharacter)
{
Write-Host "normalVariablewithspecialcharacter '$normalVariablewithspecialcharacter' and '$specialcharacter' specialcharacter match"
}

else 
{
Write-Host " normalVariablewithspecialcharacter'$normalVariablewithspecialcharacter' and '$specialcharacter' specialcharacter don't match"
}
if ($Secretvariablewithnospecialcharacter -eq $notspecialcharacter)
{
Write-Host "Secretvariablewithnospecialcharacter '$Secretvariablewithnospecialcharacter' and '$notspecialcharacter' notspecialcharacter match"
}

else 
{
Write-Host " Secretvariablewithnospecialcharacter '$Secretvariablewithnospecialcharacter' and '$notspecialcharacter' notspecialsecretexp don't match"
}

Write-Host "1234abcd";
==========End of script=============

b. Details of VSTS Deploy task - Azure PowerShell
===================================================================
2018-08-27T16:25:01.9014389Z Task         : Azure PowerShell
2018-08-27T16:25:01.9014659Z Description  : Run a PowerShell script within an Azure environment
2018-08-27T16:25:01.9014900Z Version      : 3.1.2
2018-08-27T16:25:01.9015134Z Author       : Microsoft Corporation
2018-08-27T16:25:01.9015401Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613749)
2018-08-27T16:25:01.9015965Z ===================================================================

c. Details of Build task - PowerShell
===================================================================
2018-08-27T16:13:20.6918025Z Task         : PowerShell
2018-08-27T16:13:20.6918306Z Description  : Run a PowerShell script
2018-08-27T16:13:20.6918619Z Version      : 1.2.3
2018-08-27T16:13:20.6918890Z Author       : Microsoft Corporation
2018-08-27T16:13:20.6919248Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613736)
2018-08-27T16:13:20.6919642Z ===================================================================
d. In the above Azure PowerShell task and build task the Script argument are as follow:
===========
-Secretvariablewithspecialcharacter "$(Secretvariablewithspecialcharacter)" 
-normalVariablewithspecialcharacter "$(normalVariablewithspecialcharacter)" 
-Secretvariablewithnospecialcharacter "$(Secretvariablewithnospecialcharacter)"

e. The values of the environment variable are set as below
==================

1. Below is a secret environment variable with special character
$(Secretvariablewithspecialcharacter) = "1234§-¤%#&/=abcd"

2. This is a environment variable with special character
$(normalVariablewithspecialcharacter)= "1234§-¤%#&/=abcd"

3. Below is a secret environment variable with no special character
$(Secretvariablewithnospecialcharacter)" = "1234abcd"

Expected behavior after triggering the build:
-----------------
Printing parameters:
Secretvariablewithspecialcharacter: ******
normalVariablewithspecialcharacter: 1234§-¤%#&/=abcd
Secretvariablewithnospecialcharacter: ******
notspecialcharacter: 1234abcd
specialcharacter: 1234§-¤%#&/=abcd
Secretvariablewithspecialcharacter ***** and 1234§-¤%#&/=abcd specialcharacter match
normalVariablewithspecialcharacter '1234§-¤%#&/=abcd' and '1234§-¤%#&/=abcd' specialcharacter match
Secretvariablewithnospecialcharacter '****' and '1234abcd' notspecialcharacter match
******

Actual behavior after triggering the build:

---------------
2018-08-27T16:13:22.5803219Z Printing parameters:
2018-08-27T16:13:22.5975638Z Secretvariablewithspecialcharacter: 1234-%#&/=abcd
2018-08-27T16:13:22.5982503Z normalVariablewithspecialcharacter: 1234-%#&/=abcd
2018-08-27T16:13:22.5988068Z Secretvariablewithnospecialcharacter: ***
2018-08-27T16:13:22.5994138Z notspecialcharacter: ***
2018-08-27T16:13:22.6000358Z specialcharacter: 1234A-A%#&/=abcd
2018-08-27T16:13:22.6022558Z Secretvariablewithspecialcharacter '1234-%#&/=abcd' and '1234A-A%#&/=abcd' specialcharacter don't match
2018-08-27T16:13:22.6029803Z  normalVariablewithspecialcharacter'1234-%#&/=abcd' and '1234A-A%#&/=abcd' specialcharacter don't match
2018-08-27T16:13:22.6035509Z Secretvariablewithnospecialcharacter '***' and '***' notspecialcharacter match
2018-08-27T16:13:22.6041088Z ***

As you see above the expected behavior and actual behavior are not same.

Please help in handling the secret variables and secret variables with special characters correctly in the above script.
the statement Write-Host "1234abcd"; should write the value 1234abcd, but instead its masked using ***
Please let me know if you need additional details.

**Comment by iSazonov** [comment]
@rathirad Please add version information $PSVersionTable.

**Comment by rathirad** [comment]
@iSazonov  - The $PSVersionTable.PSVersion  is 5.1.14393.2312

I have setup the build and release task setup at https://rathirad.visualstudio.com/HelloWorldPowershell/
Please let me know if you would like to have a look.

**Comment by iSazonov** [comment]
@rathirad The repo is only for PowerShell Core. Can you repo with latest builds of PowerShell Core?

I think it is better to move the issue to UserVoice.

**Comment by rathirad** [comment]
@iSazonov -  Please note this is not a new feature request. Please advice as to why this bug need to be added to user voice.  If the special character cannot be handle currently, can you provide the list of special characters which we can use in PowerShell task in VSTS.

**Comment by rathirad** [comment]
@iSazonov - Do you have any update for me.

**Comment by iSazonov** [comment]
@rathirad The repo is only for PowerShell Core. For Windows PowerShell please report to UserVoice site.

**Comment by rathirad** [comment]
@iSazonov - Could you please confirm if I need to post this request at https://windowsserver.uservoice.com/forums/301869-powershell

**Comment by iSazonov** [comment]
@rathirad Yes.

**Comment by rathirad** [comment]
@iSazonov - Thank you. I have posted the request at -
 https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/35242300-the-vsts-deploy-task-azure-powershell-and-build-ta
