### ISSUE TITLE
response to prompts needs to be in UPPER case on Ubuntu 18.04

### ISSUE THREAD

**Issue by mi-hol** [PowerShell/PowerShell#7639]
## Expected Behavior
response to prompts can be any case because PowerShell is case-insensitive by design. 
## Current Behavior
Only on Ubuntu 18.04 prompts (i.e. for install-module) are required to be in UpperCase.
Verification details provided by @edyoung are on https://github.com/PowerShell/PowerShellGet/issues/314

## Possible Solution
Allow lower case response

## Steps to Reproduce (for bugs)
```
Get-Culture
Set-Content foo.txt -Value "hi" ; $ConfirmPreference="low"; Remove-Item foo.txt
```

![2018-08-24 10_10_23-window](https://user-images.githubusercontent.com/22799428/44573406-d1ac8200-a786-11e8-984b-40f4dbd57f1c.png)
and
![uppercasepromptrequired](https://user-images.githubusercontent.com/22799428/44488724-c445a980-a659-11e8-905d-40ad94bcd879.PNG)

## Your Environment

```PowerShell

> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.4
PSEdition                      Core
GitCommitId                    6.1.0-preview.4
OS                             Linux 4.4.0-17134-Microsoft #137-Microsoft Thu Jun 14 18:46:00 PST 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
and 6.1.0.rc1 https://github.com/PowerShell/PowerShellGet/issues/314#issuecomment-416077139

**Comment by iSazonov** [comment]
Can you repo on standalone Ubuntu 18.04?

**Comment by joeyaiello** [comment]
Throwing it in 6.1.0, we should at least triage it and validate on non-WSL before we ship GA

**Comment by DHowett** [comment]
Test result from Ubuntu 18.04.1 in Docker (Linux host)

```
PS /> cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
PS /> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-rc.1
PSEdition                      Core
GitCommitId                    6.1.0-rc.1
OS                             Linux 4.17.0-3-amd64 #1 SMP Debian 4.17.17-1 ...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


PS /> install-module -name SqlServer

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this
repository, change its InstallationPolicy value by running the Set-PSRepository
 cmdlet. Are you sure you want to install the modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help
(default is "N"):y

Installing package 'SqlServer'
Downloaded 0.00 MB out of 24.78 MB.
[                                                                    ]      
```

**Comment by mi-hol** [comment]
@DHowett thanks! 
Would you mind to run the verification command at top and add results?
This would allow me to create an issue in the WSL github :)

**Comment by rkeithhill** [comment]
I couldn't repro this on my Ubuntu 18.04 VM running PS Core 6.1-rc1.

![image](https://user-images.githubusercontent.com/5177512/44923705-4c851800-ad06-11e8-871f-e29250ce4359.png)

**Comment by mi-hol** [comment]
closing here as it seems a weird WSL related issue
