### ISSUE TITLE
Get-HotFix doesn't take ComputerName via Pipeline

### ISSUE THREAD

**Issue by kvprasoon** [PowerShell/PowerShell#7640]
Even though this cmdlet is not available in corecli now, observed a problem in it, `-ComputerName` parameter accepts value from pipeline by property name as per the definition, but there is no `ProcessRecord()` method, iterating through collection is handled via a `foreach` statement in `BeginProcessing()` method.

![image](https://user-images.githubusercontent.com/12897753/44676609-7235c700-aa51-11e8-8364-265ced89fdb7.png)

**Comment by MaximoTrinidad** [comment]
This is not a valid PowerShell Core cmdlet.  Please must file the Windows PowerShell issue in Uservoice at:
https://windowsserver.uservoice.com/forums/301869-powershell 

:)

**Comment by iSazonov** [comment]
@SteveL-MSFT Have we plans to port Get-HotFix cmdlet or enable it for Windows only?

**Comment by BrucePay** [comment]
I could actually see us trying to produce a cross-platform version of this cmdlet.

**Comment by iSazonov** [comment]
Experience with Get-ComputerInfo shows that it is not so easy considering the difference between platforms.

**Comment by iSazonov** [comment]
@kvprasoon We return the cmdlet to PowerShell Core. If you want you can fix the issue.

**Comment by Maamue** [comment]
I decided I could tackle this, but found out #10852 fixed this issue and is merged. Can we close this issue and remove the label "Up for Grabs"?
