### ISSUE TITLE
Sometimes the thread was getting stuck for EndInvoke

### ISSUE THREAD

**Issue by Qjames** [PowerShell/PowerShell#7644]
Recently, I'm using runspacepool to do some work. But I met a problem that sometimes the runspace doesn't get invoked. But if I Ctrl+C to end the main process, the script in block will be invoked to execute. Can someone help me on this, why it get stucked sometimes? I'm running in windows server 2012. The foreach loop will be loop 68 times. My code is like below:

```
$throttleLimit = $env:NUMBER_OF_PROCESSORS
$scriptBlock = {
    Param(
        [string]$svc_name
    )
    #execute powershell script in the block
    .\xxxxx.ps1
}
$RunspacePool = [runspacefactory]::CreateRunspacePool(1, $throttleLimit)
$RunspacePool.Open()
$Jobs = @()

foreach($svc in $MicroServiceAutoPilotMapping.Keys)
{
    $Job = [powershell]::Create().AddScript($scriptBlock).AddArgument($svc)
    $Job.RunspacePool = $RunspacePool
    $Jobs += New-Object psobject -Property @{
        Service = $svc
        Pipe = $Job
        Result = $Job.BeginInvoke()
    }
}
WriteStep "Waiting..." -NoNewline

while ($Jobs.Result -ne $null)
{
    $completed = $Jobs | Where-Object { $_.Result.IsCompleted -eq $true }
    foreach ($job in $completed)
    {
        WriteStep "EndInvoke $($job.Service)"
        $job.Pipe.EndInvoke($job.Result)
        WriteStep "$($job.Service) end successfully"
        $job.Result = $null
    }
}
$RunspacePool.Close()
$RunspacePool.Dispose()
```

$PSVersionTable
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.18968
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

**Comment by iSazonov** [comment]
@Qjames Do you use Windows PowerShell? Can you repo on latest build of PowerShell Core?

**Comment by Qjames** [comment]
@iSazonov Yes, I'm using Windows PS, and can be reproduced on both winserver 2012 and winserver 2016.

**Comment by iSazonov** [comment]
@Qjames The repo is only for PowerShell Core. Please move the Issue to UserVoice.

**Comment by Qjames** [comment]
@iSazonov do you mean close the issue and open in where?
Thanks.

**Comment by iSazonov** [comment]
Yes.
