### ISSUE TITLE
Winrm install .net 4.7.2 developer pack crash in windows server 2012 r2

### ISSUE THREAD

**Issue by JokiesD** [PowerShell/PowerShell#7645]
Steps to reproduce
------------------
![image](https://user-images.githubusercontent.com/42765350/44707946-7658f780-aad8-11e8-8563-3e777d937740.png)
Remote this dev pack return crash
https://www.microsoft.com/net/download/thank-you/net472-developer-pack
```powershell
enter-pssession -computer $myIP -credential $mycredential
cd $env:temp
.\ndp472.exe /quiet /norestart |out-string

```
OS Version:Windows 2012 r2 datacenter
![image](https://user-images.githubusercontent.com/42765350/44708591-1f542200-aada-11e8-943e-353202f4de71.png)

This issue can be reproduced on any new installed 2012 r2 server
Expected behavior
-----------------

![image](https://user-images.githubusercontent.com/42765350/44708335-70afe180-aad9-11e8-980d-27ad5c54ce58.png)

```none

```

Actual behavior
---------------
![image](https://user-images.githubusercontent.com/42765350/44708258-3f371600-aad9-11e8-980b-2d80e37d2a75.png)
```none

```

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by iSazonov** [comment]
@JokiesD Thank you for the report! 

The repo is only for PowerShell Core. Please move the issue to [UserVoice site](https://windowsserver.uservoice.com/forums/301869-powershell).

**Comment by chuanjiao10** [comment]
1 Try not to use the development version. use NDP472-KB4054530-x86-x64-AllOS-ENU.exe
2 restart if need.
3 close this issue please.

**Comment by chuanjiao10** [comment]
win2012 r2 patch 
https://support.microsoft.com/en-us/help/4457129/windows-81-update-kb4457129
Applies to: Windows 8.1Windows Server 2012 R2 
This security update includes improvements and fixes that were a part of update KB4343891 (released August 30, 2018) and addresses the following issues:
Security updates to Windows media, Windows Shell, Windows Hyper-V, Windows datacenter networking, Windows kernel, Windows virtualization and kernel, Microsoft JET Database Engine, Windows MSXML, and Windows Server.
For more information about the resolved security vulnerabilities, see the Security Update Guide.
