### ISSUE TITLE
The code that creates delegates for scriptblocks can't handle certain return types.

### ISSUE THREAD

**Issue by BrucePay** [PowerShell/PowerShell#7651]
In `ScriptBlock.InvokeAsDelegateHelper()` we pass the result of the execution through `GetRawResult()` which results in a scalar value if the return pipe contains one object. The type conversion on the return value can't deal with the scalar in some case resulting in a run time error. Making this work is important for methods like `[Linq.Enumerable]::SelectMany()` which takes a delegate `[System.Func[TSource,int,System.Collections.Generic.IEnumerable[TResult]]]`

Steps to reproduce
------------------
```powershell
([func[system.collections.generic.ienumerable[object]]] { 1 }).Invoke()
```
Expected behavior
-----------------
```none
1
```
Actual behavior
---------------
```none
Exception calling "Invoke" with "0" argument(s): "Cannot convert the "1" value of type "System.Int32" to type "System.Collections.Generic.IEnumerable`1[System.Object]"."
At line:1 char:1
+ ([func[system.collections.generic.ienumerable[object]]] { 1 }).Invoke ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : PSInvalidCastException

```

Environment data
----------------

```powershell
PSCore (1:102) >  $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.2
PSEdition                      Core
GitCommitId                    v6.1.0-preview.2
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
I think part of the problem is there's no conversion path for `T` to `IEnumerable<T>`.  I've had similar issues inheriting classes with abstract methods that return an `IEnumerable<>`.

A shorter repro is that this doesn't work:

```csharp
[System.Collections.Generic.IEnumerable[object]]1
```

But this does

```csharp
[System.Collections.Generic.IEnumerable[object]][object[]]1
```

In classes the workaround is to force the return value to something already inheriting `IEnumerable<>` like above, but that doesn't seem to work here.

**Comment by BrucePay** [comment]
@SeeminglyScience In this specific case, the code returns a collection, checks to see if it's length 1 then turns it into a scalar. If the cast worked, we'd then take that scalar and turn it back into a collection of 1 element which is not desirable. More generally, you can't cast a scalar to IEnumerable[T] because converting from a scalar to a collection requires creating an instance of the collection and you can't create an instance of IEnumerable[T], only instances of concrete types that implement IEnumerable[T}.  Now we could add a special case (hack but one of many) in the type converter logic that picked a specific concrete type (probably array of T) to do the conversion but I'm not sure it's desirable. Thoughts?

**Comment by SeeminglyScience** [comment]
@BrucePay I think the pattern is common enough that it makes sense.  Maybe even the other collection like interfaces `T[]` implements like `IList<T>`, `ICollection<T>`, etc.

I don't think it would be desirable to *always* force the result to be an array (you wouldn't want to cast a LINQ method result unnecessarily) but if the target object is not already of the specified cast type, then forcing to `T[]` makes a lot of sense to me.

**Comment by IISResetMe** [comment]
Isn't this... expected behavior?

`([func[system.collections.generic.ienumerable[object]]] { Write-Output @(1) -NoEnumerate }).Invoke()` works fine

**Comment by love2hina-net** [comment]
It was the same situation when I encountered that SelectMany didn't work in PowerShell.

```
using namespace System.Collections.Generic
using namespace System.Text.RegularExpressions
using namespace System.Linq

[Match] $match = [Regex]::Match('{#begin condition header:2 footer:1}', '\{#(\w+)(?:\s+(\S+))*\}')
$captures = [Enumerable]::SelectMany($match.Groups, [Func[Group, IEnumerable[string]]] {
    param([Group] $g)
    return [Enumerable]::Select($g.Captures, [Func[Capture, string]] {
        param([Capture] $c)
        return [string] $c.Value
    })
})

foreach ($capture in $captures) {
    Write-Debug $capture
}

Line |
  14 |  foreach ($capture in $captures) {
     |           ~~~~~~~~
     | Cannot convert the "{#begin condition header:2 footer:1}" value of type "System.String" to type "System.Collections.Generic.IEnumerable`1[System.String]".
```

I'll leave a comment for this issue that some people actually encountered it.
