### ISSUE TITLE
32-bit linux binaries where

### ISSUE THREAD

**Issue by ek4** [PowerShell/PowerShell#7659]
?

**Comment by iSazonov** [comment]
There are no official 32-bit unix packages.

**Comment by ek4** [comment]
Why no?

**Comment by iSazonov** [comment]
@SteveL-MSFT Could you please answer?

**Comment by SteveL-MSFT** [comment]
@ek4 we haven't had any requests for x86 built binaries until now.  Unless there is a number of customers asking for 32-bit support, it's a burden to regularly build and test.  For now, we could update our build script to output 32-bit binaries if the packaging/validation can be owned by the community.

**Comment by SteveL-MSFT** [comment]
@rkeithhill excellent point!  Looks like https://github.com/dotnet/coreclr/issues/9265 tracks .NET Core support for x86 Linux.  Until then, nothing we can do.

**Comment by BobVul** [comment]
@SteveL-MSFT There is actually one prior request [here](https://github.com/PowerShell/PowerShell/issues/4707), plus a [SE question](https://unix.stackexchange.com/questions/508581/installing-powershell-on-32-bit-kali-os-fails), so there's at least some interest.
