### ISSUE TITLE
Up Arrow Command History Cursor Location (6.1-rc Only)

### ISSUE THREAD

**Issue by tommymaynard** [PowerShell/PowerShell#7670]
This issue is being open in regard to the placement of the cursor when using the up arrow to cycle through previously executed commands in 6.1-rc. In 5.1 and 6.0.4, it works correctly; however, in 6.1-rc it does not.

After any command, when pressing the up arrow, the cursor is placed at the beginning of the command/line. The expectation is that the cursor will be at the end. Instead of being able to add to the previous command, on its far right end, I'm having to first move to the far right end, and then begin typing. It's not major, but it is a different experience from 5.1 and 6.0.4.

Steps to reproduce
------------------

```powershell
> Get-ChildItem
> # Up arrow, cursor is under the G in Get-ChildItem.
```

Expected behavior
-----------------

```none
Expected that the cursor will be at the end of the previous command(s).
```

Actual behavior
---------------

```none
Cursor is placed at the beginning of the previous command(s).
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-rc.1
PSEdition                      Core
GitCommitId                    6.1.0-rc.1
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
I can not repo. Need more information. 
Is the problem with and without loaded PSReadline? What version of PSReadline? Can you repo if disable your .ps profile?

**Comment by tommymaynard** [comment]
Nice catch @iSazonov. Once I removed the PSReadLine module (2.0.0), I didn't suffer the same fate. I didn't bother disabling my profile scripts, as removing PSReadLine provided me the expected behavior. Sorry for the wasted cycle, but at least you caught it early!

**Comment by MaxCQ** [comment]
For those who ended up here from google...

Assume you have PSReadLine installed...

It's PSReadLine default behavior. Add below to your profile.

`Set-PSReadLineOption -HistorySearchCursorMovesToEnd`

[https://github.com/PowerShell/PSReadLine/issues/944](https://github.com/PowerShell/PSReadLine/issues/944)
