### ISSUE TITLE
Self-contained binary

### ISSUE THREAD

**Issue by MarkTiedemann** [PowerShell/PowerShell#7672]
Would be nice if the `pwsh.exe` binary was self-contained.

Use case, for example:

```
C:\dev\example (master)
λ mklink /H pwsh.exe tools\pwsh\pwsh.exe
Hardlink created for pwsh.exe <<===>> tools\pwsh\pwsh.exe

C:\dev\example (master)
λ pwsh.exe --version
A fatal error occurred, the required library hostfxr.dll could not be found at C:\dev\example\
```

Also, who prefers downloading a `.zip` file compared to an `.exe` file?

**Comment by iSazonov** [comment]
It is .Net Core feature/limitation. Seems they have a old tracking issue without progress.
