### ISSUE TITLE
Get-Content -Tail throws TailNotSupported for the providers except the FileSystem

### ISSUE THREAD

**Issue by jianyunt** [PowerShell/PowerShell#7678]
Based on the current design the `Get-Content -Tail` is allowed to FileSystemProvider only. For other providers, we will get  [TailNotSupported exception ](https://github.com/PowerShell/PowerShell/blob/5d03e1653a7d518715fa3f00587cad6b5c78cc89/src/Microsoft.PowerShell.Commands.Management/commands/management/GetContentCommand.cs#L140) See below example. In addition other provider cannot define the `Tail` as dynamic parameter either, it is because it is [define already here](https://github.com/PowerShell/PowerShell/blob/5d03e1653a7d518715fa3f00587cad6b5c78cc89/src/Microsoft.PowerShell.Commands.Management/commands/management/GetContentCommand.cs#L56).  Any workaround?

``` PowerShell

PS Alias:\> Get-Content .\cat -Tail 2
Get-Content : The Tail parameter currently is supported only for the FileSystem provider.
At line:1 char:1
+ Get-Content .\cat -Tail 2
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (2:Int32) [Get-Content], InvalidOperationException
    + FullyQualifiedErrorId : TailNotSupported,Microsoft.PowerShell.Commands.GetContentCommand

```

I am trying to add Get-Content and Set-Content supp

Steps to reproduce
------------------
cd alias
Get-Content .\cat -Tail 2

I am trying to add Get-Content to the SHiPS for the CloudShell. It looks like we can not use -tail.

```powershell

```

Expected behavior
-----------------
Enable Get-Content -tail for other providers.

Actual behavior
---------------

```none

```

Environment data
----------------

```powershell
> $PSVersionTable

5.1.17134.228 or PowerShell 6.1.0-rc.1

```

**Comment by iSazonov** [comment]
We could make the parameter dynamic.
