### ISSUE TITLE
Unexpected InvalidCastException from dynamic binding when calling particular .NET method

### ISSUE THREAD

**Issue by jazzdelightsme** [PowerShell/PowerShell#7686]
I ran into this very strange exception the other day when trying to use the PerfView tracing library to process some ETL files in PowerShell. When calling the `Process` method on an `ETWTraceEventSource` object, it throws an `InvalidCastException`, but it seems to make no sense.

The signature of the method in question is:

```
PS C:\Users\danthom\AppData\Local\Temp\aixgncuv.npy> $traceEventSource.Process

OverloadDefinitions
-------------------
bool Process()
```

Seems like it should be straightforward to call, right? But when you do, you get this eyebrow-raising error:

```
The result type 'System.Boolean' of the dynamic binding produced by binder 'PSInvokeMember: Process ver:0 args:0 constraints:<>' is not compatible with the result type 'System.Object' expected by the call site.
At line:41 char:1
+ $traceEventSource.Process()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (:) [], InvalidCastException
+ FullyQualifiedErrorId : System.InvalidCastException
```

What's up with that?

Steps to reproduce
------------------

```powershell
$tmpDir = Join-Path ([system.io.path]::GetTempPath()) ([system.io.path]::GetRandomFileName())

Write-Host "Creating temporary repro directory: $tmpDir" -Fore Cyan

$null = mkdir $tmpDir
Push-Location $tmpDir


$zipFile = '.\Microsoft.Diagnostics.Tracing.TraceEvent.zip'
$uri = 'https://github.com/Microsoft/perfview/releases/download/T.2.0.22.0/Microsoft.Diagnostics.Tracing.TraceEvent.2.0.22.nupkg'

Write-Host "Downloading $zipFile" -Fore Cyan

iwr -UseBasicParsing -Uri $uri -Outfile $zipFile

$dir = '.\Microsoft.Diagnostics.Tracing.TraceEvent'
Expand-Archive $zipFile -Dest $dir

$dllPath = "$dir\lib\netstandard2.0\Microsoft.Diagnostics.Tracing.TraceEvent.dll"

Import-Module $dllPath

# We need an .etl... well, let's just create one real quick, I guess.

Write-Host "Creating an ETL file (tmp.etl)..." -Fore Cyan

$etlFile = Join-Path $PWD 'tmp.etl'

$traceSession = [Microsoft.Diagnostics.Tracing.Session.TraceEventSession]::new( 'PsBugReproSession', $etlFile )

$traceSession.EnableWindowsHeapProvider( $pid )
start-sleep -seconds 3
$traceSession.Dispose()

$traceEventSource = [Microsoft.Diagnostics.Tracing.ETWTraceEventSource]::new( $etlFile )

Write-Host "Now let's read through all the events in the .etl file..." -Fore Yellow

# Moment of truth... will this work?
$traceEventSource.Process()
```

Expected behavior
-----------------
No errors.

Actual behavior
---------------

```none
The result type 'System.Boolean' of the dynamic binding produced by binder 'PSInvokeMember: Process ver:0 args:0 constraints:<>' is not compatible with the result type 'System.Object' expected by the call site.
At line:41 char:1
+ $traceEventSource.Process()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (:) [], InvalidCastException
+ FullyQualifiedErrorId : System.InvalidCastException
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-rc.1
PSEdition                      Core
GitCommitId                    6.1.0-rc.1
OS                             Microsoft Windows 10.0.17744
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@jazzdelightsme  Thanks for great repo!

I agree that it is bad message. The binder is very complex. Perhaps @daxian-dbw know how/where we can improver the message.

As for th error I guess you should assign a callback
From https://msdnshared.blob.core.windows.net/media/MSDNBlogsFS/prod.evol.blogs.msdn.com/CommunityServer.Components.PostAttachments/00/10/44/21/52/_TraceEventProgrammersGuide.docx
```c++
using Microsoft.Diagnostics.Tracing;
using System;

class Program
{
    static void Main()
    {
        using (var source = new ETWTraceEventSource("MyEventData.etl"))
        {
            // Set up the callbacks 
            source.Dynamic.All += delegate(TraceEvent data) {
                Console.WriteLine("GOT EVENT {0}", data);
            };
            source.Process(); // Invoke callbacks for events in the source
        }
    }
}
```

**Comment by jazzdelightsme** [comment]
No, adding a callback is no help (I left it out because it is not important to the repro). And it makes sense that having a callback or not is relevant to the problem: if `$traceEventSource.Process()` were complaining that I was not using it right, that would imply that the `Process()` method was being called... but it cannot be, because PS failed during binding.

Also, the problem can be worked around by using `Add-Type` to add some C# code to call the `Process()` method, which then works with no problem. And it works fine without adding any callbacks (though it is not useful, of course).

This error is strange to me, because I don't recall ever having seen a binder error before. What is so special about this no-argument, bool-returning method?!

P.S. To anybody actually trying to use the TraceEvents.dll library from PowerShell, I would recommend NOT using `TraceEventSource` anyway; use `TraceLog` instead, which reads in all the events up-front and then you can slice-n-dice in PS.

```powershell
$traceLog = [Microsoft.Diagnostics.Tracing.Etlx.TraceLog]::OpenOrConvert( $etlFile )
```

**Comment by iSazonov** [comment]
@jazzdelightsme Thanks for workaround with Add-Type. Looks like an edge case bug in binder.

**Comment by jazzdelightsme** [comment]
Fun fact: this seems to happen when the method in question is called "`Process`" or "`End`": https://github.com/PowerShell/PowerShell/issues/14267#issuecomment-735980310
