### ISSUE TITLE
Out-of-Date installation instruction  for Ubuntu 18.04 - how to solve once for all times?

### ISSUE THREAD

**Issue by mi-hol** [PowerShell/PowerShell#7687]
The [currently published instructions for Ubuntu 18.04  direct-download](https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-powershell-core-on-linux?view=powershell-6#installation-via-direct-download---ubuntu-1804) reference an out-of-date production version 6.0.3 and does not mention the preview versions like RC1. This is a re-occurring issue for each release (just search closed issues).
I wonder how this can be fixed once for all times?

A meta layer for artifacts where the always changing name is just an attribute came to mind.
This is a wider issue affecting nearly every IT project so github should add such a feature.
AS interim PlatyPS might be a solution (note: just an idea I am not familiar with it)

**Comment by mi-hol** [comment]
@SteveL-MSFT From my view the out-of-date file names in all 'direct download instruction' could be a reason why for example RC1 is not getting installed by a larger user base

**Comment by SteveL-MSFT** [comment]
@mi-hol agree that we should try to come up with something static rather than trying to keep the doc updated to latest versions.  Don't have a good solution off the top of my head than to say something like "download latest release" and have the version in the sample be generic like "powershell_6.1.0-preview.ubuntu.18.04_amd64.deb" and a note saying: "replace the example version with the specific version".

@binaryWard your issue is a different problem that needs to be looked at

**Comment by mi-hol** [comment]
@SteveL-MSFT while I understand the reasoning for a 'low tech' text-only solution, I had actually hoped for a 'high tech' solution.
PlatyPS's schema looked to me like a great starting point
´´´´
schema: 2.0.0
external help file: {file name for `New-ExternalHelp`}.xml
´´´´

**Comment by rkeithhill** [comment]
I was really hoping that after the 6.1 GA release, all we had to do to install PS Core on Ubuntu was simply execute:
```
sudo apt update
sudo apt install -y powershell
```
Has there been any progress on getting PS Core into the official Canonical apt repo?

**Comment by SteveL-MSFT** [comment]
@rkeithhill Getting into an official repo essentially means that distro has accepted the responsibility of maintaining and servicing a fork of your code in their code base.  This is why different distros have different versions of some common utilities and they don't necessarily always move to the latest version.  On the other hand, we do publish to the Snap store which shifts the maintenance of the packages back to the package owners instead of the distro owners.  This means that you can just run:

> sudo snap install powershell --classic

On systems that have the Snap client by default.  Independent of that, we are more likely to succeed on getting PSCore6 in Azure Linux images by default.

**Comment by chuanjiao10** [comment]
> Has there been any progress on getting PS Core into the official Canonical apt repo? 

-----I hope that ps core 6.1 stable version can be included in ubuhtu 1804.2

> reference an out-of-date production version

To solve this problem, I have a very good idea:           @sdwheeler 
Add a line to the installation documentation, such as:
Sudo yum remove -y powershell #remove old version
Or
Sudo yum remove -y powershell-preview # Delete the old version
Ubuntu be same.

look:
```powershell
curl -o /etc/yum.repos.d/microsoft.repo  https://packages.microsoft.com/config/rhel/7/prod.repo 
sudo yum remove -y powershell #删除旧版 
sudo yum install -y powershell
pwsh -c 'install-module psreadline -AllowPrerelease -Force'
pwsh -c 'mkdir "$env:HOME/.config/powershell" '
pwsh -c 'Add-Content  -Value 'Set-PSReadlineOption -EditMode Windows' -LiteralPath $profile '
```

ubuntu1604：
```
curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
sudo curl -o /etc/apt/sources.list.d/microsoft.list https://packages.microsoft.com/config/ubuntu/16.04/prod.list
sudo apt-get update
sudo apt-get remove -y powershell #删除旧版 
sudo apt-get install -y powershell
pwsh -c 'install-module psreadline -AllowPrerelease -Force'
pwsh -c 'mkdir "$env:HOME/.config/powershell" '
pwsh -c 'Add-Content  -Value 'Set-PSReadlineOption -EditMode Windows' -LiteralPath $profile '
```

ubuntu1804：
```
curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
sudo curl -o /etc/apt/sources.list.d/microsoft.list https://packages.microsoft.com/config/ubuntu/18.04/prod.list
sudo apt-get update
sudo apt-get remove -y powershell #删除旧版 
sudo apt-get install -y powershell
pwsh -c 'install-module psreadline -AllowPrerelease -Force'
pwsh -c 'mkdir "$env:HOME/.config/powershell" '
pwsh -c 'Add-Content  -Value 'Set-PSReadlineOption -EditMode Windows' -LiteralPath $profile '
```


debian9：
```
sudo apt-get update
sudo apt-get install curl gnupg apt-transport-https
curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch main" > /etc/apt/sources.list.d/microsoft.list'
sudo apt-get update
sudo apt-get remove -y powershell #删除旧版 
sudo apt-get install -y powershell
pwsh -c 'install-module psreadline -AllowPrerelease -Force'
pwsh -c 'mkdir "$env:HOME/.config/powershell" '
pwsh -c 'Add-Content  -Value 'Set-PSReadlineOption -EditMode Windows' -LiteralPath $profile '
```

> Getting into an official repo essentially means that distro has accepted the responsibility of maintaining and servicing a fork of your code in their code base.

Negotiate with Canonical, let ubuntu 1804.2  mini install  run that script or command:

```
curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
sudo curl -o /etc/apt/sources.list.d/microsoft.list https://packages.microsoft.com/config/ubuntu/18.04/prod.list
sudo apt-get update
sudo apt-get remove -y powershell #删除旧版 
sudo apt-get install -y powershell
pwsh -c 'install-module psreadline -AllowPrerelease -Force'
pwsh -c 'mkdir "$env:HOME/.config/powershell" '
pwsh -c 'Add-Content  -Value 'Set-PSReadlineOption -EditMode Windows' -LiteralPath $profile '
```
Good idea    ?

**Comment by binaryWard** [comment]
@SteveL-MSFT  
I realize I didn't state if it was the Ubuntu 18.04 workstation or server.  Ubuntu Server has a new installer "Subiquity" which has the "live" in the iso filename and is the default installer. The older installer is obtained through the "alternative downloads" and has a filename without "live".

Ubuntu Server 18.04 "alternative download" .iso worked. I was able to use the apt repo instructions and install the powershell-preview.

```
Name                           Value
----                           -----
PSVersion                      6.1.0-rc.1
PSEdition                      Core
GitCommitId                    6.1.0-rc.1
OS                             Linux 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

The Ubuntu Server 18.04 -live- still gives me the error but I can try that again.  The new installer has an interesting change where there is a "powershell" to select in the installer.

If I can recreate this problem I will create a new issue.  At first I thought it was related to the documentation but seems there could be something else.

**Comment by SteveL-MSFT** [comment]
@binaryWard would be great if you can post a screenshot of where the installer has `powershell` as an option.  Wasn't aware they did that.

**Comment by binaryWard** [comment]
@SteveL-MSFT if this works the following link should be a screenshot of the "cloud" iso using the newer Ubuntu Installer.
![powershell begin it has] (https://user-images.githubusercontent.com/389969/46301108-02908b80-c56b-11e8-9301-175494d888bd.PNG)

**Comment by mi-hol** [comment]
closing due to lack of interest
