### ISSUE TITLE
Why do we use rcedit?

### ISSUE THREAD

**Issue by PetSerAl** [PowerShell/PowerShell#7688]
It seems that `dotnet` build process is capable to set all necessary assembly metadata, like version and copyright strings, application icon. Why do we use external utility to do that instead? Is any good reason to use `rcedit` to edit compiled `.exe` rather than set this metadata thru `.csproj` file?

**Comment by thezim** [comment]
See #5178 and its associated issues for the back story. Perhaps this is no longer needed with .Net Core 2.1.

**Comment by iSazonov** [comment]
@PetSerAl Do you know that dotnet can assign an icon to exe?
I see that a tracking issue is still open. https://github.com/dotnet/cli/issues/3267

**Comment by PetSerAl** [comment]
@iSazonov You are right. `dotnet` does not support this when publishing self-contained app for .NET Core runtime.
