### ISSUE TITLE
High DPI

### ISSUE THREAD

**Issue by kingcean** [PowerShell/PowerShell#7694]
For high DPI, e.g. displayed in Surface, the text is too small.

**Comment by iSazonov** [comment]
Do you mean a Github font size or PowerShell console size?

**Comment by kingcean** [comment]
PowerShell console.

**Comment by iSazonov** [comment]
PowerShell doesn't manager console font. It uses system defaults or user settings.

**Comment by DHowett** [comment]
This is likely because you’re using “Raster Fonts”. Don’t do that, and you’ll get high DPI support.

**Comment by persalmi** [comment]
I still have this issue even if I change to true type font like Consolas, have to bump size up to 36 or something when running on a 15.6 inch 4K laptop. Using 200% screen scale for Windows 10. @kingcean and  @DHowett what font size do you set?

**Comment by iSazonov** [comment]
Do you see the issue for cmd window?
