### ISSUE TITLE
Select-Object -Unique is much slower than Sort-Object -Unique

### ISSUE THREAD

**Issue by HumanEquivalentUnit** [PowerShell/PowerShell#7707]
Reading a file of ~60,000 lines, picking only unique entries:

```
$lines = [System.Io.File]::ReadLines('/path/to/file.txt')

$lines | Select-Object -Unique   # 6-12 minutes

$lines | Sort-Object -Unique    # 2-3 seconds
```

(Relevant source code for [sort-object unique handling](https://github.com/PowerShell/PowerShell/blob/5d03e1653a7d518715fa3f00587cad6b5c78cc89/src/Microsoft.PowerShell.Commands.Utility/commands/utility/sort-object.cs#L58) and relevant source code for [select-object -unique handling](https://github.com/PowerShell/PowerShell/blob/8374a5c97dbdf2367f9db3a6cde74ca3df14d224/src/Microsoft.PowerShell.Commands.Utility/commands/utility/select-object.cs#L600), appears to happen on PSv5.1 Windows and PSv6.1-preview 4 Linux).

I see that `Select-Object` stores a list of items it has seen, and has a nested loop to compare every incoming item against every item in the list, a full object compare instead of just the property being sorted on, and every added property. so it is doing more work, and should be expected to be slower. Even so, it is *so much* slower - for a case of 'unique strings' which seems like it would be common, but may not be - could it be sped up?

Would it be reasonable to have it store a HashSet of something like `obj.ToString()` as well, and then for each incoming object, lookup in the HashSet - if it's not there, then the object must be unique and new, and it can be output without further work. If the value is in the hashset, it can do the full comparison.  Or would that be too much extra memory use?

Using `sort-object` is a workaround if you don't mind the order changing, but if you try `select-object` and think it's slow, sorting seems like it would add extra work on top and take longer - it's not obvious that it might be ~100x faster.

**Comment by iSazonov** [comment]
Seems we could use the same code in Sort-Object, Group-Object and Select-Object.

/cc @powercode

**Comment by powercode** [comment]
Seems like there are room for improvement :)

**Comment by iSazonov** [comment]
I guees we could move the new Sort-Object code to OrderObjectBase.cs on first step and then reuse it all related cmdlets.

**Comment by HumanEquivalentUnit** [comment]
@iSazonov A PR for the HashSet looks fun; a PR for merging the code of three cmdlets, without breaking backwards compatibility, looks scary and probably too big for my skills.

(How does `Group-Object` fit into this?)

**Comment by iSazonov** [comment]
@HumanEquivalentUnit Yes, there maybe we have to refactor a lot of code. I hope @powercode  will have the inspiration for this. :-)

> (How does Group-Object fit into this?)

I've been watching this code for a long time. It seems that there are useful comments in OrderObjectBase.cs.

**Comment by jantari** [comment]
> Seems we could use the same code in Sort-Object, Group-Object and Select-Object.

What if one wants to preserve the order of the objects? `Select-Object -Unique` does that.

If we're going to clean up the cmdlets around this feature I think the first to go should be `Select-Unique` as its utterly useless and confusing due to only rejecting duplicates when they're pre-sorted. Unexpected behavior imo
