### ISSUE TITLE
Start-ResGen is not recognized 

### ISSUE THREAD

**Issue by chucklu** [PowerShell/PowerShell#7708]
Steps to reproduce
------------------

```powershell
Start-ResGen test.txt

```

Expected behavior
-----------------

should generate file with extension .resources like [Resgen](https://docs.microsoft.com/en-us/dotnet/framework/tools/resgen-exe-resource-file-generator) did

Actual behavior
---------------

```none
Start-ResGen : The term 'Start-ResGen' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Start-ResGen .\LISA.ControlPanel.txt
+ ~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Start-ResGen:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-rc.1
PSEdition                      Core
GitCommitId                    6.1.0-rc.1
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
In build process we use `Start-PSBuild -ResGen`
https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/resx-files.md#resources

**Comment by chucklu** [comment]
@iSazonov  thanks, I have import the module in profile according the documentation
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/import-module?view=powershell-6

> Import-Module imports a module only into the current session. To import the module into all sessions, add an Import-Module command to your PowerShell profile. For more information about profiles, see [about_Profiles](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-6).

**Comment by chucklu** [comment]
``` powershell
$PROFILE
C:\Users\clu\Documents\PowerShell\Microsoft.PowerShell_profile.ps1
```


the content

> Import-Module 'C:\Users\clu\source\repos\GitHub\Other\posh-git\src\posh-git.psd1'
> Import-Module 'C:\Users\clu\source\repos\GitHub\Other\PowerShell\build.psm1'
