### ISSUE TITLE
Issue with pwsh 6.1.0-rc1 New-PSSession using SSH Key Auth

### ISSUE THREAD

**Issue by pldmgg** [PowerShell/PowerShell#7709]
Same issue posted here since not sure if OpenSSH-Win64 or pwsh issue: https://github.com/PowerShell/Win32-OpenSSH/issues/1244

In this test scenario, zerotesting5.zero.lab (192.168.2.13) is the localhost and zerowin16sshb.zero.lab (192.168.2.53) is the Remote Host.

Relevant info about both machines:

- Both are running Windows 2016 Standard
- Both have pwsh 6.1.0-rc1 (and ONLY pwsh 6.1.0-rc1) installed
- Both are running OpenSSH-Win64 7.7.2.0 (ssh-agent and sshd services are Running)
- Both have the following sshd_config: https://gist.github.com/pldmgg/73ef10856bed885ffcf1df4d11560d72

From zerotesting5.zero.lab (localhost) in pwsh.exe, do the following:

```powershell
# This fails:
New-PSSession -HostName zerowin16sshb -UserName zero\zeroadmin -KeyFilePath "C:\Users\zeroadmin\.ssh\zeroadmin_090418-cert.pub"

# This fails:
New-PSSession -HostName zerowin16sshb -UserName zero\zeroadmin -KeyFilePath "C:\Users\zeroadmin\.ssh\zeroadmin_090418"

# This works:
ssh zeroadmin@zero@zerowin16sshb

# This works:
ssh -o "IdentitiesOnly=true" -i "C:\Users\zeroadmin\.ssh\zeroadmin_090418" -i "C:\Users\zeroadmin\.ssh\zeroadmin_090418-cert.pub" zeroadmin@zero@zerowin16sshb

# This works:
ssh -o "IdentitiesOnly=true" -i "C:\Users\zeroadmin\.ssh\zeroadmin_090418" zeroadmin@zero@zerowin16sshb
```

For both of the `New-PSSession` failures above, the error message is as follows:

```powershell
New-PSSession : [zerowin16sshb] There is an error processing data from the background process. Error reported: PowerShell 6.1.0-rc.1.
At line:1 char:1
+ New-PSSession -HostName zerowin16sshb -UserName zero\zeroadmin -KeyFi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotingTransportException
+ FullyQualifiedErrorId : 2102,PSSessionOpenFailed
```

For both of the `New-PSSession` attempts, output of `sshd.exe -ddd` on zerowin16sshb is the following:

https://gist.github.com/pldmgg/95fc0a364c201896646fac59957cfe79

Not sure if this is an OpenSSH-Win64 issue or a pwsh.exe issue, but since the straight ssh commands work and `New-PSSession` doesn't, I'm leaning towards pwsh.exe. But I'm also thinking that it could be something like ssh.exe not telling pwsh.exe's `New-PSSession` that it's done whatever it's doing...

**Comment by MaximoTrinidad** [comment]
On the sshd_config, I normally got uncommented:

Port 22
PubkeyAuthentication yes
PasswordAuthentication yes

Then, the ssh_port_22 rule need to be in place in the firewall.

Also, when using Enter-PSSession -Hostname, I don't include the computer name with the username. 

Hope this help in any way!
:)

**Comment by pldmgg** [comment]
Thanks @MaximoTrinidad !

Regarding Port, PubkeyAuthentication, and PasswordAuthentication, my understanding is that those commented options are actually set by default, so the only reason I would uncomment them is if I wanted to change those default settings (i.e. Port other than 22, or 'no' for either of the other settings).

Regarding firewall, I've turned them completely off for both machines.

For `Enter-PSSession`, do you mean that you don't include the Domain preceding the account name for the -UserName parameter?

**Comment by MaximoTrinidad** [comment]
One thing! Turning off firewall, I think it won't work because ssh relays on using port 22 and that's what's makes it secure and established connections between ssh machines.  Remember, this is not winrm remoting, its a total different connection protocol.

Yes! Don't use domain name with the username, again the -hostname parameter uses SSH protocol. SSH port 22 need to be set in order to work.  At least is my understanding!

I've been using Win32-OpenSSH for some time now and I now things keep changing. 

:)

**Comment by pldmgg** [comment]
Ok...well, the ssh commands do work without issue, so I think this is more of an issue with pwsh and specifically the PSSession cmdlets...

**Comment by MaximoTrinidad** [comment]
Well! Let see if someone can provide more insight on it.
I normally use it with enter-pssession, and I haven't try it without having the SSHport22 rule in the firewall. 

:)

**Comment by thezim** [comment]
Try using -SSHTransport see 
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/new-pssession?view=powershell-6 for more help.

**Comment by pldmgg** [comment]
Tried -SSHTransport with the same result. Also tried -UserName with just the account name as opposed to Domain\Account - same result.

One thing that did actually make a difference though (but did not ultimately solve the problem), was adding a REG_SZ String Value for DefaultShell with value "C:\Program Files\PowerShell\pwsh.exe" to `HKLM:\Software\OpenSSH\`.  (Note that, it didn't exist before). Adding this registry value (and subsequently restarting the sshd service) made the `New-PSSession` cmdlet prompt me for a password (which it shouldn't do because I'm using -KeyFilePath...but at least something happened). Unfortunately, authentication never succeeded eventhough the password for the Domain Admin account was correct and password auth is allowed in the sshd_config. Adding this registry value also caused the aforementioned ssh commands to prompt me for a password (which, again, shouldn't happen because I'm trying to do Public Cert Authentication) with the same result (i.e. authentication was never successful eventhough the password was correct).

Removing this registry value and restarting the sshd service got me back to the state mentioned in my original post - i.e. Public Cert Authentication works with ssh.exe, but does not work with the `*-PSSession` cmdlets.

Still pretty stumped on this...

But after googling around for awhile, I've gotta just ask this general question:

Has **anyone** gotten Public Certificate Authentication to work between two **Windows OSes** using pwsh.exe? Everything I've seen online is between Windows and Linux (which I **do** have working)...

**Comment by pldmgg** [comment]
More information on this...still not solved, but I've narrowed down the problem to the sshd Subsystem invocation of pwsh. Still not clear whether this is a pwsh.exe or OpenSSH-Win64 problem...

The `ForceCommand pwsh.exe -NoProfile` option in my original sshd_config concealed the fact that the "successful" ssh commands were NOT in fact using Subsystem to put me in a pwsh.exe session. Instead, logs indicate that sshd was...

```
Starting session: shell on windows-pty for zero\\zeroadmin from 192.168.2.13 port 50944 id 0
```

...and then immediately running the `ForceCommand` to put me in pwsh.exe. To clarify, what I **should** be seeing here is...

```
Starting session: subsystem 'powershell' for zero\\zeroadmin from 192.168.2.13 port 51060 id 0
```

...which is what I see when I run `New-PSSession`. (My updated sshd_config comments-out the `ForceCommand` option : https://gist.github.com/pldmgg/2850f834889fc430c08e3fd4e735c3e3)

Unfortunately commenting out `ForceCommand` did not make it so that my ssh commands used `Starting session: subsystem...` - they were/are still showing `Starting session: shell`.

So the first problem is figuring out why Subsystem is NOT being used with straight ssh commands, and it IS being used (and failing for some unknown reason) by the pwsh.exe `*-PSSession` cmdlets.

Updated sshd logs can be found here:

1) SSHD_Results_New-PSSession_No_DefaultShell_In_Registry: https://gist.github.com/pldmgg/6cf1a2e1ca02ae540062222fc50bbb63

2) SSHD_Results_SSHExe_No_DefaultShell_In_Registry:
https://gist.github.com/pldmgg/3fa040a73ce6f83385dbc05acb96cf1a

**Comment by pldmgg** [comment]
Adding more info from thread on Win32-OpenSSH: https://github.com/PowerShell/Win32-OpenSSH/issues/1244

Right now, my requirement is to use Public Cert Auth and Subsystem sshd_config such that both ssh.exe and Enter-PSSession put me in a pwsh session on the remote host.

So far, the only way I've been able to accomplish this is to:

SCENARIO 1: 
Without `DefaultShell` entry in the registry, with `ForceCommand pwsh.exe -NoProfile`  in sshd_config, with `Subsystem powershell C:/symlinks/pwsh.exe -sshs -NoLogo -NoProfile` in sshd_config.

- The ssh commands in my original post place me in a pwsh.exe on the Remote Host (SUCCESS)
- `*-PSSession` cmdlets on the client side fail for some unknown reason (FAILURE)
- NOTE: Eventhough `Subsystem...` is active in sshd_config, it is not honored when using ssh.exe. It is honored when using the `*-PSSession` cmdlets.
- IMPORTANT NOTE: I've just confirmed that using `ForceCommand pwsh.exe -sshs -NoLogo -NoProfile` as you suggested causes ssh.exe to hang on the client side - so `ForceCommand pwsh.exe -NoProfile` is the only thing that works for me in this scenario, and only with ssh.exe commands (`*-PSSession` cmdlets still fail in the same way)

SCENARIO 2:
With `DefaultShell` entry in the registry of `C:/Program Files/Powershell/6-preview/pwsh.exe` without `ForceCommand` in sshd_config, with `Subsystem powershell C:/symlinks/pwsh.exe -sshs -NoLogo -NoProfile` in sshd_config.`

- The ssh commands in my original post place me in a pwsh.exe on the Remote Host (SUCCESS)
- `*-PSSession` cmdlets on the client side fail for some unknown reason (FAILURE)
- NOTE: Eventhough `Subsystem...` is active in sshd_config, it is not honored when using ssh.exe. It is honored when using the `*-PSSession` cmdlets.

Fore every other permutation of these three configuration settings (`DefaultShell`, `ForceCommand`, `Subsystem`) :

- Attempting to connect interactively via the ssh commands outlined in my original post have either -
1) Placed me in cmd.exe on the remote host
2) Prevented me from connecting altogether
3) Hung indefinitely

- Attempting to connect via the `*-PSSession` cmdlets has never been successful under any circumstances

**Comment by pldmgg** [comment]
Closing and reopening under a new issue because info here is too difficult to digest.
