### ISSUE TITLE
Add a switch to Select-String that returns the matching parts only, analogous to grep -o

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#7712]
<sup>Related: #7713 and  #7867</sup>

Sometimes all you want `Select-String` to do is to output only the matching parts of the input lines as strings, similar to what `grep -o` does on Unix-like platforms; e.g.:

```powershell
# Extract only the parts that match the regex, each on its own line.
PSonUnix> "line1`nline2`nline3" | grep -o '[0-9]'
1
2
3
```

The equivalent `Select-String` solution is currently cumbersome:

```powershell
PS> "line1", "line2", "line3" | Select-String '[0-9]' | ForEach-Object { $_.Matches[0].Value }
1
2
3
```

If we introduced a switch named, say, ~~`-MatchingPartOnly` (name TBD, could have an alias of `-o`)~~
`-OnlyMatching` (see [decision below](https://github.com/PowerShell/PowerShell/issues/7712#issuecomment-436818795)), the command could be simplified to:

```powershell
PS> "line1", "line2", "line3" | Select-String '[0-9]' -OnlyMatching
```

As an alias, `-om` could be considered (just `-o` could break existing code that used it for `-OutVariable`).

This would also speed up processing, because constructing `[Microsoft.PowerShell.Commands.MatchInfo]` instances can be bypassed.

Environment data
----------------

Written as of:

```none
PowerShell Core 6.1.0-preview.4
```

**Comment by iSazonov** [comment]
@SteveL-MSFT Can you approve?

**Comment by iSazonov** [comment]
I think this should works  for `-SimpleMatch` too.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this, seems fine to add but should match the grep description of the parameter and call it `-OnlyMatching`

**Comment by iSazonov** [comment]
The OnlyMatching name doesn't correlate with "output" 😕

**Comment by HumanEquivalentUnit** [comment]
> Sometimes all you want Select-String to do is to output only the matching parts of the input lines as strings

Seems like a lot of the time, that's all I want `-match` to do as well; and this would get roughly as close as my imaginary `-keep` operator (the inverse of `-replace`):

```powershell
PS C:\> 'a word and here' | Select-String -AllMatches -MatchingPartOnly -Pattern'\w{4}'
word
here
PS C:\> 'a word and here' | sls -a -m '\w{4}'
word
here
PS C:\> 'a word and here' -keep '\w{4}'
word
here
```

😃 Yay!

**Comment by mklement0** [comment]
@HumanEquivalentUnit, I quite like the idea of a `-keep` (or perhaps `-extract`) operator . Can I suggest you create a feature request for it?

**Comment by HumanEquivalentUnit** [comment]
@mklement0 I did; https://github.com/PowerShell/PowerShell/issues/7958 but it looked like a duplicate at the time, of your linked issue which is basically the same request.

**Comment by mklement0** [comment]
Oops! Completely forgot about #7867's `-matchall` proposal, which is indeed the same in essence - thanks.

**Comment by meterien** [comment]
Should this issue be marked as fixed?

**Comment by mklement0** [comment]
@SteveL-MSFT There's one remaining design question to answer:

`grep -o` returns _multiple_ matches on each line:

```
$ echo foo | grep -o o
o
o
```

If we follow this logic, `-OnlyMatching` would effectively invariably imply `-AllMatches`.

However, it may make more sense to have `-OnlyMatching` only report the _first_ match by default, with the option to report _all_ if `-AllMatches` is also specified.

**Comment by iSazonov** [comment]
It is related to question about SimpleMatch + AllMatches.

**Comment by mklement0** [comment]
Yes: here we don't strictly have a backward-compatibility problem, because `-OnlyMatching` will be a new feature.

Technically we are therefore free to to support combining `-SimpleMatch` and  `-AllMatches` with `-OnlyMatching` to output all matching literal substrings (even multiple ones on a single line).

However, given the [committee decision](https://github.com/PowerShell/PowerShell/pull/11102#issuecomment-634980498) _not_ to fix #11102 in order to support combining  `-SimpleMatch` and  `-AllMatches`  (in the default, non-`-OnlyMatching` case), this would lead to an awkward asymmetry.

**Comment by iSazonov** [comment]
I believe we could have an symmetry and PowerShell Committee could discuss both cases:
- -SimpleMatch + -AllMatches
- -OnlyMatching + -AllMatches

**Comment by vazome** [comment]
If someone curious about a current way of doing so,  you can use this:

```
$value = 'aa' #or even [System.IO.File]::ReadLines($filename)
$options = [Text.RegularExpressions.RegexOptions]::IgnoreCase -bor [Text.RegularExpressions.RegexOptions]::CultureInvariant
$regex = 'REGEX'
$properselectstring = [regex]::Matches($value,$regex,$options)
$properselectstring.value
```
