### ISSUE TITLE
IDE for PowerShell Core?

### ISSUE THREAD

**Issue by lstatie** [PowerShell/PowerShell#7714]
I have been using PowerShell 5.1 ISE at work.
Is there a way to use an Integrated Scripting Environment for PowerShell Core? I would like to continue working on the script that I maintain for work, using PowerShell Core 6. The ISE allows me to work on a large script, debug it and test it

**Comment by mklement0** [comment]
Use [Visual Studio Code ](https://code.visualstudio.com/), as described in [here](https://docs.microsoft.com/en-us/powershell/scripting/core-powershell/vscode/using-vscode?view=powershell-6)

**Comment by lstatie** [comment]
Thank you so very much for the prompt response.

**Comment by thezim** [comment]
@lstatie I use VSCode it for 5.1 too. Far superior to ISE in almost every way.

**Comment by lstatie** [comment]
Good to know thezim, I will keep that advice in mind. Thank you.

**Comment by lstatie** [comment]
Another question:
I am using VS Code v1.27.0 with Powershell extension 1.8.4. When the script is running and shows errors in the  output, There seems to be no way to stop the run so I can fix the issue. 

I see a turning circle next to the word "PowerShell" and I can find no way to stop the script from running. 

Is there a way to stop the script so I can edit the script and run it again?
The PowerShell ISE allows me to stop running scripts, but debugging there is quite lacking.

**Comment by thezim** [comment]
Debugging is covered [here](
https://code.visualstudio.com/docs/editor/debugging). The key is finding debug bar (marked C) in the first image on the page. I prefer the keyboard shortcuts myself as they are common with ISE and Visual Studio. Keyboard binding are [here](
https://code.visualstudio.com/docs/getstarted/keybindings). If you are having issues debugging you should file issues in 
https://github.com/PowerShell/vscode-powershell. VS Code can be bit overwhelming at first coming from ISE but if you stick with it you will eventually never look back or when your forced to use ISE you will feel like your back using flip phone.

**Comment by lstatie** [comment]
Another question:
I am using VS Code v1.27.0 with Powershell extension 1.8.4. When the script is running and shows errors in the  output, There seems to be no way to stop the run so I can fix the issue. 

I see a turning circle next to the word "PowerShell" and I can find no way to stop the script from running. 

Is there a way to stop the script so I can edit the script and run it again?
The PowerShell ISE allows me to stop running scripts, but debugging there is quite lacking.

**Comment by lstatie** [comment]
For some reason, rebooting my PC fixed the issue I was asking about in the previous post.
Things are working correctly now.

**Comment by chuanjiao10** [comment]
![win linux ps1](https://user-images.githubusercontent.com/8968667/45257155-1e719900-b3d4-11e8-909b-de1abd8d4c37.jpg)

how to use windows + vscode + sftp plugin ,edit ps1 files ,
when sava,sync ps1 files,txt files ...
