### ISSUE TITLE
Convert-TxtResourceToXml did not work

### ISSUE THREAD

**Issue by chucklu** [PowerShell/PowerShell#7716]
Steps to reproduce
------------------

```powershell
 Convert-TxtResourceToXml .\test.txt

```

Expected behavior
-----------------

```none
Convert the txt file to a file with extension .resx
```

Actual behavior
---------------

```none
ConvertFrom-StringData : Data line ';comment' is not in 'name=value' format.
At C:\Users\clu\source\repos\GitHub\Other\PowerShell\build.psm1:2187 char:38
+ ... esourceHashtable = ConvertFrom-StringData (Get-Content -Raw $txtFile)
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [ConvertFrom-StringData], PSInvalidOperationException
+ FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.ConvertFromStringDataCommand

You cannot call a method on a null-valued expression.
At C:\Users\clu\source\repos\GitHub\Other\PowerShell\build.psm1:2188 char:17
+ ...             $resxContent = $resourceHashtable.GetEnumerator() | ForEa ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvokeMethodOnNull
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-rc.1
PSEdition                      Core
GitCommitId                    6.1.0-rc.1
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

I already import the latest build.psm1 to profile of my powershell.
https://docs.microsoft.com/en-us/dotnet/framework/resources/creating-resource-files-for-desktop-apps#resources-in-text-files
The file content in test.txt contains some comment start with ";"(it seems "#" is another comment symbol)
The [Resgen.exe ](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/ccec7sz1(v=vs.100)) can handle it correctly.

**Comment by chucklu** [comment]
@iSazonov  previously I have a batch script,which using [Al.exe (Assembly Linker)](https://docs.microsoft.com/en-us/dotnet/framework/tools/al-exe-assembly-linker) and  [Resgen.exe (Resource File Generator)](https://docs.microsoft.com/en-us/dotnet/framework/tools/resgen-exe-resource-file-generator) to **generate a file with extension .resources.dll**

> 
> ResGen test.txt
> al /t:lib /culture:en-US  /embed:test.resources /out:test.resources.dll /fileversion:1.1.0.0

Now I want to embed the file version to the .resources.dll dynamically, 
It's not convenient to get the file version of test.exe by batch script, but I can get the file version by powershell script easily.
```powershell
(Get-Item ..\bin\Debug\test.exe).VersionInfo.FileVersion
```
So, I want to write a powershell script to geneate a resources.dll from a txt file(name = value format).

**Comment by iSazonov** [comment]
@chucklu Framework ResGen.exe and our ResGen is different tools. Our ResGen was temporary created for the repo to _only_ build PowerShell because .Net Core doesn't support _strong type based_ resources. 

If you want work with classic resources you should use `dotnet` command -  it will compile your resource files. I don't know if .Net Core support embed resources.

In any case your question is out of the repo.

**Comment by chucklu** [comment]
I found an issue reported by you https://github.com/PowerShell/PowerShell/issues/2882
I have tried to use the `dotnet-resgen` command,
```None
dotnet-resgen --help
dotnet-resgen : The term 'dotnet-resgen' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ dotnet-resgen --help
+ ~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (dotnet-resgen:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```
my dotnet core version is 2.1.401.

I am not sure if I missed some module

**Comment by chucklu** [comment]
add the track issue for resgen msbuild project in https://github.com/Microsoft/msbuild/issues/2272

**Comment by iSazonov** [comment]
@chucklu I think `dotnet-resgen` is in `dotnet build` command.

**Comment by chucklu** [comment]
I  found you are using `dotnet msbuild /t:"ResGen"` to build a project in above issue Microsoft/msbuild#2272 
It's not used to convert a .txt file to .resx file. May be I should use the framework tool

**Comment by chucklu** [comment]
@iSazonov  Do you know how to add a environment path to current session? (like the import-module function in powershell)
I am not sure where the ResGen.exe and al.exe will locate,

In batch script, I import the environment path temporarily

> SET P1=C:\Program Files\Microsoft Visual Studio 8\SmartDevices\SDK\SDKTools;
> SET P2=C:\Windows\Microsoft.NET\Framework\v2.0.50727;C:\Windows\Microsoft.NET\Framework64\v2.0.50727;
> SET P3=C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;
> SET P4=C:\Program Files\Microsoft.NET\SDK\v2.0 64bit\Bin;
> SET P5=C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Bin;
> SET P6=C:\Program Files\Microsoft SDKs\Windows\v7.0A\bin;
> SET P7=C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin;
> SET P8=C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools;
> SET P9=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6 Tools;
> SET P10=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools;
> SET P11=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.2 Tools;
> 
> PATH=%P1%%P2%%P3%%P4%%P5%%P6%%P7%%P8%%P9%%P10%%P11%

Then I invoke the ResGen and al command, I am not sure how to make it in powershell.
Any suggestion? Thanks in advance.

**Comment by iSazonov** [comment]
See https://stackoverflow.com/questions/714877/setting-windows-powershell-path-variable

**Comment by chucklu** [comment]
@iSazonov  thanks
