### ISSUE TITLE
Default Progress foreground/background colors don't translate well to other color schemes

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShell#7717]
The default progress colors look OK (not great) when used from a console with the default color scheme e.g.:

![image](https://user-images.githubusercontent.com/5177512/45131905-37681900-b14c-11e8-81fd-b56cdb50ae48.png)

But when using color schemes like `OneHalfDark` provided by the MS `colortool` utility, the lack of contrast between the FG/BG colors starts to become problematic:

![image](https://user-images.githubusercontent.com/5177512/45131981-6b433e80-b14c-11e8-930a-a654a9ef0eb3.png)

If we switched to better contrasting colors - say black on yellow (or black on the original DarkCyan) - the resulting text is easier to read in other color schemes:

![image](https://user-images.githubusercontent.com/5177512/45132106-e573c300-b14c-11e8-8d6e-1e96b0cb06bb.png)

![image](https://user-images.githubusercontent.com/5177512/45132131-fae8ed00-b14c-11e8-9d08-dc5dcdbab943.png)

Even just changing the FG progress color to black helps:

![image](https://user-images.githubusercontent.com/5177512/45132171-253aaa80-b14d-11e8-94e6-1c9f172f9d56.png)

```
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-rc.1
PSEdition                      Core
GitCommitId                    6.1.0-rc.1
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Related #2488. 

@rkeithhill Please add $PSVersionTable information in the issue description for tracking a milstone.

The best way is to implement a Coloriser and use a PowerShell color scheme.

**Comment by rkeithhill** [comment]
Ya know, PowerShell 7 would be a great time to introduce nicer progress fg/bg colors.  The current colors feel very, very dated.  :-)

**Comment by nelsontkq** [comment]
This is an issue on linux as well:  
![Screenshot from 2019-10-14 10-27-17](https://user-images.githubusercontent.com/19982338/66770767-405a0c80-ee6d-11e9-82e6-1de12aed6b59.png)
