### ISSUE TITLE
Start-ResGen did not work

### ISSUE THREAD

**Issue by chucklu** [PowerShell/PowerShell#7718]
Hi,
     I  have no idea about how to use Start-ResGen command.
     I find the source code in [build.psm1](https://github.com/PowerShell/PowerShell/blob/master/build.psm1#L2128)
     It seems you are using "dotnet run" with the [C# ResGen project ](https://github.com/PowerShell/PowerShell/tree/master/src/ResGen)

  When I check the source code of C# project, I find some comments in main function.
```C#
     // We are assuming resgen is run with 'dotnet run pathToResxFile.resx'.
```
  I  have tried to pass a file name to the "Start-ResGen" command,but it did not work for both txt and resx.
      
```powershell
> Start-ResGen .\test.txt
Start-ResGen : A positional parameter cannot be found that accepts argument '.\test.txt'.
At line:1 char:1
+ Start-ResGen .\test.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Start-ResGen], ParameterBindingException
+ FullyQualifiedErrorId : PositionalParameterNotFound,Start-ResGen

> Start-ResGen .\test.resx
Start-ResGen : A positional parameter cannot be found that accepts argument '.\test.resx'.
At line:1 char:1
+ Start-ResGen .\test.resx
+ ~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Start-ResGen], ParameterBindingException
+ FullyQualifiedErrorId : PositionalParameterNotFound,Start-ResGen
```
     

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-rc.1
PSEdition                      Core
GitCommitId                    6.1.0-rc.1
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@chucklu The function is used intenally in build process to convert *.resx files to *.cs files. See "resources" folders in the repo.
You do not need to run it explicitly. Please read our docs about build process.
All you need to do is run
```
Start-PSBuild -Clean
```
The script clean up your local repo, run TypeGen, ResGen and then build PowerShell in debug mode.

We use our ResGen because .Net Core doesn't still port the feature.

**Comment by chucklu** [comment]
@iSazonov  got it, thanks for your explanation in https://github.com/PowerShell/PowerShell/issues/7716
