### ISSUE TITLE
Add PowerShell Core to the Microsoft Store

### ISSUE THREAD

**Issue by DubbySlashy** [PowerShell/PowerShell#7730]
This way, PowerShell Core can be updated automatically and can be used on Windows 10 in S mode.

**Comment by pv2b** [comment]
Windows 10 in S mode doesn't run Powershell by design. https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-10-s-planning#what-is-blocked-in-windows-10-s

That said, why not for the rest of the world that doesn't run Windows 10 S?

**Comment by vexx32** [comment]
Aye. If there's an issue with it being there for Windows S, surely it can just be listed as incompatible or something, or just run in constrained language only if run on Windows S.

Having it on the Store would be a great addition, giving it a supporting framework for delivering updates without a great deal of extra work... Assuming getting it on the store at all isn't an insane amount of work :)

**Comment by chuanjiao10** [comment]
Should A key upgrade,or automatic silent upgrade, .NET framework and powershell 6 on windows  #5490

**Comment by kilasuit** [comment]
@chuanjiao10 - your comment is totally unwarranted on this thread as it shares no similarity in context to the ask the OP is making in this thread

Please in future look to keep comments on topic and not hijack other threads when not necessary

**Comment by kilasuit** [comment]
Asked for again in #9827

**Comment by SteveL-MSFT** [comment]
The good news is we already have msix builds.  There's [one issue](https://github.com/PowerShell/PowerShell/issues/9278) that I wanted to get fixed before we publish to the store, but perhaps we can move forward and just relnote that limitation.  I'll look into this next week (6.2.x will be first)

**Comment by kilasuit** [comment]
Considering we've had some newer msix builds that require you to be able to sideload apps is this something that is far off on the radar or is this a planned for 7 GA?

**Comment by SteveL-MSFT** [comment]
I'm planning on starting with Preview5.  Wanted to publish Preview4 but our versioning didn't match Store requirements, so I've already made a PR to fix that.

**Comment by rodrigoscna** [comment]
Any news on this, now that the 7 version was released?

**Comment by kilasuit** [comment]
@rodrigoscna Steve recently tweeted this about store updates 

https://twitter.com/Steve_MSFT/status/1235266800343871488?s=20

**Comment by rodrigoscna** [comment]
@kilasuit Great to know! Thanks!

**Comment by kilasuit** [comment]
looks like this has moved a little bit more now and is looking very hopeful https://twitter.com/Steve_MSFT/status/1295887521537118209?s=20

**Comment by pronichkin** [comment]
so, it's... [done](https://twitter.com/Steve_MSFT/status/1296914276897026048?s=20)?

**Comment by kilasuit** [comment]
@pronichkin - I think that for preview yes we can say it is, but for the stable that'll hopefully happen for the 7.0.4 release (if there is one)

**Comment by SteveL-MSFT** [comment]
Stable will come later in the Store.

**Comment by Gnbrkm41** [comment]
Hello! any updates on getting the new preview (p7) on the store? Pwsh is saying that there's a new preview release but it doesn't appear to be up on the store yet.

**Comment by kilasuit** [comment]
@Gnbrkm41 it can take up to 3 days from it being published to the store for it to be marked available for download from the store as per this tweet from @SteveL-MSFT earlier on https://twitter.com/Steve_MSFT/status/1303755418028523520?s=20

**Comment by ChristopherHaws** [comment]
@Gnbrkm41 I am able to see it: https://www.microsoft.com/store/productId/9P95ZZKTNRN4

**Comment by kilasuit** [comment]
@ChristopherHaws under the hood the reference used for the PowerShell Preview (Store) entry in the below Session menu screenshot will update seemlessly when the new versions of the store apps are installed
![image](https://user-images.githubusercontent.com/6355225/92913846-0568ac00-f423-11ea-84f3-74748301166a.png)

If you set this in your settings.json 
``` 
"powershell.powerShellDefaultVersion": "PowerShell Preview (Store)"
```
that will then mean that it always uses the Store version & when that updates it will just work (as it just has for me & the latest update install)
> 
> 
> @Gnbrkm41 it can take up to 3 days from it being published to the store for it to be marked available for download 

@Gnbrkm41 it is now in the store :-)

**Comment by Gnbrkm41** [comment]
Yep. Noticed it this morning. Thanks 😃

**Comment by MaximoTrinidad** [comment]
I reported this one yesterday: 
**Microsoft Store not updating to latest version of PowerShell Preview** #13615

:)
