### ISSUE TITLE
Autocomplete parameter name request - please show the name for the positionally bound thing immediately right of the cursor

### ISSUE THREAD

**Issue by HumanEquivalentUnit** [PowerShell/PowerShell#7733]
Write `Get-Content 'file.txt'`, put the cursor left of the filename, try to autocomplete the `-Path` parameter name; it's not in the list.

```
    # move the cursor to the left of the argument, where the parameter name would be 
    Get-Content 'file.txt'
               ^

    # Write a - and try to autocomplete the -Path parameter name
    Get-Content -{ctrl-space} 'file.txt' 
                 ^
    # -Path is not shown in the list of available parameter names
```

I don't want all the parameter names shown all the time, removing ones which have been used is really useful .. but if it could show the name for whichever parameter is just right next to the cursor and has been bound positionally, that would also be really useful.

Current workaround for long parameter names - try autocomplete, cancel it, comment out the rest of the line, retry autocomplete, choose the name, uncomment the line.

**Comment by vexx32** [comment]
I am constantly running into this is vs code. It'd be nice to have it be a little more sensible here.

Honestly, I feel as though even just only filtering out already-named parameters would be sufficient. Even if it just listed all the positionally bound ones regardless of where they were, it'd be a huge improvement... But if it could be this sensible, it'd be great!

**Comment by PCSIT** [comment]
I'd like to see the auto complete list to include all unless the parameter is already explicitly named.

**Comment by thegooddoctorgonzo** [comment]
I'd like to see the auto complete list to include all unless the parameter is already explicitly named.

**Comment by iSazonov** [comment]
I can repo in Windows PowerShell but can not in PowerShell Core.

**Comment by vexx32** [comment]
See below (this is PS Core 6.1 RC1)
![image](https://user-images.githubusercontent.com/32407840/45226307-81f0af00-b28c-11e8-8885-2809bd826b6b.png)

**Comment by HumanEquivalentUnit** [comment]
With 6.1.0-rc.1 on Server 2016 it reproduces for me; interestingly:

 - If I type `-{ctrl-space}` to see the menu, `-Path` is not there
 - If I type `-{tab}` to cycle through the options, `-Path` is not there
 - If I type `-Pa{tab}` it *will* autocomplete to `-Path`

**Comment by vexx32** [comment]
Yep, looks like the code paths change if you start to specify some of the name. Entering `-P{ctrl-space}` shows -Path as an option as well.

**Comment by iSazonov** [comment]
In my test I haven't PSReadline loaded and I see `-Path` if I type `-{tab}`. With PSReadline loaded the problem is present.

**Comment by SeeminglyScience** [comment]
Here's an easier repro that should be the same across profiles as long as you don't have a custom `TabExpansion2` function loaded.  Tested in 6.1.0-rc1 Windows

```powershell
$inputString = 'Get-ChildItem - a'
$completion = [System.Management.Automation.CommandCompletion]::CompleteInput(
    $inputString,
    ($inputString.Length - 2),
    @{})

$completion.CompletionMatches.CompletionText -match 'path'
# returns nothing

$inputString = 'Get-ChildItem -'
$completion = [System.Management.Automation.CommandCompletion]::CompleteInput(
    $inputString,
    $inputString.Length,
    @{})
$completion.CompletionMatches.CompletionText -match 'path'
# returns:
# -Path
# -LiteralPath
```

**Comment by HumanEquivalentUnit** [comment]
Nice!  Thank you :)
