### ISSUE TITLE
Ubuntu 18.04 Bionic - move libicu55 to libicu57

### ISSUE THREAD

**Issue by freeone3000** [PowerShell/PowerShell#7737]
For Ubuntu 18.04 LTS, the powershell deb dependency should be on libicu57 instead of libicu55 as it was on Xenial.

**Comment by iSazonov** [comment]
@freeone3000 Could you please add more information? What PowerShell Core version do you use?

I see that currently we set the dependence to `libicu60` for 18.04.

/cc @rjmholt

**Comment by freeone3000** [comment]
Proper package was powershell-preview, the powershell package was for
xenial, not bionic. Thanks for looking into this.

**Comment by TravisEz13** [comment]
Sounds like your question was answered.  Please reopen if that is not correct.
