### ISSUE TITLE
While adding certificate to store security warning get cancelled automatically in PowerShell core 6.0.4

### ISSUE THREAD

**Issue by shrikantjoshi007** [PowerShell/PowerShell#7748]
Environment : 
In PS core version 6.0.4 on Server 2016
---------------------------------------------------------------------------------
Issue Details : 

Trying to import certificate using below code

OpenFlags = [System.Security.Cryptography.X509Certificates.OpenFlags]
$store = new-object system.security.cryptography.X509Certificates.X509Store -argumentlist "Root","CurrentUser"
 $Store.Open($OpenFlags::ReadWrite)
 $Store.Add($Cert)
 $Store.Close()
-------------------------------------------------------------------
Expected Behavior : 

Below warning get popup, which need to click as yes, then certificate get added in store for current user

![securitywarning](https://user-images.githubusercontent.com/43136133/45294571-69e18f80-b519-11e8-9967-8789457e73ac.JPG)

-------------------------------------------------------------------
Actual Behavior :

No security warning message get popup, directly throw the below error 

Exception calling "Add" with "1" argument(s): "The operation was canceled by the user".Exception.Message
At C:\HPENimblePowerShellToolkit\scripts\helpers.ps1:85 char:18
+                  ValidateServerCertificate $group
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,ValidateServerCertificate 

---------------------------------------------------------------------------------
I observed this issue only on server 2016 machine where I installed PowerShell 6.0.4, but when I tried it on server 2012R2 with same PS version, warning popup appear and allow me to click yes and install the server certificate.

I feel PS core provide the "No" input to dialog internally and cancelled the operation, with error message as "The operation was canceled by the user"

Please Suggest.

**Comment by iSazonov** [comment]
Can you test with latest 7.0 build?

**Comment by iSazonov** [comment]
Close as stale issue. Feel free to continue discussion.
