### ISSUE TITLE
Add tests for framework dependent package

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#7750]
Add tests to validate package generated by #7729. The package must be built and then installed on a machine having the dotnet runtime installed. Then `dotnet ` should be called on `pwsh.dll` that is built. 

Steps to reproduce
------------------

```powershell
dotnet pwsh.dll
```

Expected behavior
-----------------

```none
PowerShell console starts and can execute cmdlets.
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-rc.1
PSEdition                      Core
GitCommitId                    6.1.0-rc.1
OS                             Microsoft Windows 10.0.18230
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by anmenaga** [comment]
This is essentially another config in package validation tests that we need to add. I'll assign this to myself.
