### ISSUE TITLE
PowerShell shows a prompt when importing signed module: "Do you want to run software from this untrusted publisher?"

### ISSUE THREAD

**Issue by f0rt** [PowerShell/PowerShell#7756]
Team,
I'm importing a module developed by our team signed with a valid certificate and I get this message when importing:

> Do you want to run software from this **untrusted publisher**?
> File moduleName **.psm1** is published by CN=xxx, OU=xxx, O=xxx, L=xxx, S=xxx, C=xxx and is not trusted on your system. Only run scripts from trusted publishers.
> [V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"):

When I inspect the certificate I see the following information:
- Certificate status: "This certificate is OK."
- Certificate path: Verisign ->  Symantec Class 3 SHA256 Code Signing CA -> My company certificate

I saw this workaround but it will be very inconvenient for our customers: https://social.technet.microsoft.com/Forums/windows/en-US/47651485-cbdf-4884-8680-fbdb550ea403/powershell-wrongly-prompting-for-untrusted-publisher

So what is causing this and is there a way to fix it for our module?

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.16299.611
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.611
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by iSazonov** [comment]
Do you distribute your certificate to computers (Trusted Publisher store)?

**Comment by f0rt** [comment]
No, since it is a public certificate. Also on my setup execution policy is set to All Signed.

**Comment by iSazonov** [comment]
I think you should https://blogs.technet.microsoft.com/heyscriptingguy/2010/06/17/hey-scripting-guy-how-can-i-sign-windows-powershell-scripts-with-an-enterprise-windows-pki-part-2-of-2/

**Comment by f0rt** [comment]
Thanks. What is the version this was introduced in?
