### ISSUE TITLE
Strings with Virtual Terminal (VT) / ANSI escape sequences that are truncated for display make effects linger

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#7767]
<sup>Related: #7744</sup>

[Virtual Terminal escape sequences](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences) allow, among other things, formatting of console (terminal) output, notably to produce _colored_ output.

An escape sequence that changes the output color - e.g., `` "`e[32m" `` to switch to green - stays in effect until the color is reset - e.g., with `` "`e[m" ``

Example:

```powershell
"before `e[32mgreen`e[m after"  # prints only the word "green" in green.
```

Therefore, if PowerShell _truncates_ strings for output formatting, a string may get cut off so that the reset sequence is _not_ output, which means that the color unexpectedly stays in effect.

#7744 shows the problem in the context of using an [OSC escape sequence](https://en.wikipedia.org/wiki/ANSI_escape_code#Escape_sequences) to construct a hyperlink (which only some terminals support; others render just the link label).

This is a nontrivial problem to solve, because PowerShell would have to be aware of all potential escape sequences and _know how to reset their effects_ so that the appropriate escape sequence can be appended to the truncated string.

Steps to reproduce
------------------

```powershell
[pscustomobject] @{ test1="before `e[32mgreen`e[m after"; test2='next col' } | Format-Table @{ e='test1'; width=17 }, test2
```

Expected behavior
-----------------

```none
test1              test2
-----              -----
before gr...       next col
```

`gr...` should render green, but `next col` should render with the default color.

Actual behavior
---------------

```none
test1             test2
-----             -----
before gr...  next col
```

That is, `next col` too is printed in green, and green output stays in effect (the prompt rendered after the command will be green too).

Additionally, note that the column alignment is off.

Environment data
----------------

```powershell
PowerShell Core v6.1.0-rc.1 on macOS 10.13.6
PowerShell Core v6.1.0-rc.1 on Ubuntu 16.04.4 LTS
PowerShell Core v6.1.0-rc.1 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.165)
```

**Comment by iSazonov** [comment]
I would like to know that there is a better practice for working with VT.

**Comment by mklement0** [comment]
What do you mean by that, @iSazonov?

**Comment by SteveL-MSFT** [comment]
It seems we could go with a simple approach and always reset the console color anytime after we truncate.

**Comment by mklement0** [comment]
That's promising, @SteveL-MSFT; it will definitely work with _colors_, but is there an equivalent generic reset mechanism for _other types of escape sequences_, such as the OSC sequences mentioned in #7744 (there may be, I haven't checked).

**Comment by iSazonov** [comment]
We don't want to see escapes in trace log. So we need a rendering subsystem.

**Comment by SeeminglyScience** [comment]
Worth noting that ``` `e[m``` won't reset underline (at least on Windows), so ``` `e[24m``` may be needed as well.

**Comment by mklement0** [comment]
That smells like a bug, @SeeminglyScience, and I actually can't reproduce it on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.285)

Does the following really not work for you?

```powershell
"before `e[4munderlined`e[m after"
```

**Comment by SeeminglyScience** [comment]
@mklement0 huh, it does now.  I wonder if a Windows update fixed that or if I'm just thinking of something else...

Either way nevermind :)

**Comment by jazzdelightsme** [comment]
I made the same comment on #7744, but: [DbgShell](https://github.com/Microsoft/DbgShell)'s approach is not to try to reset/undo escape sequences; rather just leave them all in. In other words, when truncating, it only truncates *content*, but preserves all escape sequences (code [here](https://github.com/Microsoft/DbgShell/blob/52f5edda36b435f4f18703b9b2ae816fb47dc901/DbgProvider/internal/CaStringUtil.cs#L267)).

That said, resetting does seem like a good idea in general for a formatting engine. I came searching for Issues after running `Get-Variable` where I had a bunch of variables like `${RED}`, `${YELLOW}`, `${BLACK}`, etc. defined, which totally horked my console. Fortunately I also had a `Reset-Colors` command.

**Comment by BalassaMarton** [comment]
Is it possible to reopen this issue? Hyperlinks are still lingering after truncation:
![image](https://github.com/user-attachments/assets/a52da65b-256c-432e-bc90-350a4347a6fd)
