### ISSUE TITLE
Get-Content throws confusing error when targeting a container

### ISSUE THREAD

**Issue by vexx32** [PowerShell/PowerShell#7770]
Rather than either producing a sensible error, or behaving in a reasonably predictable manner, `Get-Content` incorrectly throws an `Access Denied` error when pointed at a container object. This is *also* the case when using the variable accessor syntax.

Steps to reproduce
------------------

```powershell
PS> Get-Content c:\
```
or
```powershell
PS> ${c:\}
```

Expected behavior
-----------------

Option #1: A sensible error is produced
```none
Get-Content : Unable to access item contents as it is a container. You may be looking for Get-ChildItem instead.
At line:1 char:1
+ Get-Content c:\
+ ~~~~~~~~~~~~~~~
+ CategoryInfo          : ***: (C:\:String) [Get-Content], ***
+ FullyQualifiedErrorId : ***,Microsoft.PowerShell.Commands.GetContentCommand
```
Option #2: Route the call through to Get-ChildItem instead.
What is the "content" of a container if not its child items? It would make at least intuitive sense for Get-Content to simply call Get-ChildItem if passed a path to a container object instead of a leaf object.
```none
Directory: C:\


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10/20/2017   2:55 PM                msys64
d-----        4/11/2018   7:38 PM                PerfLogs
d-r---        9/11/2018   2:11 PM                Program Files
d-r---        8/27/2018   6:53 AM                Program Files (x86)
d-----       10/17/2017   2:52 PM                tmp
d-r---        5/16/2018   3:10 AM                Users
d-----        11/6/2017   2:57 PM                usr
d-----         9/3/2018   5:02 AM                Windows
```

Actual behavior
---------------

(Cmdlet access)
```none
Get-Content : Access to the path 'C:\' is denied.
At line:1 char:1
+ Get-Content c:\
+ ~~~~~~~~~~~~~~~
+ CategoryInfo          : PermissionDenied: (C:\:String) [Get-Content], UnauthorizedAccessException
+ FullyQualifiedErrorId : GetContentReaderUnauthorizedAccessError,Microsoft.PowerShell.Commands.GetContentCommand
```
(Variable access syntax)
```none
Access to the path 'C:\' is denied.
At line:1 char:1
+ ${C:\}
+ ~~~~~~
+ CategoryInfo          : PermissionDenied: (C:\:String) [], UnauthorizedAccessException
+ FullyQualifiedErrorId : GetContentReaderUnauthorizedAccessError
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-rc.1
PSEdition                      Core
GitCommitId                    6.1.0-rc.1
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

In my opinion, given the fact that the variable access syntax is a bit... edge case at the best of times (although undoubtedly also very handy at times) it would seem to make sense that Get-ChildItem would be called in these cases, so that it's possible to explore a provider in this fashion without necessitating use of the cmdlets at all.

**Comment by vexx32** [comment]
It's also worth noting that in the variable access syntax, `{$C:\File.txt} = "string"` will actually overwrite the file contents using `Set-Content`. Whether it makes the slightest lick of sense to allow `Set-Content` to have some kind of effect on container objects also, I don't know. I've a few ideas, but I suspect doing such a thing will just enable a far too simple way to wipe a whole hard drive of files. 😄

**Comment by BrucePay** [comment]
A user-mode process can't "read" the contents of a directory. We're just returning the underlying OS error message:
```powershell
PSCore (2:9) >  [io.file]::ReadAllBytes('c:\')
Exception calling "ReadAllBytes" with "1" argument(s): "Access to the path 'c:\' is denied."
At line:1 char:1
+ [io.file]::ReadAllBytes('c:\')
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : UnauthorizedAccessException
```

We could probably do something with the error message (e.g. say access is denied because it's a container) but alternate file systems may in fact support reading the contents of the directory (e.g. old Unix file systems) so failing automatically _because_ it's a container is probably not ideal. 

> behaving in a reasonably predictable manner, 

In what way is it not predictable?  Does it not produce an error in some cases? (I suppose technically it's unpredictable because the underlying file systems may have varying semantics but that's not a common case and would be by design anyway.)

>  variable access syntax is a bit... edge case at the best of times (although undoubtedly also very handy at times) it would seem to make sense that Get-ChildItem would be called in these cases

Variable notation simply exposes what the underlying provider does. Since the provider produces an error, so does variable notation.

> It's also worth noting that in the variable access syntax, {$C:\File.txt} = "string" will actually overwrite the file contents using Set-Content. Whether it makes the slightest lick of sense to allow Set-Content to have some kind of effect on container objects also, I don't know

Again, this operation is not supported by the operating system. (I only know a couple of (very old) operating systems that allowed user processes to manipulate directories. In one case it was a bug.)

**Comment by vexx32** [comment]
Okay, so there's a disconnect here. What do *you* mean by 'read the contents of a directory'?

Is that a distinct thing from what Get-ChildItem does? It seems sensible (at least on the surface) for 'reading the content' of a directory' to be analogous to 'enumerating the contained objects'

**Comment by iSazonov** [comment]
It would be amazing to turn `Get-Content` into `dir`.

There definitely needs to improve the error message.

**Comment by iSazonov** [comment]
> Did you mean surprising, @iSazonov, as in users won't expect it? Amazing sounds like you're in favor of such a change.

Yes, surprising :-)

**Comment by vexx32** [comment]
I'm not so much in favour of letting users do this with the cmdlets themselves, I think; there the intent can be specified. I'm thinking mostly in terms of the variable syntax itself:

```
${C:\Program Files}
```
Should, to me at least, call Get-ChildItem instead of Get-Content, because the targeted item is a container. 

I think an error is still sensible for a nonsensical use like this:
```
${C:\Program Files} = "foo"
```

Rather than simply having Get-Content automatically call Get-ChildItem when targeting a container, I think it would simply be more sensible for the variable syntax to not be constrained to a single method, and be capable of calling Get-ChildItem when pointed at a container object. (And since there is no Set-ChildItem, nor would having one be very sensible in my opinion, attempting to *set* a container value like this should error.)

I agree that changing the behaviour of the cmdlets themselves in such a fashion is verging on insanity.

**Comment by vexx32** [comment]
Ultimately I personally think it simply makes sense for it to treat an access to the contents of a container as a call to get-childitem.

Regardless of whether that is agreed upon or not, I think the error message *definitely* needs a rework (and as much as I might _wish_ for the namespace variable notation to exhibit better discoverability in and of itself, that's the main thing -- if it's going to throw an error, it should be a comprehensible one.)

**Comment by iSazonov** [comment]
We have  the dup #2686.
