### ISSUE TITLE
Import-CSV doesn't understand sep= header

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#7776]
Excel saves csv with a sep= header to indicate the delimiter/separator.  The cmdlet doesn't understand this header so it treats it as the header row incorrectly.

Steps to reproduce
------------------

```powershell
@"
sep=,
a,b,c
1,2,3
"@ > test.csv
import-csv ./test.csv

```

Expected behavior
-----------------

```none
a b c
- - -
1 2 3
```

Actual behavior
---------------

```none
sep=
----
a
1
```

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.1.0-rc.1
PSEdition                      Core
GitCommitId                    6.1.0-rc.1
OS                             Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by thezim** [comment]
I cannot get Excel 2016 on Windows to repro this in any of the following formats as far as inserting a `sep=`.
```
CSV (Comma delimited) (*.CSV)
CSV (Macintosh) (*.CSV)
CSV (MS-DOS. (*.CSV)
```

I see the your repro is on macOS. It is Numbers producting the CSV? Or possibly Excel on macOS is just different. I've worked with a lot of CSVs in my career and have never seen `sep=` before.

**Comment by iSazonov** [comment]
We need more info. I did not find any specifications.
Is "sep=" always in first line?
Is separator char always single char?

**Comment by thezim** [comment]
Only spec I found was [rfc4180](
https://tools.ietf.org/html/rfc4180) which does not include `sep=`.

**Comment by SteveL-MSFT** [comment]
The original issue was reported to me by a customer.  Looking online.  It seems that `sep=,` is not standard and with latest Excel on my macBook, I don't repro this either.  At this time, it seems like it's a legacy Excel feature to insert that metadata.  I'm ok with closing this until there's more community feedback.
