### ISSUE TITLE
Alpine Linux image has console rendering issues

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#7780]
Not a PSReadLine issue.  Repros if unloaded.  Most likely a corefx issue with console and terminfo.  

Steps to reproduce
------------------

```powershell
docker run -it mcr.microsoft.com/powershell:preview-alpine-3.8
get-command
```

Expected behavior
-----------------

```none
get-command
```

Actual behavior
---------------

```none
ggegetget-get-cget-coget-comget-commget-commaget-commanget-command
```

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.1.0-fixalpine
PSEdition                      Core
GitCommitId                    6.1.0-fixalpine
OS                             Linux 4.9.93-linuxkit-aufs #1 SMP Wed Jun 6 16:55:56 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by SteveL-MSFT** [comment]
cc @alexandair

**Comment by TravisEz13** [comment]
I've made the fix and kicked off a build to rebuild the linux docker images.

We should have `mcr.microsoft.com/powershell:alpine-3.8` and `mcr.microsoft.com/powershell:preview-alpine-3.8` ready soon.

**Comment by TravisEz13** [comment]
both containers have been updated.

**Comment by alexandair** [comment]
I've tried them both and they work nicely now.
@TravisEz13 What's the difference between these images?

**Comment by TravisEz13** [comment]
the stable image is based off the 6.1.0 code.
The preview image is based off the 6.1.0-rc.1 code.

**Comment by TravisEz13** [comment]
I'm closing this issue, but feel free to ask questions here.

**Comment by chuanjiao10** [comment]
1 Congratulations!

2 The size of this image is not small, 172mb.

3 Since the GA version of ps core 6.1 cannot support the docker module, it is expected to release the 6.04 version + alpine image.
Or fix these 2 issues as soon as possible:
#7368
#7796

4 My ultimate goal is: 
powershell + docker module + alpine.
Release “a small  + powershell + docker module” image,it can be used management container and image .
Well, this should be a selling point.

**Comment by TravisEz13** [comment]
The current image is experimental and a work in progress

> 2 The size of this image is not small, 172mb.

The current way we build the image is less than optimal and may be leaving garbage behind.  We need to add PSModuleRestore support to the alpine build to avoid this.

> 3 Since the GA version of ps core 6.1 cannot support the docker module, it is expected to release the 6.04 version + alpine image.

1. The docker module is abandoned with no plans to resume work on this.  This effort was by the Microsoft container team and ran into supportability issues.
2. 6.0.4 is not capable of supporting Alpine.
