### ISSUE TITLE
.NET Core WSMan Remoting to Exchange Online

### ISSUE THREAD

**Issue by christophwille** [PowerShell/PowerShell#7781]
I built a small sample that works on Windows fine, but doesnt on Mac. I verified in pwsh interactively first that it works for pscore 6.1 (lists mailboxes) both on Windows and Mac:

https://github.com/christophwille/pscore-playground/blob/master/NetCorePSCore-Simple/NetCorePSCore/Program.cs#L54

The C# code itself worked already with v6 on Windows and only one package reference

https://github.com/christophwille/pscore-playground/blob/master/NetCorePSCore-Simple/NetCorePSCore/NetCorePSCore.csproj#L9

I added about every package I could think of via #7333 but it still fails with (Mac: you won't get further than New-PSSession)

!Errors! Operation is not supported on this platform. :: This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system. :: Cannot validate argument on parameter 'Session'. The argument is null. Provide a valid value for the argument, and then try running the command again. :: The term 'Get-Mailbox' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Most likely I am still missing something in terms of NuGet package or setup. Thanks for any ideas.

**Comment by adityapatwardhan** [comment]
@dantraMSFT  Can you have a look at this?

**Comment by dantraMSFT** [comment]
@adityapatwardhan, I'm pretty sure the host has to take a dependency on the native nuget package the PowerShell depends on; otherwise, the native binaries wont be available.

**Comment by christophwille** [comment]
Is there a sample on how this has to be done, a gist or some instructions? I added everything and the kitchen sink (m.ps.consolehost, m.m.i,...) and the result is still the same. I must be missing something, but I don't know what that something is (ie I might be initializing ps the wrong way, really missing a NuGet, ...). 

I could not add Microsoft.Powershell.Native because that is 6.0.4 on the myget source.

**Comment by christophwille** [comment]
Just tested on Ubuntu 18.04 with version as-is in my repository: it works there. Now the question is which of the NuGet made it work there (if any outside of SDK), but still the question remains re:Mac why it doesn't there.

**Comment by iSazonov** [comment]
Most of issues is with ssh version.
