### ISSUE TITLE
PowerShell 6.1.0 (RTM) Windows MSI installer does not specify minor version in names

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#7782]
Using the latest 6.1.0 release, the name of the installed package, the window name and the context menu only include the major version but not  the minor version, which will make it hard to distinguish the side-by-side versions. I believe this must be a regression that happened in the refactoring to make the preview packages of 6.1. cc @SteveL-MSFT  @joeyaiello 

![image](https://user-images.githubusercontent.com/9250262/45544436-38194300-b80f-11e8-9327-23021f8a8881.png)

![image](https://user-images.githubusercontent.com/9250262/45544475-52532100-b80f-11e8-8ba0-c9f182485a16.png)

**Comment by aharpervc** [comment]
The default install folder is `C:\Program Files\PowerShell\6`, as well. 6.0.1 was placed in `C:\Program Files\PowerShell\6.0.1` so this change is surprising. I'm assuming it's the same issue.

**Comment by bergmeister** [comment]
@aharpervc Thanks for adding more details. This is possibly related due to #7783

**Comment by bergmeister** [comment]
Ok, thanks, will close then
