### ISSUE TITLE
PowerShell 6.0.4 and 6.1.0 MSIs are not side by side 

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#7783]
According to the [Lifecycle of PowerShell Core](https://docs.microsoft.com/en-us/powershell/scripting/PowerShell-Core-Support?view=powershell-6), one has 6 months to update to the new version. However, during that period I still expect to be able to use 6.0 and 6.1 side by side, which is not the case for the Windows MSIs.
Installing 6.1.0 will remove 6.0.4 as part of it.
In the same way, 6.0.4 cannot be installed when  6.1.0 is already installed:
![image](https://user-images.githubusercontent.com/9250262/45544813-50d62880-b810-11e8-92c8-7289c91ad107.png)

Again, I suspect this is due to the refactoring that happened for the 6.1 preview MSI builds to not have them side-by-side
cc @SteveL-MSFT  @joeyaiello @TravisEz13

**Comment by iSazonov** [comment]
PowerShell Core is side-by-side but not MSI.

**Comment by vexx32** [comment]
IIRC, the preview builds are side by side with release builds, but different versions of the release builds installed via msi will overwrite.

**Comment by bergmeister** [comment]
@iSazonov As per @TravisEz13 's comment [here](https://github.com/PowerShell/PowerShell-RFC/pull/115#issuecomment-370087060), each version should have its own product code and therefore be side-by-side, there is no reason to prevent side-by-side of minor versions.

**Comment by bergmeister** [comment]
It seems, I missed this detail in this RFC [here](https://github.com/PowerShell/PowerShell-RFC/blob/master/5-Final/RFC0026-MSI-Installation-Path.md) that came from this [PR](https://github.com/PowerShell/PowerShell-RFC/pull/115/files). However, the current state of the RFC does not state what the final decision was. I'd rather prefer the mentioned alternative of having minor versions side-by-side @joeyaiello

**Comment by iSazonov** [comment]
Plan was to allow upgrade from 6.0.x to 6.1.x. 
Perhaps we'll have new upgrade code for 7.0 (because of breaking changes).

**Comment by vexx32** [comment]
And it's not as though you *can't* install side by side -- just not with the MSI. Side by side of adjacent minor versions needs to be handled manually, at present.

Can you imagine how annoying it would get having to uninstall/reinstall every minor version for those who *don't* want to maintain 15 separate PS Core versions side by side? 😄

**Comment by SteveL-MSFT** [comment]
Correct, the current intended design is that the MSI will upgrade stable builds over stable builds and preview builds over preview builds.  If side-by-side for minor versions is needed, one must use the zip and not the MSI installer.

**Comment by bergmeister** [comment]
Ok, thanks. Will close then
