### ISSUE TITLE
Time is wrong in powershell 6.1.0 for systems that have a default time zone of UTC.

### ISSUE THREAD

**Issue by mscotthowell** [PowerShell/PowerShell#7791]
Steps to reproduce
------------------
Steps to repro:
kernel version:
[showell@bizzy ~]$ uname -a
Linux bizzy 4.17.19-100.fc27.x86_64 #1 SMP Fri Aug 24 15:32:56 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Default system timezone setting
[showell@bizzy ~]$ timedatectl
Local time: Fri 2018-09-14 23:49:13 UTC
Universal time: Fri 2018-09-14 23:49:13 UTC
RTC time: Fri 2018-09-14 23:49:13
Time zone: UTC (UTC, +0000)
System clock synchronized: yes
systemd-timesyncd.service active: yes
RTC in local TZ: no
Powershell version:

```powershell
```
Expected behavior
-----------------
```
Either show time in local TZ or UTC
```
Actual behavior
---------------
```Results:
Note: Local server TZ is EDT 
Linux:
PS /home/showell> date
Fri Sep 14 23:49:13 UTC 2018

Powershell:
PS /home/showell> get-date

Friday, September 14, 2018 11:49:13 PM

```
Environment data
----------------

PS /home/showell> Get-Host | Select-Object Version
Version

6.1.0
```powershell
> $PSVersionTable
```

**Comment by mscotthowell** [comment]
Steps to repro:
kernel version:
[showell@bizzy ~]$ uname -a
Linux bizzy 4.17.19-100.fc27.x86_64 #1 SMP Fri Aug 24 15:32:56 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Default system timezone setting
[showell@bizzy ~]$ timedatectl
                      Local time: Fri 2018-09-14 23:46:20 UTC
                  Universal time: Fri 2018-09-14 23:46:20 UTC
                        RTC time: Fri 2018-09-14 23:46:19
                       Time zone: UTC (UTC, +0000)
       System clock synchronized: yes
systemd-timesyncd.service active: yes
                 RTC in local TZ: no
Powershell version:
PS /home/showell> Get-Host | Select-Object Version

Version
-------
6.1.0

Results:
Linux: <correct>
PS /home/showell> date
Fri Sep 14 23:49:13 UTC 2018

Powershell: <incorrect>
PS /home/showell> get-date

Friday, September 14, 2018 11:50:20 PM

**Comment by mklement0** [comment]
Please clean up your original post, using the fenced code blocks, and add an explanation of what doesn't work as expected.

**Comment by mklement0** [comment]
It's still unclear what your issue is, and your post is still poorly formatted.
