### ISSUE TITLE
[PSCore 6.1]PSCore doesn't scroll correctly on WSL

### ISSUE THREAD

**Issue by Berrysoft** [PowerShell/PowerShell#7799]
1. Install PSCore 6.1 on WSL(Ubuntu 18.04) on Windows 10 1803.
2. Run `pwsh`.
3. Scroll down the shell window some lines.
4. Type some letters.

The letters will still start by the original position of the cursor, and it won't happen to `bash`.

**Comment by alexandair** [comment]
I can confirm this.

**Comment by ThomasNieto** [comment]
Testing with 7.1 rc1 and bash. I can confirm that the behavior is the same between pwsh and bash. Is this still an issue on 7.1?
