### ISSUE TITLE
Broken link in about_CommonParameters

### ISSUE THREAD

**Issue by Crypt32** [PowerShell/PowerShell#7804]
Steps to reproduce
------------------

```powershell
Get-Help Get-Content -Full
```

Expected behavior
-----------------

```none

```

Actual behavior
---------------

```none
    <CommonParameters>
        This cmdlet supports the common parameters: Verbose, Debug,
        ErrorAction, ErrorVariable, WarningAction, WarningVariable,
        OutBuffer, PipelineVariable, and OutVariable. For more information, see
        about_CommonParameters (https:/go.microsoft.com/fwlink/?LinkID=113216). <--- broken
```
Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.17134.165
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.165
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by iSazonov** [comment]
@Crypt32 Can you repo with latest build PowerShell Core?

**Comment by Crypt32** [comment]
I don't have access to PS Core

**Comment by iSazonov** [comment]
The repo is for PowerShell Core. For Windows PowerShell please report to UserVoice site.

**Comment by iSazonov** [comment]
You also can report to https://github.com/PowerShell/PowerShell-Docs

**Comment by mklement0** [comment]
@Crypt32:

The problem currently affects all cmdlets, it seems, and has already been reported in the docs repo:

https://github.com/PowerShell/PowerShell-Docs/issues/2900

As a  stopgap, you can manually correct the URL and refresh the page - see https://github.com/PowerShell/PowerShell-Docs/issues/2900#issuecomment-422897225

That said, simply googling by cmdlet name may get you there more quickly.

Also - and you may be well aware of that - remember that the quickest way to open an online help page for a cmdlet is to use `Get-Help -Online` , e.g. `Get-Help -Online Get-Content` - of course, that's only useful if the link isn't broken.
