### ISSUE TITLE
OS agnostic means of obtaining username

### ISSUE THREAD

**Issue by thecliguy** [PowerShell/PowerShell#7805]
I'm writing a script to be used on both Windows and GNU/Linux _(I'm currently using Ubuntu but intend to use the script on various distros)_.

I would like to obtain the username of the account under which the script is running. Ideally I'd like to do so using a single technique that'll work irrespective of the operating system.

Using an environment variable seemed like the obvious choice but alas Windows uses `$env:USERNAME` and Ubuntu uses `$env:USER`. Furthermore, `$env:USER` is inadequate because it is not populated if the script is run as a cron job.

As a workaround I am using whoami, Windows has shipped with such a binary since Windows Vista and likewise Ubuntu (normally) ships with the GNU coreutils in which it is present. Whilst this satisfies the requirement of an OS agnostic means of obtaining username (at least for Windows and Ubuntu) it relies on the presence of a third party binary, a dependency I'd rather not have.

Is there already an OS agnostic means of obtaining username using PowerShell? If not are there any plans to introduce such a thing - or has this already been discussed and dismissed?

Environment data
----------------

Ubuntu:
```
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Linux 4.4.0-134-generic #160-Ubuntu SMP Wed Aug 15 14:58:00 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Windows 10:
```
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Seems the question is for CoreFX repo.

**Comment by thezim** [comment]
This is the only OS agnostic way I have found so far via CoreFX. Note that these are not bound to any environment variable which makes them agnostic. I pondered if PowerShell Core should have yet another $PS* variable for these, but additions to that space is difficult to get approved and the below is simply enough for my needs.

```powershell
[Environment]::UserName
```
And if you need the hostname.
```powershell
[Environment]::MachineName
```

**Comment by thecliguy** [comment]
@thezim Thanks for that, it looks promising. I will test your suggestion and let you know the outcome tomorrow.

**Comment by thecliguy** [comment]
@thezim Thank you, I have tested your suggested method of `[Environment]::UserName` and it works perfectly for my requirements.

I do wonder if PowerShell should have something more discoverable, but I will proceed to close the issue as this does fulfil the objective.

Thanks again.
