### ISSUE TITLE
New X509Certificate2 crashes PowerShell with AccessViolationException when certain properties are referenced

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#7806]
Issue from @keystroke.

When a new X509Certificate2 object is created with the empty constructor, it succeeds. However, it is initialised with its `Handle` property set to `IntPtr.Zero`. So accessing certain properties on that object try to dereference that `Handle` and cause an access violation.

Steps to reproduce
------------------

```powershell
$cert = [System.Security.Cryptography.X509Certificates.X509Certificate2]::new(); $cert.SendAsTrustedIssue
```

Expected behavior
-----------------

Value is possibly `$null` or `False`.

Actual behavior
---------------

PowerShell crashes (the window disappears)

Further Information
-----------------------

Also try
```powershell
[System.Security.Cryptography.X509Certificates.X509Certificate2]::new() | fl *
```

This crash reproduces back to Windows PowerShell 5.1.

The property accessed in the particular repro is a script property that triggers this method:
https://github.com/PowerShell/PowerShell/blob/8d4dd1e58f025ca576d38846b9adb5bdeeafd505/src/Microsoft.PowerShell.Security/security/CertificateProvider.cs#L2958-L2988

It seems that `X509Certificate2` has a property called `Handle` which is set to `IntPtr.Zero` by default, causing the access violation.

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.18242
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Does #7808 address the Issue?

**Comment by rjmholt** [comment]
I don't think so unfortunately. This occurs because C# code dereferences a null pointer. The X509Certificate2 wrapper code really needs an alternate code path in all its properties for when there's no underlying certificate (i.e. `Handle` is null) -- or perhaps they should lazily create one?

**Comment by iSazonov** [comment]
> wrapper code really needs an alternate code path 

I agree.

> perhaps they should lazily create one?

Currently ETS is used - this is already "lazy".
