### ISSUE TITLE
ubuntu 18.04 Get-ChildItem results in path too long error

### ISSUE THREAD

**Issue by fhsdfuihisfg** [PowerShell/PowerShell#7809]
Hi, I see from the microsoft document that powershell 6.0 supports long path (#3960)
https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-core-60?view=powershell-6

Why do I encounter path too long error in ubuntu 18.04? Please help.
I have installed the lastest version. (6.1 preview)

**Comment by iSazonov** [comment]
Please add simple repo steps with latest build ( 6.1 GA ) and error message.

**Comment by thezim** [comment]
Just wondering but are the any cyclic (links) protections in `Get-ChildItem` or the provider?

**Comment by BrucePay** [comment]
Unix/Linux protects itself against this when resolving links. See the man page for readlink(2). If you have a cycle, you'll get the following error:

> ELOOP  Too many symbolic links were encountered in translating the pathname.

**Comment by fhsdfuihisfg** [comment]
Installed powershell  6.1 GA  on ubuntu 18.04 lts server
Try create a directory with name of 260 length:
`New-Item "./rKyzLVTkd2KsVHOc68troEpa9UX08tY6eV4hzGXT4crcieJwqIkhrW17P3L0E7niECToJ1aSSE9piv0DlNuMA8ilQf3UBOH6PPD2YQ63I0bNQoqwvX5azJlk87ombSUC0HrEJDGJKTc1q6mTM4NLfT4O5NbQoOa1kFhzkovCy3vDtwWG6OfkidD1joDE28i3Rh1FQwgKSRwBH42tpuK2pmIMXcBqW8z8BXT8d24xeww7z01JbqPxQjlvvwga2GDAAkGe" -Type Directory`

Results in PathTooLongException

**Comment by fhsdfuihisfg** [comment]
I think I find the problem. I have a filename in unicode which appears to be shorter than 260 limit, but after passing it into a online unicode converter, the converted path is actually longer than 260 characters, which makes powershell reports path too long error.

I think it is confusing that the file is allowed to save into disk first place(which appears to under the 260 limit), and then turn out incompatible with powershell later when using command.

**Comment by iSazonov** [comment]
It is CoreFX limitation. You could report in CoreFX repo.
