### ISSUE TITLE
Context Menu\Folder shortcut problem after installing PS Core 6.1 on Windows

### ISSUE THREAD

**Issue by PGomersall** [PowerShell/PowerShell#7815]
Steps to reproduce
------------------
Install PowerShell Core 6.1 on Windows choosing to add context menu "Open PowerShell from here". Once installed, just clicking any Windows shortcut for a folder opens a PowerShell 6.1 window not the Windows Explorer window at the folder.
This only seems to happen with Directory\Folder shortcuts in Quick Launch (%APPDATA%\Microsoft\Internet Explorer\Quick Launch) that are then exposed on Quick Launch toolbar on W10 taskbar as they respond to single click to open. The single click open PowerShell. Uninstall returns behavior to normal.

Expected behavior
-----------------

Clicking a folder shortcut opens the folder in Windows Explorer. 
```

Actual behavior
---------------

Clicking any Windows shortcut when on Quick Launch toolbar on W10 taskbar for a folder opens a PowerShell 6.1 window not the folder in a Windows Explorer window at the folder.

```

Environment data
----------------
PS D:\Downloads> $PSVersiontable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

This system is a fully patched W10 Education x64 version in domain environment.

```

**Comment by iSazonov** [comment]
@bergmeister Could you please comment the Issue?

**Comment by PGomersall** [comment]
Chris,
I have updated the issue on github.
Pete

Pete Gomersall
IT Team Lead
Academic & Research Systems Administration, Information Technology Services
MCSA, MCSE, MCDBA & MCT
Room 143 ITS Building 54
Northern Arizona University
Phone: +1 (928) 523-6877
Cell: +1 (928) 814-8717

**Comment by bergmeister** [comment]
Just an update that I can reproduce now and will start to look into it.
