### ISSUE TITLE
Is the NoLanguage language mode broken?

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#7821]
I may be missing something, but going by [the docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_modes?view=powershell-6):

> In NoLanguage language mode, users may run commands, but they cannot use any language elements.

In reality, at least _switching_ a session to `NoLanguage` mode seems to prevent _everything_ from executing, including cmdlets and external programs (not just language elements).

Is that the intent? Do permissible commands need to specified explicitly somehow?

Steps to reproduce
------------------

```powershell
$ExecutionContext.SessionState.LanguageMode = 'NoLanguage'
Get-Date
```

Note: Switching the language mode of an interactive session is atypical, but it's easy to demonstrate the symptom that way.

Expected behavior
-----------------

Normal `Get-Date` output.

Actual behavior
---------------

The following error occurs:

```powershell
The syntax is not supported by this runspace. This can occur if the runspace is in no-language mode.
...
```

Pretty much _any_ command fails.

Environment data
----------------

```powershell
PowerShell Core v6.1.0 on macOS 10.13.6
PowerShell Core v6.1.0 on Ubuntu 16.04.5 LTS
PowerShell Core v6.1.0 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.165)
Windows PowerShell v5.1.17134.228 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.165)
```

**Comment by BrucePay** [comment]
PowerShell in `NoLanguage` mode can only be used through the API.

**Comment by mklement0** [comment]
Thanks, @BrucePay - but I see the same symptom when I use the API:

```powershell
$ps = [powershell]::Create()
$ps.RunSpace.SessionStateProxy.LanguageMode = 'NoLanguage'
$ps.AddScript('Get-Date').Invoke()
```

Output:

```none
Exception calling "Invoke" with "0" argument(s): "The syntax is not supported by this runspace. This can occur if the runspace is in no-language mode."
...
```

**Comment by BrucePay** [comment]
No language means no _script text of any form is permitted_. This precludes the use of the `AddScript()` method which sends fragments of PowerShell script to be parsed and executed. You can only use `AddCommand()` and `AddParameter()` which don't go through the parser.

**Comment by mklement0** [comment]
Thanks, @BrucePay.

So this is primarily a documentation problem - see https://github.com/PowerShell/PowerShell-Docs/issues/2940

Additionally, it may make sense:

* to prevent switching to `NoLanguage` in _interactive_ sessions - because permitting it makes the session unusable.

* to throw an exception when calling the `.AddScript()` API method while `NoLanguage` is in effect.

**Comment by mklement0** [comment]
I'm closing this, as I'm assuming that no one is holding their breath for the enhanced error prevention/handling I've proposed - hopefully the enhanced documentation will do.
