### ISSUE TITLE
Uninstall problem(context menu was not removed)

### ISSUE THREAD

**Issue by chucklu** [PowerShell/PowerShell#7826]
Steps to reproduce
------------------

uninstall the previous version powershell6-preview

Expected behavior
-----------------

delete the folder and context menu at the same time

Actual behavior
---------------

folder was deleted, but the context menu not

Environment data
----------------

```
I do not remember the version number since I have uninstalled it.
But I have the package name PowerShell-6.1.0-rc.1-win-x64.msi which used to install previous version.
```
![image](https://user-images.githubusercontent.com/3004057/45811761-87c0a880-bd00-11e8-8273-d3ef63d1cf5c.png)

**Comment by bergmeister** [comment]
I have this problem on my machine as well. It seems there must've been a faulty MSI during a preview phases when the 6.1-preview packages were renamed to `6-preview. `6.1.0` correctly removes the context menu on uninstall. Since this is a preview build, I'd advise to manually remove the left-over registry keys, you can find them [here](https://github.com/PowerShell/PowerShell/blob/master/assets/Product.wxs)

**Comment by CoolOppo** [comment]
I also have been dealing with this for months. Wish someone would whip up a quick tool to automate this as it's very annoying for hundreds of people to have to go to their registry to fully remove a program.

**Comment by bergmeister** [comment]
PR #8496 has been made to fix this, can you report which version. Otherwise this is just the nature of previews that some previews might have bugs in them (I saw it generally working but there were some 'bad' versions in the past that caused that)

**Comment by KalleOlaviNiemitalo** [comment]
I saw a similar problem when upgrading from 6.2.0 to 7.0.0-preview.1:

1. Install PowerShell-6.2.0-win-x64.msi
2. Install PowerShell-7.0.0-preview.1-win-x64.msi
3. Uninstall 6.2.0
4. Repair 7.0.0-preview.1, just in case the uninstallation of 6.2.0 damaged it

After those steps, I had duplicate registry keys, e.g. `HKEY_LOCAL_MACHINE\SOFTWARE\Classes\DesktopBackground\Shell\PowerShell6x64` and `HKEY_LOCAL_MACHINE\SOFTWARE\Classes\DesktopBackground\Shell\PowerShell7-previewx64`. The PowerShell6x64 keys ought to have been deleted. I presume Windows Installer did not delete them because the component GUID was not changed.

[This comment](https://github.com/PowerShell/PowerShell/pull/8496#issuecomment-449071069) says PowerShell intends to switch from MSI to MSIX instead of frobbing the component GUIDs. Is that still going to happen before the 7.0.0 release?

(By the way, I spent a while searching docs.microsoft.com for information on the `HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Directory\ContextMenus` key. However, it turns out to be referenced by `ExtendedSubCommandsKey` values of other Registry keys, rather than specially recognized by the shell.)

**Comment by chucklu** [comment]
After installing `PowerShell-7.0.0-preview.3-win-x64.msi`, the previous preview context menu looks weird. And I have checked the `C:\Program Files\PowerShell\6-preview`, it might empty by the Powershell7-preview installer.
https://github.com/PowerShell/PowerShell/issues/7826#issuecomment-525013525
![image](https://user-images.githubusercontent.com/3004057/63922081-8fdba900-ca76-11e9-8938-a6dcb369c7ab.png)

**Comment by maicWorkGithub** [comment]
![11png](https://user-images.githubusercontent.com/15863224/77027122-534eab00-69d0-11ea-94b8-4a45026dc458.png)

uninstalled `6` and `7-preview`, looks awful...

**Comment by bergmeister** [comment]
Please refer to this comment for manually removing left-overs https://github.com/PowerShell/PowerShell/issues/12105#issuecomment-598486477
In issue #12011 a potential solution to this is being discussed.

**Comment by maicWorkGithub** [comment]
@bergmeister still there
```
PS C:\WINDOWS\system32> $version = '7-previewx64'
PS C:\WINDOWS\system32>
PS C:\WINDOWS\system32> Remove-Item -WhatIf -Recurse "registry::HKEY_CLASSES_ROOT\Directory\shell\PowerShell$version",
>>                              "registry::HKEY_CLASSES_ROOT\Directory\ContextMenus\PowerShell$version",
>>                              "registry::HKEY_CLASSES_ROOT\Directory\Background\shell\PowerShell$version",
>>                              "registry::HKEY_CLASSES_ROOT\Drive\shell\PowerShell$version"
WhatIf: 正在目标“项: HKEY_CLASSES_ROOT\Directory\shell\PowerShell7-previewx64”上执行操作“删除键”。
WhatIf: 正在目标“项: HKEY_CLASSES_ROOT\Directory\ContextMenus\PowerShell7-previewx64”上执行操作“删除键”。
Remove-Item : 找不到路径“HKEY_CLASSES_ROOT\Directory\Background\shell\PowerShell7-previewx64”，因为该路径不存在。
所在位置 行:1 字符: 1
+ Remove-Item -WhatIf -Recurse "registry::HKEY_CLASSES_ROOT\Directory\s ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKEY_CLASSES_RO...ell7-previewx64:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

WhatIf: 正在目标“项: HKEY_CLASSES_ROOT\Drive\shell\PowerShell7-previewx64”上执行操作“删除键”。
PS C:\WINDOWS\system32> $version = '6'
PS C:\WINDOWS\system32> Remove-Item -WhatIf -Recurse "registry::HKEY_CLASSES_ROOT\Directory\shell\PowerShell$version",
>>                              "registry::HKEY_CLASSES_ROOT\Directory\ContextMenus\PowerShell$version",
>>                              "registry::HKEY_CLASSES_ROOT\Directory\Background\shell\PowerShell$version",
>>                              "registry::HKEY_CLASSES_ROOT\Drive\shell\PowerShell$version"
Remove-Item : 找不到路径“HKEY_CLASSES_ROOT\Directory\shell\PowerShell6”，因为该路径不存在。
所在位置 行:1 字符: 1
+ Remove-Item -WhatIf -Recurse "registry::HKEY_CLASSES_ROOT\Directory\s ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKEY_CLASSES_RO...ell\PowerShell6:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Remove-Item : 找不到路径“HKEY_CLASSES_ROOT\Directory\ContextMenus\PowerShell6”，因为该路径不存在。
所在位置 行:1 字符: 1
+ Remove-Item -WhatIf -Recurse "registry::HKEY_CLASSES_ROOT\Directory\s ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKEY_CLASSES_RO...nus\PowerShell6:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Remove-Item : 找不到路径“HKEY_CLASSES_ROOT\Directory\Background\shell\PowerShell6”，因为该路径不存在。
所在位置 行:1 字符: 1
+ Remove-Item -WhatIf -Recurse "registry::HKEY_CLASSES_ROOT\Directory\s ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKEY_CLASSES_RO...ell\PowerShell6:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Remove-Item : 找不到路径“HKEY_CLASSES_ROOT\Drive\shell\PowerShell6”，因为该路径不存在。
所在位置 行:1 字符: 1
+ Remove-Item -WhatIf -Recurse "registry::HKEY_CLASSES_ROOT\Directory\s ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKEY_CLASSES_RO...ell\PowerShell6:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
```

**Comment by chucklu** [comment]
@maicWorkGithub You could try to remove the context menu by [Easy Context Menu 1.6](https://www.sordum.org/files/easy-context-menu/ec_menu.zip).
![image](https://user-images.githubusercontent.com/3004057/77133488-2d8fd780-6a9e-11ea-8018-4b2ef4cd10d4.png)
select the context menu you want to remove, and click delete
![image](https://user-images.githubusercontent.com/3004057/77133524-44362e80-6a9e-11ea-99bc-df9292c94470.png)

**Comment by chucklu** [comment]
After installing PowerShell-7.0.0-win-x64.msi, the PowerShell preview 7.0 was uninstalled, but the context menu was kept.
![image](https://user-images.githubusercontent.com/3004057/77138774-456f5780-6aae-11ea-9fc9-9ba1ee2eb809.png)
Then I removed the context menu "PowerShell 7-preview" by Easy Context Menu 1.6.

**Comment by chucklu** [comment]
manually remove the menu by [Easy Context Menu 1.6](https://www.sordum.org/files/easy-context-menu/ec_menu.zip).
