### ISSUE TITLE
Autocompletion gives no results for $PSItem / $_ in Catch blocks

### ISSUE THREAD

**Issue by vexx32** [PowerShell/PowerShell#7828]
Despite the fact that catch blocks should always receive an `ErrorRecord` object as the `$_` or `$PSItem` value, there is no autocompletion / type inference performed for its properties, nor those of the Exception and/or InnerExceptions it contains.

Steps to reproduce
------------------

```powershell
try {
    throw "nope"
}
catch {
    $PSItem.{tab}
}
```

Expected behavior
-----------------

```none
    $PSItem.CategoryInfo      # And cycle through list of ErrorRecord properties on subsequent presses
```
(I know there's a programmatic way to get completion results, but I'm not familiar enough with how it works to be able to put that together at present.)

Actual behavior
---------------

```none
    $PSItem.                 # no completion results offered whatsoever
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Related #3373

**Comment by BrucePay** [comment]
@iSazonov I'm not sure why this is marked as a question. It sounds like an enhancement request to me.
