### ISSUE TITLE
Test-ModuleManifest does not populate the NestedModules field

### ISSUE THREAD

**Issue by maddieclayton** [PowerShell/PowerShell#7833]
When I run the Test-ModuleManifest cmdlet with a psd1 file that has a NestedModules field, it returns null for NestedModules (even though the dll exists and is in the correct location).  This results in Update-ModuleManifest commenting out the existing NestedModule fields when I try to update just the version.  This is causing massive issues with our versioning scripts when trying to update from PowerShell 5.1 to PowerShell 6.0.  Running this in PowerShell 5.1 with the same files works as expected.  When I pulled down PowerShell to try to debug this, I saw that NestedModules was set correctly here: https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs#L2041, but not set in moduleInfo before moduleInfo was returned here: https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs#L2800.

Steps to reproduce
------------------

```powershell
$a = Test-ModuleManifest -Path <path to module with filled out nestedmodules field>
$a.NestedModule # Returns nothing
```

Expected behavior
-----------------

```none
$a = Test-ModuleManifest -Path <path to module with filled out nestedmodules field>
$a.NestedModule # Returns correct Nested Modules
```

Actual behavior
---------------
Returns nothing
```none

```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.4
PSEdition                      Core
GitCommitId                    6.1.0-preview.4
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@maddieclayton Please check with latest build like 6.1 GA.

**Comment by maddieclayton** [comment]
@iSazonov Same issue with 6.1.  I can also repro when I pull down PowerShell and build it locally.

**Comment by maddieclayton** [comment]
@iSazonov Ping - I can created a workaround for this using Set-Content, but I'd really like to use the Update-ModuleManifest as this is what the cmdlet was created for.

**Comment by iSazonov** [comment]
@maddieclayton Thanks for update. Could you please compare with Get-Module result? Is there problem too?

**Comment by SteveL-MSFT** [comment]
Not repro'ing for me, need more detailed steps/information:

```powershell
PS /Users/steve/test> "" > foo.psm1                                                       
PS /Users/steve/test> New-ModuleManifest -Path ./nestedmodule.psd1 -NestedModules foo.psm1
PS /Users/steve/test> $a = Test-ModuleManifest ./nestedmodule.psd1                        
PS /Users/steve/test> $a.NestedModules

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        foo                                 
```

**Comment by maddieclayton** [comment]
Okay, I steadily copied over fields from the psd1 I was using into a new module manifest, and figured out where this issue is.  If any of these fields are ' * ', the nested module will be correctly found, but if all are not ' * ', it will not find the nested module:
```
# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = '*'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'
```
Easiest repro I can get is: 
```
PS C:\Users\maclayto\Documents> New-ModuleManifest -Path ./nestedmodule1.psd1 -NestedModules foo.dll -FunctionsToExport @() -CmdletsToExport @() -VariablesToExport @() -AliasesToExport @()
PS C:\Users\maclayto\Documents> $a = Test-ModuleManifest .\nestedmodule1.psd1
PS C:\Users\maclayto\Documents> $a.NestedModules
PS C:\Users\maclayto\Documents>
```
Let me know if you can repro using these steps.

**Comment by SteveL-MSFT** [comment]
The detailed repro steps helped to isolate the root cause.  Thanks!
