### ISSUE TITLE
Inquire on the Test-Json command. Allowance to use in a product that needs to support PS v6.1-

### ISSUE THREAD

**Issue by larssb** [PowerShell/PowerShell#7852]
This is a polite request on an allowance to use the [Test-Json](https://github.com/PowerShell/PowerShell/blob/53e6ec6eadc2f363fc671e96b34ade4dda3fe8eb/src/Microsoft.PowerShell.Commands.Utility/commands/utility/TestJsonCommand.cs) cmdlet code.

I'm doing a project named [HealOps](https://github.com/larssb/HealOps) and it needs to support nodes running PowerShell versions below v6.1 (the version wherein the Test-Json cmdlet is included). Therefore, it would be wonderful if I could re-use the Test-Json code you did @iSazonov. However, can I? Am I allowed to do so? I know it is a MIT license and by reading the license text I get the impression that I can. As long as I include the license disclaimer.

So, would it be okay? Thank you very much.

**Comment by iSazonov** [comment]
@larssb Yes, you can re-use the code. See https://github.com/PowerShell/PowerShell/issues/7279#issuecomment-417146225

> the recommendation is to attribute in a top level ThirdPartyNotices.txt file


Also we support side-by-side scenarios and you could redistribute latest PowerShell Core build (we have zip package) and latest Pester to target systems.

**Comment by iSazonov** [comment]
> what to write in this file 

Look the file in the PowerShell Core repo. (There is copies of original license texts).

> E.g. by downloading the NuGet packages. Or????

Yes, you need to reference the NuGet packages to compile Test-Json.
