### ISSUE TITLE
ConvertTo-/Export-CSV should support -Depth 

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell#7858]
Apologies for the pithy report, doing this at Ignite 

We support -Depth for Clixml, JSON, and XML. We should support it for CSV. 

Steps to reproduce
------------------

```powershell

```

Expected behavior
-----------------

```none

```

Actual behavior
---------------

```none

```

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by vexx32** [comment]
... *how*, exactly? Take your time, enjoy Ignite, but...

CSV as a format in general has always been about a flat table of data. How would you propose extending it to support nested items?

**Comment by BrucePay** [comment]
Per @vexx32 I am also extremely curious about this request. i have no trouble imagining how one could extend the format. I have more trouble with understanding why one would do so when there are already so many existing hierarchical formats (XML, JSON, YAML, TOML, the list goes on...)

**Comment by iSazonov** [comment]
I wonder too. For Import/Export-Csv we could consider `-MaxCount`. This might be useful for script debugging if csv files is large.

**Comment by vexx32** [comment]
I mean, maybe? But `Select-Object -First $X` is already perfectly capable of that, no?

**Comment by SteveL-MSFT** [comment]
@joeyaiello too many beers?

**Comment by potatoqualitee** [comment]
mannnnn i'da loved this
