### ISSUE TITLE
Feature: built-in update service

### ISSUE THREAD

**Issue by Allexxann** [PowerShell/PowerShell#7864]
Simply put: a cmdlet, which when ran checks for latest version of PSCore, and downloads and installs it, if there's a new release.
WindowsPS is updated via OS update system, but Core is only in manual mode, frustrating.

**Comment by vexx32** [comment]
I have heard the occasional whisper about PS Core potentially also being pulled into a Windows Update sequence, where if you have it installed it would allow you to get updates via that channel. Not sure if that's still on the cards or how far away it would be, though.

**Comment by chuanjiao10** [comment]
Should A key upgrade,or automatic silent upgrade, .NET framework and powershell #5490

**Comment by kvprasoon** [comment]
I have a script to do this. I use [this](https://www.powershellgallery.com/packages/Upgradepwsh/1.0.2) for upgrading it now on windows.

**Comment by kilasuit** [comment]
this should now be closed as it has been duplicated in#8663
