### ISSUE TITLE
PS Core on Mac - weird prompt issue PS$<5>$<5>

### ISSUE THREAD

**Issue by punkrokk** [PowerShell/PowerShell#7865]
If it is a bug report:
- make sure you are able to repro it on the latest released version. 
You can install the latest version from https://github.com/PowerShell/PowerShell/releases
- Search the existing issues.
- Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- Refer to the [known issues](https://docs.microsoft.com/powershell/scripting/whats-new/known-issues-ps6?view=powershell-6).
- Fill out the following repro template:

If it's not a bug, please remove the template and elaborate the issue in your own words.
-->

Steps to reproduce
------------------

brew cask install powershell

Expected behavior
-----------------

Normal prompt. When typing command you can read the text. 

Actual behavior
---------------

Strange behavior when typing commands: 
I just typed the string 'Install'. Below is what happened: 

![image](https://user-images.githubusercontent.com/1099386/46085154-5f5b0300-c173-11e8-8906-6456e57ebacb.png)

Environment data
----------------

```powershell
> $PSVersionTable
$<5>
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Darwin 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0




```

**Comment by SteveL-MSFT** [comment]
@punkrokk this doesn't repro for me, can you tell me what terminal you are using and the value of the TERM env var?

**Comment by punkrokk** [comment]
No longer an issue.

**Comment by brian-g** [comment]
This is happending for me on the latest version of Powershell and the latest MacOS. The value of my TERM environment variable is vt100 and it is happening on Terminal, Warp and iTerm2.
