### ISSUE TITLE
Variable comparsion delivers strange results.

### ISSUE THREAD

**Issue by logg-sar** [PowerShell/PowerShell#7866]
Hi there

maybe I´m wrong, but for me its absurd.

I would like to compare two variables. Therefore i´m using -like

```
$a="5"
$b="5"
if ($a -like "*$b*") {Write-Host equal} else {Write-Host not equal}
```
Results **equal** - which is correct

```
$a="5"
$b="1"
if ($a -like "*$b*") {Write-Host equal} else {Write-Host not equal}
```
Results **not equal** - which is correct

```
$a="5"
Remove-Variable b
if ($a -like "*$b*") {Write-Host equal} else {Write-Host not equal}
```

Results **equal** - which is obviously wrong

Without the * its working
```

$a="5"
Remove-Variable b
if ($a -like "$b") {Write-Host equal} else {Write-Host not equal}
```
Results **not equal** - which is correct

Its my fallacy?

Oh

 $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.2485
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2485
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by mklement0** [comment]
If `$b` is undefined (and `Set-StrictMode -Version 1` or higher is _not_ in effect), it defaults to `$null`.

In turn, `$null` is converted to the _empty string_ in a string context (`"..."`).

Therefore, with `$b` undefined:

```powershell
$a -like "*$b*"
```

is the same as:

```powershell
$a -like '**'
```

which is the same as 

```powershell
$a -like '*'
```

which, as expected, is `$True` for _any_ (scalar) LHS.

**Comment by logg-sar** [comment]
Ok, got it.
Thank you
