### ISSUE TITLE
Introduce a -matchall operator that finds *all* regex matches, to complement -match

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#7867]
`-match` is a handy regex-matching operator, but it is limited to finding (at most) _one_ match, as afterwards reflected in the automatic `$Matches` variable (with a scalar LHS) or directly returned (with an array-valued LHS).
Additionally, the ability to retrieve the matching part of the input and any capture-group values is lost with an array-valued LHS, because `$Matches` is then not populated.

In order to find _all_ matches of a given regex, you currently have two options:

* Pipe to `Select-String -AllMatches`, but that is inefficient for matching (collections of) strings already in memory.

* Use .NET directly, via the [`[regex]::Matches()`](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.matches#System_Text_RegularExpressions_Regex_Matches_System_String_System_String_) method, but that makes for an awkward transition from the PowerShell-native `-match` operator.

Therefore, a `-matchall` (`-imatchall`, `-cmatchall`) operator could be introduced, as a PowerShell-friendly wrapper for the `[regex]::Matches()` method

```powershell
# WISHFUL THINKING

# Scalar LHS; returns a collection of 2 matches
'foo' -matchall 'o'
# Array LHS; returns 2 collections of 2 matches each
'foo', 'baa' -matchall 'o|a'
```

could be the equivalent of:

```powershell
# Scalar LHS
[regex]::matches('foo', 'o')
# Array LHS
[regex]::matches('foo', 'o|a'), [regex]::matches('baa', 'o|a')
```

That is, the output would be either a single [`[System.Text.RegularExpressions.MatchCollection]`](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.matchcollection) instance, or an array of them, each of which contains one [`[System.Text.RegularExpressions.Match]`](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.match) instance _per match_. 
A `[System.Text.RegularExpressions.Match]` instance stringifies to the matching part of the input string, if any, and contains capture-group values as well as additional metadata about the match.

In essence, this is also what you get when you access the `.Matches` property of the `[Microsoft.PowerShell.Commands.MatchInfo]` instances returned by `Select-String -AllMatches` (though in the case of `Select-String` an `[object[]]` array of `[System.Text.RegularExpressions.Match]` is returned instead of a `[System.Text.RegularExpressions.MatchCollection]`  instance).

Environment data
----------------

Written as of:

```powershell
PowerShell Core 6.1.0
```

**Comment by vexx32** [comment]
100% yes, this would be awesome to have!

**Comment by MaximoTrinidad** [comment]
I agree!  That would be VERY Useful!!
:)

**Comment by BrucePay** [comment]
Just to complete the specification for this:
 
1. Everyone is OK with returning the raw match collections and don't expect anything additional being done to the collections/objects correct? (I just want to make sure.) 

2. Question: in the case where there is an array on the LHS, what should be the result type of the collection of `MatchCollection`s?  `Collection<MatchCollection>` ?

3. The `Matches` method takes up to 4 arguments, including Regex options and a timeout. We should support those as well so it would look like:
```powershell
$strings -matchall 'pattern'[,<options>[,<timeout>]]
```

4. The "default" operator `-matchall`  would be case insensitive unless overridden through options, with `-imatchall` and `-cmatchall` variants. 

5. Not matching is not considered a failure so `$?` is always true afterwards.

6. `$Matches` is not set by this operator.

7. TBD - we need to figure out which language modes this operator is available in. Probably the same as `-match` but we should still think about it.

Have I missed anything?

**Comment by p0W3RH311** [comment]
```
PS> 'abc' -matchall '(.)'
PS> $matches[0] # abc
PS> $matches[1] # a
PS> $matches[2] # b
PS> $matches[3] # c
```

**Comment by mklement0** [comment]
Thanks for helping to flesh this out, @BrucePay.

**Re 1, output type:**

Outputting a `MatchCollection` instance (loosely speaking, an array of `Match` instances)  is certainly easiest and fastest, but perhaps for consistency with the automatic `$Matches` variable that it should be an _array of `[hashtable]`s_ (whose entry `0` contains the full match, and the other entries the capture-group matches, as in `$Matches`).

On the flip side:

* Not all metadata will be available - but perhaps that won't be a problem in practice.
* `[hashtable]`s, unlike `Match` instances, do not stringify meaningfully, so the individual matches cannot be used as-is in expandable strings - though @vexx32's suggestion of having an option to return strings only could address that (see below).

**Re 2, collection output type with array-valued LHS:**

Again, for consistency, I suggest outputting a regular `[object[]]` array (which, combined with the suggestion above, would yield an array whose elements are hashtable arrays).

**Re 3, optional operands:**

My vote is _not_ to implement the options parameter (and, by extension, the timeout parameter), because it introduces complexity that may be confusing and not worth the effort:

* For instance, the `IgnoreCase` option could cause confusion with the implied case-insensitivity of `-matchall` and even be at odds with using `-cmatchall`; ditto for `CultureInvariant`.

* For those in the know, using _inline options_ as _part of the regex_ also provides access to the options (at least the most important ones), if desired (e.g., `` "a`nb" -match '(?s)^.*$' `` yielding `$True` due to inline option `(?s)` causing `.` to match newlines too).

* The timeout option strikes as too obscure a feature to warrant inclusion in PowerShell.

However, @vexx32 's suggestion of introducing an optional operand to return strings only is worth considering:

@vexx32, can you elaborate on that? Have each match be an array of strings whose 1st element is the overall match, with subsequent elements containing the capture-group matches? Note that you'd lose access to capture-group matches by _name_ that way (if applicable).  
So with a scalar LHS and multiple matches you'd get an array of string arrays?

**Re 4, case-insensitivity by default:**

👍

**Re 5., setting `$?` to `$True`:**

👍- it is consistent with `-match`.

**Re 6, not setting `$Matches`:**

👍

**Comment by mklement0** [comment]
@p0W3RH311 

Indexing into `$Matches` is already being used with `-match` to access the capture-group matches of a _single_ match:

```powershell
PS> $null = 'abc' -match '(.)'; $matches

Name                           Value
----                           -----
1                              a
0                              a
```

**Comment by vexx32** [comment]
@mklement0 I was thinking that for simplicity it would be lovely to simply have an optional second param or a secondary parameter (e.g., `-rawmatches`/`-rmatchall` perhaps?) that simply outputs an array of matched strings. So, as a very basic example:

```powershell
$String = "testing, testing"
$String -rmatchall '.'
# outputs: @('t', 'e', 's', 't', 'i', 'n', 'g' ...) (etc)
```
This would allow almost the mirror operation to `-split` where instead of targeting pieces to remove in order to break apart a string, you target pieces you want to keep, and it gives you the pieces in a nice and simple array. 

For array valued LHS (in *both* this raw-case and the above initial idea) I would defer to `-split`'s default handling of LHS array for consistency. I believe that would generally result in a flat array.

You are correct in that having a "raw matches" sort of parameter would remove the ability to target matches by name, but if you're using it specifically there's unlikely to be a reason to name your matches. 😄  (you may of course choose to do so regardless for clarity in the regex, but that's another story)

**Comment by ivanshen** [comment]
Is this issue still available? I would like to work on this issue.

**Comment by vexx32** [comment]
Have at it! 💖

**Comment by mklement0** [comment]
Following up from #11755: If `-allmatches` returns `[System.Text.RegularExpressions.Match]` instances (at least by default), you'll also be able to use it indirectly to get detailed information about a _single_ (the first) match, which `-match` with the `$Matches` variable won't give you:

```powershell
PS> ('hello' -allmatches 'e')[0]  # same as: [regex]::Match('hello', 'e')

Groups   : {0}
Success  : True
Name     : 0
Captures : {0}
Index    : 1
Length   : 1
Value    : e
```

**Comment by mklement0** [comment]
@SteveL-MSFT, now that the `Hacktoberfest-Accepted` label is obsolete, can you please restore the `Up-for-Grabs` label and also add the `KeepOpen` label?

**Comment by mklement0** [comment]
Thank you, @iSazonov.
