### ISSUE TITLE
Can we hide obsolete or internal-use-only helper parameters from syntax diagrams?

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#7868]
`Format-Hex`'s `-Raw` switch is obsolete in PowerShell Core - it has no effect whatsoever and is only retained for backward compatibility with Windows PowerShell v5.1 (backstory [here](https://github.com/PowerShell/PowerShell/pull/3320)).

(As an aside: This fact is [not documented](https://github.com/PowerShell/PowerShell-Docs/issues/1940),  nor was the parameter's (fairly obscure) original purpose ever documented for v5.1.)

Explaining the obsolescence in the documentation will go a long way, but I wonder if there is/should be a mechanism to _hide_ a parameter from the _syntax diagram_, so that its continued, pointless presence doesn't cause confusion / isn't a distraction when you run `Format-Hex -?` or `Get-Command Format-Hex -Syntax`, for instance.

The ability to hide parameters would in general also be useful for helper parameters that are solely meant to be used by a given cmdlet itself in recursive invocations, for instance.

Environment data
----------------

Written as of:

```powershell
PowerShell Core 6.1.0
```

**Comment by vexx32** [comment]
Something fairly simple should be in place for this. An `[Obsolete()]` parameter attribute, perhaps?

**Comment by iSazonov** [comment]
I'll try it today.

**Comment by mklement0** [comment]
Thanks for taking this on, @iSazonov.

What, specifically, will the effects of using `System.ObsoleteAttribute` be to PowerShell users?
Will it hide the parameter from the syntax diagrams, as suggested?

**Comment by iSazonov** [comment]
#7877 doesn't hide the parameter from the syntax diagrams. If #7877 will be accepted it will allow to resolve the issue on next step.
