### ISSUE TITLE
MS-WSMAN set to empty when connecting to EXO with pwsh

### ISSUE THREAD

**Issue by BellaLi** [PowerShell/PowerShell#7870]
Steps to reproduce
------------------

Download exchange online connector and try to connect with PowerShell 6.1.0 on Windows.

```powershell
ipmo .\CreateExoPSSession.ps1
Connect-EXOPSSession
```

Expected behavior
-----------------
MS-WSMAN cookie should be set, as Windows PowerShell do.
Set-Cookie: MS-WSMAN=admin@M365x361429.onmicrosoft.com=rJqNiZqNgayxya+tz8uyvcvMycrRkZ6Sj42bz8vRj42Qm9GQiouTkJCU0ZyQkoHOxsvMzM/IzsvJgc3PzsfSz8jSz8urz8/FysjFz8c=; expires=Wed, 04-Jul-2018 00:57:08 GMT; path=/PowerShell-LiveID; secure; HttpOnly

```none

```

Actual behavior
---------------

With fiddler to observe the traffic, I found MS-WSMAN empty in Response Header.

Cookies / Login
Set-Cookie: MS-WSMAN=; expires=Mon, 26-Sep-1988 18:01:02 GMT; path=/PowerShell-LiveID; secure; HttpOnly

The same symptom is also observed on Linux.

[Session: 3 Date: 2018-09-19 18:24:58.0915427Z]
POST /PowerShell-LiveId?BasicAuthToOAuthConversion=true;PSVersion=6.1.0 HTTP/1.1
Connection: Keep-Alive
Content-Length: 1485
Content-Type: application/soap+xml;charset=UTF-8
Authorization: Basic
…..
Host: outlook.office365.com:443
Cookie: MS-WSMAN=

```none

```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
This is working for me:

```powershell
$usercredential = Get-Credential
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $UserCredential -Authentication Basic -AllowRedirection
```

I see in Fiddler that the cookie is being set (which is set by WinRM, not PowerShell).  I suspect the problem may be in the cmdlet you're using.
