### ISSUE TITLE
install-powershell.sh should autodetect whether to use curl or wget

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/PowerShell#7872]
Turns out minimalized versions of Amazon Linux 2 (e.g. the container) do not have wget - same as OSX.

Use command -v to test which one is present.

If neither is present, give instructions to download the second script manually and rerun the primary script.

Code is here: https://github.com/PowerShell/PowerShell/blob/master/tools/install-powershell.sh#L143-L147

I am interested in doing this.

**Comment by SteveL-MSFT** [comment]
@DarwinJS consider it yours!  Thanks!

**Comment by DarwinJS** [comment]
Resolved by merged PR.
