### ISSUE TITLE
Should _script in Tokenizer.cs be ReadOnlyMemory<char> instead of string?

### ISSUE THREAD

**Issue by vexx32** [PowerShell/PowerShell#7887]
From what I have read, it seems like using `ReadOnlyMemory<char>` instead of `string` could potentially offer some performance gains in the tokenizer if we use it for the `_script`:

https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/parser/tokenizer.cs#L519

(N.B.: This would obviously require much more extensive changes than just that. We'd need to make more use of the `.Span` and `.Span.Slice()` instead of `stringbuilder` as the tokenizer currently does, for example.)

However, I lack sufficient understanding of how `{ReadOnly}Memory<T>` functions in practice to be able to say if it's just... better off as it is currently. Given what I have been reading thus far, it seems like it might be worth the change. However:

1. Unlike `{ReadOnly}Span<T>`, `{ReadOnly}Memory<T>` cannot be directly indexed into; its `.Span` property must be accessed in order to be able to index into the contained memory / values. 
    * Continually pulling the `.Span` from `Memory<T>` as the tokenizer might need to for its successive indexing may incur *more* overhead than allocating strings, building new strings via StringBuilder, etc.; I don't know enough of its behaviour to really grok how they'd compare just yet, or if there's a better way to lay out the tokenizer's processes in general to minimise this potential issue.
2. This would require changing several significant portions of how the tokenizer functions to `.Slice` the spans and pass them along instead of utilising `StringBuilder` objects, which *should* be more efficient at least in those areas once the initial `ReadOnlySpan<char>` has been allocated.

I have had a bit of a play around with how the code itself would look, and I have yet to get it working completely with `ReadOnlyMemory`

The changes that are required are more extensive than I've presently been able to figure out. I think I can make it work, but I've yet to get a working prototype branch.

I would be interested in the opinions of you folks who've been working on this project for a long time and/or have much more experience with `Memory<T>` and `Span<T>` than I do.

* Is this worth the time investment to figure out, in your opinion?

* Would you expect it to be more efficient than the current method (allocating a potentially huge string and indexing one character at a time)? 

* Would it just be a lot better to simply have `_script` be turned into `char[]` instead of `string`?

Look forward to your feedback! ❤️ 

cc @daxian-dbw @iSazonov as y'all have been enormously helpful as I've been tinkering already and you probably know this much better than I!

**Comment by iSazonov** [comment]
I've looked at this before and found that this code (parser and tokenizer) is extremely optimized. 

Before trying to improve this code, we need performance tests. I know that @daxian-dbw  had plans about this.

**Comment by iSazonov** [comment]
StringBuilder was optimized in .Net Core 2.0. It is very efficient.

**Comment by vexx32** [comment]
Yeah, I've no doubt StringBuilder is insanely fast, but -- if we didn't *need* to build the string? Just `.Slice()` the existing `Span<char>` or `Memory<char>` by indexes? I get the impression that it could be faster, potentially. Needs some careful planning, though, for sure. 😁

**Comment by iSazonov** [comment]
I looked at this code in PerfView and found it very efficient. I do not think that we will get a noticeable win here. There are much less effective parts in our code that need improvement.

We had an idea to implement Trivia (and also enhancements in classes). In this case, it was possible to combine this with improvements in parser and tokenizer.

**Comment by iSazonov** [comment]
Yes, we'll have Trivia RFC.
