### ISSUE TITLE
Breaking Change: Two PSGallery Entries

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/PowerShell#7888]
During an automated build, this command:
Install-Module Pester -MinimumVersion '4.0.5' -MaximumVersion '4.0.5' -Force -SkipPublisherCheck

Get's this error:
![image](https://user-images.githubusercontent.com/11597190/46230542-e7d5d100-c336-11e8-99cf-8b3e03f86e4e.png)

By the time I get to the machine for diagnosis, get-packagerepository only shows the regular entry for "PSGallery"

My code never creates a PSGallery2.

Is there some new background behavior with the new PowerShellGallery.com ?

**Comment by kilasuit** [comment]
@DarwinJS do you have any more information on this at all?

**Comment by DarwinJS** [comment]
No.  I just know this code is unchanged and I can't find that PSGallery2 exists when I get on the machine.

**Comment by DarwinJS** [comment]
I know I can fix it with '-Repository PSGallery' - but it would be a pain to need to do that on every install-module command.

**Comment by SteveL-MSFT** [comment]
@DarwinJS can you open an issue in https://github.com/powershell/powershellget repo?

**Comment by kilasuit** [comment]
Where is this on? As the version shown of PowerShellGet being 1.0.0.1 was the version that had many changes being shipped within different Insider builds of Windows 10.

Also this should really be filed on the PowerShellGet repository & not this one as it's an issue with PowerShellGet at first glance

Could you raise this over there and include the following further information

-  Windows OS version
