### ISSUE TITLE
Add-Type -Typedefinition fails with error "Unexpected exception: [The filename, directory name, or volume label syntax is incorrect]"

### ISSUE THREAD

**Issue by muthar** [PowerShell/PowerShell#7889]
We are referencing a PS1 file "Library.ps1" in another PS1 file "Feature.ps1" and invoking a function defined in the Library. The function has an optional parameter which is defined as an Enum Type using Add-Type -TypeDefinition within the same library.  The feature powershell file invokes the function without passing this optional enum parameter and we have noticed that it fails intermittently with the below error  :

Unexpected exception: [The filename, directory name, or volume label syntax is incorrect]. TRAP_DETAILS: ErrorFile [C:\Library.ps1], ErrorLine [29: Add-Type -TypeDefinition $EventType]

**Sample Code as below :`**

Below is the definition of EventType :

          $EventType = @"
              public enum EventType
              {
                  StartEvent,
                  EndEvent,
                  Informational,
                  Failure
              }
          "@
          
          Add-Type -TypeDefinition $EventType

          Function LibraryFunction
          {
          param([Parameter(Mandatory=$true)]
              $ID,
              [Switch]$parameter1,
              [Parameter(Mandatory=$false)]
              [EventType]$EventType,
              )

          Write-Host $ID
          }

Below is the way the function is being invoke in the feature file :

LibraryFunction -ID 3 -parameter1 

Could you help us in understanding why this error is being thrown intermittently? The code keeps failing in production with the above error and when we try the execution, the same code path executes fine. Any help is much appreciated!

**Comment by vexx32** [comment]
Try defining the `enum` inline without `Add-Type`:

```powershell
enum EventType
{
    StartEvent,
    EndEvent,
    Informational,
    Failure
}
```

I would conjecture that if this type is being loaded more than once in the same powershell session (script is being executed multiple times and trying to redefine the same type) there will be an error like this.

You may have to use `Import-Module` when loading this file and then execute the function as needed.

**Comment by mklement0** [comment]
@vexx32: Redefining the same type with `Add-Type` is normally not a problem - the redefinition attempts should be quiet no-ops.

Also, there is no obvious connection between the error message and `Add-Type`.
The error message relates to malformed filesystem paths, and the `Add-Type` call doesn't even involve any.

@muthar: Are you seeing this in Windows PowerShell, PowerShell Core, or both, and in what versions?
