### ISSUE TITLE
Add keyword completions for try/catch/throw/continue

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#7891]
From https://github.com/PowerShell/vscode-powershell/issues/703.

PowerShell apparently offers completions for some keywords, but not:
- `try`
- `catch`
- `finally`
- `continue`

Providing these would improve script authoring experience

**Comment by vexx32** [comment]
Tangentially related and in the same vein as #7828 -- would be nice to have completions for all common error handling cases. 😄

**Comment by Cirzen** [comment]
I would also request adding to this keywords for:

- `begin`
- `process`
- `end`

As autocompletion when writing these blocks for advanced functions frequently populates the editor with unintended code.
