### ISSUE TITLE
Powershell 6.1.0 on MacOS crashes with  "Segmentation fault: 11" when trying to 

### ISSUE THREAD

**Issue by fckbo** [PowerShell/PowerShell#7896]
Steps to reproduce
------------------

```powershell 6.1.0
install powershell
- brew update
- brew cask install powershell

run it
- pwsh

$cred=Get-Credential
Enter-PSSession -ComputerName '10.11.10.133' -Credential $cred -Authentication Negotiate
```
Then Powershell crashes with the message: 
Segmentation fault: 11

Expected behavior
-----------------

```
PowerShell should connect to remote system
```

Actual behavior
---------------

```
PowerShell crashes
```

Environment data
----------------
MacOS version: 10.13.6
Remote win 2016 server can be accessed from another Win2016 server with test-wsman, winrs and PowerShell

![image](https://user-images.githubusercontent.com/10832015/46250729-fad4c800-c440-11e8-9051-d4eb942d412f.png)
![image](https://user-images.githubusercontent.com/10832015/46250743-3f606380-c441-11e8-9fc2-15402c21efac.png)

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment]
It is not supported https://github.com/PowerShell/psl-omi-provider#connecting-from-linux-to-windows
Although this should not fall in "Segmentation fault" - "Platform is not supported" user friendly message is expected.

/cc @dantraMSFT

**Comment by fckbo** [comment]
Thx for your answer, 

reading the Microsoft documentation https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_remote_requirements?view=powershell-6, the "Basic Authentication Limitations on Linux and macOS
" chapter actually highlight NTLM as an alternative to https with basic auth. 
Is this documentation obsolete ?
Is

**Comment by PixleProgrambetaxl** [comment]
+1

**Comment by SteveL-MSFT** [comment]
We should fix the crash and return a better error message.  I believe NTLM and Kerberos is not supported on macOS due to unavailability of required libraries.  The doc should be updated.

**Comment by TravisEz13** [comment]
I cannot currently repro this issue:
```
Enter-PSSession : Connecting to remote server *** failed with the following error message : MI_RESULT_FAILED For more information, see the about_Remote_Troubleshooting Help topic.
At line:1 char:1
+ Enter-PSSession -ComputerName *** -Cred ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (tplunkhp.ntdev.corp.microsoft.com:String) [Enter-PSSession], PSRemotingTransportException
+ FullyQualifiedErrorId : CreateRemoteRunspaceFailed
```
