### ISSUE TITLE
[Feature] -Property parameter to support Child properties using dot operator

### ISSUE THREAD

**Issue by kvprasoon** [PowerShell/PowerShell#7898]
Just a thought, 

Below Objects for this example.
````
$r=[PSCUstomObject]@{
    Column1   = [PSCUstomObject]@{NColumn1='NR1';NColumns2='NR2'}
    Columns2 = 'R2'
}

$t=[PSCUstomObject]@{
Column1   = [PSCUstomObject]@{NColumn1='NR11';NColumns2='NR2'}
Columns2 = 'R2'}
````

What we have now
-----------------
```
compare $r.Column1.NColumn1 $t.Column1.NColumn1

#or

compare $r.Column1 $t.Column1 -Property NColumn1

#or
(gps|select -ExpandProperty starttime).day
```

What I am proposing
--------------------
````
compare $r $t -Property Column1.NColumn1

#or
Get-Process | Select-Object -Property StartTime.Day
````

Just a low priority/up-for-grabs feature request.

**Comment by iSazonov** [comment]
Please clarify - we already have `Compare-Object -Property`.

**Comment by kvprasoon** [comment]
My suggestion is not just for `Compare-Object` , see below use case for `Get-Process`

````
Get-Process | Select-Object -Property StartTime.Day

#instead of
(Get-Process | Select-Object -ExpandProperty StartTime).Day
#or
Get-Process | Select-Object -First 1 -ExpandProperty StartTime | Select-Object -ExpandProperty Day
````
I'm sure this will not be a huge value add, but just a thought.

**Comment by vexx32** [comment]
Even for things like Select-Object -Property this could be useful.

However, given that a property name that includes a period is currently a valid name, how is Select-Object to be able to distinguish the intent?

```powershell
$obj = [PSCustomObject]@{
    'Property.Name' = 'test'
    Property = [PSCustomObject]@{
        Name = 'this will not be selected'
    }
}

$obj | Select-Object -Property Property.Name

$Obj.'Property.Name'
$Obj.Property.Name # different to above!
```

So really, this can't be done neatly any way you slice it, because there's not really any 'invarid characters' in a property name. Anything that *might* be normally invalid or read differently can still be accepted as a property name by simply enclosing it in quotes.

**Comment by kvprasoon** [comment]
Yes, I know such property with dot can exist, but Just posted here when I got the thought.

**Comment by vexx32** [comment]
No worries... just wondering if you had any ideas on potential solutions.

Perhaps we could consider use of escape characters like the tilde a potential method here?

Given the above object example:

```powershell
$obj | Select-Object -Property 'Property`.Name'
```
But even then I suppose it's *possible* to use a tilde in a property name... 😕

**Comment by mklement0** [comment]
#6509 suggested the same feature in the context of `ForEach-Object` and `Where-Object` and ran into the same problem.

Arguably, interpreting `$obj | Select-Object Property.Name` as access to the _nested_  `.Property.Name` property is the much more common use case and should be the default, but changing that now would be a breaking change.

Even if we didn't have this backward-compatibility problem, we'd have to come up with an opt-in mechanism for the as-is interpretation of the name (where `Property.Name` _as a whole_ should be considered the (single) property name):

* Using single- or double-quoting for that is not really an option, given that in argument mode there's normally no distinction between arguments `foo.bar` and `'foo.bar'`.

* ``'foo`.bar'`` - a combination of a _literal_ string with an embedded _literal_ `` ` `` to be interpreted by the _target command_  as an escape char. -  would work in principle, but it is awkward.   
That said, this approach is already required if you want to escape metacharacters in wildcard expressions.

**Comment by kvprasoon** [comment]
@iSazonov Both are kind of same, I'm ok for having one issue for this.

**Comment by mklement0** [comment]
Thanks, @iSazonov. I've generalized the description of the linked issue to incorporate @kvprasoon's suggestion and also generalized the title.
