### ISSUE TITLE
Get-Date -Day NN parameter can overrun the number of days in a month, on short months, with unexpected output.

### ISSUE THREAD

**Issue by HumanEquivalentUnit** [PowerShell/PowerShell#7911]
The dates 31st September, or 30th February are invalid, but `Get-Date` allows you to ask for them. It only validates the -Day param in the range 1-31, but doesn't check the length of the month. Asking for the "last" days in a short month, overruns the end of the month and returns a datetime at the beginning of the next month, instead of an exception. This is inconsistent with other .Net DateTime and Get-Date behaviour:

```
[datetime]::new(2018, 2, 31)            # Exception
Get-Date '2018-02-31'                   # Exception
Get-Date -Year 2018 -Month 2 -Day 31    # returns a DateTime in March
``` 

Expected behavior
-----------------

An error, similar to trying the same thing with `[datetime]::new()`, e.g.

```Exception [..] "Year, Month, and Day parameters describe an un-representable DateTime."```

Actual behavior
---------------

Returning a date, but (surprise!) not the one requested.

Environment data
----------------

Happens on PS 6.1.0 Core release version on Linux and on PSv5.1 on Windows.

**Comment by chuanjiao10** [comment]
(Get-Date -Year 2018 -Month 9 -Day 1).AddDays(-1)
Powershell has more date types than bash, making calculations easy.

**Comment by iSazonov** [comment]
It is a breaking change.
/cc @SteveL-MSFT

**Comment by HumanEquivalentUnit** [comment]
Looking at the code, I don't think this was added deliberately. The cmdlet takes `DateTime.now` and then adds each parameter value (year, month, day, hour) as an offset to that. All of those have a consistent size (seconds in a minute, minutes in an hour, hours in a day) - except days in a month, which varies. Using the same offset calculation there is what sometimes overruns past the end of the short months.

It's inconsistent, and therefore probably a bug. It is a breaking change, not sure whether it's worth fixing:

```
[datetime]::new(2018, 2, 31)            # Exception
Get-Date '2018-02-31'                   # Exception
Get-Date -Year 2018 -Month 2 -Day 31    # DateTime in March
``` 

If it is worth it, here is a possible fix:

```
                // Day parameter can be 1-31, but some months have fewer days;
                // check against month length to avoid overrunning into next month.
                if (Day > DateTime.DaysInMonth(dateToUse.Year, dateToUse.Month))
                {
                    var e = new PSArgumentOutOfRangeException(
                                "Day",
                                Day,
                                "Day value is greater than the number of days in the month");

                    ThrowTerminatingError(
                        new ErrorRecord(e, "InvalidDate", ErrorCategory.InvalidArgument, null));
                }
```

(Is that a reasonable Exception to throw?)

**Comment by HumanEquivalentUnit** [comment]
@SteveL-MSFT Thank you for reviewing it; I have no specific need for it to be changed, so from my view this could be closed and left for the record.

I was about to say, is it worth adding to the Get-Date documentation as a caution - but it's already there. Places I should have looked first (sorry!).
