### ISSUE TITLE
APT unable to find powershell package on ubuntu 18.04 

### ISSUE THREAD

**Issue by abhi18av** [PowerShell/PowerShell#7949]
Hi Team Powershell,

I have a cloud instance running Ubuntu1804 on ARMv7 CPUs. 

Here's the output of my `lscpu` command

```
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           Marvell
Model:               2
Model name:          PJ4B-MP
Stepping:            0x2
CPU max MHz:         1333.0000
CPU min MHz:         666.5000
BogoMIPS:            50.00
Flags:               half thumb fastmult vfp edsp thumbee vfpv3 tls idiva idivt vfpd32 lpae
```

The problem I'm facing is that if though I've followed all the instructions for installing `powershell` via the Ubuntu ppa mentioned in the[ installation instruction page](https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-powershell-core-on-linux?view=powershell-6#installation-via-package-repository---ubuntu-1804) - `apt` is unable to find the package in the repository.

```
root@scaleway :~# apt install powershell -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package powershell
```

Could you please help me out a little bit ?

**Comment by SteveL-MSFT** [comment]
We currently only build arm32 packages for Raspbian and not Ubuntu so you won't find it published in the Microsoft repo (only for x64).

**Comment by abhi18av** [comment]
Thanks for the info Steve :)

Then in this case the only way forward is to manually install and use the
generic arm32 binary?

**Comment by SteveL-MSFT** [comment]
@abhi18av if you can help validate the existing linux-arm32 pkg works, we can consider publishing it to packages.microsoft.com

**Comment by abhi18av** [comment]
Yup, it works.

However the response time is a bit slow but works just fine :)

**Comment by SteveL-MSFT** [comment]
@abhi18av it's a bit slower on startup since crossgen isn't supported on arm32, but it's good to know it works.  Will have to see if the tooling we're using allows creating a .deb for arm32 before we can publish it on packages.microsoft.com.

cc @TravisEz13

**Comment by abhi18av** [comment]
That sounds great @SteveL-MSFT 👍 

Please feel free to close this issue as, for me, it has been answered sufficiently well.

Also, for testing on the arm32 infrastructure and ubuntu, I do recommend for you to use 
https://www.scaleway.com/pricing/#anchor_baremetal the C1 bare metal instance  :)
