### ISSUE TITLE
Does powershell support Termux?

### ISSUE THREAD

**Issue by myfreess** [PowerShell/PowerShell#7950]

**Comment by SteveL-MSFT** [comment]
Best that I can tell, Termux does two things:

1. terminal for Android - you should be able to use this to ssh to another machine and run PowerShell
2. Linux environment based on Debian/Ubuntu for Android - perhaps you can try the generic linux.tar.gz pkg we build and see if it works?

**Comment by myfreess** [comment]
@SteveL-MSFT  thanks！Is Powershell for linux a GUI program?

**Comment by SteveL-MSFT** [comment]
@myfreess no, PowerShell is a shell and thus works in the console

**Comment by CtrlShiftEscape** [comment]
I can't execute it, can anyone help?
`$ ls -l pwsh
-rwxrwxrwx    1 u0_a67   u0_a67       77172 Nov 14 05:08 pwsh
$ readelf -h ./pwsh
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           ARM
  Version:                           0x1
  Entry point address:               0xfb9d
  Start of program headers:          52 (bytes into file)
  Start of section headers:          75972 (bytes into file)
  Flags:                             0x5000402, Version5 EABI, hard-float ABI, <unknown>
  Size of this header:               52 (bytes)
  Size of program headers:           32 (bytes)
  Number of program headers:         9
  Size of section headers:           40 (bytes)
  Number of section headers:         30
  Section header string table index: 29
$ ls -l ./pwsh
-rwxrwxrwx    1 u0_a67   u0_a67       77172 Nov 14 05:08 ./pwsh
$ ./pwsh
bash: ./pwsh: No such file or directory
$`

**Comment by DRSDavidSoft** [comment]
If anyone's interested, this is indeed possible:

https://github.com/termux/termux-packages/issues/1729

**Comment by SteveL-MSFT** [comment]
I've heard PowerShell works within https://github.com/CypherpunkArmory/UserLAnd
