### ISSUE TITLE
PowerShell cannot find executable, but which and bash can

### ISSUE THREAD

**Issue by felixfbecker** [PowerShell/PowerShell#7953]
Steps to reproduce
------------------

I have this `PATH`:
```
/Users/felix/src/ps-nvm/vs/v10.10.0/bin:./node_modules/.bin:/usr/local/opt/qt/bin:/Users/felix/google-cloud-sdk/bin:/Users/felix/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Library/TeX/texbin:/usr/local/microsoft/powershell/6:/usr/bin:/bin:/usr/sbin:/sbin
```
`/Users/felix/src/ps-nvm/vs/v10.10.0/bin` contains a `node` binary:
```
-rwxr-xr-x  1 felix  staff  39631440 Sep  6 22:40 /Users/felix/src/ps-nvm/vs/v10.10.0/bin/node
```

Running `which node` correctly returns:

```
> which node
/Users/felix/src/ps-nvm/vs/v10.10.0/bin/node
```

And running `bash -c 'node'` also invokes node correctly.

I also checked that no other other directory in PATH contains a bad symlink named `node`.

Expected behavior
-----------------

Running `node` should invoke the NodeJS binary.

Actual behavior
---------------

PowerShell invokes the `Node` function from DSC.

`Get-Command node` returns this:
```powershell
> Get-Command node

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Node                                               0.0        PSDesiredStateConfiguration
```

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Darwin 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
This happens whenever the `PSDesiredStateConfiguration` module happens to be loaded, because its `Node` _function_ then takes precedence over the `node` _external utility_, based on the usual command-form-precedence rules.

(I'm not sure why and when, but in VSCode I have at times ended up with `PSDesiredStateConfiguration` imported, without my having done so explicitly.)

PowerShell still knows about the external utility, though, as running `Get-Command -All node` will show you.


```powershell
# If DSC isn't loaded, 'node' invokes the external utility by that name in $env:PATH
PS> Remove-Module -EA Ignore PSDesiredStateConfiguration; Get-Command node

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     node                                               0.0.0.0    /usr/local/bin/node

# Once DSC is loaded, its Node function takes precedence.
PS> Import-Module  PSDesiredStateConfiguration; Get-Command node

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Node                                               0.0        PSDesiredStateConfiguration

# Use -All to show all available command forms.
PS> Import-Module  PSDesiredStateConfiguration; Get-Command -All node

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Node                                               0.0        PSDesiredStateConfiguration
Application     node                                               0.0.0.0    /usr/local/bin/node
```

If this were Windows, you could use `.exe` to disambiguate, but on Unix-like platforms that's not an option.

**Comment by felixfbecker** [comment]
How could it have happened that I loaded this module? This happens to me on a fresh terminal instance

**Comment by mklement0** [comment]
The - obviously cumbersome - workaround:

```powershell
PS> & (Get-Command -CommandType Application node) --version # OK, calls Node.js
v10.7.0
```

POSIX-like shells have syntactic sugar (_quoting_ any part of the command name to request bypassing _aliases_) and built-in helper functions (`command`, which bypasses functions too) to deal with this scenario.

Perhaps we need something similar in PowerShell.

**Comment by felixfbecker** [comment]
`&(which node)` works fine too. But I don't want to use a workaround, what I really want to know is how DSC ends up in the session without me ever calling any command from it or importing it. I don't use DSC, but I use `node` all the time.

**Comment by mklement0** [comment]
@felixfbecker: The likeliest explanation is that something in your `$PROFILE` caused the module to be loaded - it doesn't happen for me, on any platform.

Try `pwsh -noprofile -command "get-command node"` to see if it happens without your profile as well.

**Comment by SeeminglyScience** [comment]
> (I'm not sure why and when, but in VSCode I have at times ended up with PSDesiredStateConfiguration imported, without my having done so explicitly.)

In VSCode, intellisense will import modules that are not already loaded for syntax/parameters/argument completers.

May not be related to the original issue, just wanted to clear that up.

**Comment by mklement0** [comment]
I appreciate the clarification, @SeeminglyScience.

**Comment by felixfbecker** [comment]
Is there a way to trace when modules get loaded?
