### ISSUE TITLE
Join-Path should accept an array of -ChildPath

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#7954]
When building long paths in a cross-platform way (and particularly if we're not sure of the provider), it would be very useful to be able to avoid chaining multiple calls to Join-path (which is currently a common practice).

I propose changing the -ChildPath parameter to accept a string array and be `ValueFromRemainingArguments` 

And then iterate over the values and produce one long path.

**Comment by thezim** [comment]
Isn’t that what AdditionalChildPath is for?

**Comment by kvprasoon** [comment]
Yes, it accepts value from remaining argument too... 🤔
@Jaykul ?

**Comment by rkeithhill** [comment]
Yeah, I thought @dlwyatt already implemented this.

**Comment by Jaykul** [comment]
😊

**Comment by thezim** [comment]
For what it is worth the [documentation](
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/join-path?view=powershell-6) is broken, the parameter is not in the syntax section currently. Odd as I added it some time [ago](
https://github.com/PowerShell/PowerShell-Docs/pull/1740).

**Comment by kvprasoon** [comment]
It got reverted by https://github.com/PowerShell/PowerShell-Docs/pull/2623
