### ISSUE TITLE
Question: .Net Core Roadmap: 2.2 vs 3.0

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#7956]
The current roadmap [here](https://github.com/dotnet/core/blob/master/roadmap.md) states that .Net Core 2.2 should go RTM in Q4 2018 but .Net Core 3.0 only in Q1 2019.
There are already official previews of 2.2 available [here](https://www.microsoft.com/net/download/dotnet-core/2.2) but 3.0 offers only daily bleeding edge builds.

What are the plans on using a newer version of .Net Core and which version will be the next targeted update?

**Comment by SteveL-MSFT** [comment]
@iSazonov is correct that we can't ship a 6.2 on an unsupported 3.0 release.  Based on .NET Core's current roadmap, 6.2 will likely be based on 2.2 and 6.3 would be on 3.0.
