### ISSUE TITLE
Ideas for a clean, direct regex mirror of -replace, to "keep the match"?

### ISSUE THREAD

**Issue by HumanEquivalentUnit** [PowerShell/PowerShell#7958]
An example regex thing I do is to extract the number out of this string: `"blah blah blah 456 blah blah"`.

The available options are all full of syntax, noise, and multiple steps:

1. `if ($text -match '(\d+)') { $matches[1] }`
1. `$text | select-string '\d+' | % matches | % value`
1. `[regex]::matches($text, '\d+').Value`
1. `$text -replace '.*?(\d+).*', '$1'`

But if I wanted to /drop/ the number from the string, there's a really clean short direct way to do it:

1. `$text -replace '\d+'`

NB. that in this example I could simply use `$text -replace '[^\d]'` , but coming up with an inverted regex often is not that simple. Especially if there's a string involved, so an inverted character class won't work. It often means separately matching the start and end, andleaving the middle bit unchanged, as I've tried to show in example number 4 above. 

This is a pattern I find myself using quite often in the shell, and it bugs me that there's a first class way to get rid of, and swap string content, but not exactly a first class mirror of that, a way to keep some string content. 

What I'm dreaming of, is an operator that works like the opposite of `-replace`, like this: 

1. `$text -keep '\d+'`

An operator which behaves like `[regex]::matches($text, '\d+').Value` - i.e. the result would be plain strings, not MatchInfo, not `$matches` being set somewhere off in memory. If there's one match there's one string output. If there's N matches, then N strings output. No position, no metadata, no nesting. If there's no matches, there's no output (it doesn't return `$false`). If it's used on an array of strings on the left, it will output the matches from each of them, not filtering the array.

Maybe it could take another parameter like `-split` does to return only the first N items, so

    PS C:\> "abc 123 def 456 ghi 789" -keep '\d+', 2
    123
    456

Binary operator `-keep` (or `-pluck`, `-getmatch`, `-gimme`, `-matchNgo`, `-extract`, `-matchvalues`, or whatever name).

Does that exist in other languages? Does anyone wish it did?

**Comment by HumanEquivalentUnit** [comment]
I wrote this independently before I saw issue #7867. That is still about outputting a chunk of metadata, which is not what I want, but there is talk in the comments of string output, I will chase this up there instead.

**Comment by jimbobmcgee** [comment]
You are pretty close with `$text -replace '.*?(\d+).*', '$1'`.  Have you considered:

```
$text -replace '(.*?)(\d+)(.*)', '$1$3'
```

i.e. Capture the prefix as Group 1, the number as Group 2 and the suffix as Group 3; then replace that match with the content of Group1 and Group 2

This tends to work best when there is only one match in the string.

Alternatively, an approach I sometimes like is the split/join:

```
($text -split '\d+') -join ''
```

i.e. Split the source string into an array of substrings, using your expression as the separator, then rejoin the array of substrings using an empty string as the separator.

I believe it has the effect you are looking for, but it depends how performant you need to be.  On a large source data, split/join will probably allocate a significant number of strings.
