### ISSUE TITLE
Pushing a configuration on linux using DSC does not work

### ISSUE THREAD

**Issue by lispmarc** [PowerShell/PowerShell#7976]
Hi
	I have a problem of getting DSC to work on Linux. 
My configuration is the following
	Linux : OpenSuse Leap 42.3
	OpenSSL version : OpenSSL 1.0.2j-fips  26 Sep 2016
	OMI version installed : omi-1.4.2-5.ssl_100.ulinux.x64.rpm
	DSC version installed : dsc-1.1.1-294.ssl_100.x64.rpm

The configuration that I want to push is 

Configuration SuseConfiguration {
    param ([string]$node)
    Import-DscResource -ModuleName nx

    Node $node {
        nxFile ExampleFile {
            DestinationPath = "/tmp/example/hello"
            Contents = "Hello World I'm Hall`n"
            Ensure = "Present"
            Type = "File"
        }
    }
}

When I use Start-DscConfiguration to push the configuration to my linux machine I get the error
Invalid CIM_Error object posted from provider
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimEx 
   ception
    + FullyQualifiedErrorId : OMI:MI_Result:1002

If I copy the generated mof file directly to the linux machine 
and run /opt/microsoft/dsc/Scripts/StartDscConfiguration.py I get the errors

/opt/omi/bin/omicli: result: MI_RESULT_INVALID_CLASS_HIERARCHY

/opt/omi/bin/omicli: result: Invalid CIM_Error object posted from provider

Any help is really appreciated

Marc Mertens

**Comment by SteveL-MSFT** [comment]
@kwirkykat can you help or add someone who can?

**Comment by lispmarc** [comment]
I found the origin of the problem in that the directory /tmp/example diddn't exists and the nxFile Resource will not create missing directories. It is still strange that omi-cli does give a total different error, not related to the real error. 

Marc Mertens
