### ISSUE TITLE
Correct path casing when performing `cd`

### ISSUE THREAD

**Issue by be5invis** [PowerShell/PowerShell#7977]
Steps to reproduce
------------------

```powershell
# On Windows
# When having a directroy called "Z:\Dir" 
PS Z:\> cd "dir"
```

Expected behavior
-----------------

```none
CWD is set to `Z:\Dir`
```

Actual behavior
---------------

```none
CWD is set to `Z:\dir`
```

**Comment by iSazonov** [comment]
Related #1273. Maybe dup?

**Comment by mklement0** [comment]
@iSazonov: I think the real duplicate is #5678.

More specific discussion of causes and solutions starts at https://github.com/PowerShell/PowerShell/issues/5678#issuecomment-418159153

**Comment by SteveL-MSFT** [comment]
Yes, this is dupe of #5678
