### ISSUE TITLE
AddScript Method does not work when hosting PS core remoting script in dot net core console application.

### ISSUE THREAD

**Issue by Justiii3** [PowerShell/PowerShell#7984]
Hello,
I've been experiencing some issues with the AddScript method when hosting PowerShell core in dotnet core console application.
The issue is that the method does not execute when running the application when there is PowerShell core remoting script. I've tested different ways to import the script inside the console app and every time I get the same issue, which is AddScript method doesn't do anything when  running PS core remoting script. AddSciprt method works perfectly fine when the script does not do any PS core remoting. Additional information and problem explanation below with code examples that are producing the same result.

Here is an example of the code that I'm using:

//EXAMPLE CODE 1:

            string userName = "User";
            string server = "10.192.10.10"; - for example
            string path = "root/ssh/**id_rsa**";

            using (Runspace runspace = RunspaceFactory.CreateRunspace())
            using (PowerShell powershell = PowerShell.Create())
            {

                PSCommand command = new PSCommand();
                command.AddCommand("New-PSSession");
                command.AddParameter("HostName", server);
                command.AddParameter("Username", userName);
                command.AddParameter("KeyFilePath", path);

                powershell.Commands = command;
                runspace.Open();
                powershell.Runspace = runspace;
                Collection<PSSession> result = powershell.Invoke<PSSession>();

                foreach (ErrorRecord current in powershell.Streams.Error)
                {
                    Console.WriteLine("Exception: " + current.Exception.ToString());
                    Console.WriteLine("Inner Exception: " + current.Exception.InnerException);
                }
                if (result.Count != 1)
                    throw new Exception("Unexpected number of Remote Runspace connections returned.");

                command = new PSCommand();
                command.AddCommand("Set-Variable");
                command.AddParameter("Name", "ses");
                command.AddParameter("Value", result[0]);
                powershell.Commands = command;
                powershell.Runspace = runspace;
                powershell.Invoke();

                command = new PSCommand();
                command.AddScript("Import-PSSession -Session $ses");
                powershell.Commands = command;
                powershell.Runspace = runspace;
                powershell.Invoke();

                command = new PSCommand();
                command.AddScript(@"Invoke-Command -Session $ses -ScriptBlock {
               Script here for example - Get-Process
        }");
                powershell.AddCommand("Out-String");
                powershell.Commands = command;
                powershell.Runspace = runspace;

                Collection<PSObject> results = new Collection<PSObject>();
                results = powershell.Invoke();
               
               foreach (PSObject Obj in results)
               {
                 Console.WriteLine(Obj.BaseObject.ToString());
               }

```
//EXAMPLE CODE 2. Again the AddScript does nothing with the script and no output is visible. When running the PS1 script file, runs successfully and there are no issues.

using (var runspace = RunspaceFactory.CreateRunspace())
{
    try
    {
        var script = File.ReadAllText("MyScript.ps1");
        runspace.Open();
        var ps = PowerShell.Create();
        ps.Runspace = runspace;
        ps.AddScript(script);
        ps.Invoke();
        ps.AddCommand("MyFunction").AddParameters(new Dictionary<string, string>
        {
            { "Param1" , value1},
            { "Param2", value2},
            { "Param3", value3},            
        });

        foreach (var result in ps.Invoke())
        {

        }
    }
    catch (Exception ex)
    {
        Debug.WriteLine(ex.Message);
    }
}
```

Additional Information:

1. When running the script from the *.PS1 file, it runs without a problem. I'm using PowerShell Remoting core over ssh
2. Source server (running the dot net core app) - Ununtu 18.04.
3. Target Server Windows 2012 R2 installed the latest OpenSSH -v7.7.2.0p1-Beta
4. When running any other script using the above methods that does not include PS remoting the console app works and I can see output. 
5. I can see that the powershell remoting is successful from the logs on the target server.
6. When running the csproj file, the solution restores, builds and runs with no errors. The code just exits and the output is missing.
7.  Powershell remoting is configured so it accepts a public key authentication, which when running ps1 script files executes with no errors and It works.
8. Everytime I run EXAMPLE CODE 1, I can see that a session is created from the logs of the target server. Also to confirm, when I output the Collection<PSSession> result = powershell.Invoke<PSSession>(); to string I can see the details of the PS Session. The moment we reach the AddScirpt method that is executing the Invoke-Command, it runs, but there is no output generated from the script and the Collection<PSObject>results = Collection<PSObject>(); the variable is empty.

I hope everything is clear.

I'm not sure If I'm doing something wrong or this is a bug, I would appreciate any help.
-->

Expected behavior
-----------------

Expecting the output from the PS remoting script to be visible in console output

Actual behavior
---------------

the "results" variable is == null and there is no output. 

Environment data
----------------
$PSVersionTable of Source server

```
Name                           Value
----                           -----
PSVersion                      6.1.0-rc.1
PSEdition                      Core
GitCommitId                    6.1.0-rc.1
OS                             Linux 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

$PSVersionTable of Target server:

```
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
C# Project Packages: 

    <PackageReference Include="Microsoft.PowerShell.Commands.Diagnostics" Version="6.1.0" />
    <PackageReference Include="Microsoft.PowerShell.Commands.Management" Version="6.1.0" />
    <PackageReference Include="Microsoft.PowerShell.SDK" Version="6.1.0" />
    <PackageReference Include="System.Management.Automation" Version="6.1.0" />
  </ItemGroup>

Dotnet version  - dotnet core 2.1.4.402 
PowerShell win32/OpenSSH version - v7.7.2.0p1-Beta

**Comment by Justiii3** [comment]
Hello,
I might have found a simple workaround that I've tested and it works.

Basically instead of asking the don net application to call the remoting script via .AddScript method you ask the dot net app to call a local powershell process that executes the remoting script. The script file should be somewhere on the server you're executing the application from. To show this as a code I'm using the following.

string script  = "start-process pwsh-preview" -argument "path to script file"
using (Runspace runspace = RunspaceFactory.CreateRunspace())
using (Powershell powershell = Powershell.Create())
{
runspace.Open();
PSCommand command = new PSCommand();
command.AddScript(script);
 powershell.Commands = command;
powerhell.Runspace = runspace;
Collection<PSObject> results = new Collection<PSObject>();
results = powershell.Invoke();
I'm yet to test calling the script with parameters (not sure how to do it yet maybe someone here can help). As well as hosting in docker container the entire thing. Most likely PowerShell core will need to be installed as well as dot net core in the docker image for it to work.

**However the main problem where AddScript method DOES NOT EXECUTE remoting script is still there.**

**Comment by Justiii3** [comment]
Anyone? Any idea on what the issue is here?

**Comment by DerGuru** [comment]
I am not completely sure, what your specific error message will say. Mine was: "Import-PSSession : Files cannot be loaded because running scripts is disabled on this system. Provide a valid
certificate with which to sign the files."
Adding "Set-ExecutionPolicy RemoteSigned" before the "New-PSSession... " did the trick for me.
[Inpired by this](https://answers.microsoft.com/en-us/msoffice/forum/all/error-when-importing-pssession-on-o365/3eaf0b1a-b5e0-467d-a113-06146a17a9c6) but the link states, that you will need admin rights, which I did not.

**Comment by Justiii3** [comment]
Hello,

I've created a new project yesterday, Installed System.Management.Automation  and Microsoft.PowerShell.SDK versions 6.2.1 . 
I've ran the project with EXAMPLE CODE 1 and that worked perfectly. The project was ran on the same environment as the one described in the issue.

Thank you for your help

Closing the Issue
