### ISSUE TITLE
Update terminal title for remote sessions

### ISSUE THREAD

**Issue by NetForce1** [PowerShell/PowerShell#7991]
Ssh updates the terminal title when logging into another machine. It would be very helpful if powershell did the same upon Enter-PSSession, especially when working in multiple terminal tabs (each with a session to a different machine).

**Comment by iSazonov** [comment]
Related #7991

**Comment by SteveL-MSFT** [comment]
@iSazonov did you mean to reference a different issue?  You've created a circular reference :)

**Comment by iSazonov** [comment]
@SteveL-MSFT I discover that sometimes users don't look GitHub references and only read post messages.

**Comment by SteveL-MSFT** [comment]
@NetForce1 do you have a proposal on what you would like the title to be?

**Comment by iSazonov** [comment]
We could look that `putty` shows.

**Comment by NetForce1** [comment]
It should at least include the username and hostname of the machine you are logged in to. On Ubuntu the GNOME Terminal sets the prompt as the window title when using bash locally or via ssh. But when I launch Powershell, it shows the bash prompt from where I launched pwsh. 

On my machine the the prompt (and thus the terminal title) looks like: `username@hostname: /path/to/working/dir`
