### ISSUE TITLE
Tests testing that all packages use the latest version should not be part of CI build

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#7992]
PR #7661 added  [package.tests.ps1](https://github.com/PowerShell/PowerShell/blob/master/test/common/package/package.tests.ps1), to check that all referenced packages are of the latest version. This causes a lot of unnecessary build failures in forks and PRs because it takes time for the bot to kick in and the update to be approved and merged and then one needs to upstream or re trigger the build and hope that no other 3rd party has published a new update in the meantime...
Those tests should be moved to a different build definition that is run e.g. only on a daily basis but definitely not part of CI or a PR. cc @TravisEz13

**Comment by TravisEz13** [comment]
Agreed.  We have added a bot to do this work now.  The tests can be removed or disabled.

**Comment by bergmeister** [comment]
@iSazonov I do not see this issue as closed until the tests are not part of the CI/PR builds any more

**Comment by iSazonov** [comment]
@bergmeister Sorry.

**Comment by SteveL-MSFT** [comment]
I'll submit PR to remove these tests

**Comment by bergmeister** [comment]
Thanks :-)

**Comment by TravisEz13** [comment]
No problem, we were just try to find the right solution.  Sometimes it takes trial and error.
