### ISSUE TITLE
Problems with Invoke-Restmethod and the PATCH method 

### ISSUE THREAD

**Issue by constantinhager** [PowerShell/PowerShell#8019]
Hello,

I want to edit a gist in github via PowerShell. The gist is a private gist.
The PAT Token has the right to create gists. I have tried It with the stable build of PowerShell Core 6.1.
I read the documentation and Produced the following PowerShell:

```powershell
$Uri = "https://api.github.com/gists/xxxx"

[HashTable]$Body = @{
      description = "Description"
      files       = @{
          "Test.txt" = @{
               content  = "Test Content"
               filename = "Test.txt"
          }
      }
}

$base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f $UserName, $PATToken)))
$Header = @{"Authorization" = ("Basic {0}" -f $base64AuthInfo)}
$ApiBody = ConvertTo-Json -InputObject $Body -Compress
$result = Invoke-RestMethod -Uri $Uri -Method "PATCH" -Headers $Header -Body $ApiBody -ContentType "application/json"
```

I do not get any result back and the gist isn't changing either. If I try It with for example Postman the gist gets updated. 

Any help would be appreciated.

Thanks
Constantin

**Comment by constantinhager** [comment]
i did that
```PowerShell
$ApiBody = ConvertTo-Json -InputObject $Body -Compress
```

and then I assigned It to the Body parameter 
```PowerShell
Invoke-RestMethod -Uri $Uri -Method "PATCH" -Headers $Header -Body $ApiBody -ContentType "application/json"
```

**Comment by mklement0** [comment]
@constantinhager: I assume you're saying that explicitly passing a JSON string to `-Body` solved your problem, correct?
If so, could you please close this issue?

@thezim: I'm not too familiar with `Invoke-RestMethod`, but, based on my brief experiments and  the following excerpt from the docs:

> When the input is a GET request, and the body is an IDictionary (typically, a hash table), the body is added to the URI as query parameters. For other request types (such as POST), the body is set as the value of the request body in the standard name=value format.

I'd say that a hashtable passed to `-Body` is _never_ converted to a JSON string, even with <br>`-ContentType application/json`.

From what I gather, the `-Body` parameter's from-hashtable conversion is only useful for:

* GET requests that you want to submit via a query string appended to the URL.

* Other requests such as POST that use content type `application/x-www-form-urlencoded`.

In all other cases you're expected to pass a string that matches the format specified via `-ContentType`.

**Comment by constantinhager** [comment]
i did that

`$ApiBody = ConvertTo-Json -InputObject $Body -Compress`

and then I assigned It to the Body parameter
`Invoke-RestMethod -Uri $Uri -Method "PATCH" -Headers $Header -Body $ApiBody -ContentType "application/json"`

I get nothing back and the gist does not change. So that does not solve my problem

**Comment by mklement0** [comment]
Thanks, @constantinhager. In the future, please include the _outcome_ of what (else) you've tried up front, so this back and forth can be avoided.

**Comment by thezim** [comment]
I could not repro the issue, the below worked for me with a private `gist` and the appropriate API token with `Create gists` permission.

```powershell
$Uri = "https://api.github.com/gists/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[HashTable]$Body = @{
      description = "New Description"
      files       = @{
          "gistfile1.txt" = @{
               content  = "New Test Content"
               filename = "gistfile1.txt"
          }
      }
}
$UserName = "thezim"
$PATToken = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
$base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f $UserName, $PATToken)))
$Header = @{"Authorization" = ("Basic {0}" -f $base64AuthInfo)}
$ApiBody = ConvertTo-Json -InputObject $Body -Compress
$result = Invoke-RestMethod -Uri $Uri -Method "PATCH" -Headers $Header -Body $ApiBody -ContentType "application/json"
```

```
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by constantinhager** [comment]
Thank you. That worked. Strange. I called the invoke-restmethod out of another function. This is not working. Thank you for the assistance.
