### ISSUE TITLE
Installation on Ubuntu running on ARMv8 architecture 

### ISSUE THREAD

**Issue by abhi18av** [PowerShell/PowerShell#8023]
Hello Powershell team,

I tried to install powershell on my scaleaway `ARMv8` server on Scaleway by following the instructions on https://www.hanselman.com/blog/InstallingPowerShellCoreOnARaspberryPiPoweredByNETCore.aspx 

I chose the `linux-arm32` binary from the releases page on Github which according to this article should work perfectly fine 
https://www.androidauthority.com/arms-64-bit-architecture-is-good-for-developers-407346/

However, I am stuck at the following error 

```
root@cub:~# /opt/microsoft/powershell/6.1.0/pwsh
-bash: /opt/microsoft/powershell/6.1.0/pwsh: cannot execute binary file: Exec format error 
```

Could you please help me out here ?

**Comment by iSazonov** [comment]
@tylerl0706 Could you please answer?

**Comment by tylerl0706** [comment]
Sorry I'm not familiar with this service. What OS are you using here?

My guess is that there may be additional dependencies that need to be installed.

Here are the official Raspian steps:
https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-powershell-core-on-linux?view=powershell-6#raspbian

**Comment by abhi18av** [comment]
Hi @tylerl0706 , here's the service in question 

https://www.scaleway.com/pricing/

I'm using the Ubuntu18.04 image and since the Raspbian and Ubuntu are both debian based, many packages just work.

**Comment by abhi18av** [comment]
Yes @tylerl0706 , I tried installing those however it still didn't work that well.

I have since moved away from toying with that idea and have started using the traditional `x86_64` architecture again.

Please feel free to close the issue :)

**Comment by tylerl0706** [comment]
Was it giving you the same error? Out of curiosity

**Comment by abhi18av** [comment]
Yes,  unfortunately it was.

**Comment by SteveL-MSFT** [comment]
@abhi18av the error indicates the architecture for the executable doesn't match the OS.  Running `file pwsh` should confirm it's the appropriate arch for that platform.

**Comment by abhi18av** [comment]
I have since tried the latest `arm64` binary for `powershell-6.2.0-preview.3` and it works fine :)

I'll close this issue since the future releases address all these problems.
