### ISSUE TITLE
Win10 PowerShell initialization failed

### ISSUE THREAD

**Issue by kickgod** [PowerShell/PowerShell#8027]
Steps to reproduce
------------------

```powershell
Click to launch Powershell
```

Expected behavior
-----------------

```none
Normal start
```

Actual behavior
---------------

设置: 在加载格式数据文件时出错: 
Microsoft.PowerShell.Core，，C:\Windows\System32\WindowsPowerShell\v1.0\Help.format.ps1xml: 由于发生以下验证异常，已跳过文件: 无法加载文件 C:\Windows\System32\WindowsPowerShell\v1.0\Help.format.ps1xml，因为有软件限制策略阻止运行该文件，例如，使用组策略创建的软件限制策略。。
Microsoft.PowerShell.Core，，C:\Windows\System32\WindowsPowerShell\v1.0\Registry.format.ps1xml: 由于发生以下验证异常，已跳过文件: 无法加载文件 C:\Windows\System32\WindowsPowerShell\v1.0\Registry.format.ps1xml，因为有软件限制策略阻止运行该文件，例如，使用组策略创建的软件限制策略。。
 

详细信息: 
	ExceptionClass=RuntimeException
	ErrorCategory=NotSpecified
	ErrorId=ErrorsUpdatingFormats
	ErrorMessage=在加载格式数据文件时出错: 
Microsoft.PowerShell.Core，，C:\Windows\System32\WindowsPowerShell\v1.0\Help.format.ps1xml: 由于发生以下验证异常，已跳过文件: 无法加载文件 C:\Windows\System32\WindowsPowerShell\v1.0\Help.format.ps1xml，因为有软件限制策略阻止运行该文件，例如，使用组策略创建的软件限制策略。。
Microsoft.PowerShell.Core，，C:\Windows\System32\WindowsPowerShell\v1.0\Registry.format.ps1xml: 由于发生以下验证异常，已跳过文件: 无法加载文件 C:\Windows\System32\WindowsPowerShell\v1.0\Registry.format.ps1xml，因为有软件限制策略阻止运行该文件，例如，使用组策略创建的软件限制策略。。

	Severity=Warning

	SequenceNumber=15

	HostName=ConsoleHost
	HostVersion=5.0.10240.17443
	HostId=655d2ab7-b2a5-4a01-94b1-7ecc7c434a10
	HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
	EngineVersion=5.0.10240.17443
	RunspaceId=a6a218c3-83bf-4c44-869a-7d57049ce3fe
	PipelineId=1
	CommandName=
	CommandType=
	ScriptName=
	CommandPath=
	CommandLine=

AdditionalInfo:
	Name=;Value=
	Name=;Value=
	Name=;Value=

Environment data
----------------
Win10 Professional Edition

```powershell
> $PSVersionTable

```

**Comment by iSazonov** [comment]
Please add $PSVersionTable information

**Comment by vexx32** [comment]
@iSazonov given that @kickgod is unable to *start* PowerShell, that may prove to be difficult for them.

Do you know which version of PowerShell you are attempting to start? Is it PowerShell Core (pwsh.exe) and do you know what version you installed?

**Comment by kickgod** [comment]
Name                           Value
----                           -----
PSVersion                      5.0.10240.17443
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   10.0.10011.16384
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3

**Comment by kickgod** [comment]
English:
I copied the C:\Windows\System32\WindowsPowerShell\v1.0\Help.format file of the classmate's computer and the Registry.format to the corresponding file directory of my computer. Instead of the original file, it worked again. I suspect that The two files are corrupt, but I found that my Visual Studo 2017 package management console is not working. I copied the non-directory files in the v1.0 file directory to C:\Program Files (x86)\Microsoft Visual Studio. It is working again in \2017\Professional\Common7\IDE. I don't know what this principle is, just suspect that the file is damaged.

Chinese：
我复制了同学电脑的C:\Windows\System32\WindowsPowerShell\v1.0\Help.format文件 和Registry.format 到我的电脑对应文件目录下,替代原来的文件,它又工作了,我怀疑是那两个文件损坏,但是我发现我的Visual Studo 2017 的程序包管理控制台不工作了,我又把 v1.0文件目录下的非目录文件复制到了C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE 里面它才又工作了。我不知知道这个原理是什么,只是怀疑文件损坏，

**Comment by adityapatwardhan** [comment]
This seems to be Windows PowerShell.

For Windows PowerShell 5.1 issues, suggestions, or feature requests please use the following link instead:
Windows PowerShell [UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)
