### ISSUE TITLE
Provider help topics are missing

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#8030]
Steps to reproduce
------------------

* First, run `Update-Help` from an elevated / `sudo` prompt to ensure that the latest topics have been downloaded.

```powershell
# This works in WinPS.
Get-Help -Category provider Environment
```

Expected behavior
-----------------

The `Environment` PS provider's help topic should print.

Actual behavior
---------------

An error about a missing file is reported.

```none
Get-Help : System.Management.Automation.dll-Help.xml
At line:1 char:1
+ Get-Help -Category Provider Environment
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OpenError: (:) [Get-Help], FileNotFoundException
+ FullyQualifiedErrorId : LoadHelpFileForTargetFailed,Microsoft.PowerShell.Commands.GetHelpCommand
```

Environment data
----------------

```powershell
PowerShell Core v6.1.0 on macOS 10.14
PowerShell Core v6.1.0 on Ubuntu 16.04.5 LTS
PowerShell Core v6.1.0 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.165)
```

**Comment by cantoris** [comment]
I can't find any Provider help in v7.2.2 on Win10 21H2 x64 either, though I can see the docs online.
eg Both of the following do not return the expected docs
```PowerShell
Get-Help -Category Provider
Get-Help -Name *filesystem*
```
Both the above work in Windows PowerShell 5.1.

**Comment by ThomasNieto** [comment]
This is due to the PowerShell team migrating the docs from the help xml to about topics. I don't agree with the change but its still there technically but breaks the `-Category` parameter search.

```powershell
Get-Help about*provider*

Name                              Category  Module                    Synopsis
----                              --------  ------                    --------
about_Alias_Provider              HelpFile
about_Certificate_Provider        HelpFile
about_Environment_Provider        HelpFile
about_FileSystem_Provider         HelpFile
about_Function_Provider           HelpFile
about_Providers                   HelpFile
about_Registry_Provider           HelpFile
about_Variable_Provider           HelpFile
about_WSMan_Provider              HelpFile
```

**Comment by cantoris** [comment]
> This is due to the PowerShell team migrating the docs from the help xml to about topics. 
> ```powershell
> Get-Help about*provider*
> 
> Name                              Category  Module                    Synopsis
> ----                              --------  ------                    --------
> about_Alias_Provider              HelpFile
> ```

Even after "Get-Module -ListAvailable | Update-Help -Force", your command above still gives me no results in PS 7.2.6?!

**Comment by theJasonHelmick** [comment]
Thank you @mklement0 -- as mentioned this was due to a migration to about topics.  `Get-Help *provider* `should provide the expected results.
