### ISSUE TITLE
github milestones and projects are in need of updates

### ISSUE THREAD

**Issue by mi-hol** [PowerShell/PowerShell#8031]
@SteveL-MSFT The currently visible milestones and projects are not indicative of pwsh development plans.
I wonder if there is no longer a owner for them?

**Comment by SteveL-MSFT** [comment]
@mi-hol yes, it's a bit out of date.  I'll get them updated after PSConfAsia this week.

**Comment by mi-hol** [comment]
issue closed but no update as promised :(

**Comment by SteveL-MSFT** [comment]
I'll keep this open until it actually gets updated.  My team is still going through planning.

**Comment by Jaykul** [comment]
PING!

**Comment by mi-hol** [comment]
closing as 6.3 has nice milestones 👍

**Comment by iSazonov** [comment]
We are waiting blog post about 7.0 plans and perhaps a meta issue.
