### ISSUE TITLE
array indexing by regex or wildcard

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#8033]
hello

in powershell the operator [] is for indexing array for example

Steps to reproduce
------------------

```powershell
$n = 'foo','bar','test','far','lol'

$n[0]

$n[0..3]

```

but it may be nice if the array index by regex et not by int for example

```powershell
$n('^f')
# or 
$n['^f']

# return:
#foo
#far
```

it possible to use

```powershell
$n | select-string '^f'
```
or may be
```powershell
$n -match '^f'
```
but in other case operator range is more simple to use and it return expected match without diving into object returned by "select-string"

**Comment by vexx32** [comment]
Personally, I don't think there's much really to be gained by modifying the array indexer in this fashion. As you mentioned, `-match` and other operators already do this. 

Not to mention that your regex example fundamentally isn't *indexing*, it's *filtering*, which is not really what the operator is for.

**Comment by mklement0** [comment]
Agreed, `$n -match '^f'` seems like a concise-enough and more readable idiom  to me. (`@($n) -match '^f'`, if `$n` could be a scalar).

Conceptual issues aside, the proposed `$n['^f']`syntax is _ambiguous_ and could break existing scripts, given that the following currently works:

```powershell
$ndx = '1'  # index as string (nothing you'd do intentionally, but it could happen)
$n[$ndx]  # -> 'bar' - string index was automatically coerced to [int].
          #  How do you distinguish it from regex '1'?
```

While `$n('^f')` doesn't clash with existing behavior, it strikes me as obscure and too similar to a method call.

**Comment by iSazonov** [comment]
We have an issue for adding LINQ support - I believe this resolve your request.
