### ISSUE TITLE
PSReadline with my PS 6.1 

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#8034]
hello

Steps to reproduce
------------------

```powershell
PS C:\> Get-Module PSReadLine

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.0.0      PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadL...


PS C:\> Get-Module PSReadLine | ipmo -Verbose
VERBOSE: Importing cmdlet 'Get-PSReadLineKeyHandler'.
VERBOSE: Importing cmdlet 'Get-PSReadLineOption'.
VERBOSE: Importing cmdlet 'Remove-PSReadLineKeyHandler'.
VERBOSE: Importing cmdlet 'Set-PSReadLineKeyHandler'.
VERBOSE: Importing cmdlet 'Set-PSReadLineOption'.
VERBOSE: Importing function 'PSConsoleHostReadLine'.
PS C:\>
```

but dont work, no colorized syntax, no intellisense ...etc ...why ? 
in my PS 5.0 PSreadline work like a charm 

Environment data
----------------
```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by p0W3RH311** [comment]
![sans titre](https://user-images.githubusercontent.com/36144546/46997784-77b8a080-d0d5-11e8-90cf-c2653bc4ed19.png)

**Comment by MaximoTrinidad** [comment]
Ah!  Wait!!  The difference is ... I'm using PowerShell Core 64 bit version.  You're using the 32 bit.
Can you try with the 64 bit version to see that works??

:)

**Comment by lzybkr** [comment]
@p0W3RH311 - if you're using a non-English keyboard layout, you might be hitting a known issue that was fixed in this [PR](https://github.com/lzybkr/PSReadLine/pull/768).

**Comment by MaximoTrinidad** [comment]
Well, I see no issues with either 86 bit and 64 bit versions.

![powershellcore_issue_02_2018-10-15_15-18-51](https://user-images.githubusercontent.com/19892435/47088856-711d4c80-d1ed-11e8-9cc2-e9612398d0da.jpg)
