### ISSUE TITLE
pwsh launched from zsh doest not respect proxy environment vars.

### ISSUE THREAD

**Issue by DaveCrown** [PowerShell/PowerShell#8036]
Steps to reproduce
------------------

```
pwsh
find-module

```

Expected behavior
-----------------

``` 
modules are returned

```

Actual behavior
---------------

```
pwsh hangs.

```

Environment data
----------------

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Linux 4.18.13-200.fc28.x86_64 #1 SMP Wed Oct 10 17:29:59 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by mklement0** [comment]
Are you referring to the `http_proxy` environment variable, as described [here](https://www.cyberciti.biz/faq/linux-unix-set-proxy-environment-variable/), for instance?

Since we're talking about environment variables, the shell that you're calling _from_ shouldn't matter.

Someone with more domain knowledge will hopefully join the conversation, but here's a quick pointer: The absence of the string `http_proxy` in the source code of PowerShell itself and the `PowerShellGet` module suggests that PowerShell is currently unaware of this variable altogether, so this may have to turn into a (more fully fleshed out) feature request.

**Comment by DaveCrown** [comment]
That is correct. I’m using an environment variable, that I declare in /etc/environment making it systemwide. Bash and zsh both use that file.

**Comment by mklement0** [comment]
From what I can tell, the definitions in `/etc/environment` are read by the system itself and all user processes inherit these environment variables, so what your default shell is shouldn't matter (even PowerShell itself would be fine).

In short: PowerShell should _see_ `$env:http_proxy`, but it seems it simply doesn't do anything with it.

**Comment by mklement0** [comment]
To elaborate a little: it isn't Bash or zsh _itself_ that respects the `http_proxy` environment variable, it is _external utilities_ such as `curl` that respect it.

If you were to invoke such utilities from PowerShell, they should work as usual.

By contrast, PowerShell's built-in analogous functionality, such as `Invoke-WebRequest`, seemingly does _not_ respect `http_proxy`, so making it do so would be a feature request (assuming my analysis is correct).

**Comment by thezim** [comment]
You can try the workaround in #3112 until it is supported.

**Comment by mklement0** [comment]
Thanks, @thezim - hadn't even occurred to me to search for "http_proxy" in _this_ repo...

@SteveL-MSFT, can you please close this as a duplicate?

**Comment by DaveCrown** [comment]
I just have to remember to run it from bash, and it works like a champ.

**Comment by mklement0** [comment]
@DaveCrown: 

Run what from Bash? If you're calling external utilities such as `curl`, it shouldn't matter whether you're calling them from Bash or PowerShell.

Or are you saying that you're seeing a difference there? If so, that would warrant further investigation.

**Comment by DaveCrown** [comment]
Sorry, thought I had thatbdetail in there. When I run pwsh from bash, Import-Module works fantastic. When I run it from zsh, it won’t connect. I keep all my proxy config in /etc/environment, so that I don’t have to manage proxy settings for root.
