### ISSUE TITLE
New-Variable -Scope Private doesn't create a private variable.

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#8040]
`New-Variable -Scope Private` doesn't create a private variable, only `New-Variable -Option Private` does (the other `-Scope` values work as intended).

(`New-Alias -Scope Private` works fine, by contrast.)

Steps to reproduce
------------------

```powershell
(New-Variable foo1 -Scope Private -PassThru).Options
(New-Variable foo2 -Option Private -PassThru).Options
```

Expected behavior
-----------------

```none
Private
Private
```

Actual behavior
---------------

```none
None
Private
```

That is, `-Scope Private` was quietly ignored.

While the private "scope" ultimately translates into an _option_ on a variable created in the current scope, `-Scope Private` should still be supported, given that `-Scope Global` and `-Scope Script` work as intended.

Environment data
----------------

```powershell
PowerShell Core v6.1.0 on macOS 10.14
PowerShell Core v6.1.0 on Ubuntu 16.04.5 LTS
PowerShell Core v6.1.0 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.165)
Windows PowerShell v5.1.17134.228 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.165)
```

**Comment by whitequill** [comment]
I was just noticing a similar problem.
`New-Variable -Scope private -Name test -Value "D:\Users\brazg\Documents\test"`
if you type
`$global:test` or `$local:test` or `$private:test` they will all return the same value.

**Comment by yegorf1** [comment]
Interesting, because if you write `Private` in lower-case (`private`), it will work as supposed. As I see, equality test made with case ignorance (https://github.com/PowerShell/PowerShell/blob/v6.1.0/src/Microsoft.PowerShell.Commands.Utility/commands/utility/Var.cs#L832), but it doesn't work

**Comment by mklement0** [comment]
@whitequill: I've read the topic, but it doesn't tell you the whole story.

> if `New-Variable -Scope` has to do with where the code is run

`-Scope` specifies in what the scope the variable is _created_, as also reflected in the [`New-Variable`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/new-variable?view=powershell-6) help topic:

> Specifies the scope of the new variable.

And that is indeed how it works for `-Scope Global`, `-Scope Script` and `-Scope Local`, but it doesn't work for `-Scope Private`, which is the inconsistency this issue is about.

An example of where it works:
 
```powershell
& { new-variable -scope script hi there } # from a child scope, create a variable in the script scope
$hi  # output the newly created script-scope variable
```

Note that in the global scope (from the command line) both the  `script` scope is the same as the global scope.

> but `$private` should be its own scope independent of other variable names.

Strictly speaking, `private` is _not a separate scope_.
Instead, it is a _flag_ (option) on a variable in a _given scope_ that prevents _descendant_ scopes from seeing its value or modifying it with explicit cross-scope access.

Thus, `New-Variable -Option Private` is the technically more accurate way to create a private variable in the _current scope_ - and it does work as intended.

You can even _combine_ that with `-Scope`  to create a private variable in a _different_ scope:

```powershell
& { new-variable -scope script -option Private hi there } # create private var. in script scope
$hi # OK, private script-level var. was created, and is (obviously) accessible in the script scope.
& { $hi } # NO output in child scope, because the script-scope variable is private.
```

Since variables in the  private "scope" are only ever accessible in the `local` i.e. current scope, there is some _technical_ justification in treating `-Scope Local` and `-Scope Private` both as `-Scope Local`, but it certainly _confounds user expectations_, needlessly so, not least, because it works differently - and as expected - with `New-Alias`.
