### ISSUE TITLE
Automate logging in powershell functions

### ISSUE THREAD

**Issue by aricamf** [PowerShell/PowerShell#8044]
Hi
May I know how I can add logs to begin and end of a function in Powershell automately? Something like the AspectJ for Java.  I have the question as I'm going to have the clear call stack trace like all functions call with log "<Script>:<Function>:Begin" and "<Script>:<Function>:End" at the beginning and end.

Thanks

**Comment by vexx32** [comment]
`Start-Transcript` is probably the most effective and simple way to start with this kind of thing.

Just remember to `Stop-Transcript` at the end! 😄

**Comment by aricamf** [comment]
@vexx32 Thanks for the comments so much! Hm...then I have to "Start-Transcript", "Stop-Transcript" in each function...any...automate solution here?

**Comment by iSazonov** [comment]
We could enhance our Trace commands.

**Comment by vexx32** [comment]
If you're on a domain you can set GPOs to automate logging for PowerShell; see here for some ideas: https://blogs.msdn.microsoft.com/powershell/2015/06/09/powershell-the-blue-team/

**Comment by aricamf** [comment]
@vexx32 I've read the logging paragraph of the above document. Yes, it's a solution to have better traceability of function calls, though a little big complex. I will consider this as a temp solution.

Thanks so much.
