### ISSUE TITLE
Some color settings make some text invisible

### ISSUE THREAD

**Issue by imba-tjd** [PowerShell/PowerShell#8045]
Hi.
When the background color set to 12, 12, 12(the first color) and text color set to 59, 120, 255(the 10th color), text in string will be invisible. PS5 doesn't have this problem because it changes the line's backgroud color.

In PS6:
![default](https://user-images.githubusercontent.com/24759802/47017710-89f21780-d185-11e8-9697-e38c574ee222.png)

In PS5:

![default](https://user-images.githubusercontent.com/24759802/47017803-d76e8480-d185-11e8-9285-207e4f1ce491.png)

I have searched issues but English isn't my native language so it's hard for me to find whether there are dups. If there were, please close this one, thanks.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by lzybkr** [comment]
There is a similar complaint [here](https://github.com/lzybkr/PSReadLine/issues/744), so further discussion can take place in that issue.

For now, your best bet is probably to customize the color, see an [example](https://github.com/lzybkr/PSReadLine/blob/master/docs/Set-PSReadLineOption.md#examples).
