### ISSUE TITLE
ValidateSet missing quotes when auto-complete value begins with "process".

### ISSUE THREAD

**Issue by LethiferousMoose** [PowerShell/PowerShell#8048]
Steps to reproduce
------------------
Creates a function that has a ```ValidateSet``` enabled parameter.

```powershell
function Test-AutoComplete {
    param([ValidateSet('process is the first word in this string')]
          [Parameter(Position=0)]
          [string] $TestParam)
}
```

Expected behavior
-----------------
The auto-complete suggestion **will** wrap the string in quotes because it contains spaces.
```powershell
Test-AutoComplete -TestParam 'process is the first word in this string'
```

Actual behavior
---------------
The auto-complete suggestion **does not** wrap the string in quotes because it begins with the word "process".
```powershell
Test-AutoComplete -TestParam process is the first word in this string
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

I assume this an issue because "process" is a reserved word. This issue should also check whether any other reserved words have issues with ```ValidateSet```:
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_reserved_words?view=powershell-6

**Comment by LethiferousMoose** [comment]
Debugged this in my fork, looks like it's treating the word "process" as a process block when it tries to complete the value.

**Comment by iSazonov** [comment]
> Is there an expert in this area

If only somebody from community... maybe @vexx32 or @SeeminglyScience.

>  like it's treating the word "process" as a process block 

Looks like ValidateSet priority should be higher.

**Comment by LethiferousMoose** [comment]
This is my first time poking around the code, I'll probably look at it a bit more. But most of the code that runs this seems super generic. I'm sure someone else can answer this, but I don't really get how it "knows" this is a parameter at the level it decided to return a script block token. I'm curious why it behaves normally with other keywords like `catch`. I'll do more digging tomorrow...

**Comment by iSazonov** [comment]
You could search `ValidateSet` in completor source files.
