### ISSUE TITLE
Is hardlinks really that important that they need to be in the Mode for fileinfo?

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShell#8051]
Getting the hardlink flag takes about 25% of the time to display a fileinfo when doing ls.

Is it really that important? Could it be made optional, or hidden behind some option?

**Comment by iSazonov** [comment]
Do p/invoke so slow?

**Comment by powercode** [comment]
I guess windows only.
The slowness comes from having to reopen each file to get the hardlink count. The rest of the information is available in the FileInfo object. 

For the hardlink, we need to call `CreateFile` (slow) to get a handle, and then use it to get the handle info (fast).

cmd.exe doesn't do this. It shows link types when there is a reparse-point. We could display when there is a reparse point, and ignore hardlinks.

**Comment by iSazonov** [comment]
> The slowness comes from having to reopen each file to get the hardlink count

I wonder that is so slow. In the [topic](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/2f2fc25b-6dd3-43ec-850c-c6ca6b428455/how-to-detect-a-hard-link-while-scanning-files?forum=windowssdk) I see " In testing, it slowed down our processing from 240ms for 21000 files, to 750ms. "

**Comment by powercode** [comment]
I'm not sure it is a breaking change. If I recall correctly, formatting is explicitly not a part of the public contract.

**Comment by jborean93** [comment]
> cmd.exe doesn't do this. It shows link types when there is a reparse-point. We could display when there is a reparse point, and ignore hardlinks.

IIRC a hard link isn't set as a reparse point so having a check on that won't work. I'm unsure as to the speed but you can use [FindFirstFileName](https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-findfirstfilenamew) and [FindNextFileName](https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-findnextfilenamew) to enumerate all hard links on a file without calling `CreateFile`. As for what that does internally I have no idea.

**Comment by iSazonov** [comment]
Seems two fields is affected - LinkType and Mode.

**Comment by powercode** [comment]
The problem is the extra roundtrips to disc, since we don't get enough information from the FileInfo. And going from a FileInfo to a filehandle, which is needed to get the the hardlink count, is expensive on windows.

I argue that this info is so rarely needed that paying the price all the time is not motivated.

Here's some pointers to the relevant docs for people interested in looking deeper:

Desc| Comment 
-----|-----
[GetFileInformationByHandleEx](https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-getfileinformationbyhandleex)| The API to get extended file info
[FILE_INFO_BY_HANDLE_CLASS enumeration](https://msdn.microsoft.com/en-us/8f02e824-ca41-48c1-a5e8-5b12d81886b5)|Enum to select info to retrieve
[_FILE_STANDARD_INFO structure](https://docs.microsoft.com/sv-se/windows/desktop/api/winbase/ns-winbase-_file_standard_info)| The struct for getting the hardlink count
[System.IO](https://github.com/dotnet/corefx/tree/master/src/System.IO.FileSystem/src/System/IO)| Source code for .net FileInfo etc
[Interop definitions in corefx](https://github.com/dotnet/corefx/tree/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/Common/src/Interop/Windows/kernel32)| Structs etc used by the framework to get the data from the file system.

**Comment by powercode** [comment]
@iSazonov I'm not that concerned about the LinkType as it isn't displayed by default. 
I'm starting to think that the right solution is just to change the default formatting. We can keep the current as a non-default view.

**Comment by iSazonov** [comment]
@powercode Remove mode from default view? I'd vote to follow cmd.exe behavior (exclude hardlynk from the mode)

**Comment by powercode** [comment]
I'm fine with that too.

**Comment by iSazonov** [comment]
@SteveL-MSFT Can you confirm the change?

**Comment by rkeithhill** [comment]
Will `-Force` "force" the display of this info?  I do have some hardlinks that I'd link to see what they're targeting.

**Comment by vexx32** [comment]
Get-ChildItem's `-Force` flag is primarily for displaying hidden or system files. I'd be inclined to think... probably not. I believe there was discussion of a separate switch to enable querying this information?

**Comment by iSazonov** [comment]
I'd consider -IncludeHardLinks for Get-Item and Get-ChildrenItem.

**Comment by SteveL-MSFT** [comment]
I would be ok with removing hardlinks by default.  A dynamic param for FileSystemProvider may be an ok solution.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and is ok with not having hardlinks in the default view

**Comment by henrivdr** [comment]
I agree with @iSazonov on a seperate switch like -IncludeHardLinks or a generic -IncludeLinks since it also needs to adjust the Process Token Privilege on Windows to get the proper LinkType and Target info, per invocation. See #7127

**Comment by SteveL-MSFT** [comment]
This is already fixed by #8789
