### ISSUE TITLE
Enable Invoke-Command -ThrottleLimit to be used on localhost without remote connection.

### ISSUE THREAD

**Issue by mkellerman** [PowerShell/PowerShell#8052]
Many modules exists out there to allow Throttling of parallel jobs/tasks. And the main reasons people use them are for simple throttling of tasks. 

Ex: 
````
$Computers = Get-Content 'computers.txt'
Invoke-Command -ScriptBlock { 
    Param($Computer) 
    Test-Connection $Computer
} -ThrottleLimit 5 -ArgumentList $Computers
````

Do I really need to enable Powershell Remoting to execute this simple task? 

If it's impossible to do with Invoke-Command, I would suggest adding ThrottleLimit to Start-Job.

**Comment by iSazonov** [comment]
@mkellerman Did you already see `Start-ThreadJob` cmdlet?

**Comment by mkellerman** [comment]
@iSazonov  I haven't, but I have seen many modules out there: PoshRSJob, Invoke-Parallel.

Invoke-Command already has a -ThrottleLimit parameter, and works well with remote execution. But why not enable it for local execution? Even if it uses jobs internally, or some other mechanism. Why make the user download an external module?

**Comment by SteveL-MSFT** [comment]
@mkellerman as @iSazonov pointed out, `Start-ThreadJob` has a `-ThrottleLimit` parameter.  `Start-Job` probably should have it as well...  As you noticed, `Invoke-Command` has `-ThottleLimit` when used with remoting which makes sense.  You could point `Invoke-Command` to localhost, but I think `Start-ThreadJob` is a much better existing solution.

**Comment by mkellerman** [comment]
@SteveL-MSFT Ahhhh, my bad. I didn't know it was part of a new release.. I saw this GitHub project (https://github.com/PaulHigin/PSThreadJob) and thought it was an external module we had to install.

Cheers!

**Comment by SteveL-MSFT** [comment]
@mkellerman `ThreadJob` is included with PSCore6.1, but can optionally be installed for Windows PowerShell and PSCore6.0
