### ISSUE TITLE
new operator // (if not defined)

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#8058]
please consider this example

Steps to reproduce
------------------

```powershell
if(-not $lang) {
   $lang = $lol
   if(-not $lang) {
      $lang = $bar
      if(-not $lang) {
         write-host "do something"
         $lang = 'PS+'
      }
   }
}
```
new syntax inspired from perl

```powershell

$lang //= $lol // $bar //  {
  write-host "do something"
  "PS+"
}
```

if $lang is not defined then $lang = $lol, if $lang is not defined then $lang = $bar if $lang is not defined then affect the result of scriptblock to $lang...in this case $lang = 'PS+' and print in console 'do something'

**Comment by vexx32** [comment]
Given that PS comes from c#, perhaps utilising the common 'if null' implied behaviour of `?` would be best here?

```
$lang ?= Value
```

**Comment by SeeminglyScience** [comment]
It's worth defining defining what "defined" means in this context.  In other words is it:

1. The variable hasn't been set in the current scope
1. The variable hasn't been set in the current scope *and* has not been inherited from a previous scope (true "not defined")
1. Any of the above *or* the variable has been set but is null or empty

**Comment by vexx32** [comment]
I think 3 is probably the most effective and most intuitive solution here.

**Comment by SeeminglyScience** [comment]
@vexx32 I agree, though I'd like to see that handled with `$var = $var ?? 'value if empty'` personally.

**Comment by vexx32** [comment]
That syntax isn't bad, but given how similar that is to `$var = $var + 10` I can almost guarantee there would still be demand for the shorthand. :)

**Comment by mklement0** [comment]
Great idea, but this has already been proposed in the context of #3240, with `??` / `?=` syntax.

I suggest we continue the conversation there.

**Comment by BrucePay** [comment]
Not quite as concise as //= (but much more so than the nested `if` statements), you can use the `-or` operator to do the following:
```powershell
if (($lang = $lol) -or  ($lang = $bar) -or ($lang = "default"))  {
   "lang is $lang"
}
```
Short-circuiting will stop execution at the first assignment that doesn't result in null.

**Comment by mklement0** [comment]
Unfortunately, that's not enough for a true, general "if undefined/null" pattern, given that a strictly Boolean test would fail for all "falsy" values, such as `0`.

Accounting for that gets unwieldy:

```powershell
$lol = 0
if ($null -ne ($lang = $lol) -or  ($null -ne ($lang = $bar)) -or ($lang = "default"))  {
   "lang is $lang"
}
```

But let us continue the discussion in #3240 - or, syntax form aside, is there something here not covered in the other proposal?
