### ISSUE TITLE
Cleanup using StringComparison.CurrentCulture

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#8064]
We need review using StringComparison.CurrentCulture in all code base.

[Best Practices for Using Strings in .NET](https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings)

For stable behavior InvariantCulture looks right for date and time formats but Unicode standard Simple Case Folding is better for comparison and sorting.

**Comment by iSazonov** [comment]
@mklement0 I invite you based on your  https://github.com/PowerShell/PowerShell/issues/8180#issuecomment-459890092
> Choosing a consistent default across cmdlets and operators (#8064) is a great idea, but I wonder if that's considered an acceptable breaking change; while that #8566 was indeed a breaking change, this was driven by unacceptable behavior having surfaced on Unix.

It seems is a huge work but I believe that we could investigate till next LTS version when we could accept possible breaking changes.

**Comment by adamedx** [comment]
Adding what may be a related issue encountered in 6.1.2 where `sort-object` behaves differently on the same input on Windows vs. Linux:

```powershell
PS> $PSVersionTable.Platform;('a', 'ab', 'aC' | Sort-Object ) -join ','
Win32NT
a,ab,aC
PS> $PSVersionTable.Platform;('a', 'ab', 'aC' | Sort-Object ) -join ','
Unix
a,aC,ab
```
In my case, tests caught this, but the impact is actually a real defect.

**Comment by adamedx** [comment]
Thank you @mklement0  and @iSazonov , I've opened #8824 to track this explicitly then. I hope we can get the same behavior cross-platform consistency for sort and related functionality on PowerShell Core that Ruby, JavaScript, Python, et. al. exhibit. And certainly the default behavior on Linux (or at least Ubuntu 18.04) is different than PowerShell Desktop, which besides being the source of 99.999% of PowerShell scripts, has set the most usable standard here, where comparisons are case insensitive.
