### ISSUE TITLE
PSReadLine broke the Insert Key functionality that previously existed before its inclusion in PowerShell

### ISSUE THREAD

**Issue by JoeSalmeri** [PowerShell/PowerShell#8066]
This  bug has existed since the PSReadLine module was introduced to PowerShell and goes back to before PowerShell Core existed.  It exists in BOTH Windows PowerShell (latest version) as well as PowerShell Core 6.1.

Prior to the inclusion of the PSReadLine module, when typing at the PS command line, you could press the Insert key to toggle between insert mode and overtype mode. 

After the PSReadLine module was included, when typing at the PS command line you are always in insert mode and the Insert key no longer toggles between insert mode and overtype mode.

Initially when I found this issue (years ago when PS-ReadLine was first introduced), I found that the Insert key did not have a Handler defined via Set-PSReadLineKeyHandler, however after doing more research it appears that there is no function available in PSReadLine to bind the key to which provides the traditional insert toggle mode that has existed since the DOS days at the command line and existed in PS before PSReadLine was introduced.

Please add the Insert key toggle mode to PSReadLine.

As a related issue, when viewing the Properties for a PowerShell instance on the Options tab, in the Edit Options, there is a "Insert Mode" checkbox which allows you to toggle whether the PowerShell instance opens in insert mode or overwrite mode.  This is also none functional as a result of that behavior missing from the PSReadLine module.

Steps to reproduce
------------------

```powershell

Press insert key and note that it does not toggle between insert mode and overwrite mode.

```

Expected behavior
-----------------

``
Press insert key and have it toggle between insert mode and overwrite mode.

```

Actual behavior
---------------

```none

```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by thezim** [comment]
PSReadLine issues are here.

https://github.com/lzybkr/PSReadLine/issues

**Comment by lzybkr** [comment]
This is a duplicate, any further discussion should happen in https://github.com/lzybkr/PSReadLine/issues/402.

**Comment by JoeSalmeri** [comment]
@thezim thanks for the heads up.  @lzybkr thanks for the link to the issue I reported
