### ISSUE TITLE
The Markdown spelling tests should be converted to a Pester test

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#8078]
Current tests:
https://github.com/PowerShell/PowerShell/blob/1dc4a7903f6a579640d3cf9e7104512e85b4455c/.vsts-ci/spelling.yml#L27

Example of the markdown lint tests written in pester:  
https://github.com/PowerShell/PowerShell/tree/master/test/common/markdown

**Comment by RDIL** [comment]
I can take a shot at this.
(please assign me)
