### ISSUE TITLE
Set-Location -LiteralPath does not treat "-" and "+" as literals.

### ISSUE THREAD

**Issue by kvprasoon** [PowerShell/PowerShell#8086]
From great feature, I would say Navigation is impossible to folder named `-` and `+`

![image](https://user-images.githubusercontent.com/12897753/47222628-cfaf1a00-d3e9-11e8-9d32-64a2cb915c42.png)

```Set-Location -LiteralPath -``` as well

Environment data
----------------

```

Name                           Value
----                           -----
PSVersion                      6.2.0-preview.1
PSEdition                      Core
GitCommitId                    6.2.0-preview.1
OS                             Microsoft Windows 10.0.18262 
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
Surely this is accessible with `cd .\-` and `cd .\+`?

**Comment by kvprasoon** [comment]
@vexx32  But that's not how directory navigation should be.

**Comment by vexx32** [comment]
That's an opinion, not a fact. And I'm sure folks accustomed to using `cd -` and `cd +` on Linux would disagree there. 😄

**Comment by rkeithhill** [comment]
You have a similar issue with a dir named `[foo]`.  You can cd to it with `cd -lp [foo]` but the same doesn't work with `cd -lp -`.  I think perhaps that should work in addition to `cd .\-`.

**Comment by vexx32** [comment]
Yeah, I'd agree that `-LiteralPath` should not exhibit the history-navigation behaviour for obvious reasons!

**Comment by SteveL-MSFT** [comment]
`Set-Location -LiteralPath -` should treat it as a literal path and not `Pop-Location` so that is a bug.  We can use this issue to track that.

**Comment by mklement0** [comment]
@kvprasoon, can you please change the issue title to something like the following?

> Set-Location -LiteralPath does not treat "-" and "+" as literals.
