### ISSUE TITLE
When will Alpine stable docker images start getting created with the rest?

### ISSUE THREAD

**Issue by AceHack** [PowerShell/PowerShell#8094]
I'm looking at the image

https://github.com/PowerShell/PowerShell-Docker/blob/master/release/stable/alpine/docker/Dockerfile

I'm wondering when it will start being used and created like I notice the latest 6.2 does not use it.

Also, there are comments like:

> # TODO: once the official build produces a full package for Alpine, remove this overlay of the Alpine files

So when will the official build produce a full package for Alpine?

**Comment by AceHack** [comment]
Any update?  Seems like alpine with 6.1.2 got created?  How to install to base alpine image?

**Comment by pixelrebirth** [comment]
Id like to poke this as well and see a more official answer on possibly getting Alpine linux installation a well documented possibility. Maybe even in the APK repos? 

`apk add powershell` would be glorious

**Comment by iSazonov** [comment]
@TravisEz13 Could you please make a conclusion about the issue? Should we track anything in the repo?

**Comment by TravisEz13** [comment]
There are no plans to create a package currently.  We have created images
`docker run --rm -it mcr.microsoft.com/powershell:preview-alpine-3.9`
`docker run --rm -it mcr.microsoft.com/powershell:preview-alpine-3.10`
`docker run --rm -it mcr.microsoft.com/powershell:alpine-3.8`
`docker run --rm -it mcr.microsoft.com/powershell:preview-alpine-3.8`
