### ISSUE TITLE
change <string> to <string[]> for tee-object

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#8097]
instead of cryptic syntax change the type of parameter -variable  <string> to <string[]>...please

Steps to reproduce
------------------

```powershell
PS C:\> ($d=($c=($b=($a=1))))
1
PS C:\> gv a,b,c,d

Name                           Value
----                           -----
a                              1
b                              1
c                              1
d                              1


PS C:\> rv a,b,c,d
PS C:\> 1 | Tee-Object -Variable a,b,c,d

```

Expected behavior
-----------------

```none
PS C:\> gv a,b,c,d

Name                           Value
----                           -----
a                              1
b                              1
c                              1
d                              1
```

Actual behavior
---------------

```none
Tee-Object : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Var
iable'. Specified method is not supported.
At line:1 char:26
+ 1 | Tee-Object -Variable a,b,c,d
+                          ~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Tee-Object], ParameterBindingException
+ FullyQualifiedErrorId : CannotConvertArgument,Microsoft.PowerShell.Commands.TeeObjectCommand
```

it don't work like expected because the type of -variable parameter is 'string'

```powershell
PS C:\> Get-Help Tee-Object -Parameter variable

-Variable <string>

    Required?                    true
    Position?                    Named
    Accept pipeline input?       false
    Parameter set name           Variable
    Aliases                      None
    Dynamic?                     false
```

it will be nice if the type is changed to '<string[]>' to support multiple variable

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
You don't need cryptic syntax to create and initialize multiple variables with the same value:

```powershell
$a = $b = $c = $d = 1
```

Also, using a pipeline with `Tee-Object` just to initialize variables would be heavy-handed.
(And for capturing command output, a single output variable strikes me as sufficient).

**Comment by p0W3RH311** [comment]
thanks mklement0...the idea is not to create and initialize multiple variables with the same  value only but also output the result like this

```powershell
PS C:\> ($a = $b = $c = $d = 1)
1
```

this behaviour is missing with tee-object

**Comment by mklement0** [comment]
`Tee-Object`  does output the input it receives, in addition to _also_ sending it to a (single) file or a (single) variable.

Are you saying there's value in making `Tee-Object` save the input to _multiple_ variables?
Can you give us an example scenario where that would be useful?
