### ISSUE TITLE
add hyper-operators 

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#8098]
hello
please, add a hyper-operators to PS6 [ + - * / ]

here some examples

Steps to reproduce
------------------

```powershell
PS C:\> 1 * 2 * 3 * 4 * 5
120
PS C:\> * 1..5
120
PS C:\> 5 + 998 + 41 + 7
1051
PS C:\> + 5,998,41,7
1051
PS C:\> $factor_10 = * 1..10
3628800
```

**Comment by mklement0** [comment]
Intriguing idea - certainly makes for more flexible and concise operation expressions.

Just to note (I don't think the idea should be discounted for that reason): `*` and `/`  (but not `+` and `-`) are currently interpreted as _command names_ at the start of a statement, so interpreting them as operators is _technically_ a breaking change.

Conceivably, the pattern could be extended to `-and` / `-or` and `-band` / `-bor`, but note that, again, such tokens would currently be interpreted as command names at the start of a statement.

**Comment by vexx32** [comment]
Hmmmm. The syntax seems a bit... Unclear in intent?

Perhaps something like:
```
-multiply $array
-sum $array
```
Might be a bit clearer?

**Comment by p0W3RH311** [comment]
> 
> 
> Hmmmm. The syntax seems a bit... Unclear in intent?
> 
> Perhaps something like:
> 
> ```
> -multiply $array
> -sum $array
> ```
> 
> Might be a bit clearer?

yes unary operator seem a good idea

**Comment by vexx32** [comment]
Yeah, I see what you mean @mklement0. My main issue with them being unary operators too similar to their binary counterparts is that this then introduces... unclear syntax in more complex expressions. Or do we simply enforce either/or and prevent them also behaving as binary operators in such expressions?

Consider:
```powershell
2 * 1..5 # Okay, so guess this would be equivalent to 2 * (* 1..5)? Or is it invalid syntax?
* 1..5 + 1..5 # This hurts my brain.
```
Etc., etc. -- Some of those *look* like they ought to work, but you could possibly argue either way on exactly how they ought to behave.

**Comment by p0W3RH311** [comment]
> 
> 
> Yeah, I see what you mean @mklement0. My main issue with them being unary operators too similar to their binary counterparts is that this then introduces... unclear syntax in more complex expressions. Or do we simply enforce either/or and prevent them also behaving as binary operators in such expressions?
> 
> Consider:
> 
> ```powershell
> 2 * 1..5 # Okay, so guess this would be equivalent to 2 * (* 1..5)? Or is it invalid syntax?
> * 1..5 + 1..5 # This hurts my brain.
> ```
> 
> Etc., etc. -- Some of those _look_ like they ought to work, but you could possibly argue either way on exactly how they ought to behave.

using parens seem resolve most problem ?
```powershell
(* 1..5) (+ 1..5)
(* 1..5) + (1..5)
* (1..5 + 1..5)
2 (* 1..5)
```

**Comment by vexx32** [comment]
Exactly. In pure unary syntax the proposal is great, but in a more complex expression I think we'd just end up with a largely unintelligible or overly-parenthesized mess. 😕

**Comment by iSazonov** [comment]
I think the scenario can be addressed by LINQ. We already have a tracking Issue to add LINQ support.

**Comment by vexx32** [comment]
I think that one's #2226?

Hmm, where did the RFC for that get to...

**Comment by mklement0** [comment]
Yeah, I can see how the precedence issues can get mind-bending.

LINQ support (the RFC is [here](https://github.com/PowerShell/PowerShell-RFC/pull/86/files)) would definitely give us the same functionality in principle:

Conveniently in the case of `+` (summing):

```powershell
PS> (1, 2, 3, 4).Sum()  # once we have support for LINQ extension methods
10
```

Not so conveniently in the other cases, using `*` as an example:

```powershell
PS> (1, 2, 3, 4).Aggregate({ param($soFar, $element) $element * $soFar }) 
24
```

On the plus side, `.Aggregate()` allows implementation of custom aggregations.

**Comment by HumanEquivalentUnit** [comment]
If you wanna turn PowerShell into an array language, steal some ideas from the J language 😃 

http://www.jsoftware.com/help/learning/01.htm section 1.8 introduces the "Insert" operator, which is described as:

> We see that `+/2 3 4` means `2+3+4` and `*/2 3 4` means `2*3*4`. The symbol `/` is called "Insert", because in effect it inserts whatever function is on its left between each item of the list on its right. The general scheme is that if F is any dyadic function and L is a list of numbers a, b, c, .... y, z then:
>         F / L     means    a F b F .... F y F z 

And then we're well on the way to transforming an array all at once instead of loops and filters everywhere and...

But seriously, `$array | measure-object -sum | select-object -expandproperty sum` is the PowerShell way to sum a list, and LINQ Sum/Aggregate is the .Net way to `reduce()` a list, and I'd rather see LINQ support first, then more consideration of operators to cover for it missing.

`+ 5,998,41,7` does already have a meaning in PowerShell.

```
# and maybe extend the syntax to math library:
-exponent 1..5,2
```

There is an open issue about an operator to map to `[math]::pow()` somewhere

**Comment by rjmholt** [comment]
Taking a leaf out of the Haskell book, where operators are just infix functions:

```powershell
function *
{
    param(
        [Parameter(ValueFromRemainingArguments=$true, ValueFromPipeline=$true)]
        [object]
        $Num
    )

    begin
    {
        $acc = 1
    }

    process
    {
        if ($Num -as [object[]])
        {
            foreach ($v in $Num)
            {
                $acc = $acc * $v
            }
            return
        }

        $acc = $acc * $Num
    }

    end
    {
        return $acc
    }
}
```

```
> * (1..5)
120

> * 3 4 5
60

> 10,3,7 | *
210
```

**Comment by rjmholt** [comment]
Extending this a bit further, basic folds are possible:

```powershell
function fold
{
    param(
        [Parameter()]
        [string]
        $Function,

        [Parameter()]
        [object]
        $Zero,

        [Parameter(ValueFromPipeline=$true, ValueFromRemainingArguments=$true)]
        [object]
        $Obj
    )

    begin
    {
        $acc = $Zero
    }

    process
    {
        if (-not ($Obj -as [object[]]))
        {
            $acc = & $Function $acc $Obj
            return
        }

        foreach ($o in $Obj)
        {
            $acc = & $Function $acc $o
        }
    }

    end
    {
        return $acc
    }
}

function *
{
    $args[0] * $args[1]
}

function +
{
    $args[0] + $args[1]
}
```

```
> fold + 0 1 2 3
6

> 3..7 | fold * 1
2520

> fold + '' 'x','y','z'
xyz
```
