### ISSUE TITLE
Can we get rid of the "address" method?

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#8105]
Looking at any array, even an empty one:

```posh
@().address

OverloadDefinitions
-------------------
System.Object&, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e Address(int )
```

This method can't really be used, right?

```posh
@(1,2).address(0)
No coercion operator is defined between types 'System.Object&' and 'System.Object'.
At line:1 char:1
+ @(1,2).address(0)
+ ~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (:) [], InvalidOperationException
+ FullyQualifiedErrorId : System.InvalidOperationException@(1,2).address(0)
```

But it's getting in the way of stuff like ...

```posh
([xml]'<root>
<user><address>huddledmasses.org</address><anything/></user>
<user><address>github.com</address><else/></user>
</root>').root.user.address
```

**Comment by jcotton42** [comment]
Doing some sleuthing shows that it's only on `T[]` and not `Array` itself
```
> [array].GetMember('Address')
~
> [int[]].GetMember('Address')


Name                       : Address
DeclaringType              : System.Int32[]
ReflectedType              : System.Int32[]
MemberType                 : Method
MetadataToken              : 100663296
Module                     : CommonLanguageRuntimeLibrary
IsSecurityCritical         : False
IsSecuritySafeCritical     : False
IsSecurityTransparent      : True
MethodHandle               : System.RuntimeMethodHandle
Attributes                 : PrivateScope, Public
CallingConvention          : Standard, HasThis
ReturnType                 : System.Int32&
ReturnTypeCustomAttributes : Int32&
ReturnParameter            : Int32&
IsGenericMethod            : False
IsGenericMethodDefinition  : False
ContainsGenericParameters  : False
MethodImplementationFlags  : IL
IsPublic                   : True
IsPrivate                  : False
IsFamily                   : False
IsAssembly                 : False
IsFamilyAndAssembly        : False
IsFamilyOrAssembly         : False
IsStatic                   : False
IsFinal                    : False
IsVirtual                  : False
IsHideBySig                : False
IsAbstract                 : False
IsSpecialName              : False
IsConstructor              : False
CustomAttributes           : {}
```

**Comment by iSazonov** [comment]
Do we create it? Where?

**Comment by Jaykul** [comment]
Sort-of. The actual method is an underlying framework thing.

PowerShell lets you use _property_ syntax to see the overloads of methods, so we turn a method (that is completely **uncallable** in PowerShell, because it returns a pointer, _not an object_), into a method **and** a property -- and then we let the (totally useless) property get in the way of property unrolling syntax such as what is used in XML ...

**Comment by SeeminglyScience** [comment]
I think this particular method is safe to hide.  It's an implementation detail (well, in C# at least) to get a index from multidimensional array by reference ([sharplab example](https://sharplab.io/#v2:C4LglgNgNAJiDUAfAAgBgATIIwG4CwAUMgMyYBM6AwugN6HoOakCuAdgM4CGAZgKaYAWdAFkAFGFbAA2lAC66TgEpa9RmoBOvbugnB0AY3QBedJu2cpqKOiyz8BNQF9CjoA=))

Roslyn hides it as well, along with `Get` and `Set`.

There's some documentation on it in the [CLI Partition 2](https://download.microsoft.com/download/D/C/1/DC1B219F-3B11-4A05-9DA3-2D0F98B20917/Partition%20II%20Metadata.doc) spec on page 63.

**Comment by vexx32** [comment]
Interesting point, @BrucePay, about the `.Count` property. Hashtables have a similar problem, where if you define a `Keys` or `Count` or similar _key_ in a hashtable, the properties of the container become inaccessible.

I think that if we introduce a new operator to access the content specifically, hashtables should be reworked as well to avoid the frankly irritating workarounds (e.g., code like [this](https://github.com/vexx32/PSWordCloud/blob/7dc82bf7bd36477c5782c156f5fcd570d69f76de/PSWordCloud/Public/New-WordCloud.ps1#L414)). (Especially since hashtables already _have_ a perfectly serviceable method of accessing keys.

Which begs the question, I suppose; could we co-opt the hashtable/array syntax for this purpose here as well?

**Comment by BrucePay** [comment]
@vexx32 I didn't understand your last question. Did you mean the array indexing syntax `$foo[13]` ?

**Comment by Jaykul** [comment]
@BrucePay I can see your point about hiding the member, the problem is that it's actually really hard to figure out where the thing came from. It's an **ugly** surprise.

An explicit unrolling operator would be a workaround, but it has the same problem as .foreach: it's not discoverable at all -- and I have no way of knowing that I need it! 

When I type:  `$doc` I see a "root" property, so I type `$doc.root` and I see a "user" so I type `$doc.root.user` and I see the address ...  There's no way for me to know there's a landmine. It doesn't even show up when you pipe the `$doc.root.user | get-member -force` ... 

And then, to add insult to injury, the `Address` method isn't callable in PowerShell, at all.

Of course, the `Address` method is on `[System.Object[]]` which I shouldn't really be dealing with in XML land anyway. Logically speaking this **ought** to be a `System.Xml.XmlElementList` or a `System.Xml.XPathNodeList` or one of those other .NET 1.0 era XML custom collection objects...

**Comment by SteveL-MSFT** [comment]
Removing @PowerShell/powershell-committee review until there is a firm proposal

**Comment by SeeminglyScience** [comment]
This also applies to the default indexer name `Item` (see #19570)

Marking for WG Engine review

**Comment by daxian-dbw** [comment]
The Engine WG reviewed this issue and agreed that the `Address` method should be hidden from the reflection members of the `T[]` type, given that it's not callable from PowerShell and is already hidden in Roslyn.
Implementation-wise, we suggest doing this in the .NET adapter -- filter out the `Address` method when populating reflection members for `T[]` types.
