### ISSUE TITLE
Escape Char with Powershell ISE

### ISSUE THREAD

**Issue by rbabruce** [PowerShell/PowerShell#8110]
I am attempting to use the `b or `r sequence as per https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_special_characters?view=powershell-6

if I use the example in that page and issue the command write-host “backup`b`b out” in Powershell (non ISE) you get “back out” as the output as per the example however if you do this in ISE you get “backup out” instead.

It would appear that ISE cannot handle these two special characters. From what I can tell all the others such as `t and `n work fine.

This is verified by DoctorDNS in the following issue post
https://github.com/PowerShell/PowerShell-Docs/issues/3151

Thanks
Robert

**Comment by mklement0** [comment]
Yes, it appears that the PowerShell host that is part of the ISE doesn't properly render embedded escape sequences as `` `b `` and `` `r` `` in expandable (double-quoted) strings.

However, given that this repo is for PowerShell _Core_, which cannot be used in the ISE, please report your issue at https://windowsserver.uservoice.com/forums/301869-powershell?category_id=148050

**Comment by doctordns** [comment]
As an aside to @mklement0 comment - this code _does_ work inside PWSH 6
