### ISSUE TITLE
Console icon is missing.

### ISSUE THREAD

**Issue by Elderry** [PowerShell/PowerShell#8117]
Steps to reproduce
---
- Open pwsh.exe

Expected behavior
---
- Console opened with correct icon.

Actual behavior
---------------
- Console opened with default icon.
![image](https://user-images.githubusercontent.com/1892221/47479462-de6d5500-d85f-11e8-98f6-59c7143b675c.png)
This images shows that native powershell has correct icon, while powershell core only shows default icon.

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.2.0-preview.1
PSEdition                      Core
GitCommitId                    6.2.0-preview.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
@Elderry did you use the MSI installer or the zip pkg?  This doesn't repro for me.

**Comment by Elderry** [comment]
@SteveL-MSFT MSL installer.

**Comment by thezim** [comment]
Does it work in a normal console? If I’m not mistake you are using cmder.

**Comment by Elderry** [comment]
I figured out that it's my shortcut(lnk) file's problem. Here is the script I used to create shortcut:
```
$shortcut = $(New-Object -ComObject 'WScript.Shell').CreateShortcut($Path)
```
For PowerShell Core, I have to explicitly add this line
```
$shortcut.IconLocation = "$Target, 0"
```
to make console display the correct icon, while Native PowerShell doesn't has this problem.

**Comment by SteveL-MSFT** [comment]
Glad you figured it out!
