### ISSUE TITLE
Why Get-ChildItem ignores parameter

### ISSUE THREAD

**Issue by dvdobrovolskiy** [PowerShell/PowerShell#8118]
Sorry for dump question but why Get-ChildItem ignores variables?

$name = Read-Host "Enter path"
#$folder = Get-ChildItem -Path $name -force -Recurse
#$folder = Get-ChildItem $name -force -Recurse $name
#$folder = Get-ChildItem -force -Recurse "$name "
#any of 3 lines above  Get-ChildItem try to get current folder instead of $name

**Comment by RichardSiddaway** [comment]
What are you entering for the path?

I tried 


PS>  $name = Read-Host "Enter path"
Enter path: c:\test
PS>  Get-ChildItem -Path $name

on PowerShell 6.1, 6.2 preview 1 and Windows PowerShell v5.1.  
In all cases I got a listing for  Directory: C:\test  as requested

**Comment by dvdobrovolskiy** [comment]
5.1

this 
$name = Read-Host "Enter path"
Get-ChildItem -Path $name

works but next doesnot

$name = Read-Host "Enter path"
$folder = Get-ChildItem -Path $name -force -Recurse

mean it works but attempts to access all in root
Get-ChildItem : Отказано в доступе по пути "F:\$RECYCLE.BIN\S-1-5-21-1085864948-1320191706-3175111971-1001".
F:\test.ps1:4 знак:11
+ $folder = Get-ChildItem -Path $name -force -Recurse
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (F:\$RECYCLE.BIN...3175111971-1001:String) [Get-ChildItem], Unauthoriz
   edAccessException
    + FullyQualifiedErrorId : DirUnauthorizedAccessError,Microsoft.PowerShell.Commands.GetChildItemCommand

**Comment by vexx32** [comment]
I'm pretty sure you can't *set* the dates in this fashion, as far as I'm aware. Those properties are, I believe, read-only.

If you can post your full script (with any sensitive data removed), including the path you're entering for Get-ChildItem, I can attempt to isolate the exact problem for you. :)

**Comment by dvdobrovolskiy** [comment]
it was full script))

`$folder = Get-ChildItem  -force -Recurse f:\sensitive data
foreach($object in $folder)
{
     $object.LastWriteTime=("26 December 2017 12:05:00")
	 $object.LastAccessTime=("26 December 2017 12:05:00")
	 $object.CreationTime=("26 December 2017 12:05:00")
}`

and it does change dated for file and folder))
