### ISSUE TITLE
deb packages for Ubuntu 16.04 v6.1.0 and v6.2.0-preview.1 not producing a runnable `powershell` command

### ISSUE THREAD

**Issue by dilijev** [PowerShell/PowerShell#8122]
Steps to reproduce
------------------

```sh
$ wget https://github.com/PowerShell/PowerShell/releases/download/v6.1.0/powershell_6.1.0-1.ubuntu.16.04_amd64.deb
$ sudo dpkg -i ./powershell_6.1.0-1.ubuntu.16.04_amd64.deb
(Reading database ... 129370 files and directories currently installed.)
Preparing to unpack .../powershell_6.1.0-1.ubuntu.16.04_amd64.deb ...
Unpacking powershell (6.1.0-1.ubuntu.16.04) over (6.1.0-1.ubuntu.16.04) ...
Setting up powershell (6.1.0-1.ubuntu.16.04) ...
Processing triggers for man-db (2.7.5-1) ...
$ powershell
powershell: command not found
```

Also repros for the preview package:

```sh
$ wget https://github.com/PowerShell/PowerShell/releases/download/v6.2.0-preview.1/powershell-preview_6.2.0-preview.1-1.ubuntu.16.04_amd64.deb
$ sudo dpkg -i ./powershell-preview_6.2.0-preview.1-1.ubuntu.16.04_amd64.deb
Selecting previously unselected package powershell-preview.
(Reading database ... 129558 files and directories currently installed.)
Preparing to unpack .../powershell-preview_6.2.0-preview.1-1.ubuntu.16.04_amd64.deb ...
Unpacking powershell-preview (6.2.0~preview.1-1.ubuntu.16.04) ...
Setting up powershell-preview (6.2.0~preview.1-1.ubuntu.16.04) ...
Processing triggers for man-db (2.7.5-1) ...
$ powershell-preview
powershell-preview: command not found
```

Expected behavior
-----------------

As with 6.0.0-beta5 (the last version I had installed), the powershell command should work after installing

```sh
$ wget https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-beta.5/powershell_6.0.0-beta.5-1ubuntu1.16.04.1_amd64.deb
$ sudo dpkg -i ./powershell_6.0.0-beta.5-1ubuntu1.16.04.1_amd64.deb
$ powershell
PowerShell v6.0.0-beta.5
Copyright (C) Microsoft Corporation. All rights reserved.

PS /home/doilij/Downloads>
```

**Comment by SteveL-MSFT** [comment]
Starting with PSCore6.0-beta.9, we changed the executable name from `powershell` to `pwsh`.  It'll be `pwsh` going forward.

**Comment by dilijev** [comment]
Hi Steve, I was thinking it was likely the case that the executable was renamed. However, neither the readme, nor the dpkg output, nor any online documentation I could find made this clear. This was definitiely a case of not knowing what I was looking for. Could you please add some more references to this change?

**Comment by SteveL-MSFT** [comment]
@dilijev see the note at the top of the release notes at https://github.com/PowerShell/PowerShell/releases/tag/v6.0.0-beta.9 for when we first announced this.  It also links to the issue with discussion on the reasoning for the change.  We also noted to run `pwsh` in our Linux install instructions: https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-powershell-core-on-linux?view=powershell-6

**Comment by dilijev** [comment]
You can see how, having missed that discussion and the note in that release, and already knowing the name of the package, and how to install packages on Linux, that I would completely miss both of those places. I think visibility on this can be added in places where it would be obvious for the people who think they know what they are doing, or at least the README?
