### ISSUE TITLE
Get-Date -Format R does not correct time to GMT

### ISSUE THREAD

**Issue by RDStewart** [PowerShell/PowerShell#8126]
Steps to reproduce
------------------
Run Get-Date -Format R
```
PS /Users/rdstewart> date;Get-Date -Format R 
Thu Oct 25 18:03:44 CDT 2018
Thu, 25 Oct 2018 18:03:44 GMT
```

Expected behavior
-----------------
I would expect the time to be corrected to GMT.
```
PS /Users/rdstewart> date;Get-Date -Format R 
Thu Oct 25 18:03:44 CDT 2018
Thu, 25 Oct 2018 23:03:44 GMT
```

Actual behavior
---------------
Get-Date -Format R appears to return the local time with the time zone identifier "GMT", even though the time it shows is not actually corrected to GMT.

Environment data
----------------
I have observed this on several Windows 10 systems, one Linux system, and one Mac. The output above is from the Mac. I only have version information from the Mac handy:
```powershell
PS /Users/rdstewart> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Darwin 16.7.0 Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by RDStewart** [comment]
Poking around PowerShell/src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetDateCommand.cs, it looks like the R format specifier doesn't trigger any of the -Format special cases, so it gets passed directly to [DateTime].ToString(Format, CultureInfo.CurrentCulture) on line 304.

I'm not sure where the DateTime object type is defined. I assume it's part of C#, but I don't use C# on a regular basis. Sorry I probably filed this in the wrong project. If someone could point me to the right place, I would appreciate it.

**Comment by SteveL-MSFT** [comment]
@RDStewart you are correct that for unhandled formats, it passes it straight to the .Net API.  In this case, it's equivalent to

> [DateTime]::Now.ToString("R")

Looking at the [.NET documentation for this api](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#the-rfc1123-r-r-format-specifier) it says that it explicitly doesn't convert the datetime and that is something the user must do themselves.  It seems like we could update the cmdlet to support "R" and convert to UTC first.

cc @iSazonov who knows more about this than I

**Comment by chuanjiao10** [comment]
duplicate #7341

**Comment by chuanjiao10** [comment]
PS /root> get-date -uformat %r ; date +%r
09:09:44 上午
上午 09时09分44秒

PS /root> get-date -uformat %R ; date +%R
09:09
09:09

**Comment by SteveL-MSFT** [comment]
@chuanjiao10 comparing to the `date` command, this appears to be "by design"?

**Comment by chuanjiao10** [comment]
en，There are almost no problems,or little

**Comment by SteveL-MSFT** [comment]
Running `date -R` gives the equivalent of `get-date -format R` so we are consistent (or rather .NET Core is consistent).  Expectation is that user converts UTC offset from GMT.

**Comment by iSazonov** [comment]
I confirm.

**Comment by RDStewart** [comment]
Documenting my workaround for anyone else who stumbles on the reported issue. This works consistently for me:

Get-Date -Date (Get-Date).ToUniversalTime() -Format R

It still seems odd that Get-Date by itself emits the current time in every context I have tried _except_ when using "-Format R". I think the RFC1123 formatter should print the correct time zone abbreviation for what it believes it is showing rather than the current state, where it appears to print the letters "GMT" regardless of time zone.

This workaround is acceptable to me, though.

**Comment by RDStewart** [comment]
While looking for this issue to find the workaround I used, I noticed I had missed something in one of the replies.
> Running `date -R` gives the equivalent of `get-date -format R` so we are consistent (or rather .NET Core is consistent). Expectation is that user converts UTC offset from GMT.

`date -R` returns the correct time:

```
PS /Users/rdstewart> date;date -R;Get-Date -Format R
Fri Nov  6 13:24:10 CST 2020
Fri, 06 Nov 2020 13:24:10 -0600
Fri, 06 Nov 2020 13:24:10 GMT
```
The time returned is the same, but `date -R` does not incorrectly claim to be GMT.

The workaround still works for me.
