### ISSUE TITLE
-as operator is unexpectedly selectively culture-sensitive, unlike casts

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#8129]
<sup>Related: #6989</sup>

_Casts_ from _strings_ use the _invariant_ culture whenever the underlying type has a static `::Parse()` method that accepts an `IFormatProvider` parameter.

Surprisingly, the `-as` operator does _not_ exhibit this behavior and instead exhibits _culture-sensitive_ behavior, but does so _inconsistently_.

Steps to reproduce
------------------

```powershell
[cultureinfo]::CurrentCulture = 'fr-FR'

[double] '1,2.3'
'1,2.3' -as [double]

[datetime] '10/20/2018 1:22:33 AM'     # OK, invariant culture is used.
'10/20/2018 1:22:33 AM' -as [datetime] # Yields $null, because the *current* culture is used.
```

Expected behavior
-----------------

```none
12,3
12,3

samedi 20 octobre 2018 01:22:33
samedi 20 octobre 2018 01:22:33
```

Actual behavior
---------------

```none
12,3
12,3
samedi 20 octobre 2018 01:22:33
# !! No output, because the string wasn't recognized as a date.
```

That is, `-as [datetime]` only works with strings that are formatted according to the rules of the _current_ culture; `'20 octobre 2018 01:22:33' -as [datetime]` would work, for instance.

By contrast, `'1,2.3'` _was_ consistently interpreted according to the rules of the _invariant_ culture (where `,` is the grouping char., and `.` the decimal mark; with `fr-FR` in effect, the culture-sensitive `[double]::parse('1,2.3')` would fail).

Environment data
----------------

```powershell
PowerShell Core 6.2.0-preview.1 on macOS 10.14
PowerShell Core 6.2.0-preview.1 on Ubuntu 16.04.5 LTS
PowerShell Core 6.2.0-preview.1 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.165)
Windows PowerShell v5.1.17134.228 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.345)
```

**Comment by RichardSiddaway** [comment]
I can confirm this behaviour

I'm using en-GB culture   so dates are day/month/year

```

PS> [datetime]'25/12/2018 1:00:00 PM'
Cannot convert value "25/12/2018 1:00:00 PM" to type "System.DateTime". Error: "String was not recognized as a valid
DateTime."
At line:1 char:1
+ [datetime]'25/12/2018 1:00:00 PM'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastParseTargetInvocationWithFormatProvider

```

fails as expected. The .NET constructor wants month/day/year so

```
PS> [datetime]'12/25/2018 1:00:00 PM'

25 December 2018 13:00:00

```

This is known .NET related issue since PowerShell v1

The -as operator

```
PS> '25/12/2018 1:00:00 PM' -as [datetime]

25 December 2018 13:00:00

```
accepts and uses the culture specific date format

whereas

'12/25/2018 1:00:00 PM' -as [datetime]

returns null

Checked this on
PowerShell v5.1, v6.1, v6.2 preview 1 on Windows 10 1803 Build 17134.345

My PowerShell v6.1 on WSL uses en-US culture so I get these results


PS /home/Richard> '25/12/2018 1:00:00 PM' -as [datetime]
PS /home/Richard> '12/25/2018 1:00:00 PM' -as [datetime]

Tuesday, December 25, 2018 1:00:00 PM

and

[datetime]'12/25/2018 1:00:00 PM'
[datetime]'25/12/2018 1:00:00 PM'


work as previously shown as expected

**Comment by mklement0** [comment]
Thanks for confirming the issue, @RichardSiddaway.

> The .NET constructor wants month/day/year so
> This is known .NET related issue since PowerShell v1

It's actually _PowerShell_ that _by design_ opts for interpreting strings using the _invariant culture_, for predictability across cultures.

Also note that there's no _constructor_ involved in this case (there is none that accepts a _string_ in this case): PowerShell calls the `[datetime]` type's static `.Parse()` method, and explicitly chooses the overload that allows it to pass the invariant culture as the culture to interpret the input string by.

For instance, behind the scenes,

```powershell
[datetime] '12/25/2018 1:00:00 PM'
```

is effectively translated to:

```powershell
[datetime]::Parse('12/25/2018 1:00:00 PM', [cultureinfo]::InvariantCulture)
```

Also note that, fortunately, it isn't just US-style month-first dates that the invariant culture recognizes; there are formats that are less confusing to international audiences; e.g.:

```powershell
[datetime] '2018-12-25 13:00:00'
```

**Comment by RichardSiddaway** [comment]
Irrespective of the exact mechanism there is still a mismatch between cast and -as as shown in both sets of examples

**Comment by iSazonov** [comment]
I guess that unification here will big breaking change.
Perhaps we could resolve all related issues introducing globally "invariant culture mode" like .Net Core now has. Only we have to review all code and add Culture parameter in most of cmdlets.

**Comment by mklement0** [comment]
I assume you're referring to [.NET Core Globalization Invariant Mode](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/globalization-invariant-mode.md); correct, @iSazonov?

From my limited understanding this is a per-application configuration setting.

Can you say more about how this could fit into PowerShell, and what the `-Culture` parameters would do?

**Comment by iSazonov** [comment]
Yes, I thought that we could set CurentCulture to Invariant. I don't think about this in depth but it could be interesting.

**Comment by RichardSiddaway** [comment]
This has the potential to be a huge breaking change.  As a first step I'd suggest that the PowerShell documentation should be revised to reflect the difference in behaviour between cast and -as

**Comment by mklement0** [comment]
Re documenting the behavior: good idea - see https://github.com/PowerShell/PowerShell-Docs/issues/3193 and, for #6989, https://github.com/PowerShell/PowerShell-Docs/issues/3194

**Comment by mklement0** [comment]
To make matters worse, I just realized that even the behavior of `-as` itself is internally inconsistent:

E.g., using `-as [double]` is again culture-_invariant_ (I've added an example to the OP) - unlike `-as [datetime]`.

I haven't dug deeper to see what logic underlies this discrepancy
