### ISSUE TITLE
Improve contents of $PSVersionTable Automatic Variable with Windows Edition Number

### ISSUE THREAD

**Issue by doctordns** [PowerShell/PowerShell#8136]
Currently, the $PSVersionTable automatic variable provides a number of key properties of the version of PowerShell running. One thing missing from that variable is the Edition value of the running Windows OS.

Steps to reproduce
------------------

```powershell

PS [C:\foo> ]> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.18262
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.1.0}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Expected behavior:

````powershell
PS [C:\foo> ]> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.18262
Edition                        1809
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.1.0}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
Actual behavior
---------------

The automatic variable does not currently contain the Edition whereas running WInVer provides that. You can also use a WMI call. But Updating $PSVersionTable would be very useful.

**Comment by SteveL-MSFT** [comment]
`[System.Environment]::OSVersion` may be what you are looking for.  I don't think we want to keep making `$PSVersionTable` bigger.  Would rather have a cross-platform `Get-ComputerInfo` that has OS info.

**Comment by doctordns** [comment]
[System.Environment]::OSVersion does not return the Edition of WIndows 10. :-(

**Comment by SteveL-MSFT** [comment]
@doctordns `Get-ComputerInfo` as it exists today is expensive to run and I don't think returns info the user wants in a consumable form most of the time.  If you can explain the use case where you need this info, it would help to justify adding it.

**Comment by iSazonov** [comment]
Another note is that PowerShell is portable - what is Edition on Unix? I think that for consistency it should be in CoreFX.
