### ISSUE TITLE
Update-Help fails to update six built-in modules

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShell#8141]
Steps to reproduce
------------------

```powershell
Update-Help -Force
```

Expected behavior
-----------------

```none
That help is updated with no errors.
```

Actual behavior
---------------

```none
Update-Help : Failed to update Help for the module(s) 'Appx, NetworkTransition, SecureBoot, SmbWitness, TrustedPlatformModule, WindowsUpdateProvider' with UI culture(s) {en-US} : One or more errors occurred. (A task was canceled.)
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by adityapatwardhan** [comment]
@rkeithhill I could not reproduce the problem for `WindowsUpdateProvider`. 

Can you give me the output of the `Update-Help -Force -Verbose <modulename>` for the others?

**Comment by adityapatwardhan** [comment]
Does `Update-Help` for those modules also fail from `Windows PowerShell`?

**Comment by rkeithhill** [comment]
Well, all the **other** modules update for me now (when updating the individual modules).  Just tried with `update-module -force` and yeah. only `WindowsUpdateProvider` is failing atm.

**Comment by adityapatwardhan** [comment]
Glad to hear that. I am following up on the `WindowsUpdateProvider` module.

**Comment by houstdav000** [comment]
So far as I can tell, this still seems to be an issue, regardless of powershell version. I've had it happen in 5.1, 6.2.3, 7.0.0-preview.5, and every other version. Powershell 6.2.3 Gives that the WindowsUpdateProvider is receiving a 404 error, while the other modules state that "A Help URI cannot contain more than 10 redirections. Specify a valid Help URI"

**Comment by houstdav000** [comment]
Okay, for that 404, I just used WireShark, and it's trying to download the HelpInfo from `http://download.microsoft.com/download/D/4/B/D4BFF683-2CDD-4424-925F-16F07A04F44E/WindowsUpdateProvider_faed25e4-6939-439d-8c13-4778ac5ac8a7_HelpInfo.xml`

**Comment by sdwheeler** [comment]
The ones owned by the PowerShell team have been fixed or are being tracked in other issues. For modules not owned by the PowerShell team, issues should be opened with the appropriate owners.

@iSazonov I think this issue can be closed.
