### ISSUE TITLE
$PWD, at launch from taskbar, should default to $home on Windows

### ISSUE THREAD

**Issue by HemantMahawar** [PowerShell/PowerShell#8144]
Steps to reproduce
------------------
- Set the content of `$PROFILE.CurrentUserAllHosts` (`profile.ps1` under `$home\Documents\PowerShell`) to print $PWD (such as `Write-Verbose -Message $pwd -Verbose`)
- Launch PWSH or PWSH-Preview from taskbar icon
- Does **NOT** repro if starting PWSH or PWSH-Preview using full path

> Note: The shortcut **Target** property is set to `"C:\Program Files\PowerShell\6 (or 6-preview)\pwsh.exe" -WorkingDirectory ~`

Expected behavior
-----------------
- It should list user's `$home` as the current working directory

Actual behavior
---------------
- It produces `VERBOSE: C:\WINDOWS\system32` as the output

Environment data
----------------
```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0 or 6.2.0-preview.1
PSEdition                      Core
GitCommitId                    6.1.0 or 6.2.0-preview.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by HemantMahawar** [comment]
@SteveL-MSFT while you are working on #8079, maybe look at this as well ;)

**Comment by vexx32** [comment]
I don't think it can be fixed in both cases.

If we process profile before applying working directory, per @SteveL-MSFT's PR, we cannot also give the profile script access to the *about-to-be-set* working directory via $pwd.

If we retain current behaviour, where profile script is processed after, a `Set-Location` call in the profile script will unilaterally override anything set on the shortcut.

**Comment by SteveL-MSFT** [comment]
I tested against #8079 and the `$profile.CurrentUserAllHosts` starts in $HOME
