### ISSUE TITLE
Get-CimInstance : FAILED

### ISSUE THREAD

**Issue by apetitjean** [PowerShell/PowerShell#8147]
I have the exact same behaviour than in #4466 issue.

I'm on Windows Server 2008R2 SP2.

To give you more context, I've just unziped the PS Core 6.1 archive to run it. 
I haven't used the MSI installer because it wanted me to install the WMF 4.0 minimum (because of WinRM). As I don't need WinRM, I prefer not to update WMF.

Hence, on my server I only have Windows PowerShell 2.0 installed.

Steps to reproduce
------------------

```powershell
Get-CimInstance Win32_Process

Get-CimInstance : FAILED
At line:1 char:1
+ Get-CimInstance Win32_Process
+ ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo            : NotSpecified: (:) [Get-CimInstance], CimException
+ FullyQualifiedErrorId : Microsoft.Management.Infrastructure.CimException,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand
```

Expected behavior
-----------------

```none

```

Actual behavior
---------------

```none

```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.16299 
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Did you see the comment https://github.com/PowerShell/PowerShell/issues/2777#issuecomment-343571939 ?
