### ISSUE TITLE
Add a new parameter Raw to ConvertFrom-StringData

### ISSUE THREAD

**Issue by PoshKazun** [PowerShell/PowerShell#8149]
Currently, ConvertFrom-StringData doesn't have a param to use  unescaped strings. You should invoke additional commands to escape strings (Regex.Escape or a preceding backslash( \\), etc..).  It would be convenient to use a single param(for example -Raw) without additional conversions.

http://csharpindepth.com/Articles/General/Strings.aspx

The complete set of escape sequences is as follows:

\' - single quote, needed for character literals
\" - double quote, needed for string literals
\\ - backslash
\0 - Unicode character 0
\a - Alert (character 7)
\b - Backspace (character 8)
\f - Form feed (character 12)
\n - New line (character 10)
\r - Carriage return (character 13)
\t - Horizontal tab (character 9)
\v - Vertical quote (character 11)
\uxxxx - Unicode escape sequence for character with hex value xxxx
\xn[n][n][n] - Unicode escape sequence for character with hex value nnnn (variable length version of \uxxxx)
\Uxxxxxxxx - Unicode escape sequence for character with hex value xxxxxxxx (for generating surrogates)
Of these, \a, \f, \v, \x and \U are rarely used in my experience.

Steps to reproduce
------------------

```powershell
ConvertFrom-StringData 'foo=abc\n\t\rabc'
```

**Comment by mklement0** [comment]
Please correct the name of the cmdlet in the issue title (`Convert-StringData` -> `ConvertFrom-StringData`).

Are you saying you want the option to treat the input strings as _literals_, i.e., without the usual interpretation of the escape sequences?

**Comment by chuanjiao10** [comment]
My guess：
Add a new parameter “-Delimiter” to Convert-StringData

str：
abc\n\tdef
111\n\t222   

then use:
Convert-StringData “-Delimiter” "`n`t"

**Comment by lzybkr** [comment]
I don't see a good reason to use C# style escapes.

Assuming you wouldn't mind PowerShell style escapes, there is an api you can use:

```powershell
ConvertFrom-StringData $ExecutionContext.InvokeCommand.ExpandString('foo=abc`n`t`rabc')
```

**Comment by boernsen-development** [comment]
I have problems converting the following text:

```powershell
PS> $string = "Path = test\test.txt 
Size = 123456789"
```

What is actually want is:

```powershell
Name                           Value
----                           -----
Path                           test\test.txt
Size                           123456789
```

However, converting it yields:

```powershell
PS> $string | ConvertFrom-StringData

Name                           Value
----                           -----
Path                           test     est.txt
Size                           123456789
```

Apparently `\t` is interpreted as tab. Just escaping everything is wrong either as it also escapes the required newlines preventing `ConvertFrom-StringData` from converting properly:

```powershell
PS> [regex]::Escape($string)
Path\ =\ test\\test\.txt\ \nSize\ =\ 123456789

PS> [regex]::Escape($string) | ConvertFrom-StringData

Name                           Value
----                           -----
Path\                           test\test.txt …
```

What is the recommended workaround without manually replacing characters? Shall I open a new issue?
