### ISSUE TITLE
Tabs completion disappear when the parameter type is uint

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#8153]
When i change parameter type from "int" to "uint",Tabs completion disappear in command line

Note:
 This also affects vscode.

Steps to reproduce
------------------

a.ps1:

```powershell

param
(
[uint]$abc
)

```

a.ps1 -tabkey  # Tabs completion disappear,but "[int]$abc" normal.

b.ps1:

```powershell

param
(
[uint]$abc,
[int]$def
)

```

b.ps1 -tabkey  # Tabs completion disappear, **any with  "[uint]$abc"** 

Important information:
------------------
1 This bug exists in 6.1 and **has been fixed** in 6.2 preview.1.

2 No issue, no pr. No one knows who was fixed and what was fixed. From a professional perspective, we should not condone this.

3 Both versions are using PSReadLine 2.0.0-beta3 (#7711), so I guess it has nothing to do with psreadline.

4 win10 17663.1 rs5 + powershell 5.1 has this bug,After i install PSReadLine 2.0.0-beta3, bug still.

**We must have an issue and pr and test about this bug**, right?
about this bug, i post issue，need test code now.

Environment data
----------------
centos75 + ps v6.1  #has this bug

centos75 + ps v6.2.0-preview.1  #not this bug

reporter
----------------
By the chinese powershell study & research group. QQ group No. is 183173532

**Comment by vexx32** [comment]
I'm not 100% sure, but there's a good chance this was resolved due to my PRs.

Pretty sure before I edited things `[uint]` was *not* a valid type unless you manually add the accelerator.

If you type it as `[uint32]` it should still tab complete correctly in the old version.

**Comment by chuanjiao10** [comment]
yes ,you right.
i confirm byte,sbyte,int16,uint16,int32,uint32,int64,uint64,single,double,decimal. on 6.1 version. all normal.

**only uint ,or with uint ,has this bug ,on 6.1 version.**

**Comment by vexx32** [comment]
Unless there is a particularly pressing need (or you can convince the PS team) I doubt it will be backported to PS 5.1. It's not a bug, it's just a new feature I added in as seemed appropriate with the new numeric literals I've been working on.

You'll note also that `long` and `ulong` accelerators are missing in order versions, but present in the current preview.

In discussion on the relevant PRs (linked in the most recent issue release / changelog) I believe the concern was raised, and the consensus was *don't use the new type accelerators if you plan on running the script on older versions of PS*.

It's there as a kindness and convenience measure to assist users who wish to be able to use the new type literals more seamlessly. It was never expected to be backported, at least in my mind.

/cc @SteveL-MSFT, if you have anything to add here?

**Comment by SteveL-MSFT** [comment]
@vexx32 is exactly right.  5.1 is considered done with exception of critical security fixes.  PSCore6 runs happily side-by-side with 5.1 so if one wants to leverage the new features, they should use PSCore6 on Windows.
