### ISSUE TITLE
When running 'update-ca-trust' (or equivalent) on Linux, you must exit pwsh and re-enter before Invoke-RestMethod (and similar) recognize the new trust

### ISSUE THREAD

**Issue by pldmgg** [PowerShell/PowerShell#8156]
Steps to reproduce
------------------

- From a pwsh session, add a new CA .pem file to `/etc/pki/ca-trust/source/anchors` (or equivalent location for your Linux distro).
- Run `update-ca-trust` (or equivalent command for your Linux distro).
- Try and use `Invoke-RestMethod` (or similar) on an HTTP API using TLS. It will fail saying it doesn't trust the certificate.
- Exit pwsh
- Enter pwsh
- Try the same `Invoke-RestMethod` (or similar) operation, and it will succeed

Expected behavior
-----------------

Using `Invoke-RestMethod` (or similar) after running `update-ca-trust` (or similar) should succeed without having to exit pwsh and start a new pwsh process.

**Comment by SteveL-MSFT** [comment]
This looks like https://github.com/dotnet/corefx/issues/32576
