### ISSUE TITLE
Powershell 6.2 facing issue on opening my application

### ISSUE THREAD

**Issue by manoj2994** [PowerShell/PowerShell#8181]
Hi i have downloaded powershell 6.2 package for my windows 7 sp 1 version.and i ensured that wmf 5.1,.net core and c runtime also installed when i open powershell 6.2 application the window opens and closes immediately and iam sure installed can someone please help me on this

**Comment by iSazonov** [comment]
@manoj2994 Please update the issue description. Perhaps Google translate helps you.

**Comment by manoj2994** [comment]
@isazonov may be my english is not good anyway thanks. i found the solution.its just missing of  dotnet core dependency packages for win 7 .its working now
