### ISSUE TITLE
Crash on backspace at start of line, in stdin/stdout mode

### ISSUE THREAD

**Issue by bugale** [PowerShell/PowerShell#8193]
Steps to reproduce
------------------
Run the following python code:

```
import subprocess
ps = subprocess.Popen("powershell.exe", stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
ps.stdin.write(b'\b')
ps.stdin.flush()
```

Expected behavior
-----------------
Since no character was sent, the backspace should be ignored

Actual behavior
---------------
Crash, at ConsoleHostUserInterface.cs:1390.
``` sb.Remove(sb.Length - 1, 1); ``` is called, but sb.Length is 0

https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs#L1386-L1396

How to fix
----------------
There should be a check for the length of the string builder, and the code should ignore the backspace if the length is 0

**Comment by MaximoTrinidad** [comment]
@bugale 

Please, you need to provide the PowerShell Core version and operating system information as has been requested in the template when creating the issue.

On this repository, Windows PowerShell issues are not been addressed.  This is only for PowerShell Core issues.  (More information at: https://github.com/PowerShell/PowerShell#windows-powershell-vs-powershell-core)

Thanks!

**Comment by MaximoTrinidad** [comment]
Sorry for that!  I notice later you're using python.

In the future, please provide the information the issue templates are asking as it help everyone understand what you're working with and on what OS you're having issues.

Thanks again,
:)

**Comment by bugale** [comment]
Okay, sorry, and thanks for informing me. The issue by the way, occurs both on Windows PowerShell, and Powershell Core in probably all versions.
I opened a pr to fix this issue.

**Comment by MaximoTrinidad** [comment]
Awesome!  Remember the PR only impact PowerShell Core, as for Window PowerShell there's no more changes done to it moving forward. Work on Windows PowerShell is complete!

Thanks for the PR!

:)

**Comment by adityapatwardhan** [comment]
Issue re-opened as the PR was reverted by change #8239
