### ISSUE TITLE
InformationRecord should derive from InformationalRecord

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#8201]
I find it bewildering that _of all the Record types_, the **Information** record isn't an `InformationalRecord`

That is, the [InformationRecord](https://github.com/PowerShell/PowerShell/blob/5d03e1653a7d518715fa3f00587cad6b5c78cc89/src/System.Management.Automation/engine/InformationRecord.cs) class does not derive from the [InformationalRecord](https://github.com/PowerShell/PowerShell/blob/5d03e1653a7d518715fa3f00587cad6b5c78cc89/src/System.Management.Automation/engine/hostifaces/InformationalRecord.cs) class the way that the Verbose, Debug, and Warning records do.

It looks to me like we could make it inherit without much fuss, and the missing PipelineIterationInfo and especially the InvocationInfo properties would be very useful for a variety of applications of the InformationRecord and it's tag-based filtering.

**Comment by Jaykul** [comment]
For consistency, I would love it if ErrorRecord could derive from this too -- although it already has stuff like the ScriptStackTrace, etc, so it probably doesn't matter...

Also, for what it's worth, I wouldn't suggest Progress inherit this, because it's already slower than we'd like ;-)

**Comment by vexx32** [comment]
Progress needs a whole revamp in itself really. See #7983

**Comment by BrucePay** [comment]
@Jaykul If you look at the source, you'll see that `InfomationRecord` is an elaboration on writing a string to the console i.e. `Write-Host`.  It exists for an entirely different purpose than InformationalRecord which provides metadata about the runtime state of the engine. In other words, an `InfomationRecord` is  _from_ an application and an `InformationalRecord` is _about_ an application. The name collision is unfortunate but isn't going to change given they're both public classes.
