### ISSUE TITLE
Enable PreAuth with webcmdlets

### ISSUE THREAD

**Issue by TiloGit** [PowerShell/PowerShell#8202]
How can PreAuthenticate be used with "Invoke-WebRequest"? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ee17672-1f7a-9955-294d-3a38d83663c6
* Version Independent ID: fea87b3b-67e8-dbe5-dfb3-d60a5ebe0d39
* Content: [Invoke-WebRequest (Microsoft.PowerShell.Utility)](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/invoke-webrequest?view=powershell-3.0)
* Content Source: [reference/3.0/Microsoft.PowerShell.Utility/Invoke-WebRequest.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Utility/Invoke-WebRequest.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by SteveL-MSFT** [comment]
@TiloGit following the example in the article, currently you would have to create the appropriate `Authorization` header and use like:

```powershell
invoke-webrequest -headers @{authorization=$myauthheader} $url
```

I believe `-Credential` only works on the 401 response.

It doesn't seem that there are many websites that require pre-auth, however, implementing this should be pretty straight forward if only BASIC auth is required.

**Comment by lukexjeremy** [comment]
The [comment from Jon Hanna](https://weblog.west-wind.com/posts/2010/Feb/18/NET-WebRequestPreAuthenticate-not-quite-what-it-sounds-like#cmt_709615) on Rick Strahl's article raises a good point too. Waiting for a 401 is the best default. That 401 could offer digest auth, but you've lost that security gain if you've already sent basic credentials.

Perhaps sending the basic credentials upfront could be a switch parameter, e.g. `-PreemptBasicAuth` or `SendBasicCredentialsFirst`, with documentation explaining the use case. 

I wouldn't mind having a go at this, providing I'm on the right track.

**Comment by lukexjeremy** [comment]
Has this been addressed recently?

Just tried `Invoke-WebRequest -Uri google.com -AllowUnencryptedAuthentication -Authentication Basic -Credential (Get-Credential)` and Wireshark displayed the following in the first packet sent. 

![image](https://user-images.githubusercontent.com/36614708/49081914-ffc4c500-f293-11e8-88a0-ea32a8ea04f5.png)

I followed this through in a debugger as well and it appears that the credentials were sent immediately.

**Comment by TiloGit** [comment]
Hi, don't have PS 6 around, so can't test with "-AllowUnencryptedAuthentication -Authentication Basic"

**Comment by TiloGit** [comment]
tested on PS 611 and seems fine with new options:  "-AllowUnencryptedAuthentication -Authentication Basic"
PS C:\tools> $PSVersionTable

> Name                           Value
> PSVersion                      6.1.1
> PSEdition                      Core
> GitCommitId                    6.1.1
> OS                             Microsoft Windows 6.3.9600
> Platform                       Win32NT
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
> PSRemotingProtocolVersion      2.3
> SerializationVersion           1.1.0.1
> WSManStackVersion              3.0

**Comment by markekraus** [comment]
@lukexjeremy provided the answer. We added explicit authentication in v 6.0.0. Closing issue.
