### ISSUE TITLE
Invoking a ScriptBlock without a local scope but with underbar?

### ISSUE THREAD

**Issue by Zhentar** [PowerShell/PowerShell#8208]
I have two script blocks, "A" and "B". I want to invoke "A", and then later invoke "B", and have variables set by "A" available to "B". I've found a number of ways to achieve that by itself; the wrinkle however is that I also need `$_` to be populated when "A" is invoked.

This (seems to) do exactly what I want:
```cs
var invokeWithinModule = new PSModuleInfo(false);
script = invokeWithinModule.NewBoundScriptBlock(script);
var result = script.DoInvokeReturnAsIs(useLocalScope: false,
                                       errorHandlingBehavior: 2 /*writeToCurrentErrorPipe */,
                                       dollarUnder: inputObject,
                                       input: AutomationNull.Value,
                                       scriptThis: AutomationNull.Value,
                                       args: null);
```

The only trouble being that `DoInvokeReturnAsIs` is not a public function.

I've been trying to find a way to do this without touching other peoples' `private`s or `internal`s, and have not had any success; there does not seem to be any public API surface that both invokes without local scope and populates underbar (except for `Measure-Command`, but that outputs to a null pipe). I've also tried intermediate script blocks and using the dot source operator, e.g.:
```cs
script = invokeWithinModule.NewBoundScriptBlock(script);
var invokeWrapperBlock = invokeWithinModule.NewBoundScriptBlock(ScriptBlock.Create("$args[0] | . $args[1]"));
results = invokeWithinModule.SessionState.InvokeCommand.InvokeScript(false, invokeWrapperBlock, null, inputObject, script);
```
But for reasons beyond my ken the code in "script" never sees `$_` (or anything else from the wrapper) at all.

Is there a decent way to achieve this? Should there be?

**Comment by SeeminglyScience** [comment]
The closest to what you want to achieve is `ScriptBlock.InvokeWithContext`, e.g.

```powershell
{ $_ }.InvokeWithContext(
    @{},
    [System.Collections.Generic.List[psvariable]][psvariable]::new('_', 'underBarValue'),
    @())
# underBarValue
```

That *does* create a new scope though, so it isn't perfect.

It would be nice if there was a `useLocalScope` parameter on `InvokeWithContext`, or even an API closer to `DoInvokeReturnAsIs` where you could explicitly set `dollarUnder`, `scriptThis`, `args`, `input` and `useLocalScope` would be really useful. (`errorHandlingBehavior` is probably unnecessary for a public API though)
