### ISSUE TITLE
Copy-Item fails with [ in dir or file name

### ISSUE THREAD

**Issue by schnitz76** [PowerShell/PowerShell#8212]
Steps to reproduce
------------------

New-Item "E:\Personal\TEST_FROM\Dir_0_0" -ItemType Directory
New-Item "E:\Personal\TEST_FROM\Dir_0_[1" -ItemType Directory
New-Item "E:\Personal\TEST_FROM\Dir_0_[2]" -ItemType Directory
New-Item "E:\Personal\TEST_FROM\Dir_0_3]" -ItemType Directory
New-Item 'E:\Personal\TEST_FROM\New Text Document.txt'
New-Item 'E:\Personal\TEST_FROM\New Text Document [2.txt'
New-Item 'E:\Personal\TEST_FROM\New Text Document [2].txt'
New-Item 'E:\Personal\TEST_FROM\New Text Document 2].txt'

$SourceLocation = "E:\Personal\TEST_FROM\"
$DestinationLocation = "E:\Personal\TEST\"

Get-ChildItem "E:\Personal\TEST_FROM\"

$SourceFileList = @(Get-ChildItem -Recurse $SourceLocation)
$DestinationFileList = @(Get-ChildItem -Recurse $DestinationLocation)
$CompareResult = Compare-Object -ReferenceObject $SourceFileList -DifferenceObject $DestinationFileList -IncludeEqual

foreach ($obj in $CompareResult){
    $FullSourceObject = $obj.InputObject.FullName
    $FullDestinationObject = $obj.InputObject.FullName.Replace($SourceLocation, $DestinationLocation)
    if ($obj.SideIndicator -eq "<="){Copy-Item -Path $FullSourceObject -Destination $FullDestinationObject}
}

Get-ChildItem "E:\Personal\TEST"

Expected behavior
-----------------

Get-ChildItem "E:\Personal\TEST" should match Get-ChildItem "E:\Personal\TEST_FROM\"

Actual behavior
---------------

PS C:\Program Files\PowerShell\6> Get-ChildItem "E:\Personal\TEST_FROM\"

    Directory: E:\Personal\TEST_FROM

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        11/8/2018   9:57 AM                Dir_0_[1
d-----        11/8/2018   9:57 AM                Dir_0_[2]
d-----        11/8/2018   9:57 AM                Dir_0_0
d-----        11/8/2018   9:57 AM                Dir_0_3]
-a----        11/8/2018   9:57 AM              0 New Text Document [2.txt
-a----        11/8/2018   9:57 AM              0 New Text Document [2].txt
-a----        11/8/2018   9:57 AM              0 New Text Document 2].txt
-a----        11/8/2018   9:57 AM              0 New Text Document.txt

PS C:\Program Files\PowerShell\6> Get-ChildItem "E:\Personal\TEST"

    Directory: E:\Personal\TEST

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        11/8/2018   9:57 AM                Dir_0_0
d-----        11/8/2018   9:57 AM                Dir_0_3]
-a----        11/8/2018   9:57 AM              0 New Text Document 2].txt
-a----        11/8/2018   9:57 AM              0 New Text Document.txt

Environment data
----------------

PS C:\Program Files\PowerShell\6> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by SteveL-MSFT** [comment]
@schnitz76 can you try your repro with `-LiteralPath`?

**Comment by schnitz76** [comment]
Copy-Item -LiteralPath does work as intended.  Is this by design?  If so I apologize for the trouble.

**Comment by kvprasoon** [comment]
@schnitz76  Yes and is somewhat clear from the help doc.

```
♥->Get-Help Copy-Item -Parameter literalpath

-LiteralPath <String[]>
    Specifies a path to the item. The value of the LiteralPath parameter is used exactly as it is typed. No characters
    are interpreted as wildcards. If the path includes escape characters, enclose it in single quotation marks. Single
    quotation marks tell Windows PowerShell not to interpret any characters as escape sequences.

    Required?                    true
    Position?                    named
    Default value                None
    Accept pipeline input?       True (ByPropertyName)
    Accept wildcard characters?  false
```

**Comment by mpawelski** [comment]
As a _casual_ powershell user I've been beaten by this many times. This is one of many gotchas for beginners that really discourage people from using pwsh. 

@SteveL-MSFT  Maybe now that powershell has future outside of windows we can do some breaking changes for this common gotchas? I mean change the default behavior to be less error prone and more beginner friendly (in other words Powershell should fall you into [The Pit of Success](https://blog.codinghorror.com/falling-into-the-pit-of-success/) for common scenarios). In the case of `Copy-Item` maybe `-Path` should have `-LiteralPath` behavior and we should add `-WildcardPath` param as other option?

**Comment by vexx32** [comment]
That would be a rather extensive breaking change, frankly speaking... there are a *lot* of cmdlets that have `-Path`/`-LiteralPath` parameters. And if you change it just for this one cmdlet, it then becomes another exception for people to memorise. Not fixing the problem, just changing the problem at hand here.

**Comment by mpawelski** [comment]
Well, I'm speaking from perspective of very casual powershell user that writes one or two scripts every couple of months.

So I clearly don't represent powershell community here with huge number of scripts already written and I don't know how big of an impact this breaking change could be.
I just never needed wildcards functionality of `-Path`. It just always feel natural to write `cp path destination` when I write some script and I always die a little bit inside when I get error because my file path had `[` inside 😉. And I think there are many people like me.

**Comment by schnitz76** [comment]
I will close this as user error.

**Comment by SteveL-MSFT** [comment]
@mpawelski we've done a bunch of work to make PowerShell work better on non-Windows and we'll continue to do so.  We can also make changes to help new users.  However, we also have to be careful not to break existing users.  If there's a way to improve the experience without introducing a breaking change, I'd love to hear it :)

**Comment by kvprasoon** [comment]
@mpawelski When there is a help documentation for a script/cmdlet , its always safe and good if we read the documentation properly even for one time use.
