### ISSUE TITLE
Request: provide password to SSH (or -Credentials support)

### ISSUE THREAD

**Issue by estein9825** [PowerShell/PowerShell#8213]
Is there a way to provide a password inline to the powershell SSH command?  I know there is a Keyfile option, but it can create issues if someone gets ahold of the public key.  This is going to be deployed to a virtual machine that will be able to then communicate with multiple Linux instances, which means anyone with the public key could log into those Linux instances.

It would be great if SSH offered support for the -Credentials flag as well.

**Comment by SteveL-MSFT** [comment]
What you're asking for is https://github.com/PowerShell/PowerShell/issues/5782

If someone gets ahold of your public key, that would only allow them to allow you access to something.  The private key is needed to authenticate against the public key and you should keep the private key safe.  The public key (hence the name) is ok to be public.
