### ISSUE TITLE
Start-Transcript sporadically loses exe output

### ISSUE THREAD

**Issue by AceHack** [PowerShell/PowerShell#8215]
About half the time there is not output result in the $logFile even though on the console there was plently of output.  The other half of the time there is output in the $logFile.  It seems very random on if the output works or not.  Actually I would say a little less than half the time the helm ouput does NOT appear in the $logFile.

I'm using PowerShell core 6.1 on Windows 10.

```
Start-Transcript -Force -IncludeInvocationHeader -Path $logFile
try {
    helm upgrade --install --wait --force --debug -f ./helm/zookeeper/values.yaml platform-zookeeper ./helm/zookeeper
} finally {
    Stop-Transcript
}
```

This also happen with `kubectl` commands as well.

**Comment by AceHack** [comment]
This appears to be a similar issue.

http://web.archive.org/web/20130608164153/http://connect.microsoft.com/PowerShell/feedback/details/315875/unable-to-capture-all-session-output-into-a-transcript

**Comment by iSazonov** [comment]
Do you get a _random_ output in transcript file run by run?
