### ISSUE TITLE
The values of the scope parameter should be consitent accross cmdlets, where they mean the same thing

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#8216]
https://twitter.com/Jaykul/status/1060278217360195584 . @jaykul
```
Naming is hard. Not THIS hard, but hard:

Set-ExecutionPolicy -Scope LocalMachine
Install-Module -Scope AllUsers
New-PSDrive -Scope Global -Persist
```

**Comment by rjmholt** [comment]
Perhaps we need the concept of a "session scope" or something to unify all the things that can be system-wide, shared between users, or user-specific, and have that as an API (like a layered stack) that all these cmdlets can read from?

**Comment by TravisEz13** [comment]
We also need to think about compatibility, unless we want to break everyone.

Also, one of the cmdlets is in PowerShellGet ...
