### ISSUE TITLE
Implement PowerShell Direct

### ISSUE THREAD

**Issue by andschwa** [PowerShell/PowerShell#822]
Where PSRP can take place over the host/guest path provided by the LIS drivers for Linux VMs running on Hyper-V.

**Comment by andschwa** [comment]
@bgelens I'm pretty sure that the LIS drivers live in the Linux tree, and have for quite some time; thus, they're available for [far more than just RHEL/CentOS](https://technet.microsoft.com/windows-server-docs/compute/hyper-v/supported-linux-and-freebsd-virtual-machines-for-hyper-v-on-windows), and are built-in.

If you're running Linux 4.x, you'll have Hyper-V sockets for sure. If you're running any of PowerShell's supported Linux distributions, you have LIS drivers. The only edge case is CentOS 7, and it by default will still have LIS built-in, but if you stuck with Linux 3.10 (unlikely), you won't have sockets, in which case you'd need to backport the drivers (or install a modern kernel).

**Comment by bgelens** [comment]
@andschwa I wouldn't take socket support for granted currently. LIS drivers are certified by the distros and in my experience are always a bit lagging. Great Ubuntu is in line but [Suse](https://technet.microsoft.com/windows-server-docs/compute/hyper-v/supported-suse-virtual-machines-on-hyper-v), [CentOS / RHEL 7 - 7.2](https://technet.microsoft.com/windows-server-docs/compute/hyper-v/supported-centos-and-red-hat-enterprise-linux-virtual-machines-on-hyper-v) and [Debian ](https://technet.microsoft.com/windows-server-docs/compute/hyper-v/supported-debian-virtual-machines-on-hyper-v) don't have socket support out of the box yet.
Unfortunately the distros running on Hyper-V in the Enterprise (at least my customers) are mostly RHEL based and thus need additional work to have this available.
Then again, when PSv6 will be GA? Hopefully all distros have updated their build-in Hyper-V drivers.
My comment was mend to raise awareness, not to undermine the importance of this feature.
Don't get me wrong, I'm in big favor of this feature! Please make this available :-)
