### ISSUE TITLE
Command not working in .NET Core console app, but working directly in PowerShell

### ISSUE THREAD

**Issue by casrou** [PowerShell/PowerShell#8226]
Steps to reproduce
------------------
- Install [PDFtk Server](https://www.pdflabs.com/tools/pdftk-server/)
- Create console app with .NET Core 2.2
```C#
class Program
{
    static void Main(string[] args)
    {
        using (PowerShell ps = PowerShell.Create())
        {
            var results = ps.AddScript("pdftk").Invoke();
            Console.WriteLine(results[0].ToString());
        }
        Console.ReadLine();
    }
}
```

Expected behavior
-----------------

![image](https://user-images.githubusercontent.com/29134373/48307081-d0008800-e545-11e8-92f7-f80fb86afb0c.png)

Actual behavior
---------------
When debugging and inspecting
> ps > Streams > Error > Results View > [0]
```none
{The term 'pdftk' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.}
```

Environment data
----------------

From PowerShell:
```powershell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.228
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.228
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

From Visual Studio:
![image](https://user-images.githubusercontent.com/29134373/48307131-de9b6f00-e546-11e8-94b4-d663728c342f.png)

I have tried `6.2.0-preview.1`, `6.1.0` and `6.0.4` Nuget Packages.

Thanks!

**Comment by SteveL-MSFT** [comment]
@casrou check what `$env:PATH` resolves to within your netcore app.  Make sure the path to PDFtk is within that path.

**Comment by casrou** [comment]
`C:\Program Files (x86)\PDFtk Server\bin\` is indeed there.

**Comment by casrou** [comment]
Alright. I have no idea, what have happened, but I tried `pdftk` from within my netcore app once again - and now.. It worked..
Unfortunately, I do not recall having done anything to fix it (other than maybe restarting my computer), but it seems to be working now. 
I apologize for any incovenience.

**Comment by SteveL-MSFT** [comment]
@casrou if you figure out what happened to make it work, it would be great to have it documented :)

**Comment by sonphnt** [comment]
@casrou Are you using .Net Core Console app and Windows PowerShell 5.1? I am using the same but getting different $env:PSModulePath.

**Comment by casrou** [comment]
I was using .Net Core 2.2 and PowerShell 5.1, yes. I'm not sure, what you are asking. Sorry

**Comment by sonphnt** [comment]
@casrou The thing is when I run $env:PSModulePath in Windows Powershell ISE. I get a Module Path like "C:\Program Files\WindowsPowershell\Modules" but when I run it in C# with powershell.AddScript("$env:PSModulePath"), I get a path "C:\Program Files\Powershell\Modules" (Without prefix windows). So that why the script (import-module, download something bla bla ) is not working in Console app but it works well if I run it in Windows PS ISE. 

Lile Consolse app could not find modules. What is your Powershell directory?
"C:\Program Files\WindowsPowershell\Modules" OR
"C:\Program Files\Powershell\Modules"

Thanks

**Comment by casrou** [comment]
I only have the `C:\Program Files\WindowsPowerShell` of those two directories.
