### ISSUE TITLE
Using '=' operator to assign Environment Variables is fatal

### ISSUE THREAD

**Issue by ajventi** [PowerShell/PowerShell#8228]
Attempting to assign a value to an environment variable using the '=' operator hangs powershell, sometimes giving an error after a few minutes, but often just hanging until terminated.

Using the Set-Item Cmdlet behaves as expected.

Steps to reproduce
------------------
$Env:SHELL = pwsh

Expected behavior
-----------------
Variable is assigned. 

Actual behavior
---------------

..... system hangs indefinitely

Environment data
----------------

> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Darwin 17.7.0 Darwin Kernel Version 17.7.0: Wed Oct 10 23:06:14 PDT 2018; root:xnu-45...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by vexx32** [comment]
Please verify your assignment statement?

It looks like you're doing this:

```
$env:SHELL = pwsh
```

When you need to be doing this:

```
$env:SHELL = 'pwsh'
```

The former will actually start an instance of pwsh and then attempt to store any output to the environment variable.

The latter stores the string 'pwsh' into the var which tells the OS the name or path of the shell to use.

**Comment by ajventi** [comment]
Oh boy, that's a mental lapse, sorry about that. Everything is working as expected.
