### ISSUE TITLE
PSRP WSMan client library to C#

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#8233]
PSCore6 currently depends on OMI native client library for non-Windows to remote PSRP over WSMan.  This library currently has a number of limitations and issues.  To continue to support WSMan based remoting, we should consider writing a new library in managed code.  It also appears that [corefx supports Kerberos/NTLM over HttpClient](https://github.com/dotnet/corefx/issues/30203) so that should solve one of the immediate limitations with the native library.  This library should also be a generally useful public api on nuget for other languages to remote into PowerShell via PSRP.

**Comment by SteveL-MSFT** [comment]
@iSazonov tests is lacking which is why we get reports of issues that should have been caught by tests.  In this case, we would add tests along with this porting work.  We would probably use the same library on downlevel Windows that doesn't have WMF4+, however, this library isn't expected to have full parity with WinRM (at least initially) so relying on WinRM in those cases would make sense.  Long term, it would make sense to have a single library for all platforms.

**Comment by iSazonov** [comment]
In which repository should this be done?
We need at least a test environment.

**Comment by SteveL-MSFT** [comment]
@iSazonov I created https://github.com/PowerShell/WSMan-Client-Library if you want to experiment.  cc @PaulHigin

**Comment by PaulHigin** [comment]
If we want to create a new managed version of WSMan client, then I feel we should start with an RFC.

**Comment by iSazonov** [comment]
... and continue with tests :-) 

Seems it will be large and complex RFC.

**Comment by iSazonov** [comment]
How this correlate with https://www.dmtf.org/standards/ws-man ?

**Comment by SteveL-MSFT** [comment]
@iSazonov PSRP over WSMan relies on the [PowerShell Remoting Protocol](https://msdn.microsoft.com/en-us/library/dd357801.aspx?f=255&MSPPError=-2147217396) which is built on top of WS-Man (or SSH now in PSCore6) which is the same as the one you linked to.  WS-Man is a SOAP based protocol that goes over HTTP(S).

**Comment by iSazonov** [comment]
So we should port [this client](https://github.com/PowerShell/psl-omi-provider/blob/master/src/Client.c) and get direct dependency on native OMI library?

**Comment by SteveL-MSFT** [comment]
@iSazonov the goal here is to remove dependency on OMI library altogether and just have C# code

**Comment by iSazonov** [comment]
I see OMI project is actively updated. Shouldn't this issue be addressed there? I mean OMI client library ported at first in OMI project? What is a reasonable compromise?

**Comment by PaulHigin** [comment]
PowerShell remoting uses OMI only as a bridge for non-Windows platforms.  Its support of WinRM client is incomplete and problematic.  My goal is to completely remove OMI as a dependency.  I agree with @SteveL-MSFT that the best way to do this is to investigate implementing WinRM client in cross-platform managed code, resulting in an RFC that outlines the work required.

**Comment by iSazonov** [comment]
It seems I started to understand :-)

1. We really will not have a conflict with the OMI project?
2. Having two client (Windows (WMF) and the new one on Unix) is seems a problem too. CoreFX reimplemented HttpClient to exclude curl and get the _same behavior_ on all platforms. 
I assume that we are doomed to the same thing - to have single managed WinRM client library for all platforms including Windows 10 (not only Windows 7 without WMF4). In other words, PowerShell Core uses the new managed client, Windows PowerShell uses WMF client.

**Comment by SteveL-MSFT** [comment]
@iSazonov I've had discussions with the OMI team internally and there is no conflict or overlap.  We should use the same client code for both Windows and non-Windows although that would not happen initially as some capabilities we get from WinRM are not a priority for non-Windows.

**Comment by iSazonov** [comment]
@SteveL-MSFT Could you please update the issue description and title that we want to implement WinRM client on managed code?

Is there someones (firms) to whom this may be useful and who could be contribute/test? You could blog post to announce the new project.

Also I hope your team prepares the RFC (I have no idea who else could do it.) 
Currently, I can only review a code in the repo and maybe reorganize/cleanup it to make it easier to add the new experimental code.

**Comment by SteveL-MSFT** [comment]
@iSazonov I think this specific item is pretty specialized and complicated so unlikely for someone in the community to be able to contribute.  Since we have the new repo for this work, I'm going to close this item.  It's not blocking at this time, but will become blocking in the future if more customers want to use PSRP over WSMan from non-Windows.

**Comment by iSazonov** [comment]
Today I researched this a bit and came to the conclusion that it could be useful for other projects on managed code. There is nothing on GitHub like WSMan on C#. I hope the project will not be frozen for a long time. Ping me when it will start.

**Comment by SteveL-MSFT** [comment]
@iSazonov to set expectation, I don't expect to start on this until at least April 2019

**Comment by iSazonov** [comment]
@SteveL-MSFT @PaulHigin What is a status of "WSMan on C#"? We receive continuous issues for remoting from Unix-s.

**Comment by sakno** [comment]
Guys, any progress on this?
