### ISSUE TITLE
Question : why error when Add-Type System.Drawing.Common

### ISSUE THREAD

**Issue by dotChris90** [PowerShell/PowerShell#8240]
Hello PowerShell Team, 

Sorry very much to disturb you. I am not sure if it is a bug in PowerShell Core or from .NET Core - so please correct me if i am wrong ;) 

Background : 
----------------------
I and some other people try to bring Numpy into .NET world as https://github.com/Oceania2018/NumSharp. 
Since we love .NET in general we started some language specific projects in src folder for Ironpython and PowerShell Core. PowerShell would be an extrem elegant and powerful language in numeric we find. We want to be as close to Numpy as possible. So also want to offer the possibility to transform a bitmap object from System.Drawing namespace into a NumSharp NDArray.  

Problem : 
-----------
Before all worked fine. But when we tried to add the nuget package System.Drawing.Common to our project PowerShell can not construct any object from our Project. 

It was tried : 
- build the C# based PS Module and using Import-Module -Name ./NameOfDll.dll
- using Add-Type -Path ./NameOfDll.dll directly to add the .NET types
- using Add-Type -Path ./System.Drawing.Common directly

There is always the same error and can not figure out what it means. 

**format-default : The following exception occurred while retrieving members : "Could not load file or assembly 'System.Drawing.Common, Version=4.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' The system cannot find the file specific.**

The nuget package is https://www.nuget.org/packages/System.Drawing.Common. 

My PS Version is 
- Version 6.1.0
- PSEdition Core 
- OS Microsoft Windows 10.0.17134

I know it is very unprecise and not 100% PowerShell specific … but I would be already happy if I could get a better clue what could be the error. 

Thanks for your time team. :)

**Comment by iSazonov** [comment]
What do you get in interactive PowerShell Core session with:
```powershell
[System.Drawing.Bitmap]
```

**Comment by dotChris90** [comment]
@iSazonov wow you right. The namespace System.Drawing is already included. And the constructor works like expected. Does PS using the Bitmap from a compatibility package to old PowerShell? I am not absolutly sure why this Assembly seems to be added when start PS and in C# not. ^^'

**Comment by SteveL-MSFT** [comment]
@dotChris90 PSCore6.1 includes [Microsoft.Windows.Compatibility](https://www.nuget.org/packages/Microsoft.Windows.Compatibility/) which brings in `System.Drawing.Common.dll` so it's there by default.

**Comment by iSazonov** [comment]
We have System.Drawing.Common.dll in PowerShell Core publish directory.

**Comment by dotChris90** [comment]
Hey thanks for the hints and explanations. I think this is enough for some more investigation from my side. I will try out more little bit and let you know. Thanks for your help. :)

**Comment by dotChris90** [comment]
Just to inform you - yes all correct. The System.Drawing.Common.dll was exactly in the PowerShell Core folder. Just one question because curious - Is this dll exactly the same like on https://www.nuget.org/packages/System.Drawing.Common/? Just want to check if different versions or sth else is the problem. ;)

**Comment by dotChris90** [comment]
ok - it really was an version problem …. sorry for such a stupid bug -.- 
The PowerShell Core i have using 4.5.0 version but our package using 4.5.1. I close this issue. 
Sorry for disturb. ^^'

**Comment by iSazonov** [comment]
PowerShell Core is self-contained app. So the dll version can be changed in next preview/release.
