### ISSUE TITLE
New-PSDrive fails with a UNC path with a trailing backslash when combined with -Persist

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#8242]
Without the `-Persist` switch, you can optionally specify the root path with a trailing `\` - in other words: whether or not a trailing `\` is present makes no difference.

If you add the `-Persist` switch (Windows-only, only with single-letter drive names), a path with a trailing `\` causes an obscure error:

```none
New-PSDrive : The network resource type is not correct
```

Note that successful creation of the drive (without `-Persist`) actually _retains_ the trailing `\`, as reflected in the `.Root` property of the drive, but it seems to have to no ill effects.

Note: A separate problem is that trying to use `-Persist` on Unix-like platforms, where it is fundamentally unsupported, does not indicate that fact in its error message - see #8250

Steps to reproduce
------------------

On _Windows_:

```powershell
New-PSDrive -root '\\foo\bar\' -name N  -PSProvider filesystem  -Persist
```

Expected behavior
-----------------

Drive creation should succeed.

Actual behavior
---------------

The following error occurs:

```none
New-PSDrive : The network resource type is not correct
```

Simply removing the trailing `\` makes the problem go away.

Environment data
----------------

```powershell
PowerShell Core 6.2.0-preview.1 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.165)
Windows PowerShell v5.1.17134.228 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.345)
```

**Comment by MaximoTrinidad** [comment]
@mklement0 

Interesting!! I got a different error in all of my systems: Linux and Windows, In either PowerShell Core GA 6.1.0 and Preview 6.2.0-Preview.1.

```
... To use the Persist switch parameter, the drive name must be supported by the operating system (for example, drive letters A-Z).
At line:1 char:1
+ new-psdrive -root "\\xxxxx\xxxx" -name Shared1 -PSProvide ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Shared1:PSDriveInfo) [New-PSDrive], InvalidOperationException
+ FullyQualifiedErrorId : DriveNameNotSupportedForPersistence,Microsoft.PowerShell.Commands.NewPSDriveCommand
```
![psdrive_01_2018-11-12_19-17-01](https://user-images.githubusercontent.com/19892435/48382921-8b91fb00-e6b1-11e8-9ab1-09843e4d433a.jpg)
![psdrive_02_2018-11-12_19-17-01](https://user-images.githubusercontent.com/19892435/48382923-9056af00-e6b1-11e8-939b-00e2d9529e05.jpg)
![psdrive_03_2018-11-12_19-17-01](https://user-images.githubusercontent.com/19892435/48382930-951b6300-e6b1-11e8-825a-1a52feee0bd6.jpg)
![psdrive_04_2018-11-12_19-17-01](https://user-images.githubusercontent.com/19892435/48382933-9a78ad80-e6b1-11e8-88b6-9a46a20f1c46.jpg)

Definitely! Something with the "-Persist" parameter.
:)

**Comment by mklement0** [comment]
@MaximoTrinidad: You've hit an unrelated problem, namely that `-Persist` is fundamentally unsupported on Unix-like platforms, which the error message does not indicate - see #8250

I've also updated the initial post to make that clearer.

**Comment by SteveL-MSFT** [comment]
Since `-Persist` as it's designed today is really `net use /persistent:yes` so only works with UNC paths, it seems ok to just trim the trailing slash

**Comment by MaximoTrinidad** [comment]
Thanks @SteveL-MSFT  and @mklement0!
:)

**Comment by gushmazuko** [comment]
I found solution for me:

**Comment by alextovey** [comment]
whats the fix for this im still getting the issue.

**Comment by mklement0** [comment]
@alextovey I see the problem neither in v7.0 nor the current preview (3); note that only critical fixes are back-ported to _Windows PowerShell_.

**Comment by mwellerNVIH** [comment]
Hi fellas,

I still get the error `New-PSDrive: The network name cannot be found.` when attempting to mount a remote share with a trailing backslash (`\`) and no `-Persist` flag. I can confirm leaving the trailing backslash _and also adding `-Persist`_ works.
![2021-12-01 11_06_11](https://user-images.githubusercontent.com/47873136/144297915-d39a9055-2935-4d0e-9b69-0a28227a4877.png)

```
PSVersion                      7.1.3
PSEdition                      Core
```

**Comment by iSazonov** [comment]
@mwellerNVIH Please open new issue with repo steps. Perhaps it is related to `\\wsl\`.

**Comment by hlmtre** [comment]
> @mwellerNVIH Please open new issue with repo steps. Perhaps it is related to `\\wsl\`.

The blanked-out section actually is not on `\\wsl\`, that's just the prefix of the server name. I can open a new issue if needed though.

**Comment by iSazonov** [comment]
@hlmtre Thanks for clarify! It seems you see "revert" issue for that. So please open new issue.
