### ISSUE TITLE
ConvertTo-Json -AsArray does not exist

### ISSUE THREAD

**Issue by ryanfog** [PowerShell/PowerShell#8243]
Steps to reproduce
------------------

```powershell
CovertToJson Ctrl + Space
```

Expected behavior
-----------------

```
I expect to see -AsArray parameter as documented here https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertto-json?view=powershell-6

```

Actual behavior
---------------

```
Parameter is missing and is unavailable.

```

Environment data
----------------

```powershell
> $PSVersionTable
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17763  1
```

**Comment by vexx32** [comment]
This parameter was added in PowerShell Core, so you will not see it in PS 5.1. Note the docs page you're looking at is targeted to show PowerShell 6 information. 

If you install PowerShell Core 6.1 or a more recent preview, you will see the new parameter available. 😄
