### ISSUE TITLE
New-PSDrive -Persist should report a platform-not-supported error (System.PlatformNotSupportedException) on Unix-like platforms

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#8250]
Using `New-PSDrive -Persist`, i.e. creating a persistent drive mapping at the OS level, is only supported on Windows.

While trying to use it on Unix-like platforms does report an error, the error message is confusing (see below).

Steps to reproduce
------------------

```powershell
New-PSDrive -root '\\foo\bar\' -name N  -PSProvider filesystem  -Persist
```

Expected behavior
-----------------

The error message should indicate that the host platform is not supported, along the lines of `System.PlatformNotSupportedException`

Actual behavior
---------------

The following error is reported:

```none
New-PSDrive : When you use the Persist parameter,
              the root must be a file system location on a remote computer.
```

The reason is that the code currently blindly follows a Windows code path until it eventually hits the `PathIsNetworkPath()` method in `FileSystemProvider.cs`, which categorically returns `false` on Unix.

Environment data
----------------

```powershell
PowerShell Core 6.2.0-preview.1 on macOS 10.14
PowerShell Core 6.2.0-preview.1 on Ubuntu 16.04.5 LTS
```

**Comment by lukexjeremy** [comment]
I'd like to do this for a first contribution. 

My initial thought is that I'd expect `-Persist` to work on Nano Server and IoT Core. Therefore, throwing on `Persist && !Platform.IsWindows` would be the right condition. I'll try to verify that, just in case `Platform.IsWindowsDesktop` is actually the better choice. 

`NewPSDriveCommand.ProcessRecord` throws if `Persist` is used with a provider other than `FileSystem`. This seems like the perfect location to also check that `Persist` is not used outside of Windows.
