### ISSUE TITLE
Inheritable ScriptBlock attributes

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/PowerShell#8256]
There are a number of attributes that can be used in ScriptBlocks that I believe should be inherited by any ScriptBlocks whose definitions are nested within the same scope. For example, `DebuggerHidden`, `DebuggerStepThrough`, `DebuggerNonUserCode`, and `Experimental`. Each of these flags currently only applies to the ScriptBlock in which they are defined, which means you must manually apply those same flags to any nested ScriptBlocks. This is inconvenient, and almost always forgotten.

If you have a script or function to which one of these attributes is applied, and within that script or function you do one of the following, currently you must manually add the same attributes to the nested blocks of code:

1. Define and invoke a nested script block, so that you can run some code with a different level of strict mode (as is done in PowerShell error handling code);
1. Define and invoke a nested script block so that you can follow the DRY principle and maximize code reuse;
1. Define and invoke a nested function for the same reason as the previous;

This design does not make sense, and it makes it more difficult to implicitly apply certain attributes under certain conditions.

I would like PowerShell to automatically apply the attributes mentioned (are there others? feedback welcome) to any nested functions or script blocks that are invoked from within a function or script where these attributes are used, so that they only need to be applied once over a block of code in order for that block of code to properly reflect the use of that attribute.

I've already started looking at how to resolve this, but `CompiledScriptBlock` doesn't currently have a property that identifies a parent `CompiledScriptBlock` (if there is one). I think that's the right approach (adding logic to the `InitializeMetadata` method), but I'm a little unsure at this time how to go about adding it. Suggestions on how to go about doing that, as well as thoughts/comments on the ideas presented here, are welcome and appreciated.

**Comment by lzybkr** [comment]
I'm not sure the engine should automatically add attributes, at least not in a way that is visible via `ScriptBlock.Attributes`.

How does C# work, e.g. with local functions?

I realize I've broken this ideal already with format script blocks, but I didn't see a better option. Maybe I should have just marked those script blocks as "format" script blocks and the debugger would also skip those.

For the debugging related attributes, I do think it is reasonable to behave as though the parent attribute was specified, just that it shouldn't be visible via the api.

As for the implementation, you can get the parent from the Ast property.

**Comment by KirkMunro** [comment]
Also, something that needs to be considered here is compiled script blocks. Based on my tests, a script block is compiled when it is defined. That means if you come along later and tweak the `DebuggerHidden` attribute on that script block, it will make that script block hidden or visible to the debugger (depending on how you changed it), _but any script blocks that are defined within that script block will maintain the debugger visibility that they had when the outer script block was defined.

Assuming my understanding of how script block compilation works in PowerShell, that means toggling the debugger visibility attributes should result in a recompilation of the compiled script block that contains those attributes in order to make sure script blocks have the appropriate debugger visibility settings.

**Comment by vexx32** [comment]
Is it worthwhile looking at whether you can simply set a flag when entering a scriptblock with DebuggerHidden set and retain it until you actually exit that scope? I.e., all child scope should inherit it by simple virtue of how PS handles the structure, rather than having to recursively set it implicitly?

**Comment by lzybkr** [comment]
Compilation happens in stages. Each stage happens on demand, e.g. if you access a property that requires that stage.  Attributes happen to be one of the first things that get "compiled" because the `Attributes` property happens to be important in various ways.

There is one design difficulty regarding recompilation - caches. You'd want a design that invalidates caches that might be affected, and also a way to ensure new caches can't be introduced that accidentally miss invalidation upon recompilation.

**Comment by KirkMunro** [comment]
Related: #10530.
