### ISSUE TITLE
COM RCWs are seemingly never garbage-collected, causing COM components to linger

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#8263]
The CLR provides RCWs (runtime-callable wrappers) around instances of COM components to provide managed code a seamless experience of accessing COM objects as if they were managed ones.

When these RCWs get garbage-collected, the underlying COM object is eventually released as well.

This works as expected in C# code, but PowerShell variables seemingly never release these RCWs, as demonstrated below, at least not via variables in child scopes that have gone out of scope.

Steps to reproduce
------------------

On Windows:

```powershell
# Kill any preexisting Excel instances.
if (gps -ea ignore excel) { spps -name excel }

# In a child scope, instantiate and quit Excel.
& {
  $xl = New-Object -ComObject Excel.Application
  $xl.Quit()
  # Without setting $x to $null or running Remove-Variable xl
  # the RCW that $xl points to is never released.
  # $xl = $null  # or: Remove-Variable xl
}

# Wait for the Excel process to disappear.
@'
Waiting for Excel process to disappear, which should only take a few seconds.
If waiting doesn't terminate, Excel is still alive. Press ^C to stop waiting.
'@
while (gps -ea ignore excel) {
  write-host -NoNewline .
  Start-sleep 1
}
write-host "`nExcel process has terminated."
```

Expected behavior
-----------------

The loop should exit after a few seconds, indicating that the Excel process exited.

Actual behavior
---------------

The loop never exits.

The only way to get the COM component to be released is by explicitly setting the `$xl` variable to `$null` or by removing the variable altogether with `Remove-Variable xl`.

This manual process should not be required.

Environment data
----------------

```powershell
PowerShell Core 6.2.0-preview.1 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.345)
Windows PowerShell v5.1.17134.228 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.345)
```

**Comment by george-chakhidze** [comment]
I canʼt reproduce this using Windows PowerShell `5.1.17763.134`  (Windows `10.0.17763.134`).

**Comment by mklement0** [comment]
Thanks, @george-chakhidze - I don't see it anymore either, neither in WinPS nor in PS Core; perhaps I simply didn't wait long enough.
