### ISSUE TITLE
Powershell 6 stops executing when internal normal executable finishes

### ISSUE THREAD

**Issue by erwinwolff** [PowerShell/PowerShell#8264]
Steps to reproduce
------------------

It happens with this C# code using automation.

```
using (PowerShell PowerShellInstance = PowerShell.Create())
{
PowerShellInstance.AddScript(File.ReadAllText(Path.Combine(_configuration[repoPath], "build.ps1")));
var output = PowerShellInstance.Invoke();
}
```

within the build.ps1 script this command is executed:

`nuget update -self`

There are no errors when executed in an actual command console. However, when the C# automation is used the output is limited to:

```
Checking for updates from https://www.nuget.org/api/v2/.
Currently running NuGet.exe 4.7.1.
NuGet.exe is up to date.
```
And then the execution of build.ps1 is over.

Expected behavior
-----------------

The powershell instance loads and executes the build script to its very end. Including the nuget update.

Actual behavior
---------------

At some point, nuget.exe (not a powershell script) executes, quits and also prematurely kills the build.ps1 script.

**Comment by iSazonov** [comment]
Does the script work as expected if you run nuget without parameter "self"?

**Comment by erwinwolff** [comment]
Within the regular command console: yes
Within the Powershell Automation context: no

**Comment by iSazonov** [comment]
Could you share more information (sample script and C# code) in gist?

**Comment by erwinwolff** [comment]
sure

**Comment by erwinwolff** [comment]
After some more researched it turned out NuGet wasn't the cause of the problems. It was a Write-Host debug message that wasn't appended to the PSObject output collection. Strangely, the output of "echo" is, but the output of "Write-Host" isn't.

What brings me to the next point: why is the output of Write-Host not added to the PSObject collection? It would have saved me time debugging.

**Comment by erwinwolff** [comment]
No it doesn't

![2018_11_15_13_38_59_consoleapp3_debugging_microsoft_visual_studio](https://user-images.githubusercontent.com/602021/48553506-0cccd600-e8dc-11e8-9c15-5b0b2d72a2de.png)

**Comment by vexx32** [comment]
Write-Host doesn't write to output

**Comment by erwinwolff** [comment]
Isn't it odd that a function called "Write-Host" doesn't write to the output?

**Comment by iSazonov** [comment]
PowerShell cam works without console. In the case Write-Host output is not silently ignored - it writes to Informational stream.  https://blogs.technet.microsoft.com/heyscriptingguy/2014/03/30/understanding-streams-redirection-and-write-host-in-powershell/

**Comment by vexx32** [comment]
Odd? Not really. If you want to write to output, there's the `Write-Output` function. `Write-Host` is designed to write to the _interactive_ console display without placing objects in the standard output stream, as there are many cases users want informational displays without having to later filter them out of their output collections. 😄
