### ISSUE TITLE
Incorrect help for Get-Content's -Encoding parameter

### ISSUE THREAD

**Issue by slessard** [PowerShell/PowerShell#8268]
Get-Help for the Get-Content commandlet erroneously reports that one of the valid values for the -Encoding parameter is "byte" but if you try to use byte you get an exception stating `Cannot bind parameter 'Encoding'. Cannot convert the "byte" value of type "System.String" to type "System.Text.Encoding".`

Steps to reproduce
------------------

```
Get-Help Get-Content
```
the output includes:

```
SYNTAX
    Get-Content ... [-Encoding {Unknown | String | Unicode | Byte | BigEndianUnicode | UTF8 | UTF7 | UTF32 | Ascii | Default | Oem}] 
```
then execute the commandlet as follows:

```
PS > Get-Content -Encoding byte /etc/var/hosts
Get-Content : Cannot bind parameter 'Encoding'. Cannot convert the "byte" value of type "System.String" to type "System.Text.Encoding".
At line:1 char:23
+ Get-Content -Encoding byte /etc/var/hosts
+                       ~~~~
+ CategoryInfo          : InvalidArgument: (:) [Get-Content], ParameterBindingException
+ FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.GetContentCommand
 

```

Expected behavior
-----------------
Get-Help for Get-Content does NOT report "byte" as a valid value for the -Encoding switch

Actual behavior
---------------
Get-Help for Get-Content incorrectly says "byte" IS a valid value for the -Encoding switch

```
SYNTAX
    Get-Content [-Path] <String[]> [-ReadCount <Int64>] [-TotalCount <Int64>] [-Tail <Int32>] [-Filter <String>] [-Include <String[]>] [-Exclude <String[]>] [-Force] [-Credential <PSCredential>] [-Delimiter <String>] [-Wait] [-Raw] 
    [-Encoding {Unknown | String | Unicode | Byte | BigEndianUnicode | UTF8 | UTF7 | UTF32 | Ascii | Default | Oem}] [-Stream <String>] [-AsByteStream] [<CommonParameters>]

```

Environment data
----------------

```
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Darwin 16.7.0 Darwin Kernel Version 16.7.0: Wed Oct 10 20:06:00 PDT 2018; root:xnu-3789.73.24~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by TheIncorrigible1** [comment]
I think this is a carry-over from Windows PowerShell's documentation where `Byte` is a valid argument, but it looks like in PowerShell Core, it expects an Encoding *object* instead.

**Comment by mklement0** [comment]
@slessard: On a general note, please report problems with the documentation at https://github.com/PowerShell/PowerShell-Docs/issues.

`-Encoding Byte` was replaced with switch `-AsByteStream`, given that raw bytes aren't really an encoding  (see #7986).

The online documentation already reflects this change - https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-content?view=powershell-6#optional-parameters

Be sure to run `Update-Help` to update your local copies of the help topics as well.

After doing that, the `Byte` enumeration value is gone:

```powershell
 [-Encoding {A `System.Text.Encoding` object | ASCII | BigEndianUnicode | OEM |
    String | Unicode | UTF7 | UTF8 | UTF8BOM | UF8NoBOM | UTF32 | Unknown}]
```

The somewhat cryptic representation confirms what  @TheIncorrigible1 stated: in addition to the enumeration values you can now also pass `System.TextEncoding` instances directly to `-Encoding` (but, as stated, for byte streams, use `-AsByteStream`; to get byte array as a _single object_, add `-Raw).

**Comment by slessard** [comment]
I just updated help and still get the incorrect documentation as stated in my bug report

**Comment by mklement0** [comment]
@slessard: Can you try again with `sudo`?

```powershell
sudo pwsh
Update-Help
```

According to the docs, `Update-Help` must be run with admin privileges, which is what I've done to get the updated content.

However, if that was the problem, I would have expected you to see an error.

**Comment by MaximoTrinidad** [comment]
Just an FYI

Try to upgrade to PowerShell Core 6.1.1 and/or 6.2.0-preview.1
This issue no longer exist!

![pscore_encoding_01_2018-11-14_12-36-23](https://user-images.githubusercontent.com/19892435/48501039-34536e00-e80a-11e8-9c9b-821cf5964ab9.jpg)

**Comment by slessard** [comment]
> @slessard: Can you try again with `sudo`?
> 
> ```powershell
> sudo pwsh
> Update-Help
> ```
> 
> According to the docs, `Update-Help` must be run with admin privileges, which is what I've done to get the updated content.
> 
> However, if that was the problem, I would have expected you to see an error.

Nope. Didn't change anything.

**Comment by MaximoTrinidad** [comment]
Just an FYI

Try to upgrade to PowerShell Core 6.1.1 and/or 6.2.0-preview.1

I did a before/after "Update-Help", and the help documentation shows updated on both the latest version and preview.

A heads up... The "Unknown" need to be cleanup!

![pscore_encoding_01_2018-11-14_12-36-23](https://user-images.githubusercontent.com/19892435/48501688-c1e38d80-e80b-11e8-94d0-fecd253ba466.jpg)

**Comment by MaximoTrinidad** [comment]
By the way!!  

No need to do sudo as that was one of the latest improvement on version 6.1.1 and preview.  Maybe include "-force" parameter as I've been doing it as a habit.

Latest GA is 6.1.1.

I just tested in Ubuntu 18.04 doing the Get-Help and it did change the help documentation.

:)

**Comment by slessard** [comment]
HomeBrew says there's nothing newer than what I have installed (but that's a different issue.) I'll believe you that the help content is updated in 6.1.1


![image](https://user-images.githubusercontent.com/580119/48502000-8d240600-e80c-11e8-8c67-08c03837ae80.png)

**Comment by slessard** [comment]
> Maybe include "-force" parameter as I've been doing it as a habit.

`-force` FTW!

Thanks Maximo!

**Comment by MaximoTrinidad** [comment]
Home Brew updates always happens later.  You'll need to upgrade manually to get 6.1.1.
:)

**Comment by MaximoTrinidad** [comment]
Woohoo!!  @slessard you got it!
:)

**Comment by SteveL-MSFT** [comment]
Brew casks updates are handled by the community so there is a small lag.
