### ISSUE TITLE
PowerShell 6.1.1 - Context Menu "Open Here" gives error when path is root of drive

### ISSUE THREAD

**Issue by najeebanwer** [PowerShell/PowerShell#8278]
Steps to reproduce
------------------
Use "Open Here" context menu at root folder of drive, e.g. C:\

Expected behavior
-----------------
No error message.

Actual behavior
---------------
Shows the following error, although the correct folder is open in PowerShell:

> PowerShell 6.1.1
> Copyright (c) Microsoft Corporation. All rights reserved.
> 
> https://aka.ms/pscore6-docs
> Type 'help' to get help.
> 
> Set-Location : Cannot find path 'C:" ' because it does not exist.
> + CategoryInfo          : ObjectNotFound: (C:" :String) [Set-Location], ItemNotFoundException
> + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
> 
> PS C:\>

Environment data
----------------

```powershell
> $PSVersionTable

```
Name                           Value
----                           -----
PSVersion                      6.1.1
PSEdition                      Core
GitCommitId                    6.1.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by MaximoTrinidad** [comment]
Can you please be clearer on the "Steps to reproduce"?  How do you get to the "Open Here"?
I got Windows 10 Insider version 18282 and I don't see a "Open Here.." in File Explorer script property.

But, of course I may be missing an Option to be set, and the information you provide can help understand how to get to the issue.

Greatly Appreciated!

**Comment by najeebanwer** [comment]
@MaximoTrinidad,
The "Open here" context menu is one of the options during PowerShell installation.

![image](https://user-images.githubusercontent.com/34123660/48561088-d92a8580-e8b4-11e8-9ec5-6b1a7c362a09.png)

**Comment by najeebanwer** [comment]
Closed issue by mistake...

**Comment by MaximoTrinidad** [comment]
@najeebanwer 

Yeap! There's an issue when select "Open Here.."  from the c:\ Windows root.  It's happening in both PSCore 6.1.1 and Preview 6.2.0-preview.1.

![pscore_openhere_issues_01_2018-11-15_10-25-07](https://user-images.githubusercontent.com/19892435/48563025-6f64a880-e8c1-11e8-9377-0a530de6e650.jpg)

**Comment by najeebanwer** [comment]
Maybe backslash in a quoted string should be treated as a literal and not an escape character?

**Comment by vexx32** [comment]
This isn't fundamentally something PowerShell has control over, though; it's an issue with the command call itself being parsed in Windows and how it's being handed to PowerShell, it would seem?

**Comment by SteveL-MSFT** [comment]
@vexx32 is correct, by the time .Net gets the arg, it's `c:"`.  We don't get the raw input as it's been unescaped by Win32 apis.  All potential solutions I can think of are hacky, so maybe just special case this where `<driveletter>:"` is received, transform to `<driveletter>:\`

**Comment by SteveL-MSFT** [comment]
Alternative proposal, we add a new parameter that handles this case since `"c:\program files\"` would similarly fail because according to [Microsoft cpp command line parsing](https://docs.microsoft.com/en-us/cpp/cpp/parsing-cpp-command-line-arguments?view=vs-2017) a backslash preceding a double quote is a double quote otherwise it's literal.  So we can have something like: `-TrailingQuoteAsBackSlash` as a hidden switch to `pwsh` that will automatically convert a trailing quote to a single backslash.  The normal path of using `-WorkingDirectory` won't change and normal rules apply where the outer shell must escape correctly before passing to PowerShell.

**Comment by bergmeister** [comment]
Just as a remark, this scenario actually used to work in the original implementation that I did where I was using `pwsh.exe -NoExit -Command Set-Location -LiteralPath '%V'`, I changed this later in PR [6660](https://github.com/PowerShell/PowerShell/pull/6660/files) to use the `-WorkingDirectory` parameter as the initial implementation could not deal with single quotes

**Comment by najeebanwer** [comment]
On PowerShell-6.2.0-preview.3-win-x64, this works partially.
The "Open here as Administrator" context menu item has the "-RemoveWorkingDirectoryTrailingCharacter" argument and that works.
The "Open here" context menu item does not have this argument. Or maybe it was in the duplicate "Open here" item in the Registry that I deleted?

**Comment by SteveL-MSFT** [comment]
@najeebanwer you probably deleted the wrong duplicate.  I would suggest removing the other one and doing a repair with the MSI.

**Comment by bamfbamf** [comment]
I still get this problem on 6.1.2
