### ISSUE TITLE
Hashtable key lookups are unexpectedly culture-sensitive, don't recognize in-session culture changes

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#8280]
<sup>Related: #6989, #8129, #3831</sup>

Note: 
* This issue probably has little real-world impact, and probably comes down to just _documenting_ the current behavior, but before I create a docs issue, I'd like to understand the backstory.

Thanks to sleuthing by @PetSerAl, two aspects of hashtable behavior came to light:

* Key lookups are culture-_sensitive_, i.e., use the _current_ culture, as opposed to the _invariant_ culture that is used in most other contexts.

* The culture used for lookups (as specified during hashtable construction) is _locked in at session startup-time_, because _cached_ culture information is used.

See: https://github.com/PowerShell/PowerShell/blob/877b9a9fbf0bed3876de3c00ff34525aba96c749/src/System.Management.Automation/engine/parser/Compiler.cs#L5694-L5696

Steps to reproduce
------------------

From a session in which culture `tr-TR` (Turkey) was in effect _at session startup time_  - e.g., on Unix, start the session with `bash -c 'LANG=tr-TR pwsh'`, run the following:

```powershell
@{ i = 'yes' }.I; 'i' -eq 'I'
```

Expected behavior
-----------------

```none
yes
True
```

Actual behavior
---------------

```none
True
```

That is, the hashtable lookup didn't succeed, because in the Turkish culture `I` is _not_ the uppercase equivalent of `i`.

By contrast, `-eq`, due to being culture-_invariant_, reported `$True`.

Environment data
----------------

```powershell
PowerShell Core 6.2.0-preview.1
```

**Comment by rjmholt** [comment]
This is related to https://github.com/PowerShell/PowerShell/issues/7761.

I think there is desire for culture invariant or even just ordinal case-insensitive comparison, but it needs to not break cultures like tr-TR.

Another discussion thread: https://github.com/dotnet/roslyn/issues/29938.

**Comment by mklement0** [comment]
Thanks, @rjmholt - interesting stuff. 

The larger question here is why hashtables were chosen to exhibit _any_ culture-sensitivity, given that in many contexts it is the invariant culture that is applied (I've tried to provide an overview in [this SO answer](https://stackoverflow.com/a/37603732/45375)).

>  it needs to not break cultures like tr-TR.

Note that `-eq` already "breaks" tr-TR (as shown above), and always has, due to its culture-invariant behavior.
Given that `-eq` is conceptually closely related to determining key equality in hashtable lookups, you'd expect the latter to work the same.

**Comment by iSazonov** [comment]
@mklement0 It seems the issue was fixed.

**Comment by mklement0** [comment]
Thanks, @iSazonov; it was fixed by switching to _ordinal_  string comparisons for lookup:

https://github.com/PowerShell/PowerShell/blob/1e5655b48cdad707ee3678435c4b587c0856a35c/src/System.Management.Automation/engine/parser/Compiler.cs#L6442-L6444
