### ISSUE TITLE
Missing changelog for version 6.1.1

### ISSUE THREAD

**Issue by beruic** [PowerShell/PowerShell#8282]
I got an update yesterday, updating Powershell to version 6.1.1, but cannot findthe changes in the changelog.

I am on Ubuntu 18.04, and I have installed/get updates from the repository at https://packages.microsoft.com/ubuntu/18.04/prod.

**Comment by SteveL-MSFT** [comment]
The change is here: https://github.com/PowerShell/PowerShell/releases/tag/v6.1.1

**Comment by TravisEz13** [comment]
I created a PR to merge the changelogs into master to make them easier to find:
https://github.com/PowerShell/PowerShell/pull/8283
