### ISSUE TITLE
aka.ms link to MSI download links

### ISSUE THREAD

**Issue by zebulonsmith** [PowerShell/PowerShell#8296]
It would be great if there was an aka.ms shortcut for the current version of each of the MSI installers published. 

That would make it much easier to deploy PS Core with tools like SCCM. A simple install script could be used to download the MSI and then run the installation with the advantage that you'd always be installing the current version.

**Comment by SteveL-MSFT** [comment]
@zebulonsmith I created https://aka.ms/installpowershell.ps1 which points to the install script on this repo.  You can use it as:

```powershell
iex "& { $(irm https://aka.ms/install-powershell.ps1) } -UseMSI -Preview"
```

However, there's currently a known issue with the Preview MSI where it doesn't work after install and you need to try re-installing and running repair.  We should have that fixed for next Preview though.

**Comment by SteveL-MSFT** [comment]
The Preview.4 MSI is fixed, so this should just work.

**Comment by zebulonsmith** [comment]
Steve, this somehow fell into my spam folder and I just found it today.
Thanks a ton for adding that!

**Comment by sime3000** [comment]
> @zebulonsmith I created https://aka.ms/installpowershell.ps1 which points to the install script on this repo. You can use it as:
> 
> ```powershell
> iex "& { $(irm https://aka.ms/install-powershell.ps1) } -UseMSI -Preview"
> ```
> 
> However, there's currently a known issue with the Preview MSI where it doesn't work after install and you need to try re-installing and running repair. We should have that fixed for next Preview though.

So if I run this command today on an existing PowerShell 7 installation what will it install ?  i.e. reinstall the PowerShell 7.0.0 base release or update to the 7.0.1 stable release or update to the current preview release which is 7.1 preview 3 ?
