### ISSUE TITLE
executing CMD with carrots (^) in argument 

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PowerShell#8299]
# Steps to reproduce

```powershell
cmd /d /s /c """.\appdata\local\programs\Microsoft VS Code\bin\code.cmd"" ""%%testing^carrots.txt"""
```

# Expected behavior

VS Code opens with file `%testing^carrots.txt`

# Actual behavior

VS Code opens with `%testing^^carrots.txt`

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
I thought maybe this was just a 'core' thing but it happens on Windows PowerShell 5.1 too.

Why is there some form of an escaping operation occurring that is causing the `^` to be doubled?  If I don't double the quotes around the file argument, then I have to quadruple the carrots in order to get a single one to VS Code and that's understood and expected, but the double carrot when I only typed a single one is not expected.

For instance, this works:
```Powershell
cmd /d /s /c """.\appdata\local\programs\Microsoft VS Code\bin\code.cmd"" %%testing^^^^carrots.txt"
```

However, you must have doublequote characters around the file path argument if it contains spaces, as carrots cannot escape a space.  But inside a doublequote, carrots don't need escaped.

**Comment by SteveL-MSFT** [comment]
This appears to be a cmd.exe thing and not related to PowerShell.  The equivalent in cmd.exe without additional quote escaping (not under `pwsh`):

```
cmd /d /s /c "".\appdata\local\programs\Microsoft VS Code\bin\code.cmd" "%%testing^^carrots.txt""
cmd /d /s /c "".\appdata\local\programs\Microsoft VS Code\bin\code.cmd" "%%testing^carrots.txt""
```

Both produce the same results you see.  Interestingly, `^^^` and `^^^^` also don't work.  Couldn't find a combination that actually produced a resulting single carat with cmd.exe.

**Comment by vexx32** [comment]
Does `\^` work to produce a single caret?

**Comment by SteveL-MSFT** [comment]
@vexx32 nope, that produces a folder called "%%testing" and a file in that folder "carrots.txt" since it's treated as a directory separator.

**Comment by msftrncs** [comment]
Okay, lots of trying things, and I finally found that CALL in the CMD script is what causes the `^` to be doubled, but its something in VS Code or Node that strips one of the `%` off, because CALL doesn't do that.  I determined this by switching out the CMD file for a simple ECHO script to echo the results, and then I changed the command I was using in PowerShell to CALL:

``` PowerShell
cmd /d /s /c 'call "code.bat" "%testing^carrots.txt"'
```
So not a PowerShell problem.

**Comment by msftrncs** [comment]
@SteveL-MSFT, one thing I have noticed, is that PowerShell will wrap the argument to CMD.EXE (I suppose to all executables) with additional quotes if there are any spaces in the argument, even if that argument is already fully quoted.  As long as one knows this is happening, it simply means the arguments to CMD.EXE never need to be separately quoted (though obviously the compound arguments still need to be separately quoted, but anyone coming from CMD.EXE background is going to be surprised. This is also different than when calling `spawn` in Node JS to spawn CMD.EXE, where I have to intentionally wrap the argument in quotes.

**Comment by SteveL-MSFT** [comment]
@msftrncs you can always use `--%` to pass the rest of the cmdline as-is to the native command:

```powershell
cmd --% ...your args as they would appear outside of powershell...
```
