### ISSUE TITLE
Exception when tab completion overruns buffer

### ISSUE THREAD

**Issue by yevster** [PowerShell/PowerShell#8304]
# Steps to reproduce
1. On Windows, create a new ShortCut to PowerShell Core. Set the buffer height to 15:
![image](https://user-images.githubusercontent.com/7320197/48663152-d1581600-ea59-11e8-824b-87e7e5b55971.png)

2. Open the shortcut and paste the following:
```powershell
Set-PSReadlineOption -EditMode Emacs
function Get-GitHubRepository{
    Param(
        # The username whose repositories are to be retrieved
        [Parameter(Mandatory=$true, Position=0)]
        [string]
        $Username
    )

    Write-Host 'This part does not matter'
}

```

3. Type in: `Get-GitHubRepository -` and after the dash, press TAB. If nothing happens, press it again.

# Expected behavior
The list of possible parameters appears. cropped by the limits of the buffer.

# Actual behavior
An exception occurs, which I cannot fully copy because small buffer.

# Environment data

```none
PSVersion                      6.1.1
PSEdition                      Core
GitCommitId                    6.1.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by SteveL-MSFT** [comment]
@yevster not able to repro this.  First, can you try with 6.2-preview.2 to see if it repros?  Second, how long is your prompt as that may be a factor.  Finally, does it repro if you remove PSReadLine (remove-module psreadline)?

**Comment by yevster** [comment]
Hi, @SteveL-MSFT,

Yes, it's reproducible with 6.2-preview.2. The prompt is long, e.g. `PS C:\Users\yebronsh\Desktop\PowerShell-6.2.0-preview.2-win-x64>`. Expanding the window horizontally or vertically increases the buffer and eliminates the exception. If you can't reproduce it, try shrinking the buffer even further in shortcut settings.

`Remove-Module` does eliminate the exception, but it also eliminates the Emacs-style tab completion.

With a larger buffer, you may still be able to reproduce the issue by pressing TAB repeatedly after the hyphen.

**Comment by yevster** [comment]
Incidentally, is PSReadLine source on GitHub? I couldn't find it here.

**Comment by SteveL-MSFT** [comment]
@yevster since it appears to be due to PSReadLine, can you see if there is an existing issue here https://github.com/lzybkr/PSReadLine/issues otherwise open a new issue?  Thanks!

**Comment by yevster** [comment]
Covered by lzybkr/PSReadLine#663
