### ISSUE TITLE
Allow ConvertTo-Xml to emit CLIXML (the same XML format as Export-Clixml)

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#8311]
# Summary of the new feature/enhancement

Follow-up from https://github.com/PowerShell/PowerShell/issues/8308#issuecomment-439737699, quoting @SteveL-MSFT:

> Ideally, it seems like we should have had `ConvertTo-Xml` take a `-Format` parameter that supported CliXml and other xml formats rather than having this confusion between `ExportTo-CliXml` and `ConvertTo-Xml` having incompatible xml formats.

Note that the documentation is lacking, as of this writing, as it mistakenly suggests that `ConvertTo-Xml` is the in-memory equivalent of `Export-CliXml` - see https://github.com/PowerShell/PowerShell-Docs/issues/3310

_Update_: Adding dedicated `ConvertTo-CliXml` and `ConvertFrom-CliXml` cmdlets has been requested and green-lit (#3898), though the associated PR has gone stale: https://github.com/PowerShell/PowerShell/pull/5815

In light of that, it may be better to leave `ConvertTo-Xml` alone and simply fix / amend its documentation.

**Comment by SteveL-MSFT** [comment]
Marking as `First-Time-Issue` as I think this should be relatively straight forward to add a parameter and have it use some of the internal APIs used by `Export-CliXml` to do the conversion.

**Comment by ece-jacob-scott** [comment]
Hack Illinois participant
Working with Dan and Tyler

I will take this one on.

**Comment by mklement0** [comment]
See #3898 and the discussion in https://github.com/MicrosoftDocs/PowerShell-Docs/issues/6612#issuecomment-690763976

**Comment by mklement0** [comment]
_Update_: `ConvertTo-CliXml` and `ConvertFrom-CliXml` will finally be available, in **v7.5+** (starting in PowerShell 7.5.0-preview.4) - see https://github.com/PowerShell/PowerShell/pull/21063
