### ISSUE TITLE
Support using sockaddr_un scheme with Invoke-RestMethod.

### ISSUE THREAD

**Issue by tdaniely** [PowerShell/PowerShell#8314]
# Summary of the new feature/enhancement

Support using "sockaddr_un" (AF_UNIX sockets) with Invoke-RestMethod.

# Proposed technical implementation details

Example usage:
`Invoke-RestMethod sockaddr_un://var/run/docker.sock/containers/json

As far as I understand the socket layer should behave the same so no big changes in the code, except adding the scheme and address family option. I don't think this should affect Powershell code.
System.Uri will need to support new scheme, which obviously means changes in framework & core.

**Comment by SteveL-MSFT** [comment]
If CoreFx supports this, we can support it.  Until then, I don't think it makes sense to specialize it into the cmdlet.

**Comment by tdaniely** [comment]
Actually I'm not sure if the dotnet people will go for this. The protocol is still HTTP. That the transport is different doesn't really matter.

With curl you do it like this:
`curl -XGET --unix-socket /var/run/docker.sock http://localhost/containers/json`

So maybe the answer isn't core support. Probably warrants some design discussion.
