### ISSUE TITLE
Make PowerShell SDK NuGet packages ship IL assemblies

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#8322]
### Problem

The current PowerShell SDK NuGet packages have crossgen'ed assemblies in them, which are huge in size compared to the IL version of those assemblies, e.g. `System.Management.Automation.dll` from the NuGet package is 19.4mb while the IL version of it is 6.6mb. This causes a size bloat to applications that host PowerShell runtime.

### Suggestion

Instead of ship with crossgen'ed assemblies, make the PowerShell SDK NuGet packages bundle with IL assemblies.

The pros of this:
- Much smaller size
- Much simpler folder structures of the NuGet packages

The cons of this:
- Slower startup time

I totally see the perf benefit of having crossgen'ed assemblies in the SDK NuGet packages, so I'm not suggesting completely rule it out. We need to think about whether it's possible to keep the benefits from both approach.

/cc @adityapatwardhan @TylerLeonhardt @SteveL-MSFT

**Comment by SteveL-MSFT** [comment]
Can't we just ship the IL assemblies under the `any` runtime id?

**Comment by iSazonov** [comment]
It would be separate nuget package.

**Comment by adityapatwardhan** [comment]
Verified that the assemblies in `Microsoft.PowerShell.SDK` are MSIL.

Example:

```
[System.Reflection.AssemblyName]::GetAssemblyName("C:\Users\aditya\.nuget\packages\system.management.automation\7.1.0\runtimes\win\lib\net5.0\System.Management.Automation.dll") | fl

Name                  : System.Management.Automation
Version               : 7.1.0.0
CultureInfo           : 
CultureName           :
CodeBase              :
EscapedCodeBase       :
ProcessorArchitecture : MSIL
ContentType           : Default
Flags                 : PublicKey
HashAlgorithm         : SHA1
VersionCompatibility  : SameMachine
KeyPair               :
FullName              : System.Management.Automation, Version=7.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
```

**Comment by iSazonov** [comment]
I don't see any conclusion about performance concerns. How should users do if they want crossgened SDK dll-s?
