### ISSUE TITLE
[ISE] booth PHP and Node.js's interactive shells dont work

### ISSUE THREAD

**Issue by AylanBoscarino** [PowerShell/PowerShell#8336]
# Steps to reproduce

```powershell
php -a
```

```powershell
node
```

# Expected behavior

The interactive shell to be available to insert commands of the respective language.

# Actual behavior

when executing node's it stops right there and you need to stop the operation, on  php -a it just shows the message "Interactive shell" and nothing happens

# Environment data

Using Windows 10 x64, tried booth running as administrator and the x86 version of ISE.

**Comment by DHowett-MSFT** [comment]
The ISE cannot host console applications, as it is not a Console. I believe it is also deprecated and will not be part of PowerShell Core.

**Comment by rkeithhill** [comment]
PowerShelll ISE is not part of PowerShell Core as ISE relies upon WPF that is not cross-platform.  Issues for ISE should be filed on UserVoice - https://windowsserver.uservoice.com/forums/301869-powershell?category_id=148050

**Comment by iSazonov** [comment]
@AylanBoscarino Please move the issue to UserVoice.
