### ISSUE TITLE
Problems with uppercase cyrillic letters.

### ISSUE THREAD

**Issue by StefanTitze** [PowerShell/PowerShell#8338]
I am not able to enter most of the cyrillic letters in uppercase into the console window. All Lowercase letters are working:

Serbian:

ЉЊЕРЗУИОППЂ
AДГЈКЛЋЖ
ЅЏБНМ

Russian:

ЙУКЕНГЗ
ЫВАПРОЛДЖЭ
МИЬБЮ

This problem does not occur with the PowerShell 5.1 console window.

Regards

Stefan Titze

-----
Windows 10 x64 1803 17134.407
PowerShell 6.1.1

**Comment by iSazonov** [comment]
Can you check after unload PSReadline?

**Comment by StefanTitze** [comment]
The problem is solved when I’m unloading PSReadline.


[cid:baramundi_logo_7d238272-c360-403f-a4b5-16fee20dd77a.png]<http://www.baramundi.de/>

Stefan Titze
Scrum Master

Fon: +49 821 5 67 08 - 575
Fax: +49 821 5 67 08 - 19
E-Mail: stefan.titze@baramundi.de<mailto:stefan.titze@baramundi.de>

baramundi software AG
Beim Glaspalast 1
86153 Augsburg
www.baramundi.de<http://www.baramundi.de>

Besuchen Sie uns:
LinkedIn<https://www.linkedin.com/company/2797106> | Xing<https://www.xing.com/companies/baramundisoftwareag> | Twitter<https://twitter.com/baramundiWORLD> | YouTube<https://www.youtube.com/user/baramundisoftware/>

Vorstand: Dipl.-Ing. (FH) Uwe Beikirch | Dr. Lars Lippert
Aufsichtsratsvorsitzender: Dr. Dirk Haft
Sitz und Registergericht: Augsburg, HRB-Nr. 2064 | USt-IdNr. DE 210294111

[cid:License_Management_Signatur_DE_7e5097fa-4e23-4726-b13e-4817aa09b6f0.jpg]<https://www.baramundi.de/kampagnen/baramundi-license-management/?utm_source=E-Signatur&utm_medium=Gruppe_Dev&utm_campaign=bLicense_de_DE>
Von: Ilya <notifications@github.com>
Gesendet: Montag, 26. November 2018 13:56
An: PowerShell/PowerShell <PowerShell@noreply.github.com>
Cc: Stefan Titze <stefan.titze@baramundi.de>; Author <author@noreply.github.com>
Betreff: Re: [PowerShell/PowerShell] Problems with uppercase cyrillic letters. (#8338)


Can you check after unload PSReadline?

**Comment by anmenaga** [comment]
I can repro on `PSVersion = 6.1.1`.
Some uppercase letters not working when entered using `Shift` key;
Everything seems to work with `Caps Lock` turned on.

**Comment by lzybkr** [comment]
Closing as this was reported [here](https://github.com/lzybkr/PSReadLine/issues/798).
