### ISSUE TITLE
DSC - Automatic conflict remediation for partial configurations

### ISSUE THREAD

**Issue by f0nt4** [PowerShell/PowerShell#8351]
The LCM is already able to detect conflicts, with a fairly small change you could make it automatically resolve it.  In my opinion we should be able to set a priority of each partial configuration in the meta config of the LCM. 
With a priority set and when a conflict is detected, the LCM could look at the priority and choose a winner and therefor automatically solve the conflict.

You could than create a layered approach of partial configs (by different teams) without having to be afraid of running into conflicts.

For more control we could introduce a LCM setting to turn auto remediation on or off.
Nice to haves would be options to report remediated conflicts and to change the behaviour of the priority (when 1 would be highest, you could set the priority be applied descending making 1 the lowest).

This is something I see more people struggling with, which results in solutions like datum (https://github.com/gaelcolas/Datum) which makes it unnecessary complicated to create a hierarchical structure in the partial configs. 
At our company with somewhere around 9000 servers which are spread around the globe, we want to introduce a global config, which then can be overwritten with regional settings and on top of that server role and server specific settings.

**Comment by iSazonov** [comment]
@TravisEz13 Should the Issue be moved to DSC repo?

**Comment by TravisEz13** [comment]
LCM is Windows PowerShell and should be filed per the issue template guidelines for Windows PowerShell.

**Comment by iSazonov** [comment]
@f0nt4 Please move the issue to UserVoice.
