### ISSUE TITLE
slimmer output for start-transcript

### ISSUE THREAD

**Issue by qt3m45su0najc7** [PowerShell/PowerShell#8359]
I'd like to see two options for start-transcript to reduce clutter and improve readability  

-noheadermast (reduces or eliminates the first 15 or so lines that always appear)
-setprompt (to replace the default prompt that is captured) because you may not want to see 
\\server\directory\directory\directory\datetime long format here >

**Comment by lukexjeremy** [comment]
So I notice PowerShell transcripts also include a footer, e.g. 

```
**********************
PowerShell transcript end
End time: 20181201203353
**********************
```

It would be odd to completely exclude the header and leave the footer in.

Headers and footers are useful to delimit multiple sessions in a single transcript. 

Perhaps a `-MinimalTranscriptHeader` option, producing the following would be suitable. 

```
**********************
PowerShell transcript start
Start time: 20181201203347
**********************
```

**Comment by lukexjeremy** [comment]
`-UseMinimalHeader` is merged 🎉 I'll have a look at `-SetPrompt` soon.

**Comment by lukexjeremy** [comment]
After some research, I'm not sure a `-SetPrompt ...` parameter is the right approach. 

The prompt is the return value of the [`prompt` function](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_prompts?view=powershell-6#built-in-prompt). Override that function to change the prompt, e.g. in your PS profile. You could handle all manner of scenarios by basing `prompt`'s logic on environment variables.

Given that, I think `Start-Transcript` would be overstepping its boundaries by changing the prompt.

**Comment by lukexjeremy** [comment]
Can we call this issue closed?

**Comment by qt3m45su0najc7** [comment]
I don't know whether the 'minimaltranscriptheader' you proposed was implemented.  I didn't see any doc changes.  
If you are asking me personally, please feel free to act as you see best.  I'll submit as close and comment.

**Comment by lukexjeremy** [comment]
I'm sorry that wasn't clear!

The doc change references the PR, not this issue. So it didn't appear in the timeline here. 

In summary, the optional parameter `-UserMinimalHeader` and associated doc changes were added to Powershell 6.2.
