### ISSUE TITLE
Can't access elements of hash table created by ConvertFrom-Json -AsHashtable by key

### ISSUE THREAD

**Issue by artem-nefedov** [PowerShell/PowerShell#8360]
# Steps to reproduce

```
# create hash table with ConvertFrom-Json -AsHashtable
PS /home/user> $x = '[{"name1":"val1"},{"name2":"val2"}]' | ConvertFrom-Json -AsHashtable
# validate that it is created correctly
PS /home/user> $x

Name                           Value
----                           -----
name1                          val1
name2                          val2

# try accessing an element by key
PS /home/user> $x['name1']
PS /home/user>
```

# Expected behavior

```
Value of the element is returned correctly
```

# Actual behavior

```
Nothing is returned
```

# Environment data

```
Name                           Value
----                           -----
PSVersion                      6.1.1
PSEdition                      Core
GitCommitId                    6.1.1
OS                             Linux 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
# Additional info
Same actions work if hash table is created via `$var = @{ 'name1' = 'val1'; 'name2' = 'val2' }` syntax. Both are `System.Collections.Hashtable`, which is why I don't understand the difference in behavior.

**Comment by BrucePay** [comment]
@artem-nefedov I suspect that this is another case where the object is actually wrapped in a `PSObject` . `PSObject` is transparent at the PowerShell layer but the C# layer needs to check to see if the object is a `PSObject` and if so, get the base object before proceeding. I fixed a similar bug in `Group-Object` a while back

**Comment by artem-nefedov** [comment]
@SteveL-MSFT I completely missed that point. You are right.
I'm closing this.
