### ISSUE TITLE
Installation fails on Ubuntu 16.04 and Ubuntu 18.04

### ISSUE THREAD

**Issue by Indhukrishna** [PowerShell/PowerShell#8379]
Followed the installation instructions for manual installation from here - https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-powershell-core-on-linux?view=powershell-6#ubuntu-1804

```powershell
Installation fails with the following error
install errors: dpkg: dependency problems prevent configuration of powershell:

powershell depends on liblttng-ust0; however:

Package liblttng-ust0 is not installed.

dpkg: error processing package powershell (--install):

dependency problems - leaving unconfigured

Errors were encountered while processing:

powershell

failed to run commands: exit status 1

Failed to install package; install status Failed
```

Even though installation fails, PowerShell Core is installed on the machine. This behavior repros on both Ubuntu 16.04 and ubuntu 18.04

**Comment by Indhukrishna** [comment]
@SteveL-MSFT This was using an Amazon Linux EC2 VM. Please let me know if you need more information,

**Comment by Indhukrishna** [comment]
@datenteiler Running sudo apt -f install doesn't fix it.   It uninstalls the package. 
Output of sudo apt -f install

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages will be REMOVED:
  powershell
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 158 MB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 51834 files and directories currently installed.)
Removing powershell (6.1.1-1.ubuntu.16.04) ...
Processing triggers for man-db (2.7.5-1) ...
```

**Comment by SteveL-MSFT** [comment]
@Indhukrishna best I can find, only Amazon Linux 2 supports .NET Core and PSCore6 (https://aws.amazon.com/about-aws/whats-new/2018/03/announcing--net-core-ami-for-amazon-ec2/).  I don't know the differences between Amazon Linux and Amazon Linux 2.

**Comment by jeroenlandheer** [comment]
**Solution:** `sudo add-apt-repository universe`

**Comment by philipslan** [comment]
I saw this issue recently when trying to download `v7.0.0-rc.2` with Ubuntu 18.04 on WSL. Seem to have fixed the issue after running the following:

```
sudo apt-get update
# install the requirements
sudo apt-get install -y \
        less \
        locales \
        ca-certificates \
        libicu63 \
        libssl1.1 \
        libc6 \
        libgcc1 \
        libgssapi-krb5-2 \
        liblttng-ust0 \
        libstdc++6 \
        zlib1g \
        curl
```
