### ISSUE TITLE
Add CI for validating links in Markdown files

### ISSUE THREAD

**Issue by andschwa** [PowerShell/PowerShell#838]
With, say, [awesome_bot](https://github.com/dkhamsing/awesome_bot).

**Comment by andschwa** [comment]
I think what we're looking for here is:

- [ ] ensuring links are correct (not broken)
- [ ] spell checking of markdown files
- [ ] maybe style checking

Since AppVeyor is consistently faster than Travis CI, and this probably only needs to be in one place, an extra step only on AppVeyor I think would be sufficient.

@vors started creating a PowerShell-based [MarkdownLinkChecker](https://github.com/vors/MarkdownLinkCheck) that could be used, but IIRC it couldn't handle checking relative links `[example](../docs/example)`, which is actually our primary link use case.

I think this issue would be a good Hacktoberfest submission.

**Comment by vors** [comment]
Actually it's the exact oposite: MarkdownLinkCheck checks relative links fine and doesn't check absolute links

**Comment by iSazonov** [comment]
> spell checking of markdown files

Solved.

**Comment by joeyaiello** [comment]
Two out of three of the above are fixed, the only part that we still need is link validation. 

@TravisEz13 could you please unassign if you're not actively working on the hyperlink aspect (which is not a 6.0.0 priority)?

**Comment by RDIL** [comment]
Completed by me.  Please close @TravisEz13 or @SteveL-MSFT

**Comment by TravisEz13** [comment]
@RDIL 	thanks again.  Did you review my work to change yours into a test?

**Comment by RDIL** [comment]
Um if it was already merged then yes I believe so.
