### ISSUE TITLE
Simple keyboard editing commands don't work in in PowerShell Integrated Console

### ISSUE THREAD

**Issue by jagdishrajan** [PowerShell/PowerShell#8380]
# Steps to reproduce & Expected behavior

In the command line Ctrl+Left Arrow should jump a word to the left.  Ctrl+Shift+Left Arrow should select the word to the left.  None of this seems to work.

```

# Actual behavior

The terminal command line just moves the cursor left or right by one character, no matter what command is used.

```

# Environment data

PSVersion                      5.1.17134.407
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.407
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by iSazonov** [comment]
@jagdishrajan Thanks for your report! 

The repo is for PowerShell Core version. For Windows PowerShell please report to UserVoice site.

I can not reproduce the issue PowerShell Core and Windows PowerShell so please share more information about your environment.

**Comment by vexx32** [comment]
By `Ingegrated Console` do you mean the VS Code integrated console? That is an entirely separate project, maintained in the **vscode-powershell** repo. The limitations of the integrated console there are well-known, and are well on the way to being rectified. I believe prototype versions of the extension are available from the repo and/or their AppVeyor build artifacts which _do_ include PSReadLine support and thus have these issues largely resolved.

**Comment by jagdishrajan** [comment]
Sorry, I should have created this in vscode-powershell repo.  Closing this issue as it does not pertain to PowerShell console v6.
