### ISSUE TITLE
"about_Logical_Operators" page on docs.Microsoft.com looks broken

### ISSUE THREAD

**Issue by Shekan** [PowerShell/PowerShell#8392]
When visiting [https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_logical_operators?view=powershell-6](url),  the "Long Description" section looks as though something went wrong in the formatting of the text, specifically the text immediately following:
> PowerShell supports the following logical operators.

I'm currently using Google Chrome Version 70.0.3538.110 on Windows 10.

**Comment by vexx32** [comment]
Oof, yeah, that doesn't look pretty! You might want to put this into the [PowerShell-Docs](https://github.com/PowerShell/PowerShell-Docs) repository, though, as the documentation is maintained separately to the primary PowerShell project here! 😄
