### ISSUE TITLE
Fix Clear-Host on Nano

### ISSUE THREAD

**Issue by andschwa** [PowerShell/PowerShell#841]
When running PowerShell Core on Nano, the `Clear-Host` command fails due to an unsupported `System.Console.SetBufferContents` call.

I think the fix would be to modify the function to just call `cls.exe` directly, and catch any errors around `System.Console`.

The [current implementation](https://github.com/PowerShell/PowerShell/blob/76ad94d8a760cd3f865e2dcb151287ce33e0cd5d/src/System.Management.Automation/engine/InitialSessionState.cs#L4725) clears the host manually with calls to `$RawUI.SetBufferContents`.

**Comment by joeyaiello** [comment]
This works right now via a Nano Docker container in a "real" console host, and that *might* be good enough. I need to validate with @xumins.

**Comment by SteveL-MSFT** [comment]
We can reopen this if there is customer feedback
