### ISSUE TITLE
New console fonts not showing up after registry addition

### ISSUE THREAD

**Issue by E3V3A** [PowerShell/PowerShell#8413]
I've just added the following fonts according to (parhaps outdated) instruction, using the registry like this: 

```powershell
$key = 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Console\TrueTypeFont'
Get-ItemProperty -Path $key

# There is already an item with two zeros, so we need 3 and 4...
Set-ItemProperty -Path $key -Name '000' -Value 'Arial'
Set-ItemProperty -Path $key -Name '0000' -Value 'Calibri'
```
I then:
1.Restarted Windows Explorer. 
2. Restarted Powershell Console

However, they don't show up in the console options.  
Has this been disabled? 

Using: 
```
Name                           Value
----                           -----
PSVersion                      6.1.1
PSEdition                      Core
GitCommitId                    6.1.1
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by mklement0** [comment]
I don't think what fonts show up in the properties dialog of console windows is under PowerShell's control.

https://www.mydigitallife.net/how-to-enable-more-fonts-for-windows-command-prompt/ mentions that a _reboot_ is required, but I don't know if that alone will solve the problem.

You can ask the [Windows Console team](https://github.com/Microsoft/console) or perhaps on http://superuser.com

**Comment by E3V3A** [comment]
Yep, seem that none of those fonts conform to those (old) rules. 

The only one I could get to install was `DejaVu Sans Mono` after having compiled it myself with FontForge.
