### ISSUE TITLE
PowerShell commands run to completion even with a broken pipe to an external (native) program

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#8420]
Note: The issue isn't specific to Unix, as originally stated - see #15329

`... | Select-Object -First 1` stops the upstream command after receiving the 1st input object, but the same is not true when the sink is an _external program_:

# Steps to reproduce

```powershell
1..10 | Write-Output -ov result | head -n 1; $result.Count
```

# Expected behavior

```none
1
1
```

# Actual behavior

```none
1
10
```

That is, `Write-Output` unexpectedly ran to completion, even though `head` exited after receiving the first input line, making it pointless to send additional objects to the pipeline.

# Environment data

```none
PowerShell Core v6.2.0-preview.2 on macOS 10.14.1
PowerShell Core v6.2.0-preview.2 on Ubuntu 18.04.1 LTS
```

**Comment by KevinMarquette** [comment]
In this case, `Select-Object` manipulating the pipeline to make this happen. I'm not sure if an external program would be able to do the same. In the current implementation it looks like it would be up to the external program to handle this.

[src/Microsoft.PowerShell.Commands.Utility/commands/utility/select-object.cs#L692](https://github.com/PowerShell/PowerShell/blob/a1299cd6d4e649b5e42edbbdc23a5bb1c74d82a0/src/Microsoft.PowerShell.Commands.Utility/commands/utility/select-object.cs#L692)

**Comment by iSazonov** [comment]
I am not sure that the external command terminates after reading first item. I guess it collects all input. Can we use our TestExe for check?

**Comment by mklement0** [comment]
@iSazonov: `head` is designed to exit once it has received enough input; doing so leaves the pipe broken, and when the process on the writing end tries to write to the pipe the next time, it normally receives a `SIGPIPE` _signal_, or, if `SIGPIPE` is unexpectedly ignored (see #8421 ), the system call returns error _code_ `EPIPE`.

@KevinMarquette: Yes, as you say,`Select-Object` uses internal class `StopUpstreamCommandsException` to stop upstream cmdlets, and, as an aside, it would be nice for user code to have that ability too - see #3821 and #6070.

In the case at hand, however, it would have to be PowerShell that does the `SIGPIPE` / `EPIPE` detection and translates it into PowerShell-appropriate termination of the upstream commands.

I haven't looked into the implementation side of things yet.

**Comment by iSazonov** [comment]
Thanks @mklement0 - I don't read #8421 before commented here.

For reference https://github.com/PowerShell/PowerShell/pull/2450
