### ISSUE TITLE
PSCredential versus UPN

### ISSUE THREAD

**Issue by PascalVerbruggen** [PowerShell/PowerShell#8423]
Why can't you use a UPN for the Credential parameter of Start-Job?

PSVersion                      5.1.17134.407
Windows 10 1803

**Comment by iSazonov** [comment]
@PascalVerbruggen  The repo for PowerShell Core only. Please update your request for PowerShell Core latest version and repo steps.

**Comment by iSazonov** [comment]
Dup #12735
