### ISSUE TITLE
Consider locking in key aliases for calculated properties

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#8429]
# Summary of the new feature/enhancement

PowerShell's elastic syntax (matching by unambiguous name prefix) is great for interactive use, but should be avoided in scripting.

Calculated properties currently employ elastic syntax:
Specifying a calculated property with single-letter key names - e.g., `@{ n='prop'; e = { $_.val + 1 } }` - is convenient, but lacks longterm stability, because `n` and `e` only unambiguously resolve to `name` and `expression` as long as no other keys starting with `n` or `e` are supported.

If `n` and `e` were officially declared _aliases_ of `name` and `expression` an exact match for which would be considered unambiguous, the stability problem would go away.
Similarly, aliases should also be defined for all other currently supported keys: `formatstring` (`f`), `label` (`l`); `width` (`w`); `alignment` (`a`);  `ascending` (`asc`); `descending` (`desc`).

With these aliases locked in, adding keys in the future would not break existing code.

This would be akin to the concept of parameter aliases (e.g., `-ov` for `-OutVariable`, `-lp` for `-LiteralPath`, or `-c` for `-Command` in the CLI).

# Proposed technical implementation details

The internal `HashtableEntryDefinition` used to represent entries in hashtables defining calculated properties already has a `SecondaryNames` property that effectively amounts to aliases (it's already used to make `name` and `label` synonymous).

However, the `IsKeyMatch()` method must be amended to give precedence to (case-insensitive) _full_ key-name matches among `KeyName` and `SecondaryNames`.

**Comment by doctordns** [comment]
I am not sure the phrase 'empty elastic syntax' is helpful. Not sure what elastic syntax means. How about the document gets to the meat: "You can use PowerShell hash tables to create calculated properties for a range of cmdlets (including Select-Object, Format-Table, and Format-LIst).  For calculated properties, the hash table can only have two keys: Name and  Expression. Both key names can be abbreviated to fewer characters (but as least 1 character ) Using other hash table key names results in a DictionaryKeyIllegal exception.

**Comment by mklement0** [comment]
@doctordns: I wasn't suggesting using that term (see info below); if we did, it would need its own conceptual topic too (which is worth considering, separately).

I like what you wrote, but - aside from also needing to describe the key sets for the other cmdlets that support calculated properties - I would add advice to only use the _full_ key names in _scripts_.  

The need for this advice will go away if and when this proposal gets implemented.

---

The phrase is _elastic syntax_ (no _empty_); it is used in @BrucePay's book [_PowerShell in Action_](https://www.manning.com/books/windows-powershell-in-action-third-edition):
> "
PowerShell supports an elastic syntax—concise on the command line and complete in scripts. Aliases are used to facilitate elastic syntax.
[...]
The idea is that PowerShell can be terse when needed and descriptive when appropriate. 
[...]
The syntax is concise for simple cases and can be stretched like an elastic band for larger problems. 
This is important in a language that is both a command-line tool and a scripting language.

**Comment by doctordns** [comment]
O agree with that point! But I'd word it along the lines: Using Full key names in scripts is recommended. Leaving that recommendation unstated for command line purposes. I teach PowerShell and the alias key names, on first sight, is quite confusing.

**Comment by iSazonov** [comment]
@mklement0 Are you ready to push a PR? Then we could ask PowerShell Committee.

**Comment by mklement0** [comment]
@doctordns: Sounds good to me, but why don't you repost your suggested wording over at https://github.com/PowerShell/PowerShell-Docs/issues/3383?

As an aside: Simpler syntax for calculated properties is being proposed -  see #8107

**Comment by mklement0** [comment]
@iSazonov: I'll give it a shot, thanks.

**Comment by mklement0** [comment]
@iSazonov: Please see #8430, and note the open questions there.
