### ISSUE TITLE
Proposal: Resolve-Path with -Relative parameter should allow the use of a reference path

### ISSUE THREAD

**Issue by terrabitz** [PowerShell/PowerShell#8435]
# Summary of the new feature/enhancement

As a PowerShell developer, I want to be able to obtain the path of an item relative to a path that is not my current directory so that I can avoid changing my current location context for a relative directory lookup. 

# Proposed technical implementation details

Assuming I have a directory like this:

```none
/MyProject
    |-/dir
        |-test_1.txt
        |-test_2.txt
        |-/subdir
            |-test_3.txt
```

Currently, if I want to do a resolve a path relative to a *different* directory, I have to use set-location before calling `Resolve-Path`. For example, if I wanted to get all my `.txt` file locations *relative to `dir`*, I would have to do something like this:

```powershell
/MyProject> cd dir
/MyProject/dir> Get-ChildItem -Recurse -Include "*.txt" | Resolve-Path -Relative
./subdir/test_3.txt
./test_1.txt
./test_2.txt
/MyProject/dir> cd ..
```

Ideally, I would like to do something like this:

```powershell
/MyProject> Get-ChildItem .\dir -Recurse -Include "*.txt" | Resolve-Path -Relative -ReferencePath .\dir
./subdir/test_3.txt
./test_1.txt
./test_2.txt
```

**Comment by Jaykul** [comment]
Totally agree. We shouldn't have to `Push-Location` just to use this feature.

**Comment by rkeithhill** [comment]
You could use `Join-Path -Resolve` for this:
```
PS> Join-Path $home\Downloads ../Documents -Resolve
C:\Users\Keith\Documents
```
This also has the benefit of correcting the directory sep char for the platform.

**Comment by terrabitz** [comment]
@rkeithhill  I don't think that'll work for this particular problem. It appears that the `-Resolve` switch on `Join-Path` is only for checking whether the resulting joined path actually exists. At least on the surface, it doesn't appear to help with relative resolution. From the [docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/join-path?view=powershell-6):

```none
-Resolve
Indicates that this cmdlet should attempt to resolve the joined path from the current provider.

* If wildcards are used, the cmdlet returns all paths that match the joined path.
* If no wildcards are used, the cmdlet will error if the path does not exist.
```

**Comment by an-dr-eas-k** [comment]
This is my workaround: 
```
function Resolve-RelativePath {
	[CmdletBinding()]
	param(
		[parameter(Mandatory, ValueFromPipeline)]$Path,
		$ReferencePath="."
	)
	$Path = (Resolve-Path $Path).Path
	$ReferencePath = (Resolve-Path $ReferencePath).Path

	Write-Verbose "path: $path, reference: $ReferencePath"
	$PSCmdlet.SessionState.Path.NormalizeRelativePath($Path, $ReferencePath)
}
```

**Comment by chriskuech** [comment]
This would help mitigate #10509 .  Would love to see some traction on this, as it seems pretty simple.

**Comment by iSazonov** [comment]
What if we add new parameter for base path `Resolve-Path -BasePath` as optional for `Relative` parameter?
