### ISSUE TITLE
Make PowerShell Core availabe as a .NET global tool

### ISSUE THREAD

**Issue by jcotton42** [PowerShell/PowerShell#8441]
PowerShell Core should be available as a global tool so installing PowerShell for use in a build environment would be as simple as `dotnet tool install pwsh`

The [6.1 release notes](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-core-61?view=powershell-6#net-core-21) say this is "coming soon" but it's been 3 months and as far as I can tell there is still no tool package for PSCore

**Comment by SteveL-MSFT** [comment]
Work has started on this.  However, @adityapatwardhan is currently on vacation.  Perhaps we'll get it early next year.

**Comment by iSazonov** [comment]
In .Net Core 3.0 there is a _Local dotnet tools_.

**Comment by jcotton42** [comment]
Checking in on the status of this issue.

I see it's marked in the Future milestone but it was also marked as "soon" in the 6.1 release notes.

**Comment by SteveL-MSFT** [comment]
Work is on-going on this.  Hopefully next month.

**Comment by jcotton42** [comment]
@SteveL-MSFT excellent

**Comment by jcotton42** [comment]
Is this going to make it into 6.2?

**Comment by adityapatwardhan** [comment]
In all likelihood this will make it in 6.2

**Comment by jcotton42** [comment]
I see 6.2 is out now, did this make it in?

**Comment by SteveL-MSFT** [comment]
@jcotton42 There's some additional work needed before this is available as a dotnet global tool, but it's still happening.  Probably in April.

**Comment by jcotton42** [comment]
@SteveL-MSFT is there any way I could contribute to that work? I'm pretty busy with school but might find time to help.

**Comment by SteveL-MSFT** [comment]
@jcotton42 I appreciate the offer, but it's not engineering work on our side that we're waiting on

**Comment by AceHack** [comment]
Just looking at the latest .NET SDK 3.0 preview Dockerfiles it looks like it's installing PowerShell as a dotnet tool.
https://github.com/dotnet/dotnet-docker/blob/master/3.0/sdk/stretch/arm64v8/Dockerfile

**Comment by SteveL-MSFT** [comment]
@AceHack Nice observation, but not 100% correct.  It is installing that nupkg as a dotnet tool, but "soon", you should just be able to do: dotnet tool install powershell without pre-downloading the nupkg.

**Comment by adityapatwardhan** [comment]
PowerShell v6.2.2 has been released as a global tool. Please give it a try.

https://www.nuget.org/packages/PowerShell/
