### ISSUE TITLE
No built-in editor when remoting

### ISSUE THREAD

**Issue by dilshaat** [PowerShell/PowerShell#8443]
I constantly use `Enter-PSSession` Cmdlet to log into our remote servers and I need to edit many property files. Since this is remote session, `notepad.exe` does not work and this creates difficulties for me now. Having many years of experience with Bash where VIM is always available, this feature is urgently needed, not only for me, also for many sys admins as well. Is there any project on this going on? or any suggestion for me?

**Comment by alexandair** [comment]
You can use Visual Studio Code with PowerShell extension. Open an interactive session with Enter-PSSession and then run `psedit <path_to_a_file_you_want_to_edit>`.

**Comment by thecliguy** [comment]
Possibly relevant: https://github.com/PowerShell/PowerShell/issues/4885

**Comment by dilshaat** [comment]
> You can use Visual Studio Code with PowerShell extension. Open an interactive session with Enter-PSSession and then run `psedit <path_to_a_file_you_want_to_edit>`.

This indeed helped me.
