### ISSUE TITLE
PowerShell Drops Headerless Columns

### ISSUE THREAD

**Issue by bigboy-pdb-spam** [PowerShell/PowerShell#8445]
# Documentation Issue

The [PowerShell documentation for `ConvertFrom-Csv`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertfrom-csv?view=powershell-6) for the optional parameter `-Header` states:

"_If you enter fewer column headers than there are columns, the remaining columns will have no headers_"

Since the `ConvertFrom-Csv` function appears to convert csv rows to `PSCustomObjects`, this implies that the data is available via some function. However, the data appears to have been discarded. In other words, the documentation should state:

"_If you enter fewer column headers than there are columns, the data for the remaining columns is discarded_".

**NOTE**:  This is also true for PowerShell 5 and possibly previous versions

# Steps to reproduce

```powershell
$csv = $(Write-Output "a,b,c`nd,e,f`ng,h,i" | ConvertFrom-Csv -Header 1)

# The additional columns do not appear to be accessible because only the identified columns are displayed
$csv
$csv.''
$csv | Get-Member
$csv | Select-Object '*'
```

If headerless columns can be accessed, then the following code should not produce an error:

```powershell

Write-Output "a,b,c`nd,e,f`ng,h,i" | ConvertFrom-Csv -Header @()
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.1.1
PSEdition                      Core
GitCommitId                    6.1.1
OS                             Linux 4.14.83-1-MANJARO #1 SMP PREEMPT Fri No...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by bigboy-pdb-spam** [comment]
Sorry, I meant to open this as a documentation problem. I don't know what I need to do to convert this to a documentation problem (or if I have permission to do so or if it can be done)

**Comment by vexx32** [comment]
Documentation issues should generally be in the https://github.com/PowerShell/PowerShell-Docs repo. 😄

**Comment by vexx32** [comment]
Yeah, both should be in the other repo; the template you mention is primarily there just to notify folks who come here that docs issues need to be in the other repo (and contains a link to that repo as well, if I remember correctly).

I think you should be able to close the issues yourself if you want to!

**Comment by bigboy-pdb-spam** [comment]
@vexx32 Sorry and thanks. I opened the [an issue within that repo](https://github.com/PowerShell/PowerShell-Docs/issues/3401).
