### ISSUE TITLE
Copy-Item -Include / -Exclude filters with -Recurse are unexpectedly applied to an input directory path itself

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#8459]
Related: 

* #4988, which demonstrates that using `-Include` \ `-Exclude` causes _non-existent_ input paths to be ignored.

* #3304, which shows that `Get-ChildItem -Include` \ `-Exclude` - _without `-Recurse`_ - unexpectedly apply to a - possibly implied input directory's name _itself_, not to the items _inside_ the directory.

While adding `-Recurse` to `Get-ChildItem` fixes the problem, the same is not true for `Copy-Item`, which continues to apply `-Include` and `-Exclude` filters to the input directory name too, which is especially problematic with `-Include`:

# Steps to reproduce

```powershell
Set-Location $HOME
'---'
# Note: Wildcard *.* does NOT match 'Desktop', because it has no extension.
Copy-Item -Recurse Desktop /tmp -Include *.*  -WhatIf
'---'
Copy-Item -Recurse Desktop /tmp -Exclude desk* -WhatIf
```
# Expected behavior

```none
---
What if: Performing the operation "Copy Directory" on target "Item: C:\Users\jdoe\Desktop Destination: C:\tmp\Desktop"
---
What if: Performing the operation "Copy Directory" on target "Item: C:\Users\jdoe\Desktop Destination: C:\tmp\Desktop"
```
That is, both commands should indicate that a copy operation will take place (even though the details aren't mentioned).

# Actual behavior

```none
---
---
```

That is, both commands were unexpectedly _quiet no-ops_, because `-Include` filter `*.*` and  `-Exclude` filter `desk*` were both applied to `Desktop` itself, eliminating the one and only input path.

# Environment data

```none
PowerShell Core v6.2.0-preview.2 on macOS 10.14.1
PowerShell Core v6.2.0-preview.2 on Ubuntu 18.04.1 LTS
PowerShell Core v6.2.0-preview.2 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.407)
Windows PowerShell v5.1.17134.407 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.407)
```

**Comment by mklement0** [comment]
> copy with -Include *.* in 6.2.0-Preview.3 works for me for this scenario

Intriguing. I just tried on the following platforms with preview 3, and it does _not_ work for me, meaning that there's _no output_; what is your exact invocation scenario?

```none
PowerShell Core v6.2.0-preview.3 on macOS 10.14.2
PowerShell Core v6.2.0-preview.3 on Ubuntu 18.04.1 LTS
PowerShell Core v6.2.0-preview.3 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.471)
Windows PowerShell v5.1.17134.407 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.471)
```

> Should be intelligent enough to exclude the source path...

Yes, if you provide a _container_ as the source path, combined with `-Recurse` (arguably, even without it, but that's a separate issue), the wildcard should not be applied to the container itself, only to its descendants - that's how it (sensibly) works with `Get-ChildItem`.

> And isn't the -Exclude source path behaviour an expected one ? 

In light of the above: what about the current behavior is expected?

**Comment by kvprasoon** [comment]
I didn't notice the term `directory` , I tried with file and worked
`♥->copy -Recurse -Path .\t.log -Include *.* -Verbose -Force -Destination C:\Temp\ -WhatIf     What if: Performing the operation "Copy File" on target "Item: C:\Windows\Temp\testcopy\t.log Destination: C:\Temp\t.log".
`

and doesn't work for directory as you mentioned. But the exclusion issues is common for directories and path.

`♥->copy -Recurse -Path .\t.log -Exclude t* -Verbose -Force -Destination C:\Temp\ -WhatIf
♥->
`

**Comment by mklement0** [comment]
It's actually not about file vs. directory, it's that `*.*` only matches names _with an extension_, so `*.*` doesn't match `Desktop`, but matches `t.log`.

**Comment by kvprasoon** [comment]
Got it, Thanks ! `*.*` matches with directory with `.` in its name too.

**Comment by AlexGadd** [comment]
This is still an issue, able to replicate on windows 11 with powershell 7.6.1
