### ISSUE TITLE
Didn't set CategoryActivity to the specified value

### ISSUE THREAD

**Issue by TingLiu6** [PowerShell/PowerShell#846]
[Write-Error] after running command below, $Error[0].CategoryInfo.Activity Should Be 'myactivity', but it returns 'write-error'.
```
$exception = New-Object -TypeName System.ArgumentNullException -ArgumentList paramname 
Write-Error -Message myerrortext -Exception $exception -ErrorId myerrorid -Category syntaxerror -TargetObject TargetObject -CategoryActivity myactivity -ErrorAction SilentlyContinue
```

**Comment by adityapatwardhan** [comment]
@lzybkr This is because of hard coded value at: https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Utility/commands/utility/write.cs#L385

I think when a value is supplied we should use it instead of hard-coded "write-error".
