### ISSUE TITLE
Hashtable or Array?

### ISSUE THREAD

**Issue by whitequill** [PowerShell/PowerShell#8466]
# Support Question
I'm listing a directory's content to a variable with the following command:
`$pyd = Get-ChildItem .\*.pyd | ForEach-Object{ @{Path=$_.FullName}}`

When I use `$pyd.GetType()` it show that it is an Array.  Shouldn't it be showing it to be a Hashtable?
I'm just making sure this is the intended behavior. I don't want to list a bug that isn't there.
## Official support

[PowerShell Support Lifecycle](http://aka.ms/pslifecycle)

## Community Resources

[Slack Community Chat](https://powershell.slack.com) - Interactive chat with other PowerShell enthusiasts
[PowerShell.org Forum](https://powershell.org/forums/) - Search or post new general PowerShell usage questions

**Comment by vexx32** [comment]
It's an array... of hashtables. 😉 

If you pipe that end to `Get-Member` you'll see that each object is indeed a hashtable. Arrays can hold anything, and any time you store multiple objects from the pipeline into a variable, they will be packaged into an array so that PS can store them. 😄

**Comment by whitequill** [comment]
I was thinking it was a hashtable of strings. That is why it got me confused.

**Comment by vexx32** [comment]
It is! It's an array... Of hashtables... With strings in them! :D

**Comment by whitequill** [comment]
I think what I wanted to do was this: `$pyd = Get-ChildItem .\*.pyd | ForEach-Object{ @($_.FullName)}`
I guess I'll just ask. How to do you put a list of files into a command like:

this is what you do in bash;`ln ../source/*.pyd .`, but powershell doesn't like it.
New-Item -ItemType HardLink -Path <destination directory> -Name .\*.pyd -Value <source directory>

It also doesn't like a variable with a array of files or an array of hashtables of strings.
