### ISSUE TITLE
Setting ulimit inside PowerShell

### ISSUE THREAD

**Issue by andyleejordan** [PowerShell/PowerShell#847]
While setting up the OS X build, I encountered a funny issue. Running `ulimit -n 4096` inside PowerShell had no effect, so I had to run it before launching the PowerShell process. Now, `ulimit` is both a Bash built-in and a native command on OS X. My guess is that, when running from PowerShell, it was launched as a child process (of course) and so the system call to `setrlimit` only affected the launched child process, not PowerShell itself.

I think the appropriate fix would be to add a built-in `ulimit` function to PowerShell that called `setrlimit` in-proc, thus modifying the current process's open file descriptor limit.

This is a total edge case that we should take care of at some point, but I don't think it's super high priority.

**Comment by andschwa** [comment]
This would be a great feature for Hacktoberfest. It's (probably) just a bit of Linux/OS X native code added to libpsl-native and a new PowerShell cmdlet that P/Invokes it.

**Comment by SteveL-MSFT** [comment]
Related https://github.com/PowerShell/PowerShell/issues/6725

**Comment by adityapatwardhan** [comment]
The prototype is located at: https://github.com/PowerShell/UnixUtils

We need to release it to powershell gallery when time permits.

**Comment by kilasuit** [comment]
> The prototype is located at: https://github.com/PowerShell/UnixUtils
> 
> We need to release it to powershell gallery when time permits.
> 

Did this ever get released @SteveL-MSFT / @adityapatwardhan ?
