### ISSUE TITLE
When using ZIP package, some ps1xml files (PsReadline and Microsoft.PowerShell.Utility) are not trusted

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#8474]
# Steps to reproduce

Download ZIP from GitHub releases [here](https://github.com/PowerShell/PowerShell/releases/download/v6.1.1/PowerShell-6.1.1-win-x64.zip) using the latest version of Chrome on Windows (I tried not only 6.1.1 but also 6.0.5). The ZIP does not seem to be signed, the properties on the zip show me that not everything is being trusted.
![image](https://user-images.githubusercontent.com/9250262/50057344-fa56ee00-0160-11e9-989e-c521c148e1d2.png)
If I then extract it, and execute `pwsh.exe`, I get prompts about parts of PowerShell Core not being trusted.

````powershell
PowerShell 6.1.1
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

Do you want to run software from this untrusted publisher?
File C:\users\cberg\downloads\powershell-6.1.1-win-x64\Modules\PSReadLine\PSReadLine.format.ps1xml is published by
CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US and is not trusted on your system.
Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"): r

Do you want to run software from this untrusted publisher?
File
C:\users\cberg\downloads\powershell-6.1.1-win-x64\Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psm
1 is published by CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US and is not trusted
on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"): r
Loading personal and system profiles took 5298ms.
````

# Expected behavior

All files shipped as part of PowerShell are completely trusted at runtime and I do not get any prompts when opening pwsh the first time or have to unblock the zip.

# Actual behavior

Some files shipped as part of PowerShell are not being trusted, this includes:
- PSReadline.ps1xml
- Microsoft.PowerShell.Utility.psm1
- WSMan.format.ps1xml (came up during tab-completion)

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.1.1
PSEdition                      Core
GitCommitId                    6.1.1
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by KevinMarquette** [comment]
This is a standard behaviour of Windows when downloading ZIPs from untrusted zones. If you unblock the ZIP before extracting the files, then the extracted files will not be blocked. I don't know that you can sign ZIP files.

**Comment by bergmeister** [comment]
Whilst that is true, my point was rather that PowerShell can still execute fine inside the not unblocked extracted zip because it trusts the binaries due to them being signed except for a few ps1xml files (despite them being signed as well).
To me it would be nice if everything just worked even when not being unblocked, given that 98% works already, I think that's not unreasonable.

**Comment by SteveL-MSFT** [comment]
This doesn't repro with PS7 preview.6

**Comment by bergmeister** [comment]
Yes, I can confirm, it does not happen with 7.0-preview6 or 6.2.2 any more
