### ISSUE TITLE
`using module` fails to check already-loaded modules for available custom types

### ISSUE THREAD

**Issue by vexx32** [PowerShell/PowerShell#8475]
`using module` _only_ works on modules in $env:PSModulePath, i.e., it is _impossible_ to target already-loaded modules.

This can be frustrating when developing and testing modules that make use of custom types in some shape or form that expect them to be exportable from the module.

# Steps to reproduce

## Create two files

1. A simple module file defining a custom attribute. Save as `TestModule.psm1`

```powershell
class CustomAttribute : Attribute {
    CustomAttribute() {}
}
```

2. A file with script-level attribute and `using module` attached. Save as `BrokenFile.ps1`

```powershell
using module TestModule
[Custom()]
param()

Write-Host "hello!"
```

## Attempt to have PowerShell parse the file

We can use `Get-Command` for this; if the parse fails, the resulting object's `ScriptBlock` property is empty.

```
PS> Import-Module .\TestModule.psm1
PS> $Command = Get-Command .\BrokenFile.ps1
PS> $Command.ScriptBlock
```

# Expected behavior

The scriptblock property should be populated, and output the contents to console, as the `using module`  directive is targeting a named module already loaded in the current session.

```none
PS> $Command.ScriptBlock
using module TestModule
[Custom()]
param()

Write-Host "hello!"
```

# Actual behavior

```none
PS> $Command.ScriptBlock
<no output>
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

/cc @rjmholt

**Comment by rjmholt** [comment]
Absolute path should work.

We will need to loop in @lzybkr, @daxian-dbw and @brucepay, because this may be by-design behaviour. `using module` may be deliberately intended for runtime-state-invariant behaviour.

**Comment by vexx32** [comment]
I can understand if that is the intent, however I would probably think that sort of behaviour may be better reserved for strict-mode states only, perhaps?

**Comment by lzybkr** [comment]
`using module` should support relative paths but not non-constant paths.

I think we discussed allowing `using module $PSScriptRoot\whatever` but decided it wasn't necessary as the language constructed was defined to look for paths relative to the file as though you'd used `$PSScriptRoot` **and** allowing a variable implied you could use non-constant paths.
