### ISSUE TITLE
Make Start-Sleep accept fractional seconds

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#8477]
# Summary of the new feature/enhancement

While `Start-Sleep -MilliSeconds` offers fine-grained control over the sleep duration, it would be convenient not to have two switch parameters just to be able to effectively specify _fractional_ seconds.

E.g., instead of:

```powershell
Start-Sleep -MilliSeconds 1400
```

it would be nice to be able to write:

```powershell
Start-Sleep 1.4  # wishful thinking; translate into 1,400 msecs.
```

This is in line with the `sleep` utility on macOS and Linux, which accepts fractional values (e.g., `sleep 1.4`)

Currently, fractional values are _quietly converted to `[int]` values_, which means that _rounding_ is applied, which is not only obscure behavior, but behavior that existing code is unlikely to rely upon.

As an aside: `Start-Sleep` is misnamed and should be called `Invoke-Sleep` - see #3990.

# Proposed technical implementation details (optional)

Change the data type of the `-Seconds` parameter from `[int]` to `[double]` and simply cast the internal conversion to milliseconds to `(int)`.

**Comment by Prototyyppi** [comment]
Hi, Can I have a look at this

**Comment by SteveL-MSFT** [comment]
@Prototyyppi consider it yours!

**Comment by iSazonov** [comment]
Why double?

**Comment by mklement0** [comment]
@iSazonov:

I simply chose `[double]`, because that's what number literals with a a decimal point (e.g., `1.4`) become in PowerShell.

Note that that even the current `[int]` type cannot be used in its full range, because internally the value is multiplied by `1000` to get milliseconds, while still using `[int]` for the calculation:

```powershell
PS> start-sleep ([int]::maxvalue)
Start-Sleep : Cannot validate argument on parameter 'Seconds'. 
The 2147483647 argument is greater than the maximum allowed range of 2147483
```

Note that `2147483` is simply the result of integer-dividing `[int]::MaxValue]` by `1000`.
In fact, an explicit validation attribute on the `-Seconds` parameter enforces that: https://github.com/PowerShell/PowerShell/blob/40223881cbc9444c21245884096cc502275cb1ae/src/Microsoft.PowerShell.Commands.Utility/commands/utility/StartSleepCommand.cs#L45

That is, the (undocumented) max. sleep duration is currently `24.20:31:23` (24+ days).

That probably shouldn't change, irrespective of what non-integral type we choose - unless we feel we need to raise that limit.

So, what's your concern re `[double]`?

**Comment by iSazonov** [comment]
I am thinking about decimal.

**Comment by mklement0** [comment]
@iSazonov: I think that kind of precision is overkill and may give users a false sense of how faithful the actual sleep duration is to the requested one.

**Comment by iSazonov** [comment]
We could use a validate pattern like `ddddd.ddd`.

**Comment by mklement0** [comment]
@iSazonov: What is the benefit of that, and why do you need `[decimal]` for that?

**Comment by mklement0** [comment]
@iSazonov: 

To put it differently: in a way we already have a potential over-promising problem, by supporting `-MilliSeconds` values; e.g.:

```powershell
PS> (Measure-Command { Start-Sleep -Milliseconds 10 }).TotalMilliseconds
11.7617  # e.g.
```

I think it's sufficient to _document_ the limits of accuracy and to otherwise make do with `[double]`.

**Comment by mklement0** [comment]
> I don't like "1.1e1"

Note that `Start-Sleep 1.1e1` already works, because PowerShell happily converts this `[double]` literal to an `[int]` during parameter binding.
PowerShell's flexible automatic type conversions can be confusing at times, but by and large they're very useful - I don't think we should introduce any artificial restrictions here.

> Also I'd don't add such changes because it complicates backporting scripts.

_Any_ new feature complicates back-porting - it's the price of innovation.
There are many cases already where features have been added later (`-Raw`, `-File`, `-Directory`, ...), and there's no way around knowing what features where introduced when if you want to target earlier versions too.

Now we may have to think about how to "batch" new features coupled with semantic versioning so that it doesn't become too complex to keep track of what feature was introduced when, but that is a separate discussion.
