### ISSUE TITLE
powershell vimdiff equivalent

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#8479]
How to compare two object ,like two text files?
We can use Compare-Object but it does not nice , is there any cmdlet that work like vimdiff in linux ?

![compare-object](https://user-images.githubusercontent.com/36788337/50072194-4d877a00-020f-11e9-9ed6-56329f66d9d3.png)

**Comment by thezim** [comment]
@tlsalex unfortunately no. A good diff module would be a welcome addition the community.

**Comment by vexx32** [comment]
It looks like you can extend the functionality of Compare-Object relatively easily to accomplish this.

http://www.leeholmes.com/blog/2013/11/29/using-powershell-to-compare-diff-files/

This page has one example, although the code could use some TLC. I see no reason why we couldn't add to the functionality of Compare-Object with a `-Diff` or `-Detailed` or some similarly-named optional switch. 😄
