### ISSUE TITLE
How to enter a remote PSSession as elevated user

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#8483]
I tried to add one windows capability on my server,
But it show me Access is denied, and of course it runs well on local console which run powershell as administrator. 

If we use sysinternals tool which is psexec.exe to remote a machine , we can give it a -h parameter , that let us to run cmd with the account's elevated token.

So the question is whether PowerShell has a similar way to enter a remote session ?
If the answer is no , is there any other way to implement ?

![deny](https://user-images.githubusercontent.com/36788337/50130705-e83c9300-02b9-11e9-9ae7-13af4ea20f0a.png)

**Comment by tlsalex** [comment]
And how to enter a elevated user mode after you already inside a remote PSSession ?

**Comment by iSazonov** [comment]
sudo discussion #3232

**Comment by tdaniely** [comment]
Run sshd elevated.

**Comment by he852100** [comment]
@iSazonov 

This seems to be two different needs. Even with administrator rights, remote login sits without a way to execute the command successfully   

这好像是两种不同的需求。即使拥有管理员权限,远程登录也没有办法执行成功这个命令
```
```powershell
PS C:\Users\Administrator> Add-WindowsCapability -Online -Name "
Tools.Graphics.DirectX~~~~0.0.1.0"
Add-WindowsCapability : 拒绝访问。
所在位置 行:1 字符: 1                                           + Add-WindowsCapability -Online -Name "Tools.Graphics.DirectX~~
~~0.0.1. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-WindowsCa
   pability], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.AddWindo
   wsCapabilityCommand
```
```

**Comment by he852100** [comment]
```powershell
$name='Capability'
Register-ScheduledJob -Name $name -ScriptBlock {add-WindowsCapability -Online -Name "Tools.Graphics.DirectX~~~~0.0.1.0"} -RunNow
Start-Sleep 2
Wait-Job $name|Receive-Job  #;Remove-Job $name
Unregister-ScheduledJob $name -force
```
```powershell
PS > get-WindowsCapability -Online -Name '
*Tools.Graphics*'|select name,State

Name                                  State
----                                  -----
Tools.Graphics.DirectX~~~~0.0.1.0 Installed
```
