### ISSUE TITLE
Set-Content -PassThru and -OutVariable lack parity with file contents

### ISSUE THREAD

**Issue by markekraus** [PowerShell/PowerShell#8485]
It appears that when Set-Content sets a Newline at the end of the file, the new line is not also included in the content of -PassThru or in the content of `-OutVariable`.

IMO, the output should be an exact match for the content actually placed in the file, including the appended newline.

# Steps to reproduce

```powershell
$Path = 'c:\temp\testfile.txt'
$Result = "a" | Set-Content -Encoding UTF8 -PassThru -OutVariable SetContent -Path $Path
$FileContent = Get-Content -Raw -Path $Path
describe "Newline Parity" {
    It 'OutVariable should be the same as File Content' {
        $SetContent[0] | Should -BeExactly $FileContent
    }
    It 'PassThru should be the same as FileContent' {
        $Result | Should -BeExactly $FileContent
    }
}
```

# Expected behavior

```none
Describing Newline Parity
  [+] OutVariable should be the same as File Content 49ms
  [+] PassThru should be the same as FileContent 46ms
```

# Actual behavior

```none
  [-] OutVariable should be the same as File Content 378ms
    Expected strings to be the same, but they were different.
    Expected length: 3
    Actual length:   1
    Strings differ at index 1.
    Expected: 'a\r
    '
    But was:  'a'
    ------------^
    3:         $SetContent[0] | Should -BeExactly $FileContent
  [-] PassThru should be the same as FileContent 172ms
    Expected strings to be the same, but they were different.
    Expected length: 3
    Actual length:   1
    Strings differ at index 1.
    Expected: 'a\r
    '
    But was:  'a'
    ------------^
    6:         $Result | Should -BeExactly $FileContent
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
Just to state what `-PassThru` is _currently_ doing:

It is  the _input objects_ that are being passed through, not the derived string representation sent to the output file:

```powershell
PS> (1..2 | Set-Content -PassThru t.txt).GetType().Name
Object[]
```

I agree that it makes more sense to pass out the derived string representation, mirroring what is sent to the file.

**Comment by UberKluger** [comment]
The parameter name `-PassThru` would imply to me that a received object is "passed through" unaltered (current behaviour). For situations where it is desired that the output object (pipeline or `-OutVariable`) should accurately reflect the stored contents of the file, see #16773 for a possible (non-breaking) solution to this. In summary, `Set-Content` (and any other desired cmdlet) should have a `-Raw` option to allow the passed object to be written verbatim (without added new-lines). Desired new-lines would be added to the (possibly pre-stringified) object before being passed in and so would be a part of the (string) passed through.

While this could require a not insignificant added complexity to such scripts (particularly where pre-stringification is required), the actual number of cases would likely be small and so the overall added versatility (i.e. total control of the saved contents) in other cases could be well worth it.
