### ISSUE TITLE
UNC Path works with Import-Module

### ISSUE THREAD

**Issue by pjamesburwell** [PowerShell/PowerShell#8487]
This works too, and even from UNC path:
`Import-Module -Verbose C:\PSPrivateGallery\Modules\PSGallery`

**Comment by vexx32** [comment]
I'm not really sure what the problem is here? Need more info; if you could, please fill out the standard issue template with all the details you have. 😄

**Comment by SteveL-MSFT** [comment]
UNC paths are supported
