### ISSUE TITLE
Invoke-WebRequest/RestMethod Attached "Expect: 100-continue" on Requests

### ISSUE THREAD

**Issue by Arefu** [PowerShell/PowerShell#8489]
# Support Question
I've been messing around with a project today and noticed that sometimes my requests fail, I couldn't quite nail it down until I installed Fiddler and saw that in the headers my script was requesting `Expect: 100-continue`, after a bit of digging I also noticed once I login to the web page manually it returns a 200, I just added `-Headers` to my script to also Expect 200, but I would like to know why this is? I never set it up to expect anything before now.

## Official support

[PowerShell Support Lifecycle](http://aka.ms/pslifecycle)

## Community Resources

[Slack Community Chat](https://powershell.slack.com) - Interactive chat with other PowerShell enthusiasts
[PowerShell.org Forum](https://powershell.org/forums/) - Search or post new general PowerShell usage questions

**Comment by markekraus** [comment]
@Arefu 
Could you provide some command examples that could replicate the issue?

Also, can you clarify it the the `Expect:` you saw i fiddler was in the request headers from your client and not in the response headers?

Finally, can you confirm you still have the problem after having disabled all antivirus, firewalls, and local proxies? Sometimes AV and security software can mess with http request payloads.

**Comment by Arefu** [comment]
```POST http://10.57.181.82/servlet?p=login&q=login HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT; Windows NT 10.0; en-NZ) WindowsPowerShell/5.1.17763.134
Content-Type: application/x-www-form-urlencoded
Host: 10.57.181.82
Cookie: JSESSIONID=2b416af439772b416d60
Content-Length: 43
Expect: 100-continue
```
Is my header from PowerShell which is my CLIENT header, I can verify this because when I append the Expect 200 into my Headers I get
```POST http://10.57.181.82/servlet?p=login&q=login HTTP/1.1
Expect: 200-ok,100-continue
User-Agent: Mozilla/5.0 (Windows NT; Windows NT 10.0; en-NZ) WindowsPowerShell/5.1.17763.134
Content-Type: application/x-www-form-urlencoded
Host: 10.57.181.82
Content-Length: 43
Connection: Keep-Alive
``` 
In Fiddler, I have no extra anti-virus installed but Windows Defender. But I will disable them, and try without a Fiddler capture running it could be that.

**Comment by markekraus** [comment]
It looks like you are experiencing this with Windows PowerShell 5.1. For Windows PowerShell 5.1 issues, suggestions, or feature requests please use the following link instead: Windows PowerShell [UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell). This repository is for PowerShell Core 6 issues.

Can you see if you have the same trouble with 6.1.1? 

https://github.com/PowerShell/PowerShell/releases/tag/v6.1.1
