### ISSUE TITLE
Provide repro for ProcessName being incorrect on OS X

### ISSUE THREAD

**Issue by andschwa** [PowerShell/PowerShell#849]
Same problem as dotnet/corefx#5378 is happening on OS X 10.11 on Travis. The particular asserts have been disabled in b930eeef9. We need to create a non-PowerShell repro to share with the CoreFX team.

**Comment by joeyaiello** [comment]
Could someone with a Mac (like @BrucePay or @JamesWTruher) tell me if this one still repros? Thanks!
