### ISSUE TITLE
powershell tcpdump equivalent

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#8490]
Is there a cmdlet that can be used to capture data according to the specific protocol or IP address within PowerShell ?

Just like the tcpdump command in Linux

**Comment by iSazonov** [comment]
PowerShell allows you to run any external command and capture it output. So you could use tcpdump like before.

**Comment by vexx32** [comment]
This is a similar idea using a native Windows command and parsing the output to retrieve specific bits of information:

https://vexx32.github.io/2018/11/08/Named-Regex-Matches-PSCustomObject/

You could adapt a similar solution. Actually capturing TCP data from PS is not something that I think it is able to do natively... _however_ such a command could probably be written using the .NET methods that PS has easy access to. 😄
