### ISSUE TITLE
PSDefaultParameterValues

### ISSUE THREAD

**Issue by alicain** [PowerShell/PowerShell#8492]
When setting PSDefaultParameterValues for Get-aduser as follows: 
$PSDefaultParameterValues=@{'Get-ADUser:Properties' = "SamAccountName" , "UserPrincipalName" , "DistinguishedName" , "GivenName" , "Surname" , "Name" , "Enabled" , "employeeid" , "lastlogondate"}
In addition to the requested parameters, SID / ObjectGUID and ObjectClass are still displayed.

**Comment by vexx32** [comment]
The AD cmdlets will do this regardless of $PSDefaultParameterValues, with specifying these properties manually, so it's not really related to that.

The AD cmdlets have a 'defaut property set' of a handful of properties that it returns when no properties are specifically requested. When you request specific properties, it treats those as "additional" to the default set, _not_ as a full replacement for its default set.

If you want to have objects with only certain properties on them, you need to use Select-Object to pare off the properties you don't want.
