### ISSUE TITLE
Precedence of comma and addition operators doesn't make sense

### ISSUE THREAD

**Issue by vexx32** [PowerShell/PowerShell#8495]
The comma operator has either higher or the same precedence as addition, causing `+` to behave as though concatenating arrays rather than adding values as one would more reasonably expect (in my opinion).

# Steps to reproduce

```powershell
$a = 0..10
$x = 5
$a[$x, $x + 1, $x + 2]
```

# Expected behavior

Addition should be more similar to multiplication, taking place before the comma operator in the absence of explicit parentheses.

```none
5
6
7
```

# Actual behavior

```none
5
5
1
5
2
```

As it is not completely clear, what's actually happening is that PS is treating the resolution more like it was entered like this:

```none
$a[ @($x, $x) + @(1, $x) + 2 ]
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by MaximoTrinidad** [comment]
Hum! 
I don't think anything is wrong. I would use parentheses to contain the expressions results. 
That's me!
```
PS [40] > $a[($x), ($x + 1), ($x + 2)]
5
6
7

PS [44] > $b = 5; $c = 6; $d = 7;
PS [45] >
PS [46] > $a[$b, $c, $d]
5
6
7
PS [50] >
```

:)

**Comment by vexx32** [comment]
Sure, you _can_. But in most languages folks are used to, simple math operations generally evaluate before something like concatenating reference objects like arrays. 😄 

In my opinion, I think requiring parentheses to evaluate as "add arrays together" is _much_ more sensible.

**Comment by SteveL-MSFT** [comment]
@vexx32 if we were starting from scratch, I would agree with you.  However, this would be a breaking change.

**Comment by mklement0** [comment]
@vexx32: 

I get that the current behavior may be surprising, but changing it would be a massively breaking change.

The current behavior _is_ documented, namely in [`about_operator_precedence`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operator_precedence?view=powershell-6).

As @SteveL-MSFT  states, such a change would definitely be  a [vZeroTechnialDebt](#6745)-related proposal.

**Comment by vexx32** [comment]
@SteveL-MSFT @mklement0 I would be _very_ surprised indeed if anyone actually depended on the current behaviour. But knowing how PowerShell users are, I fully expect to be surprised pretty shortly as someone turns up depending on the current behaviour. 😏 

That said, I agree this is the sort of fundamental language precedence that is... _difficult_ at best to ever have changed.

I still think it _should_ be a noted and tracked issue, just in case we ever _do_ get any kind of zero-tech-debt version in the works as @mklement0 mentions.

**Comment by mklement0** [comment]
@vexx32: 

>  it should be a noted and tracked issue,

It is: in [`about_operator_precedence`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operator_precedence?view=powershell-6).
And, as long as the surprising behavior can't be changed, that's the best we can do.

> if anyone actually depended on the current behaviour. But knowing how PowerShell users are, I fully expect to be surprised pretty shortly as someone turns up depending on the current behaviour.

I hear you, but changing something as fundamental as operator precedence is bound to break existing code, especially if users have read the docs and have come to rely on what they find there; e.g.:

```powershell
PS> , 1   +   2, 3
1
2
3
```

**Comment by vexx32** [comment]
😬 

Haha, if I had someone hand me code written like _that_, it'd be getting rewritten on the first pass. 😄 

I'll make a note over there, thanks!

**Comment by vexx32** [comment]
Appreciate you taking the time to lay that all out, @BrucePay! 😄 

You're right, it is complicated somewhat by the fact that the comma operator sometimes just isn't an operator, which maybe is a bit unfortunate given that method invocation is a separate parsing mode _anyway_ and perhaps other delimiters _might_ have been a slightly more effective choice given the easy confusion of arrays vs method arguments as it is.

But really I guess the "issue" here is that it doesn't really match up to expectations of operator precedence that I would generally expect... and maybe, at the end of the day, that's just me. 😄

**Comment by jzabroski** [comment]
@vexx32  Can you please edit your original post to say that the comma operator has the highest precedence of all PowerShell operators?

Quote from PowerShell in Action (**emphasis mine**):

> 5.4.1 The comma operator
> You’ve already seen many examples using the comma operator to build arrays. We covered this topic in some detail in chapter 3, but there are a couple of things we still need to cover. **In terms of precedence, the comma operator has the highest precedence of any operator except for casts and property or array references.** This means that when you’re building an array with expressions, you need to wrap those expressions in parentheses. In the next example, you’ll build an array containing the values 1, 2, and 3. You’ll use addition to calculate the final value. Because the comma operator binds more strongly than the plus operator, you won’t get what you want:
> ```
> PS (1) > 1,2,1+2
> 1
> 2
> 1
> 2
> ```

**Comment by jzabroski** [comment]
@SteveL-MSFT Did you close this by accident?

**Comment by mklement0** [comment]
@jzabroski, this issue is being linked to from #6745, which should be sufficient.
