### ISSUE TITLE
Getting Windows Tar Packaged

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/PowerShell#8499]
# Support Question

Sorry - I don't know how to touch bases with everyone who gets on the calls.

I can't find that windows tar has built binaries available anywhere publicly.  Does anyone know where they might be?

If they truly aren't built anywhere, does anyone know if the Free for Open Source Azure Pipelines could be configured to build it?  (https://azure.microsoft.com/en-us/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/)

**Comment by SteveL-MSFT** [comment]
Found the internal owner will see if they respond.  Since it's the end of year, might not hear back til next year.

**Comment by DarwinJS** [comment]
I forgot to mention that after posting this issue, I opened an issue on the github page for the project and asked if they distribute binaries - they answered no and closed the issue.  Not sure if the internal person is the same as the repo owner.

**Comment by SteveL-MSFT** [comment]
@DarwinJS it's likely the same person.  What is the repo?

**Comment by SteveL-MSFT** [comment]
Thanks @DarwinJS that doesn't look like a Microsoft owned repo but the repo for the original source and I don't expect they would build/maintain binaries.

**Comment by DarwinJS** [comment]
@SteveL-MSFT - is it possible to get the compile settings and/or CI job config that Microsoft is using to compile the built-in version?  For instance, I noticed 7zip format is not included in the one that ships on Windows.

**Comment by SteveL-MSFT** [comment]
Unfortunately not able to get that information
