### ISSUE TITLE
Window Quick Link integration

### ISSUE THREAD

**Issue by breyed** [PowerShell/PowerShell#8514]
On recent Windows versions, you can configure the Quick Link menu opened via <kbd>Windows</kbd>+<kbd>X</kbd> to open a PowerShell prompt instead of a Command Prompt. This option has always been powerful but slow. PowerShell Core's faster startup can help here, but only if the Quick Link menu item opens PowerShell Core instead of PowerShell.

When PowerShell Core is installed on Windows, there should be a way the user can configure which version of PowerShell to use from the Quick Link menu.

An alternative approach is to provide a way to remove the non-Core version of PowerShell so that there is no ambiguity. For users who only need the features in Core, this would be the most straightforward.

**Comment by SteveL-MSFT** [comment]
I appreciate the enthusiasm, but a bit early to properly discuss this :)
