### ISSUE TITLE
Unable to load shared library 'libpsrpclient' or one of its dependencies

### ISSUE THREAD

**Issue by djniu** [PowerShell/PowerShell#8548]
Since this issue #6281 was closed, I build a net core project and use the latest Nuget package, then make a docker image to test, the exception "System.DllNotFoundException: Unable to load shared library 'libpsrpclient' or one of its dependencies" still throws

# Steps to reproduce
Error:
```
This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for th is system. ---> System.DllNotFoundException: Unable to load shared library 'libpsrpclient' or one of its dependencies
```
csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="psrp" Version="1.4.5-0" />
    <PackageReference Include="System.Management.Automation" Version="6.1.1" />
  </ItemGroup>
</Project>
```
Docker file:
```
FROM microsoft/dotnet:2.1-sdk AS publish
WORKDIR /src
COPY . .
WORKDIR /src/TestDocker
RUN dotnet publish TestDocker.csproj -c Release --runtime linux-x64 -o /app --source "https://proget.xxxxx.net/nuget/NuGet.org" --source "https://powershell.myget.org/F/powershell-core/api/v3/index.json"

FROM microsoft/dotnet:2.1-runtime AS base
WORKDIR /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "TestDocker.dll"]
```
Code:
```
var credential = new PSCredential(userName, secureString);
 WSManConnectionInfo connectionInfo = new WSManConnectionInfo(
                new Uri("https://outlook.office365.com/PowerShell-LiveID"),
                "http://schemas.microsoft.com/powershell/Microsoft.Exchange", credential);
connectionInfo.AuthenticationMechanism = AuthenticationMechanism.Basic;
Runspace runspace = RunspaceFactory.CreateRunspace(connectionInfo);
```

# Expected behavior

```
Application run as expected

```

# Actual behavior
```
Exception throw:
System.Management.Automation.Remoting.PSRemotingTransportException: This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system. ---> System.DllNotFoundException: Unable to load shared library 'libpsrpclient' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environmen
t variable: liblibpsrpclient: cannot open shared object file: No such file or directory
   at System.Management.Automation.Remoting.Client.WSManNativeApi.WSManInitialize(Int32 flags, IntPtr& wsManAPIHandle)
   at System.Management.Automation.Remoting.Client.WSManClientSessionTransportManager.WSManAPIDataCommon..ctor()
```

**Comment by djniu** [comment]
Finally I figure out what's going on. I checked how the psrp loaded the libpsrpclient.so and found out that the psrpclient require libssl1.0.0, however in microsoft/dotnet:2.1-runtime based image, there are only libssl1.0.2 and libssl1.1, so I edited the docker file and manually to install libssl1.0.0. Here we can't use command "apt-get install libssl1.0.0" to install, need to use "dpkg -i libssl1.0.0_1.0.1t-1+deb8u10_amd64.deb" to install. 

Code in Docker file:
```
RUN apt-get -y install wget
RUN wget "http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u10_amd64.deb"
RUN dpkg -i libssl1.0.0_1.0.1t-1+deb8u10_amd64.deb
```

**Comment by Veverke** [comment]
Adding on @djniu 's solution
That alone did not work for me.
libssl package would not install due missing `multiarch-support` dependency.
So the dockerfile additions that fixed the issue for me look like

`
     RUN wget "http://http.us.debian.org/debian/pool/main/g/glibc/multiarch-support_2.19-18+deb8u10_amd64.deb"
     RUN dpkg -i multiarch-support_2.19-18+deb8u10_amd64.deb
     RUN wget "http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u12_amd64.deb"
     RUN dpkg -i libssl1.0.0_1.0.1t-1+deb8u12_amd64.deb     
     #install powershell WSMan.Management module (https://www.bloggingforlogging.com/2020/08/21/wacky-wsman-on-linux/)
`
