### ISSUE TITLE
validatescript tab-completion dont show possible values

### ISSUE THREAD

**Issue by timoline** [PowerShell/PowerShell#8549]
(Maybe it should be at vscode repo)

# Steps to reproduce

```
function Test-Service
{
    [CmdletBinding()]
    param (
        [ValidateScript({Get-Service | Select-Object Name})]
        $Service
    )
    
    begin
    {
    }
    
    process
    {
        $Service
    }
    
    end
    {
    }
}
```

# Expected behavior

Test-Service -Service  [tab]
when pressing tab you should see possible values

# Actual behavior

doesnt show values

# Environment data

Name                           Value
----                           -----
PSVersion                      6.1.1
PSEdition                      Core
GitCommitId                    6.1.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by timoline** [comment]
Great examples thx!

But are you saying that tab-complition is not possible like validateset?

**Comment by vexx32** [comment]
Yeah, ValidateScript is too open-ended to autocomplete its own values. You can apply an `[ArgumentCompleter()]` attribute to complete the values instead if you want that. 😄

**Comment by timoline** [comment]
do you have a good example?

Your examples on your blog still doesnt work for me.

**Comment by vexx32** [comment]
If you could show me what you've attempted to work with I could offer specific suggestions. 😄 

But in general, this sort of method works well:

```powershell
function Get-File {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory, Position = 0)]
        [ValidateScript(
            {
                $_ -in (Get-ChildItem -File).Name
            }
        )]
        [ArgumentCompleter(
            {
                param($Command, $Parameter, $WordToComplete, $CommandAst, $FakeBoundParams)
                $ValidValues = (Get-ChildItem -File).Name
                return @($ValidValues) -like "$WordToComplete*"
            }
        )]
        [string]
        $Filename
    )
    "The selected file is $Filename"
}
```

**Comment by timoline** [comment]
I tried your above example.

Get-File -filename [tab]

My assumption is: when pressing tab, the values will be shown, but it isn't

**Comment by mooock** [comment]
ohh man, really looked for this answer. i also thought the validationscript did everything, but how you show it make sense. i also did a script that worked when implementing the -in
