### ISSUE TITLE
manipulate disk using native cmdlet

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#8551]
I want to convert disk from Basic to Dynamic using native cmdlet, but seems there is no that kind of cmdlet.
I tried to convert disk from ssd to hdd , but fail as bellow , and I also do not how to change the "canpool" property as I can not find a cmdlet can do that ,  any advise ?
![hdd-type](https://user-images.githubusercontent.com/36788337/50501212-6f93be80-0a91-11e9-9ffe-f3b128f37d22.png)

**Comment by SteveL-MSFT** [comment]
That cmdlet is not one owned by the PowerShell team.  As @iSazonov suggested, please use the Windows 10 Feedback tool.

**Comment by iSazonov** [comment]
Press Start button, type "Feedback", click "Feedback Hub" - use the application to send a feedback to MSFT.
