### ISSUE TITLE
macOS: Using the clear-screen-and-reset-scrollback-buffer keyboard shortcut makes PowerShell misplace user input

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#8559]
On macOS, both Terminal.app and iTerm2.app support keyboard shortcut <kbd>Command-K</kbd> for clearing the screen as well as the scrollback buffer.

PowerShell doesn't realize that the cursor position has been reset, and prints user input on the previously active line instead of the first.

# Steps to reproduce

On macOS:

```powershell
Get-ChildItem -Recurse | Select -First 100 # issue command that places cursor on the bottom line
# Press Command-K
```

# Expected behavior

The prompt should be displayed on the 1st line, and typing input should show next to it.

# Actual behavior

While the prompt is displayed on the 1st line, typing input causes it to be printed on the line that was active when the keyboard shortcut was pressed; note how the `a`, typed after clearing the screen, is printed on the bottom line:

![image](https://user-images.githubusercontent.com/588825/50517254-cd370380-0aaf-11e9-8f28-4475e9459af2.png)

# Environment data

```none
PowerShell Core v6.2.0-preview.3 (6.2.0-preview.3) on macOS 10.14.2
```

**Comment by SteveL-MSFT** [comment]
@mklement0 can you open this issue in PSReadLine repo?

**Comment by mklement0** [comment]
Sure; please see https://github.com/lzybkr/PSReadLine/issues/841
