### ISSUE TITLE
Hard to find good issues for first time contributors.

### ISSUE THREAD

**Issue by renehernandez** [PowerShell/PowerShell#8562]
As I am looking to contribute for the first time, I found that there are many issues labeled with *Up-for-Grabs*, but they vary a lot in complexity. 

This makes it harder for me to figure out which issues I should approach and whether I may need some small clarifications or I am way out of my league.

A label such as *First-Time-Issue* would simplify a lot this part of the process.

**Comment by vexx32** [comment]
Definitely would be a welcome addition. It's not always the easiest thing to determine with certainty, but a general bucket of "this should be relatively straightforward to figure out" would be a good idea. 

That said... if you ever _are_ out of your depth, I've noted in the past that simply opening an issue or commenting on an existing issue and asking for some assistance or general guidance is pretty well received here. Most of the time, the contributors and the PS team are pretty willing to help get you past anywhere you might get stuck. 😄

**Comment by SteveL-MSFT** [comment]
`Up-for-grabs` means more like "The PowerShell Team acknowledges this is an issue, but it's not a priority for us".  For `First-time-issue`, I would suggest looking at the `Hacktoberfest` label :)

Those are issues we also don't believe is a priority, but do think they are relatively simple or suitable for a hackathon type project.

https://github.com/powershell/powershell/issues?q=is%3Aopen+is%3Aissue+label%3AHacktoberfest

**Comment by renehernandez** [comment]
@SteveL-MSFT Thanks for the suggestion, I have reviewed the hacktoberfest label and it seems a better fit to start. I think it would be nice to update the issues section in the [Contributing Guide](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#contributing-to-issues) to mention the hacktoberfest label

**Comment by iSazonov** [comment]
`First-time-issue` is offered by GitHub and I guess that many people expect it in the repo.

**Comment by SteveL-MSFT** [comment]
I've created the `First-Time-Issue` label.  We can start marking candidate issues with this label.  I'll submit a PR to update the docs.

**Comment by vexx32** [comment]
Thanks, Steve! 😄
