### ISSUE TITLE
Feature request: add '&&' (and possibly '||')

### ISSUE THREAD

**Issue by mikemaccana** [PowerShell/PowerShell#8570]
# Summary of the new feature/enhancement

'&&' is a common idiom for running a command if the previous command succeeded. For evidence for the popularity of adding this feature, including discussion with Jeffrey Snover, see  https://stackoverflow.com/questions/563600/can-i-get-to-work-in-powershell

**Comment by mklement0** [comment]
Good idea, but this has already been suggested in #3241
