### ISSUE TITLE
ExecutionPolicy and File options are not order agnostic

### ISSUE THREAD

**Issue by Groostav** [PowerShell/PowerShell#8574]
Powershells `-ExecutionPolicy` and `-File` options are order sensitive. _Almost all_ of the command line tools I use do not have functional differences in the order of their command line options. This has lead me to build a mental model of arguments as an _unordered dictionary_ or _set of tuples and flags_. In fact it is more like an ordered table.

# Steps to reproduce
```ps1
# run with admin privileges
Set-ExecutionPolicy Restricted 
# restart the shell, dont need admin
Write-Output "echo 'I'm running!'" | Out-File "./hello.ps1"

powershell.exe -ExecutionPolicy Bypass -File ./hello.ps1 #successfully prints "I'm running!"
powershell.exe -File ./hello.ps1 -ExecutionPolicy Bypass # fails: scripting is disabled by execution policy
```

# Expected 
Argument order should not matter. Where it does matter it should be validated. It should be documented as such.
 -  `-File` and `-ExecutionPolicy` can be written in any order
 - OR: calling `powershell -File asdf -ExecutionPolicy Bypass` results in an error "ExecutionPolicy must come  before the -File option"
 - OR: `powershell.exe -Help` should mention that the `ExecutionPolicy` parameter is order sensitive.

# Actual 
Argument order does matter, and when that order is not used correctly powershell fails silently
 -  the `-File` and `-ExecutionPolicy` arguments are order sensitive. 
 - `-ExecutionPolicy` appears to simply "not work" in some circumstances, and with the apparent security implications of such a variable I was willing to write it off as windows security black magic _when infact [PEBCAK](https://www.bing.com/search?q=define%3A+PEBCAK)_

# Environment data

```none
PSVersion                      5.1.17134.407
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.407
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

---

I'm loathe to admit that this has contributed to a 2-year quirk in my software. Years ago I tried the `-ExecutionPolicy Bypass` option, had no impact, so I simply moved past it _requiring that our users enabled scripting on their systems_. This was a way bigger deal to deployment that I thought it would and contributed to a couple dozen man-hours of support time. More recently I tried `-ExecutionPolicy Bypass` again and everything worked as its supposed to because, by chance, I wrote it first. Perhaps I'm dumb or impatient, but my mental model of command line as being an "option dictionary" did not lead me to think about argument order.

**Comment by Groostav** [comment]
more specifically, a session:

```
PS C:\Users\geoff> Get-ExecutionPolicy
Restricted
PS C:\Users\geoff> .\hello.ps1
.\hello.ps1 : File C:\Users\geoff\hello.ps1 cannot be loaded because running scripts is disabled on this system. For
more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ .\hello.ps1
+ ~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
PS C:\Users\geoff> powershell.exe -ExecutionPolicy Bypass -File .\hello.ps1
hello!
PS C:\Users\geoff> powershell.exe -File .\hello.ps1 -ExecutionPolicy Bypass
File C:\Users\geoff\hello.ps1 cannot be loaded because running scripts is disabled on this system. For more
information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : SecurityError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

**Comment by vexx32** [comment]
As I recall, both the `-File` and `-Command` parameters must _always_ come last in a command line call to `powershell`. 

When using `-File`, any further arguments after the file name are interpreted as _arguments to be passed to the script itself_. See [here](https://docs.microsoft.com/en-us/powershell/scripting/components/console/powershell.exe-command-line-help?view=powershell-6#-file--).


When using `-Command` everything that follows is interpreted as part of the command string when called from the command line. If you're executing an instance of `powershell` _from_ PowerShell itself, then you can use an actual script block to properly delineate the command you're passing in. See [here](https://docs.microsoft.com/en-us/powershell/scripting/components/console/powershell.exe-command-line-help?view=powershell-6#-command).

So, yeah, it's not really possible for `-File` or `-Command` to be order-agnostic; in general those two need to be the last in any command sequence, although apart from that you can put the other parameters in whichever order you like. 😄

**Comment by Groostav** [comment]
ah, so this is just yet another gotcha in shell scripting --though now that I think about it the C family of languages all have their own gotchas around `vararg` arguments, so I suppose I shouldn't be surprised to find them here too. 

Is another good practice is then to also write scripts that validate they dont get any data they don't expect? Then I would've seen an exception in something like the `param` block for my script, once I had it running.

Is there an option for something like that with `Param()` and its various annotations? In other words, is there an elegant way I can use the `Param` block to test if any extra arguments or options have been left on the command line for my script, and throw an exception in such a case?

Also, I'm no expert at reading complex usage documents, but this seems unfortunate:

```
> powershell.exe /?
PowerShell[.exe] [-PSConsoleFile <file> | -Version <version>]
    #...
    [-ConfigurationName <string>]
    [-File <filePath> <args>] [-ExecutionPolicy <ExecutionPolicy>]
    [-Command { - | <script-block> [-args <arg-array>]
    #...
```

If you write `-File path arg1 arg2 -ExecutionPolicy Bypass`, as is kind've implied by the documentation, then `-ExecutionPolicy` and `Bypass` simply become _arg3_ and _arg4_, correct? 

Anyways, thanks for the clarification, I'm suprised at long I've been using powershell for and not realized some of these ambiguities.

**Comment by vexx32** [comment]
In my experience, specifying `[CmdletBinding()]` will explicitly forbid any additional arguments from being supplied, _unless_ a declared parameter has the `[Parameter(ValueFromRemainingArguments)]` attribute declared.

Agreed that the display is confusing as heck, and yes your inference is correct.
