### ISSUE TITLE
about_Sort_Object: Mixed Ascending/Descending Example

### ISSUE THREAD

**Issue by JediSQL** [PowerShell/PowerShell#8578]
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/sort-object?view=powershell-6

For the -Descending option there is this remark: "_To sort by some properties in ascending order and others in descending order, you must specify their property values by using a hash table._" An example of how to do that would be very helpful.

**Comment by vexx32** [comment]
This should also be in the https://github.com/PowerShell/PowerShell-Docs repo. 😄

**Comment by iSazonov** [comment]
Please move to PowerShell-Docs repo.
