### ISSUE TITLE
Automatic variable Input is empty once it has been accessed

### ISSUE THREAD

**Issue by nyanhp** [PowerShell/PowerShell#8584]
# Steps to reproduce

I was unable to find a related issue for my problem. To reproduce the behavior, simply use $Input more than once in a process block.

```powershell
function Test-PipelineInput
{
    process
    {
        Get-Item $Input
        Get-Item $_
        Get-Item $PSItem

        Write-Host "
        `$_ is $_
        `$PSItem is $PSItem
        `$Input is $Input
        "        
    }
}

'/' | Test-PipelineInput
```

# Expected behavior

I would expect that the value of $Input is preserved, as is the value of $_ (and its alias).

```none
    Directory:

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d--hs-        12/30/2018 12:22 PM                C:\
d--hs-        12/30/2018 12:22 PM                C:\
d--hs-        12/30/2018 12:22 PM                C:\

        $_ is /
        $PSItem is /
        $Input is /
```

# Actual behavior

In PowerShell Core 6.1 and 6.2-preview.2 as well as Windows PowerShell, $Input is cleared once it has been accessed in any way.

```none
    Directory:

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d--hs-        12/30/2018 12:22 PM                C:\
d--hs-        12/30/2018 12:22 PM                C:\
d--hs-        12/30/2018 12:22 PM                C:\

        $_ is /
        $PSItem is /
        $Input is
```

# Environment data

Tested with 5.1 and 6.1 as well.

```none
Name                           Value
----                           -----
PSVersion                      6.2.0-preview.2
PSEdition                      Core
GitCommitId                    6.2.0-preview.2-34-g6e523f21ebf6c6db02c6990481c737ccee693f8e
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
@BrucePay we may want to move this to the Docs repo, then, as the wording needs to make this difference more clear, it would seem. :smile:

**Comment by BrucePay** [comment]
@vexx32 Agreed.

**Comment by nyanhp** [comment]
Yes, there should be some documentation regarding this :) I was unable to find any helpful info in the code and as @vexx32 mentioned, the help topic did not really offer definitive insight into this behavior.

**Comment by BrucePay** [comment]
@nyanhp Could you close this issue and open a new issue in the docs repo? Thanks!

**Comment by nyanhp** [comment]
Thanks! There we go: https://github.com/PowerShell/PowerShell-Docs/issues/3571
