### ISSUE TITLE
Ctrl+C blocked and/or swallowed by the debugger

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell#8586]
# Steps to reproduce

```powershell
function foo {}
Set-PSBreakpoint -Command foo
foo
```

1. The debugger will break.
1. Run some long-running task that you'll have time to Ctrl+C, but that will finish in a reasonable time. I used `ls ~\Downloads`.
1. Ctrl+C (once) before the command finishes. It won't work.
1. When the command finishes, observe that the debugger is no longer attached. 

# Expected behavior

It's expected that the command being executed from within the debugger will be killed, but that the debugger will not be killed and remain attached.

# Actual behavior

The command doesn't halt execution, and the debugger is unattached at the end of its execution.

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0-preview.3
PSEdition                      Core
GitCommitId                    6.2.0-preview.3
OS                             Microsoft Windows 10.0.18301
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by RDIL** [comment]
Can confirm this.
