### ISSUE TITLE
Installing Powershell Core prevents Windows Powershell to be launched from the address bar of Windows Explorer

### ISSUE THREAD

**Issue by leoniDEV** [PowerShell/PowerShell#8588]
# Steps to reproduce
Install Powershell Core 6.2.0-preview.3 on a Windows Machine,
open an arbitraty folder in Windows Explorer and type powershell in the address bar
```powershell

```

# Expected behavior
run powershell with the pwd sets to the folder opened in Windows Explorer
![powershell](https://user-images.githubusercontent.com/11667486/50622300-64ff7c00-0f0c-11e9-8374-99dcedc870ba.gif)
```none

```

# Actual behavior
Open the $Home\Documents\Powershell folder in Windows Explorer
![pswh](https://user-images.githubusercontent.com/11667486/50622407-19999d80-0f0d-11e9-82a3-4a74e0ce67ca.gif)
```none

```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0-preview.3
PSEdition                      Core
GitCommitId                    6.2.0-preview.3
OS                             Microsoft Windows 10.0.18305
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by MaximoTrinidad** [comment]
@leoniDEV,

Just an FYI

If you type "pwsh", it work!  

If you type PowerShell, and you have a PowerShell folder name, then it goes to the PowerShell folder.
If you want to open a Windows PowerShell Console, then you'll need to type "PowerShell.exe".

I don't think is a bug as typing powershell won't open PowerShell Core.

:)

**Comment by leoniDEV** [comment]
The bug isn't that typing `powershell` in the address bar won't open Powershell Core, but to me the bug was that if Powershell Core is installed you can't run Windows Powershell typing `powershell` in the address bar of Windows Explorer.

Anyway this issue can be closed as now I know that need to add the .exe extension to run powershell

**Comment by RobLOlson** [comment]
Thanks for documenting these work-arounds.  Whether it's technically considered a bug or not, I'm kind of annoyed that installing PowerShell Core changed the default behavior of my OS......
