### ISSUE TITLE
Find the right layout for files

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#859]
We may want to reflect this layout in SD to make mapping trivial.

Few key points from the offline discussion:

1. We organize things so sources for one Module (i.e. .cs and .psd1) leave together
2. We want a flat structure for the most part, but not everywhere (i.e. SMA is too big to be a single flat folder).

**Comment by andschwa** [comment]
@vors can we close this now?

**Comment by vors** [comment]
Sure
