### ISSUE TITLE
Powershell 6.0.2

### ISSUE THREAD

**Issue by bersue** [PowerShell/PowerShell#8590]
Update-Help läuft auf die Fehlermeldung:
update-help : Failed to update Help for the module(s) 'WindowsUpdateProvider' with UI culture(s) {de-DE} : One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
At line:1 char:1
+ update-help
+ ~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
+ FullyQualifiedErrorId : UnknownErrorId,Microsoft.PowerShell.Commands.UpdateHelpCommand

**Comment by iSazonov** [comment]
@bersue Please use our issue template to report issue.
