### ISSUE TITLE
It should be possible to disable writing BOMs in new files created with `Out-File` and `>`

### ISSUE THREAD

**Issue by radix** [PowerShell/PowerShell#8592]
# Summary of the new feature/enhancement

It should be possible to configure PowerShell to not write a BOM when writing files with redirection, such as with `echo foo > myfile.txt`.

# Proposed technical implementation details (optional)

I suggest adding a `-NoBOM` parameter to Out-File, which disables writing the BOM.

Then I suppose it could be configured as the default like so:

```powershell
$PSDefaultParameterValues['Out-File:NoBOM'] = $true
```

**Comment by vexx32** [comment]
Strictly speaking this is the purview of the encoding utilised; you can specify either `-Encoding UTF8` or `-Encoding UTF8BOM` with `Out-File` in PS Core to determine whether you'd like the byte order mark or not. 😄

**Comment by radix** [comment]
@vexx32 It writes the BOM even when "UTF8" is specified as the encoding:

```powershell
PS C:\Users\radix> out-file MyCoolFile.txt -Encoding UTF8 -InputObject "hello, world!"
PS C:\Users\radix> python -c "print repr(open('MyCoolFile.txt').read())"
'\xef\xbb\xbfhello, world!\n'
```

**Comment by vexx32** [comment]
Which version of PS are you using? It behaves correctly in PS Core 6.1.0, at least. 🙂

**Comment by radix** [comment]
I guess I'm on 5.1.0 :( I'm using the version included in my Windows 10.

```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17134  407
```

Thanks for confirming this works now. I guess I'll have to figure out how to upgrade!

**Comment by vexx32** [comment]
You can download the MSI installer from here for either the latest preview or stable versions here:
https://github.com/PowerShell/PowerShell/releases

PS Core installs side-by-side with Windows PowerShell. 🙂
