### ISSUE TITLE
`switch` statement: deprecate the -exact option

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#8599]
Note: By _deprecation_ I mean "soft" deprecation, i.e., deprecation _without (eventual) removal_, in the interest of backward compatibility.

# Summary of the new feature/enhancement

The `-exact` option is _never needed_ and was presumably only ever implemented for symmetry with `-wildcard` and `-regex`, as a way to explicitly opt into the _default_ behavior, which is essentially: implied `-eq` comparison, which with strings means case-insensitive comparison in full (though you can opt into case-sensitivity by adding `-casesensitive`).

Given that I think most users expect this behavior by default anyway, `-exact` only raises unnecessary questions, not least due to its name, given that it can be combined with `-casesensitive` (as an aside: to contrast it with `-wildcard` and `-regex`, `-literal` would have made more sense as a name).

# Proposed technical implementation details (optional)

* Remove `-exact` from tab completion, if possible.

* Mention `-exact` in the docs as never being necessary and existing primarily for backward compatibility.

**Comment by BrucePay** [comment]
@mklement0 
>The -exact option is never needed and was presumably only ever implemented for symmetry with -wildcard and -regex, as a way to *explicitly opt into the default behavior*,

Explicitly indicating intent is a useful thing.

**Comment by mklement0** [comment]
@BrucePay:

> Explicitly indicating intent is a useful thing.

Sometimes, yes, but not categorically:

Given that:

* the option's name is confusing, as explained.
* that the _default_ behavior is sensible and is what users are likely to expect, along with the need to _opt into_ variant behaviors (`-wildcard`, `-regex`, `-casesensitive`).

I'd say we're better off without `-exact` overall.

Note that there's no `-caseINsensitive` either, for instance, and I don't think anyone wishes there were.

**Comment by vexx32** [comment]
Aye, the default behaviour is essentially what users coming from other languages will more or less expect.

Having a switch named -Exact makes it sound like it's more specific than the default, which it isn't.

**Comment by BrucePay** [comment]
@mklement0 
> the option's name is confusing, as explained.

I supposed we could have named them `-ExactMatch`, `-WildCardMatch`, `-RegularExpressionMatch`. That's pretty clear. On the other hand, since _matching_ is the whole point of the switch statement, it seems a bit redundant. 

> into variant behaviors (-wildcard, -regex, -casesensitive).

-CaseSensitive is not, in itself, a variant behaviour. It's a modifier for wildcard/regex/exact e.g.
```powershell
    switch -CaseSensitive -Exact(Match) {
```

In general, _allowing_ script authors to strongly express intent is a pervasive theme in the design of PowerShell: long options, noun-verb command names, even language operators like `-ieq`, `-ceq`, `-eq`, etc. support this. And while the need for elastic syntax means that this can not be _required_ , it is absolutely encouraged for production scripting.

**Comment by mklement0** [comment]
> I supposed we could have named them `-ExactMatch`

The problem is the word _exact_ (a case-insensitive match is not an exact one); _literal_ would have been better, but I still think there's no need for this option altogether (see below).

> `-CaseSensitive` is not, in itself, a variant behaviour

Switching from case-insensitive to case-sensitive matching is a variant behavior too, just along a different dimension.

> even language operators like -ieq, -ceq, -eq, etc. support this. 

A `switch` statement without options can - and is likely to - be conceived of as a generalized `-eq` statement, with `-eq` being used to match the branch conditions.

As such, adding `-exact` would be akin to complementing the `-eq` operator with an `-exacteq` operator, which is both unnecessary and confusing.
