### ISSUE TITLE
[CI Tests] [Azure Pipelines] Rename spelling task 

### ISSUE THREAD

**Issue by RDIL** [PowerShell/PowerShell#8600]
Because of #8471 , we need to rename the `spelling` PipeLine as it is no longer just spelling, it now also checks to see if links works.  
@TravisEz13 said he would do it, but I figured I would open an issue so nobody forgets!

**Comment by TravisEz13** [comment]
Thanks

**Comment by TravisEz13** [comment]
I renamed the task to `PowerShell-CI-static-analysis` . We need to rename the YAML now.  @RDIL 	Would you mind submitting a PR just renaming it to something to match the new task and mentioning me in the PR?

**Comment by RDIL** [comment]
(can you assign me to this issue so I remember to fix this when I get home?) @TravisEz13

**Comment by TravisEz13** [comment]
I don't think you broke anything.  I'm looking at it.  But I assigned it to both of us.

**Comment by RDIL** [comment]
👍
