### ISSUE TITLE
ConvertTo-Json adds extra spaces on PS6

### ISSUE THREAD

**Issue by Stephanevg** [PowerShell/PowerShell#8604]
# Steps to reproduce

```powershell
# on powershell 5.1

<#
Name                           Value
----                           -----
PSVersion                      5.1.16299.785
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.785
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
#>

$a = @{"Woop"="wap"}
$a | convertTo-Json
```

```powershell
# on powershell 6

<#
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
#>

$a = @{"Woop"="wap"}
$a | convertTo-Json
```

# Expected behavior

I would expect the strings to be 100% identical across versions and platforms.

# Actual behavior

If you take a close look at the two generated Json strings, one would notice that the PS6 one has a few empty spaces less then the same output from PS5.1

looking closer at it using an online Diff checker, it will show the extra spaces:
(Ps6.0 version is on the left side, ps5.1 on the right)
![image](https://user-images.githubusercontent.com/6302961/50813102-92399900-1315-11e9-807d-f1d0556a9d52.png)

# Environment data
See Above

**Comment by markekraus** [comment]
JSON is a serialization that is indifferent white space. The goal of `ConvertTo-Json` is not to produce strings, but to produce JSON. In the transition to v6, the settings were changes to use a the format that it does as it is more widely accepted by linting tools. https://github.com/PowerShell/PowerShell/pull/2787/files

This is "by design" and is not a breaking change.

**Comment by Stephanevg** [comment]
Hi, 
Thanks for your ffast answer @markekraus 
Although I understand this is not a breaking change, as it was changed to respect the common standard, this is still a difference in behaviour between PS5.1 and PS6. Nothing really important, up until you are comparing strings that have been generated using ConvertTo-Json. Only then it will matter.

## Solution
I just would like to share what fixed my issue, just in case, somebody outthere faces the same problem in the future:
The first thing I did, is to use the switch "-Compress" delivered with ConvertTo-Json to compress the json, and remove all the formating stuff. This mostly fixed all the issues I had, except for cases where I had empty arrays. Where on PS6 I got ```[]``` but on ps 5.1 ```[ ]``` (See the extra space in ps5.1?)
For that I used the following function

```powershell
# Thanks to Jakob Jares for the tip!
function Clear-WhiteSpace ($Text) {
    "$($Text -replace "(`t|`n|`r)"," " -replace "\s+"," ")".Trim()
}
```
Cheers

**Comment by markekraus** [comment]
> Nothing really important, up until you are comparing strings that have been generated using ConvertTo-Json.

As I mentioned, the goal of `ConvertTo-Json` is not to create strings. It creates a JSON object. It is not recommended to try and perform string operations on JSON.

**Comment by Stephanevg** [comment]
>As I mentioned, the goal of ConvertTo-Json is not to create strings. It creates a JSON object.

Yes I get that. But I am constructing a Javascript query, which **must** contain the json data.
I had pester tests comparing the results to a predefined string, just to be sure, that the code is complete (As I cannot test Javascript in Pester - Or at least, I couldn't find how).
these tests were passing on Windows(5.1), but **not** on Linux (Ps6).

> It is not recommended to try and perform string operations on JSON.

Yep, I get that too, but I had no other choice, as the ```convertto-Json``` was acting differently depending on the PS version. (As I explained above ```-Compress``` was not sufficent because empty arrays would have had an extra space on PS6).

I am not saying this is a bug or so. Just want to make potential 'googlers' aware of how I resolved this problem.

**Comment by RafaMarquesLearn** [comment]
> Hi,
> Thanks for your fast answer @markekraus
> Although I understand this is not a breaking change, as it was changed to respect the common standard, this is still a difference in behaviour between PS5.1 and PS6. Nothing really important, up until you are comparing strings that have been generated using ConvertTo-Json. Only then it will matter.
> 
> ## Solution
> I just would like to share what fixed my issue, just in case, somebody outthere faces the same problem in the future:
> The first thing I did, is to use the switch "-Compress" delivered with ConvertTo-Json to compress the json, and remove all the formating stuff. This mostly fixed all the issues I had, except for cases where I had empty arrays. Where on PS6 I got `[]` but on ps 5.1 `[ ]` (See the extra space in ps5.1?)
> For that I used the following function
> 
> ```powershell
> # Thanks to Jakob Jares for the tip!
> function Clear-WhiteSpace ($Text) {
>     "$($Text -replace "(`t|`n|`r)"," " -replace "\s+"," ")".Trim()
> }
> ```
> 
> Cheers

Thanks, this helped me!!

**Comment by atlantamatt** [comment]
> > Nothing really important, up until you are comparing strings that have been generated using ConvertTo-Json.
> 
> As I mentioned, the goal of `ConvertTo-Json` is not to create strings. It creates a JSON object. It is not recommended to try and perform string operations on JSON.

This tool is absolutely not "indifferent to whitespace" otherwise -Compress would be the default, not an option.

Literally, the first line in the Microsoft documentation for ConvertTo-Json is : "Converts an object to a JSON-formatted string."

Imposing a human-readable stylistic change between versions should be frowned upon since different machines/applications treat whitespace differently, ie VSCode, Visual Studio, Git, WinMerge. If you do impose stylistic changes to match some unnamed, unrelated application then allow the user the ability to continue using the old style, or specify the style they want

**Comment by iliahz** [comment]
https://jonathancrozier.com/blog/formatting-json-with-proper-indentation-using-powershell
