### ISSUE TITLE
Get-Help misrepresents non-advanced functions as advanced ones when comment-based help is present

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#8605]
# Steps to reproduce

```powershell
# Define a simple (non-advanced) function with comment-based help.
function foo {
# .SYNOPSIS
# Hiya
}

Get-Help foo
```

Similarly, if you use `Get-Help` with `-Full` or `-Detailed`, the following inapplicable paragraph is shown:

```none
PARAMETERS
    <CommonParameters>
        This cmdlet supports the common parameters: Verbose, Debug,
        ErrorAction, ErrorVariable, WarningAction, WarningVariable,
        OutBuffer, PipelineVariable, and OutVariable. For more information, see
        about_CommonParameters (https://go.microsoft.com/fwlink/?LinkID=113216).
```

# Expected behavior

```none
...
SYNTAX
    foo 
...
```

# Actual behavior

```none
...
SYNTAX
    foo [<CommonParameters>]
...
```

That is, the syntax diagram mistakenly suggests that `foo` is an advanced function.

# Environment data

```none
PowerShell Core 7.1.0-preview.5   # originally reported for: PowerShell Core v6.2.0-preview.3 
```

**Comment by ChrSchultz** [comment]
mklement0, my output of the function above in PowerShell Core v6.2.0 -preview.rc1 Windows 10 64-bit is:
´´
C:\Users\ic-sc> get-help foo

NAME
    foo

SYNTAX
    foo


ALIASES
    None


REMARKS
    None
``
I think thats fixed , update to rc.1

**Comment by mklement0** [comment]
Interesting, @ChrSchultz, I still see the problem in RC1, both on Windows 10 (64-bit; Version 1809, OS Build: 17763.379) and on macOS 10.14.3
