### ISSUE TITLE
`Join-String -InputObject 1,2,3` result is not equal to `1,2,3 | Join-String` result.

### ISSUE THREAD

**Issue by sethvs** [PowerShell/PowerShell#8610]
`Join-String -InputObject 1,2,3` result is not equal to `1,2,3 | Join-String` result.

# Steps to reproduce

```powershell
1,2,3 | Join-String
Join-String -InputObject 1,2,3
```

# Expected behavior

```none
123
123
```

# Actual behavior

```none
123
1 2 3
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0-preview.3
PSEdition                      Core
GitCommitId                    6.2.0-preview.3
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
Cool, thanks for fixing this; for the general issue with scalar `-InputObject` parameters, see #4242.

**Comment by sethvs** [comment]
@mklement0 Thanks. I'll leave the decision to maintainers.

**Comment by BrucePay** [comment]
Note that this is a breaking change.

**Comment by mklement0** [comment]
@BrucePay: It's highly likely that this is a  [Bucket 3: Unlikely Grey Area](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md#bucket-3-unlikely-grey-area) change:

```powershell
Join-String -InputObject 1,2,3
```

is currently effectively the same as:

```
"$(1,2,3)"
```

That is, the only operation being performed is the stringification of the input array (implicit joining with `$OFS`) _during parameter binding_ - `Join-String` itself is then a no-op, given that it then receives a _single_ input string; in other words: there's nothing left to join.

**Comment by sethvs** [comment]
@BrucePay The `Join-String` cmdlet has been released in preview.3 only and not in official releases.

**Comment by mklement0** [comment]
Good point, @sethvs.

---

As for _how_ to implement the proposed change:
@PetSerAl has since shown that switching to `PSObject[]` in an effort to treat `-InputObject` _arguments_ the same as `PSObject`-based `-InputObject` _pipeline_ input doesn't work in all cases: https://github.com/PowerShell/PowerShell/issues/4242#issuecomment-453753539

---

As for *whether* to implement the change at all:

We need to decide whether we even want to support `-InputObject` argument / pipeline equivalence for collection-enumerating cmdlets such as `Join-String` (my vote: yes), or whether we should treat `-InputObject` simply as an _auxiliary_ parameter that facilitates _pipeline input_ but is not to be used _directly_ with _arguments_ - see https://github.com/PowerShell/PowerShell/issues/4242#issuecomment-453831509

If the latter, `Join-String -InputObject 1,2,3` would then by design not be (meaningfully) supported, and there'd be nothing to change.

**Comment by vexx32** [comment]
🤔 

I think that from a semantic perspective, having `-InputObject` be primarily an implementation detail of standard pipeline support isn't necessarily _wrong_ per se? I think it would be better if there were some way via attribute or some such to denote a parameter as `Pipeline-Only` such that it wouldn't appear in tab completions or be usable for input directly; in this way we could avoid some of the confusion perhaps?

But whatever option ultimately wins out here... we should also consider that while there is a _mostly_ consistent implementation amongst standard cmdlets, it's not completely consistent, which is a problem: without a consistent and clear example to follow, third-party cmdlets tend to do pick and choose they feel is most appropriate more often, which seems to lead to less consistent and practices in the wider PowerShell community in this regard.

As a result, I think that opting to change anything here will only have a meaningful impact if we can decide on and then actually enact a consistent implementation across all the standard PowerShell cmdlets.

**Comment by daxian-dbw** [comment]
> I think it would be better if there were some way via attribute or some such to denote a parameter as Pipeline-Only such that it wouldn't appear in tab completions or be usable for input directly

Just some thoughts: It's useful to use `-InputObject` directly in case that you already have the collection object handy and want to avoid the unnecessary pipeline binding overhead.
In the case of calling a cmdlet in C#, disallowing the use of `-InputObject` directly would mean that you have to pass in the collection object by `powershell.Invoke(myCollection)`

**Comment by mklement0** [comment]
@daxian-dbw: The performance argument is also mentioned in https://github.com/PowerShell/PowerShell/issues/4242#issuecomment-453831509 and, at the risk of talking myself hoarse, can we please continue the conversation there? (I also encourage you to clarify your C# argument - _there_.)
