### ISSUE TITLE
Bug in FormatMessageFromModule()

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#8612]
FormatMessageFromModule() from CommonUtils.cs is not used and has a bug (newline == 2 only on Windows) - remove the _public_ method or fix?
https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Diagnostics/CommonUtils.cs#L124-L128

/cc @daxian-dbw

**Comment by maw136** [comment]
Not really a bug since there is P/Invoke code (FormatMessage) earlier which can't work outside of Windows.

**Comment by iSazonov** [comment]
Currently we added CI Codacy so we'll see such issues and fix them.
