### ISSUE TITLE
Services Name and DisplayName

### ISSUE THREAD

**Issue by cpagelsen** [PowerShell/PowerShell#8619]
A colon is detected as Invalid Data in both the Name and Display Name of a Service.  However, it is valid.  I have created services with such names on 2008 R2 and 2012 R2 servers.  This prevents the use of all Service cmdlets where Service names contain  a ":".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b49bd8c6-edea-b763-7040-ea6da7bba0e7
* Version Independent ID: 5d352766-b39b-7740-5ce3-ec092cdfd1b9
* Content: [Start-Service (Microsoft.PowerShell.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/start-service?view=powershell-6#feedback)
* Content Source: [reference/6/Microsoft.PowerShell.Management/Start-Service.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Start-Service.md)
* Product: **powershell**
* GitHub Login: @daxian-dbw
* Microsoft Alias: **dongbow**

**Comment by SteveL-MSFT** [comment]
@joeyaiello tested this and it works with quotes as long as the name is in quotes otherwise a colon would be interpreted as a PS Drive

**Comment by cpagelsen** [comment]
I have simplified the PowerShell script to reproduce the problem. Using quotes didn’t work either

 

#simple powershell test

[CmdletBinding()]

Param

    ([Parameter(Mandatory=$true)][string]$computerName

    )

$s = """PMBService:1"""

#$s = "PMBService:1"

$Cred = Get-Credential

Invoke-Command -ComputerName $computerName -Credential $Cred -ScriptBlock {Start-Service -Name $s -PassThru}

**Comment by cpagelsen** [comment]
Could this be a problem because I’m on PowerShell 5?

**Comment by BrucePay** [comment]
Hi @cpagelsen 

The code in your repro has a problem.  As written, `$s` will be a new variable in the remote session that defaults to `$null`. You need to add the `$using:` scope qualifier to cause the local variable to be sent to the remote side:

```powershell
Invoke-Command -ComputerName $computerName -Credential $Cred -ScriptBlock {Start-Service -Name $using:s -PassThru}
```

Can you try this out and let us know what happens? Thanks.

**Comment by cpagelsen** [comment]
Thank you.  It does  work and solves my problem.  I am a bit of a novice with PowerShell so your help is much appreciated.  Sorry for being a bother.

 

Charles

**Comment by dickyw71** [comment]
Hi, I am a new triaging issues on the PowerShell repo.

I see that this issue:
- hasn't been updated since 11-Jan-2019
- has a proven fix/answer by @BrucePay 
- is resolved for @cpagelsen, who opened the issue

Based on this, I suggest that this issue should be considered for closure and labelled `Resolution-By Design`.

**Comment by vexx32** [comment]
Thanks, @dickyw71! 🙂
