### ISSUE TITLE
Join-String does not produce the same result as -join

### ISSUE THREAD

**Issue by PetSerAl** [PowerShell/PowerShell#8632]
# Steps to reproduce

```powershell
class C: System.Collections.IEnumerable {
    [string] ToString() { return 'Correct' }
    [System.Collections.IEnumerator] GetEnumerator() { return ('Not', 'Correct').GetEnumerator() }
}
[C]::new(), [C]::new(), [C]::new() -join ', '
[C]::new(), [C]::new(), [C]::new() | Join-String -Separator ', '
```

# Expected behavior

```none
Correct, Correct, Correct
Correct, Correct, Correct
```

# Actual behavior

```none
Correct, Correct, Correct
Not Correct, Not Correct, Not Correct
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0-preview.3
PSEdition                      Core
GitCommitId                    6.2.0-preview.3-104-ge399b06cd23a8d9a7df9be5ed329471ba5b8eb82
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.2.0-preview.3}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by PetSerAl** [comment]
@vexx32 

>By the time the cmdlet receives input, the `GetEnumerator()` has *already been called* by the pipeline logic.

Any evidence to support this claim?

```powershell
function My-Join-String { @($input) -join ', ' }
[C]::new(), [C]::new(), [C]::new() | My-Join-String
```

**Comment by vexx32** [comment]
@PatSerAl Ah, I see! Okay, I misunderstood the original point.

Looks like it's enumerating each pipeline item, likely in an attempt to make pipeline input behave the same as `Join-String -InputObject ([C]::new(), [C]::new(), [C]::new())`

@mklement0 and I have discussed this a bit and have a code pattern that could help rectify it outlined in #4242 as you've seen.

**Comment by PetSerAl** [comment]
@vexx32 If it enumerating each pipeline item, the it should produce `Not, Correct, Not, Correct, Not, Correct` instead of `Not Correct, Not Correct, Not Correct`.

**Comment by vexx32** [comment]
Not quite. It calls the enumerator of your object to enumerate it, and receives back a two element array for each item. It doesn't then enumerate each of those arrays, that would be an extra level of enumeration. 🙂

**Comment by PetSerAl** [comment]
That is the problem. `Join-String` should not do `[C] -> [Array] -> [String]` instead of `[C] -> [String]`.

**Comment by iSazonov** [comment]
Are other cmdlets affected by this?

**Comment by vexx32** [comment]
I don't think a lot of cmdlets will be. Most cmdlets implement `-InputObject` strictly for pipeline use, so they can make some generally safe assumptions.

There may be some, but I don't know of any affected in the same way as this one is... Yet :smile:
