### ISSUE TITLE
Performance problem: `Get-ChildItem -Recurse -Include *` / `-Path *` is significantly slower than `Get-ChildItem -Recurse | Where-Object Name -like *` on Windows

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#8662]
Note: `-Filter` is noticeably faster and should always be the first choice, but it cannot always be substituted for `-Include`.

Using a wildcard with `-Path` is even slightly slower than `-Include`.

# Steps to reproduce

Run the following from directory that is the root of a sizable tree, with a warmed-up file cache.

```powershell
(Measure-Command { Get-ChildItem -Recurse -Include * }).TotalSeconds
(Measure-Command { Get-ChildItem -Recurse | Where-Object Name -Like * }).TotalSeconds
```

A single run may not produce representative timings; to conveniently average multiple runs (10 by default), use `Time-Command` from [this Gist](https://gist.github.com/mklement0/9e1f13978620b09ab2d15da5535d1b27) as follows:

```powershell
Time-Command { Get-ChildItem -Recurse -Include * }, { Get-ChildItem -Recurse | Where-Object Name -like * }
```

# Expected behavior

`Get-ChildItem -Recurse -Include *` should be faster  than `Get-ChildItem -Recurse | Where-Object Name -Like *`, given that only _one_ cmdlet is involved that performs filtering _internally_.

# Actual behavior

* On Windows, `Get-ChildItem -Recurse -Include *` is about _twice as slow_ in my tests.

* On macOS and Linux, the two commands perform about the same, which, however, is still surprising.

# Environment data

```none
PowerShell Core v6.2.0-preview.3 on macOS 10.14.2
PowerShell Core v6.2.0-preview.3 on Ubuntu 18.04.1 LTS
PowerShell Core v6.2.0-preview.3 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.471)
Windows PowerShell v5.1.17134.407 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.471)
```

**Comment by IISResetMe** [comment]
At a quick glance, it looks like `-{In,Ex}clude` and wildcards in `-Path` causes powershell to [re-traverse every single container](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/SessionStateContainer.cs#L1794) in the tree when recursively retrieving child items

**Comment by BinToss** [comment]
I wonder if this is caused by MsMpEng. While running reproduction commands (which still haven't finished), pwsh and msmpeng are showing 40-60 MB/s of I/O Read and Other activity.
