### ISSUE TITLE
PowerShell SDK 6.1.2 won't install in PSCore 6.1.2

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#8672]
I'm not sure what I'm missing here.  I can find the package but won't install.

# Steps to reproduce
1. Find the package
```powershell
Find-package -Name Microsoft.PowerShell.SDK
```
2. Install the package:
```powershell
Install-package Microsoft.PowerShell.SDK
```
# Expected behavior
To install without any issues
```none

```

# Actual behavior
See cmdline error during installation:
```
PS [33] > Install-package Microsoft.PowerShell.SDK

The package(s) come(s) from a package source that is not marked as trusted.
Are you sure you want to install software from 'Nuget'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
Install-package : Unable to find dependent package(s) (Microsoft.NETCore)
At line:1 char:1
+ Install-package Microsoft.PowerShell.SDK
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Microsoft.NETCore:String) [Install-Package], Exception
+ FullyQualifiedErrorId : UnableToFindDependencyPackage,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

PS [45] >
```

# Environment data

```none
PS [45] > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.2
PSEdition                      Core
GitCommitId                    6.1.2
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


PS [60] >
```
![pscoresdkerr_01_2019-01-17_9-36-29](https://user-images.githubusercontent.com/19892435/51325665-6d42d580-1a3b-11e9-8257-dc6ea17e2791.jpg)

**Comment by SteveL-MSFT** [comment]
This seems to be more of a question for PackageManagement module than PSCore6.  cc @edyoung

**Comment by MaximoTrinidad** [comment]
@SteveL-MSFT 

So! I this issue a long time ago and it still happening with version 6.2.0.
I did send an email to the owner via the PowerShell Gallery with no response.

What's the best way to install the latest PowerShell SDK if the Gallery won't work?

:)

![PSCoreSDKerr_2019-04-08_18-02-59](https://user-images.githubusercontent.com/19892435/55759911-a1b9a280-5a28-11e9-88e5-17d64c17b935.jpg)

**Comment by SteveL-MSFT** [comment]
@MaximoTrinidad You need to open an issue here: https://github.com/OneGet/oneget

**Comment by MaximoTrinidad** [comment]
Thanks @SteveL-MSFT!

I will use the link to open the issue... the email to owner from PowerShell Gallery is (unfortunately) useless.
