### ISSUE TITLE
import-module on module that is Blocked gives poor error message

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#868]
Customer issue reported on Reddit.  Probably not common since PowerShellGet is now available.

Download PoshRSJob module from here: https://github.com/proxb/PoshRSJob/releases
Extract using the Windows Shell (not expand-archive as it doesn't preserve the blocked stream)
Ipmo PoshRSJob

Expected: error message saying that the files are blocked and can't be loaded due to policy and how to fix

Actual:
ipmo : Could not load file or assembly 'file:///C:\Users\slee\Downloads\PoshRSJob\bin\PoshRS.PowerShell.dll' or one of
its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
At line:1 char:1
- ipmo .\PoshRSJob.psd1
- ~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
  - FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by raghav710** [comment]
@SteveL-MSFT  Should this issue be closed? Is the requirement still there?

**Comment by SteveL-MSFT** [comment]
Just tried this with 6.0.1 and with default `remotesigned` it gives you a good error message.  If you set execution policy to `unrestricted`, `import-module` reports that the script is not trusted and prompts.  Closing as the original issue no longer repros.
