### ISSUE TITLE
[docs] [code] AppVeyor/Travis CI references exist

### ISSUE THREAD

**Issue by RDIL** [PowerShell/PowerShell#8686]
# Documentation Issue / Code issue  

If you use the search bar at the top of this page to type in `AppVeyor`, or `TravisCI`/ `travis ci`, you will get results.  I have been trying to mitigate these results with my PRs numbered #8685, #8669, and #8639.  The remaining results need to be removed.

**Comment by RDIL** [comment]
We are getting closer!  Only 15 references left.

**Comment by RDIL** [comment]
@iSazonov can you add `Issue-Docs` please

**Comment by iSazonov** [comment]
@RDIL We haven't such label.

**Comment by RDIL** [comment]
Oh huh

**Comment by TravisEz13** [comment]
code cleanup is close enough
