### ISSUE TITLE
Update AppImageThirdPartyNotices.txt

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#8689]
Update `assets/AppImageThirdPartyNotices.txt`:
* Fix typo Copyrighy -> Copyright.
* Update year to 2019.

- [ ] Locate upstream licenses
  - icu4c? https://github.com/unicode-org/icu/blob/master/icu4c/LICENSE

**Comment by xtqqczze** [comment]
See also: #8646

**Comment by xtqqczze** [comment]
@dabutvin

**Comment by RDIL** [comment]
@xtqqczze see #9100

**Comment by xtqqczze** [comment]
File `assets/AppImageThirdPartyNotices.txt` removed in #9100.
