### ISSUE TITLE
Throw 'Could not load file or assembly' exception when using package System.Management.Automation in C# project (target net framework)

### ISSUE THREAD

**Issue by xycui** [PowerShell/PowerShell#8698]
# Steps to reproduce
(Please re-open [issue#7675](https://github.com/PowerShell/PowerShell/issues/7675))
1. Create new console project with VS 2017 or ```dotnet new console```
2. Edit csproj file to change to change the ```TargetFramework``` to ```net461``` even ```net471```.  netcoreapp is working. 
3. Add ```RuntimeIdentifier``` (2 different types of exception will be thrown)
```xml
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
```
4. Debug the code in main like below
```
namespace test
{
    using System.Management.Automation;

    internal class Program
    {
        private static void Main(string[] args)
        {
            PowerShell ps = PowerShell.Create();
            Console.ReadKey();
        }

    }
}
```

# Expected behavior
The code could pass.

# Actual behavior
- If not add RuntimeIdentifier tag. csproj like this:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net471</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management.Automation" Version="6.1.2" />
  </ItemGroup>

</Project>
```
Throw exception: 
```
System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Management.Automation, Version=6.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'
```
![image](https://user-images.githubusercontent.com/2989428/51429080-f4fc3000-1c45-11e9-86c2-1330d20dd30b.png)

- if add the RuntimeIdentifier tag. csproj like this:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net471</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management.Automation" Version="6.1.2" />
  </ItemGroup>

</Project>
```
Throw exception:
```
System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.'
```
<img width="911" alt="untitled" src="https://user-images.githubusercontent.com/2989428/51429001-11e43380-1c45-11e9-9213-6c0f8940fe0a.png">

# Environment data
OS: Windows 10
Visual studio:  Visual studio 2017 5.9.5

# My analyze & questions for your reference
I check the nuget package ```System.Management.Automation``` with NuGet package Explore     
![image](https://user-images.githubusercontent.com/2989428/51429019-41933b80-1c45-11e9-8afb-9bf9e423f155.png)     
Here are the problems: 
1. All the libs files are in ref/runtimes folder instead of lib folder. Maybe it is fine. **But how to deal with the Any CPU case?** Repro step3 is added after I checked the nuget package. That is a real Any CPU case.
2. Even if the ```RuntimeIdentifier``` is assigned. We can see from the screen shot that: the System.Runtime 4.2.1.0 is in **referenced assemblies** of the System.Management.Automation.dll(double click the file in Nuget Package Explorer). Maybe most of the **referenced assemblies**(dependencies) are in the Netframework binaries. But when we add the System.Runtime reference manualy we could see: The version of it is **4.1.2.0**.
![image](https://user-images.githubusercontent.com/2989428/51429555-7e156600-1c4a-11e9-816d-0feba26aca47.png)
3. System.Runtime is not the only dependency with the issue. We could add binding redirect to force redirect version of this dependency. (I don't think it is a good solution).  You will still see the exception, but with another dll name.

**Comment by xycui** [comment]
> Please see comment in #4669.

I also check the package of Microsoft.PowerShell.SDK. I think the package has the similar issue which I have mentioned in the origin post. Please take a look at section:
> My analyze & questions for your reference
![image](https://user-images.githubusercontent.com/2989428/51466223-a4e7af80-1da4-11e9-85ff-9ec64d31db98.png)

**Comment by bergmeister** [comment]
@xycui The problem is that you are building against full .net, you'd have to use .net core or .net standard instead
What are you trying to achieve on a high level? the SMA package is just for referencing the API's, it does not do anything by itself. Do you want to host PowerShell instead and are you clear on the difference between PowerShell v5 (also known as Windows PowerShell) vs v6 (PowerShell Core, which this repo is about)? From a .Net app, I would only expect that referencing the Windows PowerShell NuGet packages work.

**Comment by SteveL-MSFT** [comment]
For hosting PowerShell, if you're specifically targeting the .Net Framework runtime, you should be using https://www.nuget.org/packages/Microsoft.PowerShell.5.ReferenceAssemblies/ which targets Windows PowerShell (built on .Net Framework).  Otherwise, Microsoft.PowerShell.SDK is specifically for PSCore6 which is targeting the .Net Core runtime.

**Comment by xycui** [comment]
@SteveL-MSFT Thanks for the reply. This is what I need.

**Comment by xycui** [comment]
@SteveL-MSFT Maybe the package (PowerShell.SDK and System.Management.Automation) could be package to netcore?  Just because net standard could also be used by net framework target? Or any doc for the case of net framework to use Microsoft.PowerShell.5.ReferenceAssemblies instead.

**Comment by adityapatwardhan** [comment]
https://github.com/PowerShell/PowerShell/issues/8721 is opened for changing the target framework for SDK nuget package to `netcoreapp2.1`
