### ISSUE TITLE
MIT license is not an EULA

### ISSUE THREAD

**Issue by mercuriete** [PowerShell/PowerShell#8704]
# Steps to reproduce

1. Download powershell MSI
2. Instale msi

# Expected behavior

I am not required to Accept license and I can click next.

# Actual behavior

There is a checkbox forcing me to Accept an opensource license

# Environment data

Windows 10 x64 1803

# how to fix It

1. Delete EULA checkbox 
2. Dont grey out Next button.

**Comment by RDIL** [comment]
Well they have to make sure you agree to the terms, this is on purpose and will likely not be changed.

**Comment by xtqqczze** [comment]
@RDIL Actually, @mercuriete is probably right, there is no need to agree to an open-source license like MIT to acquire a right to *use* the software. See this question on Stack Exchange to an explanation:
https://opensource.stackexchange.com/a/2867

**Comment by SteveL-MSFT** [comment]
cc @TravisEz13

**Comment by TravisEz13** [comment]
@mercuriete 	I have a PR outstanding.  The EULA dialog uses an RTF, and we wanted to eliminate the RTF generation.  After an internal review, it was decided that a link was sufficient.

**Comment by mercuriete** [comment]
@TravisEz13 
Thank you for your work 👍

**Comment by TravisEz13** [comment]
@mercuriete 	No problem.
