### ISSUE TITLE
Uninstall/disable windows powershell (bundled) and use Powershell core as default in Windows 10

### ISSUE THREAD

**Issue by sl1pkn07** [PowerShell/PowerShell#8705]
Hi

i want uninstall the bundled/permanent disable, with all bundled modules, Windows powershell (5.1), and use Powershell Core (latest) and set it as budled default powershell in my Windows 10 pro installation

How i can do this?

greetings

**Comment by vexx32** [comment]
PowerShell Core still has some items missing compared to Windows PowerShell, in any case. Certain tasks can't be accomplished in PS Core just yet, so retaining Windows PowerShell is still necessary. 

Additionally, I believe Windows PowerShell is used in many OS tasks behind the scenes, so I don't think it would be wise to try to remove it.

**Comment by iSazonov** [comment]
After moving to .Net Core 3.0, we will significantly increase the possibilities of PowerShell Core and can port most of cmdlets. Then we could consider replacing Windows PowerShell with PowerShell Core.

**Comment by kilasuit** [comment]
@iSazonov that doesn't answer the question though as the answer is
```
Currently you cannot remove Windows PowerShell v5.1 from your Windows machine but you can & should remove the version 2 engine
```
