### ISSUE TITLE
Powershell Versions

### ISSUE THREAD

**Issue by eronlewis** [PowerShell/PowerShell#8706]
In the documentation for Powershell commands, can it be listed which versions of powershell the command works with? EX. get-localgroupmember command only works in Powershell 5.1 and up. But you have to check on the left hand side where it says Powershell version to see if the command is compatible with a certain version. This could just be listed at the top of the documentation of each command.

**Comment by vexx32** [comment]
@eronlewis This would be lovely!

But I'd recommend filing this issue in the PowerShell/PowerShell-Docs repo, as that repo typically handles the help files. 😄

**Comment by eronlewis** [comment]
Can you send a link to that repo?

**Comment by kilasuit** [comment]
@eronlewis the URL is linked within the issue on github and auto shrinks it so you will need to view on Github not via your emails
