### ISSUE TITLE
Release 6.2.0-Preview.4

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PowerShell#8710]
# Release Process for v6.2.0-Preview.4

- [x] Create a private branch named `release-v6.x.x` in Azure Dev Ops repository.
   All release related changes should happen in this branch.
- [x] Run tests on all supported Linux distributions and publish results
- [x] Prepare packages
    - [x] Build release packages
    - [x] Sign the MSI packages and RPM package.
    - [x] Install and verify the packages.
    - [x] Trigger the docker staging builds (signing must be done.)
- [x]  Update documentation, and scripts.
    - [x] Update [CHANGELOG.md](../../CHANGELOG.md) with the finalized change log draft.
    - [x] Update other documents and scripts to use the new package names, links, and `metadata.json`.
- [x] Create NuGet packages and publish them to `powershell-core` feed.
- [x] Run release build to publish Linux packages to Microsoft YUM/APT repositories.
- [x] Create the release tag and push the tag to `PowerShell/PowerShell` repository.
- [x] Run release build to create the draft and publish the release in Github.
- [x] For preview releases,
  merge the release branch to Github `master` with a merge commit.
- [ ] For non-preview releases,
  make sure all changes are either already in master or have
- [ ] Delete the release branch.
- [x] Trigger the docker image release.
- [x] Test and publish NuGet packages on NuGet.org
- [x] Retain builds.

**Comment by iSazonov** [comment]
Can we close this?
