### ISSUE TITLE
PowerShell Windows Backup Commands

### ISSUE THREAD

**Issue by wanderleihuttel** [PowerShell/PowerShell#8717]
I would like to suggest that the Windows Backup PowerShell's commands to accept  a folder in the same disk in the hypervisor host as a target. Another software of Backup like Veeam is possible to do this. There's no sense require only a entire disk or only network share to do this.
It would be better accept any folder in the Hypervisror host as a target to save the backup.

Something like: New-WBBackupTarget -folder c:\some_folder_as_backup_destiny

Thanks

**Comment by iSazonov** [comment]
@wanderleihuttel The cmdlet is not in the repo. The repo is only for PowerShell Core. Please move your report to UserVoice site or report with Feedback tool from Windows 10.
