### ISSUE TITLE
Check in the .csproj files that are used to build reference assemblies for our SDK nuget packages

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#8721]
# Summary of the new feature/enhancement

Currently the `.csproj` files for build reference assemblies are generated on-the-fly (the content is kept in a resource.psd1 file as templates).
We need a way to update the version of nuget packages referenced by those `.csproj` files, and the proposal is to have the .csproj files checked in, and then we can use the DependBot to manage the version of nuget packages referenced by those .csproj files.

Also, the generated SDK nuget packages are currently declared as `netstandard2.0`. We should change it to `netcoreapp2.1` as the runtime libraries are `netcoreapp2.1` specific.

**Comment by iSazonov** [comment]
DependBot  already updates the csproj files?

**Comment by adityapatwardhan** [comment]
Yes we have enabled Dependabot to scan these.

**Comment by iSazonov** [comment]
Do we need a test for this (that we have actual versions)?
Also have Dependabot  a schedule? In the case we could grab repo in state before update.
