### ISSUE TITLE
Verbose output on function exported but isn't actually exported (nor intended to be exported) from script module

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#8740]
# Steps to reproduce

```powershell
New-ModuleManifest -Path ./noexport.psd1 -RootModule noexport.psm1 -FunctionsToExport @()
 "function test-notExported {}" > noexport.psm1
ipmo ./noexport.psd1 -verbose
```

# Expected behavior

```none
VERBOSE: Loading module from path '/Users/steve/test/Modules/noexport/noexport.psd1'.
VERBOSE: Loading module from path '/Users/steve/test/Modules/noexport/noexport.psm1'.
```

# Actual behavior

```none
VERBOSE: Loading module from path '/Users/steve/test/Modules/noexport/noexport.psd1'.
VERBOSE: Loading module from path '/Users/steve/test/Modules/noexport/noexport.psm1'.
VERBOSE: Exporting function 'test-notExported'.
```

Note that the function isn't actually exported, seems like the verbose message is in the wrong place in the code.

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0-preview.3
PSEdition                      Core
GitCommitId                    6.2.0-preview.3
OS                             Darwin 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
Note that this came up as importing Az module with -Verbose shows a "Exporting function Test-DotNet" message.  However, after debugging this, it appears that for a function to be visible in the current session, it is "exported" and then "imported".  So you would see both verbose messages.  This seems by-design, but certainly a bit confusing.  Perhaps we could change the "Exporting function ..." message to something else to make it more obvious.  However, since I haven't seen lots of mention about this, putting it up-for-grabs on a suggestion.

**Comment by BrucePay** [comment]
@SteveL-MSFT This is by design. A command is exported from the `.psm1` module and then imported into the `.psd1` module which may, in turn, export it into the caller's session state. A `.psd1` file is essentially a "view" into the set of modules it aggregates. You get the two verbose messages so if something isn't exported, you can tell at what level the problem exists i.e. wasn't exported at the `.psm1` level or it wasn't exported at the `.psd1` level making, it easier to debug.

**Comment by vexx32** [comment]
@BrucePay @SteveL-MSFT perhaps the data can be useful, but what's actually happening needs to be clarified in the messages, as for anyone who doesn't know exactly how module leading works, that's extremely unclear. :smile:

Perhaps the first messages could say something more like "Discovered function X in X.psm1"

And the second more along the lines of "Discovered function/alias X in X.psd1, matched to X in X.psm1; exporting function to session."

Just something that gives enough clarity on where the importing routines are in the process. Ideally, verbose or debug messages should provide useful data that someone receiving can either act upon or have a good idea of who to call upon to look at it.

**Comment by SteveL-MSFT** [comment]
@vexx32 @BrucePay I'm not suggesting removing the existing verbose messages, but to make them more clear.  This was initially brought to my attention by a PowerShell MVP so if they were confused, I can only imagine non-MVP users being confused.  "Discovered" seems like a good description that a user can understand.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this, the messages come from functions being exported from the psm1 and if there is a psd1 there is a corresponding message being imported if it passes the filter `FunctionsToExport`.  Without understanding the internals, the current messages can be confusing to the user.  Having indentation would help with the nesting of the modules.  Recommendation is to change:

```
Exporting function `test`
```

to

```
Exporting function `test` from noexport.psm1
Not exporting function `test` from noexport.psm1 via noexport.psd1
```

**Comment by vexx32** [comment]
@pougetat are you still working on this? 🙂

**Comment by pougetat** [comment]
@vexx32 Hey, really sorry about this late response. I'm not working on this but if you want to work on it then I suggest looking at the PR that I closed. I learned some interesting things regarding the Import-Module cmdlet talking with @rjmholt

**Comment by rjmholt** [comment]
👋
