### ISSUE TITLE
Split-Path switches (-Leaf, -Parent, ...) do not work with -LiteralPath

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#8751]
Note: This affects all switches supported by `Split-Path`; combining them with the (implied) `-Path` works fine, but with `-LiteralPath` the parameter set cannot be resolved.

# Steps to reproduce

```powershell
Split-Path -LiteralPath foo/bar
Split-Path -Parent -LiteralPath foo/bar
Split-Path -Leaf -LiteralPath foo/bar
```

# Expected behavior

```none
foo
foo
bar
```

# Actual behavior

```none
foo
Parameter set cannot be resolved using the specified named parameters. ...
Parameter set cannot be resolved using the specified named parameters. ...
```

# Environment data

```none
PowerShell Core v6.2.0-preview.3 on macOS 10.14.2
PowerShell Core v6.2.0-preview.3 on Ubuntu 18.04.1 LTS
PowerShell Core v6.2.0-preview.3 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.471)
Windows PowerShell v5.1.17134.407 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.471)
```

**Comment by jagadeesh408** [comment]
I am also facing the same issue. Does this issues resolved?
If yes, can someone guide me on the solution

**Comment by mklement0** [comment]
It looks like the workaround is to simply use `-Path`, which - unlike with other cmdlets - doesn't actually treat its argument as a wildcard pattern in the case of `Split-Path`; in other words: `-Path` apparently acts the way that `-LiteralPath` normally does.

**Comment by jagadeesh408** [comment]
but i have a path like date\matter\movva, jagadeesh [jagadeesh408] and if i am using -path to get the leaf it is skipping the result due to the special characters [].
When i am using -literalpath for removing the leaf from the path it is working fine but not for getting the leaf

**Comment by mklement0** [comment]
I don't see this behavior (neither in WinPS 5.1, nor in 7.0, nor in 7.1.0-preview.3); do you get a different result, or am I missing something?

```powershell
PS> Split-Path -Path 'date\matter\movva, jagadeesh [jagadeesh408]' -Leaf
movva, jagadeesh [jagadeesh408]
```

**Comment by jagadeesh408** [comment]
I am using this way 
split-Path -path "'$($filepaths1[$i])'" -Leaf -Resolve 
where $filepaths1 is array of different paths and getting the error as below

split-Path : Cannot find drive. A drive with the name ''D' does not exist.

when i am using the command only with single quotes as below, it is not taking the variable also as string

split-Path -path '$($filepaths1[$i])' -Leaf -Resolve

**Comment by mklement0** [comment]
Do not enclose the file path in _embedded_ `'` characters - such a path won't be valid; also don't use `'` as the syntactic quotes, for the reasons you state (single-quoted strings are verbatim strings).

Just use the expression as-is, without quoting:

```
split-Path -path $filepaths1[$i] -Leaf -Resolve
```

If you want to use `-Resolve`, you actually _must_ use `-Path`, not `-LiteralPath` (which is strange in itself).

**Comment by jagadeesh408** [comment]
if i am using this 
split-Path -path $filepaths1[$i] -Leaf -Resolve

whenever $filepaths1 have a path like **date\matter\movva, jagadeesh [jagadeesh408]**  with special characters like [], it is skipping the result and providing me the null results

**Comment by mklement0** [comment]
If you want `date\matter\movva, jagadeesh [jagadeesh408]` to be treated as a _literal_ path, you mustn't use `-Resolve`, because `-Resolve` tells `Split-Path` to treat the path as a _wildcard expression_.

**Comment by mklement0** [comment]
(Correction to my earlier comment, which I removed.)

Since you're only looking for the leaf (file name) component, simply omit the `-Resolve` part, which prevents the unwanted interpretation of the input paths as wildcard expressions:

```powershell
split-Path -path $filepaths1[$i] -Leaf
```

That said, it does make sense to combine `-Resolve`  with `-LiteralPath` as well, namely to expand the - literal, but possibly relative - path to a _full path_ before extracting the part of interest.

For instance, you may want to use `-Qualifier` to extract the drive spec. from a literal path specified as a _relative_ path (without `-Resolve`, the relative path would be interpreted as-is, and therefore has no drive spec.); this is currently impossible:

```powershell
# !! Currently fails, due to the bug at hand.
Split-Path -LiteralPath file.txt -Resolve -Qualifier
```

**Comment by jagadeesh408** [comment]
Thanks, 
I will test it and update the thread if any issues
