### ISSUE TITLE
[BUG] `Out-Host` pollutes the terminal input line

### ISSUE THREAD

**Issue by GeeLaw** [PowerShell/PowerShell#8759]
# Steps to reproduce

First download this picture: [example.png](https://user-images.githubusercontent.com/4462444/51808943-d7cfee80-224f-11e9-80f9-3ead818d001b.png)

<img width="200" alt="example" src="https://user-images.githubusercontent.com/4462444/51808943-d7cfee80-224f-11e9-80f9-3ead818d001b.png">

Suppose you have put the file on your desktop on macOS. Open Terminal and `exec pwsh`, then execute the following command in PowerShell for macOS:

```powershell
$x = Get-Content '~/Desktop/example.png'
# Out-Host is written explicitly for expository purposes.
# For an interactive session, '| Out-Host' is the default and can be omitted.
$x | Out-Host
```

# Expected behavior

After executing `$x | Out-Host`, you get a bunch of non-sense in the Terminal window, and **ready to type your next line of command**.

# Actual behavior

After executing `$x | Out-Host`, you get a bunch of non-sense in the Terminal window, and **get strange strings for the next line of command**.

The `example.png` itself demonstrates this behavior. N.B. don't look at the content written to the Terminal, as I cannot find a "fixed point" -- most picture that are complex enough will produce garbage strings on the input line.

The Terminal window should be immune to `Out-Host`. Windows `conhost` is immune to it.

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.1.2
PSEdition                      Core
GitCommitId                    6.1.2
OS                             Darwin 18.2.0 Darwin Kernel Version 18.2.0: Th...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
I guess it is side effect because of escapes.

**Comment by GeeLaw** [comment]
I should rephrase

> The Terminal window should be immune to `Out-Host`.

As

> `Out-Host` should protect the Terminal window by appropriating handling the special characters that cause the problem.
