### ISSUE TITLE
[BUG] function name with quoted region $( causes subexpression

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PowerShell#8762]
# Steps to reproduce

```powershell
function :" any name$(hello$a)" {} # successful
function :" any name$(hello$a" {} # unsuccessful

```

I would not have expected that placing a $( inside a function name, inside quotes (which do not become part of the function name) would ~not~ require the closing ')'.

I suspect this is a larger problem in the tokenizer which is not separating out that it is just processing a function name and really thinks its working an expandable string.  I've witnessed and found the bug report regarding 'missing closing parenthesis in expandable strings even when in comments` (was a while back).

Any chance this would be changed in the future?  I have been experimenting with the VS Code's PowerShell Syntax to handle the complex function names PowerShell permits.  This would seem to be a non-breaking change if it only affected tokenizing during function names.

Or is there some unseen feature going on here?

# Environment data

Behavior is the same on 6.2.0pr3, 6.1.2, and before.

**Comment by GeeLaw** [comment]
I think I have problem in understanding this part:

> I would not have expected that placing a $( inside a function name, inside quotes (which do not become part of the function name) would not require the closing ')'.

This means:

> You expect putting '$(' inside a function name inside (double) quotes would require the closing ')'.

Then what you're seeing is just expected by you.

I wouldn't expect people naming functions with

```powershell
function :" any name$(hello$a)" {} # successful
function :" any name$(hello$a" {} # unsuccessful
```

But the first statement creates a function with name `: any name$(hello$a)` (literal), and can be invoked with `& ': any name$(hello$a)'`. The second statement doesn't go through now, but if we compare it to the previous example, that should create a function named `: any name$(hello$a` (literal).

Alternatively, you could create the latter function in imagination by

```powershell
function :' any name$(hello$a' { 1 | out-host }
# or, equivalently
function :" any name`$(hello`$a" { 1 | out-host }

& ': any name$(hello$a' # prints 1
```

That said, this is not to dismiss this issue. As seen in your first example, that string is **not** expandable. But those names are really weird! And interestingly, you must **begin** your function name without quotes.

**Comment by msftrncs** [comment]
sorry, @GeeLaw , I double negative'd that one...  :)

Correct, so far I cannot start a function name with a quoted text, as in to start it with a space, but if you use a scope modifier (ie `function local:" hello" {}`), your effective function name starts with a space, which you can access via `&` and a quoted string.  It is possible to make the first character of a function name a quote though, using a backtick.  ``` function `"hello`" {} ``` is function `"hello"`.

I am just trying to make the syntax highlighter work the same way the tokenizer does, as I never know what users might throw at it.
