### ISSUE TITLE
Syntax coloring PSVersion 5.1.17763.134

### ISSUE THREAD

**Issue by KennethVanMele** [PowerShell/PowerShell#8764]
Syntax coloring isn't working anymore in PSVersion 5.1.17763.134. `Set-PsReadlineOption` doesn't seem to be working correctly. If this already has a fix, please do tell me as I can't seem to find it.
$PSVersionTable and probable fix I found but it returns an error:
![windows powershell](https://user-images.githubusercontent.com/25532686/51831396-4cf40000-22f2-11e9-93af-13f035f35d45.png)

**Comment by vexx32** [comment]
This repo isn't really for Windows PowerShell issues, but nonetheless I'm sure we can help with something like this...

First thought is to probably sheck your version of PSReadLine with `gmo psreadline` and see if there's an update with `Update-Module PSReadLine` -- you may need to instead use `Install-Module PSReadLine -Force` if you've never updated it before.

**Comment by kilasuit** [comment]
this looks to be an issue with PSReadline and should really be raised on the PSReadline repo over at https://github.com/lzybkr/PSReadLine
