### ISSUE TITLE
Restart-Service and Get-Service process names passed by parameter in alphabetical order

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#8768]
Note: It may be too late to change this, in which case the behavior must be _documented_ (even with a fix it should be documented for _older_ versions).

---

If you use the _pipeline_ to provide multiple service names to `Restart-Service` and `Get-Service`, the input order of the names is honored, as expected.

By contrast, using the (implied) `-Name` parameter results in (update: what _appears to be_) _alphabetical ordering_, which is problematic, because the order in which services are started may matter.

# Steps to reproduce

On Windows:

```powershell
'wuauserv', 'AppReadiness'  | Restart-Service -WhatIf
'---'
Restart-Service 'wuauserv', 'AppReadiness'  -WhatIf  # should be equivalent

"`n===`n"

('wuauserv', 'AppReadiness'  | Get-Service).Name
'---'
(Get-Service 'wuauserv', 'AppReadiness' ).Name  # should be equivalent
```

That is, whether the names were provided via the pipeline or by parameter shouldn't make a difference.

# Expected behavior

```none
What if: Performing the operation "Restart-Service" on target "Windows Update (wuauserv)".
What if: Performing the operation "Restart-Service" on target "App Readiness (AppReadiness)".
---
What if: Performing the operation "Restart-Service" on target "Windows Update (wuauserv)".
What if: Performing the operation "Restart-Service" on target "App Readiness (AppReadiness)".

===

wuauserv
AppReadiness
---
wuauserv
AppReadiness
```

# Actual behavior

```none
What if: Performing the operation "Restart-Service" on target "Windows Update (wuauserv)".
What if: Performing the operation "Restart-Service" on target "App Readiness (AppReadiness)".
---
What if: Performing the operation "Restart-Service" on target "App Readiness (AppReadiness)".
What if: Performing the operation "Restart-Service" on target "Windows Update (wuauserv)".

===

wuauserv
AppReadiness
---
AppReadiness
wuauserv
```

Note how the commands that pass the names as an _argument_ result in the services getting processed in _alphabetical_ order.

# Environment data

```none
PowerShell Core v6.2.0-preview.3 on macOS 10.14.2
PowerShell Core v6.2.0-preview.3 on Ubuntu 18.04.1 LTS
PowerShell Core v6.2.0-preview.3 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.471)
Windows PowerShell v5.1.17134.407 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.471)
```

**Comment by iSazonov** [comment]
@mklement0 I don't found where we would sort. Seems we use List class in IncludeExcludeAdd()

**Comment by mklement0** [comment]
Intriguing, @iSazonov. I haven't looked at the code, but it is evident that _some_ change of order is taking place, and that's the problematic part (that it is _alphabetic_ ordering was a _guess_).
