### ISSUE TITLE
[BUG] out-file in 5.1 outputs UTF-16, then in 6.1 is UTF-8 for same file

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PowerShell#8782]
# Steps to reproduce

Start with no file 'test.txt' present.

```powershell
"hello!" | out-file -append test.txt # text pattern is important, even number of bytes!
more test.txt
```
The above command in Windows PowerShell 5.1, generates test.txt apparently in UTF-16 LE.

Then repeating the command in PowerShell Core 6.1 causes it to append the text to the end of the now existing file in UTF-8.

Now repeating the command in Windows PowerShell 5.1 causes it to append the text again as UTF-16.

Delete the file and reverse the order, and the results are simply reversed.

Same behavior if 6.2 PR3 is used.  This could be a result of #707.

# Expected behavior

The documentation states that the default encoding is UTF-16, for both 5.1 and 6, there is not a separate selection for 6.1 in the docs.

I ran a script I had written and been running in 5.1, on 6.1, and it uses the `out-file -append` command to write to a log, and the most recent log entry failed to be readable afterwards.

# Environment data

Windows 10 1809.

**Comment by vexx32** [comment]
The default was indeed changed since 5.1, likely related to the issue you mention. Docs should absolutely be updated, but this might need to be opened in the [PowerShell-Docs](https://github.com/MicrosoftDocs/PowerShell-Docs) repo instead.

**Comment by iSazonov** [comment]
Now we are default to UTF-8.
Please move the issue to PowerShell-Docs.
