### ISSUE TITLE
Remove unnecessary comma requirement in parameter attribute

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PowerShell#8790]
# Summary of the new feature/enhancement

A `Parameter()` attribute arguments should not require a comma when separated by newline's.  The comma's serve no purpose, unlike the comma's between each parameter.  While the assignment operator will allow line continuation, nothing else will, so each argument will end at the first newline that isn't in `()` anyway.

However, to be honest, I cannot think of anywhere else where comma's are not required for separating items enclosed in `()`.

```PowerShell
function `#a―― ($a
= 35,   # this is allowed
    [Parameter(Mandatory = $true,
        ValueFromPipeline
         =$true, # this isn't allowed anyway
        ValueFromPipelineByPropertyName = $true)]
    [AllowEmptyCollection() ]
    [AllowNull()]
    [AllowEmptyString()]
    [object]$PropertyList
    ) {}
```

without comma's:
```PowerShell
function `#a―― ($a = 35, 
    [Parameter(Mandatory = $true
        ValueFromPipeline = $true
        ValueFromPipelineByPropertyName = $true)]
    [AllowEmptyCollection() ]
    [AllowNull()]
    [AllowEmptyString()]
    [object]$PropertyList
    ) {}
```

**Comment by iSazonov** [comment]
I guess that it is parsed as a parameter list and will affect function and method calls.

**Comment by vexx32** [comment]
Hmm. Possibly. But the AST for an attribute declaration is very much distinct from a normal method call. It probably isn't impossible to have them parsed differently, although I do not know if it is necessarily something we ought to do.

**Comment by iSazonov** [comment]
@lzybkr Could you please comment?

**Comment by lzybkr** [comment]
First, this sounds like a bug to me - easy to fix and shouldn't preclude requiring commas between arguments:

```powershell
    [Parameter(ValueFromPipeline
         = $true)]
```

I can't think of a technical reason to require commas, but I'm not sure I like the aesthetics.

The syntax mimics the parameter list for method invocation in part because an attribute is calling a method - the constructor (followed by setting properties from the named argument values.)

**Comment by Jaykul** [comment]
I was just about to file a request asking for the commas _between parameters_ to be optional when I saw this. In other places where we explicitly _know_ we're dealing with a list, we do allow commas to be optional. The most obvious is arrays:

```PowerShell
$rhyme = @(
"one"
"two"
)
```

I don't see anything that would absolutely prevent making the commas **between** attribute properties optional -- to be clear, it wouldn't just affect `Parameter()` but all attributes -- but I'm not sure I think it's useful. They are weird and have many syntaxes anyway:

```PowerShell
[Parameter("Mandatory", "Hide", Mandatory, ValueFromPipeline, ValueFromPipelineByPropertyName)]
[object]$PropertyList
```
```PowerShell
[Parameter("Mandatory", 
           "Hide",
           Mandatory,
           ValueFromPipeline,
           ValueFromPipelineByPropertyName)]
[object]$PropertyList
```
```PowerShell
[Parameter("Mandatory", 
           ExperimentAction = "Hide",
           Mandatory = $false,
           ValueFromPipeline = $true,
           ValueFromPipelineByPropertyName)]
[object]$PropertyList
```

Adding the option to leave out the commas _if there's a newline_ seems fine (without having looked at the parser code), even if it's not hugely compelling...

```PowerShell
[Parameter("Mandatory"
           ExperimentAction = "Hide"
           Mandatory = $false
           ValueFromPipeline = $true
           ValueFromPipelineByPropertyName)]
[object]$PropertyList
```
