### ISSUE TITLE
Test faling 3+% of the time `XmlCommand DRT basic functionality Tests.Import-Clixml StopProcessing should `

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#8801]
XmlCommand DRT basic functionality Tests.Import-Clixml StopProcessing should 

https://powershell.visualstudio.com/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_build/results?buildId=11653

```
Error message
Expected 'Stopped', but got Completed.

Stack trace
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Utility\XMLCommand.Tests.ps1: line 77
77: 		$ps.InvocationStateInfo.State | Should -Be "Stopped
```

**Comment by iSazonov** [comment]
I'd remove tests for stopping. We would have to implement smarter hooks.

**Comment by TravisEz13** [comment]
@adityapatwardhan 	@JamesWTruher 	what do you think?
