### ISSUE TITLE
Remove cmdlets not available on all platforms from core

### ISSUE THREAD

**Issue by grandmasterv** [PowerShell/PowerShell#8802]
I'm new to Powershell so please be kind if this issue is being addressed elsewhere.  I looked and could not find any discussion about this problem.

I started using powershell core v6.1 stock install (no additional modules installed) to script across platforms (Win, Lin, Mac) as its being touted as a great solution for this. However shortly after I began to use it I quickly ran into a problem where one cmdlet is available on one platform (Win of course) but not another (Mac). I was shocked that this is the case as I would consider that behaviour NOT cross platform. I feel these cmdlets should be placed in a different module like the Windows Compatibility Module if they are to only be available on that platform.  There could be a separate compatibility module for each platform but they should not be included in the core if not supported across all platforms.

I found that this has caused problems on platforms like Linux in the issue here:
https://github.com/PowerShell/PowerShell/issues/3577

# Steps to reproduce

```powershell
Get-ComputerInfo
```

# Expected behavior

Works on Windows, Mac, and Linux

# Actual behavior

Only works on Windows.

```powershell
get-computerinfo
get-computerinfo : The term 'get-computerinfo' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ get-computerinfo
+ ~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (get-computerinfo:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.1.2
PSEdition                      Core
GitCommitId                    6.1.2
OS                             Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xn...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@grandmasterv Our goal is to port ALL the cmdlets. 
Currently this is not possible for two reasons. Firstly, not all API are ported in .Net Core. With each subsequent .Net Core release, ported APIs become more and after .Net Core 3 we will get a lot of new ported APIs. This open ways to port other cmdlets. Secondly, some API are missing in Unix systems. Certainly .Net Core team will look for solutions. 
This also explains why PowerShell Core on Windows has fewer cmdlets than Windows PowerShell.
As for your proposal, it has already been discussed. This will not give benefits to Unix users since these cmdlets do not exist, but it will complicate the lives of Windows users.

Right solution is to contribute (fill free!) to .Net Core and PowerShell Core to get its full featured.

**Comment by grandmasterv** [comment]
Hello Illya,

Thanks for shining some light on the reason behind the cmdlets existing on one platform and not another. It seems this problem started in .net core. I feel that .net core should also not make an API function available unless it can be used on all supported platforms as it’s touted as a cross-platform library.  Powershell should not be replicating their problem. What I’m getting at is the overall design decision to release for one platform only instead of waiting till all the parts are available to support a release on ALL platforms.  Your correct in that removing the ones that exist now in windows that don’t exist in other platforms would complicate things and the best way to address that gap is to contribute (still a newb here but I’ll work towards it) but no new cmdlets should be released that are single platform only.

**Comment by iSazonov** [comment]
I believe we all want to have .Net Core on all platforms with full API set. This is such a huge job that it will take several more years before we get closer to this. This is a convergent process. We will have to move step by step. And all this time we will experience various inconveniences. It's unavoidable. Create more feedback and contribute to speed up the process!
