### ISSUE TITLE
System.Speech.Synthesis.SpeechSynthesizer Speak method throws Object reference not set to an instance of an object." in PowerShell 6.1.2

### ISSUE THREAD

**Issue by wsuhoey** [PowerShell/PowerShell#8809]
System.Speech.Synthesis.SpeechSynthesizer Speak method throws Object reference not set to an instance of an object." in PowerShell 6.1.2, but not in PowerShell 5.1.

# Steps to reproduce

```powershell
Add-Type -AssemblyName System.speech
$speak = New-Object System.Speech.Synthesis.SpeechSynthesizer
$speak.Speak("test");
```

# Expected behavior

```none
hear "test" from speakers, just like in PS 5.1
```

# Actual behavior

```none
Exception calling "Speak" with "1" argument(s): "Object reference not set to an instance of an object."
```

# Environment data

`$psversiontable` results:

5.1:
```
PSVersion                      5.1.17134.407
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.407
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

6.1.2:
```
Name                           Value
----                           -----
PSVersion                      6.1.2
PSEdition                      Core
GitCommitId                    6.1.2
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Also tried submitting an issue on .NET Core's GitHub repo, but they closed it almost immediately:
https://github.com/dotnet/core/issues/2277

**Comment by iSazonov** [comment]
@wsuhoey PowerShell Core is based on .Net Core but the dll you use is from .Net Framework - it is not compatible.
I see that the API is not ported https://source.dot.net/#q=System.Speech and you can not use it in PowerShell Core. You need use a workaround like Windows PowerShell Compatibility https://github.com/PowerShell/WindowsCompatibility

**Comment by vtagion** [comment]
Rather than closing this, shouldn't porting to .Net Core be the next step/priority? I understand that it is not a PowerShell Core issue per se (except that it doesn't work). This should be added to .Net Core github issues and a link added here.

**Comment by vexx32** [comment]
I don't see anything specifically for speech synthesizer, but given that per https://github.com/dotnet/corefx/issues/32413 they still don't have a cross-platform audio player library for .NET Core, it doesn't appear that this is a high priority.

If you want this functionality it will likely be easy enough to find a third-party DLL and use that from PowerShell.

**Comment by cybercastor** [comment]
Hi!
Any update on this issue ? We are on June 2021. This issue was raise 2_ years ago.

Thanks

**Comment by vexx32** [comment]
You'd have to check with the .NET folks on this one @cybercastor. Speech synthesis isn't a focus area for PowerShell, so any support for that is going to come from .NET or potentially pulling in a third-party library.

**Comment by cybercastor** [comment]
All good. I understand. Thank you for the time you took for this reply. I will go down the rabbit hole and let the community know if I figure out anything. Cheers!
