### ISSUE TITLE
Implicit remoting (Import-PSSession/Export-PSSession): proxy functions for external scripts are unexpectedly defined with ".ps1" as part of the name

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#8813]
With implicit remoting with `Import-PSSesssion` / `Export-PSSession`, If I ask for `get-foo` with `-CommandName`, and it is found as script `get-foo.ps1` on the remote machine, the implicitly remoting proxy _function_ that is created for it is currently literally named  `get-foo.ps1` - including the `.ps1` extension - which is problematic in two respects:

* I can't invoke `get-foo.ps1` as just `get-foo`, the way I can when invoking an actual script.

* If there's a local _non-script_ command named `get-foo` (e.g., a local _function_), `Import-PSSession` doesn't recognize the name collision and happily defines `get-foo.ps1` quietly. Invoking `get-foo` then continues to call the _local_ command.

# Steps to reproduce

* On one machine that acts as the remote machine:
   * Make sure that it can be remoted into (`Enable-PSRemoting`).
   * Create a `Get-Foo.ps1` script with content `'hi from Get-Foo.ps1'` and put in a folder in `$env:PATH` (as visible to the user account that will be used for remoting).

* On another machine, from which to implicitly remote:
  * Run `Import-PSSession -CommandType ExternalScript -CommandName Get-Foo (New-PSSession <remote-machine>)`
  * Run `Get-Foo; Get-Foo.ps1`

# Expected behavior

```none
hi from Get-Foo.ps1
hi from Get-Foo.ps1
```

That is, both `Get-Foo` and `Get-Foo.ps1` should succeed in transparently invoking the remote `Get-Foo.ps1` script via implicit remoting.

# Actual behavior

```none
The term 'Get-Foo' is not recognized as the name of a cmdlet, function, script file, or operable program.
hi from Get-Foo.ps1
```

That is, `Get-Foo` didn't work, because the local proxy _function_ is _literally_ named `Get-Foo.ps1`.

To replicate local invocation behavior of an external script, both `Get-Foo` an `Get-Foo.ps1` must be defined; one could be the actual proxy function, the other an alias.

# Environment data

```none
PowerShell Core v6.2.0-preview.4 on macOS 10.14.2
PowerShell Core v6.2.0-preview.4 on Ubuntu 18.04.1 LTS
PowerShell Core v6.2.0-preview.4 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.471)
Windows PowerShell v5.1.17134.407 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.471)
```

**Comment by iSazonov** [comment]
@PaulHigin Could you please comment?

**Comment by PaulHigin** [comment]
This appears to be related to a command discovery issue.  Any discoverable script can be invoked by just the name or the name and extension (Get-Foo or Get-Foo.ps1).  And the name returned includes the extension:
```
> (Get-Command Get-Foo).Name
Get-Foo.ps1
```
This may be intentional ... I don't know.

Regarding implicit remoting name collision, you can mitigate that by specifying a name prefix:
```
Import-PSSession -Session $session -CommandName Get-Foo -Prefix My
Get-MyFoo.ps1
```

**Comment by mklement0** [comment]
@PaulHigin:

> Any discoverable script can be invoked by just the name or the name and extension 

Yes, if it is a _script_.

In the implicit remoting case, the _script_ is proxied by a _function_, and that's what causes the problem:

If you _include `.ps1` in the function name_, you can _only_ invoke that function _with_ the "extension" - which introduces an undesirable _asymmetry_:

* The (reasonable) expectation that a command that can _locally_ be called with `Get-Foo` can be invoked the same way via implicit remoting  is not fulfilled - you now _must_ invoke as `Get-Foo.ps1`.

* While the `-Prefix` parameter is handy for _anticipated_ collisions, in the case at hand the problem is that there is _no_ collision - even though there _should be one_:
   * If you (reasonably) expect `Get-Foo` to call the transparently proxied `Get-Foo.ps1` script, you'll be surprised if `Get-Foo` calls a different local function or alias by that name.

**Comment by iSazonov** [comment]
> To replicate local invocation behavior of an external script, both `Get-Foo` an `Get-Foo.ps1` must be defined; one could be the actual proxy function, the other an alias.

If we define `Get-Foo` we can have a conflict with a local name. How would we distinguish them?

**Comment by mklement0** [comment]
There's potential for conflict with _both_ names, but even a conflict with _one_ of them should be treated as a collision that is handled as usual (failure by default, explicit override via `-AllowClobber`).

To spell out the collision scenarios:

* `Get-Foo.ps1` could be an existing local script on the calling machine that's in a folder listed in `$env:PATH`.

* `Get-Foo` could (also) be an existing local _non-script_ command (which, due to command precedence, could shadow a `Get-Foo.ps1` script)

With `-AllowClobber`, defining _both_ `Get-Foo` and `Get-Foo.ps1` proxies (one as the alias of the other) then unambiguously calls the remote `Get-Foo.ps1` script, whether you invoke the proxy as `Get-Foo` or as `Get-Foo.ps1` - as with local invocation.

**Comment by iSazonov** [comment]
This could be proposed solution in the PR description.

**Comment by PaulHigin** [comment]
This a bug in implicit remoting.  I was just pointing out that command discovery returns the name plus extension, implicit remoting relies on command discovery and probably uses the name as-is.  We don't want to create multiple proxies for a single command since they are resource intensive.  Instead I think we should just fix implicit remoting to create proxy function names without file extensions.

**Comment by mklement0** [comment]
> This a bug in implicit remoting.

Yes, that's why I created this issue.

> I was just pointing out that command discovery returns the name plus extension, implicit remoting relies on command discovery and probably uses the name as-is

That was my guess too.

> We don't want to create multiple proxies for a single command since they are resource intensive.

_If_ we have to choose, I agree that the extension-_less_ name is the name to choose (`Get-Foo` rather than `Get-Foo.ps1`).

But in what way is simply also creating a `.ps1` _alias_  - the equivalent of `Set-Alias Get-Foo.ps1 Get-Foo`  - resource-intensive?
Or are you thinking of the scenario where _all_ remote commands, across all command types, are proxied?

As an aside: proxying _scripts_ is probably not the typical use case anyway.

Again, this is about implicit remoting _transparently_ working as if the proxied commands were local.
