### ISSUE TITLE
Please sign any .ps1 scripts in this repository

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#8814]
You currently have a script for helping install PowerShell as per https://github.com/PowerShell/PowerShell/blob/master/tools/install-powershell.ps1

This script is not signed - could you please sign this and others if you are sharing them to be used in production environments by users :-)

**Comment by iSazonov** [comment]
Perhaps @TravisEz13 could address the question.

**Comment by TravisEz13** [comment]
I'm assuming you are asking to sign with a Microsoft Certificate.  I'd have to investigate any other option.

What is the goal for us signing it (there are different certificates with different amounts of engineering work on our part for each scenario)?

1. Know that it comes from Microsoft and has not been tampered with.
1. The First option plus knowing it is safe to use.

It would be impractical to sign scripts that are simply checked into the repo and under development.  Anything we sign falls under additional requirements that sample code we have in the repo.  

To solve this, we would have to create a release mechanism such as releasing it as a script on the gallery.  

@SteveL-MSFT 	Can you give feedback?

**Comment by TravisEz13** [comment]
@iSazonov 	That would be scenario 2. Windows Defender Application Control (formerly Device guard) is similar.

**Comment by SteveL-MSFT** [comment]
The scripts are (hopefully) a temporary problem on Windows (we're looking at different options).  On Linux, and macOS, I believe it's easy enough to install using apt/yum/brew.  In the interim, we could sign the install-powershell.ps1 script and publish to PSGallery.

**Comment by iSazonov** [comment]
We have a request to have Update-PowerShell cmdlet. We could replace install-powershell.ps1 with the cmdlet which could download a signed manifest from persistent link and use the manifest to download new PowerShell version or updates.
