### ISSUE TITLE
Invoke-Expression doesn't make $PSCmdlet available in advanced-function scriptblocks

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#8815]
A given script block that uses `[CmdletBinding()]` to act like an advance function fails when its text is passed to `Invoke-Expression`, because in the latter case `$PSCmdlet` is undefined.

# Steps to reproduce

```powershell
$sb = { [CmdletBinding()] param() [bool] $PSCmdlet }
& $sb  # OK
Invoke-Expression $sb.ToString() # $PSCmdlet isn't defined
```

# Expected behavior

```none
True
True
```

# Actual behavior

```none
True
False
```

# Environment data

```none
PowerShell Core v6.2.0-preview.4 on macOS 10.14.2
PowerShell Core v6.2.0-preview.4 on Ubuntu 18.04.1 LTS
PowerShell Core v6.2.0-preview.4 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.471)
Windows PowerShell v5.1.17134.407 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.471)
```

**Comment by iSazonov** [comment]
It seems it is a security limitation.

**Comment by mklement0** [comment]
I don't think so, @iSazonov, because that would be an oddly specific and obscure restriction for it to be by design, given that:

* there are no other restrictions that I am aware of
* this restriction is trivia to bypass if you define a _function_ and call it:

```powershell
PS> iex 'function foo { [CmdletBinding()] param() [bool] $PSCmdlet }; foo'
True # $PSCmdlet available, as expected
```
