### ISSUE TITLE
Need RFC for WWW provider

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#8835]
# Summary of the new feature/enhancement

We need RFC for WWW provider/drive/namespace based on HTTP/HTTPS that will do the following:
```powershell
Get-Content https://aka.ms/install-powershell.ps1
Invoke-Command https://aka.ms/install-powershell.ps1
& https://aka.ms/install-powershell.ps1
```
This new provider would have to report all its "files" as downloaded-from-the-net for the purposes of enforcing execution policy.

The issue come from #8816
Related #5491, #5909

## Additional information

Also we could request RFC for FTP and WinSCP/SSH providers.

**Comment by SteveL-MSFT** [comment]
Related: https://github.com/PowerShell/PowerShell/issues/5491
