### ISSUE TITLE
`Start-Transcript` cmdlet insert newlines even when I use Write-Host -NoNewline

### ISSUE THREAD

**Issue by billcharlton0028** [PowerShell/PowerShell#8836]
From [Start-Transcript][1]: 

> The Start-Transcript cmdlet creates a record of all or part of a
> PowerShell session to a text file. The transcript includes all command
> that the user types and all output that appears on the console.

**Code**

	cls
	$global:scriptPath = Split-Path $script:MyInvocation.MyCommand.Path
	$global:scriptName = $global:scriptPathAndName.Replace(($global:scriptPath + "\"),"")
	$global:scriptNameNoExt = $global:scriptName.Replace(".ps1","")

	Start-Transcript -LiteralPath ($global:scriptPath + "\" + (get-date -f "yyyy-MM-dd_HH-mm-ss") + "_" + $global:scriptNameNoExt + ".log") 

	foreach ($n in 1..3)
	{
		write-host -NoNewline ("test line " + $n + " ")
	}

	write-host 

	Stop-Transcript

**Console output - appears as expected**

    Transcript started, output file is C:\temp\2019-02-06_07-13-43_test.log
    test line 1 test line 2 test line 3 
    Transcript stopped, output file is C:\temp\2019-02-06_07-13-43_test.log

**Transcript content - where did the newlines come from?**

	**********************
	Windows PowerShell transcript start
	Start time: 20190206071343
	Username: xxx
	RunAs User: xxx
	Machine: xxx
	Host Application: xxx
	Process ID: 10092
	PSVersion: 5.1.14409.1018
	PSEdition: Desktop
	PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.14409.1018
	BuildVersion: 10.0.14409.1018
	CLRVersion: 4.0.30319.42000
	WSManStackVersion: 3.0
	PSRemotingProtocolVersion: 2.3
	SerializationVersion: 1.1.0.1
	**********************
	Transcript started, output file is C:\temp\2019-02-06_07-13-43_test.log
	test line 1
	test line 2
	test line 3

	**********************
	Windows PowerShell transcript end
	End time: 20190206071343
	**********************

  [1]: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.host/start-transcript?view=powershell-6

**Comment by nudlsoop** [comment]
If you are executing as SYSTEM on Windows then the line-breaks seem to be related to the width of SYSTEM's default console window

**Comment by jacargentina** [comment]
This continues alive and kicking; @nudlsoop any workaround to avoid that behaviour ?

**Comment by Holdi601** [comment]
Yeah but im executing it as a user and it still does it. Especially if i have an outputstream character per character as it puts each new character in a new line

**Comment by MantvydasD** [comment]
There was no new version to the Powershell 5.1, so yes the issue still exists.

**Comment by Birgos** [comment]
Any news on this? This issue still exists with powershell version **7.4.1**...

**Comment by JimRoton** [comment]
Using PowerShell 7.4.5 and this is still an issue.
