### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by RDIL** [PowerShell/PowerShell#8838]
# Steps to reproduce
Unknown

# Expected behavior

In my PR #8822 , the windows CI has failed for a reason I don't think is related.  So here is the report

# Actual behavior

CI is failing, logs linked below

# Environment data

https://powershell.visualstudio.com/PowerShell/_build/results?buildId=12517&view=ms.vss-test-web.build-test-results-tab
```none

```

**Comment by iSazonov** [comment]
I see in the report:
> pwsh.exe : PowerShell updated your execution policy successfully, but the setting is overridden by a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective execution policy of Unrestricted. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more information please see "Get-Help Set-ExecutionPolicy".

**Comment by RDIL** [comment]
Nice find.  I believe that a `try`/`catch` block is present.  This still should be fixed if it isn't an isolated error.

**Comment by iSazonov** [comment]
Looks like the race condition #8715 because it is test for "-SettingsFile".
