### ISSUE TITLE
Feature Request - Invoke-Command should support passing parameters as a hashtable

### ISSUE THREAD

**Issue by vexx32** [PowerShell/PowerShell#8839]
# Summary of the new feature/enhancement

Simply put, rather than:
```
Invoke-Command $sb -ArgumentList $arg1, $arg2
```

I would like to be able to do:
```powershell
Invoke-Command $sb -Parameters @{NamedArg = $value1; Switch = $true}
```

(note that currently it's _impossible_ to call a scriptblock with a `[switch]` parameter as they cannot be passed positionally; this would serve to resolve that, effectively, while permitting more complex functions)

This would enable a function to do something _very_ amusing, like so:
```powershell
Invoke-Command -ComputerName testPC -Scriptblock $MyInvocation.MyCommand.ScriptBlock -Parameters $PSBoundParameters
```

Not that that's really my use case, just thought it was fun! I'm mostly interested in giving `Invoke-Command` more robust function calling capability so we can call local functions in a remote session more easily, a la:

```powershell
Invoke-Command -ScriptBlock ${function:Test-Function} -Parameters $Params -ComputerName RemotePC
```

**Comment by DHowett** [comment]
Something like this might already be possible with [splatting](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-6):

```
% $Params=@{"LiteralPath" = "C:\"; "Hidden" = $true;}; invoke-command -ScriptBlock { Get-ChildItem @Params }


C:\

d--hs-        2/13/2017  10:23 PM                $RECYCLE.BIN
d--h--         2/3/2019   3:23 PM                $WINDOWS.~BT
d--hs-         2/4/2019   5:07 PM                Config.Msi
d--hsl        8/25/2016   8:17 PM                Documents and Settings
d--h--       11/17/2018   6:36 PM                ProgramData
d--h--        9/18/2018   5:32 PM                Recovery
d--hs-        9/22/2017   5:53 PM                System Volume Information
-a-hs-         2/4/2019   4:54 PM     6840606720 hiberfil.sys
-a-hs-         2/4/2019   4:54 PM     2550136832 pagefile.sys
-a-hs-         2/4/2019   4:54 PM       16777216 swapfile.sys
```

Your last example might be possible by pasting the body of the function into a new function on the other end and splatting args against the _new_ remote function. I tried to get that working, but in the limited time I allocated to prototyping I couldn't.

**Comment by vexx32** [comment]
Yes @DHowett this _can_ be done, but the syntax for doing so is _decidedly_ more irritating to use!

Example:
```powershell
$Parameters = @{Param1 = $Value; Switch = $true}
Invoke-Command -ComputerName RemotePC -ScriptBlock {
    New-Item Function:\TempFunc -Value ${using:function:my-function} > $null
    TempFunc @using:Parameters
}
```

Being how relatively easy this is to accomplish in any case, Invoke-Command should just support it out of the box in my opinion.

**Comment by iSazonov** [comment]
@vexx32 Do you see the RFC? 
https://github.com/PowerShell/PowerShell-RFC/blob/e09b14fe01b636ea38260da9e70ff024dc32936b/2-Draft-Accepted/RFC0002-Generalized-Splatting.md

**Comment by vexx32** [comment]
@iSazonov yeah, I've been following along with that one.

This is less about splatting itself and more about how Invoke-Command doesn't support passing parameters to its script block by name, only by position with -ArgumentList.

**Comment by iSazonov** [comment]
The RFC targets "Splatting in method invocations" too. If it doesn't resolve your request we need to enhance the RFC I believe.

**Comment by vexx32** [comment]
That portion of the RFC is designed to be used specifically with .NET methods. For example:

```powershell
[System.IO.File]::ReadAllBytes@@{Path = 'C:\test.txt' }
```

The fact that Invoke-Command as a Cmdlet itself only supports passing positional arguments is a separate issue.

**Comment by anthbro** [comment]
I am having this issue too and splatting is not the issue...  Not accepting named arguments is the issue.

**Comment by justin-romano** [comment]
Hey Guys, This is a real issue with scripts as it is easy to get the order of parameters wrong and write bad scripts.  The ideal solution, to me, would look like this
```powershell
$args = @{
    P1 = 1
    P3 = 3
    P2 = 2
}

Invoke-Command -ScriptBlock{
    param($P1, $P2, $P3)
    Write-Host "$P1 $P2 $P3"
} -ArgumentList @args -Session $somesession
```
if you have a script with lots of parameters you want to call on another session, you are in for ugly brittle code ;-)

**Comment by mklement0** [comment]
@justin-romano, while `-ArgumentList @args` is tempting, it conflicts with [splatting](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Splatting) syntax: by definition, a splatted value such as `@args` cannot be the _value_ of a _single parameter_.

Given that `-ArgumentList` is `[object[]]`-typed, for reasons of backward compatibility it cannot be used to implement @vexx32's proposal, so a _new_ parameter is indeed necessary.

However, for symmetry with `-ArgumentList` I suggest `-ArgumentHashTable`.

You can think of `-ArgumentHashTable` as _deferred_ splatting: you're telling `Invoke-Command` to use the specified hashtable for splatting _at the time the script [block] is invoked_.

Note that other cmdlets, such as `Start-Job` and `Start-ThreadJob` would benefit from such a parameter too.

**Comment by vexx32** [comment]
Given that PS makes the distinction between arguments as positional and parameters as more structured (think `$args` vs `$PSBoundParameters`) I don't think there's any value in introducing a clunky new term like `-ArgumentHashtable` and in my opinion `-Parameters` is more succinct and appropriate as it doesn't introduce naming collisions if folks shorthand the parameter names.

**Comment by mklement0** [comment]
P.S.,  the name `$PSBoundParameters` is consistent with the above, given that only _parameters_ (placeholders) can be bound (that is, _arguments_ / _values_ are assigned (bound) to them).
