### ISSUE TITLE
Set-Culture does not work in remote server

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell#8856]
_From @quickware on January 22, 2019 13:49_

The following command does not change the UI culture on remote machine.

$server = "xyz"
Invoke-Command -ComputerName $server -ScriptBlock{
            #Requires -RunAsAdministrator
            Set-Culture -CultureInfo en-GB;            
            Set-TimeZone -id "GMT Standard Time"
            Get-UICulture                  
            Get-Culture            
        }

_Copied from original issue: MicrosoftDocs/PowerShell-Docs#3585_

**Comment by sdwheeler** [comment]
What version of PowerShell are you using on both hosts?

**Comment by sdwheeler** [comment]
_From @doctordns on February 9, 2019 13:13_

Set-Culture does not seem to work locally either:
```powershell
PS [C:\foo> ]> get-culture                                                                                              
LCID             Name             DisplayName
----             ----             -----------
2057             en-GB            English (United Kingdom)
PS [C:\foo> ]> set-culture no-nb
PS [C:\foo> ]> get-culture                                                                                              
LCID             Name             DisplayName
----             ----             -----------
2057             en-GB            English (United Kingdom)
```
I seem to recall that this behavoiur is by design.

**Comment by iSazonov** [comment]
@sdwheeler The cmdlet is not in the repo and more - it is deprecated for PowerShell Core. PowerShell Committee approved new Get-PSCulture and Set-PSCulture cmdlets #3833. The issue should be reported on UserVoice and/or documented.

**Comment by iSazonov** [comment]
And from my understanding Set-Culture doesn't change culture for current session - it is change system settings and user need restart PowerShell to get new culture.
