### ISSUE TITLE
PowerShell

### ISSUE THREAD

**Issue by Duchoadongland** [PowerShell/PowerShell#8865]
# Summary of the new feature/enhancement

A clear and concise description of what the problem is that the new feature would solve.
Try formulating it in user story style (if applicable):
'As a user I want X so that Y.' with X being the being the action and Y being the value of the action.

# Proposed technical implementation details (optional)

Consider providing an example PowerShell experience with expected result.

**Comment by markekraus** [comment]
@Duchoadongland as you have not provided any information beyond the default form values, I'm closing this issue. If you would like to re-open the issue, please update your issue with relevant details.
