### ISSUE TITLE
Get-Service should return SecurityDescriptor as one of the property

### ISSUE THREAD

**Issue by kvprasoon** [PowerShell/PowerShell#8872]
# Summary of the new feature/enhancement

As a user I want to get the security descriptor of a service so that I can verify and modify it if required. This can be achieved by introducing a new `SecurityDescriptor` property in the Service object.

The output should look like
```
PS >Get-Service BITS | Select-Object -Property SecurityDescriptor

SecurityDescriptor
------------------
D:(A;CI;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;IU)(A;;CCLCSWLOCRRC;;;SU)
```

**Comment by doctordns** [comment]
Purely for Amusement, I asked ChatGP to tell me how to get the SID. Here is what is produced:

"Certainly! Here's a PowerShell script that uses the Get-Service cmdlet to retrieve a Windows service's security descriptor and then displays it using the Get-Acl cmdlet:

```powershell

$serviceName = "YourServiceName"

# Get the service object
$service = Get-Service -Name $serviceName

# Get the security descriptor for the service
$acl = Get-Acl "Microsoft.PowerShell.Core\FileSystem::$($service.ServiceHandle.ToString())"

# Display the security descriptor
$acl | Format-List
```
"

I told the bot that this gave an error and asked for a second guess. It delivered this:

```powershell
$serviceName = "YourServiceName"

# Get the service object
$service = Get-Service -Name $serviceName

# Get the security descriptor for the service
$acl = Get-Acl "System\$($service.ServiceName)"

# Display the security descriptor
$acl | Format-List
```

Apologies for any wasted bandwidth.

That said, I have added this issue to the next Cmdlet WG meeting for discussion. I suspect this is an issue we would  need to rely on .NET to implement.

**Comment by TobiasPSP** [comment]
The cmdlet working group has reviewed this. We believe since the cmdlet is already going though API and has the SDDL information, this information is indeed valuable and should be part of the returned information.
