### ISSUE TITLE
Odd Behavior with Get-Help

### ISSUE THREAD

**Issue by LethiferousMoose** [PowerShell/PowerShell#8875]
# Steps to reproduce

Call Get-Help on a PS Script Module followed by a Get-Member

```powershell
Get-Help about_psconsolehostreadline | Get-Member
```

# Expected behavior

```none
Properties on the return object should be similar to the return object from calling Get-Help on a Function, Alias, or cmdlet. Where you could easily read each section via getter properties.
```

# Actual behavior

```none
Result object claims to be of type String, but has NoteProperties for:
Category     
Component    
Functionality
Name         
Role         
Synopsis     
Chars        
Length

This seems very confusing, why does a String type have additional properties and why only some properties?
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kilasuit** [comment]
I think that this is as expected and is not an issues as such, but perhaps requires some expanded documentation being published as `about_*` files almost just text files that have some minor conversions that allow them to be surfaced in the help system.

Perhaps one of the team can expand further

**Comment by iSazonov** [comment]
We have plans to implement vNext HelpSystem based on Markdown and decouple it to separate module. I hope the RFC will be approved soon. So I close the Issue until new version will be published for testing.

**Comment by LethiferousMoose** [comment]
Is there an issue tracking the vNext HelpSystem?

**Comment by iSazonov** [comment]
@LethiferousMoose Please look the RFC PR https://github.com/PowerShell/PowerShell-RFC/pull/102
