### ISSUE TITLE
ValidateSet issues when calling Get-Help for a module

### ISSUE THREAD

**Issue by LethiferousMoose** [PowerShell/PowerShell#8877]
# Steps to reproduce

- Create two PowerShell script modules, let's call them **ModuleOne** and **ModuleTwo**.
- Add root folder containing both modules to the ```PSModulePath``` so they get picked up
- In **ModuleOne** create an implementation of ```System.Management.Automation.IValidateSetValuesGenerator```. 
- In **ModuleTwo**, add to the top of file```Using module ModuleOne```
- Create a function in **ModuleTwo** that uses ```ValidateSet``` using the class defined in **ModuleOne**
- Create a help file in **ModuleTwo** under the en-US folder.
- Call ```Get-Help about_ModuleTwo```

**Project/ModuleOne/ModuleOne.psm1**
```powershell
class ExampleValuesGenerator : System.Management.Automation.IValidateSetValuesGenerator {
    [string[]] GetValidValues() {
        return @('Test1', 'Test2')
    }
}
```

**Project/ModuleTwo/ModuleTwo.psm1**
```powershell
Using module ModuleOne

function TestValues {
    param([ValidateSet([ExampleValuesGenerator])]
          [string[]] $TestArg)

   # I do something
}
```

**Project/ModuleTwo/en-US/about_ModuleTwo.help.txt**
```powershell
TOPIC
    about_ModuleTwo

SHORT DESCRIPTION
    Some short text.

LONG DESCRIPTION
    Some longer text.

KEYWORDS
    about_ModuleTwo
```

# Expected behavior
```none
The help documentation is return like normal.
```

# Actual behavior

```none
An error occurs while trying to fetch the ExampleValuesGenerator type:
Get-Help : Unable to find type [ExampleValuesGenerator].

Note: This only occurs when I use the Keywords, calling ```Get-Help ModuleTwo``` works as expected.
```

This sounds very similar to #5661

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@LethiferousMoose Please clarify - after removing KEYWORDS from about_ModuleTwo.help.txt you do not get the error?

**Comment by LethiferousMoose** [comment]
Here's an example:
- `Get-Help about_ModuleTwo` - this gives an error
- `Get-Help ModuleTwo` - this does not give error and returns the help

**Comment by LethiferousMoose** [comment]
@iSazonov So I just re-tested this on the latest version, I don't think this is still an issue.

**Comment by iSazonov** [comment]
@LethiferousMoose If you can not repo on latest builds please close the issue. Thanks!
