### ISSUE TITLE
Publish RPM to fedora/27 repo and Update fedora instructions

### ISSUE THREAD

**Issue by phillipsj** [PowerShell/PowerShell#8879]
I followed the direction located [here](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-6#installation-via-package-repository-preferred---fedora-27-fedora-28).

And I receive the following error:

sudo dnf install powershell
Repository packages-microsoft-com-prod is listed more than once in the configuration
Last metadata expiration check: 0:05:34 ago on Tue 12 Feb 2019 08:19:37 PM EST.
No match for argument: powershell
Error: Unable to find a match

# Steps to reproduce

1. Start with a fresh install of Fedora 29
2. Install Microsoft .NET Core following directions [here](https://dotnet.microsoft.com/download/linux-package-manager/fedora28/sdk-current).
3. Follow directions to install PowerShell Core from [here](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-6#installation-via-package-repository-preferred---fedora-27-fedora-28)

# Expected behavior

That there wouldn't be a naming conflict that prevents searching the repository to find the PowerShell package.

# Actual Issue

Both the .NET Core package repository and the PowerShell package repository for Fedora both use the same package name which cause the conflict.

## .NET Core
[packages-microsoft-com-prod]
name=packages-microsoft-com-prod
baseurl=https://packages.microsoft.com/fedora/27/prod/
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc

## PowerShell
[packages-microsoft-com-prod]
name=packages-microsoft-com-prod
baseurl=https://packages.microsoft.com/rhel/7/prod/
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc

# Workaround

I just opened the *microsoft.prod* repo file that was created and edited it to change the repository name.

[packages-microsoft-com-pwsh]
name=packages-microsoft-com-pwsh
baseurl=https://packages.microsoft.com/rhel/7/prod/
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc

# Actual Resolution

Either change the name of one of the package files or create a single repo that all Microsoft packages can be obtained.

**Comment by iSazonov** [comment]
@SteveL-MSFT @TravisEz13 Please look the Issue - this may need to be fixed beore the next release.

**Comment by SteveL-MSFT** [comment]
@phillipsj I just created a new Fedora 29 VM and following the instructions it installed powershell 6.1.3 just fine.

**Comment by phillipsj** [comment]
Did you follow all my repro  steps or did you just do the PowerShell
install.  You have to install the other Microsoft product too.  That is the
conflict.

**Comment by SteveL-MSFT** [comment]
@phillipsj sorry, didn't install dotnet.  I see what the problem is.  At the time we started publishing pwsh, packages.microsoft.com only had rhel and didn't have a folder for fedora.  They have that now which is what dotnetsdk uses.  The problem is if you follow both instructions, then the Microsoft repo is registered twice differently which `dnf` complains about.  The fix is that we should also publish to the fedora location and update our install instructions.  cc @TravisEz13

**Comment by phillipsj** [comment]
No worries, I really enjoy using Powershell and want it to be seamless.
Thanks for looking into it.

**Comment by TravisEz13** [comment]
Fedora 27 is EOL 
https://fedoramagazine.org/fedora-27-end-of-life/

**Comment by phillipsj** [comment]
This issue isn't resolved, this applies to all fedora installations including Fedora 30. I feel that you all didn't try to reproduce this issue.

**Comment by TravisEz13** [comment]
I see the request is to publish individual packages for each fedora distribution.  Can you open a feature request?

**Comment by phillipsj** [comment]
That isn't the request.  The request is to not name your repo the same as
the .net core repo in your yum file.

**Comment by phillipsj** [comment]
Happy to do a call to get this sorted out.  Here is an image of what I
describing.
https://twitter.com/phillipsj73/status/1152760880326729729?s=09

**Comment by TravisEz13** [comment]
It is the net effect of your request, unless you would like to ask .NET to change.
I’ve filed it for you
https://github.com/PowerShell/PowerShell/issues/10202

**Comment by TravisEz13** [comment]
Unless you can provide more details
