### ISSUE TITLE
$FormatEnumerationLimit with Format-Table not works well on some cases

### ISSUE THREAD

**Issue by JumpingYang001** [PowerShell/PowerShell#888]
$FormatEnumerationLimit = 1
$result=Format-Table -inputobject @{'test'= 1, 2}
Expect:test                           {1...}
Actual:test                           {1, 2}

$FormatEnumerationLimit = "abc"
$result=Format-Table -inputobject @{'test'= 1, 2}
Expect: throw exception?
Actual:test                           {1, 2}

$FormatEnumerationLimit = 2
Remove-Variable FormatEnumerationLimit
$result=Format-Table -inputobject @{'test'= 1, 2}
Expect:throw exception?
Actual:test                           {1, 2}

Above cases is from UT:https://github.com/PowerShell/psl-monad/blob/master/monad/tests/monad/DRT/commands/utility/UnitTests/FormatAndOutputTests.cs#L512

**Comment by mklement0** [comment]
The first issue is that only a _global_ variable by that name is respected (similar issue: #3645):

```powershell
# Variable created in child scope: FAILS
> & { $FormatEnumerationLimit = 1; Format-Table -inputobject @{'test'= 1, 2} }
Name                           Value                                                                                                                                               
----                           -----                                                                                                                                               
test                           {1, 2}                                                                                                                                              

# Variable created in global scoe: OK
> & { $global:FormatEnumerationLimit = 1; Format-Table -inputobject @{'test'= 1, 2} }
Name                           Value                                                                                                                                               
----                           -----                                                                                                                                               
test                           {1...}                                                                                                                                              
```

The 2nd issue is that the `$FormatEnumerationLimit` is not type-constrained, not even in the global scope.

On a related note: Other preference variables are type-constrained in the global scope (e.g., `$ErrorActionPreference`, but aren't predefined in descendant scopes, which makes them effectively unconstrained there, whereas some preference variables aren't predefined at all, also making them unconstrained on creation - see #3483 and #3644 

The 3rd issue raises the general question whether preference variables should be _removable_.
Arguably, there's no harm in removing them, as long as they have implicit default values - which appears to be the case here (default value is `4`, as documented):

```powershell
> Remove-Variable FormatEnumerationLimit; Format-Table -inputobject @{'test'= 1, 2,3,4,5}
Name                           Value                                                                                                                                               
----                           -----                                                                                                                                               
test                           {1, 2, 3, 4...}                                                                                                                                     
```

That said, if all preference variables were tagged as such, not only would their discovery be much easier, but removal could easily be prevented too; making preference variables programmatically discoverable has been suggested before, on [uservoice.com](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/17407222-powershell-and-collections-in-particular-collect)
On a related note, #4394 suggests improving the discoverability of variables of _automatic_ variables.

**Comment by KirkMunro** [comment]
There doesn't seem to be any pending action for this issue. Can we close it?

**Comment by mklement0** [comment]
Having just come across this again: 

There's clearly a bug here that's worth fixing: the `$FormatEnumerationLimit` value _in effect in the calling scope_ should be respected - you shouldn't have to modify the _global_ instance of the variable.

**Comment by doctordns** [comment]
I hit this bug last week. 

Bump?
