### ISSUE TITLE
LICENSE file contradicts itself

### ISSUE THREAD

**Issue by alexbuzzbee** [PowerShell/PowerShell#8882]
The License file contains the following language:

> Copyright (c) Microsoft Corporation. All rights reserved.

However, it then goes on to apparently contradict this by placing the code under the MIT license, which is generally considered not "all rights reserved." This may not present an actual legal issue, but the open source community generally considers "all rights reserved" to mean "proprietary and closed-source," so using that term could cause confusion.

This language also appears in the startup text when launching PowerShell:

> PowerShell 6.1.1
> Copyright (c) Microsoft Corporation. All rights reserved.

I would recommend changing this to simply give the copyright year, and possibly acknowledge the non-Microsoft contributors, for example:

> Copyright (c) 2016 Microsoft Corporation and contributors.

(Going from the date of project start.)

**Comment by iSazonov** [comment]
/cc @joeyaiello @SteveL-MSFT 

CoreFX uses MIT license title in files.

**Comment by SteveL-MSFT** [comment]
Please see https://github.com/PowerShell/PowerShell/issues/2129
