### ISSUE TITLE
Powershell character scape & issue

### ISSUE THREAD

**Issue by andrefsoliveira** [PowerShell/PowerShell#8885]
Hi all,

i'm trying run a Azure CLI (v2.0.57)  command via Windows Powershell, but it's not working as expected.

I'm do the same thing on the azure portal, ms-dos and also on CloudShell web interface and it's works perfectly.

The command is the follow:

`az eventgrid event-subscription create --name "sopas" --source-resource-id "/subscriptions/id/resourceGroups/name/providers/Microsoft.EventGrid/topics/name" --endpoint-type "webhook" --endpoint "https://prod-16.westeurope.logic.azure.com:443/workflows/xxx/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=xxx" --debug --verbose`

The error on windows powershell is the follow:

```
az : ERROR: The attempt to validate the provided endpoint https://prod-16.westeurope.logic.azure.com/workflows/371848cd5a2242cda3f88bfcce80962a/triggers/manual/paths/invoke failed. For more details, visit 
https://aka.ms/esvalidation.
At line:3 char:1
+ az eventgrid event-subscription create --name "sopas" --source-resour ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: The atte...s/esvalidation.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
'sp' is not recognized as an internal or external command,
operable program or batch file.
'sv' is not recognized as an internal or external command,
operable program or batch file.
'sig' is not recognized as an internal or external command,
operable program or batch file.
```

How could i avoid this behavior ?

Am I doing something wrong ?

Can someone help ?

Thanks!

**Comment by MaximoTrinidad** [comment]
You may want to try re-posting this issue at https://github.com/Azure/azure-powershell.
It will give you a better response.

Remember this repository is only for PowerShell Core issues.  

Also, please include all necessary PowerShell, AzureCLI, Az module (if needed) version information requested in the issue templates.   
:)

**Comment by andrefsoliveira** [comment]
I'm sorry.

I have already post this issue on Azure CLI Project, and the answer was that this is a Powershell issue and it's why i'm here.

I will create a new post on Azure-Powershell project, as you suggested.

Thanks!

**Comment by MaximoTrinidad** [comment]
@andrefsoliveira 

Awesome!!  You will always get a quick response.  
Thanks for posting the issue.

:)
