### ISSUE TITLE
InitializationScripts with dynamic module in restricted mode

### ISSUE THREAD

**Issue by ritchxu** [PowerShell/PowerShell#8892]
As elaborated in this blog post [PowerShell Constrained Language mode and the Dot-Source Operator](https://blogs.msdn.microsoft.com/powershell/2018/11/26/powershell-constrained-language-mode-and-the-dot-source-operator/), there are caveats in constrained mode.

Here is our use case, we dynamically generate a `.psm1` which only contains statements like `Import-Module A.psd1` `Import-Module B.psd1`, etc. We flush the generated `.psm1` file to disk and add it to the [InitializationScripts](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.runspaces.runspaceconfiguration.initializationscripts?view=powershellsdk-1.1.0#System_Management_Automation_Runspaces_RunspaceConfiguration_InitializationScripts) to run.

Everything works fine in non-Constrained Language mode, but once we turned on Constrained Language mode, the shell suddenly could not see and run the dynamically generated `.psm1` file even though the file exists. Is there any known issue with Constrained Language mode for this use case?

**Comment by iSazonov** [comment]
Do you really need Constrained Language mode?
Please read https://blogs.msdn.microsoft.com/powershell/2017/11/02/powershell-constrained-language-mode/ - perhaps you should explicitly export.

**Comment by ritchxu** [comment]
I did explicitly export my functions instead of using wildcard, that issue is considered solved. The new problem here is that dynamically generated `.psm1` file could not be "seen". I'm suspecting because it was dynamically generated, it wasn't signed script and somehow constrained mode would cause it being filtered out?

**Comment by vexx32** [comment]
What errors were reported? I think it's unlikely that the PSM1 couldn't be seen, and more likely that something that was in the PSM1 wasn't permitted in constrained language mode.

**Comment by iSazonov** [comment]
Perhaps you need to generate a module manifest.

**Comment by ritchxu** [comment]
> What errors were reported? I think it's unlikely that the PSM1 couldn't be seen, and more likely that something that was in the PSM1 or the modules it was importing wasn't permitted in constrained language mode.

My apology, one correction the dynamically generated file is of `.ps1` extension. The error is like

> The term 'C:\DynamicallyGenerated.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

The strange thing is right after this error, if I execute 'C:\DynamicallyGenerated.ps1' in the same console, it executed with no issue.

**Comment by ritchxu** [comment]
To update this thread, I did change the approach to running the part of importing module in memory, instead of generating script dynamically and load from it. The approach worked, implying there might be indeed unclear issue with loading dynamically generated script.
