### ISSUE TITLE
 get-childitem skips the properties in the top level registry key

### ISSUE THREAD

**Issue by jszabo98** [PowerShell/PowerShell#8897]
Get-childitem skips the properties in the top level registry key (key1).  It is like get-childitem skipping the files in the top level folder.  (I could have sworn this was changed in some version of PS6.)

# Steps to reproduce

```powershell
C:\> get-childitem hkcu:\key1
```

# Expected behavior

```none
    Hive: HKEY_CURRENT_USER

Name                           Property
----                           --------
key1                           name1 : value1
```

# Actual behavior (nothing)

```none
```

To me it should be like the file system:

```powershell
PS C:\> get-childitem c:\folder1
```
```none
    Directory: C:\folder1


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        2/14/2019  10:51 AM             10 file1
```

Supposing I wanted to recursively dump out the keys, values and data from hkcu:\key1 and everything underneath (what's the idiomatic way to do that?).  I would have to do:

```powershell
$(get-item hkcu:\key1; get-childitem -recurse hkcu:\key1) | ...

# ideally get

Path Name Value Type
---- ---- ----- ----
...  ...  ...   ...

```

Another way to look at it:

```powershell
PS C:\> cd hkcu:\key1
PS HKCU:\key1> dir
# no output, even though values are here
```

Sorry for any confusion between keys/values/data and path/name/value.

# Environment data

```powershell
PS C:\> $PSVersionTable
```
```none
Name                           Value
----                           -----
PSVersion                      6.1.2
PSEdition                      Core
GitCommitId                    6.1.2
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
Yeah, the registry provider is weird and doesn't work at all like other providers. 

Get-ChildItem will generally retrieve only subkeys. If you want to get the properties of a single key, you need to use `Get-ItemProperty`

**Comment by jszabo98** [comment]
Just one more comment.  This is how I wished get-itemproperty worked:

```powershell
function get-itemproperty2 {
  param([parameter(ValueFromPipeline)]$key)
  process {
    $key.getvaluenames() | foreach-object {
      $value = $_
      [pscustomobject] @{
        Path = $Key -replace 'HKEY_CURRENT_USER',
          'HKCU:' -replace 'HKEY_LOCAL_MACHINE','HKLM:'
        Name = $Value
        Value = $Key.GetValue($Value)
        Type = $Key.GetValueKind($Value)
      }
    }
  }
}
```

**Comment by vexx32** [comment]
I like that functionality, but I think that really ought to be exhibited by `Get-ChildItem` itself in the registry provider context, as it more closely mimics how other providers behave.
