### ISSUE TITLE
Start-Process -Verb Runas fails with quoted arguments passed to batch files

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#8898]
# Steps to reproduce

On Windows, run the following Pester tests [_updated based on @iSazonov's feedback_], which trie to pass an unquoted and a double-quoted argument through to a batch file via `Start-Process`' 
`-ArgumentList` aka `-Args` parameter, which doesn't work as expected in combination with `-Verb RunAs`.
 
```powershell
Describe "Start-Process -Verb RunAs bug"  {

  BeforeAll {
    # Create a temp. batch file that simply echoes the arguments it receives.
    '@echo %*'  | Set-Content $env:TEMP\$PID.cmd
    # Arguments to pass to the batch file via Start-Process - note the inclusion of a double-quoted token.
    $batchFileArgs = 'foo "bar baz"'
    # Output redirections to capture the outcome.
    $redirections = " 1>$env:TEMP\$PID-out.txt 2>$env:TEMP\$PID-err.txt"
  }

  It "Starting a batch file with NO elevation accepts double-quoted arguments" {
    Start-Process -Wait $env:TEMP\$PID.cmd -Args ($batchFileArgs + $redirections)
    Get-Content $env:TEMP\$PID-Err.txt | Should -BeNullOrEmpty
    Get-Content $env:TEMP\$PID-out.txt | Should -Be $batchFileArgs
  }

  # NOTE: This test prompts for elevation (UAC prompt).
  It "Starting a batch file WITH elevation accepts double-quoted arguments" {
    Start-Process -Wait -Verb RunAs $env:TEMP\$PID.cmd -Args ($batchFileArgs + $redirections)
    Get-Content $env:TEMP\$PID-Err.txt | Should -BeNullOrEmpty
    Get-Content $env:TEMP\$PID-out.txt | Should -Be $batchFileArgs
  }

  AfterAll {
    Remove-Item $env:TEMP\$PID.cmd, $env:TEMP\$PID-*.txt    
  }

}
```

Note that both `Start-Process` commands _open a new window_, but since the new process terminates very quickly, you'll only see a brief flash.

The 2nd command, due to running with elevation, shows a UAC prompt.

# Expected behavior

Both tests should succeed, i.e, both `Start-Process` calls should pass the specified arguments through (write them to stdout), without writing anything to stderr.

# Actual behavior

```none
  Describing Start-Process -Verb RunAs bug
    [+] Starting a batch file with NO elevation accepts double-quoted arguments 1.19s
    [-] Starting a batch file WITH elevation accepts double-quoted arguments 2.56s
      Expected $null or empty, but got @(''C:\Users\jdoe\AppData\Local\Temp\9612.cmd" foo "bar' is not recognized as an internal or external command,', 'operable program or batch file.').
      18:     Get-Content $env:TEMP\$PID-Err.txt | Should -BeNullOrEmpty
      at <ScriptBlock>, C:\Users\jdoe\Desktop\pg\pg.Tests.ps1: line 18
Tests completed in 3.75s
Tests Passed: 1, Failed: 1, Skipped: 0, Pending: 0, Inconclusive: 0
```

That is, the elevated (2nd) invocation failed, complaining about something like `'C:\Users\jdoe\AppData\Local\Temp\9612.cmd" foo "bar` - this indicates _broken quoting_; note how the batch-file path starts with `'`(!), not `"`.

Note that if the `-Args` value doesn't have embedded `"..."` tokens, the problem goes away.

# Environment data

```none
PowerShell Core v6.2.0-preview.4 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.471)
Windows PowerShell v5.1.17134.407 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.471)
```

**Comment by iSazonov** [comment]
@mklement0 Please clarify - does the cmd run or does it get arguments?

**Comment by mklement0** [comment]
@iSazonov: From the OP: 

> While the _second_ one does open a new window (after confirming the UAC prompt), it is instantly closed, rendering only as brief flashing.

So my _guess_ is that the `cmd.exe` is being created but dies instantly - the commands inside the batch file never get to execute.

**Comment by iSazonov** [comment]
@mklement0 Thanks! Please update repo steps so that we can clearly see this (write to file?) and use it in Pester test.

**Comment by mklement0** [comment]
@iSazonov: Please see my update of the OP.

**Comment by MaynardMiner** [comment]
The issue has to be within the ``-ArgumentList`` parameter, as it can run a process with ``-Verb runas`` without ``-ArgumentList`` (at least for me).

**Comment by mklement0** [comment]
@MaynardMiner, yes, this issue is all about argument passing (`-Args`, as used in the tests, is the alias name of `-ArgumentList`).
