### ISSUE TITLE
Get-Help is not working in restricted sessions with Invoke-Command

### ISSUE THREAD

**Issue by krishnayalavarthi** [PowerShell/PowerShell#8900]
# Steps to reproduce

```powershell
New-PSSessionConfigurationFile -SessionType RestrictedRemoteServer -Path .\MyJEAEndpoint.pssc
​Test-PSSessionConfigurationFile -Path .\MyJEAEndpoint.pssc​
​Register-PSSessionConfiguration -Path .\MyJEAEndpoint.pssc -Name 'JEAMaintenance' -Force​
​$jeasession = New-PSSession -ComputerName 'localhost' -ConfigurationName 'JEAMaintenance'​
​Invoke-Command -Session $jeasession -ScriptBlock { Get-Command }​
​
Invoke-Command -Session $jeasession -ScriptBlock { Get-help }​ # This will fail​
​UnRegister-PSSessionConfiguration -Name 'JEAMaintenance'

```

# Expected behavior

```none
# This command should give the right results
Invoke-Command -Session $jeasession -ScriptBlock { Get-help }​ 
```

# Actual behavior

```none
# This command is failing
Invoke-Command -Session $jeasession -ScriptBlock { Get-help }​ 
```

# Environment data

PS C:\WINDOWS\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

PS C:\WINDOWS\system32>

```none

```

**Comment by iSazonov** [comment]
@krishnayalavarthi  Please add environment data.

**Comment by iSazonov** [comment]
Close as stale issue. Feel free to continue discussion.
