### ISSUE TITLE
Passing parameters to $env:PAGER is broken in 6.2.0-preview.4

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShell#8912]
I have `$env:PAGER` set to `less "-PPowerShell help page line %lt (press h for help or q to quit)"` and on PS Core 6.1.0 on Windows 10 1809, PS Core uses less and gives me this nice footer during paging:

![image](https://user-images.githubusercontent.com/5177512/52985938-40277100-33b3-11e9-83a4-525e06308539.png)

But in PS Core 6.2.0-preview.4 that same env var setting, causes `more.com` to be invoked. That is rather rude - ignoring my less preference.

# Steps to reproduce
Set the following env var value.
```powershell
$env:PAGER = 'less "-PPowerShell help page line %lt (press h for help or q to quit)"'
```

# Expected behavior
I get paging via less and with my desired footer.

# Actual behavior
more.com is invoked instead.

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0-preview.4
PSEdition                      Core
GitCommitId                    6.2.0-preview.4
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rkeithhill** [comment]
Ah, I see this warning when I scroll up - it goes by pretty fast and winds up off-screen:
```
WARNING: Ignoring invalid custom-paging utility command line specified in $env:PAGER: less "-PPowerShell help page line %lt (press h for help or q to quit)"
```
OK, so this is a breaking change.  Is there a work-around?

**Comment by rkeithhill** [comment]
I'm not sure this script works as expected:
```
            # Split the command line into tokens, respecting quoting. 
            $customPagerCommand, $customPagerCommandArgs = & { Write-Output -- $customPagerCommandLine }
```
e.g.
```
$customPagerCommandLine = 'less "-PPowerShell help page line %lt (press h for help or q to quit)"'
$customPagerCommand, $customPagerCommandArgs = & { Write-Output -- $customPagerCommandLine }
```
Outputs the entire value to `$customPagerCommand` because `$customPagerCommandLine` is always interpreted as a single string.  Something like this works but I wouldn't recommend iex:
```
 $customPagerCommand, $customPagerCommandArgs = iex "Write-Output -- $customPagerCommandLine"
```

**Comment by rkeithhill** [comment]
Another possible approach:
```
$errs = $null
$t = [System.Management.Automation.PSParser]::Tokenize($customPagerCommandLine, [ref]$errs)
$customPagerCommand = $t[0]
$customPagerArgs = $t[1]
```

**Comment by rjmholt** [comment]
Looks like this is defined here:
https://github.com/PowerShell/PowerShell/blob/ff3edaa2e38d715b287bbb7046fd75a5ba5d1061/src/System.Management.Automation/engine/InitialSessionState.cs#L4106-L4215

Possibly last changed in this commit: https://github.com/PowerShell/PowerShell/commit/4858afb613e0f39c620c3cdc82ab4e00099eeb3e.

**Comment by pougetat** [comment]
Just saw this issue. I'll look into it asap since I committed that code. :)

**Comment by pougetat** [comment]
@rkeithhill First of all thanks for investigating this. I did find a workaround for you. Essentially you need to specify the path to the less executable as part of your custom env:PAGER.
Try something like this : 

$env:PAGER = '"C:\Program Files\Git\usr\bin\less.exe" "-PPowerShell
help page line %lt (press h for help or q to quit)"'

**Comment by pougetat** [comment]
@rkeithhill @rjmholt 
I've looked into this issue and it does seem that my code is not tokenizing the custom env:PAGER that is being set. I am about to open a PR that tokenizes properly and once it is merged this env:PAGER variable will work :

$env:PAGER = '"C:\Program Files\Git\usr\bin\less.exe" "-PPowerShell
help page line %lt (press h for help or q to quit)"'
