### ISSUE TITLE
SSH in VS Code

### ISSUE THREAD

**Issue by mcorning** [PowerShell/PowerShell#8921]
# Support Question
Do I need to install [OpenSSH ](https://github.com/PowerShell/openssh-portable) (assuming there's an installer msi available) before i can use VS Code to remote debug my Ubuntu VM with SSH?

I am trying to follow this article [Using Visual Studio Code for remote editing and debugging](http://bit.ly/2TUWkjO), but my VS Code Powershell Extensions v1.11 don't recognize the **-HostName** arg.

I wonder how the author got his example to work?

## Official support

[PowerShell Support Lifecycle](https://aka.ms/pslifecycle)

## Community Resources

[Slack Community Chat](https://powershell.slack.com) - Interactive chat with other PowerShell enthusiasts
[PowerShell.org Forum](https://powershell.org/forums/) - Search or post new general PowerShell usage questions

**Comment by mcorning** [comment]
I just discovered that OpenSSH Client is part of my version of Windows 10.

So what do we need to do to VS Code to remote using SSH?

**Comment by rkeithhill** [comment]
The author was using macOS as the host OS.  You should be able to do this on Windows 10.  Recent version of Windows 10 (1803/1809) come with OpenSSH Client but you have to enable it as an "optional feature".  If you have an older version of Windows 10, grab Chocolatey (https://chocolatey.org) and install with `choco installopenssh`.

**Comment by rkeithhill** [comment]
The `Enter-PSSession -HostName foo` command requires that you use PowerShell Core (this repo) instead of Windows PowerShell.  The bottom right part of VSCode will show the version of PowerShell used when a .ps1 has been opened. It should look like this for PS Core 6.1:

![image](https://user-images.githubusercontent.com/5177512/53060387-94942480-3477-11e9-9ab5-aa0315c05163.png)

If not, click on the version number and select PowerShell Core 6.1.  Of course, if you don't have PowerShell Core installed you will need to install it from this repo.

**Comment by mcorning** [comment]
thanks a 0xF4240, @rkeithhill, for the quick response. and yes, that (obscure <g/>) switch worked. at least I now have more cool PS capabilities like SSH.

however, i get a **Permission denied** error when i enter azureuser@[my vm dns] and enter the azureuser password I just set up in Azure Portal. Does it matter that azureuser has both a password and a public key?
probably not because i can successfully use those credentials in VS Code using the **SSH** terminal.

I should note that earlier today I upgraded PS itself from v5.1 to v6.1, and i received the same permission denied error using the same credentials I just entered in VS Code running PS 6.1. that consistency between PS and VS Code is the only thing that's not surprising about all this.

so, what's the difference between SSH and PSIntegrated?

btw, here's the complete error:
```
Enter-PSSession : The background process reported an error with the following message: The SSH client session has ended with error message: Permission denied, please try again.
Permission denied, please try again..
At line:1 char:1
+ Enter-PSSession -HostName [my dns].eastus.cloudapp.azure.com
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ResourceUnavailable: (:) [Enter-PSSession], PSRemotingTransportException
+ FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.PowerShell.Commands.EnterPSSessionCommand
```

**Comment by iSazonov** [comment]
Can we close the discussion?

**Comment by mcorning** [comment]
Yes

Rwap

________________________________
