### ISSUE TITLE
use powershell6 don't connect AzureAD

### ISSUE THREAD

**Issue by liu129jun** [PowerShell/PowerShell#8924]
use powershell6 don't connect AzureAD

This repository is **ONLY** for PowerShell Core 6 issues.
PowerShell 6.1.3
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS C:\Users\bond> Install-Module -Name AzureAD
PS C:\Users\bond> Connect-AzureAD
Connect-AzureAD : The term 'Connect-AzureAD' is not recognized as the name of a
cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:1
+ Connect-AzureAD
+ ~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Connect-AzureAD:String) [], CommandNo
tFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\bond>

**Comment by MaximoTrinidad** [comment]
Seems the module is only meant to be use in Windows PowerShell and not PowerShell Core.
Azure new modules are under the Az.* names which can be use in either version of PowerShell.

This is a good example of what's missing in the PowerShell Gallery module page. It should a be better tag for the modules to identify what's Windows PowerShell, PowerShell Core, or both.

:)

**Comment by markekraus** [comment]
@MaximoTrinidad It _is_ supported by PSGallery:

https://www.powershellgallery.com/packages?q=Tags%3A%22PSEdition_Core%22
https://www.powershellgallery.com/packages?q=Tags%3A%22PSEdition_Desktop%22
https://docs.microsoft.com/en-us/powershell/gallery/concepts/module-psedition-support 

It _could_ be more visible. Also, it is very much up to the module author to set that, as there is no obvious way to tell if a module supports one or both from the code alone. Since Windows PowerShell has been around longer before there was any need to distinguish the 2 versions, it's a safer bet that anything that doesn't say it explicitly supports core does not support core.

**Comment by bergmeister** [comment]
Sounds like the module should possibly throw at import time. Even for binary modules one can even use simple approaches like e.g. [this](https://github.com/PowerShell/PSScriptAnalyzer/blob/development/Engine/PSScriptAnalyzer.psm1#L17) one

**Comment by liu129jun** [comment]
Thanks.
I hope I will support you in the future.

**Comment by MaximoTrinidad** [comment]
@markcowl 

OK! I see it but not in the older module.  But, you're missing the point and I wasn't very clear.  
My Apologies!

This need to be populated to all Windows Modules (old modules) and not only the new ones.  For example "AzureAD":
https://www.powershellgallery.com/packages?q=AzureAD

Not many people will assume the module is only for Windows PowerShell.  
I totally support the @bergmeister comment that it should fail during the module import.

:)

**Comment by markekraus** [comment]
@MaximoTrinidad As I said, that is very much up to the module authors. There is no obvious way for us to detect if a module is compatible with core or not unless the module author signals to us that their module is not compatible. In light of that, the only safe assumption is that an author has not explicitly signaled the module is not compatible with core, it is likely not compatible with core. But that's just an assumption. The module author may also have made their module core compatible without signaling. In that case you can test to see if it works or not.

In any case, for AzureAD (and any other module not maintained in this repo) you will need to track down the module owner and file requests/bugs through whatever channels they have. Perhaps the PowerShell team can point us in the direction of the correct product group (I'm not sure if this one is owned by o365 or Azure AD)

**Comment by MaximoTrinidad** [comment]
@markekraus 

Ah! To bad.  This just create confusion with people adopting PowerShell Core. 

:)

**Comment by markekraus** [comment]
@MaximoTrinidad Depends on your perspective. Many modules made for Windows PowerShell "just work" on PowerShell Core without the need to make adjustments. If the decision had been made to only import modules that explicitly called out Core compatibility, the adoption rate of Core would probably be much much slower. 

It is a pain point, though, that sometimes the discovery of incompatibility comes as a surprise for the user. However, to the PowerShell Team's credit, they did a fair amount of advocating and advertising that Module authors and users should check their modules and code for core compat and update their code long before Core was GA. But they can only do so much.

I will also add "user beware". Users should be researching the modules they are using and the compatibility with their systems and PowerShell version. It is the responsibility of the module authors and the users to communicate on these things. The language and project itself can only do so much.

**Comment by MaximoTrinidad** [comment]
Thanks @markekraus !!

All Good!  As time goes I known it will get better.

:)

**Comment by franckberneron** [comment]
I fully understand @markekraus 's point on the users' checking compatibility issues but honestly, the AzureAD module is not just some exotic tool. So a compatibility warning is the least that could be done. Everyone's pushing for the adoption of PS Core so just walk it all the way and make things clear for end users.
I've just lost about half a day's work trying to figure out why the thing wouldn't work in PS Core, messing with $env, $profile, you name it...😖
Luckily I ended up finding this GH Issue so I'll revert to PS 5.1 so get back to real work now.
Not a happy camper, really.
