### ISSUE TITLE
Feature Request: Native API build

### ISSUE THREAD

**Issue by Amaroq-Clearwater** [PowerShell/PowerShell#8928]
# Summary of the new feature/enhancement
I'm not entirely sure how Native API applications actually work in depth, since I only recently learned about the Native API's existence, but I given what I know so far they seem pretty awesome, and there might actually be some use for more Native API applications.

As such, I would like to see a build of PowerShell which is based on the Native API for Windows NT, that way certain PowerShell commands or scripts could be used prior to booting into Windows, such as for diagnostics and recovery.

#Proposed technical implementation details
There's already a Native Shell which somebody developed, but it hasn't been updated for any operating systems beyond Windows XP as far as I can tell, and it is still sorely lacking in features.
http://hex.pp.ua/nt-native-applications-shell-eng.php

Now for performance optimization of something as low-level as the Native API, I'd also suggest looking into Ravioli Memory. As far as I can gather, it's supposed to be an open-source and highly efficient implementation of Garbage Collection for bare-metal languages such as C and C++. It may also have some potential applications when it comes to security.
https://www.reenigne.org/blog/rethinking-memory/ 

Just one potential obstacle to all of this...
Even with the .NET core, it would probably be difficult to make PowerShell function correctly on the Native API alone, and I'm not entirely sure if it's possible to build a Native API version of the .NET core in the first place, let alone implementing any necessary Win32/Win64 or UWP functions whilst still allowing the program to compile and run as a Native application. If there's an easy solution to that, I'd love to hear about it!

**Comment by HumanEquivalentUnit** [comment]
> certain PowerShell commands or scripts could be used prior to booting into Windows

At that point, boot from a rescue disk (Windows or Linux, with PowerShell optional), or attach the virtual hard disk to another VM. You'll get a much more powerful diagnostic environment, with less time and effort.

The effort involved to do this would be enormous - years - but without the full Windows API, WMI or event log or networking or any other big subsystems, the amount of usable PowerShell cmdlets would be tiny, and the amount of *useful* ones even smaller, I think.

**Comment by bergmeister** [comment]
I agree and even if someone builds such a command, it should be in a separate module, I do not see the need for it being part of the PS engine

**Comment by Amaroq-Clearwater** [comment]
Hence why it would probably be a fork. Native API-based applications are just a niche field, I suppose.

**Comment by iSazonov** [comment]
> such as for diagnostics and recovery.

Windows PE is commonly used. And PowerShell is there.

**Comment by HumanEquivalentUnit** [comment]
> Hence why it would probably be a fork.

If you want to fork, you need only the fork button in Github - [the PowerShell license](https://github.com/PowerShell/PowerShell/blob/master/LICENSE.txt) is the MIT License; everyone has permission to fork and rework it for almost any purpose including commercial ones.

**Comment by SteveL-MSFT** [comment]
The amount of work involved and the niche of this scenario seems to indicate it isn't a good cost to value proposition.
