### ISSUE TITLE
Code coverage outdated

### ISSUE THREAD

**Issue by RDIL** [PowerShell/PowerShell#8930]
Basically, our code coverage is still using api.appveyor.com which we don’t use anymore.  This means that code coverage might not be being updated.

**Comment by iSazonov** [comment]
@JamesWTruher @SteveL-MSFT Will MSFT team create new issue with roadmap for cross-platform code coverage?

**Comment by SteveL-MSFT** [comment]
@JamesWTruher is actively working on cross-platform code coverage.  No ETA yet.
