### ISSUE TITLE
Get-Command: -All switch stops returning all commands after command has been loaded

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#8931]
# Steps to reproduce

First install 2 versions of a module, I am using `PowerShellGet` as an example (1 is the default module that comes with the installation and a user installed module (in this case the versions happen to be the same but the bug also happens when the versions differ). `Get-Module` returns me both `Install-Module` cmdlets when using the `-All` parameter by design. However, the `-All` switch stops working as expected once the command in question has been loaded

```powershell
> Get-Command -all | where-object {$_.name -eq 'install-module'}

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Install-Module                                     2.0.4      PowerShellGet
Function        Install-Module                                     2.0.4      PowerShellGet


> Get-Command install-module

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Install-Module                                     2.0.4      PowerShellGet


> Get-Command -all | where-object {$_.name -eq 'install-module'}

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Install-Module                                     2.0.4      PowerShellGet
```

# Expected behavior

The 3rd command should behave like the 1st one, the call to `Get-Command Install-Module` or invoking `Install-Module`, both of which causes the command to load, should not affect the behaviour of the `-All` parameter because its purpose is to always return ALL commands.

# Actual behavior

The 3rd command does not return all commands any more

# Environment data

This bug does not seem to be a regression as it is also present in Windows PowerShell 5.1

```none
Name                           Value
----                           -----
PSVersion                      6.2.0-preview.4
PSEdition                      Core
GitCommitId                    6.2.0-preview.4
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
It looks like second case uses another code path like find loaded command and stop. Perhaps we could fix this with -Force if this doesn't still work.
