### ISSUE TITLE
Performance Optimization: OpenACC acceleration

### ISSUE THREAD

**Issue by Amaroq-Clearwater** [PowerShell/PowerShell#8932]
# Summary of the new feature/enhancement
Operations in PowerShell which consist of a single task being performed on many things at once could be accelerated significantly using [OpenACC Libraries](https://en.wikipedia.org/wiki/OpenACC) as PowerShell would be able to utilize the parallel computing power of modern GPUs such as those provided by Nvidia, AMD, and even the integrated graphics on various Intel CPUs. For owners of APUs and consumer-class Intel CPUs especially, it would basically be a free performance upgrade!

OpenACC is best suited for Single-Instruction-Multiple-Data (SIMD) operations, so not _all_ code would benefit from parallelization in this manner.

**Comment by iSazonov** [comment]
@Amaroq-Clearwater PowerShell Core is based on C#, .Net Core and Roslyn and used all benefits from its. I think your suggestion is more for Roslyn. You could start discussion in Roslyn repo.
On the other hand, you can find several discussions in the repo on how we would benefit from using parallel (calculations).

**Comment by Amaroq-Clearwater** [comment]
OpenACC could probably be adapted for C#, and .NET Core could probably be adapted with OpenACC. Not sure how difficult it would be, but PowerShell would be far from the only beneficiary if this were to happen.

**Comment by vexx32** [comment]
Precisely, and that's what @iSazonov was saying. This kind of change would have to happen at a much lower level than PowerShell, either in Roslyn or in .NET Core. 😄
