### ISSUE TITLE
Performance problem: -cmatch prevents automatic caching of on-demand-compiled regexes

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#8941]
Note: This isn't a _bug_ per se, but a _performance issue_.

Note that `-creplace` and `switch -regex -casesensitive` appear NOT to be affected.

# Steps to reproduce

```powershell
$strArray = , 'foo' * 1e5  # an array with N elements containing 'foo'
# Contrast the performance of -match vs. -cmatch
$scriptBlocks = 
 { foreach ($str in $strArray) { $null = $str -match  'f?(o)' } },
 { foreach ($str in $strArray) { $null = $str -cmatch 'f?(o)' } }

$scriptBlocks | % { (Measure-Command $_).TotalSeconds }
```

# Expected behavior

Roughly the same execution time in both cases - `-cmatch` should actually be slightly _faster_.

# Actual behavior

Sample result from my macOS 10.14.3 machine:

```none
0.6651756
1.3135713
```

That is, `-cmatch` unexpectedly took about _twice as long_.

That this may be related to unexpectedly _bypassing_  .NET's  automatic caching of on-demand-compiled regexes is evidenced by the fact that if you _force_ caching as follows, the problem goes away:

```powershell
# Forces caching of the regex; running the above code again then performs as expected.
$null = switch -casesensitive -regex ($null) { 'f?(o)' { } }
```

# Environment data

```none
PowerShell Core v6.2.0-preview.4 on macOS 10.14.2
PowerShell Core v6.2.0-preview.4 on Ubuntu 18.04.1 LTS
PowerShell Core v6.2.0-preview.4 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.471)
Windows PowerShell v5.1.17134.407 on Microsoft Windows 10 Pro (64-bit; Version 1803, OS Build: 17134.471)
```

**Comment by iSazonov** [comment]
It's funny :-)
