### ISSUE TITLE
PowerShell Core should be supported in WinRm from Linux systems

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#8942]
# Summary of the new feature/enhancement

In the scenario where krb5-user (in Ubuntu Kerberos client) has been installed and configured to connect to a Windows System joined AD domain using PowerShell Core remoting, will connect opening a Windows PowerShell session.

It would be nice in both Windows and other cross-platform systems to have the ability to choose with PowerShell Edition to use: Windows PowerShell, PowerShell, or PowerShell Preview.

Maybe adding and -PSEdition parameter then providing which PowerShell Edition to connect.

**Comment by SteveL-MSFT** [comment]
You can do this today already.  When using `New-PSSession`, use the `-ConfigurationName` parameter.  By default, it uses `Microsoft.PowerShell` which maps to Windows PowerShell.  If you run `Enable-PSRemoting` from PSCore6, it creates `PowerShell.6` or `PowerShell.6-Preview` depending on the release as well as the version specific one like `PowerShell.6.1.0`.

**Comment by MaximoTrinidad** [comment]
@SteveL-MSFT 

Oh! I will check this out and update my blog post.  

Thanks you,
:)

**Comment by MaximoTrinidad** [comment]
Just an FYI!

It works!! THANK YOU!!
