### ISSUE TITLE
UX Regression

### ISSUE THREAD

**Issue by skydnn** [PowerShell/PowerShell#8948]
This has to be the worst regression of a product that I have ever seen.  I was forced to upgrade from Powershell 5 today to 6.1 because I was forced to change from AzureRM to Az, and no matter what I did I could not uninstall from Powershell 5.

With the install of 6.1 I no longer seem to have Powershell ISE

Not only that, what makes this a terrible experience is that with 5 I typed connect-azurermaccount and I got a popup to sign in.  now with connect-azaccount I get some text with a URL to goto, which I have to copy and paste into a browser in order to then type in some random code in order to then sign in.  This whole experience is Terrible.

**Comment by vexx32** [comment]
Windows PowerShell (v1-v5.1) and Core (v6+) are intended to be used side by side. Windows PowerShell is considered as a relatively critical system component, so you won't be able to uninstall it without a fairly significant impact to your operating system.

The ISE has been deprecated and is not being developed anymore. You can still use the ISE to edit scripts if you would like, although PowerShell Core cannot be integrated with it. If you prefer, you can install Visual Studio Code, which does have an official PowerShell extension available and compatible with both editions of PowerShell.

As for the Azure cmdlet issue, that module isn't maintained by the PowerShell team at all, it's handled separately by the Azure team. Unfortunately this can no evidence result in less than perfect communication between the teams, but by and large I believe the module should work. PowerShell Core is, however, built on .NET Core (Windows PowerShell uses Framework) which for the moment means that it isn't able to create GUI elements like windows PowerShell can. This is being worked on as better GUI support comes to .NET Core; it seems .NET Core 3.0 will be porting over some of the GUI support for Windows, at least.

Hopefully that helps for the time being, but if you have any questions, all us folks here are more than happy to help you further!

**Comment by kilasuit** [comment]
@skydnn A few things

Az still works within Windows PowerShell 5.1 so whilst you may have needed to move to Az module you were not required to also upgrade to PowerShell Core

For issues with Az/AzureRM you want to raise them in the following repo https://github.com/Azure/azure-powershell/

In regards to this
> Not only that, what makes this a terrible experience is that with 5 I typed connect-azurermaccount and I got a popup to sign in. now with connect-azaccount I get some text with a URL to goto, which I have to copy and paste into a browser in order to then type in some random code in order to then sign in. This whole experience is Terrible.

please see this issue https://github.com/Azure/azure-powershell/issues/7430 and specifically this comment https://github.com/Azure/azure-powershell/issues/7430#issuecomment-426480499 where it is mentioned that the Interactive Login flow is not currently supported but is being tracked in this issue https://github.com/Azure/azure-powershell/issues/7358

hope the above helps
