### ISSUE TITLE
add jumphost support for SSH PSSessions 

### ISSUE THREAD

**Issue by matsmcp** [PowerShell/PowerShell#8950]
# Add functionality to be able to use jumphosts

Please add support to use jumphosts  with ssh pssessions.
With SSH you can use the -J flag to jump through jump/Bastion-hosts for increased security or simplified networking.

I would like to see the same functionality with pssessions.

**Comment by matsmcp** [comment]
My idea is to add to new switches, for example -JumpHost and -JumpHostUser to SSHConnection and relevant command like invoke-command, new-pssession and so on ...

**Comment by iSazonov** [comment]
@matsmcp It is open source project so you can fork and make experiments. Ask if you need help.

**Comment by matsmcp** [comment]
Well, to be honest I do not code C or C derivate code at all so if it should be an improvement. I shouldn't try to code it. I'm very happy to help out with testing and so on

**Comment by matsmcp** [comment]
https://github.com/PowerShell/PowerShell/issues/12762 is related to this

**Comment by matsmcp** [comment]
After doing some more testing I'm happy with #12802 as a solution to this issue.
With 7.3.3 I can jump through  jump/Bastion-hosts, I can do multiple jumps and I can use different credential sets for each jump too.
