### ISSUE TITLE
Invoke-RestMethod "-Method Head" does not work

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#8956]
If I only want to return a string, then I can use Invoke-RestMethod.
I found "-Method Head" does not work,it is by design?
It seems that Invoke-RestMethod is a semi-finished curl, is the powershell team planning to continue developing it?
Whether other methods work, I have not tested.

Invoke-WebRequest can return normally
---------------- 
Invoke-WebRequest -Method HEAD -uri https://cn.bing.com
Invoke-WebRequest -Method HEAD -uri https://cn.bing.com -UseBasicParsing
Invoke-WebRequest -Method HEAD -uri http://httpd.apache.org

linux + curl return.test http and https.
----------------
[root@centos76 ~]# curl -I http://httpd.apache.org
HTTP/1.1 200 OK
Date: Fri, 22 Feb 2019 17:51:50 GMT
Server: Apache/2.4.18 (Ubuntu)
Last-Modified: Tue, 22 Jan 2019 17:13:31 GMT
ETag: "24bf-5800f18b8870b"
Accept-Ranges: bytes
Content-Length: 9407
Vary: Accept-Encoding
Content-Type: text/html

[root@centos76 ~]# curl -I https://cn.bing.com
HTTP/1.1 302 
Cache-Control: private
Content-Length: 139
Content-Type: text/html; charset=utf-8
Location: https://www4.bing.com/
Vary: Accept-Encoding
Set-Cookie: SNRHOP=TS=636864553995912819&I=1; domain=.bing.com; path=/
X-MSEdge-Ref: Ref A: D1BD88DFB7F140AF98BFC1C703B69D3B Ref B: BJ1EDGE0211 Ref C: 2019-02-22T18:03:14Z
Set-Cookie: _EDGE_S=F=1&SID=034B443A5C9062700A1E49315DBE6340; path=/; httponly; domain=bing.com
Set-Cookie: _EDGE_V=1; path=/; httponly; expires=Wed, 18-Mar-2020 18:03:14 GMT; domain=bing.com
Set-Cookie: MUID=189FE2FCC09967092A40EFF7C1B766BE; path=/; expires=Wed, 18-Mar-2020 18:03:14 GMT; domain=bing.com
Set-Cookie: MUIDB=189FE2FCC09967092A40EFF7C1B766BE; path=/; httponly; expires=Wed, 18-Mar-2020 18:03:14 GMT
Date: Fri, 22 Feb 2019 18:03:14 GMT

Steps to reproduce
------------------
```powershell
Invoke-RestMethod -Method HEAD -uri https://cn.bing.com
Invoke-RestMethod -Method HEAD -uri https://cn.bing.com -UseBasicParsing
Invoke-RestMethod -Method HEAD -uri http://httpd.apache.org
 
```

Expected behavior
-----------------

Actual behavior
---------------
retrun nothing

Environment data
----------------
centos76 + PowerShell 6.1.3  
centos76 + PowerShell 6.2.0-preview.4
windows10 17763 

reporter
----------------
By the chinese powershell study & research group. QQ group No. is 183173532

**Comment by markekraus** [comment]
This is "by design". `Invoke-RestMethod` only acts on the _body_ of a response. `-Method 'HEAD'` would only return the _headers_ of the response with no _body_. Without a _body_ to process, `Invoke-RestMethod` does nothing. You can, however, retrieve the headers via the `-ResponseHeadersVariable` parameter on `Invoke-RestMethod`:

```powershell
Invoke-RestMethod -Method HEAD -uri https://cn.bing.com -ResponseHeadersVariable Headers
$Headers
```

Result:

```none
Key                       Value
---                       -----
Cache-Control             {max-age=0, private}
Vary                      {Accept-Encoding}
P3P                       {CP="NON UNI COM NAV STA LOC CURa DEVa PSAa PSDa OUR IND"}
Set-Cookie                {SRCHD=AF=NOFORM; domain=.bing.com; expires=Tue, 23-Feb-2021 23:27:29 GMT; path=/, SRCHUID...
Strict-Transport-Security {max-age=31536000; includeSubDomains; preload}
X-MSEdge-Ref              {Ref A: C6652D43CA8F426BB80F98EFC2C2B21F Ref B: SJCEDGE0207 Ref C: 2019-02-23T23:27:29Z}
Date                      {Sat, 23 Feb 2019 23:27:28 GMT}
Content-Length            {115241}
Content-Type              {text/html; charset=utf-8}
```

Please keep in mind that the purpose of `Invoke-RestMethod` and `Invoke-WebRequest` are not to have full 100% parity with curl or wget. But many features are there, just accessed differently.
