### ISSUE TITLE
Enter-PSHostProcess tests.By Process Id.Can enter using NamedPipeConnectionInfo is Failing 6% of the time

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#8971]
![image](https://user-images.githubusercontent.com/10873629/53306480-61b8aa80-3842-11e9-955b-edc1183c7470.png)

Test: Enter-PSHostProcess tests.By Process Id.Can enter using NamedPipeConnectionInfo
Priority: 0
Test file: not available
Machine: fv-az379
Tested build: [PR-8964-20190223.01](https://powershell.visualstudio.com/PowerShell/_Build?_a=summary&buildId=14114)
Error message: Exception calling "Invoke" with "0" argument(s): "The runspace state is not valid for this operation."
Stack trace: 
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Core\Enter-PSHostProcess.Tests.ps1: line 58 58: $ps.AddScript('$pid').Invoke() | Should -Be $pwsh.Id

**Comment by iSazonov** [comment]
@TylerLeonhardt Could you please look the issue?

**Comment by iSazonov** [comment]
Today I have to rebuild tests some times. Put the test in pending until we fix.

**Comment by TylerLeonhardt** [comment]
I'm look into this. I'll try to get a solid repro locally using Docker.
