### ISSUE TITLE
Unexpected problems with Set-Location in user profile.

### ISSUE THREAD

**Issue by unnamedcrewman** [PowerShell/PowerShell#8974]
UPDATE:  Solved; non-issue

In my Powershell profile, I'm trying do a quick check for the existence of a specific drive/folder, and then use `Set-Location` to change my working directory based on the result.  I'm using the exact same profile for Powershell 5.1 and 6, but I'm getting different, and somewhat unexpected results in Powershell 6. 

The entire profile is:

    Write-Host "Testing for D:\ ..."

    if (Test-Path D:)
    {
        Write-Host "D: is alive and well"
        Write-Host "Switching to D:\ ..."
        Set-Location -Path D:\
    }

    $dir = Get-Location

    Write-Host "Current directory is: "$dir

The Results I get for 5.1 are:

    Windows PowerShell
    Copyright (C) Microsoft Corporation. All rights reserved.

    Testing for D:\ ...
    D: is alive and well
    Switching to D:\ ...
    Current directory is:  D:\
    PS D:\>                     <=====(I expected the D:\ here)

The results I get from 6 are:

    PowerShell 6.1.3
    Copyright (c) Microsoft Corporation. All rights reserved.

    https://aka.ms/pscore6-docs
    Type 'help' to get help.

    Testing for D:\ ...
    D: is alive and well
    Switching to D:\ ...
    Current directory is:  D:\
    PS C:\Users\bleep>          <===== (I expected D:\ here instead of C:\Users\bleep)

I've read some stuff about `Set-Location`, and I get the hint that it maybe not as intuitive as it as I was expecting (i.e. differences between CWD and process directory), but I've not found enough to help me understand if that relates to the issue here, or if there is a "solution".

I have two basic questions:

- Is this expected behavior?
- If it is expected, is there a way to achieve the 5.1 result (a prompt in the D:\ drive)  via a profile script for Core 6?

NB. I know that there are a number of ways to set the starting directory(commandline switch; modified windows shortcut, etc.), but at this point I'm specifically interested in the possibility of doing it through a startup script.

**Comment by iSazonov** [comment]
Can you repo without PSReadline?

**Comment by unnamedcrewman** [comment]
I still get the same behavior without PSReadline.

I tested with PSReadline disabled two ways: 

- Adding `Remove-Module -Name PSReadline` as the first line of the profile.
- By deleting the PSReadline folder from `C:\Program Files\PowerShell\6\Modules` folder.

**Comment by unnamedcrewman** [comment]
Well, I'm a bit of an idiot.  I'm just starting out trying to learn/use the console a bit more, and I've always started PowerShell from the start menu using the shortcut there.  In poking around on some other stuff, I just realized that `-WorkingDirectory ~`  is baked into the Start menu shortcut that gets setup on installation.  Removing the working directory requirement solves my problem.

Sorry for the fuss.
