### ISSUE TITLE
Allow combining Get-Random -Count with (implied) -Minimum / -Maximum to create multiple random values

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#8986]
# Summary of the new feature/enhancement

Currently, you can only obtain multiple values with `-Count` if you supply an _input collection_ to select random elements from.

However, **sometimes you want to generate multiple random values from a given _range_,** such as "generate 3 random values in the range 0 to 1":

```powershell
# WISHFUL THINKING - currently, you have to call Get-Random in a *loop*.
PS> Get-Random -Maximum 1.0 -Count 3
0.00964209344687038
0.399765062797705
0.589964029188251
```

# Proposed technical implementation details

Allow combining parameter `-Count` with (implied) `-Minimum` and /or `-Maximum` as well, in which case `-Count` simply specifies how many values in the range to generate.

**Comment by iSazonov** [comment]
What output type is expected? Int? Double?

**Comment by vexx32** [comment]
Whatever the input type for mininum/maximum is, is it not? I believe Get-Random dynamically determines that based upon input.
