### ISSUE TITLE
NMAP not working in powershell remoting

### ISSUE THREAD

**Issue by berny275** [PowerShell/PowerShell#8998]
# Steps to reproduce

I can do the following from the powershell prompt or from cmd and I get the same output.

```
nmap -sn -n -oX - 10.128.77.0/24
```

This gives me a list of the 19 hosts on my dev network.

The same command in powershell (I've checked this with procmon to make sure):
```
$remotenmapserver = "localhost"
$nmaparg1 = "-sn"
$nmaparg2 = "-n"
$nmaparg3 = "-oN"
$nmaparg4 = "-"
$nmaparg5 = "10.128.77.0/24"


$ScriptBlockContent =
                            {
                                $nmaparg1 = $args[0]
                                $nmaparg2 = $args[1]
                                $nmaparg3 = $args[2]
                                $nmaparg4 = $args[3]
                                $nmaparg5 = $args[4]
                                nmap $nmaparg1 $nmaparg2 $nmaparg3 $nmaparg4 $nmaparg5

Invoke-Command -AsJob -ComputerName $remotenmapserver -ScriptBlock $ScriptBlockContent -ArgumentList $nmaparg1,$nmaparg2,$nmaparg3,$nmaparg4,$nmaparg5
```
I get 7 hosts.

# Expected behavior

nmap being executed as an external command under powershell and powershell remoting should yield the same results

# Actual behavior

The powershell remoting environment seems to be limited in some way but I can't find any documentation as to how or why and I can't seem to find any way to work around it either.

# Environment data

```
Name                           Value


PSVersion                      6.1.3
PSEdition                      Core
GitCommitId                    6.1.3
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by thezim** [comment]
I see that in your PowerShell version you are using `-oN` while in the native version you are using `-oX`. I can’t recall the zillion args of nmap but perhaps this was a mistake?

**Comment by berny275** [comment]
Sorry, that's probably just me debugging it. Output Normal vs Output XML.

I've asked the nmap crew what it's doing as well, and I'm awaiting an answer for that one. I think it's trying to do raw sockets and controlling ethernet / IP frames directly, but if it works from Powershell why not from Powershell remoting?

**Comment by berny275** [comment]
If I use:

echo "& nmap -sn -n -oX - 10.128.77.0/24" > c:\temp\nmap.ps1
$nmaparg1 = "-noprofile"
$nmaparg2 = "-file"
$nmaparg3 = "c:\temp\nmap.ps1"
$nmaparg4 = "-verb"
$nmaparg5 = "RunAs"

And run it from a administrator powershell prompt, it works, I get all 19 hosts.

If I run that without administrator privs, again, I get 7 hosts

If I run it without admin privs though and don't use powershell remoting, I get 19 hosts. So there's definitely something in permissions inherited with powershell remoting.
