### ISSUE TITLE
Feature Request: Add suggestions for common cmd.exe commands

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#9006]
# Summary of the new feature/enhancement

Users trying to move from cmd to PowerShell struggle with muscle memory on commands like `dir /s` which don't work since `dir` is an alias to `get-childitem` and parameters start with a hyphen and `/s` for subdirectories would need to be `-r` for recursion.

# Proposed technical implementation details (optional)

Have a built in list of common cmd built-in commands and when the user tries it, a CommandNotFoundException is thrown the suggestion framework can suggest the PowerShell equivalent.

**Comment by iSazonov** [comment]
Can MSFT use telemetry to collect such errors? This would greatly facilitate the work (and make it "portable" - Unix users haven't such problems?).

**Comment by SteveL-MSFT** [comment]
@iSazonov feel free to add that to https://github.com/PowerShell/PowerShell-RFC/pull/158

We've discussed getting telemetry on errors as it would tell us what issues customers are having but there are privacy concerns of the contents of the ErrorRecord

**Comment by iSazonov** [comment]
@SteveL-MSFT Done.

**Comment by iSazonov** [comment]
Perhaps it is good area for (local) ML/AI.

**Comment by rkeithhill** [comment]
Could we also get suggestions for common native exes on Windows?  I should get suggestions when I mis-type git, bash, npm, python, gcc, node, etc.  Today the experience isn't very helpful on Windows:
```
08-07 14:50:32 7> npn run build
npn: The term 'npn' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Suggestion [4,General]: The most similar commands are: nsn, cp, cpi, gp, gpv, gps, mp, nal, ndr, ni.
[user/hill/ULC-3286-impl-install-license-service-stub +0 ~7 -0 !] KLM:src\KeysightLicenseManager
!08-07 14:50:38 8> gir fetch 
gir: The term 'gir' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Suggestion [4,General]: The most similar commands are: dir, gdr, gi, gin, gip, gal, gbp, gc.
```
NOTE: suggestions work better on Linux for some reason:
```
08-07 15:02:33 4> npn run build
npn: The term 'npn' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Suggestion [4,General]: The most similar commands are: nsn, npm, npx, cpi, gp, gpv, gps.
/home/hillr
08-07 15:03:47 5> gir fetch
gir: The term 'gir' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Suggestion [4,General]: The most similar commands are: dir, gdr, gi, git, gal, gbp, gc, gci, gcm.
/home/hillr
```
🤷‍♂️

**Comment by iSazonov** [comment]
It would be great to have more meta data about Windows utilities in a format that we could use in IntelliSense, argument binding and so on.
