### ISSUE TITLE
Web Cmdlets don't allow $null username in a PSCredential for basic auth

### ISSUE THREAD

**Issue by burkasaurusrex** [PowerShell/PowerShell#9017]
It would be great if there was a way to pass a PSCredential with a $null username to the web cmdlets. I ran into this with an API that has no username, just a API key that is used for basic auth.

# Steps to reproduce

```powershell
$TestCreds = Get-Credential

if ($TestCreds.UserName) {
    $TestCreds = New-Object System.Management.Automation.PSCredential -ArgumentList (
        [pscustomobject] @{ 
            UserName = $null
            Password = $TestCreds.Password
        }
    )
}

Invoke-RestMethod -Uri 'https://httpbin.org/headers' `
                  -Authentication Basic `
                  -Credential $TestCreds
```

# Expected behavior

```powershell
$TestCreds = Get-Credential

if ($TestCreds.UserName) {
    $TestCreds = New-Object System.Management.Automation.PSCredential -ArgumentList (
        [pscustomobject] @{ 
            UserName = ' '
            Password = $TestCreds.Password
        }
    )
}

Invoke-RestMethod -Uri 'https://httpbin.org/headers' `
                  -Authentication Basic `
                  -Credential $TestCreds
```

There is a workaround where you pass a username with a single space. The space is base64 encoded however. So, in the example below, I passed 'username' and 'password' as the creds. You'll notice that 'IDpwYXNzd29yZA==' was passed in the basic auth header, which decodes to ' :password' (note the leading space).

```none
PowerShell credential request
Enter your credentials.
User: username
Password for user username: ********

headers
-------
@{Authorization=Basic IDpwYXNzd29yZA==; Host=httpbin.org; User-Agent=Mozilla/5.0 (Windows NT 10.0; Microsoft Windows 10.0.17134; en-US) PowerShell/6.1.2}
```
# Actual behavior

```none
Invoke-RestMethod : Object reference not set to an instance of an object.
At C:\Users\bdavis\Documents\Scripts\temp_01.ps1:12 char:1
+ Invoke-RestMethod -Uri 'https://httpbin.org/headers' `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Invoke-RestMethod], NullReferenceException
+ FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.1.2
PSEdition                      Core
GitCommitId                    6.1.2
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by markekraus** [comment]
This seems more like an abuse of the PSCrednetial API which is not supposed to work with null usernames... but.. we could maybe address this edge case here 

https://github.com/PowerShell/PowerShell/blob/ff3edaa2e38d715b287bbb7046fd75a5ba5d1061/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs#L805

really though, I think even needing an empty username with basic auth is an edge case... in most APIs where a null/empty basic auth user is acceptable, so to us any string in the username (e.g. Azure DevOps REST API).

**Comment by burkasaurusrex** [comment]
Yea, no argument that needing an empty username with basic auth is an edge case (ha, not the only peculiarity I'm dealing with for this API...).

I didn't realize that you shouldn't be able to make a `PSCredential` with a `$null` username? If you're not supposed to be able to create a `PSCredential` with a $null username, then I don't see any reason to handle the above scenario in the web cmdlets. 

It seems like you should be able to create a `PSCredential` with a `$null` username, but that sounds more like a design choice than a bug. I could see something like `Get-Credential -AllowNullUsername` or something, as well as a `PSCredential` constructor that just takes a `SecureString`.

The counter argument would be that a `PSCredential` with a `$null` username is really just a `SecureString`. It seems more secure to keep the password in a `PSCredential` and pass that variable to various cmdlets instead of decrypting the password, storing it in an intermediary variable unencrypted (and consequently memory), and then passing it as a parameter.

Hopefully that makes sense.

**Comment by vexx32** [comment]
There's no need to decrypt the securestring, since those can be passed around to cmdlets if you choose. The barrier there is mainly just that most cmdlets accept the PSCredential, but not securestring directly.

If the username isn't going to be used, you can generally just use a random username, even if it's literally just a single place.

**Comment by burkasaurusrex** [comment]
Thanks for the comment. Yea, you'll notice I called out that workaround in the original issue. The point of my last comment is that a random username or a ' ' username is not the same as a `$null` username.

I don't believe there's currently a way to feed a `SecureString` to `Invoke-WebRequest -Credential` without a) decrypting the `SecureString` or b) passing a non-null username?

**Comment by markekraus** [comment]
@burkasaurusrex PR #9536
