### ISSUE TITLE
XmlCommand DRT basic functionality Tests.Import-Clixml StopProcessing should succeed Failed

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#9018]
<span style="color:6d6d6d;">Test</span>: <b>XmlCommand DRT basic functionality Tests.Import-Clixml StopProcessing should succeed</b><br><span style="color:6d6d6d;">Priority</span>: 0<br><span style="color:6d6d6d;">Test file</span>: <span style="color:6d6d6d;">not available</span><br><span style="color:6d6d6d;">Machine</span>: fv-az363<br><span style="color:6d6d6d;">Tested build</span>: <a href="/PowerShell/_Build?_a=summary&amp;buildId=13625" target=_blank rel="nofollow noopener noreferrer">Daily-master-4de3a721420fd6ccea27ccea43bfd94263c83be8-201902201145</a><br><span style="color:6d6d6d;">Error message</span>: <b>Expected 'Stopped', but got Completed.</b><br><span style="color:6d6d6d;">Stack trace</span>: <br><span>at &lt;ScriptBlock&gt;, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Utility\XMLCommand.Tests.ps1: line 77
77: 		$ps.InvocationStateInfo.State | Should -Be &quot;Stopped&quot;</span><br><br>

**Comment by iSazonov** [comment]
@TravisEz13 Link to tested build doesn't work.

Is it random fail or stable?

**Comment by TravisEz13** [comment]
Yeah... This was test of automation to move issues from powershell.visualstudio.com to github.  There was only one failure for daily builds.  I'm fine with closing this.

**Comment by TravisEz13** [comment]
I demo'ed this to the team.  I'm going to close this issue.
