### ISSUE TITLE
Documentation Improvement proposal: classes include

### ISSUE THREAD

**Issue by seolog78** [PowerShell/PowerShell#9043]
# Documentation Issue

One of the classes advantages is a possibility to reuse once developed classes in the future.
I would like to find in the "Powershell: about classes" text an example of storing classes as separate files and including them by reference in the main ps-script. 
The background idea: to collect future capable classes as files by script development and save time and notation length using only "includes".
Such an example would have an essential education influence on the readers community.

**Comment by iSazonov** [comment]
@seolog78 Please move the issue to https://github.com/MicrosoftDocs/PowerShell-Docs

**Comment by seolog78** [comment]
Moved
