### ISSUE TITLE
Simply change colors

### ISSUE THREAD

**Issue by K2AAE** [PowerShell/PowerShell#9049]
All I want is for Power Shell to be READABLE - seems NO ONE can do this.
Set-PSReadLineOption -Colors @{
"ContinuationPrompt" = 	[ConsoleColor]:: White
"Emphasis" = 	[ConsoleColor]:: White	
"Error" = 	[ConsoleColor]:: White
"Selection" = 	[ConsoleColor]:: White
"Default" = 	[ConsoleColor]:: White
"Comment" = 	[ConsoleColor]:: White
"Keyword" = 	[ConsoleColor]:: White
"String" = 	[ConsoleColor]:: White
"Operator" = 	[ConsoleColor]:: White
"Variable" = 	[ConsoleColor]:: White
"Command" = 	[ConsoleColor]:: White
"Parameter" = 	[ConsoleColor]:: White
"Type" = 	[ConsoleColor]:: White
"Number" = 	[ConsoleColor]:: White
"Member" = 	[ConsoleColor]:: White
}

**Comment by iSazonov** [comment]
Related discussions #8963 #2381

**Comment by iSazonov** [comment]
New issue for discussion #10780
