### ISSUE TITLE
Cannot set default working directory

### ISSUE THREAD

**Issue by chriskuech** [PowerShell/PowerShell#9053]
# Steps to reproduce
0. Note that there is no way to set the default working directory at the console application level (unlike many popular consoles)
1. Create a profile at `$PROFILE`
2. In the profile, add
    ```powershell
    Set-Location C:\
    Write-Host "Profile has been loaded"
    ```
3. Open a new PowerShell session
4. Note that the profile has run but the working directory is still `$HOME`

# Expected behavior
Current working directory after loading the profile is the location set in the profile (`C:\`)

# Actual behavior
Current working directory after loading the profile is `$HOME`

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.1.3
PSEdition                      Core
GitCommitId                    6.1.3
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by TravisEz13** [comment]
I cannot repro this issue is 6.1.3 on macOS

**Comment by TravisEz13** [comment]
I can on Windows.

**Comment by TravisEz13** [comment]
I'm pretty sure the `-workingdirectory` switch is superseding the profile

**Comment by TravisEz13** [comment]
It does on mac as well, but not all the time.

**Comment by TravisEz13** [comment]
Verified this is fixed in `6.2.0-preview.4`

**Comment by TravisEz13** [comment]
Also, note that assumption `0` in the repo is incorrect.  It was this very feature causing this issue.

**Comment by chriskuech** [comment]
I see what you mean.  The console itself has no way to set the working directory--it is handled by the shortcut.
