### ISSUE TITLE
Feature Request - Publish SHA512 Hashes for PowerShell Core Release Downloads on GitHub

### ISSUE THREAD

**Issue by RealDrGordonFreeman** [PowerShell/PowerShell#9060]
# Summary of the new feature/enhancement

I am requesting the PowerShell team begin publishing the SHA512 hashes for downloads of the PowerShell Core releases on GitHub.

This would solve the problem of verifying file integrity to better ensure the download has not been tampered with.

# Proposed technical implementation details (optional)

The technical implementation of this would probably require the PowerShell team to create an automated PowerShell script to produce the hashes for each release, then upstream those hashes to the appropriate HTML tables on GitHub.

Producing the hashes can be done using PowerShell's `Get-FileHash` cmdlet.

The GitHub download page should then either publish the hash for each release openly as a displayed string (it's quite long) or link to a file which contains the hashes for each release.

Example:

>  Supported Platform | Downloads (stable) | Downloads (preview) | Hash | How to Install

When a user downloads a PowerShell release, they can then verify the hash against the GitHub published version using the same cmdlet.

**Comment by msftrncs** [comment]
How can this not already be done with the SHA256 hashes that are already published?  `Get-FileHash` supports `-Algorithm SHA256`.   Am I missing something?

**Comment by RealDrGordonFreeman** [comment]
> 
> 
> How can this not already be done with the SHA256 hashes that are already published? `Get-FileHash` supports `-Algorithm SHA256`. Am I missing something?

Yes, you're missing something. The request is to publish hashes, any hashes. Currently there are no hashes available for the release downloads on GitHub. Unless you know where they are.

**Comment by msftrncs** [comment]
https://github.com/PowerShell/PowerShell/releases

**Comment by TravisEz13** [comment]
Here is a screenshot from https://github.com/powershell/powershell/releases which @msftrncs 	mentions:
![image](https://user-images.githubusercontent.com/10873629/54056699-bbf02e80-41a5-11e9-9443-24d85f6732a5.png)

**Comment by RealDrGordonFreeman** [comment]
Thank you! The existence of these hashes need to be known better. It is not obvious and not known where to find them. Anyways, thank you again for pointing out the location.
