### ISSUE TITLE
System.Management.Automation 6.1.3 not compatible with .Net Standard Library

### ISSUE THREAD

**Issue by Safirion** [PowerShell/PowerShell#9062]
I have a projet with a common lib in .Net Standard 2.0 using System.Management.Automation in version 6.1.2. NuGet manager tell me that there is a new version of this package but I can't upgrade it because the  version 6.1.3 don't allow me to target .Net Standard : only .Net Core App 2.1.

https://www.nuget.org/packages/System.Management.Automation/

**Comment by iSazonov** [comment]
PowerShell Core target framework is _always_ .Net Core App because we use some API which are absent in .Net Standard.

**Comment by Safirion** [comment]
Yes, that's what I understood by reading dependencies although they have not changed between 1.6.2 and 1.6.3. So I will create another library in .Net Core App 2.1. You can close this issue.

Thank you 👍

**Comment by WinInsider** [comment]
There is .net standard nuget package (official) PowerShellStandard.Library
