### ISSUE TITLE
previews and prereleases use the same folder

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/PowerShell#9072]
# Support Question
When creating the chocolatey package for the prerelease of 6.2.0-rc1, I noticed it installs to c:\program files\Powershell\6-preview - the same folders as previews.

This makes sense to me as it is non-default version and *should* be an upgrade to a preview - if EVERY prerelease is installed on a given machine.

Does it share MSI component GUIDS and Product Codes with actual previews so that we don't end up with two different MSI products pointing to the same file set?

Also, is the packaging constructed such that the NEXT preview installed after a pre-release will automatically work as expected and intended by MSI?

FYI - I updated the regular package to detect prerelease installation and give proper messaging to users - rather than imply they had upgraded their default, production version.

/cc @TravisEz13

**Comment by iSazonov** [comment]
> Does it share MSI component GUIDS and Product Codes with actual previews

Yes, preview and RC have the same product code, release - another one.

**Comment by DarwinJS** [comment]
Awesome - thanks!

**Comment by TravisEz13** [comment]
In effect, the RC is a special kind of preview.  If that makes sense.  The plan for now is for the stable build to be one continuous upgrade and the previews to be one continuous upgrade until we find something that prevents that plan.
