### ISSUE TITLE
PSVersion 5.1.17763.1 UTF8 characters are lost...

### ISSUE THREAD

**Issue by Hofas** [PowerShell/PowerShell#9083]
# Steps to reproduce

```powershell 5.1.17763.1

```

# Expected behavior

`when i use psreadline no mather what version 1.2 or 2.0 i schuld be able to use UTF-8 cahracters'

```

# Actual behavior

`after upgrade PS to ver. 5.1.17763.1 when i use PSreadline module i can't get east europe characters from utf8 charset , after i uninstall-module psreadline i can use polisch characters freely 
after install once again psreadline module, once agan can't get poslish letters...'

```

# Environment data

 5.1.17763.1

```5.1.17763.1

```

**Comment by vexx32** [comment]
If this is a PSReadLine issue, please open the issue in the [PSReadLine](https://github.com/lzybkr/PSReadLine) repository itself. 🙂
