### ISSUE TITLE
Get-ChildItem interface options are duplicated on the page

### ISSUE THREAD

**Issue by zebfross** [PowerShell/PowerShell#9085]
# Documentation Issue

Also the -Recurse option is on the same line as -Exclude which makes it hard to find and a little confusing.

**Comment by vexx32** [comment]
If you're talking about the syntax diagrams, we're aware they're confusing at the best of times. I have a reference mock-up of how we could start doing it better going forward, and some folks have suggested different colours etc.

The syntax diagrams in documentation are, I believe, generated from the default help output initially, so although doc issues usually don't belong on this repo, there in an issue already for this so we can improve this in the PowerShell engine itself and then propagate the change into documentation.

**Comment by iSazonov** [comment]
@zebfross Please add more information in the issue description.
