### ISSUE TITLE
Can't install on Debian Buster

### ISSUE THREAD

**Issue by kashfshah** [PowerShell/PowerShell#9087]
Operating System: Linux Debian sid (Debian unstable - Debian 10, Buster)
```
$ uname -a
Linux hostname 4.19.0-3-amd64 #1 SMP Debian 4.19.20-1 (2019-02-11) x86_64 GNU/Linux
```
**Description:**

Apparently the Debian 9 installation package depends on an old version of libicu.  Currently depends on libicu57 and doesn't accept libicu63 (Debian 10 default) as satisfying the dependency.

Workaround: use the binary installation instructions at https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-6#binary-archives.

**Install failure:**
```
$ sudo apt-get install -y powershell
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 powershell : Depends: libicu57 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

No packages being held:
`$ sudo apt-mark showhold
`

**Comment by iSazonov** [comment]
The version is still not supported by .Net Core 3.0 https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md
and we can not support it too.

**Comment by kashfshah** [comment]
Installation on Debian 10 Buster (MX Linux) worked without a hitch on .NET Core 3.1 - thanks!
