### ISSUE TITLE
[Bug] `Write-Progress` does not respect the progress colors

### ISSUE THREAD

**Issue by GeeLaw** [PowerShell/PowerShell#9088]
# Steps to reproduce

```powershell
1..100 | foreach {
Write-Progress -Activity 'Test' -PercentComplete $_ -Id 100 -Status 'Sleeping'
sleep -Milliseconds 200
}
Write-Progress -Activity 'Test' -Id 100 -Completed
```

# Expected behavior

The same result as it is on Windows PowerShell, respecting the colors.

<img src="https://user-images.githubusercontent.com/4462444/54039899-e8418600-4178-11e9-91d7-911932d1d908.png" width="270" alt="Windows PowerShell" />

# Actual behavior

<img width="270" alt="PowerShell on macOS" src="https://user-images.githubusercontent.com/4462444/54039865-d7911000-4178-11e9-9fca-67accdfa5132.png">

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.1.2
PSEdition                      Core
GitCommitId                    6.1.2
OS                             Darwin 18.2.0 Darwin Kernel Version 18.2.0: Th...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

`$Host.PrivateData` has the following value (they're customized):

```none
ErrorForegroundColor    : White
ErrorBackgroundColor    : Red
WarningForegroundColor  : Black
WarningBackgroundColor  : Yellow
DebugForegroundColor    : Cyan
DebugBackgroundColor    : Black
VerboseForegroundColor  : DarkYellow
VerboseBackgroundColor  : Black
ProgressForegroundColor : Yellow
ProgressBackgroundColor : DarkCyan
```

The colors I am using.

<img width="222" alt="Terminal colors" src="https://user-images.githubusercontent.com/4462444/54039948-0c9d6280-4179-11e9-9743-3c744b27cf55.png">

**Comment by RDIL** [comment]
Is this Darwin specific?

**Comment by GeeLaw** [comment]
@RDIL : Just had time to test PowerShell core on Windows. The issue doesn't reproduce with the following `$PSVersionTable`:

```none
Name                           Value
----                           -----
PSVersion                      6.1.3
PSEdition                      Core
GitCommitId                    6.1.3
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

I don't have a Linux box available at this momemt.

**Comment by r-darwish** [comment]
I checked 6.2.3. It's broken in both macOS and Linux and works as expected in Windows.
