### ISSUE TITLE
Feature Request: What if $PSScriptRoot returned $PWD when used interactively?

### ISSUE THREAD

**Issue by jazzdelightsme** [PowerShell/PowerShell#9089]
# Summary of the new feature/enhancement

Sometimes when I'm writing a little script, I test out a bit of code by pasting into a console. And if I had a reference to `$PSScriptRoot` in that code, it blows up, usually looking for files in the root of my drive. E.g. `Get-Content "$PSScriptRoot\Version.txt"` turns into `Get-Content "\Version.txt"` (which in turn becomes an access for "C:\Version.txt", which of course does not exist).

The current behavior of `$PSScriptRoot` returning null/empty when there is no script running makes sense from the point of view that, "hey, there is no script, so... no script root". However, in *practice* I think it might be much more convenient for the value of `$PSScriptRoot` to be the current [PowerShell] directory (`$PWD`) when accessed interactively.

This certainly wouldn't solve all uses of `$PSScriptRoot` from the command line (what if you're not in the right directory?), but it would certainly improve a particular common case.

Is this a breaking change? I think it's in the "unlikely grey area" bucket--it seems unlikely that somebody would take a dependency on `$PSScriptRoot` being empty when accessed from the command line (though certainly not impossible, such as if someone tried to write a guard to detect being pasted into a console instead of being run from script).

**Comment by iSazonov** [comment]
It seems we can not detect interactive input.

**Comment by jazzdelightsme** [comment]
@iSazonov : well... what if any time `$PSScriptRoot` is going to return `null`, then just return `$PWD` instead?

**Comment by kvprasoon** [comment]
Making it work interactively will make the name of this variable meaningless.

**Comment by GeeLaw** [comment]
FWIW, `$PSScriptRoot` is the empty string, not `$null`, when used interactively. I don't know if in any possible future we would be working on a platform where the empty string is a valid absolute path.

BTW, don't join paths yourself. Use `[System.IO.Path]::Combine` instead.

**Comment by lzybkr** [comment]
This is an interesting idea, it's definitely tripped me up before.

I do think it's a risky change though - there are too many scenarios where `$PSScriptRoot` might not have a useful value, and I think it's likely real scripts might use that detail in some meaningful way.

Maybe what you really want is to replace `$PSScriptRoot` with `$PWD` when pasting? It seems simple to do as a custom PSReadLine key binding.

**Comment by rkeithhill** [comment]
We've also seen people have issues with this in VSCode with the PowerShell extension when the select script and press <kbd>F8</kbd> to run it in the console. In this case, the extensions "knows" the path for the script.  If we could just **set** the $PSScriptRoot variable in the global session, then <kbd>F8</kbd> would work better for folks.

**Comment by SeeminglyScience** [comment]
For PSRL you can override `PSConsoleHostReadLine` like this

```powershell
function PSConsoleHostReadLineProxy {
    Microsoft.PowerShell.Core\Set-StrictMode -Off
    $command = [Microsoft.PowerShell.PSConsoleReadLine]::ReadLine($host.Runspace, $ExecutionContext)
    $ast = [System.Management.Automation.Language.Parser]::ParseInput(
        $command,
        [ref] $null,
        [ref] $null)

    $findVariablesDelegate = {
        param($a)
        end {
            $a -is [System.Management.Automation.Language.VariableExpressionAst] -and
            $a.VariablePath.UserPath -eq 'PSScriptRoot'
        }
    }

    $variables = $ast.FindAll($findVariablesDelegate, $true) |
        Microsoft.PowerShell.Utility\Sort-Object { $PSItem.Extent.StartOffset } -Descending

    $newPrompt = [System.Text.StringBuilder]::new($command)
    foreach ($variable in $variables) {
        $extent = $variable.Extent
        $null = $newPrompt.
            Remove($extent.StartOffset, $extent.EndOffset - $extent.StartOffset).
            Insert($extent.StartOffset, '$($PWD.ProviderPath)')
    }

    return $newPrompt.ToString()
}

Microsoft.PowerShell.Utility\New-Alias PSConsoleHostReadLine PSConsoleHostReadLineProxy -Force
```

Worth noting though that this won't work in the VSCode preview extension because it doesn't actually call `PSConsoleHostReadLine`.  Maybe that should be revisited though.

**Comment by chriskuech** [comment]
Writing code with `$PSScriptRoot` is a best practice to avoid opaque dependencies on shell location.  However, this makes testing snippets very frustrating, as they must be rewritten.  This feature would be immensely valuable on a daily basis.

**Comment by MartinGC94** [comment]
With the PR: https://github.com/PowerShell/PowerShell/pull/18764 declined, I guess we need to think about some other alternatives for this.  
Ideally the editor would be able to tell PowerShell which file a particular segment came from and also which line. Not only would this make it possible to use `$PSScriptRoot` it would also enable the use of line breakpoints without running the file from the top.  
This could be as simple as adding an overload to `AddScript` (see: https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.powershell.addscript ) to accept a path and start line offset and have editors like VS Code call that with the appropriate parameters.  
I don't know the internals well enough to know if this is realistic though.
