### ISSUE TITLE
Feature Request "ps_modules" as full analogy for "node_modules" and package.psm1 (analogy for package.json)

### ISSUE THREAD

**Issue by dmitriyse** [PowerShell/PowerShell#9098]
# Summary of the new feature/enhancement
## Motivation: 
1) Separated package/module environments for different working folders.
2) Automated install of all modules requested by artifacts in a working folder (analog to package.json)
## Current state
Currently we have only "AllUsers" and "CurrentUser" installation scopes.
## Typical scenario:
For example you have some repository with the collection of powershell scripts which service this repository. These PowerShell scripts are requires big amount of modules.
Typical expected scenario (almost the same as with npm and package.json):
1) Clone repository with the powershell staff 
2) Install required PowerShell modules to subfolder "ps_modules"  (by executing Install-Dependencies command at the working direcotry.
3) Work with repo including execution of repo-local scripts which in turn uses locally installed modules from "ps_modules"
4) Delete working directory
5) Default folders for "CurrentUser" and "AllUsers" scopes do not contains short-term usage modules

# Proposed technical implementation details
## `$PSCurrentModulePath` variable
`$PSCurrentModulePath` - a read-only variable that chenges behavior of all PowerShellGet commands.
Once this variable is not `$null`, Import-Module searches modules from `$PSCurrentModulePath/ps_modules` first.
## `Select-CurrentModule` cmdlet
1) if `$PSCurrentModulePath` is not `$null` than the command unloads all modules that already loaded from the `$PSCurrentModulePath`
2) Switches `$PSCurrentModulePath` to the new location
3) Auto-load modules from the `$PSCurrentModulePath/ps_modules` when commands from `$PSCurrentModulePath/ps_modules` are invoked
## `Install-Module` defaults and and `CurrentModule` scope
1) The new `CurrentModule` scope changes behavior of the `Install-Module` cmdlet and forces it to install module to `$PSCurrentModulePath/ps_modules`
2) if `$PSCurrentModulePath` is not $null then `Install-Module` uses 'CurrentModule` scope by default
## `Install-Module` and additional syntax for `package.psm1` files
1) `package.psm1` should contain metadata with it module requirements like `dependencies` section in an `package.json`
2) When `$PSCurrentModulePath` is not `$null` then Install-Module beside installation of module to `$PSCurrentModulePath/ps_modules` also adds record to the metadat in the `$PSCurrentModulePath/package.psm1`
## `Install-Dependencies` cmdlet
if `$PSCurrentModulePath` is not `$null` than this command should download and install dependencies from the `$PSCurrentModulePath/package.psm1` to the `$PSCurrentModulePath/ps_modules`

# Alternative approach
Utilize npm infrastructure with publishing powershell modules as npm packages and implement the current "node_modules" provider for the PowerShellGet.

**Comment by GeeLaw** [comment]
Have you tried `Save-Module`/`Import-Module`?

```powershell
Function Import-ModuleForDirectory
{
    Get-ChildItem -LiteralPath .\ps_modules\ -Filter *.psm1 -File -Recurse -Force -ErrorAction Ignore |
        Import-Module;
}

Function Get-ModuleForDirectory
{
    Get-Content .\package.json | ConvertFrom-Json | Write-Output |
        ForEach-Object {
            Save-Module $_.Name -Path .\ps_modules\ # blah blah blah
        };
}
```

Also, I'm not sure how `node_modules` work. One problem I find unintuitive: What if you `cd`-ed out of the current folder? Do the modules get automatically unloaded?

**Comment by dmitriyse** [comment]
Yes, I know the current capabilities of PowerShell. 
But it misses two good conceptions from its competitors (Node.Js, Python):
1) Virtual Environments
2) Dependency list to install automatically into virtual environments.

I am working on some solution that solves these pitfalls (after some time I will describe it here).
Also, you can inspect this solution http://ramblingcookiemonster.github.io/PSDepend

**Comment by GeeLaw** [comment]
I read your solutions. There're a few wheels already there.

- You could write a module manifest for your repository to list all the modules you need as the dependencies. It's `requirements.txt` in a different format.
- You can then use `Find-Module -IncludeDependencies`/`Save-Module` to download them into your directory (recursing on the dependencies).
- Set `$env:PSModulePath` environment variable changes the order of module searching. This is the wheel for your proposed `$PSCurrentModulePath`.
- You can then `Import-Module` the repo's module manifest. It will honor the priority set by `$env:PSModulePath`.

**Comment by dmitriyse** [comment]
Yes, there are enough existing PS features to build "PowerShell Virtual Environments" as a Module.
There is a number of some solution but they are not widely used and actively supported.
I think PowerShell requires some "standard" solution. 
I will update this proposal with the working prototype after a week or two.
P.S.
@GeeLaw, thank you for pieces of advice, I exactly used `Find-Module -IncludeDependencies`/`Save-Module` + `$end:PSModulePath`

**Comment by dmitriyse** [comment]
In general, PowerShell requires more efforts to bring to itself best practices and features from other scripting languages: Python, Node.js. Now PowerShell resides on also on the same territory (general cross-platform scripting).

For example, some tool to filter files over directories and subdirectories, Like `Gulp.src()` include/exclude patterns.

Get-ChildItem is very limited and ugly compared to simple and Powerfull Gulp.src.

**Comment by GeeLaw** [comment]
I don't fully understand the benefit of making this part of PowerShell instead of, what you already mentioned, "a module". I think publishing this as a module on PSGallery/GitHub and advocating it in the community is a better idea.

Making this package manager part of PowerShell **couples** the package manager with PowerShell. The package manager is updated only when PowerShell itself is updated. Making this a module available from PSGallery/GitHub allows faster iteration of the package manager, e.g., adding more sources of packages.

If you compare this to `pip`, you have to install Python per-user to update `pip` without administrator privilege. (I don't know whether you could install a per-user version of pip if you installed Python machine-wide, because I never installed it machine-wide...) However, I don't think people update modules that come with PowerShell.

**Comment by dmitriyse** [comment]
>I don't fully understand the benefit of making this part of PowerShell instead of, what you already mentioned, "a module". 

It was my first attempt to solve the problem. Before I found `$env:PSModulePath` and become familar with all existing functions.
I totally agree with you, It would be better to just create new module with additional features.

Some additional function would be great to see for example `Save-Modules -IncludeDependencies` wich inputs "Name, Version" pairs. We have https://github.com/PowerShell/PowerShellGet for that kind of requrests.

I going to close this issue soon with transfer discussion to another repos/issues.

**Comment by GeeLaw** [comment]
+1 for `Save-Module -IncludeDependencies`. I was surprised it didn't exist in the first place.

**Comment by dmitriyse** [comment]
Good News. `Save-Module` already saves all dependencies to a target path.

**Comment by dmitriyse** [comment]
This proposal should be implemented as an additional module.
I have created the first usable version of the proposed feature:
https://www.powershellgallery.com/packages/PSSolutions

This discussion should be transferred to this repo https://github.com/ClrCoder/PSSolutions
