### ISSUE TITLE
The repo website link https://microsoft.com/powershell is broken

### ISSUE THREAD

**Issue by rohith** [PowerShell/PowerShell#9103]
![image](https://user-images.githubusercontent.com/5032439/54088342-30cc8f80-4383-11e9-8ff1-b0b3eda8fc7c.png)

**Comment by kilasuit** [comment]
I think this needs updating to `https://docs.microsoft.com/en-us/powershell/`

**Comment by vexx32** [comment]
Also, `aka.ms/powershell` points to `https://docs.microsoft.com/en-gb/powershell/` which is _better_ but weird that it points to an EN-GB page specifically instead of detecting the user's language.

**Comment by iSazonov** [comment]
@vexx32 I get `https://docs.microsoft.com/en-us/powershell/`

**Comment by rohith** [comment]
@vexx32 even I get `https://docs.microsoft.com/en-us/powershell/`

**Comment by vexx32** [comment]
Weird. I'll have to check what's funky with my region settings, heh. Thanks, fellas. :)

**Comment by rohith** [comment]
Well it seems to be working now
