### ISSUE TITLE
No Example for New-Alias, how to to use it after creating a new alias!!!

### ISSUE THREAD

**Issue by MindFulVoice** [PowerShell/PowerShell#9105]
# Windows PowerShell

For Windows PowerShell 5.1 issues, suggestions, or feature requests please use the following link instead:
Windows PowerShell [UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)

This repository is **ONLY** for PowerShell Core 6 issues.

**Comment by vexx32** [comment]
```powershell
PS> New-Alias -Name ddd -Value 'Get-ChildItem'
PS> ddd
```

Aliases are called like any other command. 🙂

**Comment by MindFulVoice** [comment]
I was trying to do
ps>new-alias toRootDir 'cd c:\'
ps>toRootDir
Did not work, there must be a reason, why it does not, when they designed
this feature. :-)

**Comment by vexx32** [comment]
Aliases are designed to essentially just register a new name for the same command, and don't really provide for supplying arguments as well. For example, `cd` is an alias to `Set-Location`. You can provide it all the same arguments, but it supplies no arguments of its own.

For what you want, you'd simply define a new function:
```powershell
function toRootDir { Set-Location 'C:\' }
```

**Comment by MindFulVoice** [comment]
Thanks for the solution.

I work on Linux also, so the aliases under Linux shells, do allow
arguments.
So when you want to design something, e.g. alias under powershell,
you would do some research to see in other platforms, how they have
implemented,
and take the best or if possible improve upon it. That is why it is
baffling.
Of course you can say that the Linux implementation is wrong, as far as the
definition of alias goes.
I am sure some body in the microsoft design team had a good reason not to
support the alias arguments.
Just thinking out loud.

Thanks
sguha
