### ISSUE TITLE
Performance problem: -Name slows down Get-ChildItem -Recurse

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#9119]
`-Name` is a convenient switch to only output item _names_  (without `-Recurse`) or _relative paths_ (with `-Recurse`).

Given that only _string_ instances rather than `System.IO.File/DirectoryInfo` instances are output, one would expect `-Name` to speed things up (or at least not to slow things down); however, with `-Recurse` present, `-Name` _slows down_ the command noticeably.

# Steps to reproduce (on Windows)

```powershell
# Warm up the cache
$null = Get-ChildItem -Recurse 'C:\Program Files' 

# Without -Name
(Measure-Command { Get-ChildItem -Recurse 'C:\Program Files' }).TotalSeconds

# With -Name
(Measure-Command { Get-ChildItem -Name -Recurse 'C:\Program Files' }).TotalSeconds
```

# Expected behavior

The command with `-Name` should be faster (or at least not slower).

# Actual behavior

Sample timings:

```none
1.544098   # without -Name
4.5759553  # with -Name
```

That is, adding `-Name` made the command about 3 times _slower_.

# Environment data

```none
PowerShell Core 6.2.0-preview.4
```

**Comment by iSazonov** [comment]
I expect #8995 will address this.

**Comment by ericdching** [comment]
It looks like this issue is more pronounced in Powershell 7.0.

Running the following command from a nodeJS project:
```
Get-ChildItem -Recurse -Name
```
Returns 12886 files.

**PowerShell 6.2.3**

Without -Name

```
IsRunning Elapsed          ElapsedMilliseconds ElapsedTicks
--------- -------          ------------------- ------------
    False 00:00:00.7503959                 750    750395941
```

With -Name

```
IsRunning Elapsed          ElapsedMilliseconds ElapsedTicks
--------- -------          ------------------- ------------
    False 00:00:01.3749722                1374   1374972263
```

**PowerShell 7.0.0-rc.1**

Without -Name
```
IsRunning Elapsed          ElapsedMilliseconds ElapsedTicks
--------- -------          ------------------- ------------
    False 00:00:00.6832990                 683    683299055
```

With -Name

```
IsRunning Elapsed          ElapsedMilliseconds ElapsedTicks
--------- -------          ------------------- ------------
    False 00:00:09.0078861                9007   9007886141
```

I see similar results for both macOS and Windows.

**Comment by iSazonov** [comment]
I guess this perf regressions comes from https://github.com/PowerShell/PowerShell/pull/9250
If previously I thought Kaspersky AV slow down file operations, now I tested with Microsoft AV.
![image](https://user-images.githubusercontent.com/22290914/71713470-b4340180-2e2b-11ea-8877-dae5ae19981c.png)

**Comment by SteveL-MSFT** [comment]
@iSazonov that method should be called in all cases, and not just when `-Name` is used

**Comment by SteveL-MSFT** [comment]
Seems like we should expose an overload to `GetChildNames()` to accept recursion.  Then the FileSystemProvider can implement this and simply use `EnumerateFileSystemEntries()` to quickly return just the names.   In `SessionStateContainer.cs`, it would try the overload first, but not all providers implement it and fallback to current behavior.  Since this is not a mainline issue, not going to implement this for now.

**Comment by iSazonov** [comment]
> that method should be called in all cases, and not just when -Name is used. 

@SteveL-MSFT For `dir -Recurse` it is called 3 times for root directory, for `dir -Recurse -Name` - 3 times for every subdirectory and 1 time for every file.

**Comment by SteveL-MSFT** [comment]
@iSazonov yes, because when `-Recurse` and `-Name` is used together, the recursion is done outside of the `FileSystemProvider` so each call into the provider results in a call to `GetCorrectCasedPath()`.  However, there's actually a lot of other work happening because of the manual recursion than just that API call.  The `FileSystemProvider` can leverage the `EnumerateFileSystemEntries()` to just get the names, but the current interface doesn't expose such a call into the provider.

**Comment by HumanEquivalentUnit** [comment]
I found `-Name` makes things slower; @jborean93 looked into it and suggested this possible cause:

- The strings are decorated with .PSPath, .PSParentPath, .PS... properties.

- Normally a FileInfo is returned from the FileSystem Provider, the Provider Base adds these decorators.
- With `-Name`, a FileInfo is made but only the name string is returned, the Provider Base then resolves the string to a path and another FileInfo is made to add these extended properties. 
- `-Name` ends up doing more work.

This code may be involved:

- FileSystemProvider.cs [writing either a FsInfo or FsInfo.Name to the output](https://github.com/PowerShell/PowerShell/blob/26f621952910e33840efb0c539fbef1e2a467a0d/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L1542-L1552)
- ProviderBase.cs [wrapper code](https://github.com/PowerShell/PowerShell/blob/26f621952910e33840efb0c539fbef1e2a467a0d/src/System.Management.Automation/namespaces/ProviderBase.cs#L1756-L1860)
