### ISSUE TITLE
Get-ChildItem -Name adds provider NoteProperty members, Get-ChildItem -Name -Recurse does not

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#9120]
Perhaps surprisingly, using `-Name` decorates the _strings_ being output with NoteProperty members from the underlying PS provider, such as `.PSPath`, just as with the default output types (e.g., `System.IO.FileInfo` / `System.IO.DirectoryInfo` for the filesystem provider).

However, this currently happens inconsistently, namely only if `-Recurse` isn't also specified.

As an aside: providing a way to opt out of this decoration (`-Raw`) may be helpful for performance reasons; see also: #9119 

# Steps to reproduce

Run the following Pester test:

```powershell
Describe "Get-ChildItem -Name provider-properties test" {
  It "-Name adds provider properties" {
    Get-ChildItem / -Name | Select-Object -First 1 | Get-Member -Name PSPath | Should -Not -BeNullOrEmpty
  }
  It "-Name -Recurse adds provider properties too" {
    Get-ChildItem / -Name -Recurse | Select-Object -First 1 | Get-Member -Name PSPath | Should -Not -BeNullOrEmpty
  }
}

```

# Expected behavior

Both tests should pass.

# Actual behavior

```none
Executing script ....Tests.ps1

  Describing Get-ChildItem -Name provider-properties test
    [+] -Name adds provider properties 612ms
    [-] -Name -Recurse adds provider properties too 156ms
      Expected a value, but got $null or empty.
      6:     Get-ChildItem / -Name -Recurse | Select-Object -First 1 | Get-Member -Name PSPath | Should -Not -BeNullOrEmpty
      at <ScriptBlock>, ....Tests.ps1: line 6
```

# Environment data

```none
PowerShell Core 6.2.0-preview.4
Windows PowerShell v5.1.17134.407
```

**Comment by ChrSchultz** [comment]
same behavior in PowerShellCore 6.1.1,

**Comment by iSazonov** [comment]
Related #8995
