### ISSUE TITLE
Feature Request: allow switch to support collection of conditions per condition statement block

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PowerShell#9125]
# Summary of the new feature/enhancement

`switch` could use to support an array of condition arguments per each condition statement block.  This would have effectively be the same as `-in item1, item2, …`

IEC 61131-3 (similar to Pascal) supports this with their `CASE {expression} OF` statement.

```PASCAL
ACTION	CleanUp:
(* Processing CleanUp, intended for the CAN implementation to utilize if Request_RESULT is > 1 prior
   to processing of the next received request. *)
(* handle cleanup if application doesn't react to Request_RESULT, as its not really required to *)
CASE Request_RESULT OF
2,3:
	(* download or upload request was not acted upon, must be an invalid object *)
	TX_ERR_INV_OBJ(); (* object of request must have been invalid and could not be found *)
4,5:
	(* when = 4, application must have accepted the download completion without error *)
	Request_RESULT := SEL( ActXfr_Dn OR ActXfr_Up, 0, 1 );
6:
	(* application accepted an upload request which coincides with an active download,
	   the download is being aborted, so notify the application.  *)
	Request_RESULT := 5;
7:
	(* application must have accepted the expedited download without error *)
	TX_ACK_EXP_DN();
END_CASE

END_ACTION
```

EDITED: Here is an example application except, where `switch` replaces `foreach` and a set of `if`/`elseif` statements.

```PowerShell
# iterate through the rule set and capture the possible scope names
foreach ($key in $ruleset.PSObject.Properties.Name) {
	if ($key -cin 'name', 'contentName') {
		# return the specified scope selectors
		$ruleset.PSObject.Properties[$key].Value
	}
	elseif ($key -cin 'patterns') {
		foreach ($rule in $ruleset.PSObject.Properties[$key].Value) {
			# recurse the contained patterns
			getscopes_recurse $rule
		}
	}
	elseif ($key -cin 'beginCaptures', 'captures', 'endCaptures', 'repository') {
		foreach ($prop in $ruleset.PSObject.Properties[$key].Value.PSObject.Properties) {
			# recurse the sub-items, note that we don't keep the sub-items names, including the sub-repositories
			getscopes_recurse $prop.Value
		}
	}
}
```

as

```PowerShell
# iterate through the rule set and capture the possible scope names
switch -CaseSensitive ($ruleset.PSObject.Properties.Name) {
	name, contentName {
		# return the specified scope selectors
		$ruleset.PSObject.Properties[$_].Value
		continue
	}
	patterns {
		foreach ($rule in $ruleset.PSObject.Properties[$_].Value) {
			# recurse the contained patterns
			getscopes_recurse $rule
		}
		continue
	}
	beginCaptures, captures, endCaptures, repository {
		foreach ($prop in $ruleset.PSObject.Properties[$_].Value.PSObject.Properties) {
			# recurse the sub-items, note that we don't keep the sub-items names, including the sub-repositories
			getscopes_recurse $prop.Value
		}
		continue
	}
}
```
(notice the arguments not requiring quotes)

Another simpler example:
```PowerShell
    hidden [object] GetAddress () {
        return $(switch ($this.RecType.value__) {
            0 {$this.GetAddress16()}
            1 {$this.GetAddress16()}
            2 {$this.GetAddress24()}
            3 {$this.GetAddress32()}
            5 {$this.GetAddress16()}
            6 {$this.GetAddress24()}
            7 {$this.GetAddress32()}
            8 {$this.GetAddress24()}
            9 {$this.GetAddress16()}
        })
    }
```
vs
```PowerShell
    hidden [object] GetAddress () {
        return $(switch ($this.RecType.value__) {
            0, 1, 5, 9 {$this.GetAddress16()}
            2, 6, 8 {$this.GetAddress24()}
            3, 7 {$this.GetAddress32()}
        })
    }
```

Since the `switch` statement already breaks up sets, and the engine already errors if it finds a comma in the condition argument, I cannot see a reason this couldn't be implemented.   The confusion might come, on what other ways can a collection of condition values be passed.  I don't think there would be any other ways.

`value1, value2, value3` - this is 3 conditions
`(value1, value2, value3)` - this is a single condition of a collection of 3 values (and is currently supported)

**Comment by msftrncs** [comment]
I have updated above my somewhat poorly configured first comparison

I might add, that IEC 61131-3 also supports a range condition (using `..`) in its `CASE`, but that might not be so easy to implement, as the range operator wouldn't be available with the argument syntax currently employed by PowerShell's `switch`.  IEC 61131-3's `CASE` was only meant for numeric values.

**Comment by vexx32** [comment]
One option is to _actually_ use the -in operator (or indeed any other).

```powershel
switch ($values) {
    {$_ -in 1, 2, 3} {
        "Value was 1, 2, or 3"
    }
}
```

**Comment by msftrncs** [comment]
@vexx32, correct, I originally had this code (first comparison) configured that way, but it didn't seem to benefit the application at that time but I had other issues as well, due to needing to access the names of the properties of the PSCustomObject returned from ConvertFrom-JSON, so I had rewritten it to the way the first comparison shows.

**Comment by vexx32** [comment]
Not sure I follow what you're trying to achieve here. It sounds like it should be doable with what we have already.

What are you looking to accomplish?

**Comment by msftrncs** [comment]
What I am proposing is just a syntactically shorter way (specifically for `-in` applications).  The difference is after using `{$_ -in (collection)}`, and then being sure to use `continue`, I might as well use `if` and `elseif`, which is why I switched my code back to that method.  My original code example however didn't originally use the property names, instead iterating on the entire property requiring the longer `{$_.Name -cin (collection of strings)}`.

Also notice that single word simple string values do not need quotes if they are the argument of the condition, but they do when they are the operand of an operator.  That is what defeats the possible use of the range operator, however.

**Comment by lzybkr** [comment]
I'm definitely in favor of improvements, but have concerns over breaking existing scripts.

Today this "works" though the behavior is surprising:

```powershell
switch ("1 2 3") {
    (1,2,3) {'matched'}
}
```

This syntax is dangerously close to your obvious syntax.

I know some folks would like something more like the `match` expression in F# or Rust - that might be an option to have a `switch` that is less surprising without the worries about compatibility.

At any rate, it would be good to see a RFC for a change like this, regardless of the eventual proposal.

**Comment by msftrncs** [comment]
Is there any concern here of breaking existing scripts, so far with what I propose here?  My experimentation so far suggests that a comma separated value is not currently directly supported, so while `(1,2,3)` is valid and works as you describe, `1, 2, 3` is not currently valid and generates an error.
