### ISSUE TITLE
[Experimental Feature PSTempDrive ] Temp: not accessible.

### ISSUE THREAD

**Issue by ChrSchultz** [PowerShell/PowerShell#9131]
# Steps to reproduce

```

1. Enable-ExperimentalFeature PSTempDrive
2. restart Powershell
3. Get-PSDrive, verify Temp   .... Filesystem    C:\Users\<username>\AppData\Local\Temp is listed
4. enter Temp:\ to acces PSTempDrive  



```

# Expected behavior
changing to ~/Temp, 

# Actual behavior

```
Temp:\ : The term 'Temp:\' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Temp:\
+ ~~~~~~
+ CategoryInfo          : ObjectNotFound: (Temp:\:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```

# Environment data
Windows 10. 0.17763 64-bit.

----                           -----
PSVersion                      6.2.0-rc.1
PSEdition                      Core
GitCommitId                    6.2.0-rc.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by vexx32** [comment]
This is a bit of a fun one, actually. If I recall carrectly, `C:` and similar are *actual defined functions*, not something PS knows how to figure out on its own.

I guess @SteveL-msft forgot to add one for `Temp:`

**Comment by mklement0** [comment]
Good point, @vexx32, though note that this nod to `cmd.exe` is only applied to "native" filesystem drives, not to _PS_ drives such as `Temp:`, so I don't think anything needs to be done here.

**Comment by GeeLaw** [comment]
This has always been the case -- you can't `HKLM:` or whatever, and you can't `C:\`. The command `C:` is there for Command Prompt users.

BTW, `C:` is not `Set-Location -LiteralPath C:\`, it's `Set-Location -LiteralPath C:`, which preserves the current directory of drive C. This is a legacy of the transition from DOS to Windows.
