### ISSUE TITLE
 Get-Item with stream:  Unable to load DLL 'api-ms-win-core-file-l1-2-2.dll'

### ISSUE THREAD

**Issue by s-shamesmuhametov-parc** [PowerShell/PowerShell#9144]
# Steps to reproduce

```powershell
Get-Item test.txt -Stream *
```

# Expected behavior

```none
Success result info.
```

# Actual behavior

```none
Get-Item : Unable to load DLL 'api-ms-win-core-file-l1-2-2.dll' or one of its dependencies: Не найден указанный модуль. (Exception from HRESULT: 0x8007007E)
```

$error[0] | fl * -force
```none
PSMessageDetails      :
Exception             : System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-file-l1-2-2.dll' or one of its dependencies: Не найден указанный модуль. (Exception from HRESULT: 0x8007007E)
                           at System.Management.Automation.Internal.AlternateDataStreamUtilities.NativeMethods.FindFirstStreamW(String lpFileName, StreamInfoLevels InfoLevel, AlternateStreamNativeData lpFindStreamData, UInt32 dwFlags)
                           at System.Management.Automation.Internal.AlternateDataStreamUtilities.GetStreams(String path)
                           at Microsoft.PowerShell.Commands.FileSystemProvider.GetItem(String path)
                           at System.Management.Automation.SessionStateInternal.GetItemPrivate(CmdletProvider providerInstance, String path, CmdletProviderContext context)
TargetObject          :
CategoryInfo          : NotSpecified: (:) [Get-Item], DllNotFoundException
FullyQualifiedErrorId : System.DllNotFoundException,Microsoft.PowerShell.Commands.GetItemCommand
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

# Environment data

OS:  Windows 8.1 x64 (6.3.9600)
 $PSVersionTable
```none
Name                           Value
----                           -----
PSVersion                      6.1.3
PSEdition                      Core
GitCommitId                    6.1.3
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@SteveL-MSFT @adityapatwardhan We could fix this in the same way as #10417.

**Comment by SteveL-MSFT** [comment]
@iSazonov yeah, that might be ok

**Comment by eabase** [comment]
@SteveL-MSFT 
Is there a work around for those of us who doesn't have (or are able to run) pwsh 7+?

**Comment by iSazonov** [comment]
@eabase If it is so important for you, you could fork and make custom 6+ build.

**Comment by eabase** [comment]
> 
@iSazonov 

> If it is so important for you, you could fork and make custom 6+ build.

Sorry Ilya, I don't quite have the dev skills to make custom PWSH builds to fix things that should already work. However, the MS docs is referring to be able to use this, so surely there must be a simple way to work around this. The question is where that DLL is supposed to be, and why it's not there in the first place. Since the others are there. There are several similarly named DLLs...so what make this one so different?

**Comment by iSazonov** [comment]
@eabase I don't experience in the area but I think a root of the issue is that we are targeting Win7 in build but the dll is for Windows 8 or Windows 10. Numbers is the dll name indicate this difference.

**Comment by eabase** [comment]
@iSazonov 

> .I think a root of the issue is that we are targeting Win7 in build but the dll is for Windows 8 or Windows 10. Numbers is the dll name indicate this difference.

Not sure I completely understand. Are you saying that you're targeting W7 and therefore the W8,W10 DLL's are not being built? 
(I'm on W81 for all practical purposes here.)

**Comment by iSazonov** [comment]
Yes, we use Win7-x64 target for compile PowerShell release version.

**Comment by eabase** [comment]
1. Does that mean that it's missing also for W10?
2. Can we copy a DLL from another Windows version (or somewhere else)? 
3. Can you provide a DLL I can test with? (or where I can find it?)

**Comment by iSazonov** [comment]
1. Since we compile with Win7-x64 the dll is absent on all versions.
2. You can, no fix is planned in the repo.
3. The dll should in umbrella lib but I found two reference
https://docs.microsoft.com/en-us/windows/win32/apiindex/windows-umbrella-libraries
https://docs.microsoft.com/en-us/uwp/win32-and-com/win32-apis

Also you could find apisets dlls in c:\windows\system32\downlevel. The dll should be only on old Windows 10 version (10.0.10586)
https://docs.microsoft.com/en-us/uwp/win32-and-com/win32-apis
