### ISSUE TITLE
WSL + tmux + pwsh (latest) + outputing obj converted from large nested JSON + [Ctrl-C] = hang

### ISSUE THREAD

**Issue by tigerinus** [PowerShell/PowerShell#9147]
# Steps to reproduce

1. Setup TMUX with split pane in WSL (debian) on Windows 10.
2. Run pwsh in one of the split pane
3. Run
```powershell
$tt = cat ./adept-transform-excluded-1-2019-03-15-14-30-18-3c343d77-2a4e-4816-8510-6610e9f35325 | ForEach-Object {$_ | ConvertFrom-Json}     # where the file contains about 5000 json docs, where each doc has a 'message' string property which contains escaped JSON doc
$ttt = $tt.message | ForEach-Object {$_ | ConvertFrom-Json}
$ttt # starts writing a lot of text to screen
```
4. Hit [Ctrl - C] trying to stop the output.

# Expected behavior
It goes back pwsh prompt

# Actual behavior
It hangs. Have to kill pwsh process 

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.1.3
PSEdition                      Core
GitCommitId                    6.1.3
OS                             Linux 4.4.0-17763-Microsoft #379-Microsoft Wed Mar 06 19:16:00 PST 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

# Sample JSON doc (with confidential info deleted)

```json
{"message": "{\"remote_addr\": \"x.x.x.x\", \"body\": {\"query\": \"serum\", \"size\": \"1\"}, \"headers\": {\"X-REAL-IP\": \"x.x.x.x\", \"CONNECTION\": \"upgrade\", \"HOST\": \"x.x.x.x\", \"CONTENT-LENGTH\": \"31\", \"CONTENT-TYPE\": \"application/json\", \"ACCEPT\": \"*/*\", \"ACCEPT-ENCODING\": \"gzip, deflate\", \"USER-AGENT\": \"Python/3.6 aiohttp/3.5.1\", \"X-CLOUD-TRACE-CONTEXT\": \"6d991cb1200242818619a6a082535c5d/1962556942779393608\", \"VIA\": \"1.1 google\", \"X-FORWARDED-FOR\": \"x.x.x.x, x.x.x.x\", \"X-FORWARDED-PROTO\": \"https\"}}", "service_metadata": {"created_at": 1551306683.69, "username": "ubuntu", "pid": 24960, "ppid": 24957, "cwd": "/home/ubuntu/adept-search", "name": "gunicorn", "uids": [1000, 1000, 1000], "cpu_info": {"user_time": 0.52, "system_time": 0.25, "percent": 0.0}, "memory_info": {"rss": 65994752}, "connections": [["0.0.0.0", "4000"]]}, "id": "c69a1240-ca5c-43c0-aa96-ba146eed49e7"}
```

**Comment by SteveL-MSFT** [comment]
@tigerinus Does this repro on Linux outside of WSL?  Would help to identify if this is something we need to investigate in PSCore6 vs something in WSL.  Thanks

**Comment by tigerinus** [comment]
@SteveL-MSFT I tried the same steps on a AWS VM running Amazon Linux 2, but I couldn't repro this issue.

I feel it could be either pwsh or WSL when handling stdout/stderr with TMUX in split panel.

I am using TMUX 2.8

Not a big deal. It's just a developer experience issue at commandline.

**Comment by SteveL-MSFT** [comment]
@tigerinus Did you use pwsh with your AWS VM?  Making sure what you mean by "couldn't repro this issue".   If you remove WSL from the equation and it does't repro, then you probably need to open an issue here https://github.com/Microsoft/WSL.  If it repros with pwsh outside of WSL, we can certainly take a look.

**Comment by tigerinus** [comment]
This happens again and it starts getting annoying.

I honestly don't have a strong proof that this is an issue in pwsh. However I did capture a full dump (`createdump -f` under lldb) and uploaded at https://1drv.ms/u/s!AjMewDztobzRgxeaNvNay8fT6P2b

Hope it helps triaging the issue further.

**Comment by SteveL-MSFT** [comment]
My suspicion is that there is an issue with WSL emulation of the Linux kernel.  There are some improvements to WSL that may resolve this, so at this point, I would probably suggest waiting until then to see if it still repros.

**Comment by iSazonov** [comment]
Since Windows moved to WSL-2 we could close the issue.

**Comment by rkeithhill** [comment]
The version of Windows that supports WSL2 doesn't ship for at another 6 months.  And when it does ship it will still support both WSL1 and WSL2.

**Comment by iSazonov** [comment]
I guess that MSFT will have no investments to WSL1 and we should not expect corrections there.

**Comment by SteveL-MSFT** [comment]
Regardless, this appears to be an external issue we can't fix in PowerShell.
