### ISSUE TITLE
Parameters with no Position Attribute not defaulting to 'Named'

### ISSUE THREAD

**Issue by dotps1** [PowerShell/PowerShell#9151]
# Steps to reproduce

```powershell
function foo-bar {
    [CmdletBinding()]
    [OutputType()]

    param (
        [Parameter()]
        [String[]]
        $MyParam
    )
}
```

Generate markdown help with platyPS, and the parameter `MyParam` will have a position attribute value of `0` rather than named.  This is not a platyPS issue, as that just generates help based on what its given, so PowerShell is handing this value to platyPS, this is just a and easy way to see the data.  you can see a real example of this happening in my WinSCP PowerShell repo: https://github.com/dotps1/WinSCP/issues/92

# Expected behavior

`Position: Named`

# Actual behavior

`Position: 0`

# Environment data

```none
PSVersion                      6.1.3
PSEdition                      Core
GitCommitId                    6.1.3
OS                             Darwin 18.2.0 Darwin Kernel Version 18.2.0: T...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
This can also be seen by defining a test function as an advanced function and pulling `Get-Help -Parameter *`:

```powershell
PS> function Test-Function {
>> [CmdletBinding()]
>> param(
>> $One,$Two,$Three
>> )
>> }
PS> Get-Help Test-Function -Parameter *
```
Output:
```

-One <Object>

    Required?                    false
    Position?                    0
    Accept pipeline input?       false
    Parameter set name           (All)
    Aliases                      None
    Dynamic?                     false


-Three <Object>

    Required?                    false
    Position?                    2
    Accept pipeline input?       false
    Parameter set name           (All)
    Aliases                      None
    Dynamic?                     false


-Two <Object>

    Required?                    false
    Position?                    1
    Accept pipeline input?       false
    Parameter set name           (All)
    Aliases                      None
    Dynamic?                     false
```

**Comment by RichardSiddaway** [comment]
By default function parameters are positional

From the help file about_Functions_Advanced_Parameters

By default, all function parameters are positional. PowerShell assigns
position numbers to parameters in the order in which the parameters are
declared in the function. To disable this feature, set the value of the
PositionalBinding argument of the CmdletBinding attribute to $False.The
Position argument takes precedence over the value of the PositionalBinding
argument for the parameters on which it is declared. For more information,
see PositionalBinding in about_Functions_CmdletBindingAttribute.

**Comment by dotps1** [comment]
I tried this already.  Same behavior.

Sent from my iPhone

On Mar 16, 2019, at 12:15 PM, RichardSiddaway <notifications@github.com<mailto:notifications@github.com>> wrote:


By default function parameters are positional

From the help file about_Functions_Advanced_Parameters

By default, all function parameters are positional. PowerShell assigns
position numbers to parameters in the order in which the parameters are
declared in the function. To disable this feature, set the value of the
PositionalBinding argument of the CmdletBinding attribute to $False.The
Position argument takes precedence over the value of the PositionalBinding
argument for the parameters on which it is declared. For more information,
see PositionalBinding in about_Functions_CmdletBindingAttribute.

**Comment by vexx32** [comment]
🤔 OK, just re-tested my quick-test in PS w/o PlatyPS. That _does_ seem to work for PS's builtin help.

I guess PlatyPS must not be checking that value.

```
PS C:\Users\Joel> function Test-Function {
>> [CmdletBinding(PositionalBinding=$false)]
>> param(
>> $One,$Two,$Three
>> )
>> }
PS C:\Users\Joel> test-function
PS C:\Users\Joel> get-help test-function -parameter *

-One <Object>

    Required?                    false
    Position?                    Named
    Accept pipeline input?       false
    Parameter set name           (All)
    Aliases                      None
    Dynamic?                     false


-Three <Object>

    Required?                    false
    Position?                    Named
    Accept pipeline input?       false
    Parameter set name           (All)
    Aliases                      None
    Dynamic?                     false


-Two <Object>

    Required?                    false
    Position?                    Named
    Accept pipeline input?       false
    Parameter set name           (All)
    Aliases                      None
    Dynamic?                     false
```

**Comment by dotps1** [comment]
Interesting.  I only tested with platyPS, I’ll move this issue over there then.  Thanks!!

Sent from my iPhone

On Mar 16, 2019, at 12:44 PM, vexx32 <notifications@github.com<mailto:notifications@github.com>> wrote:


🤔 OK, just re-tested my quick-test in PS w/o PlatyPS. That does seem to work for PS's builtin help.

I guess PlatyPS must not be checking that value.

PS C:\Users\Joel> function Test-Function {
>> [CmdletBinding(PositionalBinding=$false)]
>> param(
>> $One,$Two,$Three
>> )
>> }
PS C:\Users\Joel> test-function
PS C:\Users\Joel> get-help test-function -parameter *

-One <Object>

    Required?                    false
    Position?                    Named
    Accept pipeline input?       false
    Parameter set name           (All)
    Aliases                      None
    Dynamic?                     false


-Three <Object>

    Required?                    false
    Position?                    Named
    Accept pipeline input?       false
    Parameter set name           (All)
    Aliases                      None
    Dynamic?                     false


-Two <Object>

    Required?                    false
    Position?                    Named
    Accept pipeline input?       false
    Parameter set name           (All)
    Aliases                      None
    Dynamic?                     false
