### ISSUE TITLE
A [decimal]-typed RHS in an arithmetic operation unexpectedly forces the result into a [decimal], which can fail

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#9154]
Generally, PowerShell retains the data type of the LHS in an arithmetic operation, if the LHS's data type is already wide enough / supports non-integral numbers in order to accommodate the result.

With a `[decimal]`-typed RHS, that appears not to be the case - the `[decimal]` type is enforced as the result type, which can break the calculation.

Perhaps was the idea was not to lose precision, which could happen if the `[decimal]` were converted to a `[double]`, but the behavior is both inconsistent and surprising.

# Steps to reproduce

Divide an (implicitly typed) `[double]` by an (implicitly typed) `[decimal]`.

```powershell
79228162514264337593543950335.0 / 10000000000000000000
```

# Expected behavior

```none
7922816251.42643
```

That is, the result should be a `[double]`,  as you would get if you forced the RHS to a `[double]` too (`79228162514264337593543950335.0 / 10000000000000000000.0`)

# Actual behavior

The following error occurs:

```none
Value was either too large or too small for a Decimal.
...
```

# Environment data

```none
PowerShell Core 6.2.0-rc.1
Windows PowerShell v5.1 
```

**Comment by msftrncs** [comment]
Why does specifying a trailing `.0` force a number which can be represented as a [decimal] to be represented as a much less capable [double]?   The trailing zero has no value in the representation of the number, either in resolution or scale, only certainty, and neither double nor decimal have provision for certainty (at least not of the decimal portion).  In otherwords, the error is wrong, the value is not too large for a [decimal].  However, after its converted to [double], the loss of precision results in a rounding up, so later when it tries to implicitly convert it to a higher precision type ([decimal]) the number is just now too big).

I think conversions are always towards the type that has the highest precision (which is almost always the type that takes more space), not the type that is either left or right.

**Comment by vexx32** [comment]
Conversions are usually to the type on the LHS. If both types are numeric, then both types are cast into the numerically "wider" type of the two (whichever can hold the larger values, essentially, which is not necessarily the highest precision).

`1.0` is parsed into a `double` the exact same way in c# and probably other languages also. Double is the default floating-point number for powershell. If you want it to be a decimal, you need to apply the `d` suffix: `1.0d`
