### ISSUE TITLE
enable  port forwarding within PowerShell

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#9158]
The very cool features on linux is about the port forwarding when we ssh to a remote server.
I hope PowserShell come with these cool things.

**Comment by iSazonov** [comment]
PowerShell doen't implement a transport but uses ssh as transport. So the feature you request is ssh feature and you can use it directly from ssh.

**Comment by JustinGrote** [comment]
@tlsalex Put another way, you can run ssh.exe just fine in a powershell console. Port forwarding is an SSH feature, not a "linux" feature, and you can do this on Windows with Putty (Plink) or Win32_OpenSSH, or Mac with OpenSSH, and you can run both commands from inside a powershell console, so what you want already exists! 👍
