### ISSUE TITLE
pwsh 6.2.0-rc.1 No Code Highlighting

### ISSUE THREAD

**Issue by YuriySamorodov** [PowerShell/PowerShell#9168]
Simple as that,
Code is not being highlighted in pwsh 6.2.0-rc.1

# Steps to reproduce

```powershell
$host
```

# Expected behavior
![image](https://user-images.githubusercontent.com/5260172/54635527-68c78700-4a95-11e9-8704-7e148db82165.png)

# Actual behavior
![image](https://user-images.githubusercontent.com/5260172/54635542-75e47600-4a95-11e9-9053-77694c9e47fa.png)

# Environment data

```none
Name             : ConsoleHost
Version          : 6.2.0-rc.1
InstanceId       : 20ad1bf2-69de-44e5-9baa-0321535fb2dd
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

**Comment by vexx32** [comment]
Call `Get-Module` and check that `PSReadLine` is imported?

If not, try to import it manually with `Import-Module` and see if there are any errors on import. 😄

**Comment by YuriySamorodov** [comment]
@vexx32 ```PSReadLine``` imported successfully. No difference:
![image](https://user-images.githubusercontent.com/5260172/54636865-5f8be980-4a98-11e9-9edf-969fc32cd671.png)

**Comment by vexx32** [comment]
@YuriySamorodov what output do your get from `Get-PSReadLineOption`?

**Comment by YuriySamorodov** [comment]
@vexx32 
```Output
Get-PSReadLineOption : The type initializer for 'Microsoft.PowerShell.PSConsoleReadLine' threw an exception.
At line:1 char:1
+ Get-PSReadLineOption
+ ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Get-PSReadLineOption], TypeInitializationException
+ FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.PowerShell.GetPSReadLineOption
```

**Comment by vexx32** [comment]
Looks like the little birdie on the PowerShell Discord was correct. 

What's your keyboard layout?

/cc @lzybkr @SteveL-MSFT

**Comment by YuriySamorodov** [comment]
@vexx32 I have two: en-US (main) and ru-RU (secondary)

**Comment by SteveL-MSFT** [comment]
@YuriySamorodov There's a known issue with non en-US keyboard layouts and PSReadLine 2.0.0-beta3.  A fix has already been made in master branch of PSReadLine, but there hasn't been a release yet.  Working with @lzybkr on getting a release out.

**Comment by YuriySamorodov** [comment]
@SteveL-MSFT @lzybkr Probably we can reference issues #9168 #9169 and PSReadline bug you were working on?

**Comment by SteveL-MSFT** [comment]
This should be addressed by https://github.com/lzybkr/PSReadLine/pull/831
