### ISSUE TITLE
SSH_AUTH_SOCK not set properly on macOS

### ISSUE THREAD

**Issue by Xatter** [PowerShell/PowerShell#9173]
On MacOS setting `pwsh` as the default shell does not inherit `SSH_AUTH_SOCK` correctly.
It is set when the default shell is any of `bash`, `zsh`, `sh`, `csh`, `ksh`, `tcsh` and even an upgraded `/usr/local/bin/bash` 4.0

# Steps to reproduce
Install powershell in your favorite way. 
`brew install powershell`

Add shell as valid
`sudo bash -c 'echo /usr/local/bin/pwsh >> /etc/shells'`

change default shell to be powershell
`chsh -s /usr/local/bin/pwsh`

Open new terminal window
Attempt to ssh to a box using public key authentication
ERROR
check environment
`env`

`SSH_AUTH_SOCK` is set incorrectly

# Expected behavior

`SSH_AUTH_SOCK` is set/inherited correctly from `launchd` as `SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.GeBuqoT3cx/Listeners`

# Actual behavior
`SSH_AUTH_SOCK` is incorrectly set to `SSH_AUTH_SOCK=/var/folders/9m/tbsk3cb11mn0wylphnk1q9fw0000gn/T//ssh-FNbRaGfc7CBQ/agent.2256`

# Environment data

macOS Mojave 10.14.3 

```none
Name                           Value
----                           -----
PSVersion                      6.1.3
PSEdition                      Core
GitCommitId                    6.1.3
OS                             Darwin 18.2.0 Darwin Kernel Version 18.2.0: Th...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
`env`

``` none
SHLVL=0
TMPDIR=/var/folders/9m/tbsk3cb11mn0wylphnk1q9fw0000gn/T/
PSModulePath=/Users/xatter/.local/share/powershell/Modules:/usr/local/share/powershell/Modules:/usr/local/microsoft/powershell/6/Modules
ASPNETCORE_URLS=http://+:5000
XPC_SERVICE_NAME=0
SSH_KEY_PATH=~/.ssh/rsa_id
GPG_TTY=/dev/ttys001
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=421.1
TERM=xterm-256color
SSH_AGENT_PID=2257
XPC_FLAGS=0x0
PWD=/Users/xatter/dev-setup/mac
SHELL=/usr/local/bin/pwsh
HOME=/Users/xatter
SSH_AUTH_SOCK=/var/folders/9m/tbsk3cb11mn0wylphnk1q9fw0000gn/T//ssh-FNbRaGfc7CBQ/agent.2256
TERM_SESSION_ID=859672CB-E827-4655-AE0A-9C97F524D949
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PATH=/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/MacGPG2/bin:/usr/local/share/dotnet:/Users/xatter/.dotnet/tools:/usr/local/microsoft/powershell/6:/usr/bin:/bin
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.jA1Yxly8A9/Render
USER=xatter
LOGNAME=xatter
LANG=en_US.UTF-8
```

# Workaround
Set `bash` as your default shell then launch `pwsh` manually and it will correctly inherit `SSH_AUTH_SOCK`

**Comment by rjmholt** [comment]
I'm guessing this is a login shell issue. Can you try with PowerShell preview (`brew cask install powershell-preview`) instead? That has support for being called as a login shell
