### ISSUE TITLE
Open source PowerShell ISE

### ISSUE THREAD

**Issue by wrbst** [PowerShell/PowerShell#9175]
Quick question.

As the main PowerShell IDE now is VSCode, why don't you open source the PowerShell ISE as well?

**Comment by HumanEquivalentUnit** [comment]
> "ISE is based on a control we got from the Visual Studio team, it's the same control they use - or used, I don't know if they still use it - in Visual Studio. [..] this is why, by the way, you'll never see the ISE open sourced that I'm aware of, because it's based around this control that is based on source that is closed source from Microsoft and it's closed source because the people who own it don't want to maintain it and support third parties in the open source, so we're kind of stuck with this boat anchor. So. VS Code!.

- Bruce Payette's "A Historical Architecture Tour of PowerShell" talk from PS Conf EU, here https://youtu.be/tQic7z75O6Y?t=6085

**Comment by wrbst** [comment]
Thank you about this clarification.
