### ISSUE TITLE
Get-Help summary version

### ISSUE THREAD

**Issue by kfsone** [PowerShell/PowerShell#9189]
# Problem statement:

Current "get-help" is "default:useless" for most usage: the default user experience is ~6 lines of generic "REMARKS", a number of "RELATED LINKS" and a small amount of space for the last few lines of the description.

It is rare to have to *not* scroll up to read the useful/relevant portion of the output.

Consider: "get-help get-help" in a default Windows Powershell window.

# Proposals

Add -Syntax and -Description options that limit output to only those portions,

Potentially consider Pagination by default?

And/or add a -Summary option that presents a more compact output:

    {Name}: {Synopsis}
    {Description-first-paragraph}
    SYNTAX
    {Syntax}

For example

    Get-Help: Displays information about Windows Powershell commands and concepts.
    The Get-Help cmdlet displays information about Windows Powershell concepts and commands, including cmdlets, functions, CIM commands, workflows, providers, aliases and scripts.

    SYNTAX
    Get-Help [[-Name] <String>] ...

**Comment by rkeithhill** [comment]
> Potentially consider Pagination by default?

There is pagination if you use the `man` alias on Windows or the `help` function on Linux (since `man` already exists as a native util) e.g. `man get-help`.  PowerShell even honors the `PAGER` environment variable.  On Windows, I use `less` via `$env:PAGER = "less"`.

**Comment by kfsone** [comment]
Ah, and fortunately “help” is consistent on both. Just a shame that Windows doesn’t ship with a better paginator by default? 😊

 

-Oliver

**Comment by rkeithhill** [comment]
>  Just a shame that Windows doesn’t ship with a better paginator

^ +100

And yes, if you bounce between Windows and macOS/Linux a lot it is better to train yourself to use the `help` function directly.  I still get bit typing `man <ps-help-topic>` on Linux.  :-)
