### ISSUE TITLE
Linux CI build does not fail when Pester Tag is missing

### ISSUE THREAD

**Issue by ThreeFive-O** [PowerShell/PowerShell#9193]
# Steps to reproduce
Omit the Tag for a Pester describe block and trigger the Linux CI build process.
```powershell
Describe "Sample test" {
}
```
See Draft PR #9192 for example.

# Expected behavior
Build process should fail for Windows, macOS and Linux. 
`ci.psm` calls `Get-PesterTag` from `build.psm1` to check if all test blocks have a valid Tag.

# Actual behavior
Linux CI build succeeds and tests are executed without any error. 
See Draft PR #9192 for reference.

# Environment data

```none

```

**Comment by ThreeFive-O** [comment]
cc @TravisEz13 and @RDIL

**Comment by RDIL** [comment]
I’ll take a look later.

**Comment by ThreeFive-O** [comment]
Issue no longer exists after PR #9209, which is merged now.
Draft PR #9192 now successfully fails on Linux too. 
Thank you @TravisEz13 and @RDIL!

**Comment by TravisEz13** [comment]
Technically it's still an issue, if you add the `[feature]` tag to the start of the last commit

**Comment by ThreeFive-O** [comment]
@TravisEz13 Draft PR #9192 fails on all platforms with added [feature] tag for commit message. This is the expected behavior. Therefore I'm not able to reproduce it for PR CI runs.
Since the merged code base for tests all include tags for Pester, only PRs would be able to introduce this problem.
If you have time, maybe you could have a quick look, if I missed something.

**Comment by TravisEz13** [comment]
Your failure occurs in the build, which will fail as expected.  The issue occurs when a pester test fails.

**Comment by TravisEz13** [comment]
Added the fix for this to #9212

**Comment by ThreeFive-O** [comment]
@TravisEz13 Thank you for clarification, but for the issue I described above the problem is fixed. The fix in #9212 describes a scenario which is post-build. This was a separate issue, but not the one I intended to describe with my issue.
