### ISSUE TITLE
Set-StrictMode -Version only accepts 6.<ownMinorVersion> and not 6 (6.0)

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#9206]
Note:  The last _documented_ strict-mode version as of this writing is `2.0` - see https://github.com/MicrosoftDocs/PowerShell-Docs/issues/2135.

However, `3`, `4`, `5`, and `5.1` are accepted too, both in Windows PowerShell and in Core.

One would therefore expect `6` (`6.0`) and `6.<lowerMinorVersions>` to be accepted, but currently only `6.<ownMinorVersion>` is.

# Steps to reproduce

Run the following Pester test:

```powershell
Describe "Set-StrictMode version numbers" {
  BeforeAll {
    $htVersions = '1', '2', '3', '4', '5', '5.1', '6', '6.1', '6.2' | % { @{ Version = $_ } }
  }  
  It "Accepts version number <Version>" -TestCases $htVersions {
    param($Version)
    { Set-StrictMode -Version $Version } | Should -not -Throw 
  }
  
}
```

# Expected behavior

All tests should pass.

# Actual behavior

In v6.2.0-rc.1, the following versions cause the tests to fail:

```none
6.0
6.1
```

# Environment data

```none
PowerShell Core 6.2.0-rc.1
```

**Comment by agowa338** [comment]
Same for Version 7,
this just broke skripts after updating to 7.1 as now `Set-StrictMode -Version 7` now throws an error of `Set-StrictMode: Cannot validate argument on parameter 'Version'. The "7.0" argument does not contain a valid PowerShell version. Supply a valid version number and then try the command again.`

**Comment by agowa** [comment]
Still exists in latest version of powershell.

```
PS C:\> Set-StrictMode -Version 7
Set-StrictMode: Cannot validate argument on parameter 'Version'. The "7.0" argument does not contain a valid PowerShell version. Supply a valid version number and then try the command again.
```

**Comment by agowa** [comment]
This is a joke, is ist?
