### ISSUE TITLE
dd and rsync equivalent in PowerShell

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#9211]
Is there any cmdlet that work like dd and rsync in linux ,
If no , will the Powershell team add the similar feature to powershell ?

PS: 
I know here(this repo) is for powershell core ,not for windows powershell,
The key point is no one will care my request or help me if I post my question to bellow official webpage . 

However , here , sometimes ,some one will answer me question. and I get what I want.

Windows PowerShell
Windows PowerShell issues/suggestions need to be reported to [UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)
https://windowsserver.uservoice.com/forums/301869-powershell

**Comment by chuanjiao10** [comment]
How about the powershell version of robocopy? In 2016, I also saw someone submitting an issue. Is anyone willing to help continue to develop?

@tlsalex you can use dd and rsync in linux version of powershell,any linux command you can use.
can you tell us what do you want?

**Comment by DWSR** [comment]
> Is there any cmdlet that work like dd and rsync in linux ,
> If no , will the Powershell team add the similar feature to powershell ?

`dd` and `rsync` are both available natively for Windows, through Cygwin, or through WSL.

> How about the powershell version of robocopy? In 2016, I also saw someone submitting an issue. Is anyone willing to help continue to develop?

`robocopy` is not a part of `cmd` but a separate standalone application. It doesn't make sense to make a "powershell" version of it. You could certainly write a version in PowerShell that uses the native File APIs, but that would be reinventing the wheel.

**Comment by SteveL-MSFT** [comment]
In general, native commands will work within PowerShell.  It would be nice to have a PowerShell equivalent so you can work with objects, but the reality is that if there is a native command that works, it wouldn't make sense to spend time on an equivalent cmdlet vs spending that time on addressing some other issue.

**Comment by chuanjiao10** [comment]
It doesn't make sense to make a "powershell" version of it. ----
![image](https://user-images.githubusercontent.com/8968667/55051762-7383ac80-5091-11e9-9cae-03b552ed57b6.png)

**Comment by HumanEquivalentUnit** [comment]
> How about the powershell version of robocopy? In 2016, I also saw someone submitting an issue. Is anyone willing to help continue to develop?

For reference, that issue is here: #2581 and is "up-for-grabs"

**Comment by SteveL-MSFT** [comment]
Just to be clear, I'd love to see cmdlets for all heavily used native commands, however, it's a question of priority.  I'd rather spend team resources on enabling new scenarios and use cases vs porting something that works today (perhaps not ideal) just to make it PowerShell-y.  Would love to see the community pick up this type of requests.

**Comment by RichardSiddaway** [comment]
I know this has been asked before but if we had the equivalent of ConvertFrom-String in PowerShell core it would be relatively simple to wrap the native commands in PowerShell which would also serve as a transition path for Windows administrators

**Comment by vexx32** [comment]
`ConvertFrom-StringData` is available, though more limited.

Honestly I always find it easier to [work with a decent regex `-match` expression and generate PSCustomObjects](https://vexx32.github.io/2018/11/08/Named-Regex-Matches-PSCustomObject/) from that. `ConvertFrom-String` was always a lot more work in my opinion, and despite what it said on the tin I have yet to find anyone who preferred it over the alternatives. You might be the first there, Richard. 🙂

**Comment by SteveL-MSFT** [comment]
@RichardSiddaway `ConvertFrom-String` is discussed here https://github.com/PowerShell/PowerShell/issues/726
