### ISSUE TITLE
Get-Help reports multiple versions of conceptual help topics for side-by-side modules

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#9215]
If you have 2 versions of a module installed side by side, the conceptual help topics from _both_ versions are reported by `Get-Help`, in list form.

Not only is it hard to tell which is which, it is non-obvious how to display their _content_.

As an aside: There is currently no way to ask for a given module version's help specifically.

# Steps to reproduce

Run the following Pester test:

Note: This test installs the stable version of PSReadLine (1.2) alongside the the 2.0.0-beta3 version that ships with PowerShell Core 6.2.0-rc.1 with `-Scope CurrentUser`.

```powershell
Describe "Duplicate conceptual help topic test." {
  BeforeAll {
    # Install the stable version of PSReadLine (1.2) alongside the 
    # the 2.0.0-beta3 version that ships with PowerShell Core 6.2.0-rc.1
    Install-Module -Scope CurrentUser PSReadLine -Force 
  }
  It "Only 1 about_psreadline topic is found." {
    (Get-Help about_PSReadLine | Measure-Object).Count | Should -Be 1
  }
}
```

# Expected behavior

The test should pass.

# Actual behavior

The test fails:

```none
[-] Only 1 about_psreadline topic is found. 80ms
Expected 1, but got 2.
```

# Environment data

```none
PowerShell Core 6.2.0-rc.1
```

**Comment by iSazonov** [comment]
Continue in #11205
