### ISSUE TITLE
Support via powershell.slack.com is a brick wall

### ISSUE THREAD

**Issue by cawoodm** [PowerShell/PowerShell#9216]
The github issues page directs users to powershell.slack.com but there is no way to get in to that site. The page at https://powershell.slack.com presents a login (which I don't have) but no register page. New users are directed to "Contact the workspace administrator for an invitation". So that's a brick wall - unless I'm supposed to request access here?

**Comment by vexx32** [comment]
Does it? OK, that has to be changed to this link: https://j.mp/psslack

If you prefer the Discord platform, you can access that from: https://j.mp/psdiscord

Both environments are bridged via a bot, so you'll get a similar experience in both. 🙂

**Comment by cawoodm** [comment]
Yaaaay!
