### ISSUE TITLE
How to connect with proxy and PowerShell 6.0

### ISSUE THREAD

**Issue by v-akhana** [PowerShell/PowerShell#9219]
We connect to Azure from internal network through authentication proxy server.  In case of using PowerShell version 5.1, proxy settings can be done as below.

```
$proxyUrl = 'proxy URL'
$proxyId = 'proxy user ID'
$proxyPwd = 'proxy password'

$password = ConvertTo-SecureString $proxyPwd -AsPlainText -Force
$cred = New-Object System.Management.Automation.PSCredential $proxyId, $password
$proxy = New-Object System.Net.WebProxy $proxyUrl
$proxy.Credentials = $cred
[System.Net.WebRequest]::DefaultWebProxy = $proxy
```

In terms of PowerShell 6.0, I would like to use proxy as well, but cannot use the command let above with proxy error.
I would like to ask you how to connect with “Connect-AzAccount” using proxy server and PowerShell 6.0.

**Comment by TravisEz13** [comment]
PowerShell 6.0 is not currently supported.  You need to upgrade to PowerShell 6.1.3 for support.

You would need to contact the team that supports `Connect-AzAccount` .  How to configure the proxy is going to vary based on how they implemented the cmdlet.  I believe you can file an issue at https://github.com/Azure/azure-powershell for the `Az` Module.

**Comment by v-akhana** [comment]
Thank you Travis!
I contact to https://github.com/Azure/azure-powershell .
