### ISSUE TITLE
Pty

### ISSUE THREAD

**Issue by phyoyathupty** [PowerShell/PowerShell#9221]
# Windows PowerShell

For Windows PowerShell 5.1 issues, suggestions, or feature requests please use the following link instead:
Windows PowerShell [UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)

This repository is **ONLY** for PowerShell Core 6 issues.

**Comment by mklement0** [comment]
@phyoyathupty, please either update your issue's title and body to provide relevant information, or, if you created the issue accidentally, close it.
