### ISSUE TITLE
Is there any cmdlet can check  which process is accessing my files(or accessing which files)

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#9227]
Sometimes , try to remove USB drive, but system shows me "this device is currently is use xxxxxxxx".

Want to know which cmdlet can check which process is accessing my files currently.

**Comment by vexx32** [comment]
I think this is doable via Get-CimInstance and the Win32_Process class, if I'm not mistaken. It's a bit of extra code beyond the cmdlet itself, but shouldn't be insanely complicated...

If you need more to go on, ping me tomorrow morning and I'll revisit this in code properly. :)

**Comment by kvprasoon** [comment]
This capability is there in `handle.exe` which is part of famous [sysinternals suite](https://docs.microsoft.com/en-us/sysinternals/downloads/sysinternals-suite) . AFAIK, there is no built-in PowerShell cmdlet to do this.

**Comment by tlsalex** [comment]
@vexx32 ,I want to get your answer ,thank you.

**Comment by vexx32** [comment]
@tlsalex There seems to be almost enough data in there to figure it out, but at present it doesn't look like there's a good way to put the pieces together, and a couple pieces are missing from the WMI/CIM classes to make it happen.

At the moment it does seem as though @kvprasoon has the right of it. P/Invoke is another way to go about it, but you need to branch out to some C# to have that work at the moment.
