### ISSUE TITLE
ConvertTo-Json unexpectedly serializes AutomationValue.Null as an empty object, not null

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#9231]
PowerShell commands that output nothing output the special `[System.Management.Automation.Internal.AutomationNull]::Value` singleton, which typically behaves like `$null`.

Unexpectedly, `ConvertTo-Json` doesn't treat it as `$null`, but treats it as an _empty object_, which is undesired.

# Steps to reproduce

```powershell
# Note: `. {}` yields the [System.Management.Automation.Internal.AutomationNull]::Value
# singleton, not $null.
[pscustomobject] @{ foo = . {}; bar = $null } | ConvertTo-Json
```

# Expected behavior

```none
{
  "foo": null,
  "bar": null
}
```

# Actual behavior

```none
{
  "foo": {},
  "bar": null
}
```

# Environment data

```none
PowerShell Core 6.2.0-rc.1
Windows PowerShell v5.1 
```

**Comment by vexx32** [comment]
cc @markekraus

**Comment by cawoodm** [comment]
Also `. {}` is equal (`-eq`) to `$null` but doesn't serialize to `null`.

**Comment by markekraus** [comment]
heh.. that's a fun one... we may need to create a custom JSON handler for AutomationNull or something.
