### ISSUE TITLE
Get-ComputerInfo - takes as long to get 1 property as 183 properties

### ISSUE THREAD

**Issue by HumanEquivalentUnit** [PowerShell/PowerShell#9234]
`Get-ComputerInfo` returns 183 properties in 7 seconds.

`Get-ComputerInfo -Property TimeZone` returns 1 property in .. 7 seconds.

`Get-TimeZone` runs in 0.0015 seconds. and returns more detailed information.

Can it run faster, if asked for less data?

Environment:

```powershell
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.14393 
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by tlsalex** [comment]
Agree with you , I also want to know the answer , maybe we need to use WMI

**Comment by RichardSiddaway** [comment]
Looking at the data returned I think its already using WMI.  I suspect the speed issue is because its gathering all the data and then filtering down to the properties you asked for

**Comment by jeffbi** [comment]
@RichardSiddaway It is using WMI (well, CIM if I recall correctly). At the time the cmdlet was originally written, the mandate was to collect and display _all_ the data. The ability to report a single property was added kind of at the last minute and the decision at the time was to continue collecting all, then select to one to report.

**Comment by RichardSiddaway** [comment]
WMI was Microsoft's first CIM implementation.  CIM (in PowerShell terms) was the methodology introduced in PowerShell v3 including CIM sessions
These days CIM and WMI are interchangeable unless you're talking about the WMI or CIM cmdlets

**Comment by powercode** [comment]
I'm not sure why the designers of the cmdlet added property filtering capabilities. That is already available in Select-Object, so it seems like something that shouldn't have been there in there first place. If you read the source, it just gets everything, and if you only want a subset of the properties, it creates a psobject and populates it with those. 

Feature creep in my book.

**Comment by slycordinator** [comment]
Still valid:

PowerShell 7.4.1
```
PS C:\Users\USER> Measure-Command {Get-ComputerInfo -Property TimeZone} | Select -ExpandProperty TotalMilliseconds
2049.3817
PS C:\Users\USER> Measure-Command {Get-TimeZone} | Select -ExpandProperty TotalMilliseconds
1.9275
```

Windows PowerShell (5.1.19041.3930)
```
PS C:\Users\USER> Measure-Command {Get-ComputerInfo -Property TimeZone} | Select -ExpandProperty TotalMilliseconds      2498.4514
PS C:\Users\USER> Measure-Command {Get-TimeZone} | Select -ExpandProperty TotalMilliseconds
2.4808
```

In both cases, `Get-TimeZones` completes about 1000 times faster than `Get-ComputerInfo -Property TimeZone`

**Comment by jeffbi** [comment]
This is unlikely ever to be fixed. Newer versions of PowerShell are open source and cross-platform, and the CIM code (along with a few Windows API function calls) are not portable to Linux or macOS.

As I've said before, the original mandate was to collect *all* the data. Only later was it decided to add `-Property`, which selects from all the already-collected data.
