### ISSUE TITLE
Measure-Object: allowing the combination of -Line, -Char, -Word with -Property is pointless

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#9237]
`-Property` requires specifying the name of an existing property.

In the case of `-Line`, `-Char`, `-Word`, the inputs are by definition _strings_, whose only property is `Length`.

Therefore, only `-Property Length` is accepted without breaking the call, but _doing so is pointless and effectively ignored_.

Suggested fix:

*  `-Line`, `-Char`, `-Word` should  be in a parameter set that doesn't include `-Property`.

* Define format data for output type `Microsoft.PowerShell.Commands.TextMeasureInfo` that hides the in applicable `Property` property (which is inherited from the abstract `Microsoft.PowerShell.Commands.MeasureInfo` class), and similarly exclude it for `Deserialized.Microsoft.PowerShell.Commands.TextMeasureInfo`.

# Steps to reproduce

```powershell
# Pointless use of -Property
'foo' | Measure-Object -Line -Property Length

'foo' | Measure-Object -Line
```

# Expected behavior

```none
Measure-Object: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.

Lines Words Characters
----- ----- ----------
    1                 

```

# Actual behavior

```none

Lines Words Characters Property
----- ----- ---------- --------
    1                  Length



Lines Words Characters Property
----- ----- ---------- --------
    1                  
```

That is, `-Property Length` was accepted, but ignored -  even though it is reflected in the output.

Similarly, even without `-Property`, the inapplicable `Property` is shown in the output.

# Environment data

```none
PowerShell Core 6.2.0-rc.1
Windows PowerShell v5.1 
```

**Comment by SeeminglyScience** [comment]
@mklement0 Using `Property` with one of those parameters changes the *target* to the property's value.  e.g.

```powershell
$string = 'This is a test value'
$customObj = [pscustomobject]@{ MyProperty = $string }
$customObj | Measure-Object -Character -Property MyProperty

# Lines Words Characters Property
# ----- ----- ---------- --------
#                     20 MyProperty

$string.Length
# 20
```

**Comment by mklement0** [comment]
Thanks, @SeeminglyScience, that makes sense - it hadn't occurred to me to combine the features this way

I'll close this, but I've created a docs issue to suggest making the relationship between these parameters clearer: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/4062
