### ISSUE TITLE
Request: Improve user experience of Get-WinEvent -FilterHashtable

### ISSUE THREAD

**Issue by HumanEquivalentUnit** [PowerShell/PowerShell#9239]
Get-WinEvent uses `-FilterHashtable @{..}` as one way to describe which events to retrieve, and the hashtable takes keys like `ID`, `StartTime`. But there's no way to find out which keys are valid without reading the help.

This feels like a PS-style design would have exposed those keys as parameters, they would show up for tab completion and introspection, and then splatting would be available for the hashtable use case.

My experience would be better if there was a quick way to see the valid keys without having to refer to the help, so:

1. Would it be possible for tab-completion to suggest valid hashtable keys, if the hashtable was being written in this context, e.g. `get-winevent -filterhashtable @{ <tab>` ?
1. Would it be possible to make `Ctrl-Space` suggestions, which currently lists all parameters in a nice view, also support showing some text which isn't parameters - hashtable keys specifically in this case, or in a more general case cmdlets could optionally show a cheatsheet section with some free-form text.
1. What about exposing the keys as parameters, making them usable by splatting, and deprecating -FilterHashTable?

(FilterXPath and FilterXml parameters also exist, I have no comment on them, they can stay how they are from my point of view).

**Comment by iSazonov** [comment]
> What about exposing the keys as parameters, making them usable by splatting, and deprecating -FilterHashTable?

I wonder doesn't splatting use hash?

I think IntelliSense for `get-winevent -filterhashtable @{ <tab>` is best choice.

**Comment by vexx32** [comment]
Sure, splatting uses hashtables, but at least you can get native tab completion for parameters (if they were exposed as parameters) and then get everything sorted before you convert it to a splat. Tab-completion would be available out of the box and not require a weird hacky solution for this specific case.

**Comment by iSazonov** [comment]
To get started we would have to add over 15 parameters (!) for the System section only.

**Comment by iSazonov** [comment]
If we get back ConvertFrom-String we could make requests on "native" language :-)

**Comment by vexx32** [comment]
I don't think relying on conversions from string is a good route to go on an administrative level for system event data gathering. 😕

**Comment by HumanEquivalentUnit** [comment]
@iSazonov could you explain where the 15 comes from? The [documentation here]( https://docs.microsoft.com/en-us/powershell/scripting/samples/Creating-Get-WinEvent-queries-with-FilterHashtable?view=powershell-6) and [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.diagnostics/Get-WinEvent?view=powershell-6) only shows ten (`LogName, ProviderName, Path, Keywords, ID, Level, StartTime, EndTime, UserID, Data`) plus the ability to reference "any named data field", I cannot see where it says that they are limited to a section (or that it says they are localised into different languages - does that mean `get-winevent -filterhashtable @{StartTime='2019-01-01'}` does not work on your computer because of the English "StartTime" ?).

Am I thinking about this all wrong, and I should imagine it like `Get-AdUser -Filter "<blob>"` or `Invoke-SqlCmd "<sql blob>"` where the filter only makes sense to the provider?  Should I be looking for Windows Event Log discussions of how it can filter?  (And if so, is the supported filtering different on different versions of Windows?)
