### ISSUE TITLE
Is there or similar SUID, SGID and Sticky stuff in windows, any PS cmdlet can do that?

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#9243]
Always met some not well designed software , which is required admin permission to run it. But we can't give a normal user a admin permission.

I wonder if there is a way to make a program always runs in admin permission, just like the SUID in linux  /usr/bin/passwd.

Or is there a similar way to do that in windows.

Sorry this seems not a powershell issue , but maybe PowerShell already have some cmdlet implement that, we just don't know

**Comment by iSazonov** [comment]
Please look #3232

**Comment by tlsalex** [comment]
Hello @iSazonov ,

Maybe it is not clear enough for my question , what do I mean is a normal user can run a program that required admin permission without type any admin credential(by assign some privilege to it). just double click on the app ,and the app runs well , but the program run as admin actually.

Just like the normal user in linux , update his password with passwd command , but the passwd command itself run as root.

**Comment by iSazonov** [comment]
There is no SUID, SGID in Windows. You could be create a service running under elevated account and create utils which communicated with the service.

**Comment by SteveL-MSFT** [comment]
@tlsalex [JEA](https://github.com/powershell/jea) is what you are looking for.  The short version is that you can configure a PowerShell endpoint to runas another account.  So you can give trusted users limited access to admin tasks.
