### ISSUE TITLE
6.2.0-rc.1 Remove-Item -Recurse broken for reparse points

### ISSUE THREAD

**Issue by Baribeault** [PowerShell/PowerShell#9246]
in 6.1.2 this command works : Remove-Item C:\Users\david\OneDrive\Documents\ -Recurse

but in 6.2.0-rc.1 I get this error

PS C:\Users\david> Remove-Item C:\Users\david\OneDrive\Documents\ -Recurse
Remove-Item : Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
At line:1 char:1
+ Remove-Item C:\Users\david\OneDrive\Documents\ -Recurse
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Remove-Item], FormatException
+ FullyQualifiedErrorId : System.FormatException,Microsoft.PowerShell.Commands.RemoveItemCommand

**Comment by powercode** [comment]
@Baribeault Can you add the output of 
```powershell
$error[0] | fl -showerror -force *
```

**Comment by Baribeault** [comment]
PS C:\Users\david> $error[0] | fl -showerror -force *

PSMessageDetails      :
Exception             : System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
                           at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
                           at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
                           at System.String.Format(IFormatProvider provider, String format, Object arg0)
                           at System.Management.Automation.Internal.StringUtil.Format(String formatSpec, Object o)
                           at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveDirectoryInfoItem(DirectoryInfo directory, Boolean recurse, Boolean force,
                        Boolean rootOfRemoval)
                           at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveItem(String path, Boolean recurse)
                           at System.Management.Automation.SessionStateInternal.RemoveItem(CmdletProvider providerInstance, String path, Boolean recurse,
                        CmdletProviderContext context)
TargetObject          :
CategoryInfo          : NotSpecified: (:) [Remove-Item], FormatException
FullyQualifiedErrorId : System.FormatException,Microsoft.PowerShell.Commands.RemoveItemCommand
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

**Comment by vexx32** [comment]
Hmm, sounds like someone might have messed with one of the resx strings there.

Does `$error[0].Exception.GetBaseException() | fl -f` give any additional information?

**Comment by Baribeault** [comment]
PS C:\Users\david> $error[0].Exception.GetBaseException() | fl -f

Message        : Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
Data           : {}
InnerException :
TargetSite     : System.Text.StringBuilder AppendFormatHelper(System.IFormatProvider, System.String, System.ParamsArray)
StackTrace     :    at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
                    at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
                    at System.String.Format(IFormatProvider provider, String format, Object arg0)
                    at System.Management.Automation.Internal.StringUtil.Format(String formatSpec, Object o)
                    at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveDirectoryInfoItem(DirectoryInfo directory, Boolean recurse, Boolean force, Boolean
                 rootOfRemoval)
                    at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveItem(String path, Boolean recurse)
                    at System.Management.Automation.SessionStateInternal.RemoveItem(CmdletProvider providerInstance, String path, Boolean recurse,
                 CmdletProviderContext context)
HelpLink       :
Source         : System.Private.CoreLib
HResult        : -2146233033

**Comment by vexx32** [comment]
Looks like it should be from these three here, I'd venture to guess, and the resx strings used therein:
```
1. at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveDirectoryInfoItem(DirectoryInfo directory, Boolean recurse, Boolean force, Boolean
rootOfRemoval)
2. at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveItem(String path, Boolean recurse)
3. at System.Management.Automation.SessionStateInternal.RemoveItem(CmdletProvider providerInstance, String path, Boolean recurse,
CmdletProviderContext context)
```

**Comment by iSazonov** [comment]
> C:\Users\david\\__OneDrive__\Documents\

We don't work with OneDrive well.

**Comment by GregWoods** [comment]
Ubuntu shell works fine in Windows

**Comment by sba923** [comment]
I confirm this issue is still there with PowerShell 7.0:

![image](https://user-images.githubusercontent.com/12860484/78645251-84c3e380-78b7-11ea-8226-f1125a6df0ab.png)

When this fails, the same `Remove-Item -Recurse -Force` operation works in Windows PowerShell 5.1.

**Comment by sba923** [comment]
Same as https://github.com/PowerShell/PowerShell/issues/11721

**Comment by dgard1981** [comment]
Is there a workaround here? This has been acknowledged as a bug for over a year with seemingly no movement.

**Comment by iSazonov** [comment]
I guess it is not complex fix. I guess we need detect _surrogate_ reparse points. If I remember correctly we already did this for read operations.

**Comment by fmorriso** [comment]
This is still happening on July 28, 2020 using PowerShell Core 7.0.3, so whatever is the problem with regular PowerShell (5.x?) has carried over intact (unfortunately) to it's sire, PS 7.x.

**Comment by moorichardmoo** [comment]
I think I must be missing something. Is it really the case that the LTS release of PowerShell Core doesn't contain the working functionality to delete files? 
I'm getting "Index (zero based) must be greater than or equal to zero and less than the size of the argument list." even if I pipe the input from a Get-ChildItem foreach loop rather than use -Recurse. Is that a problem only I'm experiencing or is that related to this issue?

**Comment by fmorriso** [comment]
As of August 18, 2020, using PowerShell 7.0.3 on Windows 10 Pro Version 2004 (OS Build 19041.450), the following works correctly for me:
`Get-ChildItem -Path .\node_modules -Recurse | Remove-Item -Recurse`

**Comment by sba923** [comment]
It's only broken in the OneDrive folder where files are not actual files but reparse points.

**Comment by DJackman123** [comment]
@fmorriso, does that command work for you when .\node_modules contains folders?  I was able to delete individual files from my OneDrive using Remove-Item, but not folders.  At least not when the folders are non-empty.  But if I delete everything that Get-ChildItem -Recurse lists in reverse order (so files in the folder are deleted before attempting to delete the parent folder) then it works.  So my command looks like this:

```
Get-ChildItem -Path .\node_modules -Recurse | Sort-Object { (--$script:i) } | Remove-Item
```

**Comment by fmorriso** [comment]
I copied an angular project from my c:\projects\angular\ folder to c:\users\username\OneDrive\projects\angular\ and then tried my script and it worked just fine (directory node_modules and all files/subdirectories beneath it were deleted).

**Comment by DJackman123** [comment]
That's interesting.  If you tried to just Remove-Item -Recurse on a folder would that give the error from this bug?  I noticed that I was able to delete folders in my personal OneDrive without problems, but in my OneDrive for business folder it gave this error.  I'm guessing it's because my OneDrive for Business is having the local "My Documents" and other folders routed to it (even though the folders I'm testing with aren't in there).

**Comment by fmorriso** [comment]
I performed the following starting at `c:\users\userName\OneDrive\projects\angular\dummyProject\` with no issues (the top-level directory and all subdirectories/files were removed):
`
Remove-Item -Path .\node_modules -Recurse
`

**Comment by gatesvp** [comment]
Here to confirm the same issue with PowerShell `7.0.3`.
![image](https://user-images.githubusercontent.com/319590/93011005-52de3980-f547-11ea-91b0-0630fc640a52.png)

For context, I am in the middle of a large OneDrive sync and I'm trying to clean up some dead folders. But those dead folders are within other folders that are still being synced.
![image](https://user-images.githubusercontent.com/319590/93011015-7903d980-f547-11ea-961b-9760346851e5.png)

If, instead I try to delete a folder from somewhere that has been "synced", I don't get this problem.
![image](https://user-images.githubusercontent.com/319590/93011087-05160100-f548-11ea-9366-80cdc96ea24e.png)

It looks like folders in transit to OneDrive cloud are somewhat invisible to OneDrive PowerShell Core during this process.

Hopefully that's a useful repro case:
 - Generate gigabytes of OneDrive changes
 - Attempt to delete folders deep in the structure of the changes that are syncing

**Comment by fmorriso** [comment]
Based on previous comments, I wonder if the issue can be avoided by pausing OneDrive synchronization prior to invoking `Remove-Item -Recurse`.

**Comment by gatesvp** [comment]
Hey @fmorriso , this was a good idea, but I just tested this and no luck. Still the same results.
![image](https://user-images.githubusercontent.com/319590/93021515-d45db800-f597-11ea-8f35-3fbf89a2616e.png)

**Comment by simonsabin** [comment]
I've found this works as a workaround. essentially you have to empty the folders and then remove the folders when empty. 
```
"foldername" | %{
  Get-ChildItem -Recurse $_ -force -file | %{ remove-item $_ -force -Verbose}
 # This gets paths in reverse order so you can remove from the parent down
  (Get-Childitem $_ -Recurse -force).Fullname |sort-object {$_.length} -Descending | remove-item -force -Verbose; 
}
```

**Comment by fireflycons** [comment]
Presumably the C# code behind `Remove-Item` and anywhere else that files are being "deleted" (so possibly `Move-Item` too) needs to correctly recognise and handle the reparse points used by OneDrive.

It would be nice to get this fix once complete rolled out in a patch to Windows PowerShell too, not to put a requirement on using PS Core to work with OneDrive.

As mentioned in several places, OD for business causes havoc with module management due to My Documents being part of the OD file system. 

As a workaround, is there a way to tell both Windows PowerShell and PS Core to use different directories for user-scoped modules such that they can be pointed away from OD?

**Comment by MisinformedDNA** [comment]
I'm getting a new work PC and had to backup all my data to OneDrive. Due to how slow OneDrive is, I decided to go through and delete as much as I could. Now I have errors like this when opening "leftover" directories.

```
[Window Title]
Location is not available

[Content]
C:\Users\XXXX\...\somefolder is not accessible.

The tag present in the reparse point buffer is invalid.

```

I used a combination of `Remove-Item -Recurse` and deleting directly from File Explorer.

I can't even delete these folders anymore. Clicking "Delete" in File Explorer results in literally nothing. It doesn't get deleted and it doesn't even prompt me with a confirmation or anything. It just does nothing.

Luckily, I'm getting a new computer so this should all go away, but it has been an awful experience.

**Comment by sba923** [comment]
> I'm getting a new work PC and had to backup all my data to OneDrive. Due to how slow OneDrive is, I decided to go through and delete as much as I could. Now I have errors like this when opening "leftover" directories.
> 
> ```
> [Window Title]
> Location is not available
> 
> [Content]
> C:\Users\XXXX\...\somefolder is not accessible.
> 
> The tag present in the reparse point buffer is invalid.
> ```
> 

What version / build number of Windows and what version of the OneDrive sync client are you using?

**Comment by gatesvp** [comment]
I was using the latest version of everything as of the time I posted that
message. I update everything basically weekly.

**Comment by SteveL-MSFT** [comment]
@iSazonov are you going to make another attempt to fix this?

**Comment by iSazonov** [comment]
#15571 is waiting a code review.

**Comment by sba923** [comment]
Is this fixed in 7.2?

**Comment by iSazonov** [comment]
> Is this fixed in 7.2?

I hope :-) Please install 7.2 and try to work with OneDrive.

**Comment by sba923** [comment]
I was at work when I got the notification so I thought I would just get the answer without testing 😝Of course 7.2 is on all my systems so I can test... And now I know I have to since there is no pre baked answer.

**Comment by iSazonov** [comment]
> I thought I would just get the answer without testing

You got :-) We push some commits to fix such issues and I hope now all works well. If you still see problems, feel free to report.

**Comment by sba923** [comment]
I think the answer is clear 😆

![image](https://user-images.githubusercontent.com/12860484/143203659-192b07d7-14e2-40e6-a288-cae38934cf8b.png)


Good job!
