### ISSUE TITLE
6.2 - Color code (?) getting appended to prompt

### ISSUE THREAD

**Issue by Lombra** [PowerShell/PowerShell#9251]
Just installed PSCore 6.2, upgrading from 6.0. Whenever I input any text into the prompt, some extra characters (`[107m`), which I think may be a color code of some sort, gets appended to the line. For each space, an additional color code is added to the end.

# Steps to reproduce

Type any text into the prompt, such as 'w'.

# Expected behavior

```none
PS C:\> w
```

# Actual behavior

```none
PS C:\> w [107m
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 6.1.7601 S
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
Is this a PSReadLine issue or something in contrast perhaps?

/cc @lzybkr @stevel-msft

**Comment by Lombra** [comment]
Yes, that seems to fix it.

**Comment by SteveL-MSFT** [comment]
@Lombra can you provide more details of your environment to see if I can replicate it?

**Comment by Lombra** [comment]
Certainly. What would you like to know?

I use the 64 bit version of Powershell. Windows 7 Ultimate. Don't think I have any additional modules installed. Will check. Got PS 5 installed also.

**Comment by SteveL-MSFT** [comment]
Win7 doesn't understand VT100 codes and I believe PSReadLine doesn't do any check before using them (with latest changes to have single cross platform code base).  For now, you might have to install PSReadLine 1.2.

**Comment by lzybkr** [comment]
PSReadLine supports Win7 by translating limited VT sequences, see [here](https://github.com/lzybkr/PSReadLine/blob/929f4f9bf4aa9ab320c9529d1dc064a94abd0379/PSReadLine/PlatformWindows.cs#L404).

**Comment by iSazonov** [comment]
Dup #14594
