### ISSUE TITLE
Feature Request/Clarification namespace variable notation shorthand for current drive or working directory?

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PowerShell#9254]
# Summary of the new feature/enhancement

Is there a reasonable shorthand to use the namespace variable notation to reference the current drive on Windows systems?  (at least I think this would be a Windows only thing). 

I guess the same notation would be a question on Linux like systems as well, in order to access a relative path of the file system provider?

# Proposed technical implementation details (optional)

If not, could a notation such as `${.:somefile.txt}` be suitable?  It appears that '.' and '~' have been reserved from being part of drive names.  Either one could work here.

**Comment by vexx32** [comment]
`.` isn't really the current _drive_; it's the current **directory**. Similarly, `~` refers to the user's home directory.

They're folders on the current or a specific PSDrive.

That said, I agree it makes sense to allow these relative (semi-relative(?) in the case of `~`) markers to be used for the namespace variable notation, except perhaps since they're not actually drive names they should probably still follow the colon perhaps? `${:./somefile.txt}`

**Comment by msftrncs** [comment]
But, without specifying a drive, its just a variable.   I was proposing that `.` could be a drive that represents the current drive (in addition to the fact that it also represents the current folder in a normal path).

Your example using `C:`  is was what I was basing this on.  You can get to the current folder on an existing drive if you specify the drive, but you cannot specify a filesystem provider path that also uses the current drive, or working path, which you may not know the drive.

If there isn't a way to accomplish this now in the current language, I think its a missing feature of completeness.

To be fair, it could also just be a drive called `pwd:`.

**Comment by msftrncs** [comment]
Fired up Ubuntu to make sure I understood how things work in a Linux world, and noticed that even though `/` is not a valid drive name character, the primary file system provider drive is `/` (since Linux d.   This would indicate there is some precedence to use reserved characters in a core system drive name.

However, I seem to be unable to get this notation to work at all on ubuntu, with PS 6.1.1.  It seems that the `/` drive is not actually valid, even though it is defined.

**Comment by vexx32** [comment]
Yeah that's an existing bug; I think @mklement0 opened an issue for that one not too long ago.

**Comment by mklement0** [comment]
Thanks, @vexx32: it's #3245

**Comment by msftrncs** [comment]
So, I thought maybe `${filesystem::.somefile.txt}` would work, but `filesystem::` provider current working directory doesn't follow PowerShell's working directory, aka, the issue with [xml] save() method.
