### ISSUE TITLE
Alternative log formats

### ISSUE THREAD

**Issue by strawgate** [PowerShell/PowerShell#9255]
# Summary of the new feature/enhancement

The different streams coming from powershell would be more useful if they were in a format like json and included metadata like logging level, function, datetime, etc.

It would be nice to have a straightforward way to customize the logging in powershell without having to use custom logging functions.

Examples:
* If I'm running powershell scripts as a scheduled task or in a container I would like to be able to ship the logs to log management via a log collector
* Include information other than the message itself automatically using structured logs. Information like a timestamp, severity, or other information like memory usage, cpu time, pid, etc
* Simplify parsing the log for important messages like warnings/errors and allow the logs to be more consumable by a machine

**Comment by iSazonov** [comment]
@strawgate Please add use cases and scenarios.
