### ISSUE TITLE
Windows PowerShell ISE stopping 

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#9260]
Remote to a server which has an IP address 10.0.0.132(DHCP),
Then change the IP address to 10.0.0.41(manually with new-netipaddress )
Then Windows PowerShell ISE then tried to reconnect the old ip address, after a while ,
ISE  show me it already disconnect from the old IP address successfully.
But it didn't return the console , the status bar still shows stopping , seems it still doing something.
At that moment, I have to close ISE ,and re_open it.
Any advise for that ? 
Or how to exit current pssession after I change IP address , tried to  use “(new-netipaddress xxxxx) -and exit ” but fail.

![Capture](https://user-images.githubusercontent.com/36788337/55285646-68e35300-53c2-11e9-890f-4e3c35ed4b87.PNG)

**Comment by iSazonov** [comment]
@tlsalex PowerShell ISE is not in the repo. Please report to UserVoice or/and Windows 10 Feedback tool.
