### ISSUE TITLE
Documentation request for PowerShell Grammar

### ISSUE THREAD

**Issue by Big5-sec** [PowerShell/PowerShell#9263]
Dear Powershell Community,

First of all, please excuse me if this issue is somehow polluting your feed. I did not known where to ask for my request :

Since Powershell v3, there has not been any Language Reference for Powershell. Today, to get a glimpse at the grammar of Powershell, one needs to parse "//G " comments in Parser.cs.
However, the grammar is quite incomplete, with multiple references to the same rule or even rules without expected childs.

Disposing of a complete grammar could help several OSS projects that are basing their analysis on the parsing of Powershell.  It could also helps to simply understand the core of Powershell coding.

So, might it be possible to get a powershell grammar as a documentation of the project?

Thanks in advance,
regards

**Comment by chuanjiao10** [comment]
local document at:
c:\Windows\System32\WindowsPowerShell\v1.0\en-US

web document at:
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/?view=powershell-6

**Comment by iSazonov** [comment]
It is dup #2254.

Also see #7408 - request to implement standalone Parser.
