### ISSUE TITLE
Multiple byref arguments of the same variable do not reference the same location for ValueTypes

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#9267]
# Steps to reproduce

```powershell
Add-Type -TypeDefinition '
    public struct MyStruct
    {
        public int X;

        public MyStruct(int x) => X = x;

        public static void AlterStructs(ref MyStruct s1, ref MyStruct s2)
        {
            s1.X += 10;
            s2.X += 10;
        }

        public static int WorkingExample()
        {
            var myStruct = new MyStruct(10);
            AlterStructs(ref myStruct, ref myStruct);
            return myStruct.X;
        }
    }'

$myStruct = [MyStruct]::new(10)
[MyStruct]::AlterStructs([ref] $myStruct, [ref] $myStruct)
```

# Expected behavior

```powershell
PS> $myStruct.X
30
PS> [MyStruct]::WorkingExample()
30
```

# Actual behavior

```powershell
PS> $myStruct.X
20
PS> [MyStruct]::WorkingExample()
30
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

# Remarks

Also reproduces on Windows PowerShell v5.1.

**Comment by vexx32** [comment]
This seems to be a little more akin to how the `ref` function behaves in F#.

In f#, when you apply `ref X` it copies the value and then provides a reference to the cell that holds the copied value. It appears PowerShell is doing something similar.

I suspect you'll need to follow the f# pattern here to do this, by first storing the [ref] value somewhere. For example:

```
$ref = [ref][MyStruct]::new(10)
[MyStruct]::AlterStructs($ref, $ref)
$ref.Value
```

**Comment by SeeminglyScience** [comment]
> In f#, when you apply ref X it copies the value and then provides a reference to the cell that holds the copied value. It appears PowerShell is doing something similar.

Yeah more or less, though I don't think it's purposeful here.  Here's where it's handled:

https://github.com/PowerShell/PowerShell/blob/4005f50faaa5d7f37de431aeb9283ac4f144c088/src/System.Management.Automation/engine/runtime/Binding/Binders.cs#L7151-L7156

PowerShell is creating a temporary variable to use byref so it can call `PSReference.set_Value` after the method invocation. That stops your example syntax from working as well, same result of `20`. A possible solution would be to use the same `ParameterExpression` for any arguments where `PSReference._value` is the same `PSVariable`.

Tbh I'm not really sure this is worth fixing, just wanted it documented somewhere (even if that's as an issue closed as `wontfix`)
