### ISSUE TITLE
get-content -- not recognizing unicode no bom

### ISSUE THREAD

**Issue by jszabo98** [PowerShell/PowerShell#9268]
It would be nice if get-content automatically recognized unicode no bom.  Notepad does.

# Steps to reproduce

```powershell
$file = 'hi.txt'
'hi there' | set-content -Encoding unicode $file
$bytes = [io.file]::ReadAllBytes($file)
[IO.File]::WriteAllBytes($file, $bytes[2..$bytes.length])
get-content $file
```

# Expected behavior

```none
hi there 
```

# Actual behavior

```none
# displays nulls as spaces

h i   t h e r e 
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      5.1.16299.1004
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.16299.1004}
BuildVersion                   10.0.16299.1004
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by vexx32** [comment]
I don't know that there's actually a reliable way to have that work. Notepad might just be using its default encoding to read the file. Both utf16-le and utf16-be encodings (both of which are referred to as "Unicode") require a byte order mark.

If you want to specify an encoding when you retrieve the data with Get-Content, I believe it has an -Encoding parameter you can use to force in to use the encoding you'd like.

Autodetection can only do so much if the file literally goes against established standards for the format.

**Comment by iSazonov** [comment]
I guess we use .Net Core StreamReader heuristics.

**Comment by jszabo98** [comment]
PS 6 uses utf8 no bom by default.  *shrug*  I just helped someone on a forum with a utf16 no bom file.  https://powershell.org/forums/topic/multi-line-pattern-looking-for-contained-content-in-file/#post-147620

**Comment by vexx32** [comment]
Certainly, UTF8 without a BOM is a pretty common standard. However, as far as I'm aware, all UTF16 files are supposed to have a BOM as otherwise they are frequently indistinguishable in terms of _valid_ characters or not from a UTF8noBOM file. Reading a UTF16 w/o BOM file _by default_ is problematic as it is _also_ a perfectly valid UTF8 w/o BOM file, and without reading the entire file first, there's no way to be sure one way or the other.

I don't see any issues with requiring you to specify an encoding in ambiguous situations. 🤷‍♂️

**Comment by HumanEquivalentUnit** [comment]
Related: Notepad guesses using [IsTextUnicode()](https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-istextunicode), and it supports Little Endian UTF16 without BOM, it does not support Big Endian UTF16 without BOM.

Source: Raymond Chen's The Old New Thing blog, which Microsoft have moved recently and broken all the old links to, but [here's a Google cache view](https://webcache.googleusercontent.com/search?q=cache:7KkwzhYbQZoJ:https://devblogs.microsoft.com/oldnewthing/20040324-00/%3Fp%3D40093+)

> However, as far as I'm aware, all UTF16 files are supposed to have a BOM as otherwise they are frequently indistinguishable in terms of valid characters or not from a UTF8noBOM file.

I thought so too, but I've gone to try and prove it, and found that it isn't.  The current Unicode 12 standard is [here in this huge PDF](https://www.unicode.org/versions/Unicode12.0.0/UnicodeStandard-12.0.pdf) and on page 41 / section 2.6 there's a table of Encoding Schemes. If the data stream is marked as `UTF-16BE` or `UTF-16LE` such as in a HTTP transfer or database record, no BOM is allowed. If it's  UTF16 generally but the byte order is not marked anywhere else, then a BOM is "allowed". I can't see anywhere it says it's mandatory.

**Comment by chuanjiao10** [comment]
Why write your national acronym on your passport instead of "guess"? 
Too many brains are filled with shit-like ideas,for example, "No BOM is correct". 
So I have to tell you: 

BOM is a very good thing.Any text file should use it. 

BOM is the encoded name.Or id.
 
Q: how do I determine file encoding without BOM? 
A: guess. 

Q: who can identify text files without BOM? 
A: no software can do 100%. 
Get-content can't, notepad++ can't, ultraedit can't, 

Not using BOM in a text file ,is the same thing as shit.

**Comment by jszabo98** [comment]
PS 6 is utf8 no bom by default.  On here is an algorithm to recognize utf8 no bom at least.  https://unicodebook.readthedocs.io/guess_encoding.html

**Comment by vexx32** [comment]
Right, but in order to _guess_ the encoding, you have to read the file data multiple times. PowerShell is an administrative tool at the end of the day, and I'm not really sure it makes any sense to make that assumption for the user.

**Comment by chuanjiao10** [comment]
> https://unicodebook.readthedocs.io/guess_encoding.html Notepad++ and Ultraedit can handle unicode no bom (utf16 le not utf16 be, just like Notepad).

Chinese script users don't think so, because guessing Chinese often fails. Especially when the text file is short.

In fact, Japan, South Korea, India. These large character sets are all similar.

Guessing becomes complicated, requires a large dictionary, and the guess rate is low. So using the BOM invented by Microsoft is the only correct one.

**Comment by jszabo98** [comment]
For what it's worth.  Opening a chinese unicode no bom document (http://www-personal.umich.edu/~dporter/sampler/advocate.gb) in:

```
notepad    ok
uedit64    ok
notepad++  fail
ise        fail
```

**Comment by iSazonov** [comment]
> In fact, Japan, South Korea, India. These large character sets are all similar.

It is true for all non-english. You could feeadback in .Net and Windows - most of (performance) optimizations is done for Latin and english.

**Comment by jszabo98** [comment]
Here's IsTextUnicode() in Powershell, just for kicks.

```powershell
$MethodDefinition = @'
[DllImport("Advapi32",SetLastError=false)]
public static extern bool IsTextUnicode(byte[] buf, int len, ref IsTextUnicodeFlags opt);

[Flags]
public enum IsTextUnicodeFlags:int 
{
  IS_TEXT_UNICODE_ASCII16            = 0x0001,
  IS_TEXT_UNICODE_REVERSE_ASCII16    = 0x0010,

  IS_TEXT_UNICODE_STATISTICS         = 0x0002,
  IS_TEXT_UNICODE_REVERSE_STATISTICS = 0x0020,

  IS_TEXT_UNICODE_CONTROLS           = 0x0004,
  IS_TEXT_UNICODE_REVERSE_CONTROLS   = 0x0040,

  IS_TEXT_UNICODE_SIGNATURE          = 0x0008,
  IS_TEXT_UNICODE_REVERSE_SIGNATURE  = 0x0080,

  IS_TEXT_UNICODE_ILLEGAL_CHARS      = 0x0100,
  IS_TEXT_UNICODE_ODD_LENGTH         = 0x0200,
  IS_TEXT_UNICODE_DBCS_LEADBYTE      = 0x0400,
  IS_TEXT_UNICODE_NULL_BYTES         = 0x1000,

  IS_TEXT_UNICODE_UNICODE_MASK       = 0x000F,
  IS_TEXT_UNICODE_REVERSE_MASK       = 0x00F0,
  IS_TEXT_UNICODE_NOT_UNICODE_MASK   = 0x0F00,
  IS_TEXT_UNICODE_NOT_ASCII_MASK     = 0xF000
}
'@

Add-Type -MemberDefinition $MethodDefinition -Name Advapi32 -Namespace Win32

[Win32.Advapi32+IsTextUnicodeFlags]$opt = 0xffff

$file = $args[0]
$bytes = [io.file]::ReadAllBytes($file)
$result = [win32.advapi32]::IsTextUnicode($bytes, $bytes.length, [ref]$opt)

[pscustomobject]@{
  Result = $result
  Flags = $opt
}


PS C:\users\me> istextunicode hi.txt

Result                                                                            Flags
------                                                                            -----
  True IS_TEXT_UNICODE_STATISTICS, IS_TEXT_UNICODE_CONTROLS, IS_TEXT_UNICODE_NULL_BYTES

```

**Comment by iSazonov** [comment]
If anybody want a progress with the issue please open new issue in CoreFX repo - it is right place for the enhancement. Currently Core team started to plan .Net Core 5.0.
