### ISSUE TITLE
Feature Request: Color output of  gci 

### ISSUE THREAD

**Issue by musm** [PowerShell/PowerShell#9270]
# Summary of the new feature/enhancement
Add colored output so when performing `gci` we have an output that is similar to the colored output in a linux shell.

# Proposed technical implementation details (optional)

https://github.com/joonro/Get-ChildItemColor

**Comment by iSazonov** [comment]
We could track this in  #7857 PSMore.

**Comment by musm** [comment]
Is the PSMore project actively maintained any more ? It seems not.

**Comment by musm** [comment]
Yes it doesn't seem too active.

**Comment by musm** [comment]
Bump, it doesn't seem like it's activate at all?

**Comment by SteveL-MSFT** [comment]
We want to wait until we have a consistent way within the engine to support attributed text

**Comment by SteveL-MSFT** [comment]
I have an implementation here https://github.com/PowerShell/PowerShell/pull/14403

Does the design look reasonable?  Are there other default extensions (with colors/styles) that should be included by default?

Originally I considered supporting images and audio files, but don't necessarily want to add a huge number of entries to the extension hashtable.

**Comment by bfoster68** [comment]
Love this idea because readability is paramount

**Comment by musm** [comment]
Love it. I was never keen on how Ubuntu gives directories a background color, and would be happy if we did not copy that stylistic choice. A distinct foreground color to distinguish folders without a background would be my preference.

**Comment by petervandivier** [comment]
Allowing users to configure `$PROFILE` to customise the colour theme or selectively override defaults for this seems pretty important to me. Even if it's an arcane syntax, the ability to choose (as with [`$LS_COLORS`](https://www.howtogeek.com/307899/how-to-change-the-colors-of-directories-and-files-in-the-ls-command/) for example) should be a first-release feature.

**Comment by Jaykul** [comment]
😖 😕 😠 

Why are core team members wasting time implementing stuff that's [already done](https://github.com/devblackops/Terminal-Icons)
I thought we had **pledged** to stop implementing things in the core that are easily doable by modules?

**Comment by SteveL-MSFT** [comment]
@Jaykul I did this on the weekend on my free time.

**Comment by ThomasNieto** [comment]
Using ansi escape sequences directly isn't very user friendly or verbose. 

I still don't understand why we aren't putting color support directly into the formatting/output layer.

**Comment by SteveL-MSFT** [comment]
@ThomasNieto for consoles, ANSI escape sequences ARE the de facto standard.  PowerShell needs to work with existing native commands that already output ANSI escape sequences.  In this case, the end user does NOT need to work directly with ANSI escape sequences.  That is the whole point of `$PSStyle`.  The formatting shows the "raw" ANSI escape sequences for users that understand them, but otherwise they are colored to what would be rendered.  If a user wanted to change `Directory` to be just blue, they would do:

```powershell
$PSStyle.FileInfo.Directory = $PSStyle.Foreground.Blue
```

**Comment by ThomasNieto** [comment]
Don't users have to use ansi codes if they want to change the color? If so, that isn't use friendly at all. Users have to first figure out what code is being used (people may not even know that it's an ansi code or what ansi is). Once they find out what ansi is then they have to look up what ansi code the color they want to use is.

My point is to have formatting system do all the heavy lifting by providing a user friendly way (enum or something) for format definitions and configuration via preference variable. The formatting system can ansi under the scenes.

**Comment by SteveL-MSFT** [comment]
@ThomasNieto I think you're missing the point of `$PSStyle` that I described above.  Users don't need to understand ANSI escape sequences.  If you want red and green in a string in PowerShell script, it would look like:

```powershell
"$($PSStyle.Foreground.Red)Merry $($PSStyle.Foreground.Green)Christmas"
```

Or combine multiple styles:

```powershell
"$($PSStyle.Italic+$PSStyle.Foreground.Yellow+$PSStyle.Background.Magenta)Hello"
```

With the automatic variable, you also get tab-completion.

**Comment by iSazonov** [comment]
> Users don't need to understand ANSI escape sequences.

I believe most of users would prefer to pick up a predefined color theme and do not waste time manually setting dozens of parameters.
We could look on other applications. MS Office allows select one from 4 predefined themes. Notepad++ has tens "styles" (aka themes) and embedded editor for them.

**Comment by Jaykul** [comment]
> 
> 
> Using ansi escape sequences directly isn't very user friendly or verbose.
> 
> I still don't understand why we aren't putting color support directly into the formatting/output layer.

This _is_ directly in the formatting/output layer. It's modifying the default format.ps1xml (which is in C# now, because it's faster that way)

**Comment by MAGOO56** [comment]
First, I really love this idea! I have two comments:

1. The leading period in the extension property seems redundant. Could this be left out?
2. Can wildcarding or simple regex be used to reduce the number of entries? (eg. 'ps1xml1|ps(d|m)?1' toreplace the separate entries ps1, psd1, psm1, and ps1xml1 which have the same setting)

**Comment by SteveL-MSFT** [comment]
The leading period should probably be left out.  Allowing a regex will make things slower.
