### ISSUE TITLE
List of issues with using as default shell on Linux

### ISSUE THREAD

**Issue by SRGOM** [PowerShell/PowerShell#9272]
[] `gparted` gives `Error executing command as another user: No authentication agent found.`

[] "Unicode" characters have an issue with display. 

[] Unable to `startx` from console.

**Comment by iSazonov** [comment]
Did you configure path env variable?

**Comment by SRGOM** [comment]
Looks like I may not have. I'm going to try later again.

Also thank you for doing a wonderful job with bringing PS to Linux (finally a usable shell!) and for being so responsive to the community!

**Comment by iSazonov** [comment]
We have some related issues for using PowerShell Core like default shell. You could read them. @mklement0 did great review of the area.

**Comment by mklement0** [comment]
Thanks, @iSazonov.

See https://github.com/PowerShell/PowerShell/issues/975#issuecomment-331049792

Glad to hear you're enjoying PowerShell on Linux, @SRGOM

**Comment by chuanjiao10** [comment]
1 powershell as the default shell of linux, how much compatibility can you achieve?

2 Alternatively, use powershell only in the ssh terminal.
```
Pwsh -c 'Add-Content -Value "`nSubsystem powershell /usr/bin/pwsh -sshs -NoLogo -NoProfile" -LiteralPath /etc/ssh/sshd_config '
```
3 Is it possible to add a Boolean automatic variable $AsDefaultShell, if true, for some compatibility settings.

**Comment by SRGOM** [comment]
I did set PATH but at least one problem still remains- unable to start `startx`

`xauth: Unable to lock authority file .Xauthority`

**Comment by iSazonov** [comment]
Fir reference #9173

**Comment by SRGOM** [comment]
Seemingly fixed in preview. Would try out something and reopen if needed.
