### ISSUE TITLE
Get-Module -ListAvailable -Name MSOnline always returns an empty collection when run from .NET Core C#

### ISSUE THREAD

**Issue by zzcraig** [PowerShell/PowerShell#9282]
# Steps to reproduce

```                    
        public void Process(out string error)
        {
            using (var ps = PowerShell.Create())
            {
                ps.AddScript("Get-Module -ListAvailable -Name MSOnline");

                var results = ps.Invoke();

                if (results.Count == 0)
                {
                    error = "You do not have the PowerShell MSOnline module installed.  Please run Install-Module MSOnline in PowerShell, then restart this app.";
                }
                else
                {
                    error = null;
                }
            }
        }

```

I can run the same command directly in PowerShell & it lists MSOnline without an issue.  However, when run from within my .NET project, I get nothing.

I have NuGet packages installed:
Microsoft.PowerShell.SDK 6.2.0
Microsoft.PowerShell.Commands.Diagnostics 6.2.0
Microsoft.WSMan.Management 6.2.0

I have also attempted this in a clean console application with the above code only, on another machine and see the same results!

# Expected behavior

Results should contain one result listing MSOnline.

# Actual behavior

Results is an empty collection

**Comment by vexx32** [comment]
I believe this is down to $env:PSModulePath not being defined in this kind of setup. No assumptions are made about PowerShell actually being installed here, nor where modules might be. You're going to have to set that value appropriately first. :)

**Comment by zzcraig** [comment]
Hmm, interesting.  I have just run $env:PSModulePath from the C# app and can see it does have some path variables set, and those folders contain some modules.

I've tried running Get-Module -ListAvailable from the console app and also get no results.  Considering I do have some module paths, surely I should get at least something?

**Comment by vexx32** [comment]
Assuming they're compatible with PowerShell Core 6.2 I think so.

This kind of issue came up once before, but I can't find the issue right now. I'm sure someone else here has a better idea of where it is, but if not I'll keep looking a bit later.

**Comment by zzcraig** [comment]
Thanks :)

Just to add to this, I have checked the ps.Stream.Errors (and other) collections and am not seeing any errors or warnings or anything else.

**Comment by toddalbers** [comment]
Why was this issue marked as answered?  I don't see any entries above that even come close to answering it.  Others were able to recreate the issue above, but were just as perplexed as the original poster above.  I am experiencing this exact same issue, 2 years after the posts above.  I have not been able to find a solution to it.  It works fine within the PowerShell app and in PowerShell add-in is MS Code.  But, calling it from C# returns 0 results.  I respectfully request that this thread be reopened and that the "Answered" designation be removed.  I am trying to find the solution or explanation for this issue.  If I find it, I will come back here and post it, if I can.  Not even sure if this message will post.

**Comment by eturgeon123** [comment]
still no answer ?
