### ISSUE TITLE
ConvertTo-Csv / Export-Csv do not create valid CSV with new-lines and double-quotes

### ISSUE THREAD

**Issue by jsnape** [PowerShell/PowerShell#9284]
# Steps to reproduce

Using the following as a test (this is valid CSV).

```text
label,testvalue
"blank",""
"null",
"comma","the quick, brown, fox"
"single-quote","the quick 'brown' fox"
"double-quote","the quick ""brown"" fox"
"newline","the quick brown
     fox"
"newline after double-quote","the quick ""brown""
     fox"
"newline before double-quote","the quick ""brown
    "" fox"
"double-quote comma newline","the quick ""brown"",
     fox"
```

```powershell
PS> (gc test.csv | convertFrom-csv) | Export-csv -Path test2.csv -NoTypeInformation
# or
PS> (gc test.csv | convertFrom-csv) | ConvertTo-Csv -NoTypeInformation | Out-File -Path test2.csv -NoTypeInformation
```

# Expected behavior

The output file should look the same as the input file

# Actual behavior

Its OK that there are quotes around everything now but the formatter has closed the double-quote before the line break and as a result introduced new records into the file.

```text
"label","testvalue"
"blank",""
"null",
"comma","the quick, brown, fox"
"single-quote","the quick 'brown' fox"
"double-quote","the quick ""brown"" fox"
"newline","the quick brown"
"fox""",
"newline after double-quote","the quick ""brown"""
"fox""",
"newline before double-quote","the quick ""brown"
" fox""",
"double-quote comma newline","the quick ""brown"","
"fox""",
```

# Environment data

```PowerShell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by banoresaurabh** [comment]
Hi there, I would like to work on this issue.

**Comment by vexx32** [comment]
It's `Up-for-Grabs`, so feel free to have at it. 😄

**Comment by rspears74** [comment]
I've been looking at this. The `-UseQuotes` parameter can be used to specify whether or not to use quotes. Default is `Always`. I tried specifying `Never` and sure enough the output has mostly no quotes, with a few odd extras left over. The `AsNeeded` option, which seems like what should be the default, returns a null object error and the output csv stops right after the comma after `blank`, which probably explains why it's not the default.

**Comment by bobbytreed** [comment]
I was preparing to document this and ran into the same issue as @rspears74. The error is not very descriptive at all and really doesn't tell you what you need to do to resolve it.

**Comment by vexx32** [comment]
Given that typically newlines are record separators in a CSV file, it almost seems like we should be _encoding_ newlines somehow in the file. Is there an established standard for doing so?

**Comment by jsnape** [comment]
@vexx32 No there isn't a standard for escaping control characters. That would be more like CTX: http://www.creativyst.com/Doc/Std/ctx/ctx.htm

There is a secondary standard which uses an escape character instead e.g. backslash before the newline; a bit like unix pipe delimited files. However this is not supposed to be mixed with quoted fields. i.e. you either quote or escape. A lot of csv parsers don't handle the quoted version though.

If you are asking about converting the newlines to something else e.g. \r\n then, no there is nothing standard about this. That is outside the scope of CSV since really it depends on the reader and writer of these files. Given PowerShell is such a good toolbelt then we could be looking to read and write csv written by many other applications.

**Comment by vexx32** [comment]
Right, but if most CSV parsers can't handle newlines -- should we?

**Comment by iSazonov** [comment]
We could look how Excel output multi line cells to csv.

**Comment by lselden** [comment]
Is this too stale to re-comment on? This is still an issue as of Powershell v7.2-preview6. If you use `-UseQuotes AsNeeded` then fields with newlines or quotes won't be formatted properly. As per @jsnape There is an accepted standard for escaping fields (RFC4180) that has the following relevant rules ([link](https://datatracker.ietf.org/doc/html/rfc4180#section-2)):



> 6.  Fields containing line breaks (CRLF), double quotes, and commas
>        should be enclosed in double-quotes.

> 7.  If double-quotes are used to enclose fields, then a double-quote
>        appearing inside a field must be escaped by preceding it with
>        another double quote.

The `Import-Csv` and `ConvertFrom-Csv` both correctly handle CSVs formatted in this standard. Additionally, it's the standard used by multiple popular tools, like Excel, Google Sheets, (CsvHelper)[https://joshclose.github.io/CsvHelper/], and (fast-csv)[https://github.com/C2FO/fast-csv].

Relevant code:
* (Format Headers)[https://github.com/PowerShell/PowerShell/blob/v7.2.0-preview.6/src/Microsoft.PowerShell.Commands.Utility/commands/utility/CsvCommands.cs#L970]
* (Format Lines)[https://github.com/PowerShell/PowerShell/blob/v7.2.0-preview.6/src/Microsoft.PowerShell.Commands.Utility/commands/utility/CsvCommands.cs#L1041
https://github.com/PowerShell/PowerShell/blob/v7.2.0-preview.6/src/Microsoft.PowerShell.Commands.Utility/commands/utility/CsvCommands.cs#L970]

To be RFC-4180 compliant you'd quote if you detect any newline characters (`[\r\n]`), the escape character (i.e. `"`) or the delimiter (i.e. `"` or `\t`).

**Comment by kganjam** [comment]
I have a file that is tab delimited and includes quoted strings. Python's [csv library](https://docs.python.org/3/library/csv.html#csv.Dialect) has an option to not interpret quotes (quoting=csv.QUOTE_NONE). It would be nice if PowerShell had an option for this, otherwise I don't have a straightforward way to properly read these files. 

e.g., the following loses quotes even though I am using simple tab delimited format:

```
"`"foo`"`t`"bar`", a`ta, `"baz`"`n`"foo`"`t`"bar`", a`ta, `"baz`"" | convertfrom-csv -Delimiter "`t"
```
```
foo bar, a a, "baz"
--- ------ --------
foo bar, a a, "baz"
```

**Comment by lselden** [comment]
(Please excuse formatting - on mobile)

Is this reading a file? This issue is about converting TO  CSVs rather than
from. Have you tried replacing the quotes before converting?

# try using double doublequotes, that’s standard CSV quote escaping. If
that doesn’t work try another like null char `0 or vertical tab `v
$replaceChar = '""'

(Get-Content myfile.tsv -Raw) -replace '"',$replaceChar | ConvertFrom-Csv
-Delimiter "`t"

If it’s converting TO a CSV then I’d be surprised if it doesn’t maintain
quotes - please provide sample code. Try with -UseQuotes Never

**Comment by jsnape** [comment]
This issue still exists on PowerShell 7.3:

```PowerShell
PS>  $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

The output is still incorrect and unchanged from above:

```csv
"label","testvalue"
"blank",""
"null",
"comma","the quick, brown, fox"
"single-quote","the quick 'brown' fox"
"double-quote","the quick ""brown"" fox"
"newline","the quick brown"
"fox""",
"newline after double-quote","the quick ""brown"""
"fox""",
"newline before double-quote","the quick ""brown"
" fox""",
"double-quote comma newline","the quick ""brown"","
"fox""",
```

**Comment by jsnape** [comment]
Before:
```CSV
label,testvalue
"blank",""
"null",
"comma","the quick, brown, fox"
"single-quote","the quick 'brown' fox"
"double-quote","the quick ""brown"" fox"
"newline","the quick brown
     fox"
"newline after double-quote","the quick ""brown""
     fox"
"newline before double-quote","the quick ""brown
    "" fox"
"double-quote comma newline","the quick ""brown"",
     fox"
```

After:
```CSV
"label","testvalue"
"blank",""
"null",
"comma","the quick, brown, fox"
"single-quote","the quick 'brown' fox"
"double-quote","the quick ""brown"" fox"
"newline","the quick brown"
"fox""",
"newline after double-quote","the quick ""brown"""
"fox""",
"newline before double-quote","the quick ""brown"
" fox""",
"double-quote comma newline","the quick ""brown"","
"fox""",
```

![image](https://github.com/PowerShell/PowerShell/assets/1582936/5433d754-13e8-49e2-a90e-b0b7a664d8a5)

The main issue is the fields with newlines and double-quotes in at the end.

**Comment by lselden** [comment]
This is my test code - I don't get those extra entries:
```powershell
$original = @"
label,testvalue
"blank",""
"null",
"comma","the quick, brown, fox"
"single-quote","the quick 'brown' fox"
"double-quote","the quick ""brown"" fox"
"newline","the quick brown
     fox"
"newline after double-quote","the quick ""brown""
     fox"
"newline before double-quote","the quick ""brown
    "" fox"
"double-quote comma newline","the quick ""brown"",
     fox"
"@;
$lines = $original | ConvertFrom-Csv;
$converted = $lines | ConvertTo-Csv -UseQuotes AsNeeded;
$convertedLines = $converted | ConvertFrom-Csv;
$lines | Compare-Object $convertedLines -Property label,testvalue -IncludeEqual -SyncWindow 1
```
![image](https://github.com/PowerShell/PowerShell/assets/2904993/c334542d-f4ab-41b5-b3a0-f02deb75421c)

**Comment by jsnape** [comment]
Your code does indeed give your result. So what is the difference between your script and my:

```PowerShell
(gc test.csv | convertFrom-csv) | ConvertTo-Csv -UseQuotes AsNeeded -NoTypeInformation | Out-File -Path test2.csv
```

Does the get-content make a difference?

@lselden Can you try the line above and see if it still works for you?

**Comment by lselden** [comment]
> 
> @lselden Can you try the line above and see if it still works for you?

The difference is you're missing the [`-Raw` parameter ](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-content?view=powershell-7.4#-raw) in your `Get-Content`, which means you're stripping the newlines out.

**Comment by jsnape** [comment]
🤦🏼‍♂️ doh. my bad... I can confirm this works just fine. Its just a PEBKAC issue now. Happy to close.
