### ISSUE TITLE
installpsh-amazonlinux.sh not detecting amazon linux

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/PowerShell#9285]
# Windows PowerShell

I can't figure out what commit did this, but the OS detection routine in installpsh-amazonlinux.sh has been dramatically simplified from what is still in install-powershell.sh.

It is now missing the amazon linux detection routines.

The original design allowed for the underlying installers to be called directly - but they still need the full linux detection routine in order validate they are being run on the correct OS.

My container builds that install PowerShell are now failing: 

https://gitlab.com/DarwinJS/amazon-linux-2-container-with-powershell/-/jobs/189478956
https://gitlab.com/DarwinJS/amazon-linux-2-ec2-build-container-with-powershell/-/jobs/189478955

For the time being I'm going to switch my build to a known working branch in my own fork of this repo.

Is there a reason this does not show up in automated testing?

I don't personally have the time to fix this.

/cc @TravisEz13

**Comment by TravisEz13** [comment]
Yup... I am waiting on feedback on two issues in the docker repo before I can add tests for amazon linux.


https://github.com/PowerShell/PowerShell-Docker/issues/200

On this issue, I think we can move these changes in to the sub-image proposed by 200, assuming we go with that solution.
https://github.com/PowerShell/PowerShell-Docker/issues/178

**Comment by TravisEz13** [comment]
I have a PR adding CI for this and the script is working fine.  At least calling it through `install-powershell.sh`
https://github.com/PowerShell/PowerShell/pull/9314

**Comment by DarwinJS** [comment]
As I mentioned, the original intent was that if you knew your distro, you wouldn't need two scripts to get the job done.

It looks like the sub-installers are now dot sourced into the overall script - which means the distro detection is passing through.

But then this big block of now non-working (for Amazon Linux) distro detection in the sub-install script is unnecessary if the sub-install is going to always assume it is called from the overall: https://github.com/PowerShell/PowerShell/blob/master/tools/installpsh-amazonlinux.sh#L53-L83

I liked it the original way because for those of us who are automating a known distro we don't need two internet downloads - or any actually.  And then these sub-installs can self-validate that you are running them on the proper platform.

**Comment by TravisEz13** [comment]
This is the only change not by you, although you reviewed the change:
https://github.com/PowerShell/PowerShell/pull/9071

I'm adding a CI job for your scenario to my PR.
