### ISSUE TITLE
checksum seems to be wrong

### ISSUE THREAD

**Issue by maxfunke** [PowerShell/PowerShell#9291]
The chechsum for v6.2.0 for alpine is not the same as expected. Therefore I guess my following command fails (after downloading of course):

```bash
tar zvxf /tmp/ps.tar.gz -C $MY_PS_INSTALL_FOLDER
gzip: invalid magic
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

# Steps to reproduce

download tar.gz for 
```bash
curl https://github.com/PowerShell/PowerShell/releases/download/v6.2.0/powershell-6.2.0-linux-alpine-x64.tar.gz --output /tmp/ps.tar.gz

sha256sum /tmp/ps.tar.gz
```

# Expected behavior

returns same checksum as listed in release v6.2.0
```none
A44243CA24AF415F7393C53BE6BF3E7A5B546B79C9F3F870F9A974CAFE8831E6  /tmp/ps.tar.gz
```

# Actual behavior

returns different checksum
```none
189a52e839f598b15c3c024e61b231e53de234fd5bb43ffdbffe0b1262a8eece  /tmp/ps.tar.gz
```

# Environment data

```none
curl 7.58.0
tar 1.29
sha256sum 8.28
```

**Comment by iSazonov** [comment]
I downloaded the file and opened without problem. It seems you have cached broken file.

**Comment by chuanjiao10** [comment]
e:\DL\powershell-6.2.0-linux-alpine-x64.tar.gz  
A44243CA24AF415F7393C53BE6BF3E7A5B546B79C9F3F870F9A974CAFE8831E6

**Comment by maxfunke** [comment]
Cache maybe was a problem. Thanks
