### ISSUE TITLE
Delimiting lines have reduced or disappeared since version 6.2.0

### ISSUE THREAD

**Issue by 1morechill** [PowerShell/PowerShell#9299]
Running the following command (as an example) :
`gci C:\Windows\System32 -Filter win*.exe -Depth 1 -ErrorAction SilentlyContinue | ft Name,Length -GroupBy Directory`

### Returns delimiting lines between the grouped-by object and the property headers on version 6.1.3 (and Desktop Edition 5.1.x as well) : 

   Directory: C:\Windows\System32

Name                                  Length
----                                  ------
WinBioDataModelOOBE.exe                60928
Windows.Media.BackgroundPlayback.exe   13312
Windows.WARP.JITService.exe            32768
WindowsActionDialog.exe                60928
WindowsUpdateElevatedInstaller.exe     47104
wininit.exe                           388376
winload.exe                          1468952
winlogon.exe                          779776
winresume.exe                        1179680
winrs.exe                              50176
winrshost.exe                          28672
WinSAT.exe                           2800128
winver.exe                             58880

   Directory: C:\Windows\System32\Boot

Name           Length
----           ------
winload.exe   1468952
winresume.exe 1179680

   Directory: C:\Windows\System32\oobe

Name          Length
----          ------
windeploy.exe 177664

   Directory: C:\Windows\System32\wbem

Name        Length
----        ------
WinMgmt.exe  82432

### **While grouped-by object and property headers are stuck together on version 6.2.0 as delimiting lines have disappared :**

   Directory: C:\Windows\System32
Name                                  Length
----                                  ------
WinBioDataModelOOBE.exe                60928
Windows.Media.BackgroundPlayback.exe   13312
Windows.WARP.JITService.exe            32768
WindowsActionDialog.exe                60928
WindowsUpdateElevatedInstaller.exe     47104
wininit.exe                           388376
winload.exe                          1468952
winlogon.exe                          779776
winresume.exe                        1179680
winrs.exe                              50176
winrshost.exe                          28672
WinSAT.exe                           2800128
winver.exe                             58880

   Directory: C:\Windows\System32\Boot
Name           Length
----           ------
winload.exe   1468952
winresume.exe 1179680

   Directory: C:\Windows\System32\oobe
Name          Length
----          ------
windeploy.exe 177664

   Directory: C:\Windows\System32\wbem
Name        Length
----        ------
WinMgmt.exe  82432

**Comment by SteveL-MSFT** [comment]
Delimiting lines here means adding extra whitespace?  The extra newlines were removed on purpose.

**Comment by iSazonov** [comment]
![image](https://user-images.githubusercontent.com/22290914/65837111-2b2d9b80-e30d-11e9-9bc1-af9605570285.png)

**Comment by rkeithhill** [comment]
Ah, if I just run gci on that dir I see proper space:
 
![image](https://user-images.githubusercontent.com/5177512/65837344-5a172380-e2b3-11e9-802a-57d032079ee1.png)

But running it through the `Format-Table -GroupBy` is resulting in the missing line.

**Comment by SteveL-MSFT** [comment]
Ok, I agree that the two should match.  I'll look into this tomorrow.

**Comment by 1morechill** [comment]
Many thanks
