### ISSUE TITLE
PowerShell classes leak to other runspaces on macOS

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/PowerShell#9313]
# Steps to reproduce

```powershell
class MyClass {
    # Property: Holds name
    [String] $Name

    # Constructor: Creates a new MyClass object, with the specified name
    MyClass([String] $NewName) {
    # Set name for MyClass
      $this.Name = $NewName
    }

    # Method: Method that changes $Name to the default name
    [void] ChangeNameToDefault() {
      $this.Name = "DefaultName"
    }
  }
[MyClass].GetType()
[PowerShell]::Create().AddScript('[MyClass]::new("ffff")').Invoke()
```

# Expected behavior

Class types should not leak to other runspaces.

# Actual behavior

Type was able to be created in other runspace.
![image](https://user-images.githubusercontent.com/2644648/55677077-612a1f80-5896-11e9-8823-727c9656279d.png)

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Darwin 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

# Notes

This doesn't repro without _using_ the class in some way (i.e. calling `[MyClass].GetType()`). That part is important.

cc @daxian-dbw who wasn't able to repro this (I assume on Windows? Using PowerShell Core 6.2?)

**Comment by vexx32** [comment]
@TylerLeonhardt been a while since I played with it, but don't new `[powershell]` instances execute in the current runspace unless you manually assign them a new one?

**Comment by TylerLeonhardt** [comment]
I'm pretty sure they're in a new runspace because `Get-Runspace` returns another runspace. Just to be sure, I tried manually creating a new runspace and the issue still repros:

```pwsh
class MyClass {
    # Property: Holds name
    [String] $Name

    # Constructor: Creates a new MyClass object, with the specified name
    MyClass([String] $NewName) {
        # Set name for MyClass
        $this.Name = $NewName
    }

    # Method: Method that changes $Name to the default name
    [void] ChangeNameToDefault() {
        $this.Name = "DefaultName"
    }
}
$rs = [runspacefactory]::CreateRunspace()
$rs.Open()
[MyClass].GetType()
[PowerShell]::Create($rs).AddScript('[MyClass]::new("ffff")').Invoke()
```

**Comment by rkeithhill** [comment]
Windows  PowerShell 5.1 behaves the same way.  A loaded type definition is available process wide unless maybe the process is using AppDomains for isolation but 5.1 doesn't appear to use AppDomains.  And there is no support for AppDomains in .NET Core anyway.

**Comment by SeeminglyScience** [comment]
@rkeithhill I'd expect the type to still be loaded, but I wouldn't expect PowerShell to resolve it since resolution is scope based:

```powershell
& {
    class MyClass {}
}

# Returns the above class
[AppDomain]::CurrentDomain.GetAssemblies().
    Where{
        [Reflection.CustomAttributeExtensions]::IsDefined(
            $_,
            [Management.Automation.DynamicClassImplementationAssemblyAttribute])
    }.ForEach{
        # The types sometimes have a distinguishing namespace
        $_.Modules[0].FindTypes([Reflection.Module]::FilterTypeName, 'MyClass')
    }

# Throws type not found
[MyClass]
```

**Comment by daxian-dbw** [comment]
PSReadLine plays a role in the repo. To get consistent repro on all platforms (including powershell.exe), do the following:
1. start pwsh/powershell.exe with `-noprofile`
2. copy the following to pwsh/powershell.exe:
```
class MyClass {
    # Property: Holds name
    [String] $Name

    # Constructor: Creates a new MyClass object, with the specified name
    MyClass([String] $NewName) {
    # Set name for MyClass
      $this.Name = $NewName
    }

    # Method: Method that changes $Name to the default name
    [void] ChangeNameToDefault() {
      $this.Name = "DefaultName"
    }
  }
```
3. copy the following to pwsh/powershell:
```
[MyClass].GetType()
[PowerShell]::Create().AddScript('[MyClass]::new("ffff")').Invoke()
```
Then you will see the `Name: ffff` printed out.

--------------------------------------------

The moment you remove PSReadLine, this won't repro. This is because PSReadLine always parse the input before it's sent to engine to execute. The parsing involves resolving `[MyClass]`, and put it in the type cache with the wrong `TypeResolutionState`.
