### ISSUE TITLE
invoke-webrequest support socks5

### ISSUE THREAD

**Issue by zepprebel** [PowerShell/PowerShell#9319]
Hello,

As you probably know or not, Telegram app are blocked on the territory of the Russian Federation, it would be great to add support for **socks5** to **invoke-webrequest**, this will greatly help Russian users)

P. S sorry for my bad english/ from Russian with love)

**Comment by iSazonov** [comment]
PowerShell Core is based on .Net Core API HttpClient. Please vote there https://github.com/dotnet/corefx/issues/9768
