### ISSUE TITLE
Get-Date and .AddSeconds() inconsistent with UTC-local time conversion

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell#9320]
This issue is copied from https://github.com/MicrosoftDocs/PowerShell-Docs/issues/4127.
Originally submitted by @rwlangeveld.

---

Issue Details
-----------------

Converting from UTC to local time with DST (being CEST in my case) seems to give unexpected results.
I ran into this issue while converting Unix (epoch) time to a PowerShell/.Net datetime object. I take 
00:00:00 AM, January 1, 1970 (UTC) as a starting point, and add the given Unix time (in seconds) to it. Then I want to translate that to the correct local time.
In winter, this works fine in multiple ways. In summer, using DST, this seems not to give me the expected results in most ways. Only one way, I got this to work. Which at least seems to be very inconsistent...

Examples
-----------------
_NB. I translated the day- and month names in the examples from Dutch to English manually._

I start with specifying the begin date as '01-01-1970 00:00:00Z', with 'Z' denoting this as being UTC.
When adding only one second, and converting to local time, all seems find.
Since January 1 is in the winter, no DST is involved in local time (CET = UTC+1). UTC does not have DST.

PS H:\> (Get-Date '01-01-1970 00:00:00Z').AddSeconds(1).TolocalTime()
Thursdag 1 January 1970 01:00:01

PS H:\> (Get-Date '01-01-1970 00:00:00Z').TolocalTime().AddSeconds(1)
Thursdag 1 January 1970 01:00:01

When not specifying UTC. The time region is unspecified, therefore should be assumed to be UTC, when translating to local time, I expect. This seems to be true:

PS H:\> (Get-Date '01-01-1970 00:00:00').AddSeconds(1).TolocalTime()
Thursdag 1 January 1970 01:00:01

PS H:\> (Get-Date '01-01-1970 00:00:00').TolocalTime().AddSeconds(1)
Thursdag 1 January 1970 01:00:01

When adding enough seconds to enter DST in local time (CEST = UTC+2), however, things get a little unexpected... 
I add exactly 181 days (181d * 24h/d * 60m/h * 60s/m = 15638400 seconds).
In UTC I expect to be at midnight again. But since this new date is in the summer, in local time, I expect to be 2 hours later.. (Since local time is CE**S**T now, being CET+DST, being UTC+2.)

PS H:\> (Get-Date '01-01-1970 00:00:00Z').AddSeconds(15638400).TolocalTime()
Wednesday 1 July 1970 0**1**:00:00
Seems to be a bug to me...! Converting UTC to CEST here, should be **+2** hours!

PS H:\> (Get-Date '01-01-1970 00:00:00Z').TolocalTime().AddSeconds(15638400)
Wednesday 1 July 1970 0**1**:00:00
Seems to be a bug to me...! Converting UTC to CET here, should be +1 hour. However, **adding enough time to enter CEST (CET+DST) this should have been corrected by +1 hour**...

PS H:\> (Get-Date '01-01-1970 00:00:00').AddSeconds(15638400).TolocalTime()
Wednesday 1 July 1970 02:00:00
**CORRECT!**

PS H:\> (Get-Date '01-01-1970 00:00:00').TolocalTime().AddSeconds(15638400)
Wednesday 1 July 1970 0**1**:00:00
Wrong again...

This seems to be a bug in the (lack of) implementation of DST conversion in time calculations to me.

Any help, feedback or bugfix would be appreciated.
Thank you in advance.

Rogier Langeveld

Version(s) of document impacted
------------------------------
- [?] Impacts 6.next document
- [?] Impacts 6 document
- [X] Impacts 5.1 document
- [?] Impacts 5.0 document
- [?] Impacts 4.0 document
- [?] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
Some more results...:

PS H:\> (Get-Date '01-01-1970 00:00:00Z')
donderdag 1 januari 1970 01:00:00
_as expected. Automatically converted to local time, being in CET = UTC+1_

PS H:\> (Get-Date '01-01-1970 00:00:00Z').ToLocalTime()
donderdag 1 januari 1970 01:00:00
_as expected. Automatically converted to local time, being in CEST = UTC+1, manually converted to local time, staying the same_

PS H:\> (Get-Date '01-07-1970 00:00:00Z')
woensdag 1 juli 1970 02:00:00
_exactly 181 days after '01-01-1970 00:00:00Z'_
_as expected. Automatically converted to local time, being in CEST = CET+DST = UTC+2_

PS H:\> (Get-Date '01-07-1970 00:00:00Z').ToLocalTime()
woensdag 1 juli 1970 02:00:00
_exactly 181 days after '01-01-1970 00:00:00Z'_
_as expected. Automatically converted to local time, being in CEST = CET+DST = UTC+2, manually converted to local time, staying the same_

PS H:\> (Get-Date '01-01-1970 00:00:00Z').AddSeconds(15638400)
woensdag 1 juli 1970 01:00:00
NOT as expected. Being exactly 181 days after '01-01-1970 00:00:00Z'_, but in CEST now. Should be as above.

PS H:\> (Get-Date '01-01-1970 00:00:00Z').AddSeconds(15638400).ToLocalTime()
woensdag 1 juli 1970 01:00:00
NOT as expected. Being exactly 181 days after '01-01-1970 00:00:00Z'_, but in CEST now. Should be as above.

(15638400 seconds = 181 days)
Just to be sure...:  

PS H:\> Get-TimeZone
Id                         : W. Europe Standard Time
DisplayName                : (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
StandardName               : W. Europe Standard Time
DaylightName               : W. Europe Summer Time
BaseUtcOffset              : 01:00:00
SupportsDaylightSavingTime : True

**Comment by rjmholt** [comment]
Looking into this, a problem is that being in UTC+1 leads to deceptive examples (I'm running in UTC-8).

These actual behaviours are in .NET rather than in PowerShell.

```
> ([datetime]'01-01-2018 00:00:00')

Monday, January 1, 2018 12:00:00 AM

```

```
> ([datetime]'01-01-2018 00:00:00').AddSeconds(15638400)

Sunday, July 1, 2018 12:00:00 AM

```

```
> ([datetime]'01-01-2018 00:00:00').AddSeconds(15638400).ToLocalTime()

Saturday, June 30, 2018 5:00:00 PM

```

The part to watch here is the [`Kind`](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.kind?view=netcore-2.2):

```
> (Get-Date '01-01-2018 00:00:00').Kind
Unspecified

> ([datetime]'01-01-2018 00:00:00').Kind
Unspecified

> (Get-Date '01-01-2018 00:00:00Z').Kind
Local

> ([datetime]'01-01-2018 00:00:00Z').Kind
Local
```

It looks like a `DateTime` value will retain its kind and will behave and be displayed appropriately. `Unspecified` seems to behave the same as `Utc`, but I think the distinction exists to record that the timezone was not explicitly given.

This means that when a `Local` time is not DST, it **will not be converted to DST** when time is added. It keeps its original timezone (where the DST timezone is treated as distinct from the standard one). But when `ToLocalTime()` is used, it converts the time to the appropriate local timezone that applies *at the time of the datetime value*:

```
> ([datetime]'01-01-2018 00:00:00')

Monday, January 1, 2018 12:00:00 AM

> ([datetime]'01-01-2018 00:00:00').ToLocalTime()

Sunday, December 31, 2017 4:00:00 PM

> ([datetime]'01-01-2018 00:00:00').AddSeconds(15638400)                                                                     
Sunday, July 1, 2018 12:00:00 AM

> ([datetime]'01-01-2018 00:00:00').AddSeconds(15638400).ToLocalTime()

Saturday, June 30, 2018 5:00:00 PM

> ([datetime]'01-01-2018 00:00:00Z')

Sunday, December 31, 2017 4:00:00 PM

> ([datetime]'01-01-2018 00:00:00Z').ToLocalTime()

Sunday, December 31, 2017 4:00:00 PM

> ([datetime]'01-01-2018 00:00:00Z').AddSeconds(15638400)

Saturday, June 30, 2018 4:00:00 PM

> ([datetime]'01-01-2018 00:00:00Z').AddSeconds(15638400).ToLocalTime()

Saturday, June 30, 2018 4:00:00 PM

```

In any event, the actual semantics of `System.DateTime` are determined by .NET -- we can't really fix them.

**Comment by rjmholt** [comment]
But there's not great documentation of this stuff in the .NET docs. May with worth opening an issue with them.
