### ISSUE TITLE
Zip release packages should not have PDB files

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#9321]
# Steps to reproduce

Expand any PowerShell package release. 

# Expected behavior

No PDB files should be present.

# Actual behavior

Multiple PDB files are present in the package. They also differ according to the bit-ness of the package.

# Environment data

```none

Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.18875
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
In 7.0 Preview4 I see only two PDB files
![image](https://user-images.githubusercontent.com/22290914/65832941-2e606180-e2e4-11e9-8729-3ef841247d57.png)

**Comment by SteveL-MSFT** [comment]
The .tgz also has the same pdbs.  Seems like when we tar and zip, we should just exclude pdb files.

**Comment by anmenaga** [comment]
`7.0.0-rc.2-linux-arm32.tar.gz` package has these:
```
root@pi:~# ls -1 ./PS700RC2/*.pdb
./PS700RC2/Microsoft.PowerShell.Commands.Management.pdb
./PS700RC2/Microsoft.PowerShell.Commands.Utility.pdb
./PS700RC2/Microsoft.PowerShell.ConsoleHost.pdb
./PS700RC2/Microsoft.PowerShell.MarkdownRender.pdb
./PS700RC2/Microsoft.PowerShell.SDK.pdb
./PS700RC2/Microsoft.PowerShell.Security.pdb
./PS700RC2/pwsh.pdb
./PS700RC2/System.Management.Automation.pdb
```

**Comment by SteveL-MSFT** [comment]
`tar` has `--exclude` that can exclude the pdbs, but `Compress-Archive` doesn't have such a capability currently.  Although you can pipe files to `Compress-Archive`, it doesn't work correctly with folders so you can't use that to exclude pdbs.  Seems ok to just delete the pdbs from the source location prior to packaging...

**Comment by iSazonov** [comment]
Oh, it seems we have so many issues that lost important ones. Maybe we should triage every new one and include in GitHub projects and set a milestone. I any case the issue workflow should be improved.

**Comment by iSazonov** [comment]
> Seems ok to just delete the pdbs from the source location prior to packaging...

Maybe it is better to _move_ them in a folder because we seem have a request publish pdb-s too?

**Comment by SteveL-MSFT** [comment]
I believe the request is to publish symbols separately, so we need a package that has all the symbols for a released build making it easier to debug issues.  So for that, I agree it would make sense to copy all the symbols to a separate folder and build a separate package for that.
