### ISSUE TITLE
6.2.0 release shows incorrect PowerShellGet version being used

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#9334]
In the Build and Packaging improvements of the release notes it shows

```
Bump PowerShellGet from 2.0.4 to 2.1.1 in /src/Modules (#9110, #9145)
```

however v6.2.0 ships with PowerShellGet 2.1.2

cc @TravisEz13

**Comment by TravisEz13** [comment]
This was a typo, when consolidating the messages for the two PRs.
