### ISSUE TITLE
Which Raspberry device's operaring system does powershell support? 

### ISSUE THREAD

**Issue by uemahra** [PowerShell/PowerShell#9340]
Hi,
On Raspberry, there are a lot of operating systems, like Raspbian, CentOS ARM, FreeBSD ARM, Kali linux ARM, OpenWRT...
I use powershell mainly on Raspberry, so which operating systems does powershell support?

**Comment by anzenketh** [comment]
Please see the following for what Platforms are supported.
https://devblogs.microsoft.com/powershell/powershell-core-6-0-generally-available-ga-and-supported/

**Comment by anzenketh** [comment]
Please see https://devblogs.microsoft.com/powershell/powershell-core-6-0-generally-available-ga-and-supported/ for the supported platforms.
