### ISSUE TITLE
Powershell cannot be found on Ubuntu 18.04

### ISSUE THREAD

**Issue by akshaybabloo** [PowerShell/PowerShell#9347]
I am still unable to install powershell in Ubuntu 18.04, I get an error `Unable to locate package powershell`. I have also tried adding `sudo add-apt-repository universe`, still same.

**Comment by MaximoTrinidad** [comment]
Can you provide the actual installation cmd line you use to try install PowerShell? 
Which version of PowerShell you're trying to install?
Did you follow the installation instructions in Github(https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-6#ubuntu-1804)?

Please provide all steps to reproduce the issue as without it is impossible to see what's wrong.
