### ISSUE TITLE
Support Question: Where to file bugs with Storage module?

### ISSUE THREAD

**Issue by jzabroski** [PowerShell/PowerShell#9350]
# Support Question

Where to file bugs with Storage module?

Example: `Get-Disk` does not actually return all disks associated with an operating system. In particular, Amazon AWS EBS Volumes do not return, at least on `r5d` instances.

**Comment by iSazonov** [comment]
You could use Windows Feedback tool and UserVoice site.

**Comment by jzabroski** [comment]
@iSazonov  I found the root cause and submitted a PR to improve the docs : https://github.com/MicrosoftDocs/windows-powershell-docs/pull/990
