### ISSUE TITLE
Feature Request: intellisense in powershell windows

### ISSUE THREAD

**Issue by khoshroomahdi** [PowerShell/PowerShell#9358]
# Summary of the new feature/enhancement
i like to have intellisense in powershell windows

# Proposed technical implementation details (optional)

**Comment by vexx32** [comment]
You might have to explain a bit more what you mean.

PowerShell by default already has intellisense provided through PSReadLine. Is it not showing up for some reason?

**Comment by SeeminglyScience** [comment]
@vexx32 technically intellisense refers to automatic suggestions like when typing in an editor.  PowerShell's tab completion often gets referred to as intellisense (I have bad habit of this) when it isn't really. The feature proposed in lzybkr/PSReadLine#687 would count, or something like the [PowerTab](https://github.com/jasonmarcher/PowerTab) project if it was triggered on key press.

**Comment by khoshroomahdi** [comment]
I have intellisense on ise but not in powershell

**Comment by iSazonov** [comment]
PSReadline is best place for the feature implementation.
