### ISSUE TITLE
What is the Export-Command assembly

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#9361]
There's an assembly granted `InternalsVisibleTo` called `Export-Command` but I can't find any information on it.

https://github.com/PowerShell/PowerShell/blob/13fd3af8106dbfd5d65e697036af5999255badc7/src/System.Management.Automation/AssemblyInfo.cs#L22-L27

Maybe worth a comment above the attribute if it's an internal only tool or something along those lines.

**Comment by iSazonov** [comment]
@SteveL-MSFT Can we remove the reference?

**Comment by SteveL-MSFT** [comment]
I searched the old WinPS code base and there is a reference to old test code of an `Export-Command` that was removed.  I think we should just remove this from our code.
