### ISSUE TITLE
$? not work in function prompt

### ISSUE THREAD

**Issue by clouds56** [PowerShell/PowerShell#9363]
# Steps to reproduce

set `profile.ps1` to
```powershell
function Prompt {
  if ($? -ne $true) { "false" } else { "true" } + " > "
}
```
and in the shell run some cmdlet that would fail
```powershell
true > some to fail
true > $?
False
true > 
```

# Expected behavior

```none
true > some to fail
false > $? # should prompt false here
False
true > 
```

# Actual behavior

```none
true > some to fail
true > $? # still true
False # this is correct "false"
true > 
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.18875
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
It seems to work fine for me (also when I place the function in my `$PROFILE`):

```powershell
PS> function Prompt { "$?> " }
True> 1 / 0
# ... error message
False>
```

Can you given an example command where it doesn't work?

Also note that `$?` may not always have the value you expect: see #3359

**Comment by clouds56** [comment]
Thanks for help!
I see, and I found that it is conda that shadows the value
```
# from Conda.psm1
function prompt() {
    if ($Env:CONDA_PROMPT_MODIFIER) {
        $Env:CONDA_PROMPT_MODIFIER | Write-Host -NoNewline
    }
    CondaPromptBackup;
}
```

**Comment by clouds56** [comment]
I cannot think of a way for my script to work with `$?` in prompt without aware of other prompts
The state of last statement is so important in prompt, could we have a command that restore `$?`, since `Set-Variable -Name ? -Value $false -Force` won't work here, the successfully `Set-Variable` would set `$?` to `$true` anyway
```powershell
$ErrorStatus = $?
# some command here
Restore-ErrorStatus $ErrorStatus
```
or have another auto variable like `$StatusOfShell` that only reflect status of command run in shell, for `prompt` and other functions to run.

**Comment by iSazonov** [comment]
Close as stale issue. Feel free to continue discussion.
