### ISSUE TITLE
Limit of 32 parameter sets

### ISSUE THREAD

**Issue by MiYanni** [PowerShell/PowerShell#9372]
# Summary
I didn't know to enter this as a bug, a documentation issue, or a feature request. Basically, **there is a limit of 32 usable parameter sets**. This hard limit is not documented anywhere (from what I could find). There is a blog post about it from 2015 for someone using *PowerShell 3.0*:
https://www.craig-tolley.co.uk/2015/07/01/maximum-number-of-powershell-parameter-sets-in-function/

The reason is that the maximum number of parameter sets that can be associated with a parameter is 32. It is 32 because a `uint` (32-bit number) is storing a bitmask of which parameter sets that parameter is part of. In a technical sense, there is allowed up to `uint.MaxValue` defined parameter sets. However, the parameters themselves can only associate to 32 parameter sets.

The method that allows `uint.MaxValue` as a mapping index is [AddParameterSetToMap](https://github.com/PowerShell/PowerShell/blob/23451ac32f789a93d0575413700dbdf3861059e6/src/System.Management.Automation/engine/MergedCommandParameterMetadata.cs#L220). However, the next method below that one, [GenerateParameterSetMappingFromMetadata](https://github.com/PowerShell/PowerShell/blob/23451ac32f789a93d0575413700dbdf3861059e6/src/System.Management.Automation/engine/MergedCommandParameterMetadata.cs#L270), you can see that it uses [ParameterSetFlag](https://github.com/PowerShell/PowerShell/blob/13fd3af8106dbfd5d65e697036af5999255badc7/src/System.Management.Automation/engine/ParameterSetSpecificMetadata.cs#L141) as a bitmask to determine which parameter sets a parameter is part of.

# Proposals
If this is seen as a bug or feature request, it likely would be fixed if [ParameterSetFlag](https://github.com/PowerShell/PowerShell/blob/13fd3af8106dbfd5d65e697036af5999255badc7/src/System.Management.Automation/engine/ParameterSetSpecificMetadata.cs#L141) would be used as an actual index into a List of parameter sets. Then, you can define parameter sets up to `uint.MaxValue`.

If this is seen as a documentation issue, the *max parameters sets allowed* (being 32) should be documented in the reference document for [about_Functions_Advanced_Parameters](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters#parametersetname-argument) and in the conceptual document for [Cmdlet Parameter Sets](https://docs.microsoft.com/en-us/powershell/developer/cmdlet/cmdlet-parameter-sets).

**Comment by lzybkr** [comment]
I wonder about the usability of a command with 32 parameter sets, but assuming that's not an issue, what about upping the limit to 64? That might be a simple change (by using a `ulong` instead of `uint`).

I'm concerned a list might be bad for performance. The parameter binder is already really slow. I don't know the full history, but this bitmask always felt like the only consideration for performance in the original parameter binder code.

**Comment by MiYanni** [comment]
@lzybkr I'm currently working on this: https://devblogs.microsoft.com/powershell/cmdlets-via-autorest/

Basically, based on the number of optional parameters exposed by a REST service, we'd need to create a quite large number of parameter sets. Originally, it would be 2<sup>x</sup> number of parameter sets. So, 5 optional REST parameters would be the limit. Since we are now aware that this limitation exists, we'll adjust our parameter set generation strategy to attempt to reduce that. We need to support PowerShell 5.1 for now, so the fix here won't be useful for our efforts until much later down the road.

The primary concern is making this limitation known. Beyond that blog post (and looking at the code directly), I found no documentation about this. Upping it to 64 would be beneficial in the future, though. If performance is a concern, AFAIK, the parameter set names are unique. So, using them as a key to a `Dictionary` should be performant.

Additionally, PowerShell should inform the user that they hit that limit when defining a cmdlet. Right now, it **overflows** and makes it quite confusing when trying to understand the issue. An error here would be preferred so at least the developer making the cmdlet knows the issue.

**Comment by lzybkr** [comment]
I agree there should be an error if you hit the limit. I'm guessing it's a breaking change with minimal risk, but maybe some scenarios work despite having too many parameter sets?

Do keep in mind what the help looks like for commands with many parameter sets. Optional parameters turning into 2<sup>x</sup> parameter sets would probably result in very confusing output from `Get-Command -Syntax`.

**Comment by vexx32** [comment]
😬 I can see the syntax diagrams now, and they are _not_ pretty!

Speaking of, I should get that syntax diagram rework looked at again, see how I can fix that up some, perhaps.

**Comment by MiYanni** [comment]
@lzybkr @vexx32 We have worked around having too many parameter sets. Now, we are (generally) < 10 parameter sets for a given cmdlet. Some cmdlets will go above that, but we shouldn't (hopefully) hit the 32 limit. Despite our generator changes, all my points above are still valid about proper documentation and error handling for this limitation.

**Comment by fflaten** [comment]
Isn't it about time that we change this to `_nextAvailableParameterSetIndex == 32`, `_nextAvailableParameterSetIndex > Math.Log2(uint.MaxValue)` or something and actually throw the exception? 🙂 

https://github.com/PowerShell/PowerShell/blob/65b83e90d5ee79464dba0dc2b41d3da38c4f8d5c/src/System.Management.Automation/engine/MergedCommandParameterMetadata.cs#L231-L241

> I agree there should be an error if you hit the limit. I'm guessing it's a breaking change with minimal risk, but maybe some scenarios work despite having too many parameter sets?

Working code due to pure luck should not be a blocking issue. Those who waste a lot of time troubleshooting hard-to-detect behavior due to this overflow is a bigger problem.

In a perfect world this would even be backported to 5.1. It could **technically** be changed to a warning so it wouldn't break anything and every affected command will have `-WarningAction` to suppress if they don't care.

**Comment by iSazonov** [comment]
@fflaten Feel free to pull PR with simple check (==32) and new tests.

**Comment by iSazonov** [comment]
> If this is seen as a documentation issue, the _max parameters sets allowed_ (being 32) should be documented in the reference document for [about_Functions_Advanced_Parameters](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters#parametersetname-argument) and in the conceptual document for [Cmdlet Parameter Sets](https://docs.microsoft.com/en-us/powershell/developer/cmdlet/cmdlet-parameter-sets).

/cc @sdwheeler for information.

**Comment by sdwheeler** [comment]
This documented in https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_parameter_sets
