### ISSUE TITLE
Invoke-RestMethod wrong return type

### ISSUE THREAD

**Issue by kvdw** [PowerShell/PowerShell#9381]
For a project I'm trying to parse data from an API. I've been struggling with strange behavior from Invoke-RestMethod.
When you want to filter right away, the where-object doesn't work. During troubleshooting I found a strange occurrence when using Invoke-RestMethod, it doesn't always return a powershell object. You can 'fix' it in your code by using round brackets, or putting the data in a variable.

# Steps to reproduce

```powershell
(Invoke-RestMethod https://jsonplaceholder.typicode.com/users) | gm
-> returns pscustomobject

$a = Invoke-RestMethod https://jsonplaceholder.typicode.com/users
$a | gm
-> returns pscustomobject

 Invoke-RestMethod https://jsonplaceholder.typicode.com/users | gm
-> returns system.object[] -> WRONG
```

# Expected behavior

```powershell
 Invoke-RestMethod https://jsonplaceholder.typicode.com/users | gm
should return a pscustomobject, instead of a system.object[]

```

# Actual behavior

If you don't use rounded brackets or put the output in a variable first, you get a system.object[], which you cannot use to filter with f.e. where-object.

I've also found out this only happens when the results of the API is an array of json objects, if you use f.e. endpoint https://jsonplaceholder.typicode.com/posts/1 , all 3 examples below all give a pscustomobject back

I don't have access to another PC with PSCore, so I cannot confirm if it's on other platforms besides Windows Server 2019

# Environment data

```

Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.17763 (= Windows 2019)
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0..}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
This is intentional behaviour, as @markekraus describes in his [blog post](https://get-powershellblog.blogspot.com/2018/06/why-invoke-restmethod-and-convertfrom.html) on the subject. Essentially, it's to preserve the nature of the response object in as close-to-the-actual-object form as possible.

As mentioned in the blog post, you can simply pipe through a `ForEach-Object {$_}` statement to force the collection to be unrolled every time.

**Comment by kvdw** [comment]
Hi @vexx32 , thank you. I wasn't aware of this issue. Thank you for the information!
