### ISSUE TITLE
Allow automatic variable Is* inside PowerShell module manifest file

### ISSUE THREAD

**Issue by fmichaleczek** [PowerShell/PowerShell#9386]
NugetPackage have sometimes 2 distincts dll for Windows/Unix plateform.
It's not possible to determine which OS is running from a PowerShell module manifest file.
This issue should be resolved in  early PS 7.0 cycle because Net.Core 3.0 will add more scenarios with cross plateforms.

# Steps to reproduce

Add a condition with variable IsWindows into the property RequiredAssemblies inside a PowerShell module manifest file.

```powershell
RequiredAssemblies =  @(
    if ( $IsWindows ) { 
        '.\bin\LibName\runtimes\win\lib\netstandard2.0\LibName.dll' 
    }
    else { 
       '.\bin\LibName\runtimes\unix\lib\netstandard2.0\LibName.dll' 
    }
)
```

# Expected behavior

PowerShell module manifest file is loaded.

# Actual behavior

PowerShell Error  
```none
import-module : The module manifest 'ModuleName.psd1' could not be processed because it is not a valid PowerShell module manifest file. Remove the elements that are not permitted: At ModuleName.psd1:50 char:10
+     if ( $IsWindows ) {
+          ~~~~~~~~~~
A variable that cannot be referenced in restricted language mode or a Data section is being referenced. Variables that can be referenced include the following: $PSCulture, $PSUICulture, $true, $false, $null, $PSScriptRoot, $PSEdition, $EnabledExperimentalFeatures.
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
Interesting idea... I hit a similar issue when trying to use SkiaSharp. I ended up solving the issue in a PSM1: https://github.com/vexx32/PSWordCloud/blob/master/Module/PSWordCloud.psm1

**Comment by iSazonov** [comment]
@fmichaleczek Thanks for your suggestion.
 It is dup #5541 Please discuss/vote there.
