### ISSUE TITLE
ConvertFrom-Markdown throws Null Exception when run inside Runspace

### ISSUE THREAD

**Issue by Badgerati** [PowerShell/PowerShell#9390]
When running the `ConvertFrom-Markdown` command from within a new runspace, the command throws a null reference exception.

# Steps to reproduce

```powershell
$pool = [runspacefactory]::CreateRunspacePool(1, 2, $Host)
$pool.Open()

$ps = [powershell]::Create()
$ps.RunspacePool = $pool
$ps.AddScript({
    try {
        '# test' | ConvertFrom-Markdown | Out-Default
    }
    catch {
        $_ | Out-Default
    }
}) | Out-Null

$ps.Invoke()
$ps.Dispose()
```

# Expected behavior

```none
The command should return a MarkdownInfo object
```

# Actual behavior

```none
The command throws a null reference exception:

ConvertFrom-Markdown : Object reference not set to an instance of an object.
At line:3 char:21
+         '# test' | ConvertFrom-Markdown | Out-Default
+                     ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [ConvertFrom-Markdown], NullReferenceException
+ FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.ConvertFromMarkdownCommand
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Linux 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

(note: the same happens on Windows, too)

# Notes

Looking into the code, it seems to be caused by the following line: https://github.com/PowerShell/PowerShell/blob/2174dd81a4e624932feee4457ca376203b14c8ac/src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConvertFromMarkdownCommand.cs#L69

The `this.CommandInfo.Module` is null when running within a new runspace. The line appears to create a default `PSMarkdownOptionInfo` object if the session variable is `null` - so if the module is null maybe create a default `PSMarkdownOptionInfo`?

**Comment by iSazonov** [comment]
/cc @adityapatwardhan @SteveL-MSFT 

I debug the code. It is bug. 
`this.CommandInfo.Module` is null here:
https://github.com/PowerShell/PowerShell/blob/e9ffbe5cf27ad6461607fcf4bc69258652a88d33/src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConvertFromMarkdownCommand.cs#L67-L70
