### ISSUE TITLE
Use PowerShell to stop Syncing OneDrive folders

### ISSUE THREAD

**Issue by ShehzadUIT** [PowerShell/PowerShell#9391]
I am looking for a PowerShell script that stops syncing OneDrive folders.
I.e. I want to trigger the Stop Sync encircled using PS:
![IM1](https://user-images.githubusercontent.com/39981185/56336314-3a97ad00-61e3-11e9-90b8-05e801fed30c.JPG)

**Comment by iSazonov** [comment]
@ShehzadUIT The repo is for development only. For support please use forums or/and stackoverflow.com
