### ISSUE TITLE
Powershell for Mac displaying escape(?) sequences

### ISSUE THREAD

**Issue by waynebeech** [PowerShell/PowerShell#9420]
# Support Question

When I run powershell on the Mac (using either Terminal or iTerm2) I get what appears to be escape sequences as I type.  For example:
[sabine:~/python] wayne% pwsh
PowerShell 6.2.0
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS /Users/wayne/python> $<5>$PSVersionTable.PSVer$<5>
$<5>
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
6      2      0

PS /Users/wayne/python>

notice the $<5> strings.  the appear and move as I type and obstruct part of  the commands.

I did unload PSReadLine with

Remove-Module -Name PSReadline

and of course a lot of the nice features went away however the escape string issue remained.

## Official support

[PowerShell Support Lifecycle](https://aka.ms/pslifecycle)

## Community Resources

[Slack Community Chat](https://powershell.slack.com) - Interactive chat with other PowerShell enthusiasts
[PowerShell.org Forum](https://powershell.org/forums/) - Search or post new general PowerShell usage questions

**Comment by SteveL-MSFT** [comment]
What is `$env:TERM` set to?

**Comment by waynebeech** [comment]
it is currently set to vt100.

possible values appear to be

ansi, dtterm, nsterm, rxvt, vt52, vt100, vt102, xterm, xterm-16color and xterm-256color

wayne

**Comment by SteveL-MSFT** [comment]
Not sure how you got set to vt100.  You should really have it set to xterm-256color.  This should work with both Terminal and iTerm2
