### ISSUE TITLE
Hash sum mismatch for powershell for Ubuntu 14.04

### ISSUE THREAD

**Issue by minwoo832** [PowerShell/PowerShell#9424]
I'm getting the following error when trying to install Powershell for ubuntu 14.04
Failed to fetch https://packages.microsoft.com/ubuntu/14.04/prod/dists/trusty/main/binary-amd64/Packages  Hash Sum mismatch
Unable to locate the package powershell

# Steps to reproduce

```
# Download the Microsoft repository GPG keys
wget -q https://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb

# Register the Microsoft repository GPG keys
sudo dpkg -i packages-microsoft-prod.deb

# Update the list of products
sudo apt-get update

# Install PowerShell
sudo apt-get install -y powershell
```

# Expected behavior

```
Powershell for Ubuntu 14.04 should be installed.
```

# Actual behavior

```
After running sudo apt-get update, I get the following error:
Failed to fetch https://packages.microsoft.com/ubuntu/14.04/prod/dists/trusty/main/binary-amd64/Packages  Hash Sum mismatch

After running sudo apt-get install -y powershell, I get the following error:
Unable to locate the package powershell
```

**Comment by minwoo832** [comment]
Also tried running
sudo rm -rf /var/lib/apt/lists/*
But I still get the same error.

**Comment by jdavisp3** [comment]
Same here.

**Comment by TravisEz13** [comment]
Related issue:  https://github.com/dotnet/core/issues/2608 
Based on this it was fixed 14 hours ago.

FYI, 14.04 is EOL and therefore we don't support it anymore.
