### ISSUE TITLE
Updatable Help tests have become unreliable 

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#9426]
Updatable Help tests have become unreliable, causing all merge test failures in the linux pipeline in the last 14 days:
![image](https://user-images.githubusercontent.com/10873629/56461452-4c568d00-6368-11e9-8ed6-1f063e6468f7.png)

Causing all unmitigated test failure in the macOS pipeline in the last 14 days(green mitigated, red unmitigated): 
![image](https://user-images.githubusercontent.com/10873629/56461485-cd158900-6368-11e9-850c-7fb826524670.png)

No failure are seen for these tests in the windows pipeline.

**Comment by iSazonov** [comment]
@TravisEz13 Are we still tracking this?
