### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by amroth3003** [PowerShell/PowerShell#9436]
I I'm trying to install powershell on my nas server which has a debian on ARM processor

![image](https://user-images.githubusercontent.com/46945805/56511799-7be9ce80-64fb-11e9-91f0-cbe1c85f37bf.png)

The dependencies are installed even dotnet, however I am instructed Illegal
![image](https://user-images.githubusercontent.com/46945805/56511818-860bcd00-64fb-11e9-99ce-ff4976940e7b.png)

The package installed from the source is

![image](https://user-images.githubusercontent.com/46945805/56511870-b489a800-64fb-11e9-8f3e-4a6025fcba9f.png)

**Comment by fmichaleczek** [comment]
@amroth3003 You should try with a latest release.

I remember ARM build works starting 6.1.

**Comment by amroth3003** [comment]
is a same error

![image](https://user-images.githubusercontent.com/46945805/56524217-04c23380-6517-11e9-84cd-f019429f5bcf.png)

**Comment by fmichaleczek** [comment]
@amroth3003 you will found the same symptoms here : 
https://github.com/PowerShell/PowerShell/issues/5696

Have you install requirements ( libunwind8 ) ?

PowerShell ARM is experimental with Raspbian (Stretch) on R-Pi2/3.
Could you provide ARM CPU Information ?

**Comment by amroth3003** [comment]
yes libunwind8 is install

![image](https://user-images.githubusercontent.com/46945805/56528114-b152e400-651c-11e9-99e4-5843571655c0.png)

**Comment by fmichaleczek** [comment]
@amroth3003 your plateform is not supported by the project, and never been tested.

The best thing to do is provide more logs and informations about your case :
-  cat /etc/os-release
- a 'gdb' log like here [#5696](https://github.com/PowerShell/PowerShell/issues/5696)

With a specific ARM processor like this one, nobody can reproduce your problem easily.

**Comment by iSazonov** [comment]
.Net Core should support an arch before we can get this in PowerShell.

**Comment by fmichaleczek** [comment]
@iSazonov .Net Core 2.1 already support Debian 9 arm32. [Prerequisites for .NET Core on Linux](https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x)

Marvel Armada 370 proc is used in Synology hardware, it's an armv7.

The .Net Core team has maybe a processors list tested ?

PowerShell.Native has only been tested on Raspberry for ARM arch.

**Comment by iSazonov** [comment]
> The .Net Core team has maybe a processors list tested ?

Please ask in Core repo.

**Comment by amroth3003** [comment]
Is a Nas Server Buffalo

PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"


processor       : 0
model name      : ARMv7 Processor rev 1 (v7l)
BogoMIPS        : 33.33
Features        : half thumb fastmult vfp edsp thumbee vfpv3 vfpv3d16 tls idivt
CPU implementer : 0x56
CPU architecture: 7
CPU variant     : 0x1
CPU part        : 0x581
CPU revision    : 1

Hardware        : Marvell Armada 370/XP (Device Tree)
Revision        : 0000
Serial          : 0000000000000000

**Comment by fMichaleczek** [comment]
Dot.Net Core requires an ARM CPU with feature "vfpv4d32" and your CPU isn't compatible.

/cc @SteveL-MSFT

**Comment by SteveL-MSFT** [comment]
Unfortunately, unless .NET Core supports it, PowerShell can't support it.  If support by .NET Core changes in the future, we can revisit on how we produce a PowerShell build for it.
