### ISSUE TITLE
Garbage Collector usage

### ISSUE THREAD

**Issue by fmichaleczek** [PowerShell/PowerShell#9439]
# Support Question

I would like to know what is specific to PowerShell about GC implementation and which scenarios are community supported.

[GCSettings.IsServerGC #7112](https://github.com/PowerShell/PowerShell/issues/7112#issuecomment-398751342)

PowerShell could be a library loaded by an dotnet application, i would like to know what's happen to the GC in this context.

[.Net Memory Management poster](https://pbs.twimg.com/media/Dou1QbLXsAUMV0o.jpg:large)

**Comment by iSazonov** [comment]
There is nothing special about GC in this repository. We use .Net Core GC with default parameters. For host scenarios application owners should tests.
