### ISSUE TITLE
Feature Request: Format-Tree

### ISSUE THREAD

**Issue by chriskuech** [PowerShell/PowerShell#9444]
# Summary of the new feature/enhancement

The `tree` command is very useful for getting a clear understanding of a directory structure.  It would be great if this command was ported to PowerShell as `Format-Tree` so it could be integrated with `System.IO.FileSystemInfo`.  It would be even better if this command worked generically with string inputs and a scriptblock parameter, like a recursive `Group-Object` with `tree` formatting, though I'm unsure how this scenario would ideally be implemented.

**Comment by fmichaleczek** [comment]
@chriskuech This feature is available on the PSGallery [Show-Tree](https://www.powershellgallery.com/packages/Show-Tree/1.0.0)

**Comment by chriskuech** [comment]
```
Install-Script Show-Tree
Show-Tree
```

This snippet works on Windows but not on Linux.  I noticed this is tagged with "Nano"--is this script compatible with PowerShell Core on *nix?

**Comment by fmichaleczek** [comment]
@chriskuech 
Nano tag is for Windows Server Nano a nano edition.

About your problem, the script has been installed here on an ubuntu WSL `~/.local/share/powershell/Scripts/Show-Tree.ps1 `

This command will show the exact Location
`(Get-InstalledScript).InstalledLocation`

You will be able to execute it through the full path or use the downloaded location in the PSGallery (nuget package are only zip file)

An issue is already open on PowerShellGet (module for Install-Script).
[PowerShellGet#29](https://github.com/PowerShell/PowerShellGet/issues/29)

@SteveL-MSFT
