### ISSUE TITLE
PowerShell class syntax doesn't support multiple conversion operators with the same input type

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#9445]
While it _is_ possible to define implicit / explicit conversion operators as static `op_implicit` and `op_explicit` methods, they are currently subject to the same rules as _regular_ methods, which means that you can define only _one_ conversion operator per operator type and  input type.

That is, trying to define a second conversion operator with a different target type is interpreted the same way as a regular method, which results in the same error message you'd get if you tried to define a method overload that differs by return type only (which isn't permitted).

# Steps to reproduce

```powershell
& {
  class Foo {

    # Implicit conversion to [int]
    static [int] op_Implicit([Foo] $Instance) {
      return 42
    }

    # Implicit conversion to [long]
    static [long] op_Implicit([Foo] $Instance) {
        return 666l
    }

  }
  1 + [Foo]::new()
} | Should -Be 42
```

# Expected behavior

The test should succeed.

# Actual behavior

The test fails with `The member 'op_Implicit' is already defined.`

# Environment data

```none
Windows PowerShell v5.1 / PowerShell Core 6.2.0
```

**Comment by fmichaleczek** [comment]
@mklement0 Something to add to the long list [#6652](https://github.com/PowerShell/PowerShell/issues/6652)
