### ISSUE TITLE
Cannot uninstall version 6.1.0

### ISSUE THREAD

**Issue by atfernando** [PowerShell/PowerShell#9449]
# Steps to reproduce

```
1. Uninstall powershell 6.1.0 from Control Panel.
2. Try to install a newer version.
```
# Expected behavior
```
Uninstall the current version
```
# Actual behavior

```
Prompts to locate the original 6.1.0 msi file which isn't available to download.
```

# Environment data

```
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment]
With MSI you can install/uninstall only one version. For Side-By-Side scenarios use zip packages.

**Comment by atfernando** [comment]
Hi @iSazonov 
Thanks for the comment. I do not wish to have 2 versions side by side but to uninstall version 6.1.0 and install / update to the latest version. And I'm not able to do it.
A prompt asking for the path of the msi file pops up when I try to uninstall 6.1.0 or install 6.2

Hope this makes sense. Thanks

**Comment by iSazonov** [comment]
You could try to repair previous installation.
Or you could clean up registry manually and remove msi keys for previous version.

**Comment by atfernando** [comment]
Hi @iSazonov ,

Same prompt for the msi file pops up when I try to repair the previous installation. 
Any idea why 6.1.0 is deleted from Github?

Thanks,
Anton

**Comment by vexx32** [comment]
@atfernando I think 6.1.0 was one of the releases affected by a security vulnerability, which would be why it was pulled I think.

**Comment by iSazonov** [comment]
@atfernando You need to clean up registry from broken msi keys. Note that it is not supported. (Supported way is to reinstall OS system.) You could ask help on forums.

I close the issue because we can fix nothing in the repo.
