### ISSUE TITLE
The default encoding is not correct

### ISSUE THREAD

**Issue by chucklu** [PowerShell/PowerShell#9450]
# Steps to reproduce

```powershell
[System.Text.Encoding]::Default.EncodingName
```

# Expected behavior

```none
Chinese Simplified (GB2312)

```

# Actual behavior

```none
Unicode (UTF-8)
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.1.3
PSEdition                      Core
GitCommitId                    6.1.3
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

# Additional Info
When I execute the same command in powershell 5.1, It returns the correct default encoding of operation system(Microsoft Windows [Version 10.0.17763.316]).
![image](https://user-images.githubusercontent.com/3004057/56560426-fa676e80-65d6-11e9-8793-eac21c9238cd.png)

\
\
I also tried in visual studio with C# code
```C#
  [Test]
        public void GetDefaultEncodings()
        {
            var defaultEncoding = Encoding.Default;
            Console.WriteLine(
                $"{defaultEncoding.EncodingName},{defaultEncoding.CodePage},{defaultEncoding.WindowsCodePage}");
        }
```
And the output is Chinese Simplified (GB2312),936,936

**Comment by iSazonov** [comment]
@chucklu Your report is for .Net Core - please report in CoreFX repository.

**Comment by chucklu** [comment]
ok, I will create a new issue in CoreFx repository.
