### ISSUE TITLE
Registry provider: key names "." and ".." aren't supported in PS drive paths due to filesystem-like path normalization

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#9451]
If you use a path with a key literally named `.` or `..` that is based on one of the registry drive provider's drives such as `HKCU:`, these names are currently misinterpreted as referring to the current and parent "directory" respectively, as in the filesystem.

The workaround is to use a provider-native path via the `registry::` prefix.

If it's too late to change this behavior and perhaps people rely on it, expecting filesystem-analogous behavior, the pitfall - and workaround - should be _documented_.

Note that creating a key named `.` is not a hypothetical example; you need it to define a file type for extension-less file names, for instance (`HKEY_CLASSES_ROOT\.`)

# Steps to reproduce (on Windows)

Note: The same applies analogously to a key literally named `'..'`.

```powershell
# A path to a key named "."
$regPathPS = 'HKCU:\_tmp\.'
# Equivalent provider-native path.
$regPathProviderNative = 'registry::HKEY_CURRENT_USER\_tmp\.'

# Create the key using the provider-native path
# - which is currently the only option.
$null = New-Item -Force $regPathProviderNative

# Try to retrieve the new key using the PS drive notation.
# This currently retrieves 'HKCU:\_tmp' instead, i.e., the
# *parent* path, because the "." is misinterpreted as a reference to
# the "directory" HKCU:\_tmp
try {

  (Get-Item -LiteralPath $regPathPS).PSChildName | Should -Be '.'

} finally {
  # Clean up.
  Remove-Item -Recurse -LiteralPath (Split-Path -Path $regPathPS)
}
```

# Expected behavior

The test should pass.

# Actual behavior

The test fails:

```none
...
Strings differ at index 0.
Expected: '.'
But was:  '_tmp'
...
```

# Environment data

```none
PowerShell Core 6.2.0 / Windows PowerShell v5.1
```

**Comment by kvprasoon** [comment]
Is the problem is in `Get-Item` ? It get the proper childname using `Get-ChildItem`

**Comment by mklement0** [comment]
@kvprasoon, no: `Get-ChildItem` is equally affected. 

It only works _incidentally_ in this scenario: it still targets only `registry::HKEY_CURRENT_USER\_tmp` and _enumerates its children_ - the only one of which happens to be `.` in the test above; if you create a sibling key, say, `registry::HKEY_CURRENT_USER\_tmp\foo`, you'll see that `Get-ChildItem HKCU:\_tmp\.` enumerates them both.
