### ISSUE TITLE
new request : powershell equivalent of task manager

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#9452]
Within a shell (Powershell) , how to show all info that show in GUI task manager.  any cmdlet do that job ?

GUI:
![task_manager](https://user-images.githubusercontent.com/36788337/56625008-cd19cf80-666d-11e9-9079-871376a90ed6.png)

Expect PowerShell Version Work Like This
![top](https://user-images.githubusercontent.com/36788337/56625074-1407c500-666e-11e9-8347-c33017df2950.png)

**Comment by rjmholt** [comment]
PowerShell's `Get-Process` (`gps`) displays a lot of this information. The .NET Process object has access to almost all of it, so if you want a different view you could write a formatter. Otherwise, on *nix platforms, `top` and `htop` are also excellent tools.

**Comment by tlsalex** [comment]
Hello @rjmholt , thanks ,  but within gps , can not see the overall resource usage , like cpu and memory overall usage. it just shows the resource usage for single process.

**Comment by rjmholt** [comment]
Your best option is likely to [create a new formatter](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-6). You could then add [PowerShell calls to get total system resource usage](https://stackoverflow.com/questions/6298941/how-do-i-find-the-cpu-and-ram-usage-using-powershell) and put them at the top.

**Comment by fmichaleczek** [comment]
if you want to explore the same data as TaskManager, PowerShell can help you to automate things. 

If you want a fast C++ window top, check on github this project : [NTop](https://github.com/Nuke928/NTop).  This kind of tools take all the console, so powershell or not, there are no difference at all. (except if the tool only work on cmd and have weird display in PS).

**Comment by tlsalex** [comment]
Hello @fmichaleczek ,
NTop it does a very cool tool , however it still missing something that I want , which is the disk usage for each process , I already raise a request for that feature under NTop project.

I am more prefer the official powershell-like NTop.

**Comment by rjmholt** [comment]
Closing this issue since it's out of scope for the PowerShell project. A feature like this would work better as its own module, since it would then work with older PowerShell versions too.
