### ISSUE TITLE
Feature Request: pwsh -x flag

### ISSUE THREAD

**Issue by krystian-wojtas** [PowerShell/PowerShell#9463]
# Posix shell

Posix shells have very helpful -x cli flag. It could be also enabled inside script code with line 'set -x'. It shows commands as they are exactly executed

Example shell code
```
% cat hello.sh
#!/bin/sh

set -x

msg="world"
echo "hello $msg"
```

Output
```
% ./hello.sh
+ msg=world
+ echo hello world
hello world
```

If there is something unexpected in script, then I can easily copy interesting line to another terminal and run it.

# Powershell

My best finding is 'Set-PSDebug -Trace 2' function.

Example powershell code
```
% cat hello.ps
#!/usr/bin/pwsh

Set-PSDebug -Trace 2;

$msg="world"
write-host "hello $msg"
```

Output
```
% ./hello.ps
DEBUG:    5+  >>>> $msg="world"

DEBUG:     ! SET $msg = 'world'.
DEBUG:    6+  >>>> write-host "hello $msg"

hello world
```

Powershell shows lines of source code. It does not evaluate variables values. I would like to see `write-host "hello world"` as extra debug message.

# Question

Is it possible to see executed lines of script code in powershell? Could it evaluate variables values before printing debug message about executing command? How to do it?

**Comment by fmichaleczek** [comment]
@krystian-wojtas you should use Trace-Command
 
` Trace-Command -Name * -Expression {$msg="world";write-host -Message "hello $msg"} -PSHost `

**Comment by iSazonov** [comment]
> It does not evaluate variables values. 

I thing PowerShell engine has not this _explicitly_ as strings. I guess it is possible to enhance the engine to construct such string _but only in simple cases_ (arguments can be complex expressions!) and this will add huge complicity in code without benefits - we can see all we need in debug and trace output.

**Comment by krystian-wojtas** [comment]
@fmichaleczek Yes, probably it is exactly what I need. This function is also promising
[Set-Tracesource](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/set-tracesource)

Great answer, thank you very much for it.

I couldn't find these functions by myself earlier. Then I wrote some small tool as a workaround
https://gitlab.com/krystian.wojtas/powershell-debug
It works fine for small project I take part into. Next time I will use your advices. Good to know that powershell have proper way for doing it.

**Comment by chuanjiao10** [comment]
@krystian-wojtas 
Translation reading my post:
debug powershell script on vscode on linux：
http://bbs.chinaunix.net/thread-4299559-1-2.html
