### ISSUE TITLE
Feature Request: code profiler

### ISSUE THREAD

**Issue by krystian-wojtas** [PowerShell/PowerShell#9464]
# Tool to profile code

Is there available any tool to show how many times each line of powershell script code was executed?

**Comment by fmichaleczek** [comment]
@krystian-wojtas in PowerShell, you have : 
- [Measure-Command](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/measure-command?view=powershell-6)
- [Trace-Command](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Trace-Command?view=powershell-6)

In trace-command, there is a parameter ListenerOption that can be configured with Timestamp, but if you trace with a lot of options, you code will not run at same speed.

**Comment by iSazonov** [comment]
We have the idea without any progress https://github.com/PowerShell/PowerShell/issues/7857#issuecomment-425985568

**Comment by krystian-wojtas** [comment]
@iSazonov thank you for your answer.
