### ISSUE TITLE
New Request: Operate Local Group Policy with cmdlet

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#9470]
In my daily task , sometimes I need to manipulate local group policy , currently , I just use GUI to do that , but it does not work efficiency with GUI .
Maybe someone will tell me to use PolicyFileEditor module . I did try before , but that is not what I want.

I hope some cmdlet that work like bellow:

get-grouppolicy -scope (localpgo or domaingpo) -All
set-grouppolicy - scope xx  - value xx
disable-grouppolicy -scope xx -name xx

**Comment by fmichaleczek** [comment]
@tlsalex GPO is a part of Windows Server, you should ask on [Windows Server Uservoice](https://windowsserver.uservoice.com/forums/295047-general-feedback)

**Comment by tlsalex** [comment]
thanks , but no one will care my request in the Windows Server Uservoice  , ms just care my license .

**Comment by kvprasoon** [comment]
@fmichaleczek GPO is part of WindowsServer and there are cmdlets to manage them. The request here is to manage local group policies.

**Comment by fmichaleczek** [comment]
@kvprasoon the first suggested example is `get-grouppolicy -scope (_localpgo or domaingpo_) -All`
