### ISSUE TITLE
Can't build PowerShell once Visual Studio 2019 has been installed

### ISSUE THREAD

**Issue by sba923** [PowerShell/PowerShell#9472]
I recently installed Visual Studio 2019 on my main dev machine.

This is the most probably cause for .NET to have been upgraded to the latest version.

As a consequence, I can't build PowerShell Core anymore:

````
PS C:/Users/steph/Source/Repos/PowerShell> start-psbuild
WARNING: The 'dotnet' in the current path can't find SDK version 2.1.504, prepending C:\Users\steph\AppData\Local\Microsoft\dotnet to PATH.
WARNING: The currently installed .NET Command Line Tools is not the required version.

Installed version: 2.1.505
Required version: 2.1.504

Fix steps:

1. Remove the installed version from:
    - on windows '$env:LOCALAPPDATA\Microsoft\dotnet'
    - on macOS and linux '$env:HOME/.dotnet'
2. Run Start-PSBootstrap or Install-Dotnet
3. Start-PSBuild -Clean
````

I don't want to break VS2019, or to revert to VS2017.

Is there a means to work around this issue?

**Comment by iSazonov** [comment]
Current plan is to move to .Net Core 3.0. So we skip 2.1.505. You could download and install 2.1.504.

**Comment by sba923** [comment]
Can I deploy 2.1.504 alongside the 2.1.505 that VS2019 presumably installed, without breaking VS2019?

**Comment by iSazonov** [comment]
I would be very amized if it happened. Try 2.1.504 msi installer without removing  2.1.505.

**Comment by sba923** [comment]
I have downloaded and installed 2.1.504 from [here](https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-2.1.504-windows-x64-installer). Now `Start-PSBuild` is happy. VS2019 launches fine (which is expected, of course), haven't tried to build a .NET Core app yet.
