### ISSUE TITLE
CLI: Stdin input does not implicitly become pipeline input

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#9497]
Currently, _stdin_ input streamed to `pwsh` _from the outside_:

* does _not_ automatically become pipeline input;
  * accessing stdin input currently requires constructing a separate pipeline in PowerShell code using `$Input`

* only automatically becomes input to _interactive prompts_, such as `Read-Host` calls or the automatic prompts displayed when mandatory arguments are missing.

This has the following implications:

**You cannot directly pipe data to PowerShell commands from the outside:**

Contrast the following two commands:

```sh
# Bash:
# stdin input is "relayed" to the 'wc' utility
$ printf 'one\ntwo' | bash -c 'wc'
2
```

```powershell
# PowerShell:
PS> printf 'one\ntwo' | pwsh -noprofile -c 'Measure-Object -Word | % Words'
0 # !! Measure-Object did NOT receive stdin input.

# Explicit reference to $Input in an internal pipeline is required:
PS> printf 'one\ntwo\n' | pwsh -noprofile -c '$Input | Measure-Object -Word | % Words'
2
```
printf 'one\ntwo\n' | pwsh -noprofile -c 'Measure-Object -Word'

**If you're calling an _advanced script that binds pipeline input_, it cannot be invoked with just `-File`, because it won't receive pipeline input**:

```powershell
# Create an advanced script that echoes each pipeline input enclosed in [...]
'[CmdletBinding()] param([Parameter(ValueFromPipeline)] $var) process { "[$var]" }' > t.ps1

# Call from either Bash or PowerShell (same behavior).
PS> echo hi | pwsh -noprofile -file t.ps1
[]  # !! t.ps1 did NOT receive stdin input

# The workaround is again non-obvious and cumbersome:
PS> echo hi | pwsh -noprofile -command '$Input | ./t.ps1'
[hi]  # OK
```

**Similarly, if you author a pipeline-binding advanced script as _shebang-line-based script on Unix_, it cannot receive stdin input directly**:

```powershell
# Create a shebang-line-based script...
@'
#!/usr/bin/env pwsh
[CmdletBinding()] param([Parameter(ValueFromPipeline)] $var) process { "[$var]" }
'@ > foo

# ... and make it executable.
chmod +x foo

# Call from either Bash or PowerShell (same behavior).
PS> 1..2 | ./foo
[]  # !! Pipeline input wasn't bound, not even with pipeline input from PowerShell.
``` 

---

PowerShell's behavior here is at odds with traditional shells and arguably makes the typical use case unnecessarily difficult.

Note: **I'm unclear on whether this can be fixed without breaking existing behavior.**

The challenge is to know when to provide stdin input via an _implied PowerShell pipeline_, and when to use stdin input line by line, on demand, to respond to _interactive prompts_.

E.g., the following currently works - the two distinct `Read-Host` prompts are "answered" by 1 stdin input line each:

```powershell
$ 'one\ntwo\n' | pwsh -noprofile -c 'read-host first; get-date;  read-host second'
first: one
one

Monday, April 29, 2019 10:52:04 AM
second: two
two
```

# Environment data

```none
PowerShell Core 6.2.0
```

**Comment by bergmeister** [comment]
I am hit by the same problem, I have to work with the databricks CLI, which has a terrible UX that requires me to pipe stdin to the the native binary and it seems I have to use `bash` for now as I could not translate the following to `PowerShell`::
```
databricks configure --token <<EOF
https://$(databricks_location).azuredatabricks.net
$(databricks-token)
EOF
```
I've tried piping a string to it
```pwsh
$newline = [System.Environment]::NewLine
"${newline}https://$DatabricksLocationShort.azuredatabricks.net${newline}$DatabricksToken${newline}" | databricks configure --token
```
with variations of `${newline}` or also trying to pipe an array with no luck....

**Comment by mklement0** [comment]
It sounds like you're describing the _opposite_ direction: piping _to_ an external program.

In my experience that usually _does_ work; e.g.:

```powershell
@'
one
two
three
'@ | bash -c 'cat -n'  # outputs the stdin input lines with line numbers
```

**Comment by bergmeister** [comment]
Thanks for the info.
I decided to use authentication via environment variables on the PowerShell process level instead now because shockingly this is even more secure as the azure databricks cli would store the credentials in  plaintext in  ~/.databrickscfg (accessible only when running as Admin though but still!)

**Comment by mvalikar** [comment]
@bergmeister  Can you share code how you are able to authenticate Databricks through Environment variables. I am pretty much struck in this case

**Comment by bergmeister** [comment]
@mvalikar You set the DATABRICKS_HOSTand  DATABRICKS_TOKEN environment variables as per docs, I suggest to set them only for the current process for security purposes and clean them up at the end
https://docs.databricks.com/dev-tools/cli/index.html

**Comment by jiasli** [comment]
The same happens when directly calling `ps1` which pipes to an external program.

For example, `test.sh` and `test.ps1` have the same content:

```sh
python -c "import sys; print(sys.stdin.read(), end='')"
```

In Bash, when piping to `test.sh`, the inner `python` receives from `stdin` automatically:

```sh
$ echo "sometext" | ./test.sh
sometext
```

On contrary, in PowerShell when piping to `test.ps1`, the inner `python` can't receive from `stdin` and waits for user input.

```pwsh
> echo "sometext" | ./test.ps1
<waiting for user input>
```

A workaround is to explicitly pipe `$input` to `python` in `test.ps1`.

```pwsh
$input | python -c "import sys; print(sys.stdin.read(), end='')"
```

**Comment by jiasli** [comment]
Using `$input` will also break interactive input:

Assume we have `test.sh` and `test.ps1`:

```
python -c "print(input())"
```

In Bash:

```
$ ./test.sh
sometext  < input here
sometext
```

but in PowerShell, it results in failure:

```
> ./test.ps1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
EOFError: EOF when reading a line
```

**Comment by jiasli** [comment]
A workaround I can think of is to check if `$input` is empty:

- If `$input` is not empty, pipe it to python
- If `$input` is empty, don't pipe it to python and leave python to read `stdin` from TTY

(We need to save `$input` to another variable `$stdin` since `$input` is an enumerator and can be accessed only once.)

```ps1
$stdin = "$input"
if ($stdin) {
    $stdin | python -c "print(input())"
}
else {
    python -c "print(input())"
}
```

**Comment by mklement0** [comment]
> Can we detect if piping is used from `$input`?

Use `$MyInvocation.ExpectingInput`

```powershell
& { $MyInvocation.ExpectingInput } # -> $false
1 | & { $MyInvocation.ExpectingInput } # -> $true
```

> How can we detect if [...] `$input` is empty string  (an empty pipe is used)?

If it's OK to collect all input up front:

```powershell
python -c "print('', end='')" | & { $allLines = @($Input); $allLines.Count -eq 0 }
```

Otherwise:

```powershell
# -> $true
python -c "print('', end='')" | & { begin { $emptyInput = $true } process { $emptyInput = $false  } end { $emptyInput }  }
```

Note that _without_ pipeline input, the `process` block is also called, namely exactly _once_.


> What if stdin contains binary stream?

PowerShell currently has _no_ support for binary data in its pipelines when communicating with _external programs_ - everything is treated as _text_ - both on sending and receiving - see 
* #1908

**Comment by jiasli** [comment]
@mklement0, thanks a lot for the insights.

This solution you mentioned doesn't seem to work. It returns `True` even with empty `stdin`:

```powershell
> & { $allLines = @($Input); $allLines.Count -eq 0 }
True
> python -c "print('', end='')" | & { $allLines = @($Input); $allLines.Count -eq 0 }
True
> python -c "print('a', end='')" | & { $allLines = @($Input); $allLines.Count -eq 0 }
False
```

The other solution also has some unexpected behavior:

```powershell
> & { begin { $emptyInput = $true } process { $emptyInput = $false  } end { $emptyInput }  }
False
> python -c "print('', end='')" | & { begin { $emptyInput = $true } process { $emptyInput = $false  } end { $emptyInput }  }
True
> python -c "print('a', end='')" | & { begin { $emptyInput = $true } process { $emptyInput = $false  } end { $emptyInput }  }
False
```

**Comment by mklement0** [comment]
I answered your questions in isolation, You need to combine your logic with `$MyInvocation.ExpectingInput` as needed, to distinguish the pipeline from the non-pipeline scenarios.
Apart from that, I see no unexpected behavior. ` & { $allLines = @($Input); $allLines.Count -eq 0 }` is designed to return _`$true`_ if there is either no input from the pipeline at all or  if that input is empty.
`& { begin { $emptyInput = $true } process { $emptyInput = $false  } end { $emptyInput }  }` is designed to return `$true` only if there's pipeline input and it is empty.

**Comment by pcgeek86** [comment]
I'm running into the same limitation. I'm trying to use PowerShell to write a script to handle the `pre-push` git hook.

Since I am unable to grab stdin from PowerShell, I am unable to process this data.

![image](https://user-images.githubusercontent.com/466713/212444289-ebd14ff8-e356-4ec7-9b36-8d1554159406.png)

```
pre-push
This hook is called by [git-push[1]](https://git-scm.com/docs/git-push) and can be used to prevent a push from taking place. The hook is called with two parameters which provide the name and location of the destination remote, if a named remote is not being used both values will be the same.

Information about what is to be pushed is provided on the hook’s standard input with lines of the form:

<local ref> SP <local object name> SP <remote ref> SP <remote object name> LF

For instance, if the command git push origin master:foreign were run the hook would receive a line like the following:

refs/heads/master 67890 refs/heads/foreign 12345

although the full object name would be supplied. If the foreign ref does not yet exist the <remote object name> will be the all-zeroes object name. If a ref is to be deleted, the <local ref> will be supplied as (delete) and the <local object name> will be the all-zeroes object name. If the local commit was specified by something other than a name which could be expanded (such as HEAD~, or an object name) it will be supplied as it was originally given.

If this hook exits with a non-zero status, git push will abort without pushing anything. Information about why the push is rejected may be sent to the user by writing to standard error.
```

### Workaround

The only workaround that I've seen, to read StdIn from PowerShell, is to use `$Host.UI.ReadLine()`, however that has a bug where it results in duplicate output. Also, the `ReadLine()` method hangs script execution. If you reach the last line of input, and you call `ReadLine()` again, your script will completely hang.

![image](https://user-images.githubusercontent.com/466713/212444362-77a70984-5cf3-42ad-ac9d-ccf68400e414.png)

**Comment by pcgeek86** [comment]
Yeah, let's just waste all the time and effort that the community has put into reporting bugs and usability issues. Good plan as usual, Microsoft.

<img width="715" alt="image" src="https://github.com/PowerShell/PowerShell/assets/466713/72ff8536-c34b-4e48-995b-a44513ccb902">

**Comment by fireflycons** [comment]
@pcgeek86 I had a similar issue while creating a mechanism to handle powershell hooks natively (without git-bash) in git for Windows. The trick is to grab `stdin` directly and read from it, as shown under the cookbooks heading here https://github.com/fireflycons/git-hook-dispatcher
