### ISSUE TITLE
If Else Statements on Linux Fail

### ISSUE THREAD

**Issue by chrisfitch** [PowerShell/PowerShell#9499]
I'm using PS Core 6.2 on Windows 10 and with WSL. If the else statement is on the next line it doesn't work in linux but does on windows. 

#This will run on Windows but not Linux
If (1 -eq 1) {
    'This number is  1'
}  
Else {
    'This number is  not 1'
}

#This will run on Windows and Linux
If (1 -eq 1) {
    'This number is  1'
} Else {
    'This number is  not 1'
}

#This will run on Windows but not Linux
If (1 -eq 1) {'This number is  1'}
Else {'This number is  not 1'}

#This will run on Windows and Linux
If (1 -eq 1) {'This number is  1'}Else {'This number is  not 1'}

**Comment by vexx32** [comment]
Is this just in the console, or are you seeing this with running scripts as well? This might be a PSReadLine issue; the behaviour you're expecting isn't actually native PS behaviour, but comes about thanks to the PSReadLine handler.

**Comment by chrisfitch** [comment]
You're right, it's just console behavior. If I save and run the ps file it works. Didn't realize it was just the console.

**Comment by chuanjiao10** [comment]
yes，in powershell script，space，tab，return，Does not affect script results。
eg:
```
1+
       #there has tab，return。
2
```


```
'a'.toupper().

tolower()
```

**Comment by iSazonov** [comment]
Please try without PSReadline module.
