### ISSUE TITLE
Feature Request: A command pallet option to open a terminal with elevated rights

### ISSUE THREAD

**Issue by tmknight** [PowerShell/PowerShell#9507]
# Summary of the new feature/enhancement

The ability to open a terminal with elevated rights: e.g. in Windows "Open Terminal as Administrator"

# Proposed technical implementation details

This would be welcome when one typically should be running VS Code as a standard user, though there may be a need to execute code with elevation.  Currently executing with elevation within VS Code requires opening VS Code with elevation.

I am primarily a Windows PowerShell user, though I can see this being helpful for PowerShell in other OS and possibly terminals for other code languages.

**Comment by fMichaleczek** [comment]
@tmknight your issue is an improvement on VSCode, you should move it on [VSCode-PowerShell repository](https://github.com/PowerShell/vscode-powershell)

**Comment by vexx32** [comment]
This should probably be opened as an issue for VS Code itself, as I doubt PowerShell or even the PowerShell extension has the capability to enable that if VS Code doesn't support it first. 🙂

**Comment by tmknight** [comment]
Doh!  Brain f@rt for where I was posting...apologies
