### ISSUE TITLE
Investigate updateable help on Linux (Update-Help)

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell#951]
Haven't checked to see if this works yet, but I highly suspect that, given its dependency on CABs, that the updateable help system is completely broken.

**Comment by vors** [comment]
Clearing the assignee

**Comment by Francisco-Gamino** [comment]
I am assigning this issue to me. I am working on a solution which is going to use zips on Linux. This means that the documentation team needs to upload to the download center a zip file in addition to the cab. On Windows, we will use both zip and cabs, and on Linux just zips. @adityapatwardhan is looking into adding the code to the publishing tools to generate the zip files.

**Comment by HemantMahawar** [comment]
@Francisco-Gamino Can you add milestone alpha.12 if this is going to ship in the next release?

**Comment by Francisco-Gamino** [comment]
This issue has been fixed.

**Comment by Francisco-Gamino** [comment]
This issue has been fixed.
