### ISSUE TITLE
Feature Idea: Retroactive Transcripts

### ISSUE THREAD

**Issue by lukexjeremy** [PowerShell/PowerShell#9514]
# Summary of the new feature/enhancement

As a user, I experiment and figure out useful pipelines during a Powershell session. Often, I only realise the value of the session at its end. I would like to retroactively create a transcript, even though I didn't enter `Start-Transcript` at the beginning of the session.

**Comment by vexx32** [comment]
Not so much a _transcript_, but `Get-History` is already a thing, if that helps. :)

**Comment by lukexjeremy** [comment]
That will do it! Thank you.
