### ISSUE TITLE
Support Question: Support ARM64 Linux?

### ISSUE THREAD

**Issue by JaneConan** [PowerShell/PowerShell#9515]
# Support Question

- When PowerShell support ARM64 Linux?

- Is the cli exactly the same as Windows?

**Comment by fMichaleczek** [comment]
@JaneConan PowerShell has an experimental build for Raspbian (ARM32/ARM64)
[Install PowerShell Core on Raspbian](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-6#raspbian)
[PowerShell 6.2 Download Release Page](https://github.com/PowerShell/PowerShell/releases/tag/v6.2.0)

What is your Linux Distribution ?

About the cli, are you talking about "Windows PowerShell" or "PowerShell Core on Windows" ?

**Comment by JaneConan** [comment]
> @JaneConan PowerShell has an experimental build for Raspbian (ARM32/ARM64)
> [Install PowerShell Core on Raspbian](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-6#raspbian)
> [PowerShell 6.2 Download Release Page](https://github.com/PowerShell/PowerShell/releases/tag/v6.2.0)
> 
> What is your Linux Distribution ?
> 
> About the cli, are you talking about "Windows PowerShell" or "PowerShell Core on Windows" ?

Thx! Let's have a try~
Kylin Linux, just like Ubuntu.

About cli, I means "PowerShell Core on Windows" 
Is that the same as we did on Windows?

**Comment by fMichaleczek** [comment]
powershell.exe is Windows PowerShell (1.0-5.1) and pwsh.exe is PowerShell Core (6.*+)
You should read this document to understand differences [Known Issues for PowerShell 6.0](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/known-issues-ps6?view=powershell-6)

**Comment by JaneConan** [comment]
All right Thx! Let's have a try~
