### ISSUE TITLE
Batch files (.bat files in windows) doesnt work correctly in powershell

### ISSUE THREAD

**Issue by usta** [PowerShell/PowerShell#9516]
Hello everyone,
This is a bug report not directly powershell ( 6.2 ) but windows itself, but thinking that it will be nice to keep it here for reference to someone else hit it again. ( To solve problem )

Within windows 10 build 18885 the powershell couldnt run bat files correctly even if you are in same path with the file. On the other hand it is working perfectly with cmd .

Solution : Just update at least windows 10 build 18890.1000 and everything working perfectly

**Comment by kiedtl** [comment]
PowerShell can only run `.ps1` scripts. I don't think it's intended to run BAT file.

**Comment by usta** [comment]
I am not talking about double clicking or internal processing. I am talking about when you try to run any bat file it acts like it couldn't find or access that file, ( I am not even talking about trying to find via path variable even it couldn't execute in the same working directory. I know it is weird but it probably a bug in window 10's build 18885 bug and it only effects PowerShell ( because everything working good in cmd )

**Comment by kiedtl** [comment]
> I am not talking about double clicking or internal processing.

Oh, whoops. You mean find the file and execute it in CMD?

**Comment by usta** [comment]
lets say that :
1 - d:
2 - cd gradle\bin
3 - gradle.bat
this 3 works in cmd but not in powershell but works in cmd ( in windows
build 18885 but it start to work after update to windows build 18890.1000 )

**Comment by TheIncorrigible1** [comment]
That's because you're not fully-pathing the file and it's not in the path... this has been the case since powershell 1.0.

**Comment by kiedtl** [comment]
Try `./gradle.bat`

**Comment by usta** [comment]
then there was another problem about path variable because if it was about
missing ./ ( i am not sure if i add it or not but probably i also added )
still it doesnt worked on the other hand after windows update it start to
work and i am not installed gradle or touched path variables , i installed
and was using it without problem then i upgraded to 18880 (or not sure
maybe18888 ) then it became not working. and just yesterday i upgraded to
18890.1000 it start to work

**Comment by usta** [comment]
if you need a little investigation i may reinstall whole setup just like it
was not working. maybe it caused a problematic upgrade to 18880.
i can try it via real system or on a vm if needed. ( but if I can reproduce
same behavior it will be much better if it was on a vm so i can share that
image )

**Comment by TravisEz13** [comment]
Per the issue template, please report windows issues to UserVoice: https://windowsserver.uservoice.com/forums/301869-powershell
https://raw.githubusercontent.com/PowerShell/PowerShell/master/.github/ISSUE_TEMPLATE/Bug_Report.md
