### ISSUE TITLE
Remove-Item on MacOS fails to use credentials of current user

### ISSUE THREAD

**Issue by spboyer** [PowerShell/PowerShell#9519]
# Steps to reproduce

```powershell
Remove-Item ./node_modules/ -Recurse
```

# Expected behavior
Delete all files/folders in `./node_modules/`

# Actual behavior

```none
Remove-Item : You do not have sufficient access rights to perform this operation.
At line:1 char:1
+ Remove-Item ./node_modules/ -Recurse
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : PermissionDenied: (/Users/shayneboyer/\u2026e/node_modules/.bin:DirectoryInfo) [Remove-Item], IOException
+ FullyQualifiedErrorId : RemoveFileSystemItemUnAuthorizedAccess,Microsoft.PowerShell.Commands.RemoveItemCommand
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Darwin 18.5.0 Darwin Kernel Version 18.5.0: Mon…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Related to #9246  ?

**Comment by spboyer** [comment]
Requires `-Force` flag, but probably should not?

**Comment by smurawski** [comment]
The `-force` enables removing hidden or read-only files/folders.  I believe in this case the `.bin` is a hidden directory and why we see the error in removing it.

(from the [help](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/remove-item?view=powershell-6#parameters))
> Forces the cmdlet to remove items that cannot otherwise be changed, such as hidden or read-only files or read-only aliases or variables.

**Comment by SteveL-MSFT** [comment]
Perhaps we could improve the error message if this is the case that the folder is read-only
