### ISSUE TITLE
Should Compiled Powershell Commandlets be able call other PSCmdlets from within the same session.

### ISSUE THREAD

**Issue by romero126** [PowerShell/PowerShell#9521]
# Summary of the new feature/enhancement
Should Compiled Powershell Commandlets be able call other PSCmdlets from within the same session.

So the problem first arose when I was trying to call another Known PSCmdlet from a module I am building. In this scenario the idea was to create an object 

WriteHostCommand cmd = new WriteHostCommand();
cmd.Object = "Hello world";
cmd.ForeGroundColor = ConsoleColor.Cyan;
cmd.Invoke();

"An error occurred while enumerating through a collection: Cmdlets derived from PSCmdlet cannot be invoked directly."

# Proposed technical implementation details (optional)

The idea behind this premise is as Powershell Commands become increasingly capable. Modules written in C# looses the ability to rapidly prototype for Powershell commandlets. 

The idea would be to allow Invoke to function.. with a Property for a SessionState. 

Thoughts?

**Comment by rgbav** [comment]
I am also missing this...
