### ISSUE TITLE
[bug] [linux] PowerShell not compatible with ICU v64+?

### ISSUE THREAD

**Issue by kiedtl** [PowerShell/PowerShell#9522]
# Steps to reproduce

1. on Arch Linux (not sure if it happens on any other system) run `pwsh` to start PowerShell. 

# Expected behavior

PowerShell should start up without errors.

# Actual behavior
If `core/icu` package is v64 or higher, the following error appears and PowerShell crashes:
```
FailFast:
Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.

   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.AppDomain.InitializeCompatibilityFlags()
   at System.AppDomain.Setup(System.Object)
[1]    30888 abort (core dumped)  pwsh
```

To fix this I had to downgrade the ICU package (which breaks a couple of other packages).

# Environment data

PowerShell data:
```
Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Linux 5.0.10-arch1-1-ARCH #1 SMP PREEMPT Sat Apr 27 20:06:45 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
Neofetch:
```
kiedtl@kmach
------------
OS: Arch Linux x86_64
Host: Aspire E5-576 V1.43
Kernel: 5.0.10-arch1-1-ARCH
Packages: 1437 (pacman), 3 (snap)
Shell: zsh 5.7.1
WM: i3
Theme: Adwaita [GTK2]
Icons: Adwaita [GTK2]
Terminal: alacritty
CPU: Intel i3-8130U (4) @ 3.400GHz
GPU: Intel UHD Graphics 620
Memory: 2881MiB / 15916MiB
Disk (/): 19G / 51G (40%)
```
PowerShell was installed using the snap package.

---
(Not sure if this a PowerShell problem or a .NET Core problem.)

**Comment by iSazonov** [comment]
PowerShell doesn't use ICU directly. I think it is .Net Core issue.

**Comment by kiedtl** [comment]
> PowerShell doesn't use ICU directly. I think it is .Net Core issue.

OK, I'll file an issue there.

**Comment by iSazonov** [comment]
Please add reference to the issue.

**Comment by farzadmf** [comment]
@kiedtl Can you please update this issue to know whether your issue was solved or not?

**Comment by kiedtl** [comment]
no, not solved yet. I didn't get around to filing an issue on the .NET core repo either, sorry.

BTW, I've tried to have both versions of the package installed, however pacman ( the package manager for my distro, Arch linux) doesn't allow two version of a package to be installed at the same time. -_-

**Comment by farzadmf** [comment]
Yep, same for me here. I'm using Manjaro, which is also Arch-based. Based on the things I saw (for example dotnet/core#2186, it's a configuration that can be done in .NET Core for individual projects, but I have no idea how to set it for Powershell running from the `snap` package

**Comment by iSazonov** [comment]
You could ask in https://github.com/PowerShell/PowerShell-Snap repository.
