### ISSUE TITLE
Format of ConvertTo-Json is not matching what document states

### ISSUE THREAD

**Issue by prbans** [PowerShell/PowerShell#9525]
# Steps to reproduce

```powershell
Get-Date | Select-Object -Property * | ConvertTo-Json
```

# Expected behavior

Example 4 - https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertto-json?view=powershell-6
![image](https://user-images.githubusercontent.com/42591144/57107778-c6cac980-6ce5-11e9-89b4-44f76f637fa9.png)

# Actual behavior

![image](https://user-images.githubusercontent.com/42591144/57107784-cd594100-6ce5-11e9-9ffe-8febe7788a48.png)

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      5.1.17763.497
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.497
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by fMichaleczek** [comment]
@prbans Your environment data shows PS 5.1 and the documentation link is for PS 6 
The good link for your version is [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertto-json?view=powershell-5.1)

**Comment by prbans** [comment]
How do I upgrade my powershell to be v6 in that case?

Is there an option I can pass to V5 that enables V6 behavior?

**Comment by vexx32** [comment]
Download and install V6 from the repo here: https://github.com/PowerShell/PowerShell/releases

And no, there are no further features being added to v5, so if you want v6 behaviour, you have to use v6. 🙂
