### ISSUE TITLE
Feature Request: PE support in Expand-Archive 

### ISSUE THREAD

**Issue by cowlinator** [PowerShell/PowerShell#9527]
# Summary of the new feature/enhancement

`Expand-Archive` should support PE (Portable Executable) archive type, which was created by Microsoft, and is frequently used in Windows.

As a user, I want to be able to extract the contents of self-extracting archives such as Windows installers, so that I can automate custom installs not provided by the installer creators.

# Proposed technical implementation details (optional)

`Expand-Archive` should support PE (Portable Executable) archive type.

Example usage:

`Expand-Archive -LiteralPath "docker_installer.exe" -DestinationPath "docker_temp" -Force`

**Comment by iSazonov** [comment]
Please move your request to https://github.com/PowerShell/Microsoft.PowerShell.Archive
