### ISSUE TITLE
Feature Request: Equivalent of bash `&&`

### ISSUE THREAD

**Issue by guitarrapc** [PowerShell/PowerShell#9539]
# Summary of the new feature/enhancement

> Note: Sorry in advance, if there are already similar cases. I couldn't find with && or old connect case # 778798

To improve more Linux-friendlyness, I do like to propose `&&` syntax, again. (as many others used to do since powershell is released)

In CMD or Bash, there are `&&` which means "execute command 1, and if it succeeds, execute command 2".

When I move cmd/bash command `build && run_tests` to PowerShell, I need to change code to run with following choices.

1.  `(build) -and (run_tests)`
1. `build; if ($?) {run_tests}`
1. `cmd /c "build && run_tests" or `bash -c "build && run_tests"` (don't forget quote command with "", it means can not straight copy&pate.)

`-and` is powershellish way but not familiar to fresh users, and it will output Error Message and `boolean output`. try ` (ls z:\) -and (echo hoge)`.

I think offer `build && run_tests` syntax is great experience for many users.

# Proposed technical implementation details (optional)

New operator `&&`.

Currently it produce error.

```
PS> echo fuga && echo hoge
At line:1 char:11
+ echo fuga && echo hoge
+           ~~
The token '&&' is not a valid statement separator in this version.
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : InvalidEndOfLine
```

## Ref

> https://connect.microsoft.com/PowerShell/feedback/details/778798/implement-the-and-operators-that-bash-has
>
> https://stackoverflow.com/questions/563600/can-i-get-to-work-in-powershell

**Comment by mklement0** [comment]
Indeed it would be nice to have that, but it has already been proposed in #3241.

**Comment by guitarrapc** [comment]
thanks, close as dup.
