### ISSUE TITLE
Implement shell globbing

### ISSUE THREAD

**Issue by andschwa** [PowerShell/PowerShell#954]
PowerShell is going to need to support file globbing for native commands, like:

``` powershell
gcc *.c
```

That scenario should probably work.

/cc @BrucePay @lzybkr

**Comment by andschwa** [comment]
This is implemented in #2325, but the issue has been usurped by RFC 9, please see https://github.com/PowerShell/PowerShell-RFC/issues/33. Closing.

**Comment by joeyaiello** [comment]
Reopening to track the need for a revised RFC.

**Comment by daxian-dbw** [comment]
This issue is closed via #3643.
There is a follow-up issue tracking the future work in this area: #3655

**Comment by khaewnoy** [comment]
> PowerShell is going to need to support file globbing for native commands, like:
> 
> ``` powershell
> gcc *.c
> ```
> 
> That scenario should probably work.
> 
> /cc @BrucePay @lzybkr 
>
