### ISSUE TITLE
Powershell core in C# - Not loading PKI Module.

### ISSUE THREAD

**Issue by paragmkulkarni** [PowerShell/PowerShell#9542]
Hi, 

I am pretty new to GitHub. 
Below is my scenario.

I have a powershell script which generates a self signed certificate. This ps1 file runs very fins if i execute using powershell command prompt. It generates certificate and a pfx file both and outputs the path where those are created.

I am trying to using the same script file in .Net Core console application using Powershell SDK (ver > 6.0).  Code to execute powershell script is as below 

C# Code to invoke powershell script.
`String script = File.ReadAllText(@"CertificateGenerator.ps1");
               InitialSessionState initial = InitialSessionState.CreateDefault();
                initial.ImportPSModule(new[] { "PKI" });
                Runspace rs = RunspaceFactory.CreateRunspace(initial);
                rs.Open();
                using (PowerShell powerShellInstance = PowerShell.Create())
                {
                    powerShellInstance.Runspace = rs;
                    powerShellInstance.AddScript(script, true);

                    powerShellInstance.AddParameter("deviceName", deviceID);
                    powerShellInstance.AddParameter("pfxPassword", password);

                    //Result of the script with Invoke()
                    Collection<PSObject> result = powerShellInstance.Invoke();

                    if (powerShellInstance.Streams.Error.Count > 0)
                        Console.WriteLine($"Errors ({powerShellInstance.Streams.Error.Count}):\n");

                    if (result.Count >= 3)
                    {
                        certificateFilePath = result[1].ToString();
                        pfxFilePath = result[2].ToString();
                    }
                }`               

But when executed Certificate nor pfx is generated. In the Powershell instance i get an error as below 
Exception	{System.Management.Automation.CommandNotFoundException: The term 'New-SelfSignedCertificate' is not recognized as the name of a cmdlet, function, script file, or operable program.

So i tried to import the "PKI" module in the script. Post that i get below error
Exception = {System.TypeInitializationException: The type initializer for "Module" threw an exception.

Just information :: This script if executed using same C# code from Win form application (.Net framework) runs very smoothly and as expected.

Can you please help me with this. My intent is to automate the certificate generation process for the simulated devices.

Below is the script
`
Param(
	   [parameter(ValueFromPipeline,ValueFromPipelineByPropertyName)]
       [string]$deviceName = "testx509sim5", 
	   [string]$pfxPassword = "test"
)

$BasePath = Convert-Path .;
New-Item -Path $BasePath -Name "Certificates" -ItemType "directory" -Force
$BasePath = $BasePath + "\Certificates\";

$pfxcertificatename = $BasePath + $deviceName + "_personalinfo.pfx";
$certificatename = $BasePath + $deviceName + "_certificate.cer";
$password = ConvertTo-SecureString -String $pfxPassword -AsPlainText -Force;

try
{
	$cert = New-SelfSignedCertificate -Type Custom -Subject "CN=$deviceName, O=TEST, C=US" -KeySpec Signature -KeyExportPolicy Exportable -HashAlgorithm sha256 -KeyLength 2048 -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.2") -CertStoreLocation "Cert:\CurrentUser\My";
	$cert | Export-PfxCertificate -FilePath $pfxcertificatename  -Password $password;
	Set-Content -Path $certificatename -Value ([Convert]::ToBase64String($cert.RawData)) -Encoding Ascii;
}
catch
{
	$_;
}
$certificatename;
$pfxcertificatename;
`

**Comment by iSazonov** [comment]
Please see the sample https://github.com/rjmholt/SelfSignedCertificate/
