### ISSUE TITLE
Add support for tab completing common/suggested parameter values.

### ISSUE THREAD

**Issue by veleek** [PowerShell/PowerShell#9548]
# Summary of the new feature/enhancement

You can use ValidateSet to quickly and easily add tab-completion to parameter values.  But in some cases a user wants to add tab completion for common value to help enable discoverability while still allowing the user to provide any value.

# Proposed technical implementation details (optional)

Add a `SuggestedParametersAttribute` which should be defined almost identically to `ValidateSet` (including enabling generating the set using a script.  Decorating a parameter with this will enable tab-completion for that parameter, but doesn't result in any further validation.

```ps
function New-Pet
{
  [CmdletBinding]
  param(
    # Only support this fixed set of pet types 
    [ValidateSet("cat","dog","fish")] $PetType,

    # We provide suggestions for the common parameters, but the user
    # can choose to provide whatever they want as the value.
    [SuggestedSet("Buttons", "Spot", "Goldie")] $PetName
  )

  ...
}
```

**Comment by vexx32** [comment]
This already exists; it's called `[ArgumentCompleter()]` and it takes a scriptblock parameter:

```powershell
function New-Pet {
    [CmdletBinding]
    param(
        # Only support this fixed set of pet types 
        [ValidateSet("cat","dog","fish")] $PetType,

        # We provide suggestions for the common parameters, but the user
        # can choose to provide whatever they want as the value.
        [ArgumentCompleter({"Buttons", "Spot", "Goldie"})] $PetName
    )

    "$Petname the $PetType!"
}
```

You can get pretty fancy with it, and it's not the only way to go. Some alternatives as well as a more in depth example of ArgumentCompleter can be found in my blog post here: https://vexx32.github.io/2018/11/29/Dynamic-ValidateSet/

**Comment by veleek** [comment]
@vexx32 Thanks so much for the pointer.  I've literally searched for this multiple times on multiple days and have not been able to find anything.  Every single "add tab-completion to powershell arguments" article seems to side step this functionality.  So glad to find it already available!

**Comment by vexx32** [comment]
No worries! 

Quick thing I forgot to mention, you can also add these to cmdlets you *didn't* write yourself with the `Register-ArgumentCompleter` cmdlet :)

**Comment by veleek** [comment]
Just wanted to add a quick follow-up for anybody else who is searching for a solution and runs into this example.  Unlike `ValidateSet`, the `ArgumentCompleter` accepts a scriptblock that should return all possible options _based on the current input_.  

If you use the simple example above:

```posh
param(
    ...
    [ArgumentCompleter({"Buttons", "Spot", "Goldie"})] $PetName
)
```

Then when if you type `New-Pet -PetName Go[TAB]` it will auto-complete to the first value in the returned set - which in this case is `Buttons`.  This is not the expected behavior for most scenarios so it can be confusing.  To get the expected behavior, you need to filter your list of results so you only return the values you want.

```posh
param(
    ...
    [ArgumentCompleter(
    {
        param($Command, $Parameter, $WordToComplete, $CommandAst, $FakeBoundParams)
        "Buttons", "Spot", "Goldie" -like "$WordToComplete*" 
    })] $PetName
)
```

Alternatively you can simplify it a bit by using the implicitly passed `$args` variable to do the same thing.
```posh
param(
    ...
    [ArgumentCompleter({"Buttons", "Spot", "Goldie" -like "$($args[2])*" })] $PetName
)
```

And the complete working example.  Note that typing `Gold` and hitting tab will cycle through the matching values as expected.

```posh
function New-Pet {
    [CmdletBinding()]
    param(
        # Only support this fixed set of pet types 
        [ValidateSet("Cat","Dog","Fish")] $PetType,

        # Provide some common values but allow the user to provide their own.
        [ArgumentCompleter({
            param($Command, $Parameter, $WordToComplete, $CommandAst, $FakeBoundParams)
            "Buttons", "Spot", "Goldie", "Golden" -like "$WordToComplete*" 
        })] $PetName
    )

    "$Petname the $PetType!"
}
```

**Comment by iSazonov** [comment]
@veleek You could open new issue in https://github.com/MicrosoftDocs/PowerShell-Docs if you see that documentation is poor.
