### ISSUE TITLE
Add key to result JSON

### ISSUE THREAD

**Issue by souuuf** [PowerShell/PowerShell#9549]
# Support Question
Hello, 

I want to generate a json file from a result of Get-AzureADUser Query.

My output is this:
[
    {
        "DisplayName":  "xxxx",
        "UserPrincipalName":  "yyyy",
        "Country":  null,
        "City":  null
    },
    {
        "DisplayName":  "uuu",
        "UserPrincipalName":  "ooo",
        "Country":  null,
        "City":  null
    }
]
-----
and I want to generate this : (adding the key Values to this result)
{
"Values":[
    {
        "DisplayName":  "xxxx",
        "UserPrincipalName":  "yyyy",
        "Country":  null,
        "City":  null
    },
    {
        "DisplayName":  "uuu",
        "UserPrincipalName":  "ooo",
        "Country":  null,
        "City":  null
    }
]
}
-------
How I can modify my code to get this format please ?
below my code:

$Users = Get-AzureADUser -Filter "startswith(displayName,'soufiane')"
 
$Users | where {$_.userprincipalname -like "*web*"} | Select DisplayName, UserPrincipalName, Country, City  | ConvertTo-Json -depth 100 | Out-File "C:\Users.txt"

## Official support

[PowerShell Support Lifecycle](https://aka.ms/pslifecycle)

## Community Resources

[Slack][powershell-slack] and [Discord][powershell-discord] Community Chat - Interactive chat with other PowerShell enthusiasts. Both Slack and Discord are bridged via a bot and can seamlessly talk to each other.
[PowerShell.org Forum](https://powershell.org/forums/) - Search or post new general PowerShell usage questions

[powershell-slack]: https://join.slack.com/t/powershell/shared_invite/enQtMzA3MDcxNTM5MTkxLTBmMWIyNzhkYzVjNGRiOTgxZmFlN2E0ZmVmOWU5NDczNTY2NDFhZjFlZTM1MTZiMWIzZDcwMGYzNjQ3YTRkNWM
[powershell-discord]: https://discordapp.com/invite/AtzXnJM

**Comment by iSazonov** [comment]
@souuuf The repo is for PowerShell development. For getting help please use community resources like forums and chats.
