### ISSUE TITLE
New Request -- Use part of RAM cache for C Drive

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#9550]
In windows server 2016 , the storage space , can use SSD to cache for HDD, can use NVMe to cache SSD , even can use PMEM ....

In windows server 2016, with the Iscsi Target server ,we can create a RAM disk.

But I am running a windows 10 , and now, I am using a 3td part software named PrimoCache , to use part of my free RAM to cache my C drive.

I wonder ,in the future,  whether will have any cmdlet  can use my free RAM to create a cache to cache my C drive .

How do you think?

**Comment by iSazonov** [comment]
This could be RAM disk file provider. But I don't think that it will implemented in the repo.
