### ISSUE TITLE
!!! READ TEMPLATE COMPLETELY FIRST!!!

### ISSUE THREAD

**Issue by force2reckin** [PowerShell/PowerShell#9573]
[browser.20190427T213602-0700.log](https://github.com/PowerShell/PowerShell/files/3161591/browser.20190427T213602-0700.log)
# Security Issue

Excerpt from [Issue Management - Security Vulnerabilities](https://github.com/PowerShell/PowerShell/blob/master/docs/maintainers/issue-management.md#security-vulnerabilities)

> If you believe that there is a security vulnerability in PowerShell Core,
it **must** be reported to [secure@microsoft.com](https://technet.microsoft.com/security/ff852094.aspx)
to allow for [Coordinated Vulnerability Disclosure](https://technet.microsoft.com/security/dn467923).
**Only** file an issue, if secure@microsoft.com has confirmed filing an issue is appropriate.

When you have permission from secure@microsoft.com to file an issue here,
please use the Bug Report template and state in the description that you are reporting the issue in coordination with secure@microsoft.com.

**Comment by TravisEz13** [comment]
@force2reckin I'm not sure how this is PowerShell related.

**Comment by TravisEz13** [comment]
Please update issue title and description if this is a real powershell issue.
