### ISSUE TITLE
Typo in Get-Help Stop-Process -examples?

### ISSUE THREAD

**Issue by Xaunadu** [PowerShell/PowerShell#9592]
When running "Get-Help Stop-Process -examples", the calculator example reads out $p = Get-Crocess -name "calc".

**Comment by vexx32** [comment]
Nice catch! This should be filed as an issue in https://github.com/Microsoft/PowerShell-Docs though 🙂

**Comment by Xaunadu** [comment]
Sorry about that. Should I add it on there instead when I get the chance?

**Comment by vexx32** [comment]
Absolutely, whenever you can. :)

Or if you prefer, you can submit a PR to the affected documents and change it directly. They're usually pretty quick to look over PRs in that repo as well.

**Comment by Xaunadu** [comment]
Sure thing. Thanks for the info!
