### ISSUE TITLE
Compress-Archive -- Size issue

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#9598]
Try to package a folder around 5GB size.
But compress-archive  thrown me Exception of type 'System.OutOfMemoryException' .
From google , seems it has size limitation, Any one can give some advice ? 
If it has size limitation , should it be improved ?

**Comment by anmenaga** [comment]
Most likely you're hitting this limitation:
[The .Net ZipFile class currently has a limitation of 2GB sizes](https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/19)
