### ISSUE TITLE
Get-WinEvent is not friendly than Get-EventLog

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#9608]
Get-EventLog is more comfortable providing the ability to ask for Events without checking any documentation.
However, Get-WinEvent  is a little more complicated to define a HashTable to filter events.

I hope Get-WinEvent can be improved by using more parameters , just like Get-WinEvent can use tons of parameter and the value of parameter can be automatically completed by using TAB.

$FilterHashTable = @{
        LogName   = 'Security'
        ProviderName= 'Microsoft-Windows-Security-Auditing' 
        #Path = <String[]>
        #Keywords = <Long[]>
        ID        = 4625
        #Level = <Int32[]>
        StartTime = (Get-Date).AddDays(-1)
        EndTime   = Get-Date
        #UserID = <SID>
        #Data = <String[]>
    }
    Get-WinEvent -FilterHashtable $FilterHashTable -MaxEvents 5
    Get-EventLog -LogName 'Security' -Source 'Microsoft-Windows-Security-Auditing' -Newest 5

**Comment by iSazonov** [comment]
New logs have more advanced API and the API was exposed to Get-WinEvent cmdlet. There is only a few common parameters. They are easy to remember or take from examples of help. Powerful queries can only be made using XML. So I do not see any benefit from adding new parameters. Perhaps we could improve IntelliSense.

**Comment by theJasonHelmick** [comment]
Thank you for the feedback - this is by design.
