### ISSUE TITLE
ConvertTo-Json doesn't place type hint correctly

### ISSUE THREAD

**Issue by davidseibel** [PowerShell/PowerShell#9610]
In Windows PowerShell, if converting an object to JSON that has a type hint __type, it would correctly place the type hint as the first property in the JSON output.  This is a requirement of some APIs (including WCF-based APIs, see here: https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/stand-alone-json-serialization#type-hint-position-in-json-objects)

In PowerShell Core, this ordering is no longer enforced.

### Expected Output (Example from Windows PowerShell):
```PowerShell
C:\> [PSCustomObject]@{ param1 = "test"; __type = "sometype"; param2 = "test" } | ConvertTo-Json
{
    "__type":  "sometype",
    "param1":  "test",
    "param2":  "test"
}
```

### Actual Output:
```PowerShell
C:\> [PSCustomObject]@{ param1 = "test"; __type = "sometype"; param2 = "test" } | ConvertTo-Json
{
  "param1": "test",
  "__type": "sometype",
  "param2": "test"
}
```

### Version Data:
```PowerShell
Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by Cirzen** [comment]
As I understand it, it's the hashtable where the ordering is not guaranteed, and technically never has been, even if the results normally came out alphabetically sorted. 
You should be able to use `[pscustomobject][ordered]@{__type="foo", param1 = ""...}` to maintain a specific order and put the type hint first in the associative array.

**Comment by vexx32** [comment]
You're not wrong, but it looks like the API used in Windows PowerShell had a special case for type hints which should likely be mimicked in the new APIs used for 6.0+

**Comment by davidseibel** [comment]
I should clarify, I'm specifically running into this problem with PowerShell classes.  I just used PSCustomObject for the example.  Sure, I could work-around this by placing __type first in the class (as Cirzen recommends), but this doesn't work when sub-classing:

```PowerShell
class BaseClass {
    $__type = "BaseClass"
    $baseprop = "value"
} 

class SubClass : BaseClass {
    $subprop
    SubClass() {
        $this.__type = "SomeClass"
    }
}

$test = [SubClass]::new()
$test | ConvertTo-Json
```
Windows PowerShell output:
```PowerShell
{
    "__type":  "SomeClass",
    "subprop":  null,
    "baseprop":  "value"
}
```
PowerShell Core output:
```PowerShell
{
  "subprop": null,
  "__type": "SomeClass",
  "baseprop": "value"
}
```

**Comment by vexx32** [comment]
Yeah, this definitely should be handled by the json serializer.

/cc @markekraus is this potentially a simple fix? 🙂

**Comment by davidseibel** [comment]
I found a workaround for the sub-classing problem: just redefine the property on the subclass rather than reusing the inherited property (as I did in my earlier example):

```PowerShell
class BaseClass {
    $__type = "BaseClass"
    $baseprop = "value"
} 

class SubClass : BaseClass {
    $__type = "SubClass"
    $subprop = "anothervalue"
}

$test = [SubClass]::new()
$test | ConvertTo-Json
```
Output:
``` PowerShell
{
  "__type": "SubClass",
  "subprop": "anothervalue",
  "baseprop": "value"
}
```
This works on both 5.1.17134.858 and 7.0.0-rc.3.  I have not tested on other versions.
