### ISSUE TITLE
add parameter option - Get-Clipboard -TextFormatType TabSeparatedValue

### ISSUE THREAD

**Issue by jasonchester** [PowerShell/PowerShell#9612]
# Summary of the new feature/enhancement
When copying from excel, data is returned using a tab as a delimeter.

using Get-Clipboard in powershell requires an additional step to convert the tab separated text into objects.

```powershell
Get-Clipboard | ConvertFrom-Csv -Delimiter `t
```
It would simplify the following command if Get-Clipboard supported TabSeparatedValue, the above could be replaced with the following.
```powershell
Get-Clipboard -TextFormatType TabSeparatedValue
```

# Proposed technical implementation details

Add **TabSeparatedValue** as an option to the **TextFormatType** parameter in the **Get-Clipboard** commandlet

**Comment by iSazonov** [comment]
At first, the cmdlet is not implemented in the repo. You could move the request to UserVoice.
Also I guess ClipBoard uses generic API. So you need request Office team.
