### ISSUE TITLE
New request -- Show the updating item when do a Invoke-GPUpdate

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#9615]
No mater we are doing an Invoke-GPUpdate  or gpupdate .
It shows me nothing except that "updating policy".

However , company has tones of gpo objects. and DC is in a office that far away from the client.
It took a very very long time to update GPO. Sometimes I wonder whether the update process is dead or not.  nothing happen.

If Invoke-GPUpdate comes with a verbose-like parameter , which will show updating xxx gpo objects. completed xxx gpo object , updating xxxx gpo object , completed xxxx gpo objects ... ,then things will be much better.

BR

**Comment by iSazonov** [comment]
@tlsalex The cmdlet is not in the repo/ Please move your report to UserVoice or use Windows 10 Feedback tool.
