### ISSUE TITLE
PoshChan is great but PR conversations can become noisy really quickly

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/PowerShell#9620]
I love the addition of the PoshChan bot and receiving email messages for PR tests that fail. That's tremendously valuable, thank you for adding that, I really appreciate it.

That said, I think you should reconsider PoshChan's interaction with conversations on the PR. The automated build process already shows its results in a PR, and while manually pulling the details of a failed build step is tedious/annoying, pulling those details out and adding them directly to the PR conversation is too noisy and takes value away from a PR conversation, especially when there are multiple builds (Windows, macos, linux) and when certain tests fail on each of those builds, resulting in the same information being posted three times.

How about updating PoshChan to gather the data for build step failures and posting a single message to the conversation that:
1. Tags the PR author; and
1. Includes a **link** to the specific issues (which would be stored elsewhere -- a randomly named text file in the cloud, or something similar) so that the PR author can review and correct the issues while still having useful, less noisy conversation in the PR itself.

Either that or have PoshChan hide/remove old messages from a PR conversation when a new build starts so that only the latest are immediately visible, and on successful build hide/remove any previous messages.

**Comment by SteveL-MSFT** [comment]
@KirkMunro can you open an issue here? https://github.com/SteveL-MSFT/PoshChan-Bot

Let me think about this a bit.  There isn't an API to hide comments, but there is one to delete them.
