### ISSUE TITLE
Add nameof keyword

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#9626]
# Summary of the new feature/enhancement

The `nameof` keyword would be very useful for the same reasons it's useful in C#.  It may not necessarily be required in basic automation, but when writing highly resilient/portable tooling it becomes significantly more desirable.

There are two main scenarios I have in mind as motivation:

1. Ensuring a parameter variable is populated by parameter binding (and not by a previous scope) with `$PSBoundParameters.ContainsKey`.
    ```powershell
        function Test-Parameter {
        [CmdletBinding()]
        param(
            [Parameter()]
            [string] $FileName
        )
        end {
            if ($null -ne $FileName) {
                # This may be true, but doesn't necessarily mean the parameter was passed.
                'FileName isn''t null!'
            }


            # Currently you need to write:
            # if ($PSBoundParameters.ContainsKey('FileName')) {
            if ($PSBoundParameters.ContainsKey(nameof($FileName))) {
                'FileName was actually specified!'
            }
        }
    }

    Test-Parameter -FileName 'test'

    # returns
    # FileName isn't null!
    # FileName was actually specified!

    $FileName = 'something else'
    Test-Parameter

    # returns
    # FileName isn't null!
    ```
1. Argument related error reporting, especially in classes.
    ```powershell
    class Utils {
        static [void] DeleteFile([string] $fileName) {
            if ([string]::IsNullOrEmpty($fileName)) {
                # Current you need to write:
                # throw [ArgumentNullException]::new('fileName')
                throw [ArgumentNullException]::new(nameof($fileName))
            }
        }
    }
    ```

Granted there is a lack of symbol rename support in most editors (including PSES) but that won't be the case forever, and it's still typically easier to notice a variable name vs the contents of a string.

# Proposed technical implementation details (optional)

## Syntax

```antlr
nameof_expression
    : 'nameof' body
    ;

body
    : start_tag target end_tag
    ;

start_tag
    : '{'
    | '('
    ;

end_tag
    : '}'
    | ')'
    ;

target
    : variable_expression_ast
    | member_expression_ast
    | type_expression_ast
    | command_ast
    ;
```

I suggest allowing `{}` as an enclosure because the only way to get similar functionality today is to write a function like this:

```powershell
function nameof {
    [CmdletBinding()]
    param(
        [Parameter(Position=0, Mandatory)]
        [ValidateNotNull()]
        [ScriptBlock] $Expression
    )
    end {
        $firstElement = $Expression.Ast.EndBlock.Statements[0].PipelineElements[0]
        if ($firstElement.Expression.VariablePath.UserPath) {
            return $firstElement.Expression.VariablePath.UserPath
        }

        if ($firstElement.Expression.Member) {
            return $firstElement.Expression.Member.SafeGetValue()
        }

        if ($firstElement.GetCommandName) {
            return $firstElement.GetCommandName()
        }

        if ($firstElement.Expression.TypeName.FullName) {
            return $firstElement.Expression.TypeName.FullName
        }
    }
}
```

Allowing `{}` would keep compatibility with code using that pattern today (assuming anyone else does that)

## AST

```csharp
public class NameOfExpressionAst : ExpressionAst
{
    public CommandBaseAst Target { get; }

    public NameOfExpressionAst(IScriptExtent extent, CommandBaseAst target);
}
```

Typing the `Target` as a `CommandBaseAst` conveys that the contents should be a single command or expression.

Semantic checks should be used to assert:

1. A `CommandAst` has only one element, which is a bare word `StringConstantExpressionAst`
1. A `CommandExpressionAst` has an expression of type `MemberExpressionAst`, `VariableExpressionAst`, or `TypeExpressionAst`
1. If the underlying target is a `MemberExpressionAst`, the `Member` property is a `StringConstantExpressionAst`

I picked the base `ExpressionAst` because it would be ideal if the keyword could be parsed in all parsing modes (except command argument mode)

## Implementation

The `Compiler` could emit a string `ConstantExpression` based on `Target` when visiting `NameOfExpressionAst`.

|Type|Value Path|
|---|---|
|CommandAst|target.GetCommandName()|
|MemberExpressionAst|((StringConstantExpressionAst)target.Member).Value|
|VariableExpressionAst|target.VariablePath.UserPath|
|TypeExpressionAst|target.TypeName.FullName|

## Impact

This would technically be a breaking change, but impact could be minimized by requiring no whitespace between the `nameof` keyword and the opening tag.

**Comment by BrucePay** [comment]
Hi @SeeminglyScience - just a thought. As near as I can tell, nowhere in this issue have you actually included any examples showing how and why this feature would be used in PowerShell. Saying that it's like C# isn't helpful for people who aren't C# programmers (i.e. the bulk of PowerShell users). So I think adding a few lines of expository text and some examples would help convince people that this is a good idea. Just a thought...

**Comment by SeeminglyScience** [comment]
@BrucePay I did describe the scenarios where it'd be most useful in PowerShell.  I've added some code examples to help illustrate, thank you!

**Comment by patridge** [comment]
In addition to use cases above, I'd also love this feature for the debugging potential as I develop scripts/cmdlets.

I'm currently trying to figure out where things are going wrong with a collection of interdependent variables I'm declaring as I write my first cmdlet. Since I'm still writing it, some of the variable names change, so I want to use the exact variable name when dumping out values.

Something like this would be handy for that output.

```powershell
Write-Host "$(nameof($someVariable)): $someVariable"
```

I'm just starting to learn to use `Get-Variable -Scope Local` as a workaround on the debugging side, but a `nameof` shorthand would allow for more output control and eliminate some of the noise that is also part of the full local scope.

**Comment by VesperGarment** [comment]
A case I've run into that would like this. Although a bit meta. The following:

```
$CurrentUser = New-Object System.Security.Principal.NTAccount($CurrentUserName)
Export-ModuleMember -Variable 'CurrentUser'
```
triggers 
```
PSScriptAnalyzer/UseDeclaredVarsMoreThanAssignments
```
because it thinks $CurrentUser wasn't used. If I could instead write 
```
$CurrentUser = New-Object System.Security.Principal.NTAccount($CurrentUserName)
Export-ModuleMember -Variable nameof($CurrentUser)
```
then PSScriptAnalyzer and anything else that parses PS code and watches variables would be able to get this case right.

It strikes me that there aren't _any_ runtime reasons to add this. Explicit strings run just fine. If this were added, it'd have to be motivated by readability (by humans and robots) and resilience to errors creeping in over time. Perhaps `nameof($AnUndefinedVariable)` should be an error as opposed to either `$null` or `'AnUndefinedVariable'`.

**Comment by Jaykul** [comment]
Without rename refactoring support in the PowerShell VS Code extension, it feels like the only benefit you'd get is if `nameof` threw a _parse time_ error if the variable or member didn't actually already exist...

**Comment by jeffshumphreys** [comment]
Used to use C#. It helps with refactoring variable names. I refactor names so they match their actual use as opposed to what I thought they were going to be used for.  This speeds maintenance and readability.
Renaming in VS Code using Ctrl+F2 may find these strings, not sure.
