### ISSUE TITLE
Integrating ML.NET with Powershell

### ISSUE THREAD

**Issue by mikeTWC1984** [PowerShell/PowerShell#9683]
### System information
- **Windows POwershell / Powershell Core**
- **Windows 10, Linux (Ubuntu)**:
- **ML version 1.0.0-preview**:

### Issue

I'm trying to integrate ML.NET with powershell. I'm using [Sentiment Analysis sample](https://github.com/dotnet/samples/tree/master/machine-learning/tutorials/SentimentAnalysis) for testing. Sample code runs just fine as a C# console app, but throws errors if executed as Powershell Cmdlet. It doesn't matter if it's binary cmdlet  ( using same exact code as console app) or pure PS. It doesn't work even if I save sample as a class library (and calling static methods from PS).

- **Shuffle input cursor reader failed with an exception**
If disabling shuffling, getting this:
- **Splitter/consolidator worker encountered exception while consuming source data**

This happens when calling fit method after trainer is added to the pipeline (I can call fit on estimator with no error). I tried Log regression and Fast Tree trainers (getting same errors)

Not sure if there is any fundamental blocker, but I think it would be extremely useful to get it work with PowerShell. Below are links to MLNET source files where those errors are described, is there anything incompatible with powershell runtime?

[Shuffle input cursor](https://github.com/dotnet/machinelearning/blob/45b6c43387294d19cad843a21e87539213e8d34c/src/Microsoft.ML.Data/Transforms/RowShufflingTransformer.cs#L652)
[Splitter/consolidator worker](https://github.com/dotnet/machinelearning/blob/45b6c43387294d19cad843a21e87539213e8d34c/src/Microsoft.ML.Data/Data/DataViewUtils.cs#L832)

### Source code / logs

```PowerShell

<# Downloading assemblies and data set

# download nuget if needed
# iwr "https://dist.nuget.org/win-x86-commandline/latest/nuget.exe" -OutFile "nuget.exe"

nuget install Microsoft.ML -version 1.0.0-preview

mkdir bin

gci "*\lib\netstandard*\*.dll" | copy-item -Destination ".\bin"

$url = "https://raw.githubusercontent.com/lucasalexander/mlnet-samples/master/sentiment-analysis/data/yelp_labelled.txt"
Invoke-WebRequest -Uri $url -OutFile "yelp_labelled.txt"

#>


Add-Type -Path "$pwd\bin\*.dll" 


$dataPath = "$pwd\yelp_labelled.txt"

$mlCOntext = [Microsoft.ML.MLContext]::new()

$columns = [System.Collections.Generic.List``1[Microsoft.ML.Data.TextLoader+Column]]::new()

$columns.Add([Microsoft.ML.Data.TextLoader+Column]::new("SentimentText", "String", 0))
$columns.Add([Microsoft.ML.Data.TextLoader+Column]::new("Label", "Boolean", 1))

$columns.Add([Microsoft.ML.Data.TextLoader+Column]::new("PredictedLabel", "Boolean", 2))
$columns.Add([Microsoft.ML.Data.TextLoader+Column]::new("Probability", "Single", 3))
$columns.Add([Microsoft.ML.Data.TextLoader+Column]::new("Score", "Single", 4))

$opt = [Microsoft.ML.Data.TextLoader+Options]::new()
$opt.Separators = "`t"
$opt.Columns = $columns
$opt.HasHeader = $false


$dataView = [Microsoft.ML.TextLoaderSaverCatalog]::LoadFromTextFile($mlCOntext.Data, $dataPath, $opt)

# preview data
# [Microsoft.ML.DebuggerExtensions]::Preview($dataView).rowview | foreach { $_.Values.Value -join " | " }


$splitDataView =  $mlCOntext.Data.TrainTestSplit($dataView, 0.2)
$trainSet = $splitDataView.TrainSet
$testSet = $splitDataView.TestSet


$estimator = [Microsoft.ML.TextCatalog]::FeaturizeText($mlCOntext.Transforms.Text, "Features", "SentimentText")


$optTrain = [Microsoft.ML.Trainers.SdcaLogisticRegressionBinaryTrainer+Options]::new()
$optTrain.FeatureColumnName = "Features"
$optTrain.LabelColumnName = "Label"


# this will avoid 'Shuffle input cursor' error, but raise 'Splitter/consolidator' error
$optTrain.Shuffle = $false  

$trainer = [Microsoft.ML.StandardTrainersCatalog]::SdcaLogisticRegression($mlCOntext.BinaryClassification.Trainers, $optTrain)

<# fast tree trainer, but getting Splitter/consolidator error again
$topt = [Microsoft.ML.Trainers.FastTree.FastTreeBinaryTrainer+Options]::new()
$topt.FeatureColumnName = "Features"
$topt.LabelColumnName = "Label"
$trainer = [Microsoft.ML.TreeExtensions]::FastTree($mlCOntext.BinaryClassification.Trainers, $topt)
#>


$pipe = [Microsoft.ML.LearningPipelineExtensions]::Append($estimator, $trainer, "Everything")


$model = $pipe.Fit($trainSet)  # ERROR OCCURS HERE !!!

# if apply fit on estimator no error will occur and predict/evaluate block will work (with some dummy results)

# $model = $estimator.Fit($splitDataView.TrainSet)

$predict = $model.Transform($TestSet)

$mlCOntext.BinaryClassification.Evaluate($predict, "Label")
```

**Comment by SteveL-MSFT** [comment]
I tried this and it repro'd.  Looking at the innerexceptions, it couldn't load the native library.  On my MacBook, I copied `libCpuMathNative.dylib` to the same location as `Microsoft.ML.CpuMath.dll` and this worked for me.

**Comment by vexx32** [comment]
Tack another one onto the list for native library loading issues, heh.

Wonder if you package this as a module if we start to hit issues similar to #9488 / #8861?

**Comment by mikeTWC1984** [comment]
Looks like that was it, thanks! It fixed the issue for both Powershell and Core if running on Windows as a script. I get some other error running it on WSL linux, I'll try actual linux machine later today. @vexx32  is right, it doesn't work as a module in Powershell Core (6.2) (getting original error), hope this issue will be fixed on the next release, ml stuff really need to be wrapped as a module to be useful.

**Comment by realpobblebonk** [comment]
If someone could better document the steps in the workaround it would be appreciated. Also has Microsoft acknowledged the issue or do we need to raise this somewhere else to get it on their radar.

**Comment by vexx32** [comment]
There is a workaround here now, but it does require a bit of finagling on the part of the module author.

https://github.com/PowerShell/PowerShell/issues/8861#issuecomment-599138174
