### ISSUE TITLE
Given that methods in custom classes do not support optional parameters (with default values), attempting to define them should fail

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#9684]
Note: If #9701 is implemented, this issue becomes moot.

# Steps to reproduce

```powershell
class Foo {
  # This method definition shouldn't be permitted, because optional parameters
  # aren't supported.
  [string] Bar($Baz = 'Bam') { return $Baz }
}
[Foo]::new().Bar()
```

# Expected behavior

The class definition should fail, given that optional parameters aren't supported.

# Actual behavior

The class definition succeeds, but the argument-less invocation of the method fails.

```none
Cannot find an overload for "Bar" and the argument count: "0".
```

# Environment data

```none
PowerShell Core 6.2.1
```

**Comment by iSazonov** [comment]
If we implement this error message it will 75% from implementing the feature :-)

**Comment by vexx32** [comment]
Yeah, in truth if we're going to be poking around here I'd rather we make this work properly.

**Comment by mklement0** [comment]
I didn't realize that was on the menu.

I'll have the feature then, please :)

**Comment by iSazonov** [comment]
Maybe reopen with the feature request?

**Comment by mklement0** [comment]
Good idea; please see #9701

**Comment by iSazonov** [comment]
@mklement0 Thanks! I think we can close the issue.
