### ISSUE TITLE
MacOS HomeBrew - should we have different casks for different releases?

### ISSUE THREAD

**Issue by glawrence** [PowerShell/PowerShell#9685]
# Summary of the new feature/enhancement

Recently @SteveL-MSFT made me aware of [PowerShell Core Support Lifecycle | Microsoft Docs](https://docs.microsoft.com/en-us/powershell/scripting/powershell-support-lifecycle?view=powershell-6#powershell-release-end-of-life) which I take to mean that both PowerShell Core 6.1.x and 6.2.x are current, supported releases. However up until now HomeBrew only has one cask, for the latest version, which does "feel" right and I know there are other open issue about preview releases, which is a different matter.

My query is this: with 6.1 and 6.2 supported and 7.0 coming soon, should we continue with one cask, for the latest version, or should we have a cask for every version that has not gone past its end-of-life date?

# Proposed technical implementation details (optional)

The proposal would be to have multiple casks, which I am happy to help with as I have updated the main one a couple of times. I am not sure how the naming would work for non-latest releases. Clearly I am happy to help be part of the solution to this but thought it right to raise a request so others can comment.

**Comment by SteveL-MSFT** [comment]
@glawrence there's currently two casks: main (stable) and preview.  In general, for every OS, we've been having two channels so this is consistent.  There isn't a separate channel for 6.1.x as 6.2.x is the newest stable release.

**Comment by glawrence** [comment]
Seems fine to me then. I assume we will move to 7.x when that releases and leave 6.x behind, which is fine by me. Thanks
