### ISSUE TITLE
Please tag v6.2.1 as latest release

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/PowerShell#9686]
We have automatic tools to download latest official release of PowerShell Core and 6.1.4 is tagged as latest instead of 6.2.1. Please update the tags.

*Edit:* Or 6.1.4 is the latest official release of PS Core?

# 6.1.4 is tagged as latest instead of 6.2.1:

![image](https://user-images.githubusercontent.com/16168755/58156965-a0aaa080-7c77-11e9-9a62-4f0cf0d4f41f.png)
![image](https://user-images.githubusercontent.com/16168755/58157103-eebfa400-7c77-11e9-96ac-c841f5668ea1.png)

**Comment by stknohg** [comment]
I have the same problem too. (https://github.com/stknohg/PSCoreUpdate/issues/2)
Please update the latest release.

**Comment by vexx32** [comment]
Probably not something they can really change after-the-fact; afaik that's just built into how Github handles releases. It's not looking at the release name. Both 6.2.1 and 6.1.4 are servicing releases handling the recently-filed CVE issues for 6.2 and 6.1; both were updated as both are still officially supported. I'm assuming the 6.2.1 was released first, probably only by a minute or two, but because the 6.1.4 was released after it, Github flags it as the "latest release".

**Comment by stknohg** [comment]
From GitHub [API doucument](https://developer.github.com/v3/repos/releases/#get-the-latest-release),

> The latest release is the most recent non-prerelease, non-draft release, sorted by the `created_at` attribute. The `created_at` attribute is the date of the commit used for the release, and not the date when the release was drafted or published.

Certainly we may not be able to do anything...

**Comment by vexx32** [comment]
The best thing to do, I think, would be to ask that the process for handling releases like this is to release the earlier version first.

What do you think, @TravisEz13?

**Comment by kborowinski** [comment]
@vexx32 That would be nice, otherwise I would have to rewrite update cmdlet and go through painfull change management process in my org

@stknohg Thanks for the link, good read.

**Comment by iSazonov** [comment]
We should update the 6.2.1 tag date
https://stackoverflow.com/questions/22822586/swap-latest-release-on-github

/cc @TravisEz13

**Comment by TravisEz13** [comment]
@iSazonov Force pushing a tag is technically very bad.  We have agreement on this thread to do it, but anyone that sync'ed the tag, will now have to deal with having a different version of history for that tag.

cc @adityapatwardhan @SteveL-MSFT 

We can try to update the process to prevent this is the future.

**Comment by iSazonov** [comment]
Is "Latest release" only GitHub feature? In the case we could ask GitHub team to enhance the feature for such cases.

**Comment by adityapatwardhan** [comment]
The issue has been fixed by deleting and re-pushing the tag. If you are seeing errors on `git fetch --tags` then please use `git fetch --tags --force`.
