### ISSUE TITLE
Why am I catching Inner Exceptions?

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#9689]
# Steps to reproduce

Find a pair of functions or cmdlets where one of them throws a given type of exception, and the other throws a _different_ exception type, but with the first type as an `InnerException`.  Now try to handle both exception types in one try/catch.

```powershell
using namespace System.Management.Automation

function ThrowsParameterBinding {
    [CmdletBinding()]param($FileName)

    $infe = [ItemNotFoundException]::new("File Not Found")
    $pbe =  [ParameterBindingException]::new( "FileName", $infe)
    throw $pbe
}

function ThrowsItemNotFound {
    [CmdletBinding()]param($Path)
    $infe = [ItemNotFoundException]::new("File Not Found")
    throw $infe
}

function Get-WorkDone {
    trap [ParameterBindingException] {
        "Do extra work to handle a ParameterBindingException" 
        continue
    }
    trap [ItemNotFoundException] {
        "Do extra work to handle an ItemNotFoundException"
        continue
    }

    "Do some initial work"
    ThrowsParameterBinding
    ThrowsItemNotFound
    "Do some cleanup"
}
```

# Expected behavior

```none
> Get-WorkDone
Do some initial work
Do extra work to handle a ParameterBindingException
Do extra work to handle an ItemNotFoundException
Do some cleanup
```

# Actual behavior

```none
> Get-WorkDone
Do some initial work
Do extra work to handle a ItemNotFoundException
Do extra work to handle an ItemNotFoundException
Do some cleanup
```

# Environment data

This has been like this forever, and it still happens in the latest PowerShell

If you're really careful, you can work around it by using `try { ... } catch { throw $_ }` which somehow normalizes things. See #6205

**Comment by JustinGrote** [comment]
I saw something similar with try/catch today. If you try to catch a .NET method exception and you specify the type, you get the innerexception rather than the methodexception
![image](https://user-images.githubusercontent.com/15258962/77578976-b475f300-6e96-11ea-9176-8e14b8c3886a.png)
