### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by jmorey4158** [PowerShell/PowerShell#9699]
# Documentation Issue

Compress-Archive
Issue: When using -Path parameter with shares, the share path is appended (without '\') to file names. 

For example, if archiving 'SomeInfo.txt' on share '\\myshare\somefolder', the resulting filename in the zip file is 'mysharesomefolderSomeInfo.txt'

Workaround: To resolve this, I used the -LiteralPathparameter instead.

**Comment by fMichaleczek** [comment]
@jmorey4158 The cmdlet Compress-Archive is part of the module Microsoft.PowerShell.Archive and has his own github repository : [github/Microsoft.PowerShell.Archive](https://github.com/PowerShell/Microsoft.PowerShell.Archive)
You should move your issue in this repo.
