### ISSUE TITLE
Enable PSRP to use a SSH Reverse Tunnel

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#9700]
# Summary of the new feature/enhancement

Today, PSRP over SSH is hard coded to establish a regular SSH connection.  This prevents scenarios of connecting to a machine behind a firewall that would otherwise be able to use a SSH Reverse Tunnel.

# Proposed technical implementation details (optional)

Need some PSSessionOptions to tell PSRP to do a second hop connection from the public ip to the reverse tunnel port along with any different credentials than those used from the initial hop to the gateway.

cc @TylerLeonhardt @PaulHigin

**Comment by TylerLeonhardt** [comment]
The important aspect of this is that PowerShell shouldn't be required on the jump box
