### ISSUE TITLE
Background job operator does not work when invoking a script block variable

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/PowerShell#9703]
When a variable with a script block is passed to a background job via `using`, the variable inside the job is a string instead of a script block.

As @bpayette [indicated below](https://github.com/PowerShell/PowerShell/issues/9703#issuecomment-495774758), this was by design to reduce the risk of accidentally executing code; however, this clearly seems like a design flaw now that we have the `&` background operator in PowerShell, and while it can be worked around, any code that works around it should be unnecessary. It is worth mentioning that the workaround demonstrated below would continue to work even if this bug was fixed because objects of type `scriptblock` convert implicitly to string, so the likelihood of this causing an issue for folks if it was fixed should be very low.

# Steps to reproduce

```powershell
Invoke-Pester -ScriptBlock {
    Describe 'Tests for using variables of specific types' -Tags 'CI' {
        It 'Implicit using with background job operator and variable of type ScriptBlock' {
            $sb = {Get-Process -Id $pid}
            $job = & $sb &
            $results = $job | Receive-Job -Wait
            $results | Should -BeOfType PSObject
            $results.PSTypeNames | Should -Contain Deserialized.System.Diagnostics.Process
        }
    }
}
```

### Expected behavior

```none
Tests Passed: 1, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0
```

### Actual behavior

```none
Tests Passed: 0, Failed: 1, Skipped: 0, Pending: 0, Inconclusive: 0
```

### Workaround

```PowerShell
Invoke-Pester -ScriptBlock {
    Describe 'Tests for using variables of specific types' -Tags 'CI' {
        It 'Implicit using with background job operator and variable of type ScriptBlock' {
            $sb = {Get-Process -Id $pid}
            $job = & ([scriptblock]::Create($sb)) &
            $results = $job | Receive-Job -Wait
            $results | Should -BeOfType PSObject
            $results.PSTypeNames | Should -Contain Deserialized.System.Diagnostics.Process
        }
    }
}
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by bpayette** [comment]
This is (or was)  by design. IIRC we serialize scriptblocks to strings in flight to reduce the risk of accidentally executing code. The problem was that, when trying to secure a remote endpoint, there were so many places that scriptblock parameters could automatically get executed we just blocked everything. Since you can explicitly turn a string into a scriptblock with `[ScriptBlock]::Create()` (but not with a cast!) it was viewed as being not too onerous. Of course this doesn't really make sense for background jobs so maybe we should reconsider our strategy here :-)

**Comment by KirkMunro** [comment]
Thanks for the background, @bpayette, that makes sense. I agree the strategy doesn't seem appropriate when running a background job that invokes an anonymous function.

Aside: I really dislike "ampersand background operator" as an operator name. Why can't it just be called the "background operator" or the "run in background operator". Why include the glyph itself in the operator name? Other PowerShell operators generally aren't named that way.

**Comment by KirkMunro** [comment]
I'm going to update the title and description so that this focuses specifically on use of the `&` background operator, since that is what needs revisiting.
