### ISSUE TITLE
Unblock-File fails silently 

### ISSUE THREAD

**Issue by lanatmwan** [PowerShell/PowerShell#9707]
In Windows PowerShell 5.1 this command will unblock files as expected:

gci C:\Users\myUser\OneDrive\Documents\foodir -Recurse -File | unblock-file  

However, on the same machine, PowerShell 6.2.1 does not perform the unblock or give any indication of a problem.

**Comment by fMichaleczek** [comment]
I try :
- download a blocked file ( https://notepad-plus-plus.org/repository/7.x/7.7/npp.7.7.Installer.x64.exe )
- create a subfolder foodir in my OneDrive directory
- move the blocked file to 'foodir'
- verify the file is blocked => True
- Enter the same command 'gci C:\Users\XXX\OneDrive\Documents\foodir -Recurse -File | unblock-file'
- verify the file is unblocked => True

I can't reproduce your issue. ( Windows 10 1809/17763.475 + PS 6.2.1)

Please provide more informations to reproduce your issue.

**Comment by iSazonov** [comment]
Could you check that 
`gci C:\Users\myUser\OneDrive\Documents\foodir -Recurse -File`
has any output?

**Comment by lanatmwan** [comment]
My apologies, the silent failure is only when not elevated, which I think is the same (unfortunate) behavior as 5.1. 

Name                           Value
----                           -----
PSVersion                      6.2.1
PSEdition                      Core
GitCommitId                    6.2.1
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by iSazonov** [comment]
@lanatmwan Feel free to contribute.
