### ISSUE TITLE
Proxy support for Non Windows Powershell

### ISSUE THREAD

**Issue by JaiGaneshCode** [PowerShell/PowerShell#9721]
I am trying to open a New-PSSession to ConnectionURI "https://outlook.office365.com/powershell-liveid/" from my Ubuntu or CentOS machine which is behind a proxy. 
For this command I am unable to set proxy using the PSSessionOptions and cmdlet ProxyAccessType, ProxyAuthentication and ProxyCredentials.
As my machine is behind a Proxy server and all outgoing connections must pass through the proxy machine, I get MI_RESULT_FAILED error mentioning error connecting to remote server.

Please help me out on this.

**Comment by iSazonov** [comment]
You could try to use PSSessionOption https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/new-pssessionoption?view=powershell-6

**Comment by iSazonov** [comment]
@PaulHigin Could you please comment the issue about proxy support in New-PSSession cmdlet?

**Comment by JaiGaneshCode** [comment]
I tried the ProxyAccessType on Ubuntu and CentOS with powershell 6.0.4, 6.2.0 but got the error saying ProxyAccessType is not recognized in New-PSSessionOptions.

**Comment by peacand** [comment]
I'm also interested by this feature. Is there any way to make New-PSSession going through a proxy with Powershell Core on Linux ?

**Comment by peacand** [comment]
It is exactly for Azure scenarios that I would like to use it  ;-). To connect to Exchange Online powershell from Linux through a HTTP proxy.

**Comment by PaulHigin** [comment]
"I get MI_RESULT_FAILED error mentioning error connecting to remote server."

It looks like WinRM/OMI implementation does not support proxies.

**Comment by SteveL-MSFT** [comment]
Since OMI is no longer being developed and needed for non-Windows WSMan support, it's unlikely we'll get proxy support for non-Windows.

**Comment by peacand** [comment]
For those who might need to use New-PSSession on Linux through a HTTP proxy, you can use the project Proxychains which hooks transparently TCP connection from any binary through a SOCKS or HTTP proxy. I tested with pwsh, it works well  :-)

[https://github.com/haad/proxychains](https://github.com/haad/proxychains)


<blockquote><img src="https://avatars0.githubusercontent.com/u/67790?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/haad/proxychains">haad/proxychains</a></strong></div><div>proxychains - a tool that forces any TCP connection made by any given application to follow through proxy like TOR or any other SOCKS4, SOCKS5 or HTTP(S) proxy.  Supported auth-types: &quot;user/pa...</div></blockquote>

**Comment by spKhan00** [comment]
@JaiGaneshCode  Is this issue fixed?? I am having the same problem.
