### ISSUE TITLE
Optionally ignore class attribute errors

### ISSUE THREAD

**Issue by mikeTWC1984** [PowerShell/PowerShell#9725]
# Summary of the new feature/enhancement

Currently, if script has class attributes PS is parsing them first, so if assembly containing attribute definition is not loaded it will block the script. So you either need to load them manually first, or  create 2 scripts or load assembly in profile. Would be nice to make it work without extra hacks.

# Proposed technical implementation details (optional)
Any of below would work

- Just ignore class attribute errors (only catch error at runtime)
- Have some statement to ignore those errors
- Have script execute Using prior resolving attributes

# Sample

Just a sample of the script. It will crash until you manually  execute Add-Type or Using
```powershell
 # Add-Type -path ".\bin\*.dll"

Using module ModuleHavingAssemblies
Using namespace Microsoft.ML.Data

class SentimentData {
 [LoadColumn(0)][String]$SentimentText
 [LoadColumn(1)][ColumnName("Label")][Boolean]$Sentiment
}

class SentimentPrediction {
[ColumnName("PredictedLabel")][Boolean]$Prediction
[Double]$Probability
[Double]$Score
}
```

**Comment by iSazonov** [comment]
@mikeTWC1984 Thanks for your contribution! 
It is dup #3641 - please discuss there.
