### ISSUE TITLE
Feature Request: "Open here" Takes Three Steps to Execute (Too Slow)

### ISSUE THREAD

**Issue by ryanelian** [PowerShell/PowerShell#9738]
# Summary of the new feature/enhancement

![image](https://user-images.githubusercontent.com/8892187/58434066-15506580-80e4-11e9-94a9-7e68f7d4e1f0.png)

Old Powershell can be invoked in two steps by using:
- SHIFT key (left hand) + Right click (right hand)
- Clicking "Open Powershell window here"

The new Powershell needs to be invoked using three steps by:
- Right clicking
- Then hovering the mouse to the PowerShell 6 dropright. **THEN PAUSING MOMENTARILY UNTIL THE MENU APPEARS!!!**
- Then clicking the "Open here"

This quirk makes Powershell 6 literally unplayable for me.

# Proposed technical implementation details (optional)

Take the "Open here" and "Open here as Administrator" out of the dropright menu.

So that Powershell 6 can be invoked in two steps.

Alternatively, make the original "Open Powershell window here" opens Powershell 6 please.

**Comment by paulschmeida** [comment]
While grouping Powershell options into a submenu might make it "literally unplayable" for you, some people play other games too and for them this is a better and more logical approach. I would like my context menu to fit on my screen.
