### ISSUE TITLE
Can pscore support powershell-style spawning?

### ISSUE THREAD

**Issue by 573** [PowerShell/PowerShell#9744]
# Steps to reproduce

```powershell
$ pwsh.exe -Command Start-Process -Wait -NoNewWindow pwsh.exe -ArgumentList 'Get-Help'
The argument 'Get-Help' is not recognized as the name of a script file. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

# Expected behavior
The commands output being (truncated)
```none

TOPIC
    PowerShell Help System

SHORT DESCRIPTION
    Displays help about PowerShell cmdlets and concepts.

LONG DESCRIPTION
    PowerShell Help describes PowerShell cmdlets,
```

# Actual behavior
The commands output being
```none
The argument 'Get-Help' is not recognized as the name of a script file. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

# Environment data

```none

Name                           Value
----                           -----
PSVersion                      6.2.1
PSEdition                      Core
GitCommitId                    6.2.1
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
`pwsh` now default to `-File` rather than to `-Command`, which is why you must include `-Command` in your `-ArgumentList` in order for `Get-Help` to be interpreted as a a _command_ rather than a _script file_:

In order to do that, additionally enclose the entire original `-Command` argument in `"..."`:

```powershell
pwsh -Command "Start-Process -Wait -NoNewWindow pwsh -ArgumentList '-Command', 'Get-Help'"
```

**Comment by 573** [comment]
So what you're saying is, there is basically no way to fully translate, i. e. the following pre-pscore expression without much adding quotes (note the powershell.exe instance)?

    pwsh.exe -NoProfile -Command "Start-Process" -Wait -NoNewWindow powershell.exe -ArgumentList 'Set-ClipboardText','-Value','$(([string](pwsh" "-Command" "Get-ClipboardText)).Replace(''" "'',''\\" \\"''))'

Have this to translate a list of full paths to files in Intellij to a format needed by some app. The problem with adding more double quotes here is, that Intellij applies some semantics already a bit different to what one expected would a different shell be used instead of powershell.
