### ISSUE TITLE
CHANGELOG out of date

### ISSUE THREAD

**Issue by jzabroski** [PowerShell/PowerShell#9750]
Only lists PowerShell 6.2; does not list 6.2.1

**Comment by TravisEz13** [comment]
6.1.4 was missed too.

**Comment by TravisEz13** [comment]
@jzabroski 	Thanks for pointing this out.

**Comment by jzabroski** [comment]
@iSazonov - @msftbot is somewhat lying to me.  CHANGELOG.md and releases are not in sync.  Poignantly, I expect master branch CHANGELOG.md to contain the rolling changelog across all releases, so you can easily grep it and/or scroll to see what changes impact you as you upgrade.
