### ISSUE TITLE
MSI generation script should get the version number dynamically

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#9763]
# Steps to reproduce

Fault code: 
https://github.com/PowerShell/PowerShell/blob/87e6e74ca96f59dacc1d4d3933c6cb843dea8ea0/tools/packaging/packaging.psm1#L2611

# Expected behavior

Value should not be hard coded.

# Actual behavior

Value hard coded to '6'.

# Environment data

N/A

**Comment by iSazonov** [comment]
We already have this in csproj
https://github.com/PowerShell/PowerShell/blob/87e6e74ca96f59dacc1d4d3933c6cb843dea8ea0/PowerShell.Common.props#L40-L48

@daxian-dbw stopped me from injecting this values in code :-) until better times.
