### ISSUE TITLE
Re-enable CodeFactor

### ISSUE THREAD

**Issue by vexx32** [PowerShell/PowerShell#9764]
# Summary of the new feature/enhancement

@daxian-dbw mentioned in the most recent PS Community call that CodeFactor was not disabled intentionally, there was simply something in the way the Github integration works that automatically disables it after a certain period of time.

Would be great to have it back, as it was good for style recommendations and had a lot less false positives than Codacy does in certain portions of the code base.

/cc @iSazonov

**Comment by iSazonov** [comment]
I like using CodeFactor in the repo too. 
It helped us remove most of the style issues that were especially annoying while reviewing PRs.

**Comment by RDIL** [comment]
It's back

**Comment by vexx32** [comment]
Excellent, thanks everyone! :blush:
