### ISSUE TITLE
Invoke-RestMethod does not return response headers 

### ISSUE THREAD

**Issue by jianyunt** [PowerShell/PowerShell#9769]
# Background
I am  responding my client request with 401 and sending back respond header with WWW-Authenticate: basic realm="apps" by following https://tools.ietf.org/html/rfc7235#section-4.1.
I can test it using postman. But I cannot use invoke-RestMethod because it does not return anything while 401.

# Steps to reproduce

```powershell
Invoke-RestMethod -Method Get -uri http://www.bing.comcomcomc -ResponseHeadersVariable aa
$aa      # it's empty

```

# Expected behavior

headers should be displayed even if server response with error code. 

# Actual behavior

headers are empty if server responses with 401.

# Environment data

6.1

**Comment by jianyunt** [comment]
Add @adityapatwardhan

**Comment by vexx32** [comment]
It's probably just a typo in the issue but just in case -- your code sample shows you're setting the headers to `aa` and then retrieving the variable `$dd`?

**Comment by jianyunt** [comment]
thanks @vexx32 ! I fixed the typo in the repo.

**Comment by kilasuit** [comment]
I can't repro this in 7-preview1 or 6.2.0 when running the below working code

```PowerShell
Invoke-RestMethod -Method Get -uri http://www.bing.com -ResponseHeadersVariable aa
$aa 
```

**Comment by vexx32** [comment]
@kilasuit that's not a `401` response from the server though, right?

**Comment by jianyunt** [comment]
@kilasuit  yes, it works for happy cases. Try the uri with error.  
Invoke-RestMethod -Method Get -uri http://www.bing.comdddddd -ResponseHeadersVariable aa
In my case, I need to challenge client with 401 and expect client send me auth token, stuff.

**Comment by markekraus** [comment]
a 401 response is treated a failed response and we do not populate the headers on fail responses. However, this would be worked around if we implement this https://github.com/PowerShell/PowerShell/issues/5555#issuecomment-489849231

**Comment by felixfbecker** [comment]
You can get the response headers from the error:
```powershell
try {
  Invoke-RestMethod '...'
} catch [Microsoft.PowerShell.Commands.HttpResponseException] {
  $_.Exception.Response.Headers.WwwAuthenticate
}
```
`Headers` is a [`System.Net.Http.Headers.HttpResponseHeaders`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.headers.httpresponseheaders?view=netcore-2.2) object.
See also https://docs.microsoft.com/en-us/dotnet/api/microsoft.powershell.commands.httpresponseexception?view=pscore-6.2.0.

**Comment by glawrence** [comment]
I have been struggling with this, note that [httpbin.org](https://httpbin.org/#/Status_codes) is very handy for testing and that $_.Exception.Response.StatusCode.value__ seems to work on PowerShell 6.2.1 and 4.0. However I agree with others this should be easier especially with 2xx codes

**Comment by nmflavio** [comment]
Try this one:

$resp = try { Invoke-RestMethod -Method Get -uri http://example.com/notfound } catch { $_.Exception.Response.Headers.ToString() }

PS C:\Users\Administrator> $resp
Content-Length: 94741
Cache-Control: private
Content-Type: text/html; charset=utf-8
Date: Thu, 31 Oct 2019 13:35:17 GMT

**Comment by SteveL-MSFT** [comment]
This should also be addressed by https://github.com/PowerShell/PowerShell/pull/10466
