### ISSUE TITLE
Get-Random will not select an object from the input set more than once

### ISSUE THREAD

**Issue by pinecones-sx** [PowerShell/PowerShell#9774]
Get-Random is the cmdlet to produce a random number.  You can also use it to produce multiple random selections from an input set.

The issue is that in this scenario, its behavior is not random.  Instead it will select individual objects from the input object a maximum of 1 time.

While this is a nice feature to have, it is not truly random and is unexpected behavior.  I am recommending to make the results truly random and to add unique selection as an optional switch.  (such as -Unique)

# Steps to reproduce

```powershell
$sourceSet = 0..1
While ($sourceSet[0] -ne $sourceSet[1]){
    $sourceSet = Get-Random -InputObject @(0..1) -Count 2
}
```

# Expected behavior

```none
Loop ends with $sourceSet -eq 1,1 or $sourceSet -eq 0,0
```

# Actual behavior

```none
Loop runs indefinitely.
```

# Environment data

```none
Name                           Value                                                                                                                                                               
----                           -----                                                                                                                                                               
PSVersion                      5.1.17763.503                                                                                                                                                       
PSEdition                      Desktop                                                                                                                                                             
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                             
BuildVersion                   10.0.17763.503                                                                                                                                                      
CLRVersion                     4.0.30319.42000                                                                                                                                                     
WSManStackVersion              3.0                                                                                                                                                                 
PSRemotingProtocolVersion      2.3                                                                                                                                                                 
SerializationVersion           1.1.0.1    
```

**Comment by kvprasoon** [comment]
Provided the `-Count` option, this scenario is valid and should give non unique values. As suggested, adding `-Unique` will be an add-on.

**Comment by iSazonov** [comment]
@kvprasoon I feel the issue is more difficult. Original behavior is "randomize an entire collection", and the proposal is "random selection from a collection". Current parameter sets and names do not clarify this enough. I'd want to see more use-cases and more analysis. Also proposal Unique is a breaking change.

**Comment by kvprasoon** [comment]
I would say it should be _random selection from a collection_ than _randomize an entire collection_

From documentation.

> The Get-Random cmdlet gets a randomly selected number. If you submit a collection of objects to Get-Random, it gets one or more randomly selected objects from the collection.

**Comment by vexx32** [comment]
That phrasing does seem more accurate. Given the wording in the current documentation it sounds as though the current behaviour was somewhat intentional for whatever reason

We can avoid this being a breaking change if we invert the logic and name the switch something like `-AllowDuplicates` perhaps? The default stays the same, but users can opt in to the new behaviour if they want it?

**Comment by iSazonov** [comment]
AllowDuplicate does not make the behavior intuitive.
Current behavior is "randomize collection from pipeline or InputObject". So parameter name for this could be `RandomizeCollection`/`RandomizeInput`/`Randomize`. But we need _another_ behavior - I don't know that is right (math) term would be. `RandomAccess`/`RandomInputAccess` or `AsRandomSet`. I like the last

**Comment by vexx32** [comment]
I don't think any of those appropriately describe what's going on here, though, unfortunately. @SteveL-MSFT any naming suggestions, perhaps? I'm not coming up with much at the moment. 😄

**Comment by pinecones-sx** [comment]
I really think real random selection should be a switch, and just call it a day.

That keeps it from being a breaking change and makes it discoverable.

**Comment by SteveL-MSFT** [comment]
So I understand the problem correctly, `-Count` today selects n number of items at once so you will never get duplicates.  Useful for drawing raffles, for example.

However, the ask is a way to have a switch to allow selecting n number of items where each draw is distinct such that you could end up with duplicates.  And you don't want to do this with an outer loop calling the cmdlet.  I guess `-AllowDuplicate` would be the first thing I can think of.

**Comment by pinecones-sx** [comment]
Correct.

The issue is that it isn't just returning a random selection, it is returning a random selection and removing it from the collection.

It's not just about not wanting to get results in a different way, it is that the cmdlet itself works in a way that is misleading.  If you are using it with a collection of objects, it isn't operating in a truly random way.

**Comment by SteveL-MSFT** [comment]
[here](https://github.com/PowerShell/PowerShell/blob/aba3bd5df1ea9d97790e7b232e50995e9f3d1e37/src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetRandomCommand.cs#L534) in the code is where it explicitly removes the selected item from being considered next time.  This is how Windows PowerShell also works, so if the current behavior is not documented well, we should update the documentation.  If there is a need to add a switch to change this behavior, that would be acceptable as well.
