### ISSUE TITLE
7.0 preview installer is setting the wrong path for the PATH environment variable. (on Windows)

### ISSUE THREAD

**Issue by st0le** [PowerShell/PowerShell#9776]
# Steps to reproduce
Install the Powershell 7.0 Preview 1 on Windows. (install with defaults)

# Expected behavior

```none
PATH should have C:\Program Files\PowerShell\7-preview\
```

# Actual behavior

```none
PATH contains C:\Program Files\PowerShell\7-preview\preview
```
Here's the path after running installing it in Sandbox (saw the same issue on my devbox)
![image](https://user-images.githubusercontent.com/3803209/58674649-a18da300-8305-11e9-8722-8239d2d64f77.png)

**Comment by iSazonov** [comment]
@bergmeister Can you confirm the issue?

**Comment by GoateePFE** [comment]
I can confirm this is still an issue in 7.0.0-preview.6 @iSazonov

**Comment by SteveL-MSFT** [comment]
This is actually intended as the `pwsh-preview.cmd` batch file resides there while the real `pwsh.exe` is in the parent folder.  By changing the path to the parent, `pwsh` will start the last one instead of always the stable one.
