### ISSUE TITLE
Compress-Archive does not return the reported type

### ISSUE THREAD

**Issue by figueroadavid** [PowerShell/PowerShell#9777]
This issue is present in Powershell 5.1, and 6.2.1 (verified)
The help for Compress-Archive shows that the output is system.io.fileinfo.  However, when a zip file is successfully created, there is no output. 
Either the help should be updated, or the system.io.fileinfo object should be produced.  The preference is that the object gets produced.  

# Steps to reproduce

```powershell
help Compress-Archive -full
PS C:\> compress-archive -path c:\demo -destinationpath c:\demo.zip
```

# Expected behavior

```
PS C:\> compress-archive -path c:\demo -destinationpath c:\demo.zip
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       05/30/2019  10:56 PM           3686 demo.zip

```

# Actual behavior

```
PS C:\> compress-archive -path c:\demo -destinationpath c:\demo.zip
PS C:\>
```

# Environment data

```
Name                           Value
----                           -----
PSVersion                      6.2.1
PSEdition                      Core
GitCommitId                    6.2.1
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
@figueroadavid as with some other file-handling cmdlets (e.g., `Rename-Item`) it appears `Compress-Archive` does not create output by default and requires that you use `-PassThru` to do so.

That said, I don't think that module is maintained in this repo itself; I'm actually surprised this doesn't behave like `New-Item` as well, actually, but you might submit that as a request on the [Microsoft.PowerShell.Archive](https://github.com/PowerShell/Microsoft.PowerShell.Archive) repo. 🙂
