### ISSUE TITLE
Help command in PS 6.2.1 has a non-functional -ShowWindow parameter

### ISSUE THREAD

**Issue by figueroadavid** [PowerShell/PowerShell#9778]
# Steps to reproduce

```powershell
help Compress-Archive -ShowWindow
#works with any command, not just Compress-Archive
```

# Expected behavior

```powershell
help Compress-Archive -ShowWindow
#expect a new window to pop up displaying the help for the cmdlet.
#Since this is really a Windows platform thing, then it would be ok if this parameter simply was not there

```

# Actual behavior

```powershell
PS C:\Program Files\PowerShell\6> help Compress-Archive -ShowWindow
Get-Help : A parameter cannot be found that matches parameter name 'ShowWindow'.
At line:64 char:22
+     $help = Get-Help @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Get-Help], ParameterBindingException
+ FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.GetHelpCommand

```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.1
PSEdition                      Core
GitCommitId                    6.2.1
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
Is this present on the full `Get-Help` cmdlet as well, or only on the `help` short function? I remember you said that the parameter was coming up from tab completion he's.ite the engine saying it's not there, so I wonder if it's just been left behind on the `help` function.

**Comment by figueroadavid** [comment]
You are correct.. it is generating from `help` but not from `get-help`.  
So.. should this issue be moved back to the main thread to update the `help` command?

**Comment by vexx32** [comment]
Not sure, actually. Is this mentioned in that thread? /cc @SteveL-MSFT I know you've been poking at Out-GridView already a bit, is this one on your radar?

**Comment by doctordns** [comment]
This parameter is removed in PowerShell 7 (preview 1). 

But if @Stevel-MSFT does have returning the parameter and getting it to work (even if Windows only for now) - that would be nice!

**Comment by SteveL-MSFT** [comment]
Since WPF only works on Windows, bringing this back means we should have a cross platform solution.  Perhaps render as HTML and present in browser might be viable.
