### ISSUE TITLE
window width wirth bash on ubuntu

### ISSUE THREAD

**Issue by jackasser** [PowerShell/PowerShell#9781]
# Steps to reproduce

```powershell
command bash
```

# Expected behavior

```none
start with same width window
```

# Actual behavior

```none
change window's width.
```

# Environment data

```none
windows10 PRO
```

**Comment by BrucePay** [comment]
@jackasser On what version of PowerShell are you seeing this issue?

**Comment by jackasser** [comment]
@BrucePay 
This is my version.
PSVersion                      5.1.17763.503
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.503
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by vexx32** [comment]
Can you try with the latest PowerShell release from [here](https://github.com/PowerShell/PowerShell/releases/tag/v7.0.0-preview.1) please?

5.1 isn't supported for this repo, and a _lot_ of bugs have been fixed since 5.1 is released. 🙂

**Comment by jackasser** [comment]
@vexx32 
Thank you for your infomation!!
how to install from [here](https://github.com/PowerShell/PowerShell/releases/tag/v7.0.0-preview.1)??

**Comment by vexx32** [comment]
Scroll to the bottom of the changelog, and under Assets select the version that you'd like to get. Both x86 and x64 versions are available for Windows, and you can grab either the .zip or the installer .msi as you prefer. :)

**Comment by jackasser** [comment]
I install ver.7.0.0
but not fixe
