### ISSUE TITLE
Add .CPL back to $env:PathExt

### ISSUE THREAD

**Issue by brwilkinson** [PowerShell/PowerShell#9797]
Is it possible to add in the .CPL pathext ?

I use this frequently for launching control panel items.

e.g.
appwiz
sysdm

# Windows PowerShell

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.18908.1000

ls env:pathext

Name                           Value
----                           -----
PATHEXT                        .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
```

# Actual behavior

```Powershell
 $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.1

ls env:pathext

Name                           Value
----                           -----
PATHEXT                        .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
```

The ENV:Pathext was already removed on linux, so I hope Windows should still have .CPL.

- Do not add `PATHEXT` environment variable on Unix (#7697)

**Comment by iSazonov** [comment]
You could directly add new value to PATHEXT environment variable. Why must pwsh do this internally?

**Comment by brwilkinson** [comment]
This currently gets added in windows powershell, without it, it's a breaking change.




Ben Wilkinson


(cell): +1 917 843 7243


Sent from Windows 10







On Mon, Jun 3, 2019 at 4:13 AM -0600, "Ilya" <notifications@github.com> wrote:












You could directly add new value to PATHEXT environment variable. Why must pwsh do this internally?

**Comment by iSazonov** [comment]
I don't know history why it was removed.
/cc @SteveL-MSFT

**Comment by SteveL-MSFT** [comment]
This was inadvertently removed as part of https://github.com/powershell/powershell/pull/4942.  Since this is a break from WinPS, we should put it back.
