### ISSUE TITLE
InvokeCommandCmdlet.cs is actually for invoke-expression cmdlet

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#9807]
The code within https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Utility/commands/utility/InvokeCommandCmdlet.cs is actually for invoke Expression & this seems counter intuitive and perhaps an incorrect oversight.

Should this file be aptly renamed?

**Comment by vexx32** [comment]
Yes please!

The fewer misnamed files the better! 😄

**Comment by TravisEz13** [comment]
CodeCleanup is an enhancement.
