### ISSUE TITLE
Feature Request: Enable code style formatting in CI

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#9819]
# Summary of the new feature/enhancement

We have closed on stylecop rules.  We should runa code formatter on the code base to apply the single style and immediately enable code formatting in CI so style is no longer a PR review discussion.

# Proposed technical implementation details (optional)

**Comment by iSazonov** [comment]
We did run CodeFormatter over all code base. It do not fix all that we need.

**Comment by SteveL-MSFT** [comment]
Closing as dupe of https://github.com/PowerShell/PowerShell/issues/4708
