### ISSUE TITLE
Request -- Add image path to get-service and get-process

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#9826]
Sometimes it does is a good idea to know the image path when using get-service and get-process.

![image-path](https://user-images.githubusercontent.com/36788337/58935224-755ba180-879f-11e9-95a3-25f17bd3cac9.png)

U may ask why I do not use bellow cmdlet directly , but I think get-process and get-service is much easier.

Get-WmiObject win32_service | select Name, DisplayName, State, PathName | ft -AutoSize
Get-CimInstance -ClassName win32_service | select Name, DisplayName, State, PathName | ft -AutoSize

**Comment by iSazonov** [comment]
It is dup #3322
