### ISSUE TITLE
Publish PowerShell (Core) to Windows Store

### ISSUE THREAD

**Issue by pronichkin** [PowerShell/PowerShell#9827]
Right now it appears that [Python has an advantage](https://devblogs.microsoft.com/python/python-in-the-windows-10-may-2019-update/) over PowerShell (Core) because:

- Python is published to Windows Store
- You can open deep link to the store natively by typing "python" in cmd

PowerShell (Core) currently has neither of these benefits. This is upsetting—especially if we want to eventually displace Windows PowerShell with it.

Publishing to Windows Store would also aid frequent automatic updates, which is important for the Betas, I suppose.

**Comment by vaylen** [comment]
because fuck u thats why

**Comment by kilasuit** [comment]
@pronichkin this has been asked for before so I've linked this issue to another 2 where install/update threads have been prior discussed  

for a larger background please see - https://github.com/PowerShell/PowerShell/issues/8663#issuecomment-456272838
