### ISSUE TITLE
Are the Utils PowerShell Core Depends on in Linux managed and published?

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/PowerShell#9830]
The Get-Help on Linux Depends on "less" command - this is an Amazon Linux 2 container (which - as provided by AWS - has a completely minimalized package footprint) and I get this error:
![image](https://user-images.githubusercontent.com/11597190/58968131-826a9780-8783-11e9-9a8e-458b6c99c381.png)

This raises the questions:
- is there a managed list of what PowerShell core assumes is on the system?
- shouldn't the packages for PowerShell Core check for and resolve these dependencies if system commands depend on them?
- or should it just not depend on any OS packages?

Apologies if this is covered somewhere - if so, please drop a link in this issue :)

**Comment by vexx32** [comment]
I have raised a concern related specifically to the availability of `less` here before: 

https://github.com/PowerShell/PowerShell/issues/7851

FWIW it's not `Get-Help` that has this dependency; it's the `help` function, which is actually a function and not a true alias. `Get-Help` on its own normally does not provide paging.

**Comment by SteveL-MSFT** [comment]
It seems we can resolve this by checking if `less` is available before using it.  Otherwise, see if `more` is available.  If neither, then don't page.

**Comment by iSazonov** [comment]
It seems we already check if `less` or another pager present.
