### ISSUE TITLE
Maintain a PSScriptAnalyzer Profile for PowerShell 7 for Windows AND Linux THROUGHOUT Preview Releases

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/PowerShell#9831]
# Summary of the new feature/enhancement

Maintain PowerShell 7 Compatibility Profiles (https://github.com/PowerShell/PSScriptAnalyzer/tree/development/PSCompatibilityCollector/profiles) throughout the preview release phase so that everyone can easily understand how the releases are making progress to supporting their existing PowerShell code.

It might actually also help generate knowledge about what needs addressing before a GA release.

While it is understood that these would eventually be made available - this issue is to lobby for these profiles to become a deliberate and managed part of each agile iteration of PowerShell 7.

# Proposed technical implementation details (optional)

Brainstorm and scope what these profiles should cover.
Release a set of PowerShell 7 compatibility profiles with each preview release.

/cc @joeyaiello @SteveL-MSFT

**Comment by SteveL-MSFT** [comment]
Interesting idea.  cc @rjmholt

**Comment by rjmholt** [comment]
Yeah good idea!

For now they should go [here](https://github.com/PowerShell/PSScriptAnalyzer/tree/development/PSCompatibilityCollector/optional_profiles) (the profiles folder ships with PSSA and I already doubled the size of the module).

We should implement https://github.com/PowerShell/PSScriptAnalyzer/issues/1148 to really deliver this.

**Comment by DarwinJS** [comment]
Glad there is some energy around it!

You guys might already be thinking this, but if the ScriptAnalyzer itself is a different dev team, I would say the PowerShell team should own the initiative on developing the PowerShell 7 data files - even if in the other repo - so that the objective of keeping high customer value by having it keep pace with the functional improvements in each sprint is realized.

**Comment by DarwinJS** [comment]
msftbot seems to be miserly on closing issues eh?
