### ISSUE TITLE
Allow PSTypeConverter to convert to string

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#9836]
# Summary of the new feature/enhancement

Currently registering a PSTypeConverter that converts to string doesn't do anything.
Any defined functionality is ignored for `value.ToString()`.

An example to try out:

```csharp
using System;
using System.ComponentModel;
using System.IO;
using System.Management.Automation;

[TypeConverter]
public class DirectoryInfoTypeConverter : PSTypeConverter
{
    public override bool CanConvertFrom(object source, Type type)
    {
        return source.GetType() == typeof(DirectoryInfo)
            && type == typeof(string);
    }

    public override object ConvertFrom(object source, Type type, IFormatProvider fp, bool ignoreCase)
    {
        return "moo";
    }

    public override bool CanConvertTo(object source, Type type)
    {
        return source.GetType() == typeof(DirectoryInfo)
            && type == typeof(string);
    }

    public override object ConvertTo(object source, Type type, IFormatProvider fp, bool ignoreCase)
    {
        return "moo";
    }
}
```

```powershell
Update-TypeData -TypeConverter DirectoryInfoTypeConverter -TypeName System.IO.DirectoryInfo

(gi .) -as [string]
```

Compare this to if you change the original converter to:

```csharp
[TypeConverter]
public class DirectoryInfoTypeConverter : PSTypeConverter
{
    public override bool CanConvertFrom(object source, Type type)
    {
        return source.GetType() == typeof(DirectoryInfo)
            && type == typeof(int);
    }

    public override object ConvertFrom(object source, Type type, IFormatProvider fp, bool ignoreCase)
    {
        return 33;
    }

    public override bool CanConvertTo(object source, Type type)
    {
        return source.GetType() == typeof(DirectoryInfo)
            && type == typeof(int);
    }

    public override object ConvertTo(object source, Type type, IFormatProvider fp, bool ignoreCase)
    {
        return 12;
    }
}
```

This is actually already [a uservoice issue](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/16972927-custom-pstypeconverter-cannot-be-used-to-convert-o).

# Proposed technical implementation details (optional)

We should discuss how this code:

https://github.com/PowerShell/PowerShell/blob/f5e3de036e84f37820eb1dac635c337f8fc17718/src/System.Management.Automation/engine/LanguagePrimitives.cs#L5620-L5652

could be changed. Clearly PowerShell currently has a set of types where the language type conversion takes precedence, and it's not clear why that's not configurable. Inserting a type converter lookup as the first call would not break most cases, but could break some things.

Also that `if`/`else` cascade needs a serious refactor...

**Comment by rjmholt** [comment]
(Looked into this as a workaround for https://github.com/PowerShell/PowerShell/issues/9800)

**Comment by iSazonov** [comment]
Could you please add working sample? I can not compile with Add-Type.

**Comment by BrucePay** [comment]
@rjmholt We were pretty careful to not prioritize conversions to string since anything can be converted to string and so that conversion will **always** succeed. It's the "gray goo" of type conversions. Also the type conversion algorithm is intended to be reasonable i.e. you should be able reason about what will happen or at least be able to understand why a particular conversion was chosen after the fact. Making the conversion order mutable makes it much harder to reason about.

**Comment by rjmholt** [comment]
> Could you please add working sample? I can not compile with Add-Type.

@iSazonov Just for you I've added the usings

**Comment by rjmholt** [comment]
@BrucePay yeah I suspected the current order was quite deliberate and I understand the reasoning.

My counterpoints would be:
- I want this converter because the grey goo has failed - .NET changed a `ToString()` behaviour.
- I'd argue that having a type conversion order that's fixed for some types and not for others is more complex than having one simple algorithm for finding a type converter (and having a mechanism to register, query and unregister your own)
- I'd characterise the conversion order itself as immutable (you can't change the algorithm) but custom converter registration as mutable -- which I feel would be a simple single point of configuration
- PSTypeConverters feel obscure enough to me (I don't think they're documented) that they can be considered something of an expert feature, like AssemblyLoadContext manipulation. So I think we should let people shoot themselves in the foot with them (but provide easy ways to disarm...)

**Comment by lzybkr** [comment]
As it is today, a `TypeConverter` only come into play if there are no language defined conversions.

Allowing a `TypeConverter` before other conversions would make PowerShell less reliable - it would be impossible to reason about conversions (not that it's easy now) because you literally no longer control conversions at all - anyone could define a type converter that takes over any conversion.  I can easily see it being abused for nefarious purposes.
