### ISSUE TITLE
SOAP support in all platforms

### ISSUE THREAD

**Issue by Sarafian** [PowerShell/PowerShell#9838]
# Summary of the new feature/enhancement

Currently, the only way to consume a SOAP API from PowerShell 6 or higher, is to render manually the XML envelopes and do a POST with `Invoke-RestMethod`. Before PowerShell 6, there was `New-WebServiceProxy` which managed to provide some of the WS* standards and worked quite well with most simple SOAP interfaces. When this was not enough, one could fall back to coding in  C# leveraging the `System.ServiceModel` assembly which unfortunately is not ported to .NET Core and therefore it is not an alternative in PowerShell 6 or higher.

SOAP is not as dead as some people proclaim. Yes, it is not the current choice, but there are so many established API in SOAP, that makes it still alive. The one I've most recently encountered is the [Amadeus](https://developers.amadeus.com) which is used in the travel industry extensively and it doesn't seem to be going away soon. The travel industry, banking and insurance sector are known for keeping what works and for this reason the existing SOAP endpoints will not go away anytime soon. This makes PowerShell effectively a non-suitable scripting language and it shouldn't be.

SOAP support was already there and needs to become available again for all platforms.

Use cases I can think of are:
- Use SOAP APIs from PowerShell on all platforms.
  - Cheaper NX based VMs
  - NX based containers support which are in general more lightweight than then windows server core counterparts.
- Leverage a much-improved PowerShell 6 experience and performance when working with SOAP. SOAP tends to be generally heavy and I've already noticed how much faster the newer versions are compared to the previous ones
- Integrate with SOAP using Azure Functions which currently supports only PowerShell 6. This would allow: 
  - A quick and dirty abstraction over REST
  - Azure Logic apps would benefit as well
  - Overall integration with other cognitive services and chatbots when SOAP is involved.
- Windows Server Nano containers support.

# Proposed technical implementation details

I think that this is not a PowerShell issue alone and support from the .NET team is required to port some of the missing APIs and assemblies and support the otherwise known WCF on other platforms. 

Notice that on the [roadmap](https://devblogs.microsoft.com/dotnet/introducing-net-5/) announcement for .NET 5, many comments are about the missing support for WCF and there is quite a recognizable frustration.

# Known repositories currently blocked from PowerShell 6

I've added some repositories that I've been in involved with over the last years when working with SOAP interfaces.

- [1ASOAP](https://github.com/Sarafian/1ASOAP/) provides a toolkit for working with Amadeus (aka 1A) endpoints. The repository has three internal modules that are probably going to be split into 3 different repos. The [SOAPProxy](https://github.com/Sarafian/1ASOAP/tree/master/Source/SOAPProxy) is the one that depends on `New-WebServiceProxy` to drive SOAP clients and this one blocks it from PowerShell 6. The remark is available [here](https://github.com/Sarafian/1ASOAP/tree/master/Source/SOAPProxy#powershell-core-not-supported) as well.
- [WcfPS](https://github.com/Sarafian/WcfPS) was built around C# and the `System.ServiceModel` and `System.IdentityModel` assemblies. It generates in memory proxies but it can support even federated authentication (WSTrust 1.3) which is not available in PowerShell. The dependency on the `System.ServiceModel` effectively blocks it from PowerShell 6.
- [ISHRemote](https://github.com/sdl/ISHRemote) is an automation toolkit for [a CMS over DITA by SDL known as Tridion Docs](https://sdl.github.io/). It is built around C# and the `System.ServiceModel` and `System.IdentityModel` assemblies to leverage support for SOAP over federate authentications using WSTrust 1.3. The dependency on these assemblies blocks it PowerShell 6 and non-Windows based operating systems.

**Comment by SteveL-MSFT** [comment]
I don't know when or if .NET will support this, so an alternate would be if there was an Open Source library that is .NET Core compatible that could be used.

**Comment by BrucePay** [comment]
WRT a delivery vehicle, given that this is not a core scenario (anymore), I think making it availables as a module on PSGallery makes more sense. The trickier bit is getting the underlying .NET classes that PowerShell requires ported to Core. It might be helpful to open an issue in the .NET Core repository requesting this functionality.

**Comment by iSazonov** [comment]
> It might be helpful to open an issue in the .NET Core repository requesting this functionality.

:-) And answer will 
>this is not a core scenario (anymore),

Although they could make a standalone package with the API.

**Comment by SteveL-MSFT** [comment]
Agree with @BrucePay, making it a standalone module makes sense regardless if we ship it with PowerShell package.  Long term plan has been to have less cmdlets/modules ship with PowerShell and have them independently maintained, updated, and published on PSGallery.

**Comment by ChrisMagnuson** [comment]
In light of the news about PowerShell 7 trying to unify the fork and get us back on one version of PowerShell I came looking to see if New-WebServiceProxy was going to be addressed and found this issue.

I use New-WebService proxy to communicate with things like Adobe InDesign Server, Adobe Scene 7 Dynamic Media classic, ConnectShip Progistics (apis for shipping packages via Fedex, USPS, UPS, etc.), and in the past used this for managing Cisco Unified Communications Manager (and all the other on premise Cisco Collaboration tools).

Being able to quickly work with SOAP APIs has been really critical in being able to automate a wide array of systems that System Administrators would come in contact all using PowerShell helping it become the go to language for everyone on our team and not having this has been one of the blockers for us being able to adopt PowerShell core.

**Comment by iSazonov** [comment]
@ChrisMagnuson Thanks for your feedback! Based on MSFT team suggestion could you please clarify - do you ready to grab this in separate community project?

**Comment by SteveL-MSFT** [comment]
Now that .NET Team has [announced](https://devblogs.microsoft.com/dotnet/supporting-the-community-with-wf-and-wcf-oss-projects/) a community project for WCF support, this may be viable.  Haven't looked to see how complete it is.

**Comment by ChrisMagnuson** [comment]
In the article they mention “NET Core WCF Client“. 

Given that in powershell we are acting as a soap client could that be used?

Googling for that name didn’t come back with something that matched that exactly, maybe this is what they are referring to: https://github.com/dotnet/wcf

**Comment by SteveL-MSFT** [comment]
@ChrisMagnuson I believe the right repo is https://github.com/CoreWCF/CoreWCF

**Comment by Sarafian** [comment]
@ChrisMagnuson and @SteveL-MSFT, I've done some more digging into this topic from the perspective of a couple of repositories I've in mind and mentioned on my original post.

The [CoreWCF](https://github.com/CoreWCF/CoreWCF) repo allows a soap client to function based on two requirements and their respected issues.
- The interface and the data contracts are defined in code. This means a binary module. But, PowerShell as a scripting language, needs to ability to consume a SOAP endpoint dynamically like `New-WebServiceProxy`
- Not all bindings are available, so complicated soap flows will not be supported. This limits the possibilities but I consider this a low impact issue. Most architect knew about the short commings of SOAP due to its complexity and have steered away from the most advanced bindings.

To work around the issue, I've considered packaging `dotnet-svcutil` tool or its code into a module that behind the scenes would generate the code, compile it into memory and wrap it around an object. This is pretty much what  the new `New-WebServiceProxy` cmdlet does. The problem is that I can't find the code for `dotnet-svcutil` and when I looked deeper I run into an answer stating "that this is not open source yet. ". I've also not been able to find the code for the `New-WebServiceProxy` to try and .NET standar-ize it and offer it a binary module.

**Comment by iSazonov** [comment]
@Sarafian See https://github.com/PowerShell/PowerShell/blob/bd6fdae73520931f0d27a29d6290e18761772141/src/Microsoft.PowerShell.Commands.Management/commands/management/WebServiceProxy.cs#L38

**Comment by Sarafian** [comment]
> @Sarafian See
> 
> https://github.com/PowerShell/PowerShell/blob/bd6fdae73520931f0d27a29d6290e18761772141/src/Microsoft.PowerShell.Commands.Management/commands/management/WebServiceProxy.cs#L38

Thanks @iSazonov . The workhorse in the `New-WebServiceProxy` is the [DiscoveryClientProtocol](https://docs.microsoft.com/en-us/dotnet/api/system.web.services.discovery.discoveryclientprotocol?view=netframework-4.8) offered by the `System.Web.Services.dll` as already mentioned. The DiscoveryClientProtocol has some dependencies to other types from the same assembly and from a sampling I did, none of them are available in the upcoming `netcore-3.0` (currently preview 6).

`System.Web.Services.dll` is the driver for ASMX web services and I'm not sure that any solution should be based on this codebase. This is the reason that `New-WebServiceProxy` is limited and supports very basic soap configurations. 

Has anyone ever tried to convert its [code](https://github.com/microsoft/referencesource/tree/master/System.Web.Services) to .NET standard?

I'm more and more convinced that this is .NET team issue and maybe the PowerShell team can put an extra word :smile: .  I hope the new WCF in .net core 3, shares similarities in terms of features with `New-WebServiceProxy`. If they offer some the constructs to configure a Web Service, then hopefully they offer the drivers to generate in memory proxies like e.g. `DiscoveryClientProtocol`. In WCF this was [WsdlImporter ](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.description.wsdlimporter?view=netframework-4.8) and still unavailable for .net core 3 (preview 6)

**Comment by SteveL-MSFT** [comment]
@Sarafian Unfortunately, I don't see .NET team treating this as a priority at all which is why they invested in the CoreWCF project (even if incomplete).  They are investing in REST and gRPC.  We're doing some work in PS7 to make it more seamless using Windows PowerShell modules, so perhaps we can make it easier to call Windows PowerShell's `New-WebServiceProxy` from PS7.

**Comment by Sarafian** [comment]
> @Sarafian Unfortunately, I don't see .NET team treating this as a priority at all which is why they invested in the CoreWCF project (even if incomplete). They are investing in REST and gRPC.

@SteveL-MSFT thanks for reaching out and clarifying. It is expected what you said.

> We're doing some work in PS7 to make it more seamless using Windows PowerShell modules, so perhaps we can make it easier to call Windows PowerShell's `New-WebServiceProxy` from PS7.

That would solve homogenity within the powershell experience, because the current way of executing windows specific modules with implicit remoting is really not good. Anyhow, this will not solve azure function with powershell, unless the functions teams decides to "strengthen" the powershell support.

**Comment by SteveL-MSFT** [comment]
Azure Functions can run on a Windows sandbox which contains Windows PowerShell.  Even today, you could from PSCore6 call out to powershell.exe to run whatever Windows PowerShell pipeline you need.

**Comment by Sarafian** [comment]
> Azure Functions can run on a Windows sandbox which contains Windows PowerShell. Even today, you could from PSCore6 call out to powershell.exe to run whatever Windows PowerShell pipeline you need.

Hmmm didn't know that. This is very good news. Thanks @SteveL-MSFT .

**Comment by mikeTWC1984** [comment]
I was looking for a way to mirror New-WebServiceProxy on linux powershell (to consume SharePoint soap services), and dotnet-svcutil seem to be a good option. It's not generating client automagically like windows powershell, but actually doing this manually might be even better approach in many cases (you just generate client code once and then reuse it).   Below are some notes to get started (if not familiar with this tool)

To generate cs file with client definition, install dotnet sdk 2 (it's not compatibale with v3 yet, but you can have both), then install the tool itself (dotnet tool install --global dotnet-svcutil) and create some dummy  app (dotnet new console)
Then download all wsdl files you need and run: dotnet-svcutil *.wsdl -sync 
If no error, build the project (dotnet build) and import project dll from ./bin/Debug/netcoreapp
You can also load the type from cs file directly:
```
Add-Type -TypeDefinition (get-content -raw ./ServiceReference/Reference.cs) -ReferencedAssemblies  netstandard, 
 System.ServiceModel,
 System.ServiceModel.Primitives,
 System.Private.ServiceModel,
 System.Runtime.Serialization.Xml,
 System.Xml, System.Diagnostics.Tools,
 System.Xml.ReaderWriter,
 System.Diagnostics.Debug,
 System.Runtime.Serialization.Primitives 
# might need some extra libs to refer
```
Once type is loaded you should instantiate Client  object. Type name likely will be "ServiceName" + "SoapClient", or something containing Client word. In case of SharePoint lists service:
```
$defaultConfig = [ServiceReference.ListsSoapClient+EndpointConfiguration]::ListsSoap
$client = [ServiceReference.ListsSoapClient]::new($defaultConfig)
```
If there is no auth or you are on windows network with NTLM you are likely all set. Otherwise try to configure auth using $client.ClientCredentials property, or you can also use other constructor for the client:
```
$result = [System.ServiceModel.BasicHttpBinding]::new()
$result.Security.Transport.ClientCredentialType = [System.ServiceModel.HttpClientCredentialType]::Ntlm; # choose the one you need
$endPoint = [System.ServiceModel.EndpointAddress]::new("https://sharepoint.site/_vti_bin/Lists.asmx")
$client = [ServiceReference.ListsSoapClient]::new($result, $endPoint)
```
You can also use this constructor to consume same service from different endpoint.

**Comment by Sarafian** [comment]
@mikeTWC1984 have considered wrapping everything in and generating proxies dynamically like it is done in the [WcfPS](https://github.com/Sarafian/WcfPS/tree/master/Modules/WcfPS) module? It uses .net classes that normally the wsdl importers use to generate the service references but instead of saving in file it compiles in memory.

**Comment by mikeTWC1984** [comment]
@Sarafian  is WcfPS compatible with powershell core, at least with Windows version?

**Comment by Sarafian** [comment]
> @Sarafian is WcfPS compatible with powershell core, at least with Windows version?
I am not sure. You will probably need to change some namespaces. Keep in mind that the advanced stuff related to token are definitely not available.

**Comment by vazome** [comment]
Please add this

**Comment by gerneio** [comment]
Inspired by above comments ([here ](https://github.com/PowerShell/PowerShell/issues/9838#issuecomment-576103664) and [here](https://github.com/PowerShell/PowerShell/issues/9838#issuecomment-504328041)), I created a hack-ish `New-WebServiceProxy` replacement which allowed my to use existing PS modules that relied on it (i.e. such as [ReportingServicesTools](https://github.com/microsoft/ReportingServicesTools/)). See my comment [here](https://github.com/microsoft/ReportingServicesTools/issues/239#issuecomment-2742133163) as well as a [gist](https://gist.github.com/gerneio/57b1705037ee0fdde72751f35891d554) I put together with various details and examples. Note that it would probably need to be heavily modified to be a drop-in replacement for any existing implementations due to how the WSDL code gen has changed.

**Comment by Sarafian** [comment]
@gerneio is the [gist](https://gist.github.com/gerneio/57b1705037ee0fdde72751f35891d554) compatible with .net core? Problem with the code generated from a WSDL is that in some service descriptions, the code required for it to work hasn't been implemented in core I think.

When I had developed the WcfPS and the ISHRemote, we were using WSTrust 1.3 and segments from 1.4 which were not supported. In my opinion, this might be one of the biggest issues. Conditional compatibility with core depending on which parts of the WS* standards are used.
My apologis, it's been a while since I last worked with SOAP tech and I don't remember the terms very well.

**Comment by wilsoncg** [comment]
The gist is using dotnet-svcutil, which the [docs](https://learn.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide?tabs=dotnetsvcutil2x) are saying is dotnet core.

**Comment by gerneio** [comment]
All I can confirm for sure is that it worked as a drop-in replacement for the handful of cmdlets that I needed out of `ReportingServicesTools`. Other services might not be so straightforward.

Fyi, i also had success running this in linux environments on PS Core.

**Comment by Sarafian** [comment]
> The gist is using dotnet-svcutil, which the [docs](https://learn.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide?tabs=dotnetsvcutil2x) are saying is dotnet core.

Thanks. I wonder now about the coverage of the WS* standards. I did a quick check but didn't find much information.
