### ISSUE TITLE
PowerShell 7.0.0 error with keyboard input on multi layered keyboard

### ISSUE THREAD

**Issue by MovGP0** [PowerShell/PowerShell#9839]
# Steps to reproduce

- Use a multi layered keyboard layout like [Neo2](https://github.com/neo-layout/neo-layout/tree/master/windows)
- Install PowerShell 7.0.0-preview1
- Open PowerShell and enter a special character (ie. `-` or `$`). You need to hold the caps lock key to switch the input layer. 

# Expected behavior

Only the special character is entered on the console. Ie. 

```none
Get-ChildItem
$PsVersionTable
```

# Actual behavior

The special character is prefixed with an `@` sign: 

```none
Get@-ChildItem
@$PsVersionTable
```

In fact, every press of the caps lock key (Key Code 20) enters an `@` sign. 

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.1
PSEdition                      Core
GitCommitId                    7.0.0-preview.1
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by MovGP0** [comment]
Note that PowerShell Core 6.x and PowerShell 5.x are not effected by this bug.

**Comment by vexx32** [comment]
/cc @daxian-dbw @lzybkr 

I have a recollection of you two talking about modifier keys being displayed in console. Is this related to that discussion / PR?

**Comment by daxian-dbw** [comment]
This should be a duplicate of https://github.com/PowerShell/PSReadLine/issues/914
A fix was made that worked fine with US-international and the default French keyboard, but unfortunately, it doesn't work with Neo2.

**Comment by MovGP0** [comment]
It is indeed a duplicate. Closing this one and subscribing the other. Thanks!
