### ISSUE TITLE
Get-eventlog tab completes but is not a cmdlet

### ISSUE THREAD

**Issue by maunderingpowershell** [PowerShell/PowerShell#9852]
# Steps to reproduce
Run Get-eventlog

# Expected behavior

This command by itself should ask the user to specify a value for the parameter "logname" and then get the contents of the log matching the new value of that parameter.

# Actual behavior

```
Returns the following error:
Get-EventLog : The term 'Get-EventLog' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-EventLog
+ ~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Get-EventLog:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException


```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.1
PSEdition                      Core
GitCommitId                    7.0.0-preview.1
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by kvprasoon** [comment]
Not able to repro. This cmdlet doesn't tab completes as it doesn't exist so far in PowerShell 6+ .

**Comment by maunderingpowershell** [comment]
So is the get-eventlog cmdlet still coming to powershell 7? The cmdlet does tab complete but it fails when run.

Chris Maunder
Systems Administrator
Royal Engineered Composites

308-832-2760 x110
CMaunder@royalcomposites.com<mailto:CMaunder@royalcomposites.com>

**Comment by iSazonov** [comment]
/cc @SteveL-MSFT Should we get Get-EventLog cmdlet back in 7.0? 
Should we make an inventory in return all missing cmdlets?

**Comment by SteveL-MSFT** [comment]
`Get-EventLog` is deprecated as it only supports the old EventLog APIs (which doesn't have access to the new ETW logs).  Instead, users should be using `Get-WinEvent` which uses the new ETW APIs and can get the old EventLog logs.
