### ISSUE TITLE
Feature Request: add [list] type accelerator

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShell#9853]
# Summary of the new feature/enhancement

Arrays work fine for a lot of scenarios in PowerShell except with size gets large and the number of additions to the array is big.  In the community, we encourage folks to use a list for "perf critical" scenarios.  It would be nice if we could make it simpler for folks to use lists.  

# Proposed technical implementation details (optional)

A good start is to create a type accelerator for list.  Now I don't know if the type accelerator mechanism supports type parameters allowing me to do this:

```powershell
$list = [list[string]]::new()  # explicitly create with explicit type parameter
$list = [list][foo.bar]::HugeArrayOfStrings # infer type parameter and initialize the list from the array
```
If it doesn't I suppose we could internally use PSObject as the type parameter.  This wouldn't be as strongly typesafe but it would largely address the perf issue for reference types.  Not so much for value types though.

**Comment by rjmholt** [comment]
Related to https://github.com/PowerShell/PowerShell/issues/5643.

There's some discussion around it in https://github.com/PowerShell/PowerShell/issues/5643#issuecomment-358521960.

**Comment by vexx32** [comment]
🤔 Gonna roll this into a build and see what issues I come across. Been wanting to do this for _ages_!

**Comment by vexx32** [comment]
Initial results are pretty promising for only a one-line code change.

```powershell
$list = [list[string]]::new() # works correctly
$list = [list][foo.bar]::HugeArrayOfStrings # fails, see below
```
![image](https://user-images.githubusercontent.com/32407840/59118899-60a61780-891f-11e9-81ab-2fab1f5580ce.png)

So at minimum we'd need to also include a type converter that is capable of recognising that our source is an array, and our target is a list, and then just pull the basetype from the array and plug it into the List as a generic type argument.

Not sure exactly how well that works with the existing conversion path shenanigans but it appears to be very doable.
