### ISSUE TITLE
Please provide a way to get the certificate from a web response.

### ISSUE THREAD

**Issue by alujones** [PowerShell/PowerShell#9856]
# Summary of the new feature/enhancement

I had some code working locally on a Windows laptop in Powershell 5, which used Net.WebRequest to get the Certificate returned by a server, so as to validate its ownership.

Tried to use the code in PowerShell 6, and/or in Azure Functions (which also use PS6), and was unable to do so - ServicePoint.Certificate was always $null, no matter what site I tried.

I see you've done some work adding -SkipCertificateCheck, and are working on adding custom certificate validation functionality - but all I really need is to see what certificate is provided by the web server. Ideally without performing the entire request - I currently use a HEAD Method, but I'm aware that might have issues, too.

# Proposed technical implementation details (optional)

Current code (PS5):
$wr1 = [Net.HttpWebRequest]::Create('https://www.github.com')
$wr1.Method = 'HEAD'
$ignore = $wr1.GetResponse()
if ($wr1.ServicePoint -ne $null)
{
  if ($wr1.ServicePoint.Certificate -ne $null) {
    Write-Host "The certificate is $($wr1.ServicePoint.Certificate.Subject)"
  } else {
    Write-Host "The certificate is null - can't get the subject."
  }
} else {
  Write-Host "The service point is null, can't get the certificate."
}

Ideal target code, something like:

$wr1 = Invoke-WebRequest 'https://www.github.com' -SkipCertificateCheck -SkipHeaderValidation -Method 'Head'
Write-Host "Certificate subject is $($wr1.Certificate.Subject)"

**Comment by bergmeister** [comment]
This is not an issue of PowerShell but the underlying .Net Core Framework.
The API that you use is now deprecated and alternative APIs like HttpClient are recommended. See the below issue for details and possible solutions
https://github.com/dotnet/corefx/issues/36979

**Comment by markekraus** [comment]
If just getting the certificate from the remote server is your goal:

```powershell
function Get-RemoteCertificate {
  [CmdletBinding()]
  [OutputType([System.Security.Cryptography.X509Certificates.X509Certificate])]
  param (
    [Parameter(
      Mandatory,
      ValueFromPipeline
    )]
    [ValidateNotNull()]
    [Uri]
    $Uri
  )
  process {
    try {
      $TcpClient = [System.Net.Sockets.TcpClient]::new($Uri.Host, $Uri.Port)
      try {
        $SslStream = [System.Net.Security.SslStream]::new($TcpClient.GetStream())
        $SslStream.AuthenticateAsClient($Uri.Host)
        $SslStream.RemoteCertificate
      } finally {
        $SslStream.Dispose()
      }
    } finally {
      $TcpClient.Dispose()
    }
  }
}
```

**Comment by DennisL68** [comment]
> If just getting the certificate from the remote server is your goal:
> 
> ```powershell
> function Get-RemoteCertificate 
> ```
TcpClient doesn't work with self signed certificates and an error will be generated...

~~~
Exception calling ".ctor" with "2" argument(s): "A connection attempt failed because the connected party did not properly
respond after a period of time, or established connection failed because connected host has failed to respond
~~~

**Comment by iSazonov** [comment]
@DennisL68 TcpClient know nothing about certificates. Look SslStream.

**Comment by jsclmedave** [comment]
@iSazonov Can you elaborate?   "cpClient know nothing about certificates. Look SslStream."

**Comment by iSazonov** [comment]
> @iSazonov Can you elaborate? "cpClient know nothing about certificates. Look SslStream."

https://source.dot.net/#System.Net.Security/System/Net/Security/SslStream.cs,537
