### ISSUE TITLE
Get-Variable leaks "private"-scoped variables

### ISSUE THREAD

**Issue by travis-c-lagrone** [PowerShell/PowerShell#9859]
# Steps to reproduce

```powershell
pwsh -NoProfile -Command {
    New-Variable -Name 'foo' -Value 'bar' -Scope Global -Option Private
    & { Get-Variable -Name 'foo' -Scope Global -ValueOnly -ErrorAction Ignore }
}
```

# Expected behavior

```none
```

# Actual behavior

```none
bar
```

# Environment data

```none

Name                           Value
----                           -----
PSVersion                      6.2.1
PSEdition                      Core
GitCommitId                    6.2.1
OS                             Microsoft Windows 10.0.17763 
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.2.1}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by travisclagrone** [comment]
For comparison, here is the behavior with the `$` operator instead:

**Steps to reproduce**

```powershell
pwsh -NoProfile -Command {
    New-Variable -Name 'foo' -Value 'bar' -Scope Global -Option Private
    & { $global:foo }
}
```

**Expected behavior**

```none
```

**Actual behavior**

```none
```

**Comment by bpayette** [comment]
@travisclagrone Yes, this looks like a bug. IIRC, for performance reasons, language variable access goes through one interface and cmdlet variable access goes through the (much slower) provider interface which would explain the difference in behaviour. With regards to terminology, "private" was an unfortunate choice. "Private" variables in PowerShell are intended to be equivalent to unexported variables in sh/ksh/bash. All that said, changing this now would be a breaking change and I don't see a compelling reason to do that.
