### ISSUE TITLE
Expand HiddenAttribute to work with classes

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#9861]
# Summary of the new feature/enhancement

When developing a module that has a mix of C# and PowerShell elements, it's often desirable to have some classes accessible in PowerShell that are not necessarily part of the supported public API's.  Currently this is done either via reflection or just documentation. Allowing `HiddenAttribute` to decorate classes would provide a nice way to telegraph that it's not part of the public contract.

# Proposed technical implementation details (optional)

1. Add the following `AttributeTargets` to `HiddenAttribute`'s `AttributeUsage` decoration.
    * Class
    * Struct
    * Enum
    * Interface
    * Delegate

1. Add a check for `HiddenAttribute` to `CompletionCompleters.CompleteType(CompletionContext, string, string)`.  Or in `InitializeTypeCache`, but it seems better to store some extras then to check every type at once for the attribute.

1. Add an `IsHidden` ETS member to `System.Type` and *maybe* add it to formatting.

**Comment by bpayette** [comment]
@SeeminglyScience 
> often desirable to have some classes accessible in PowerShell that are not necessarily part of the supported public API's

I didn't understand this. Can you provide an example?  Thanks.

**Comment by SeeminglyScience** [comment]
@bpayette Yeah that sentence got away from me a bit.

Lets say I'm building a module that has a mix of cmdlets and functions, and I have some utility classes on the C# side that I might typically make `internal`.  If I want to reuse those utility classes in the PowerShell portion of the module, then I either need to use reflection or make the class public.

If the proposed change was made, I would be able to do this instead:

```csharp
// Utils.cs
namespace MyModule.Internal
{
    [Hidden, EditorBrowsable(EditorBrowsableState.Never)]
    public static class Utils
    {
        // Some utility method to handle path resolution and error handling uniformly.
        public static string TransformPath(PSCmdlet cmdlet, string path) => null;
    }
}
```

```powershell
# MyModule.psm1
function Test-Something {
    [CmdletBinding()]
    param(
        [Parameter()]
        [string] $Path
    )
    end {
        $fullPath = [MyModule.Internal.Utils]::TransformPath($PSCmdlet, $Path)
    }
}
```
