### ISSUE TITLE
Checking for TypeConverter's should use TypeDescriptor.GetConverter

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#9863]
As per https://github.com/dotnet/runtime/issues/29823, it is no longer reliable to directly check for `TypeConverterAttribute` as some types are now handled intrinsically within `TypeConverter`.

The following code needs to utilize `TypeDescriptor.GetConverter` instead:

https://github.com/PowerShell/PowerShell/blob/65a3e467cc95059d16f58174335e6dd3a58c459b/src/System.Management.Automation/engine/LanguagePrimitives.cs#L1490-L1499

Related issues: #9815

**Comment by iSazonov** [comment]
@SeeminglyScience Thanks for great investigations! Do you ready to pull PR?

I found TypeConverterAttribute still in some places.

**Comment by SeeminglyScience** [comment]
> Do you ready to pull PR?

Nah you can mark this one up for grabs I think.  It should be a simple change but it will need some tests that I don't have the bandwidth for atm.

**Comment by iSazonov** [comment]
> It should be a simple change

It can be not trivial. The TypeConverterAttribute  is used in PSMemberViewTypes.

@SteveL-MSFT It seems it is critical for 7.0.

**Comment by vexx32** [comment]
@iSazonov we'd need to test to be sure, but from the referenced .NET Core issue it seems .NET Core team are saying that we should not need to be checking directly for `TypeConverterAttribute`, and that the `TypeDescriptor.GetConverter` method(s) will check that as well as the various other methods of registering type converters.

**Comment by iSazonov** [comment]
TypeConverterAttribute is not deprecated and we should keep current code. Also the attribute can be used in any custom code.

**Comment by iSazonov** [comment]
Now fix works. Will pull tomorrow with a test.

**Comment by joeyaiello** [comment]
@iSazonov given the changes that .NET made in .NET 5, has this been fixed in 7.1? If so, can you please close it as fixed?

**Comment by iSazonov** [comment]
@joeyaiello .Net team changed the implementation some times for last 1-2 years because they want to reduce cross assembly dependencies. I think we need re-check that all converters we want to have work in current version (I think they is near RC and .Net 5 has stable package design).

**Comment by SteveL-MSFT** [comment]
@iSazonov , this seems to have been fixed by https://github.com/PowerShell/PowerShell/pull/12580?

**Comment by vexx32** [comment]
.NET team recommended the method provided on TypeDescriptor for finding type converters... it doesn't look like that PR makes use of that?

**Comment by iSazonov** [comment]
I guess .Net now stable in the area - **our tests from #12580 works**. But they (.Net team) do not still close/fix all related issues so it is not clear can we benefit more from .Net and improve PowerShell engine itself.

Since our tests are passed we could close the bug labeled issue as fixed and continue monitor silently.

**Comment by CarloToso** [comment]
@iSazonov Can we close this issue?

**Comment by iSazonov** [comment]
We need recheck. I did not monitor latest changes in .Net.
