### ISSUE TITLE
PowerShell ISE Feature Request: Able to change hotkeys

### ISSUE THREAD

**Issue by the-eric-kwok** [PowerShell/PowerShell#9877]
# Summary of the new feature/enhancement
The Intellisense hotkey (Ctrl+Space) is corrupt with the hotkey to activate Chinese IME. So I want to change my hotkey in the configure page.

**Comment by corbob** [comment]
To borrow from the issue template for Windows PowerShell issues (ISE is a feature of Windows PowerShell):

---

# Windows PowerShell

For Windows PowerShell 5.1 issues, suggestions, or feature requests please use the following link instead:
Windows PowerShell [UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)

This repository is **ONLY** for PowerShell Core 6 issues.

---

Based on this, I'd suggest adding it to the UserVoice, although from my understanding it's not likely to be addressed as the ISE is considered complete.
