### ISSUE TITLE
Unable to Disconnect a powershell session connected to office365

### ISSUE THREAD

**Issue by kireetivvs** [PowerShell/PowerShell#9878]
I want to disconnect from a remote powershell connected to office365 and connect back later. Tried the `Disconnect-PSSession` command but it throws error.
**Steps to reproduce:**
```
$UserCredential = Get-Credential
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://ps.compliance.protection.outlook.com/powershell-liveid/ -Credential $UserCredential -Authentication Basic -AllowRedirection
.
.
Disconnect-PSSession $Session

Disconnect-PSSession : Disconnect-PSSession operation failed for runspace Id = 69bb5dfe-4149-4c38-bcb8-658e5f4da6e5
for the following reason: The disconnection operation is not supported on the remote computer. To support
disconnecting, the remote computer must be running Windows PowerShell 3.0 or a later version of Windows PowerShell.
At line:1 char:1
+ Disconnect-PSSession $Session
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ([PSSession]Session1:PSSession) [Disconnect-PSSession], RuntimeExcepti
   on
    + FullyQualifiedErrorId : PSSessionDisconnectFailed,Microsoft.PowerShell.Commands.DisconnectPSSessionCommand
```
Locally I have Powershell version 4 running. And `Get-PSSessionConfiguration` shows PSVersion 4 at server. And `Remove-PSSession` works perfectly. Any help appreciated

**Comment by bpayette** [comment]
Hi @kireetivvs, just to make sure we're talking about the same thing, `Disconnect-PSSession` is not the same as `Remove-PSSession`. `Remove` removes the remote runspace then closes the connection. `Disconnect` closes the connection but leaves the remote session running so you can reconnect to it at a later time.  Also be aware that  [`Get-PSSessionConfiguration`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/get-pssessionconfiguration?view=powershell-6)  returns information about the _local_ computer not remote ones.

**Comment by kireetivvs** [comment]
@bpayette, yes I am looking for reconnecting to the session later. So ```Disconnect-PSSession``` is the cmdlet I want to make use of. Any idea why Disconnect isn't working for Office 365 powershell session?

**Comment by BrucePay** [comment]
@PaulHigin Any thoughts?

**Comment by PaulHigin** [comment]
I remember that this disconnect/reconnect feature was disabled for IIS hosted endpoints, which covers Exchange endpoints.  This was done at the WSMan layer (not PowerShell) and I don't remember the details, but @manojampalam should be able to provide more information.

**Comment by manojampalam** [comment]
I believe @PaulHigin is correct. Disconnected session feature is not supported in IIS hosted WSMan endpoints.
