### ISSUE TITLE
No completions for dynamic parameters on command in scriptblock

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/PowerShell#9880]
Issue Description
=====

I am experiencing a problem with... Dynamic Parameters within a script block. Following gif shows the problem. 

![Problem-VSCodeDynamicParameters](https://user-images.githubusercontent.com/15063294/59164194-264c9e00-8b0a-11e9-9916-4096e1ee8f1e.gif)

I am actually not quite sure on the behavior but it seems that DynamicParameters are not expanded when using inside ScriptBlock. It's missing 3 dynamic parameters that I have defined. Outside of scriptblock, it works fine.

This is how the function looks like:

```powershell
function New-HTMLTab {
    [CmdLetBinding(DefaultParameterSetName = 'FontAwesomeBrands')]
    param(
        [parameter(ParameterSetName = "FontAwesomeBrands")]
        [parameter(ParameterSetName = "FontAwesomeRegular")]
        [parameter(ParameterSetName = "FontAwesomeSolid")]
        [Parameter(Mandatory = $false, Position = 0)][ValidateNotNull()][ScriptBlock] $HtmlData = $(Throw "No curly brace?)"),
        [parameter(ParameterSetName = "FontAwesomeBrands")]
        [parameter(ParameterSetName = "FontAwesomeRegular")]
        [parameter(ParameterSetName = "FontAwesomeSolid")]
        [alias('TabHeading')][Parameter(Mandatory = $false, Position = 1)][String]$Heading,
        [parameter(ParameterSetName = "FontAwesomeBrands")]
        [parameter(ParameterSetName = "FontAwesomeRegular")]
        [parameter(ParameterSetName = "FontAwesomeSolid")]
        [alias('TabName')][string] $Name
    )
    DynamicParam {
        $ParameterSetBrands = New-Object System.Management.Automation.ParameterAttribute
        $ParameterSetBrands.Mandatory = $false
        $ParameterSetBrands.ParameterSetName = 'FontAwesomeBrands'

        $ParameterSetRegular = New-Object System.Management.Automation.ParameterAttribute
        $ParameterSetRegular.Mandatory = $false
        $ParameterSetRegular.ParameterSetName = 'FontAwesomeRegular'

        $ParameterSetSolid = New-Object System.Management.Automation.ParameterAttribute
        $ParameterSetSolid.Mandatory = $false
        $ParameterSetSolid.ParameterSetName = 'FontAwesomeSolid'


        $IconsBrands = New-Object  System.Collections.ObjectModel.Collection[System.Attribute]
        $IconsBrands.Add($ParameterSetBrands)
        $IconsBrands.Add((New-Object System.Management.Automation.ValidateSetAttribute($Script:FontAwesomeBrands)))
        $IconsBrandsRuntime = New-Object System.Management.Automation.RuntimeDefinedParameter('IconBrands', [string], $IconsBrands)
        #$IconsBrandsRuntime.Value = 'safari'

        $IconsRegular = New-Object  System.Collections.ObjectModel.Collection[System.Attribute]
        $IconsRegular.Add($ParameterSetRegular)
        $IconsRegular.Add((New-Object System.Management.Automation.ValidateSetAttribute($Script:FontAwesomeRegular)))
        $IconsRegularRuntime = New-Object System.Management.Automation.RuntimeDefinedParameter('IconRegular', [string], $IconsRegular)

        $IconsSolid = New-Object  System.Collections.ObjectModel.Collection[System.Attribute]
        $IconsSolid.Add($ParameterSetSolid)
        $IconsSolid.Add((New-Object System.Management.Automation.ValidateSetAttribute($Script:FontAwesomeSolid)))
        $IconsSolidRuntime = New-Object System.Management.Automation.RuntimeDefinedParameter('IconSolid', [string], $IconsSolid)

        # Finalization
        $RuntimeParamDic = New-Object System.Management.Automation.RuntimeDefinedParameterDictionary
        $RuntimeParamDic.Add('IconBrands', $IconsBrandsRuntime)
        $RuntimeParamDic.Add('IconRegular', $IconsRegularRuntime)
        $RuntimeParamDic.Add('IconSolid', $IconsSolidRuntime)
        return $RuntimeParamDic
    } 
    End {

    }

}
```

Attached Logs
=====

Follow the instructions in the [README](https://github.com/PowerShell/vscode-powershell%23reporting-problems) about
capturing and sending logs.

[1560113331-d265095b-ac02-467c-8c8b-912394121ba51560113328300.zip](https://github.com/PowerShell/vscode-powershell/files/3269960/1560113331-d265095b-ac02-467c-8c8b-912394121ba51560113328300.zip)

Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.18362 |
| VSCode | 1.35.0|
| PowerShell Extension Version | 2019.5.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|5.1.18362.113|
|PSEdition|Desktop|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.18362.113|
|BuildVersion|10.0.18362.113|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.5.0|
|bracket-pair-colorizer-2|CoenraadS|0.0.28|
|code-settings-sync|Shan|3.2.9|
|githistory|donjayamanne|0.4.6|
|gitlens|eamodio|9.8.1|
|markdown-all-in-one|yzhang|2.3.1|
|markdown-preview-enhanced|shd101wyy|0.4.1|
|material-icon-theme|PKief|3.8.0|
|polacode|pnp|0.3.2|
|powershell|ms-vscode|2019.5.0|
|project-manager|alefragnani|10.5.2|
|rainbow-csv|mechatroner|1.1.1|
|theme-monokai-pro-vscode|monokai|1.1.13|
|vscode-pull-request-github|GitHub|0.8.0|
|vscode-wakatime|WakaTime|2.1.2|
|xml|DotJoshJohnson|2.5.0|

**Comment by PrzemyslawKlys** [comment]
It's like ScriptBlock within a ScritpBlock is blocking it. Until I open brackets for New-HTMLTab11 autocomplete works fine. You can test above code on Mac.

**Comment by SeeminglyScience** [comment]
Just to clarify I don't think it's the parent script block, but instead the script block to the right that is throwing off tab completion. `New-HTMLTab -<tab>` works, `New-HTMLTab -<tab> {}` does not.  The psuedo parameter binding that completion uses to determine available parameters may not take dynamic parameters into account when there's a positional argument.

The easiest workaround for now is to just add a <kbd>#</kbd> before the <kbd>{</kbd> and then remove it after completion.

**Comment by PrzemyslawKlys** [comment]
I've actually removed dynamic parameters for my case because of this. It's not a priority for me now although having 1400 strings in ValidateSet doesnt' look pretty :-) But hoping for a fix for future releases.
