### ISSUE TITLE
Get String and Replace Question

### ISSUE THREAD

**Issue by rzh3ll** [PowerShell/PowerShell#9883]
Hello,

I want to search multiple files with a string from my control File and put it into an Output.log

It works well most times.

But when my search string in my Control file has String with paranthesis (example : (84, 83, 69, 21, 78) it doesnt work.

Can i mask the Paranthesis in my Control File ? I tried :

´ `

""

''

but it didnt work, he hates my paranthesis.

The Script is :

Set-StrictMode -Version latest

$path = Split-Path -parent $MyInvocation.MyCommand.Definition

$files = Get-Childitem $path *.cld | Where-Object { !($_.psiscontainer) }

$controls = Get-Content ($path + "\control_file.heller")

$output = $path + "\Gefundene_Listtypen.log"

Function getStringMatch

{

\# Loop through all *.cld files in the $path directory

Foreach ($file In $files)

{

\# Loop through the search strings in the control file

ForEach ($control In $controls)

{

$result = Get-Content $file.FullName | Select-String $control -quiet -casesensitive

If ($result -eq $True)

{

$match = $file.FullName

"Der Listtyp : $control wurde in diesem Coldjob gefunden: $match" | Out-File $output -Append

}

}

}

}

getStringMatch

The Control File contains only the string :

(88, 87, 85, 89, 55) length 5 types

How can i make this work ?

Thanks for help.

**Comment by iSazonov** [comment]
@rzh3ll The repo is for developers. Please move your question to any PowerShell forum.

Try to use `select-string -SimpleMatch`.
