### ISSUE TITLE
Add publicly implementable adapter for methods

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#9890]
`PSPropertyAdapter` is cool, but every time I've thought about using it I've stopped because I typically also want methods.  Considering it was purposefully omitted from the public API and already exists in the internal API, I'm guessing this was a design decision.  Could someone clarify the intention?  Was this a security related decision or could this be opened up?

**Comment by BrucePay** [comment]
@SeeminglyScience IIRC we created `PSPropertyAdapter` as a compromise for a partner team that had property bags that they wanted to _easily_ expose as PSObjects. Our general expectation was that anyone who wanted to expose data as a `PSObject` would write a custom *ObjectAdapter but that's a non-trivial proposition (hence the compromise)  Of course this all pre-dates the DLR (which PowerShell supports) so you might want to look at `DynamicObject` and friends and see if they are suitable for your purposes.

**Comment by SeeminglyScience** [comment]
> Our general expectation was that anyone who wanted to expose data as a PSObject would write a custom *ObjectAdapter but that's a non-trivial proposition

When you say custom `*ObjectAdapter` do you mean like `DotNetAdapter`/`DirectoryEntryAdapter`/etc? If so then yeah I'd take that in a heart beat, but `Adapter` is internal.

> Of course this all pre-dates the DLR (which PowerShell supports) so you might want to look at DynamicObject and friends and see if they are suitable for your purposes.

Yeah for some things `IDynamicMetaObjectProvider` works *okay*.  Even when I'm going that route though, I need a better way to telegraph members.  Since it uses `GetDynamicMemberNames`, `Get-Member` just shows the member name and that it's dynamic.  I love being able to customize binding, but it leaves a lot to be desired in presentation.

The bigger problem with that route though, is I can't apply it broadly.  I *have* to create a wrapper object for every object and every result (I know, PowerShell does it, but it can hide it in the language).  The dream would be to be able to specify an `Adapter` *and* custom `DynamicMetaObjectBinder`'s broadly (even against all types) but I sure would settle for `Adapter`!

This may not be the best example of a use case, but it would certainly make [ImpliedReflection](https://github.com/SeeminglyScience/ImpliedReflection) a lot more functional (not to mention maintainable).

**Comment by SeeminglyScience** [comment]
Can this be reopened please? cc @iSazonov 

The design question was answered, but it still stands as a feature request.
