### ISSUE TITLE
PowerShell 7-preview1 Suggestions remians on screen even after selecting an item

### ISSUE THREAD

**Issue by 0xaryan** [PowerShell/PowerShell#9894]
![UqoPy4ryiP](https://user-images.githubusercontent.com/9091958/59467575-4602ff80-8e45-11e9-91a5-704e7b483990.gif)

# Steps to reproduce
Use any suggestion with many items, for example write `[System.T` and press `ctrl+space`
in console hosts like ConEmu or Visual Studio Code Terminal, then choose an item. (This doesn't happen in the main PowerShell host)

# Expected behavior
The item should be auto-completed and then hide from screen.

# Actual behavior
The item gets selected but remains on screen.

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.1
PSEdition                      Core
GitCommitId                    7.0.0-preview.1            TypedReference
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
This is a PSReadLine issue.
@0xaryan Can you please move the issue report to https://github.com/powershell/psreadline? The bug report template has a script for you to run to collect some extra environment data, which would be very helpful to the diagnosis.

**Comment by 0xaryan** [comment]
@daxian-dbw By "Move the issue" you mean [transferring it](https://help.github.com/en/articles/transferring-an-issue-to-another-repository)?
If so, I can't because _"To transfer an open issue to another repository, you must have write permissions on the repository the issue is in and the repository you're transferring the issue to. "_

Or you mean reposting this issue there?

**Comment by daxian-dbw** [comment]
Sorry for the ambiguity. I mean reopening the issue in the PSReadLine repository.

**Comment by 0xaryan** [comment]
Alright, I reposted this here: https://github.com/PowerShell/PSReadLine/issues/946
