### ISSUE TITLE
Bundled version of the ThreadJob module is outdated

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#9906]
The version of the `ThreadJob` module that comes with PowerShell Core 7.0.0-preview.1 is 1.1.2, whereas the latest (production) release per https://www.powershellgallery.com/packages/ThreadJob is 2.0.0

**Comment by iSazonov** [comment]
We have 2 opened PRs from Dependabot but with test errors. I expect we will have new version in next preview.
