### ISSUE TITLE
7.0.0-preview.1 problems with keyboard layouts that use dead-keys

### ISSUE THREAD

**Issue by jonitis** [PowerShell/PowerShell#9910]
# Issue
All versions of PowerShell (5.1, 6.2, 7.0) have different problems with input of accented characters.   The issue with 7.0.0 preview 1 is that entering dead-key character should wait for next character to produce the combined character. For examle '+a=ā. '+(space)='. Instead we immediately get @ character. If followed by correct latin character we also get combined accented character. Pressing the dead-key should not produce any output until next key is pressed.
  It is getting better in 7.0, but still broken compared to cmd.exe or plain notepad.exe.

# Steps to reproduce

Install "Latvian (standard)" keyboard layout. Produce accented characters using both supported methods (use a,c,e,g,i,k,l,n,s,u,z as base characters):
1. Hold AltGr+Latin character. E.g. AltGr+a=ā, AltGr+S=Š
2. Tap dead-key ', followed by latin character. E.g. '+a=ā, '+S=Š

# Expected behavior

```
// Using AltGr
āčēģīķļņšūž

// Using dead-key
āčēģīķļņšūž
```

# Actual behavior

PowerShell 7 works correctly with AltGr, but produces unexpected characters with dead-key 
```
// Using AltGr
āčēģīķļņšūž
// Using dead-key
@ā@č@ē@ģ@ī@ķ@ļ@ņ@š@ū@ž
```
PowerShell 6.2 swallows all AltGr combinations, but works as expected with dead-keys
```
// Using AltGr
<nothing>
// Using dead-key
āčēģīķļņšūž
```
PowerShell 5.1 swallows all AltGr combinations and with dead-keys produces non-accented character. 100% unusable
```
// Using AltGr
<nothing>
// Using dead-key
acegiklnsuz
```
cmd.exe works with both methods as expected:
```
// Using AltGr
āčēģīķļņšūž
// Using dead-key
āčēģīķļņšūž
```

# Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.1
PSEdition                      Core
GitCommitId                    7.0.0-preview.1
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jonitis** [comment]
Area-PSReadline

**Comment by jonitis** [comment]
One can use Microsoft Keyboard Layout Creator 1.4 to see what combined characters should be produced by keyboard layout on each key combination
https://www.microsoft.com/en-us/download/details.aspx?id=22339

**Comment by vexx32** [comment]
See here: https://github.com/PowerShell/PSReadLine/pull/945#issuecomment-502710868

Being worked on in the PSReadline repo. :smile:

**Comment by daxian-dbw** [comment]
@jonitis Can you please try out the fix in https://github.com/PowerShell/PSReadLine/pull/945? You can get the `PSReadLine.zip` from the artifact tab of that PR CI: https://ci.appveyor.com/project/PowerShell/psreadline/builds/25306787/artifacts

**Comment by jonitis** [comment]
@vexx32, @daxian-dbw With provided PSReadLine the keyboard input works as expected. Good to know that fix is already available. Thanks for prompt reply! You can close the issue.

**Comment by daxian-dbw** [comment]
Related to https://github.com/PowerShell/PSReadLine/issues/914. The fix is ready in PR https://github.com/PowerShell/PSReadLine/pull/945
