### ISSUE TITLE
Remove the 'DisableZipDownload' setting when the official fix is in Azure DevOps

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#9912]
Downloading zip file is broken in Azure DevOps Windows CIs, and we applied `DisableZipDownload: true` for Windows CIs to work around the issue (#9911).
The temporary fix should be removed once the official fix is in Azure DevOps.

**Comment by ThreeFive-O** [comment]
@daxian-dbw This issue was not auto-closed by the referenced already merged PR. Just wanted to let you know.

**Comment by daxian-dbw** [comment]
Thanks @ThreeFive-O.
Closing via #10260
