### ISSUE TITLE
PS v7 points to PS v6 docs

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#9913]
As per the below Screenshot from PSv7 there is still a pointer to PSv6 Docs
![image](https://user-images.githubusercontent.com/6355225/59620857-d1221500-9125-11e9-908c-375a8b3171a4.png)

this should be changed prior to v7 becoming GA

**Comment by rkeithhill** [comment]
There's a PR that changes this to https://aka.ms/powershell.
