### ISSUE TITLE
Tidy Up Checks for null/AutomationNull

### ISSUE THREAD

**Issue by vexx32** [PowerShell/PowerShell#9922]
# Summary of the thing

There are quite a few places in the codebase that utilise the pattern `value == null || value == AutomationNull.Value`. I've mentioned this briefly before: https://github.com/PowerShell/PowerShell/issues/9561#issuecomment-497814351

# Solution

We need to review the places in the code this pattern occurs and assess:

1. Does it make sense to check for this? For cmdlets (there are a couple) it may not need to be checked. The parameter binder automatically coerces AutomationNull to true null before passing it in.
    - Small caveat being that on occasion there may potentially be AutomationNulls inside some collection types that will not be picked up by the binder and converted, so there may still be some places this check is warranted.

2. Should this _really_ be a manual check every time? We have `LanguagePrimitives.IsNull()` which already performs this check. We should replace most if not all of the existing patterns like this with the single method, rather than doing a manual check. In the unlikely event that this pattern needs to be updated, it'll be significantly less work if the method is actually being utilised properly.

## Code Links

Below is a list of locations in the code where this check is made, so that we can properly assess each occurrence and make sure we don't make a careless fix. Additionally, in certain locations it _may_ make sense to utilise the `IsNullLike()` (name pending review) method instead (from #9794), if we also want to accept DBNull or NullString as "null" in that place in the code.

https://github.com/PowerShell/PowerShell/blob/d67ee7aee3cf4e25fcd750e5f576054b0361a031/src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConvertTo-Html.cs#L692

https://github.com/PowerShell/PowerShell/blob/aba3bd5df1ea9d97790e7b232e50995e9f3d1e37/src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/OutGridView/OutGridViewCommand.cs#L177

https://github.com/PowerShell/PowerShell/blob/42c289fc8eeaeb684cd8f2b5f55d4b1ee869dbfc/src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetMember.cs#L142

https://github.com/PowerShell/PowerShell/blob/aba3bd5df1ea9d97790e7b232e50995e9f3d1e37/src/Microsoft.PowerShell.Commands.Utility/commands/utility/Measure-Object.cs#L481

https://github.com/PowerShell/PowerShell/blob/aba3bd5df1ea9d97790e7b232e50995e9f3d1e37/src/Microsoft.PowerShell.Commands.Utility/commands/utility/OrderObjectBase.cs#L385

https://github.com/PowerShell/PowerShell/blob/d67ee7aee3cf4e25fcd750e5f576054b0361a031/src/Microsoft.PowerShell.Commands.Utility/commands/utility/Select-Object.cs#L822

https://github.com/PowerShell/PowerShell/blob/7e423e7451a4530060422aff1c821c0dc0712372/src/System.Management.Automation/engine/Attributes.cs#L1436

https://github.com/PowerShell/PowerShell/blob/bd6fdae73520931f0d27a29d6290e18761772141/src/System.Management.Automation/engine/CmdletParameterBinderController.cs#L3363

https://github.com/PowerShell/PowerShell/blob/bd6fdae73520931f0d27a29d6290e18761772141/src/System.Management.Automation/FormatAndOutput/common/BaseFormattingCommand.cs#L99

https://github.com/PowerShell/PowerShell/blob/bd6fdae73520931f0d27a29d6290e18761772141/src/System.Management.Automation/FormatAndOutput/common/BaseOutputtingCommand.cs#L49

https://github.com/PowerShell/PowerShell/blob/bd6fdae73520931f0d27a29d6290e18761772141/src/System.Management.Automation/FormatAndOutput/common/BaseOutputtingCommand.cs#L49

**Comment by iSazonov** [comment]
I found 14 such patterns and up to 310 uses of LanguagePrimitives.IsNull()
Looks like simple cleanup.
IsNullLike() we should consider separately.
