### ISSUE TITLE
Get-Service & Set-Service: StartType & StartupType

### ISSUE THREAD

**Issue by NeoBeum** [PowerShell/PowerShell#9923]
EDIT: Pending Review for Pull Request: https://github.com/PowerShell/PowerShell/pull/9940

# Summary of the new feature/enhancement
Get-Service returns Property "StartType"
Set-Service sets property "StartupType" _**and also "StartType"**_

# Proposed technical implementation details (optional)
Create Alias for Set-Service to accept "StartType" as an argument.
This improves flow with property fields. (.. something that is lacking with WMI Objects and MSFT_Disks).

```
Get-Service sshd | Select *

Name                : sshd
RequiredServices    : {}
CanPauseAndContinue : False
CanShutdown         : False
CanStop             : True
DisplayName         : OpenSSH SSH Server
DependentServices   :
MachineName         : .
ServiceName         : sshd
ServicesDependedOn  : {}
ServiceHandle       : SafeServiceHandle
Status              : Running
ServiceType         : Win32OwnProcess
StartType           : Automatic
Site                :
Container           :
```

Invalid Command
```
Set-Service sshd -StartType Manual
Set-Service : A parameter cannot be found that matches parameter name 'StartType'.
```
Valid Command
```
Set-Service sshd -StartupType Manual   
```

**Comment by kvprasoon** [comment]
Which version of PowerShell are you using ?

`Set-Service` already have this parameter.

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-service?view=powershell-6

**Comment by NeoBeum** [comment]
@kvprasoon  read properly

and: The PS that shipped with 18362.1 and also PS 6.2.0

![Nope](https://i.imgur.com/tV8IHDi.jpg)

**Comment by kvprasoon** [comment]
ohk, so its about `StartType` being `StartupType`. got confused by `new feature` tagline.

**Comment by NeoBeum** [comment]
me too.

I'm also covering sabotage where previous feature "startuptype" is replaced by "starttype" and only "starttype"
because I've seen it happen with other things... like install and re-install, re-install if previously installed
:(

**Comment by iSazonov** [comment]
We could resolve the inconsistency with alias.

**Comment by NeoBeum** [comment]
Yeah, I just haven't looked through the repos to find the services functions.
I could probably do that now that I have some spare time.

**Comment by iSazonov** [comment]
@NeoBeum See https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs

**Comment by NeoBeum** [comment]
https://github.com/PowerShell/PowerShell/pull/9939

**Comment by NeoBeum** [comment]
On a side note: is the DISM Module for PS on GitHub?

**Comment by iSazonov** [comment]
@NeoBeum Please open new issue to discuss your suggestion.

**Comment by NeoBeum** [comment]
@iSazonov Ok. I'll work on the rest of the DISM functions that are missing and type a brief so I can create a new issue.

Here is the new pull request for the Get;Set; Service.
https://github.com/PowerShell/PowerShell/pull/9940
