### ISSUE TITLE
Feature Request: $PSModuleRoot

### ISSUE THREAD

**Issue by vexx32** [PowerShell/PowerShell#9927]
# Summary of the new feature/enhancement

Currently there are a couple ways to get a module root folder path:

- One is $PSScriptRoot, but only reliably within the PSM1 itself; modules that separate functions out into other files and folders and import via dot-source can't use $PSScriptRoot directly.
- Another is `$myinvocation.MyCommand.Module.ModuleBase` which suffers from being highly undiscoverable and messy to use. 
- A third possible option is to pull the PSModuleInfo of the desired module with Get-Module and check the ModuleBase property.

If we can add the $PSModuleRoot variable it will offer a very concise and reliable way to get this information without these methods.

# Proposed technical implementation details (optional)

We need to ensure this value is accessible from both the module functions (regardless of if they're split out as separate files which get dot-sourced in the psm1) as well as the PSM1 itself.

Possibly it should also be available in the PSD1 as one of the approved variables there?

**Comment by fMichaleczek** [comment]
I'm agree with this feature request, we can use $PSModuleRoot inside function and if functions are compiled in a one script module script, PSModuleRoot's value is still valid.

As a PowerShell developper, it will give me more flexibility when i begin a new module developpement.

> Possibly it should also be available in the PSD1 as one of the approved variables there?

I don't think $myinvocation.MyCommand.Module value is accessible when you parse the psd1 to load the module. $PSScriptRoot is not event necessary ( ./ is shorter )

**Comment by iSazonov** [comment]
It is not clear why we need this. What is the use cases? What is scenarios we need address?

**Comment by vexx32** [comment]
Mainly, the ability to reference additional files kept in the module folder. There are many such potential uses here: configuration files, additional libraries, script files (in the case of modules which lead their functions from individual files) etc.

**Comment by iSazonov** [comment]
> the ability to reference additional files kept in the module folder

It looks like .PSD1 is not functional enough to do the job. I would look how we can enhance the manifest 
instead of hacks in code.

**Comment by vexx32** [comment]
I don't think that's a complete solution, but it would certainly help.

**Comment by SeeminglyScience** [comment]
> > the ability to reference additional files kept in the module folder
> 
> It looks like .PSD1 is not functional enough to do the job. I would look how we can enhance the manifest
> instead of hacks in code.

While I agree, that doesn't necessarily eliminate the need for something like this.  You probably wouldn't want anything loaded conditionally (or lazily) to be in the manifest for instance.

That said, I'm not sure how often it would be needed, and if that would be often enough to be warranted.  You can get the same effect by adding `$PSModuleRoot = $PSScriptRoot` in the `.psm1`.

**Comment by daniatic** [comment]
this would be great to have. Is this $myinvocation.MyCommand.Module.ModuleBase still the best option?
