### ISSUE TITLE
#requires -version 6.2 throws on 7.0.0-preview.1

### ISSUE THREAD

**Issue by bgelens** [PowerShell/PowerShell#9938]
# Steps to reproduce

Add a #requires version statement with 6.2 to a script and run on 7.0.0-preview.1

```powershell
#requires -version 6.2
```

# Expected behavior

works

# Actual behavior

![image](https://user-images.githubusercontent.com/10071039/59742639-7d6f1300-926e-11e9-831f-0cc4f0b548a2.png)

# Environment data

```none

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.1
PSEdition                      Core
GitCommitId                    7.0.0-preview.1
OS                             Darwin 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kvprasoon** [comment]
It works, but only on elevated shell now :-)

**Comment by kvprasoon** [comment]
Interesting, works only till 6.0, fails for 6.1/2.

**Comment by bgelens** [comment]
After some digging I found this issue [here](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/Utils.cs#L653) I'll see if I can fix it myself
