### ISSUE TITLE
Feature Request - Where-Object speed improvements

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/PowerShell#9941]
# Summary of the new feature/enhancement

As it stands I've stopped using **Where-Object** in performance-related scenarios. I used it a lot when creating different scripts but then I found out it's actually **7-10x slower** than simple foreach loop. 

```powershell
$UsersAll = Get-ADUser -Properties Manager, DisplayName, EmailAddress -Filter '*'
$UsersWithManagers = foreach ($User in $UsersAll) {
    $Manager = ($UsersAll | Where-Object { $User.Manager -eq $_.DistinguishedName })
    [PSCustomobject] @{
        SamAccountName = $User.SamAccountName
        Manager        = $User.Manager
        ManagerDisplay = $Manager.DisplayName
        ManagerEmail   = $Manager.EmailAddress
    }
}
$UsersWithManagers | Format-Table -AutoSize
```
This takes 7 minutes 54 seconds on a domain of size 4412 users. With foreach approach like this:

```powershell
$UsersAll = Get-ADUser -Properties Manager, DisplayName, EmailAddress -Filter '*'
$UsersWithManagers = foreach ($User in $UsersAll) {
    $Manager = foreach ($_ in $UsersAll) {
        if ($User.Manager -eq $_.DistinguishedName) {
            $_
            break
        }
    }
    [PSCustomobject] @{
        SamAccountName = $User.SamAccountName
        Manager        = $User.Manager
        ManagerDisplay = $Manager.DisplayName
        ManagerEmail   = $Manager.EmailAddress
    }
}
$UsersWithManagers | Format-Table -AutoSize
```

It takes just 59 seconds. I ended up using hashtable for that particular problem (https://evotec.xyz/how-i-didnt-know-how-powerful-and-fast-hashtables-are/) but the main idea here is that **Where-Object** is just slow for larger loops. 

It would be really cool to "fix" this in PowerShell 7 so Where-Object can once again be used as GO TO to solution for filtering stuff.

**Comment by iSazonov** [comment]
Related article https://learn-powershell.net/2015/02/20/a-look-at-filtering-performance-in-powershell/

I think there is 2 slow thinks:
- pipeline itself
- where-object internally

I guess we could transform Where-Object to Filter function and get up to 20x improvements.
The code reference
https://github.com/PowerShell/PowerShell/blob/94b6b6f4f7985be7c006c3eb87691992d872142a/src/System.Management.Automation/engine/InternalCommands.cs#L1632-L1643

**Comment by paule96** [comment]
I have also an example for this problem. If you use there Where-Object function of PowerShell it is slow. If you use the Linq function of the object you get twice the perfomance, with more or less the same code..

![image](https://user-images.githubusercontent.com/11291885/90290785-cc1e3a00-de7e-11ea-814a-6fb3737c1f5a.png)

**Comment by vexx32** [comment]
Point of clarity, that `.Where()` method has absolutely nothing to do with Linq; Linq extension methods aren't supported in PS and can't be used without accessing them directly as static methods (i.e., `[System.Linq.Enumerable]::Where()`). The method you're using is specific to PS's method binding, it's documented in the `about_arrays` help topic :)

But yeah, pipeline binding and processing has some overhead, for sure. 🙂
