### ISSUE TITLE
Are resource strings considered part of the supported API?

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#9950]
Here's an example:

```powershell
& { [CmdletBinding()]param()
    $PSCmdlet.GetResourceString('HelpDisplayStrings', 'ProviderIsNotFileSystem')
}

# returns:
# The path {0} does not contain a FileSystem provider. Verify that the specified path contains the FileSystem provider, and then retry the command.
```

In general I wouldn't expect them to be supported, but it would be quite useful and the above method makes me think that might have been the intent.

**Comment by vexx32** [comment]
Wouldn't they be considered part of display/error formatting for the most part?

**Comment by KalleOlaviNiemitalo** [comment]
I suppose PSCmdlet.GetResourceString is intended to be used from compiled cmdlets, in which case it loads the resources from your assembly, rather than the System.Management.Automation assembly.

**Comment by SeeminglyScience** [comment]
Yeah that sounds about right
