### ISSUE TITLE
After remotely logging onto a Ubuntu system, Backspace doesn't work and  path $ appearance is messy

### ISSUE THREAD

**Issue by yiqiaoc11** [PowerShell/PowerShell#9951]
The path appearance is messy after we logged onto a Ubuntu from windows 10's version 1903.

cd ..
];alla_att@tesla: ~vanilla_att@tesla:~$ ls

**Comment by daxian-dbw** [comment]
It's not clear to me what kind of logging in was that, ssh? powershell remoting? else?
@yiqiaoc11 can you please provide more information about the issue, including repro steps and screenshots? Also, please try out the latest 7.0.0-rc.2 version of PowerShell to see if the issue remains.
