### ISSUE TITLE
Seemingly unused code

### ISSUE THREAD

**Issue by RDIL** [PowerShell/PowerShell#9956]
It seems that https://github.com/PowerShell/PowerShell/blob/master/test/docker/networktest/New-DockerTestBuild.ps1
isn't used or called ever.
Is it just me or is it not used?

**Comment by TravisEz13** [comment]
@JamesWTruher 	Do we still need this?

**Comment by iSazonov** [comment]
@TravisEz13 @JamesWTruher Have you a conclusion?

**Comment by TravisEz13** [comment]
@PoshChan Please remind me in 2 days
