### ISSUE TITLE
Export PSReadLine to changes to public project

### ISSUE THREAD

**Issue by andschwa** [PowerShell/PowerShell#996]
This is just so I remember to do this for @lzybkr.

**Comment by andschwa** [comment]
Changes have been exported, closing.

**Comment by lzybkr** [comment]
This shouldn't be closed until PSReadline has a single source of truth.

- [ ] Changes are accepted
- [ ] Package from lzybkr/PSReadline are being consumed here
- [ ] PSReadline sources are removed from this repo

**Comment by andschwa** [comment]
Okay, well I'm at least changing over the assignee then.

**Comment by it-praktyk** [comment]
After this change, the easiest way to pull the Pester module from PowerShell Gallery is to add it to the file `src/Modules/PSGalleryModules.csproj` but as the result,
- Pester module will be pulled every time
- the switch `CI` used in the functions
  - `Start-PSBuild`
  - `Restore-PSModuleToBuild`
will be useless and have to be removed.

Another option - probably a more accurate - is to create the new one csproj file - by analogy to `src/Modules/PSGalleryModules.csproj` (the proposed name PSGalleryModulesCI.csproj) and add an additional parameter to the function [`Copy-PSGalleryModules`](https://github.com/PowerShell/PowerShell/blob/beffdcf94d00b51d9339bb26dbc0e477cd147c92/build.psm1#L2463-L2514) that will contain a path to csproj file ([an equivalent of the current line 2484](https://github.com/PowerShell/PowerShell/blob/beffdcf94d00b51d9339bb26dbc0e477cd147c92/build.psm1#L2484)) and call the function `Copy-PSGalleryModules` twice when $CI will be used.

In both options the functions
- [`Restore-PSPester`](https://github.com/PowerShell/PowerShell/blob/beffdcf94d00b51d9339bb26dbc0e477cd147c92/build.psm1#L663-L673)
- [`Restore-GitModule`](https://github.com/PowerShell/PowerShell/blob/beffdcf94d00b51d9339bb26dbc0e477cd147c92/build.psm1#L2415-L2460)
will be removed.

What do you think? Am I right?

My comment is related to #4618.

**Comment by lzybkr** [comment]
@it-praktyk - `msbuild restore` caches the package locally, so if the cache already has the correct version, nothing is pulled.

Furthermore, at least in AppVeyor (I'm not sure about Travis) - the cache is saved across builds, so we shouldn't see too many pulls from CI.

I think what I did for `PSReadLine` can be done for `Pester` as well and as you point out - that would get rid of some code in `build.psm1` - but I haven't looked as closely as you - maybe we don't need the `-CI` parameter assuming the nuget cache is working as I described.

**Comment by TravisEz13** [comment]
`travis-ci` can cache... I started working on making it but never finished.  The `-CI` parameter is to pull in Pester only during CI builds.  The desire is to not ship pester with PowerShell and have people use `Install-Module` to get pester.

**Comment by iSazonov** [comment]
Can we leave Pester in debug builds? I don't like run `Restore-PSPester` every time.
