### ISSUE TITLE
CI runs code that shouldn't be run

### ISSUE THREAD

**Issue by RDIL** [PowerShell/PowerShell#9962]
`install-ps.yml` is run, but shouldn't be.
Maybe we should move to `/.vsts-ci/templates`?

For example:
https://powershell.visualstudio.com/PowerShell/_build/results?buildId=25996

**Comment by iSazonov** [comment]
@RDIL @TravisEz13 Is the issue actual and should be fixed or we can close?

**Comment by RDIL** [comment]
It looks like this pipeline's logs got deleted, but I haven't contributed here recently so I am not sure.

**Comment by TravisEz13** [comment]
Builds are only retained for a short time.  There is no way to tell now.  I've never seen this happen.
