### ISSUE TITLE
powershell equivalent of KList

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#9972]
What to know whether PS come with the cmdlet that equivalent of Klist.

KList: This is a great command line tool that lists Kerberos tickets as well as being able to purge Kerberos tickets. The nice thing about this tool is that you can selectively purge Kerberos tickets rather than deleting all tickets like the KerbTray utility does.

**Comment by iSazonov** [comment]
You can run klist from PowerShell. Why do you need cmdlrt?
