### ISSUE TITLE
PowerShell Core Enter-PSSession not connecting from MAC to Windows.

### ISSUE THREAD

**Issue by gowrishcode** [PowerShell/PowerShell#9973]
Hello,

Could you please help on this issue. I am unable to PS Remote from Mac to Windows 10.

I have have configured all requirements in Windows. Please help me.

PowerShell Core for MacOS
PowerShell Core installed on the Windows server
The Win32 OpenSSH build installed on the Windows

The SSH client session has ended with error message: The SSH transport process has abruptly terminated causing this remote session to break.
At line:1 char:1
+ Enter-PSSession -HostName 192.168.1.136 -UserName gowrish@outlook.com ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Enter-PSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.PowerShell.Commands.EnterPSSessionCommand
PS /> 

PS Core Version:
PS /Users/gowrish> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.1
PSEdition                      Core
GitCommitId                    6.2.1
OS                             Darwin 18.6.0 Darwin Kernel Version 18.6.0: Thu…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by iSazonov** [comment]
Do you see the issue with latest PowerShell 7.0 build?

**Comment by bloodzer0** [comment]
I have the same problem

macOS powershell

PS /Users/zero> $PSVersionTable


Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
