### ISSUE TITLE
Show-command

### ISSUE THREAD

**Issue by lumirjasny** [PowerShell/PowerShell#9974]
# Steps to reproduce
#Following list directory c:\windows
$PSDefaultParameterValues = @{"Get-ChildItem:Path" = 'c:\windows'}
Get-ChildItem

#Following does not list directory c:\windows
$PSDefaultParameterValues = @{"Get-ChildItem:Path" = 'c:\windows'}
Show-Command Get-ChildItem

# Expected behavior
Show-Command should be pre-filled with path parameter to c:\windows

# Actual behavior
Show-Command parameter path is empty

# Environment data

Name                           Value
----                           -----
PSVersion                      5.1.14393.2879
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2879
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by kvprasoon** [comment]
`Show-Command` is not a valid cmdlet in PowerShell 6+.

And , the above behavior is expected, `Show-Command` is a UI way of using a cmdlet. Nothing will be pre populated. When using default values, it is identified and used after command invocation. Here you can click on Run button and hit enter, you'll get the desired behavior.

**Comment by iSazonov** [comment]
Tracked in https://github.com/PowerShell/GraphicalTools/issues/15
