### ISSUE TITLE
useLocalContext in AddScript not equivalent of "dot sourcing"

### ISSUE THREAD

**Issue by KnicKnic** [PowerShell/PowerShell#9979]
I am trying to progammatically "dot source" a script file (through c#). 
* According to https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_scopes?view=powershell-6#using-dot-source-notation-with-scope 
    * "dot sourcing" is equivalent to running the script in the local context. 
* https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.powershell.addscript?view=pscore-6.2.0#System_Management_Automation_PowerShell_AddScript_System_String_System_Boolean_ 
    * you can run the script in the local context by using AddScript with true for useLocalScope. 

However different results are produced, as it does not appear the script is executed in the local scope through **AddScript** function.

Would love if a workaround exists.

# Steps to reproduce
## test.ps1
```powershell

write-host $localScope
$localScope = "local"

write-host $script:scriptScope
$script:scriptScope = "script"

write-host $global:globalScope
$global:globalScope = "global"
```
## failing steps
```powershell
$psCommand = [System.Management.Automation.PowerShell]::Create([System.Management.Automation.RunspaceMode]::CurrentRunspace)
$null = $psCommand.AddScript(".\test.ps1", $true)
$psCommand.Invoke()
$psCommand = [System.Management.Automation.PowerShell]::Create([System.Management.Automation.RunspaceMode]::CurrentRunspace)
$null = $psCommand.AddScript(".\test.ps1", $true)
$psCommand.Invoke()
```

# Expected behavior
** Note: purposefully put in blank lines **
```none



local
script
global
```
## Above is what is output when "dot source"
```powershell
. .\test.ps1
. .\test.ps1
```
# Actual behavior

```none





global
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.1
PSEdition                      Core
GitCommitId                    6.2.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by bpayette** [comment]
@KnicKnic If `UseLocalScope` is set to true, the script will be run in a _new local scope_. If it's false then it will run in the global scope. So it works the opposite way you expect unfortunately. Also, `AddScript` is used to run a piece of PowerShell code in-line. If you want to run a script file (script command), you should use `AddCommand()` passing in the name of the file. Something like:
```powershell
 [powerShell]::Create("CurrentRunspace").AddCommand("./doit.ps1", $false).Invoke()
```
should work.

**Comment by KnicKnic** [comment]
@bpayette thank you.

I was confused by thinking false would be the default for the functions without the option. Thanks for clearing that up.

As for Add-Script, I now realize it can execute statements I would type into the shell where as add-command needs an actual command.
```powershell
[powerShell]::Create("CurrentRunspace").AddScript("$some_variable = `"value`"", $false).Invoke()
[powerShell]::Create("CurrentRunspace").AddScript("write-host $some_variable", $false).Invoke()
```
What are the benefits of using AddCommand I assume it invokes less parsing?
