### ISSUE TITLE
Update-Help cmdlet -> 404

### ISSUE THREAD

**Issue by jmwielandt** [PowerShell/PowerShell#9981]
Hi, 

```
PS C:\Users\Jose\Desktop> update-help
update-help : Failed to update Help for the module(s) 'Defender, HgsClient, HgsDiagnostics, UEV, Whea, WindowsDeveloperLicense' with UI culture(s) {es-ES} : A Help URI cannot contain more than 10 redirections. Specify a valid Help URI.
At line:1 char:1
+ update-help
+ ~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
+ FullyQualifiedErrorId : TooManyRedirections,Microsoft.PowerShell.Commands.UpdateHelpCommand

update-help : Failed to update Help for the module(s) 'WindowsUpdateProvider' with UI culture(s) {es-ES} : One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
At line:1 char:1
+ update-help
+ ~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
+ FullyQualifiedErrorId : UnknownErrorId,Microsoft.PowerShell.Commands.UpdateHelpCommand
```

The same on powershell 5.1 (but saying st about `HelpInfoUri`).

But ```Update-Help -Module Microsoft.PowerShell*``` works, or at least it didn't throw any error.
 <hr />

If I try: ```Update-Help -UICulture en-US```, exactly the same.

Are your servers on?
Because I'm writing this from the same computer where I have the issue. Isn't my internet connection.

A few weeks ago it works, in both powershells.
Thanks~

**Comment by deanmsands3** [comment]
PwSh 7, Win10x64 1903
I got the same thing (sans HostGuardian).
```
PS C:\Users\deanm> Update-Help
Update-Help : Failed to update Help for the module(s) 'Defender, UEV, Whea, WindowsDeveloperLicense' with UI culture(s) {en-US} : A Help URI cannot contain more than 10 redirections. Specify a valid Help URI.
At line:1 char:1
+ Update-Help
+ ~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
+ FullyQualifiedErrorId : TooManyRedirections,Microsoft.PowerShell.Commands.UpdateHelpCommand

Update-Help : Failed to update Help for the module(s) 'WindowsUpdateProvider' with UI culture(s) {en-US} : One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
At line:1 char:1
+ Update-Help
+ ~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
+ FullyQualifiedErrorId : UnknownErrorId,Microsoft.PowerShell.Commands.UpdateHelpCommand

```

**Comment by darthwalsh** [comment]
I see it as well. Looks like a content problem in MicrosoftDocs/windows-powershell-docs#139 and a few other FWLinks

**Comment by awsumbill** [comment]
Hey, I don't know if this is helpful or not, but `Update-Help` worked on Ubuntu 18.04.03 LTS on WSL

**Comment by darthwalsh** [comment]
@iSazonov is the issue fixed? A few months ago the Windows PowerShell was still having issues, and I don't see any fixes linked.

**Comment by iSazonov** [comment]
@darthwalsh It is not a problem with Update-Help code. It is a content issue. You can ask in PowerShell-Doc repo when it will be available.

**Comment by tomohulk** [comment]
im running into this issue when storing the cab file in the GitHub repo of my projects.  To me that seems like an appropriate place to keep the files.  why is there a 10 hop limit?

**Comment by peterennis** [comment]
Just ran into this also:

```
 Update-Help
Update-Help : Failed to update Help for the module(s) 'Defender, HgsDiagnostics, WindowsDeveloperLicense' with UI culture(s) {en-US} : A Help URI cannot contain more than 10 redirections. Specify a valid Help URI.
At line:1 char:1
+ Update-Help
+ ~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
+ FullyQualifiedErrorId : TooManyRedirections,Microsoft.PowerShell.Commands.UpdateHelpCommand

Update-Help : Failed to update Help for the module(s) 'WindowsUpdateProvider' with UI culture(s) {en-US} : One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
At line:1 char:1
+ Update-Help
+ ~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
+ FullyQualifiedErrorId : UnknownErrorId,Microsoft.PowerShell.Commands.UpdateHelpCommand
```

**Comment by glenlance** [comment]
we all need some response instead of a flash cursor :
**Update-Help -Verbose -Force -ErrorAction SilentlyContinue -UICulture en-US**

**Comment by jeffpatton1971** [comment]
Team,

For powershell devs working in github, keeping code in GitHub would make sense, but there appear to be weird restrictions on naming and re-directions, can someone actually clarify in stone what we should placing in our HelpInfoUri fields, as it appears a container such as https://github.com/project/cabs isn't good enough as that's basically what I'm doing, and i've received the too many hops message as well as your server isnt' available message.

> im running into this issue when storing the cab file in the GitHub repo of my projects. To me that seems like an appropriate place to keep the files. why is there a 10 hop limit?
> 
> ```
> Update-Help : Failed to update Help for the module(s) 'WinSCP' with UI culture(s) {en-US} : A Help URI cannot contain more than 10 redirections. Specify a valid Help URI.
> ```
> 
> ```
> Name             : ConsoleHost
> Version          : 6.2.3
> InstanceId       : ff9dca02-0d82-4543-91fd-a1b6ddce4021
> UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
> CurrentCulture   : en-US
> CurrentUICulture : en-US
> PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
> DebuggerEnabled  : True
> IsRunspacePushed : False
> Runspace         : System.Management.Automation.Runspaces.LocalRunspace
> ```

**Comment by Jaykul** [comment]
@tomohulk @jeffpatton1971 you really need to open a new bug if you want to talk about the hop limit ...

But for what it's worth, the link needs to lead to an actual .cab file (see [Supporting Updateable Help](https://docs.microsoft.com/en-us/powershell/scripting/developer/help/supporting-updatable-help). You also need to use a [permanent link](https://docs.github.com/en/github/managing-files-in-a-repository/getting-permanent-links-to-files), which would means linking to a specific branch.

It might be better to set up [github pages](https://pages.github.com/) to host the cab on....

**Comment by jeffpatton1971** [comment]
@Jaykul lol fair..but FWIW I've gotten my issue sorted, using github to store the files I needed the rawgithub.com host and to have the trailing slash on the URL, as well as make sure that the version number was a proper system.version value.

**Comment by ThomasNieto** [comment]
@jeffpatton1971 do you have an example module/repo where you have that working?

**Comment by jeffpatton1971** [comment]
hey @ThomasNieto I sure do here's the link..

https://github.com/SchemaModule/PowerShell
