### ISSUE TITLE
Intellisense fails to resolve Dynamic parameters cmdlets when -Path or -LiteralPath is a quoted path like "c:\"

### ISSUE THREAD

**Issue by ViperTG** [PowerShell/PowerShell#9983]
When trying to tab through the parameters of Get-ChildItem it does not suggest most of the switches and also skips the Attributes parameter if the Path parameter contains the character `:` which it pretty common for paths.

It only occurs when the `:` is written as a string in the command line, so using a variable that has the path with the `:` in it works fine, also any path written without `:` like `\.`

If you type the fist letter of the parameter then is suggests it correctly, like `-D[tab]` will complete to `-Directory` as expected, but it should still suggest them when tabbing through the parameters.

This has negative effects in editors like VSCode also since it is PowerShell that is reporting the completion data to the editor i believe.

I see this error on all version of PowerShell I have available, 5.1, 6.21 and 7.0.0 Preview 1

- When Path contains ":"
![Get-ChildItem-bug1](https://user-images.githubusercontent.com/26866146/59974758-22138c80-95b0-11e9-86cd-efe43b2eb3b3.png)
- When Path does not contain ":"
![Get-ChildItem-bug2](https://user-images.githubusercontent.com/26866146/59974760-263faa00-95b0-11e9-8ca4-730ad0ab0f87.png)

Parameters that it fails to suggest:
- Attributes
- FollowSymlink
- Directory
- File
- Hidden
- ReadOnly
- System

# Steps to reproduce

```powershell
Get-ChildItem -Path "c:\" -[tab][tab][tab][tab]...
```

# Expected behavior

```none
Get-ChildItem -Path "c:\" -Directory
```

# Actual behavior

```none
Get-ChildItem -Path "c:\" -Depth
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.1
PSEdition                      Core
GitCommitId                    6.2.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.1
PSEdition                      Core
GitCommitId                    7.0.0-preview.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by ViperTG** [comment]
I did some digging in the source and stepped through it with a debugger and I think I know what is happening.

It seems to be an issue with the path parameter value being quoted.
When the trying to autocomplete the parameters the GetDynamicParameters of GetChildrendCommand is being called, the path that is passed to that include the quotations and using double quotes also extra escape chars.

So path becomes `\"c:\\\"` or if single quoted it gets passed `'c:\'`

During resolving of the path the path is determined to be DRIVE-QUALIFIED which is correct but then in the call to GetDriveRootRelativePathFromPSPath and in then IsAbsolutePath in `LocationGlobber.cs` that is supposed to return the driveName is looking for the : in the string and  then end up returning the driveName like this

`driveName = path.Substring(0, index);`

Problem with that is the string still has quotes before the driveletter, resulting in the driveName being returned as `'c` or even `\"c`

This then causes the lookup of the drive information to throw an `System.Management.Automation.DriveNotFoundException`exception, this causes the dynamic parameters function to return null and that is why the dynamic parameters is not getting shown when the path is quoted and contains a : in the path

**Comment by ViperTG** [comment]
Also `-LiteralPath` parameter shows same behavior.

**Comment by ViperTG** [comment]
Issue still persists in 6.2.2 and 7.0 preview 2

````
Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
````

````
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.2
PSEdition                      Core
GitCommitId                    7.0.0-preview.2
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
````

**Comment by ViperTG** [comment]
From more testing this affects all CmdLets that have -Path or -LiteralPath and have dynamic parameters also.

So this affects resolving any of the dynamic parameters in all these cmdlets
```none
CommandType Name          Version Source                          DynamicParameters
----------- ----          ------- ------                          -----------------
     Cmdlet Add-Content   7.0.0.0 Microsoft.PowerShell.Management NoNewline,Encoding,AsByteStream,Stream
     Cmdlet Clear-Content 7.0.0.0 Microsoft.PowerShell.Management Stream
     Cmdlet Copy-Item     7.0.0.0 Microsoft.PowerShell.Management FromSession,ToSession
     Cmdlet Get-ChildItem 7.0.0.0 Microsoft.PowerShell.Management Attributes,FollowSymlink,Directory,File,Hidden,ReadOnly,System
     Cmdlet Get-Content   7.0.0.0 Microsoft.PowerShell.Management Delimiter,Wait,Raw,Encoding,AsByteStream,Stream
     Cmdlet Get-Item      7.0.0.0 Microsoft.PowerShell.Management Stream
     Cmdlet Remove-Item   7.0.0.0 Microsoft.PowerShell.Management Stream
     Cmdlet Set-Content   7.0.0.0 Microsoft.PowerShell.Management NoNewline,Encoding,AsByteStream,Stream
     Cmdlet Test-Path     7.0.0.0 Microsoft.PowerShell.Management OlderThan,NewerThan
```

I have tested all these and weirdly `Copy-Item` is not affected for it's dynamic parameters, bu all the rest shows this problem of failing to show their dynamic parameters.

What happens is not the : but rather the path being quoted, to `c:\`works but `"c:\"` fails. When the path is quoted then LocationGlobber is passed a escaped string or something like `\"c:\\\"` and then it fails to parse that to a drive and throws a `System.Management.Automation.DriveNotFoundException` and then the dynamic parameter parsing stops. 

Note this is only happening in the Intelllisense and the execution is working fine.

**Comment by ViperTG** [comment]
Still present in 7.0.0-preview.6

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.6
PSEdition                      Core
GitCommitId                    7.0.0-preview.6
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by ViperTG** [comment]
Still present in 7.0.1 and 7.1.0 preview-2

```
Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```
Name                           Value
----                           -----
PSVersion                      7.1.0-preview.2
PSEdition                      Core
GitCommitId                    7.1.0-preview.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by theJasonHelmick** [comment]
I can confirm that this behavior still exists in PowerShell 7.2.2 as described above. Thank you @ViperTG for the investigation.  I will discuss with the working group as we investigate on our side.
