### ISSUE TITLE
Support Question: How to change PowerShell icon ?

### ISSUE THREAD

**Issue by lakshit1** [PowerShell/PowerShell#9984]
# Support Question

## Official support

[PowerShell Support Lifecycle](https://aka.ms/pslifecycle)

## Community Resources

[Slack][powershell-slack] and [Discord][powershell-discord] Community Chat - Interactive chat with other PowerShell enthusiasts. Both Slack and Discord are bridged via a bot and can seamlessly talk to each other.
[PowerShell.org Forum](https://powershell.org/forums/) - Search or post new general PowerShell usage questions

[powershell-slack]: https://join.slack.com/t/powershell/shared_invite/enQtMzA3MDcxNTM5MTkxLTBmMWIyNzhkYzVjNGRiOTgxZmFlN2E0ZmVmOWU5NDczNTY2NDFhZjFlZTM1MTZiMWIzZDcwMGYzNjQ3YTRkNWM
[powershell-discord]: https://discordapp.com/invite/AtzXnJM

Please tell me How to change PowerShell icon

**Comment by dads07a** [comment]
Do you mean the shortcut? If so you would do it as per [here](https://www.digitalcitizen.life/how-change-icon-shortcut).
