### ISSUE TITLE
Cannot modify lnk of shell properties

### ISSUE THREAD

**Issue by Xarkam** [PowerShell/PowerShell#9985]
I can't modify powershell 6 properties (font, font size, ect). 
By trying it all, I get this error :
![image](https://user-images.githubusercontent.com/331816/59979688-17c2b400-95eb-11e9-9358-44e6d95f8d5a.png)
So, the message inform me the shortcut doesn't exist. But, I'm on french windows and apparently, it look into `start menu` folder. But on french windows it's `Menu Demarrer`. 
![image](https://user-images.githubusercontent.com/331816/59979747-e8607700-95eb-11e9-9fdc-85db9755a813.png)

How to correct this ?
Thanks.
# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.1
PSEdition                      Core
GitCommitId                    6.2.1
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
You should have permissions to do this. Try set permissions or modify properties from elevated session.

**Comment by vexx32** [comment]
This looks more like a localization issue @iSazonov  -- note the path it's _expecting_ to find the shortcut is set as the English-language path, but as the OS language is in French it's at a different location.

Not sure if that makes this an issue with our MSI installer and how it's handling shortcuts, or if it's a Windows OS issue. @SteveL-MSFT, would that be on our end here or something for the OS team to check out?

**Comment by Xarkam** [comment]
Thank you for taking the time to read my report @vexx32 .
This seems a problem of internationalisation with the OS.

Now the workaround: I copied the shortcut to modify it. I then recopied it to the source folder.

@iSazonov if you are not able to read an issue correctly, let someone do it for you.
I hate to have that kind of response that says you did not take the time to understand the problem.

**Comment by iSazonov** [comment]
@Xarkam I tried to reproduce before reply and I saw only one problem with permissions (UAC). Could you please clarify that the shortcut works (you can run PowerShell)? If the shortcut works it is not localization issue.

**Comment by Xarkam** [comment]
@iSazonov, yes I can run powershell core. With or not privilege elevation

Before writing my report, I did some analysis. 

- Permissions are the same as other folders and shortcuts.
- I also verified that changing the shortcut with elevations of file explorer privileges did not work.
- I also verified that a powershell started with a privilege elevation did not work.
- I also verified that cannot modify directly from powershell properties (with and no with privilege elevation)
- 

The error is still the same, he says he does not find the shortcut to edit.

I am convinced that it is a problem of localization since the shortcut really exist but that the name of the folder starmenu does not exist in a French windows.

**Comment by iSazonov** [comment]
@Xarkam If this were a localization error, you would not be able to start the program using this shortcut but you can do it.
Look at the rights to the shortcut. Only administrators have access to modify.
![image](https://user-images.githubusercontent.com/22290914/60173148-99068a80-9827-11e9-98db-5892e28114bf.png)

Usually we don't change properties on shortcut, we run an application by the shortcut and then change properties in the application window (Alt-Space -> Properties). In the case Windows saves the config in HKCU registry where user has permissions to write.

**Comment by Xarkam** [comment]
@iSazonov I may express myself badly.

I formulate differently: using alt + space -> properties, I also have the error. That I'm running powershell core in normal mode or with elevation of privilege.

As the error message tells me that it does not find the shortcut file in a specific location, I decided to directly edit the shortcut.

Can you explain to me why even with elevation of privilege, I can not change it. I do not have any problems like this with the shortcuts of other apps. It's also something I checked before opening an issue.

**Comment by iSazonov** [comment]
@Xarkam I tried on localized Windows 10 1809 version. I can not change the shortcut properties as regular user - shortcut not found - that is expected as I haven't permission. If I run pwsh.exe and in the windows open Properties from top left corner I can change font and other properties. So  localized version is not a cause of your problem.
Perhaps you have a protection software installed (like antivirus)?
Also I see on your screenshot special permission for an account (first two top lines) - can you check that this does not block your access?

**Comment by Xarkam** [comment]
Finally, we move forward.

I managed not to get the error message by pressing windows + r and running pwsh.exe

If I go through the start menu, I get the error message.
