### ISSUE TITLE
Flat view of nested properties

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#9986]
Perhaps an enhancement to `Format-List` to get a flat list of nested properties.  See https://github.com/soheilpro/catj as an example for json, but we should work with any format.

**Comment by vexx32** [comment]
This would require some method of checking for recursive entries. 

If we implement such a thing, the solution should be generalized, so that serializers can work with it as well.

**Comment by SteveL-MSFT** [comment]
@vexx32 if we had code to check for recursion, we can also resolve the `-Depth` parameter issue for json :)

As for JSON/CliXml/XML/etc... just use `ConvertFrom-* | Format-List -Flat` to leveraget this
