### ISSUE TITLE
Powershell environment variables not returned

### ISSUE THREAD

**Issue by Jonathan-7** [PowerShell/PowerShell#9993]
# Steps to reproduce

```
PS C:\Users\username> $env:TEST='test'

```

# Expected behavior

``` 
PS C:\Users\username> $TEST
PS C:\Users\username> test

```

# Actual behavior

```> $TEST
PS C:\Users\username> <blank>

```

# Environment data

```$PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.1
PSEdition                      Core
GitCommitId                    6.2.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
Environment variables are not displayed although they are set:
I have also been having issues with other apps and scripts executed from powershell not working properly due to this
PS C:\Users\username> $env:TEST='test'
PS C:\Users\username> $TEST
PS C:\Users\username> echo "$TEST"

PS C:\Users\username> Get-ChildItem Env:
TEST                           test

**Comment by vexx32** [comment]
The variable names `$env:TEST` and `$TEST` are two different variables. The latter is a regular PowerShell variable. The former is a process-scope environment variable. They target completely different things.

`$env:` is not a variable scope like `$script:` or `$global:`; it refers to a PSDrive which targets the Environment variable provider. Similarly, a variable named `$c:test.txt` would target the file contents of such a file on the C filesystem drive.

**Comment by Jonathan-7** [comment]
@vexx32 what is the best way to set an environment variable and print it out? I've been having issues with PS missing info with different CLI tools and had the feeling it was related to this.

**Comment by vexx32** [comment]
Just the same way you set it! :blush: 

```powershell
$env:MyVar = 'TEST'
$env:MyVar # returns the string TEST
```

**Comment by Jonathan-7** [comment]
@vexx32 this is working so it's not the root cause for the problem I was having, thanks

**Comment by kilasuit** [comment]
@Jonathan-7 You are best using this if on Windows
```PowerShell
[Environment]::SetEnvironmentVariable('VariableName', 'VaribaleValue', 'Machine')
```
As per https://docs.microsoft.com/en-us/dotnet/api/system.environment.setenvironmentvariable?view=netframework-4.8#System_Environment_SetEnvironmentVariable_System_String_System_String_System_EnvironmentVariableTarget_ there isn't the Machine/User value avail on unix versions of dotnet so this will only work in current process it seems

**Comment by vexx32** [comment]
Yep,wife you need to set persistent environment variables definitely do that - but probably go for setting user variable rather than machine ones unless it really needs to be machine-wide :)
