### ISSUE TITLE
Add performance tests to track the perf improvement/regression in long term

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#9996]
PowerShell needs performance tests to track the perf improvement and regression in long term.
The perf tests will roughly fall in two categories:
- Individual cmdlets, such as those work closely with `PSObject`: `ConvertFrom/To-Csv`, `ConvertFrom/To-Json`; the `*-Object` cmdlets; the `Select-String` and etc.
- scenarios that exercise particular components of the engine, such as the parameter binder (pipeline binding especially), compiler/binder/interpreter, etc.

**Comment by iSazonov** [comment]
.Net Core team moved all benchmark tests in separate repo. We need to consider the experience.

**Comment by LinuxOnTheDesktop** [comment]
> .Net Core team moved all benchmark tests in separate repo. We need to consider the experience.

Excuse me, but to _which_ repository? Also: 'We need to consider the experience' - eh?
